gitpod-io/gitpod

components/ide/jetbrains/gateway-plugin/build.gradle.kts, components/ide/jetbrains/gateway-plugin/gradle.properties
Update platform version from 'gateway-plugin' to the [nightly](https://www.jetbrains.com/intellij-repository/snapshots) (_com.jetbrains.gateway: 222-NIGHTLY-CUSTOM-SNAPSHOT_), to make use of the latest API.
Also, update the minimum version of the plugin to 222.3048.1, so it can only be installed on new gateway versions (2022.2+) downloaded from https://www.jetbrains.com/remote-development/gateway/ after June 16 2022.
Gateway 2022.1 (221) will is not going to receive new features.
Follow-up for #10505
- Download JetBrains Gateway from https://www.jetbrains.com/remote-development/gateway/ - The download button of this page actually downloads EAP Version. (At the moment of writing, the latest EAP version is 222.3048.1)
- Download the gateway-plugin version built on this PR from …
=> Update platform version from 'gateway-plugin' to target JetBrains Gateway v2022.2-Nightly

.werft/vm/manifests.ts
Currently, the Harvester VM uses `scsi`, we change to `virtio` to gain the performance.
Check the VM image supports the `virtio` by
```shell
$ lsmod | grep virtio_blk
```
Related slack discussion https://gitpod.slack.com/archives/C01KGM9EBD4/p1655444499062949
Fixes #
Check the VM is bootable.
```release-note
None
```
None
=> Change disk bus from scsi to virtio to gain performance

.werft/jobs/build/deploy-to-preview-environment.ts, .werft/jobs/build/installer/post-process.sh, .werft/vm/manifests.ts, .werft/vm/manifests/rook-ceph/cluster-test.yaml, .werft/vm/manifests/rook-ceph/common.yaml, .werft/vm/manifests/rook-ceph/crds.yaml, .werft/vm/manifests/rook-ceph/operator.yaml, .werft/vm/manifests/rook-ceph/snapshotclass.yaml, .werft/vm/manifests/rook-ceph/storageclass-test.yaml, .werft/vm/vm.ts
Install Rook/Ceph v1.9.5 in the preview environment which supports CSI volume snapshot.
We overwrite some default values:
- Disable the Ceph FS https://github.com/gitpod-io/gitpod/blob/d19c9b549a5b2e777c931f3aa05f7180eeb23390/.werft/vm/manifests/rook-ceph/operator.yaml#L30
- StorageClass 
- Disable the volume expansion https://github.com/gitpod-io/gitpod/blob/d19c9b549a5b2e777c931f3aa05f7180eeb23390/.werft/vm/manifests/rook-ceph/storageclass-test.yaml#L55
- Change volumeBindingMode from Immediate to WaitForFirstConsumer https://github.com/gitpod-io/gitpod/blob/d19c9b549a5b2e777c931f3aa05f7180eeb23390/.werft/vm/manifests/rook-ceph/storageclass-test.yaml#L57
Fixes #10201
1. Open the URL https://jenting-in5edb98e0f2.preview.gitpod-dev.com/workspaces
2. Enable the feature flag …
=> Install Rook/Ceph which supports CSI volume snapshot in preview environment

components/ws-daemon/pkg/quota/size.go, components/ws-daemon/pkg/quota/size_test.go
I found this while browsing the repo
https://github.com/gitpod-io/gitpod/blob/d114f037a1c34df5206bb93fc9fe48481f28bfd7/components/ws-daemon/pkg/quota/size_test.go#L26-L27
`-42m` works because the regex correctly matched on the `42m` part, see https://regexr.com/6o0va
so does this
``` go
{"-42m", 42 * quota.Megabyte, nil},
{"ab-42mcd", 42 * quota.Megabyte, nil},
```
Quick fix is to constrain starting and ending characters, i.e.
``` go
^(\d+)(k|m|g|t)?$
```
This test now succeeds 
https://github.com/gitpod-io/gitpod/blob/d114f037a1c34df5206bb93fc9fe48481f28bfd7/components/ws-daemon/pkg/quota/size_test.go#L15
```release-note
Fixed quota size regex allowing false positives
```
=> [ws-daemon] Fix quota size regex's false positives

.werft/jobs/build/build-and-publish.ts, .werft/jobs/build/deploy-to-preview-environment.ts
NOTE: I have added the hold label because the build fails are we seem to have a problems with VMs right now.
This PR instruments our build job to include annotations on the root span that we can use as part of our ["Preview environments should start successfully" SLI](https://www.notion.so/gitpod/Preview-Environment-Service-Level-Indicators-SLIs-55b649ad17774f279c142af55ad2fec7#f483f73aa4974ad3b8b6825fa2f251fa).
These annotations are used to created a derived column in Honeycomb that represents our SLI. The structure of the `IF(condition, then-value, else-value)` - see [here](https://docs.honeycomb.io/working-with-your-data/use-advanced-operators/derived-columns/reference/#if) - additionally for SLIs in Honeycomb `true` means the event should count as a success, `false` means it should …
=> Introduce SLI for preview environment start

.werft/jobs/build/helm/values.payment.yaml, .werft/jobs/build/installer/installer.ts, .werft/jobs/build/payment/stripe-configmap.yaml, components/server/ee/src/user/stripe-service.ts, components/server/src/config.ts, install/installer/pkg/components/server/configmap.go, install/installer/pkg/components/server/constants.go, install/installer/pkg/components/server/deployment.go, install/installer/pkg/components/server/types.go, install/installer/pkg/config/v1/experimental/experimental.go
Make Stripe usage-based product price IDs configurable.
Companion ops PR: https://github.com/gitpod-io/ops/pull/2819 (internal)
Fixes https://github.com/gitpod-io/gitpod/issues/10655
1. Trigger a custom Werft build (using the config from this PR)
- E.g. like so: `kubectx dev` then `werft job run github -j .werft/build.yaml -a with-clean-slate-deployment=true`
2. Then, same test flow as in https://github.com/gitpod-io/gitpod/pull/10630
```release-note
NONE
```
=> [server] Make Stripe usage-based product price IDs configurable

operations/observability/mixins/platform/dashboards/preview-environments/overview.json
This adds a simple text panel to our [Preview Environments dashboard](https://grafana.gitpod.io/d/preview-environments/preview-environments?orgId=1) which links to our new SLO for Preview Starts in Honeycomb as well as a simple query and the description of the SLO (the RFC).
Fixes https://github.com/gitpod-io/ops/issues/2768
In the Grafana for my preview environment I manually imported the dashboard by copy-pasting the JSON in the repo. It loaded it just fine, see below:
I was expecting it to create the Preview Environment dashboard automatically, but did didn't. Should it have @ArthurSens?
```release-note
NONE
```
N/A
=> Add text panel with link to Preview Start SLO

.github/pull_request_template.md, .werft/build.ts, .werft/jobs/build/job-config.ts, .werft/jobs/build/validate-changes.ts, dev/changelog/pullrequest.go
Preview environments become optional with a toggle switch in the PR template.
The org-wide PR template is at:
https://github.com/gitpod-io/.github/blob/main/.github/pull_request_template.md
But we only care about modifying the template for this repository - therefore I've added it here and made the change.
Fixes https://github.com/gitpod-io/gitpod/issues/9899
Job without `with-preview` set: https://werft.gitpod-dev.com/job/gitpod-custom-aa-opt-in-prevs.1/logs
Job with `with-preview` set: https://werft.gitpod-dev.com/job/gitpod-custom-aa-opt-in-prevs.2/logs
```release-note
NONE
```
=> Opt-in preview environments

components/workspacekit/cmd/rings.go, components/ws-manager/pkg/manager/create.go
When adding support for prebuilds to work with PVC, noticed that pod's lifecycle hook does not execute for prebuilds, because when they are done, they transition into completed state. 
So this PR changes how prestophook.sh is executed and allows prebuilds to execute it as well now.
Related to https://github.com/gitpod-io/gitpod/pull/10689
1. Open preview environment
2. Open workspace. Edit file. Close workspace. Notice pending changes in workspace dashboard.
3. Now enable persistent_volume_claim feature from admin dashboard for your user.
4. Do step 2 again.
```release-note
none
```
=> call prestophook.sh from ring1 directly

components/usage/go.mod, components/usage/pkg/db/dbtest/workspace.go, components/usage/pkg/db/workspace.go, components/usage/pkg/db/workspace_test.go
Ensures that we do not include more than 2^16 placeholders in a `WHERE field IN (values)` prepared query.
https://bugs.mysql.com/bug.php?id=101630
Fixes #10642
Unit tests
```release-note
NONE
```
NONE
=> [usage] Batch lookup Workspaces to fix too many placeholders error

components/usage/pkg/controller/reconciler_test.go, components/usage/pkg/db/dbtest/workspace_instance.go, components/usage/pkg/db/workspace_instance.go, components/usage/pkg/db/workspace_instance_test.go
The underlying query used `creationTime` to validate the record should be included but in https://github.com/gitpod-io/gitpod/issues/10642#issuecomment-1154861661 it was pointed out that should not be the case, and `startedTime` should be used instead.
The rest of the changes are to tests, and streamlining test object creation.
Fixes #10642
Unit tests
```release-note
NONE
```
NONE
=> [usage] Fix querying workspace instances to use startedTime existence to filter

.gitpod.yml, .werft/build.yaml, .werft/debug.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup-jetbrains.yaml, .werft/ide-integration-tests-startup-vscode.yaml, .werft/ide-run-integration-tests.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/run-integration-tests.yaml, .werft/wipe-devstaging.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile
Update env in the dev Dockerfile to use the werft gRPC API
Fixes [#2083](https://github.com/gitpod-io/ops/issues/2083)
NONE
=> update env to use werft grpc

install/installer/pkg/components/usage/configmap.go, install/installer/pkg/components/usage/configmap_test.go, install/installer/pkg/components/usage/deployment.go, install/installer/pkg/components/usage/objects.go, install/installer/pkg/components/usage/objects_test.go, install/installer/pkg/config/v1/experimental/experimental.go
Make the frequency at which the usage component runs configurable via a configmap.
Fixes https://github.com/gitpod-io/gitpod/issues/10720
Part of #9036 
* Open the preview environment.
* Edit the `usage-configmap` (`kubectl edit cm usage-config`) and change the `schedule` to `1m`.
* Kill the usage pod to restart it with the new config (`kubectl delete pod <usage pod>`).
* Tail the logs of the new usage pod, including timestamps (`kubectl logs -f --timestamps=true <usage-pod>`)
* Watch the logs of the usage component and see that it now runs at 1 minute intervals rather than the previous 1 hour.
```release-note
NONE
```
=> [usage] Add configmap for usage component to control run frequency

components/usage/pkg/db/dbtest/workspace_instance.go, components/usage/pkg/db/workspace_instance.go, components/usage/pkg/db/workspace_instance_test.go
Lists Workspace Instances in batches of 100
Fixes #
Unit tests
```release-note
NONE
```
NONE
=> [usage] Batch list workspace instances in range

dev/preview/previewctl/cmd/root.go, dev/preview/previewctl/cmd/ssh_vm.go, dev/preview/previewctl/pkg/preview/preview.go, dev/preview/ssh-vm.sh
Add the command `previewctl ssh`, which will SSH into the related preview's Virtual Machine.
It can also be used to SSH into VM unrelated to the branch, by passing the `--branch` flag
We don't have a issue for this one, but we agreed to work on this in our team's sync
Open a preview from this PR and run:
* `previewctl ssh`
* `previewctl ssh --branch main`
```release-note
NONE
```
=> previewctl: Add SSH command

components/supervisor/cmd/run.go, components/supervisor/pkg/supervisor/supervisor.go
Makes supervisor compatible with run-gp and cleans up some code.
In Gitpod no behaviour should change.
To test this with run-gp:
1. open a workspace on https://github.com/gitpod-io/run-gp
2. run `./hack/update-images.sh cw-run-gp-compat.3`
3. run `./hack/update-assets.sh`
4. run `go run main.go`
```release-note
NONE
```
=> [supervisor] Make compatible with run-gp

.werft/build.ts, .werft/installer-tests.ts, .werft/jobs/build/job-config.ts, .werft/jobs/build/self-hosted-upgrade-tests.ts, .werft/run-sh-upgrade-tests-gke.yaml, install/infra/terraform/k3s/main.tf, install/infra/terraform/tools/external-dns/main.tf, install/infra/terraform/tools/external-dns/variables.tf, install/tests/Makefile, install/tests/main.tf, install/tests/manifests/kots-config.yaml, install/tests/tests.sh
This PR adds a new werft flag to test the upgrade of gitpod self-hosted from one version to the latest. This is intended to be used in a release PR, to see how the upgrade would work from the previous version(we can specify the version) to the latest. The setup uses the `beta` channel of replicated, since this is where the release ends up before going to the stable channel according to our workflow. To run the test you can add the following comment to the PR:
```
/werft run no-preview with-upgrade-tests fromVersion=2022.4.2
```
The above comment will creates a GKE cluster, install `20224.2` version of Gitpod, makes sure it is up and running, upgrades the Gitpod version to latest and confirm it has the basic functioning. This is the first :skateboard: , we will add the integration tests …
=> Add self-hosted upgrade tests

operations/observability/mixins/platform/dashboards/preview-environments/overview.json
Add panels to show all our Preview Environments SLIs
The query for our SLI 2(probe success rate) looks strange, as it shows 200% success rate. Using the same query in grafana explore it shows me 100%, which is the expected behavior. I hope that it is just some Grafana misbehavior, but we can fix it if it still looks strange after the merge
Fixes https://github.com/gitpod-io/ops/issues/2765
Fixes https://github.com/gitpod-io/ops/issues/2767
```release-note
NONE
```
=> Add SLIs to preview-environment dashboard

.werft/build.yaml, .werft/observability/monitoring-satellite.ts
Configure Prometheus in Preview Environments to remote-write metrics to core-dev, but only the ones needed for our SLIs.
Fixes https://github.com/gitpod-io/ops/issues/2764
Fixes https://github.com/gitpod-io/ops/issues/2766
Unfortunately, we're still having some network issues between previews and core-dev, but once that is solved we should be able to query metrics from the core-dev Prometheus with the following query:
```
{environment="preview-environment"}
```
```release-note
NONE
```
=> previews: Remote-write metrics to core-dev

components/usage/pkg/db/workspace_test.go
Sometimes (~15/100 from my repeated runs), the DB cleanup hook post tests would conflict with the data creation and would cause the tests to fail due to the exact missing IDs. Generating new random IDs hasn't failed in my test runs.
Unit tests
```release-note
NONE
```
NONE
=> [usage] Fix flaky test for ListWorkspacesByID

.werft/installer-tests.ts, install/infra/terraform/gke/main.tf, install/infra/terraform/k3s/main.tf, install/tests/Makefile, install/tests/manifests/kots-config-gcp-db.yaml, install/tests/manifests/kots-config-gcp-registry.yaml, install/tests/manifests/kots-config-gcp-storage.yaml
This PR adds the external dependencies test for GCP cloud platform. These dependencies include `cloudsql` as external database, `GCR` as external registry, and `cloud storage` as external storage. These dependencies are randomly selected for each test providing us a overall testing of every combination over a course of days. 
Fixes #
You can run the following command to test one of the available combinations:
```
werft run github -j .werft/gke-installer-tests.yaml
```
```release-note
NONE
```
=> Add tests for external dependencies in GCP

components/gitpod-protocol/src/installation-admin-protocol.ts, components/installation-telemetry/cmd/send.go, components/installation-telemetry/pkg/server/installationAdmin.go, components/server/src/installation-admin/telemetry-data-provider.ts
This pull request adds the Gitpod license type (replicated, gitpod) to installation telemetry.
Fixes #10508.
Installation telemetry should include the `licenseType` field in the dashboard Admin page and the installation telemetry job:
```
❯ kubectl logs installation-telemetry-manual-0001-lwr54 | jq .
{
"level": "info",
"message": "installation-telemetry has successfully sent data - exiting",
"serviceContext": {
"service": "installation-telemetry",
"version": "commit-efde5061d789299a2c5273d38d13376083fb4816"
},
"severity": "INFO",
"telemetry": {
"userId": "822b56b6-6e51-4d74-afbb-900399356a1f",
"event": "Installation telemetry",
"timestamp": "0001-01-01T00:00:00Z",
"properties": {
"licenseType": "replicated",
"totalInstances": 0,
"totalUsers": 1,
"totalWorkspaces": 0,
"version": …
```
=> [installation-telemetry] Add licenseType to sent telemetry

.github/workflows/jetbrains-updates-template.yml
Allow PRs for JetBrains IDEs updates to be created with a Preview Environment.
We need it to test the IDEs.
#10816
Not sure if it can be tested without having some IDE update.
```release-note
NONE
```
None.
=> Allow PRs for JetBrains IDEs updates to be created with a Preview Environment

WORKSPACE.yaml
Updates stable VS Code Web to 1.68.2 with 
- Fix ports tunnel not works https://github.com/gitpod-io/openvscode-server/commit/55e0ef639c53fd38710b45a073cccb756fda264f
Fixes https://github.com/gitpod-io/gitpod/issues/10828
Tested here https://github.com/gitpod-io/openvscode-server/pull/370
You can test again if you want
```release-note
Fix vscode ports tunnel in `Remote Explorer` broken
```
=> [code] build stable image for 1.68.2 with port tunnel broken fix

install/installer/pkg/components/workspace/ide/constants.go
Updates stable VS Code version to 1.68.2.
Relates to https://github.com/gitpod-io/gitpod/issues/10828
Switch to stable in the preview environment and in the about dialog confirm you are running 1.68.2
```release-note
NONE
```
=> [code] make 1.68.2 stable

operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
Workspaces that have been terminating for more than one day will be detected and acted upon as they affect the backup process for other workspaces on the same node.
[grafana](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22VictoriaMetrics%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22sum(time()%20-%20kube_pod_deletion_timestamp%7Bnamespace%3D%5C%22default%5C%22,%20pod%3D~%5C%22%5Ews-.*%5C%22%7D)%20by%20(pod)%20%3E%2024%20*%2060%20*%2060%20%22%7D%5D,%22range%22:%7B%22from%22:%221655276180662%22,%22to%22:%221655845434062%22%7D%7D)
Runbook: https://github.com/gitpod-io/runbooks/pull/355
```release-note
NONE
```
=> observability: Add GitpodWorkspaceTooLongTerminating alert.

components/server/src/auth/rate-limiter.ts
Increase startWorkspace rate limit 1 → 3 starts per user per 10 seconds.
This makes getting stuck in this screen less frequent:
1. Start many parallel workspaces
2. They should come up fast (without getting stuck in `Preparing` for some seconds while priting rate-limit messages in the console)
```release-note
NONE
```
=> [server] Increase startWorkspace rate limit 1 → 3 starts per user per 10 seconds

.werft/jobs/build/payment/stripe-configmap.yaml, components/usage/pkg/stripe/stripe.go, components/usage/pkg/stripe/stripe_test.go
Update credit prices, calculation, and Stripe product IDs.
Fixes #
1. Trigger a custom Werft build (using the config from this PR)
- E.g. like so: `kubectx dev` then `werft job run github -j .werft/build.yaml`
1. Once built, in the preview, create a team called "Gitpod" (or any team name containing the word "Gitpod")
2. Go to Team Settings > Team Billing
3. Wait for the Usage-Based UI to show up
4. Subscribe to Usage-Based Billing by entering a credit card (e.g. 4242 4242 4242 4242, 4/24, 424)
5. Wait for the Stripe subscription to be created
6. Once you can, click on "Manage Billing"
- Your subscription should be linked to a product called `Gitpod Usage (with latest prices)`
7. Start a workspace
8. Wait for one hour (or manually trigger a `usage` report*)
9. Go to the Stripe dashboard > …
=> [Usage-based] Update credit prices, calculation, and Stripe product IDs

install/kots/manifests/kots-preflight.yaml
Changed the node memory preflight check:
1. Changed it so that it errors on 16gb
2. Reworded it to be about per node memory, not per cluster memory
Fixes #10726 
```release-note
NONE
```
=> [Self-Hosted] Changed preflight memory check error amount and reworded

operations/observability/mixins/workspace/rules/components/ws-daemon/alerts.libsonnet
This PR reduces the number of calls to 6 in the last week.
[grafana](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22VictoriaMetrics%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22increase(kube_pod_container_status_restarts_total%7Bcontainer%3D%5C%22ws-daemon%5C%22,%7D%5B10m%5D)%20%3E%200%20%22,%22hide%22:true%7D,%7B%22refId%22:%22B%22,%22expr%22:%22increase(gitpod_ws_manager_workspace_backups_failure_total%7Btype%3D%5C%22REGULAR%5C%22%7D%5B10m%5D)%20!%3D%200%22,%22hide%22:true%7D,%7B%22refId%22:%22C%22,%22expr%22:%22sum(increase(kube_pod_container_status_restarts_total%7Bcontainer%3D%5C%22ws-daemon%5C%22%7D%5B10m%5D))%20%3E%200%20AND%20sum(increase(gitpod_ws_manager_workspace_backups_failure_total%7Btype%3D%5C%22REGULAR%5C%22%7D%5B10m%5D))%20%3E%200%22,%22h …
=> observability: Ring the phone only when a data loss occurs with GitpodWsDaemonCrashLooping

.werft/workspace-run-integration-tests.yaml
Trigger to bootstrap a preview environment in workspace integration test job.
Fixes #
```console
werft run github -j .werft/workspace-run-integration-tests.yaml
```
```release-note
None
```
None
=> Trigger to bootstrap a preview environment in workspace integration test job

.werft/platform-delete-preview-environments-cron.ts
We have may preview envs running without `mysql-0` DB. To ensure they get garbage collected eventually, this PR treats them as *not* active. 
Context: https://gitpod.slack.com/archives/C01KGM9EBD4/p1655991725949059
```release-note
NONE
```
=> Assume that preview envs without `mysql-0` are not active.

components/supervisor/pkg/supervisor/ssh.go
[supervisor] enabled SSH debug log by default, it write to workspace standard log
Fixes #
1. Start a workspace in preview environment
2. connect via ssh
3. use `kubectl logs ws-${instanceId}` see log, it should contain ssh debug log, but in ssh client, it didn't print environment variable
```release-note
NONE
```
=> [supervisor] enabled SSH debug log by default

components/ws-manager/cmd/run.go, components/ws-manager/pkg/manager/monitor.go, components/ws-manager/pkg/manager/volume_snapshot_controller.go
Add volume_snapshot_controller to watch the VolumeSnapshot object, and once the VolumeSnapshot object is ready, notify the Pod in the finalizer loop that the VolumeSnapshot is ready.
This improves the volume snapshot metric `gitpod_ws_manager_volume_snapshot_seconds` more accurately when the workspace stops.
Fixes #10334
1. Enable PVC feature flag
2. Watch the time that the VolumeSnapshot object becomes ready `kubectl get vs -w`
3. Open a workspace, write some data into it, close the workspace
4. Port forward ws-manager 9500 to localhost `kubectl port-forward <ws-manager-pod> 9500:9500`
5. Get the metrics `curl -XGET 'localhost:9500/metrics' | grep gitpod_ws_manager_volume_snapshot_seconds`, and check if the time matches step 2.
```release-note
None
```
None
=> [ws-manager] Watch VolumeSnapshot object and notify to the Pod finalizer loop

install/installer/pkg/components/ws-proxy/deployment.go
After https://github.com/gitpod-io/gitpod/pull/10514/files#diff-b20fcd9b24f3f080dc12476d648794f320434fee1053e2195a18d2ecd38482e2R47-R49,
`ws-proxy` goes through the `proxy` to talk the `ide-proxy`. For `self-signed` instances of
Gitpod this means that `ws-proxy` also needs to trust the self-signed Cert.
For that to happen, This PR starts loading the `customCACert` onto `ws-proxy`
along with the necessary env variables.
Fixes #
```release-note
[installer] Fix workspace URL loading issue with `self-signed`
```
=> [installer] add `customCACert` volume to `ws-proxy`

install/installer/pkg/components/components-webapp/components.go, install/installer/pkg/components/components-workspace/components.go
Blobserve is served through the IDE proxy now
```release-note
NONE
```
/hold
=> [installer] Move blobserve out workspace clusters

components/server/src/user/token-service.ts
Fixes https://github.com/gitpod-io/gitpod/issues/10762
1. Use git with the gitlab.com integration for a while, no issues with tokens should occur.
```release-note
Token renewals should not run concurrently.
```
=> Fix concurrent token renewal issues

components/gitpod-db/src/typeorm/workspace-db-impl.ts
This PR fixes a SQL query bug in the admin dashboard, which causes to  return an empty page instead the list of a user's workspaces. 
Verify that workspaces are shown as expected in the admin panel.
```release-note
Fix a SQL query bug on admin panel.
```
=> [db] fix adminGetWorkspaces/findAllWorkspaceAndInstances

components/gitpod-db/src/typeorm/entity/db-workspace-instance.ts, components/gitpod-db/src/typeorm/migration/1655988518555-WorkspaceInstanceUsageAttributionId.ts, components/gitpod-db/src/workspace-db.spec.db.ts, components/gitpod-protocol/src/workspace-instance.ts, components/server/src/user/user-service.ts, components/server/src/workspace/workspace-starter.ts
Refactor workspace instance `attributedTeamId` to an explicit, not-team-specific `usageAttributionId`.
Fixes https://github.com/gitpod-io/gitpod/issues/10822
1. Should build
2. Workspace instances should always get a `usageAttributionId`
- If the workspace is for a project that's owned by a Team, the attribution ID should look like `team:1234`
- If the workspace is for a user project, or for no project at all, the attribution ID should look like `user:1234`
```release-note
NONE
```
=> Refactor workspace instance `attributedTeamId` to an explicit, not-team-specific `usageAttributionId`

install/installer/pkg/components/server/deployment.go, install/installer/pkg/config/v1/experimental/experimental.go
In https://github.com/gitpod-io/gitpod/pull/10807, we are adding support for configuring configcat through an ENV variable to target various ConfigCat environments.
The SDK Key is **NOT A SECRET**, it is a unique identifier of app just like Google Analytics has a unique identifier.
* Relates to #10807 
Run installer with config:
```
experimental:
webApp:
configcatKey: "config-cat-key-here"
```
Observe it's in the resulting yaml
```release-note
NONE
```
NONE
=> [experiments] Configure ConfigCat SDK through installer

.werft/jobs/build/installer/installer.ts
Configures ConfigCat in preview env with our non-production configcat environment
* Related to https://github.com/gitpod-io/gitpod/pull/10807
Preview starts
```release-note
NONE
```
NONE
=> [experiments] Add configcat key for preview-envs

components/ws-manager-bridge/src/bridge.ts
This PR prepares for fixing a bug with prebuilds being stuck in `queued` indefinitely in rare cases. (4/5 in the chain)
To that end, if mostly refactors the method `controlInstances` in `Bridge`, and adds tracing to it.
Context: https://github.com/gitpod-io/gitpod/issues/9395
Follow-up: #10882 
- start a [workspace on this branch](https://gitpod.io/#https://github.com/gitpod-io/gitpod/pull/10727) and `./dev/preview/install-k3s-kubeconfig.sh`
- start a workspace in the preview env
- enable debug logs for `ws-manager-bridge`: `gpctl debug log ws-manager-bridge`
- check the logs and notice this pattern:
- "Controlling instances..."
- "Controlling running instances..."
- "Done controlling running instances."
- "Done controlling instances."
```release-note
fix prebuilds stuck in `queued` …
```
=> [bridge] Refactor Bridge.controlInstances and add tracing (4/5)

components/dashboard/src/experiments/configcat.ts, components/server/src/experiments.ts
While debugging with @easyCZ why getting feature flag values was sometimes so slow, we found that by default, our experiments client waits for 5 seconds before returning the initial value (see [all options](https://configcat.com/docs/sdk-reference/js/#auto-polling-default)):
Disabling this delay makes getting feature flag values instantaneous. 🪄 ⚡
Fixes https://github.com/gitpod-io/gitpod/issues/10786
1. Create a team called "Gitpod"
2. Go to Team Billing
3. The Usage-Based UI should be instantly visible, even if you reload the page
```release-note
NONE
```
=> Disable 5 second delay before returning feature flag value

components/ws-manager-bridge/src/bridge.ts
1 of 2 PRs that attempt to fix the bug described in #8596 
Explanation: https://github.com/gitpod-io/gitpod/issues/8596#issuecomment-1165542976
Context: #8596
- see that everything works as expected
- check ws-manager-bridge logs and search for "We received an empty "failed" condition overriding an existing one"
```release-note
NONE
```
=> [bridge] Add log.error in case we are about to override a previous "failed" condition

components/gitpod-protocol/go/gitpod-service.go, components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts
Add a new `rawDuration` field to the object returned by `getWorkspaceTimeout`. This represents the workspace timeout as a string in the format `30m`, `60m`, `180m`. The existing `duration` field translates these times into `short` or `extended`.
This is necessary for the new `gp timeout show` command (https://github.com/gitpod-io/gitpod/pull/10782) to present the workspace timeout in a format that makes the most sense to the user.
https://github.com/gitpod-io/gitpod/pull/10782
1. Open the preview environment and start a workspace.
3. In the browser console on the workspaces list run:
```js
await window._gp.gitpodService.server.getWorkspaceTimeout()
```
Observe the new `rawDuration` field in the response object:
```json
{
"duration": "short", 
"durationRaw": "30m"
"canChange": true,
}
``` …
=> [server] Return raw duration from `getWorkspaceTimeout`

components/ws-manager/pkg/manager/monitor.go
It would be great if we could add events to the workspace pod that shows the progress of volume snapshot operations, we could see the event by `kubectl describe pods <workspace-pod-name>`.
That way it will be easier to debug later on if the workspace pod is stuck or misbehaving.
Fixes #10887
1. Create a preview environment and enable the feature flag `persistent_volume_claim`.
2. Launch a workspace and write a large data into it.
```console
dd if=/dev/urandom of=data bs=16M count=256
```
4. Stop the workspace.
5. During the workspace stopping, kubectl describe the workspace pod to see the volume snapshot event.
```console
kubectl describe pod -l component=workspace
```
```release-note
[experimental] Add volume snapshot events to workspace pod event
```
None
=> [ws-manager] Add volume snapshot events to workspace pod event

components/gitpod-cli/cmd/timeout-show.go, components/gitpod-protocol/go/gitpod-service.go
Add a `gp timeout show` command to the `gp` CLI to go along with the recently added `gp timeout extend` command (see https://github.com/gitpod-io/gitpod/pull/10619).
1. Create a workspace in preview environment
2. Run `gp timeout show`
3. Output should be (value depends on user's plan):
```
60m
```
4. Extend the workspace timeout with `gp timeout extend`. 
5. Rerun `gp timeout show`. Output should be:
```
180m
```
6. Open another workspace, and extend its timeout `gp timeout extend`
7. Back to first one, `gp timeout show` should back to original one
```release-note
Add command `gp timeout show` to show the timeout of current workspace
```
We'll need to add something to https://github.com/gitpod-io/website/pull/2218 either before or after it's merged.
=> Add `gp timeout show` command

components/supervisor/pkg/supervisor/supervisor.go
```release-note
NONE
```
Internal thread: https://gitpod.slack.com/archives/C02F19UUW6S/p1656015438957279
logs: https://cloudlogging.app.goo.gl/JfCNHN3Boof8pgUe6
=> [supervisor] Remove noisy log and refactor error handling

components/content-service/pkg/git/git.go, components/content-service/pkg/initializer/git.go, components/content-service/pkg/initializer/initializer.go, components/content-service/pkg/initializer/snapshot.go, components/content-service/pkg/layer/provider.go, components/content-service/pkg/logs/logs.go, components/server/ee/src/prebuilds/prebuild-manager.ts, components/server/ee/src/workspace/workspace-starter.ts, components/server/src/workspace/workspace-starter.ts, components/ws-daemon/pkg/content/service.go, components/ws-manager/pkg/manager/monitor.go
This PR adds support for PVC to prebuilds.
You can now enable PVC in your project settings, and all prebuilds going forward will use PVC and backup prebuild result into Volume Snapshot. When you open workspace from such prebuild, it will automatically opt in into using PVC feature.
Prebuilds using PVC can only be opened using PVC feature. 
If something is not working or broken, you just disable that option in project setting and trigger a new prebuild to use old method.
Opening workspace from a prebuild that contains a lot of data should be much faster when using PVC. 
Fixes #10260
1. Open preview environment
2. Add your project. 
3. Go into project settings and enable PVC feature flag.
4. Trigger new prebuild.
5. Open workspace from that prebuild.
For extra points:
Enable incremental …
=> Add PVC support to prebuilds

components/dashboard/src/admin/Settings.tsx, components/gitpod-protocol/src/installation-admin-protocol.ts, components/installation-telemetry/cmd/send.go, components/installation-telemetry/pkg/server/installationAdmin.go, components/licensor/ee/pkg/licensor/licensor.go, components/licensor/ee/pkg/licensor/replicated.go, components/licensor/typescript/ee/src/api.ts, components/server/src/installation-admin/telemetry-data-provider.ts
This pull request exposes the GitPod Customer ID field in installation telemetry.
This issue resolves #10183.
The `customerID` field will be available in the Gitpod Admin/Settings page, displayed in the installation-telemetry job output, and will be present in the segment.io telemetry.
<details>
<summary>Telemetry Disabled</summary>
**Dashboard: Admin/Settings:**
**Installation telemetry job:**
```json
{
"level": "info",
"message": "installation-telemetry is not permitted to send - exiting",
"serviceContext": {
"service": "installation-telemetry",
"version": "commit-2b1c7e10da04762651d753db7b1fb1b9954b3e70"
},
"severity": "INFO",
"time": "2022-06-24T15:28:09Z"
}
```
</details>
<details>
<summary>Telemetry enabled, Customer ID disabled</summary>
**Dashboard: Admin/Settings:** …
=> installation-telemetry: add customer ID

components/gitpod-protocol/data/gitpod-schema.json, components/gitpod-protocol/go/gitpod-config-types.go, components/gitpod-protocol/src/protocol.ts, components/ide/jetbrains/image/status/BUILD.yaml, components/ide/jetbrains/image/status/go.mod, components/ide/jetbrains/image/status/go.sum, components/ide/jetbrains/image/status/main.go, components/ide/jetbrains/image/status/main_test.go, components/ide/jetbrains/image/status/testdata/.gitpod.yml
Add `vmoptions` in gitpod schema (`.gitpod.yml`).
```yaml
jetbrains:
intellij:
vmoptions: "-Xmx4g"
goland:
vmoptions: "-Xmx3g"
```
- This is a follow-up PR with https://github.com/gitpod-io/gitpod/pull/10175
- Schema description text is borrowed from https://www.jetbrains.com/help/idea/remote-development-a.html#rd_add_vm_options
- VMOptions specified by project level `.gitpod.yml` have higher priority than user's environment variables. Suppose we have a workspace with:
- project level `.gitpod.yml`: `jetbrains.intellij.vmoptions = "-Xmx4g"`
- Gitpod user preferences `INTELLIJ_VMOPTIONS` EnvVar set to `-Xmx3g -Didea.is.internal=true` 
- the final effective VMOptions will be `-Didea.is.internal=true -Xmx4g`
Remedy for https://github.com/gitpod-io/gitpod/issues/8704
> Build & test `status` …
=> [jb] enable vmoptions config in .gitpod.yml

components/usage/cmd/run.go, components/usage/pkg/controller/billing.go, components/usage/pkg/controller/reconciler.go, components/usage/pkg/controller/reconciler_test.go, install/installer/pkg/components/usage/constants.go, install/installer/pkg/components/usage/deployment.go, install/installer/pkg/components/usage/deployment_test.go, install/installer/pkg/components/usage/objects_test.go
Make the payment processing part of the usage controller optional. If the secret containing Stripe API keys is configured then enable payments, otherwise disable it.
Usage metering and usage based billing are separate concepts that we will need to enable and disable independently of one another. In Gitpod SaaS we will want both, but for self-hosted installations, users will only care about usage metering.
At some point we will want to have the usage collection and billing integration in separate services but for now, while they both live in the usage component, let's at least be able to toggle billing integration on and off.
Part of #9036 
* Trigger separate Werft builds, one setting `with-payment=true` and the other without.
* Observe that when payment is enabled, the usage component …
=> [usage] Make billing optional in the usage component

components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Correctly show loading state when subscribing a team to usage-based billing.
Fixes https://github.com/gitpod-io/gitpod/issues/10656
Same test process as in https://github.com/gitpod-io/gitpod/pull/10630
...except, after you've just submitted your credit card details:
- the state should not briefly show you "Billing: Not active" with a green button again
- instead, the UI should immediately be "pending"
- (and eventually become "Billing: Active" when the Stripe processing is done)
| 1. Inactive | 2. Add card | 3. Pending | 4. Active |
| --- | --- | --- | --- |
| <img width="647" alt="Screenshot 2022-06-24 at 18 02 00" src="https://user-images.githubusercontent.com/599268/175573851-81c915b4-1c19-4d49-a3b2-66e622826a3c.png"> | <img width="535" alt="Screenshot 2022-06-24 at 18 02 15" …
=> [dashboard] Correctly show loading state when subscribing a team to usage-based billing

install/installer/pkg/common/customize.go, install/installer/pkg/common/customize_test.go, install/installer/pkg/common/display.go, install/installer/pkg/common/objects.go, install/installer/pkg/config/v1/config.go
Implementation of the customization functions as per the [agreed spec](https://github.com/gitpod-io/gitpod/issues/10461). Also contains plenty of unit tests to ensure that the spec is applied correctly
Fixes #10826
Fixes #10902
Fixes #10903
Enter a `customization` parameter in the config.yaml as [per the documentation](https://github.com/gitpod-io/gitpod/issues/10461#issuecomment-1160504435) and check it generates the appropriate output
**NB** the example in the docs gives `ws-manager` deployment as an example of overriding things. This was missed out of the original PR and a [separate PR](https://github.com/gitpod-io/gitpod/pull/10907) has been raised to add that in - please use something else instead of `ws-manager` for testing
```release-note
[installer]: implementation customization …
```
=> [installer]: implementation customization functions

install/kots/manifests/gitpod-installation-status.yaml, install/kots/manifests/gitpod-installer-job.yaml, install/kots/manifests/kots-config.yaml
Adds the config section to the KOTS dashboard for the customization file
**NB** this must be applied to a cluster which does not have Gitpod installed. If you have it installed, you must run `helm un -n gitpod gitpod` beforehand if you intend to change any labels with your customization file. This is because Kubernetes cannot change the labels of a deployment/daemonset/statefulset. As this is for a specific set of enterprise customers who have engaged us for support, this should be an acceptable compromise for the time being.
This may be fixed in a future PR.
This is not an issue if changing annotations
Fixes #10910
Deploy via KOTS to a cluster, using this YAML as your customization file
```yaml
customization:
- apiVersion: apps/v1
kind: Deployment
metadata:
name: server
annotations: …
```
=> [kots]: apply customization file to Installer

components/server/src/installation-admin/telemetry-data-provider.ts
An errant `git rebase` accidentally merged in the customer ID into telemetry
data, bypassing a later check in telemetry collection that checked the `sendCustomerID`
field. This commit restores the appropriate check.
Introduced by #10629 
Go to `Admin/Settings`, disable the `Include customer ID in telemetry` option, and refresh the page. The customer ID field should not be present when the checkbox is unticked.
```release-note
NONE
```
NONE
=> [installation-telemetry] Respect `sendCustomerID` admin setting

components/dashboard/src/settings/Billing.tsx, components/gitpod-protocol/src/protocol.ts, components/server/src/user/user-service.ts
When payment is enabled, attribute all workspace instance usage to an explicitly selected "billing account".
TODO:
Follow-ups:
- Auto-select "billing account" when there is no ambiguity (e.g. when a team upgrades to usage-based billing, also update all its users' `usageAttributionId` where it makes sense)
- Auto-revert to user account when the team subscription is cancelled, or when the user leaves the team
Fixes https://github.com/gitpod-io/gitpod/issues/10901
1. Open a workspace with no project
2. Create a project under your user (this automatically triggers a prebuild, so no need to also start a workspace)
3. Create a Team A, with a Project A under it
4. Create a Team B, with a Project B under it
5. Verify attribution*:
a. Workspace with no project --> your user
b. Workspace with user …
=> [Usage-based] When payment is enabled, attribute all workspace instance usage to an explicitly selected "billing account"

components/usage/pkg/db/dbtest/workspace_instance.go, components/usage/pkg/db/workspace_instance.go, components/usage/pkg/db/workspace_instance_test.go
Adds model definition to consume usage attribution id
* Part of https://github.com/gitpod-io/gitpod/issues/10922
Unit tests
```release-note
NONE
```
=> [usage] Add usageAttributionID to WorkspaceInstance model (in go)

install/installer/pkg/components/docker-registry/helm.go, install/installer/pkg/helm/helm.go
Configure customization in the Helm container registry. 
Fixes #10966
Fixes #10967
Add a customization YAML such as below:
```yaml
customization:
- apiVersion: apps/v1
kind: Deployment
metadata:
name: docker-registry # Important - the component name is "docker-registry"
annotations:
hello: world
labels:
hello2: world2
spec:
env:
- name: hello3
value: world3
```
```release-note
[installer]: allow docker-registry customization
```
=> [installer]: allow docker-registry customization

components/ws-manager/cmd/run.go
For self-hosted, the VolumeSnapshot is optional for now, we should enable the volume_snapshot_controller only when the VolumeSnapshot CRD exists.
Fixes #
https://gitpod.slack.com/archives/C01KLC56NP7/p1656394622810719?thread_ts=1656366685.819199&cid=C01KLC56NP7
1. Scale down the volume snapshot controller.
```console
kubectl scale --replicas=0 deploy/snapshot-controller -n kube-system
```
1. Delete the VolumeSnapshot/VolumeSnapshotContent/VolumeSnapshotClass CRDs.
```console
kubectl delete vsclass --all
kubectl delete crds volumesnapshotclasses.snapshot.storage.k8s.io
kubectl delete crds volumesnapshots.snapshot.storage.k8s.io
kubectl delete crds volumesnapshotcontents.snapshot.storage.k8s.io
```
1. Restart the ws-manager, and make sure the ws-manager is able to start.
```console
kubectl …
```
=> [ws-manager] enable the volume snapshot controller when the VolumeSnapshot CRD exists

.werft/build.yaml, .werft/jobs/build/deploy-to-preview-environment.ts, .werft/jobs/build/installer/installer.ts, .werft/jobs/build/job-config.ts, .werft/jobs/build/prepare.ts, .werft/observability/monitoring-satellite.ts, .werft/platform-delete-preview-environments-cron.ts, .werft/platform-delete-preview-environments-cron.yaml, .werft/util/certs.ts
Removes the core-dev preview environment options
Fixes [#2529](https://github.com/gitpod-io/ops/issues/2529)
```
NONE
```
=> remove core-dev preview environment options

components/ws-proxy/pkg/sshproxy/forward.go, components/ws-proxy/pkg/sshproxy/server.go
[ssh-gateway] improve send heartbeat and add track, [tracking plan](https://www.notion.so/gitpod/ide_close_signal-e2a0f435fd4745b68567eb4d9afc8fd5)
Fixes #
1. Start a workspace
2. connect ssh via copy/paste command
3. open segment, monitor event `ide_close_signal`, it will be send if you close ssh connect.
4. connect ssh via copy/paste command but not require pty
```bash
ssh 'workspaceId#ownerToken@workspaceId.ssh.ws.pd-ssh-improve-hb.preview.gitpod-dev.com' echo test
```
5. monitor segment event `ide_close_signal`, it not send
```release-note
SSH Gateway will send heartbeat only user explicitly request pty
```
=> [ssh-gateway] improve send heartbeat and add track

components/docker-up/BUILD.yaml
Sync fork https://github.com/gitpod-io/compose/releases/tag/2.6.1-gitpod.0
```release-note
Update docker compose to v2.6.1
```
=> [docker-up] Update docker compose to v2.6.1

.werft/observability/monitoring-satellite.ts
Removing a nodepool that is no longer used
Fixes #
```release-note
NONE
```
=> Remove unneeded node selector

components/server/src/auth/resource-access.spec.ts, components/server/src/auth/resource-access.ts, components/server/src/workspace/gitpod-server-impl.ts
This PR adds tests for workspace-like GuardedResources: `Workspace`, `WorkspaceInstance` and `WorkspaceLog`.
It's a precursor for a follow-up PR.
Context: https://github.com/gitpod-io/gitpod/pull/10696
- `cd components/server && yarn test`
```release-note
NONE
```
=> Add tests for GuardedResources: Workspace, WorkspaceInstance and WorkspaceLog (1/2)

.werft/aks-installer-tests.yaml, .werft/installer-tests.ts, install/infra/terraform/aks/README.md, install/infra/terraform/aks/database.tf, install/infra/terraform/aks/kubernetes.tf, install/infra/terraform/aks/local.tf, install/infra/terraform/aks/main.tf, install/infra/terraform/aks/monitoring.tf, install/infra/terraform/aks/networks.tf, install/infra/terraform/aks/output.tf, install/infra/terraform/aks/registry.tf, install/infra/terraform/aks/storage.tf, install/infra/terraform/aks/variables.tf, install/infra/terraform/tools/azure-external-dns/main.tf, install/infra/terraform/tools/cert-manager/main.tf, install/infra/terraform/tools/cloud-dns-ns/main.tf, install/infra/terraform/tools/issuer/azure/main.tf, install/infra/terraform/tools/issuer/azure/variables.tf, install/tests/Makefile, install/tests/main.tf
This PR adds `AKS` to the cloud providers supported in the installer nightly tests. This is a very basic setup of `AKS` without external dependencies and such. That would be done in a follow-up PR.
Fixes #
If you have access to the `core-dev` cluster on GCP, you can run the following command:
```
werft run github -a debug=true -j .werft/aks-installer-tests.yaml
```
The integration tests are still failing. This issue is being handled by the workspace team.
```release-note
NONE
```
=> Add `AKS` terraform module 

components/server/ee/src/workspace/gitpod-server-impl.ts
**Problem**: When a user chooses a billing-enabled team to attribute their usage to, the UI needs to know which team has an active usage-based subscription (teams without an active subscription cannot accept usage attribution).
**Symptoms**:
| Infinite spinner in user billing settings | Console error |
| --- | --- |
| <img width="400" alt="Screenshot 2022-06-28 at 4 49 21 PM" src="https://user-images.githubusercontent.com/599268/176197673-86997f08-ef45-4440-9c79-dd26f48cdea0.png"> | <code>Error: operation not permitted: missing update permission on team</code> |
**Solution**: Allow team members to read their team's active subscription ID if it exists. This fixes the UI, and allows selecting a valid "billing account".
Fixes #
1. Join a team with usage-based billing, but where you're not an …
=> [server] Allow team members (non-owners) to read the team's usage-based subscription ID

components/usage/pkg/controller/billing.go, components/usage/pkg/controller/reconciler.go, components/usage/pkg/controller/reconciler_test.go, components/usage/pkg/db/workspace_instance.go
Updates usage controller flow to do the following:
1. Find all Workspace Instances (with time bounds) which have an `usageAttributionId` set.
2. Groups these (in-code) by Attribution ID to create the report
We can't use SQL level group-by because it can only be used with summary functions (like count). The secondary reason is that the Billing controller (which runs after the usage controller) needs to given the full list of WorkspaceInstances to exclude any WorkspaceInstances which it may have already billed for (in another invoice, for example). For this, it has to get the raw data-set and can't receive an aggregation.
* Part of https://github.com/gitpod-io/gitpod/issues/10922
Unit tests
Can be run against staging by port forwarding
```release-note
NONE
```
NONE
=> [usage] Use attribution ID to reduce DB queries for usage report

components/server/ee/src/user/stripe-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts
Fixes #
1. Upgrade a team to usage-based billing
2. Notice in the Stripe dashboard your new customer with an active subscription
3. Delete the team
4. In the Stripe dashboard, the above customer should no longer have an active subscription
```release-note
NONE
```
=> [server] When deleting a team with an active usage-based subscription, also cancel the subscription

.werft/observability/monitoring-satellite.ts
As a follow-up to https://github.com/gitpod-io/ops/pull/3006, this PR changes the remote-write address used by preview-environments
Fixes #
```release-note
NONE
```
=> previews: Replace remote-write address

components/content-service/pkg/initializer/git.go
Change log message from Warning to Debug to prevent excessive log entries.
It is fine if that function errors out, that code path is only needed for prebuilds using PVC, but would be excessive to try to pass that information into that function to do `if` statement.
Fixes #
```release-note
none
```
=> [content-service] change log message from Warn to Debug

.werft/vm/manifests.ts
Reverts gitpod-io/gitpod#10987
Cannot start preview environments
Start a preview environment
```release-note
NONE
```
=> Revert "Update preview VM image"

components/supervisor/pkg/supervisor/supervisor.go
https://git-scm.com/docs/git-rev-parse
xref: https://cloudlogging.app.goo.gl/iaodaYmM7HfTDpwq8
- Stop the workspace and wait until is not running
- Reopen the workspace
- Check workspace logs and check it does not contain:
`fatal: --unshallow on a complete repository does not make sense`
```release-note
NONE
```
=> [supervisor] Check if git repository is shallow before running --unshallow

components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodClientProjectSessionTracker.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/services/HeartbeatService.kt
add track for sent closed heartbeat
Fixes #
1. start a workspace with IntelliJ
2. open and the close the client
3. monitor in segment, it should send a `ide_close_signal` event
```release-note
NONE
```
=> [jb] add track for sent closed heartbeat

components/gitpod-db/src/typeorm/migration/1655992230337-DropDeprecatedAttributedTeamId.ts
Once we've merged and successfully deployed https://github.com/gitpod-io/gitpod/pull/10868, we should merge this Pull Request to clean up the left-over `attributedTeamId` column.
Optionally, we may also want to "save" the historical attribution data from that older column and back-fill the newer column with it.
Follow-up to https://github.com/gitpod-io/gitpod/pull/10868
1. Should build
```release-note
NONE
```
=> Clean up unused `attributedTeamId` column from workspace instances post-deployment

components/server/ee/src/workspace/gitpod-server-impl.ts
Automatically set a user's explicit `usageAttributionId` in cases where there is no ambiguity:
Fixes https://github.com/gitpod-io/gitpod/issues/10973
1. Start a workspace --> its usage should get attributed to your user
- `d_b_workspace_instance.usageAttributionId` == `user:{YOUR_USER_ID}`
2. Join a team that has usage-based billing enabled, and start another workspace --> its usage should get attributed to the team
- `d_b_workspace_instance.usageAttributionId` == `team:{TEAM_ID}`
3. Leave that team again, and start yet another workspace --> its usage should get attributed to your user again
- `d_b_workspace_instance.usageAttributionId` == `user:{YOUR_USER_ID}`
```release-note
NONE
```
=> Automatically set a user's `usageAttributionId` in cases where there is no ambiguity

components/usage/pkg/controller/controller.go, components/usage/pkg/controller/controller_test.go
Ensures that a single instance of the usage component does not invoke multiple usage controller ticks concurrently. This is done by consuming from a channel which only ever executes linearly. Additionally, we skip buffering runs when we've exceeded 1 item queued already - prevents build up.
Fixes #
Unit tests
```release-note
NONE
```
NONE
=> [usage] Ensure controller ticks are not concurrent

install/installer/pkg/common/customize.go, install/installer/pkg/common/customize_test.go
Changes how the customize envvars orders it's output. It keeps the existing envvars in the order that's given and the customized envvars are ordered in terms of first one received. This is to avoid unnecessary deploys in a GitOps setup.
Overrides the "fix failing test" commit in #10836 by @Furisto - it achieves the same effect, but does so in the application code rather than the test
Fixes #11000
The unit tests provides the test coverage. @mads-hartmann should check that the order is as expected
```release-note
[installer]: order the custom envvars
```
=> [installer]: order the custom envvars

components/dashboard/src/projects/Prebuilds.tsx
The Prebuilds page not always align correctly the columns, e.g. see screeenshot below:
I think this small CSS change could improve already some scenarios.
N/A
1. Start the dashboard for gitpod.io
(I would also suggest Prev Env, but there are no prebuilds there)
|--------|-------|
|     <img width="1702" alt="Screenshot 2022-06-09 at 11 21 36" src="https://user-images.githubusercontent.com/2318450/172899230-1ad3474f-867d-48ff-980a-0a299e5d93a3.png">   |   <img width="1725" alt="Screenshot 2022-06-09 at 11 21 03" src="https://user-images.githubusercontent.com/2318450/172899216-dff2ad65-5f18-4d17-8ea1-e8dd09a10e91.png">    |
```release-note
NONE
```
=> chore(dashboard): adjust prebuild table col width

components/dashboard/src/components/PrebuildLogs.tsx, components/dashboard/src/projects/Prebuild.tsx, components/dashboard/src/start/CreateWorkspace.tsx, components/dashboard/src/start/StartWorkspace.tsx, components/gitpod-protocol/src/gitpod-service.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
This PR gives a perceived consistency between the create workspace page and the prebuild detail view.  
Fixes #9132
1. Make a commit to a project with a prebuild.
2. Go to the project page's Branches tab. Once the prebuild is shown as "Running", start a new workspace.
3. See the logs running and the prebuild status showing below.
```release-note
Prebuild status is shown under the logs when starting a workspace.
```
=> [prebuilds] prebuild detail view in create workspace

components/dashboard/src/projects/Prebuilds.tsx, components/dashboard/src/projects/ProjectSettings.tsx, components/gitpod-db/src/typeorm/workspace-db-impl.ts, components/gitpod-db/src/workspace-db.ts, components/gitpod-protocol/src/teams-projects-protocol.ts, components/gitpod-protocol/src/util/logging.ts, components/server/ee/src/prebuilds/gitlab-app.ts, components/server/ee/src/prebuilds/prebuild-manager.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/workspace-starter.ts
Cancels all running and queued prebuilds for the same branch when a new commit is pushed. 
Adds a project setting to opt-out of this behavior.
Fixes #6569
- Add a project with a long prebuild task
- push multipüle times to the same branch
- see how the previous prebuilds get cancelled.
- push to a different branch and verify that running prebuilds on the other branch are not getting cancelled.
- disable the project setting and verify that the cancellation doesn't happen
```release-note
Outdated prebuilds (i.e. new commits are pushed on a branch) are automatically canceled. This behavior can be disabled in the project's settings.
```
=> [server] abort running prebuilds on same branch

.werft/jobs/build/installer/installer.ts
Currently, when we create a workspace from https://github.com/gitpod-io/spring-petclinic on Preview Environment, it will trigger an OutOfMemoryError during the Build Task.
This happens because `JAVA_TOOL_OPTIONS` currently is set to `-Xmx134m` due to [this line](https://github.com/gitpod-io/gitpod/blob/6aebb2abf8aae1ea8ada0af39867c8ee6688f5be/.werft/jobs/build/installer/installer.ts#L127) which affects `GITPOD_MEMORY` env var, which in turn is used to set Java's memory [here](https://github.com/gitpod-io/gitpod/blob/65384dbc13544d0a79ca055403e5be7d974d89ad/components/supervisor/pkg/supervisor/supervisor.go#L929-L931).
This PR increases Preview Environments memory to address this issue. By increasing memory to `256Mi`, `JAVA_TOOL_OPTIONS` …
=> Double the Requests Memory from Workspace Resources to increase memory available for Java

.werft/platform-delete-preview-environments-cron.yaml
Re-adds the  SA secret used to obtain the core-dev cluster creds. It's required by the delete job to clean-up the certs and LBs.
Currently the job fails:
```
STDERR: ERROR: (gcloud.auth.activate-service-account) Unable to read file [/mnt/secrets/gcp-sa/service-account.json]: [Errno 2] No such file or directory: '/mnt/secrets/gcp-sa/service-account.json'
```
https://werft.gitpod-dev.com/job/gitpod-platform-delete-preview-environments-cron-main.2362
```release-note
NONE
```
=> Re-add core-dev SA secret to preview del job

install/preview/BUILD.yaml, install/preview/README.md
This PR updates the new preview installation method, to be
called `local-preview`. This is part of the recent change
across the documentation https://github.com/gitpod-io/website/pull/2326
The image tag is still `preview-install` in the readme's and other
documentations, but it will be updated once we start publishing
releases with it.
Part of https://github.com/gitpod-io/website/pull/2326
```release-note
[preview] rename `preview-install` to `local-preview`
```
=> [preview] rename `preview-install` to `local-preview`

components/usage/pkg/db/dbtest/workspace_instance.go, components/usage/pkg/db/workspace_instance.go
Originally implemented in TS in https://github.com/gitpod-io/gitpod/pull/10454
Adds the field definition into the Go model, such that it can be used for computing usage by WorkspaceClass
* Relates to https://github.com/gitpod-io/gitpod/issues/10985
Unit tests work
```release-note
NONE
```
NONE
=> [usage] Add WorkspaceClass field to WorkspaceInstance model (in go)

.werft/build.ts, install/infra/terraform/aks/kubernetes.tf, install/infra/terraform/aks/local.tf, install/infra/terraform/tools/azure-external-dns/main.tf, install/tests/Makefile, install/tests/main.tf, install/tests/manifests/kots-config-azure-db.yaml, install/tests/manifests/kots-config-azure-registry.yaml, install/tests/manifests/kots-config-azure-storage.yaml, install/tests/output.tf
This PR updates the `AKS` nightly tests to add the following:
- Create storage, database and registry dependencies on Azure and use a corresponding `kots-config` to install Gitpod
- Reduces the minimum number of nodes to 1 in AKS and change the name pattern to have a `test` keyword in it
- Add `txt-owner-id` keyword to external-dns to ensure multiple `external-dns`(in concurrent tests, etc.) doesn't cleanup each other's entries
Fixes #
You can run the following, provided you have `core-dev` cluster access in the workspace:
```
werft run github -s .werft/installer-tests.ts -j .werft/aks-installer-tests.yaml
```
```release-note
NONE
```
=> Add tests for external dependencies in AKS

components/usage/cmd/run.go, components/usage/pkg/server/server.go, components/usage/pkg/stripe/stripe.go
Refactors `usage` server startup into a function to allow for an integration tests to be created, this also cleans up the commands a bit.
This is the first part of https://github.com/gitpod-io/gitpod/issues/10753, subsequent PR will specify a file with the configuration rather than pass config as command line arguments.
* Relates to https://github.com/gitpod-io/gitpod/issues/10753
* Follow-up https://github.com/gitpod-io/gitpod/pull/11028
Component starts in preview
Unit tests still work
```release-note
NONE
```
NONE
=> [usage] Refactor server start into a function, specify config

components/dashboard/src/workspaces/Workspaces.tsx
Since a few weeks ago, we group and hide "Inactive Workspaces" but don't provide any explanation on what those are. Instead of a description, we only warn that they will be deleted in 14 days.
I propose to change that description to clarify what an "inactive workspace" is while keeping the information about the garbage collection.
| Before  | After |
| ------------- | ------------- |
| <img width="1091" alt="image" src="https://user-images.githubusercontent.com/666176/176009641-d4fbad2c-0510-45fe-afd7-6f3822c1ad4d.png"> | <img width="1105" alt="image" src="https://user-images.githubusercontent.com/666176/176009545-5673b3fc-ec1e-4601-8347-664953b3370e.png">  |
N/A
If needed, running the preview.
```release-note
NONE
```
=> Clarify meaning of "Inactive Workspaces"

components/usage/pkg/controller/reconciler.go, components/usage/pkg/controller/reconciler_test.go
* Takes WorkspaceClass data from the retrieved dataset to determine number of credits this workspace costs
* Relates to https://github.com/gitpod-io/gitpod/issues/10985
Unit tests
```release-note
NONE
```
NONE
=> [usage] Use workspace class when computing credits used

components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodTerminalService.kt
- Auto-forward Task Terminals Ports on JetBrains IDEs.
- Fix an issue about Gitpod Task Terminals now showing up if the user closes the Thin Client (or loses connection) right after opening it.
Note: This only works on Latest JetBrains IDEs (v2022.2).
- It can take a few seconds for the port to be forwarded, after it gets opened o the terminal (up to 10 secs), due to the detection interval from IntelliJ's `portForwardingManager.forwardPortsOfPid`. We can't control this interval time. But it's not an issue if the HTTP server is already running when the user opens the Thin Client.
- Forwarded ports on Terminals from Gitpod Tasks won't display the message "Your application is listening on ports" that you see when you start a server on a normal IntelliJ Terminal Widget.
| Open port on Gitpod …
=> Auto-forward Task Terminals Ports on JetBrains IDEs

components/gitpod-db/src/blocked-repository-db.spec.db.ts, components/gitpod-db/src/blocked-repository-db.ts, components/gitpod-db/src/container-module.ts, components/gitpod-db/src/tables.ts, components/gitpod-db/src/typeorm/blocked-repository-db-impl.ts, components/gitpod-db/src/typeorm/entity/db-blocked-repository.ts, components/gitpod-db/src/typeorm/migration/1656408949484-AddBlockedRepositoryTable.ts, components/gitpod-protocol/src/blocked-repositories-protocol.ts, components/server/src/workspace/workspace-starter.ts
Add a `d_b_blocked_repository` table to the application database and use it at workspace startup to check whether a workspace should be blocked. Also checks if the user should be blocked for attempting to start such a workspace and blocks the user as necessary.
Part of https://github.com/gitpod-io/gitpod/issues/11030
* Get a kube context for the preview environment for this branch:
```bash
previewctl install-context
```
* Port forward to the database (username and password is in the `server` environment):
```bash
kubectl port-forward svc/mysql 3306:3306
```
* Using `mysql` client or `mycli` (needs `brew install mycli` first) add an entry to the `d_b_blocked_repository` table.
```sql
insert into d_b_blocked_repository (`urlRegexp`, `blockUser`, `deleted`) values ("github.com/<your github …
```
=> [server] Read blocked repositories from database

operations/observability/mixins/workspace/rules/components/ws-daemon/alerts.libsonnet
Because every time series is uniquely identified by its metric name and a set of labels, every unique combination of key-value label pairs represents a new alert for this time series.
There is no common value for these metrics
- kube_pod_container_status_restarts_total
- gitpod_ws_manager_workspace_backups_failure_total
Fixes #
```release-note
None
```
None
=> [alerts] fix pod/container/namespace not rendering

components/dashboard/src/components/PrebuildLogs.tsx, components/dashboard/src/start/CreateWorkspace.tsx, components/server/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/workspace-starter.ts
This PR deprecates an older mechanism to stream image build logs. Removing that revealed that it was shadowing reliabilty problems, so those got fixed in the frontend as well. :see_no_evil: 
I hid the changes behind a feature flag to safely test the effects in staging + prod (different ingress infrastructure).
Fixes #11024
- create a team and project (e.g. on this [test repo](https://github.com/geropl/gitpod-test-repo/tree/gpl/docker-build-2mins))
- push a commit, for instance to [this branch](https://github.com/geropl/gitpod-test-repo/tree/gpl/docker-build-2mins)
- switch to "Branches", wait for the prebuild to start and click on the Prebuild Details view
- open a second tab on "Branches", and once the prebuild is there, click "start workspace" right next to it
- observe that a) …
=> Reliably fetch logs for imagebuild and prebuild itself

components/dashboard/src/projects/ProjectSettings.tsx
Following up from https://github.com/gitpod-io/gitpod/pull/10962#discussion_r910117371, this is a minor copy update for the preference option for canceling prebuilds on outdated commits in project settings.
```release-note
NONE
```
=> Update project settings preference copy

components/installation-telemetry/cmd/send.go, gitpod-ws.code-workspace, install/installer/pkg/components/gitpod/cronjob.go, install/installer/pkg/config/v1/experimental/experimental.go, install/kots/manifests/gitpod-installer-job.yaml, install/preview/entrypoint.sh
This PR adds a new `experimental.telemetry.data.platform` config option
that is then passed to `GITPOD_INSTALLATION_PLATFORM` env variable, which
is then transmitted by the `gitpod-telemetry` job as the `platform`
property into our telemetry store. The value of this env variable
is then overrided by each install method.
This env can have the following values:
- `installer` by default as when the installation is done directly
through the installer, We don't have enough information
about the environment.
-  [One of the `distribution` values](https://docs.replicated.com/reference/template-functions-static-context#distribution)
when done through `kots`. This would have the distribution in which
Gitpod is being installed, and is dependent on `kots`.
- `local-preview` when the installation is …
=> [telemetry] Add new `telemetry.data` config option for telemetry

components/ws-proxy/pkg/proxy/pass.go, components/ws-proxy/pkg/proxy/routes.go
[ws-proxy] not use target host when serve workspace port route
At this PR https://github.com/gitpod-io/gitpod/pull/10514  
We use targetHost in order to allow `blobserve` behind `ide-proxy` to process requests properly, but this creates a problem that causes users to receive the wrong host when they use `https://{port}-workspaceUrl`, which is `internal-pod-ip: port`, this PR fixes that bug
|  In gen 51   | in preview environment  |
|  ----  | ----  |
| ![image](https://user-images.githubusercontent.com/8299500/176864422-9de9f827-3835-47d9-bad0-5f2291983bf9.png)  | ![image](https://user-images.githubusercontent.com/8299500/176868722-2f2b7440-5bf5-4c38-b728-2dd31e99c5fb.png) |
Fixes #11070
1. Open a workspace
2. run `curl lama.sh | sh`
3. use `gp preview $(gp url 8080) --external` to open a …
=> [ws-proxy] not use target host when serve workspace port route

install/kots/manifests/gitpod-installation-status.yaml, install/kots/manifests/gitpod-installer-job.yaml
This PR updates the image tags in the kots builds to use
the latest config changes. Not updating this broke dev builds
as it tries to set a config change that isn't present in the
image itself.
Fixes #
```release-note
NONE
```
=> [kots] update image to be the latest config change build

components/server/src/workspace/gitpod-server-impl.ts
Fixes #
- create a team and project (e.g. on this [test repo](https://github.com/geropl/gitpod-test-repo/tree/gpl/docker-build-2mins))
- push a commit, for instance to [this branch](https://github.com/geropl/gitpod-test-repo/tree/gpl/docker-build-2mins)
- switch to "Branches", wait for the prebuild to start and click on the Prebuild Details view
- open a second tab on "Branches", and once the prebuild is there, click "start workspace" right next to it
- observe that a) streaming of image build logs and b) streaming of prebuild logs works as expected
```release-note
fix prebuild permissions
```
=> [server] Workaround for lagging prebuild permissions

components/dashboard/src/projects/Prebuilds.tsx
Following up from https://github.com/gitpod-io/gitpod/pull/10696, this will fix text alignment for the prebuild status description text.
Cc @geropl based on a [recent discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1656682927568149?thread_ts=1656675972.139439&cid=C02EN94AEPL) (internal).
|-|-|
| <img width="898" alt="logs-before" src="https://user-images.githubusercontent.com/120486/176916314-16b65cb9-aeb4-42b5-9c8b-4f691c8da8e0.png"> | <img width="898" alt="logs-after" src="https://user-images.githubusercontent.com/120486/176916319-cb93bc7f-7b0f-4bd9-a817-df2b085ca157.png"> |
```release-note
NONE
```
=> Update prebuild status description alignment

install/tests/Makefile
EKS clusters implement `LoadBalancer` type services with ELBs; when an
EKS cluster is destroyed via terraform these ELBs are not automatically
deleted. The continued presence of these ELBs will remain attached to
the associated subnets and prevent the subnets and VPC from being
destroyed.
This commit resolves the issue by explicitly deleting the `gitpod`
namespace (and pausing to allow the ELBs to be removed) before
continuing.
This issue is related to #11092 and may partially resolve that issue; more testing is needed.
```
werft job run github \
gitpod-io/gitpod:alt/fix-int-test/delete-gitpod-ns \
-s .werft/installer-tests.ts \
-j .werft/eks-installer-tests.yaml \
-a debug=true -a
```
```release-note
NONE
```
N/A
=> [install/tests] Delete gitpod namespace before infrastructure removal

components/ws-proxy/pkg/proxy/routes.go
Add X-Forwarded-Port header, as it's required by some software, like [FusionAuth](https://fusionauth.io/).
- This issue was reported by `(M) Chakshu` on Discord [[1](https://discord.com/channels/816244985187008514/989421509615448104)].
- https://github.com/FusionAuth/fusionauth-issues/issues/470
- [Open a workspace on the Preview Environment of this PR](https://felladrin-6876f11602.preview.gitpod-dev.com/#https://github.com/gitpod-io/empty).
- Run `curl lama.sh | sh`
- Run `gp preview $(gp url 8080) --external` to open a browser.
- Confirm you see, in the terminal logs of the request, the `X-Forwarded-Port` header. It should be the same port displayed at the end of `X-Forwarded-Host` header.
```release-note
Requests on ws-proxy now contain also the `X-Forwarded-Port` header.
```
None.
=> [ws-proxy] Add X-Forwarded-Port header

components/ide/jetbrains/gateway-plugin/gradle.properties
Temporarily use a fixed version of JetBrains Gateway SDK, to solve Werft not being able to build the gateway plugin  on main branch [[1](https://werft.gitpod-dev.com/job/gitpod-build-main.3765)].
It's currently failing with the message
```
> Task :compileKotlin FAILED
e: /tmp/build/components-ide-jetbrains-gateway-plugin--publish.0b3644e51dba5594b271ae6e6c3ef871e0b47c39/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt: (231, 41): Type mismatch: inferred type is RemoteCredentialsHolder but HostTunnelConnector was expected
```
Later I'll create another PR fixing the code to make it work again with the latest version of Gateway SDK.
Check if Werft build succeeds for this PR: https://werft.gitpod-dev.com/job/gitpod-build-felladrin-temporarily-use-a-fixed-version-ofa.0 …
=> Temporarily use a fixed version of JetBrains Gateway SDK

.werft/util/certs.ts
Removes an assertion from the wait exec for certificate failures
Fixes #10823
```release-note
NONE
```
=> remove certificate kubectl wait assert

components/workspacekit/cmd/rings.go, components/workspacekit/go.mod, components/workspacekit/go.sum, components/workspacekit/pkg/seccomp/notify.go, components/ws-daemon/pkg/iws/iws.go, dev/image/Dockerfile
- improve logging
- upgrade libseccomp-golang https://github.com/gitpod-io/libseccomp-golang/pull/2
- Addition of parallel processing of shisumu koru
Fixes https://github.com/gitpod-io/gitpod/issues/9247
Precisely up to the reduction. For some reason seccomp notify is cancelled by the linux kernel. Neither docker-compose nor runc can handle it.
We mitigate it a bit by processing it as quickly as possible.
More detail
https://github.com/seccomp/libseccomp-golang/commit/3879420cc921efb4f1a2d75bea84e6158ef21a78
open this repository and works fine
https://github.com/appwrite/integration-for-gitpod
```release-note
Improve system call handling
```
=> improve seccomp notify

components/dashboard/src/Menu.tsx, components/dashboard/src/components/Alert.tsx, components/dashboard/src/components/ConfirmationModal.tsx, components/dashboard/src/settings/Account.tsx, components/dashboard/src/settings/ProfileInformation.tsx, components/dashboard/src/workspaces/Workspaces.tsx, components/gitpod-protocol/src/protocol.ts, components/licensor/typescript/ee/src/api.ts, components/server/src/auth/auth-provider.ts, components/server/src/bitbucket/bitbucket-auth-provider.ts, components/server/src/github/github-auth-provider.ts, components/server/src/gitlab/gitlab-auth-provider.ts
This change allows users to update their name, email and company name.
It also nudges users in the workspaces view on the second day (or after) and then once a year.
Fixes #10999
Use the preview env, 
- create a new user
- verify you don't get nudged (no modal) on /workspaces
- set system time to yesterday and reload page. You should now see a modal.
- either update your profile or simply close the modal (cancel or close).
- reload page, you should not see the modal anymore (only after one year, which you can verify again by setting your system date)
- Check the settings page
```release-note
You can now update your profile information (name, email, company)
```
=> [dashboard] allow editing user information

.werft/ide-integration-tests-startup-vscode.yaml
This PR fix IDE integration test (vscode only), for Jetbrains it needs refractory
Fixes #
1. start a workspace from this branch
2. run `werft run github -j .werft/ide-integration-tests-startup-vscode.yaml`
3. see build log, it will start a preview environment, and run vscode test case
4. it will failed because vscode test failed, but it's not about this PR cc: @jeanp413 
```release-note
NONE
```
=> [integration-test]fixes vscode integration test

install/preview/entrypoint.sh
This PR updates the `entry-point.sh` to run a parallel step
that waits for the gitpod pods to be ready, and manually executes
the cronjob once its necessary.
This is necessary as our telemetry `cronjobs` are only ran
daily in the midnight, and we can't expect this schedule to work
for local previews as they are short lived.
example data that we get:
```
client.Track(&analytics.Track{
UserId: "334c379a-afee-4882-ba44-fbd7dfc0a8b0",
Event: "Installation telemetry",
Properties: map[string]interface{}{
"customerID": "",
"platform": "local-preview",
"totalInstances": 0,
"totalUsers": 0,
"totalWorkspaces": 0,
"version": "tar-preview-tel-init.4",
},
})
```
Fixes https://github.com/gitpod-io/gitpod/issues/11113
Check if there is a new job called …
=> [preview] run the telemetry job right after gitpod is ready

components/dashboard/src/components/PrebuildLogs.tsx, components/dashboard/src/start/StartWorkspace.tsx
This fixes the broken layout, but doesn't add yet the "Skip Prebuild" button as we intended [in a recent epic](https://github.com/gitpod-io/gitpod/issues/9132). Skipping prebuilds will be covered in [a follow-up issue](https://github.com/gitpod-io/gitpod/issues/11128).
| - | - |
| <img width="609" alt="Screenshot 2022-07-04 at 15 05 39" src="https://user-images.githubusercontent.com/8015191/177173689-8b6457eb-4c81-4067-92a8-ec699a50d9c1.png"> | <img width="679" alt="Screenshot 2022-07-04 at 18 19 56" src="https://user-images.githubusercontent.com/8015191/177191547-7405e8d6-1e15-41e9-97f2-08fb6e453d7a.png"> |
Fixes #11079 
1. Run a prebuild using `https://laushinka-be81110388.preview.gitpod-dev.com/#prebuild/[YOUR_REPO]`
2. See the fixed view as in the description. …
=> [prebuild] Fix view when coming from prefix

components/gitpod-db/src/blocked-repository-db.spec.db.ts, components/gitpod-db/src/blocked-repository-db.ts, components/gitpod-db/src/typeorm/blocked-repository-db-impl.ts, components/gitpod-protocol/src/admin-protocol.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
Add `adminCreateBlockedRepository` and `adminDeleteBlockedRepository` APIs to `components/server` to create and delete blocked repositories
This is a step towards using these endpoints to manage blocked repositories in the admin UI.
Part of https://github.com/gitpod-io/gitpod/issues/11030
* Open the developer tools on the admin page for this preview environment.
* Create a blocked repository:
```js
await window._gp.gitpodService.server.adminCreateBlockedRepository("github.com/<your-username>/.*", true)
```
* List blocked repositories: 
```js
await window._gp.gitpodService.server.adminGetBlockedRepositories({offset: 0, limit: 10, orderBy: 'id', orderDir: "desc", searchTerm: "foo"})
```
* (at this point you could try to start a workspace from a repo under your user to see that it really is …
=> [server] Add API to create and delete blocked repositories

components/server/src/auth/resource-access.spec.ts, components/server/src/auth/resource-access.ts
Align access level of Workspaces of type "prebuild" with Prebuilds
:information_source: It make sense to review this PR per commit:
- the 1st commit fixes the test setup (and a bug)
- the 2nd commit is the actual fix for this issue
Fixes #11127 
- `cd components/server`
- `yarn test`
```release-note
align access level of Workspaces of type "prebuild" with Prebuilds
```
=> Align access level of Workspaces of type "prebuild" with Prebuilds

.werft/util/certs.ts, .werft/util/slack.ts
Updates the certificate failure alerts to provide more debug and use @ask-platform handle
```release-note
NONE
```
=> Fix certificate alert to add more debug and use ask handle

install/installer/pkg/common/render.go, install/installer/pkg/components/rabbitmq/secret.go
This sets both the `rabbitmq.auth.password` value and the `messagebus-erlang-cookie` secret with static values. This has the benefit of not reloading the message bus every time a redeployment happens - this makes deployments faster and existing workspaces don't lose connections.
The initial ticket only mentions the cookie secret, but discovered that the [password is hardcoded in the experimental section](https://github.com/gitpod-io/ops/search?q=staticMessagebusPassword) - this doesn't change the functionality of `experiments.common.staticMessagebusPassword` so the Ops repo will still work as expected.
Fixes #10459
Deploy the application
```release-note
[installer]: set a stable password for messagebus
```
=> [installer]: set a stable password for messagebus

install/kots/manifests/kots-preflight.yaml, install/kots/manifests/kots-support-bundle.yaml
Adds a simple check to ensure that a network connection can be made to the pull registry. The command `curl https://eu.gcr.io/v2/` does actually (correctly) return an unauthorized error as the check is that it can make an HTTP connection in the timeout. However, it still exits with a code 0.
If it fails to connect within the timeout, it will exit with a non-zero error code.
In airgapped, it runs against the pull repository.
Fixes #10244
Install in a non-airgapped and airgapped environment
```release-note
[kots]: add firewall check for the pull registry
```
=> [kots]: add firewall check for the pull registry

components/ws-daemon/cmd/run.go
Increase ws-daemond process priority to improve responsiveness when the node CPU and/or I/O utilization is high
- Check `ws-daemond` process nice level running  `ps ax -o pid,ni,cmd` is `-19`
```release-note
NONE
```
Note: we cannot do the same thing with `registry-facade` because it does not run as privileged :(
=> [ws-daemon] Increase process priority

operations/observability/mixins/workspace/rules/components/nodes/alerts.libsonnet
alert when we cannot scale-up
Fixes https://github.com/gitpod-io/gitpod/issues/11051
https://github.com/gitpod-io/runbooks/pull/363
```release-note
NONE
```
no
=> obserbility: Add a alert for AutoscaleFailure.

components/content-service/pkg/storage/gcloud.go, components/content-service/pkg/storage/gcloud_test.go, components/ws-daemon/BUILD.yaml, components/ws-daemon/cmd/debug-run-initializer.go, components/ws-daemon/cmd/debug.go, components/ws-daemon/debug.Dockerfile, components/ws-daemon/leeway.Dockerfile, components/ws-daemon/pkg/content/initializer.go
Switch to gcloud gsutil cli to upload and downloads for GCS interaction with backups. This improves the speed and also removes the multipart complexity from the codebase.
```release-note
Improve transfers for S3 when backed by GCS
```
=> [content-service] Use gsutil to upload and download backups

components/dashboard/src/Analytics.tsx, components/dashboard/src/settings/Preferences.tsx, components/dashboard/src/settings/selectClass.tsx, components/ee/payment-endpoint/src/accounting/account-service.spec.db.ts, components/gitpod-db/src/typeorm/user-db-impl.ts, components/gitpod-protocol/src/protocol.ts
Add dialog for selecting workspace classes to preferences. Note that the current icons and class names are placeholders. This PR is purely for setting up the logic in the frontend.
Fixes #https://github.com/gitpod-io/gitpod/issues/10843
- Open dashboard and go to Settings -> Preferences
- Set your workspace  class
- Switch to another submenu and switch back -> your changes should have been persisted
- In the user table, additionalData should have a workspaceClasses entry
```release-note
NONE
```
=> Configure workspace classes from dashboard

components/ws-manager/pkg/manager/metrics.go, components/ws-manager/pkg/manager/monitor.go
Hey Workspace-team!
We noticed that you want to level up your game towards success-criteria-related metrics, and there is momentum in the company to start adopting SLOs to get the right metrics.
We from the platform-team are being a little more proactive regarding implementing SLOs and while trying to get the first example up and running, we noticed that your metrics for workspace backups and workspace restores are a bit out of best practices for SLOs with Prometheus 😬 
When implementing success ratio SLOs, we usually look for metrics that represent "total amount of requests" and "amount of failed requests". So the calculation looks like this: `backup error ratio = amount of backup with errors / total amount of backups`
Would it be fine if we change the current metrics to be more …
=> ws-manager: Replace backup/restore success with total metric

install/installer/cmd/render.go, install/installer/pkg/components/proxy/service.go, install/installer/pkg/components/proxy/service_test.go, install/installer/pkg/config/loader.go, install/installer/pkg/config/v1/config.go, install/installer/pkg/config/v1/experimental/experimental.go, install/installer/pkg/config/validation.go, install/kots/manifests/gitpod-installation-status.yaml, install/kots/manifests/gitpod-installer-job.yaml, install/kots/manifests/kots-config.yaml
> Anyone relying upon this config in the `experimental` section should move to the `components`. See description for new format
Deprecated the proxy's service type in `experimental` and promotes it to the primary configuration. Implements the configuration as per #10983.
Includes the KOTS config section in a separate "Components" group - the reasoning behind this is that there may be additional component-specific configuration in the future. This should make it easier to manage/visualise. This is only displayed if the "enable additional options" is enabled.
Adds the ability to deprecate config parameters.
I've also renamed "additional options" to "advanced options"
Fixes #11008
Fixes #11009
Fixes #11025
Fixes #11033 
```release-note
[installer]: promote proxy service type from …
```
=> [installer]: promote proxy service type from experimental

components/gitpod-db/src/typeorm/entity/db-blocked-repository.ts, components/gitpod-db/src/typeorm/migration/1657105883801-BlockedRepositoryFix.ts
Fixes #11146 
- create a new branch + preview environment from `main`
- open workspace on that branch
- connect to DB:
- `kubectl port-forward mysql-0 3306 &`
- `mysql -u gitpod -h 127.0.0.1 -p`, PW: `jBzVMe2w4Yi7GagadsyB` (not a secret, our default PW)
- execute both lines of migration from [here](https://github.com/gitpod-io/gitpod/pull/11175/commits/ce8901f551a1481ada0bbbb6abd7dd1c34c8fce5#diff-153bcfe720a7ac18300e0f0215b6997eb1a9e5de7332204d3d55e6a989c07626R12)
- note how they work without any issues (prod/staging tables are empty as well)
```release-note
NONE
```
=> Fix incompatible column type in DBBlockedRepository

components/dashboard/src/Menu.tsx, components/dashboard/src/utils.test.ts, components/dashboard/src/utils.ts
This bug #10666 was due to this
https://github.com/gitpod-io/gitpod/blob/402894b63b604234899db345fca0a9ce3750cec1/components/dashboard/src/Menu.tsx#L109
failing if `url` contained trailing `'/'`.
Here's a test
``` js
var url = new URL('https://gitpod.io/workspaces/')
>> ["/workspaces"].includes(url.pathname)
<- false
```
So if that was true, it should also happen to 
https://github.com/gitpod-io/gitpod/blob/402894b63b604234899db345fca0a9ce3750cec1/components/dashboard/src/Menu.tsx#L108
which was indeed the case, see https://gitpod.io/new/ (notice trailing '/').
A simple solution would have been to include another element (`"workspaces/")` in the array or discard trailing '/' and check with `includes`. Adding a new element can potentially cause similar problem if we were to forget …
=> fix(dashboard): Tab menu visible for urls trailing '/'

components/gitpod-protocol/src/experiments/types.ts, components/gitpod-protocol/src/workspace-cluster.ts, components/ws-manager-bridge/debug.sh, components/ws-manager-bridge/src/cluster-service-server.ts, components/ws-manager-bridge/src/cluster-sync-service.ts, components/ws-manager-bridge/src/config.ts, components/ws-manager-bridge/src/container-module.ts, components/ws-manager-bridge/src/main.ts, components/ws-manager-bridge/src/rpc.ts, install/installer/pkg/common/common.go, install/installer/pkg/components/server/deployment.go, install/installer/pkg/components/ws-manager-bridge/configmap.go, install/installer/pkg/components/ws-manager-bridge/deployment.go, install/installer/pkg/components/ws-manager-bridge/types.go
**Note:** This is a stacked PR that depends on https://github.com/gitpod-io/gitpod/pull/10982
During registration of a workspace cluster the workspace classes that are supported by this cluster will be fetched from the DescribeCluster endpoint of ws-manager. They are also fetched in a configurable interval (currently 60 seconds) so that updates to the supported classes are propagated to the meta side. 
I have added a feature flag, so that this change can be deployed even if the new endpoint from https://github.com/gitpod-io/gitpod/pull/10982 has not been deployed to workspace clusters yet.
Partially fixes #https://github.com/gitpod-io/gitpod/issues/10842
- Currently the feature flag (workspace_classes_backend) is active, so with debug logs activated (gpctl debug logs ws-manager-bridge) …
=> Retrieve supported workspace classes  from workspace cluster

install/installer/pkg/components/agent-smith/configmap.go, install/installer/pkg/config/v1/experimental/experimental.go
Allows to specify agent smith config via installer yaml, as currently we overwrite configmap instead when deploying in SaaS.
Related to https://github.com/gitpod-io/gitpod/issues/10418
```release-note
none
```
=> [installer] allow to specify agent smith config

components/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go
```
goroutine 155927 [running]:
github.com/gitpod-io/gitpod/ws-daemon/pkg/cgroup.extractCommand(0x22f7190?)
github.com/gitpod-io/gitpod/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go:135 +0xd0
github.com/gitpod-io/gitpod/ws-daemon/pkg/cgroup.determineProcessType(0x22f7190?)
github.com/gitpod-io/gitpod/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go:104 +0x25
github.com/gitpod-io/gitpod/ws-daemon/pkg/cgroup.(*ProcessPriorityV2).Apply.func1()
github.com/gitpod-io/gitpod/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go:83 +0x8ca
created by github.com/gitpod-io/gitpod/ws-daemon/pkg/cgroup.(*ProcessPriorityV2).Apply
github.com/gitpod-io/gitpod/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go:52 +0x18c
``` 
```release-note
NONE
```
=> [ws-daemon] Fix extraction of process arguments

components/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go, components/ws-daemon/pkg/daemon/daemon.go
xref https://github.com/gitpod-io/gitpod/pull/11159#issuecomment-1175834586
- Open a workspace using VS Code Desktop and check the NI value of processes
```release-note
NONE
```
cc @akosyakov
=> [ws-daemon] Add additional process type priorities

components/gitpod-db/src/blocked-repository-db.spec.db.ts, components/gitpod-db/src/blocked-repository-db.ts, components/gitpod-db/src/typeorm/blocked-repository-db-impl.ts, components/gitpod-protocol/src/admin-protocol.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
Add `adminGetBlockedRepositories` API to `components/server` to fetch the list of blocked repositories.
This is a step towards using these endpoints to manage blocked repositories in the admin UI.
Part of #11030
* Follow the first 3 steps on https://github.com/gitpod-io/gitpod/pull/11036 to add some blocked repositories.
* Open the developer tools on the admin page for this preview environment.
* Run:
```js
await window._gp.gitpodService.server.adminGetBlockedRepositories({offset: 0, limit: 10, orderBy: 'id', orderDir: "desc", searchTerm: "foo"})
```
setting `searchTerm` as appropriate (or omitting it entirely).
```release-note
NONE
```
/hold
=> [server] Add server API to list blocked repositories

components/server/src/github/github-repository-provider.ts, components/server/src/gitlab/gitlab-repository-provider.ts
Gain insight into if and why `hasReadAccess` might fail for user registered SCM providers.
Context: #11172 
```release-note
NONE
```
=> [server] Log hasReadAccess errors

components/ee/db-sync/src/export.ts
When DB sync runs on on 
```
"SELECT id, userId, name, key, fingerprint, deleted, _lastModified, creationTime, lastUsedTime FROM d_b_user_ssh_public_key WHERE _lastModified >= '2022-07-07 08:24:39.562'"
```
It fails with 
```
"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'key, fingerprint, deleted, _lastModified, creationTime, lastUsedTime FROM d_b_us' at line 1"
```
This is because of `name` and `key` are keywords in SQL. This fixes it.
Also, we shouldn't string roll an ORM model... :/
Fixes #
```release-note
NONE
```
NONE
=> [db-sync] Escape column names

components/ide/code-desktop/status/main.go, components/ide/code/codehelper/main.go, components/ide/jetbrains/image/status/main.go, components/supervisor/pkg/supervisor/supervisor.go
Fixes #11101
1. Select vscode desktop in dashboard
1. Open https://gitlab.com/bakins-bits/gitpod-setup-for-bitcoin-core-dev in prev env
2. When vscode desktop connects to workspace check the workspace openup with three folders by default - `bitcoin` `btcdeb` `gitpod-setup-for-bitcoin-core-dev`
```release-note
NONE
```
=> Fix workspace location when opening in vscode desktop

WORKSPACE.yaml
Update code to `1.69.0`
https://afalz-gene7246070292.preview.gitpod-dev.com/workspaces
```release-note
NONE
```
=> [code] Generate stable images for 1.69

install/installer/pkg/components/workspace/ide/constants.go
Updates stable VS Code version to 1.69.0.
Part of https://github.com/gitpod-io/gitpod/issues/10990
Switch to stable in the preview environment and in the about dialog confirm you are running 1.69
```release-note
NONE
```
=> [code] Update stable to 1.69

components/dashboard/src/admin/UserDetail.tsx, components/dashboard/src/settings/Teams.tsx, components/gitpod-db/src/typeorm/team-subscription-db-impl.ts
This PR fixes two issues:
1. "Teams" UI no longer displays slots from multiple Team Subscriptions, but used the id to match them correctly
2. Do not forward "deleted" Team Subscriptions from the DB.
3. User Details: filter out deleted subscriptions
Fixes #11203 
Not sure how to test: I'd argue we should thoroughly review the diff and judge based on that.
```release-note
two fixes the old Team Subscription UI
```
=> Team Subscription UI fixes

components/dashboard/src/components/PrebuildLogs.tsx, components/dashboard/src/start/CreateWorkspace.tsx, components/dashboard/src/start/StartWorkspace.tsx
This makes sure the buttons will always show (and view always scrollable) regardless the screen size.
Tested on workspace start, prebuild detail view, and prebuild prefix trigger.
Fixes #11189
1. Make a change to a repo with a prebuild
2. Resize the screen to a small size, buttons should always be in view.
```release-note
Make prebuild logs responsive for small viewports
```
=> [prebuild] Make prebuild logs view more responsive

components/content-service-api/go/initializer.go, components/content-service-api/go/initializer_test.go, components/ws-manager/pkg/manager/create.go, components/ws-manager/pkg/manager/create_test.go, components/ws-manager/pkg/manager/manager.go, components/ws-manager/pkg/manager/manager_test.go, components/ws-manager/pkg/manager/testdata/validateStartReq_invalidType.golden, components/ws-manager/pkg/manager/testdata/validateStartReq_invalidType.json, components/ws-manager/pkg/manager/testdata/validateStartReq_oversizedSecret.golden, components/ws-manager/pkg/manager/testdata/validateStartReq_oversizedSecret.json, components/ws-manager/pkg/manager/testdata/validateStartReq_valid.golden, components/ws-manager/pkg/manager/testdata/validateStartReq_valid.json
Otherwise content init fails for private repositories.
1. open a workspace on a private repo
2. enable the protected_secrets FF and open a workspace on a private repo
```release-note
NONE
```
=> [ws-manager] Only extract secrets when FF is set

components/ee/db-sync/src/export.ts
Follow up to https://github.com/gitpod-io/gitpod/pull/11196. We also need the same escaping when running `INSERT`s.
Fixes #
```release-note
NONE
```
=> Escape column names in INSERT statement

components/dashboard/src/admin/WorkspaceDetail.tsx
Sometimes it is useful to know the node a workspace was scheduled on. This adds the node name to the admin dashboard.
n.a.
- Start a workspace in preview environment and check the workspace in admin
```release-note
None
```
=> [dashboard] Show assigned node for workspace

components/dashboard/src/Menu.tsx, components/dashboard/src/projects/ProjectSettings.tsx, components/dashboard/src/settings/Preferences.tsx, components/gitpod-protocol/src/experiments/configcat.ts, components/gitpod-protocol/src/experiments/types.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/gitpod-server-impl.ts
This will more effective segmentation based on emails and potentially other things, like identity providers (GitHub, GitLab, BitBucket etc.)
Fixes #
```release-note
NONE
```
=> [feature flags] Nudge passing in full User shapes and derive email from it

install/installer/pkg/components/usage/networkpolicy.go, install/installer/pkg/components/usage/objects.go, install/installer/pkg/components/usage/objects_test.go
Add a network policy for the usage component so that it accepts incoming gRPC connections from `server` (and no other components).
Part of #9036 
1. Open a preview environment and install the kubecontext for this branch:
```
previewctl install-context
```
2. Run an ubuntu pod in the `default` namespace.
```
kubectl run ubuntu -it --image ubuntu -- /bin/sh
```
3. Install a `grpc` client like [evans](https://github.com/ktr0731/evans/releases) or `grpcurl` into the container.
4. Try to connect from the `ubuntu` pod to the `usage` service:
```
./evans --host usage -p 9001 -r repl
```
See that it fails.
5. Label the `ubuntu` pod:
```
kubectl label pod ubuntu component=server
```
6. Try the same `evans` command from inside the ubuntu container.
This time the connection succeeds because the pod …
=> [usage] Add network policy to allow ingress from server

components/ee/payment-endpoint/src/accounting/account-service.spec.db.ts, components/gitpod-db/src/user-db.spec.db.ts, components/gitpod-db/src/workspace-db.spec.db.ts, components/gitpod-protocol/src/workspace-instance.ts, components/server/src/auth/resource-access.spec.ts, components/server/src/workspace/workspace-starter.ts, components/ws-manager-bridge/src/bridge.ts, components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
This PR makes ws-manager-bridge respect and record the status version reported by ws-manager.
Prior this behaviour was only used for prebuilds. We need to extend this behaviour to get rid of a host of heuristics which aim to identify the latest update, and to properly support the public API.
If I understand correctly, this change renders the prebuild status check ineffective because it preempts this check. If this is really the case, we want to consider removing the prebuild status check.
cc @easyCZ 
1. Start and stop workspaces - things should work as normal
2. Inspect the database/instance updates. You should see the status.version increment
```release-note
NONE
```
=> [ws-manager-bridge] Use WS update status version

components/ws-manager/pkg/manager/manager.go
If we have an error after backoff, log it as an error, otherwise log errors during backoff as a warning.
The errors we encounter while doing exponential backoff should be treated as warnings, because they don't necessarily require action. This way, the error at the end (signifying we could not start a workspace) becomes more valuable.
For example, during a traffic shift, these were showing as errors, but that was false (we were waiting for nodes to scale-up).
Fixes # n/a
1. Go to the [preview environment](https://kylos101-b4ce73b066e.preview.gitpod-dev.com/workspaces)
2. Before you start a workspace in the preview environment, `kubectl cordon` the node (_this is already done_), so a workspace pod cannot be scheduled
3. Try starting a workspace 
4. Observe via `kubectl logs …
=> [ws-manager] log errors as warnings during exponential backoff

dev/gpctl/cmd/workspaces-last-heartbeat.go
Fixes #
- Open a workspace in prev env
- Open this gitpod with this PR
- Get workspace instance id that you created
```
kubectl get pods | grep ws-
env | grep INSTANCE_ID
```
- Exec `gpctl workspaces last-heartbeat <instance_id>` in gitpod repo workspace
Should output like
```
gitpod /workspace/gitpod/dev/gpctl (main) $ go run main.go workspaces last-heartbeat 3191e531-2c7c-42e5-8f28-57ab47fd33f9
2022-07-08T09:21:09.103544311Z
```
```release-note
NONE
```
=> [gpctl] add command to get last heartbeat time of workspace

components/ws-proxy/pkg/proxy/routes.go
Remove the port number from "X-Forwarded-Host" header as it's already defined in "X-Forwarded-Port".
This is a [suggestion](https://github.com/gitpod-io/gitpod/pull/11110#issuecomment-1179524427) from @ChakshuGautam, and it seems correct to don't have a port there.
- https://github.com/gitpod-io/gitpod/pull/11110
- Open a workspace on the Preview Environment of this PR.
- Run `curl lama.sh | sh`
- Run `gp preview $(gp url 8080) --external` to open a browser.
- Confirm you see, in the terminal logs of the request, the "X-Forwarded-Host" and "X-Forwarded-Port" headers. The first should have only the host and the second, only the port.
```release-note
Requests on ws-proxy won't contain the port anymore on the "X-Forwarded-Host" header. It will contain only the host. If you need the port, you …
```
=> [ws-proxy] Remove the port number from "X-Forwarded-Host" header as it's already defined in "X-Forwarded-Port"

operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
Around the time Build one first reported this issue (see [internal](https://gitpod.slack.com/archives/C03145ZD98D/p1657005586660919)) at around 9:15 AM European central Time 7:15 UCT the
`gitpod_workspace_regular_not_active_percentage` was quite high around 0.9 as can be seen from the picture (it got it's peak at 7AM which was still 0.135). So we definitely do need to reduce the `0.15` value we specify in the prom rule. I propose we set this to `0.10`
Now the second thing is, even at this hour, our total active workspaces were much lower, and out alert to go off we have set a limit of `100`. This needs to be reduced too. I propose we eliminate this condition to get alerted if the percentage of inactive workspaces get high enough.
According to the trend I see, the inactivity period would …
=> Improve  "GitpodWorkspaceTooManyRegularNotActive" alert

components/common-go/baseserver/config.go, install/installer/pkg/components/usage/configmap_test.go
Add an `omitempty` struct tag to the `TLS` field in the baseserver config. This makes it slightly easier to write tests against.
See [this comment](https://github.com/gitpod-io/gitpod/pull/11224#discussion_r916627199) on https://github.com/gitpod-io/gitpod/pull/11224
```release-note
NONE
```
/hold
=> Use `omitempty` struct tag in baseserver config

components/server/src/projects/projects-service.ts, components/server/src/workspace/gitpod-server-impl.ts
Moves the tracking call for `project_created` to `projects-service.ts` in order to have access and use the project's ID.
1. Open a preview environment, sign up, and create a project
2. Go to the [debugger of Staging Untrusted](https://app.segment.com/gitpod/sources/staging_untrusted/debugger) and ensure that a `project_created` call was fired and that it contains the project's ID as one of its properties
```release-note
NONE
```
=> [Analytics] move "project_created" call to projects-service.ts and add project ID

components/dashboard/src/App.tsx, components/dashboard/src/Menu.tsx, components/dashboard/src/teams/TeamBilling.tsx, components/dashboard/src/teams/TeamSettings.tsx, components/dashboard/src/teams/TeamUsage.tsx, components/gitpod-protocol/src/gitpod-service.ts, components/gitpod-protocol/src/usage.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
Skateboard of table of billable sessions with dummy data behind a feature flag.
We didn't have a design for this skateboard table (which will be updated according to the actual design), so the view here was my decision based on a combination of [this](https://gitpod.slack.com/archives/C01KPEPQYE6/p1657289918794709?thread_ts=1657137000.465299&cid=C01KPEPQYE6) and what dummy data we agreed on.
Fixes #11257 
I didn't list #10328 because this is only a skateboard of it - so I added this PR as a task under it.
1. Join team "Gitpod" with this [link](https://laushinka-7c7be98297.preview.gitpod-dev.com/teams/join?inviteId=d0842f9c-4a3a-48d0-b234-9453fd3afd80).
2. Create any team.
3. Go to the team's Settings.
4. Click on "Usage".
```release-note
Users can see their billable sessions.
```
=> Implement skateboard Usage view with dummy data

install/preview/prettylog/main.go
Currently, It takes a while before Gitpod is ready even though
the status says `Gitpod is running` as its not checking for
readyness.
This PR updates the output to separate btw `starting` and `running`.
`Gitpod is running` message is showed only when we see that
the `gitpod-telemetry-init` job has run which happens when
all pods are ready.
Fixes https://github.com/gitpod-io/gitpod/issues/11259
```release-note
[local-preview] Differentiate btw Gitpod `starting` and `running`
```
=> [local-preview] Differentiate btw Gitpod `starting` and `running`

components/common-go/baseserver/config.go, components/usage/BUILD.yaml, components/usage/config.json, components/usage/go.mod, components/usage/go.sum, components/usage/pkg/apiv1/usage.go, components/usage/pkg/server/server.go, install/installer/pkg/components/usage/configmap.go, install/installer/pkg/components/usage/configmap_test.go, install/installer/pkg/components/usage/constants.go, install/installer/pkg/components/usage/networkpolicy.go, install/installer/pkg/components/usage/objects.go, install/installer/pkg/components/usage/objects_test.go, install/installer/pkg/components/usage/service.go
https://github.com/gitpod-io/gitpod/pull/11221 added the `.proto` definitions for a placeholder gRPC API for the `usage` component. 
This PR implements the server side of that placeholder API.
Also updates the installer to deploy config for the `usage` component so that it serves gRPC and adds a k8s service through which it can be accessed.
Fixes https://github.com/gitpod-io/gitpod/issues/10324
*  Run the `usage` service locally:
```
cd components/usage
leeway build .:init-testdb
DB_USERNAME=gitpod DB_PORT=23306 DB_PASSWORD=test go run . run
```
* Access the gRPC API (using [evans](https://github.com/ktr0731/evans/releases)):
```
evans -p 9001 -r repl
> package usage.v1
> show services
```
The placeholder API is shown:
```release-note
NONE
```
/hold
=> [usage] Implement initial gRPC API 

components/server/src/prometheus-metrics.ts
Because we don't have enough precision where it matters
Fixes #
```release-note
NONE
```
NONE
=> [server] Reduce gitpod_server_api_calls_duration_seconds precision, add 2 buckets

components/ee/db-sync/src/export.ts
Escape column names in backquotes when `db-sync` generates `UPDATE` statements.
This ensures that `db-sync` is able to generate these statements for tables having SQL keywords as column names.
Fixes https://github.com/gitpod-io/gitpod/issues/11265
Take the `db-sync` image built on this branch and hot-patch the `db-sync` image running in staging. See that `db-sync` runs without error in staging.
```release-note
NONE
```
=> [db-sync] Escape column name in UPDATE statement

WORKSPACE.yaml
Updates stable VS Code Web to 1.69.0 with 
- https://github.com/gitpod-io/openvscode-server/pull/379 picked
Fixes #
See How to Test section in https://github.com/gitpod-io/openvscode-server/pull/379
```release-note
NONE
```
=> [code] build stable image for 1.69.0 with ports onOpen fix

install/preview/entrypoint.sh, install/preview/manifests/coredns.yaml
Due to the way docker works in non-native platforms, It is
very hard to have a consistent experience across all platforms
as we can't just use the [docker bridge netwrok IP's in non-native
platforms](https://docs.docker.com/desktop/networking/). This means that users have to search 
their Host IP, and use It to get up and working  
[which we tried, but understand that it's not a good UX](https://github.com/gitpod-io/website/pull/2349).
But users can use `127-0-0-1.nip.io` as the DOMAIN which resolves to
`127.0.0.1` and is available in all platforms as its `localhost`. This
works well and good for all user communication
but internal communication fails as `127-0-0-1.nip.io` for them
is something else.
So, This PR fixes that by adding new coredns `gitpod.db` coredns
config essentially …
=> [local-preview] Support `127-0-0-1.nip.io` for `DOMAIN`

components/usage/pkg/controller/reporter.go
Because default buckets are too low for us to measure this.
Fixes #
```release-note
NONE
```
=> [usage] Set reconcile duration buckets to 30s, up to 300s

components/usage/pkg/controller/billing.go, components/usage/pkg/controller/reconciler.go
To ensure that metrics reported also capture the error
Fixes #
```release-note
NONE
```
NONE
=> [usage] Billing controller returns an error

.werft/k3s-installer-tests.yaml
The k3s YAML file unfortunately got badly commit conflict resolved. This is a tiny PR that fixes the syntax.
Fixes #
```
werft run github -j .werft/k3s-installer-tests.yaml
```
```release-note
NONE
```
=> [installer-tests] Fix the k3s installer tests YAML

components/gitpod-protocol/src/experiments/configcat-server.ts, components/gitpod-protocol/src/experiments/configcat.ts, components/gitpod-protocol/src/experiments/types.ts, components/image-builder-api/typescript/src/sugar.ts, components/server/src/container-module.ts, components/server/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/image-source-provider.ts, components/server/src/workspace/workspace-cluster-imagebuilder-client-provider.ts, components/server/src/workspace/workspace-starter.ts, components/ws-manager-api/typescript/src/client-provider.ts, components/ws-manager-bridge/src/cluster-service-server.ts, components/ws-manager-bridge/src/cluster-sync-service.ts
This is part II of a translation from [Chris' PR](https://github.com/gitpod-io/gitpod/pull/9337). To be able to move forward with this, it got split into two:
1. The deprecation of the old log retrieval mechanism in [this PR](https://github.com/gitpod-io/gitpod/pull/11026) (feature flag: "deprecateOldImageLogsMechanism")
2. Make `server` talk to `ws-manager` for image builds (this PR) (feature flag: "movedImageBuilder")
The idea is to get both merged, and be able to test and iterate independently.
/cc @kylos101 
**Note 1**: All formatting should be in commit 1, so it's sufficient to review commit 2 alone.
**Note 2**: Commit 3 + 4 do not strictly belong into this PR but I left them here because they ease testing. :lotus_position: 
Fixes #9248
Context: #9337
- [preview …
=> [server] Use image-builder from workspace cluster (feature flag: "movedImageBuilder")

components/dashboard/src/App.tsx, components/dashboard/src/Menu.tsx, components/dashboard/src/admin/BlockedRepositorySettings.tsx, components/dashboard/src/admin/License.tsx, components/dashboard/src/admin/PageWithAdminSubMenu.tsx, components/dashboard/src/admin/ProjectsSearch.tsx, components/dashboard/src/admin/Settings.tsx, components/dashboard/src/admin/TeamsSearch.tsx, components/dashboard/src/admin/UserDetail.tsx, components/dashboard/src/admin/UserSearch.tsx, components/dashboard/src/admin/WorkspacesSearch.tsx, components/dashboard/src/admin/admin-menu.ts, components/dashboard/src/components/PageWithSubMenu.tsx, components/dashboard/src/contexts/FeatureFlagContext.tsx, components/dashboard/src/index.tsx
Add a feature-flagged entry in the admin sidebar that will show a placeholder blocked repositories admin UI.
The feature flag is enabled for non-production environments (ie preview and staging).
Part of #11030 
Start the preview environment and see the new `Repositories` menu item in the `Admin` menu:
The link takes you to an empty placeholder page:
```release-note
NONE
```
=> Add feature flag for blocked repositories UI

.gitpod.yml, dev/preview/previewctl/cmd/install_context.go, dev/preview/previewctl/pkg/k8s/vm.go, dev/preview/previewctl/pkg/preview/preview.go
This PR implements the `--watch` option and uses it in `.gitpod.yaml`. I considered the following requirements:
- It should deal with users changing branches
- It should deal with users using "with-clean-slate-deployment"; that is, it should re-install the kubectx if the underlying VM is recreated.
This changes the behaviour of "--watch" so that it runs forever and polls the current branch and VM periodically to see if a new preview environment context should be installed.
If we wanted to avoid polling could've created a channel for changes to the preview environment. For changes to the VM we could (I think) have used an Informer. Branch changes would be a bit more tricky though but might be achievable using a git hook that sends a signal to the process. Or if the current branch is stored …
=> Keep preview environment context in sync

.werft/util/certs.ts
Specify the KUBECONFIG in the cmctl command
```release-note
NONE
```
=> Specify the KUBECONFIG var in the cmctl command

components/gitpod-protocol/src/attribution.ts, components/gitpod-protocol/src/protocol.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/resource-access.spec.ts, components/server/src/auth/resource-access.ts, components/server/src/user/user-service.ts
Context: #10325 
- `(cd components/server && yarn test)`
```release-note
NONE
```
=> [server, protocol] GuardedCostCenter and AttributionId.parse/render (3/5)

components/workspacekit/pkg/readarg/readarg.go
This PR fix some edge case when workspace run mount, in ubuntu base system, if you run `mount --make-rshared /` the filesystem is NULL point, so if you want read string from NULL it will failed
Fixes #11299 
1. start a workspace
2. run `docker run -it --rm --privileged ubuntu` start a container
3. run `mount --make-rshared /` in container
```release-note
NONE
```
=> [workspacekit] fix mount when use ubuntu docker image

WORKSPACE.yaml
Update code to `1.69.1`
```release-note
NONE
```
=> [code] Generate stable image for 1.69.1

install/installer/pkg/components/workspace/ide/constants.go
Updates stable VS Code version to 1.69.1.
Part of https://github.com/gitpod-io/gitpod/issues/10990
Switch to stable in the preview environment and in the about dialog confirm you are running 1.69.1
```release-note
NONE
```
=> [code] Update stable to 1.69.1

install/installer/pkg/components/ws-proxy/configmap.go, install/installer/pkg/config/v1/experimental/experimental.go
Improve configmap generation for SaaS
Related https://github.com/gitpod-io/gitpod/issues/10418
```release-note
none
```
=> [installer] improve ws-proxy configmap

.werft/jobs/build/installer/installer.ts, components/usage/config.json, components/usage/pkg/server/server.go, install/installer/pkg/components/usage/configmap.go, install/installer/pkg/config/v1/experimental/experimental.go
Provide config to usage component about how to price each workspace class
Fixes #
1. Run the build directly, as it changes werft config `werft run github -j .werft/build.yaml -f`
2. Check the pod started
3. Check pod logs and validate you're seeing 
```
{"config":{"controllerSchedule":"1h0m0s","creditsPerMinuteByWorkspaceClass":{"default":0.1666666667,"gitpodio-internal-xl":0.3333333333},"server":{"services":{"grpc":{"address":":9001"}}}},"level":"info","message":"Starting usage component.","serviceContext":{"service":"usage","version":"commit-5201aba69e22b07e3d75e0181e19f7711ed987e3"},"severity":"INFO","time":"2022-07-11T08:53:29Z"}
```
```release-note
NONE
```
=> [usage] Workspace Pricer uses config

install/kots/manifests/kots-app.yaml
Adds default monitoring graphs to the [KOTS Graphs](https://docs.replicated.com/reference/custom-resource-application#graphs) section of the app config. This allows users to connect to their own Prometheus instance and for the Gitpod instance to give out simple graphs. The graphs are based upon the published graphs in our [monitoring docs](https://www.gitpod.io/docs/self-hosted/latest/monitoring).
**NB** we have limited (documented) control over the Y axis, so we end up with negative time periods by default. My feeling is that this is a convenience inside the KOTS dashboard and that, ultimately, most people will use Grafana over this. However, this should remain as a convenience for those who want a limited monitoring solution over a full-blown Grafana instance.
Install a Prometheus …
=> [kots]: add monitoring graphs

install/kots/manifests/kots-preflight.yaml
Applies tests on the CPU/memory to the workspace nodes only. Our [requirements](https://www.gitpod.io/docs/self-hosted/latest/cluster-set-up) only stipulate the performance of these nodes, not all the nodes in the cluster.
This also changes the wording for the CPU tests to change "cluster" to "node" (a remnant of when we had the tests on a cluster basis).
Fixes #9307
Run the preflight checks
```release-note
[kots]: add node CPU/memory check tests to workspace node only
```
=> [kots]: add node CPU/memory check tests to workspace node only

components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/GitpodServerLauncher.java, components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/testclient/TestClient.java, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt
Clean code from GitpodServerLauncher and update JetBrains backend-plugin to work when the user has proxies.
This reverts the hotfix from https://github.com/gitpod-io/gitpod/pull/11232 and passes a default `SslContextFactory` to `HttpClient`, which the root cause of the issue https://github.com/gitpod-io/gitpod/issues/11228. For reference, this is the error message the server was triggering:
```
java.lang.IllegalStateException: HttpClient has no SslContextFactory, wss:// URI's are not supported in this configuration
at io.gitpod.gitpodprotocol.api.GitpodServerLauncher.listen
```
Resolves #11291
- Open https://felladrin-11291.preview.gitpod-dev.com/#referrer:jetbrains-gateway:intellij/https://github.com/gitpod-io/empty
- Get the instance of the workspace by running `env | grep …
=> Clean code from GitpodServerLauncher and update JetBrains backend-plugin to work when user has proxies

components/server/src/oauth-server/db.ts
Add `function:sendHeartBeat` scope for vscode clients
```release-note
NONE
```
=> Add `function:sendHeartBeat` scope

install/preview/entrypoint.sh, install/preview/prettylog/main.go
This PR updates the `local-preview` to printout
the Domain of the Gitpod Instance for users to
access.
Part of #11316 
```bash
docker run -p 443:443 --privileged --name gitpod --rm -it -v gitpod:/var/gitpod eu.gcr.io/gitpod-core-dev/build/local-preview:tar-local-preview-domain.0
```
```release-note
[local-preview] show `DOMAIN` in the output
```
=> [local-preview] show `DOMAIN` in the output

.werft/workspace-run-integration-tests.yaml
Search the job with `with-preview` annotation.
Fixes #
```release-note
None
```
None
=> Enhance workspace integration test

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup-jetbrains.yaml, .werft/ide-integration-tests-startup-vscode.yaml, .werft/ide-run-integration-tests.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/run-integration-tests.yaml, .werft/self-hosted-installer-tests.yaml, .werft/wipe-devstaging.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile
- Update go to v1.18.4 https://groups.google.com/g/golang-announce/c/nqrv9fbR0zE
- Update google-cloud-sdk to v393.0.0 
```release-note
NONE
```
=> Update dev-environment image

.werft/build.yaml, .werft/debug.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup-jetbrains.yaml, .werft/ide-integration-tests-startup-vscode.yaml, .werft/jobs/build/self-hosted-upgrade-tests.ts, .werft/jobs/build/trigger-integration-tests.ts, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/workspace-run-integration-tests.yaml, dev/preview/werft-credential-helper.sh
This updates the `werft-credential-helper.sh` script so that it works outside of workspaces and updates all the Werft jobs that use the Werft CLI to set the required environment variable `WERFT_GITHUB_TOKEN_PATH`. It also sets `WERFT_CREDENTIAL_HELPER` as the value that is set in the Dockerfile uses `/workspace/gitpod` as that is where the repository is cloned in workspaces, but in Werft it's in `/workspace`.
This is prerequisite to requiring authentication when using the Werft CLI.
Places where we use the CLI to trigger other jobs:
- https://github.com/gitpod-io/gitpod/blob/ac58e182c2e7a985e1dee78deba03e07c405ecaa/.werft/jobs/build/trigger-integration-tests.ts#L39
- https://github.com/gitpod-io/gitpod/blob/b05b848db227f07e1dc2b5180a627dcc0c9edf38/.werft/jobs/build/self-hosted-upgrade-test …
=> Extend werft-credential-helper to work outside of workspaces and update jobs

components/ws-daemon/pkg/content/service.go
(This PR is stacked on top of https://github.com/gitpod-io/gitpod/pull/11330, please review commit: https://github.com/gitpod-io/gitpod/commit/8d2d1c6d686a03efb2be274fb3831f534fbf8ded)
Some workspaces fail with `cannot get git status`, which is not a critical error.
Observed in some cases it failed due to potentially corrupt\misconfigured .git folder (potentially due to user's actions).
This PR would make it so that we don't fail workspace when this happens and instead continue disposing it.
For example, we already do that if workspace folder does not contain .git folder in it:
https://github.com/gitpod-io/gitpod/blob/905be0afd12bc43d348591225727ae5c3181982a/components/ws-daemon/pkg/internal/session/workspace.go#L309-L312
Main reasoning is that even if we cannot get git status, all that …
=> [ws-daemon] do not fail workspace if git status failed during dispose 

components/server/src/bitbucket/bitbucket-repository-provider.spec.ts, components/server/src/bitbucket/bitbucket-repository-provider.ts
As described in #11190 this PR implements the missing BitbucketRepositoryProvider.hasReadAccess
Fixes #11190
Note, those tests are not executed in werft. One need to drive them manually.
* grab an OAuth2 token for bitbucket.org and set it in you env using this command:
```
export GITPOD_TEST_TOKEN_BITBUCKET='{ "value": "FOOBAR=", "username": "x-token-auth", "scopes": []  }'
```
* run test 
```
yarn mocha --opts mocha.opts /workspace/gitpod/components/server/src/bitbucket/bitbucket-repository-provider.spec.ts
```
```release-note
NONE
```
=> Implement hasReadAccess for Bitbucket

.werft/jobs/build/deploy-to-preview-environment.ts, .werft/jobs/build/prepare.ts, .werft/util/certs.ts
Refactor the way we create and wait for certs.
These changes should lead to:
- Less failures, as we retry and wait 5 times
- Earlier failures, as we fail out before we start deploying things
```release-note
NONE
```
=> Refactor cert to create and wait in the background

components/gitpod-db/src/typeorm/entity/db-workspace-instance-usage.ts, components/gitpod-db/src/typeorm/migration/1657722262390-RenameWorkspaceIdColumn.ts, components/usage/pkg/controller/reconciler.go, components/usage/pkg/db/workspace_instance_usage.go, components/usage/pkg/db/workspace_instance_usage_test.go
Change the name of the `workspaceId` column to `instanceId` in the `d_b_workspace_instance_usage` table as that's what it stores.
As there is no production data in this table the migration is simply to drop the table and recreate it.
/hold because this is based on https://github.com/gitpod-io/gitpod/pull/11343.
Part of https://github.com/gitpod-io/gitpod/issues/10323
Connecting to the database in the preview env for this PR shows the table with the correct column name.
```release-note
NONE
```
=> [usage] Rename misnamed column in usage table

.werft/jobs/build/prepare.ts, .werft/util/certs.ts
Adds a namespace flag to the `cmctl` debug command on cert failure
```release-note
NONE
```
=> Add namespace flag to cert debug command

.werft/util/certs.ts
Fix the loop to not be infinite
```release-note
NONE
```
=> Fix cert loop

.werft/util/certs.ts
Fix the cert check to be true for Ready
```release-note
NONE
```
=> Fix the check cert function

components/gitpod-db/src/typeorm/entity/db-workspace-instance-usage.ts, components/gitpod-db/src/typeorm/migration/1657722262390-RenameWorkspaceIdColumn.ts, components/usage/pkg/controller/reconciler.go, components/usage/pkg/controller/reconciler_test.go, components/usage/pkg/db/workspace_instance_usage.go, components/usage/pkg/db/workspace_instance_usage_test.go
Store the usage report in the database table created in #11311 whenever usage reconciliation runs.
⚠️ This PR does not yet populate the `creditsUsed` or `generationId` fields ⚠️ 
Part of #10323 
Run the usage component against the database in this PR's preview environment:
* Port forward to the database in the preview env
* Edit the local config `components/usage/config.json` for the usage controller to run every 10s.
* Run the usage component:
```bash
DB_USERNAME=gitpod DB_PASSWORD=<> DB_HOST=localhost DB_PORT=3306 go run . run
```
(get the password from `server` environment)
* Wait a while for reconciliation to run a couple of times.
* Connect to the port-forwarded database with eg `mycli` and observe the data in `d_b_workspace_instance_usage`.
Unit tests.
```release-note
NONE
```
=> [usage] Persist usage reports in database

components/ws-manager/pkg/manager/monitor.go, components/ws-manager/pkg/manager/monitor_test.go, install/installer/pkg/components/ws-manager/role.go
When the node goes NotReady, the workspace Pod goes into a Terminating state.
In this case, the workspace Pod `status.containerStatuses.state` is still `Running`.
We should try to backup the workspace content if the Pod is Terminating and the underlying node is not ready or even gone.
This is the node taint if the node turns into a NotReady state.
This is the current workspace Pod spec.toleration
Therefore, for the cases
- `node.kubernetes.io/disk-pressure` and `node.kubernetes.io/memory-pressure`: the workspace Pod keeps in tolerance indefinitely. -> We would not handle this case because the tolerance second is not configured.
- `node.kubernetes.io/network-unavailable`: the workspace Pod tolerance duration is 30 seconds. -> We handle this case
- `node.kubernetes.io/not-ready` and …
=> Call finalizeWorkspaceContent if the workspace Pod in Terminating

components/content-service/pkg/initializer/prebuild.go
Avoiding issues with files included in the prebuild that could be owned by a different issue (permission issues).
Fixes https://github.com/gitpod-io/gitpod/issues/10953
- Open a workspace using https://github.com/aledbf/supervisor-bug
- Check the directory letsencrypt exists and the file acme.json is owned by root
```release-note
NONE
```
=> [content-service] Do not stash untracked files

components/ws-daemon/pkg/content/service.go
Now that we have better performance, we can increase the concurrency.
```release-note
NONE
```
=> [ws-daemon] Increase number of concurrent backup uploads

components/content-service/pkg/git/git_test.go
Fixes https://werft.gitpod-dev.com/job/gitpod-build-main.3905
```release-note
NONE
```
=> [content-service] Fix TestGitStatusFromFiles test

components/supervisor/pkg/supervisor/supervisor.go
Ensure we close the content file and avoid [redeclaring `err` variable](https://go.dev/ref/spec#Short_variable_declarations) (used in [defer](https://github.com/gitpod-io/gitpod/blob/1882d6692663fa82775de1761f261c546bd2aed9/components/supervisor/pkg/supervisor/supervisor.go#L1310))
```release-note
NONE
```
=> [supervisor] Refactor content-init error handling

components/gitpod-db/src/container-module.ts, components/gitpod-db/src/index.ts, components/gitpod-db/src/typeorm/entity/db-webhook-event.ts, components/gitpod-db/src/typeorm/migration/1657702361007-AddWebhookEvent.ts, components/gitpod-db/src/typeorm/webhook-event-db-impl.ts, components/gitpod-db/src/webhook-event-db.spec.db.ts, components/gitpod-db/src/webhook-event-db.ts, components/gitpod-protocol/src/index.ts, components/gitpod-protocol/src/webhook-event.ts, components/server/ee/src/prebuilds/bitbucket-app.ts, components/server/ee/src/prebuilds/bitbucket-server-app.ts, components/server/ee/src/prebuilds/github-app.ts, components/server/ee/src/prebuilds/github-enterprise-app.ts, components/server/ee/src/prebuilds/gitlab-app.ts
This PR adds recording of webhook events received for GH/GHE/GL/BB/BBS.
For each `push` event received for any configured repositories, a record will be stored in the DB containing the raw payload necessary to trigger a prebuild at any time. To start with a 🛹, the actual trigger remains untouched here, only the status is updated up the the point of a successful prebuild trigger (or any error case.) The status updates will be already beneficial in the follow up PR to render updates on the dashboard.
The proposed DB table is quite simple. 
```
mysql> describe d_b_webhook_event;
+------------------+--------------+------+-----+----------------------+--------------------------------+
| Field            | Type         | Null | Key | Default              | Extra                          | …
```
=> Record webhook events

components/gitpod-protocol/src/workspace-cluster.ts, components/server/src/workspace/workspace-starter.ts, components/ws-manager-api/typescript/src/client-provider.spec.ts, components/ws-manager-api/typescript/src/constraints.ts, components/ws-manager-bridge-api/cluster-service.proto, components/ws-manager-bridge/src/cluster-service-server.ts, dev/gpctl/cmd/clusters-update.go
This PR removes the `has-more-resources` admission constraint. We have since started using workspace classes for this functionality, hence clean up this bit of code.
This PR is part of a stack of changes:
- https://github.com/gitpod-io/gitpod/pull/11383
- ➡️ https://github.com/gitpod-io/gitpod/pull/11384
- https://github.com/gitpod-io/gitpod/pull/11385
There should be no functional changes due to this removal.
```release-notes
NONE
```
=> [ws-manager-bridge] Remove HasMoreResources admission constraint

components/dashboard/src/App.tsx, components/dashboard/src/projects/Events.tsx, components/gitpod-protocol/src/gitpod-service.ts, components/gitpod-protocol/src/teams-projects-protocol.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/projects/projects-service.ts, components/server/src/workspace/gitpod-server-impl.ts
Related https://github.com/gitpod-io/gitpod/issues/10764
1. Verify you do not see "Prebuild Events" in the menu, as this is a 🛹  PR without any discussions about proper UI design.
2. Push a commit to a repository configured as a project with this preview environment and verify you see webhook events rendered on: https://at-prebuild-events.preview.gitpod-dev.com/projects/YOUR-PROJECT/events
```release-note
NONE
```
=> Simple UI for Prebuild Events (sneak preview)

install/installer/pkg/components/ws-manager/role.go
We missed the add `watch` node clusterrole permission to ws-manager.
We missed adding the watch node permission in PR #11337.
```release-note
None
```
None
=> Add missing permission to watch node object

components/usage/pkg/controller/billing.go, components/usage/pkg/controller/reconciler.go, components/usage/pkg/controller/reconciler_test.go, components/usage/pkg/server/server.go
Calculate and persist credits used for each instance in the usage store. 
On each usage reconciliation run, we store the reconciled usage in the database. This information should include the number of credits consumed by each instance.
Previously, this value was set to 0 for all instances.
Part of https://github.com/gitpod-io/gitpod/issues/10323
Unit tests.
To test manually, run the usage component locally against the database from a preview environment that has had at least one workspace started in it. When the reconciler runs, see that the value for `creditsUsed` is populated in the `d_b_workspace_instance_usage` table:
```release-note
NONE
```
=> [usage] Persist credits used for each instance in the usage store

components/ws-manager/pkg/manager/status.go, components/ws-manager/pkg/manager/testdata/status_containerd4214_STOPPING00.golden, components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED01.golden, components/ws-manager/pkg/manager/testdata/status_disposal_STOPPING02.golden
Do not clear up any failed state, as that will trip server in thinking that workspace has not failed, when in reality it did.
Which in turn causes subsequent workspace start to fail as server will instruct to restore workspace from backup.
Fixes https://github.com/gitpod-io/gitpod/issues/10315
```release-note
none
```
=> [ws-manager] do not overwrite failed state

operations/observability/mixins/workspace/rules/components/nodes/alerts.libsonnet
[alerts] change alert for adding new nodes rapidly to only count if node type is regular workspace
Fixes #
```release-note
NONE
```
=> [alerts] change alert for adding new nodes rapidly to only count if node type is regular workspace

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup-jetbrains.yaml, .werft/ide-integration-tests-startup-vscode.yaml, .werft/ide-run-integration-tests.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/run-integration-tests.yaml, .werft/self-hosted-installer-tests.yaml, .werft/wipe-devstaging.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile
Add [evans](https://github.com/ktr0731/evans) to the dev image.
`evans` is a general purpose gRPC client. 
It's useful for working with, for example, the public api and the new usage API for [usage based billing](https://github.com/gitpod-io/gitpod/issues/9036).
Also remove some observability tool archive files that were left lying around the home directory during the image build process.
```release-note
NONE
```
=> [dev] Install `evans` into dev image and tidy up home directory

components/ws-manager/pkg/manager/status.go, components/ws-manager/pkg/manager/testdata/status_containerd4214_STOPPING00.golden, components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED01.golden, components/ws-manager/pkg/manager/testdata/status_disposal_STOPPING02.golden
This reverts #11419 because it causes all normally closed workspaces to report error `container workspace completed; containers of a workspace pod are not supposed to do that. Reason:`
Fixes #
1. start a workspace in preview environment
2. stop it
3. should not show an error
```release-note
NONE
```
=> Revert "[ws-manager] do not overwrite failed state"

components/server/package.json, components/server/src/auth/auth-provider-service.ts, components/server/src/workspace/gitpod-server-impl.ts, yarn.lock
This PR removes a conservative host name validation using a plain regex. Instead we test and report if the host (optionally with port) is reachable.
Improves the situation around #5305
Try configuring and using a Git Provider which is listening on a port other than the default 443, thus requires to specify a port. 
```release-note
Test if host of a Git Integration is reachable.
```
=> Test if auth host is reachable

.werft/util/certs.ts
Fixes cert logic to correctly return the debug from the commands
```release-note
NONE
```
=> Fix cert exec commands to correctly return debug

1658144661198-WorkspaceInstanceUsageAddExtraFields.ts, components/gitpod-db/src/typeorm/entity/db-workspace-instance-usage.ts
Adds extra fields to workspace instance usage such that we can perform common groupings easily
Fixes #
Preview 
```release-note
NONE
```
=> [usage] Store user, project, workspace, type & class + migration

components/usage/pkg/controller/billing.go, components/usage/pkg/controller/billing_test.go, components/usage/pkg/controller/reconciler.go
Per instance, we want to work with fractional credits and only round the total for a team when we submit usage reports to stripe.
Part of #9036 
Unit tests
```release-note
NONE
```
=> [usage] Use floating point values to hold instance credit usage

operations/observability/mixins/platform/dashboards/preview-environments/overview.json
Updates our dashboard with the new metrics from HTTP-prober
```release-note
NONE
```
=> Update Preview env's dashboard with new metrics

components/ws-manager/pkg/manager/manager.go, components/ws-manager/pkg/manager/monitor.go
We add an event to the workspace Pod in #10889 for the take volume snapshot operation (InProgress, ReadyToUse).
In this PR, we add an event to the workspace Pod when the PVC is restored from the VolumeSnapshot.
Hence, we would know the workspace Pod PVC is restored from the VolumeSnapshot or not.
Fixes #10887
1. Create a preview environment and enable the feature flag `persistent_volume_claim`.
2. Launch a workspace
3. Describe the workspace pod, and the event message should matches
```console
Events:
Type    Reason                  Age   From                     Message
----    ------                  ----  ----                     -------
Normal  PersistentVolumeClaim   19s   ws-manager               PVC "<pvd-name>" created successfully
```
4.  and write a large data into it. …
=> [ws-manager] Add event to workspace Pod when the PVC restored from the VolumeSnapshot

components/common-go/kubernetes/kubernetes.go, components/ws-manager/pkg/manager/monitor.go
The annotation "gitpod.io/containerIsGone" is no more used. Removing it.
Fixes #
```release-note
None
```
None
=> Remove no more used annotation "gitpod.io/containerIsGone"

components/ws-daemon/pkg/cgroup/plugin_proc_limit_v2.go, components/ws-daemon/pkg/daemon/config.go, components/ws-daemon/pkg/daemon/daemon.go, install/installer/pkg/components/ws-daemon/configmap.go, install/installer/pkg/config/v1/experimental/experimental.go
Allow setting a limit to the number of processes inside a workspace. By default, we have none.
- Edit ws-daemon configmap and set `"procLimit": 512`
- Open a terminal and run `while true; do sleep 1 && date & done`
- Check you sporadically see `bash: fork: retry: Resource temporarily unavailable`
**
```release-note
Add support for limiting number of processes in workspaces
```
Note: testing this requires cgroups v2
=> [ws-daemon] Add support for limiting number of processes in workspaces

components/gitpod-db/src/tables.ts
Fixes missing events from the other cluster.
Follow-up to https://github.com/gitpod-io/gitpod/pull/11356
```release-note
NONE
```
=> Add mising db-sync config for d_b_webhook_event

.github/workflows/delete-kots-channel.yml
GitHub Action to delete a KOTS channel on branch deletion. This will cut down on the amount of manual work that @gitpod-io/engineering-self-hosted have to do in housekeeping in the Replicated vendor portal.
In most cases, this will actually do nothing. Most branches do not create a channel in Replicated - the only time is if a PR is run with `/werft run publish-to-kots` when it will publish to a channel with the same name as the branch. This Action exists to delete these channels when the branch is deleted.
If a channel has customers assigned to it, it will not delete the channel as the workflow is that channels must have zero customers before they can be deleted - that's a failsafe against customer channels such as `stable` or `enterprise` being deleted. Also, this Action can never error …
=> [kots]: delete channel on branch delete

WORKSPACE.yaml
Update code to `1.69.2`
https://github.com/microsoft/vscode/releases/tag/1.69.2
Prev env: https://afalz-upda5069630ad0.preview.gitpod-dev.com
Part of https://github.com/gitpod-io/gitpod/issues/10990
```release-note
NONE
```
=> [code] Generate stable image for 1.69.2

install/installer/cmd/render.go, install/installer/go.mod, install/installer/go.sum, install/installer/pkg/postprocess/postprocess.go, install/kots/manifests/gitpod-installation-status.yaml, install/kots/manifests/gitpod-installer-job.yaml
Adds the ability to post-process the Installer's YAML natively in the Golang binary. This extends the [YQ library](https://github.com/mikefarah/yq), so any valid [YQ expression](https://mikefarah.gitbook.io/yq/operators) can be used to amend the generated YAML.
It also removes the `status` object from both Network Policies and Stateful Sets, both of which are problematic when supporting multiple versions of Kubernetes.
This also removes the problems associated with upgrades to the Kubernetes libraries (eg #11003) and allows for #11177 to be merged.
Run the Installer, there should be no `status` in any `NetworkPolicy` or the OpenVSXProxy `StatefulSet` resources.
```release-note
[installer]: add in ability to post-process the generated YAML
```
=> [installer]: add in ability to post-process

components/usage/pkg/apiv1/usage.go, components/usage/pkg/controller/reconciler.go, components/usage/pkg/controller/reconciler_test.go, components/usage/pkg/db/dbtest/workspace.go, components/usage/pkg/db/workspace_instance.go, components/usage/pkg/db/workspace_instance_test.go, components/usage/pkg/db/workspace_instance_usage.go
1. Retrieve OwnerID and ProjectID when querying workspace instances (joined with Workspaces)
2. Populate fields from the retrieved WorksapceInstancesForUsage into the report
3. Store these in the DB
Fixes #
Unit tests
```release-note
NONE
```
=> [usage] Store workspace, project, type & class

components/common-go/experiments/configcat.go, components/common-go/experiments/flags.go, components/common-go/experiments/noop.go, components/common-go/experiments/types.go, components/common-go/experiments/types_test.go, components/common-go/go.mod, components/common-go/go.sum
Implement experiments Client abstraction in golang. This largely follows the same format as the server/dashboard version.
To use the client, the environment must have the SDK key set, otherwise returns a client which always returns a default value.
Thanks to @Furisto who started the implementation!
Fixes #
```release-note
NONE
```
=> [common-go] Add experiments client & ConfigCat implementation

components/ws-proxy/pkg/sshproxy/server.go
[ssh-gateway] Reject ssh connection when workspace not found
For reviewer: In general, the SSH authentication process is as follows
`NoClientAuthCallback` -> `PublicKeyCallback(if private key provider)` -> `PasswordCallback`
there are 2 special error type
1. `ssh.ErrNoAuth` This Error only exists in the `NoClientAuthCallback`, which means that this callback is skipped and not counted as attempts
2. `ssh.ErrDenied` This Error means that retries are no longer allowed and the validation process is complete.
All error created by `NewSSHErrorWithReject` is base on `ssh.ErrDenied`
The new authentication process is simple than before
`NoClientAuthCallback` responsible for checking if workspace exists, if not, close the connection, if it does, determine if the username is in the form of …
=> [ssh-gateway] Reject ssh connection when workspace not found

install/installer/pkg/components/workspace/ide/constants.go
Updates stable VS Code version to 1.69.2.
Using stable VS Code in [prev env](https://afalz-upda5069630ad0.preview.gitpod-dev.com), version is correct:
Part of https://github.com/gitpod-io/gitpod/issues/10990
Switch to stable in the preview environment and in the about dialog confirm you are running 1.69.2
```release-note
NONE
```
=> [code] Update stable to 1.69.2

operations/observability/mixins/workspace/dashboards.libsonnet, operations/observability/mixins/workspace/dashboards/node-swap.json
[Preview dashboard](https://grafana.gitpod.io/d/node-swap/gitpod-node-swap?orgId=1&refresh=1m)
```release-note
NONE
```
=> Add dashboard for swap utilization per cluster and node

components/gitpod-db/src/container-module.ts, components/gitpod-db/src/cost-center-db.ts, components/gitpod-db/src/index.ts, components/gitpod-db/src/tables.ts, components/gitpod-db/src/typeorm/cost-center-db-impl.ts, components/gitpod-db/src/typeorm/entity/db-cost-center.ts, components/gitpod-db/src/typeorm/migration/1658241900000-CostCenter.ts, components/gitpod-protocol/src/protocol.ts, components/server/src/user/user-service.ts
Implement a CostCenter entity to attribute workspace usage to.
Fixes https://github.com/gitpod-io/gitpod/issues/10757
```release-note
NONE
```
=> [db][protocol] Implement a CostCenter entity to attribute workspace usage to

components/dashboard/src/teams/TeamUsage.tsx, components/gitpod-protocol/src/usage.ts, components/server/ee/src/workspace/gitpod-server-impl.ts
Because it won't be set when the instance is still running.
Fixes #
```release-note
NONE
```
=> [usage] Make endTime non-mandatory for billed session

components/usage/pkg/controller/reconciler_test.go
Use variable instead of equivalent constant.
unit tests.
```release-note
NONE
```
=> [usage] Tiny fix to use variable rather than literal value in test

install/kots/manifests/kots-preflight.yaml
Add preflight checks to the IDE/meta nodes as per the requirements
Fixes #11347
Deploy via KOTS
```release-note
[kots]: add preflight checks for IDE/meta nodes
```
=> [kots]: add preflight checks for IDE/meta nodes

components/dashboard/src/teams/TeamUsage.tsx
to fix this issue
Fixes #
```release-note
NONE
```
=> [usage] Round credit & hours values in UI

components/usage/pkg/db/workspace_instance_usage.go, components/usage/pkg/db/workspace_instance_usage_test.go
Orders the results to ensure we get a stable view in the UI
Fixes #
unit 
```release-note
NONE
```
=> [usage] Ensure billed usage results are ordered

operations/observability/mixins/Makefile, operations/observability/mixins/components/bar_gauge_panel.libsonnet, operations/observability/mixins/cross-teams/dashboards/gitpod-overview.libsonnet
By default the new row is collapsed
```release-note
NONE
```
=> Add Summary row to Gitpod overview dashboard

components/ws-manager/pkg/manager/monitor.go
Fixes #11511 
```release-note
none
```
=> [ws-manager] fix not handling err in initializeWorkspaceContent

install/preview/entrypoint.sh, install/preview/leeway.Dockerfile
This PR removes the dependency of `cert-manager` and thus
reducing resource usage. This is replaced by the usage of
`mkcert` instead. 
Each certificate is induvidually generated on those domains
and stored into specific files for `k3s` to apply them which
is then used by Gitpod.
Part of #11303 
```release-note
[local-preview] Remove `cert-manager` dependency
```
=> [local-preview] Remove `cert-manager` dependency

components/dashboard/src/settings/Billing.tsx, components/gitpod-db/src/typeorm/migration/1658394096656-UsageAttributionId.ts, components/gitpod-protocol/src/gitpod-service.ts, components/gitpod-protocol/src/protocol.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/user/user-service.ts, components/server/src/workspace/gitpod-server-impl.ts
This PR implements validations for `setUsageAttribution` in `UserServer`.
Also `usageAttributionId` is moved to be a field of `User` entity.
A follow-up to https://github.com/gitpod-io/gitpod/pull/10893
```release-note
NONE
```
=> Move usageAttributionId

components/dashboard/src/teams/TeamUsageBasedBilling.tsx, components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
🛹  PR to configure spending limit on a team's Billing page.
This PR does not include setting unlimited spending on a team.
Partial fix for  #11401
Configure spending limit on the preview environment.
```release-note
Configure team's spending limit on its Billing page.
```
=> Add Spending Limit to Billing page

.github/workflows/jetbrains-updates-template.yml
Fixes the incorrect behavior described in https://github.com/gitpod-io/gitpod/pull/11496#issuecomment-1191220663.
Sadly, this can't be tested easily, **but** the way I tested is I tried using the GitHub API and when I didn't provide `gitpod-io/` it worked for requesting reviews.
```release-note
NONE
```
=> Fix team reviews in Jetbrains auto updates

.werft/jobs/build/self-hosted-upgrade-tests.ts
This PR temporarily disables integration tests during upgrade test pipeline. Since the main point of running these tests is to get a self-hosted preview of the upgraded version of Gitpod during release test, having the installation messed up due to integration tests cause problems. This PR disables the tests from this phase, assuming the crons run tests every night anyway we don't necessarily need this.
Fixes #
```release-note
NONE
```
=> [installer] Disable integration tests during upgrade tests

components/ide/jetbrains/gateway-plugin/README.md, components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt
Adjust the Workspace Start URL the in JetBrains Gateway workspaces list.
This is now aligned with the URL used in WebApp workspaces list.
It's aligned with the URL used in the workspaces list from Gitpod Dashboard:
https://github.com/gitpod-io/gitpod/blob/05ae248a7c4e2527dac6f23fab9ba89d9f3ac6b8/components/dashboard/src/workspaces/WorkspaceEntry.tsx#L56-L59
https://github.com/gitpod-io/gitpod/blob/05ae248a7c4e2527dac6f23fab9ba89d9f3ac6b8/components/dashboard/src/workspaces/WorkspaceEntry.tsx#L66-L69
Fixes #11284
- Follow the instructions from [how to test it from a Pull Request](https://github.com/gitpod-io/gitpod/blob/bebfb53a007d14269d8d9383073f7bf15d4dc49c/components/ide/jetbrains/gateway-plugin/README.md#how-to-test-from-a-pull-request).
- Check if when clicking the "Connect" button …
=> Adjust the Workspace Start URL the in JetBrains Gateway workspaces list

components/server/ee/src/prebuilds/github-enterprise-app.ts
[server] GH: Send 401 with message on failed webhook
Requested in a customer call
```release-note
NNE
```
=> [server] GH: Send 401 with message on failed webhook

components/usage/pkg/apiv1/usage.go, components/usage/pkg/apiv1/usage_test.go, components/usage/pkg/db/dbtest/workspace_instance_usage.go, components/usage/pkg/db/workspace_instance_usage.go, components/usage/pkg/db/workspace_instance_usage_test.go
Implements filtering of Usage records by time
* When range is not supplied, it takes now as the end, and fetches last 31 days
Fixes #
Unit tests
```release-note
NONE
```
=> [usage] ListUsage filters by time range

components/dashboard/src/teams/TeamUsage.tsx, components/gitpod-protocol/src/util/gitpod-host-url.ts
This handles the views when there is either no data or no access.
| NO DATA | NO ACCESS |
| - | - |
| <img width="448" alt="Screenshot 2022-07-22 at 10 20 28" src="https://user-images.githubusercontent.com/8015191/180396719-0193e7a6-c1d7-428d-a9f1-a77c95da61bd.png"> | <img width="293" alt="Screenshot 2022-07-22 at 11 00 04" src="https://user-images.githubusercontent.com/8015191/180404061-0c2457af-bfc6-4b22-8955-7e1edfa91c2b.png"> |
Fixes #11495
1. Join https://lau-usage-de27c2b151.preview.gitpod-dev.com/teams/join?inviteId=e3fe8d85-f7a8-4b83-b7b4-0d2d20bac787.
2. As member, you should see the "Please request access" message.
3. After that I can set you as owner, and then you'll see the "No sessions found" view.
```release-note
NONE
```
=> [UBP] View without data or access

components/ws-manager-api/typescript/src/promisified-client.ts, components/ws-manager/pkg/manager/manager.go
The call `startWorkspace` [here](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-api/typescript/src/promisified-client.ts#L111) uses a timeout of 30s that is not respected [here](https://github.com/gitpod-io/gitpod/blob/f25de2cdbf49f72f35be6313392160e92afd12e9/components/ws-manager/pkg/manager/manager.go#L142) and the consequence is that we never remove the annotation `gitpod.io/attemptingToCreate` and ws-daemon never creates the socket in the workspace. 
Similar to https://github.com/gitpod-io/gitpod/issues/11327
This is also the place that introduces the behavior of why some workspaces stay in `Preparing workspace …` and after a refresh, we can open the IDE.
With this change, we don't see the behavior in the workspace cluster, but we still require a refresh to open …
=> Refactor Manager StartWorkspace

components/dashboard/src/App.tsx, components/dashboard/src/AppNotifications.tsx, components/dashboard/src/components/Alert.tsx, components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
This PR add the basic notification to signal reaching of spending limits as described in https://github.com/gitpod-io/gitpod/issues/11404. The static message is provided by the server API.
**Screenshot** shows a notification when a spending limit of **1** is reached.
The notification is dismissible, but will reappear on reload until the condition is resolved. 
Relates to #11404
* setting up proper refresh rate for `usage` component
* setting up a spending limit on a team with billing enabled
* starting a workspace and waiting for the usage to reach 80% or more
* reloading the dashboard
```release-note
Notify when spending limit is reached.
```
=> Add spending limit notifications

.werft/util/certs.ts
Delete the certificate if it fails and recreate it. When certificate issues do occur, we want to fail immediately
```release-note
NONE
```
=> Add a delete rety and fail into the certificate issue function

components/ws-manager/pkg/manager/monitor.go
Address some of the issues found in logs https://cloudlogging.app.goo.gl/JFjbmUaMZiHCeBmW6
```release-note
NONE
```
=> [ws-manager] Only build snapshots of initialized/ready workspaces

install/infra/terraform/eks/kubernetes.tf
Currently, when using the EKS module, the `disk_size` field set doesn't change the value. This is because templates are getting created for both the node pools. To change the disk size in the template as well, we define `block_device_mappings` for both the managed node pools
Partly fixes #11533 (not to be closed)
Documentation task is still TODO for terraform modules.
```release-note
NONE
```
=> [terraform] update the disk size in eks module

components/ws-manager/pkg/manager/annotations.go, components/ws-manager/pkg/manager/monitor.go
Directly delete the workspace Pod and remove the finalizer before the VolumeSnapshot is ready, the VolumeSnapshot is created, and the workspace Pod is removed as well. However, the PVC does not be removed after that.
Partially #10531
1. Create a workspace-preview environment
2. Enable feature flag `persistent_volume_claim`.
3. Launch a workspace.
4. Manually delete the workspace pod `kubectl delete pod <pod-name>`.
5. Before the VolumeSnapshot is ready to use, remove the workspace pod finalizer `kubectl patch pod <pod-name> -p '{"metadata":{"finalizers":null}}' --type=merge`.
```release-note
None
```
None
=> Delete PVC once the VolumeSnapshot is ready to use

components/usage/pkg/db/workspace_instance_usage.go, components/usage/pkg/db/workspace_instance_usage_test.go
Before, the extra range filters would eventually be appended as top level OR, which would lead to returning results which didn't actually match the Attribution ID
Fixes #
Unit test
Test as a regression, remove the changes to the implementation and run the test
```release-note
NONE
```
=> [usage] Fix usage query

install/installer/pkg/components/registry-facade/daemonset.go
During a refactor the wrong component/version combination [got introduced](https://github.com/gitpod-io/gitpod/commit/316b4930575a22af53e15550e89e67d34cabb66e). The `/app/ready-probe-labeler` is present in the `registry-facade` image (cmp. [here](https://github.com/gitpod-io/gitpod/blob/316b4930575a22af53e15550e89e67d34cabb66e/components/registry-facade/leeway.Dockerfile#L14)).
This _sometimes_ results in failing Gitpod installations when `registry-facade` and `ws-daemon` are _not_ last change within the same commit.
Fixes #
- check `registry-facade` deamonset and check it has the "registr-facade" same image just like the "registry-facade" 
```release-note
NONE
```
=> [installer] registry-facade: Fix render bug

.werft/jobs/build/installer/installer.ts
Run usage reconciliation more frequently in preview envs to make developing the service easier.
Previously to trigger usage runs in preview it was necessary to edit the configmap.
Part of #9036 
```release-note
NONE
```
=> [dev] Set usage reconciliation schedule to 1m in preview

components/usage/BUILD.yaml, components/usage/go.mod, components/usage/go.sum, components/usage/pkg/contentservice/client.go, components/usage/pkg/contentservice/noop.go, components/usage/pkg/controller/reconciler.go, components/usage/pkg/server/server.go, install/installer/pkg/components/usage/configmap.go, install/installer/pkg/components/usage/configmap_test.go
https://github.com/gitpod-io/gitpod/pull/11474 added a new `UsageReportService` to `content-service` that allowed S3 signed upload URLs to be retrieved for the purpose of uploading usage reports to cloud storage.
This PR hooks up the `usage` component  with the `content-service` so that it requests a signed upload URL from `content-service` each time it runs.
Subsequent PRs will use this signed URL to actually upload usage reports to cloud storage.
Part of #9036 
Builds on https://github.com/gitpod-io/gitpod/pull/11474
Look at the logs for the `usage` component in the preview environment for this PR. When usage reconciliation runs it successfully requests a signed upload URL from the `content-service`:
```release-note
NONE
```
=> [usage] Request signed upload URL from `content-service`

WORKSPACE.yaml, components/ide-proxy/Dockerfile, components/ide-proxy/conf/Caddyfile, components/ide-proxy/static/code/marketplace.json, install/installer/pkg/components/blobserve/configmap.go
Adds https://github.com/gitpod-io/openvsx.org.json/blob/main/marketplace.json as a static asset to our IDE proxy.
Part of https://github.com/gitpod-io/openvscode-server/pull/380.
```release-note
NONE
```
=> Add our Extension control manifest to the IDE proxy

components/docker-up/BUILD.yaml
Sync fork https://github.com/gitpod-io/compose/compare/v2.6.1...v2.7.0
- Run `docker-compose --version`, should return `Docker Compose version 2.7.0-gitpod.0`
```release-note
Update docker compose to v2.7.0
```
=> [docker-up] Update docker compose to v2.7.0

components/dashboard/src/settings/Account.tsx, components/dashboard/src/settings/Billing.tsx, components/dashboard/src/settings/EnvironmentVariables.tsx, components/dashboard/src/settings/Integrations.tsx, components/dashboard/src/settings/Notifications.tsx, components/dashboard/src/settings/PageWithSettingsSubMenu.tsx, components/dashboard/src/settings/Plans.tsx, components/dashboard/src/settings/Preferences.tsx, components/dashboard/src/settings/SSHKeys.tsx, components/dashboard/src/settings/Teams.tsx
Create and use a new `PageWithSettingsSubMenu` component to move all the many calls to `getSettingsMenu` into one place. 
Previously all the various settings pages would call `getSettingsMenu` individually to draw the menu.
This is a refactoring step towards moving all feature flags into the `FeatureFlagContext` (#11609)
Part of https://github.com/gitpod-io/gitpod/issues/11609.
```release-note
NONE
```
=> [dashboard] Extract `PageWithSettingsSubMenu` component

components/usage/pkg/db/types.go, components/usage/pkg/db/types_test.go
The report generated by usage would not have properly serialized timestamps, it would come out as:
```json
{
...
"user:some-user-ID": [
{
"id": "1f62df2f-4248-4b5f-a947-ce9df115bc14",
"workspaceId": "csweichel-testrepo-z4qnprx42vk",
"ownerId": "someOwnerID",
"projectId": {
"String": "",
"Valid": true
},
"workspaceClass": "default",
"workspaceType": "regular",
"usageAttributionId": "user:userAttributionID",
"creationTime": {},
"stoppedTime": {}
}
]
}
```
Fixes #
Unit tests
```release-note
NONE
```
=> [usage] Allow marshalling of VarCharTime to JSON

components/dashboard/src/Menu.tsx, components/dashboard/src/contexts/FeatureFlagContext.tsx, components/dashboard/src/index.tsx, components/dashboard/src/settings/PageWithSettingsSubMenu.tsx, components/dashboard/src/settings/settings-menu.ts
Move the UBP feature flag into the `FeatureFlagContext`. We want to consolidate all setting of feature flags in this context.
Stacked on:
* https://github.com/gitpod-io/gitpod/pull/11610
Part of https://github.com/gitpod-io/gitpod/issues/11609
```release-note
NONE
```
=> [dashboard] Move usage based pricing feature flag into feature flag context

components/dashboard/src/teams/TeamUsage.tsx, components/gitpod-protocol/package.json, components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/package.json, components/server/src/workspace/gitpod-server-impl.ts, components/usage-api/typescript/src/usage/v1/sugar.ts
Extends the server with time-filtering args.
The client sends `number` and then it gets converted in the server to `google.protobuf.Timestamp`.
Relates #11526
[Preview](https://laushinka-c45de4dc15.preview.gitpod-dev.com/t/gitpod/usage) still renders and calls `listBilledUsage` with the time params (the websocket connection in the network tab).
```release-note
NONE
```
=> [usage] Extend server args with time-filtering

components/server/ee/src/workspace/gitpod-server-impl.ts
Workspace classes look not to be stable enough to be always present on the records, see [internal conversation](https://gitpod.slack.com/archives/C02F19UUW6S/p1658744227235839)
Fixes #
```release-note
NONE
```
=> [usage] Make workspace class non-mandatory

components/dashboard/src/payment-context.tsx, components/dashboard/src/teams/TeamUsage.tsx, components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Follow up to https://github.com/gitpod-io/gitpod/pull/11613 to clean up the `PaymentContext` and it's usages now that the feature flag is provided by the `FeatureFlagContext`.
Part of https://github.com/gitpod-io/gitpod/issues/11609
Team usage view is once again visible:
As is the widget to enable billing for a team:
```release-note
NONE
```
=> [dashboard] Remove showUsageBasedUI from PaymentContext

components/server/ee/src/workspace/gitpod-server-impl.ts
Because setSeconds doesn't work the same for ts Date and pb.Timestamp
Fixes #
```release-note
NONE
```
=> [usage] Fix conversion of from and to pb.Timestamp

components/usage/pkg/contentservice/client.go, components/usage/pkg/contentservice/noop.go, components/usage/pkg/controller/reconciler.go
As part of the move towards usage based pricing (https://github.com/gitpod-io/gitpod/issues/9036), we'd like for the usage aggregator (`components/usage`) to be able to upload its usage reports to cloud storage. This will provide an audit trail of usage reports, allowing us to cross reference usage entries in the database with the usage reports that provided the data. In future, we may also allow access to these reports to users directly.
This is the third part of the PR stack:
https://github.com/gitpod-io/gitpod/pull/11474: Add a means of getting signed S3 upload URLs from content-service.
https://github.com/gitpod-io/gitpod/pull/11493: Request the signed upload URLs from the usage component.
This PR: Use the upload URL to upload compressed usage reports to object storage and stop …
=> [usage] Upload usage reports to cloud storage

components/dashboard/src/service/service-mock.ts, components/dashboard/src/settings/selectClass.tsx, components/gitpod-protocol/src/gitpod-service.ts, components/gitpod-protocol/src/workspace-class.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/workspace-classes.ts, install/installer/pkg/components/server/configmap.go, install/installer/pkg/components/server/types.go, install/installer/pkg/config/v1/experimental/experimental.go
Source the workspace classes that should be displayed in the settings dialog from the server instead of hard coding them.
Fixes #https://github.com/gitpod-io/gitpod/issues/11583
- Open dashboard in preview environment
- Check that workspace classes configured in the server config map are dispalyed
```release-note
None
```
=> Fetch workspace classes from server

components/ws-manager/pkg/manager/monitor.go
Retry the function `doFinalize` when the ws-daemon pod is not found so that we can reach the condition https://github.com/gitpod-io/gitpod/blob/444ccf07dd7ac17ea244f1bc1944d27bfbdaef95/components/ws-manager/pkg/manager/monitor.go#L1272-L1278
Fixes #10682
1. Create a workspace.
2. Create a large file.
```console
dd if=/dev/urandom of=4G bs=16M count=256
```
4. Stop the workspace `Gitpod: stop workspace` and immediately go to step 5.
5. During the workspace stopping, keep deleting the ws-daemon pod for at least 1 minute. Note, we probably would hit the issue #11606, but we'd like to tackle it in separate PR. 
```console
while true; do kubectl delete pod -l component=ws-daemon; done
```
6. Cancel step 5 (ctrl+c).
7. Check the workspace changes to the stopped state and the backup content …
=> Retry the finalizer loop when the ws-daemon pod not found

operations/observability/mixins/meta/dashboards.libsonnet, operations/observability/mixins/meta/dashboards/components/usage.json
Initial dashboard showing ticks of the controller, and RPCs against the endpoints
You can observe it [in staging](https://grafana.gitpod-staging.com/d/8W7P-jg4z/component-usage?orgId=1)
Fixes #
```release-note
NONE
```
=> [usage] Add grafana dashboard

.werft/vm/manifests/rook-ceph/cluster-test.yaml
The rook-ceph-mgr-a pod keeps in CrashLoopBackOff state.
There could be something breaking with the latest ceph. So, let's stick to v17.2.1.
https://github.com/rook/rook/commit/4501cc25c6534a2fa66233812fe79f0a3382e07e
Fixes #
1. Create a preview environment
2. Check all the pods under rook-ceph namespace are in Running state
```console
kubectl get pod -n rook-ceph
```
```release-note
None
```
None
=> [preview-env] Use ceph v17.2.1 instead of latest v17

operations/observability/mixins/components/bar_gauge_panel.libsonnet, operations/observability/mixins/cross-teams/dashboards/gitpod-overview.libsonnet
- Add stats from the last seven days
- Remove decimals
```release-note
NONE
```
=> Improve Summary dashboard row

components/dashboard/src/contexts/FeatureFlagContext.tsx, components/dashboard/src/settings/Preferences.tsx
Move the workspace classes feature flag into the `FeatureFlagContext`.
Part of #11609
Workspace classes UI still displays correctly on the user settings page:
```release-note
NONE
```
=> [dashboard] Move workspace classes feature flag into context

components/dashboard/src/admin/WorkspacesSearch.tsx
This will replace the custom alert component added in https://github.com/gitpod-io/gitpod/pull/8632 for searching workspaces only by their IDs.
Fixes https://github.com/gitpod-io/gitpod/issues/8701
1. Go to **/admin/workspaces**
2. Breathe and enjoy the hidden power of components
|-|-|
| <img width="1440" alt="Screenshot 2022-07-23 at 12 41 08 AM (2)" src="https://user-images.githubusercontent.com/120486/180572700-e08ea515-1460-4823-a190-f4b3b7cc3efe.png"> | <img width="1440" alt="Screenshot 2022-07-23 at 12 41 27 AM (2)" src="https://user-images.githubusercontent.com/120486/180572703-edec9cf6-1bd2-412b-b6c7-e85ee21e8abd.png"> |
```release-note
Replce workspace search alert
```
=> Replace workspace search alert

components/dashboard/src/projects/ProjectSettings.tsx
Fix the broken dashboard settings page. Previously, changes to the checkbox settings would not be persisted.
([internal discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1658820587067219))
Toggle the checkboxes on the page, navigating between views and refreshing the page:
https://user-images.githubusercontent.com/8225907/181002449-cd7a51a0-0b7b-4511-82c5-eedba04551c6.mov
```release-note
[dashboard] Fix persistence of checkbox values on settings page
```
=> [dashboard] Fix project settings page

components/usage/pkg/contentservice/client.go, components/usage/pkg/contentservice/noop.go, components/usage/pkg/controller/billing.go, components/usage/pkg/controller/reconciler.go, components/usage/pkg/controller/reconciler_test.go, components/usage/pkg/server/server.go
This wasn't needed any more, as we already compute the CreditsUsed in the usage controller
This also fixes a bug where the pricer was using a different `now` timestamp to what the usage controller used.
Relates to https://github.com/gitpod-io/gitpod/issues/10785
Unit tests
```release-note
NONE
```
=> [usage] Remove pricer dependency from billing controller

components/server/ee/src/prebuilds/github-service.ts
The |Team or persona scope| / Projects / New Project widget has been super slow since the feature's debut when running against large Github Enterprise instances with 10s of thousands of repositories under many-100 git-orgs. Since the current implementation is filtering to show only the repos where the current user has 'admin' permissions only after all pages are fetched and it makes the UI wait for the entire result set to be fetched before returning, the UI is frozen for 5-10+ minutes.
Still, even as being frozen / super slow (added a TODO to fix / optimize), this feature remained usable, since it is a one-time project setup. However, since we upgraded to GH Enterprise v 3.x, it seems that some returned pages might contain one or more null items, where the current filter expression …
=> fix: new project widget broken if 'null' item(s) received from gh api

operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
Updates `GitpodWorkspaceStuckOnStarting` to #t_workspace_alerts.
Since alerts with no user impact should never go to PagerDuty, what is written in the runbook is already clear enough:
* [This issue has little to no user impact, but will result in on-call being paged regularly due to stuck nodes.](https://github.com/gitpod-io/runbooks/blob/e24540d28700262a4b8e8331640c1d2cea449c02/runbooks/GitpodWorkspaceStuckOnStarting.md?plain=1#L26)
Hey @kylos101, I'm coming back to your suggestion to re-classify the alert to something less severe.
https://github.com/gitpod-io/runbooks/pull/373#discussion_r929248324
```release-note
NONE
```
=> Route GitpodWorkspaceStuckOnStarting to #t_workspace_alerts

operations/observability/mixins/workspace/dashboards.libsonnet, operations/observability/mixins/workspace/dashboards/node-problem-detector.json
Dashboard for https://github.com/kubernetes/node-problem-detector/
```release-note
NONE
```
=> Add dashboard for node problem detector

components/ws-daemon/pkg/dispatch/dispatch.go
Use a background context instead one with a timeout. We cannot rely on a fixed time to wait for the disposal of the workspace.
```release-note
NONE
```
=> [ws-daemon] Fix wait until workspace is stop

components/ws-manager/pkg/manager/manager.go, components/ws-manager/pkg/manager/manager_test.go
Reverts https://github.com/gitpod-io/gitpod/pull/11517 and improve error messages
```release-note
NONE
```
=> [ws-manager] Refactor connectToWorkspaceDaemon

.werft/jobs/build/job-config.ts, .werft/jobs/build/prepare.ts, .werft/vm/manifests.ts, .werft/vm/vm.ts
In ide integration test, we need run many workspace in the same time, this PR introduces a werft annotation `with-large-vm`, if job with this annotation, it will create a vm that use 12 cpu, and 24GB memory.
Fixes #
```release-note
NONE
```
=> [werft] support large vm

components/usage/pkg/controller/billing.go, components/usage/pkg/stripe/stripe.go
Propagating context ensures that requests get cancelled when the parent context is cancelled, and generally help with tracing. They are a standard golang practice.
Fixes #
```release-note
NONE
```
=> [usage] stripe.UpdateUsage uses context

install/installer/pkg/components/server/configmap.go, install/installer/pkg/components/server/configmap_test.go, install/installer/pkg/config/v1/config.go, install/installer/pkg/config/v1/config.md, install/installer/pkg/config/v1/experimental/experimental.go, install/kots/manifests/gitpod-installation-status.yaml, install/kots/manifests/gitpod-installer-job.yaml
This PR moves out options to specify the default workspace image and the `allowList` of private image registries out of the `experimental` section.
The workspace image and the allow list for the registry can be specified as follows:
```
workspace:
workspaceImage: 691173103445.dkr.ecr.eu-west-1.amazonaws.com/691173103445.dkr.ecr.eu-west-1.amazonaws.com/busybox:new
containerRegistry:
privateBaseImageAllowList:
- 691173103445.dkr.ecr.eu-west-1.amazonaws.com
```
Fixes #10791
Fixes #11408
- Open this PR in a gitpod workspace with access to the `core-dev` cluster.
- Download the replicated license corresponding[ to this channel.](https://vendor.replicated.com/apps/gitpod/customer/2CFmg83KrHD3gQAbHd4DPYHsJY0/manage)
- `mkdir -p installer/licenses/nvn/`
- cp path/to/replicatedlicense …
=> [installer] move workspaceImage out of experimental config

components/dashboard/src/teams/TeamUsage.tsx
Allows users to select billing months.
Fixes #11526
Go to https://lau-time-view-11526.preview.gitpod-dev.com/t/gitpod/usage and click on the previous months.
```release-note
NONE
```
=> [usage] Allow selecting billed months

components/server/src/workspace/config-provider.ts
This PR makes the logic for finding a gitpod.yml sequential.
Currently, we run the gitpod.yml inference on every workspace start, which sends lots of requests (around 20) to the git provider in order to check for build files. Since this is a fallback mode that is only relevant in those cases where there is no `.gitpod.yml` I have changed the logic so it is sequential and only runs when really needed.
fixes #11649
Start workspaces on repositories with gitpod.yml and without.
Make sure the right gitpod.yml is used.
```release-note
NONE
```
=> [bitbucket] make less requests and fail on error

components/dashboard/src/contexts/FeatureFlagContext.tsx, components/dashboard/src/projects/ProjectSettings.tsx
Move the persistent volume claim feature flag into the `FeatureFlagContext`.
Refactor the context so that we have a simple, uniform way to add new dashboard feature flags.
Closes #11609
All feature flags still work as before.
```release-note
NONE
```
=> [dashboard] Move PVC feature flag to context

components/dashboard/src/teams/TeamUsage.tsx
This introduces a spinner when the data is being fetched.
Fixes #11677
1. Join https://lau-loading-11677.preview.gitpod-dev.com/teams/join?inviteId=6dd143f5-9997-4e43-a1ef-1ba9edd2169b
2. Set network conditions to Slow 3G
3. Go to https://lau-loading-11677.preview.gitpod-dev.com/t/gitpod/usage
```release-note
NONE
```
=> [usage] Have spinner while loading

install/kots/manifests/kots-preflight.yaml, install/kots/manifests/kots-support-bundle.yaml
The KOTS `run` collectors previously ran in the `default` namespace. This puts them in the namespace where the application is stored
Deploy via KOTS
```release-note
[kots]: put the "run" collectors into the active namespace
```
=> [kots]: put the "run" collectors into the active namespace

components/ws-manager/pkg/manager/create.go, components/ws-manager/pkg/manager/manager.go
Check the pod label to determine the PVC feature flag is set
Fixes #
1. Enable the feature flag PVC, launch the workspace and the PVC object created
2. Disable the feature flag PVC, launch the workspace and no PVC object be created
```release-note
None
```
None
=> Check the pod label to determine the PVC feature flag is set

components/ws-manager/pkg/manager/metrics.go, components/ws-manager/pkg/manager/status.go, components/ws-manager/pkg/manager/testdata/actOnPodEvent_wsstartup_Creating00.golden, components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED01.golden, components/ws-manager/pkg/manager/testdata/status_disposal_STOPPING02.golden, components/ws-manager/pkg/manager/testdata/status_wsstartup_Creating00.golden
This PR fixes two issues:
1. As described in https://github.com/gitpod-io/gitpod/issues/10315#issuecomment-1185810931 it resolves an issue of sending sometimes incorrectly to server empty failed state, even though prior to that we might have sent failure error message. This breaks opening that workspace again, as server will incorrectly assume that there was a backup created (no failure error) and will attempt to restore second workspace from backup, which will fail, thus completely breaking opening that workspace for the customer.
2. We incorrectly mark completed container as an error.  When container is stopped, it is will be in a completed state. That is not an error. 
This two fixes need to go hand in hand.
For more info, see the link above for the comment describing the issue in …
=>   [ws-manager] fix incorrect handling of failure state for workspaces 

dev/preview/previewctl/cmd/install_context.go
`previewctl install-context --branch <branch-name>` does not use the branch name flag.
It keeps using the result of `git rev-parse --abbrev-ref HEAD`.
Fixes #
`previewctl install-context -branch <branch-name>` should branch name input.
```release-note
None
```
None
=> previewctl: install-context honors the branch name

.github/workflows/jetbrains-update-plugin-platform-template.yml, .github/workflows/jetbrains-update-plugin-platform.yml
Add a GitHub Action that runs every day checking if there's some update the Platform Version from JetBrains Plugins. If so, it create a Pull Request.
Resolves #11120
- It won't be able to be tested manually, but I've ran it once by setting it to run on this PR, and from it we can see it's working as expected: When the version is up to date, nothing happens, but if it's outdated, a PR will be created:
- https://github.com/gitpod-io/gitpod/runs/7546306836?check_suite_focus=true
- https://github.com/gitpod-io/gitpod/runs/7546306657?check_suite_focus=true (You can ignore the red icon in this case, as it just failed because it can't create a PR from another PR without specific configuration)
- But you can read the PR changes and confirm if the code looks good.
```release-note
NONE
```
None.
=> Automatically create Pull Requests for updating the Platform Version from JetBrains Plugins when available

install/installer/pkg/components/openvsx-proxy/statefulset.go
This adds the `kube-rbac-proxy` to the `openvxs-proxy` statefulset, exposing the metrics endpoint through it, so prometheus is able to scrape it correctly.
[Before and after updating the address](https://grafana.gitpod.io/d/HNOvmGpxgd/openvsx-proxy?orgId=1&from=1658913689599&to=1658925254366&query=ws-proxy&var-datasource=VictoriaMetrics&var-cluster=All&var-node=All&var-pod=All&var-pod_instance=All&var-container_instance=All)
```release-note
NONE
```
=> Fix openvsx-proxy metrics

.github/workflows/jetbrains-updates-template.yml
Update 'create-pull-request' GitHub Action to v4.
Because `team-reviewers` is not being set when using v3 (see the [latest PR created with that template](https://github.com/gitpod-io/gitpod/pull/11680)).
None.
It has already been tested: see [this PR](https://github.com/gitpod-io/gitpod/pull/11720) created from [this template that uses v4](https://github.com/gitpod-io/gitpod/blob/403ad38fb155da8f525277d01e5ef81f1896866a/.github/workflows/jetbrains-update-plugin-platform-template.yml#L69).
```release-note
NONE
```
None.
=> Update 'create-pull-request' GitHub Action to v4

components/ws-manager/pkg/manager/monitor.go
Give the ws-daemon unavailable retry maximum be 2 mins.
We see in the production cluster, that once the ws-daemon is gone, probably due to the underlying node being gone.
We don't need to waste time to keep retrying it for 1 hour in such a case.
Somehow, the finalizeWorkspaceContent executes takes 3h14m, it not what we expected within 1 hour.
Fixes #
```release-note
None
```
None
=> Revert the ws-daemon max unavailable back to wsdaemonMaxAttempts

install/installer/pkg/components/image-builder-mk3/configmap.go
This PR updates the workspace image name in the `refCache` of `image-builder-mk3-config` configmap when a custom workspace base image is provided in the installer config file. This means the correct base images are not cached, slightly slowing the image build.
Fixes #11684
Create a Gitpod self hosted instance by opening a Gitpod workspace from main, making sure you have access to `core-dev` cluster and running: (you can read more about this preview setup [here](https://www.notion.so/gitpod/WIP-Self-hosted-automated-nightly-pipelines-fdc5a202e67b4197aa00d93b98d57927)) 
```
werft run github -j .werft/self-hosted-installer-tests.yaml -a skipTests=true -a preview=true -a deps=external
```
When the job is finished, you will get the URL and `KUBECONFIG` details under the `get-results` phase tab …
=> [installer] updating the refCache image in image-builder-mk3

operations/observability/mixins/IDE/rules/components/openvsx-proxy/alerts.libsonnet, operations/observability/mixins/IDE/rules/components/openvsx-proxy/rules.libsonnet
Add alert when openvsx registry is down
runbook: https://github.com/gitpod-io/runbooks/pull/292
```release-note
NONE
```
=> Add openvsx alert

operations/observability/mixins/IDE/rules/components/openvsx-proxy/alerts.libsonnet
Add an alert that triggers when Prometheus fails to scrape OpenVSX-proxy, or when OpenVSX-Proxy completely disappears from Prometheus' target list
Fixes #
```release-note
NONE
```
=> Add alert for OpenVSX-proxy scraping failures

components/ws-manager/pkg/manager/annotations.go, components/ws-manager/pkg/manager/create.go, components/ws-manager/pkg/manager/imagespec.go, components/ws-manager/pkg/manager/labels.go, components/ws-manager/pkg/manager/manager.go, components/ws-manager/pkg/manager/monitor.go, components/ws-manager/pkg/manager/testdata/cdwp_fullworkspacebackup.golden
Correct const variable naming. It should be a label, not an annotation.
Fixes #
None
```release-note
None
```
None
=> Correct const variable naming. It should be a label, not an annotation

operations/observability/mixins/platform/rules.libsonnet, operations/observability/mixins/platform/rules/scrape.libsonnet
Add an alert for when Prometheus fails to scrape metrics from any target. (Actually, it ignores workspaces)
Fixes #
```release-note
NONE
```
=> Add alert for target down

components/ws-manager/pkg/manager/manager.go, components/ws-manager/pkg/manager/monitor.go, components/ws-manager/pkg/manager/status.go, components/ws-manager/pkg/manager/testdata/actOnPodEvent_workspace_startup_failed.golden, components/ws-manager/pkg/manager/testdata/status_workspace_startup_failed.golden
Remove the PVC object if the workspace pod is never been ready; we still go through the stopping phase even if the workspace is not ready. However, we don't perform backup but we just remove the finalizer in the end (and remove the PVC object if it existed).
Fixes #11635
I have no idea how to make the workspace pod has never been in a ready state. 🤔 
But you could use this cluster for testing this PR https://jenting-10531.preview.gitpod-dev.com/workspaces, and open the workspace ID `gitpodio-templatenix-kzpw34u`. This workspace always hits the ErrImagePull error which belongs to the workspace pod that has never been in a ready state.
```release-note
None
```
None
=> Remove the PVC object if the workspace pod is never been ready

components/docker-up/BUILD.yaml
Sync fork https://github.com/gitpod-io/compose/compare/v2.7.0...v2.8.0
- Run `docker-compose --version`, should return `Docker Compose version 2.8.0-gitpod.0`
```release-note
Update docker compose to v2.8.0
```
=> [docker-up] Update docker compose to v2.8.0

components/dashboard/src/projects/ProjectSettings.tsx
Hide the PVC feature section on the project settings page when the PVC feature flag is not set.
Previously, the section would always be visible but the checkbox would be disabled if the feature flag was not set.
Disable the feature flag for users in non-production (via configcat) and reload a project settings page. 
```release-note
NONE
```
=> [dashboard] Hide PVC feature section when feat flag not set

components/server/src/user/user-controller.ts
Add HTTP endpoint for supervisor frontend to send heartbeat when user's leaving the browser
In the current implementation of supervisor-frontend, we will send some requests before/during browser unload, which may cause some data loss since requests will be canceled after 1 second once user close the tab. 
https://github.com/gitpod-io/gitpod/blob/00d510825c93b01bc3865c81d909d80ac6cf38df/components/supervisor/frontend/src/ide/heart-beat.ts#L45-L58
We will move those requests to use [Navigator.sendBeacon](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) to avoid data loss.
So this PR is going to add HTTP post endpoint for sendBeacon
see also [internal chat](https://gitpod.slack.com/archives/C01KGM9BH54/p1658742853684919?thread_ts=1658720614.040559&cid=C01KGM9BH54)
Fixes …
=> [server] add http endpoint workspacePageClose for beacon

components/server/ee/src/prebuilds/github-enterprise-app.ts
Iterate of team owners to find the authorized user to trigger a prebuild for a project on a push event.
Based on: https://github.com/gitpod-io/gitpod/pull/11584
Fixes https://github.com/gitpod-io/gitpod/issues/11566
```release-note
Fix broken prebuild trigger for GHE.
```
=> Fix find authorized user for GHE prebuilds

.werft/aks-installer-tests.yaml, .werft/cleanup-installer-setups.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/installer-tests.ts, .werft/k3s-installer-tests.yaml, install/infra/terraform/tools/issuer/main.tf, install/tests/Makefile, install/tests/cleanup.sh
This PR adds the cronjob to cleanup the self-hosted preview environments that are older that 10 hours. The PR also uploads the KUBECONFIG file in case of k3s to the cloud storage. In the case of managed k8s cluster, there are new targets in Makefile that get the kubeconfig file to the local.
If we want to omit a gitpod setup from deletion, you can provide a custom subdomain name as a part of the tests, that start with `gitpod-`. For eg: `gitpod-test`. It is expected that these setups will be manually deleted.
Fixes #11277
If you want to test the cron to cleanup the tests, you can run:
```
werft run github -j .werft/cleanup-installer-setups.yaml
```
```release-note
NONE
```
=> Add cronjob to cleanup preview environments

components/dashboard/src/teams/TeamUsage.tsx, components/gitpod-protocol/src/gitpod-service.ts, components/gitpod-protocol/src/usage.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/gitpod-server-impl.ts, components/usage-api/typescript/src/usage/v1/sugar.ts
Adds the ordering argument to `listBilledUsage` calls.
View implementation will be in a separate issue and PR.
Fixes #11691
1. Join [team](https://laushinka-1e1c9f7bce.preview.gitpod-dev.com/teams/join?inviteId=5e187f1c-c628-4741-b4b0-3ad9d15cde44)
2. Go to [/usage](https://laushinka-1e1c9f7bce.preview.gitpod-dev.com/t/gitpod/usage)
3. Check the network call - `listBilledUsage` should be called with the additional param '0'.
```release-note
NONE
```
=> [usage] Extend method call with order arg

components/server/src/workspace/workspace-starter.ts
This PR ties protected_secrets to a ConfigCat feature flag (on server) so that we can roll this out in production. This is the next step for https://github.com/gitpod-io/gitpod/issues/10134.
I've added the `protected_secrets` flag to ConfigCat and enabled it for non-prod environments.
1. Start a workspace
2. Observe that the workspace was started with the `protected_secrets` flag, and that its secrets were fed from a Kubernetes secret.
```release-note
NONE
```
=> [server] Tie protected_secrets to ConfigCag

components/dashboard/src/teams/TeamUsage.tsx
The wrong param names were sent, causing the API to compute default values.
```release-note
NONE
```
=> [usage] Fix arguments to the listBilledUsage call

components/usage/pkg/server/dialer.go, components/usage/pkg/server/server.go
The billing client tries to connect to the usage component gRPC server before the gRPC server is ready. This is a non-fatal error as gRPC dialing has built-in backoff/retry logic but it does produce ugly warnings in the usage component logs.
Here we use a simple solution to delay the self-connection attempt for a short period to give the gRPC server time to start.
Fixes https://github.com/gitpod-io/gitpod/issues/11743
Warning messages at `usage` component startup (as described in #11743) are no longer present.
```release-note
NONE
```
=> [usage] Delay gRPC self connection

components/dashboard/src/teams/TeamUsage.tsx
This allows the started time to be sorted in descending and ascending orders.
Fixes #11706 
1. [Join this team](https://lau-sorting-ui-11706.preview.gitpod-dev.com/teams/join?inviteId=11a4f51d-4eb6-4f51-b171-a5c747ab1357).
2. See the usage.
3. Click on the sorting in the "Started" column. The list should be re-rendered accordingly.
```release-note
NONE
```
=> [usage] Enable sorting in the UI

install/installer/pkg/components/ws-daemon/daemonset.go
Setting low values impacts the workspace density in the node.
```release-note
NONE
```
=> [ws-daemon] Increase resources more real values

components/ws-manager/pkg/manager/status.go, components/ws-manager/pkg/manager/testdata/actOnPodEvent_workspaceCompleted_01.golden, components/ws-manager/pkg/manager/testdata/status_workspaceCompleted_01.golden, components/ws-manager/pkg/manager/testdata/status_workspaceCompleted_01.json
After recent [refactor](https://github.com/gitpod-io/gitpod/pull/11489), we are not correctly handling the case when workspaces is completed (when it exits on its own, usually due to crash, etc).
This PR addresses this and also adds a test case for this.
Fixes #11759
```release-note
none
```
=> [ws-manager] fix not handling workspaces that are completed

.werft/installer-tests.ts, .werft/jobs/build/self-hosted-upgrade-tests.ts, install/infra/terraform/aks/kubernetes.tf, install/infra/terraform/aks/variables.tf, install/infra/terraform/eks/kubernetes.tf, install/infra/terraform/eks/variables.tf, install/infra/terraform/gke/main.tf, install/infra/terraform/gke/variables.tf, install/infra/terraform/k3s/main.tf, install/infra/terraform/k3s/variables.tf, install/tests/Makefile, install/tests/main.tf
This PR parameterize  the version of node image when possible and version of kubernetes. The node images are not configurable easily on managed self-hosted instances. We can only use the supported images corresponding to the Kubernetes version we are using. Hence the all supported ubuntu versions are tested only in the k3s setup.
Fixes #11349 
Fixes #11272 
One can use any of the suggested commands in this [internal document](https://www.notion.so/gitpod/Self-hosted-automated-nightly-test-pipelines-fdc5a202e67b4197aa00d93b98d57927) to test.
```release-note
NONE
```
=> [installer-tests] Support tests against multiple version of k8s and ubuntu images

.github/ISSUE_TEMPLATE/feedback_issue.yml
The goal of the feedback issue template is to make it easier and provide a skeleton for opening feedback issues for specific features as done in the past, see relevant pull request in https://github.com/gitpod-io/gitpod/pull/10593.
See also [relevant discussion](https://gitpod.slack.com/archives/C01KLC5750D/p1652903673228329) (internal). Cc @atduarte 
There were a few issues (see list below) opened recently using this template that actually aimed at providing general feedback instead. This caused new issues having the **~feedback-issue** label or the **Feedback Issue:** title prefix while containing general feedback.
This will update the description of the template to clarify the goal of this template.
- https://github.com/gitpod-io/gitpod/issues/11062
- …
=> Update feedback issue template

install/installer/pkg/components/content-service/deployment.go
Recently we added a [new alert](https://github.com/gitpod-io/gitpod/pull/11745) for whenever Prometheus fails to scrape a component, and we immediately got alerted about content-service being unreachable. After some debugging, we traced down #11591 which introduced a breaking change for many `/metrics` endpoints. 
This PR adds kube-rbac-proxy to content-service, which will make the metrics endpoint reachable again.
Resolves alerts such as [this one](https://gitpod.slack.com/archives/C03MWBB5MP1/p1659380032576119).
```release-note
NONE
```
=> Add kube-rbac-proxy to content-service

components/dashboard/src/components/ErrorMessage.tsx, components/server/ee/src/user/user-service.ts, components/server/src/auth/generic-auth-provider.ts
Fixes #9972
- try to signup with GitHub [here](https://gpl-9972-no-seats.preview.gitpod-dev.com/workspaces)
- notice how you're brought back to the login-screen, which should shows this message:
Note: the "feedback" panel is only shown on [gitpod.io](https://github.com/gitpod-io/gitpod/blob/7efea0a97f90b165afdd55e6168526424eb5e220/components/dashboard/src/components/ErrorMessage.tsx#L19).
```release-note
display an alert on signup if a user cannot login because they license does not cover for that additional seat
```
=> Display alert in "No seats" scenario

components/content-service/pkg/service/usage-report-service.go, components/usage/pkg/contentservice/client.go
As part of the move towards usage based pricing (https://github.com/gitpod-io/gitpod/issues/9036), we'd like for the usage aggregator (`components/usage`) to be able to upload its usage reports to cloud storage. This will provide an audit trail of usage reports, allowing us to cross reference usage entries in the database with the usage reports that provided the data. In future, we may also allow access to these reports to users directly.
In order to be able to upload these reports to GCP Cloud Storage, the signed URL can be created for a specific `Content-Type`; only `PUT` requests to that URL that set the same `Content-Type` header will be accepted.
This PR sets the `Content-Type` header when generating the signed URL and sets it on the `usage` component `PUT` to that URL.
Minio object …
=> [usage] Ensure `Content-Type` headers are set for GCP object storage uploads

components/ws-daemon/pkg/internal/session/store.go
Takes care of the following problem:
- We attempt to delete the workspace and delete the workspace.json file
- Workspace deletion fails at a later step for some reason
- We do not remove the session
- We reattempt deletion but because the workspace.json has already been deleted we fail again due to the missing workspace.json file.
So lets remove the workspace session even if deleting the workspace from disk fails because we will definitely fail the second time and it just generates noise. We need to focus on why it fails in the first place.
Fixes https://github.com/gitpod-io/gitpod/issues/11715
```release-note
None
```
=> Ensure workspace is only deleted once

components/dashboard/src/App.tsx, components/dashboard/src/utils.ts, install/preview/entrypoint.sh, install/preview/manifests/coredns.yaml
Currently, After `local-preview` is exited There are no
direct concrete steps for users to take.
This PR fixes this by adding a new `Alert` box to the
global dashboard if we notice that they are on a Gitpod
`local-preview` DOMAIN, which is `preview.gitpod-self-hosted.com`
(our own DOMAIN) from now.
Part of https://github.com/gitpod-io/gitpod/issues/11381
Run
```
docker run -p 443:443 --privileged --name gitpod --rm -it -v gitpod:/var/gitpod eu.gcr.io/gitpod-core-dev/build/local-preview:tar-lp-out-nudge.19
````
and see the nudge being present.
```release-note
[dashboard] Next steps nudge for local-preview
```
=> [dashboard] Next steps nudge for local-preview 

.pre-commit-config.yaml, install/installer/.gitignore, install/installer/BUILD.yaml, install/installer/Makefile, install/installer/cmd/render.go, install/installer/cmd/render_test.go, install/installer/cmd/root.go, install/installer/cmd/testdata/render/README.md, install/installer/cmd/testdata/render/minimal/config.yaml, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/versions.yaml, install/installer/pkg/common/render.go, install/installer/pkg/components/docker-registry/helm.go
This is a proposed change to allow for testing of the rendered YAML in the Installer.
The data is stored in `cmd/testdata/render`, with the test names being stored in `cmd/testdata/render/<name>/<config|output>.golden`. Files ending `.golden` are excluded from the hooks to make them testable. The intention is that there will be a suite of these tests and they verify that the known output is matched. When a change is made (even outside of this directory), the files will require changing and @gitpod-io/engineering-self-hosted is notified about potentially breaking changes to the rendered YAML - we can then approve (or not) the changes.
How to generate the files is documented.
Randomisation is controlled by specifying the `Seed` for `math/rand` and by giving the `crypto/rand` a known string. …
=> [installer]: create tests to verify render result

components/public-api-server/config.json, components/public-api-server/go.mod, components/public-api-server/go.sum, components/public-api-server/pkg/server/server.go, components/public-api-server/pkg/webhooks/stripe.go
Add a placeholder [Stripe webhook](https://stripe.com/docs/webhooks) to the `public-api` component. 
In later PRs, the webhook will:
* receive `invoice.finalized` events from Stripe.
* invoke RPCs on the `usage` component to update usage records to show that they have been included in a particular invoice.
This PR is a re-do of https://github.com/gitpod-io/gitpod/pull/11776, which added the webhook to the `usage` component directly.
After some discussion on that PR and [internally](https://gitpod.slack.com/archives/C02EN94AEPL/p1659427332329269), it was decided to move it to the public API and have the pubilc API invoke RPCs on `usage` instead.
Part of #9036 and https://github.com/gitpod-io/gitpod/issues/10937
* Install the[ `stripe` CLI](https://stripe.com/docs/stripe-cli) into the …
=> [public-api] Add a placeholder Stripe webhook

.werft/observability/monitoring-satellite.ts
Fix the sleep in the exec command
```release-note
NONE
```
=> Fix the sleep in the cmd

components/content-service/pkg/initializer/git.go, components/content-service/pkg/initializer/prebuild.go
Provide a better error message when we receive a HTTP 524 status code.
Fixes #https://github.com/gitpod-io/gitpod/issues/11712
```release-note
None
```
=> Provide better error message for HTTP 524

components/usage/pkg/controller/reconciler.go, components/usage/pkg/controller/reporter.go
Expose metrics about number of sessions updated in each run
Depends on https://github.com/gitpod-io/gitpod/pull/11681
```release-note
NONE
```
=> [usage] Add metrics for number of usage records

components/ws-daemon/pkg/iws/iws.go
As a last ditch effort detach base mounts if they cannot be unmounted. That way new accesses are denied and it will be unmounted once all processes are done using it.
Related to https://github.com/gitpod-io/gitpod/issues/11369
```release-note
None
```
=> Detach dangling base mounts

components/ws-manager/pkg/manager/monitor.go
Add annotation gitpod.io/startedDisposal once we enter finalize workspace content.
Related #11710
None
```release-note
None
```
None
=> Add annotation gitpod.io/startedDisposal ealier

components/server/src/user/user-controller.ts
In previous PR, we did not handle the json-rpc response status https://github.com/gitpod-io/gitpod/pull/11643#discussion_r934525099 of server instance ~~and sharing workspace access https://github.com/gitpod-io/gitpod/pull/11643#discussion_r934283285~~, this PR will handle it and add proper log context https://github.com/gitpod-io/gitpod/pull/11643#discussion_r932985930
We removed `accessGuard` of sharing, see reason in **How to test** section
Fixes #
~~Check if it will process with sharing workspace or not~~
No need to test with sharing, since sharing workspace have no update permission on instance which server sendHeartbeat required. This is as expected.
https://github.com/gitpod-io/gitpod/blob/c18dea6e7b49e19b86e5de5c958bfe57f4ab12c8/components/server/src/auth/resource-access.ts#L265-L2 …
=> [server] better handle workspacePageClose endpoint response status and log ctx

.gitpod.yml
Downloads the Installer dependencies at workspace-creation time so tests can be run.
Fixes #11828
Start a workspace, `cd install/installer` then `go test ./...`. These should pass
```release-note
NONE
```
=> Get the Installer dependencies for every workspace

components/dashboard/src/settings/Integrations.tsx
Redirect URI is used to be copy-pasted into OAuth applications of GHE/GL/BBS. When port numbers are included in host names, this was not handled properly in #11409.
Fixes #11795
Try to create a Git Integration with port number in hostname and see the value of the redirect URI is rendered with colon before the port number.
```release-note
Fix rendering of the redirect URI on Git Integrations page
```
=> [dashboard] Fix rendering of the redirect URI on Git Integrations page

components/dashboard/src/components/PrebuildLogs.tsx
Fix a bug where we do not load Prebuild logs when the prebuild has already finished.
Fixes #11755 
- join [this team](https://gpl-11755-logs.preview.gitpod-dev.com/teams/join?inviteId=439d46d2-f218-4752-a96c-1f566a2fe637)
- modify [this line](https://github.com/geropl/gitpod-test-repo/blob/gpl/docker-build-2mins/.gitpod.yml#L4)
- [check](https://gpl-11755-logs.preview.gitpod-dev.com/t/superhumans/gitpod-test-repo) that the prebuild is executed
- once it's "READY", go to the PrebuildDetails page (click the status) and notice how the logs are shown as well
```release-note
NONE
```
=> [dashboard] Fix displaying of logs for finished Prebuilds

.gitpod.yml
Improve workspace startup time by not compiling `previewctl` on workspace startup.
This PR removes the compile step for `previewctl` because it's already being added to the workspace here:
https://github.com/gitpod-io/gitpod/blob/81c7aa193fc6f10e015c52ac87a0a355669755f0/dev/image/Dockerfile#L256
Fixes # https://gitpod.slack.com/archives/C01KGM9AW4W/p1659516801962049?thread_ts=1659513203.668999&cid=C01KGM9AW4W
see if `previewctl` is still available in workspaces. 
```release-note
NONE
```
=> Don't compile previewctl on workspace-startup

components/server/src/workspace/workspace-starter.ts
Related https://github.com/gitpod-io/gitpod/issues/11823
```release-note
none
```
=> add log when starting workspace with pvc

components/dashboard/src/images/sort-arrow.svg, components/dashboard/src/teams/TeamUsage.tsx
Uses the correct arrow icon.
Fixes #11783
1. [Join this team](https://laushinka-3f2ec393c7.preview.gitpod-dev.com/teams/join?inviteId=47ce2625-e4d3-4c42-bb74-e6ab80c86621).
2. I will set you as owner.
3. Go to the [usage](https://laushinka-3f2ec393c7.preview.gitpod-dev.com/t/gitpod/usage) tab.
```release-note
NONE
```
=> Replace with sorting icon

components/common-go/kubernetes/probes.go
Use defined env variables to use proxies.
```release-note
NONE
```
=> Add support for HTTP_PROXY, HTTPS_PROXY and NO_PROXY in probes

components/ws-manager/pkg/manager/monitor.go
Address PR comment https://github.com/gitpod-io/gitpod/pull/11826#issuecomment-1204384417
This reverts commit e40e43d76120e5de702522e6b816f28b86a219c6.
Related https://github.com/gitpod-io/gitpod/issues/11710
None
```release-note
None
```
None
=> Revert add annotation gitpod.io/startedDisposal earlier

install/installer/pkg/components/public-api-server/configmap.go, install/installer/pkg/components/public-api-server/configmap_test.go, install/installer/pkg/components/public-api-server/constants.go, install/installer/pkg/components/public-api-server/service.go
As of https://github.com/gitpod-io/gitpod/pull/11806, the public api exposes an HTTP port for a Stripe webhook handler. This handler should be present on Gitpod SaaS but absent on self hosted installations.
This PR adds experimental config for the public api component to allow an HTTP port to be configured. If the port is not present in the configuration, `baseserver` ensures that HTTP is not served.
Part of https://github.com/gitpod-io/gitpod/issues/10937 and #9036 .
Installer unit tests to check the rendered public api configmap.
```release-note
NONE
```
=> [installer] Support configuration of the public API HTTP port

components/usage/pkg/server/server.go
Allows the reconciler to receive responses up to 30MB in size. Currently it fails with 
```
code = ResourceExhausted desc = grpc: received message larger than max (8500596 vs. 4194304)
```
This is equivalent to ~8MB, so we have some headroom.
If this becomes a problem, we can split the RPC to stop returning All records for everyone, and instead do RPC per Attribution ID or similar.
Fixes #11836
```release-note
NONE
```
=> [usage] Self-connection allows up to 30MB in message response

components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Optimization: Don't wait for the portal URL before fetching a team's spending limit -- there is no dependency between the two, so they can be fetched in parallel.
Fixes #
1. Subscribing a team to UBB and setting a spending limit should still work
```release-note
NONE
```
=> [dashboard] Optimization: Don't wait before fetching a team's spending limit

.werft/jobs/build/helm/values.dev.gcp-storage.yaml, components/content-service-api/go/config/config.go, components/content-service/pkg/service/headless-log-service_test.go, components/content-service/pkg/storage/gcloud.go, components/content-service/pkg/storage/storage.go, components/ws-daemon/example-config.json, components/ws-daemon/pkg/content/service.go, components/ws-manager/pkg/manager/testdata/status_metadata.json, install/installer/pkg/common/storage.go, install/installer/pkg/config/v1/config.go, install/installer/pkg/config/v1/config.md
Remove the backup trail feature. The feature is present only on GCP. 
The reason for the removal is consistency with other providers and also to align it with PVC.
In traces, we see the error `Maximum number of snapshots (%d of %d) reached` meaning we are not going to upload a backup for the workspace and the next time it is open, it will contain the previous state, not the last one.
Fixes #11709
```release-note
NONE
```
=> Remove backup trail

operations/observability/mixins/meta/rules/components/components.libsonnet, operations/observability/mixins/meta/rules/components/usage/alerts.libsonnet
Alert is a warning for now, and goes directly to team webapp. Runbook will be added in tandem and this alert updated.
Fixes #
```release-note
NONE
```
=> [usage] Add alert on failed reconciliations

install/installer/cmd/testdata/render/minimal/output.golden
The changes of #11807 are not reflected in the output.golden file. This PR fixes this.
```release-note
NONE
```
=> [installer] Add missing output.golden changes of #11807

components/ws-daemon/pkg/content/service.go
Log warning instead of tracing error span if the error message contains `cannot find workspace`.
Fixes #11710
Fixes #11713
None
```release-note
None
```
None
=> Log warning instead of tracing error span

.werft/jobs/build/deploy-to-preview-environment.ts, .werft/jobs/build/prepare.ts, .werft/util/certs.ts
The same thing as https://github.com/gitpod-io/gitpod/pull/11844, but more carefully. I'm splitting adding owner reference to the certificate and the garbage collection logic into separate PRs. 
The main reason for this separation is that the garbage collection will delete any certificate without an owner's reference.
A chained PR will implement the garbage collection logic(https://github.com/gitpod-io/gitpod/pull/11856)
Open a workspace from this PR and run:
```
werft run github -a with-preview -f
```
Check if the generated certificate has an owner annotation referencing the correct preview.
```
kubectl --context dev describe certificate -n certs <certificate-name>
```
```release-note
NONE
```
=> previews: Add preview owner reference to certificates

install/installer/cmd/testdata/render/minimal/output.golden, install/installer/pkg/components/proxy/templates/configmap/vhost.payment-endpoint.tpl, install/installer/pkg/components/public-api-server/networkpolicy.go, install/installer/pkg/components/public-api-server/networkpolicy_test.go
Configures ingress between `proxy` and the public API server to allow external access to the Stripe webhook (added in https://github.com/gitpod-io/gitpod/pull/11806).
* Add a new `backend` section to the `payment-ingress` section in the proxy `Caddyfile` and 
* Update a `networkpolicy` to allow `proxy` to reach the `public-api-server`.
Part of https://github.com/gitpod-io/gitpod/issues/10937
* Hit the webhook handler using its external URL:
```
brew install httpie
http POST https://payment.af-ingressf994192aa3.preview.gitpod-dev.com/stripe/invoices/webhook type=foo
```
Expected output:
```http
HTTP/1.1 200 OK
Content-Length: 15
Content-Type: text/plain; charset=utf-8
Date: Thu, 04 Aug 2022 08:05:21 GMT
X-Gitpod-Region: local.
event type: foo
```
```release-note
NONE
```
=> [usage] Configure ingress for Stripe webhook

install/installer/cmd/render_test.go
This PR updates the installer render tests:
- It resets the seed for every test case. Otherwise, adding a test case would lead to changes in other tests because the pseudo-random generator starts with a different state.
- It allows to create a golden file even when there is not file yet.
```release-note
NONE
```
=> [installer] Small render test improvements

dev/gpctl/cmd/workspaces-list.go
Add Type and Pod to output of `workspaces list`. This allows on-callers responding to https://github.com/gitpod-io/runbooks/blob/main/runbooks/GitpodWorkspaceStuckOnStarting.md more easily understand the type of workspace
Fixes #
1. [Get kube context](https://www.notion.so/gitpod/How-to-connect-to-a-cluster-2d059f96124a4976ab56599dc1a29c32#d584cca8fa194f70a20586165ca5a883)
2. Run `cd dev/gpctl && go run main.go workspaces list`
3. Observe the output columns containing type and pod. 
```release-note
NONE
```
=> [gpctl] Add workspace type to workspaces list

install/installer/cmd/testdata/render/minimal/output.golden, install/installer/pkg/components/workspace/ide/constants.go
commit hash in PR is from this PR https://github.com/gitpod-io/gitpod/pull/11875 job https://werft.gitpod-dev.com/job/gitpod-build-hw-vs-build.0
Fixes #
- Open workspace in preview env with stable vscode
- Check if the commit hash is https://github.com/gitpod-io/openvscode-server/commit/e59b2689b5dcd7e5618baf76b111b87a20e36aac
```release-note
Fix in-product changelog relative URLs not working problem
```
=> [code] update stable code image to fix changelog related url not works

components/gitpod-db/src/typeorm/migration/1659601647550-BilledSession.ts, components/usage/pkg/db/billed_session.go, components/usage/pkg/db/billed_session_test.go
Add d_b_billed_session table migration and Go definitions
Fixes #11867 
In `/components/usage/pkg/db` run `go test`
```release-note
NONE
```
=> [db][usage] Add d_b_billed_session table migration and Go definitions

README.md
Fixed the spelling errors in the README.md 
Fixes #
```release-note
NONE
```
=> Fixed some spelling errors in README.md

components/usage/pkg/server/server.go, components/usage/pkg/stripe/reporter.go, components/usage/pkg/stripe/stripe.go
Reports metric on the number of usage records udpated in stripe. This can be used to observe trends and spot issues.
Fixes #
```release-note
NONE
```
=> [billing] Report metrics on updated subscriptions

dev/gpctl/cmd/workspaces-list.go
following https://github.com/gitpod-io/gitpod/pull/11870/
Fixes #
1. Run cd dev/gpctl && go run main.go workspaces list
1. Observe the output columns containing type and pod.
```release-note
`gpctl workspaces list` shows all workspace types
```
=> gpctl: support all workspace types.

components/blobserve/pkg/blobserve/blobserve.go, components/blobserve/pkg/blobserve/blobspace.go, components/blobserve/pkg/blobserve/blobspace_test.go, components/blobserve/pkg/blobserve/refstore_test.go
```
pkg/blobserve/blobspace.go:183:14: Error return value of `os.WriteFile` is not checked (errcheck)
os.WriteFile(fmt.Sprintf("%s.used", fn), nil, 0644)
^
pkg/blobserve/blobspace.go:208:19: Error return value of `cmd.Process.Kill` is not checked (errcheck)
cmd.Process.Kill()
^
pkg/blobserve/blobspace.go:223:14: Error return value of `os.WriteFile` is not checked (errcheck)
os.WriteFile(fmt.Sprintf("%s.size", fn), []byte(fmt.Sprintf("%d", cw.C)), 0644)
^
pkg/blobserve/blobspace.go:224:14: Error return value of `os.WriteFile` is not checked (errcheck)
os.WriteFile(fmt.Sprintf("%s.used", fn), nil, 0644)
^
pkg/blobserve/blobspace.go:260:8: Error return value of `f.Seek` is not checked (errcheck)
f.Seek(0, 0)
^
pkg/blobserve/blobspace_test.go:52:15: Error return value of `os.MkdirAll` is not …
```
=> [blobserve] Fix lint issues

WORKSPACE.yaml
Build code image for `1.7.0`
Build result https://werft.gitpod-dev.com/job/gitpod-build-hw-vs-170-build.3/results
Fixes #
Relates https://github.com/gitpod-io/gitpod/issues/11638
```release-note
NONE
```
=> [code] build stable code image for 1.70

components/supervisor/frontend/src/ide/gitpod-server-compatibility.ts, components/supervisor/frontend/src/ide/heart-beat.ts
In the current implementation of supervisor-frontend, we will send some requests before/during browser unload, which may cause some data loss since requests will be canceled after 1 second once user close the tab. 
We will move those requests to use [Navigator.sendBeacon](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) to avoid data loss.
So this PR is going to add HTTP post endpoint for sendBeacon
see also https://github.com/gitpod-io/gitpod/pull/11643 and [internal chat](https://gitpod.slack.com/archives/C01KGM9BH54/p1658742853684919?thread_ts=1658720614.040559&cid=C01KGM9BH54)
👉 The first commit is cherry-picked from prev PR https://github.com/gitpod-io/gitpod/pull/11643
Fixes #
- Use preview env https://hw-hb-t.preview.gitpod-dev.com/workspaces which change …
=> [supervisor-frontend] use beacon to send heartbeat to avoid data loss

operations/observability/mixins/meta/rules/components/usage/alerts.libsonnet
Forgot to specify the outcome 🤦 
Fixes #
```release-note
NONE
```
=> [usage] Fix UsageReconciliationFailures alert

install/installer/cmd/testdata/render/minimal/output.golden, install/installer/pkg/components/workspace/ide/constants.go
Commit sha in PR comes from previous PR https://github.com/gitpod-io/gitpod/pull/11899 build result https://werft.gitpod-dev.com/job/gitpod-build-hw-vs-170-build.3/results
Fixes #
Relates https://github.com/gitpod-io/gitpod/issues/11638
Tested in https://github.com/gitpod-io/gitpod/pull/11899. So we can check version and commit hash here
- Open workspace in prev env with stable code
- Check if version and commit sha in `About`, sha should be `a2d4f1655c40b19dbc5c989a00af9184bfd93940`, version should be `1.70.0`
```release-note
[code] update stable VSCode Browser to 1.70.0
```
=> [code] update stable code image to 1.70

.github/CODEOWNERS
When Team Self-Hosted is the only codeowner of the testdata, we need to approve nearly every change of the installer. This would defacto cancel out the codeowner properties of the individual packages. Which would not make much sense, IMO.
```release-note
NONE
```
=> [codeowners] Allow all teams to approve installer testdata changes

components/ws-daemon/pkg/internal/session/store.go, components/ws-daemon/pkg/internal/session/store_test.go
This PR re-instates ws-daemon's content garbage collection which removes workspace content from disk once the state file is gone. We had originally disabled this behaviour because it interfered with the ws-daemon/ws-sync migration three years ago.
There's a grace period for content built-in which ensures we only delete content older than two hours. The motivation is to guard against accidental state mishaps.
>**Warning**
> This PR carries the risk that it might delete workspace content unintentionally. 
Fixes #11369
- see unit test
- start a workspace, produce a file in the workspace content directory which cannot be deleted and stop the workspace
- make the workspace content directory deletable again and see it being deleted
```release-note
NONE
```
=> [ws-daemon] Enable workspace content housekeeping

install/installer/cmd/testdata/render/minimal/output.golden, install/installer/pkg/common/display.go
This PR ensures that the ordering of the rendered K8s objects is stable. That allows comparing renderings with different configs.
Render with 2 different configs (e.g. with external registry and with internal registry). Without this change, the ordering is not stable and it is impossible to compare the changes. After this change, the ordering is stable and you can see with a diff what has changed in the rendering.
#11880 has an example where you can compare the golden files with and without an external registry.
```release-note
NONE
```
=> [installer] Ensure stable ordering of rendered K8s objects

components/usage/pkg/server/server.go
Reconciler fails with:
```
failed to update invoices: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (19548617 vs. 16777216)"
```
That's because we're sending the BilledSessions to the UpdateInvoices RPC. For now, we increase the size.
Fixes #
```release-note
NONE
```
=> [usage] Fix max call send message size

install/kots/manifests/gitpod-installer-job.yaml
Change the allowlist so it only amends the `privateBaseImageAllowList` in airgapped mode. As the Replicated proxy URLs were getting added (pointlessly - the base image is never them), this only needs adding for airgapped mode.
`docker.io` is still added in when in "airgapped mode" as this would be activated if someone is just mirroring their container images (this is possible in KOTS even if the license doesn't allow for airgapped installations).
The [codebase in question](https://github.com/gitpod-io/gitpod/blob/main/components/image-builder-mk3/pkg/auth/auth.go#L120-L153)
- Deploy via KOTS in non-airgapped mode
- Run `kubectl get configmaps -n gitpod gitpod -o jsonpath='{.data.config\.yaml}'`
- Should see the following:
```yaml
containerRegistry:
privateBaseImageAllowList: []
```
- …
=> [kots]: only add to base image allow list in airgapped mode

components/dashboard/src/components/BillingAccountSelector.tsx, components/dashboard/src/settings/Billing.tsx, components/dashboard/src/start/CreateWorkspace.tsx, components/gitpod-protocol/src/messaging/error.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/user/user-service.ts
When starting a workspace but usage attribution is unclear, prompt for explicit user choice.
Possible unclear situations:
- User is a member of multiple teams with usage-based billing enabled
- User explicitly chose to attribute to a team, but they've since left this team (or the team was deleted, or its subscription was cancelled)
Fixes https://github.com/gitpod-io/gitpod/issues/11579
1. Start a workspace on any repo (should work)
2. Create a team called "Gitpod" (or "Gitpod 1", "Gitpod 2"... whichever is available) to enable the Usage-Based Billing flag
3. Start a new workspace on any repo (should work)
4. Upgrade your team to Usage-Based Billing by adding a payment method (e.g. 4242 4242 4242 4242, 4/24, 424)
5. Start a new workspace on any repo (should still work)
6. Create a new team …
=> When starting a workspace but usage attribution is unclear, prompt for explicit user choice

components/ws-daemon/pkg/cgroup/plugin_iolimit_v1.go, components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go, components/ws-daemon/pkg/cgroup/plugin_proc_limit_v2.go
Log that resource limits have been updated. 
n.a.
```release-note
None
```
=> [ws-daemon] Log update of resource limits

components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
Introduces JSON RPC API to retrieve the current BillingModes for a given user/team.
Context: https://github.com/gitpod-io/gitpod/issues/11402
- see [previous PR](https://github.com/gitpod-io/gitpod/pull/11812)
```release-note
NONE
```
=> BillingMode: add Json RPC API methods (2/4)

operations/observability/mixins/meta/rules/components/usage/alerts.libsonnet
Add link to runbook
* Depends on https://github.com/gitpod-io/runbooks/pull/381
```release-note
NONE
```
=> [usage] Add runbook link for GitpodUsageScheduledReconciliationFailures

components/usage/cmd/run.go, components/usage/pkg/apiv1/billing.go, components/usage/pkg/apiv1/billing_test.go, components/usage/pkg/server/server.go
Add a new config setting to the usage component config setting to better support the rollout of usage based pricing.
The `billInstancesAfter` setting defines the date after which instances should be considered for billing - instances started before `billInstancesAfter` will never be considered by the billing controller.
Part of https://github.com/gitpod-io/gitpod/issues/10937
Unit tests for the billing controller.
For an end-to-end test do this in the preview environment:
* Join the Gitpod team: https://af-no-bill390c0e761d.preview.gitpod-dev.com/teams/join?inviteId=f35adc3b-720f-4406-85ec-101628b587bc
* Edit the usage configmap to change `billInstancesAfter`:
```yaml
{
"billInstancesAfter": "2022-08-06T00:00:00Z",
...
}
```
By changing the date, restarting the `usage` pod and starting …
=> [usage] Add `billInstancesAfter` config setting

components/dashboard/src/App.tsx, components/dashboard/src/components/ConfirmationModal.tsx, components/dashboard/src/settings/selectClass.tsx
Randomly checking webapp dashboards after recent deployment shows excessive calls to newly `getSupportedWorkspaceClasses` operations caused by `useEffect` without dependency specification, thus causing evaluation without need. 
Relates to #11571
```release-note
NONE
```
=> [dashboard] fix arbitrary useEffect

components/usage/cmd/run.go, components/usage/pkg/apiv1/billing.go, components/usage/pkg/apiv1/billing_test.go, components/usage/pkg/server/server.go, install/installer/pkg/components/usage/configmap.go, install/installer/pkg/components/usage/configmap_test.go, install/installer/pkg/config/v1/experimental/experimental.go
In https://github.com/gitpod-io/gitpod/pull/11882 the `usage` component gained a `billInstancesAfter` config setting, to better support the rollout of usage based pricing.
This PR adds the ability to set `billInstancesAfter` through the installer. 
Part of https://github.com/gitpod-io/gitpod/issues/10937
Automated installer tests.
```release-note
NONE
```
=> [installer] Support setting `billInstancesAfter`

components/public-api-server/pkg/webhooks/stripe.go, components/public-api-server/pkg/webhooks/stripe_test.go
Do some TDD on the Stripe webhook handler.
Add tests to ensure:
* The handler only accepts `POST` requests.
* The handler only responds to `"invoice.finalized"` events.
Add code to the handler to make those tests pass.
Part of #10937 
```release-note
NONE
```
=> [UBP] Add tests and functionality to the Stripe webhook handler

components/dashboard/src/start/CreateWorkspace.tsx, components/dashboard/src/start/StartWorkspace.tsx, components/gitpod-protocol/src/messaging/error.ts, components/server/ee/src/workspace/gitpod-server-impl.ts
Partially resolves #11404
Very limited UI 🛹  of a modal shown when you've reached the configured spending limit.
Related to #11404
```release-note
Add Spending Limit Reached modal on workspace creation.
```
=> Stop sign on "out of credits"

components/ws-manager/pkg/manager/monitor.go
Retry doFinalize if gRPC status code is Unavailable
Fixes #11861
None
```release-note
None
```
None
=> Retry doFinalize if gRPC status code is Unavailable

components/ide-proxy/conf/Caddyfile
[ide-proxy] add missing path for static files
Fixes #
```release-note
NONE
```
=> [ide-proxy] add missing path

operations/observability/mixins/workspace/rules/components/nodes/alerts.libsonnet
Add critical alert for when load avg is high for too long.
First, why change to critical alert:
if load average is high for too long, it will affect all workspaces on that node, so we want to react to that fast, hence critical alert (otherwise on call person can potentially be working on something else and might miss this for some time).
Why change duration to 10 min:
We want to minimize amount of false positives as much as possible. We should alert\wake up someone only on sustained high load average. 
Why change load avg check to above 10:
Again, we want to be alerted only on legit signal. Load avg above 10 for more then 10 min should signal in almost all cases that something really bad is going on on that node. 
Fixes #
```release-note
none
```
=> [alerts] change load avg alert to critical

components/content-service/pkg/git/git.go, components/content-service/pkg/git/git_test.go, components/content-service/pkg/initializer/git.go, components/content-service/pkg/initializer/prebuild.go
If the git repo has no commits, the git log displays `does not have any
commits yet`. We ignore it in tracing.
Fixes #11789
1. Open repo github.com/gitpod-io/emtpy
2. Check jaeger tracing, making sure there is no tracing error in `git.log` span.
```release-note
None
```
None
=> Ignore git error message `does not have any commits yet`

components/registry-facade/pkg/registry/blob.go
just small refactoring
Fixes #
```release-note
NONE
```
=> registry-facade: Remove unnecessary varilable declaration.

install/kots/manifests/kots-redactor.yaml, install/kots/manifests/kots-support-bundle.yaml
This is redacted to ensure that sensitive data is not included in the support bundles. Example from [Fernando at Replicated](https://community.replicated.com/t/how-can-i-export-config-options-into-a-support-bundle/879/4)
Deploy via KOTS and run a support bundle. Inspect files and look in `kots-config/gitpod/kotsadm-*/stdout.txt`. Anything sensitive will be replaces with `***HIDDEN***`
```release-note
[kots]: collect the user config in support bundles
```
=> [kots]: collect the user config in support bundles

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/run-integration-tests.yaml, .werft/self-hosted-installer-tests.yaml, .werft/wipe-devstaging.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile
- Open a workplace using this pull request
- Run `go version`
- Check the returned value is `go version go1.19 linux/amd64`
```release-note
NONE
```
=> Update go to v1.19

install/kots/manifests/kots-support-bundle.yaml
Genuinely no idea how this got in. Assume it was during the "hold" process and a copied the wrong thing across.
As per #11943
```release-note
[kots]: fix typo which meant wasn't using the appSlug in config collect
```
=> [kots]: fix typo which meant wasn't using the appSlug in config collect

components/common-go/kubernetes/kubernetes.go
We removed the use of services long ago
```release-note
NONE
```
=> [common-go] Remove unused WorkspaceSupervisorEndpoint helper

operations/observability/mixins/meta/rules/components/server/alerts.libsonnet
Update the alert description unit, it should be second(s), not millisecond(ms).
https://github.com/gitpod-io/gitpod/blob/9329cb6f33a2105b97c9c8738545f295b5e98bbc/operations/observability/mixins/meta/rules/components/server/alerts.libsonnet#L27
The alert displays `description = Server has accumulated 0.36 ms event loop lag.`
However, the Grafana dashboard max/avg/current is around 2xx ms
Therefore, we change the unit to second.
Fixes #
N/A
```release-note
N/A
```
N/A
=> Update the alert description unit

install/installer/cmd/testdata/render/customization/config.yaml, install/installer/cmd/testdata/render/customization/output.golden, install/installer/pkg/components/agent-smith/daemonset.go, install/installer/pkg/components/blobserve/deployment.go, install/installer/pkg/components/content-service/deployment.go, install/installer/pkg/components/dashboard/deployment.go, install/installer/pkg/components/database/cloudsql/deployment.go, install/installer/pkg/components/ide-metrics/deployment.go, install/installer/pkg/components/ide-proxy/deployment.go, install/installer/pkg/components/image-builder-mk3/deployment.go, install/installer/pkg/components/openvsx-proxy/statefulset.go, install/installer/pkg/components/proxy/deployment.go, install/installer/pkg/components/public-api-server/deployment.go, install/installer/pkg/components/registry-facade/daemonset.go, install/installer/pkg/components/server/deployment.go, install/installer/pkg/components/usage/deployment.go, install/installer/pkg/components/ws-daemon/daemonset.go, install/installer/pkg/components/ws-manager-bridge/deployment.go, install/installer/pkg/components/ws-manager/deployment.go, install/installer/pkg/components/ws-proxy/deployment.go
Remove a [limitation](https://www.gitpod.io/docs/self-hosted/latest/advanced/customization#limitations) on the custom labels by removing the customisation on the selector labels. These are "reverted" to just using the default labels function instead so they're consistent.
Fixes #11952
Deploy via KOTS.
1. Use a default configuration
2. Upload a configuration as per the [docs](https://www.gitpod.io/docs/self-hosted/latest/advanced/customization):
```yaml
customization:
- apiVersion: "*"
kind: "*"
metadata:
name: "*"
labels:
hello: world
annotations:
hello: world
```
3. Redeploy with the default configuration
All of these should install fine.
```release-note
[installer]: remove the custom labels from the selector labels
```
=> [installer]: remove the custom labels from the selector labels

components/dashboard/src/Menu.tsx, components/dashboard/src/contexts/FeatureFlagContext.tsx, components/dashboard/src/payment-context.tsx, components/dashboard/src/settings/PageWithSettingsSubMenu.tsx, components/dashboard/src/settings/Plans.tsx, components/dashboard/src/settings/Teams.tsx, components/dashboard/src/settings/settings-menu.ts, components/dashboard/src/teams/TeamBilling.tsx, components/dashboard/src/teams/TeamSettings.tsx, components/dashboard/src/teams/TeamUsage.tsx, components/dashboard/src/teams/TeamUsageBasedBilling.tsx, components/dashboard/src/user-context.tsx, components/gitpod-protocol/src/billing-mode.ts, components/server/ee/src/billing/billing-mode.spec.db.ts, components/server/ee/src/billing/billing-mode.ts, components/server/ee/src/workspace/gitpod-server-impl.ts
This PR introduces the usage of the `getBillindMode` calculation across the code base.
It turned out quite big in terms of lines of code, but can be either reviewed commit-by-commit, or even split into multiple PRs if that increases confidence. It contains four main changes:
- Guard calculation of BillingMode by new FF "isBillingModeEnabled": if false, getBillingMode always returns "chargebee" (in SaaS). This is meant to de-risk the rollout of "BillingModes", prior to even thinking about enabling "usage-based pricing" Feature Flag. This is meant to go away short-term (end of next week?) once we see that calling the actual impl does not break prod
- some improvements and fixes to getBillingMode
- Enforce that Chargebee/Stripe API is only usable with the respective BillingMode: There is one …
=> BillingMode: Use BillingMode to restrict API access (3/4)

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/run-integration-tests.yaml, .werft/self-hosted-installer-tests.yaml, .werft/wipe-devstaging.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile
These have become very outdated. As a way of avoiding this in future, these are set to the latest. 
```release-note
NONE
```
=> Set KOTS/Replicated dependencies to latest

install/installer/pkg/config/loader.go, install/installer/pkg/postprocess/postprocess.go, install/installer/pkg/yq/yq.go
Refactor `yq` into its own standalone library in the Installer.
Also changes the way the `apiVersion` is removed from the `config.yaml` to use `yq` so it's not dependent upon the regex. This is a problem when using the input as a JSON object (it's unlikely, but as YAML is a superset of JSON, it is something we should probably support).
Originally I thought this was required to #9926 (it's not), but I thought it had merit so spun off to its own PR.
No changes in the rendered output prove this hasn't introduced any regressions
Install via KOTS
```release-note
[installer]: refactor yq to run against arbitrary strings
```
=> [installer]: refactor yq to run against arbitrary strings

.pre-commit-config.yaml, .werft/jobs/build/deploy-to-preview-environment.ts, .werft/jobs/build/installer/installer.ts, .werft/jobs/build/installer/post-process.sh, components/common-go/analytics/analytics.go, components/gitpod-protocol/data/gitpod-schema.json, components/gitpod-protocol/go/gitpod-config-types.go, components/gitpod-protocol/hack/generate-config.sh, components/ide/jetbrains/image/status/main.go, components/ide/jetbrains/image/status/main_test.go, components/supervisor/cmd/run.go, components/supervisor/pkg/config/gitpod-config-analytics.go, components/supervisor/pkg/config/gitpod-config.go, components/supervisor/pkg/config/gitpod-config_analytics_test.go, components/supervisor/pkg/config/gitpod-config_test.go, components/supervisor/pkg/supervisor/supervisor.go
This PR adds analytics for .gitpod.yml changes. We are track when changes are persisted to a disk and debounce them for 5s. After last change we analyse changes to top-level elements and report an event for each. It allows us to gain insights in what users are changing on top-level, e.g `ports` or `tasks`,   and avoid a lot of traffic at the same time. Later we can do more fine grained analysis to see which object properties, like `ports.name`.
I had to resolve couple issues which were discovered during review or were blocking testing:
- enable analytics env inside workspace in preview environments to verify with segment
- don't fire change events for syntactically broken .gitpod.yml files, thank you @andreafalzetti for noticing it
- adding git hook which keeps goland types up to date …
=> [supervisor]: gitpod config changed analytics

components/ws-daemon/pkg/content/service.go
Include workspace id in error
n.a.
```release-note
None
```
=> [ws-daemon] Include workspace id in error

components/common-go/baseserver/server.go, components/usage/pkg/apiv1/size_test.go, components/usage/pkg/server/server.go
Increase baseserver's gRPC maximum receivable message size to 100MB. Change the `usage` client's maximum send and receive values to the same size.
The usage component is currently failing with this error:
```
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"failed to update invoices: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (33395302 vs. 16777216)","level":"error","message":"Reconciliation run failed.","serviceContext":{"service":"usage","version":"commit-8e227e13ef2caae8f56c26387a78546b9fa93b30"},"severity":"ERROR","time":"2022-08-09T11:33:09Z"}
```
This change should allow the `UpdateInvoices` RPC (and all other gRPC services registered with `baseserver`) to accept larger message sizes.
Fixes …
=> [UBP/baseserver] Allow gRPC server to receive much larger messages

components/ide/jetbrains/backend-plugin/build.gradle.kts, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodClientProjectSessionTracker.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodPortsService.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortForwardingService.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodTerminalService.kt, components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml, components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml, components/ide/jetbrains/backend-plugin/src/test/kotlin/io/gitpod/jetbrains/remote/GitpodPortsServiceTest.kt
Auto-forward all workspace open ports when using Latest JetBrains IDEs.
Changes included:
- Adds a `GitpodPortsService`, which is used by both _Stable_ and _Latest_ versions of the Backend Plugin.
- Adds a `GitpodPortForwardingService`, which affects only Latest (Unstable) Version of JetBrains IDEs, and controls the auto-forwarding of all ports.
- Adds a `GitpodPortsServiceTest` with a function unit test. It can be tested via IDE UI or command line [[1](https://github.com/gitpod-io/gitpod/pull/11081#discussion_r938863805)].
- Updates `GitpodTerminalService`, as we moved the implementation to forward all ports to `GitpodPortForwardingService`.
- Updates `GitpodClientProjectSessionTracker`, which displays notifications about ports that have just been opened, to have the correct localhost …
=> Auto-forward all workspace open ports when using Latest JetBrains IDEs

components/ws-daemon/pkg/internal/session/store.go
Add span when NewWorkspace, it helps us to trace when call NewWorkspace error.
Fixes #
None
```release-note
None
```
None
=> ws-daemon: add span when NewWorkspace

operations/observability/mixins/workspace/rules/components/nodes/alerts.libsonnet
Fixes #
```release-note
NONE
```
=> observability: Add a alert for the network connections.

components/dashboard/src/teams/TeamUsage.tsx
Aftermath of #11814
1. Usage page should be shown if UB is enabled
2. If UB is not enabled, redirect to dashboard's root should happen
```release-note
NONE
```
=> Fix redirect on team usage page

.github/workflows/code-nightly.yaml, .github/workflows/jetbrains-auto-update-template.yml, .github/workflows/jetbrains-update-plugin-platform-template.yml, .github/workflows/jetbrains-updates-template.yml
This PR changes all IDE jobs which have previously posted a message to Slack every time they were run to now only post when they are interesting to us. 
This includes them failing or being fixed (going from failing to passing).
This is all achieved by this little snippet:
```yaml
- name: Get previous job's status
id: lastrun
uses: filiptronicek/get-last-job-status@main
with:
workflow-id: 18268462
- name: Slack Notification
if: always()
if: ${{ (success() && steps.lastrun.outputs.status == 'failed') || failure() }}
...
```
Fixes #11771
For the workflows that have manual triggers (can be run by a `Run Workflow` button on the [Actions page](https://github.com/gitpod-io/gitpod/actions)), you can just trigger it and wait for it to finish. If it succeeds then it should not output anything to …
=> [IDE jobs] only post interesting notifications to Slack

.werft/platform-delete-preview-environments-cron.ts
A follow-up from #11855.
This PR aims to refactor the certificate deletion, adopting something similar to Kubernetes Owner references.
1. To delete a certificate the cron first deletes a certain preview and the certificate is left there untouched.
2. A following cron will be responsible for checking that we now have an orphan certificate, and it should be deleted.
```release-note
NONE
```
We should merge #11855 first and wait a few days to merge this one.
The reason is that the garbage collection will delete certificates without owners, and we still have preview environments that don't have such reference. 
Once all active previews have the owner reference, then it is safe to merge this one.
=> previews: Implement certificate garbage collection

install/installer/cmd/testdata/render/statefulset-customization/config.yaml, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/pkg/helm/helm.go
Spotting an error in the Helm customisations where the `typeMeta` variable wasn't being passed through to the annotations and was using the Deployment instead. This was spotted whilst trying to add an annotation to the in-cluster database statefulset, so a render test has been added to that effect.
This changes to using the correct variable instead.
See Golden files
```release-note
[installer]: use typemeta declaration in the helm customisations
```
=> [installer]: use typemeta declaration in the helm customisations

components/usage/pkg/apiv1/billing.go, components/usage/pkg/apiv1/billing_test.go
Add a trivial 'noop' implementation of `FinalizeInvoice` to the billing RPC service.
Part of #10937 
* Unit test for the billing service
or
* Port-forward to the `usage` service gRPC server:
```
kubectl port-forward svc/usage 9001:9001
```
* Use `evans` or `grpcurl` to hit the placeholder `FinalizeInvoice` RPC with an invoice id of e.g: `1234`
* Tail the logs of `deploy/usage` and see:
```
{"level":"info","message":"Finalizing invoice for invoice \"1234\"","serviceContext":{"service":"usage","version":"commit-0aa8abfc2d3b27707a248d3ab285d3561202ceab"},"severity":"INFO","time":"2022-08-08T07:27:39Z"}
```
```release-note
NONE
```
=> [UBP] Add placeholder implementation of `FinalizeInvoice`

components/public-api-server/pkg/webhooks/stripe.go, components/public-api-server/pkg/webhooks/stripe_test.go, components/usage/pkg/apiv1/billing.go, components/usage/pkg/apiv1/billing_test.go
When Stripe invoices finalize, the webhook is `POST`ed to with an `invoice.finalized` payload indicating the invoice id that was finalized. The exact shape of the payload for each event type is described in the [Stripe docs](https://stripe.com/docs/api/events/types).
This PR make the Stripe webhook extract the invoice id from the event payload. Most of the changes are to the test code that exercises the webhook to ensure that a realistic payload is attached to the `invoice.finalized` event.
Part of #10937 
Automated tests for the webhook handler.
For an end to end test:
* Run the webhook handler locally:
```
cd components/public-api-server/
go run . run
```
* Download the [Stripe CLI](https://github.com/stripe/stripe-cli/releases) and run:
```
stripe listen --skip-verify --forward-to …
```
=> [UBP] Use a realistic event payload in Stripe webhook automated tests

components/dashboard/src/components/BillingAccountSelector.tsx, components/server/ee/src/workspace/gitpod-server-impl.ts
Fix active state in usage-based billing account selector:
- When a team is selected, only show one team as active, not all teams (🤦)
- Align with workspace-start auto-selection logic (i.e. no user choice + only one billing team --> auto-select that one)
Fixes https://github.com/gitpod-io/gitpod/issues/11962
1. Enable usage-based billing by creating a team called `Gitpod [Something]`
2. In `/billing`, no billing account should be selected
3. Upgrade team `Gitpod [Something]` to usage-based billing by adding a payment method (e.g. 4242 4242 4242 4242, 4/24, 424)
4. In `/billing`, that one team should now be auto-selected
5. Create and upgrade a second team called `Gitpod [Something Else]` to usage-based billing (you can add the same credit card as above)
6. In `/billing`, no billing account …
=> [dashboard] Fix active state in usage-based billing account selector

.werft/aks-installer-tests.yaml, .werft/cleanup-installer-setups.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/installer-tests.ts, .werft/k3s-installer-tests.yaml, .werft/self-hosted-installer-tests.yaml, install/tests/Makefile, install/tests/manifests/kots-config.yaml
This PR adds slack webhook alerting capabilities to the nightly tests. Currently if any of the setup fails, alert goes to #self-hosted-jobs channel on slack and if any of the integration tests fails it goes to the corresponding team's job channel (currently only workspace and IDE). 
Fixes #11273 
You can run any tests like in this [internal doc](https://www.notion.so/gitpod/WIP-Self-hosted-automated-nightly-pipelines-fdc5a202e67b4197aa00d93b98d57927) to  check the alerts
```release-note
NONE
```
=> [installer-tests] Add slack webhook for test failures

components/dashboard/src/start/CreateWorkspace.tsx, components/server/ee/src/billing/billing-service.ts, components/server/ee/src/billing/entitlement-service-chargebee.ts, components/server/ee/src/billing/entitlement-service-license.ts, components/server/ee/src/billing/entitlement-service-ubp.ts, components/server/ee/src/billing/entitlement-service.ts, components/server/ee/src/container-module.ts, components/server/ee/src/user/eligibility-service.ts, components/server/ee/src/user/user-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/billing/entitlement-service.ts, components/server/src/user/user-service.ts, components/server/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/workspace-starter.ts, components/usage-api/typescript/src/usage/v1/sugar.ts
Based on: https://github.com/gitpod-io/gitpod/pull/11814
1. Introduce EntitlementServiceUBP
2. Implement `BillingService.checkSpendingLimitReached ` (based on [usage](https://github.com/gitpod-io/gitpod/pull/11936/commits/b50bc8e9cb449e6574197c3f6b0d2d8766a6f6a3#diff-0caf79924a209df9577c140a9aefa82d74dab19ed1d20bd1f8597259c3d83316R61) until #11692 got merged)#
3. Wiring, re-use of `BillingService` ([commit](https://github.com/gitpod-io/gitpod/pull/11936/commits/8d35e448211677fa762db3fde2adbef1dc43ff07))
Fixes #11402
Actually, after https://github.com/gitpod-io/gitpod/pull/11814 has been tested thoroughly, this can be tested in prod by enableing `isUsageBasedPricingEnabled`, and testing the rollout flow. :upside_down_face: 
```release-note
NONE
```
=> EntitlementService Usage-Based Pricing

install/installer/cmd/testdata/render/customization/config.yaml, install/installer/cmd/testdata/render/customization/output.golden, install/installer/pkg/helm/helm.go
Escape inline keys given for labels/annotations in Helm. Previously, any "." given in the annotation was expanded as a child key of an object.
Example added to render test.
```release-note
[installer]: escape inline yaml keys for labels/annotations in Helm
```
=> [installer]: escape inline yaml keys for labels/annotations in Helm

components/docker-up/dependencies.sh, components/docker-up/docker-up/main.go, components/docker-up/go.mod, components/docker-up/go.sum, components/ws-daemon/seccomp-profile-installer/main.go
Fixes #10703
Fixes #11963
Fixes #11964
- Open a workspace and run
``` 
git clone https://github.com/ComplianceAsCode/content/
cd content/Dockerfiles
docker build -t test -f ubuntu .
```
- Test command `docker run -it gitpod/workspace-full:latest bash` do not ends with `SIGABRT`
```release-note
NONE
```
=> Add clone3 to seccomp profile syscalls

.github/CODEOWNERS
On the following PR there was no need for them to be reviewers:
- https://github.com/gitpod-io/gitpod/pull/12032
Anyone from IDE team could review it.
With the changes from this PR, those will be the files owned:
```release-note
NONE
```
=> Restrict codeowners of 'supervisor-api' only to '.proto' files

components/server/ee/src/billing/billing-mode.ts, components/server/src/container-module.ts, components/server/src/workspace/workspace-starter.ts, components/usage-api/typescript/src/usage/v1/sugar.ts, components/usage/pkg/apiv1/billing.go, components/usage/pkg/apiv1/billing_test.go, components/usage/pkg/apiv1/size_test.go, components/usage/pkg/db/billed_session.go, components/usage/pkg/server/server.go
Implements setBilledSession and calls it during workspace start.
Depends on #11999
Fixes #11884
1. Do NOT create a "Gitpod" team to ensure that you are still under the Chargebee billing mode.
2. Run workspaces either as personal or in a team's project.
3. Check in the DB (I can also check it) that the session is added into `d_b_billed_session`. 
```release-note
NONE
```
=> [usage] Implement markWorkspaceInstanceSessionAsBilled

components/server/package.json, components/server/src/workspace/workspace-classes.spec.ts, components/server/src/workspace/workspace-classes.ts, components/server/src/workspace/workspace-starter.spec.ts, components/server/src/workspace/workspace-starter.ts
Ensure that if a prebuild is used to create a workspace a class is used that is appropriate for the workspace; meaning if the prebuild has a workspace class greater than the currently configured one by the customer the prebuild class is used, otherwise the class configured by the customer is used. 
Fixes #https://github.com/gitpod-io/gitpod/issues/11972
Needs https://github.com/gitpod-io/ops/pull/3728
- Select workspace class g1-large
- Start a prebuild 
- Select workspace class g1-standard
- Create a regular workspace from prebuild
- The workspace should have g1-large 
--
- Start a prebuild for another repository (with g1-standard)
- Select workspace class g1-large
- Create a regular workspace from prebuild
- The workspace should have g1-large
```release-note
None
```
=> Use prebuild workspace class for regular workspaces

.werft/jobs/build/deploy-to-preview-environment.ts, .werft/jobs/build/job-config.ts, .werft/observability/monitoring-satellite.ts
This adds a new Werft annotation `observabilityInstallationMethod` which can be used to switch the installation method used for gitpod-io/observability. The two valid options are `jsonnet` and `observability-installer` - it defaults to `jsonnet`.
When using `observability-installer` the installation is currently not successful - I consider getting it to a point where the installation is happy out of scope of this PR. Logs from [this job](https://werft.gitpod-dev.com/job/gitpod-build-mads-add-support-for-observability-installer.24/logs) below:
```
[resource mapping not found for name: "alertmanager-main" namespace: "monitoring-satellite" from "STDIN": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
ensure CRDs are installed first, resource mapping not found for …
```
=> Add support for the new observability installer in preview environments

operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
To prevent the alert from being triggered once we start traffic shifting.
The number of workspaces might be low, this cause the
gitpod_workspace_regular_not_active_percentage is easily to hit because
the gitpod_ws_manager_workspace_activity_total is low number.
Therefore, we add #workspace > 20 as another criterion for the alert.
Fixes #
https://gitpod.slack.com/archives/C01TNS8EVQT/p1660179022948519?thread_ts=1660178901.055319&cid=C01TNS8EVQT
Was:
Is:
Note: if we set the #workspace > 5
```release-note
None
```
None
=> observability: add #workspace > 20 in alert GitpodWorkspaceTooManyRegularNotActive

install/infra/modules/gke/main.tf, install/infra/modules/gke/output.tf, install/infra/modules/gke/variables.tf, install/infra/modules/tools/cloud-dns-external-dns/main.tf, install/infra/modules/tools/cloud-dns-external-dns/variables.tf, install/infra/single-cluster/aws/README.md, install/infra/single-cluster/aws/terraform.tfvars, install/infra/single-cluster/gcp/.terraform.lock.hcl, install/infra/single-cluster/gcp/Makefile, install/infra/single-cluster/gcp/README.md, install/infra/single-cluster/gcp/cluster.tf, install/infra/single-cluster/gcp/main.tf, install/infra/single-cluster/gcp/output.tf, install/infra/single-cluster/gcp/terraform.tfvars, install/infra/single-cluster/gcp/tools.tf, install/infra/single-cluster/gcp/variables.tf, install/tests/Makefile, install/tests/main.tf
This PR adds a `single-cluster` gcp terraform module, corresponding to our reference architecture for the same cloud provider.
Fixes #11535
You can follow the README [added to this PR](https://github.com/gitpod-io/gitpod/tree/nvn/tf-doc-gcp/install/infra/single-cluster/gcp#readme) to test this terraform module.
```release-note
NONE
```
=> Sync GCP terraform module to reference architecture

.github/CODEOWNERS
Otherwise it does not seem to have any effect.
```release-note
NONE
```
=> Fix order of installer testdata ownership

install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/pkg/components/content-service/rolebinding.go
In https://github.com/gitpod-io/gitpod/pull/11782 I've added kube-rbac-proxy to content-service because Prometheus was not able to reach the metrics endpoint of content-service.
After this change got deployed, the error only changed to another one. We're now getting `401 Unathorized` errors. 
Looks like I forgot to add the role binding that authorizes kube-rbac-proxy to actually verify valid tokens.
Solves alerts like [this one](https://gitpod.slack.com/archives/C03MWBB5MP1/p1660118826886249).
You can connect to the preview of this PR, port-forward prometheus and verify that content-service is being scraped successfully at the page `/targets`
```release-note
NONE
```
=> Add clusterrolebinding to allow kube-rbac-proxy verify tokens

.idea/.gitignore, .idea/gradle.xml, .idea/misc.xml, components/gitpod-protocol/java/.classpath, components/ide/jetbrains/backend-plugin/.classpath, components/supervisor-api/java/.classpath
Currently, when opening Gitpod repo main branch(independently of using Stable or Latest IDEA version), it's only displaying displaying one of the two Gradle Projects we have (along with some warnings about Gradle not being properly configured):
|       |        |
| --- | --- |
| <img width="834" alt="image" src="https://user-images.githubusercontent.com/418083/183907537-2a489143-79d7-4f32-9220-fe3d9ef164d6.png"> | <img width="339" alt="image" src="https://user-images.githubusercontent.com/418083/183908280-4fc87fd1-6b4e-4128-a0e0-ee607ec22e79.png"> |
With these changes, when we open the Gitpod repo on IntelliJ IDEA it should display the two Gradle Projects correctly configured without any warning notifications.
| Stable IDEA | Latest IDEA|
| --- | --- |
| <img width="833" alt="image" …
=> Fix IntelliJ IDEA detection of Gradle projects from Gitpod repository

components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/Workspace.java, components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/WorkspaceType.java, components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt
These changes ensure that only regular workspaces are added to the workspaces list from JetBrains Gateway.
Fixes #11450
1. Ensure you have the [latest JetBrains Gateway](https://www.jetbrains.com/remote-development/gateway/) installed.
3. Start a [manual prebuild](https://www.gitpod.io/docs/prebuilds#manual-prebuilds) of one of your workspaces.
4. Confirm the Prebuild instance doesn't appear on the workspaces list from JetBrains Gateway.
- Note: After the prebuild finishes, it will open the workspace. At this moment, it's fine the …
=> Avoid displaying prebuild-related workspaces in the workspaces list from JetBrains Gateway

components/gitpod-protocol/src/util/logging.spec.ts, components/server/src/workspace/workspace-starter.ts
Set the value for `volumeSnapshotId` one time.
Background: we're trying to log/capture the above field. Why? The problem is, sometimes a feature (PVC) is enabled for workspace start in production, and we do not know why. We added logging to learn more, but, it is missing this field `volSnapshotId: volumeSnapshotId,`. 
Related to #11823
Start a workspace
```release-note
NONE
```
=> [server] Reliably set log the value for volumeSnapshotId

components/server/src/workspace/workspace-starter.ts, components/ws-manager-bridge/src/bridge.ts
get closer to workspace instance state reflects actual state in cluster.
Fixes #12067
```release-note
NONE
```
=> [server] maintain workspace instance state

components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodMetricControlProvider.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodMetricProvider.kt, components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
Currently, in JetBrains IDE the CPU/Memory usage displayed applies to the whole node, instead of displaying the workspace's specific resources. 
With this PR we introduce two additional progress bars at the top displaying:
- `Workspace CPU`
- `Workspace Memory`
**Please note**: The Unit used for Memory resource is on purpose "GB" instead of "Mi" like in `gitpod-cli`, my reasons:
1. personally I find it shorter and easier to read `0.38GB / 1.55GB` instead of `2944Mi/11870Mi`
2. when talking about memory (in general) it's more common to refer to GB
3. in gitpod.io our memory (especially for XL) can be a large number to read if it's in `Mi`
I would actually like to propose a separate issue to change it also in `gp top` but I would like to know if there are any reasons or string objections in …
=> [JetBrains] Show Workspace CPU/Memory resources in control center

.werft/workspace-run-integration-tests.sh
This PR:
- Improves the error message when the integration tests fail due to a failed build for the preview environment (see example [here](https://werft.gitpod-dev.com/job/gitpod-custom-mads-clarify-workspace-integration-tests.0) - in 'How to test' you can see how I got the build job to fail to trigger this error case)
- Adds a clarify comment that explains why you see two Werft jobs for the integration test brach.
- I wasn't able to reproduce the dual slack messages that Kyle reported for job gitpod-custom-main.132 ([here](https://gitpod.slack.com/archives/C03E52788SU/p1660251950005989) and [here](https://gitpod.slack.com/archives/C03E52788SU/p1660251959797039)). I thought it might be due to the cleanup handler being invoked multiple times so I added a bit of logging so we can see if …
=> Workspace integration tests: Improve message when preview env build job fails

components/usage/pkg/apiv1/billing.go
This fixes the marshalling error where the SetBilledSession call returns nil.
Caused #12067
1. Tail the server logs
2. Check `d_b_billed_session`
3. Run a workspace without usage mode (don't have a Gitpod team). The workspace should run without setBilledSession-related errors and the DB entry should be created.
```release-note
NONE
```
=> [bug][usage] Fixes return of SetBilledSession

components/gitpod-cli/cmd/top.go
Small PR to align thresholds with JetBrains IDE https://github.com/gitpod-io/gitpod/pull/12053/files#diff-5490862e00fecdc038c16bc92b93a0acfd0add183d15e5fcd5a09898f3414978R27-R33
N/A
N/A
```release-note
NONE
```
=> [Gitpod CLI] Align `gp top` thresholds with JetBrains

components/ide/jetbrains/backend-plugin/gradle-stable.properties
Update Platform Version from stable JetBrains Backend Plugin, as we're now [using v222.3345 for all stable JetBrains IDEs](https://github.com/gitpod-io/gitpod/blob/611800ccb662fc2ccda6cab0e387ac1285c5472e/WORKSPACE.yaml#L12-L15).
2. Choose the _Stable_ version of IntelliJ IDEA as your preferred editor
Note: To know what's the version of the IDE (instead of the JetBrains Client version), you need to click the Control widget and "Show Main Window". Then from backend IDE you click "Top Menu >> About", to see something like:
```release-note
NONE
```
=> Update Platform Version from stable JetBrains Backend Plugin

components/openvsx-proxy/pkg/handler.go, components/openvsx-proxy/pkg/modifyresponse.go, components/openvsx-proxy/pkg/openvsxproxy_test.go, components/openvsx-proxy/pkg/run.go
Fix X-Forwarded-* headers in openvsx-proxy, [openvsx will read these values](https://github.com/gitpod-io/openvsx/blob/8624398257663b06e56e90caefee4aaa6385da70/server/src/main/java/org/eclipse/openvsx/util/UrlUtil.java#L151-L163) to properly create links to extension resources 
1. Open workspace 
2. Do some queries in vscode extension view and check response in dev tools links should point to openvsx-proxy
3. Check extensions install sucessfully
```release-note
NONE
```
=> Fix X-Forwarded-* headers in openvsx-proxy

components/registry-facade/pkg/registry/blob.go, components/registry-facade/pkg/registry/http_client.go
IPFS client should respect log levels.
- Enable IPFS
- Check registry-facade logs and confirm there are no entries similar to
`{"level":"info","message":"[DEBUG] POST http://ipfs.storage:9095/api/v0/cat?arg=%2Fipfs%2Fbafkreigmgbjgwxkqco552ec4h2rx7cjdytiyhnca77uha7msl6g7rjctfq","serviceContext":{"service":"registry-facade","version":"commit-4e941c628adc62d67b67d39df1765152f34ba703"},"severity":"INFO","time":"2022-08-12T14:47:51Z"}
`
```release-note
NONE
```
=> [registry-facade] Improve IPFS logging

test/pkg/integration/integration.go
Fix the workspace integration test failed with `invalid value "'-buildid= -w -s'" for flag -ldflags: parameter may not start with quote character '`.
Fixes #
`werft job run github -j .werft/workspace-run-integration-tests.yaml `
```release-note
None
```
None
=> Fix workspace integration test

components/server/src/auth/generic-auth-provider.ts
Don't redirect to sorry on unrecognized login errors, but instead actually display the error message.
Fixes #12112
```release-note
NONE
```
=> [server] Don't redirect to sorry on unrecognized login errors

components/dashboard/src/admin/WorkspaceDetail.tsx
Show workspace class in admin view
Fixes https://github.com/gitpod-io/gitpod/issues/12048
- Open workspace and check admin view
```release-note
None
```
=> [dashboard] Show workspace class in admin view

components/dashboard/src/teams/TeamUsage.tsx
Shows the actual time instead of "... ago"
| - | - |
| <img width="203" alt="Screenshot 2022-08-15 at 01 39 03" src="https://user-images.githubusercontent.com/8015191/184559129-f3b487ff-fbf4-46b0-85ec-4f8fc0ddc1f8.png"> | <img width="230" alt="Screenshot 2022-08-15 at 01 38 13" src="https://user-images.githubusercontent.com/8015191/184559098-8346e097-6fd0-4a24-b21b-1f8c50e90cf6.png"> |
Relates #12090 and #11640
1. Join the [team](https://lau-show-actual-time.preview.gitpod-dev.com/teams/join?inviteId=a8a0d60c-3bc2-4724-9599-bd7910f7bf6e)
2. Go to https://lau-show-actual-time.preview.gitpod-dev.com/t/gitpod/usage
3. See the actual date and time.
```release-note
NONE
```
=> [usage] Use actual date for start time

components/dashboard/src/start/StartWorkspace.tsx
It is supporting PR for https://github.com/gitpod-io/gitpod/pull/12082. It should be deployed by the webapp team before.
Fixes #
Test https://github.com/gitpod-io/gitpod/pull/12082
```release-note
NONE
```
=> [dashboard] allow to open desktop links on app domain

components/supervisor/frontend/src/ide/heart-beat.ts, components/supervisor/frontend/src/index.ts, components/supervisor/frontend/src/shared/loading-frame.ts
An idea to redirect always on parent app domain, i.e. gitpod.io, via iframe to suppress popup on each new workspace start.
**Important** We need to consider a case if a user does not have yet app, but allowed pop-up always for some reason, i.e. for another IDE.
Fixes #
- Select VS Code Desktop in settings.
- Start one workspace, click allow always in pop-up.
- Start another workspace, check that pop-up does not come anymore. VS Code Desktop is opened automatically.
```release-note
Enable allowing redirect to Desktop IDEs for all workspaces.
```
=> redirect to desktop IDE on app domain

components/ws-daemon/pkg/internal/session/workspace.go
The initial workspace failed at the beginning, so the workspace's persistent state location never exist.
Fixes #11715
Not sure, but we did see some nodes path `/var/gitpod/workspaces` with the folders
- `<instance-id>`
- `<instance-id>-daemon`
but without the corresponding `<instance-id>.workspace.json`.
```release-note
None
```
None
=> ws-daemon: ignore error when workspace persistent state location not exist

components/dashboard/src/teams/TeamUsage.tsx
Extends the results per page to 50.
Relates #11640
```release-note
NONE
```
=> [usage] Increase results per page to 50

components/server/src/workspace/workspace-starter.ts
Fixes https://github.com/gitpod-io/gitpod/issues/11823
```release-note
none
```
=> [server] fix using snapshotBucketId when it is undefined or empty

install/kots/manifests/kots-links.yaml
Whilst scouring the KOTS documentation, I discovered we have the ability to add [custom links](https://docs.replicated.com/vendor/admin-console-adding-buttons-links#add-a-button-to-the-dashboard) to the KOTS dashboard. I've added a couple as these could be quite useful for users.
This is what occurred to me, but the content/ordering is entirely configurable. Probably best for @lucasvaltl to decide on what (if anything) goes here.
Create a KOTS instance and this is on the homepage once installed
```release-note
[kots]: add useful links to the KOTS dashboard
```
=> [kots]: add useful links to the KOTS dashboard

components/server/src/workspace/workspace-starter.ts
This is a leftover/oversight from long ago. It does not make sense to mark an instances as `failed` when not also setting it to `stopped`.
Fixes #12138
```release-note
Mark workspace's whose image builds failed as `stopped`
```
=> [server] Mark instances whose image build failed as "stopped"

components/dashboard/src/index.css, components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Don't forcefully set spending limit to '1' when the input is empty.
Fixes https://github.com/gitpod-io/gitpod/issues/12091
1. Upgrade a team to usage-based billing
2. Update the spending limit
3. Delete everything in the input (in preparation for entering a new value)
4. The input should not forcefully reset to the value `1` when empty
```release-note
NONE
```
=> [dashboard] Don't forcefully set spending limit to '1' when the input is empty

components/supervisor/pkg/supervisor/services.go, components/supervisor/pkg/supervisor/supervisor.go, components/supervisor/pkg/supervisor/top.go, components/supervisor/pkg/supervisor/top_test.go
Makes the resource status request more resilient by avoiding calling syncronously upstream to fetch resource status at every requests. With more clients adding functionalities such as `gp top` or workspace cpu/memory in jetbrains ide control center, the risk of getting rate-limited is guaranteed. 
With the approached used in this PR, we retrieve data from upstream at every second and when clients request it, we return the latest available data. Additional, an exponential backoff strategy is in place to be more resilient.
Fixes #12083
Compare how [this prev](https://afalz-1208328e4f3122.preview.gitpod-dev.com) env behaves in comparison with gitpod.io by running a workspace and run `watch -n 0.1 gp top`. In gitpod.io (prod) it will almost immediately fail by returning gRPC errors because …
=> [supervisor] Make resource status request more resilient

components/ws-manager/pkg/manager/monitor.go
Due to a retry timing issue, there were cases where the workspace had already been successfully backed up on the ws-daemon side, but ws-manager was trying to back it up again with an error.
[More detail](https://github.com/gitpod-io/gitpod/issues/11710#issuecomment-1210375041)
Fixes https://github.com/gitpod-io/gitpod/issues/11710
Is there any good way to do this?
```release-note
Fixed a rare case in which prebuild was terminating successfully but failing
```
=> ws-manager: Fix consistency of disposed ws between ws-daemon and ws-manager

components/gitpod-protocol/package.json, components/image-builder-api/typescript/package.json, components/server/package.json, components/ws-manager-bridge/package.json, yarn.lock
Most gitpod components where using `google-protobuf` with version `3.19.1`, so I just updated the remaining components 
```release-note
NONE
```
=> Match google-protobuf version across components

components/ws-manager-bridge/src/cluster-service-server.ts
Return the instance ids that are preventing deregistration of the cluster
`FATA[0000] rpc error: code = Unknown desc = cluster is not empty (2 instances remaining)[21d014d2-f2a4-4085-bd7c-2835f2e58b79,8c66ad5d-13d0-4cd7-9894-5a7e01d46fa1] `
n.a.
- Register workspace cluster for preview environment with `gpctl clusters register --name ws-cluster 1 --hint-cordoned --hint-govern --tls-path ./wsman-tls/ --url [workspaceClusterIP]:8081`
- Create workspaces and set their region to the workspace-cluster
- Try to deregister workspace cluster with `gpctl clusters deregister --name ws-cluster`
```release-note
None
```
=> [bridge] Return instances preventing deregistration

components/gitpod-protocol/src/plans.ts, components/server/ee/src/billing/entitlement-service-chargebee.ts, components/server/ee/src/billing/entitlement-service-license.ts, components/server/ee/src/billing/entitlement-service-ubp.ts, components/server/ee/src/billing/entitlement-service.ts, components/server/src/billing/entitlement-service.ts
If a user is on the free tier, we want to limit the network connections that they can create.
Fixes https://github.com/gitpod-io/gitpod/issues/12161)
```release-note
None
```
=> [billing] Check if network connections should be limited

components/ide/code/codehelper/main.go
We have many false positive errors for repos without VS Code extensions in .gitpod.yml [[1](https://console.cloud.google.com/errors/detail/CNzsobWPtZqyzgE?project=workspace-clusters)] This PR does not treat them as error.
Fixes #
- Switch to latest VS Code: https://ak-code-em8be1e68403.preview.gitpod-dev.com/preferences
- Start a workspace without VS Code extensions: https://ak-code-em8be1e68403.preview.gitpod-dev.com/#https://github.com/akosyakov/parcel-demo
- It should start without any issues. Check workspace lgos that there is no `config.vscode field not exists` error anymore.
- Start a workspace with VS Code extensions: https://ak-code-em8be1e68403.preview.gitpod-dev.com/#https://github.com/gitpod-io/spring-petclinic
- It should start without any issues, Java extensions should be …
=> [code] don't report empty vscode extensions as error

components/dashboard/src/Menu.tsx, components/dashboard/src/settings/Preferences.tsx, components/dashboard/src/teams/TeamBilling.tsx, components/gitpod-protocol/src/billing-mode.ts, components/server/ee/src/billing/billing-mode.spec.db.ts, components/server/ee/src/billing/billing-mode.ts, components/server/ee/src/billing/billing-service.ts, components/server/src/user/user-service.ts, components/server/src/workspace/workspace-starter.ts
This PR includes a couple of alignments around BillingMode. It's reviewable by commit. As all changes share the same context I think it does not make sense to further split this up. :lotus_position: 
1. Improved tests + additional tests (no change in behavior)
2. Make "workspace classes" usable if either of these are true:
1. You have the "workspace_classes" FF enabled
2. The method `BillingMode.canSetWorkspaceClass` returns `true` for your BillingMode
3. Small fix to BillingModes: Only have _paid_ UBP team memberships override existing Chargebee memberships
4. Handle bad "CostCenter" error, in case you have not yet set a team spending limit for whatever reason
5. ~Make `moment` time offset work on Usage List View~ removed
6. Fix wrong usage of `findCustomerByUserId` and replace with …
=> Polish handling of BillingMode

components/server/ee/src/prebuilds/github-app.ts, components/server/ee/src/prebuilds/gitlab-app.ts
This PR should fix handling of webhook events with large amount of changes attached as payload.
Fixes #11578
* Setup a projects and push a change to the repo. Webhook events should be received as usual.
* Create an artificial change with a ton of files modified/added/removed. See that webhook events are captures without errors logged in server.
```release-note
NONE
```
=> [server] trim rawEvents to avoid DB pollution

components/server/ee/src/prebuilds/prebuild-manager.ts, components/server/ee/src/workspace/workspace-starter.ts, components/server/src/workspace/workspace-starter.ts
ensure that user that has PVC enabled will not force prebuilds to use them on projects that don't have PVC turned on
Fixes #11769 
```release-note
none
```
=> [server] ensure that user that has PVC enabled will not force prebuilds into PVC use

.werft/observability/monitoring-satellite.ts
This PR does 2 things:
* Generate CRDs from Jsonnet, and apply them so we can use the CLI installer
* Updates the configuration to match the one used by jsonnet
Fixes #12036
To get a fresh installation, you can delete the previous previews as much as needed with
```
kubectl --context harvester delete ns preview-as-cli-installer-crd
```
To spin up a fresh new environment with the new CLI, run the command from inside the workspace:
```
werft run github -f -a with-preview=true -a observabilityInstallationMethod=observability-installer
```
The CLI is hardcoded to install the observability stack in the `monitoring-satellite` namespace, while jsonnet installs in the `default` namespace.
After running the werft job, you can install the preview kubecontext with `previewctl install-context`. If …
=> Generate and apply CRDs for observability CLI installation method

components/server/src/workspace/workspace-starter.ts
Fixes #11770 
```release-note
none
```
=> [server] fix workspace PVC always restored from prebuild even if backup already exists

components/usage/pkg/apiv1/usage-report.go, components/usage/pkg/apiv1/usage_test.go
There was a disconnect between when we determined `now`, and when we used it in combination with start-/stopTimes that - based on runtime behavior - _could_ lead to negative usage being calculated.
Fixes #12064 
- [open a workspace](https://gitpod.io/#https://github.com/gitpod-io/gitpod/pull/12178)
- `leeway build components/usage:init-testdb && (cd components/usage && go test -v ./...)`
I did not manage to provoke this situation in preview envs, mainly due to data volume I guess.
It's still worth testing that usage still works as expected: 
- signup
- create a team starting with `Gitpod-...`
- import a project
- start a workspace on that project
- go to the usage view and notice the correct usage being displayed
```release-note
NONE
```
=> [usage] Test for and fix negative credits in GenerateUsageReport

components/dashboard/src/components/BillingAccountSelector.tsx, components/dashboard/src/settings/Billing.tsx
- Temporarily disable selecting personal account for usage-based billing attribution
- Improve usage-based billing account selection UX
Fixes https://github.com/gitpod-io/gitpod/issues/12097
Fixes https://github.com/gitpod-io/gitpod/issues/11498
1. Enable usage-based billing for your personal account
2. Go to `/billing`
3. You should not be able to select yourself (i.e. your individual user account) as a billing account
```release-note
NONE
```
=> [dashboard] Improve explicit usage-based billing attribution UX

install/installer/cmd/testdata/render/customization/config.yaml, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/config.yaml, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/minimal/config.yaml, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/config.yaml, install/installer/cmd/testdata/render/statefulset-customization/output.golden
That allows to compare the output.golden files of different tests to see the differences the input produces. Different domains lead to too much noise.
```release-note
NONE
```
=> [installer] Use same domain for all tests

install/kots/manifests/kots-config.yaml
Now that #11954 has been merged and the [`help_text` fix](https://github.com/replicated-collab/replicated-gitpod/issues/29) has been merged by Replicated, I noticed that the old label limitation workaround is still documented in KOTS dashboard
View in KOTS
```release-note
[kots]: remove help text documenting the limitation on custom labels
```
=> [kots]: remove help text documenting the limitation on custom labels

install/kots/manifests/kots-config.yaml
This PR updates the `reg_incluster_storage_s3*` options to
only be enabled both when `incluster` is enabled, and `s3` is
selected, instead of only the latter being used currently.
https://www.loom.com/share/2278f177783d4b9986fe3a2f2b316537
Fixes https://github.com/gitpod-io/gitpod/issues/10257
Follow steps in https://www.loom.com/share/1cbe5fb5122b499797b41aeefbba8290, and
see that it does not happen
```release-note
[kots] show `registry_s3` options only when `incluster` is enabled
```
=> [kots] show `registry_s3` options only when `incluster` is enabled

install/kots/manifests/gitpod-installer-job.yaml, install/kots/manifests/kots-config.yaml
This PR updates the `kots` UI to add a new config option to upload registry
credentials irrespective of the registry being used, which is then merged
into a single `config.json` file and passed as the registry secret which
is then used across the workspace image builder components.
Fixes https://github.com/gitpod-io/gitpod/issues/12136
Upload a `dockerconfigjson` file through the new option, 
and see those credentials in the secret by running
```
kubectl -n gitpod get secret builtin-registry-auth --output="jsonpath={.data.\.dockerconfigjson}" | base64 -d
```
```release-note
[kots] Allow users to upload a `.docker/config.json` file
```
=> [kots] Allow users to upload a `.docker/config.json` file

components/dashboard/src/start/CreateWorkspace.tsx
This will update the spending limit modal, following the updates in https://github.com/gitpod-io/gitpod/issues/11927#issuecomment-1210813607 and https://github.com/gitpod-io/gitpod/issues/11927#issuecomment-1211812281.
See also [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1660213626025459?thread_ts=1660138187.580269&cid=C02EN94AEPL) (internal).
Fixes https://github.com/gitpod-io/gitpod/issues/11927
1. Enable billing or a team
2. Set a low spending limit
3. Open a workspace
```release-note
Update spending limit modal on workspace start
```
=> Update spending limit modal on workspace start

components/ws-daemon/pkg/content/initializer.go
Destination in content.json was ignored.
https://github.com/gitpod-io/gitpod/blob/3102716172335ed1215627bef1abcba836bfc7e8/components/ws-daemon/pkg/content/initializer.go#L162
Fixes #
Can open a workspace
```release-note
None
```
=> ws-daemon: Proper use of `content.json`

components/ws-manager/pkg/manager/annotations.go, components/ws-manager/pkg/manager/monitor.go, components/ws-manager/pkg/manager/testdata/actOnPodEvent_workspace_startup_failed.golden
The `StartDisposal` annotation so far has only shown that it has started, so we will provide more detailed information.
Fixes #
1. Open a workspace
2. Stop a workspace with monitoring workspace pod's annotation
```release-note
NONE
```
=> ws-manager: Provide more detail of DiposalStatus.

components/supervisor/pkg/supervisor/supervisor.go
Fixes content init when using PVC.
Fixes #
```release-note
none
```
=> [supervisor] fix chown of /workspace when using PVC

components/content-service/pkg/layer/provider.go, components/ws-manager/pkg/manager/create.go
This PR contains two fixes:
1. Re-enables PVC support in ws-manager
2. Fixes PVC not working when restoring from prebuild.
Fixes #
Needs following merged and deployed into webapp prod prior to merging:
:heavy_check_mark: https://github.com/gitpod-io/gitpod/pull/12105
:heavy_check_mark: https://github.com/gitpod-io/gitpod/pull/12165
:heavy_check_mark: https://github.com/gitpod-io/gitpod/pull/12180
```release-note
none
```
=> re-enable PVC support

components/usage/pkg/apiv1/usage-report.go, components/usage/pkg/apiv1/usage.go, components/usage/pkg/apiv1/usage_test.go, components/usage/pkg/db/workspace_instance.go, components/usage/pkg/db/workspace_instance_test.go
Change instance runtime calculation:
- Start: use startedTime instead of creationTime
- don't count startup time at all, e.g. scale up, image build/pull, ...
- don't double-count when waiting for a prebuild to finish
- Stop: use stoppingTime instead of stoppedTime
- don't count stopping time at all, e.g. backup time
Fixes https://github.com/gitpod-io/gitpod/issues/12177
1. Unit tests
```release-note
NONE
```
=> [usage] Change instance runtime calculation: creationTime → startedTime, stoppedTime → stoppingTime

components/dashboard/src/projects/ProjectVariables.tsx
Minor truncation fix for project-specific environment variables.
Fixes #12172
1. Add a project
2. Go to project variables
3. Add a variable with a long name
|-|-|
| <img width="760" alt="variables-a-before" src="https://user-images.githubusercontent.com/120486/185663868-bc10acee-7f18-45ca-9735-36224809b3e5.png"> | <img width="760" alt="variables-a-after" src="https://user-images.githubusercontent.com/120486/185663875-495bc82f-bbf7-4882-b2aa-c858ef16aa65.png"> |
| <img width="760" alt="variables-b-before" src="https://user-images.githubusercontent.com/120486/185663884-fd7c7db5-e1e8-4b7b-b804-51c1df8fdd75.png"> | <img width="760" alt="variables-b-after" src="https://user-images.githubusercontent.com/120486/185663890-2f2529be-a70f-46c2-a28b-bcab77caec5c.png"> | …
=> Truncate project environment variable name

install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/config.yaml, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/ws-manager/configmap.go, install/installer/pkg/config/v1/config.go
See https://gitpod.slack.com/archives/C01KLC56NP7/p1660828231371779
Lets walk through the scenarios:
- Self-hosted
- The installer surface is the same as before workspace classes
- MinLimit and BurstLimit will be set to the value specified in workspace.resources.limits.cpu
- The BurstLimit will be used to set the Kubernetes limit (i.e. workspace.resources.limits.cpu as before)
-- > most customers are done at this point
- If customers also have the ws-daemon cpu limiting enabled
- Limiting will be applied based on the configuration in ws-daemon
- It will not use the annotation based limiting because the annotation will not be set on the workspace pod. This would require that the workspace_classes feature flag is enabled. This is not the case on self-hosted.
- SaaS
- Customers for which …
=> Ensure workspace classes to not break selfhosted customers

dev/ready-probe-labeler/main.go
Do not use tick value as timeout for the probe URL and instead set one with the one defined in `waitForURLToBeReachable` 
Fixes #12220
- Check `node-labeler` container logs in `registry-facade` pod
```
{"level":"info","message":"Starting node labeler...","serviceContext":{"service":"ready-probe-labeler","version":""},"severity":"INFO","time":"2022-08-22T15:33:55Z"}
{"label":"gitpod.io/registry-facade_ready_ns_default","level":"info","message":"adding label to node","serviceContext":{"service":"ready-probe-labeler","version":""},"severity":"INFO","time":"2022-08-22T15:34:12Z"}
{"fields.time":16.043640853,"level":"info","message":"node label updated","node":"g1fa206bed499b8bdc9c662.workspace-preview.gitpod-io-dev.com","serviceContext":{"service":"ready-probe-labeler","vers …
```
=> [ready-probe-labeler] Refactor timeout handling

components/ws-manager/pkg/manager/monitor.go
There were several workspaces content-initializer was taking a very long time to start. [^log1]
As a result, it seemed that stop requests sometimes came before the content-initializer.[^log2]
If content-initializer runs on ws-daemon after the workspace pod has disappeared, it should not work well because there should be no workspace directory. The lock on the initializerMap was common in ws-manager. This could cause longer locks and slower content-initializer startup. This has been improved.
[^log1]: [internal log1](https://console.cloud.google.com/logs/query;query=jsonPayload.instanceId%3D%225663503e-a764-4d88-8657-0c7659594ee9%22;timeRange=2022-08-17T22:11:00.000Z%2F2022-08-18T03:49:00.000Z;summaryFields=jsonPayload%252Flocation:false:32:beginning;cursorTimestamp=2022-08-18T03:27:45Z?pro …
=> ws-manager: Replace initializerMapLock with sync.Map

components/docker-up/BUILD.yaml
Sync fork https://github.com/gitpod-io/compose/compare/v2.8.0...v2.10.0
- Run `docker-compose --version`, should return `Docker Compose version v2.10.0-gitpod.0`
```release-note
Update docker compose to v2.10.0
```
=> Update docker-compose to v2.10.0

install/kots/manifests/gitpod-installer-job.yaml
As we're auto-detecting the containerd location in the installer job, we should be on a "workspace" node so this ensures that the installer job is run on the correct node.
This is an edge case and not one we've yet been caught by, but it's possible that the nodes are configured differently (as with SaaS) so it's something I think we should do.
Install via KOTS.
```release-note
[kots]: give installer same node affinity as ws-daemon
```
=> [kots]: give installer same node affinity as ws-daemon

components/usage/pkg/db/cost_center.go, components/usage/pkg/db/cost_center_test.go
Adds the model for d_b_cost_center in the Usage component.
Relates #12264
Under `/components/usage/pkg/db` run `go test`
```release-note
NONE
```
=> [usage] Add Go definition for d_b_cost_center

components/dashboard/src/teams/TeamUsage.tsx
Make bigger amounts of used credits more easily readable by using the browsers locale to format the number. This also solved an issue where trailing zeros would appear if the number was for example exactly `.2`. This may be intentional though and if so, it is easy to fix.
This change does not change how values are rounded, both this method and the previous one do it in the same way.
None I am aware of.
TBD. Easier to test in prod 😆 
```release-note
NONE
```
=> Use `toLocaleString` with usage of credits

components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodProjectManager.kt, components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
Currently, when we open a Java Workspace, it selects Java 17 as SDK by default:
This PR changes it to use the JDK preferred by the user (the ones defined in JAVA_HOME or PATH environment variables), in case it's not defined in a configuration file yet (e.g. `.idea/misc.xml`):
`jdkTable.preconfigure()` will set the `ProjectRootManager.getInstance(project).projectSdk` to a specific version if there’s an `.idea/misc.xml` file defining the JDK for the project.
And if there’s no configuration file, it will add a JDK to the list of available SDKs but won't set up the project SDK. That's where we set them up with the default JDK version found by `JavaHomeFinder.`
Fixes #12030
2. Choose the _Stable_ version of IntelliJ IDEA as your …
=> [jb] Use the default Java SDK version when there's no explicit configuration for it yet

install/infra/modules/eks/dns.tf, install/infra/modules/eks/local.tf, install/infra/modules/eks/output.tf, install/infra/modules/eks/variables.tf, install/infra/single-cluster/aws/variables.tf
In the `EWS` terraform module we are by default creating `AWS cert manager` entries, which are not essentially needed since by default our reference architecture suggests usage of `cert-manager`. Hence this PR makes the creation of `AWS cert manager` optional using the flag `user_aws_cert_manager`.
As of the terraform module corresponding the reference architecture, in a future PR, I will provide an option to use `aws cert manager` if the user would rather use that instead of `cert-manager` in which case, in the output, we will provide config patch necessary to post process the service annotation to use `ACM`.
Fixes #
Following the [README](https://github.com/gitpod-io/gitpod/tree/main/install/infra/single-cluster/aws#initialize-terraform-backend-and-confirm-the-plan) for the terraform …
=> [terraform] Make AWS certificate manager optional

components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Clarify that spending limit is in credits
Fixes https://github.com/gitpod-io/gitpod/issues/12115
1. Upgrade a team to Usage-Based Billing
2. Try updating the Spending Limit
```release-note
NONE
```
=> [dashboard] Clarify that spending limit is in credits

operations/observability/mixins/workspace/rules/components/workspaces/alerts.libsonnet
This alert sometimes fires incorrectly due to the number of workspaces that we have running in the cluster.
This is a short term mitigation for this alert.
Long term mitigation could be re-thinking on how we alert on this (change it to % of workspaces in the cluster for example). 
Fixes #
```release-note
none
```
=> [alerts] increase GitpodWorkspaceStuckOnStopping for time to 30min to reduce flakiness

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/common/common.go, install/installer/pkg/components/cluster/clusterrole.go, install/installer/pkg/components/cluster/objects.go, install/installer/pkg/components/cluster/podsecuritypolicies.go, install/installer/pkg/components/image-builder-mk3/clusterrole.go, install/installer/pkg/components/image-builder-mk3/objects.go, install/installer/pkg/components/registry-facade/objects.go, install/installer/pkg/components/registry-facade/podsecuritypolicy.go, install/installer/pkg/components/workspace/objects.go, install/installer/pkg/components/workspace/podsecuritypolicies.go, install/installer/pkg/components/workspace/role.go, install/installer/pkg/components/ws-daemon/clusterrole.go, install/kots/manifests/gitpod-installation-status.yaml, install/kots/manifests/gitpod-installer-job.yaml
Reverts gitpod-io/gitpod#12173
Caused issue in SaaS due to GKE having PodSecurityPolicies enabled on cluster - see [channel](https://gitpod.slack.com/archives/C03UQ58RG0M)
```release-note
Revert "[installer]: remove all podsecuritypolicies" #12313
```
=> Revert "[installer]: remove all podsecuritypolicies"

components/ws-manager/pkg/manager/monitor.go
It is not needed and only makes it more difficult to understand traces.
Plus it logs errors that are not actually errors, like NotFound, which is handled by parent function.
So this should clean up filtering for traces that actually have a valid error
Fixes #
```release-note
none
```
=> remove trace from retryifUnavailable

components/ws-manager/pkg/manager/monitor.go
Related to https://github.com/gitpod-io/gitpod/issues/12318
```release-note
none
```
=> [ws-manager] add additional logging into finalizeWorkspaceContent

components/ide-metrics-api/go/config/config.go, components/ide-metrics/cmd/run.go, components/ide-metrics/config-example.json, components/ide-metrics/pkg/server/server.go, components/ide-metrics/pkg/server/server_test.go, install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/ide-metrics/deployment.go
Prometheus metrics' lables are defined when metric init and will return error when num of labels not fit. So if we change configmap to add labels, previous clients' requests will failed.
This PR make it supports with dynamic labels
Context see also https://github.com/gitpod-io/gitpod/pull/12222#issuecomment-1223695779
Fixes #
Open this PR/branch with Gitpod
Same as title
```
cd components/ide-metrics
go run main.go --config config-example.json run
curl -X "POST" "http://localhost:3000/metrics-api/metrics/counter/add/gitpod_test_counter" \
-H 'Content-Type: application/json; charset=utf-8' \
-d $'{
"value": 12,
"labels": {}
}'
curl http://localhost:9500/metrics
```
See https://github.com/gitpod-io/gitpod/pull/12271#issue-1346547021
```release-note
NONE
```
=> [ide-metrics] allow dynamic labels for metrics

components/usage/pkg/apiv1/usage.go, components/usage/pkg/controller/reconciler.go
Implements returning of ReportID in ReconcileUsage responses.
* Depends on https://github.com/gitpod-io/gitpod/pull/12333/files
```release-note
NONE
```
=> [usage] Return report_id from ReconcileUsage RPC

components/common-go/cgroups/v2/cpu.go, components/common-go/cgroups/v2/cpu_test.go, components/ws-daemon/pkg/iws/iws.go
Prevent divide by zero error
Fixes https://github.com/gitpod-io/gitpod/issues/12295
```release-note
Prevent divide by zero error in workspace info service
```
=> [ws-daemon] Prevent divide by zero error

install/installer/cmd/render_test.go, install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/config.yaml, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/agent-smith/role.go, install/installer/pkg/components/cluster/clusterrole.go, install/installer/pkg/components/cluster/podsecuritypolicies.go, install/installer/pkg/components/image-builder-mk3/clusterrole.go, install/installer/pkg/components/registry-facade/clusterrole.go, install/installer/pkg/components/registry-facade/podsecuritypolicy.go, install/installer/pkg/components/workspace/podsecuritypolicies.go, install/installer/pkg/components/workspace/role.go, install/installer/pkg/components/ws-daemon/clusterrole.go, install/installer/pkg/config/v1/experimental/experimental.go, install/kots/manifests/gitpod-installation-status.yaml, install/kots/manifests/gitpod-installer-job.yaml
This is similar to #12173 for most users, however the current Gitpod.io clusters still have pod security policies enabled. It was decided in the incident post-mortem that, as we still need this change for self-hosted users, this change should be conditionally applied via an `experimental` flag.
Fixes #12314
As per #12173. The `use-pod-security-policy` golden files are intended to prove no changes have been made when using the experimental flag.
```release-note
[installer]: conditionally remove pod security policies
```
=> [installer]: conditionally remove pod security policies

install/installer/pkg/config/v1/config.go, install/installer/pkg/config/v1/experimental/experimental.go
Marks the `experimental.common.usePodSecurityPolicies` as deprecated and shows a warning if enabled.
```bash
Deprecated config parameter: experimental.common.usePodSecurityPolicies=true
```
Render the YAML
```release-note
[installer]: show deprecation warning if using podsecuritypolicies
```
=> [installer]: show deprecation warning if using podsecuritypolicies

components/ws-daemon/shiftfs-module-loader/entrypoint.sh
Disable build of `shiftfs` module if the kernel in the node already provides it.
```release-note
NONE
```
=> [ws-daemon] Check if the shiftfs module already exists

components/ws-daemon/pkg/internal/session/workspace.go
This was quite fun to hunt it down.
When calling WaitForInit we will wait for `operatingCondition` to broadcast to unlock us.
There are two places where broadcast is being done:
`MarkInitDone` that changes `state` to `WorkspaceReady`
`Dispose` that changes `state` to `WorkspaceDisposed`
If workspace fails during `InitWorkspace`, then its state will be disposed. 
We call InitWorkspace during `CREATING` phase, and then we `WaitForInit` in `INITIALIZING` state.
So if InitWorkspace failed, we incorrectly would mark workspace as ready, causing all types of issues down the line.
Fixes #12357
Fixes #11713
```release-note
none
```
=> [ws-daemon] when WaitForInit ensure that state is indeed ready

components/image-builder-bob/pkg/builder/builder.go
The retry to connect to the buildkit was too fast. At least in the current preview environment resources sometimes gave up before the buildkit was up and running.
Relates #12248
Pass `TestBaseImageBuild/database/it_should_build_a_base_image` on the preview env
(Maybe the test doesn't pass, but at least it fails not a connection error to buildkit)
```release-note
More reliably connect to buildkit during image builds
```
=> image-builder-bob: Introduce backoff to connect to buildkit

components/gitpod-cli/cmd/tasks-stop.go, components/gitpod-cli/go.mod, components/gitpod-cli/go.sum
I would like to introduce this new cmd `gp tasks stop` to stop 1 or all workspace tasks. It can be useful when someone wants to run some new tasks and don't care about all pre-defined ones or quickly kill some long-living process running in another task, for example.
I am not sure if the approach is too naive, but it seems to work.
There is no real issue as this is more of a "weekend idea". Perhaps it could be considered slightly related to [inner loop](https://github.com/gitpod-io/gitpod/issues/7671).
1. Go to [this prev env](https://afalz-gp-tasks-stop.preview.gitpod-dev.com)
2. Open the gitpod's repo
3. Open a new terminal and run `gp tasks stop`, `gp tasks stop <id>` and `gp tasks stop --all`
4. Observe how all tasks are terminated
```release-note
Gitpod CLI: New command `gp tasks …
```
=> [gitpod-cli] New cmd `gp tasks stop` 🧪🔬

install/infra/modules/gke/main.tf, install/infra/modules/gke/variables.tf
in line with https://github.com/gitpod-io/website/pull/2627/files, this changes the default node size for workspace nodes to 360 GB as a temporary fix while we discuss further changes. 
Fixes #
```release-note
NONE
```
=> Change workspaces disk size to 360 GB

install/infra/single-cluster/aws/terraform.tfvars
- Creates sensible defaults for domain name and cluster name in .tfvar file for the single cluster reference archtitecture terraform module. In line with [internal guidelines](https://www.notion.so/gitpod/b525670c23ee47d896802e1089808ec5#474093e901074e62bf0eef449a3792f3).
- Highlights the need to change the ami_id
Fixes #
- Check changes ensure they don't break anything
```release-note
NONE
```
=> add sensible defaults to single cluster aws .tfvars

components/usage/pkg/apiv1/usage.go, components/usage/pkg/db/cost_center.go, components/usage/pkg/db/cost_center_test.go
Implements the GetCostCenter RPC.
The use of this RPC in UpdateInvoices() will be a separate PR.
Relates #12264
Under `/components/usage/pkg/db` run `go test`
```release-note
NONE
```
=> [usage] Implement GetCostCenter RPC

components/ide/jetbrains/backend-plugin/BUILD.yaml, components/ide/jetbrains/image/BUILD.yaml, components/ide/jetbrains/image/download/BUILD.yaml, components/ide/jetbrains/image/download/download.sh, components/ide/jetbrains/image/leeway.Dockerfile
This PR separates download of JB backend from building JB images. It reduces the rebuild time to 15 mins instead of 25mins for the change of JB backend plugin.
Unfortunately copy step during image build gets invalidated for some reasons, so even we just change the backend plugin, copying of backend itself happens for all 8 images and it adds like 10 mins unnecessary. I will think later how to optimize father by probably decoupling deliver of plugins.
Related to https://github.com/gitpod-io/gitpod/issues/12268
- See this job https://werft.gitpod-dev.com/job/gitpod-build-ak-jb-backend-via-proxy.8 after test change.
- Test JB images whether they are working and functionality in place.
/hold
to remove test commit
```release-note
NONE
```
=> optimize build of JB images

components/gitpod-protocol/go/gitpod-service.go, components/gitpod-protocol/go/mock.go, components/server/src/workspace/workspace-starter.ts
Add missing function `getSupportedWorkspaceClasses` for golang lib
Previous PR of PR https://github.com/gitpod-io/gitpod/pull/12338
Fixes #
Test in PR https://github.com/gitpod-io/gitpod/pull/12338 which based on this branch `hw/ws-cls`
```release-note
NONE
```
=> [gitpod-protocol] add missing method in golang

operations/observability/mixins/cross-teams/dashboards/gitpod-overview.libsonnet
No data is shown if there is no data found, check the existing eu63 cluster.
was: 
is:
Fixes #
None
```release-note
None
```
None
=> observability: assign default zero if no data found

.werft/installer-tests.ts, install/tests/Makefile
This PR updates the supported Kubernetes versions for automated tests. AKS 1.21 has reached its end of life in July and hence we support AKS versions 1.22 through 1.24. 
In the case of EKS, We had a bug introduced previously by adding `1.23` before official ubuntu image was out. Now that it is, this PR adds that too.
Fixes #
You can try running the following
```
werft run github -j .werft/eks-installer-tests.yaml -a skipTests=true
werft run github -j .werft/aks-installer-tests.yaml -a skipTests=true
```
```release-note
NONE
```
=> [installer-tests] Update supported k8s versions for AKS and EKS

.werft/util/kubectl.ts
Make the error diagnosis of pods to starting more detailed. This can happen when preview envs don't start.
Fixes # https://gitpod.slack.com/archives/C03E52788SU/p1661435286514459?thread_ts=1661386684.170339&cid=C03E52788SU
```release-note
NONE
```
=> Make error message more detailed

components/usage/pkg/stripe/stripe.go
Fixup for a late change in the PR #12377
https://github.com/gitpod-io/gitpod/pull/12377#issuecomment-1227272819
Verify that the usage component is not reporting the error from https://github.com/gitpod-io/gitpod/pull/12377#issuecomment-1227272819 by following the standard procedure on checking the spending limit from the app:
* creating a team with "Gitpod" in its name
* enable UB and set a low spending limit
* start a workspace and let it run
* observe the notification is shown once the limit is reached:
```release-note
NONE
```
=> Fixup GetUpcomingInvoice

operations/observability/mixins/cross-teams/dashboards/gitpod-overview.libsonnet
The `Workspace Phases` section of the overview dashboard is hard to read, because type and phase values are not grouped. This started when we introduced additional node pools that host the same type and phase for workspaces.
Before:
After (notice the `type, phase` do not repeat, and have been summed together):
Fixes # n/a
Compare the output of before:
`gitpod_ws_manager_workspace_phase_total{cluster=~"eu63", phase!="RUNNING"}`
With after:
`sum by (type, phase)(gitpod_ws_manager_workspace_phase_total{cluster=~"eu63", phase!="RUNNING"})`
Also, here you can see I started 8 workspaces in this preview environment, stopped them all, and 8 showed as stopping:
```release-note
NONE
```
=> [observability] - clean-up Overview Dashboard's Workspace Phases panel

install/infra/modules/eks/variables.tf, install/infra/single-cluster/aws/terraform.tfvars, install/infra/single-cluster/aws/variables.tf, install/infra/single-cluster/gcp/terraform.tfvars, install/tests/main.tf
This PR updates the default image provided in .tfvars file for EKS. You can find all the latest supported AMIs here https://cloud-images.ubuntu.com/docs/aws/eks/
Fixes #
```
werft run github -j .werft/eks-installer-tests.yaml -a skipTests=true -a deps=external
```
```release-note
NONE
```
=> update the AMI image for k8s 1.22

components/docker-up/dependencies.sh
https://github.com/opencontainers/runc/releases/tag/v1.1.4
NONE
Open a workspace and run docker command
```release-note
Upgrade runc to 1.1.4
```
=> docker-up: Upgrade runc to 1.1.4

test/tests/components/image-builder/builder_test.go
Retry when image-builder is unavailable for some reason. I guess lack of resource.
Relates #12248
Pass TestBaseImageBuild/database/it_should_build_a_base_image on the preview env
```release-note
none
```
=> tests: Retry when image-builder is unavailable for some reason

components/gitpod-db/src/typeorm/migration/1661492836561-WorkspaceInstanceUsageLastModified.ts
Adds a required `_lastModified` field to `d_b_workspace_instance_usage` such that we can enable db_sync for it
Fixes #
```release-note
NONE
```
=> [usage] Add _lastModified column to d_b_workspace_instance_usage

install/kots/manifests/gitpod-installer-job.yaml, install/kots/manifests/kots-config.yaml
Follow upto https://github.com/gitpod-io/gitpod/pull/12174
This PR updates the installer logic to also load the auth's reigstry
URL's into `.containerRegistry.privateBaseImageAllowList`.
Fixes #
```release-note
[kots] load dockerConfigJson reigstry names into `privateBaseImageAllowList`
```
=> [kots] load dockerConfigJson reigstry names into `privateBaseImageAllowList`

.werft/jobs/build/installer/installer.ts, components/public-api/go/config/config.go, install/installer/pkg/components/public-api-server/configmap.go, install/installer/pkg/components/public-api-server/configmap_test.go, install/installer/pkg/components/public-api-server/constants.go, install/installer/pkg/components/public-api-server/deployment.go, install/installer/pkg/components/public-api-server/deployment_test.go, install/installer/pkg/components/public-api-server/objects_test.go, install/installer/pkg/config/v1/experimental/experimental.go
Adds config to installer to specify the name of a kubernetes secret to load stripe webhook signing secret from.
Actual usage of the secret will happen in another PR.
Fixes #
Unit tests
```release-note
NONE
```
=> [stripe] Inject Webhook Signing Secret into public-api

components/content-service/pkg/service/usage-report-service.go, components/content-service/pkg/service/usage-report-service_test.go, components/content-service/pkg/storage/storage.go
Implements DownloadURL rpc. This is needed to be able to download a usage report form the usage component.
* Depends on https://github.com/gitpod-io/gitpod/pull/12300
```release-note
NONE
```
=> [content-service] Implement UsageReportService.DownloadURL

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/ws-daemon/configmap.go
Add netlimit to configmap
n.a.
- Create installer config with 
```
networkLimits: 
enabled: true
connectionsPerMinute: 3000
bucketSize: 1000
```
- gitpod-installer render --config deploy/workspace/installer-values.yaml --use-experimental-config > /tmp/render.yaml
- Check output
```release-note
None
```
=> [installer] Add netlimit to configmap

components/content-service/pkg/initializer/git.go, components/supervisor/pkg/supervisor/supervisor.go
- Revert the https://github.com/gitpod-io/gitpod/pull/12238/commits/32a0f897780ac0e7f5dc5e9a5d90ae9e1a8c1d8f
- Fix the files _user:group_ is  `root:gitpod` after `git checkout` operation.
Fixes #12420
- Open preview env and enable the PVC feature flag
- Launch a workspace by PR
- Check all the files and directories under `.git/` folder, the `user:group` is `gitpod:gitpod`
```release-note
experimental: enable the feature flag PVC, the files/folders under .git/ folder user:group permission is incorrect
```
=> content-service: fix incorrect user:group after git operation

components/server/src/prometheus-metrics.ts, components/server/src/workspace/workspace-starter.ts
Counts additional reasons for startWorkspace failures.
fixes #12332
```release-note
NONE
```
=> [server] track more startWorkspace failures

install/infra/modules/eks/kubernetes.tf
- updates throughput and IOPS for workpace nodes for single cluster reference architecture in line with the [guide](https://www.gitpod.io/docs/self-hosted/latest/reference-architecture/single-cluster-ref-arch#kubernetes-cluster)
- updates disk space to 512 gb in line with https://github.com/gitpod-io/website/pull/2630
Fixes https://github.com/gitpod-io/website/pull/2630
- I tested this myself by spinning up infra using the terraform. module, then ensuring Gitpod installs and that the right IOPS and throughput is shown. This installation ran for about 18 h and I was able to start worksapces. 
```release-note
NONE
```
=> [AWS Single Cluster Ref Arch Terraform] Add  IOPS and throughput definition, changed disk size to 360GB to workspace nodes

install/infra/modules/gke/main.tf, install/infra/modules/gke/variables.tf, install/infra/single-cluster/gcp/Makefile, install/infra/single-cluster/gcp/README.md
This PR makes some small changes to GKE terraform module, making it in sync with the reference architecture. The following are the changes:
- Delete the default node pool and create a separate one for `services` workload, since this is what is being done in the reference architrecture
- Set the node count for both services and workspaces workloads
- some minor changes to the terraform output 
Fixes #
Please follow the [GCP README](https://github.com/gitpod-io/gitpod/tree/main/install/infra/single-cluster/gcp#readme) to test this.
```release-note
NONE
```
=> [terraform] Updating terraform GCP module

WORKSPACE.yaml, components/ide-metrics/pkg/server/server.go, components/supervisor/frontend/package.json, components/supervisor/frontend/src/ide/ide-metrics-service-client.ts, components/supervisor/frontend/src/index.ts, install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/ide-metrics/configmap.go
This PR adds error counting of failed VS Code Web resources to track down https://github.com/gitpod-io/gitpod/issues/12107. We investigated one such case at level of GCP Load Balancer and found out that resources are successfully returned by blobserve. [[1](https://gitpod.slack.com/archives/C01KGM9BH54/p1660889332074709?thread_ts=1660861342.562669&cid=C01KGM9BH54)] Something goes wrong in the browser.
https://github.com/gitpod-io/openvscode-server/pull/417 is a PR to instrument critical resources with error handler.
Related to https://github.com/gitpod-io/gitpod/issues/12107
- Open a preview environment workspace
- Cause a load error by for example blocking `workbench.web.main.css` as a source
- Check if error count increased (with label)
- Exec `throw new Error('1')` in browser devTool …
=> Capture errors in supervisor frontend

components/dashboard/src/admin/BlockedRepositories.tsx
Fixes some issues on inside https://github.com/gitpod-io/gitpod/blob/main/components/dashboard/src/admin/BlockedRepositories.tsx. Details are outlined below this comment.
n/a
```release-note
NONE
```
=> Blocked repositories page improvements

.werft/workspace-run-integration-tests.sh
Fix error message that VM is not ready if the first test fails due to panic
e.g. [internal link](https://gitpod.slack.com/archives/C03E52788SU/p1661732967697299)
Relates #12248 
```release-note
NONE
```
=> tests: Fix a bug in the calculation of the # of tests.

test/tests/workspace/docker_test.go
Remaining workspace will affect the performance of subsequent tests
```release-note
None
```
=> tests: Clean a workspace even if a test failed

components/gitpod-db/src/tables.ts
Enabled db-sync for the table. This is blocked on merging and deploying of https://github.com/gitpod-io/gitpod/pull/12424
* Depends on https://github.com/gitpod-io/gitpod/pull/12424 to be deployed
```release-note
NONE
```
=> [db-sync] Add d_b_workspace_instance_usage to db-sync

components/gitpod-protocol/src/util/garbage-collected-cache.ts, components/server/ee/src/billing/entitlement-service-chargebee.ts, components/server/ee/src/billing/entitlement-service-license.ts, components/server/ee/src/billing/entitlement-service-ubp.ts, components/server/ee/src/billing/entitlement-service.ts, components/server/ee/src/container-module.ts, components/server/ee/src/user/account-statement-provider.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/billing/entitlement-service.ts
Fixes caching issue withing AccountStatementProvider. The reasons for this PR is a refactoring 2 weeks back which slightly broke the credit limit check; this PR is meant to bring it back.
Fixes #
- [signup](https://gpl-fix-ac6f1a002ea6.preview.gitpod-dev.com/workspaces) with user A
- signup with user B
- add negative credits to the accounting table for user A so user A should no longer be able to start workspaces
- `INSERT INTO d_b_account_entry SET uid = '<some-id>', userId = '<your-userId>', amount = -50, date = '2022-08-26T13:47:36.360Z', expiryDate ='2022-10-26T13:47:36.360Z', kind = 'credit';`
@AlexTugarev Already did this for [your user](https://gpl-fix-ac6f1a002ea6.preview.gitpod-dev.com/admin/users/c8d4457f-ee0f-4220-9af7-e87360a59669)
- check that:
- user A …
=> Fix AccountStatementProvider 

components/dashboard/src/service/service-mock.ts, components/dashboard/src/settings/selectClass.tsx, components/gitpod-protocol/src/workspace-class.ts, components/server/src/workspace/gitpod-server-impl.ts
Show the workspace class that will be used if no workspace class has been selected yet by the user. 
Fixes https://github.com/gitpod-io/gitpod/issues/12435
- Open the workspace settings in the preview environment
- Check that Default is selected even though now workspace class has been selected yet
```release-note
None
```
=> Fix default workspace class is not selected

components/public-api/go/config/config.go, install/installer/pkg/components/public-api-server/configmap.go, install/installer/pkg/components/public-api-server/constants.go
The current implementation would mount the secret under `/stripe-secret/stripe-webhook-secret` but would set the config path to `secrets/stripe-secret`. This fixes that issue by fixing the path.
Fixes #
```release-note
NONE
```
=> [public-api] Fix Stripe Webhook Secret mount path

components/public-api-server/pkg/server/server.go, components/public-api-server/pkg/webhooks/stripe.go, components/public-api-server/pkg/webhooks/stripe_noop.go, components/public-api-server/pkg/webhooks/stripe_test.go
Implements validation of Stripe Webhooks.
Uses secret already mounted to the public-api-server to perform the validation as per Stripe documentaiton.
* Depends on https://github.com/gitpod-io/gitpod/pull/12462
```release-note
NONE
```
=> [public-api] Validate incoming stripe webhooks

install/infra/single-cluster/aws/README.md
This adds a troubleshooting item that I already ran into twice around setting the wrong image_id
```release-note
NONE
```
=> Add troubleshooting item to AWS SIngle Cluster Ref Arch Readme

.github/pull_request_template.md
Add clarification for werft annotations in the PR description
```release-note
NONE
```
=> Add clarification for werft annotations in the PR description

components/dashboard/src/AppNotifications.tsx
and do not block on empty state.
Fixes #12094
* enable UBB on a team; set a low spending limit (e.g. 1 or 2)
* change attribution to team
* create a project
* start a couple of workspaces
* turn to the dashboard and see the notification is shown on reload (it might take a couple of tries, to get the data fly through different systems)
```release-note
NONE
```
=> Expire spending limit notifications

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/ide-metrics/networkpolicy.go, install/installer/pkg/components/ide-metrics/objects.go
We introduced HTTP endpoints of ide-metrics before, but it failed to access days ago with request timeout, error log provided below
we need component `ide-proxy` to be able to traffic to `ide-metrics`
```
{"level":"error","ts":1661786928.6971843,"logger":"http.log.error","msg":"dial tcp 10.80.2.13:3000: i/o timeout","request":{"remote_addr":"<omit>","proto":"HTTP/1.1","method":"POST","host":"ide.gitpod.io","uri":"/metrics-api/metrics/counter/add/gitpod_supervisor_frontend_client_total","headers": {<omit>},"duration":10.000805928,"status":502,"err_id":"<omit>","err_trace":"reverseproxy.statusError (reverseproxy.go:886)"}
```
Fixes #
[internal doc](https://www.notion.so/gitpod/IDE-Team-Sync-036d660da5924b28bc2b3cc9598b3017#7022a362cef448ba9f69bcc182698435) to figure out why metrics are not …
=> [installer] enable traffic between proxy, ide-proxy and ide-metrics

WORKSPACE.yaml
Bring this commit https://github.com/gitpod-io/openvscode-server/commit/c983b520aa04890daa8cb2da3b947a0069716260 in gp-code/release/1.70 branch, which report scripts errors in workbench
Fixes #
Tested in commit's PR https://github.com/gitpod-io/openvscode-server/pull/417
```release-note
NONE
```
=> [code] build code image to report workbench errors

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/workspace/ide/constants.go
Update stable code browser image to [result](https://werft.gitpod-dev.com/job/gitpod-build-hw-build-vs.0/results) of the previous build PR https://github.com/gitpod-io/gitpod/pull/12480
Fixes #
- Open workspace in prev env
- Check if stable code commit hash is `c983b520aa04890daa8cb2da3b947a0069716260`
```release-note
NONE
```
=> [code] update stable code image to report workbench errors

.github/pull_request_template.md
Reverts gitpod-io/gitpod#12432
Turns out that Werft parses the attributes made in comments, so the PR means we add "with-payment", "with-preview" and "with-payment with-preview" by default (see example [job](https://werft.gitpod-dev.com/job/gitpod-build-aledbf-vm.4) from this [PR](https://github.com/gitpod-io/gitpod/pull/12483))
```release-note
none
```
=> Revert "Add clarification for werft annotations in the PR description"

.werft/observability/monitoring-satellite.ts
We've made quite a few changes to our installer since we introduced it to preview environments. This PR adjusts the config so it works again
* Start a workspace from this PR
* Run a new job with `werft run github -f -a with-preview=true -a observabilityInstallationMethod=observability-installer`
* Verify that the observability stack is properly running at monitoring-satellite's namespace
```release-note
NONE
```
=> Update obs installer config with importers

operations/observability/mixins/platform/rules/certmanager/rules.yaml
A follow up from https://github.com/gitpod-io/observability/pull/288, this PR re-introduces the removed alerts as raw YAML so they can be imported back where needed.
```release-note
NONE
```
=> Create alerts for certmanager

components/server/src/prometheus-metrics.ts, components/server/src/workspace/workspace-starter.ts
Reduce the noise on metric `gitpod_server_instance_starts_failed_total`
Fixes #
```release-note
NONE
```
=> [server] Only alert on explicit system failures

components/ws-manager/pkg/manager/monitor.go
This PR does two things:
1. Make sure that we wait for workspace content init to finish before we attempt to dispose it. That way we will not dispose workspace, while another thread is still working on content init of it.
2. Make sure only one `finalizeWorkspaceContent` is running for a given workspace. This fixes various race conditions, where `finalizeWorkspaceContent` may get called multiple times (one after another), and each call will attempt to dispose workspace, causing second and any after call to fail, since workspace was already disposed.
Fixes #11710
Start and stop workspaces.
Start workspaces that fail during init, and ensure this is handled correctly.
```release-note
none
```
=> [ws-manager] improve finalizeWorkspaceContent logic

components/supervisor/pkg/supervisor/services.go, components/supervisor/pkg/supervisor/ssh.go
[supervisor] support ssh gateway on not gitpod base image
In gitpod base docker image, we write HOME environment, but if user use none gitpod base image, the HOME environment is not set or set other value, which causes public key didn't write in correct path
|not gitpod base image|gitpod base image|
|---|---|
|<img width="762" alt="image" src="https://user-images.githubusercontent.com/8299500/187359508-182e4824-bd73-4e4a-acae-1b056a1fcf23.png">|<img width="647" alt="image" src="https://user-images.githubusercontent.com/8299500/187359722-77e0dfe0-e63f-4d06-b9c3-86c4126cfeb5.png">|
This PR change use hard code `/home/gitpod` as HOME dir
Fixes #12265
Fixes #12143
1. open this example repo in preview environment https://github.com/spring-projects/spring-petclinic
2. connect to workspace via …
=> [supervisor] support ssh gateway on not gitpod base image

components/public-api-server/pkg/server/server.go, install/installer/pkg/components/public-api-server/configmap.go
Ensures that only the key `stripe-webhook-secret` from the secret `stripe-webhook-secret` is mounted as a file, not as a directory with all keys in the secret.
See https://stackoverflow.com/questions/65399714/what-is-the-difference-between-subpath-and-mountpath-in-kubernetes
Fixes #
```release-note
NONE
```
=> [public-api] Fix stripe webhook secret mounting

components/usage/pkg/apiv1/billing.go, components/usage/pkg/apiv1/billing_test.go, components/usage/pkg/stripe/stripe.go
Retrieves the upcoming invoice and sets report ID into metadata.
This is needed to be able to retrieve the reportID when the invoice finalized, such that we can mark the workspace instances as already billed.
* Depends on https://github.com/gitpod-io/gitpod/pull/12311
```release-note
NONE
```
=> [stripe] Set reportId on invoices after updating credits

components/server/src/workspace/workspace-starter.ts
Small PR to conditionall log & trace `failedInstanceStartReason` if there is one to enable easy querying in logs or traces for alerts
Fixes #
```release-note
NONE
```
=> [server] Improve logging/tracing on failed instance start

components/usage/pkg/apiv1/billing.go, components/usage/pkg/apiv1/billing_test.go, components/usage/pkg/server/server.go
Forgot to initialize the content service in previous PR..
Fixes #
```release-note
NONE
```
=> [usage] Fix content service nil pointer

operations/observability/mixins/IDE/dashboards/components/browser-overview.json
Add browser overview dashboard, including error rate for now
Fixes #
See template grafana dashboard [here](https://grafana.gitpod.io/d/2wGfMlWVz/browser-overview?orgId=1), their JSON data should be the same
```release-note
NONE
```
=> [observability] add browser overview dashboard

components/ide/jetbrains/backend-plugin/build.gradle.kts, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodTerminalService.kt
This PR changes two behaviors in JetBrains IDEs:
- Update the terminal widget tab when the Gitpod Task title changes.
- Disconnect the terminal widget when Gitpod Task exits.
- Fixes #12142
- Touches #12126 - This doesn't fix it but alleviates it because typing "exit" in a Gitpod Task Terminal now disconnects the terminal, so users aren't able to type anything else on it. [[1](https://youtrack.jetbrains.com/issue/CWM-7222/Cant-detect-that-a-terminal-widget-was-closed-on-Thin-Client)][[2](https://github.com/gitpod-io/gitpod/issues/12126#issuecomment-1228729605)]
1. Open the Preview Environment of this PR.
2. Open any JetBrains IDE with some workspace that contains tasks defined in .gitpod.yml (e.g. https://github.com/gitpod-io/spring-petclinic)
3. Observe the terminal tab titles changing …
=> [jb] Update the terminal widget tab when the Gitpod Task title changes

components/ws-manager/pkg/manager/create.go
I do not think there is any need to fail StartWorkspace if it enouncounters unknown feature flag and makes roll out of new feature flags cumbersome due to need to wait for new workspace cluster to be rolled out.
Fixes #
```release-note
none
```
=> [ws-manager] do not error out if encountering unknown feature flag

operations/observability/mixins/platform/rules/kubernetes/rules.yaml
Following up from https://github.com/gitpod-io/observability/pull/290, this PR re-adds alerts from kubernetes as YAML manifest. It should be used at clusters where we want to get alerted about kubernetes failures.
Fixes #
```release-note
NONE
```
=> Add alerts related to kubernetes resources

components/supervisor/pkg/supervisor/supervisor.go
This is a bug, as ready file will never actually be placed into `/.workspace` folder, it will always be in `/workspace`
Related to #12464
Enable PVC feature
Start and stop workspaces (from prebuild, and normal)
```release-note
none
```
=> [supervisor] do not change ready file to /.workspace folder

components/server/ee/src/prebuilds/prebuild-manager.ts
Error log for blocked accounts do not show any detail `Error: Blocked users cannot start prebuilds`
- Use a blocked account to run a prebuild
- Search the logs. The message should include the name
```release-note
NONE
```
=> [server] Add name of blocked account when trying to run prebuilds

components/ws-daemon/pkg/netlimit/netlimit.go, operations/observability/mixins/workspace/dashboards/components/network-limiting.json
This adds a dashboard for monitoring the number of packets/bytes that have been dropped by network limiting
n.a.
- Run workload which creates a high number of connections
- Port forward grafana (kubectl port-forward deploy/grafana 3000)
-  Open https://3000-[your-workspace].gitpod.io/
- Navigate to Team Workspace / Network limiting
```release-note
None
```
=> Add dashboard for monitoring network connection limiting

components/usage/pkg/contentservice/usage_report_test.go, components/usage/pkg/db/types.go
Upload of usage report fails with `"failed to marshal report to JSON: json: error calling MarshalJSON for type db.VarcharTime: unexpected end of JSON input"`, this fixes that issue.
Fixes #
```release-note
NONE
```
=> [usage] Fix report to JSON conversion

.werft/installer-tests.ts, .werft/jobs/build/deploy-to-preview-environment.ts, .werft/jobs/build/installer/installer.ts, .werft/jobs/build/prepare.ts, .werft/observability/monitoring-satellite.ts, .werft/tsconfig.json
This enabled the `no-unused-locals` TypeScript compiler option and then removes all the unused local variables form the code.
No issue
`tsc --noEmit` in .werft is still successful. I triggered the job manually [here](https://werft.gitpod-dev.com/job/gitpod-build-mads-no-unused-locals.2) to ensure the my code was executed by werft.
```release-note
none
```
N/A
=> Enforce no-unused-locals in .werft

components/gitpod-db/src/typeorm/webhook-event-db-impl.ts, components/gitpod-db/src/webhook-event-db.ts, components/server/src/container-module.ts, components/server/src/projects/webhook-event-garbage-collector.ts, components/server/src/server.ts
by running a periodic garbage collector. This is a pattern we use for other resources.
fixes #12430
The way GC works is admittedly tricky, as it's an interplay between the periodic GC task and the `db-sync`. Periodically this will mark a bunch of entries as `deleted`, and we rely on the `db-sync` to actually delete the entries.
Because it's proven unreliable to mark entries as delete in the thousands, leaving them in the db for ever after a failure, the settings to mark as deleted periodically are: 600 entries every 6 minutes, which is a rate of ~200K/day and should not produce a lot of DB CPU usage.  
Fixes #12430
```release-note
NONE
```
=> Clean up webhook events

operations/observability/mixins/meta/dashboards/components/meta-overview.json, operations/observability/mixins/meta/dashboards/components/server.json, operations/observability/mixins/meta/rules/components/server/alerts.libsonnet
This PR adds a list of alerts we'd so far do manually on deployments. All of these go to our **team internal** Slack channel for now, so we can fine-tune them before we promote them to on-call L1 (if at all).
- ~[ ] db-sync~ I don't know how to make it not alert in regions where this pod is not running :shrug: 
- ~[ ] DB CPU usage stays within limits~ done in GCloud
- ~[ ] log error rate (replaces "GCloud Error Reporting")~ done in GCloud
Context:
- WebApp epic: https://github.com/gitpod-io/gitpod/issues/10722
- work in progress: https://www.notion.so/Increase-WebApp-Deployment-Cadence-Monitoring-and-Alerting-ee3cabd091634ffaa37ff218da6057bd
- Platform issue: https://github.com/gitpod-io/ops/issues/2873
Context: #10722
```release-note
NONE
```
=> [ops] WebApp: More alerts to make rollouts safer

components/ws-manager/pkg/manager/create.go, components/ws-manager/pkg/manager/monitor.go, components/ws-manager/pkg/manager/testdata/cpwp_custom_storage.golden, components/ws-manager/pkg/manager/testdata/cpwp_default_storage.golden, components/ws-manager/pkg/manager/testdata/cpwp_from_volume_snapshot.golden, components/ws-manager/pkg/manager/testdata/cpwp_no_class.golden, components/ws-manager/pkg/manager/testdata/cpwp_no_pvc.golden
Add more labels to PVC and VolumeSnapshot, so we have more information to troubleshoot/debug to know the VolumeSnapshot belonged to which workspace ID when the workspace pod was gone.
Also, we could find the workspace ID if the PVC keeps in Pending but somehow the workspace pod was gone.
Fixes #12507
- Enable PVC feature flag in preview env
- Launch a workspace
- Check the PVC with labels `kubectl get pvc --show-labels`
- Stop the workspace
- Check the VolumeSnapshot with labels `kubectl get vs --show-labels`
```release-note
None
```
=> Add labels to PVC and VolumeSnapshot object

.werft/vm/manifests.ts
In preview envs we use [rook](https://github.com/gitpod-io/gitpod/tree/main/.werft/vm/manifests/rook-ceph), so there's no need to apply the one from the image.
```bash
storage        csi-gce-pd-controller-6956df9894-jnn2w       0/5     ContainerCreating   0              10m
storage        csi-gce-pd-node-99hgn                        0/2     CrashLoopBackOff    14 (91s ago)   10m
```
```release-note
NONE
```
=> Don't apply csi-driver from k3s image

components/dashboard/src/admin/UserDetail.tsx, components/gitpod-protocol/src/admin-protocol.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
Allows to verify a user manually.
fixes #12540
Login with a new github user and use a different admin account to verify that user.
https://www.loom.com/share/eab41b81a50d4e859245de0bc3b4e469
```release-note
NONE
```
=> [admin] Allow manual user verification

components/usage/pkg/contentservice/client.go
FML...
Basically we were trying to JSON decode a gzip stream. Not because we weren't aware it's a gzip stream but because of a typo..
Will be adding a test for this tomorrow as well
Fixes #
```release-note
NONE
```
=> [billing] Fix usage report download

components/usage/pkg/apiv1/usage_test.go
There are test hooks for record deletion. However, these wouldn't run after each test when the test setup up was hooked up to the top level `*testing.T` (because the hook would only run after they finished). Instead, we need to bind the hooks to each subtest.
Fixes unit tests from https://github.com/gitpod-io/gitpod/pull/12562
unit tests
```release-note
NONE
```
=> [usage] Fix test for listing usage with pagination

components/usage/pkg/contentservice/client.go, components/usage/pkg/contentservice/metrics.go, components/usage/pkg/server/server.go
Metrics for how long it takes to upload/download the usage report. Will be added to our dashboard once available.
Fixes #
```release-note
NONE
```
=> [usage] Report upload/download metrics for usage report

components/gitpod-db/src/typeorm/webhook-event-db-impl.ts, components/gitpod-db/src/webhook-event-db.spec.db.ts
Fixing DB query with test. This is currently broken on main/prod :-(
Aftermath of https://github.com/gitpod-io/gitpod/pull/12472#discussion_r958152783
run db-test or check the test logs of the werft job and find the ✔️ passing test in there
```
[components/gitpod-db:dbtest]   WebhookEventDBSpec
...
[components/gitpod-db:dbtest]     ✓ testDeleteOldEvents
```
```release-notes
NONE
```
=> Fix for Webhook Event GC

components/usage/pkg/apiv1/report-generator.go, components/usage/pkg/apiv1/usage_test.go, components/usage/pkg/contentservice/usage_report.go, components/usage/pkg/contentservice/usage_report_test.go
Not really strictly needed. Would be nice, but we can always add later on once we're comfortable with size
Fixes #
```release-note
NONE
```
=> [usage] Drop raw sessions from usage report to cut size in half

components/server/src/workspace/workspace-starter.ts
Default to _not_ page on instances starts to reduce noise.
Fixes #
```release-note
NONE
```
=> [server] Don't raise alerts on unspecific startWorkspace errors

operations/observability/mixins/IDE/dashboards.libsonnet, operations/observability/mixins/IDE/dashboards/components/browser-overview.json
[observability] add cluster selector for browser overview dashboard
Cluster: `All` can show sum of all cluster result
Fixes #
See template grafana dashboard [here](https://grafana.gitpod.io/d/2wGfMlWVz/browser-overview?orgId=1&var-cluster=All), their JSON data should be the same
```release-note
NONE
```
=> [observability] add cluster selector for browser overview dashboard

install/infra/modules/gke/main.tf, install/infra/modules/k3s/main.tf, install/infra/modules/k3s/output.tf, install/tests/Makefile, install/tests/manifests/kots-config-gcp-db.yaml, install/tests/output.tf
Currently the database config for GCP is buggy. The config is missing some important details and hence on nightly tests with external database as dependency, the tests fail. This PR fixes these issues. This fixes the KOTS config with the right field names and takes the output from the GKE and k3s modules to apply them respectively.
Fixes #
```
werft run github -j .werft/gke-installer-tests.yaml -a skipTests=true -a deps=external
werft run github -j .werft/k3s-installer-tests.yaml -a skipTests=true -a deps=external
```
```release-note
NONE
```
=> [installer-tests] Fix GCP database config

.werft/installer-tests.ts, install/tests/Makefile, install/tests/main.tf, install/tests/manifests/kots-config-aws-s3-backend.yaml, install/tests/output.tf
This PR adds the automated test for `s3` used as registry backend in `EKS` cluster setup for Gitpod. As of the current test setup, when `incluster` registry is used, automatically `s3` registry backend config will be chosen for testing. 
Fixes #11269
You can the following command, opening this PR in a gitpod workspace to trigger this test:
```
werft run github -j .werft/eks-installer-tests.yaml -a deps=incluster
```
```release-note
NONE
```
=> [installer-tests] Adding test support for s3 registry backend

install/infra/modules/aks/kubernetes.tf, install/infra/modules/aks/local.tf, install/infra/modules/aks/main.tf, install/infra/modules/aks/monitoring.tf, install/infra/modules/aks/networks.tf, install/infra/modules/eks/kubernetes.tf, install/infra/modules/gke/main.tf, install/infra/modules/k3s/main.tf, install/tests/Makefile
This is basically the same changes @adrienthebo opened here https://github.com/gitpod-io/gitpod/pull/12321 
The PR was unfortunately merged to a different branch, and this is an effort to split up the PR again to ease the review since it ended up becoming really big.
The main goal of this change is to make sure re-using the same state continues to work.  So for starters things like database names cannot be re-used across most cloud providers for a week after the deletion, etc. Hence, the change @adrienthebo suggested adds a random variable to the end of resource names. Moreover, if a kubernetes cluster already exists by the name, the cluster creation is skipped and re-installation of KOTS is proceeded.
Fixes #
```release-note
NONE
```
=> [terraform] Add random variables to terrraform resource names

components/dashboard/src/teams/TeamUsage.tsx
Using the current time as the end time for usage records without an end time (ie running instances) is problematic because it can cause the usage view to show an instance as having run for longer than it really did. This makes it looks like the credits calculation for the instance is incorrect.
For running usage records, simply return "running" rather than inventing a stopped time for them.
See also related discussion on [Slack (internal)](https://gitpod.slack.com/archives/C02EN94AEPL/p1661946710590939).
Part of https://github.com/gitpod-io/gitpod/issues/12064
* Create a team with 'Gitpod' in the name in the preview env and enable usage based billing for the team
* Start a workspace
* Visit the usage view and see that the workspace is marked as 'running'.
* Stop the workspace
* Wait for …
=> [UBP] Show "running" for instances with no end time in the usage view

components/server/ee/src/billing/entitlement-service-ubp.ts
Drive-by fix:
Fixes https://github.com/gitpod-io/gitpod/issues/12169
1. Create a team called "Gitpod Something" to **enable the Usage-Based flag** for your user and team
2. Don't add a credit card just yet
3. ~~Try starting multiple workspaces in parallel -- at **4 parallel workspaces**, you should start seeing a paywall that prevents you from starting more (until the currently-running workspaces are stopped again)~~
4. ~~Once a workspace is running, you should **not be able to extend** the workspace timeout (i.e. no "clock" button in the IDE bottom bar)~~
5. Now, upgrade your team to paid by adding a credit card
6. Once upgraded, you should now be able to start up to **16 parallel workspaces** before seeing a paywall
7. You should also **be able to extend** the workspace timeout (using …
=> [server] Implement EntitlementServiceUBP.hasPaidSubscription

components/dashboard/src/components/ContextMenu.tsx, components/dashboard/src/components/Modal.tsx, components/dashboard/src/teams/TeamUsageBasedBilling.tsx, components/gitpod-db/src/accounting-db.spec.db.ts, components/gitpod-db/src/auth-provider-entry.spec.db.ts, components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/user/stripe-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/config.ts, components/server/src/workspace/gitpod-server-impl.ts
Allow new Stripe customers to select their billing currency.
Fixes https://github.com/gitpod-io/gitpod/issues/12343
```release-note
NONE
```
=> [server][dashboard] Allow new Stripe customers to select their billing currency

components/supervisor/pkg/supervisor/tasks.go
This PR is for rounding off the elapsed minutes while prebuilding. [More context - internal discussion](https://gitpod.slack.com/archives/C01KGM9BH54/p1660759739194689)
Fixes [Internal fix request](https://gitpod.slack.com/archives/C01KGM9BH54/p1660811960630029?thread_ts=1660759739.194689&cid=C01KGM9BH54)
- Open any New Workspace which has some prebuild saving with this current PR's build.
- 👀 See the Message regarding time saved in prebuild in terminal.
```release-note
NONE
```
No
=> fix: Round of the `elapsedMinutes` of prebuilds

components/gitpod-db/src/typeorm/migration/1662027342962-WorkspaceInstanceUsageUpdate.ts
Fixes #
check the db of the preview env using `describe d_b_workspace_instance_usage;` to include an index on `_lastModified` and no `on update` extra for `startedAt`.
```release-note
NONE
```
=> [db] fix d_b_workspace_instance_usage.startedAt and add ind_dbsync

install/infra/single-cluster/gcp/Makefile
Reorders the output of the `make output` command for the GCP single cluster terraform config. Specifically, the "tick Google Cloud SQL proxy" instruction is moved to the top of the database section, because this is also where it is in the UI itself.
- Look at changed files :) 
```release-note
NONE
```
=> Align GCP Single Cluster TF Database Output with Installation UI

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/workspace/ide/constants.go
Upgrade stable code to `1.71`, image comes from [Werft result](https://werft.gitpod-dev.com/job/gitpod-build-hw-build-vs.2) of previous PR https://github.com/gitpod-io/gitpod/pull/12603
Relates https://github.com/gitpod-io/gitpod/issues/12470
- Open workspace with stable code in preview env
- Check if commit hash is `a6661898efdac3fa0f6bea841044bffe58f502f3`
others tested in previous PR https://github.com/gitpod-io/gitpod/pull/12603
```release-note
Update stable VSCode Browser to `1.71`
```
=> [code] upgrade stable code to 1.71 release

.werft/workspace-run-integration-tests.sh, test/pkg/integration/integration.go, test/pkg/integration/workspace.go, test/tests/components/ws-manager/content_test.go, test/tests/components/ws-manager/prebuild_test.go, test/tests/components/ws-manager/tasks_test.go, test/tests/workspace/cgroup_v2_test.go, test/tests/workspace/contexts_test.go, test/tests/workspace/docker_test.go, test/tests/workspace/example_test.go, test/tests/workspace/k3s_test.go, test/tests/workspace/mount_proc_test.go
Stop and Wait for workspace at the end of each tests to be stabilization
Run the test
```release-note
NONE
```
=> tests: Stop and Wait for workspace at the end of each tests

.github/workflows/code-nightly.yaml
Point Github Action Nightly Job branch back to `gp-code/main`
Fixes #
No need
```release-note
NONE
```
=> [code] point nightly job back to gp-code/main

install/infra/modules/gke/main.tf
This PR disables auto-provisioning of nodes in GKE clusters. It turns out `cluster_autoscaling` infacts turns auto provisioning on. So all that is needed to enable autoscaling of nodes in GKE is to set the `autoscaling` section in node pool resources.
I am also pushing in a small change that enables Local DNS caching. This is currently enabled in the reference architecture, and this PR makes it consistent.
Thanks a lot to @lucasvaltl for catching it!!
Fixes #12587
Please follow the [README of the gcp module.](https://github.com/gitpod-io/gitpod/tree/main/install/infra/single-cluster/gcp)
```release-note
NONE
```
=> [terraform] Turn off node auto-provisioning in GKE

install/infra/modules/eks/output.tf, install/infra/modules/tools/aws-cluster-autoscaler/main.tf, install/infra/single-cluster/aws/Makefile, install/infra/single-cluster/aws/tools.tf
This commit adds the `cluster-autoscaler` component into
the terraform scripts through the latest helm chart. This also uses
the `cluster_autoscaler_irsa_role` module to create the relevant
policy, and role which is also created as a service account
and then attached to the cluster-atuoscaler component
Fixes #
```release-note
[single-cluster/eks] Add `cluster-autoscaler`
```
=> [single-cluster/eks] Add `cluster-autoscaler`

operations/observability/mixins/platform/rules/observability-stack/kube-state-metrics.yaml
Following up from https://github.com/gitpod-io/observability/pull/297, this PR re-adds useful alerts related to kube-state-metrics
Fixes #
```release-note
NONE
```
=> Add kube-state-metrics alerts

operations/observability/mixins/platform/rules/observability-stack/prometheus.yaml
Following up from https://github.com/gitpod-io/observability/pull/298, this PR re-adds useful alerts related to Prometheus.
Fixes #
```release-note
NONE
```
=> Add Prometheus alerts

operations/observability/mixins/platform/rules/observability-stack/prometheus-operator.yaml, operations/observability/mixins/platform/rules/observability-stack/prometheus.yaml
Following up from https://github.com/gitpod-io/observability/pull/299, this PR re-adds relevant alerts for prometheus-operator
Fixes #
```release-note
NONE
```
=> Add prometheus-operator alerts

operations/observability/mixins/meta/rules/components/server/alerts.libsonnet
Fixes very noisy alerts introduced with https://github.com/gitpod-io/gitpod/pull/12514, mostly because I learned that `rate(gauge)` does not work, especially not across different implementations (prometheus vs VictoriaMetrics).
Context: https://github.com/gitpod-io/gitpod/issues/10722
```release-note
NONE
```
=> [ops] WebApp: Fix team-specific alerts

components/gitpod-db/src/typeorm/migration/1662040283793-AddUsageTable.ts, components/usage/pkg/db/dbtest/usage.go, components/usage/pkg/db/usage.go, components/usage/pkg/db/usage_test.go
Introduces a usage table to keep track of any account's credit balance.
Fixes #
```release-note
NONE
```
=> Added Usage table

components/dashboard/src/teams/TeamUsage.tsx
Add a short message to the usage view to show that the data is not guaranteed to be up to date.
Part of https://github.com/gitpod-io/gitpod/issues/12064
```release-note
NONE
```
=> [UBP] Add a stale data warning to the Usage view

components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
Adds a check to make sure to avoid connecting multiple times to the same workspace. Not having this check in place is causing a loop of connections when trying to open a connection with a workspace that is already opened in another client.
The approach used is to show this message popup while we wait for a new API to request focus to the open IDE.
Fixes #9848
1. Ensure you have the [latest JetBrains Gateway](https://www.jetbrains.com/remote-development/gateway/) installed.
3. Start a workspace in gitpod.io with any JetBrains IDE as …
=> fix(jetbrains): avoid connection loops

components/gitpod-db/src/typeorm/migration/1662359515252-UsageUniqueInstanceId.ts
Migration that adds a constraint on `d_b_usage` to make `workspaceInstanceId` unique.
Fixes #
```release-note
NONE
```
=> [usage] constrain workspaceInstanceId to be unique

components/usage/pkg/apiv1/report-generator.go, components/usage/pkg/apiv1/usage_test.go, components/usage/pkg/db/dbtest/usage.go, components/usage/pkg/db/dbtest/workspace_instance.go, components/usage/pkg/db/usage.go, components/usage/pkg/db/usage_test.go, components/usage/pkg/db/workspace_instance.go, components/usage/pkg/db/workspace_instance_test.go
This PR adds ways to retrieve and store records from `d_b_usage` as well as functions to retrieve workspace instances to consider in a control loop.
The anticipated control loop would work as follows:
1) select drafts from `d_b_usage`
2) select workspaces instances where stopping is in a given time range (passed to the control loop)
3) select workspace instances where still running
4) select workspace instances where `workspaceInstanceId` exists in drafts
5) update usage for every instance that exists in drafts (might turn it into non-draft or not)
6) insert usage for all other instances (with do-nothing policy on conflict)
We could potentially combine 2,3,4 in one query but we should also allow for only running Step 2) to seed the past without considering running instances.
Fixes # …
=> [usage] Add database functions for new usage control loop

components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodMetricControlProvider.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodMetricProvider.kt, components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
This PR adds support in JetBrains Backend Control Center for displaying the Gitpod's Workspace Class, to be accessible and easily discoverable.
The PR also includes small changes to the layout of the Performance Tab to make it easier for the user to understand what metrics are related to the Workspace (relevant) and what metrics are related to the Node (less relevant for them).
| Current                                                                                                                                                              | After this PR                                                                                                                                                        | After this PR (Missing Class) …
=> feat(jetbrains): show workspace class in backend control center

components/usage/pkg/controller/reconciler.go, components/usage/pkg/server/server.go
Invokes the ReconcileUsageWithLedger RPC from the controller. Currently it considers the last hour for regular reconciliation.
Fixes #
```release-note
NONE
```
=> [usage] Invoke ReconcileUsageWithLedger from controller

components/usage/pkg/apiv1/usage.go, components/usage/pkg/apiv1/usage_test.go, components/usage/pkg/db/dbtest/usage.go, components/usage/pkg/db/usage.go
Ledger Reconciler finds running and stopped instances. Reconciler will be extended in subsequent PRs.
Fixes #
Unit tests
```release-note
NONE
```
=> [usage] Find running and stopped instances in ledger reconciler

components/server/src/oauth-server/oauth-controller.ts
Add `/oauth/inspect` endpoint
Related https://github.com/gitpod-io/gitpod/issues/12254
```release-note
NONE
```
=> Add `/oauth/inspect` endpoint

test/pkg/integration/apis.go, test/tests/workspace/contexts_test.go, test/tests/workspace/git_test.go
Add PVC feature flag to these integration test cases
- TestGitHubContexts
- TestGitActions
- TestGitLFSSupport
Fixes #12497
```console
USER_TOKEN=`kubectl --context=dev get secret integration-test-user -n werft -ojsonpath={.data.token} | base64 --decode`
cd test
USER_TOKEN=$USER_TOKEN go test  -run ^TestGitHubContexts$ github.com/gitpod-io/gitpod/test/tests/workspace -count=1 -namespace=default -kubeconfig=/home/gitpod/.kube/config -v -timeout=60m -username=integration-test-user
USER_TOKEN=$USER_TOKEN go test  -run ^TestGitActions$ github.com/gitpod-io/gitpod/test/tests/workspace -count=1 -namespace=default -kubeconfig=/home/gitpod/.kube/config -v -timeout=60m -username=integration-test-user
USER_TOKEN=$USER_TOKEN go test  -run ^TestGitLFSSupport$ …
```
=> PVC integration tests: TestGitHubContexts and TestGitActions and TestGitLFSSupport

components/usage/pkg/apiv1/usage.go, components/usage/pkg/apiv1/usage_test.go, components/usage/pkg/db/usage.go, components/usage/pkg/db/usage_test.go, components/usage/pkg/server/server.go
Implement main ledger control loop.
Collects instances and usage records and splits them into inserts and updates. In this PR, the records are not yet persisted but are printed out for verification. Next PR will add persistence to these.
Fixes #
Unit tests
```release-note
NONE
```
=> [usage] Implement ledger control loop

components/server/ee/src/prebuilds/prebuild-manager.ts
Use the new `StopWorkspacePolicy.ABORTED` introduced with #12284 to avoid
spending resources on backing up discarded prebuilds.
Fixes #11453
```release-note
NONE
```
=> [server] 'abort' prebuilds

install/preview/entrypoint.sh
Updates `ws-daemon` and `minio` to use `250Mi`
of memory and thus being low, instead of their
current high's of 4Gi and 2Gi respectively.
This also updates the CPU requirement of
`ws-daemon` to be `0.25` instead of the
current `0.5` vcpu which resulted in
insufficient CPU errors
After this change, I was able to open a couple
of workspaces on a 4vcpu and 11 GB ram docker daemon
Fixes #
Run
```
docker run -p 443:443 --privileged --name gitpod --rm -it  --mount type=volume,source=gitpod,destination=/var/gitpod eu.gcr.io/gitpod-core-dev/build/local-preview:tar-lp-low-memory.6
```
```release-note
[local-preview] set low memory & cpu requirements
```
=> [local-preview] set low memory & cpu requirements

install/tests/Makefile
Currently, for the cleanup job, we try to get the kubeconfig file so as to delete the gitpod installation, external-dns etc. that will remove loadbalancers and such. In azure, the aws cli is currently throwing an error saying it is not logged in. It turns out, it isn't automatically picking up the env vars anymore, we have to explicitly login using them. This PR logs in using azure cli before getting the kubeconfig.
Fixes #
You can try exporting the suggested env vars, and running `make azure-kubeconfig` from `install/tests/` directory.
```release-note
NONE
```
=> [installer-tests] fix azure authentication

.werft/jobs/build/deploy-to-preview-environment.ts, .werft/jobs/build/job-config.ts, .werft/observability/monitoring-satellite.ts
In https://github.com/gitpod-io/gitpod/pull/12039, we introduced two methods for installing monitoring-satellite in preview environments. This way we could let our colleagues have monitoring-satellite safely installed using the traditional Jsonnet way, while we could have a mechanism to use our CLI installer and verify that things are working as expected.
We've successfully migrated all our apps to our new installer, and previews are the last missing piece. This PR makes our CLI the default installation method for monitoring-satellite, and also removes the code for the jsonnet installation method completely.
* Open a workspace from this PR
* Run `werft run github -f -a with-preview`
* Make sure you can see the observability stack running without problems in the `monitoring-satellite` …
=> Previews: Always use CLI installer to install monitoring-satellite, instead of jsonnet

.werft/vm/vm.ts
Fixes https://github.com/gitpod-io/ops/issues/3923
```release-note
NONE
```
=> Server-side apply of ceph CRDs + wait until ready

components/gitpod-db/src/tables.ts
Adds `d_b_usage` to the list of synced tables.
I intentionally didn't specify/add a deleted column, because we don't have a deletion mechanism in place, yet.  I hope we will no longer use `db-sync` when we introduce it 😅
Fixes #
```release-note
NONE
```
=> [db-sync] sync d_b_usage

components/gitpod-protocol/src/gitpod-service.ts, components/gitpod-protocol/src/usage.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts, components/usage-api/typescript/src/usage/v1/sugar.ts, components/usage/pkg/db/usage.go
Fixes #
```release-note
NONE
```
=> [usage] Wiring ListUsage through server

components/dashboard/src/start/CreateWorkspace.tsx, components/dashboard/src/teams/TeamUsageBasedBilling.tsx, components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/billing/billing-service.ts, components/server/ee/src/billing/entitlement-service-ubp.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/billing/entitlement-service.ts, components/server/src/workspace/gitpod-server-impl.ts
This PR relabels the usage limit checks in the UI.
Fixes #12637
Check the sites described in https://github.com/gitpod-io/gitpod/issues/12637
```release-note
Reword "Spending Limit" to "Usage Limit"
```
=> Reword "Spending Limit" to "Usage Limit"

components/usage/pkg/apiv1/usage.go, components/usage/pkg/apiv1/usage_test.go, components/usage/pkg/db/dbtest/usage.go, components/usage/pkg/db/usage.go
Extends control loop to save records in the DB.
Fixes #
Unit tests
```release-note
NONE
```
=> [usage] Save inserted and updated records in the DB

components/usage/pkg/apiv1/usage_test.go
Fixes #
```release-note
NONE
```
=> [usage] Cleanup usage records after test

test/tests/components/ws-manager/multi_repo_test.go
Test multi repo support 
Fixes https://github.com/gitpod-io/gitpod/issues/12124
- cd test/tests
- `go test  -run ^TestMultiRepoWorkspaceSuccess$ github.com/gitpod-io/gitpod/test/tests/components/ws-manager -count=1 -namespace=default -kubeconfig=/home/gitpod/.kube/config -v`
```release-note
None
```
=> [integration] Test multi-repo support

install/infra/single-cluster/gcp/README.md, install/kots/manifests/kots-preflight.yaml
* Add a new troubleshooting section to the `README` accompanying the GCP terraform.
* Fix a typo in the `kots` preflight yaml.
```release-note
NONE
```
=> Self hosted documentation changes

components/usage/pkg/apiv1/usage_test.go, components/usage/pkg/db/workspace_instance.go, components/usage/pkg/db/workspace_instance_test.go
Fixes #
```release-note
NONE
```
=> [usage] Filter out not started workspace instances

.werft/platform-trigger-artificial-job.sh, .werft/platform-trigger-artificial-job.yaml
Once ready, this PR will create a cronjob that triggers new werft jobs which, in their turn, will create new preview environments.
The final goal is that we get a little more traffic for new preview environments, so we can be more proactive when they start failing.
Fixes #
```release-note
NONE
```
=> Cronjob that creates artificial traffic for new preview environments jobs.

dev/changelog/go.mod, dev/ssh-load-test/go.mod
`GOCACHE` gets corrupted due to old package versions that are being built and put in the cache at some point.
I'm **almost** certain that this should solve the problem.
@gitpod-io/engineering-workspace how is the cache populated? Is it done during a prebuild step? And is there a way to clean it?
Open a workspace and run:
```bash
go install github.com/gitpod-io/observability/installer@main
../go/pkg/mod/sigs.k8s.io/json@v0.0.0-20220713155537-f223a00ba0e2/internal/golang/encoding/json/encode.go:158:16: predeclared any requires go1.18 or later (-lang was set to go1.16; check go.mod)
../go/pkg/mod/github.com/google/btree@v1.1.2/btree_generic.go:89:16: type parameter requires go1.18 or later (-lang was set to go1.16; check go.mod)
```
This succeeds (takes a while):
```bash
GOCACHE=$(pwd)/cache …
```
=> Update dev/ssh-load-test and dev/changelog go mod versions

dev/loadgen/README.md, dev/loadgen/cmd/benchmark.go, dev/loadgen/configs/prod-benchmark-pvc.yaml, dev/loadgen/configs/prod-benchmark.yaml, dev/loadgen/pkg/loadgen/generator.go
Loadgen fixes for PVC use by @Furisto 
Fixes #
```release-note
none
```
=> Loadgen fixes

components/usage/pkg/db/usage.go, components/usage/pkg/db/usage_test.go
Implements retrieval of credit balance for all attribution IDs in the Usage table. Will be used when updating invoices against Stripe.
Fixes #
```release-note
NONE
```
=> [usage] Add listing of credit balance

.github/workflows/delete-kots-channel.yml, .werft/build.ts, .werft/installer-tests.ts, .werft/jobs/build/job-config.ts, .werft/jobs/build/self-hosted-upgrade-tests.ts, install/tests/Makefile, install/tests/cleanup.sh
This PR adds a `werft` flag to create self-hosted preview environments from PRs. The idea is that, users will be able to make the following comment to the PR and a werft job will get triggered from the build job (with status written back to Github) creating a preview environment:
```
/werft run with-sh-preview
```
The above command will do the following:
1. Publish the branch to KOTS
2. Create a replicated license for the KOTS channel created in the previous step
3. Start a self-hosted preview on a newly created k3s cluster(we are planning to work on reducing waste here)
4. Delete the created license
5. The URL of the preview setup will be available under the Results tab of the werft job
If the user wants to test on cluster other than `k3s`, they can run:
```
werft run with-sh-preview …
```
=> [installer-preview] add werft flags for triggering self-hosted preview

components/supervisor/README.md, components/supervisor/hot-deploy.sh, components/supervisor/pkg/supervisor/supervisor.go
This PR adds analytics to track cpu and memory consumption by individual workspace instances. It adds 2 new events `gitpod_cpu_changed` and `gitpod_memory_changed` correspondingly. Each event has `buckets` property and reported whenever a workspace instance hit higher bucket.
- CPU buckets: 1, 2, 3, 4, 5, 6 CPUs
- Memory buckets: 1, 2, 4, 8, 16 Gb
It will allow us to segment users by perf requirements and also correlate with other event like active language to see requirements from different languages. Mixpanel is capable to breakdown arrays to individual properties. I've verified it with IDE lab project.
Fixes #
- Start a workspace in prev env: https://ak-perf-anayltics.preview.gitpod-dev.com/#https://github.com/akosyakov/parcel-demo
- Inspect `gitpod_cpu_changed` and …
=> [supervisor] track cpu/memory usage analytics

components/usage/pkg/apiv1/usage_test.go, components/usage/pkg/db/workspace_instance.go
Previous [PR](https://github.com/gitpod-io/gitpod/pull/12696) did this only for one of the 3 queries for Workspace Instances. This change applies to all of the queries.
Fixes #
```release-note
NONE
```
=> [usage] Exclude workspace instances without a startedTime

install/preview/entrypoint.sh
This PR removes the unnecessary dead code in the
`entrypoint.sh` that isn't actually useful anymore,
or become stale.
Fixes #
```release-note
[local-preview] Remove unused dead code
```
=> [local-preview] Remove unused dead code

components/usage/pkg/apiv1/billing_noop.go, components/usage/pkg/controller/reconciler.go, components/usage/pkg/server/server.go
Invokes the ReconcileInvoices RPC implemented in https://github.com/gitpod-io/gitpod/pull/12712
Fixes #
```release-note
NONE
```
=> [billing] Trigger ReconcileInvoices in ledger reconciler

components/dashboard/src/components/UsageBasedBillingConfig.tsx, components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Extract common React components that will be used on both the team settings and user settings pages to configure usage based pricing. Specifically:
and:
These components will be re-used in a later PR when they are added to the individual user settings page.
* Create a new team in the preview environment whose name contains 'Gitpod'.
* Configure usage based pricing for the new team (via its settings page).
The setup should work correctly as before, with a new customer created in Stripe with the correct team id in the customer's metadata.
```release-note
NONE
```
=> [UBP] Extract common UBP configuration components

components/usage/pkg/apiv1/billing.go, components/usage/pkg/stripe/stripe.go
Implements reconciliation of usage balances against Stripe.
* Depends on https://github.com/gitpod-io/gitpod/pull/12710
* Depends on https://github.com/gitpod-io/gitpod/pull/12711
```release-note
NONE
```
=> [billing] Implement ReconcileInvoices

components/gitpod-protocol/src/usage.ts, components/usage/pkg/apiv1/usage.go, components/usage/pkg/apiv1/usage_test.go, components/usage/pkg/db/dbtest/user.go, components/usage/pkg/db/dbtest/workspace_instance.go, components/usage/pkg/db/usage.go, components/usage/pkg/db/workspace_instance.go, components/usage/pkg/db/workspace_instance_test.go
Fetch additional data for workspace instances and store it in d_b_usage.
Fixes #
```release-note
NONE
```
=> [usage] store more data for in usage entry

components/dashboard/src/teams/TeamUsage.tsx, components/server/ee/src/workspace/gitpod-server-impl.ts, components/usage/pkg/apiv1/usage.go, components/usage/pkg/apiv1/usage_test.go, components/usage/pkg/db/dbtest/usage.go, components/usage/pkg/db/usage_test.go, components/usage/pkg/db/workspace_instance_test.go
Connects the team usage view with the new usage API.
Fixes #
- [join our team](https://se-usage-view.preview.gitpod-dev.com/teams/join?inviteId=8509ec09-164c-4b63-8ef9-1282d640816d)
- [check usage page ](https://se-usage-view.preview.gitpod-dev.com/t/gitpod/usage)
```release-note
NONE
```
=> [dashboard] Use new usage API for team-usage

components/supervisor/pkg/supervisor/supervisor.go
Add `7` `8` bucket for CPU as we have defined `8 vCPU` workspace class.
See [internal chat](https://gitpod.slack.com/archives/C01KGM9BH54/p1662560918666619?thread_ts=1662550498.543589&cid=C01KGM9BH54)
Fixes #
No need
```release-note
NONE
```
=> [supervisor] add 7,8 bucket for cpu perf analytics

components/supervisor/pkg/supervisor/supervisor.go
Fixes #
```release-note
NONE
```
=> [supervisor] bucket per each Gb for memory analytics

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/cleanup-installer-tests.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/run-integration-tests.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile, dev/image/kubeconfig.yaml
This PR upgrade gcloud to version 400, it allows direct open auth page and copy auth code, no need copy gcloud command into local machine
|berore|after|
|--|--|
|<img width="704" alt="image" src="https://user-images.githubusercontent.com/8299500/188362690-18e2433e-2a45-48cc-a358-ffe1c2e0e657.png">|<img width="707" alt="image" src="https://user-images.githubusercontent.com/8299500/188363107-7328c538-556f-4f96-989f-de28f92716af.png">|
Also switch `gcp` auth provider to `gke-gcloud-auth-plugin` in order to remove deprecated warning
|Berore|After|
|--|--|
|<img width="720" alt="image" src="https://user-images.githubusercontent.com/8299500/188362657-906042c6-0503-4000-9270-dd814258981c.png">|<img width="700" alt="image" src="https://user-images.githubusercontent.com/8299500/188362805-3588bd12-0 …
=> [dev] Update dev-environment image and switch to gke-gcloud-auth-plugin

components/server/ee/src/user/stripe-service.ts
Create customers (user/team) with an AttributionID instead of user/team ID. We cannot yet update the find queries to use this field as we have customers in Stripe without the attributionID property.
Once this has propagated enough, we can also kill the user/team specific methods and use the Attribution ID only.
Fixes #
```release-note
NONE
```
=> [stripe] Create customers with attributionId

components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/user/stripe-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
Add a `createOrUpdateStripeCustomerForUser` method to `server` to allow the creation of Stripe customers for individual users. Previously we had only the `createOrUpdateStripeCustomerForTeam` method which would create a Stripe customer for a Gitpod team.
The only difference between the `createOrUpdateStripeCustomerForUser` and `createOrUpdateStripeCustomerForTeam` methods is the metadata in the resulting Stripe customer object. For teams we store `[teamId]: foo` and for users we store `[userId]: bar`.
* Set the billing mode to UBP for your user in the preview environment by creating a team with `Gitpod` in the name.
* In the developer console run:
```js
await window._gp.gitpodService.server.createOrUpdateStripeCustomerForUser("EUR") …
```
=> [UBP] Add server method to create a stripe customers for an individual user

components/server/ee/src/billing/billing-mode.ts
Don't count "Professional Open Source" as personal subscription when calculating billing mode.
Fixes #12672
```release-note
NONE
```
=> [server] Don't count "Professional Open Source" as personal subscription

components/server/ee/src/user/stripe-service.ts
Customers in staging & prod have been updated with this metadata.
Counterpart PR for usage component is here https://github.com/gitpod-io/gitpod/pull/12755
Fixes #
```release-note
NONE
```
=> [stripe] Use AttributionID metadata when querying for customers

components/usage/pkg/db/usage_test.go
Make tess robust against parallel DB changes
Fixes #
```release-note
NONE
```
=> [usage] make tests robust

components/usage/pkg/apiv1/usage.go, components/usage/pkg/db/workspace_instance.go, components/usage/pkg/db/workspace_instance_test.go
We've got bad data quality on workspace_instances from the past. This excludes these from our queries for running workspaces until we can fix the source of truth.
Fixes #
```release-note
NONE
```
=> [usage] Ignore running instances before August 2022

components/usage/pkg/apiv1/pricer.go, components/usage/pkg/db/workspace_instance.go, components/usage/pkg/db/workspace_instance_test.go
Fixes negative credits.
Fixes #
Unit tests
```release-note
NONE
```
=> [usage] Fix negative credits

WORKSPACE.yaml, components/gitpod-db/src/typeorm/code-sync-resource-db.spec.db.ts, components/gitpod-db/src/typeorm/code-sync-resource-db.ts, components/gitpod-db/src/typeorm/entity/db-code-sync-resource.ts, components/server/src/code-sync/code-sync-service.ts
Store editSessions in sync server
1. Create workspace using latest vscode
2. Test editsessions is working https://code.visualstudio.com/updates/v1_70#_edit-sessions-across-vs-code-for-the-web-and-desktop, in our case it could used to store changes between new workspaces of the same repo 
```release-note
[server] Support for storing vscode edit sessions in sync server
```
=> code-sync: store editSessions

components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/GitpodServer.java, components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/Error.java, components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/SetWorkspaceTimeoutResult.java, components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/TakeSnapshotOptions.java, components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/WorkspaceTimeoutDuration.java, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/AccessControlAction.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/CommunityChatAction.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/ContextAction.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/DashboardAction.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/DocumentationAction.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/ExtendWorkspaceTimeoutAction.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/FollowUsOnTwitterAction.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/ReportIssueAction.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/SettingsAction.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/ShareWorkspaceSnapshotAction.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/StopWorkspaceAction.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/UpgradeSubscriptionAction.kt, components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml, components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt, components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodStartWorkspaceView.kt
Add Gitpod-related actions to JetBrains IDEs, similar to [the ones from VS Code](https://github.com/gitpod-io/openvscode-server/blob/35504520bdbd3c4ffaf170ff6356e83caffa7ddb/extensions/gitpod-shared/src/features.ts#L335-L505).
| Actions in Control Center | Actions in Search Menu |
| --- | --- |
| <img width="701" alt="image" src="https://user-images.githubusercontent.com/2318450/189179036-367dee41-46b7-4296-a9bc-b9175e846449.png"> | <img width="494" alt="Screenshot 2022-09-07 at 15 59 57" src="https://user-images.githubusercontent.com/2318450/188911410-bf755c22-0236-4366-8f0b-480c968ec904.png"> |
| Sorted by relevance. We define the order. | Sorted alphabetically. IntelliJ defines the order. |
- Open Dashboard
- Open Context
- Open Settings
- Open Access Control
- Documentation
- Report …
=> Add Gitpod-related actions to JetBrains IDEs

components/server/src/workspace/workspace-classes.ts, components/server/src/workspace/workspace-starter.ts
- Ensure PVC workspace class does not change on restart
- Use pvc class if prebuild is pvc if user would get legacy pvc class
Fixes #12666
Fixes #12494
- Select large workspace class in your user preferences
- Enable persistent_volume_claim feature for your user in the preview environment via administration
- Start prebuild -> prebuild should have g1-large-pvc
- Create regular workspace from prebuild (should have g1-large-pvc)
- Restart workspace (should have g1-large-pvc)
```release-note
None
```
=> [server] Ensure PVC workspace class does not change on restart

components/usage/pkg/apiv1/billing.go, components/usage/pkg/stripe/stripe.go, components/usage/pkg/stripe/stripe_test.go
Customers in staging & prod have been udpated to additively contain `attributionId` metadata.
Fixes #
```release-note
NONE
```
=> [stripe] Use attributionId in stripe queries in usage
