components/ws-manager/pkg/manager/monitor.go

Fixes #
```release-note
none
```

[ws-manager] improve tracing in initializeWorkspaceContent

---

components/licensor/typescript/ee/main.go

[licensor] Fix lint issue S1023

---

install/installer/.gitignore

Saves in golden files, but not anywhere else - the release process creates version files, which was missed in the initial golden files work
```release-note
NONE
```

[installer]: gitignore versions file

---

components/dashboard/src/experiments/client.ts

By default, it would poll every 1 minute
Fixes #
```release-note
NONE
```

[configcat] Poll every 3 minutes for dashboard flags

---

components/server/src/workspace/gitpod-server-impl.ts

Removes the outdated feature flag as we no longer need it (cmp.: [configcat](https://app.configcat.com/08da1258-64fb-4a8e-8a1e-51de773884f6/08da1258-6541-4fc7-8b61-c8b47f82f3a0/08da1258-652c-4bae-88be-17963da63a1c)).
Fixes: https://github.com/gitpod-io/gitpod/issues/11024
```release-note
NONE
```

[server] Remove outdated feature flag deprecateOldImageLogsMechanism

---

components/ide-proxy/static/code/marketplace.json

Update to reflect the latest changes done by Microsoft (only updating those that are interesting to us)
```diff
--- a/marketplace.json
+++ b/marketplace.json
@@ -382,6 +382,13 @@
"displayName": "Vue Language Features (Volar)"
}
},
+		"silvenon.mdx": {
+			"disallowInstall": true,
+			"extension": {
+				"id": "unifiedjs.vscode-mdx",
+				"displayName": "VSCode MDX"
+			}
+		},
"CoenraadS.bracket-pair-colorizer-2": {
"settings": [
"editor.bracketPairColorization.enabled",
```
You can test by searching for `silvenon.mdx` in the extensions in VS Code Browser and confirming it cannot be downloaded.
```release-note
NONE
```

[code]: Update `marketplace.json`

---

.werft/workspace-run-integration-tests.sh

Simplify preparing a integration test
NONE
Can run a integration tests
```release-note
NONE
```

tests: use a empty commit instead of a temporary commit

---

test/pkg/integration/integration.go
test/pkg/integration/workspace.go
test/tests/components/ws-manager/content_test.go
test/tests/components/ws-manager/tasks_test.go

tests: Stabilization of TestRegularWorkspaceTasks
Relates #12248
Run TestRegularWorkspaceTasks
```release-note
NONE
```

tests: Stabilization of TestRegularWorkspaceTasks

---

components/usage/pkg/apiv1/billing.go
components/usage/pkg/stripe/stripe.go

This PR does the following to the stripe client:
* Re-uses a single method for searching for customers
* Increases composability of the methods by accepting CustomerID when searching for Invoices rather than TeamID or UserID
* Adds specific methods to look up a Customer from a TeamID or UserID
* Removed the `stripe.Kind`, this logic is handled by `GetCustomerByTeamID` or `GetCustomerByUserID`
These changes are needed for a subsequent PR which will be updating an Invoice with metadata
Fixes #
```release-note
NONE
```

[stripe] Refactor finding of customers, make more composable

---

components/usage/pkg/server/server.go

This is needed to be able to disable the periodic sync in US (to only run it from EU)
Fixes #
```release-note
NONE
```

[usage] Disable controller when schedule is empty

---

install/installer/cmd/testdata/render/use-pod-security-policies/output.golden

The most recent build on main failed ([ref](https://werft.gitpod-dev.com/job/gitpod-build-main.4418)) due to render tests failing. They passed on [the PR](https://github.com/gitpod-io/gitpod/pull/12222) that was merged though.
From [reading slack](https://gitpod.slack.com/archives/C01KLC56NP7/p1660035524743949?thread_ts=1660035270.795069&cid=C01KLC56NP7) I ran the following commands to update the golden files:
```sh
cd install/installer && make deps generateRenderTests
```
No issue
Hopefully this fixes the tests.
```release-note
none
```
N/A

Update render tests

---

test/tests/workspace/k3s_test.go

tests: Stabilization of k3s tests
Run the test
```release-note
NONE
```

tests: Stabilization of k3s tests

---

test/tests/workspace/docker_test.go

tests: Stabilization of docker tests
Run the test
```release-note
NONE
```

tests: Stabilization of docker test.

---

components/usage/pkg/apiv1/billing.go
components/usage/pkg/apiv1/report-generator.go
components/usage/pkg/apiv1/usage.go
components/usage/pkg/apiv1/usage_test.go
components/usage/pkg/contentservice/client.go
components/usage/pkg/contentservice/noop.go
components/usage/pkg/contentservice/usage_report.go

Reuses existing UsageReport struct to upload more details as part of the report.
Fixes #
```release-note
NONE
```

[usage] Upload report with more details

---

components/ws-manager/pkg/manager/monitor.go

`actOnPodEvent` is called multiple times and queues up any events.
So essentially `actOnPodEvent` is called based on potentially out of date state, like it happens during dispose.
This PR improved `finalizeWorkspaceContent` logic to counter for that, making it more resilient.
Fixes #12519 
Start and stop workspaces
```release-note
none
```

[workspace] fix multiple calls to finalizeWorkspaceContent can mess up dispose

---

dev/loadgen/configs/prod-benchmark-pvc.yaml
dev/loadgen/configs/workspace-preview-benchmark-pvc.yaml

Add workspace preview PVC benchmark config
Fixes #
```release-note
None
```

loadgen: workspace preview PVC benchmark config

---

.werft/vm/manifests.ts

Apply csi-driver, but don't fail
Fixes #
```release-note
NONE
```

Apply csi-driver, but don't fail

---

WORKSPACE.yaml

Build a stable code image for `1.71` release
Relates #12470
```release-note
NONE
```

[code] build code stable release 1.71

---

install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/azure-setup/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/workspace/ide/constants.go

Update code stable to align all proposal apis, code changes according to [Werft result](https://werft.gitpod-dev.com/job/gitpod-build-hw-js-debug.1/results) of [branch](https://github.com/gitpod-io/gitpod/tree/hw/js-debug) which point codeCommit to `gp-code/release/1.71` [[1](https://github.com/gitpod-io/openvscode-server/tree/gp-code/release/1.71)]
Relates https://github.com/gitpod-io/gitpod/issues/12470
- Open workspace in prev env with stable code
- Check if commit hash in `About` is `d96dc4787a7132bffb7d736e96a0b73469a9517e`
- Check `Output` section in terminal area, search with `js-debug` confirm that there is no errors about it
```release-note
NONE
```

[code] update code stable to align all proposal apis

---

operations/observability/mixins/platform/rules/observability-stack/alertmanager.yaml
operations/observability/mixins/platform/rules/observability-stack/kube-state-metrics.yaml

Following up from https://github.com/gitpod-io/observability/pull/296/files, this PR re-creates useful alerts related to alertmanager.
Fixes #
```release-note
NONE
```

Create alertmanager alerts

---

components/usage/pkg/controller/reconciler.go
components/usage/pkg/server/server.go

Initial setup for the ledger reconciler. Will print a message when it ticks.
Will be extended in subsequent PRs to add logic.
Fixes #
```release-note
NONE
```

[usage] Setup ledger reconciler tick

---

components/usage/pkg/apiv1/usage.go

Fixes #
```release-note
NONE
```

[usage] Drop big log message

---

components/usage/pkg/apiv1/usage.go
components/usage/pkg/apiv1/usage_test.go
components/usage/pkg/db/usage.go

Adds metadata into each usage record
Fixes #
```release-note
NONE
```

[usage] Serialize metadata into usage records

---

.werft/vm/manifests.ts

Fixes #
```release-note
NONE
```

Change preview pvc to ReadWriteOnce

---

components/common-go/grpc/grpc.go

When a GRPC service handles a panic it now logs the stack trace.
Fixes #
```release-note
NONE
```

[grpc] log stack on panic

---

components/usage/pkg/apiv1/billing.go

Changes existing FinalizeInvoice to use the ledger
Fixes #
```release-note
NONE
```

[billing] Implement FinalizeInvoice with usage ledger

---

operations/observability/mixins/workspace/rules/workspacefailure-SLO.yaml

In https://github.com/gitpod-io/gitpod/pull/12659, I replaced workspace alerts from jsonnet to YAML, but made a mistake with the naming 😕.
I use capital letters, and that is not compatible with kubernetes. For that reason, preview environments are failing to install monitoring-satellite and also ArgoCD is failing to update apps.
Fixes #
```release-note
NONE
```

Fix PrometheusRule name

---

test/pkg/integration/apis.go

PortForwarding sometimes returns the error because of network conditions. This PR addresses it.
Run the test
```release-note
NONE
```

test: More robust port-forward of ComponentAPI

---

dev/telepresence-hack/copy-mounts/main.go

Fixes #
```release-note
NONE
```

[server][telepresence] continue with downloadVolume on errors and log

---

dev/gpctl/cmd/workspaces-list.go

Show when workspace has user activity. This makes it easier to diagnose WorkspaceTooManyRegularNotActive alerts
n.a.
`gpctl workspaces list`
```release-note
None
```

[gpctl] Show when workspace has user activity

---

test/tests/components/ws-manager/prebuild_test.go

workspace integration test: add PVC FF to TestPrebuildWorkspaceTaskSuccess
Partially #12638
```console
cd test
go test  -run ^TestPrebuildWorkspaceTaskSuccess$ github.com/gitpod-io/gitpod/test/tests/components/ws-manager -count=1 -namespace=default -kubeconfig=/home/gitpod/.kube/config -v
```
```release-note
None
```
None

workspace integration test: add PVC FF to TestPrebuildWorkspaceTaskSuccess

---

.werft/util/kubectl.ts

Fixes https://github.com/gitpod-io/gitpod/issues/12622
```release-note
NONE
```

Preview-env don't wait for WS pods

---

.werft/workspace-run-integration-tests.sh

Fixes #
```release-note
NONE
```

test: fix broken slack notification

---

components/supervisor/pkg/supervisor/top.go

[supervisor] close connection after call api
Fixes #
```release-note
NONE
```

[supervisor] close connection after call api

---

install/installer/cmd/testdata/render/http-proxy/output.golden

This PR update installer testdata, since it block main branch werft build
Fixes #
No need
```release-note
NONE
```

[installer] fix render test data

---

.werft/platform-delete-preview-environment.ts
.werft/platform-delete-preview-environments-cron.ts
.werft/util/preview.ts

Previously `.werft/platform-delete-preview-environment.ts` would import things from `.werft/platform-delete-preview-environments-cron.ts`, however, as that file contains top-level expressions those would get executed as part of the import - the file never intended to be imported. 
This moves shared logic between `.werft/platform-delete-preview-environment.ts` and `.werft/platform-delete-preview-environments-cron.ts` to `.werft/util/preview.ts`.
No issue, see related [internal discussion](https://gitpod.slack.com/archives/C01KGM9EBD4/p1663081439162339).
With this change I was able to run the job ([link](https://werft.gitpod-dev.com/job/gitpod-custom-mads-move-classes-to-shared-lib.2/logs))
```
werft job run github -j .werft/platform-delete-preview-environment.yaml  -a …
```

Move HarvesterPreviewEnvironment to preview.ts

---

test/pkg/integration/workspace.go

test: fix a bug in stopWs
Run the test and Pass `TestBackup`
```release-note
NONE
```

test: fix a bug in stopWs

---

test/pkg/integration/workspace.go

Ignore the error https://github.com/gitpod-io/gitpod/issues/12021 once to pass the integration test everyday
Run the test
```release-note
NONE
```

test: Ignore the error #12021

---

components/gitpod-db/src/typeorm/migration/1663147758702-DropWorkspaceInstanceUsage.ts

The table is no longer used.
Fixes #
```release-note
NONE
```

[db] Drop d_b_workspace_instance_usage

---

.gitattributes

Missed a case where the golden files are further nested
Fixes #
```release-note
NONE
```

[installer] Fix gitattributes for golden files

---

.werft/platform-trigger-artificial-job.sh

Following up from https://github.com/gitpod-io/gitpod/pull/12784#discussion_r971950221
Fixes #
```release-note
NONE
```

Add protection from werft failures

---

components/usage/pkg/stripe/stripe.go

This log comes up quite verbose in the logs, we can push the context into a log field so we still get it on errors.
[See logs here](https://console.cloud.google.com/logs/query;query=resource.labels.pod_name%20:%20%2528%22usage%22%2529;timeRange=PT1H;cursorTimestamp=2022-09-16T11:10:10Z?authuser=0&project=gitpod-191109)
Fixes #
```release-note
NONE
```

[usage] Remove verbose log 'searching for customer with query'

---

components/ee/db-sync/src/replication.ts

Fixes #
```release-note
NONE
```

[db-sync] get rid of updates.join().length

---

components/ws-manager-bridge/src/bridge.ts

Clean up instance tokens and track workspace stop even in irregular cases in `ws-manager-bridge`.
(Drive-by fix split out of https://github.com/gitpod-io/gitpod/pull/12912 )
Fixes a diff identified and described here: https://github.com/gitpod-io/gitpod/pull/12912#issuecomment-1246497254
```release-note
NONE
```

[ws-manager-bridge] Clean up instance tokens and track workspace stop even in irregular cases

---

components/server/ee/src/workspace/gitpod-server-impl.ts

Fixes the billingstrategy for cost centers that were created before introdcution of `billingStrategy`
Fixes https://github.com/gitpod-io/gitpod/issues/13079
```release-note
NONE
```
- [] /werft with-preview

[ubp] ensure right billingStrategy

---

.werft/jobs/build/build-and-publish.ts

This simplifies the leeway invocation in our primary build. I'm about to add a new argument in https://github.com/gitpod-io/gitpod/pull/13093 so wanted to clean it up slightly first.
Part of https://github.com/gitpod-io/gitpod/issues/12824
Triggered a build using the CLI (´werft job run github`) to avoid job protection (see job [here](https://werft.gitpod-dev.com/job/gitpod-build-mads-simplify-leeway-invocation.14))
```release-note
NONE
```

Simplify leeway invocation

---

.werft/jobs/build/job-config.ts

werft: Add workspace for with-integration-test
Fixes #
```release-note
NONE
```

werft: Add workspace for with-integration-test

---

components/gitpod-db/src/typeorm/migration/1663751455102-PrebuildWorkspaceDBSync.ts

Needed to be able to have db-sync delete records
* Relates to https://github.com/gitpod-io/gitpod/issues/13160
```release-note
NONE
```

[db] Add deleted column to d_b_prebuilt_workspace

---

components/gitpod-db/src/typeorm/migration/1663752957582-PrebuiltWorkspaceUpdatableDBSync.ts

To enable db-sync for this table
Fixes #
```release-note
NONE
```

[db] Add deleted and _lastModified columns, index _lastModified for d_b_prebuilt_workspace_updatable

---

install/infra/modules/eks/storage.tf

Typos in policy declarations
```release-note
[AWS Infra] Terraform code updated to create correct policies for S3 buckets
```
Third times a charm?

Last tidying around  https://github.com/gitpod-io/gitpod/issues/12964

---

operations/observability/mixins/platform/rules/kubernetes/kubernetes.yaml

https://gitpod.slack.com/archives/C03MWBB5MP1/p1663829940265859?thread_ts=1663816586.287529&cid=C03MWBB5MP1
Fixes https://gitpod.slack.com/archives/C03MWBB5MP1/p1663829940265859?thread_ts=1663816586.287529&cid=C03MWBB5MP1
```release-note
NONE
```

Increase the evaluation time for CPU|MemoryOvercommit alerts

---

components/gitpod-db/src/tables.ts

* Depends on https://github.com/gitpod-io/gitpod/pull/13163
* Depends on https://github.com/gitpod-io/gitpod/pull/13164
And both need to be rolled out to production.
```release-note
NONE
```

[db-sync] Enable sync for d_b_prebuilt_workspace and d_b_prebuilt_workspace_updatable

---

components/server/src/prometheus-metrics.ts

We were calling "register default" twice
Fixes #
```release-note
NONE
```

[server] Fix metrics registration

---

operations/observability/mixins/cross-teams/dashboards/gitpod-grpc-client.json

* Adds tags
* Makes default service selection `*`
Fixes #
```release-note
NONE
```

[grafana] Fix grpc / client dashboard

---

components/server/ee/src/workspace/gitpod-server-impl.ts

Fixes a bug where we set the wrong billingStrategy.
Fixes #
```release-note
NONE
```

[server] fix setting of billingStrategy

---

install/kots/manifests/kots-support-bundle.yaml

Copy of #13378 to merge into the release branch
Fixes #
```release-note
```

[kots]: configure support bundle to get KOTS configmaps

---

components/server/ee/src/workspace/gitpod-server-impl.ts

Copy of https://github.com/gitpod-io/gitpod/pull/13402 for the release branch.
Fixes #
```release-note
```

Check `enablePayment` before Stripe operations

---

.pre-commit-config.yaml
dev/preview/.gitignore
dev/preview/infrastructure/harvester/cloudinit.yaml
dev/preview/infrastructure/harvester/lb.tf
dev/preview/infrastructure/harvester/namespace.tf
dev/preview/infrastructure/harvester/svc.tf
dev/preview/infrastructure/harvester/variables.tf
dev/preview/infrastructure/harvester/vm.tf

Terraform resources for Harvester VM + services in dev and harvester clusters. Essentially terraforming [manifests.ts](https://github.com/gitpod-io/gitpod/blob/main/.werft/vm/manifests.ts)
Fixes https://github.com/gitpod-io/ops/issues/5223
`./dev/preview/workflow/preview/deploy-harvester.sh`
```release-note
NONE
```

Terraform resources for Harvester VM and LBs

---

operations/observability/mixins/IDE/rules/opensvx.yaml

Fixes #
```release-note
NONE
```

Use user centric metrics to trigger an alert.

---

components/ws-manager/pkg/manager/manager.go

Removes request logs from some error cases.
```release-note
NONE
```

[ws-manager] Remove req logs

---

components/ws-manager/pkg/manager/manager.go

improve warning message in StartWorkspace function
Fixes #
```release-note
none
```

[ws-manager] improve warning message in StartWorkspace fn

---

components/usage/pkg/apiv1/billing.go
components/usage/pkg/stripe/stripe.go
components/usage/pkg/stripe/stripe_test.go

A few readability tweaks.
Fixes #
Unit, builds
```release-note
NONE
```

[usage] Simplify UpdateInvoices handling

---

components/server/src/container-module.ts

This is follow up https://github.com/gitpod-io/gitpod/pull/13456
Fixes #
```release-note
NONE
```

[server] bind ide-service in singleton scope

---

components/dashboard/src/contexts/FeatureFlagContext.tsx

Cherry-pick https://github.com/gitpod-io/gitpod/pull/13393 onto the release branch.
```release-note
NONE
```

[usage] don't show usage in slef-hosted yet

---

test/pkg/integration/apis.go
test/tests/components/ws-manager/prebuild_test.go

Restart control plane components `ws-manager` and `snapshot-controller` Deployment after the volume snapshot is finished.
Partially #13146
```
cd test
go test -run ^TestOpenWorkspaceFromPrebuild$ github.com/gitpod-io/gitpod/test/tests/components/ws-manager -count=1 -namespace=default -kubeconfig=/home/gitpod/.kube/config -v -timeout=20m
```
```release-note
None
```
None

test: restart control plane components after the volume snapshot is finished

---

README.md

Please check the Context [here](https://www.notion.so/gitpod/Community-Sync-ca2d492199504fd9b95ad60860d6753d#34172e6cc1164fba8e1bd0abf398500e).
Fixes #
```release-note
```

Add awesome-gitpod link in the docs section

---

components/ws-manager/pkg/manager/annotations_test.go
components/ws-manager/pkg/manager/manager_test.go

Fix panic in test when preview env is failing.
Fixes #
```release-note
none
```

[ws-manager] fix tests

---

components/dashboard/src/settings/Plans.tsx
components/gitpod-protocol/src/plans.ts

Update plans page, see relevant comment in https://github.com/gitpod-io/gitpod/issues/13229#issuecomment-1264713834.
Fixes https://github.com/gitpod-io/gitpod/issues/13229
// TODO
```release-note
Update free plan name
```

Update free plan name

---

components/usage/pkg/stripe/stripe.go

The original log (as an error) has already confused us during support. This handles the case of no subscriptions gracefully.
Fixes #
```release-note
NONE
```

[usage] Handle Stripe customers with zero subscriptions

---

components/image-builder-mk3/pkg/orchestrator/monitor.go
components/ws-daemon/cmd/content-initializer/main.go
components/ws-daemon/cmd/root.go
components/ws-daemon/pkg/content/initializer.go
test/pkg/integration/workspace.go

- Refactor loops and delays in the integration suite.
- Ensure the snapshot file from remote storage can be written
- Open a workspace using a prebuild or backup (no PVC)
```release-note
NONE
```

[test] Reduce loop wait time

---

.werft/jobs/build/job-config.ts

With this PR we'll always infer "with-preview" if "with-integration-tests" is set.
I considered allowing "with-integration-tests" without "with-preview" but decided against it for two reasons
1. It might be confusing that if you use "with-integration-tests" without "with-preview" and you actually changed any components, then your integration tests wouldn't run against the "latest" version of your component - you might not be testing what you think you're testing.
1. Currently we download the k3s kubeconfig etc. in the "deploy to preview env" method, which means that we'd have to refactor the code quite a lot if we wanted to be able to run integration tests against a preview environment without first deploying to it.
Part of https://github.com/gitpod-io/ops/issues/5381
```sh
werft job run …
```

Infer with-preview if with-integration-tests is set

---

components/usage/pkg/apiv1/billing.go
components/usage/pkg/stripe/stripe.go

Fixes #
```release-note
NONE
```

[stripe] Fix inverted comparison

---

components/usage/pkg/apiv1/billing.go
components/usage/pkg/apiv1/billing_test.go
components/usage/pkg/db/dbtest/cost_center.go
components/usage/pkg/stripe/stripe.go

Adds tests which lead to a regression in https://github.com/gitpod-io/gitpod/pull/13442 and fixed in https://github.com/gitpod-io/gitpod/pull/13611
unit tests
```release-note
NONE
```

[stripe] Add tests for ReconcileInvoices

---

.gitpod.yml
.werft/aks-installer-tests.yaml
.werft/build.yaml
.werft/cleanup-installer-tests.yaml
.werft/debug.yaml
.werft/eks-installer-tests.yaml
.werft/gke-installer-tests.yaml
.werft/ide-integration-tests-startup.yaml
.werft/k3s-installer-tests.yaml
.werft/platform-delete-preview-environment.yaml
.werft/platform-delete-preview-environments-cron.yaml
.werft/platform-trigger-werft-cleanup.yaml
.werft/workspace-run-integration-tests.yaml
dev/image/Dockerfile

What it says
Fixes #
```release-note
NONE
```

Update tf version in docker image

---

components/server/ee/src/user/stripe-service.ts
components/server/src/prometheus-metrics.ts

Reports prometheus metrics on Stripe interaction.
* Part of https://github.com/gitpod-io/gitpod/issues/13157
* Needed to get data for https://github.com/gitpod-io/gitpod/issues/13177 when migrating
Creating a UBP subscription works
```release-note
NONE
```

[server] Report Stripe client metrics

---

.werft/util/certs.ts

Check if preview cert is ready before trying to create/destroy it
Fixes #
```release-note
NONE
```

Check if preview cert is ready before trying to create/destroy it

---

components/usage/pkg/apiv1/billing.go
components/usage/pkg/stripe/stripe.go

* Depends on https://github.com/gitpod-io/gitpod/pull/13659
* Part of https://github.com/gitpod-io/gitpod/issues/13177
```release-note
NONE
```

[stripe] Implement BillingService.GetStripeCustomer

---

components/server/ee/src/user/stripe-service.ts

Use BillingService to get StripeCustomer ID
* Depends on https://github.com/gitpod-io/gitpod/pull/13667
* Part of https://github.com/gitpod-io/gitpod/issues/13177
```release-note
NONE
```

[server] Use BillingService.GetStripeCustomer to fetch customer

---

components/server/ee/src/user/stripe-service.ts

[Metrics](https://grafana.gitpod.io/d/8W7P-jg4z/gitpod-component-usage?orgId=1&from=now-1h&to=now) show that the implementation on `usage` is working well, we can remove the fallback now.
Fixes #
Subscribing to UBP still works
```release-note
NONE
```

[server] Remove fallback to search for stripe customers

---

components/server/src/workspace/gitpod-server-impl.ts

By default any non-specific error is returned as a 500, here we map (a subset) of grpc error codes to corresponding ResponseErrors with codes.
Fixes #
```release-note
NONE
```

[server] openPort maps ResourceExhausted from ws-man to TooManyRequests

---

components/gitpod-db/src/typeorm/workspace-db-impl.ts

Removes the extra comma.. 
Fixes #
```release-note
NONE
```

[server] Fix typo in probe workspaces search

---

components/usage/pkg/stripe/reporter.go
components/usage/pkg/stripe/stripe.go

Currently we'd report the full path in the metrics, but that includes resource IDs which causes the metrics to churn through cardinality. This instead uses explicit resource names
Fixes #
```release-note
NONE
```

[usage] Report Stripe metrics without full request path

---

.werft/installer-tests.ts

This pull request cleans up werft logging around self hosted test and preview environments.
Fixes #
```bash
werft run github -j .werft/k3s-installer-tests.yaml  -a domain=tests.doptig.com
```
See [gitpod-custom-alt-installer-tests-fixup-phase-name.1](https://werft.gitpod-dev.com/job/gitpod-custom-alt-installer-tests-fixup-phase-name.1)
```release-note
NONE
```

[installer-tests] fixup werft major phase naming, messaging

---

.werft/jobs/build/deploy-to-preview-environment.ts
.werft/jobs/build/prepare.ts
.werft/util/certs.ts
.werft/vm/vm.ts
dev/preview/infrastructure/harvester/cert.tf
dev/preview/infrastructure/harvester/provider.tf

Create cert-manager certificate resource using TF.
Fixes https://github.com/gitpod-io/ops/issues/5225
```release-note
NONE
```

[Future Preview Environments] Terraform Certificates

---

.werft/platform-trigger-werft-cleanup.sh

Deleting the node restarts the machine with a fresh storage, but stays cordoned off, so this drains the node before deletion and uncordons it after.
```release-note
NONE
```

Drain, delete, and uncordon node on cleanup

---

.werft/installer-tests.ts
.werft/util/shell.ts

This is a quick experiment to stream logs from subprocesses of a werft job.
At present the current subprocess exec function waits for a process to complete before emitting logs; this approach is viable for shorter tasks but Terraform runs can extend for 20+ minutes. In addition long waiting periods frequently mean that a job is in an error state, but there's no way for us to view the logs incrementally and halt a misbehaving job.
This commit alleviates this issue by adding a new async `execStream` function that will stream logs from the subprocess. When passed a slice logs will be streamed to werft; otherwise the subprocess stdout/stderr will be attached to the werft stdout/stderr.
> **note**: my experience with Typescript is limited and this is a "throw some code at the wall and see what …

[werft] Implement log streaming for subprocesses

---

test/tests/ide/vscode/python_ws_test.go

Increase vscode test timeout
```release-note
NONE
```

Increase vscode test timeout

---

components/dashboard/src/components/UsageBasedBillingConfig.tsx

Refine wording in Billing settings page based on user feedback.
Fixes #13809
View UBP billing settings for users and teams.
```release-note
NONE
```

Replace ¢ -> $ and Balance -> Balance Used

---

components/public-api/README.md

Follow-up to discussion in https://github.com/gitpod-io/gitpod/pull/13824
This PR defines (some) guarantees that the `stable` package provides.
Fixes #
```release-note
NONE
```

[public-api] Define stable and experimental packages

---

components/server/src/user/enforcement-endpoint.ts

It may contain request header credentials.
Fixes #
```release-note
NONE
```

[server] Do not log full request on enforcement-endpoint

---

components/usage/pkg/apiv1/billing.go
components/usage/pkg/stripe/stripe.go

Implements creation of Stripe customers. This will be in the future extended to also store the created customer in the DB, but we need to land and deploy the following first:
* https://github.com/gitpod-io/gitpod/pull/13936
* Part of https://github.com/gitpod-io/gitpod/issues/13935
```release-note
NONE
```

[billing] Implement CreateStripeCustomer

---

.werft/util/slack.ts

I think this should be the correct way to do the request.
Fixes #
```release-note
NONE
```

Move cert not ready alert to #team-devx-channel p2

---

components/usage/pkg/apiv1/billing.go

When the customer is first create against stripe, we also store the customer ID and Attribution ID in our DB for lookup later.
Currently delegation of StripeCreation to usage is behind a feature flag on server.
* Part of https://github.com/gitpod-io/gitpod/issues/13935
```release-note
NONE
```

[stripe] Store Stripe Customer in the db on creation

---

components/registry-facade/pkg/registry/metrics.go

Fix typo
Fixes https://github.com/gitpod-io/gitpod/pull/14042/files#r1001296126
```release-note
None
```
None

registry-facade: fix typo

---

components/image-builder-api/typescript/src/sugar.ts

It may contain credentials.
Fixes #
```release-note
NONE
```

[image-builder] Do not log full request, unless in debug mode

---

components/ws-manager/pkg/manager/annotations.go

The ws-manager relies on the workspace pod annotation (as the workspace pod state) to decide the code logic. Therefore, we must ensure the annotation is added to the workspace pod. We make the minimum change to the mark workspace annotation only.
Fixes #13932
Run the integration test
```release-note
None
```
None

ws-manager: use kubernetes operation timeout for mark workspace annotation operation

---

components/server/src/user/user-service.ts

Don't attribute usage to a team without active billing.
Fixes [issue in Slack](https://gitpod.slack.com/archives/C02EN94AEPL/p1666099912056929?thread_ts=1666083078.313979&cid=C02EN94AEPL) (internal)
1. Create a new team called "Gitpod [Something]", but don't upgrade it for now
2. Add a new project under that team
3. Start a workspace for that project
4. Go to your personal billing settings (`/billing`) -- you should **not** be able to set the above team as default billing account
5. Upgrade the team to Usage-Based billing
6. In your personal billing settings (`/billing`) set your team as default billing account
7. Cancel the team's Usage-Based subscription again
8. Start a workspace for any repository that is not a project -- this should attempt to use your default billing account, but …

[server] Don't attribute usage to a team without active billing

---

components/registry-facade/pkg/registry/metrics.go

Update blob download speed buckets

---

install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/azure-setup/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/workspace/ide/constants.go

Fixes https://github.com/gitpod-io/gitpod/issues/13410
- Open a workspace with stable code
- Check if commitHash is `4eb2aeb56544f66b029ff76d46e2fa5f863fbb6c` and version is `1.72.3` in About
- Others already tested in https://github.com/gitpod-io/gitpod/pull/14085
```release-note
NONE
```

[code] update stable code image to 1.72.3

---

dev/loadgen/pkg/loadgen/executor.go

Fixes a race condition in `loadgen benchmark` where multiple goroutines access a single slice to collect started workspace IDs. Now locks modifications with a mutex.
Saw an issue in a loadtest where one workspace (started by loadgen) didn't get stopped at the end, and loadgen timed out waiting for all workspaces to stop. 90% sure it's because this race condition was triggered 😄 The workspace had the `loadgen` annotation, and didn't get a stop request.
Run `loadgen`, should stop all workspaces when done. Tested in an ephemeral cluster
```release-note
NONE
```

fix(loadgen): Lock workspace ID collection to prevent race

---

.github/pull_request_template.md

Fixes #
```release-note
none
```

add large vm option to pull request template

---

.github/pull_request_template.md

Fixes #
```release-note
none
```

fix pull request template

---

.werft/jobs/build/installer/installer.ts
.werft/jobs/build/installer/post-process.sh
dev/preview/infrastructure/harvester/cert.tf
dev/preview/infrastructure/harvester/dns.tf
install/installer/cmd/testdata/render/shortname/config.yaml
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/pkg/components/proxy/service.go
install/installer/pkg/components/ws-manager/configmap.go
install/installer/pkg/components/ws-proxy/configmap.go

In https://github.com/gitpod-io/gitpod/pull/13953 PR, we switch to use `dev` as our preview environment shortname, but we forgot to adjust dns and cert. This PR fixes that.
After merged, old PR need run with `with-clean-slate-deployment=true`, otherwise it will not execute terraform
Fixes #
1. start a workspace in this preview environment https://hw-fix-dev-cert-err.preview.gitpod-dev.com/workspaces
2. ensure the url is `workspaceid.ws-dev.*`
3. make sure there is no cert error
4. open vscode desktop to check ssh gateway works
```release-note
NONE
```

[preview-env] fix certification error and dns issue

---

components/registry-facade/pkg/registry/blob.go

Fixes #
```release-note
NONE
```

[registry-facade] Change order to fetch blobs

---

install/installer/cmd/testdata/render/shortname/output.golden

Fix the CI
Follow up https://github.com/gitpod-io/gitpod/pull/13981
CI is passed
```release-note
NONE
```

intaller: Update the golden file

---

install/installer/scripts/kots-install.sh
install/kots/manifests/gitpod-installation-status.yaml
install/kots/manifests/gitpod-installer-job.yaml

Copy of #14120
Fixes #
```release-note
```

[installer]: print the installer version to the kots-install script

---

components/ide/jetbrains/backend-plugin/launch-dev-server.sh
components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt

Copy of https://github.com/gitpod-io/gitpod/pull/14182
Cherry picked from commit 9e1dac1e7e84b5ac0f55d5280c642e37b2469164
```release-note
NONE
```

Fix 'gp open' command to open files in JetBrains Client instead of the backend IDE

---

components/image-builder-mk3/pkg/orchestrator/orchestrator.go
components/ws-manager/pkg/manager/manager.go

cherry-pick of https://github.com/gitpod-io/gitpod/pull/14215 preparing for the release
Fixes #
```release-note
```

Log JSON as strings not an array of bytes

---

components/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go

This is a cherry-pick of  #14111
Fixes #
```release-note
```

ws-daemon: Fix the problem with nice value not being applied

---

operations/observability/mixins/IDE/dashboards/components/openvsx-mirror.json

See internal chat https://gitpod.slack.com/archives/C045J13P8A1/p1666953471820629?thread_ts=1666950146.566059&cid=C045J13P8A1
Fixes #
```release-note
NONE
```

[observability] update openvsx mirror dashboard

---

components/image-builder-bob/cmd/runc-facade/main.go

Come from https://github.com/gitpod-io/gitpod/pull/14259#pullrequestreview-1161293828
None
```release-note
NONE
```

runc-facade: Align the number of retry.

---

.werft/jobs/build/job-config.ts

Fixes #
```release-note
NONE
```

Default to letsencrypt cert issuer

---

.werft/util/certs.ts

Fixes #
```release-note
NONE
```

Don't recreate cert

---

.werft/util/certs.ts
dev/preview/infrastructure/harvester/cert.tf
dev/preview/infrastructure/harvester/dns.tf

Fixes #
```release-note
NONE
```

[preview] Remove unnecessary dns

---

WORKSPACE.yaml

Fixes #
- Start workspace in preview env with `latest` code
- Check commit hash is `0532908ef0c6f752dbd9da3cd24591de0cbb4ad0` and version is `1.72.3` in `About` page
- Check if in-product changelog is correct
```release-note
NONE
```

[code] build stable image to fix in-product changelog

---

install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/azure-setup/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/workspace/ide/constants.go

Fixes #
- Open workspace in preview env with `stable` code
- Check commit hash is `0532908ef0c6f752dbd9da3cd24591de0cbb4ad0` and version is `1.72.3` in `About` page
- Check if in-product changelog is correct
```release-note
NONE
```

[code] update stable code to fix in-product changelog

---

components/dashboard/src/App.tsx

* Part of https://github.com/gitpod-io/gitpod/issues/14310
* Depends on https://github.com/gitpod-io/gitpod/pull/14301
1. Navigate to preview, open browser console on the Network tab
2. Sing-in
3. Observe requests made to ListTeams
4. Observe dashboard works as before.
```release-note
NONE
```

[dashboard] ListTeams using PublicAPI

---

dev/kubecdl/main.go

Add one more criterion to filter the control plane nodes only.
Fixes #
kubecdl different workspace cluster names.
```release-note
None
```
None

kubecdl: filter the instance-type = control-plane

---

operations/observability/mixins/IDE/dashboards/components/openvsx-mirror.json

Fixes #
```release-note
NONE
```

[openvsx-mirror] stable dashboard variables

---

operations/observability/mixins/cross-teams/dashboards/gitpod-connect-server.json

Used incorrect labels to show legend, fixes that.
Fixes #
```release-note
NONE
```

[grafana] Fix Connect / server error requests labels

---

components/ws-manager/pkg/manager/manager.go
components/ws-manager/pkg/manager/monitor.go

Refactor some PVC related code so it is easier to call pvc snapshot code from other places
Related to https://github.com/gitpod-io/gitpod/issues/14159
running integration tests should be enough to check that nothing broke after refactor
but also enable PVC in preview env, and open\close and then re-open workspace
```release-note
none
```

refactor dispose workspace when using pvc

---

.werft/jobs/build/job-config.ts

Reverts gitpod-io/gitpod#14284
```release-note
NONE
```

Revert "Default to letsencrypt cert issuer"

---

components/public-api-server/pkg/apiv1/team.go
components/public-api-server/pkg/apiv1/team_test.go

* Part of https://github.com/gitpod-io/gitpod/issues/14335
* Unit tests
1. Open up preview, log-in
2. Obtain a token by running the below in the browser console
```javascript
"function:getTeams",
"function:getTeam",
```
3. Set your credentials on the command line:
```bash
BEARER_TOKEN="<token>"
```
4. Create a couple of teams, adjusting the `<team_name_X>` variable
```
curl \
--header 'Content-Type: application/json' \
--header "Authorization: Bearer $BEARER_TOKEN" \
--data '{ "name": "<team_name_1>" }' \
https://api.mp-papi-gea0b0afd009.preview.gitpod-dev.com/gitpod.experiment …
```

[public-api] Implement experimental GetTeam

---

components/public-api-server/pkg/apiv1/team.go
components/public-api-server/pkg/apiv1/team_test.go

* Part of https://github.com/gitpod-io/gitpod/issues/14352
Unit tests.
1. Open up preview, log-in
2. Obtain a token by running the below in the browser console
```javascript
"function:getTeams",
"function:joinTeam",
```
3. Set your credentials on the command line:
```bash
BEARER_TOKEN="<token>"
```
3. Join team using the API
```bash
curl \
--header 'Content-Type: application/json' \
--header "Authorization: Bearer $BEARER_TOKEN" \
--data '{ "invitation_id": "d1ebf649-dbf0-4b52-a5e1-53b300de0096" }' \
https://api.mp-papi-join-team.preview.gitpod-dev.com/gitpod.experimental.v1.Te …
```

[public-api] Implement experimental JoinTeam

---

components/ws-manager/pkg/manager/metrics.go
components/ws-manager/pkg/manager/status.go
components/ws-manager/pkg/manager/testdata/actOnPodEvent_failedWorkspaceMount_PENDING00.golden
components/ws-manager/pkg/manager/testdata/status_failedWorkspaceMount_PENDING00.golden

Skip the cannot mount workspace event because it might be an intermediate state.
Also, add two counter metrics to record when it happens.
Fixes #14032
We don't know how to reproduce the mount device error.
```release-note
None
```
None

Skip the cannot mount workspace event because it might be an intermediate state

---

components/dashboard/src/App.tsx

Website Slug for `gitpod.io/cde`
Fixes #
```release-note
NONE
```

Add Website Slug for CDE

---

WORKSPACE.yaml
components/ide/code/leeway.Dockerfile
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/azure-setup/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/blobserve/configmap.go

Fixes #
```release-note
NONE
```

switch to openvsx mirror

---

components/public-api-server/pkg/server/metrics.go

Forgot to actually increment the metric :/
Fixes #
```release-note
NONE
```

[public-api] Fix request started metric reporting

---

components/gitpod-protocol/go/gitpod-service.go
components/gitpod-protocol/go/mock.go
components/public-api-server/pkg/apiv1/team.go
components/public-api-server/pkg/apiv1/team_test.go

Implements updating team member (setting role) and deleting team members.
* Part of https://github.com/gitpod-io/gitpod/issues/14311
* Part of https://github.com/gitpod-io/gitpod/issues/14312
Unit tests
You can see this implementation in https://github.com/gitpod-io/gitpod/pull/14412, follow test instructions
```release-note
NONE
```

[public-api] Implement UpdateTeamMember and DeleteTeamMember

---

components/dashboard/src/teams/Members.tsx

Uses Public API to update team members and delete team members.
* Fixes https://github.com/gitpod-io/gitpod/issues/14312
* Fixes https://github.com/gitpod-io/gitpod/issues/14311
* Depends on https://github.com/gitpod-io/gitpod/pull/14411
1. Preview env
2. Create a team
3. Join the team with another account
4. Update new user to Owner, observe request is made to `UpdateTeamMember` over HTTP
5. Delete the team member, observe request is made to `DeleteTeamMember` over HTTP
6. Both operations complete OK
```release-note
NONE
```

[dashboard] Use Public API to UpdateTeamMember and DeleteTeamMember

---

components/ide/code/startup.sh
install/installer/pkg/components/blobserve/configmap.go

See [internal chat](https://gitpod.slack.com/archives/C045J13P8A1/p1667557974561709?thread_ts=1667535351.074909&cid=C045J13P8A1)
Fixes #
- Open workplace in preview env with latest code
- Make sure workspace in browser works
- Search with `/ide` folder with `{{trustedDomain}}` and `{{extensionsGalleryItemUrl}}`, should be zero result
```release-note
NONE
```

[code] update startup.sh to replace temporary variables

---

install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/azure-setup/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/workspace/ide/constants.go

[code] update stable code to add gallery metrics
Fixes #
```release-note
NONE
```

[code] update stable code to add gallery metrics

---

test/tests/components/ws-manager/prebuild_test.go

test: check the /workspace UID:GID is gitpod:gitpod
Fixes #14003
The integration test pass.
```release-note
None
```
None

test: check the /workspace UID:GID is gitpod:gitpod

---

operations/observability/mixins/IDE/dashboards/components/openvsx-mirror.json

Fixes #
See https://grafana.gitpod.io/d/lkfc1FD4k/openvsx-mirror-with-incoming-tests?orgId=1
```release-note
NONE
```

[openvsx-mirror] add incoming requests monitoring

---

components/public-api-server/pkg/apiv1/team.go

Parses TeamID as a UUID before sending the request to `server`. This adds an extra layer of validation.
Fixes #
```release-note
NONE
```

[public-api] Parse TeamID as UUID for extra validation

---

components/supervisor/pkg/supervisor/supervisor.go

Disable `config analyze` `pref analyze` and `metricsReporter` for headless (imagebuild + prebuild) workspace
See also ErrorReporting [[1](https://console.cloud.google.com/errors/detail/CJL5yduOy_66tgE;service=supervisor?project=gitpod-191109)][[2](https://console.cloud.google.com/errors/detail/CI2A8ubakqytwAE;service=supervisor?project=gitpod-191109)]
Fixes #
- Check if https://github.com/gitpod-io/gitpod/pull/13751 still works for you opened workspace if you want
- Check if https://github.com/gitpod-io/gitpod/pull/12680 still works for you opened workspace if you want
```release-note
NONE
```

[supervisor] disable analyze in headless workspace

---

operations/observability/mixins/workspace/rules/satellite/workspaces.yaml

We've just added an SLO for our observability stack, and almost immediately after adding it, we got [notified ](https://gitpod.slack.com/archives/C047CL7KN7M/p1668007583298319)😬 
After investigation, I've found out that I made some syntaxes mistakes in https://github.com/gitpod-io/gitpod/pull/13850, so this PR fixes them.
Here are the logs coming out of prometheus-operator:
```
level=info ts=2022-11-09T15:26:39.041581448Z caller=rules.go:340 component=prometheusoperator msg="Invalid rule" err="4:11: group \"workspace-rules\", rule 1, \"gitpod_workspace_regular_not_active_percentage\": could not parse expression: 1:60: parse error: unexpected right parenthesis ')'"
level=info ts=2022-11-09T15:26:39.041635381Z caller=rules.go:340 component=prometheusoperator msg="Invalid rule" err="27:11: …
```

Fix syntax errors

---

.github/workflows/jetbrains-update-plugin-platform-template.yml
.github/workflows/jetbrains-update-plugin-platform.yml

Add GitHub tokens for automatically creating, asking for reviews, and approving PRs.
- Fixes https://github.com/gitpod-io/gitpod/issues/12194
- Also fixes this kind of Job failure: https://github.com/gitpod-io/gitpod/actions/runs/3427555985/jobs/5711056573
It has been tested manually by dispatching the action targeting this branch. See the result here:
- https://github.com/gitpod-io/gitpod/pull/14569
```release-note
NONE
```

[JetBrains] Add GitHub tokens for automatically creating, asking for reviews, and approving PRs

---

components/gitpod-protocol/go/gitpod-service.go
test/pkg/integration/workspace.go
test/tests/components/server/server_test.go
test/tests/components/ws-manager/dotfiles_test.go
test/tests/components/ws-manager/protected_secrets_test.go

Fixes #
```release-note
NONE
```

[server] update go api

---

components/public-api-server/pkg/apiv1/team.go

Reduces duplication related to connection retrieval. Functionality remains the same
Fixes #
Unit tests
```release-note
NONE
```

[public-api] Cleanup connection retrieval to reduce duplication

---

components/server/src/workspace/gitpod-server-impl.ts

Looks to be entirely unused. There are no references to it, and no invocations in [metrics](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%28increase%28gitpod_server_api_calls_total%7Bmethod%3D%5C%22deprecatedDoWatchWorkspaceImageBuildLogs%5C%22%7D%5B1m%5D%29%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-90d%22,%22to%22:%22now%22%7D%7D) 
Fixes #
```release-note
NONE
```

[server] Remove deprecatedDoWatchWorkspaceImageBuildLogs() - unused

---

components/ide/jetbrains/gateway-plugin/gradle-latest.properties

This PR updates the Platform Version from JetBrains Gateway Plugin to the latest version.
1. Ensure you have the [latest JetBrains Gateway](https://www.jetbrains.com/remote-development/gateway/) installed.
3. Create a new workspace from the Gateway (it's ok to use the pre-selected IDE and Repository) and confirm if JetBrains Client can connect to it.
```release-note
NONE
```
_This PR was created automatically with GitHub Actions using [this](https://github.com/gitpod-io/gitpod/blob/main/.github/workflows/jetbrains-update-plugin-platfo …

[JetBrains] Update Platform Version from JetBrains Gateway Plugin

---

components/usage/pkg/db/usage.go

To reduce probability db-sync misses the update
* Relates to https://github.com/gitpod-io/gitpod/issues/14560
```release-note
NONE
```

[usage] Decrease Usage record create batch size

---

README.md
components/dashboard/src/Login.tsx

This PR Proposes to change the text on `/#https://github.com/gitpod-io/empty` Page with our [recent announcements](https://www.gitpod.io/cde)
|Old|New|
|---|---|
|![image](https://user-images.githubusercontent.com/55068936/201461529-556e1940-9e86-484a-b829-ccacf32a39f6.png)|![image](https://user-images.githubusercontent.com/55068936/201461569-610274a4-e2fd-4b60-9085-7889834caf67.png)|
Fixes #[internal](https://gitpod.slack.com/archives/C02EN94AEPL/p1668184183523649)
- Open Preview
- do a new Login 
```release-note
NONE
```

nit-fix: Onboarding Text on Login Dashboard

---

README.md
components/dashboard/src/Login.tsx

followup #14632
Fixes #
```release-note
NONE
```

nit-fix 💄- Followup: #14632

---

components/ws-daemon/cmd/run.go

Ensure that at least there is 1GB of free space or the value configured by the `diskGuard` setting to avoid nodes without disk
```release-note
NONE
```

[ws-daemon] Do not allow the start of ws-daemon if there not disk space

---

.github/workflows/semgrep.yml

This adds a semgrep.yml configuration file to allow code security scanning on our public Gitpod repository.

Add semgrep.yml to this repository

---

components/ee/db-sync/src/replication.ts

Small follow up to https://github.com/gitpod-io/gitpod/pull/14568
Fixes #
```release-note
NONE
```

[db-sync] Fix log line

---

components/server/src/workspace/workspace-starter.ts

This makes the `actuallyStartWorkspace` function poll the database in parallel to waiting for the response of the `startWorkspace` request. Turns out `ws-manager` is sending status updates before the requests got answered.
As a result we get the ideURL sooner and can redirect users to the workspace starting page earlier.
Improves #14061
```release-note
NONE
```

[server] don't wait for ws-man call.

---

.werft/workspace-run-integration-tests.sh

Update the integration job to use run.sh
Follow-up https://github.com/gitpod-io/gitpod/issues/13197
[A sample result](https://werft.gitpod-dev.com/job/gitpod-custom-to-update-integration-job.4)
```
werft run github -j ./.werft/workspace-run-integration-tests.yaml
```
```release-note
None
```

test: Update the integration job to use run.sh

---

components/common-go/experiments/experimentstest/client.go
components/common-go/experiments/experimentstest/client_test.go

Test utility to test experiments client, to be used with https://github.com/gitpod-io/gitpod/pull/14685
Fixes #
unit
```release-note
NONE
```

[common-go] Add experiments test client

---

components/gitpod-db/src/typeorm/user-db-impl.ts

See if this captured the ongoing error in https://github.com/gitpod-io/gitpod/issues/14464
Fixes #
```release-note
NONE
```

[db] Log error when storing ssh public key

---

install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/azure-setup/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/public-api-server/deployment.go
install/installer/pkg/components/public-api-server/objects_test.go

We'll need to talk to the DB as part of https://github.com/gitpod-io/gitpod/issues/14280
* Part of https://github.com/gitpod-io/gitpod/issues/14602
```release-note
NONE
```

[public-api] Inject database environment

---

components/server/src/user/newsletter-subscription-controller.ts

Fix unsubscribe API for users with a + in their email address
Fixes https://github.com/gitpod-io/gitpod/issues/14072
1. Log in to the preview environment with a GitHub or GitLab account that has a primary email address with a `+` in it (e.g. `name+whatever@gitpod.io`)
a. _(Alternatively, you may also log in with any account, then connect to your preview environment DB, and modify the `primaryEmail` column of your user's `d_b_identity` entry)_
2. Visit `/api/unsubscribe?email=EMAIL&type=onboarding` (where `EMAIL` is your email address with a `+` in it)
3. This should redirect you to the success page
4. Go back to the preview environment (not prod!) go to your notification settings -- the Changelog checkbox should be unchecked
```release-note
NONE
``` …

Fix unsubscribe API for users with a + in their email address

---

components/public-api-server/pkg/apiv1/tokens.go
components/public-api-server/pkg/apiv1/tokens_test.go

* Creates a stub implementation for CreateToken RPC
* Ensures that only users with enabled feature flag can access the RPC
* Slight refactor to reduce duplication
* Part of https://github.com/gitpod-io/gitpod/issues/14609
Unit tests
```release-note
NONE
```

[public-api] Initial stub implemention for CreateToken

---

components/server/src/workspace/workspace-starter.ts

fixes a linting issue in server
Fixes #
```release-note
NONE
```

[server] fix linting error

---

components/ide/jetbrains/gateway-plugin/gradle-stable.properties

This PR updates the Platform Version from JetBrains Gateway Plugin (Stable) to the latest version.
1. Ensure you have the [latest JetBrains Gateway](https://www.jetbrains.com/remote-development/gateway/) installed.
3. Create a new workspace from the Gateway (it's ok to use the pre-selected IDE and Repository) and confirm if JetBrains Client can connect to it.
```release-note
NONE
```
_This PR was created automatically with GitHub Actions using [this](https://github.com/gitpod-io/gitpod/blob/main/.github/workflows/jetbrains-update-plug …

[JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)

---

components/gitpod-db/src/typeorm/auth-code-repository-db.ts

This is an attempt to fix https://github.com/gitpod-io/gitpod/issues/14464
There is a mismatch between the library's definition of `OAuthAuthCode` shape, which leaves the `user` attribute optional, and the typeorm/db entity, where the attribute/column is mandatory. 
Instead of modifying the table column, it seems to be preferable to ensure we're not proceeding with issuing codes if no user is provided. That decision might be reconsidered in future, but for now this seems to be the safe path without gathering the whole context here. Also, this would not worsen behavior. 
```release-note
NONE
```

[server] fix persist of DBOAuthAuthCodeEntry

---

components/gitpod-db/go/BUILD.yaml
components/gitpod-db/go/go.mod

Initial setup of a `gitpod-db/go` package, without any implementation yet.
Fixes #
```release-note
NONE
```

Setup gitpod-db/go package

---

components/ide/jetbrains/gateway-plugin/gradle-latest.properties

This PR updates the Platform Version from JetBrains Gateway Plugin (EAP) to the latest version.
3. Create a new workspace from the Gateway (it's ok to use the pre-selected IDE and Repository) and confirm if JetBrains Client can connect to it.
```release-note
NONE
```
_This PR was created automatically with GitHub Actions using [this](https://github.com/gitpod-io/gitpod/blob/main/.github/workflows/jetbra …

[JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)

---

install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden

[installer] fix render test failed
Fixes #
```release-note
NONE
```

[installer] fix render test failed

---

components/server/src/workspace/workspace-starter.ts

We don't want to consider user settings for prebuilds. This change removes that consideration.
Fixes #
```release-note
NONE
```

[projects] ignore user settings for prebuilds

---

install/installer/pkg/components/public-api-server/configmap.go

Fixes the path which is mounted onto the pod
Fixes #
```release-note
NONE
```

[installer] Fix token signing key subpath

---

components/dashboard/src/components/UsageBasedBillingConfig.tsx
components/dashboard/src/index.css

Updates the credit balance information as suggested in #14847 
Fixes #14847
```release-note
NONE
```

[dashboard] update balance element

---

components/public-api-server/pkg/apiv1/tokens_test.go

Introduces a workflow test. Still a unit test, but it goes through the various CRUD operations in a chain a user might. This helps ensure that while the individual RPCs can work in isolation, it's important that they can be chained to perform workflows.
Will be extended once we implement more of the Personal Access Token RPCs
Fixes #
Unit
```release-note
NONE
```

[public-api] PAT Workflow test

---

.werft/workspace-run-integration-tests.sh

test: Fix the output when the test failed.

---

.werft/platform-delete-preview-environment.yaml
.werft/platform-delete-preview-environments-cron.yaml
.werft/platform-trigger-artificial-job.yaml
.werft/workspace-run-integration-tests.yaml

`Workdir` is set to `/workspace`, and `LEEWAY_WORKSPACE_ROOT` is hardcoded in the [docker image](https://github.com/gitpod-io/gitpod/blob/main/dev/image/Dockerfile#L180), so leeway commands fail.
Fixes 
https://werft.gitpod-dev.com/job/gitpod-custom-platform-artificial-job-d80b98f39aa1e27ebb30.1
```bash
Werft job failed with an error Error: leeway run dev/preview/previewctl:install exit with non-zero status code.
at handleResult (/workspace/.werft/util/shell.ts:42:19)
at exec (/workspace/.werft/util/shell.ts:60:9)
at configureGlobalKubernetesContext (/workspace/.werft/platform-delete-preview-environment.ts:97:9)
at /workspace/.werft/platform-delete-preview-environment.ts:86:5
at step (/workspace/.werft/platform-delete-preview-environment.ts:33:23)
at Object.next …
```

Set correct LEEWAY_WORKSPACE_ROOT for jobs

---

test/run.sh

From the [log](https://werft.gitpod-dev.com/job/gitpod-custom-to-fix-test-output.0/logs) of the integration test, we observed that only the ws-manager component was run.
Fixes #
Check the werft result, all the components should run the integration test
- ws-manager
- image-builder
- content-service
- ws-daemon
- workspace
```release-note
None
```

test: fix workspace only ran ws-manager integration test

---

test/run.sh

This reverts commit bdddbb99fff829f76758f9cdae6888d3d570066a.
Fixes #
```release-note
None
```

Revert "test: fix workspace only ran ws-manager integration test"

---

components/gitpod-db/go/personal_access_token.go
components/gitpod-db/go/personal_access_token_test.go
components/public-api-server/pkg/apiv1/tokens.go
components/public-api-server/pkg/apiv1/tokens_test.go

Implements PAT Udpate. 
* Update uses an UpdateMask to specify which fields should be updated.
* When no field is specified, the update assumes all fields should be updated.
* Part of https://github.com/gitpod-io/gitpod/issues/14612
* Depends on https://github.com/gitpod-io/gitpod/pull/14889
* Depends on https://github.com/gitpod-io/gitpod/pull/14903
* Depends on https://github.com/gitpod-io/gitpod/pull/14901
Unit tests
```release-note
NONE
```

[pat] Update Personal Access Token

---

components/dashboard/src/contexts/FeatureFlagContext.tsx

See code comments for explanation.
Fixes #
1. Preview
2. Create a team, get the team's ID
3. Update the `personalAccessTokensEnabled` feature flag to enable for your team
4. You should see Access Tokens in your personal settings menu
```release-note
NONE
```

[dashboard] Fix feature flag context evaluation

---

components/dashboard/src/settings/PersonalAccessTokens.tsx

To allow short-lived tokens, for experimentation and such
Fixes #
```release-note
NONE
```

[pat] Add 7 days as option for PAT expiration

---

components/registry-facade/pkg/registry/blob.go

Part of https://github.com/gitpod-io/gitpod/issues/13915
Works fine
```release-note
None
```

registry-facade: Be able to see where the error is coming from

---

.github/workflows/semgrep.yml

This change triggers a full scan of our repository every Wednesday at 12 am.

Adjust cron job in semgrep.yml

---

components/supervisor/pkg/metrics/metrics.go
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/azure-setup/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/ide-metrics/configmap.go

[supervisor] add some bucket for supervisor_ide_ready_duration_total
Fixes #
```release-note
NONE
```

[supervisor] add some bucket for supervisor_ide_ready_duration_total

---

components/gitpod-db/go/cost_center.go

Reset usage to the spending limit at most.
Fixes #
```release-note
NONE
```

[usage] only reset to max spendingLimit

---

components/public-api-server/pkg/apiv1/tokens.go

Removes old log which is not adding any value anymore
Fixes #
```release-note
NONE
```

[pat] Remove handling log message

---

components/public-api-server/pkg/apiv1/tokens.go
components/public-api-server/pkg/apiv1/tokens_test.go

Ensures we correctly handle not found, and test for it
Fixes #
unit tests
```release-note
NONE
```

[pat] Fix NotFound error handling

---

components/dashboard/src/settings/PersonalAccessTokens.tsx

This will update the access token scope name. 
See [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1669978940472409) (internal). Cc @laushinka @easyCZ 
1. Create a new access token and notice the new scope name (_Full Access_) in the creation form.
1. Edit an access token and notice the new scope name (_Full Access_).
1. View the access tokens list and notice the new scope name (_Full Access_).
```release-note
NONE
```

Update access token scope name

---

components/ws-manager/pkg/manager/manager.go
components/ws-manager/pkg/manager/metrics.go

Improve start and stop workspace metrics so that we can build SLOs for them.
Fixes #
```release-note
none
```

[ws-manager] improve start workspace metric

---

components/dashboard/src/components/UsageBasedBillingConfig.tsx

updates the description on the billing page
Fixes #15160
```release-note
NONE
```

[dashboard] update description

---

operations/observability/mixins/workspace/rules/central/nodes.yaml

subj.
Fixes #
```release-note
none
```

[alerts] improve autoscale alert to provide actual reason for failure in alert message

---

operations/observability/mixins/IDE/dashboards/components/ide-service.json

[observability] fix ide-service dashboard
Fixes #
```release-note
NONE
```

[observability] fix ide-service dashboard

---

.werft/jobs/build/build-and-publish.ts

This PR removes the helm release publish logic, as we have
moved away from helm charts to our own `installer`. This
just removes that part of the code as its not needed anymore.
Fixes https://github.com/gitpod-io/gitpod/issues/9845
```release-note
NONE
```

[werft] Remove helm publish job

---

dev/preview/workflow/preview/deploy-gitpod.sh

Add a bit of retries, and provides a more clear error message when it fails. Fixing the underlying issue for the certificate problems will be addressed in https://github.com/gitpod-io/gitpod/issues/15146
Fixes https://github.com/gitpod-io/gitpod/issues/14956
```release-note
NONE
```
N/A

Wait for certificate and log error when it fails

---

components/public-api-server/pkg/apiv1/user.go
components/public-api-server/pkg/apiv1/user_test.go
components/public-api-server/pkg/apiv1/workspace.go
components/public-api-server/pkg/apiv1/workspace_test.go

Implementation for https://github.com/gitpod-io/gitpod/pull/15110
```release-note
NONE
```

[public-api] implement public api methods for supervisor

---

.github/workflows/code-nightly.yml

code-nightly point back to main
```release-note
NONE
```

[code] code-nightly point back to main

---

components/ide/jetbrains/backend-plugin/gradle-latest.properties

This PR updates the Platform Version from JetBrains Backend Plugin (EAP) to the latest version.
```release-note
NONE
```
_This PR was created automatically with GitHub Actions using [this](https://github.com/gitpod-io/gitpod/blob/main/.github/workflows/jetbrains-update-plugin-platform-template.yml) template._

[JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)

---

components/ws-manager/pkg/manager/monitor.go

Fixes #
```release-note
none
```

[wsmanager] improve error tracing in finalize workspace content

---

dev/preview/workflow/preview/deploy-harvester.sh

Fixes #
```release-note
NONE
```

Fix var assignment in deploy-harvester

---

.github/CODEOWNERS

Fixes #
```release-note
NONE
```

[codeowners] Add IAM component to WebApp codeowners

---

install/installer/pkg/components/slowserver/deployment.go
install/installer/pkg/components/slowserver/render_test.go

Ensure the `db-waiter` init container in `slow-server` goes through Toxiproxy.
Not doing this may be a cause of some connection failures we see from `slow-server` to the database.
See [internal discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1670922098012619) for more context.
Part of #9198 
```release-note
None
```

[db-sync] Ensure the `db-waiter` init container in `slow-server` goes through Toxiproxy

---

operations/observability/mixins/cross-teams/dashboards/gitpod-grpc-client.json

Part of https://github.com/gitpod-io/ops/pull/7437
Fixes #
See also test grafana dashboard https://grafana.gitpod.io/d/YcUQEH54k/grpc-client-copy?orgId=1
Their JSON should be similar
```release-note
NONE
```

[observability] add job variable for grpc client

---

README.md

Update link to Awesome Gitpod repository to <https://github.com/Gitpod-Samples/awesome-gitpod>.
```release-note
NONE
```

Update link to Awesome Gitpod repository

---

.werft/jobs/build/trigger-integration-tests.ts
.werft/workspace-run-integration-tests.sh
test/README.md
test/pkg/report/features.go
test/pkg/report/report.go
test/run.sh
test/tests/workspace/cgroup_v2_test.go
test/tests/workspace/contexts_test.go
test/tests/workspace/example_test.go

This report style comes from [our RFC](https://www.notion.so/gitpod/How-to-create-the-Quality-Assurance-Report-for-the-workspace-a8b7ee2570c44a25aed7bd7d4766f1b1)
For now, I will adopt it for some test cases, and if we like, I will create PRs to handle others as well.
NONE
```console
./run.sh -r report.csv -s workspace 
cat report.csv
```
```release-note
NONE
```

test: Several test cases are supported for reporting

---

components/iam/pkg/server/server.go

Fixes #
```release-note
NONE
```

[iam] Do not log at Trace level

---

components/iam/pkg/server/server.go

Minor cleanup of how routes are registered against the IAM server. See comments for more details.
Fixes #
```release-note
NONE
```

[oidc] Cleanup registration of route handlers

---

components/ws-manager/pkg/manager/manager.go

Improve readability
NONE
```release-note
NONE
```

ws-manager: A bit improve the code not to use the magic number

---

components/iam/pkg/oidc/oauth2.go
components/iam/pkg/oidc/router.go
components/iam/pkg/oidc/service.go
components/iam/pkg/oidc/service_test.go
components/iam/pkg/server/server.go

Touch ups on the OIDC service. See inline comments for reasoning.
Fixes #
```release-note
NONE
```

[iam] Drop OIDC prefix from service, remove unused handler

---

components/gitpod-protocol/go/gitpod-config-types.go

(This file has no cache and will be generated every time)
To fix GH Action https://github.com/gitpod-io/gitpod/actions/runs/3825836824/jobs/6509111555 and other `gitpod-protocol` related leeway builds
Fixes #
No need
```release-note
NONE
```

Update copyright of generated file

---

components/server/ee/src/prebuilds/prebuild-manager.ts
components/server/ee/src/prebuilds/start-prebuild-context-parser.ts

Signed-off-by: Siddhant Khare <siddhant@gitpod.io>
Minor error message change
Fixes [internal convo.](https://gitpod.slack.com/archives/C020VCB0U5A/p1672732172597729?thread_ts=1672726351.522129&cid=C020VCB0U5A) 
```release-note
NONE
```

fix: messaging around projects & prebuild error

---

.github/workflows/code-nightly.yml
.github/workflows/jetbrains-auto-update-template.yml
.github/workflows/jetbrains-integration-test.yml
.github/workflows/jetbrains-update-backend-latest.yml
.github/workflows/poc-build.yml
.gitpod.yml
.werft/aks-installer-tests.yaml
.werft/build.yaml
.werft/cleanup-installer-tests.yaml
.werft/debug.yaml
.werft/eks-installer-tests.yaml
.werft/gke-installer-tests.yaml
.werft/ide-integration-tests-startup.yaml
.werft/k3s-installer-tests.yaml
.werft/platform-delete-preview-environment.yaml
.werft/platform-delete-preview-environments-cron.yaml
.werft/platform-trigger-artificial-job.yaml
.werft/platform-trigger-werft-cleanup.yaml
.werft/workspace-run-integration-tests.yaml
dev/image/Dockerfile

Use [Leeway v0.7.3](https://github.com/gitpod-io/leeway/releases/tag/v0.7.3) everywhere
Fixes https://github.com/gitpod-io/gitpod/issues/15485
- ✅ Open workspace from this PR and verify `leeway run dev:preview` works
- ✅Run a Werft job from this branch (`werft job run github`) and verify the build is happy ([job](https://werft.gitpod-dev.com/job/gitpod-build-mads-leeway-v0.7.3.6))
```release-note
NONE
```
N/A

Use Leeway v0.7.3

---

components/iam/pkg/apiv1/oidc_config.go
components/iam/pkg/apiv1/oidc_config_test.go

Implements GetOIDCClientConfig RPC
Needed to be retrieved when authenticating through an SSO provider
Fixes #
* Unit tests
```release-note
NONE
```

[iam] Add Get OIDC Client Config RPC

---

components/ws-manager/pkg/manager/monitor.go

Fixes #15604
See original issue
```release-note
none
```

fix headless and prebuild pods not removing never ready annotation

---

components/ws-manager/pkg/manager/status.go

Add more log to help us troubleshoot issue #12021
Related to #12021
We don't know how to reproduce the issue #12021 yet.
```release-note
None
```
None

ws-manager: add log to help troubleshoot

---

install/installer/pkg/common/common.go
install/installer/pkg/components/openfga/objects.go
install/installer/pkg/components/slowserver/objects.go
install/installer/pkg/components/toxiproxy/objects.go
install/installer/pkg/components/usage/configmap.go
install/installer/pkg/components/usage/objects.go

Refactor to reduce duplication, functionally the same.
Fixes #
```release-note
NONE
```

[installer] Reduce duplication when extracting experimental webapp config

---

components/gitpod-db/src/typeorm/typeorm.ts

Make sure that all call to `getConnection` wait for the same result.
Fixes #15655
- open a workspace on this branch
- restart the `server` component multiple times
- note that is no longer an error about `RepositoryNotFoundError: No repository for "DBAuthProviderEntry" was found. Looks like this entity is not registered in current "default" connection?`
```release-note
Fix race for DB connection
```

[db] Sync on connection initialization

---

components/supervisor/cmd/init.go

show detail message if supervisor failed
Fixes #14293
1. start a workspace using https://github.com/iQQBot/test.test/tree/pd/test-log this branch, it will fail and show detail log 
```release-note
NONE
```

[supervisor] show detail message if supervisor failed

---

components/supervisor/pkg/terminal/terminal.go

I've seen terminal test are failing randomly due to timed out https://werft.gitpod-dev.com/job/gitpod-build-jp-ws-status-stream.0
So did a little cleanup, hope it it fixes it
Related https://github.com/gitpod-io/gitpod/issues/14425
```release-note
NONE
```

Improve terminal close

---

components/public-api-server/pkg/apiv1/workspace.go

Handle StreamWorkspaceStatus send error
Addresses TODO comment https://github.com/gitpod-io/gitpod/pull/15451#discussion_r1064456341
```release-note
NONE
```

[public-api] Handle StreamWorkspaceStatus send error

---

components/supervisor/pkg/serverapi/publicapi.go

See [internal chat](https://gitpod.slack.com/archives/C01TNS8EVQT/p1673560111740899)
Fixes #
- Setup your dotfiles in preview env
- Open workspace to check if dotfiles works
Check points
✅ have only one `switch to pubcliAPI` logging in supervisor (no data race)
✅ instance update listen should works (port private/public)
✅ dotfiles
✅ switch between server / public API, backoff cancel too (no error like `backoff failed to get workspace service client of PublicAPI, try again` with error `context canceled`)
```release-note
NONE
```

Fix supervisor stuck on get config value

---

.werft/platform-delete-preview-environment.yaml

fix bad indentation from: https://github.com/gitpod-io/gitpod/pull/15764
Fixes #
```release-note
NONE
```

Add resource requirements for preview delete job

---

components/content-service/pkg/storage/s3.go

Adjust `s3manager` configuration
extracted from https://github.com/gitpod-io/gitpod/pull/15132
```release-note
NONE
```

Improve S3 speed

---

.github/workflows/build.yml

Run `leeway vet` during GHA build.
Fixes https://github.com/gitpod-io/gitpod/issues/15771
```release-note
NONE
```

Support Leeway Vet

---

components/supervisor/pkg/serverapi/publicapi.go
components/supervisor/pkg/supervisor/supervisor.go

Remove `trackEvent` api method and add caching to `GetOwnerID`
1. Open workspace check it starts sucessfully
2. Check `supervisor_readiness` event gets send
```release-note
NONE
```
/werft with-preview
/werft analytics=segment

[supervisor] Remove trackEvent api method

---

components/dashboard/src/service/service.tsx

Sends missing initial status update
1. Open a workspace and check it loads sucessfully
2. Reload workspace page, it should show editor again almost immeadiatelty
```release-note
NONE
```

Fix send initial status in IDEFrontendService

---

components/gitpod-db/src/user-to-team-migration-service.spec.db.ts
components/gitpod-db/src/user-to-team-migration-service.ts

User's without a team, will get one with 500 credits free per month.
See #15786
- Enable the migration (use `toa@` in your user's email)
- verify your team has freemium. 
- delete team
- verify you automatically get a new one and that this one again has 500 free.
```release-note
NONE
```

[server] create a freemium team when no team exist

---

.github/workflows/build.yml

Run Pre-Commit-Checks in the GHA build.
Fixes #15772
```release-note
NONE
```

Add Pre-Commit-Checks

---

.werft/platform-trigger-werft-cleanup.yaml

Fixes #
```release-note
NONE
```

Run node clean-up cron job more often

---

components/supervisor/pkg/serverapi/publicapi.go
components/supervisor/pkg/supervisor/supervisor.go

Delete `GetOwnerID` and use OwnerId from config
Check workspace opens successfully
```release-note
NONE
```

Delete `GetOwnerID` and use OwnerId from config

---

install/installer/cmd/testdata/render/overrides-inline/output.golden

Update `output.golden` file to fix the build pipeline.
Golden file updated by running `cd /workspace/gitpod/install/installer && make generateRenderTests`.
- https://werft.gitpod-dev.com/job/gitpod-build-main.6275
Confirm if Werft Build passed: https://werft.gitpod-dev.com/job/gitpod-build-felladrin-update-output-golden-file.0
```release-note
NONE
```

Update `output.golden` file to fix the build pipeline

---

components/dashboard/src/feedback-form/FeedbackComponent.tsx

- Shift the position of `emojiGroup`.
Fixes #15760 
```release-note
NONE
```

[revamp] : feedback widget UX

---

components/ws-manager/pkg/manager/manager.go

ws-manager: Add a log and trace not to overlook workspace schedule failure
For https://github.com/gitpod-io/gitpod/issues/15859
Only add a log and trace
```release-note
NONE
```

ws-manager: Add a log and trace not to overlook workspace schedule failure

---

install/installer/pkg/components/spicedb/deployment.go

Otherwise it fails to schedule in staging due to small nodes
Fixes #
```release-note
NONE
```

[spicedb] Reduce CPU requests to 1 CPU

---

components/workspacekit/cmd/rings.go

Some times supervisor gets polluted by resources exhausted errors, probably because of slow resolution of workspace info. Instead of failing, this PR propose to return a last successful information and let supervisor try again later. It already does it with the exponential backoff.
It was very apparent as part of https://github.com/gitpod-io/gitpod/pull/15795 with 2 supervisors doing it at the same time.
- Start a workspace, run gp top for sometime, check out that there is are no too many requests in supervisor anymore.
```release-note
NONE
```

[workspacekit] fall back to last successful workspace info on resource exhausted

---

components/gitpod-db/go/dbtest/conn.go

Follow-up fix for #15824
Fixes #15824
```release-note
NONE
```
leeway-target=components/gitpod-db/go:lib

Fix DB test

---

components/supervisor/pkg/serverapi/publicapi.go

Do not log error when it has `Unavailable` code
```release-note
NONE
```

[supervisor] Do not log error when it has `Unavailable` code

---

components/dashboard/src/teams/SSO.tsx

Quick fix for copy&paste error.
Related to https://github.com/gitpod-io/gitpod/pull/15903
```release-note
NONE
```

[sso/ui] Fix modal heading

---

components/server/src/ide-service.ts

Remove unused code. We always use IDE-service since mid December.
Fixes #
Test that a workspace can be started.
```release-note
NONE
```

[ide-service] remove unused code

---

operations/observability/mixins/meta/dashboards/components/server.json

Unusure, why it wasn't picked up by a linter. Will investigate.
Fixes #
```release-note
NONE
```

[dashboards] Fix double comma

---

.github/workflows/preview-env-check-regressions.yml

Introduces a new empty workflow. I created this PR for it so I can more easily work on the actual implementation on my branch by invoking the workflow manually.
Part of https://github.com/gitpod-io/gitpod/issues/15869
N/A
```release-note
NONE
```
N/A

Introduce new (empty) workflow

---

install/installer/pkg/components/spicedb/deployment.go

Fix for https://gitpod.slack.com/archives/C021ENP4CEN/p1674730281778279
Fixes #
```release-note
NONE
```

[spicedb] Fix env vars

---

install/installer/pkg/components/spicedb/deployment.go
install/installer/pkg/components/spicedb/migrations.go

Fixes #
```release-note
NONE
```

[spicedb] Remove duplicate DB_HOST env var for db-waiter

---

install/installer/pkg/components/spicedb/migrations.go

Fixes #
```release-note
NONE
```

[spicedb] Fix migrations service account name

---

.werft/platform-delete-preview-environments-cron.yaml

Only run every 4 hours so that preview environments from forks are deleted less often ([internal thread](https://gitpod.slack.com/archives/C032A46PWR0/p1674826607497579))
I will follow this up with a PR which triggers preview environment deletion when branches are deleted, which should help us keep the number of running previews low even if we only GC every 4 hours.
No issue but see [internal chat](https://gitpod.slack.com/archives/C032A46PWR0/p1674826607497579).
N/A
```release-note
NONE
``` …

Run cron every 4 hours

---

install/installer/pkg/components/slowserver/deployment.go
install/installer/pkg/components/slowserver/render_test.go

Currently db-awaiter and slow-server point to different DBs :roll_eyes: 
Fixes #
```release-note
NONE
```

[slow-server] Fix DB_HOST reference

---

components/dashboard/src/start/StartWorkspace.tsx
components/supervisor/frontend/src/shared/frontend-dashboard-service.ts

removed unused code
Fixes #
Start a workspace with IntelliJ IDEA, check that you can open VS Code Browser and IntelliJ IDEA. While redirection got IntelliJ the origin should be gitpod, not workspace.
```release-note
NONE
```

clean up after #15895

---

install/installer/pkg/components/spicedb/deployment.go

https://authzed.com/docs/spicedb/configuring-dispatch
Fixes #
```release-note
NONE
```

[spicedb] Enable dispatching

---

README.md
components/image-builder-mk3/README.md
docs/workspace/image-builder-mk3/README.md

Fixes https://github.com/gitpod-io/gitpod/issues/16075
```release-note
Update README links
```

Replace links

---

install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/azure-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/kind-webapp/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden

Follow up to: https://github.com/gitpod-io/gitpod/pull/16104
Fixes #
```release-note
NONE
```

[installer] Fix render tests

---

install/installer/pkg/components/spicedb/data/schema.yaml

Cleans up schema to focus on just organizations. Adds tests/assertions for the schema.
Fixes #
```release-note
NONE
```

[spicedb] Basic organizations model

---

.github/workflows/jetbrains-integration-test.yml

Fixes #
```release-note
NONE
```

[jb] create cache directories to fix integration tests

---

components/server/src/workspace/gitpod-server-impl.ts

Ensures user has access to team.
Fixes #
```release-note
NONE
```

[server] Guard getTeam

---

components/server/ee/src/prebuilds/github-enterprise-app.ts

github enterprise integration should respect the `prebuilds` section in the `.gitpod.yml`.
See #16139
```release-note
NONE
```

[prebuilds] respect gitpod.yml in GHE

---

.github/workflows/jetbrains-integration-test.yml

Fixes #
```release-note
NONE
```
Valid options are `jetbrains`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`

fix jetbrains integration test

---

install/installer/pkg/components/slowserver/deployment.go

Fixes #
```release-note
NONE
```

[slowserver] Fix slowserver

---

install/installer/pkg/components/spicedb/migrations.go

* Ensures job is removed once complete, this allows subsequent deploys to not fail due to the spec existing.
Fixes #
```release-note
NONE
```

[spicedb] Add job TTL to migrations

---

.github/workflows/ide-integration-tests.yml

Use dev image as the container image for the job.
Part of https://github.com/gitpod-io/gitpod/issues/15874
Tested in https://github.com/gitpod-io/gitpod/actions/runs/4085163832/jobs/7042767847
```release-note
NONE
```
N/A

Use dev image as the container image for the job

---

components/gitpod-db/src/typeorm/entity/db-user.ts
components/gitpod-db/src/typeorm/migration/1675433412120-UserOrganizationId.ts
components/gitpod-protocol/src/protocol.ts
components/public-api-server/pkg/oidc/router.go
components/public-api-server/pkg/oidc/service.go
components/server/src/iam/iam-oidc-create-session-payload.ts
components/server/src/iam/iam-session-app.spec.ts
components/server/src/iam/iam-session-app.ts

Fixes #
```release-note
Associate users logging in with a SSO provider to that Organization (and make the first an owner)
```

[organization] Associate OICD-created User with Organization

---

components/ide/code/codehelper/main.go

Debug location is running from sources. On gitpod.io we noticed that we don't apply CSP policies properly in this case. 
This PR respect gitpod domain.
Fixes #
Start a workspace with VS Code Browser. You should be able access via UI. As well as the debug workspace.
```release-note
NONE
```

[codehelper] fix CSP replacement when serving from sources

---

install/installer/pkg/components/spicedb/deployment.go

Reduces log pollution
Fixes #
```release-note
NONE
```

[spicedb] Log level info

---

components/supervisor/pkg/serverapi/publicapi.go

Add missing stream api metrics
1. Scale down server to force connection error
2. Check grafana dashboard that error counter increases
```release-note
NONE
```

[supervisor] Add missing stream api metrics

---

components/dashboard/package.json
components/dashboard/src/projects/Events.tsx
components/dashboard/src/projects/NewProject.tsx
components/dashboard/src/start/CreateWorkspace.tsx
components/dashboard/src/start/StartPage.tsx
components/dashboard/src/start/StartWorkspace.tsx
components/dashboard/src/teams/Members.tsx
components/dashboard/src/teams/SSO.tsx
components/dashboard/src/teams/TeamBilling.tsx
components/dashboard/src/user-settings/ChargebeeTeams.tsx
components/dashboard/src/user-settings/Integrations.tsx
components/dashboard/src/user-settings/PersonalAccessTokens.tsx
components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
components/dashboard/src/user-settings/Plans.tsx
components/dashboard/src/user-settings/SelectIDE.tsx
components/dashboard/src/user-settings/selectClass.tsx

Fixing a batch of lint errors to get us closer to being able to enable the linter as a blocking test. I did my best to avoid any risky changes here, opting to disable a few lint errors on specific useEffect() calls that intentionally have no deps.
Clicking around in the following areas to check that they're working as normal:
* Project creation
* main Project page
* Project prebuilds
* Personal Git Integrations
* Personal Billing
* Personal Access Tokens
* Start Workspace modal
* Team Members
* Team Billing
* Team SSO
```release-note
NONE
```
Valid …

fixing lint errors

---

components/dashboard/src/app/AppRoutes.tsx
components/dashboard/src/menu/Menu.tsx
components/dashboard/src/menu/OrganizationSelector.tsx

Some smaller fixes on the dashboard
- avoid logo disappearing
- limit with of org selector
- added redirects for old user setting slugs
Fixes #
```release-note
NONE
```

[dashboard] fix logo

---

.github/CODEOWNERS

Add @gtsiolis as codeowner
Fixes #
```release-note
NONE
```

[dashboard] Add George as CodeOwner

---

.github/workflows/build.yml

Enabling workflow dispatch so it can be triggered by the CLI
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

Enable build workflow dispatc

---

components/usage/pkg/apiv1/usage.go

Becomes fairly noisy, due to nearly 2k ops per minute on this RPC. [See logs](https://console.cloud.google.com/logs/query;query=resource.labels.pod_name%20:%20%2528%22usage%22%2529%0AjsonPayload.message%3D%22Fetching%20usage%20data%22;timeRange=PT1H;summaryFields=jsonPayload%252F%2522grpc.service%2522,jsonPayload%252F%2522grpc.time_ms%2522,jsonPayload%252F%2522grpc.code%2522:false:32:beginning;cursorTimestamp=2023-02-08T08:55:40.388468245Z?authuser=0&project=gitpod-191109).
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
Add desired feature flags to the end of the …

[usage] Reduce log level for Fetching usage data log

---

components/gitpod-protocol/src/util/tracing.ts
components/image-builder-api/typescript/src/sugar.ts

Fixes #16228
```release-note
NONE
```

[server] Make sure to only ever finish this span once

---

components/server/ee/src/billing/entitlement-service-ubp.ts

Fixes https://github.com/gitpod-io/ops/issues/8237
```release-note
NONE
```
<details>
</details>
<details>
</details>

[entitlement] Limit network connections for all users

---

components/server/src/workspace/gitpod-server-impl.ts

Originally we only did this in `start`, but we need it `create` also.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Guess region for both workspaceCreate and workspaceStart

---

test/pkg/integration/apis.go
test/tests/ide/vscode/python_ws_test.go

Fix ide tests
```release-note
NONE
```
<details>
</details>
<details>
</details>

Fix ide tests

---

components/supervisor/pkg/config/gitpod-config.go

Fix [error report](https://console.cloud.google.com/errors/detail/CJLP-_-5tNatXA;service=supervisor?project=workspace-clusters)
It's caused by ctx cancel when supervisor is going to stop, and after ctx Done `poll` func will return an call watch again here
Fixes #
- Start a empty workspace in preview env (and delete `.gitpod.yml` file if it is generated)
- Should have no such log `gitpod config watcher: failed to start` with `file not exists` error in superviosr (check GCP logging)
```release-note
NONE
```
<details>
</details>
<details>
Add desired feature flags to …

[supervisor] improve config watch logging

---

components/usage/pkg/apiv1/billing.go

Update stripe with current usage immediately, so that
invoices created between now and the next reconcile
are correct.
Fixes #16338
```release-note
NONE
```
<details>
</details>
<details>
</details>

[usage] update stripe usage on finalization

---

components/dashboard/src/start/CreateWorkspace.tsx

Ensure that we only create one workspace at a time.
Fixes #
Create Workspace and ensure you  got exactly one
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] don't create more than one workspace

---

components/dashboard/src/service/service.tsx
components/gitpod-protocol/src/frontend-dashboard-service.ts
components/gitpod-protocol/src/gitpod-service.ts
components/gitpod-protocol/src/protocol.ts
components/server/src/auth/rate-limiter.ts
components/server/src/workspace/config-provider.ts
components/server/src/workspace/gitpod-server-impl.ts

Part 1/2
Fixes #
Related https://github.com/gitpod-io/security/issues/121
Should test in https://github.com/gitpod-io/gitpod/pull/16404
```release-note
NONE
```
<details>
</details>
<details>
</details>

Add credentials token for browser IDE

---

.github/actions/delete-preview/Dockerfile
.github/actions/deploy-gitpod/Dockerfile
.github/actions/deploy-monitoring-satellite/Dockerfile
.github/actions/preview-create/Dockerfile
.github/workflows/build.yml
.github/workflows/ide-integration-tests.yml
.github/workflows/preview-env-gc.yml
.gitpod.yml
.werft/aks-installer-tests.yaml
.werft/build.yaml
.werft/cleanup-installer-tests.yaml
.werft/debug.yaml
.werft/eks-installer-tests.yaml
.werft/gke-installer-tests.yaml
.werft/k3s-installer-tests.yaml
.werft/platform-trigger-werft-cleanup.yaml
.werft/workspace-run-integration-tests.yaml
dev/image/Dockerfile
dev/kubecdl/main.go

Presently, we get an error like this when downloading a kubeconfig with `kubecdl`:
```
time="2023-02-15T22:12:42Z" level=error msg="cannot write kubeconfig. Dumping combined result:" error="open /home/gitpod/.kube/config: no such file or directory" path=/home/gitpod/.kube/config
```
Reference [this werft job](https://werft.gitpod-io-dev.com/job/ops-workspace-cluster-new-kylos101-one-app-cluster.2/raw), where the error prevented creation for a new workspace cluster.
This also happens from a fresh Gitpod workspace, which is a paper cut for the administrator/operator persona.
Fixes # n/a
Assert the code works:
```
gcloud auth login --no-launch-browser
git checkout main
cd dev/kubecdl
go run main.go us87
git checkout kylos101/kubecdl-home
go run main.go us87
kubectx
```
Assert the dev image …

[kubecdl] create `.kube` folder before writing out the config if it doesn't exist

---

components/supervisor/pkg/supervisor/supervisor.go

Adds a telemetry to track how many workspaces are using docker.
Fixes #
- Run docker --version
- Check that you see `gitpod_activate_docker` event
There should be only one event per workspace instance.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[supervisor] track workspaces with activated docker

---

components/gitpod-cli/cmd/rebuild.go

[gitpod-cli] gp rebuild respect image context
Fixes #16409
```release-note
[gitpod-cli] gp rebuild respect image context
```
<details>
</details>
<details>
</details>

[gitpod-cli] gp rebuild respect image context

---

components/dashboard/src/menu/OrganizationSelector.tsx

- Updates the checkmark icon for the selected organization in the org selector.
Fixes #16434 
```release-note
Improve the checkmark icon for the selected organization in the org selector
```
<details>
</details>
<details>
</details>

Update the checkmark icon in org selector

---

components/gitpod-cli/cmd/env.go
components/gitpod-cli/cmd/rebuild.go

gp env changes values a bit to satisfy eval, instead of using it rebuild directly applies values returned by a server
Fixes #
Verify from sources:
- Stop all tasks in the host workspace, i.e. `gp tasks stop --all`
- Run `go run . rebuild` from components/gitpod-cli
- When a debug workspace is UP the first terminal should be successful to connect to GCP
- Test that `go run . env` works still as well from components/gitpod-cli
Verify in preview envs:
- Configure env vars on user or project level with JSON object, i.e. `MY_ENV_VAR={ "foo": "bar" }`
- Start a worksapce and then run `gp rebuild`.
- Compare output of `printenv MY_ENV_VAR` in host and debug workspaces.
- Test that `gp env` works still as well.
```release-note
NONE
```
Experimental feature to run the …

[rebuild] consume workspace env var as is

---

components/supervisor/pkg/serverapi/publicapi.go

To avoid 10 minutes reconnection error
> Switch from `context.WithTimeout` to `time.Ticker` is because we have some special logic inside public/server api `onInstanceUpdate` for errors. 
It will make life easier
Fixes #
- Make sure we get `start to listen on publicAPI instanceUpdates` every 7 minutes in workspace log
test result see https://github.com/gitpod-io/gitpod/pull/16504#issuecomment-1441381561
You can also add log back and hot-deploy supervisor to test again
```release-note
NONE
```
<details>
</details>
<details>
Add desired feature flags to …

[supervisor] reconnect to publicapi after 7m

---

components/ws-daemon/cmd/run.go
components/ws-daemon/pkg/daemon/daemon.go

Expose controller-manager metrics for ws-daemon.
Was a bit tricky to implement, the controller metrics use a prometheus registry that isn't configurable. So now, instead of using `baseserver`'s default metrics registry, first construct daemon and the controller manager, and pass the controller-manager's registry to `baseserver`.
Please let me know if there's a cleaner solution I missed 🙏 I tried looking for a way to e.g. "register" the controller-manager registry with baseserver's registry, but don't think this is possible.
An alternative is exposing a second metrics endpoint on daemon, but this would require additional plumbing to get it scraped and behind the kube-proxy sidecar container, and increase the number of scrape targets in the cluster.
Check the metrics …

[ws-daemon] Expose controller metrics

---

components/gitpod-protocol/src/protocol.ts

Fixes tracking of onboarding by returning the `companyWebsite` attribute in `getProfile` instead of the `company`
Fixes #
1. Go to the debugger of the [Staging Trusted](https://app.segment.com/gitpod/sources/staging_trusted/debugger) source
2. Open up a preview environment, append `?onboarding=force` to the URL and open the page to start the onboarding flow. Complete the onboarding flow and make sure to enter a value in `Company Website`
3. Ensure that the `profile_changed` calls contain the Company Website in their payloads.
```release-note NONE
```
<details>
</details>
<details> …

[Analytics] Fix `companyWebsite` in `getProfile()`

---

components/supervisor/pkg/serverapi/publicapi.go

also log unavailable
Fixes #
Start a workspace for this PR and run validate.sh for supervisor.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[supervisor] gracefully close public API connection

---

components/dashboard/src/onboarding/StepUserInfo.tsx

See [relevant discussion](https://gitpod.slack.com/archives/C042X6P86BZ/p1677235831669819?thread_ts=1677228349.880179&cid=C042X6P86BZ) (internal). @MichaelAring @phimae 
Sign up and see how the email input is rendering on the first onboarding step.
```release-note
NONE
```
<details>
</details>
<details>
</details>

Update onboarding email input label

---

components/dashboard/src/projects/Project.tsx
components/dashboard/src/projects/ProjectListItem.tsx

Reverts gitpod-io/gitpod#16540

Revert ":wrench: Ambiguity of `New Workspace` option & :rocket: new `Settings` option "

---

install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/kind-webapp/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/redis/deployment.go

Fixes https://github.com/gitpod-io/gitpod/issues/16589
```release-note
NONE
```
<details>
</details>
<details>
</details>

[redis] Fix readiness probe

---

components/server/src/github/file-provider.ts

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Log github getFileContent errors in debug

---

components/ide-metrics/README.md

Add README to `ide-metrics` component
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

Add README to `ide-metrics`

---

components/dashboard/src/SwitchToPAYG.tsx

This PR updates styles of the Switch to PAYG page:
**BEFORE**
**AFTER**
```release-note
NONE
```
<details>
</details>
<details>
</details>

Update styles on Switch to PAYG

---

components/server/src/workspace/workspace-starter.ts

Ensures workspaces get started only once by storing the new instance in a lock where we check the existence of a running instance before.
I've considered alternative implementations using db-level primitives:
- mysql's default isolation level (REPEATABLE READ) doesn't help, as it would allow concurrent inserts of new data
- the best db-level alternative would be to use SELECT ... FOR UPDATE, which requires to explicitly maintain a larger SQL statement and keep it in sync with the workspaceinstance shape. Doable but more complicated.
- the distributed lock is a primitive we have already and doesn't do any locking for other things that starting the particular workspace. It just calls two existing db operations.
Fixes #
I've tested this manually by calling startWorkspace more than once in …

[server] ensure workspaces get started once

---

.github/workflows/comment-ops.yaml

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gha] fix comment ops p3

---

components/server/src/config.ts
components/server/src/user/user-controller.ts

Reach the endpoint on https://mp-admin-login-file.preview.gitpod-dev.com/api/login/ots/admin/foobar
Adds an extra endpoint on which we can create a new user session. I've opted to add a new one, and keep the old one for now, until we complete this.
Currently, the admin credentiaals file is not yet supplied to the instance, will be done in subsequent PR. In this iteration, we can already see we can reach the endpoint, and we get Unathenticated back.
See https://gitpod.slack.com/archives/C02EN94AEPL/p1678192114839789 for more details on why this approach.
* Part of https://github.com/gitpod-io/gitpod/issues/16223
```release-note
NONE
```
<details> …

[server] Sing-in as admin based on admin credentials file

---

components/dashboard/src/teams/Members.tsx

It limits the team member privileges and gives more control to the Owner (as prev.) to change Member roles, remove X member from org., etc.
Fixes #16744 & also related [internal conversation](https://gitpod.slack.com/archives/C02EN94AEPL/p1678334307998349)
- Create a Demo Team & Invite a member
- & see `/members` User Role access (dropdown, etc.)
```release-note
NONE
```
<details>
</details>
<details>
</details> …

Limit Team Members privileges 

---

components/registry-facade/pkg/registry/blob.go

If a blob source like IPFS cannot provide the blob fall back to another blob source instead of giving up.
Fixes https://github.com/gitpod-io/gitpod/issues/14264
The scenario is not that easy to reproduce so for testing purposes I modified the IPFS blob source handler to return an error when calling GetBlob but return true on HasBlob. This is running on eu89 right now.
Logs showing that pull from IPFS is not possible and then retrieving the blob from other providers.
```release-note
Fixed an issue where the workspace image could not be pulled if IPFS was in a bad state
```
<details>
</details>
<details>
Add desired …

[registry-facade] Fallback to other blob sources if blob cannot be provided

---

components/dashboard/src/SwitchToPAYG.tsx

Following a [recent discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1678274933848059) (internal) with @AlexTugarev regarding the switch to PAYG flow, this will rename the action button on the success step when switching to PAYG from **Go to Billing →** to **Manage usage limit →**.
See also [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1678377025465019?thread_ts=1678376926.478359&cid=C02EN94AEPL) (internal). Cc @atduarte 
| BEFORE | AFTER | 
|-|-|
| <img width="1512" alt="Screenshot 2023-03-09 at 17 56 29" src="https://user-images.githubusercontent.com/120486/224080703-33b6a62a-7364-4918-bb91-bb7c9790e055.png"> | <img width="1512" alt="Screenshot 2023-03-09 at 17 56 38" src="https://user-images.githubusercontent.com/120486/224080715-afb3dcff-cf71-422e-85ef- …

Update switch to PAYG action button label

---

components/server/src/auth/rate-limiter.ts

Further increase the rate limiting for sendHeartBeat
Fixes https://github.com/gitpod-io/ops/issues/8649
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] further limit sendHeartbeat

---

components/public-api-server/pkg/apiv1/team.go

* To populate the Team response on public-api, we need the team info, members and the invite link
* Until this PR, we've been doing this sequentially, which could lead to fairly high 99th percentile latency ([see dash](https://grafana.gitpod.io/d/Ce3ZWpNVk/connect-server?orgId=1&var-datasource=VictoriaMetrics&var-package=gitpod.experimental.v1.TeamsService&var-call=ListTeams&var-type=All&viewPanel=9))
Instead, we fetch the details for each team in the list concurrently, and then compose the final response.
Fixes #
1. Existing listing of teams works
2. Existing tests continue to work
```release-note
NONE
```
<details>
</details>
<details>
Add desired …

[public-api] List teams concurrently

---

.github/workflows/workspace-integration-tests.yml
dev/preview/workflow/preview/deploy-gitpod.sh

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

split jobs

---

components/public-api-server/pkg/server/logs.go

* Drops auth headers
* Reduces accidental double log
* Does not include body in fields
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[public-api] Cleanup logging middleware

---

components/ws-proxy/pkg/proxy/proxy.go

Remove noisy log `http: TLS handshake error from XXX.XXX.XXX.XXX:XXXXX: EOF` due to clients using plain TCP connections instead of TLS. One of the sources for these errors are the load balancer checks.
- Port forward `ws-proxy` TLS port running `kubectl port-forward svc/ws-proxy 9090 &`
- Using `netcat` check we can reach the port `nc -zv localhost 9090`
- Check the ws-proxy pod log does not contains lines like `http: TLS handshake error from XXX.XXX.XX.XX:XXXX: EOF`
```release-note
NONE
```
<details>
</details>
<details>
</details> …

Remove TLS EOF errors from logs

---

components/server/src/workspace/gitpod-server-impl.ts

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[heartbeat] Map grpc error

---

install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/kind-webapp/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/redis/networkpolicy.go
install/installer/pkg/components/redis/objects.go

Context: https://gitpod.slack.com/archives/C032A46PWR0/p1679497866300349
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

[redis] Add explicit network policy

---

components/common-go/grpc/ratelimit.go

Describe how `refillInterval` works
```release-note
NONE
```
<details>
</details>
<details>
</details>

[common-go] Add doc on refillInterval

---

components/dashboard/src/teams/TeamSettings.tsx

Small update for copy text on workspace sharing. 
```release-note
NONE
```

Update copy for workspace sharing setting

---

components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
operations/observability/mixins/meta/dashboards/components/ws-manager-bridge.json

Fixes https://github.com/gitpod-io/gitpod/issues/17023
```release-note
NONE
```
<details>
</details>
<details>
</details>

[prometheus] Remove references to db_write

---

components/server/src/server.ts

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Log when instance is quorum leader and starts db deleter, or not

---

components/registry-facade/pkg/registry/manifest.go

Avoid logging node-labeler checks on registry-facade as an error. This will help reduce noise when inspecting a running cluster.
Fixes # n/a
Observe [this](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-03-30T20:05:24.551271281Z;lfeCustomFields=jsonPayload%252FserviceContext%252Fservice;query=--%20without%20protected_secrets%20enabled%0A--%20jsonPayload.kubernetes.host%3D%22kylos101-n60493252f4%22%0A%22this%20was%20node-labeler,%20we%20expected%20no%20spec%22%0Atimestamp%3D%222023-03-30T20:05:24.551271281Z%22%0AinsertId%3D%22op3k2gftrlefs%22;summaryFields=jsonPayload%252Fseverity,jsonPayload%252FserviceContext%252Fservice:false:32:beginning;timeRange=PT6H?project=gitpod-core-dev) log.
```release-note
NONE
``` …

[registry-facade] do not log node-labeler inquires as errors

---

operations/observability/mixins/workspace/dashboards/components/ws-daemon.json
operations/observability/mixins/workspace/dashboards/components/ws-manager-mk2.json

Update ws-manager-mk2 dashboard:
* Add `Controller` var, to filter metrics on a specific controller
* Convert work queue latency and duration panels to heatmaps, to better show the distribution of values:
Same for the `ws-daemon` dashboard:
+ also updated the controller metrics queries in the ws-daemon dashboard to `topk(20, ...)` to limit the number of timeseries shown in the panels (there were a lot of series)
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[ws-manager-mk2] Dashboard controller heatmaps (WKS-21)

---

components/server/src/api/user.ts

Just for slightly easier auditing
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

[server] Log explicitly when user is blocked

---

components/usage/pkg/apiv1/pricer.go

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

[usage] Log default price applied when no config exists

---

components/dashboard/src/workspaces/CreateWorkspacePage.tsx

Minor button style change on the _new_ new workspace flow.
| <img width="1512" alt="Screenshot 2023-04-11 at 18 16 29" src="https://user-images.githubusercontent.com/120486/231225589-383ae942-6227-43a5-9214-983d3dbccd69.png"> | <img width="1512" alt="Screenshot 2023-04-11 at 18 16 37" src="https://user-images.githubusercontent.com/120486/231225603-a6bd6a27-f2b6-41d1-bc40-bc6c0c5fc567.png"> | 
Go to `/new` and notice the new block button style of the primary action button.
```release-note
Update new workspace button style
```
<details>
</details>
<details> …

Update new workspace button style

---

.github/actions/deploy-gitpod/entrypoint.sh
.github/pull_request_template.md
.github/workflows/build.yml

Adds a special property to the PR desc which gets replaced by the deployment job. It was already replaced below.
<ul>
<li><b>🏷️ Name</b> - ak-pr-summary</li>
<li><b>🔗 URL</b> - <a href="https://ak-pr-summary.preview.gitpod-dev.com/workspaces" target="_blank">ak-pr-summary.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
Fixes #
```release-note
NONE
```
<details> …

[pr] update desc with summary

---

components/dashboard/src/onboarding/LinkedInBanner.tsx
components/dashboard/src/onboarding/StepUserInfo.tsx

gitpod:summary
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

Rephrase credits to hours in LinkedIn onboarding

---

components/server/src/user/user-service.ts

Migrates new users to the org-only mode, depending on a feature flag.
<ul>
<li><b>🏷️ Name</b> - sven-migra511dca8193</li>
<li><b>🔗 URL</b> - <a href="https://sven-migra511dca8193.preview.gitpod-dev.com/workspaces" target="_blank">sven-migra511dca8193.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
Fixes WEB-129
Login to the preview environment and verify that you are in org-only mode.
```release-note
NONE
``` …

[server] migrate new users

---

components/gitpod-db/src/auth-provider-entry.spec.db.ts
components/gitpod-protocol/src/protocol.ts
components/server/src/auth/auth-provider.ts
components/server/src/auth/generic-auth-provider.ts
components/server/src/bitbucket-server/bitbucket-server-auth-provider.ts
components/server/src/bitbucket/bitbucket-auth-provider.ts
components/server/src/github/github-auth-provider.ts
components/server/src/gitlab/gitlab-auth-provider.ts

removing dead code.
<ul>
<li><b>🏷️ Name</b> - at-cleanupf9cf745817</li>
<li><b>🔗 URL</b> - <a href="https://at-cleanupf9cf745817.preview.gitpod-dev.com/workspaces" target="_blank">at-cleanupf9cf745817.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
Add desired …

[server] clean up auth provider

---

components/gitpod-db/src/typeorm/migration/1681805965892-DropTermsAcceptance.ts

* Depends on https://github.com/gitpod-io/gitpod/pull/17253/
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[db] Drop d_b_terms_acceptance_entry

---

install/installer/pkg/components/ide-service/ide_config_configmap.go

This addresses https://github.com/gitpod-io/gitpod/pull/17240#issuecomment-1511400543 and should be merged really soon before the next deployment :).
<ul>
<li><b>🏷️ Name</b> - ft-fix-revert</li>
<li><b>🔗 URL</b> - <a href="https://ft-fix-revert.preview.gitpod-dev.com/workspaces" target="_blank">ft-fix-revert.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

Revert making VS Code Browser experimental

---

components/public-api-server/pkg/apiv1/oidc.go
components/public-api-server/pkg/apiv1/oidc_test.go

Fixes WEB-165
<ul>
<li><b>🏷️ Name</b> - at-test-isab6e2e0b93</li>
<li><b>🔗 URL</b> - <a href="https://at-test-isab6e2e0b93.preview.gitpod-dev.com/workspaces" target="_blank">at-test-isab6e2e0b93.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

SSO – check for OIDC Discovery - WEB-165

---

yarn.lock

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[yarn] update yarn.lock

---

dev/preview/workflow/lib/k8s-util.sh

Fix typo in log message

---

install/installer/pkg/components/workspace/ide/constants.go

to make use on unified endpoint: https://github.com/gitpod-io/gitpod-code/pull/8
Fixes #
- Use an action like open dashboard
- Check staging trusted that an event was registered
<ul>
<li><b>🏷️ Name</b> - ak-code-analytics</li>
<li><b>🔗 URL</b> - <a href="https://ak-code-analytics.preview.gitpod-dev.com/workspaces" target="_blank">ak-code-analytics.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
Run Leeway …

bump up code

---

components/ws-manager-mk2/service/manager.go

Publish the number of active and inactive workspaces
Fixes WKS-73
- kubectl port-forward deploy/ws-manager-mk2 9500
- curl -XGET 'localhost:9500/metrics'  | grep activity
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[wsman-mk2] Publish workspace activity metric

---

components/dashboard/src/service/service.tsx
components/gitpod-protocol/src/frontend-dashboard-service.ts

Align and send ide heartbeat telemetry 
Fixes [Linear](https://linear.app/gitpod/issue/IDE-22/supervisor-frontend)
- Open workspace in preview env with browser code
- Wait for 15minutes to see if it send `ide_heartbeat` telemetry (you can override js source to reduce interval duration)
✅ 
<ul>
<li><b>🏷️ Name</b> - huiwen-ide7d8afee456</li>
<li><b>🔗 URL</b> - <a href="https://huiwen-ide7d8afee456.preview.gitpod-dev.com/workspaces" target="_blank">huiwen-ide7d8afee456.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to …

[dashboard] send heartbeat telemetry

---

components/server/src/workspace/gitpod-server-impl.ts

Enables testing of WEB-27
Fixes WEB-27
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] Disable new setup modal as long as it's an dead end

---

components/ide-service/pkg/server/server.go

[ide-service] reuse configcat client
Fixes #
<ul>
<li><b>🏷️ Name</b> - pd-fix-ide-service</li>
<li><b>🔗 URL</b> - <a href="https://pd-fix-ide-service.preview.gitpod-dev.com/workspaces" target="_blank">pd-fix-ide-service.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
Add desired feature flags to …

[ide-service] reuse configcat client

---

components/dashboard/src/App.tsx
components/dashboard/src/onboarding/OnboardingStep.tsx
components/dashboard/src/whatsnew/MigrationPage.tsx

Allow users to skip the migration three times (days) to increase the chance they actually read what it is about.
Fixes WEB-237
<ul>
<li><b>🏷️ Name</b> - se-migration-not-now</li>
<li><b>🔗 URL</b> - <a href="https://se-migration-not-now.preview.gitpod-dev.com/workspaces" target="_blank">se-migration-not-now.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[dashboard] allow skipping the migration

---

components/server/src/auth/login-completion-handler.ts

Fixes #
1. Preview
2. Sign-in
3. See cookie expires in 7 days
<ul>
<li><b>🏷️ Name</b> - mp-jwt-coof25efe86d1</li>
<li><b>🔗 URL</b> - <a href="https://mp-jwt-coof25efe86d1.preview.gitpod-dev.com/workspaces" target="_blank">mp-jwt-coof25efe86d1.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
Add …

[server] Fix setting jwt cookie maxAge

---

components/usage/pkg/apiv1/usage_test.go

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[usage] Scope db connection to subtests to ensure cleanup and prevent flakes - WEB-240

---

components/blobserve/cmd/run.go
components/blobserve/pkg/blobserve/blobserve.go

Add top level (code, method) metrics for incoming and outgoing http requests in blobserve.
[Linear](https://linear.app/gitpod/issue/IDE-38/add-slos-for-blind-spots)
- Start a workspace in previe env.
- Open this PR in Gitpod, port forward monitoring and use Grafana to explore metrics.
<ul>
<li><b>🏷️ Name</b> - ak-blobserve-metrics</li>
<li><b>🔗 URL</b> - <a href="https://ak-blobserve-metrics.preview.gitpod-dev.com/workspaces" target="_blank">ak-blobserve-metrics.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact …

[blobserve] add http requests observability

---

components/server/src/prometheus-metrics.ts
components/server/src/session-handler.ts

* Preview
* Sign-in
* See metrics endpoint contains count `k port-forward deployment/server 9500:9500, curl http://localhost:9500/metrics`
<ul>
<li><b>🏷️ Name</b> - mp-server-0ec62100c5</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-0ec62100c5.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-0ec62100c5.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[server] Parse incoming JWT sessions WEB-247

---

components/dashboard/src/app/AppRoutes.tsx
components/dashboard/src/components/UsageBasedBillingConfig.tsx
components/dashboard/src/data/featureflag-query.ts
components/dashboard/src/data/workspaces/delete-inactive-workspaces-mutation.ts
components/dashboard/src/data/workspaces/delete-workspace-mutation.ts
components/dashboard/src/data/workspaces/stop-workspace-mutation.ts
components/dashboard/src/onboarding/StepUserInfo.tsx
components/dashboard/src/start/CreateWorkspace.tsx
components/dashboard/src/teams/OrgSettingsPage.tsx
components/dashboard/src/user-settings/Integrations.tsx
components/dashboard/src/user-settings/PageWithSettingsSubMenu.tsx
components/dashboard/src/user-settings/PersonalAccessTokens.tsx
components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
components/dashboard/src/whatsnew/MigrationPage.tsx
components/dashboard/src/workspaces/CreateWorkspacePage.tsx

return the actual feature flag value from `useFeatureFlag`
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[dashboard] simplify API for useFeatureFlag

---

components/dashboard/src/components/UsageBasedBillingConfig.tsx

The `paymentVerificationFlow` flag has been released to 100% now. This removes the flag and the code for the old setup intent flow from the dashboard frontend.
A followup will be removing the setup-intent parts of the usage service.
Fixes WEB-211
* Upgrade the billing plan of your organization to verify the flow still works.
<ul>
<li><b>🏷️ Name</b> - bmh-cleanup-3ds-flag</li>
<li><b>🔗 URL</b> - <a href="https://bmh-cleanup-3ds-flag.preview.gitpod-dev.com/workspaces" target="_blank">bmh-cleanup-3ds-flag.preview.gitpod-dev.com/workspaces</a>.</li> …

Removing paymentVerificationFlow flag

---

components/blobserve/leeway.Dockerfile
components/content-service/leeway.Dockerfile
components/dashboard/leeway.Dockerfile
components/ee/agent-smith/leeway.Dockerfile
components/ide-metrics/leeway.Dockerfile
components/ide-proxy/Dockerfile
components/ide-service/leeway.Dockerfile
components/ide/jetbrains/backend-plugin/leeway.Dockerfile
components/ide/jetbrains/image/leeway.Dockerfile
components/ide/jetbrains/launcher/leeway.Dockerfile
components/image-builder-mk3/leeway.Dockerfile
components/installation-telemetry/leeway.Dockerfile
components/leeway.Dockerfile
components/local-app/leeway.Dockerfile
components/node-labeler/leeway.Dockerfile
components/openvsx-proxy/leeway.Dockerfile
components/proxy/Dockerfile
components/public-api-server/leeway.Dockerfile
components/registry-facade/leeway.Dockerfile
components/service-waiter/leeway.Dockerfile
components/usage/leeway.Dockerfile
components/ws-daemon/leeway.Dockerfile
components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
components/ws-manager/leeway.Dockerfile
components/ws-proxy/leeway.Dockerfile
dev/changelog/leeway.Dockerfile
test/leeway.Dockerfile

Update images digests using the latest version available for image/s
```release-note
NONE
```

Update images digests

---

components/ws-manager-mk2/service/manager.go

Return exposed ports in workspace status.
Also saw the workspace class wasn't getting returned as well, added that too
Fixes WKS-139
* Open a workspace
* Run `gp ports visibility 3000:public`
* Run `gp ports list`
* See port 3000 in the list with status `not served`
* Run a server on port 3000
* `gp ports list` should now show its status as `open (public)`
* The port URL should work and connect to the listening server
gitpod:summary
<details>
</details>
<details>
</details> …

[ws-manager-mk2] Return exposed ports in workspace status

---

components/dashboard/src/app/AppBlockingFlows.tsx
components/dashboard/src/data/oidc-clients/upsert-oidc-client-mutation.ts
components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
components/dashboard/src/dedicated-setup/OrgNamingStep.tsx
components/dashboard/src/dedicated-setup/SSOConfigForm.tsx
components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
components/dashboard/src/dedicated-setup/SetupCompleteStep.tsx
components/dashboard/src/dedicated-setup/SetupLayout.tsx
components/dashboard/src/images/check.svg
components/dashboard/src/provider-utils.tsx
components/dashboard/src/teams/sso/OIDCClientConfigModal.tsx
components/dashboard/src/teams/sso/SSOConfigForm.tsx

Adds the SSO Setup step to the dedicated setup flow. Configuration can be provided, and then verified. This should launch a login flow. Upon completion the user should now be logged in as themselves (not the admin user), and see the complete view.
| Header | Header |
| ![image](https://user-images.githubusercontent.com/367275/235789590-655ee28b-9cf3-4f3e-9126-4ae69db309ae.png) | ![image](https://user-images.githubusercontent.com/367275/235789807-522daef2-c243-41f0-8416-30e74493db9f.png) | 
The flow is still only launched behind the `dedicated-setup=force` query param. This will get integrated with a proper check against the state of the cell in a followup.
Fixes [WEB-245](https://linear.app/gitpod/issue/WEB-245)
TBD - need to hook up to a proper check on if the cell …

Dedicated Setup - SSO Setup

---

install/installer/pkg/components/server/configmap.go

Superseeded by admin credentials feature
Fixes WEB-200
1. preview
<ul>
<li><b>🏷️ Name</b> - mp-install2d40ffb56e</li>
<li><b>🔗 URL</b> - <a href="https://mp-install2d40ffb56e.preview.gitpod-dev.com/workspaces" target="_blank">mp-install2d40ffb56e.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
Add …

[installer] First user is no longer admin WEB-127

---

components/gitpod-db/src/typeorm/webhook-event-db-impl.ts
components/gitpod-db/src/webhook-event-db.spec.db.ts

Reverts gitpod-io/gitpod#17487

Revert "[server] Delete webhook events directly"

---

components/dashboard/src/dedicated-setup/DedicatedSetup.tsx

Fixes #
<ul>
<li><b>🏷️ Name</b> - at-fix-tooc765959580</li>
<li><b>🔗 URL</b> - <a href="https://at-fix-tooc765959580.preview.gitpod-dev.com/workspaces" target="_blank">at-fix-tooc765959580.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

Fix "too many renders" errors – WEB-302

---

components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
components/dashboard/src/dedicated-setup/OrgNamingStep.tsx
components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
components/dashboard/src/dedicated-setup/SetupCompleteStep.tsx
components/dashboard/src/dedicated-setup/SetupLayout.tsx
components/dashboard/src/dedicated-setup/use-check-dedicated-setup.ts
components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
components/dashboard/src/teams/sso/SSOConfigForm.tsx
components/dashboard/src/user-settings/Integrations.tsx

Includes a number of small fixes for the dedicated setup flow. I also made it so when you set `?dedicated-setup=force` param it will always starts at the beginning of the flow.
* Remove user avatar from to right on complete step (since we don't flip logged in user 
* Moved a set state call out of render loop when checking for active sso config.
* Updated SSO Setup form - pulled redirect url up top and added **e.g.** to issuer url placeholder 
Fixes WEB-307, WEB-301
<ul>
<li><b>🏷️ Name</b> - bmh-dedica646f8ec1c8</li>
<li><b>🔗 URL</b> - <a href="https://bmh-dedica646f8ec1c8.preview.gitpod-dev.com/workspaces" target="_blank">bmh-dedica646f8ec1c8.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See …

removing user from top right for dedicated setup

---

components/dashboard/src/components/AuthorizeGit.tsx
components/dashboard/src/projects/NewProject.tsx
components/dashboard/src/workspaces/CreateWorkspacePage.tsx

Adds Git authorization to Open Workspace page.
This PR handles there git states on workspace creation:
1) No git provider, user is not an owner
1) No git provider, user is an owner
1) One or more git provider exist, but user hasn't authenticated
Fixes WEB-309
Testing the last state is easy. [login](https://se-git-auth.preview.gitpod-dev.com/workspaces) and try creating a workspace.
<ul>
<li><b>🏷️ Name</b> - se-git-auth</li>
<li><b>🔗 URL</b> - <a href="https://se-git-auth.preview.gitpod-dev.com/workspaces" target="_blank">se-git-auth.preview.gitpod-dev.com/workspaces</a>.</li> …

[dashboard] git auth on create workspace

---

components/server/src/workspace/gitpod-server-impl.ts

Part 1 of 2: prevent removing organizational accounts on server.
Next step would be to add some feedback on the frontend.
Part of WEB-319
* Create an Org + SSO config
* Create a new account through the Org's SSO
* Try to remove account from the Org
<ul>
<li><b>🏷️ Name</b> - at-org-blo4618ab85bb</li>
<li><b>🔗 URL</b> - <a href="https://at-org-blo4618ab85bb.preview.gitpod-dev.com/workspaces" target="_blank">at-org-blo4618ab85bb.preview.gitpod-dev.com/workspaces</a>.</li> …

[server] Do not allow to remove Org accounts – WEB-319

---

components/dashboard/src/components/UsageBasedBillingConfig.tsx

This will remove the checkmark icon from the upgrade plan section, see [relevant discussion](https://gitpod.slack.com/archives/C01KPEPNBD0/p1682029962422069) (internal). Cc @mbrevoort 
|-|-|
| <img width="477" alt="Frame 1454" src="https://user-images.githubusercontent.com/120486/236812412-8589cad7-1a7e-4065-af74-f886be5f716e.png"> | <img width="477" alt="Frame 1455" src="https://user-images.githubusercontent.com/120486/236812453-3b611f34-6ff2-4a59-a370-257b2d9494b4.png"> |
1. Create an org and go to billing settings.
2. Then, notice the upgrade plan section does include the checkmark icon in front of the plan details.
<ul>
<li><b>🏷️ Name</b> - gt-remove-a92c808f46</li> …

Remove upgrade plan check icon

---

components/ws-manager-mk2/service/manager.go

Configure custom retry params for `modifyWorkspace`, still with exponential backoff but with a smaller factor (2 instead of 5), such that we retry more quickly.
Fixes WKS-155
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[ws-manager-mk2] Custom retry backoff params for modifyWorkspace

---

components/server/src/user/user-controller.ts

Given that the admin user is removed from the single Org at the end of the Dedicated Onboarding flow, we need a rescue path to be in place if the owner's access to the installation is stonewalled for any reasons. So if they would request a new admin login URL, this would make the admin user become an owner of the Org again.
Part of WEB-303
gitpod:summary
<details>
</details>
<details>
</details> …

[server] Ensure admin user is owner of any Org – WEB-303

---

components/server/src/iam/iam-oidc-create-session-payload.ts
components/server/src/iam/iam-session-app.spec.ts
components/server/src/iam/iam-session-app.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[iam] Validate OIDC Create Session Payload - WEB-338

---

components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx

This fixes a bug where after you activate a Git Integration for an org, we weren't refreshing the current user to account for a new `identity` that they might have. This made it appear that the user needed to go through the Git Integration connection flow from their User Settings area when they didn't need to. I've also added a toast at the end of the Git activate flow to make it clear that the integration was activated.
Fixes WEB-311
* You'll need a working Git Integration. I set one up on https://gitlab.gitpod-dev.com.
* Create the new Git Integration for an org
* Activate it
* At the end of the activation flow:
* You should see a toast telling you it was activated 😄 
* You can navigate (without reloading the page) to your user settings / git integrations. You should see the new …

Refresh user after activating git integration

---

components/public-api-server/pkg/oidc/router.go

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[sso] Improve SSO dance logs & user facing error messages WEB-300

---

components/gitpod-db/src/typeorm/user-db-impl.ts
components/gitpod-db/src/user-db.ts
components/server/src/user/user-service.ts

Just 🧹, no further changes included.
Should be OK if the build is successful. 
gitpod:summary
<details>
</details>
<details>
</details>

[server] remove unused code in user-service.ts

---

components/public-api-server/pkg/oidc/service.go
components/public-api-server/pkg/oidc/service_test.go

Some claims (e.g. email, name) are required. While it's defaults with most IdPs, some require manual configuration to make those claims appear in ID tokens.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[papi] validate ID token claims – WEB-337

---

components/public-api-server/pkg/apiv1/oidc.go
components/public-api-server/pkg/apiv1/oidc_test.go
components/public-api-server/pkg/oidc/oauth2.go
components/public-api-server/pkg/oidc/router.go
components/public-api-server/pkg/oidc/router_test.go
components/public-api-server/pkg/oidc/service.go
components/public-api-server/pkg/oidc/service_test.go

Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-sso-tra7454b9763d</li>
<li><b>🔗 URL</b> - <a href="https://mp-sso-tra7454b9763d.preview.gitpod-dev.com/workspaces" target="_blank">mp-sso-tra7454b9763d.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[sso] Validate Issuer URL + fix trailing slash WEB-345

---

components/server/src/jobs/fix-stripe-job.spec.db.ts
components/server/src/jobs/fix-stripe-job.ts

Fixes WEB-348
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] fix invoices

---

components/server/src/user/stripe-service.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] fix stripe query

---

components/dashboard/src/components/ConfirmationModal.tsx
components/dashboard/src/data/oidc-clients/activate-oidc-client-mutation.ts
components/dashboard/src/data/oidc-clients/oidc-clients-query.ts
components/dashboard/src/provider-utils.tsx
components/dashboard/src/teams/sso/OIDCClientConfigModal.tsx
components/dashboard/src/teams/sso/OIDCClientListItem.tsx
components/dashboard/src/teams/sso/OIDCClients.tsx
components/dashboard/src/teams/sso/SSOConfigForm.tsx

This updates the SSO config UI to account for an explicit verify and activate flow.
Fixes WEB-322
* Using the preview environment under the Org Settings => SSO area...
* Create an SSO Client (should have a gray status icon)
* After creation, you can then verify it (should have an orange status icon)
* After verification, you can activate it (should have a green status icon)
<ul>
<li><b>🏷️ Name</b> - bmh-sso-upa83c0dbe24</li>
<li><b>🔗 URL</b> - <a href="https://bmh-sso-upa83c0dbe24.preview.gitpod-dev.com/workspaces" target="_blank">bmh-sso-upa83c0dbe24.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2 …

Verify/Activate for SSO Configs

---

components/dashboard/src/components/RepositoryFinder.tsx
components/dashboard/src/components/SelectIDEComponent.tsx
components/dashboard/src/components/SelectWorkspaceClassComponent.tsx

This will update the workspace options UX.
Fixes UX-11
Try opening a workspace in `/new`, changing the default editor in user `/preferences`, or going through the user onboarding and notice the new UX for selecting context, editor, and class.
- https://gt-update-9078c1df71.preview.gitpod-dev.com/new
- https://gt-update-9078c1df71.preview.gitpod-dev.com/user/preferences
- https://gt-update-9078c1df71.preview.gitpod-dev.com/workspaces?onboarding=force
<ul>
<li><b>🏷️ Name</b> - gt-update-9078c1df71</li>
<li><b>🔗 URL</b> - <a href="https://gt-update-9078c1df71.preview.gitpod-dev.com/workspaces" target="_blank">gt-update-9078c1df71.preview.gitpod-dev.com/workspaces</a>.</li> …

Update workspace options UX

---

components/server/src/auth/verification-service.ts
components/server/src/workspace/gitpod-server-impl.ts

Verify members of paying orgs
Fixes WEB-369
Fixes #17583
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] verify members of paying orgs

---

components/dashboard/src/teams/TeamSettings.tsx

Updates copy in the delete org modal.
Fixes WEB-368
Open the delete org modal and verify the copy is updated.
gitpod:summary
<details>
</details>
<details>
</details>
/hold

Update copy around on Delete Org modal

---

components/dashboard/src/dedicated-setup/SSOSetupStep.tsx

Updates sso setup learn more doc link to point to https://gitpod.io/docs/dedicated/sso-setup-8f7696e0
Fixes WEB-310
* This one just updates the href, but you can verify the url loads correctly: `https://gitpod.io/docs/dedicated/sso-setup-8f7696e0`
* To full test it you need a preview env with dedicated emulation, which is probably a bit overkill for testing this change.
gitpod:summary
<details>
</details>
<details>
</details> …

Update SSO Setup learn more link

---

WORKSPACE.yaml

This PR updates the JetBrains IDE images to the most recent `stable` version.
<details>
1. For each IDE changed on this PR, follow these steps:
2. Open the preview environment generated for this branch
3. Choose the stable version of the IDE that you're testing as your default editor
4. Start a workspace using any repository (e.g: `https://github.com/gitpod-io/empty`)
5. Verify that the workspace starts successfully
6. Verify that the IDE opens successfully
7. Verify that the version of the IDE corresponds to the one being updated in this PR
The following resources should help, in case something goes wrong (e.g. workspaces don't start):
- …

[JetBrains] Update IDE images to new build version

---

components/dashboard/src/workspaces/CreateWorkspacePage.tsx

Fixes WEB-185
<ul>
<li><b>🏷️ Name</b> - se-create-10dad6f0b2</li>
<li><b>🔗 URL</b> - <a href="https://se-create-10dad6f0b2.preview.gitpod-dev.com/workspaces" target="_blank">se-create-10dad6f0b2.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[dashboard] name org in create dialog

---

components/dashboard/src/components/RepositoryFinder.tsx
components/dashboard/src/data/featureflag-query.ts
components/dashboard/src/onboarding/use-show-user-onboarding.ts

Cleaning up a couple old feature flags.
`paymentVerificationFlow` - wasn't used anywhere anymore
`newSignupFlow` - already enabled in prod. not enabled on dedicated but we don't show this for org users.
Also made a tweak to the `<RepositoryFinder>` component so the `div.title` attribute uses the selected repo if set. On hover you'll at least see the full repo name, which could be truncated.
* Login and signup on preview environment. Reload and verify you don't see the signup again.
* Go to the new workspace page and select a repo.
* Hover over the repo selector, and after a few seconds you'll see the native browser title popup w/ the repo url in it instead of always the word `Repository`
<ul>
<li><b>🏷️ Name</b> - …

Feature Flag Cleanup

---

components/dashboard/src/workspaces/CreateWorkspacePage.tsx

Minor follow-up from https://github.com/gitpod-io/gitpod/pull/17701. Cc @svenefftinge @easyCZ 
~~⚠️ Opening as draft to check if this change feels good.~~ Feels good enough.
| <img width="544" alt="Frame 1528" src="https://github.com/gitpod-io/gitpod/assets/120486/2f35eeaf-b964-41ba-a86c-353a3ff52783"> | <img width="544" alt="Frame 1529" src="https://github.com/gitpod-io/gitpod/assets/120486/0470012e-6f13-4c79-bab9-3e20a9c02340"> |
| <img width="544" alt="Frame 1530" src="https://github.com/gitpod-io/gitpod/assets/120486/b49c3ad1-19a2-423f-9693-f5f56f40dd14"> | <img width="544" alt="Frame 1531" src="https://github.com/gitpod-io/gitpod/assets/120486/c5a96d94-a372-42b3-a734-09403773e20b"> |
Go to `/new` and notice the UX of the new organization …

Update new workspace page header

---

components/dashboard/src/components/DropDown2.tsx
components/dashboard/src/components/RepositoryFinder.tsx
components/dashboard/src/components/SelectIDEComponent.tsx
components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
components/dashboard/src/workspaces/CreateWorkspacePage.tsx

Disable components during workspace context resolution and workspace creation/start.
Fixes WEB-382
<ul>
<li><b>🏷️ Name</b> - se-create-ws</li>
<li><b>🔗 URL</b> - <a href="https://se-create-ws.preview.gitpod-dev.com/workspaces" target="_blank">se-create-ws.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details> …

[dashboard] create ws page - disable components

---

components/server/src/jobs/org-only-migration-job.spec.db.ts
components/server/src/jobs/org-only-migration-job.ts

the query didn't include all candidates
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] fix migration query

---

components/server/src/jobs/org-only-migration-job.ts

After https://github.com/gitpod-io/gitpod/pull/17736 we can enable the migration job again
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Enable migration job again

---

components/server/src/session-handler.ts

Fixes #
1. Preview
2. Sign-in
3. Delete the `_v2_` cookie (currently we issue both, but we want to check that everything continues to work without the old session cookie present
4. Perform actions on the preview env, nothing should break.
<ul>
<li><b>🏷️ Name</b> - mp-server-5015527990</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-5015527990.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-5015527990.preview.gitpod-dev.com/workspaces</a>.</li>
</ul> …

[server] JWT Sessions set User and Session ID - WEB-410

---

components/server/src/migration/user-to-team-migration-service.ts

fixes stripe customer updates during migration
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[migration] fix migration of stripe customers

---

components/dashboard/src/admin/BlockedEmailDomains.tsx

We currently have 8000 entries on the server and we don't expect this to increase drastically, so server-side pagination is not necessary here. But the UI on the frontend should do pagination as otherwise the list and page is quite large.
Fixes #
<ul>
<li><b>🏷️ Name</b> - se-admin-d58fa058f30</li>
<li><b>🔗 URL</b> - <a href="https://se-admin-d58fa058f30.preview.gitpod-dev.com/workspaces" target="_blank">se-admin-d58fa058f30.preview.gitpod-dev.com/workspaces</a>.</li> …

[dashboard] minor improvements for email domains

---

components/public-api-server/pkg/oidc/router.go
components/public-api-server/pkg/oidc/service.go
components/server/src/auth/login-completion-handler.ts
components/server/src/container-module.ts
components/server/src/iam/iam-session-app.spec.ts
components/server/src/iam/iam-session-app.ts
components/server/src/server.ts
components/server/src/session-handler.ts
components/server/src/user/user-controller.ts

This change ensures we forward all cookies from IAM sessions to the client
Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-server-460cfce934</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-460cfce934.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-460cfce934.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[server] Issue JWT cookie in IAM Sessions for OIDC sign-in WEB-416

---

components/server/src/session-handler.ts

Fixes #
1. Preview
2. Sign-in
3. Sign-out - no v2 or jwt cookie should remain
<ul>
<li><b>🏷️ Name</b> - mp-server-60cd599d45</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-60cd599d45.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-60cd599d45.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details> …

[server] Fix clearing of JWT cookies

---

operations/observability/mixins/IDE/dashboards/components/supervisor.json

Fixes [internal chat](https://gitpod.slack.com/archives/C03QM0ZHF5Z/p1685593155012499?thread_ts=1685557340.152049&cid=C03QM0ZHF5Z)
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[observability] add WorkspaceUpdates filter to supervisor

---

components/server/src/projects/projects-service.ts

Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-project28cf5a7654</li>
<li><b>🔗 URL</b> - <a href="https://mp-project28cf5a7654.preview.gitpod-dev.com/workspaces" target="_blank">mp-project28cf5a7654.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[server] Validate cloneURL in createProject WEB-404

---

.github/workflows/code-nightly.yml

Ahh you know.. the regular ol' ahead-of-release PR :) 
Do not! ❤️

Point code nightly to release branch

---

components/server/src/auth/authenticator.ts
components/server/src/iam/iam-session-app.ts
components/server/src/server.ts
components/server/src/session-handler.ts

If the token is older than 1h, the refresh endpoint will also update it.
* Depends on https://github.com/gitpod-io/gitpod/pull/17797
<ul>
<li><b>🏷️ Name</b> - mp-server-c9ccfb03dd</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-c9ccfb03dd.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-c9ccfb03dd.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[server] Make JWT Session rolling through refresh endpoint WEB-418

---

components/server/src/workspace/gitpod-server-impl.ts

The circular structure of DBUser objects cannot be serialized for results of websocket API, thus it needs to be cleaned. 
Fixes WEB-400
Checks the dashboard works, i.e. change email on your profile page.
<ul>
<li><b>🏷️ Name</b> - at-dbuser</li>
<li><b>🔗 URL</b> - <a href="https://at-dbuser.preview.gitpod-dev.com/workspaces" target="_blank">at-dbuser.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
Run the build with werft instead of …

[server] avoid returning DBUser on ws API – WEB-400

---

components/dashboard/src/data/oidc-clients/oidc-clients-query.ts
components/dashboard/src/user-settings/Account.tsx
components/gitpod-db/src/typeorm/entity/db-identity.ts
components/gitpod-db/src/typeorm/migration/1685955742395-AddLastSigninTimeToIdentity.ts
components/gitpod-db/src/user-db.spec.db.ts
components/gitpod-protocol/src/protocol.ts
components/server/src/auth/generic-auth-provider.ts
components/server/src/iam/iam-session-app.ts

This PR introduces the `Identity.lastSigninTime` attribute, which is updated as `User.identities[signed in idp].email` on each sign-in into an Org-owned account. 
The email address provided by the IdP is to be rendered for Org-owned accounts. If the account is Org-owned we'll take the most recent email address, which takes into account that the Org might have updated the SSO config and therefore an older identity remains in the database. 
Fixes WEB-437
* Sign-in into the Org https://at-sso-email.preview.gitpod-dev.com/login/acme
* Configure a connection to a Git provider with a different email address
* This is blocked by WEB-444 as I'm not able to connect from within a simple SSO account
* See the email address is unchanged on /user/settings
<p>Gitpod was successfully deployed to your …

Read email from SSO profile – WEB-437

---

components/supervisor/pkg/supervisor/supervisor.go

Add grpc_recovery middleware to supervisor grpc server, this will enhance the stability of the supervisor
Fixes #
1. start a workspace in this preview env
2. in workspace run `gp ports test`, it should be output an error, workspace should still running
3. use `kubectl logs ws-{workspaceID}`, it should be has some PANIC log
<ul>
<li><b>🏷️ Name</b> - pd-supervi25cb0d4d8e</li>
<li><b>🔗 URL</b> - <a href="https://pd-supervi25cb0d4d8e.preview.gitpod-dev.com/workspaces" target="_blank">pd-supervi25cb0d4d8e.preview.gitpod-dev.com/workspaces</a>.</li> …

[supervisor] add grpc_recovery middleware

---

components/gitpod-db/src/periodic-deleter.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[db] fix expensive table check

---

components/server/src/workspace/workspace-starter.ts

Remove stale workspace feature flags
Fixes WKS-214
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] Remove stale workspace feature flags

---

components/dashboard/src/data/featureflag-query.ts
components/dashboard/src/start/VerifyModal.tsx
components/server/src/auth/verification-service.ts
components/server/src/workspace/gitpod-server-impl.ts

Performs phone verification via a `call` vs. `sms` if the flag, `phoneVerificationByCall`, is enabled. They user-facing copy for verification is also updated to reflect a phone call vs. sms.
A related step is to make sure we persist the verification `channel` used by a user. I'm going to handle that as a followup item to keep this one minimal since it's behind a flag (we can wait for the persist change before enabling it).
Fixes WEB-425
* This is tricky to test, as twilio isn't enabled in our preview environments by default.
* I was able to test this by manually adding the config for the verification service config in my preview environment. The environment has since been reset though.
<ul>
<li><b>🏷️ Name</b> - …

Add voice calls for phone verification

---

components/common-go/experiments/flags.go
components/public-api-server/pkg/auth/session_jwt.go
components/public-api-server/pkg/server/server.go

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[go] Remove jwtSessions feature flag

---

components/server/src/auth/generic-auth-provider.ts
components/server/src/auth/login-completion-handler.ts
components/server/src/iam/iam-session-app.spec.ts
components/server/src/jobs/org-only-migration-job.ts
components/server/src/migration/user-to-team-migration-service.spec.db.ts
components/server/src/migration/user-to-team-migration-service.ts
components/server/src/user/user-service.ts
components/server/src/workspace/gitpod-server-impl.ts

Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-fix-git-provider</li>
<li><b>🔗 URL</b> - <a href="https://mp-fix-git-provider.preview.gitpod-dev.com/workspaces" target="_blank">mp-fix-git-provider.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[server] Fix org git auth

---

components/dashboard/src/Login.tsx
components/dashboard/src/admin/BlockedEmailDomains.tsx
components/dashboard/src/admin/BlockedRepositories.tsx
components/dashboard/src/admin/ProjectDetail.tsx
components/dashboard/src/admin/ProjectsSearch.tsx
components/dashboard/src/admin/Property.tsx
components/dashboard/src/admin/UserDetail.tsx
components/dashboard/src/admin/WorkspaceDetail.tsx
components/dashboard/src/admin/WorkspacesSearch.tsx
components/dashboard/src/components/Button.tsx
components/dashboard/src/components/DropDown2.tsx
components/dashboard/src/components/Tooltip.tsx
components/dashboard/src/components/UsageLimitReachedModal.tsx
components/dashboard/src/components/toasts/Toast.tsx
components/dashboard/src/feedback-form/FeedbackComponent.tsx
components/dashboard/src/onboarding/LinkedInBanner.tsx
components/dashboard/src/projects/Events.tsx
components/dashboard/src/projects/NewProject.tsx
components/dashboard/src/projects/Project.tsx
components/dashboard/src/projects/ProjectVariables.tsx
components/dashboard/src/teams/TeamUsageBasedBilling.tsx
components/dashboard/src/usage/UsageEntry.tsx
components/dashboard/src/user-settings/PersonalAccessTokens.tsx
components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
components/dashboard/src/whatsnew/WhatsNew-2021-06.tsx
components/dashboard/src/whatsnew/WhatsNew.tsx
components/dashboard/src/workspaces/ConnectToSSHModal.tsx
components/dashboard/src/workspaces/CreateWorkspacePage.tsx
components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx

When using react fragments directly around text nodes: `<>some text</>` - it doesn't interact well with some browser extensions, like Google Translate, that manipulate the dom. [This article](https://javascript.plainenglish.io/react-fragments-a-potential-program-killer-91c5203f53e1) explains the problem well.
The problem reported was on the start workspace page, but I found issues anywhere a `<Button/>` transitions to a `loading` state. I've fixed how fragments are used there so there is never one around a direct text node. I've also cleaned up other places that are potential issues, or didn't need fragments at all.
Fixes WEB-367, WEB-442
* Check out the video in WEB-367 for exact steps & details in reproducing, but it's essentially installing Google Translate extension. Visit start …

cleaning up fragment usage

---

components/server/src/auth/generic-auth-provider.ts

Fixes #
* sign up
* log out
* try to login again
* see the login works as expected
<ul>
<li><b>🏷️ Name</b> - at-fix-log7133594c70</li>
<li><b>🔗 URL</b> - <a href="https://at-fix-log7133594c70.preview.gitpod-dev.com/workspaces" target="_blank">at-fix-log7133594c70.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

Fix logins into existing accounts

---

components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/workspace_controller_test.go

Test prebuilds and imagebuilds
Fixes WKS-78
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[ws-manager-mk2] Test prebuilds and imagebuilds

---

components/dashboard/src/components/SelectIDEComponent.tsx

Bump experimental IDE options to the top so that it is easier to find for people testing them.
Fixes https://linear.app/gitpod/issue/IDE-139
<ul>
<li><b>🏷️ Name</b> - ft-bump-brc8dc70ca84</li>
<li><b>🔗 URL</b> - <a href="https://ft-bump-brc8dc70ca84.preview.gitpod-dev.com/workspaces" target="_blank">ft-bump-brc8dc70ca84.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

Prefer experimental IDE options

---

install/installer/pkg/components/ide-metrics/configmap.go

Add counters define in ide-metrics
Related IDE-154
Related https://github.com/gitpod-io/gitpod-vscode-desktop/pull/78
<ul>
<li><b>🏷️ Name</b> - hw-fix-ide-154</li>
<li><b>🔗 URL</b> - <a href="https://hw-fix-ide-154.preview.gitpod-dev.com/workspaces" target="_blank">hw-fix-ide-154.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[ide-metrics] add counters for local-ssh proxy

---

components/server/src/jobs/org-only-migration-job.spec.db.ts
components/server/src/jobs/org-only-migration-job.ts

There are still some workspaces without an organizationId for inactive users. This job migartes the workspaces and sets the orgId.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] add organizationId to old workspaces

---

components/dashboard/src/components/AuthorizeGit.tsx

Minor style updates for git integrations during user onboarding in Dedicated.
⚠️ Haven't tested code changes in a preview environment.
|-|-|
| <img width="1512" alt="Screenshot 2023-05-16 at 21 26 21" src="https://github.com/gitpod-io/gitpod/assets/120486/e86d5707-a0ea-43b6-9110-067bccb1a595"> | <img width="1512" alt="Screenshot 2023-05-16 at 21 25 46" src="https://github.com/gitpod-io/gitpod/assets/120486/8b6ab9db-a345-44ee-8a45-0328f4e5fcde"> |
| <img width="1512" alt="Screenshot 2023-05-16 at 21 26 17" src="https://github.com/gitpod-io/gitpod/assets/120486/14fe11b3-cb1d-444e-8eac-449887be7d73"> | <img width="1512" alt="Screenshot 2023-05-16 at 21 35 15" src="https://github.com/gitpod-io/gitpod/assets/120486/52f72844-4d73-4785-b314-8ecaf4c5bbf1"> |
<p>Gitpod was …

Improve git integrations during user onboarding

---

components/server/src/redis/data-cache.ts

Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-server-bf09e39fbc</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-bf09e39fbc.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-bf09e39fbc.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[server] Cache refreshes TTL on cache hit

---

components/gitpod-db/go/cost_center.go
components/gitpod-db/go/cost_center_test.go

Restore the previous spendingLimit when users cancel  their stripe subscription-
Fixes WEB-449
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[usage] restore previous spending Limit

---

dev/gpctl/cmd/clusters-gettlsconfig.go
dev/gpctl/cmd/workspaces.go
dev/loadgen/README.md

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[gpctl] Use mk2 tls by default

---

components/server/src/jobs/fix-stripe-job.ts
components/server/src/user/stripe-service.ts

The stripe customers still haven't been updated due to a bug in the job.
Fixes WEB-479
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] fix stripe job

---

components/ws-daemon/pkg/controller/workspace_controller.go
components/ws-manager-api/go/crd/v1/workspace_types.go
components/ws-manager-mk2/controllers/metrics.go
components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/timeout_controller.go
components/ws-manager-mk2/controllers/workspace_controller.go
components/ws-manager-mk2/pkg/activity/activity.go
components/ws-manager-mk2/service/manager.go

Simplifiy condition checking
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[ws-manager-mk2] Simplifiy condition checking

---

components/common-go/baseserver/testing.go

Avoid build errors like [this](https://github.com/gitpod-io/gitpod/actions/runs/5264242467/jobs/9515287095?pr=17831#step:14:4380). 
Fixes #
See that tests are succeeding.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[common-go] Avoid "bind: address already in use" during tests

---

install/installer/pkg/components/spicedb/constants.go

Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-spicedb87f59ab3de</li>
<li><b>🔗 URL</b> - <a href="https://mp-spicedb87f59ab3de.preview.gitpod-dev.com/workspaces" target="_blank">mp-spicedb87f59ab3de.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[spicedb] Upgrade to v1.22.0 WEB-412

---

.github/workflows/authorization.yml

Uses a github action to validate spicedb schema
Fixes #
See it in action https://github.com/gitpod-io/gitpod/actions/runs/5268448661/jobs/9525127621
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[spicedb] Add CI validation check WEB-476

---

install/installer/pkg/components/spicedb/data/schema.yaml

Fixes #
https://play.authzed.com/s/hSwh3V53xCly/schema
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[spicedb] Initial schema with projects

---

.github/workflows/code-nightly.yml

Points the workflow back from the release branch

Code-nightly -> `gp-code/main`

---

components/server/src/workspace/workspace-starter.ts

Mark non-stopped instances for which no cluster is registered as stopped, if a user or an admin tries to stop them manually.
Just to be clear this is merely allowing users and admins to fix stale db state (symptoms) instead of fixing the underlying issue (WEB-480 and WKS-243)
Fixes WEB-487
<ul>
<li><b>🏷️ Name</b> - se-delete-orphaned</li>
<li><b>🔗 URL</b> - <a href="https://se-delete-orphaned.preview.gitpod-dev.com/workspaces" target="_blank">se-delete-orphaned.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact …

[server] mark orphaned instances stopped

---

dev/preview/infrastructure/modules/gce/variables.tf
dev/preview/infrastructure/modules/harvester/variables.tf
dev/preview/infrastructure/variables.tf

gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Prepare for gen100

---

components/dashboard/src/onboarding/StepOrgInfo.tsx
components/gitpod-db/go/cost_center.go
components/gitpod-db/go/cost_center_test.go
components/gitpod-db/src/typeorm/migration/1686907204398-FreeCredits.ts
components/server/src/user/user-service.ts

With this change each user will only get free credits for the first org they every created.
Fixes WEB-483
- login to the preview environment
- verify your the first org has 500 credits
- verify any additional orgs you create have 0 credits
<ul>
<li><b>🏷️ Name</b> - se-compute337effdd32</li>
<li><b>🔗 URL</b> - <a href="https://se-compute337effdd32.preview.gitpod-dev.com/workspaces" target="_blank">se-compute337effdd32.preview.gitpod-dev.com/workspaces</a>.</li>
</ul> …

[usage] compute correct spending limit

---

components/server/src/authorization/checks.ts
components/server/src/workspace/gitpod-server-impl.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[perms] Align perm checks with permissions in model

---

components/gitpod-cli/cmd/root.go

[gp-cli] respect exit-code when received SIGNAL
Fixes #17962
Fixes IDE-175
1. start a workspace in this preview env
2. run
```bash
gp sync-await does-not-matter; echo "$?"
```
3. and press Ctrl-C to abort the waiting. The result should be 130
<ul>
<li><b>🏷️ Name</b> - iqqbot-cli7c91f1f493</li>
<li><b>🔗 URL</b> - <a href="https://iqqbot-cli7c91f1f493.preview.gitpod-dev.com/workspaces" target="_blank">iqqbot-cli7c91f1f493.preview.gitpod-dev.com/workspaces</a>.</li>
</ul> …

[gp-cli] respect exit-code when received SIGNAL

---

components/server/src/authorization/checks.ts
components/server/src/authorization/definitions.ts

Just makes using spicedb API a tad more pleasant
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[perms] Helpers for relationship, object ref and subject

---

components/ide-metrics/cmd/run.go
components/ide-metrics/pkg/server/server.go
install/installer/pkg/components/ide-metrics/configmap.go

Add grpc metrics for ide-metrics itself IDE-170
Fixes IDE-170
1. open this branch in gitpod.io
2. run `./dev/preview/portforward-monitoring-satellite.sh`
3. open prometheus via workspace port url
4. open a workspace in preview env
5. search metrics `grpc_server_started_total{job="ide-metrics"}` you should see ide-metrics itself metrics and supervisor metrics
<ul>
<li><b>🏷️ Name</b> - pd-ide-170</li>
<li><b>🔗 URL</b> - <a href="https://pd-ide-170.preview.gitpod-dev.com/workspaces" target="_blank">pd-ide-170.preview.gitpod-dev.com/workspaces</a>.</li> …

Add grpc metrics for ide-metrics itself

---

operations/observability/mixins/IDE/dashboards.libsonnet
operations/observability/mixins/IDE/dashboards/components/local-ssh.json

Fixes IDE-154
Preview here https://grafana.gitpod.io/d/e78bdf2b-ad72-4bc7-832d-94eec9e7a2e6/local-ssh-reliability?orgId=1
|Without Rate (current)|With Rate|
|:-:|:-:|
|![screencapture-grafana-gitpod-io-d-e78bdf2b-ad72-4bc7-832d-94eec9e7a2e6-local-ssh-reliability-2023-06-19-03_25_17](https://github.com/gitpod-io/gitpod/assets/20944364/c62c3508-cea6-4ce6-9587-b18cc3286c60)|![screencapture-grafana-gitpod-io-d-e78bdf2b-ad72-4bc7-832d-94eec9e7a2e6-local-ssh-reliability-2023-06-19-03_10_25](https://github.com/gitpod-io/gitpod/assets/20944364/f744fad6-4738-40b4-96ba-57030b7d4c38)|
gitpod:summary
<details>
</details>
<details>
</details>
<details> …

[observability] add dashboard for local ssh IDE-154

---

install/installer/pkg/components/workspace/ide/constants.go

Blocked by
Fixes IDE-150
Relates https://github.com/gitpod-io/gitpod-code/pull/12
<ul>
<li><b>🏷️ Name</b> - hw-ports-view</li>
<li><b>🔗 URL</b> - <a href="https://hw-ports-view.preview.gitpod-dev.com/workspaces" target="_blank">hw-ports-view.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

Update Ports View to bring ability to change port forward protocol IDE-150

---

components/ws-proxy/pkg/proxy/infoprovider.go

Return last instance if multiple instances are found
Related to WKS-250
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[ws-proxy] Return last instance if multiple instances are found

---

components/content-service-api/typescript/package.json
components/gitpod-db/src/container-module.ts
components/gitpod-db/src/project-db.ts
components/gitpod-db/src/typeorm/project-db-impl.ts
components/gitpod-db/src/typeorm/transactional-db-impl.ts
components/gitpod-db/src/typeorm/user-db-impl.ts
components/gitpod-db/src/typeorm/workspace-db-impl.ts
components/gitpod-db/src/user-db.ts
components/gitpod-protocol/package.json
components/image-builder-api/typescript/package.json
components/server/package.json
components/server/src/container-module.ts
components/server/src/user/user-service.spec.db.ts
components/ws-daemon-api/typescript/package.json
components/ws-manager-api/typescript/package.json
components/ws-manager-bridge-api/typescript/package.json
components/ws-manager-bridge/package.json
yarn.lock

This PR allows DBs to be transactional, e.g enables the following pattern:
```
const relationship = relationship(ref_project(project), "org", ref_org(teamId));
try {
await this.projectDB.transaction(async (db) => {
await db.storeProject(project);
await this.spiceDB.writeRelationships(relations(relationship));
});
} catch (err) {
await this.spiceDB.writeRelationships(relations_delete(relationship));
throw err;
}
```
So far we had this for UserDB and WorkspaceDB, only.
The most interesting pieces are [here](https://github.com/gitpod-io/gitpod/blob/3dc4742d8350b273346190c1bca50234c38cfd4e/components/gitpod-db/src/typeorm/transactional-db-impl.ts#L11-L40) and [here](https://github.com/gitpod-io/gitpod/blob/3dc4742d8350b273346190c1bca50234c38cfd4e/components/gitpod-db/src/typeorm/project-db-imp …

[db, ts] Introduce a generic db.transaction()

---

components/gitpod-db/src/typeorm/migration/1686907204398-FreeCredits.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[db] check if table exists before creating

---

components/server/src/authorization/perms.ts
components/server/src/workspace/gitpod-server-impl.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[perms] Simplify guard operations

---

components/server/src/authorization/checks.ts
components/server/src/authorization/definitions.ts
components/server/src/workspace/gitpod-server-impl.ts
install/installer/pkg/components/spicedb/data/schema.yaml

Fixes WEB-512
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[perms] check for read/write permissions on orgs – WEB-512

---

components/server/src/authorization/definitions.ts
install/installer/pkg/components/spicedb/data/schema.yaml

Fixes #
https://play.authzed.com/s/b2WDk7QPgqsE/relationships
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[perms] Everyone has member in an org, plus they can have owner

---

components/dashboard/src/data/featureflag-query.ts
components/dashboard/src/hooks/use-user-loader.ts

Based on: https://github.com/gitpod-io/gitpod/pull/18024
Fixes #
<ul>
<li><b>🏷️ Name</b> - gpl-at-ret6ec96a7f02</li>
<li><b>🔗 URL</b> - <a href="https://gpl-at-ret6ec96a7f02.preview.gitpod-dev.com/workspaces" target="_blank">gpl-at-ret6ec96a7f02.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[dashboard] retry useUserQuery if error code is not 401 – WEB-560

---

components/server/src/user/user-service.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/workspace-factory.ts
components/server/src/workspace/workspace-starter.ts

To illustrate that using private and constructor injection is not hurting readability but allows to easily spot unused members.
Fixes #
<ul>
<li><b>🏷️ Name</b> - se-server-cleanups</li>
<li><b>🔗 URL</b> - <a href="https://se-server-cleanups.preview.gitpod-dev.com/workspaces" target="_blank">se-server-cleanups.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[server] make members private

---

components/gitpod-db/src/typeorm/team-db-impl.ts
components/server/src/authorization/perms.ts
components/server/src/authorization/relationships.ts
components/server/src/container-module.ts
components/server/src/workspace/gitpod-server-impl.ts

Adds owner/member relations to users, when they either:
* Create Org
* Change Role of a user
* [WEB-505](https://linear.app/gitpod/issue/WEB-505/migrate-createteam)
* [WEB-507](https://linear.app/gitpod/issue/WEB-507/migrate-setteammemberrole)
* Preview
* Change role of a user
* Deletion of users does not yet remove the relation
<ul>
<li><b>🏷️ Name</b> - mp-perms-cc78c52d95d</li>
<li><b>🔗 URL</b> - <a href="https://mp-perms-cc78c52d95d.preview.gitpod-dev.com/workspaces" target="_blank">mp-perms-cc78c52d95d.preview.gitpod-dev.com/workspaces</a>.</li> …

[perms] Grant owner/member on role change WEB-505, WEB-507

---

components/server/src/authorization/checks.ts
components/server/src/authorization/definitions.ts
components/server/src/workspace/gitpod-server-impl.ts
install/installer/pkg/components/spicedb/data/schema.yaml

Delete Org relationships with member/owner on user removal from org.
* Depends on https://github.com/gitpod-io/gitpod/pull/17993
1. Preview
2. Invite someone to Org
3. Remove the user from the org
<ul>
<li><b>🏷️ Name</b> - mp-perms-d11fd8e73dc</li>
<li><b>🔗 URL</b> - <a href="https://mp-perms-d11fd8e73dc.preview.gitpod-dev.com/workspaces" target="_blank">mp-perms-d11fd8e73dc.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
Run the …

[perms] Check & Update relationships on removeTeamMember WEB-508

---

components/dashboard/src/Login.tsx

Follow-up from https://github.com/gitpod-io/gitpod/pull/17748, for cleaning up the welcome page check for **dedicated**, etc.
Test to login and make sure the welcome page never shows up, like in dedicated in-progress pages, etc.
<ul>
<li><b>🏷️ Name</b> - gt-remote-695f04de5e</li>
<li><b>🔗 URL</b> - <a href="https://gt-remote-695f04de5e.preview.gitpod-dev.com/workspaces" target="_blank">gt-remote-695f04de5e.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

Remove welcome page check

---

components/server/src/authorization/relationships.ts
components/server/src/projects/projects-service.ts

Fixes WEB-474
- create a project
- see that it's created
- delete a project
- see that it's gone :heavy_check_mark: 
<ul>
<li><b>🏷️ Name</b> - gpl-fga-org-proj</li>
<li><b>🔗 URL</b> - <a href="https://gpl-fga-org-proj.preview.gitpod-dev.com/workspaces" target="_blank">gpl-fga-org-proj.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[perms] Project and org relations

---

components/openvsx-proxy/pkg/config.go
components/openvsx-proxy/pkg/openvsxproxy_test.go
install/installer/pkg/components/openvsx-proxy/configmap.go

for context https://gitpod.slack.com/archives/C01KGM9BH54/p1687506314260599
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

openvsx proxy clean up domain

---

install/installer/pkg/components/spicedb/constants.go

https://github.com/authzed/spicedb/releases/tag/v1.22.2
No breaking changes
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[spicedb] Upgrade to 1.22.2

---

components/server/src/workspace/gitpod-server-impl.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[perms] Implement getTeams WEB-501

---

components/server/src/projects/projects-service.ts

Follow up for [this PRs comment](https://github.com/gitpod-io/gitpod/pull/18037#discussion_r1241816833).
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] Make sure to re-add project -> org relation on failed deletion

---

components/server/src/authorization/checks.ts
components/server/src/authorization/definitions.ts
components/server/src/workspace/gitpod-server-impl.ts
install/installer/pkg/components/spicedb/data/schema.yaml

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[perms] Read/write billing - WEB-541, WEB-542, WEB-543, WEB-544, WEB-545, WEB-546, WEB-547

---

install/installer/pkg/common/render.go
install/installer/pkg/components/redis/constants.go
install/installer/pkg/components/redis/deployment.go

Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-redis-cf64372d97c</li>
<li><b>🔗 URL</b> - <a href="https://mp-redis-cf64372d97c.preview.gitpod-dev.com/workspaces" target="_blank">mp-redis-cf64372d97c.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[redis] Use chainguard image  WEB-574

---

install/installer/pkg/components/database/cloudsql/constants.go

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[cloud-sql] Remove unused constant WEB-577

---

install/installer/pkg/components/database/cloudsql/constants.go

Fixes #
Will need to be tested on staging, as we don't have GCP DB in preview
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[gce-proxy] Upgrade to 1.33.8-alpine

---

install/installer/pkg/common/render.go
install/installer/pkg/components/redis/constants.go
install/installer/pkg/components/redis/deployment.go

Reverts gitpod-io/gitpod#18067

Revert "[redis] Use chainguard image  WEB-574"

---

install/installer/pkg/common/constants.go

Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-kube-rb16363306c6</li>
<li><b>🔗 URL</b> - <a href="https://mp-kube-rb16363306c6.preview.gitpod-dev.com/workspaces" target="_blank">mp-kube-rb16363306c6.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

Upgrade kube-rbac-proxy to 0.14.2 SID-433

---

components/server/src/authorization/authorizer.ts
components/server/src/authorization/definitions.ts
components/server/src/authorization/spicedb-authorizer.ts
components/server/src/projects/projects-service.ts
components/server/src/workspace/gitpod-server-impl.ts
install/installer/pkg/components/spicedb/data/schema.yaml

Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-perms-d844bcc7aac</li>
<li><b>🔗 URL</b> - <a href="https://mp-perms-d844bcc7aac.preview.gitpod-dev.com/workspaces" target="_blank">mp-perms-d844bcc7aac.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[perms] Implement organization delete

---

components/server/package.json
yarn.lock

unused
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] Remove @google-cloud/storage

---

yarn.lock

This one resolves it self by removing the line from yarn.lock and rerunning yarn install
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[deps] update ansi-regex 3.0.0 to 3.0.1

---

.werft/package.json
.werft/yarn.lock
WORKSPACE.yaml
components/gitpod-db/package.json
components/gitpod-db/src/auth-provider-entry.spec.db.ts
components/gitpod-protocol/package.json
components/server/package.json
components/server/src/typings/express/index.d.ts
components/server/tsconfig.json
components/ws-manager-api/typescript/package.json
components/ws-manager-bridge/package.json
package.json
yarn.lock

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Upgrade ts-node to 10.4 WEB-575, WEB-576

---

dev/preview/workflow/preview/deploy-gitpod.sh
test/tests/workspace/ephemeral_storage_limit_test.go

Add e2e test for ephemeral storage limit.
Fix preview env workspace classes, got renamed in https://github.com/gitpod-io/gitpod/pull/17950
Fixes WKS-224
```
cd test
go test -v ./... -run TestEphemeralStorageLimit
```
<ul>
<li><b>🏷️ Name</b> - wv-test-epbe45fdf225</li>
<li><b>🔗 URL</b> - <a href="https://wv-test-epbe45fdf225.preview.gitpod-dev.com/workspaces" target="_blank">wv-test-epbe45fdf225.preview.gitpod-dev.com/workspaces</a>.</li> …

[test] Ephemeral storage limit, fix preview workspace classes

---

components/gitpod-db/src/container-module.ts
components/gitpod-protocol/src/analytics.ts
components/server/src/authorization/authorizer.ts
components/server/src/authorization/definitions.ts
components/server/src/authorization/spicedb.ts
components/server/src/container-module.ts
components/server/src/prebuilds/prebuild-manager.ts
components/server/src/projects/projects-service.spec.db.ts
components/server/src/projects/projects-service.ts
components/server/src/workspace/env-var-service.spec.ts
components/server/src/workspace/env-var-service.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/headless-log-controller.ts
components/ws-manager-bridge/src/container-module.ts
install/installer/pkg/components/spicedb/data/schema.yaml

The ProjectsService does now use the new authorizer to maintain relationships and check for permissions. 
It does it in addition to any checks that happen in gitpod-server-impl.ts.
To allow checking permissions we need to pass in the userId, so the majority of file changes are that.
This PR also adds a test for the project service.
Please review https://github.com/gitpod-io/gitpod/pull/18099 first
Fixes WEB-521
Fixes WEB-522
Fixes WEB-524
Fixes WEB-525
<ul>
<li><b>🏷️ Name</b> - se-projectservice</li>
<li><b>🔗 URL</b> - <a href="https://se-projectservice.preview.gitpod-dev.com/workspaces" target="_blank">se-projectservice.preview.gitpod-dev.com/workspaces</a>.</li> …

[server] ProjectService - perm-check and testing

---

components/gitpod-db/src/typeorm/team-db-impl.ts
components/gitpod-db/src/typeorm/transactional-db-impl.ts
components/server/.vscode/launch.json
components/server/src/orgs/organization-service.spec.db.ts
components/server/src/orgs/organization-service.ts
components/server/src/projects/projects-service.spec.db.ts
components/server/src/projects/projects-service.ts
components/server/src/test/service-testing-container-module.ts
components/server/src/workspace/gitpod-server-impl.ts

Moves the member management to the org service
depends on
-  https://github.com/gitpod-io/gitpod/pull/18099
- https://github.com/gitpod-io/gitpod/pull/18111
Fixes WEB-506
<ul>
<li><b>🏷️ Name</b> - se-check-for-members</li>
<li><b>🔗 URL</b> - <a href="https://se-check-for-members.preview.gitpod-dev.com/workspaces" target="_blank">se-check-for-members.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - se-check-for-members-gha.12533</li>
</ul>
<details> …

[server] Org service does member handling

---

components/server/package.json
components/server/src/projects/projects-service.spec.db.ts
components/server/src/projects/projects-service.ts
install/installer/pkg/components/spicedb/data/schema.yaml

- more testing
- throw 404 instead of undefined
- more permission checks
Fixes #
<ul>
<li><b>🏷️ Name</b> - se-projectservice-2</li>
<li><b>🔗 URL</b> - <a href="https://se-projectservice-2.preview.gitpod-dev.com/workspaces" target="_blank">se-projectservice-2.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - se-projectservice-2-gha.12632</li>
</ul>
<details> …

[server] more project service

---

components/ws-manager-mk2/service/manager.go

Prevent creation of multiple workspace instances with the same id
Fixes WKS-262
I started one workspace and then hardcoded the workspace id of that workspace in the workspace exists check
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[ws-manager-mk2] Prevent creation of multiple workspace instances with the same id

---

operations/observability/mixins/IDE/rules/opensvx.yaml
operations/observability/mixins/IDE/rules/supervisor.yaml
operations/observability/mixins/IDE/rules/vscode.yaml

[obs] add ide alert for dedicated
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[obs] add ide alert for dedicated

---

.github/workflows/lacework-inline-scanner.yml

Follow up for https://github.com/gitpod-io/gitpod/pull/18178
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[workflow] Fix trigger for lacework-inline-scanner

---

components/gitpod-protocol/src/util/timeutil.ts
components/server/.eslintrc
components/server/BUILD.yaml
components/server/src/orgs/organization-service.spec.db.ts
components/server/src/orgs/organization-service.ts
components/server/src/prebuilds/bitbucket-app.ts
components/server/src/prebuilds/bitbucket-server-app.ts
components/server/src/prebuilds/github-app.ts
components/server/src/prebuilds/github-enterprise-app.ts
components/server/src/prebuilds/gitlab-app.ts
components/server/src/projects/projects-service.spec.db.ts
components/server/src/projects/projects-service.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/workspace-starter.ts
install/installer/pkg/components/spicedb/data/schema.yaml

Adds the following functionality organization service:
- listOrganizationByMember
- getOrganization
- updateOrganization
- getSettings and updateSettings
Fixes WEB-604
<ul>
<li><b>🏷️ Name</b> - se-more-org-service</li>
<li><b>🔗 URL</b> - <a href="https://se-more-org-service.preview.gitpod-dev.com/workspaces" target="_blank">se-more-org-service.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - </li>
</ul>
<details>
Run the build …

[server] more org service

---

components/ws-manager-bridge/src/metrics.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[ws-man-bridge] Fix metric label reporting

---

.github/workflows/code-nightly.yml

Fix code-nightly.yml
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Fix code-nightly.yml

---

components/server/src/workspace/gitpod-server-impl.ts

Adds hooks to register listener for instance updates. We do not yet push updates the subscribers, but this adds the necessary hooks.
Fixes #
1. Preview continues to work
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] Register redis update listeners

---

test/tests/components/ws-daemon/cpu_burst_test.go

Relates to WKS-153
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[test] Fix CPU burst test panic

---

operations/observability/mixins/workspace/dashboards.libsonnet

Fixes WKS-300
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Fix: remove ws-manager.json dashboard

---

.github/workflows/comment-ops.yaml
.github/workflows/preview-env-check-regressions.yml
.github/workflows/preview-env-gc.yml

Fix github actions
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Fix github actions

---

.github/workflows/build.yml

Fixes #
Worked here: https://github.com/gitpod-io/gitpod/actions/runs/5520744970/jobs/10067839642?pr=18234
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[gha] Docker login for previewctl

---

.github/workflows/preview-env-delete.yml

gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Add missing Job needs

---

operations/observability/mixins/meta/rules/server.yaml

This excludes the `640` error code from the `JsonRpcApiErrorRates` alert, as we use it to indicate if logs are ready or not on a build, rather than being a typical 5xx error.
Context in this [alert thread](https://gitpod.slack.com/archives/C01TNS8EVQT/p1689107194325519).
Fixes #
You can preview the query [here](https://gitpoddedicatedprod.grafana.net/explore?left=%7B%22datasource%22:%22grafanacloud-prom%22,%22queries%22:%5B%7B%22datasource%22:%22grafanacloud-gitpoddedicatedprod-prom%22,%22expr%22:%22sum%28rate%28gitpod_server_api_calls_total%7BstatusCode%21~%5C%222.%2A%7C3.%2A%7C4.%2A%7C640%5C%22%7D%5B5m%5D%29%29%20by%20%28cluster%29%20%2F%20sum%28rate%28gitpod_server_api_calls_total%5B5m%5D%29%29%20by%20%28cluster%29%20%3E%200.04%22,%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22range …

ignore 640 error codes

---

components/ws-manager-bridge/src/app-cluster-instance-controller.ts
components/ws-manager-bridge/src/bridge-controller.ts
components/ws-manager-bridge/src/cluster-service-server.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[ws-man-bridge] Refactor constructors and cleanup deps

---

components/server/src/workspace/workspace-starter.ts

Related to  https://www.gitpodstatus.com/incidents/86797qj4xnfj
Related to ENG-470
Resolve workspace which are not successful are logged [like so](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-07-18T20:47:20.653435338Z;duration=PT30M;lfeCustomFields=jsonPayload%252FserviceContext%252Fservice;query=--%20without%20protected_secrets%20enabled%0AjsonPayload.kubernetes.host%3D%22preview-kylos101-r084e4a319a%22%0A%22Resolve%20workspace%20was%20unsuccessful%22%0Atimestamp%3D%222023-07-18T20:47:20.653435338Z%22%0AinsertId%3D%221rjxhiaffuwkpn%22;summaryFields=jsonPayload%252Fseverity,jsonPayload%252FserviceContext%252Fservice:false:32:beginning?project=gitpod-core-dev).
<ul>
<li><b>🏷️ Name</b> - …

[server] warn when resolve image is unsuccessful

---

install/installer/pkg/components/cluster/certmanager.go

This PR adds back the support of SCMs using Custom CAs to Gitpod. The components will respect the custom CA provided as a secret in the clusters. The secret name is to be passed to Gitpod config in the following format:
```
customCACert:
kind: secret
name: <secretname>
```
The secret key should be of the name `ca.crt`
Fixes ENG-581
No
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

Support custom CA in trust-manager

---

components/ws-manager-api/go/crd/v1/workspace_types.go
components/ws-manager-mk2/controllers/subscriber_controller.go

Reverts gitpod-io/gitpod#18660

Revert "Filter subscriber reconciler events"

---

components/local-app/CHANGELOG.md
components/local-app/cmd/root.go

Add a changelog file with updates up to this day.
Contributes towards EXP-913.
Exactly

Gitpod CLI changelog

---

components/gitpod-db/src/team-db.spec.db.ts

Build on main is broken. This PR resolves the issue.
See `gitpod-db` tests are running ok.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

Fix team-db spec

---

operations/observability/mixins/cross-teams/dashboards/gitpod-overview.json

Adds a SSH Summary to the Gitpod Cloud dashboard (similar to Dedicated).
Related to ENG-1340 and ENG-1350
The metric has been allowed, view in explore [here](https://grafana.gitpod.io/explore?panes=%7B%2216v%22:%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22sum%20by%28cluster%29%20%28gitpod_ws_proxy_ssh_connection_count%29%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1).
Started two ssh connections, each from different terminals.
gitpod:summary
<details>
Run the build with werft …

[ws-proxy] add SSH Summary to overview dashboard

---

components/dashboard/src/AppNotifications.tsx

Updates the effective date of our latest privacy policy.
A part of https://github.com/gitpod-io/website/pull/4197.
<ul>
<li><b>🏷️ Name</b> - ft-pp-december</li>
<li><b>🔗 URL</b> - <a href="https://ft-pp-december.preview.gitpod-dev.com/workspaces" target="_blank">ft-pp-december.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - ft-pp-december-gha.22047</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernet …

Update privacy policy effective date

---

components/server/src/orgs/organization-service.ts

Fix joinOrg via invite link permission problem (using system user but not change runContext) which is introduced in https://github.com/gitpod-io/gitpod/pull/19311
iam doCreateSession already wrapped with system user runContext
Fixes #
- It can join an org via invite link https://hw-fix-org-join.preview.gitpod-dev.com/orgs/join?inviteId=81eca3b0-a015-4628-93f0-ffdb52fa8768
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
If …

[server] fix can not join org

---

install/installer/pkg/components/workspace/ide/constants.go

Removes `Search Feature request` and `Report issue` built-in commands
Fixes https://linear.app/gitpod/issue/EXP-1086
<ul>
<li><b>🏷️ Name</b> - jp-specified-lion</li>
<li><b>🔗 URL</b> - <a href="https://jp-specified-lion.preview.gitpod-dev.com/workspaces" target="_blank">jp-specified-lion.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - jp-specified-lion-gha.22356</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPa …

[code] Update code web

---

components/server/src/orgs/organization-service.ts

Removed mistakenly in PR https://github.com/gitpod-io/gitpod/pull/19311
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details> …

Add track event `team_joined` back

---

components/dashboard/src/app/AppLoading.tsx
components/dashboard/src/data/featureflag-query.ts
components/dashboard/src/data/organizations/orgs-query.ts
components/dashboard/src/hooks/use-user-loader.ts

Add tracing logging for hanging issue
Related https://linear.app/gitpod/issue/EXP-775
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

Add tracing logging for hanging issue

---

components/ws-manager-mk2/controllers/metrics.go
components/ws-manager-mk2/service/manager.go

[ws-manager-mk2] do not report workspace activity metrics if it not leader
Fixes #
after killing the leader pod, another leader pod start report activity metrics, NOTE: pending is because `disk-pressure` not related this PR
<ul>
<li><b>🏷️ Name</b> - pd-mutil-wav-metrics</li>
<li><b>🔗 URL</b> - <a href="https://pd-mutil-wav-metrics.preview.gitpod-dev.com/workspaces" target="_blank">pd-mutil-wav-metrics.preview.gitpod-dev.com/workspaces</a>.</li> …

[ws-manager-mk2] do not report workspace activity metrics if it not leader

---

components/server/src/workspace/workspace-starter.ts

This change adds a special case for handling `ALREADY_EXISTS` errors emitted on `WsManager.StartWorkspace`.
Before, we would go and try to start the same workspace on another cluster. Now, we don't do anything but deferring to the next cycle of the `workspace-start-controller`. This aims to avoid current cases where under bad timing conditions, we might create two instances (with the same `instanceId`) on different clusters.
Fixes EXP-1326
<ul>
<li><b>🏷️ Name</b> - gpl-1326-retry-ws</li>
<li><b>🔗 URL</b> - <a href="https://gpl-1326-retry-ws.preview.gitpod-dev.com/workspaces" target="_blank">gpl-1326-retry-ws.preview.gitpod-dev.com/workspaces</a>.</li> …

[workspace-starter] Fix re-start issue in case ws-manager emits ALREDY_EXISTS

---

WORKSPACE.yaml
install/installer/pkg/components/workspace/ide/constants.go

Update code fixing server cli bug
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[code] Update code

---

components/dashboard/src/AppNotifications.tsx

This pull request fixes the issue with the billing address error and introduces an action item to update the address. The error message now includes a link to update the details in the Stripe portal.
Fixes EXP-1307
See this (notification logic was modified to re-create the error)
https://github.com/gitpod-io/gitpod/assets/55068936/d1eaadfd-98f1-471b-844b-bc7a288bf3a4
<ul>
<li><b>🏷️ Name</b> - siddhant-e9395d75439</li>
<li><b>🔗 URL</b> - <a href="https://siddhant-e9395d75439.preview.gitpod-dev.com/workspaces" target="_blank">siddhant-e9395d75439.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38e …

fix: Invalid Billing address error

---

components/server/src/auth/generic-auth-provider.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[auth] Make error from SCM trusted

---

components/dashboard/src/data/prebuilds/prebuild-queries.ts
components/dashboard/src/prebuilds/configuration-input/Combobox.tsx
components/dashboard/src/prebuilds/configuration-input/ComboboxItem.tsx
components/dashboard/src/prebuilds/configuration-input/ComboboxSelectedItem.tsx
components/dashboard/src/prebuilds/configuration-input/ConfigurationInput.tsx
components/dashboard/src/prebuilds/list/PrebuildListItem.tsx
components/dashboard/src/prebuilds/list/PrebuildTable.tsx
components/dashboard/src/repositories/detail/ConfigurationSettingsField.tsx
components/dashboard/src/repositories/detail/general/ConfigurationName.tsx
components/dashboard/src/repositories/detail/general/RemoveConfiguration.tsx
components/dashboard/src/repositories/detail/general/RemoveConfigurationModal.tsx
components/dashboard/src/repositories/detail/prebuilds/PrebuildDetailPage.tsx

Adds some minor design tweaks to the configuration input and improves the copy on the configuration remove modal.
| <img width="394" alt="image" src="https://github.com/gitpod-io/gitpod/assets/29888641/67dab461-07df-4da6-a824-4a2db41b2833"> | <img width="394" alt="image" src="https://github.com/gitpod-io/gitpod/assets/29888641/9d73ba37-58c3-49dc-9a8d-c64c5d9b9e19"> | 
Fixes #
<ul>
<li><b>🏷️ Name</b> - ft-prebuild4907def04</li>
<li><b>🔗 URL</b> - <a href="https://ft-prebuild4907def04.preview.gitpod-dev.com/workspaces" target="_blank">ft-prebuild4907def04.preview.gitpod-dev.com/workspaces</a>.</li> …

Prebuild fixes v2

---

components/ide/jetbrains/backend-plugin/gradle-latest.properties
components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodMetricControlProvider.kt

This PR updates the Platform Version from JetBrains Backend Plugin (EAP) to the latest version.
<details>
3. Start a workspace using this repository: https://github.com/gitpod-samples/spring-petclinic
</details>
```release-note
NONE
```
_This PR was created automatically with GitHub Actions using [this](https://github.com/gitpod-io/gitpod/blob/main/.github/workflows/jetbrains-update-plugin-platform-template.yml) …

Update Platform Version of JetBrains Backend Plugin (EAP)

---

components/dashboard/src/menu/OrganizationSelector.tsx
components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
components/dashboard/src/prebuilds/list/PrebuildList.tsx
components/dashboard/src/repositories/coachmarks/MigrationCoachmark.tsx
components/dashboard/src/repositories/create/AddRepositoryModal.tsx
components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
components/dashboard/src/repositories/detail/ConfigurationDetailPrebuilds.tsx
components/dashboard/src/repositories/detail/general/RemoveConfiguration.tsx
components/dashboard/src/repositories/detail/prebuilds/PrebuildSettingsForm.tsx
components/dashboard/src/repositories/detail/variables/ConfigurationVariableList.tsx
components/dashboard/src/repositories/detail/workspaces/WorkpaceSizeOptions.tsx
components/dashboard/src/repositories/list/RepoListEmptyState.tsx
components/dashboard/src/repositories/list/RepositoryList.tsx
components/dashboard/src/repositories/list/RepositoryTable.tsx

Some copy updates
Fixes EXP-1357
Fixes EXP-1410
<ul>
<li><b>🏷️ Name</b> - ft-impo-re626893b339</li>
<li><b>🔗 URL</b> - <a href="https://ft-impo-re626893b339.preview.gitpod-dev.com/workspaces" target="_blank">ft-impo-re626893b339.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - ft-impo-repos-no-more-gha.23098</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-ft-impo-re626893b339% …

Imported repositories -> Repository settings

---

components/server/src/session-handler.ts

Fixes #
- https://gpl-fix-logout.preview.gitpod-dev.com/workspaces
- login, logout, login, logout, check cookies on every step
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` …

[api] Fix /api/logout

---

components/dashboard/src/AppNotifications.tsx
components/dashboard/src/hooks/use-user-loader.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[frontend] Smooth relogin

---

components/dashboard/src/AppNotifications.tsx

Instead of executing all calls at once, be more defensive, and check previous calls.
I noticed that for some customers, we did not change them back to billing strategy "other" after they cancelled their subscription... :roll_eyes: But even for those cases, this code does not emit as much errors as before (just one).
Fixes EXP-1393
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[dashboard] Be more defensive when constructing "invalida billing address" notifications

---

components/dashboard/src/components/RepositoryFinder.tsx
components/dashboard/src/data/git-providers/unified-repositories-search-query.test.ts
components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
components/dashboard/src/data/prebuilds/prebuild-queries.ts
components/dashboard/src/menu/OrganizationSelector.tsx
components/dashboard/src/prebuilds/list/PrebuildList.tsx
components/dashboard/src/prebuilds/list/PrebuildListEmptyState.tsx
components/dashboard/src/prebuilds/list/PrebuildTable.tsx
components/dashboard/src/prebuilds/list/RunPrebuildModal.tsx
components/server/src/workspace/workspace-factory.ts

Fixes EXP-1374
<ul>
<li><b>🏷️ Name</b> - ft-rerun-prebuild</li>
<li><b>🔗 URL</b> - <a href="https://ft-rerun-prebuild.preview.gitpod-dev.com/workspaces" target="_blank">ft-rerun-prebuild.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - ft-rerun-prebuild-gha.23132</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-ft-rerun-prebuild%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPa …

Manually rerun prebuilds

---

WORKSPACE.yaml
install/installer/pkg/components/workspace/ide/constants.go

Update code to 1.87.0
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[code] Update code to 1.87.0

---

components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx

Fixes EXP-1417
https://hw-exp-1417.preview.gitpod-dev.com/workspaces
- To make persist toast easier: run dashboard with `start-local` and comment code below
- Start a failed prebuild
- Click `Rerun prebuild` it should dismiss toast
- Click Back button on breadcrumb, toast should dismiss
<ul>
<li><b>🏷️ Name</b> - hw-exp-1417</li>
<li><b>🔗 URL</b> - <a href="https://hw-exp-1417.preview.gitpod-dev.com/workspaces" target="_blank">hw-exp-1417.preview.gitpod-dev.com/workspaces</a>.</li> …

Dismiss persisted toast on prebuild detail page

---

components/ide-service-api/go/config/ideconfig.go
components/ide-service-api/go/ide_grpc.pb.go
components/ide-service-api/typescript/src/ide.pb.ts
components/ide-service/example-ide-config.json
components/ide-service/pkg/server/server.go
components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_invalid_version.golden
components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_invalid_version.json
components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_valid_version.golden
components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_valid_version.json

Add ide versions in ide-service
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Add ide versions in ide-service

---

components/server/src/user/token-provider.ts
components/server/src/user/token-service.ts
components/server/src/workspace/workspace-starter.ts

Do stuff that fixes other stuff
Fixes [#2339](https://gitpodsupport.zendesk.com/agent/tickets/2339)
<ul>
<li><b>🏷️ Name</b> - ft-force-rcf7ce0ba56</li>
<li><b>🔗 URL</b> - <a href="https://ft-force-rcf7ce0ba56.preview.gitpod-dev.com/workspaces" target="_blank">ft-force-rcf7ce0ba56.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - ft-force-refresh-ws-access-tokens-gha.24218</li> …

Force refresh workspace git access tokens

---

components/dashboard/src/workspaces/CreateWorkspacePage.tsx

Fixes [[internal chat](https://gitpod.slack.com/archives/C05H5UQBW6Q/p1713625490440099?thread_ts=1713540595.679169&cid=C05H5UQBW6Q)]
- Access preview env with https://hw-fix-autostart.preview.gitpod-dev.com/new/?autostart=true#https://github.com/gitpod-io/empty
- It should start workspace
<ul>
<li><b>🏷️ Name</b> - hw-fix-autostart</li>
<li><b>🔗 URL</b> - <a href="https://hw-fix-autostart.preview.gitpod-dev.com/workspaces" target="_blank">hw-fix-autostart.preview.gitpod-dev.com/workspaces</a>.</li> …

Fix autostart always false

---

README.md

See [Internal conversation](https://gitpod.slack.com/archives/C046Z4BBP2N/p1672905361077039)
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

✨ revamp product readme

---

components/ws-daemon/pkg/container/config.go
components/ws-daemon/pkg/container/containerd.go
components/ws-daemon/pkg/daemon/config.go
install/installer/pkg/components/ws-daemon/configmap.go

Reverts gitpod-io/gitpod#19661

Revert "[ws-daemon] Change readiness behavior to wait for registry-facade"

---

components/ws-proxy/pkg/proxy/routes.go
components/ws-proxy/pkg/proxy/routes_test.go

Fixes EXP-1841
- https://gitpod.slack.com/archives/C070SUJKYTV/p1714120489009339?thread_ts=1714119270.348569&cid=C070SUJKYTV
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[ws-proxy] Tighten cookie filter

---

.github/actions/deploy-gitpod/metadata.yml
.github/workflows/build.yml
.github/workflows/preview-env-check-regressions.yml
.github/workflows/workspace-integration-tests.yml

[github action] fix missing inputs

[github action] fix missing inputs

---

.github/workflows/build.yml
.github/workflows/ide-integration-tests.yml

[github-action] fix IDE integration test
Fixes [internal chat](https://gitpod.slack.com/archives/C02F9LQU4DR/p1714376247920669?thread_ts=1714212005.468269&cid=C02F9LQU4DR)
<ul>
<li><b>🏷️ Name</b> - pd-fix-ide-jb-test</li>
<li><b>🔗 URL</b> - <a href="https://pd-fix-ide-jb-test.preview.gitpod-dev.com/workspaces" target="_blank">pd-fix-ide-jb-test.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - pd-fix-ide-jb-test-gha.24798</li> …

[github-action] fix IDE integration test

---

components/dashboard/src/user-context.tsx

Context: EXP-1842
<ul>
<li><b>🏷️ Name</b> - gpl-test-cookie</li>
<li><b>🔗 URL</b> - <a href="https://gpl-test-cookie.preview.gitpod-dev.com/workspaces" target="_blank">gpl-test-cookie.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - gpl-test-cookie-gha.24794</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-gpl-test-cookie%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.s …

[dashboard] Check JWT token every 5 mins

---

WORKSPACE.yaml

Update docker compose for gen111
Related to ENT-13
Start a workspace in the preview environment from https://github.com/gitpod-demos/voting-app
<ul>
<li><b>🏷️ Name</b> - kylos101-gen111</li>
<li><b>🔗 URL</b> - <a href="https://kylos101-gen111.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-gen111.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - kylos101-gen111-gha.24834</li> …

[workspace cluster] update docker compose for gen111

---

components/ws-manager-api/go/crd/v1/workspace_types.go
components/ws-manager-mk2/controllers/status.go

Avoid bumping the LastTransitionTime of the WorkspaceRunningCondition on every reconciler run by only updating it if the status changed. This is a pattern we seem to be using for all other conditions as well.
Fixes ENT-48
- IDK, need to ask Thomas
<ul>
<li><b>🏷️ Name</b> - gpl-48-sta470ba46621</li>
<li><b>🔗 URL</b> - <a href="https://gpl-48-sta470ba46621.preview.gitpod-dev.com/workspaces" target="_blank">gpl-48-sta470ba46621.preview.gitpod-dev.com/workspaces</a>.</li> …

[ws-manager-mk2] Make WorkspaceRunningCondition.LastTransitionTime stable

---

WORKSPACE.yaml

Build code `1.89.0`
<ul>
<li><b>🏷️ Name</b> - hw-1890</li>
<li><b>🔗 URL</b> - <a href="https://hw-1890.preview.gitpod-dev.com/workspaces" target="_blank">hw-1890.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-1890-gha.24972</li> …

[code] build stable code `1.89.0`

---

components/server/src/workspace/workspace-starter.ts

This reduces the number of times we are asking for a new access token during workspace starts. Before we would create a new access token for _every_ run of the workspace start controller (as often as every 10s).
Now we only do that if the workspace is not created on a ws-manager, yet.
For GitHub/Gitlab this has no effect. But BitBucket seems to invalidate all prior existing access tokens on renewal, leading to broken behavior.
Related to: ENT-4
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
<summary>Preview Environment / …

[server] Don't ask for new access token if workspace is already starting

---

.github/workflows/jetbrains-update-plugin-platform-template.yml
.github/workflows/jetbrains-updates.yml

Fixes [[internal chat](https://gitpod.slack.com/archives/C02F9LQU4DR/p1715268247931849?thread_ts=1715267777.377389&cid=C02F9LQU4DR)]
✅  PR https://github.com/gitpod-io/gitpod/pull/19723 has been force pushed with action https://github.com/gitpod-io/gitpod/actions/runs/9020163004
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only if you're really …

Upgrade gha `create-pull-request` to `v6`

---

components/dashboard/src/components/forms/CheckboxInputField.tsx
components/dashboard/src/onboarding/OnboardingStep.tsx
components/dashboard/src/onboarding/StepOrgInfo.tsx
components/dashboard/src/onboarding/exploration-reasons.ts
components/dashboard/src/onboarding/signup-goals.ts

Check linked issue for detailed changes in Product onboarding form.
Fixes OPM-591
- Open preview environment & Login
- See onboarding form :eyes:
<ul>
<li><b>🏷️ Name</b> - siddhant-o2f914d60f0</li>
<li><b>🔗 URL</b> - <a href="https://siddhant-o2f914d60f0.preview.gitpod-dev.com/workspaces" target="_blank">siddhant-o2f914d60f0.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - siddhant-opm-591-update-copy-on-in-product-onboarding-form-gha.25290</li> …

Improve product onboarding form

---

components/ide/jetbrains/image/gha-update-image/lib/pin-version.ts
install/installer/pkg/components/ide-service/ide-configmap.json

- Update GHA script to make sure latest pinned version up-to-date always
A follow up PR of https://github.com/gitpod-io/gitpod/pull/19751
Fixes #
- Smoke test updated IDEs, they should work like before
<ul>
<li><b>🏷️ Name</b> - hw-jb-launcher</li>
<li><b>🔗 URL</b> - <a href="https://hw-jb-launcher.preview.gitpod-dev.com/workspaces" target="_blank">hw-jb-launcher.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-jb-launcher-gha.25288</li>
<li><b>🗒️ …

Update JetBrains launcher to latest version

---

.github/workflows/code-build.yaml
.github/workflows/code-updates.yml
components/ide/code/gha-update-image/check-code-build.ts
components/ide/code/gha-update-image/index.ts
components/ide/code/gha-update-image/lib/common.ts

Fixes #
No need to test, see https://github.com/gitpod-io/gitpod/pull/19758
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Fix code GitHub actions

---

components/dashboard/src/app/AppRoutes.tsx
components/dashboard/src/components/PillLabel.tsx
components/dashboard/src/components/podkit/buttons/LinkButton.tsx
components/dashboard/src/teams/TeamPolicies.tsx
components/dashboard/src/teams/TeamSettings.tsx

Related & For #19788 (see base branch)
Bisects the General settings to General + Policies 
Fixes OPM-608
Fixes OPM-607
Fixes OPM-611
<ul>
<li><b>🏷️ Name</b> - siddhant-ofe0cb46cdd</li>
<li><b>🔗 URL</b> - <a href="https://siddhant-ofe0cb46cdd.preview.gitpod-dev.com/workspaces" target="_blank">siddhant-ofe0cb46cdd.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - siddhant-opm-607-general-gha.25546</li> …

[Organization settings] Bisect General settings

---

components/server/src/authorization/spicedb-authorizer.ts

The goal here is to avoid large error spikes due to DEADLINE_EXCEEDED we see when rolling out spicedb changes.
All API calls should be idempotent, so the retry should be safe. 
Fixes ENT-196
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[server] SpiceDB: try up to 3 times not only for INTERNAL, but also DEADLINE_EXCEEDED

---

.devcontainer/Dockerfile

[devcontainer] fix aarch protoc

[devcontainer] fix aarch protoc

---

README.md
components/public-api-server/pkg/oidc/service.go
components/public-api-server/pkg/oidc/service_test.go

Fixes ENT-214
- Open preview env
- Login with SSO https://gitlab.gitpod-dev.com/ and it should work
- Code should not break old logic
<ul>
<li><b>🏷️ Name</b> - hw-gitlab</li>
<li><b>🔗 URL</b> - <a href="https://hw-gitlab.preview.gitpod-dev.com/workspaces" target="_blank">hw-gitlab.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-gitlab-gha.25695</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernete …

Bring more compatibility to OIDC verification

---

components/server/src/api/server.ts

I can't reproduce this in the preview, so not :100: sure this is enough to fix the issue. But the change is good anyway, and safe to deploy. :+1: 
Fixes ENT-232
<ul>
<li><b>🏷️ Name</b> - gpl-232-waf5b9e82d01</li>
<li><b>🔗 URL</b> - <a href="https://gpl-232-waf5b9e82d01.preview.gitpod-dev.com/workspaces" target="_blank">gpl-232-waf5b9e82d01.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - gpl-232-watch-prebuild-gha.25791</li> …

[server] API: Ignore write-after-close error

---

components/server/src/jobs/cap-git-status.ts

To help investigate why it's not behaving as expected.
Related: ENT-210
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] CapGitStatus: Log instanceIds of capped instances

---

components/server/src/workspace/workspace-starter.ts

The feature flag has been rolled out to all installations for some time now and looking fine. We can remove it now, as well as the old code.
Fixes ENT-179
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. …

[server] Drop feature flag workspace_start_new and related code

---

components/proxy/conf/Caddyfile

Reverts gitpod-io/gitpod#19877

Revert " [proxy] enable metrics for Caddy"

---

install/installer/pkg/components/ide-service/ide-configmap.json

Latest version is queried by command below
```
docker run --rm eu.gcr.io/gitpod-core-dev/build/versions:main-gha.26230 cat /versions.yaml | yq r -
```
Fixes [internal chat](https://gitpod.slack.com/archives/C04JEP60Q9X/p1718173349919249?thread_ts=1718093362.799819&cid=C04JEP60Q9X)
<ul>
<li><b>🏷️ Name</b> - hw-jb-launcher</li>
<li><b>🔗 URL</b> - <a href="https://hw-jb-launcher.preview.gitpod-dev.com/workspaces" target="_blank">hw-jb-launcher.preview.gitpod-dev.com/workspaces</a>.</li> …

Update all jb-launcher to latest version

---

WORKSPACE.yaml

Build code version `1.90.1` (`1c441528fd93c8521c585a91511b3b8d99f9f376`)
<ul> …

[VS Code Browser] Build stable code `1.90.1`

---

.github/workflows/code-updates.yml

Improve GHA as it keep execing for every main commit's build action

Improve code-updates GHA

---

components/ide-service/pkg/server/ideconfig.go

Fixes #
Once build is passed
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Remove unnecessary debug log

---

WORKSPACE.yaml

Build code version `1.90.2` (`dc0e7217f8f11d3249dcd2cd1d2152a2fdb45f3e`)
<ul> …

[VS Code Browser] Build stable code `1.90.2`

---

components/supervisor/pkg/supervisor/supervisor.go

Fixes a bug where the task service waitgroup would hang on forever.
Fixes an issue [reported](https://gitpod.slack.com/archives/C05LCNZKMB3/p1718957665264759) on Slack
<ul>
<li><b>🏷️ Name</b> - ft-supervi0d2ffdc696</li>
<li><b>🔗 URL</b> - <a href="https://ft-supervi0d2ffdc696.preview.gitpod-dev.com/workspaces" target="_blank">ft-supervi0d2ffdc696.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - ft-supervisor-stuck-taskservice-gha.26784</li>
<li><b>🗒️ …

Add timeout for taskservice in supervisor

---

components/server/src/audit/AuditLogService.ts

Remove sensitive information from audit logs
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[audit logs] scrub values

---

components/server/src/workspace/workspace-starter.ts

Fixes a race between the actual prebuild status and the inferred initial prebuild status.
Fixes ENT-318
https://ft-fix-pre1f4cf5cf81.preview.gitpod-dev.com/workspaces
Start a workspace and keep an eye on its status. It should never go back from Building to Queued. This is best observed on repos for which we have an image already built.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

Do not send initial `queued` prebuild phase from workspace starter

---

components/node-labeler/cmd/metrics.go
components/node-labeler/cmd/run.go
components/node-labeler/go.mod
components/node-labeler/go.sum

Reverts gitpod-io/gitpod#19909
This could potentially impact cluster autoscale computing

Revert "[node-label] remove node label when pod became unhealthy"

---

components/server/src/session-handler.spec.db.ts
components/server/src/session-handler.ts

Context: https://github.com/gitpod-io/gitpod/pull/19973
<ul>
<li><b>🏷️ Name</b> - gpl-stop-migration</li>
<li><b>🔗 URL</b> - <a href="https://gpl-stop-migration.preview.gitpod-dev.com/workspaces" target="_blank">gpl-stop-migration.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - gpl-stop-migration-gha.27104</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-gpl-stop-migration%22% …

[server] Drop old cookie migration path

---

WORKSPACE.yaml

Build code version `1.91.0` (`a412ea75aad37c687932f897378d3076e311d534`)
**Extension Verification**
**Regular Smoke Tests**
<ul>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for …

[VS Code Browser] Build stable code `1.91.0`

---

components/ide-proxy/Dockerfile

A regular update to reflect the state upstream. As of this PR, we are pointing to https://github.com/open-vsx/publish-extensions/commit/a5957f7f8ab9a05d87e81467aa4375c17e8f10e5.

Update extension control manifest

---

.github/workflows/code-nightly.yml

As originally reported by @Siddhant-K-code [on Slack](https://gitpod.slack.com/archives/C032A46PWR0/p1720631431116749?thread_ts=1720629395.854819&cid=C032A46PWR0).

Fix code nightly workflow typo

---

components/public-api/typescript-common/fixtures/toConfiguration_1.golden
components/public-api/typescript-common/fixtures/toConfiguration_2.golden
components/public-api/typescript-common/fixtures/toPrebuildSettings_1.golden
components/public-api/typescript-common/fixtures/toPrebuildSettings_2.golden

#20006 merged without the tests passing, so it did not produce a release.
Follow-up from #20037 
ENT-435
Let CI pass this time...

Update activity-based prebuilds tests

---

components/server/src/billing/entitlement-service.ts

Introduces `disable_set_timeout` (boolean) feature flag that allow to set whether users can change/extend the timeouts of a workspace when in in PAYG mode.
Fixes https://linear.app/gitpod/issue/ENT-447/org-wide-timeout-default
The feature flag `disabled_set_timeout` is set to `true` for the preview env.
Test: 
- Start a workspace and try to change the timeout. You'll see an error message.
<ul>
<li><b>🏷️ Name</b> - se-org-widc1faf03bd1</li>
<li><b>🔗 URL</b> - <a href="https://se-org-widc1faf03bd1.preview.gitpod-dev.com/workspaces" target="_blank">se-org-widc1faf03bd1.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce8 …

[server] allow configure timeouts via featureflag

---

components/dashboard/src/data/current-user/update-mutation.ts

Fixes ENT-484
- Try with preview env and append url with `?onboarding=force` to force enable onboarding
- Update answers
- Repeat step 1 and 2 to do another round of update
- Answers with type array should be uniq before update
<ul>
<li><b>🏷️ Name</b> - hw-onboarding-fix</li>
<li><b>🔗 URL</b> - <a href="https://hw-onboarding-fix.preview.gitpod-dev.com/workspaces" target="_blank">hw-onboarding-fix.preview.gitpod-dev.com/workspaces</a>.</li> …

Uniq onboarding answers before update

---

components/ws-manager-bridge/src/bridge.ts

Fixes ENT-450
- trigger a prebuild, and verify that it works and the UI on the PrebuildDetailsPage is properly updated with the "Duration" once it's stopped
<ul>
<li><b>🏷️ Name</b> - gpl-450-stoppedtime</li>
<li><b>🔗 URL</b> - <a href="https://gpl-450-stoppedtime.preview.gitpod-dev.com/workspaces" target="_blank">gpl-450-stoppedtime.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - gpl-450-stoppedtime-gha.27603</li> …

[ws-manager-bridge] Persist before publishing any update to maintain consistency guarantees

---

components/gitpod-db/src/typeorm/entity/db-audit-log.ts
components/gitpod-db/src/typeorm/transformer.ts
components/gitpod-protocol/src/util/stringify.ts
components/public-api/typescript-common/src/public-api-converter.ts
components/server/src/api/server.ts
components/server/src/audit/AuditLogService.spec.db.ts
components/server/src/audit/AuditLogService.ts
components/server/src/websocket/websocket-connection-manager.ts

Fixes ENT-501
- call listWorkspaceSessions API like described [here](https://github.com/gitpod-io/gitpod/pull/19917#issuecomment-2186569397)
- see how it does not throw an error in the server logs
<ul>
<li><b>🏷️ Name</b> - gpl-fix-pa732bb07b4c</li>
<li><b>🔗 URL</b> - <a href="https://gpl-fix-pa732bb07b4c.preview.gitpod-dev.com/workspaces" target="_blank">gpl-fix-pa732bb07b4c.preview.gitpod-dev.com/workspaces</a>.</li> …

[audit log] Fix audit log persistence

---

components/ws-manager-mk2/controllers/metrics.go

Fixes ENT-519
[Refer to this log entry](https://console.cloud.google.com/logs/query;cursorTimestamp=2024-07-23T12:31:00.204394092Z;duration=PT15M;lfeCustomFields=jsonPayload%252FserviceContext%252Fservice;query=--%20without%20protected_secrets%20enabled%0AjsonPayload.kubernetes.host%3D%22preview-kylos101-mcfb02d96e8%22%0A--%20jsonPayload.workspaceId%3D%22gitpodio-templatepython-26ftql9iecs%22%0A%22workspace%20stop%20reason%22%0Atimestamp%3D%222024-07-23T12:31:00.204394092Z%22%0AinsertId%3D%221u2bhczfa7na8p%22;summaryFields=jsonPayload%252Fseverity,jsonPayload%252FserviceContext%252Fservice,jsonPayload%252Freason:false:32:beginning?project=gitpod-dev-preview).
<ul>
<li><b>🏷️ Name</b> - kylos101-mcfb02d96e8</li>
<li><b>🔗 …

[ws-manager-mk2] log the stop reason

---

WORKSPACE.yaml

Build code version `1.92.0` (`6c693cbd752da3e2b2f15517f02efdcfa87ce3c1`)
<ul> …

[VS Code Browser] Build stable code `1.92.0`

---

.github/workflows/code-nightly.yml

Reverts gitpod-io/gitpod#20070

Switch code nightly job back

---

docs/README.md

Fixes https://github.com/gitpod-io/gitpod/issues/20085
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[readme/docs] address internal docs repository

---

components/ws-daemon/pkg/iws/iws.go

When NFS shares are mounted to workspaces their file permissions look correct on the host system (the mount is owned by 133332, the id of the gitpod user in the workspace). However in the workspace the same mount is owned by nobody. Other files outside of the nfs share are owned by 133332 as well, yet show correctly gitpod as the user. We  chown the root of the share explicitly in order to set the correct permissions.
Fixes ENT-647
- Create NFS share (e.g. in AWS)
- Start workspace
- Mount NFS share
- Try to write to the share
gitpod:summary
<details>
</details>
<details>
</details>
<details> …

Fix file permissions for NFS shares

---

components/ide/jetbrains/launcher/main.go

Fixes ENT-654
- Create a repository with https://github.com/mustard-mh/test/blob/repro/ENT-654/.gitpod.yml
- Trigger a prebuild for branch repro/ENT-654
- Start workspace with repository created on step 1
- Workspace should be able to start with IDEA 2024.2
✅ <img width="1321" alt="image" src="https://github.com/user-attachments/assets/25fc276d-d734-4973-8b2b-fcf4ce54ec7a">
<ul>
<li><b>🏷️ Name</b> - hw-fix-jb</li>
<li><b>🔗 URL</b> - <a href="https://hw-fix-jb.preview.gitpod-dev.com/workspaces" target="_blank">hw-fix-jb.preview.gitpod-dev.com/workspaces</a>.</li> …

Fix JetBrains backend plugin not up-to-date for prebuilds

---

WORKSPACE.yaml

Reverts gitpod-io/gitpod#20124  [[internal chat](https://gitpod.slack.com/archives/C045J13P8A1/p1723743882330969)]
To avoid upgrade PR been created

Revert "[VS Code Browser] Build stable code `1.92.2`"

---

components/dashboard/src/dedicated-setup/SSOSetupStep.tsx

The previous link wasn't wroking.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Update outdated SSO docs link for Enterprise onboarding

---

components/server/src/orgs/organization-service.ts

Make sure newly joined members on paid orgs aren't forced to verify using their phones.
Fixes https://gitpod.slack.com/archives/C072CPN9EP4/p1724933632658269
1. Execute this against the database and fill in your username
```bash
kubectl port-forward statefulset/mysql 3306
export DB_USERNAME=$(kubectl get secrets mysql -o jsonpath="{.data.username}" | base64 -d)
export DB_PASSWORD=$(kubectl get secrets mysql -o jsonpath="{.data.password}" | base64 -d)
mysql -u$DB_USERNAME -p$DB_PASSWORD -h 127.0.0.1 gitpod
```
```sql
UPDATE d_b_user SET lastVerificationTime = '' WHERE name = '<username>';
```
```bash
kubectl rollout restart deployment/server deployment/redis
```
2. Try to start a workspace, you should not be able to 
3. [Join my org](https://ft-fix-new57386352ca.preview.gitpod-dev.com/orgs/ …

Verify new organization joinees

---

.github/workflows/code-nightly.yml

Reverts gitpod-io/gitpod#20169

Revert "Switch code nightly job"

---

components/ws-proxy/go.mod
components/ws-proxy/go.sum
components/ws-proxy/pkg/config/config.go
components/ws-proxy/pkg/proxy/config.go
components/ws-proxy/pkg/proxy/routes.go
components/ws-proxy/pkg/proxy/routes_test.go

Fixes ENT-736
- Start a workspace in preview env
- It can access workspace via VS Code Browser
- Check ports visibility is working properly
<ul>
<li><b>🏷️ Name</b> - hw-remove-proxy-cors</li>
<li><b>🔗 URL</b> - <a href="https://hw-remove-proxy-cors.preview.gitpod-dev.com/workspaces" target="_blank">hw-remove-proxy-cors.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-remove-proxy-cors-gha.28726</li> …

[ws-proxy] remove cors settings

---

components/ide/gha-update-image/lib/jb-update-platform-version.ts

Fixes ENT-786
- Open this PR with Gitpod, and exec commands below
```
cd /workspace/gitpod/components/ide/gha-update-image
npm i -g bun && yarn
bun run index-jb-platform-update.ts --task=2
bun run index-jb-platform-update.ts --task=3
```
- Check `gradle-<version>.protperties` files changes
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only if …

[gha] fix JetBrains Gateway upgrade script

---

components/server/src/analytics-controller.ts

This pull request adds functionality to set a hashed user ID cookie in the analytics controller service. The hashed user ID is generated using the MD5 algorithm and is stored in a cookie named "gitpod_hashed_user_id". The cookie has a one-year expiration time, is HTTP-only, secure, and has a lax same-site policy. This enhancement improves user identification and tracking in the analytics system.
Fixes ENT-801
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

Add hashed user ID cookie in analytics controller service

---

components/dashboard/src/AppNotifications.tsx

Our [Privacy policy](https://www.gitpod.io/privacy) got updated. This PR makes sure users are properly notified about that.

Privacy Policy update notification

---

components/dashboard/src/AppNotifications.tsx

Reverts gitpod-io/gitpod#20331
**MERGE at Nov 6, 2024 -- 12pm CET**
/hold

Revert "Add Flex webinar notification banner" & Bring back AWS re:Invent banner

---

dev/preview/infrastructure/modules/gce/variables.tf
dev/preview/infrastructure/variables.tf

Set preview env image to match gen117
Related to CLC-927
Start a workspace in preview (see below comments)
<ul>
<li><b>🏷️ Name</b> - kylos101-dnfey3i1go</li>
<li><b>🔗 URL</b> - <a href="https://kylos101-dnfey3i1go.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-dnfey3i1go.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - kylos101-DnFEy3i1go-gha.30326</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayl …

[preview] update to gen117 image

---

.github/workflows/configcat.yml

Updated to `v2` ([docs ref](https://github.com/configcat/scan-repository))

CI: use latest Configcat GHA

---

WORKSPACE.yaml

Build code version `1.97.2` (`e81ab749002377cf40b1551661a6b80725141ff0`)
<ul> …

[VS Code Browser] Build stable code `1.97.2`

---

components/dashboard/src/workspaces/Workspaces.tsx

Fixes typos and a missing space where we render conditionally.
Fixes https://gitpod.slack.com/archives/C071G5TTS49/p1741632738642939

[dashboard] fix getting started card copy

---

yarn.lock

to fix some CVEs
fixes
```JSON
{"cve":"CVE-2023-36665","package":"protobufjs","version":"7.2.4"}
```

Gentle protobufjs bump

---

README.md

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[docs] Remove empty line

---

README.md

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Minimal change

---

components/dashboard/src/workspaces/Workspaces.tsx

Fixes a regression from #20766 that hid the workspaces page content for any users not on Enterprise.

[dashboard] fix workspaces list rendering

---

yarn.lock

[server] upgrade packages
Fixes CLC-1620
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] upgrade packages
