gitpod-io/gitpod

install/installer/pkg/components/usage/configmap.go, install/installer/pkg/components/usage/configmap_test.go
The default config prevented from actually disabling the controller in the US.
We already set it to disabled in https://github.com/gitpod-io/ops/blob/main/deploy/production/meta-us02/app/installer-config.yaml#L168, however when the config is parsed, it's treated as unset and the default from the installer is used.
We remove the default to prevent this behaviour.
Fixes #
Unit tests
```release-note
NONE
```
=> [usage] Remove default controller schedule of 1h

operations/observability/mixins/platform/rules/kubernetes/kubernetes.yaml
This PR adds an annotation to the alerts `KubeCPUOvercommit` and `KubeMemoryOvercommit` so we can make the investigation faster. Such annotation will be transformed into slack buttons by alertsmanager 🙂 
Fixes #
```release-note
NONE
```
=> Add dashboard URL for KubeCPUOvercommit and KubeMemoryOvercommit

.werft/jobs/build/helm/values.tracing.yaml, .werft/observability/monitoring-satellite.ts
In https://github.com/gitpod-io/gitpod/pull/12626, I've configured preview environments to always use our CLI installer to install monitoring-satellite. In the process, I accidentally removed the configuration that sends traces from previews to Honeycomb.
This aims to fix that.
[Slack conversation](https://gitpod.slack.com/archives/C032A46PWR0/p1662652877057059)
* Create a preview from this PR
* Open a new workspace from the preview, just to generate a new trace
* [Go to honeycomb and see traces showing up for the preview](https://ui.honeycomb.io/gitpod/datasets/preview-environments/result/FNAkhZbeYeJ)
```release-note
NONE
```
=> Send traces from previews to Honeycomb

components/ws-manager-bridge/src/bridge.ts
Currently, when we fail to update a workspace instance in ws-manager-bridge, we report it once as a failure (in the `catch`), then again as a success (in the `finally`, which always gets called regardless of whether errors happened):
https://github.com/gitpod-io/gitpod/blob/7a0efe9999c3cc31ffc63c79fe9d8334620bee37/components/ws-manager-bridge/src/bridge.ts#L190-L217
I think it would make more sense to report errors as errors, and only successes as successes.
Fixes #
```release-note
NONE
```
=> [ws-manager-bridge] Don't report workspace instance update failures as both a failure and a success

components/usage/pkg/apiv1/billing.go, components/usage/pkg/stripe/stripe.go
1. We need to debit the credit amount in usage, not credit the credit amount
2. We shouldn't try to update usage to negative values. This doesn't make sense (and isn't allowed by Stripe). Instead we set it to 0. This happens when a customer has for example bought a bundle or overpaid on an invoice.
* Depends on https://github.com/gitpod-io/gitpod/pull/12755
```release-note
NONE
```
=> [stripe] Finalized invoce debits, do not set credits to negative when updating

.gitpod.yml
This PR removes bradlc.vscode-tailwindcss from the list of extensions that we install by default in our repo. The extension has for some time been displaying an error whenever we start a workspace:
I'm removing the extension to keep our workspace boots clean and tidy. If we want to re-add the extension we should resolve the issue.
Internal discussion [here](https://gitpod.slack.com/archives/C032A46PWR0/p1662451298450909).
No issue, just Friday TIdying
Open a new workspace. The error should not appear aynmore.
```release-note
NONE
```
N/A
=> Remove bradlc.vscode-tailwindcss from list of extensions

components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
Currently, we are tracking the duration of the [`handleStatusUpdate` span](https://github.com/gitpod-io/gitpod/blob/7a0efe9999c3cc31ffc63c79fe9d8334620bee37/components/ws-manager-bridge/src/bridge.ts#L227-L432), and storing it in the following buckets:
https://github.com/gitpod-io/gitpod/blob/43e526b1d63178f4de3bcbf31b6dc01d59611fd9/components/ws-manager-bridge/src/prometheus-metrics-exporter.ts#L80
- < 2 seconds
- < 4 seconds
- < 8 seconds
- < 16 seconds
- < 32 seconds
- < 64 seconds
- < 128 seconds
- < 256 seconds
- < +Infinity
However, most of the time, this span takes actually around 50ms:
Thus, all our measurements land in the very first "< 2 seconds" bucket, which is not very useful.
Instead, I propose that we store durations in the following buckets:
``` …
```
=> [ws-manager-bridge] Use more reasonable duration buckets for workspace instance updates

components/dashboard/src/admin/TeamDetail.tsx, components/dashboard/src/admin/UserDetail.tsx, components/gitpod-protocol/src/admin-protocol.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
Fixes #
- [signup](https://gpl-12674-bm.preview.gitpod-dev.com/workspaces)
- ping me for admin rights (or get them through DB)
- Search for you [user details page](https://gpl-12674-bm.preview.gitpod-dev.com/admin/users) and see that:
- BillingMode is displayed and shows "Chargebee"
- Chargebee stuff is displayed as well (credits, etc.)
- create a team starting with `Gitpod-xxx`
- Go back to User Details and see that:
- BillingMode is displayed and shows "usage-based"
- Chargebee related info and actions is gone
- go to your teams details page and see that:
- BillingMode is displayed and shows "usage-based"
```release-note
NONE
```
=> [Admin] Show BillingMode on Team-/UserDetails pages

components/usage/pkg/apiv1/usage.go
We need to use the same draft flags between ListUsage and ListUsageSummary, else the metadata about pagination does not match.
Fixes #
```release-note
NONE
```
=> [usage] Include drafts when listing usage summary

test/tests/workspace/contexts_test.go
The branch name will vary depending on the user name and other factors. And this logic is written in the server, so it is not tested in the workspace.
https://github.com/gitpod-io/gitpod/blob/45f13cf8e9214db664adc23a418e53d92364fbb7/components/server/src/workspace/context-parser.ts#L106-L121
Run the test
```release-note
NONE
```
=> test: Workspace testing does not guarantee branch name creation

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/blobserve/deployment.go, install/installer/pkg/components/blobserve/networkpolicy.go
This PR move blobserve to `workload_ide` node, because traffic through `ide-proxy`
This PR also adjust blobserve network policy, in order to support some edge case see [internal discuss](https://gitpod.slack.com/archives/C020VCB0U5A/p1661964821598319?thread_ts=1661352400.563409&cid=C020VCB0U5A)
Fixes #12366
```release-note
NONE
```
=> [installer] change blobserve node to workload_ide

components/usage/pkg/apiv1/usage_test.go
adds a test for UsageService.ListUsage
Fixes #
```release-note
NONE
```
=> [usage] added a test for ListUsage

.werft/observability/install-satellite.sh, .werft/observability/manifests/monitoring-satellite.yaml, .werft/observability/monitoring-satellite.ts
Fixes https://github.com/gitpod-io/ops/issues/3585
```bash
werft run github -j .werft/build.yaml -a with-preview=true
```
https://werft.gitpod-dev.com/job/gitpod-custom-aa-obs-installer-ss.11 (fixed the popd issue with the last commit)
```bash
NAME                                 READY   STATUS    RESTARTS   AGE
alertmanager-main-0                  2/2     Running   0          38m
grafana-8dc9c7bb9-x5525              1/1     Running   0          2m20s
http-prober-867c755dd-drgkc          1/1     Running   0          38m
kube-state-metrics-876578749-4g8t2   3/3     Running   0          38m
kubescape-bdd7f8776-lkqlw            1/1     Running   0          38m
node-exporter-xnwlh                  2/2     Running   0          38m
prometheus-k8s-0                     2/2     Running   0 …
```
=> Install monitoring-satellite with obs-installer

components/dashboard/src/Pagination/getPagination.spec.ts, components/dashboard/src/Pagination/getPagination.ts
Fixes pagination, where the page next to current was not selectable.
Fixes #12804
```
cd components/dashboard
yarn test:unit getPagination
```
```release-note
NONE
```
=> [dashboard] (pagination) make sure next page is selectable

components/dashboard/src/components/BillingAccountSelector.tsx
Fixes #
```release-note
NONE
```
=> [dashboard] reenable attribution to personal account

.werft/build.yaml, .werft/jobs/build/job-config.ts
This PR contains a few improvements to Werft slices
- More granular slices for the "job preparation" phase. These are mostly interesting as they provide more detailed traces.
- Added a slice that contains information about what node the job was scheduled on. This can help when you're debugging caching issues as the docker layer caching is node dependant
- Pretty-printed the JSON configuration and "hid" it behind a "Expand to see the parsed configuration". This makes it less noisy visually, and more readable when you actually care about the contents of the config
No issue. Friday fun times.
Before
After
```release-note
NONE
```
N/A
=> Minor improvements to Werft slices

test/tests/components/ws-manager/tasks_test.go
Add missing PVC feature flag when testing against TestRegularWorkspaceTasks.
Fixes #12497
Run integration test
```release-note
None
```
None
=> workspace integration test: add missing PVC feature flag

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/cleanup-installer-tests.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/run-integration-tests.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile
This PR upgrade workspace-full image to `2022-09-07-02-19-02` in order to resolve `bash: vscode::add_settings: command not found` when you open a new terminal related https://github.com/gitpod-io/workspace-images/pull/922
Fixes #
1. open this branch in gitpod.io
2. start a new terminal, it should no `bash: vscode::add_settings: command not found` error anymore
```release-note
NONE
```
=> [dev] Update gitpod dev image

.werft/workspace-run-integration-tests.sh
Run the test
```release-note
NONE
```
=> Improve the script of integration test

operations/observability/mixins/cross-teams/dashboards.libsonnet, operations/observability/mixins/cross-teams/dashboards/gitpod-grpc-server.json
With our move towards a unified [(go) baseserver](https://github.com/gitpod-io/gitpod/tree/main/components/common-go/baseserver), we now also have a more standardized set of metrics for gRPC. This PR adds a generic gRPC Server dashboard.
The intention of this dashboard is to be composed into other dashboards. That is, it focuses on part of our stack but it is agnostic of any given component or deployment (cluster) model. It simply exposes metrics for grpc services and methods. This is desirable as we want to have fewer more general dashboards which we compose into more specific components and avoid always re-defining the same dashboards.
You can view this dashboard against staging [here](https://grafana.gitpod-staging.com/d/fDH4_QMVk/grpc-server)
Fixes #
```release-note
NONE
```
=> [dashboards] Add gRPC / Server dashboard

components/dashboard/src/start/VerifyModal.tsx
Following up from https://github.com/gitpod-io/gitpod/pull/12258, this will duplicate the link to support on the phone verification step when users are entering the mobile phone number, not just the verification code. The reasons behind this change:
1. We've gotten some from users in China that they are not able to use this feature using their mobile phone number. We're actively working on resolving this with the third-party service we're integrating for this feature, Twilio. See [relevant discussion](https://gitpod.slack.com/archives/C03QY10N9PZ/p1662551365578039) (internal). Cc @svenefftinge @securitymirco @KlasenK 
2. Future errors like this that prevent users from entering a mobile phone number will still end up in the same verification step, which currently doesn't include the link …
=> Add link to support on phone verification

components/usage-api/typescript/src/usage/v1/sugar.ts
Fix the `sugar.ts` file that wraps the usage component gRPC client for typescript clients.
Use a return value of the correct shape rather than explicitly casting an incorrect shape.
In particular avoid the use of `||` against an enum type that can be 0.
See https://github.com/gitpod-io/gitpod/pull/12767#issuecomment-1242053307 for the full context.
I really dislike these sugar files, they are an untested, handwritten layer over the generated gRPC client in which bugs like this can lurk. 
```release-note
NONE
```
=> [UBP] Fix usage gRPC `sugar.ts` file

components/dashboard/src/projects/NewProject.tsx
This will update the loading state when fetching repositories, and GitLab groups or GitHub orgs, based on the comment in https://github.com/gitpod-io/gitpod/issues/5075#issuecomment-1134456530, using the same pattern we use in fetching repository branches and prebuilds within a project.
Related to https://github.com/gitpod-io/gitpod/issues/5075
1. Try adding a new project
|-|-|
| <img width="1440" alt="Screenshot 2022-09-09 at 4 48 32 PM (2)" src="https://user-images.githubusercontent.com/120486/189366083-e5e65474-5cc5-40ba-b771-312a0ce85f1f.png"> | <img width="1440" alt="Screenshot 2022-09-09 at 4 48 44 PM (2)" src="https://user-images.githubusercontent.com/120486/189366089-50ccd605-1784-49d7-96c7-e3aeab0b81d9.png"> |
```release-note
Improve fetching repositories …
```
=> Improve fetching repositories loading state

.werft/jobs/build/installer/installer.ts, install/installer/.gitignore, install/installer/README.md, install/installer/cmd/config.go, install/installer/cmd/config_init.go, install/installer/cmd/init.go, install/installer/cmd/root.go, install/installer/example-config.yaml
Create a `config init` command and deprecate the `init` command.
The two commands are functionally identical, with the exception of the new command saving the file for you (the previous command just printed the output).
This is part of a major refactoring of the configuration so that it's simpler and just config generation. See #12319 for my notepad of how it'll look eventually.
Fixes #12678
Fixes #12847
Run `go run . config init` and check `gitpod.config.yaml`
```release-note
[installer]: create config command and deprecate init command
```
=> [installer]: create config command and deprecate init command

components/dashboard/src/App.tsx, components/dashboard/src/Menu.tsx, components/dashboard/src/Usage.tsx, components/dashboard/src/components/UsageView.tsx, components/dashboard/src/settings/settings.routes.ts, components/dashboard/src/teams/TeamUsage.tsx
This PR reuses the existing Usage page to show personal usage. 
First part of #12686 (adding the Usage page "as is")
🤷🏻 
No idea yet how to attribute personal account.
```release-note
Show personal Usage page.
```
=> Show personal Usage page

install/installer/leeway.Dockerfile
This reverts commit ceb75ebb61b9793158d7a904eaaf2fd7c0a07a0c to [unblock WebApp/IDE deployments](https://github.com/gitpod-io/ops/pull/4498#issuecomment-1243359823).
PR: https://github.com/gitpod-io/gitpod/pull/12834
Fixes #
```release-note
NONE
```
=> Revert "Improve layer caching by moving apk commands up"

components/ee/agent-smith/pkg/agent/agent.go
- Open a workspace that triggers an infringement rule
- Check agent-smith log. It should contains a new `CommandLine` field.
```release-note
NONE
```
=> [agent-smith] Add more details to the infringement

components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/user/stripe-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
Add a new `getStripePortalUrl` method to `server`'s JSON-RPC API.
The method generates a Stripe portal URL that is used during the billing signup flow for both teams and individual users - it replaces the existing `getStripePortalUrlForTeam` method which only worked for team signup.
1. Create a team called `Gitpod-xxx`
2. Sign the team up for UBP.
3. Create a new Stripe customer for your individual user:
```js
await window._gp.gitpodService.server.createOrUpdateStripeCustomerForUser("EUR")
```
3. Get the portal URL for the user:
```js
await window._gp.gitpodService.server.getStripePortalUrl("user:<your user id>")
```
Using the returned URL should take you to some Stripe UI.
```release-note
NONE
```
=> [UBP] Add `getStripePortalUrl` method to server

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/server/ide/configmap.go
since it's always built by main, otherwise it breaks latest JB in production
Fixes #
```release-note
NONE
```
=> [ide]: pin latest JB plugin version

components/content-service/pkg/layer/provider.go, components/supervisor/pkg/supervisor/supervisor.go
First, kudos to @jenting for catching this issue. :heart: 
What was happening is actually when using pvc and prebuilds, it would not know that workspace was open from prebuild, rendering prebuild useless (as it would do all the work that prebuild already done).
This PR fixes this. 
Fixes #12464 
Open regular workspace
Open PVC regular workspace
Open regular prebuild
Open PVC prebuild
```release-note
none
```
=> [pvc] fix prebuilds when using pvc

WORKSPACE.yaml, components/ide/code/leeway.Dockerfile, components/proxy/conf/Caddyfile, components/ws-proxy/pkg/proxy/pass.go, components/ws-proxy/pkg/proxy/routes.go, components/ws-proxy/pkg/proxy/workspacerouter.go, components/ws-proxy/pkg/proxy/workspacerouter_test.go
Adds vscode auth callback route
Fixes https://github.com/gitpod-io/gitpod/issues/12660
1. Open a workspace and install this test extension [gitpod-foo-0.0.58.zip](https://github.com/gitpod-io/gitpod/files/9538509/gitpod-foo-0.0.58.zip)
2. Update settings.json with `"gitpod.host": "https://jp-test-9.preview.gitpod-dev.com/"`
3. Run `Test FOO sign in` command
4. Check the callback page opens sucessfully, it says `You can close this page now`
5. On vscode tab login will fail, that's expected
6. Not required: If you want login to succeed, then go to this [branch](https://github.com/gitpod-io/gitpod/tree/jp/test-9) and change the redirect url to match your workspace, pointer [[1](https://github.com/gitpod-io/gitpod/commit/6b78c8c63f74956ebeba23c324f93159e41d0506)], wait for build, yeah that …
=> Adds vscode auth callback route

install/installer/cmd/config.go, install/installer/cmd/config_cluster.go, install/installer/cmd/config_cluster_shiftfs.go, install/installer/cmd/config_files.go, install/installer/cmd/config_files_containerd.go, install/installer/pkg/components/ws-daemon/daemonset.go, install/installer/pkg/config/v1/config.go, install/installer/pkg/containerd/amazon_linux.go, install/installer/pkg/containerd/k3s.go, install/installer/pkg/containerd/location.go, install/installer/pkg/shiftfs/constants.go, install/installer/pkg/shiftfs/job.go
This creates two new commands - `config cluster shiftfs` and `config files containerd` - designed to autodetect whether ShiftFS is supported and the location of the containerd files.
The ShiftFS command reuses the init container in `ws-daemon`.
The command `config cluster` and `config files` have been designed so that future commands can be written. The `config cluster` is designed for commands that deploy a Kubernetes resource to get the answer and the `config files` is designed for commands that are run against the file system, either on the cluster or against a mounted volume in a pod.
This is part of a major refactoring of the configuration so that it's simpler and just config generation. See https://github.com/gitpod-io/gitpod/pull/12319 for my notepad of how it'll look eventually. …
=> [installer]: config detects shiftfs and containerd values

components/ws-daemon/pkg/dispatch/dispatch.go
Based on https://gitpod.slack.com/archives/C033MA45L5S/p1662729393858979 the following race condition can happen:
- New workspace is found which means it is [added to the dictionary ](https://github.com/gitpod-io/gitpod/blob/037a012ed8ba61718c7d913d7a6c800ec1c9bd62/components/ws-daemon/pkg/dispatch/dispatch.go#L193)in the dispatcher
- We wait for the container to be ready and once that has happened we set the ContainerSeen state to true
- We call the add handler of the listeners to process the event
- An update event arrives and it is processed before the handler for the add event is called (the condition for the processing of the update event is that the  workspace is in the dictionary and that we have seen the container, which is now fullfilled)
- :boom:  The listener has not seen the …
=> [ws-daemon] Ensure add handler is called before update

test/tests/components/ws-manager/tasks_test.go
Enhance TestRegularWorkspaceTasks test speed.
Run the single test TestRegularWorkspaceTasks, and the time is around 4 to 5 mins.
Fixes #12497
```console
cd test
go test  -run ^TestRegularWorkspaceTasks$ github.com/gitpod-io/gitpod/test/tests/components/ws-manager -count=1 -namespace=default -kubeconfig=/home/gitpod/.kube/config -v
```
```release-note
None
```
None
=> workspace integration test: enhance TestRegularWorkspaceTasks test speed

components/ws-manager/pkg/manager/manager.go
While verifying https://github.com/gitpod-io/gitpod/issues/11453 realized that it would have been helpful to find traces related to ABORT stopWorkspace calls. So added it to tracing.
Fixes #
```release-note
none
```
=> [ws-manager] add policy key to tracing in StopWorkspace call

components/content-service/pkg/initializer/prebuild.go
When creating workspace that uses PVC from prebuild that doesn't, we need to ensure that we will do chown.
That is because when supervisor runs `executor.Execute` it runs with `root:root`, so any git op will mess up permissions.
Fixes https://github.com/gitpod-io/gitpod/issues/12420
Enable PVC feature
Open workspace from prebuild that was created without PVC.
```release-note
none
```
=> [content-service] chown after prebuild git ops when using pvc

components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
Add a general method `subscribeToStripe` to the server JSON-RPC API for  adding Stripe subscriptions to a Stripe customer, for customers representing teams or individual users.
Implement the existing `subscribeTeamToStripe` method  (which only worked for teams) in terms of the new method.
The more general method will be used to subscribe individual Stripe users in subsequent PRs.
The flow to sign a team up for UBP still works:
1. Create a team with `Gitpod` in the name.
2. Sign the team up for UBP from the billing tab on the team settings page.
```release-note
NONE
```
=> [UBP] Add `subscribeToStripe` server method

components/dashboard/src/components/UsageBasedBillingConfig.tsx, components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Show error messages in the UI when upgrading with Stripe fails for any reason.
Fixes https://github.com/gitpod-io/gitpod/issues/12580
2. Try to upgrade using an invalid credit card number, or one of Stripe's [failing test cards](https://stripe.com/docs/testing#declined-payments) -- this should always show an error message
3. Upgrade using a regular test card in the currency **USD** (e.g. 4242 4242 4242 4242, 4/24, 424) -- this should work
4. Once it went through, manage and cancel your Stripe subscription
5. Upgrade again with a regular test card, but this time with the currency **EUR**
6. The payment method should go through, but on the next page you should see an error message
(Note: Currently that second step error message is redacted, and …
=> [dashboard] Show error messages in the UI when upgrading with Stripe fails

install/preview/entrypoint.sh
This PR reduces the storage requests across PVC's, control-plane components
and workspaces storage.
Part of #11303 
Run
```
docker run -p 443:443 --privileged --name gitpod --rm -it  --mount type=volume,source=gitpod,destination=/var/gitpod eu.gcr.io/gitpod-core-dev/build/local-preview:tar-lp-lower-storage.2
```
```release-note
[local-preview] Reduce storage requirements
```
=> [local-preview] Reduce storage requirements

components/dashboard/src/components/UsageView.tsx
Three small UI improvmeents on the usage view:
- format the total usage number
- show proper time plus an indicator for running sessions
- show `No sessions found` on empty list
- show viewed range
Fixes #12803
```release-note
NONE
```
=> [usage] smaller UI improvements

install/installer/leeway.Dockerfile
This reverts commit e27e278e556336b27770368f9ca1d43acf99183d which was reverting ceb75ebb61b9793158d7a904eaaf2fd7c0a07a0c
This original PR (https://github.com/gitpod-io/gitpod/pull/12834) was reverted because it changed the layers of the Installer Docker image which our ArgoCD SaaS deployment plugin was really sensitive to. This was fixed in https://github.com/gitpod-io/ops/pull/5115 so it is now save to revert the revert ☺️
Fixes https://github.com/gitpod-io/gitpod/issues/12828
This was tested in the original PR https://github.com/gitpod-io/gitpod/pull/12834
```release-note
NONE
```
N/A
=> Revert "Revert "Improve layer caching by moving apk commands up""

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/config.yaml, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/common/ca.go, install/installer/pkg/common/common.go, install/installer/pkg/components/content-service/configmap.go, install/installer/pkg/components/image-builder-mk3/configmap.go, install/installer/pkg/components/public-api-server/configmap.go, install/installer/pkg/components/public-api-server/configmap_test.go, install/installer/pkg/components/registry-facade/daemonset.go, install/installer/pkg/components/server/configmap.go, install/installer/pkg/components/server/deployment.go, install/installer/pkg/components/usage/configmap.go, install/installer/pkg/components/usage/configmap_test.go, install/installer/pkg/components/ws-daemon/configmap.go, install/installer/pkg/components/ws-daemon/daemonset.go, install/installer/pkg/components/ws-proxy/configmap.go, install/installer/pkg/config/v1/config.go, install/installer/scripts/kots-install.sh, install/kots/manifests/gitpod-http-proxy-settings.yaml, install/kots/manifests/gitpod-installer-job.yaml, install/kots/manifests/kots-preflight.yaml
Adds preliminary support for `HTTP_PROXY` (and `HTTPS_PROXY` and `NO_PROXY`) in the Installer. This adds an optional secret which receives the proxy settings from the KOTS CLI settings - the `NO_PROXY` envvar also hard-codes some additional parameters required for the application to work.
**Important** - this is not a full feature. It is merely the initial work to enable other teams to help out in their areas of expertise. This adds the appropriate envvars to the resources and wires them all up in a fashion that allows the Gitpod stack to run without error. However, it **DOES NOT** allow an image to be built or workspace to be run. There are additional tickets in #10769 that detail these tasks
An interesting thing of note is that the `@grpc/grpc-node` library does not respect wildcard …
=> [installer]: add HTTP_PROXY envvars to the Installer

components/dashboard/src/components/UsageBasedBillingConfig.tsx, components/dashboard/src/settings/Billing.tsx, components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Building on https://github.com/gitpod-io/gitpod/pull/12732 which extracted the components to make them reusable, add the UBP configuration UI widgets to the individual user billing page:
The 'Upgrade billing' button doesn't work yet. This is fine to merge as-is because only people opted into usage based billing will see the UI (currently only Gitpod team members).
Visit your user settings page and see the placeholder UI
```release-note
NONE
```
=> [UBP] Add placeholder billing configuration UI to the user settings page

components/gitpod-protocol/go/gitpod-service.go, components/gitpod-protocol/go/mock.go, components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
Remove deprecated `sendFeedback` server method.
**Note**: This is completely unrelated to the new dashboard feedback mechanism. 💡
In the early days of Gitpod (I think when it was still in Beta, or fresh out of Beta) there was a simple mechanism to provide general feedback about Gitpod, and in exchange you would receive a credit of 50 bonus Gitpod hours.
This feature no longer exists, and we no longer even keep track of the provided feedback (it's logged at `info` level in server, which we currently discard), but the server method is still there in our API, potentially allowing clever users to credit themselves 50 hours whenever they want.
This PR removes the old, deprecated `sendFeedback` method. Also, removing it now is a good idea, because we have a new dashboard feedback mechanism in …
=> Remove deprecated sendFeedback server method

components/ide/jetbrains/backend-plugin/launch-dev-server.sh
Allow passing a test-repository URL via parameter `-r` when running launch-dev-server.sh for JetBrains Backend Plugin development.
If the parameter is not passed, it will use the default test-repository: <https://github.com/gitpod-io/spring-petclinic>.
This PR also updates the plugin's path, which is now built with the name "gitpod-remote.zip".
Resolves #10286
1. Open the branch of this PR in gitpod.io
2. Navigate to `/workspace/gitpod/components/ide/jetbrains/backend-plugin`
3. Run `./launch-dev-server.sh -r https://github.com/gitpod-io/.github`
4. Confirm it has opened the test environment with https://github.com/gitpod-io/.github repository.
5. Stop the test environment and run `rm -rf /workspace/test-repo`.
6. Run `./launch-dev-server.sh`
7. Confirm it has opened the test environment …
=> [JetBrains Backend Plugin] Allow specifying the test-repository when running launch-dev-server.sh

install/installer/cmd/config.go, install/installer/cmd/render.go, install/installer/cmd/validate_cluster.go, install/installer/cmd/validate_config.go
This uses the envvar `GITPOD_INSTALLER_CONFIG` throughout and defaults to `${PWD}/gitpod.config.yaml`. Used the more established envvar to avoid breaking any existing scripts that depend on this in the wild
```release-note
[installer]: make the installer config file consistent
```
=> [installer]: make the installer config file consistent

WORKSPACE.yaml
- Bring upstream [fixes](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aclosed+milestone%3A%22August+2022+Recovery+1%22) with release `1.71.1` to Gitpod Browser Code
- Bring experimental portsView with ConfigCat to stable Browser Code
Fixes #
- Choose latest code as IDE in prev env
- Open workspace to check if basic usage of browser vscode is ok
- Check if changing non-product ConfigCat will affect your workspace
- Check if Browser Code `About` show with version `1.71.1`
```release-note
NONE
```
=> [code] build stable image for 1.71.1 release

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/workspace/ide/constants.go
commit hash comes from [werft job](https://werft.gitpod-dev.com/job/gitpod-build-hw-build-171-1.3) of the previous PR https://github.com/gitpod-io/gitpod/pull/12926
Fixes #
Relates https://github.com/gitpod-io/gitpod/issues/12470
Tested in previous PR, we can check `About` in this one
```release-note
Update stable Browser Code to `1.71.1` release
```
=> [code] update stable browser code to 1.71.1

test/pkg/integration/workspace.go, test/tests/components/ws-manager/content_test.go, test/tests/components/ws-manager/multi_repo_test.go, test/tests/components/ws-manager/prebuild_test.go, test/tests/components/ws-manager/tasks_test.go, test/tests/ide/jetbrains/gateway_test.go, test/tests/ide/vscode/python_ws_test.go, test/tests/workspace/cgroup_v2_test.go, test/tests/workspace/contexts_test.go, test/tests/workspace/docker_test.go, test/tests/workspace/example_test.go, test/tests/workspace/git_test.go, test/tests/workspace/k3s_test.go, test/tests/workspace/mount_proc_test.go
test: Put logging of workspace starts and stops
Run the test and get logs
```release-note
NONE
```
=> test: Put logging of workspace starts and stops

test/pkg/integration/workspace.go, test/tests/components/ws-manager/content_test.go, test/tests/components/ws-manager/multi_repo_test.go, test/tests/components/ws-manager/prebuild_test.go, test/tests/components/ws-manager/tasks_test.go, test/tests/ide/jetbrains/gateway_test.go, test/tests/ide/vscode/python_ws_test.go, test/tests/workspace/cgroup_v2_test.go, test/tests/workspace/contexts_test.go, test/tests/workspace/docker_test.go, test/tests/workspace/example_test.go, test/tests/workspace/git_test.go, test/tests/workspace/k3s_test.go, test/tests/workspace/mount_proc_test.go
Make stopWs independent of the main context to have no dependence on the order of cleanUp or defer
Run the test
```release-note
NONE
```
=> test: Make stopWs independent of the main context and api variable

.werft/platform-trigger-artificial-job.yaml
We're currently having trouble with our clean-up jobs. It has been failing for the last 2 days. With us creating new previews every 30 minutes, we're saturating all our bare-metal VMs too quickly. 
This PR decreases the frequency we create artificial previews just for the sake of not overloading the underlying infrastructure until we fix our clean-up job.
Fixes #
```release-note
NONE
```
=> previews: Trigger artificial traffic every 2 hours

components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
Add two new methods to the server API for getting and setting usage limits. Both new functions take an attributionId and work for both users and teams.
For backwards compatibility, leave the `getUsageLimitForTeam` and `setUsageLimitForTeam` methods as they are still used by the dashboard, but change them to be implemented in terms of the more general `get/set` methods.
* Create a team with `Gitpod` in the name in the preview environment and sign the team up for usage based pricing.
* Run the following in the browser developer console:
```js
await window._gp.gitpodService.server.setUsageLimit('team:<teamId of the new team>', 90)
```
* Then:
```js
await window._gp.gitpodService.server.getUsageLimit('team:<teamId of the new team>')
``` …
=> [UBP] Add `getUsageLimit` and `setUsageLimit` methods to server

test/pkg/integration/apis.go, test/pkg/integration/workspace.go
Refresh client connections when they are no longer useful.
Run the test
```release-note
NONE
```
=> test: Refresh a api client if it returns Unavailable

components/usage/pkg/db/dbtest/workspace_instance.go, components/usage/pkg/db/workspace_instance.go, components/usage/pkg/db/workspace_instance_test.go, components/usage/pkg/scheduler/job.go, components/usage/pkg/scheduler/job_test.go, components/usage/pkg/scheduler/reporter.go, components/usage/pkg/scheduler/scheduler_test.go, components/usage/pkg/server/server.go
This PR does the following:
1. Adds a scheduled job (every 15m) which detects if there are any instances in the `usage` table which are for workspace instances which have stopped, but do not have a `stoppingTime` set. In this case, these instances would cause runaway credit usage for our customers.
2. When such an instance is detected, a metric is updated to allow us to alert on this.
To avoid code-duplication, the existing Ledger Job is refactored to introduce the following:
1. Wrapper which can compose a Job to enable concurrent execution prevention
2. Tests are updated to reflect this change
Fixes #
Unit tests
```release-note
NONE
```
=> [usage] Add periodic job to detect invalid workspace instances in usage

operations/observability/mixins/cross-teams/dashboards/gitpod-grpc-server.json
Update `gRPC / Server` dashboard to make variable selection dependant on each other. That is, if you pick the UsageService, you should only see RPCs which exist on the Usage Service.
Fixes #
```release-note
NONE
```
=> [dashboards] Fix gRPC/Server variable selection

test/pkg/integration/integration.go, test/tests/components/content-service/content-service_test.go
test: Handle errors relate network in port-fowarding
Run the test
```release-note
NONE
```
=> test: Handle errors relate network in port-fowarding

components/usage/pkg/scheduler/job.go, components/usage/pkg/server/server.go
Removes the detector until we land https://github.com/gitpod-io/gitpod/pull/12706 because the query is too slow without those indices.
Currently, it throws `github.com/gitpod-io/gitpod/usage/pkg/db/workspace_instance.go:252 context deadline exceeded` because the query runs for more than 10m.
Will be re-added (removal reverted) once the indices are in place.
Fixes #
```release-note
NONE
```
=> [usage] Remove stopped without stopping time detector, temporarily

components/dashboard/src/components/BillingAccountSelector.tsx
Use the more general `findStripeSubscriptionId` API rather than `findStripeSubscriptionIdForTeam` to allow the latter to be safely removed from the server JSON-RPC API in a subsequent PR.
The `BillingAccountSelector` component is used on the individual user settings page:
1. Create some `Gitpod-something` teams in the preview environment and sign them up for UBP.
2. Visit your billing settings page and use the billing account selector controls to define your cost center.
The selected cost center is respected. (Easiest way to verify this is to examine the `d_b_users.usageAttributionId` field in the db). 
```release-note
NONE
```
=> [UBP] Use `findStripeSubscriptionId` in `BillingAccountSelector` component

test/tests/components/ws-manager/content_test.go, test/tests/workspace/example_test.go
- Refactor
- Don't use gitpod-io/gitpod to save time
Fixes #
```release-note
NONE
```
=> test: Refactor content tests

test/pkg/integration/common/port_forward.go
test: Convert port-forward stderr to be easier to deal with
Run the test
```release-note
NONE
```
=> test: Convert port-forward stderr to be easier to deal with

operations/observability/mixins/meta/dashboards/components/usage.json
Fixes usage dashboard to correctly report scheduled jobs on the usage component.
Fixes #
```release-note
NONE
```
=> [usage] Update usage dashboard to track scheduled jobs

install/infra/modules/eks/storage.tf
Fixes https://github.com/gitpod-io/gitpod/issues/12964
We no longer need to attach these policies to the S3 users we create in our terraform modules.
```release-note
No longer attaches `arn:aws:iam::aws:policy/AmazonS3FullAccess` to the IAM user accounts created in our AWS terraform reference infrastructure. This level of access is no longer required now that one can provide an S3 bucket to be used for object storage.
```
=> Fix: remove global S3 access policy

dev/gpctl/cmd/workspaces-list.go
Add node to workspace list output to make it easier to identify when failing workspaces cluster on a specific node.
n.a.
`gpctl workspaces list `
```release-note
None
```
=> [gpctl] Add node to workspace list output

components/ws-manager-bridge/src/bridge.ts
This PR checks and logs if a workspace instance that the ws-manager does not know about is in `pending`, `creating`, `initializing` states, or if it is in `stopping` for longer than 10 seconds (a guard in case of a race condition).
We will monitor the logs and validate if we can deploy the planned fix [here](https://github.com/gitpod-io/gitpod/compare/main...lau/stuck-ws-11397).
Relates #11397
Relates #12955
```release-note
NONE
```
=> [bridge] Logs stuck workspace instances to validate fix

install/infra/modules/aks/database.tf, install/infra/modules/aks/kubernetes.tf, install/infra/modules/aks/local.tf, install/infra/modules/aks/main.tf, install/infra/modules/aks/networks.tf, install/infra/modules/aks/output.tf, install/infra/modules/aks/registry.tf, install/infra/modules/aks/storage.tf, install/infra/modules/aks/variables.tf, install/infra/single-cluster/azure/.env_sample, install/infra/single-cluster/azure/Makefile, install/infra/single-cluster/azure/README.md, install/infra/single-cluster/azure/cluster.tf, install/infra/single-cluster/azure/main.tf, install/infra/single-cluster/azure/output.tf, install/infra/single-cluster/azure/terraform.tfvars, install/infra/single-cluster/azure/tools.tf, install/infra/single-cluster/azure/variables.tf, install/tests/Makefile, install/tests/main.tf, install/tests/manifests/kots-config-azure-registry.yaml, install/tests/manifests/kots-config-azure-storage.yaml
This PR adds the first iteration of single cluster terraform module for AKS. We add a new directory `install/infra/single-cluster/azure` that uses the `aks` terraform module to create a single-cluster infrastructure for setting up Gitpod.
Fixes #12867 
Please follow the [README.md](https://github.com/gitpod-io/gitpod/blob/nvn/azure-tf-mod/install/infra/single-cluster/azure/README.md) added as a part of this PR.
```release-note
NONE
```
=> [azure] Single-cluster usage guide for AKS TF module

components/usage/pkg/scheduler/job.go, components/usage/pkg/scheduler/ledger_job.go, components/usage/pkg/scheduler/reporter.go
Adds a Gauge metric which tracks the last time we completed a scheduled ledger reconciliation. We'll use this metric to setup an alert for when we haven't completed a run succesfully for more than 1h (which could cause us to have gaps in the data).
This metric is setup the same way as other standard kube metrics- [see example](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22kube_job_status_start_time%7Bjob_name%3D%5C%22cert-manager-startupapicheck%5C%22%7D%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D)
Fixes #
```release-note
NONE
```
=> [usage] Track last compelted ledger job time

components/usage/go.mod, components/usage/go.sum
`go mod tidy`
Fixes #
CI builds
```release-note
NONE
```
=> [usage] Run go mod tidy

operations/observability/mixins/meta/rules/usage.yaml
Alert on the two core RPCs used in usage reconciliation. 
* Soft depends on https://github.com/gitpod-io/gitpod/pull/12917
```release-note
NONE
```
=> [usage] Alert on Usage and Invoice Reconciliations

.werft/installer-tests.ts
This PR randomly runs the automated tests against unstable and stable channels on a nightly basis. This is a requirement for IDE integration tests since they would like to continue testing the `stable` version against the new marketplace publishes.
Fixes #11679
You can start a test by running the following command:
```
werft run github -j .werft/k3s-installer-tests.yaml
```
```release-note
NONE
```
=> [installer-tests] Randomly run tests against stable and unstable channels

components/dashboard/src/projects/NewProject.tsx, components/gitpod-protocol/src/gitpod-service.ts
While reverse-engineering our `createProject` flow to identify [this workaround](https://github.com/gitpod-io/gitpod/issues/12970#issuecomment-1247024832), I noticed that we were populating two fields in `CreateProjectParams` that are not even read or stored anywhere. Thus, we can save ourselves the trouble.
Fixes #
1. Creating Projects still works
```release-note
NONE
```
=> [dashboard][protocol] Remove unused params from CreateProjectParams

install/tests/manifests/kots-config-gcp-db.yaml
This PR fixes the occasional GCP database connection failures that happen in running automated tests. Since we allow special characters, sometimes this causes errors in `yq m` command we use to merge configs.
Fixes #
```
werft run github -j .werft/gke-installer-tests.yaml -a deps=external
```
```release-note
NONE
```
=> [installer-tests] Surround  the GCP password with quotes

components/ws-manager-bridge/src/bridge.ts
Fixes logging object. ([context](https://github.com/gitpod-io/gitpod/pull/12902#discussion_r971597652))
```release-note
NONE
```
=> [bridge] Fix logging

.gitattributes
This will automatically collapse the `*.golden` files in PRs and mark them as auto-generated.
Because it's causing PRs to be messy with changes which are auto-generated
See [docs](https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github)
Fixes #
```release-note
NONE
```
=> Add .gitattributes to mark installer golden files as generated

operations/observability/mixins/meta/rules/usage.yaml
Initially as a warning on slack only
Fixes #
```release-note
NONE
```
=> [usage] Add warning alert when usage reconciliation has not been succesfull for more than an hour

components/server/ee/src/billing/billing-service.ts
For checking the usage limit, instead of checking against the current stripe invoice we want to check against the current credit balance.
Fixes #
```release-note
NONE
```
=> [usage] use credit balance for limit check

.werft/jobs/build/build-and-publish.ts, .werft/jobs/build/validate-changes.ts
This follows up on https://github.com/gitpod-io/gitpod/pull/12998 and adds `leeway vet` to the Validating changes phase too to catch such issues early on.
It also means we save 7 seconds as this was otherwise running sequentially as part of the build
No issue, just feeling like doing some minor cleanups.
```sh
werft job run github
```
```release-note
NONE
```
N/A
=> Move leeway vet to validate

components/gitpod-db/src/typeorm/workspace-db-impl.ts, components/gitpod-db/src/workspace-db.spec.db.ts, components/gitpod-db/src/workspace-db.ts, components/gitpod-protocol/src/util/timeutil.spec.ts, components/server/src/config.ts, components/server/src/prometheus-metrics.ts, components/server/src/workspace/garbage-collector.ts, components/server/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/workspace-deletion-service.ts, install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/server/configmap.go, install/installer/pkg/components/server/types.go
Introduces a 3rd workspace deletion state "purged" as discussed in #11378 .
Fixes #11378
- `(cd components/gitpod-db && yarn test)`
- open a workspace on [this branch](https://gitpod.io/#github.com/gitpod-io/gitpod/pull/11360)
- `kubectl port-forward mysql-0 3306 &`
- `mysql -u gitpod -h 127.0.0.1 -p`, PW: `PW`
- Insert these:
```
INSERT INTO `gitpod`.`d_b_workspace`
(`id`,
`creationTime`,
`ownerId`,
`contextURL`,
`description`,
`context`,
`config`,
`softDeleted`,
`softDeletedTime`,
`contentDeletedTime`,
`cloneURL`)
VALUES
('123',
'2019-09-25T21:44:13.560Z',
'123',
'https://example.org/my/repo',
'my-repo',
'{}',
'{}',
'gc',
'2019-09-25T21:44:13.560Z',
'2019-10-25T21:44:13.560Z',
'https://example.org/my/repo');
```
```
INSERT INTO `gitpod`.`d_b_workspace_instance`
(`id`,
`workspaceId`, …
```
=> Purge old Workspaces at some point

.werft/platform-delete-preview-environment.ts, .werft/platform-delete-preview-environment.yaml, .werft/platform-delete-preview-environments-cron.ts, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-artificial-job.sh, .werft/util/preview.ts
Turns out this PR got a long bigger than initially expected. That is because I ended up making several changes in a single PR. 
1) Introduce job that cleans-up individual previews.
2) Update preview clean-up cronjob to re-use the job for individial clean ups .
3) Update job that creates artificial preview to also delete the preview at the end.
Every change is done in separate commits, so please use them to make the review process easier 🙂 
Fixes #
You can test each change with different werft commands:
1) You can manually create previews and delete it individually with the following commands:
```
werft run github -a with preview
werft run github -j platform-delete-preview-environment.yaml -a preview="your preview name"
```
2) When triggering the cron job, notice that now it will trigger …
=> previews: Several improvements to clean up logic

test/pkg/integration/apis.go, test/pkg/integration/workspace.go, test/tests/components/ws-manager/prebuild_test.go, test/tests/workspace/contexts_test.go, test/tests/workspace/example_test.go
Fix [a failed of this job](https://werft.gitpod-dev.com/job/gitpod-custom-main.185)
Run the test
```release-note
NONE
```
=> test: Enhanced running in unstable environments

components/dashboard/src/AppNotifications.tsx, components/gitpod-messagebus/src/messagebus.ts, components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/messaging/local-message-broker.ts, components/server/src/workspace/messagebus-integration.ts
Dismiss Usage Limit notifications automatically on resolution, e.g. on increase of Usage Limit.
Fixes #12547
* Have 2 accounts on a team with UB enabled.
* Decrease usage limit and drive into the limit notification. 
* Increase the spending limit on one account.
* See the notification is dismissed for both accounts.
```release-note
Dismiss Usage Limit notifications automatically.
```
=> Update App Notifications

components/ws-manager/pkg/manager/manager.go, components/ws-manager/pkg/manager/monitor.go, components/ws-manager/pkg/manager/volume_snapshot_controller.go
Fix workers hang if there are over 100 VolumeSnapshot is ready, and we restart the ws-manager.
The `m.notifyPod` channel is no receiver, and it causes the 100 event workers to hang forever.
So, the ws-manager can't handle any workspace pod event and volume snapshot event changes.
Fix event workers hang if there are 100+ VolumeSnapshot ready and ws-manager restarts.
Fixes #13007
- Prepare Pod yaml manifest and save it as `pod.yaml`.
```yaml
apiVersion: v1
kind: Pod
metadata:
name: test
spec:
containers:
- name: test
image: alpine:latest
volumeMounts:
- name: volv
mountPath: /data
volumes:
- name: volv
persistentVolumeClaim:
claimName: test
```
- Prepare PVC yaml manifest and save it as `pvc.yaml`.
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: test
spec:
accessModes:
- …
```
=> ws-manager: fix event workers hang forever

components/server/src/workspace/workspace-starter.ts
Removes invocations of BillingService.SetBilledUsage
* Part of https://github.com/gitpod-io/gitpod/issues/13009
```release-note
NONE
```
=> [server] Stop calling BillingService.SetBilledUsage

components/server/ee/src/prebuilds/prebuild-manager.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/user/user-deletion-service.ts, components/server/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/workspace-starter.ts
Every time we stop a workspace instance, log the reason why. This should help with debugging.
Fixes https://github.com/gitpod-io/gitpod/issues/12283
```release-note
NONE
```
=> [server] Every time we stop a workspace instance, log the reason why

WORKSPACE.yaml, components/ide/code/leeway.Dockerfile, components/supervisor/frontend/src/ide/ide-metrics-service-client.ts, install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/ide-metrics/configmap.go
This PR advances on the changes made in https://github.com/gitpod-io/gitpod/pull/12222 and contributes a new metric field: `gitpod_vscode_web_load_total`, which will help in discovering how often (percentage-wise) errors happen in [VS Code Browser](https://www.gitpod.io/docs/ides-and-editors/vscode-browser), as described in https://github.com/gitpod-io/gitpod/issues/12107#issuecomment-1237115318.
This PR also moves all of the remaining error reporting logic found in [supervisor frontend](https://github.com/gitpod-io/gitpod/blob/main/components/supervisor/frontend/src/index.ts) to the [VS Code Browser workbench](https://github.com/gitpod-io/openvscode-server/blob/gp-code/main/src/vs/gitpod/browser/workbench/workbench.html). 
Relates https://github.com/gitpod-io/gitpod/issues/12107
Changes …
=> [code browser] measure all sessions vs errored sessions

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/cleanup-installer-tests.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/run-integration-tests.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile
`-mod=readonly` is the default option (since 1.14) if there is no vendor directory present (and we don't vendor anything from what I can see). This flag was set [~2y ago](https://github.com/gitpod-io/gitpod/commit/206fcf90c16c94593bcc60878f8aa65c7c9d2df9).
Not entirely sure the exact interaction which leads to the issue - I imagine it might be some weird combination of `gitpod-io/gitpod` being a monorepo with multiple `go.mod` files and not using workspaces ¯\_(ツ)_/¯ But ultimately it does fix installing/updating packages that rely on 1.18+
Fixes https://gitpod.slack.com/archives/C032A46PWR0/p1663224067876619
```release-note
NONE
```
=> Unset GOFLAGS from Dockerfile and update images

components/gitpod-db/src/tables.ts
Remove `d_b_workspace_instance_usage` from the table description provider that `db-sync` uses to generate a list of tables to sync.
This table was removed from the db in #12948.
With this non-existent table present in the list `db-sync` would show a warning on every sync:
```
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"db-sync","version":"<ts-not-set>"},"component":"db-sync","severity":"WARNING","time":"2022-09-16T07:51:10.741Z","message":"table d_b_workspace_instance_usage does not exist - not replicating"}
```
Relates to #12948.
Hard to test as we don't run db-sync in preview.
```release-note
NONE
```
=> Remove `d_b_workspace_instance_usage` from TableDescriptionProvider

.werft/platform-trigger-artificial-job.yaml
Now that https://github.com/gitpod-io/gitpod/pull/12784 got merged, we can revert gitpod-io/gitpod#12928
```release-note
NONE
```
=> Revert "previews: Trigger artificial traffic every 2 hours"

.werft/jobs/build/deploy-to-preview-environment.ts, .werft/util/kubectl.ts
Remove helm-related cleanup logic that is no longer needed.
No issue, just cleaning up a bit
```sh
werft job run github -a with-clean-slate-deployment=true
```
[Job here](https://werft.gitpod-dev.com/job/gitpod-build-mads-remove-more-helm.3)
```release-note
none
```
N/A
=> Remove helm-related cleanup logic

components/common-go/baseserver/metrics.go, components/common-go/baseserver/options.go, components/common-go/baseserver/options_test.go, components/common-go/baseserver/server.go, components/public-api-server/cmd/run.go, components/public-api-server/pkg/server/server.go, components/usage/cmd/run.go, components/usage/pkg/server/server.go
To be able to track which version we're on in our dashboards. Will produce the following metric:
```
gitpod_server_version{version="<version>"} 1
```
Once validated, I can also add this to other instances of baseserver
The approach to the metric with version is standard, see [docs](https://www.robustperception.io/exposing-the-software-version-to-prometheus/)
Fixes #
```release-note
NONE
```
=> [baseserver] Add metric with version of the server, use in public api and usage

components/usage/pkg/apiv1/billing.go, components/usage/pkg/stripe/stripe.go
We were doing 2 things wrong:
1. Expanding the wrong response property
2. Using the Subscription to get the Attribution ID when we needed the Customer
Both fixed here.
Fixes #13035 
```release-note
NONE
```
=> [usage] Fix stripe invoice finalization

.werft/observability/install-satellite.sh
https://github.com/gitpod-io/gitpod/pull/12989 fixed the issue with installing the obs-installer, so we no longer need to clone the repository anymore.
Fixes #
```release-note
NONE
```
=> Use go to install latest obs-installer

components/ee/db-sync/README.md
Add a `README.md` for `db-sync` based on the information that was recently added to the architecture document ([internal](https://www.notion.so/gitpod/WebApp-Architecture-784cf14bc76440e3beb8de56f61e7340#b03f15d688a54657b0d3accb440ea018)).
Part of #9198 
```release-note
NONE
```
=> Add README for `db-sync` component

.github/CODEOWNERS
This PR removes individuals from codeowners of the content service. Depending on individuals is suboptimal as it introduces a bus factor when individuals are unavailable or on holidays.
This removes @geropl, @corneliusludmann and @csweichel and instead makes Team Workspace the owner.
Fixes #
```release-note
NONE
```
=> [codeowners] Remove individuals from ownership of content-service-api

components/dashboard/src/components/UsageView.tsx
Following up from https://github.com/gitpod-io/gitpod/pull/12412#issuecomment-1246678522, since https://github.com/gitpod-io/website/pull/2715 is now merged, this will rename the _Beta_ label on the usage page to _Early Access_.
1. Enable usage-based pricing for a team.
2. Go to team usage page.
3. Notice the new Early Access label on the left sidebar. 👀 
```release-note
NONE
```
=> Rename beta label on the usage page

components/ee/db-sync/src/replication.ts, components/gitpod-db/src/tables.ts
Fixes the problems we were facing when resolving [this incident](https://app.incident.io/incidents/213).
Fixes #
```release-note
NONE
```
=> [db-sync] Fix it

components/content-service/cmd/run.go, components/ws-daemon/cmd/run.go
Bind Version to be exposed by baseserver metrics
You can see the example reported metric [here](https://grafana.gitpod-staging.com/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:false,%22expr%22:%22gitpod_server_version%22,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D) 
Support for this implemented in https://github.com/gitpod-io/gitpod/pull/13022
Fixes #
```release-note
NONE
```
=> Expose version in ws-daemon & content-service

.werft/build.ts, .werft/jobs/build/validate-changes.ts, .werft/util/werft.ts
The Werft log cutter expects each line of output to follow the specific format ([docs](https://github.com/csweichel/werft#log-cutting)). If no slice is specified in a log line then it will be attached to the "default" slice for that phase (which is a slice with the same id as the phase).
As we're just `console.log`'ing strings it means it's out responsibility to ensure we don't log multiline strings.
This PR improves our handling of slices that we explicitly fail using `werft.fail` in two  important ways:
1. Previously it would not handle multi-line error messages well which meant that the error message for a slice might get split between the slice that failed and the default slice for the phase.
2. `werft.fail` throws an error which will eventually bubble up to our main `catch` handler. …
=> Ensure error message for failed slices stay within the slice

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/workspace/ide/constants.go
Upstream endgame https://github.com/microsoft/vscode/issues/160943. Also bring
- Extension installation metrics
- Resources load error report
commit hash comes from [werft job](https://werft.gitpod-dev.com/job/gitpod-build-hw-build-1712.0/results)
Relates https://github.com/gitpod-io/gitpod/issues/12470
- Open workspace in prev env with stable browser code as IDE
- Check if it works and commit hash should be `9ae312771e40d3399bac2b7b43c5bb4a1514517c` (In Browser VSCode About)
```release-note
Update stable Browser Code to `1.71.2` release
```
=> [code] update stable browser code to `1.71.2` release

components/common-go/log/redact.go
Since the map ordering is random, not by sequence or alphabetical order. Thank @svenefftinge points out.
So, we have to force all the values redacted once one of the values matches redact fields
Fixes https://github.com/gitpod-io/security/issues/64
Check the unit test.
```console
cd component/common-go
go test -covermode atomic -run ^TestRedactJSON\$ github.com/gitpod-io/gitpod/common-go/log -timeout=60s -count=1 -race -v
```
```release-note
None
```
None
=> Force all the values redacted once one of the values matches redact fields

components/gitpod-protocol/src/protocol.ts, components/server/src/workspace/workspace-starter.ts
This instructs ws-manager to limit the rate of network connections for non paying customers. Note that this currently only audits (i.e. it records packets that would have been dropped but does not actually drop them). We will use this to refine the limits.
Fixes https://github.com/gitpod-io/gitpod/issues/13041
- User on free tier
- Make yourself admin in the preview environment
- Ensure that you are on the free open source plan
- The workspace should have the `gitpod.io/netConnLimitPerMinute` annotation
- The other parts of this have already been covered by [other PRs](https://github.com/gitpod-io/gitpod/issues?q=label%3Afeature%3Aconnection-limiting+is%3Aclosed). If you want to be sure, check the logs of ws-daemon (it should contain `will limit network connections`. …
=> Enable connection limiting for free tier

install/kots/manifests/kots-config.yaml
When creating an S3 backing to the in-cluster container registry, the `s3.amazonaws.com` endpoint only works if the bucket is in the `us-east-1` region. Without it, the registry healthcheck eventually reports a 503 error.
This documents the requirement in the KOTS dashboard.
N/A
```release-note
[kots]: note to explain the region limitation on registry S3 backing
```
=> [kots]: note to explain the region limitation on registry S3 backing

components/dashboard/src/Usage.tsx, components/dashboard/src/components/UsageView.tsx, components/dashboard/src/teams/TeamUsage.tsx
Removes unused state/parameters from UsageView.
Fixes #
```release-note
NONE
```
=> [dashboard] Remove unused state/params from UsageView

components/server/ee/src/gitlab/gitlab-app-support.spec.ts, components/server/ee/src/gitlab/gitlab-app-support.ts, components/server/package.json, components/server/src/gitlab/api.ts, components/server/src/gitlab/gitlab-file-provider.spec.ts, yarn.lock
PR updates GitLab API library, adds tests to cover changes and verify that the paginated requests now works as expected.
Fixes #12970
- `export GITPOD_TEST_TOKEN_GITLAB='{ "value": "F00....", "scopes":[] }'`
- `cd components/server && npx mocha --opts mocha.opts './**/gitlab-*.spec.ts' --exclude './node_modules/**'`
- run `createManyRepos` to create 
2. verify the check points in comments bellow 
```release-note
Update GitLab API library, which fixes paginated API requests.
```
=> [server] bump GitLab API library

components/usage-api/go/v1/billing.pb.go, components/usage-api/go/v1/billing_grpc.pb.go, components/usage-api/typescript/src/usage/v1/billing.pb.ts, components/usage-api/usage/v1/billing.proto, components/usage/pkg/apiv1/billing.go, components/usage/pkg/stripe/stripe.go
Removes no longer needed `getUpcomingInvoice` API.
Fixes #
```release-note
NONE
```
=> [usage] remove unused GetUpcomingInvoice

.gitattributes
Automatically fold and not display grpc & proto generated files
Fixes #
```release-note
NONE
```
=> [git] Mark generated proto files as regenerate to fold them

components/gitpod-db/src/typeorm/migration/1663572136760-DropBilledSessionTable.ts, components/gitpod-db/src/typeorm/migration/README.md
Last step in https://github.com/gitpod-io/gitpod/issues/13009
Fixes #
```release-note
NONE
```
=> [db] Drop d_b_billed_session table

components/server/ee/src/user/eligibility-service.ts
This PR fixes parse errors when the GH Edu API call errors. 
Fixes #12203
```release-note
NONE
```
=> [server] fix GitHub Education API call

test/pkg/integration/workspace.go, test/tests/components/ws-manager/prebuild_test.go
Add a new integration test TestOpenWorkspaceFromPrebuild, without and with PVC.
#12638
```console
cd test
go test  -run ^TestOpenWorkspaceFromPrebuild$ github.com/gitpod-io/gitpod/test/tests/components/ws-manager -count=1 -namespace=default -kubeconfig=/home/gitpod/.kube/config -v
```
```release-note
None
```
None
=> test: new integration test TestOpenWorkspaceFromPrebuild

components/server/src/config/config-inferrer.spec.ts, components/server/src/config/config-inferrer.ts
Currently, it runs `go run` which doesn't work. ([example repo used](https://github.com/the-eduardo/Go-Bank)). But it does, work with `go run .` (see below 👀)
_you can test out the same for other goLang based repos_
- Open [this repo](https://github.com/the-eduardo/Go-Bank) with new preview environment of this PR)
```release-note
improved automated code configuration service for `go`
```
Not Required
---
Signed-off-by: Siddhant Khare <siddhant@gitpod.io>
=> fix: improve GoLang config inferrer

components/ide-proxy/static/code/marketplace.json
Removes the weird indentation used before and uses 2 spaces for each new block in the https://open-vsx.org deprecated extensions list.
Just a change for format, should behave the same.
```release-note
NONE
```
=> Format `marketplace.json`

operations/observability/mixins/workspace/dashboards/network-limiting.json
Add overview panel to network limiting dashboard, that displays all workspaces that have been rate limited.
n.a.
```release-note
None
```
=> [obs] Add network limiting overview panel

components/ws-daemon/pkg/cpulimit/cpulimit.go
[ws-daemon] Ensure last tick usage is updated. For more context see https://github.com/gitpod-io/ops/issues/5243
Fixes https://github.com/gitpod-io/ops/issues/5243
See https://github.com/gitpod-io/ops/issues/5243
```release-note
None
```
=> [ws-daemon] Ensure last tick usage is updated

components/content-service/pkg/archive/tar.go, components/content-service/pkg/storage/gcloud.go
Additional tracing for prebuild init
Related to https://github.com/gitpod-io/gitpod/issues/12345
```release-note
None
```
=> [content-service] Additional tracing for prebuild init

operations/observability/mixins/meta/rules/usage.yaml
Just removes trailing quotes
Fixes #
```release-note
NONE
```
=> [usage] Remove trailing quote from alerts

.werft/aks-installer-tests.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/installer-tests.ts, .werft/k3s-installer-tests.yaml, install/tests/Makefile, install/tests/manifests/kots-config-self-signed.yaml
This PR adds a new test option called `self-signed` which is used to
enable `self-signed` integration tests. This is done by adding a new
`generate-self-signed` make option, which is called whenever `self_signed`
env variable is enabled.
Once enabled, self-signed certs are genereated and relevant `self-signed-config`
is called to attach those files into `kots` config.
Fixes https://github.com/gitpod-io/gitpod/issues/11270
Run
```
werft run github -f -s .werft/installer-tests.ts -j .werft/eks-installer-tests.yaml -a debug=true -a self-signed=true -a skipTests=true -a preview=true
```
```release-note
[infra-tests] Add self-signed integration test
```
=> [infra-tests] Add `self-signed` integration test

operations/observability/mixins/cross-teams/dashboards/gitpod-grpc-server.json
Previously the `requests started` dashboard would ignore the selected `method` variable
Fixes #
```release-note
NONE
```
=> [grafana] gRPC dashboard filters requests started on selected method

.github/CODEOWNERS, dev/preview/.gitignore, dev/preview/infrastructure/harvester/namespace.tf, dev/preview/infrastructure/harvester/provider.tf, dev/preview/infrastructure/harvester/variables.tf, dev/preview/workflow/lib/common.sh, dev/preview/workflow/lib/terraform.sh, dev/preview/workflow/preview/deploy-harvester.sh, dev/preview/workflow/terraform/terraform-apply.sh, dev/preview/workflow/terraform/terraform-init.sh, dev/preview/workflow/terraform/terraform-plan.sh, dev/preview/workflow/terraform/terraform-workspace.sh
- Introduce functions + set of scripts to manage TF
- Most basic TF for a Harvester preview env - creates only a namespace in the Harvester cluster to show how it works
- Written in bash, so they can be executed from any environment and have dependency solely on `terraform` binary being available.
- Standalone scripts for `[init, plan, apply, workspace]`, so they can be executed in any context.
Other PRs will follow with werft job and harvester VM will follow.
Fixes https://github.com/gitpod-io/ops/issues/5093
```bash
TF_VAR_preview_name=temp ./workflow/preview/deploy-harvester.sh
Initializing the backend...
Initializing provider plugins...
- Reusing previous version of hashicorp/kubernetes from the dependency lock file
- Reusing previous version of harvester/harvester from the dependency …
```
=> [Preview env] TF Workflow

components/server/ee/src/billing/billing-mode.spec.db.ts, components/server/ee/src/billing/billing-mode.ts, components/server/ee/src/workspace/gitpod-server-impl.ts
Removes unused method and a feature flag for billing mode.
Fixes #
```release-note
NONE
```
=> [server] remove unused `isBillingModeEnabled`

operations/observability/mixins/workspace/dashboards.libsonnet
Fix dashboard import error. For context see [here](https://github.com/gitpod-io/gitpod/commit/30cffea01aeb84965c50de0c49650a174ca34ce8) and [here](https://github.com/gitpod-io/observability/actions/runs/3088698598/jobs/4995483631#step:4:155).
n.a.
```release-note
None
```
=> [obs] Fix dashboard import error

install/installer/pkg/config/v1/config.go, install/installer/pkg/config/v1/validation.go, install/installer/pkg/config/validation.go
If a user selects the option to limit their user registrations (which they should if on public internet), it is possible to get their Gitpod instance into a weird state where the initial admin user is blocked if they had configured no items in the passlist.
This adds a validation check to ensure that is not possible.
Fixes #13114
Four scenarios to check:
1. If `blockNewUsers.enabled` is set to `false` and `blockNewUsers.passlist` is set to `[]` - this should pass
2. If `blockNewUsers.enabled` is set to `true` and `blockNewUser.passlist` is set to `[]` - this should fail
3. If `blockNewUsers.enabled` is set to `true` and `blockNewUser.passlist` is set to `["somedomain"]` - this should fail
3. If `blockNewUsers.enabled` is set to `true` and `blockNewUser.passlist` is set to …
=> [installer]: add validation rules to blockNewUsers in config block

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/cleanup-installer-tests.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile
This upgrade Leeway to the latest release (v.0.2.21)
Part of https://github.com/gitpod-io/gitpod/issues/12824
```release-note
NONE
```
N/A
=> Update leeway to v0.2.21

components/dashboard/src/Menu.tsx, components/dashboard/src/contexts/FeatureFlagContext.tsx
Since we have discoupled "usage" from stripe now, we can allow all users to use the usage view in order to understand how they use Gitpod (and where their hours go). This is also helpful to get a forecast of how many credits I'd need next month in case I want to switch to usage-based pricing.
This change enabled the usage view for everyone (depending on a feature flag, which is currently disabled for everyone in prod).
Fixes #
Login to the preview environment and see usage view on your individual account and all team accounts.
```release-note
Added a usage view that displays past workspace sessions on individual and team accounts.
```
=> [usage] Enable usage view with feature flag

operations/observability/mixins/meta/rules/usage.yaml
Fixes #
```release-note
NONE
```
=> [usage] Alert on Invoice Finalized

operations/observability/mixins/meta/dashboards/components/usage.json
Adds quick-links to the dashboard to jump to other relevant resources
Fixes #
```release-note
NONE
```
=> [usage] Add link to GCP logs and grpc server dashboard

operations/observability/mixins/meta/rules/usage.yaml
Alerts when stripe webhooks fail with 5xx errors
Fixes #
```release-note
NONE
```
=> [usage] Alert on Stripe webhook handling

components/usage/pkg/apiv1/usage.go, components/usage/pkg/db/cost_center.go, components/usage/pkg/db/usage.go, components/usage/pkg/db/usage_test.go
Reuses existing logic to perform CreditCents conversion
Fixes #
```release-note
NONE
```
=> [usage] Use credit cents when computing listed usage balance

components/dashboard/src/components/UsageView.tsx
Removes rounding of credits. We only store 2 decimal points, so we know that the total will also have at most 2 digits. That's okay to show in the UI.
* Fixes https://github.com/gitpod-io/gitpod/issues/13056
```release-note
NONE
```
=> [usage] Remove rounding of credits in UI

install/infra/modules/eks/storage.tf
When I removed the global access to fix https://github.com/gitpod-io/gitpod/issues/12964 it exposed the fact that our IAM permissions weren't correct to just use the S3 bucket.
```release-note
Attaches correct permissions to the IAM user to have correct level of access to just the single S3 bucket we create for that user.
```
=> Correct AWS Terraform arch to contain correct S3 permissions

components/gitpod-protocol/data/gitpod-schema.json, components/gitpod-protocol/go/gitpod-config-types.go, components/gitpod-protocol/src/protocol.ts, components/server/src/workspace/workspace-starter.ts, components/workspacekit/cmd/rings.go, components/ws-manager/pkg/manager/create.go
By default, core dumps are disabled. If we want to enable the feature, we need to update the .gitpod.yml file
```
coreDump:
enabled: true
```
Optionally we can set custom sizes
```
coreDump:
enabled: true
softLimit: <bytes>
hardLimit: <bytes>
```
Replaces #12814
Fixes https://github.com/gitpod-io/gitpod/issues/12453
**Tests:**
---
1. Default behavior
- Open a workspace https://aledbf-core.preview.gitpod-dev.com/#https://github.com/gitpod-io/template-python-django
- Run `ulimit -c` and check the value is 0
- Run `sleep 900&`
- Run `kill -s SIGSEGV [pid]`
- Check no `core.*` file exist
---
2. Enable core dumps
- Open a workspace https://aledbf-core.preview.gitpod-dev.com/#https://github.com/gitpod-io/template-python-django/tree/aledbf/enable-coredump
- Run `ulimit -c` and check the value is …
=> Enable configuration of core dump behavior

components/content-service-api/go/initializer.go, components/content-service-api/go/initializer_test.go
Adds the snapshot initializer to the `walkInitializer` function.
Fixes #12554
See unit test
```release-note
NONE
```
=> [content-service] Add snapshot initializer to walkInitializer

operations/observability/mixins/workspace/rules/workspaces.yaml
To fix this error:
`annotation \"description\": template: __alert_GitpodWorkspaceStuckOnStopping:1: malformed character constant: '%.2f'"`
Fixes #
```release-note
none
```
=> fix prometheus rule for workspaces

install/infra/modules/eks/kubernetes.tf
See https://github.com/gitpod-io/gitpod/issues/12740
Create a preview environment with werft:
```
werft run github -j .werft/eks-installer-tests.yaml -a skipTests=true -a deps=external -a preview=true
```
Once the preview is up, login to the node and confirm that image builds run on headless workspace nodes and workspaces run on regular-workspace nodes.
```release-note
[terraform/eks] Run regular and headless workspaces on separate node pools
```
=> [terraform/aws] Split up regular and headless workspace node groups

components/workspacekit/cmd/rings.go
If `GITPOD_RLIMIT_CORE` env variable it's empty we should not attempt to deserialize an empty string
Fixes https://cloudlogging.app.goo.gl/QYQWPUhwnjeTQiXD7
- Check there are no `cannot deserialize GITPOD_RLIMIT_CORE` errors.
```release-note
NONE
```
=> [workspacekit] Fix empty JSON deserialization error

components/server/ee/src/workspace/gitpod-server-impl.ts
If getting usage-based notifications fails, log a warning in `server` instead of propagating the error to the dashboard.
Should fix https://github.com/gitpod-io/gitpod/issues/13131
by silencing this error which happens when you have multiple teams with usage-based billing enabled:
```
Request getNotifications unsuccessful: 455/"Multiple teams have billing enabled."
```
More context [in Slack](https://gitpod.slack.com/archives/C027AUU7BC3/p1663683874566519?thread_ts=1663683642.094259&cid=C027AUU7BC3) (internal):
> > Should we display the prompt when we see this error?
> 
> I'd rather catch it locally and ignore it for now.
> The user will be prompted on next workspace start, anyway. 🧘
Hint: Reviewing without whitespace is easier: https://github.com/gitpod-io/gitpod/pull/13178/files?w=1 …
=> [server] If getting usage-based notifications fails, log a warning instead of propagating the error to the dashboard

components/dashboard/src/components/UsageView.tsx
Right-aligns credits and time in the usage view
* https://github.com/gitpod-io/gitpod/issues/13154
```release-note
NONE
```
=> [usage] Align credits and time in usage view

components/dashboard/src/Pagination/Pagination.tsx, components/dashboard/src/admin/ProjectsSearch.tsx, components/dashboard/src/admin/TeamsSearch.tsx, components/dashboard/src/admin/UserSearch.tsx, components/dashboard/src/admin/WorkspacesSearch.tsx
This change adds pagination support for the various admin dashboard list views.
Fixes #8983
```release-note
Admin dashboard now has pagination
```
=> [dashboard] add pagination to admin search

components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/GitpodServerLauncher.java
This PR aims to improve the user experience when connecting to a workspace using an expired token: The JB Gateway plugin refreshes the token, however while handling the first failed request exepction, the `ClientContainer` will hang for about 30 seconds while stopping.
After investigating deep into the implementation, we believe that the time is given to any existing client connection to be shutdown gracefully. By setting the stop timeout to zero, we effectively revoke this opportunity, however, in our case, we are confident that there are no more active connections so we can safely remove this period of time, which only slows down the opening of the IDE.
Fixes #12862 
0. Install [this](https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions/Dev/227116) version of the JB …
=> fix(jetbrains): gateway plugin hands on auth issue

operations/observability/mixins/IDE/dashboards/components/code-browser.json
Add resources load failed ratio to code-browser
Overview
Faster Link
Fixes #
See https://grafana.gitpod.io/d/O6T-Pf7Vz/vs-code-browser-overview-mustard?orgId=1
Their JSON should be similar (ignore `id` and `panel positon` etc)
```release-note
NONE
```
=> [observability] add resources load failed ratio to code-browser

components/dashboard/src/admin/WorkspacesSearch.tsx
This change disables workspace queries without a workspace or instance id for Saas.
Fixes #13208
```release-note
NONE
```
=> [admin] avoid global workspace queries in SaaS

components/server/src/config.ts, components/server/src/container-module.ts, components/server/src/liveness/liveness-controller.ts, components/server/src/server.ts, install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/server/configmap.go, install/installer/pkg/components/server/deployment.go, install/installer/pkg/components/server/types.go
Add a liveness probe for `server`.
The probe fails iff the nodejs event loop lag (as reported by a prometheus metric) exceeds the value set in `server` config.
**Context**:
We have an alert and corresponding [runbook](https://github.com/gitpod-io/runbooks/blob/main/runbooks/ServerEventLoopLagTooHigh.md) which fires when the event loop lag exceeds a certain threshold. The runbook simply advises the operator to restart the affected pods, something that should not require manual intervention.
1. Edit the `server-config` configmap to change the `maximumEventLoopLag` setting.
2. Restart the `server` pod after changing the configmap.
3. Hit `<preview-url>/api/live` to see the current event loop lag and see the response code change according to the current value of `maximumEventLoopLag`. …
=> [server] Add a liveness probe for event loop lag

.github/workflows/code-nightly.yaml, .github/workflows/jetbrains-auto-update-template.yml
Our IDE GH action failed [Code Browser](https://github.com/gitpod-io/gitpod/actions/runs/3102007944) / [JetBrains Nightly](https://github.com/gitpod-io/gitpod/commit/0acc0b30ec8e742dde87203eabe7d8f03db88221/checks)
This PR upgrade leeway to fix problem
Fixes #
- ✅ Run GH Action for code https://github.com/gitpod-io/gitpod/actions/runs/3106399782
- ✅ Action for JetBrains https://github.com/gitpod-io/gitpod/actions/runs/3106401962
```release-note
NONE
```
=> [github-action] upgrade leeway to v0.2.21

.werft/observability/manifests/monitoring-satellite.yaml
Following up from https://github.com/gitpod-io/observability/pull/323, this PR adds an attribute to traces that are emitted by Gitpod in preview environments. This is being done so engineers can filter spans in Honeycomb that are specific for the preview environment they're working on.
Fixes #
* Start a workspace from this PR
* Spin up a preview environment
* Start a workspace from the preview just to create some spans
* Search for traces where `preview.name = <your preview name>`
```release-note
NONE
```
=> previews: Add attribute to spans so they can be filtered in Honeycomb

components/ide/jetbrains/image/status/main.go
A user should be able to apply vmoptions to configure different proxies and custom repositories to install plugins in restricted networks or to bring proprietary plugins.
Internal discussion [[1](https://gitpod.slack.com/archives/C02CBKZEVS8/p1663324410457839)]
- configure **latest** IntelliJ IDEA as IDE: https://ak-plugins-vmoptions.preview.gitpod-dev.com/preferences
- configure VM options and plugins in .gitpod.yml: https://github.com/gitpod-io/spring-petclinic/blob/ak/vmoptions_test/.gitpod.yml#L18
- start a workspace: https://ak-plugins-vmoptions.preview.gitpod-dev.com#https://github.com/gitpod-io/spring-petclinic/tree/ak/vmoptions_test
- open logs in VS Code Browser: `/workspace/.cache/JetBrains-latest/RemoteDev-IU/_workspace_spring-petclinic/log/idea.log`
- check that VM options are …
=> [jetbrains] apply vmoptions while installing plugins

components/ws-manager/pkg/manager/monitor.go
if there are hundreds of volume snapshots, wsman will spam a lot on restart, which can cause issues.
Fixes #
```release-note
none
```
=> [ws-manager] make sure wsman does not spam in log on restart

components/content-service/pkg/git/git.go, components/content-service/pkg/initializer/git.go, test/tests/workspace/contexts_test.go
Partially reverts #13053 due to not tracking remote branches, something that impacts the commit used in the workspace (not the last one)
Internal report https://gitpod.slack.com/archives/C01KGM9BH54/p1663846572842519
- Open a workspace using a branch [https://github.com/gitpod-io/spring-petclinic/tree/ak/vmoptions_test](https://ak-plugins-vmoptions.preview.gitpod-dev.com/#https://github.com/gitpod-io/spring-petclinic/tree/ak/vmoptions_test)
```release-note
NONE
```
=> Track git branches during initial checkout

components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
As part of https://github.com/gitpod-io/gitpod/issues/12685, several server APIs were generalised to work on user attribution ids as well as team attribution ids:
* https://github.com/gitpod-io/gitpod/pull/12753
* https://github.com/gitpod-io/gitpod/pull/12876
* https://github.com/gitpod-io/gitpod/pull/12864
* https://github.com/gitpod-io/gitpod/pull/12767
* https://github.com/gitpod-io/gitpod/pull/12887
With https://github.com/gitpod-io/gitpod/pull/12942 and https://github.com/gitpod-io/gitpod/pull/12954, the more specific team-only APIs are no longer used by the dashboard and are safe to remove.
⚠️ https://github.com/gitpod-io/gitpod/pull/12942 and https://github.com/gitpod-io/gitpod/pull/12954 need to be deployed first ⚠️  …
=> [UBP] Remove team specific Stripe APIs from `server` JSON-RPC API

components/usage/pkg/server/server.go
To re-use existing setup and configuration for grpc clients. We get uniformity and ability to better track metrics
Fixes #
```release-note
NONE
```
=> [usage] Use DefaultClientOptions when creating grpc client connection

components/gitpod-db/src/index.ts, components/gitpod-db/src/typeorm/entity/db-prebuild-info-entry.ts, components/gitpod-db/src/typeorm/entity/db-prebuilt-workspace-updatable.ts, components/gitpod-db/src/typeorm/entity/db-prebuilt-workspace.ts, components/gitpod-db/src/typeorm/metrics.ts, components/gitpod-db/src/typeorm/workspace-db-impl.ts, components/server/ee/src/monitoring-endpoint-ee.ts, components/server/src/prometheus-metrics.ts, components/server/src/workspace/workspace-deletion-service.ts
When we delete Workspaces, we also need to delete corresponding prebuilds when the Workspace is based on a prebuild.
* Depends on https://github.com/gitpod-io/gitpod/pull/13165
```release-note
NONE
```
=> [server] Delete prebuild records when purging workspaces

WORKSPACE.yaml
I'm trying to make it easier to run a full leeway build from a Gitpod workspace in https://github.com/gitpod-io/ops/issues/5411. This PR sets a default values `imageRepoBase` so you don't have to pass it in using `-DimageRepoBase=xxx`
Part of https://github.com/gitpod-io/ops/issues/5411
Running `leeway build` in the root not won't complain about a missing value for `imageRepoBase`.
```release-note
NONE
```
N/A
=> Set default value for imageRepoBase

.werft/jobs/build/validate-changes.ts
Run pre-commit checks before other validation checks. Since running the validation steps in parallel we've seen issues with multiple processes trying to modify .git. We think this might be a conflict between the pre-commit checks and the other validations; specifically that both pre-commit checks and `leeyway vet` run Leeway. This PR runs the pre-commit checks first, and then runs the rest in parallel.
This is mainly based on a hunch - as this is breaking builds now I decided to try a quick-fix rather than do a deep investigation.
Fixes https://github.com/gitpod-io/ops/issues/5345
Run without job protection to see the changes - job [here](https://werft.gitpod-dev.com/job/gitpod-build-mads-run-pre-commit-before-other-validations.2)
```sh
werft job run github
```
```release-note
NONE
``` …
=> Run pre-commit checks before other validation checks

operations/observability/mixins/meta/dashboards.libsonnet, operations/observability/mixins/meta/dashboards/components/server-garbage-collector.json
Currently shows no data in staging because we've not run the GC there yet.
Fixes #
```release-note
NONE
```
=> [server] Add dashboard for garbage collection

components/usage/pkg/server/server.go
This reverts commit 0f5d689ce5af15e87f2c16a82f644c66b531cbd4.
Fixes #
```release-note
NONE
```
=> Revert "[usage] Use DefaultClientOptions when creating grpc client connection

components/server/src/workspace/workspace-deletion-service.ts
Those snapshots would not be accessible anyway after we've garbage collected the Workspace.
Fixes #
```release-note
NONE
```
=> [server] Always GC snapshots for workspaces

components/gitpod-cli/BUILD.yaml
This uses the Leeway package version when populating `versions.txt` - the motivation for this change is to improve build speed. When we use `argdeps` the package build cache will be invalidated whenever the argument changes. So having an argdeps on `version` means that we'll rebuild `components/gitpod-cli:version` and `components/gitpod-cli:app` on every CI build. Because `components/supervisor:docker` depends on `components/gitpod-cli:app` it means we'll rebuild that every time too.
This will reduce our build speeds by 38s (based on the example shown below).
**Discussion**: I went with using the Leeway package version. We could also use the git commit (`__git_commit`) or even use `version` but then just know it will only be bumped when the package is actually modified. We could also …
=> Build speed: components/supervisor:docker and glitpod-cli

WORKSPACE.yaml, install/kots/BUILD.yaml, install/kots/Makefile
I'm trying to make it easier to run a full `leeway` build from a Gitpod workspace in https://github.com/gitpod-io/ops/issues/5411. This PR sets default values for REPLICATED_API_TOKEN and REPLICATED_APP to be the empty string and changes `install/kots:lint` such that it will skip linting if the values are not set.
Part of https://github.com/gitpod-io/ops/issues/5411
With this change you can run `leeway build install/kots:lint` and it will skip the linting which means the package builds:
```
leeway build install/kots:lint
```
```
☁️  checking remote cache for past build artifacts
🔧  build  install/kots:lint  (version 797e97ea2f4b8781d619ecf20e14d2beff0da576)
[install/kots:lint] build started (version 797e97ea2f4b8781d619ecf20e14d2beff0da576)
[install/kots:lint] Installing Helm dependencies …
```
=> Only lint in install/kots:lint if env vars are set

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/server/configmap.go
We've nearly gone through all the records from > 2 years
Fixes #
```release-note
NONE
```
=> [server] Purge records older than 1 year from content deletion

install/kots/manifests/gitpod-log-collector.yaml
This ensures that the `/gitpod/log-collector` directory exists on every node at FluentBit startup. Previously, this directory was only created when a log was added which meant that the `log-collector` section in a support bundle was full of `configmap-errors` saying that the directory didn't exist.
Now, this only adds files into the support bundle if there are files to add, meaning that it's much easier to search for things to look through.
Fixes #13095
Install via KOTS and generate a support bundle
```release-note
[kots]: ensure log-collector directory on node at startup
```
=> [kots]: ensure log-collector directory on node at startup

.werft/jobs/build/self-hosted-upgrade-tests.ts, install/tests/cleanup.sh
During the upcoming release, we are changing the process to have preview setups with the latest version up for the whole week or until explicitly cleaned up. This is a temporary solution that avoids cleaning up of resources, if the terraform state(or the subdomain) starts with a `release-` prefix.
Fixes #
Try running the following:
```
werft run github -j .werft/k3s-installer-tests.yaml -a subdomain=release-tests-abc -a preview=true
```
you will see that the setup do not get cleaned up after 10 hours.
```release-note
NONE
```
=> [installer-tests] avoid cleaning up preview setup for release branches

components/gitpod-db/src/typeorm/migration/1663784254956-IndexPhoneNumber.ts, components/gitpod-db/src/typeorm/user-db-impl.ts, components/gitpod-db/src/user-db.ts, components/gitpod-protocol/src/messaging/error.ts, components/server/src/auth/verification-service.ts, components/server/src/user/phone-number.spec.ts, components/server/src/user/phone-numbers.ts, components/server/src/workspace/gitpod-server-impl.ts
Adds checks for phone numbers being used by abusers or used too often (>3) 
Fixes #12883
```release-note
Restrict reuse of phone numbers for verification
```
=> [server] don't allow more than three usages per phone number

components/BUILD.yaml
Removes reference to `install/preview:docker` build target
Context: previous PR removing said target:  #13093
```release-note
NONE
```
=> Cleanup after #13093

install/infra/modules/eks/kubernetes.tf, install/infra/modules/eks/output.tf, install/infra/modules/gke/cluster.tf, install/infra/modules/gke/database.tf, install/infra/modules/gke/local.tf, install/infra/modules/gke/output.tf, install/tests/Makefile, install/tests/cleanup.sh, install/tests/manifests/aws-auth.yaml, install/tests/output.tf
This PR basically adds a couple of make targets that will push user credentials for accessing `kubeconfig` of clusters created using the pipeline. The connection is slightly different for each managed cluster (documented in this [internal doc](https://www.notion.so/gitpod/Self-hosted-automated-preview-and-test-pipelines-fdc5a202e67b4197aa00d93b98d57927#ca0424f42ed44aa69b8c57a2b07d9c7f)):
1. GKE: A user is created that has cluster developer access, and a JSON key is created for the same user. This key is uploaded to the GCS bucket we use for terraform backend. When the user needs access to it, they can login using `gcloud auth login` and running the make target `make get-kubeconfig` after setting the variable `TF_VAR_TEST_ID`
2. k3s: The default workflow of K3s currently involves uploading …
=> [installer-tests] add make targets to backup k8s user creds 

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/ide-metrics/configmap.go
Add ide-metrics allowed components for vscode
Fixes #
No need
```release-note
NONE
```
=> Add ide-metrics allowed components for vscode

.werft/observability/install-satellite.sh
In preparation for https://github.com/gitpod-io/observability/pull/326, this PR adds the required flag to install monitoring-satellite
Fixes https://github.com/gitpod-io/ops/issues/5207
```release-note
NONE
```
=> Previews: Add required flag to install monitoring-satellite

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/workspace/ide/constants.go
Commit hash is from [werft job](https://werft.gitpod-dev.com/job/gitpod-build-hw-build-vs-ep.1/results)
Bring error reporting https://github.com/gitpod-io/openvscode-server/commit/139f4a443cbbb868a3c61e130a0f63c2dfb655f6 to stable
Fixes #
Tested in previous [PR](https://github.com/gitpod-io/openvscode-server/pull/438)
Open workspace with stable code in prev env, check if commit hash in `About` page is equal to `968fb943b510de16a4c516886f6aa38ead65cb5c`
```release-note
NONE
```
=> [code] update stable browser code for error report

components/content-service/pkg/git/git.go, components/content-service/pkg/initializer/git.go
Avoid reverting the changes https://github.com/gitpod-io/gitpod/pull/13210 and https://github.com/gitpod-io/gitpod/pull/13053
Open different workspaces that triggered the changes
- https://aledbf-git.preview.gitpod-dev.com/#https://github.com/gitpod-io/dazzle
- https://aledbf-git.preview.gitpod-dev.com/#https://github.com/gitpod-io/dazzle/commit/ddbf82c1a4dc95bda26c9f299d8e3b8f84eb659d
- https://aledbf-git.preview.gitpod-dev.com/#prebuild/https://github.com/gitpod-io/dazzle
- https://aledbf-git.preview.gitpod-dev.com/#https://github.com/NixOS/nixpkgs
- https://aledbf-git.preview.gitpod-dev.com/#prebuild/https://github.com/NixOS/nixpkgs
- https://aledbf-git.preview.gitpod-dev.com/#https://github.com/gitpod-io/spring-petclinic/tree/ak/vmoptions_test
- …
=> [content-service] Fix git checkout

operations/observability/mixins/platform/rules/kubernetes/kubernetes.yaml
This way, on-callers now how to respond to the alert. For example, to [avoid node deletion](https://gitpod.slack.com/archives/C01TNS8EVQT/p1663922870185839).
Fixes # n/a
N/A
```release-note
NONE
```
=> Link existing KubeNodeNotReady runbook to alert

.werft/aks-installer-tests.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/installer-tests.ts, .werft/k3s-installer-tests.yaml, install/tests/Makefile
This PR makes the Domain name configurable for self hosted installer tests. The main drive here is to still run the tests even after we hit the let's encrypt cert limits. This is a very tiny workaround. The domain we provide should be registered under CloudDNS under the project `dns-for-playgrounds`(the project will change in the future) with a zone name same as the domain but `.` replaced by `-`. For eg, if the domain is `tests.doptig.com`, it expects the domain to be registered under the name `tests-doptig-com`(this is how we currently do it under `dns-for-playgrounds` project.
Fixes #
You can something like the following:
```
werft run github -j .werft/k3s-installer-tests.yaml -a skipTests=true -a domain=tests.doptig.com -a subdomain=testing-abc
```
```release-note
NONE
```
If enabled …
=> [installer-tests] make domain name configurable

operations/observability/mixins/cross-teams/dashboards.libsonnet, operations/observability/mixins/cross-teams/dashboards/gitpod-grpc-client.json
See dashboard in action [here](https://grafana.gitpod.io/d/dxEjpXn4z/grpc-client?orgId=1&from=now-24h&to=now)
The dashboard is the same as the existing `gRPC / Server` but with client-side metrics.
Currently latency is not being reported and hence no data showing up in the latency section.
Fixes #
```release-note
NONE
```
=> [grafana] Add gRPC Client dashboard with metrics

.werft/installer-tests.ts, .werft/jobs/build/self-hosted-upgrade-tests.ts, install/tests/Makefile
I introduced a regression earlier today, by which the terraform state names didn't include the cloud provider name. This PR fixes this
Fixes #
```release-note
NONE
```
=> [installer-tests] fix the subdomain for upgrade tests to include cloud

components/ws-daemon/debug.Dockerfile, components/ws-daemon/leeway.Dockerfile
Ensure download is a binary
Also update cloud SDK to v402.
```
root@g70c9281d74ad68b6cd195b:/home/aledbf# k exec -it -c ws-daemon ws-daemon-v7skj -- bash
root@ws-daemon-v7skj:/# which runc
/usr/bin/runc
root@ws-daemon-v7skj:/# runc
/usr/bin/runc: line 1: syntax error near unexpected token `<'
/usr/bin/runc: line 1: `<?xml version="1.0" encoding="utf-8"?><Error><Code>ServerBusy</Code><Message>Egress is over the account limit.'
root@ws-daemon-v7skj:/# 
``` 
```release-note
NONE
```
=> [ws-daemon] Check runc download is a binary

.werft/workspace-run-integration-tests.sh
Check for any remaining integration tests previously run before starting the test. This reduces wasteful preview environments.
Relaates https://github.com/gitpod-io/gitpod/issues/12248#issuecomment-1246566840
1. Appropriately short timeouts to simplify testing
2. Create a branch for the test
```console
$ branch="wk-inte-test/$(date +%Y%m%d%H%M%S)"
$ git branch $branch
$ git push origin $branch 
```
3. Run the integration test and check it
e.g. https://werft.gitpod-dev.com/job/gitpod-custom-to-gc-inte-br.5
```release-note
NONE
```
No
=> test: Add a gc for integration branches

components/dashboard/src/projects/NewProject.tsx
Adds a simple HTML title to each item of the "New project" dropdown repo list, with the clone URL
Fixes #11917
- Start the dashboard app
- Go to the "New project" page
- Hover over an item in the repo dropdown list and wait for the title to show up
```release-note
[dashboard] While creating a new project, if you are using GitLab and have several repositories with the same exact name organized in different groups, you will now be able to tell them apart by hovering over each of them in the dropdown list.
```
=> [dashboard] add cloneUrl to repo dropdown

.werft/vm/manifests.ts
- Workspaces should open without issues
- Check k3s version is 1.23.9
- Check kernel version is 5.15.0-47-generic
```release-note
NONE
```
=> [harverster] Sync VM image

operations/observability/mixins/meta/rules/usage.yaml
Prometheus operator has been failing with this error:
```
range vector in call to function \"increase\", got instant vector"
level=info ts=2022-09-23T13:31:35.581579042Z caller=rules.go:340 component=prometheusoperator msg="Invalid rule" err="35:11: group \"usage\", rule 3, \"GitpodUsageBillingServiceFinalizeInvoiceFailures\": could not parse expression: 1:14: parse error: expected type range vector in call to function \"increase\", got instant vector"
level=info ts=2022-09-23T13:31:35.581586956Z caller=rules.go:340 component=prometheusoperator msg="Invalid rule" err="61:11: group \"usage\", rule 5, \"GitpodUsageStripeWebhookFailures\": could not parse expression: 1:14: parse error: expected type range vector in call to function \"increase\", got instant vector"
level=error …
```
=> [usage] Fix alerting rules

install/infra/single-cluster/gcp/Makefile, install/infra/single-cluster/gcp/README.md
Adds a few details to GCP single cluster reference architecture install. Also fixes `jq` syntax on `make output` task.
Run `make output` on an install
```release-note
NONE
```
=> GCP Reference Arch installer minor fixes

install/infra/single-cluster/aws/README.md, install/infra/single-cluster/azure/README.md, install/infra/single-cluster/gcp/README.md
Changes mention of which k8s versions are support to instead point to the compatibility matrix in the docs. 
Read through files changed
```release-note
NONE
```
=> Change definition of k8s version support to point to prod comp matrix

components/gitpod-protocol/src/encryption/encryption-engine.spec.ts, components/gitpod-protocol/src/encryption/encryption-engine.ts, components/gitpod-protocol/src/encryption/key-provider.ts, components/ws-manager-bridge/src/messagebus-integration.ts
Trying to get rid of deprecation log entries.
Fixes #
```release-note
NONE
```
=> [server] use Buffer.from properly

install/installer/pkg/config/v1/envvars.go, install/installer/pkg/config/v1/testdata/envvars/config-patch-no-advanced-mode/envvars.yaml, install/installer/pkg/config/v1/testdata/envvars/config-patch-no-advanced-mode/expect.yaml
Spotted a regression in the Installer refactoring where a config patch could be applied if advanced mode isn't enabled. This fixes it.
```release-note
[installer]: only allow config patch if advanced mode enabled
```
=> [installer]: only allow config patch if advanced mode enabled

install/installer/cmd/testdata/render/insecure-s3-setup/config.yaml, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/pkg/common/storage.go, install/installer/pkg/config/v1/config.go
We often tell people that, if they're unable to use the configuration of the in-cluster Minio that they should deploy their own to their cluster and connect to it over the Kubernetes core DNS. However, this isn't currently possible because the S3 connection expects for it to be over HTTPS. When using a local Kubernetes endpoint, this is likely to be over HTTP.
This allows for an S3 endpoint to use an insecure URL.
The default expectation of it being over HTTPS has not changed.
Fixes #6776
Fixes #9698 
Fixes #12416
Deploy the [KubeCon demo](https://github.com/MrSimonEmms/gitpod-self-hosted-demo) instance (run `make` on an Ubuntu machine). We need this for KubeCon as the default 8Gi PVC is not large enough, so need to configure a larger PVC.
```release-note
[installer]: allow the s3 …
```
=> [installer]: allow the s3 connection to be insecure

components/common-go/baseserver/server.go
Quite false positive error, see [[1](https://console.cloud.google.com/errors/detail/CKmX-siSlbaatgE;service=ide-service;version=?project=gitpod-191109)]
Fixes #
Unit tests should pass.
```release-note
NONE
```
=> [baseserver] do not log error when the server successfully closes

components/gitpod-db/src/tables.ts
Remove a duplicate entry for the `d_b_prebuilt_workspace` table from the `db-sync` config. 
The removed entry is the same as the remaining one but lacked the `deletionColumn` definition. 
Looking at the EU failover we have many entries in `d_b_prebuilt_workspace`  for which `deleted = 1`, which would indicate that only the entry without the `deletionColumn` was ever respected. Merging this will therefore delete those records permanently.
Relates to https://github.com/gitpod-io/gitpod/issues/9198
```release-note
NONE
```
=> [db-sync] Remove duplicate entry for `d_b_prebuilt_workspace`

components/server/ee/src/prebuilds/github-app.ts
Before this PR, only push events were recorded. Because Pull Requests updates are also triggers for prebuilds, they should be registered as well.
Fixes #12817
Inspect `<PREVIEW-URL>/t/<TEAM>/<PROJECT>/events` for events recorded for updates of pull requests on `PROJECT` repository. 
```release-note
NONE
```
=> [server][github] record "pull" webhook events

install/kots/manifests/kots-app.yaml
This prevents the preflight checks from being run in some environments (eg, EKS) as there are elevated privileges required to interrogate nodes etc.
There was a misunderstanding from the KOTS docs made in #13168 which I thought created the `kotsadm` service account. This service account appears to always be created, but this boolean limits it's capabilities (in retrospect, that's obvious. But it wasn't at the time - we caught it before it was released to the public anyway).
Deploy via KOTS on AWS. Preflight checks should run - previously, they were not running due to lack of cluster role permissions. With this fix, they should run.
```release-note
[kots]: remove the "require min RBAC" boolean
``` …
=> [kots]: remove the "require min RBAC" boolean

.werft/aks-installer-tests.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/installer-tests.ts, .werft/jobs/build/self-hosted-upgrade-tests.ts, .werft/k3s-installer-tests.yaml, install/tests/Makefile
This PR integrates the SCM authentication when running integration tests. The changes included here are the follows:
- Using the `GITHUB_SCM_OAUTH` env var to provide the secret in core-dev cluster that stores the github token for github app
- The secret will be appended with the `callBackURL`. This URL would point to an nginx server we have setup that will redirect to the correct subdomian specified using `state` query parameter
- The above changes are added only when integration tests are run, otherwise we expect the users to have the opportunity to connect to their preferred SCM
- The PR also changes one of the existing annotation `skipTests` to `runTests`. This is mostly because, we don't want the test running a default behavior, but an explicitly specified one. 
- The PR also updates …
=> [installer-tests] Add SCM authentication for integration tests

dev/preview/util/portforward-monitoring-satellite-harvester.sh
Port forwarding to Grafana/Prometheus in preview environments is broken at the moment. We get an error when we try to visit the page. See below:
```
gitpod /workspace/gitpod (ak/supervisor_observability) $ ./dev/preview/portforward-monitoring-satellite.sh -c harvester
Starting port-forwarding:
Prometheus:
https://9090-gitpodio-gitpod-ijwocmzi0o3.ws-eu67.gitpod.io
Grafana:
https://3000-gitpodio-gitpod-ijwocmzi0o3.ws-eu67.gitpod.io
Forwarding from 127.0.0.1:9090 -> 32001
Forwarding from [::1]:9090 -> 32001
Forwarding from 127.0.0.1:3000 -> 32000
Forwarding from [::1]:3000 -> 32000
Handling connection for 3000
E0926 13:52:32.090059   23719 portforward.go:406] an error occurred forwarding 3000 -> 32000: error forwarding port 32000 to pod …
```
=> Port-forward directly to k3s

components/server/ee/src/prebuilds/prebuild-manager.ts, components/server/src/workspace/workspace-starter.ts, components/ws-manager-bridge/ee/src/prebuild-updater-db.ts
Before this PR, if an image build started for a prebuild errored, e.g. due to issues with the .Dockerfile, it would mark the workspace instance as stopped, but leave the prebuild workspace entry in "PENDING" state. That causes the UI to remain in same state, which is worsened by the fact that image build logs are not persisted. 
This PR adds the missing update to the prebuild workspace entry, which will produce UI state updates as well.
Fixes #13207
Try with prebuilds for a repo with .Dockerfile build and simple errors in it, e.g. `apt-get install NOT-FOUND`, see the prebuilds is rendered as failed and does not remain in PENDING state.
```release-note
Fail prebuild if image build fails.
```
=> [server] mark prebuild as failed when image build fails

install/tests/Makefile
I introduced a bug in a recent PR that checked if `self_signed` is false instead of true for the install condition for cluster issuer. This PR fixes the bug.
Fixes #
```release-note
NONE
```
=> [installer-tests] Fix the condition for cluster-issuer install

License.txt
Fixes a pointer to a non-existing file name.
Fixes # https://github.com/gitpod-io/gitpod/issues/12639
```release-note
NONE
```
=> Fix pointer to a non-existing file.

install/tests/Makefile
Currently cluster-issuer is not getting installed in test setups due to wrong condition on a Makefile. This PR fixes that issue
Fixes #
```release-note
NONE
```
=> [installer-tests] fix cluster-issuer install test condition

install/installer/BUILD.yaml, install/installer/leeway.Dockerfile, install/installer/scripts/kots-install.sh, install/kots/manifests/gitpod-installation-status.yaml, install/kots/manifests/gitpod-installer-job.yaml, install/kots/manifests/kots-preflight.yaml
Adds a preflight check to see if there are any workspaces/image-builds running. It fails if there is one (the `textAnalyzer` doesn't allow for `warn`, which is very annoying as this isn't really a failure, but a warning).
It also stops any running workspaces/image-builds prior to the `helm upgrade` function being executed.
Fixes #13147
Try installing via KOTS both with and without a workspace running.
```release-note
[kots]: delete workspace pods before installing Gitpod
```
=> [kots]: delete workspace pods before installing Gitpod

install/kots/manifests/kots-support-bundle.yaml
As part of https://github.com/replicated-collab/replicated-gitpod/issues/52, Replicated notified us that the `troubleshoot.replicated.com/v1beta1` apiversion is deprecated.
Deploy via KOTS and create a support bundle, eg [this example](https://vendor.replicated.com/troubleshoot/analyze/2022-09-26@19:20) what I've just generated
```release-note
[kots]: update the support bundle to use the latest apiversion
```
=> [kots]: update the support bundle to use the latest apiversion

components/ws-daemon/pkg/content/initializer.go
add addional tracing for remoteContentStorage Download function (after viewing some traces, realized I am missing that info to build better picture of what is going on).
Related to https://github.com/gitpod-io/gitpod/issues/12345
Fixes #
```release-note
none
```
=> add addional tracing for remoteContentStorage Download fn

components/content-service/pkg/initializer/git.go
- https://aledbf-head.preview.gitpod-dev.com/#https://github.com/gitpod-io/dazzle
- https://aledbf-head.preview.gitpod-dev.com/#https://github.com/gitpod-io/dazzle/commit/ddbf82c1a4dc95bda26c9f299d8e3b8f84eb659d
- https://aledbf-head.preview.gitpod-dev.com/#prebuild/https://github.com/gitpod-io/dazzle
- https://aledbf-head.preview.gitpod-dev.com/#https://github.com/NixOS/nixpkgs
- https://aledbf-head.preview.gitpod-dev.com/#prebuild/https://github.com/NixOS/nixpkgs
- https://aledbf-head.preview.gitpod-dev.com/#https://github.com/gitpod-io/spring-petclinic/tree/ak/vmoptions_test
- https://aledbf-head.preview.gitpod-dev.com/#prebuild/https://github.com/gitpod-io/empty
- https://aledbf-head.preview.gitpod-dev.com/#github.com/gitpod-io/gitpod-test-repo/issues/88
Fixes #13284
```release-note …
```
=> [content-service] Fix checkout local HEAD branch

install/infra/modules/eks/storage.tf
This PR essentially reverts [this one](https://github.com/gitpod-io/gitpod/pull/12965/files). Even though with AWS CLI the permission seems enough, `mc` cli that we use for preflights(probably for other ops in Gitpod, not sure) requires a lot more permissions to do S3 ops. This is made clean in their documentation [here](https://github.com/minio/mc#example---amazon-s3-cloud-storage).
Fixes #13017 
You can run the pipeline using:
```
werft run github -j .werft/eks-installer-tests.yaml -a deps=external -a domain=tests.doptig.com
```
```release-note
NONE
```
=> [terraform] Give AWSS3FullAccess to s3 IAM users

components/ee/payment-endpoint/src/accounting/account-service-impl.ts, components/gitpod-protocol/src/protocol.ts, components/server/src/workspace/workspace-factory.ts, components/server/src/workspace/workspace-starter.ts
Last workspace probe was April 2021.
* Relates to https://github.com/gitpod-io/gitpod/issues/11315
```release-note
NONE
```
=> [server] Remove handling of Probe Workspaces

components/server/ee/src/workspace/workspace-factory.ts
The process of triggering a prebuild is async and competing events may cause a race which results in two prebuilds being started for the same commit. This practical PR introduces repeated check for already started prebuild to reduce the likelihood of prebuilds started for the same commit.
Fixes #11757
Note, this is easier to verify with https://github.com/gitpod-io/gitpod/pull/13292 been merged before, because one can inspect webhook events and compare with prebuild triggered.
Nevertheless, to verify a single prebuild is produced one needs:
* setup a project for a repo
* create a PR on that test repo which would produce a prebuild, see a prebuild is running
* verify that a PR update (force pushing a significant change, to produce a new build) is also triggering just a single prebuild per …
=> [server][prebuild] assert no prebuild is running for same commit

.werft/jobs/build/payment/stripe-configmap.yaml
Update Stripe price IDs used for individuals in Werft preview environments.
This slightly simplifies the pricing tiers for individuals. [Context](https://gitpod.slack.com/archives/C027AUU7BC3/p1664209231957839?thread_ts=1664191425.697079&cid=C027AUU7BC3) (internal)
Fixes #
```release-note
NONE
```
=> Update Stripe price IDs used for individuals in Werft preview environments

components/server/ee/src/user/stripe-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts
Refactor `StripeService.getPortalUrl` to take an `attributionId` instead of a `userId` or `teamId`.
Note: I know that we may want to eventually move `StripeService` over to the `usage` component (or, maybe better, to a dedicated `billing` component) as per https://github.com/gitpod-io/gitpod/issues/13198. However, this at least gives a cleaner API that could be migrated as is (i.e. no user- or team-specific methods, only attributionIds).
Fixes #
1. Subscribe to Stripe
2. Opening the Stripe customer portal should still work
```release-note
NONE
```
=> [server] Refactor StripeService.getPortalUrl to take an attributionId instead of a userId or teamId

.github/workflows/code-nightly.yaml, .github/workflows/jetbrains-auto-update-template.yml, .gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/cleanup-installer-tests.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environment.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile
To get golangci-lint 1.49.0 (go1.19 support)
```release-note
NONE
```
=> Update workspace-full image

install/infra/modules/k3s/output.tf, install/infra/single-cluster/k3s/Makefile, install/infra/single-cluster/k3s/cluster.tf, install/infra/single-cluster/k3s/local.tf, install/infra/single-cluster/k3s/main.tf, install/infra/single-cluster/k3s/output.tf, install/infra/single-cluster/k3s/terraform.tfvars, install/infra/single-cluster/k3s/tools.tf, install/infra/single-cluster/k3s/variables.tf
This PR adds a very rough single-cluster setup for k3s. We are adding this for consistency with Azure, AWS and GCP setups so we can consistently run the tests. We do not recommend users to use this because the underlying module still make use of `k3sup` and we have plans to move to `k3s` before suggesting this as a solution. Hence we have not included a Readme with this directory.
Fixes #12866
* Go to the directory `install/infra/single-cluster/k3s`.
* Edit `main.tf` to have the right bucket name.
* Edit `terraform.tfvars` to right parameters for the cluster.
Then run:
```
make init
make plan
make apply
make destroy
```
```release-note
NONE
```
=> [terraform] Add k3s setup for tests

install/installer/scripts/kots-install.sh
Delete service account and cluster role binding in the Installer script. KOTS doesn't delete old manifests that have been removed during upgrades, so we have to do it ourselves
```release-note
[installer]: delete old kots serviceaccount/clusterrolebinding
```
=> [installer]: delete old kots serviceaccount/clusterrolebinding

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/cleanup-installer-tests.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environment.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile
This PR bumps leeway to the latest release to prepare for Go workspaces.
```release-note
NONE
```
=> Bump leeway to v0.3.1

components/gitpod-db/src/typeorm/migration/1664271007635-RemoveEmailNotificationTable.ts
Remove the unused`d_b_email_notification_data` table. 
The table is empty in both regions.
Part of #9198 
```release-note
NONE
```
=> [db] Remove `d_b_email_notification_data` table

install/infra/single-cluster/aws/cluster.tf, install/infra/single-cluster/gcp/cluster.tf
Update the node size for GCP and AWS self hosted reference architectures as laid out in https://github.com/gitpod-io/website/pull/2790.
Related to https://github.com/gitpod-io/website/pull/2790
Not sure, would appreciate some pointers.
```release-note
Update node sizes for self hosted reference architectures
```
=> [refarch] Update node size for GCP and AWS

components/gitpod-db/src/typeorm/migration/1664275537873-RemoveGeneratedLicenseTable.ts
Remove the unused `d_b_generated_license` table from the database.
The last entry in here was created in November 2020.
Part of #9198 
```release-note
NONE
```
=> [db] Remove `d_b_generated_license` table

.werft/jobs/build/payment/stripe-configmap.yaml, components/gitpod-protocol/src/protocol.ts, components/server/ee/src/user/stripe-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts
Use different Stripe Price IDs when subscribing individuals vs teams.
Fixes https://github.com/gitpod-io/gitpod/issues/13302
1. Subscribe to usage-based as a team
2. In the Stripe admin dashboard, your team's subscription should be linked to a "Team" price (pay-as-you-go)
3. Subscribe to usage-based as an individual
4. In the Stripe admin dashboard, your user's subscription should be linked to an "Individual" price (discounted flat rate + pay-as-you-go)
```release-note
NONE
```
=> Use different Stripe Price IDs when subscribing individuals vs teams

.werft/jobs/build/installer/installer.ts
Create two workspace classes in the preview environment so we can test workspace classes in the preview environment.
- Default workspace class with 30Gi disk
- Small workspace class with 20Gi disk
Related to #12638
- Open the workspace preview.
- Enable the feature flag PVC.
- Open the workspace, and check the PVC size is 30Gi.
- Change your workspace class preference to 20Gi
- Open a new workspace, and check the PVC size is 20Gi.
```release-note
None
```
None
=> preview env: create two workspace classes default and small

install/kots/manifests/kots-support-bundle.yaml
Add configuration to collect KOTS configmaps. This is to get more information about how the KOTS app is configured, including the redactors (Gitpod and custom).
See an example support bundle
- [kotsadm-gitpod-redact-spec.json](http://localhost:8800/app/gitpod/troubleshoot/analyze/2fmq3zro4ug7bphv0ego3odikvn/contents/configmaps/gitpod/kotsadm-gitpod-redact-spec.json)
- [kotsadm-redact-spec.json](http://localhost:8800/app/gitpod/troubleshoot/analyze/2fmq3zro4ug7bphv0ego3odikvn/contents/configmaps/gitpod/kotsadm-redact-spec.json)
Fixes #13374
Deploy via KOTS, trigger a support bundle and check the files in `configmaps/gitpod`
```release-note
[kots]: configure support bundle to get KOTS configmaps
``` …
=> [kots]: configure support bundle to get KOTS configmaps

.werft/eks-installer-tests.yaml, .werft/installer-tests.ts, install/infra/modules/eks/kubernetes.tf, install/tests/Makefile
This PR adds a new `post_bootstrap_user_data` variable to the EKS terraform modules that changes the containerd config to accept new self signed SSL Certificates, and restarting `containerd` to make the same work.
This PR also changes the `self-signed` of infra tests to upload the CA certificate into gcs for us to download and use.
Fixes https://github.com/gitpod-io/gitpod/issues/12979
Run
```
werft run github -f -s .werft/installer-tests.ts -j .werft/eks-installer-tests.yaml -a debug=true -a selfSigned=true -a skipTests=true -a preview=true -a domain=tests.doptig.com
```
or use the `self-signed` instance at `https://f0761-aws.tests.doptig.com` while using the certificate from https://werft.gitpod-dev.com/job/gitpod-custom-tar-eks-selfsign …
=> [single-cluster/aws] make `self-signed` work

components/gitpod-db/src/typeorm/entity/db-volume-snapshot.ts, components/gitpod-db/src/typeorm/migration/1664205442175-AddLastModifiedToVolumeSnapshots.ts
Make the `db_volume_snapshot` table able to be synced between clusters.
* Add a migration so that the table has `_lastModified` and `deleted` fields.
Records are currently hard-deleted from this table, so the `deleted` field will not be used in practice:
https://github.com/gitpod-io/gitpod/blob/99e86333318deb096044e0f25d6000293e46f26d/components/gitpod-db/src/typeorm/workspace-db-impl.ts#L776-L779
Part of https://github.com/gitpod-io/gitpod/issues/9198
```release-note
NONE
```
=> [db-sync] Sync `d_b_volume_snapshot` table

components/server/ee/src/user/stripe-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts
Follow-up to #13351, which accidentally made all Stripe customer portal return URLs be `/billing`.
`/billing` is correct for user portals, but team portals need a different, team-specific return URL. This PR brings it back by always passing the correct `returnUrl` parameter.
Fixes #13351
1. Subscribe to usage-based as a team
2. Click on "Manage Billing"
3. Click on "Return to Gitpod"
4. You should be back in team billing, not user billing
```release-note
NONE
```
=> [server] Fix return URL of Stripe Customer Portal for teams

.werft/aks-installer-tests.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/installer-tests.ts, .werft/jobs/build/self-hosted-upgrade-tests.ts, .werft/k3s-installer-tests.yaml, install/tests/Makefile
This PR fixes a couple of things that are breaking with the automated tests:
- I recently changed `skipTests` to `runTests` in the intention that we can make skipping tests the default behavior. But the thing I didn't consider is, this would mean that the crons running every night doesn't run the tests. So rolled this change back to set running tests the default behavior
- In the cleanup script, currently for cleaning up certificates, it checks if variable `self_signed` is set. But during cleanup crons, no such variables are being set but we have to cleanup anyways. Hence the variable check is removed
- Currently, in `get-kubeconfig` targets (the ones used to retrieve kubeconfig file either locally or during werft jobs) I am using a secret being set to check if it is a cron or local. This …
=> [installer-tests] Cleanup the self-hosted test crons

components/gitpod-cli/BUILD.yaml, components/gitpod-cli/pkg/gitpod/server.go, components/gitpod-cli/pkg/gitpod/version.txt, components/local-app/BUILD.yaml, components/local-app/main.go, components/local-app/version.txt
This PR is follow up https://github.com/gitpod-io/gitpod/pull/13228
1. make the version generate simply
2. change local-app version generate function
no sure how to do with jetbrains backend plugin
Fixes #
```release-note
NONE
```
=> Build speed: glitpod-cli/local-app

components/dashboard/src/contexts/FeatureFlagContext.tsx
Don't show the usage view on self-hosted, yet.
Fixes #13390
```release-note
NONE
```
=> [usage] don't show usage in self-hosted yet

components/dashboard/src/App.tsx, components/dashboard/src/Menu.tsx, components/dashboard/src/teams/teams-context.tsx
This PR changes remembers the selection of the team, so that it doesn't jump back to the individual account whenever I visit the workspaces list.
Fixes https://github.com/gitpod-io/gitpod/issues/10496
Use the preview App and verify the promised behavior.
```release-note
Keep the last selected team selected
```
=> [dashboard] keep team selection

components/server/ee/src/workspace/gitpod-server-impl.ts
Team deletion for non-UBP teams is currently broken. This PR fixes the issue by ensuring that we don't check for UBP specific details about the team (such as any currently active Stripe subscription) before ensuring that Stripe payments are enabled.
Fixes https://github.com/gitpod-io/gitpod/issues/13392
Create a team in the preview environment and then delete it.
```release-note
[server] Fix for the inability to delete teams that were not subscribed to usage based pricing
```
=> [server] Fix team deletion for non-UBP enabled teams

install/preview/entrypoint.sh, install/preview/prettylog/main.go
Currently, When there is a failure at `checking_prerequisites` we don't actually propogate the issue resulting in confusion to the users. This PR updates the prettylog script to propogate the same as an error for the user to get more information
Part of #11316 
Run
```
docker run -p 443:443 --privileged --name gitpod -it  --mount type=volume,source=gitpod,destination=/var/gitpod eu.gcr.io/gitpod-core-dev/build/local-preview:tar-lp-better-failure.5
```
on a system with low resources
```release-note
[local-preview] Failure with more specific information
```
=> [local-preview] Failure with more specific information

install/infra/single-cluster/gcp/cluster.tf
In a recent PR that fixes the machine type of `GCP` and `AWS` terraform modules, we introduced a variable override in GCP reference architecture that appears to be inconsistent with what the parent module is expecting. Currently, due to this error the single-cluster terraform module is broken.
Fixes #
Please follow the README of the GCP single-cluster reference architecture 
```release-note
NONE
```
=> [terraform/gcp] Fix wrong variable name

.github/workflows/code-nightly.yaml, .github/workflows/jetbrains-auto-update-template.yml
To fix GH Action with JetBrains Nightly and Code Nightly
Fixes #
See action results
- https://github.com/gitpod-io/gitpod/actions/runs/3144246029
- https://github.com/gitpod-io/gitpod/actions/runs/3144243938
```release-note
NONE
```
=> Bump leeway to v0.3.1 for Github Action

operations/observability/mixins/IDE/rules/opensvx.yaml
Just to make navigation easier, this PR will improve our navigation from alert notification to grafana.
In pagerduty a new link will be added at the button:
If going straight to slack, it will appear as an extra button:
```release-note
NONE
```
=> Add dashboard URL to GitpodOpenVSXRegistryDown alert

.github/workflows/jetbrains-update-plugin-platform-template.yml
Adds the https://github.com/gitpod-io/gitpod/labels/editor:%20jetbrains to automated update PRs like https://github.com/gitpod-io/gitpod/pull/12188. This helps with both organization and the new changelog script. 
One can run the Action manually; if there is an update, the PR should have the additional label assigned. 
```release-note
NONE
```
=> Add JB label to automated update PRs

components/common-go/log/log.go
Updates common-go to emit logs that inform which code line it was emitted from.
Related discussion([ref](https://gitpod.slack.com/archives/C01KGM9AW4W/p1664387586999509))
Fixes #
* Open a workspace from this PR
* Try `kubectl logs -f ws-daemon` or any other component actually
While checking the logs, you'll notice that you'll find the code line and the function where each log was emitted from
```release-note
NONE
```
=> common-go: Add code line to all emitted logs

operations/observability/mixins/workspace/rules/nodes.yaml
This alert is specifically made to monitor workspaces that might be abusing conntrack table.
So update it to make sure it fires only for workspace pods, and not for any other pods.
Fixes #
```release-note
none
```
=> fix network connections alert to fire only for workspace pods

test/pkg/integration/apis.go, test/tests/components/ws-manager/prebuild_test.go
Update test `TestOpenWorkspaceFromPrebuild` to check whether the PVC object should exist or not.
Partially #12638
Run the workspace integration test.
```
cd test
go test -run ^TestOpenWorkspaceFromPrebuild$ github.com/gitpod-io/gitpod/test/tests/components/ws-manager -count=1 -namespace=default -kubeconfig=/home/gitpod/.kube/config -v -timeout=20m
```
```release-note
None
```
None
=> test: update test TestOpenWorkspaceFromPrebuild

components/gitpod-db/src/tables.ts
Remove the `d_b_email` table from `db-sync` config. The table was dropped in https://github.com/gitpod-io/gitpod/pull/13361.
Should have been part of https://github.com/gitpod-io/gitpod/pull/13361
Part of #9198 
```release-note
NONE
```
=> [db-sync] Remove `d_b_email` from config

install/tests/Makefile
Users interacting with EKS self-hosted preview environments may not realize that they need to source the AWS service account credentials file; this commit adds a nice warning indicating how users can load those credentials.
Fixes #
Run the following:
```
cd install/tests
TF_VAR_TEST_ID="release-aws" make get-kubeconfig
```
The following warning should be emitted:
```release-note
NONE
```
=> [install/tests] Notify users to source eks credentials

components/usage/pkg/db/cost_center.go
Produces about [120k log messages an hour](https://console.cloud.google.com/logs/query;query=resource.labels.pod_name%20:%20%2528%22usage%22%2529%0AjsonPayload.message%3D%22Get%20or%20create%20CostCenter%22;timeRange=PT1H;cursorTimestamp=2022-09-29T07:14:00.000Z?authuser=0&project=gitpod-191109)
We still continue to log it when a new one is created.
Fixes #
```release-note
NONE
```
=> [usage] Remove 'Get or create CostCenter' log

components/server/src/repohost/repo-url.spec.ts, components/server/src/repohost/repo-url.ts
Otherwise this breaks the lookup of services mapped by host (including the port.)
This is the quite apparent aftermath of enabling ports in SCM locations.
Fixes #
```release-note
Fix missing port in parsed clone URL.
```
=> [server] properly parse ports of clone URLs

components/gitpod-db/src/typeorm/migration/1664441455556-WorkspaceInstanceStartedStoppingIndex.ts
Adds missing indices to avoid full table scan.
[Internal Context](https://gitpod.slack.com/archives/C02EN94AEPL/p1662471052279859?thread_ts=1662468125.845989&cid=C02EN94AEPL)
Relates to #13060
```release-note
NONE
```
/hold to run this manually as it is a long-running migration.
=> [db] Add index to d_b_workspace_instance on startedTime & stoppingTime

operations/observability/mixins/workspace/rules/nodes.yaml
Reverts https://github.com/gitpod-io/gitpod/pull/13427. The pod refers to the pod that is exporting the metric which would be the node-exporter, so the alert will not fire as it will find no matching entries. This can be checked by using 'Explore' in Grafana and using this query: `node_nf_conntrack_entries{instance=~"workspace-.*", instance!~"serv.*"}`. When you check the values for pod in the output you will see that there are no workspace pods, only node exporter.
n.a.
```release-note
None
```
=> Revert "fix network connections alert to fire only for workspace pods"

components/gitpod-cli/cmd/ports-visibility.go, components/gitpod-protocol/go/gitpod-service.go
Add new gp-cli command to allow users to change ports visibility
Fixes https://github.com/gitpod-io/gitpod/issues/10835
Open workspace in preview env, check with portsView to see if port is locked(private) or unlocked(public)
- Run `curl lama.sh | sh` to open port 8080
- Run `gp ports visibility 8080:public` to make it public
- Check PortsView / Visit URL of 8080 in another browser to check if it's visitable
- Run `gp ports visibility 8080:private` to make it private
- Check PortsView / Visit URL of 8080 in another browser to check if it's not visitable
```release-note
[gp-cli] add command to change ports visibility
```
- https://github.com/gitpod-io/website/issues/2804
=> [gp-cli] add command to change ports visibility

components/gitpod-db/src/typeorm/migration/1664443511970-AddDeletedFieldToPendingGithubEventsTable.ts
This will be used to enable soft deletion for the `d_b_pending_github_event` table and then syncing via `db-sync`.
Part of #9198 
```release-note
NONE
```
=> [db] Add `deleted` field to `d_b_pending_github_event` table

components/ide/jetbrains/backend-plugin/build.gradle.kts, components/ide/jetbrains/backend-plugin/gradle-latest.properties, components/ide/jetbrains/backend-plugin/launch-dev-server.sh, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodClientProjectSessionTracker.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodIgnoredPortsForNotificationService.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodIgnoredPortsForNotificationServiceImpl.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortForwardingService.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodIgnoredPortsForNotificationServiceImpl.kt, components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml, components/ide/jetbrains/backend-plugin/src/main/resources-stable/META-INF/extensions.xml
Now that IDEA/PyCharm/PhpStorm/GoLand _latest_ version is v2022.3 in Gitpod, we can add support for JetBrains IDEs v2022.3.
All code changes were done to accommodate the API differences between v2022.2 and v2022.3. There were no logic/flow changes in the plugin.
The dev server script (`launch-dev-server.sh`) has been improved to allow us locally test EAP and Stable versions of the IDE, which is a common point of failure during Werft builds - because there we build the plugin for EAP and Stable IDE versions simultaneously.
- By default, running `launch-dev-server.sh`, will launch the JetBrains EAP version.
- If we want to build launch JetBrains Stable version we run it with the additional 's' parameter: `launch-dev-server.sh -s`
~~1. Access the Preview Environment of this PR
2. Open a …
=> Add support for JetBrains EAP IDEs (2022.3)

operations/observability/mixins/meta/dashboards/components/usage.json
Fixes #
```release-note
NONE
```
=> [usage] Add Stripe usage records udpated to Usage component dashboard

components/ws-manager-bridge/src/bridge.ts, components/ws-manager-bridge/src/config.ts, install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/ws-manager-bridge/configmap.go, install/installer/pkg/components/ws-manager-bridge/types.go
After validating through logging of the past two weeks (since 15.09.2022), this change marks `stopping` and `pending` states after the timeout duration to be stopped. 
Findings from the [logging](https://github.com/gitpod-io/gitpod/pull/12902):
1. Most of the logs were for `stopping` state, and we could not find a clear explanation whether they were cases that we want to be stopped. Instances could be in a `stopping` state for longer than we expect (in the previous PR it was 10 seconds after `stoppingTime`) because instances with a big back-up size can take longer.
2. A lot of the `pending` states were stuck in that state for days, and we do want them stopped.
3. We found a few `creating` states that ended up running, and these we should not stop. 
We are still unsure why these instances …
=> [bridge] Marks stuck stopping and pending instances as stopped

components/ee/payment-endpoint/src/github/subscription-reconciler.ts, components/gitpod-db/src/typeorm/entity/db-pending-github-event.ts, components/gitpod-db/src/typeorm/pending-github-event-db-impl.ts, components/gitpod-protocol/src/protocol.ts
Implement soft deletion of rows from the `d_b_pending_github_event` table.
The migration to add the `deleted` column was done in https://github.com/gitpod-io/gitpod/pull/13450.
With soft deletion in place, the table can be synced between regions in a followup PR.
Part of #9198 
```release-note
NONE
```
=> Implement soft deletion of pending github events

components/gitpod-db/src/tables.ts
With the changes to add a `deleted` column to the table (https://github.com/gitpod-io/gitpod/pull/13450) and soft-delete rows from the table (https://github.com/gitpod-io/gitpod/pull/13455), the `d_b_pending_github_event` table can now be added to `db-sync` configuration.
Part of #9198 
```release-note
NONE
```
=> [db-sync] Sync `d_b_pending_github_event` table

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/cleanup-installer-tests.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environment.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile
This pull request updates the awscli package to version 2. awscliv2 has been generally available since [February 10, 2020](https://github.com/aws/aws-cli/releases/tag/2.0.0) and commonly available AWS documentation references commands that are not available in awscliv1 (such as `aws sts get-caller-identity`).
Using the [aws access tl;dr](https://www.notion.so/gitpod/AWS-access-tl-dr-a2b322f4d67b47aba1c1ec0569224327) setup steps, confirm the following commands work and provide outputs matching the following:
```bash
aws --version
```
```bash
aws sts get-caller-identity | jq 'with_entries(.value = "redacted")'
```
```release-note
Update Gitpod workspace image to with awscliv2
```
N/A
=> Update dev workspace image with awscliv2

components/server/src/container-module.ts
Create only one GRPC client.
Fixes #
```release-note
NONE
```
=> [server] bind GRPC clients in singleton scope

components/gitpod-db/src/typeorm/entity/db-volume-snapshot.ts, components/gitpod-db/src/typeorm/workspace-db-impl.ts, components/gitpod-db/src/workspace-db.spec.db.ts
Replace the existing hard-deletion of rows in the `db_volume_snapshot` table with soft-deletion.
This will allow `db-sync` to propagate deletions between clusters.
Follow up to https://github.com/gitpod-io/gitpod/pull/13348
Part of #9198 
Unit tests
```release-note
NONE
```
=> [db] Soft delete entries in the `db_volume_snapshot` table

components/gitpod-db/src/tables.ts
Add the `d_b_volume_snapshot` table to the list of tables to be synced by `db-sync`.
* The migration to add the `_lastModfied` and `deleted` columns was added in https://github.com/gitpod-io/gitpod/pull/13348
* Soft deletion of volume snapshot records was added in https://github.com/gitpod-io/gitpod/pull/13391
With these two in place we can switch on sync for this table.
Part of #9198 
```release-note
NONE
```
=> [db-sync] Update config with `d_b_volume_snapshot` table

components/ide/jetbrains/backend-plugin/BUILD.yaml
At before we built backend every commit, because argdeps is include in compute leeway version, we don't actually use this `version` argument, remove it can make build easily
Fixes #
1. comment `/werft run` in this PR to re-trigger werft build, it should be not build `jb-backend-plugin`
```release-note
NONE
```
=> [jetbrains] remove unused argdeps

.werft/eks-installer-tests.yaml
https://github.com/gitpod-io/gitpod/pull/12278 added AWS CLI v2 as part of the `dev-image` which means we don't have to install into the werft job anymore.
Fixes #
EKS test should still run
```release-note
NONE
```
=> [install-tests/eks] Remove AWS CLI v2 installation

install/kots/manifests/kots-config.yaml
This is a tiny PR that fixes a broken link in KOTS UI. This link leads to the Customization doc page.
Fixes #
```release-note
NONE
```
=> [kots-ui] fix broken link to Customization docs

components/dashboard/src/AppNotifications.tsx, components/server/ee/src/workspace/gitpod-server-impl.ts
Shows: 
1. The team/user attributed in the billing. 
2. The link to the relevant billing page.
| REACHED | 80% |
| - | - |
| <img width="300" alt="Screenshot 2022-09-29 at 20 36 00" src="https://user-images.githubusercontent.com/8015191/193114962-c0461ce5-4a50-4918-b365-4573ec85ea35.png"> | <img width="330" alt="Screenshot 2022-09-30 at 12 47 09" src="https://user-images.githubusercontent.com/8015191/193254014-50700997-aff3-46b6-add7-69357a060fa9.png"> |
Fixes #13166
[Preview env](https://lau-notifi6e179161fd.preview.gitpod-dev.com/)
1. Join [this team](https://lau-notifi6e179161fd.preview.gitpod-dev.com/teams/join?inviteId=85c97e27-4e1e-4b49-85c9-ec4f0c14fbe4).
2. You should see the notification already.
```release-note
NONE
```
Valid options …
=> [usage] More useful notification

install/installer/pkg/components/server/configmap.go, install/installer/pkg/components/server/types.go, install/installer/pkg/config/v1/experimental/experimental.go
Adds support for enabling protected secrets in the installer.
Run the installer with the following config:
```YAML
experimental:
workspace:
enableProtectedSecrets: true
```
and observe how the server configmap now contains a new default feature flag.
```release-note
Add experimental support for protected secrets
```
=> [installer] Support enabling protected secrets

components/ide-proxy/conf/Caddyfile
[ide-proxy] add HSTS header
Fixes #https://github.com/gitpod-io/security/issues/38
1. open a workspace in preview environment, it should work as usually (special to check simple browser extension)
2. using `curl -v https://ide.pd-ide-hsts.preview.gitpod-dev.com/metrics-api/metrics/` to ensure there is HSTS header in there
```release-note
NONE
```
=> [ide-proxy] add HSTS header

test/tests/components/ws-manager/protected_secrets_test.go
Test protected secrets
Fixes https://github.com/gitpod-io/gitpod/issues/11318
```
cd test
go test -run ^TestProtectedSecrets$ github.com/gitpod-io/gitpod/test/tests/components/ws-manager -count=1 -namespace=default -kubeconfig=/home/gitpod/.kube/config -v -timeout=20m
```
```release-note
None
```
=> [test] Test protected secrets

components/content-service/pkg/initializer/git.go, test/tests/components/ws-manager/multi_repo_test.go
Check `CloneTarget` branch name when using `main` or `master`. 
Fixes https://github.com/gitpod-io/gitpod/issues/13479
- Open a workspace using a repository with `master` as the default branch name and no `main`.
```release-note
NONE
```
=> [content-service] Check git default branch name

.werft/cleanup-installer-tests.yaml
This commit depends on awscliv2 being available in the dev environment and skips the installation step in the cleanup-installer-tests job.
Depends on https://github.com/gitpod-io/gitpod/pull/12278
```bash
werft run github -j .werft/cleanup-installer-tests.yaml
```
Should result in something like the following:
```
cleanup-infra        Manage the infrastructure in
[cleanup-old-tests] Calling cleanup-old-tests
[cleanup-old-tests] STDOUT: make: Entering directory '/workspace/install/tests'
[cleanup-old-tests] ./cleanup.sh
[cleanup-old-tests] release-2-aws has the pattern gitpod-*, skipping
[cleanup-old-tests] release-azure has the pattern gitpod-*, skipping
[cleanup-old-tests] release-gcp has the pattern gitpod-*, skipping
[cleanup-old-tests] …
```
=> [werft] Use awscliv2 from dev-environment and skip install in cleanup preview job

.github/CODEOWNERS, components/BUILD.yaml, components/kots-config-check/certificate/BUILD.yaml, components/kots-config-check/certificate/entrypoint.sh, components/kots-config-check/certificate/leeway.Dockerfile, install/kots/manifests/kots-support-bundle.yaml
Add some rudimentary checks for the certificate - importantly, these are the skateboard not the finished article. These download and decode the certificate secret and perform the following checks:
1. that the secret exists and is able to be decoded as an OpenSSL x509 certificate
2. that `$DOMAIN`, `*.$DOMAIN` and `*.ws.$DOMAIN` exist in the secret (the subject alternate names seems to be non-standard, so this is a simple `grep`)
3. that the current timestamp is between the `notBefore` and `notAfter` timestamps
**NB** it does **NOT** validate that the certificate's CA is known and installed in the cluster. That's important but it's beyond the 🛹 
As with the other KOTS checks, these are perhaps a little rudimentary but they give an indication of whether the provided state is …
=> [certificates]: validate that certs are valid for a Gitpod install

components/ide/jetbrains/backend-plugin/.run/backend-plugin.run.xml, components/ide/jetbrains/backend-plugin/README.md, components/ide/jetbrains/backend-plugin/launch-dev-server.sh
1. Adds a run configuration to easily launch the debugger for `backend-plugin`
1. Update to `launch-dev-script.sh` to allow specifying a `DEBUG_PORT` and have a dynamic directory in which the test repository is cloned
2. Update contributing docs (also in view of [Hacktoberfest](https://github.com/gitpod-io/website/pull/2780))
Fixes #13051
1. Choose IntelliJ as your editor in [gitpod.io/preferences](https://gitpod.io/preferences)
2. Start a workspace for this PR: https://gitpod.io/#https://github.com/gitpod-io/gitpod/pull/13454
3. Test the run configuration while running `cd components/ide/jetbrains/backend-plugin && ./launch-dev-server.sh -p 44444`
```release-note
NONE
```
N/A
=> JetBrains: Update `launch-dev-script.sh` and contributing docs

components/gitpod-db/src/typeorm/migration/1664524890935-DeleteProbeWorkspacesAndInstances.ts
Delete Probe workspaces from the DB
* Part of https://github.com/gitpod-io/gitpod/issues/11315
```release-note
NONE
```
=> [migrations] Delete Probe workspaces from DB

components/public-api-server/pkg/server/server.go
With baseserver already providing a metrics registry, we don't have to construct it ourselves.
Fixes #
```release-note
NONE
```
=> [public-api] Reuse metrics registry from baseserver

components/gitpod-db/src/typeorm/migration/1664781308555-ChangeOauthCodePrimaryKey.ts
Add a new `uid` column to the `d_b_oauth_auth_code_entry` table. 
This table should be synced by `db-sync` but currently uses an auto-incrementing PK which will cause clashes between regions. To resolve, the plan is:
1. Add a new `uid` column and populate it (this PR).
2. Switch the PK over to the `uid` column and remove the old auto-incrementing`id` column (later PR).
3. Sync the table using `db-sync` (later PR).
Part of #9198 
```release-note
NONE
```
=> [db] Add `uid` column to `d_b_oauth_auth_code_entry` table

.github/workflows/code-nightly.yaml
Related #13410
```release-note
NONE
```
=> [code] point nightly job to gp-code/release/1.72

components/ide-proxy/conf/Caddyfile, components/ws-proxy/pkg/proxy/routes.go, components/ws-proxy/pkg/proxy/routes_test.go
Minor cleanup for blobserver response headers
1. Open a workspace and check vscode webview work, e.g. vscode ports view
```release-note
NONE
```
=> Minor cleanup for blobserver response headers

operations/observability/mixins/workspace/dashboards.libsonnet, operations/observability/mixins/workspace/dashboards/psi.json
We currently use the load average of a node to observe if it is overloaded. The shortcomings of that approach are:
- It is coarse grained.  It is not obvious which resource was contented and how strong the demand for that resource was. We need to consult additional metrics to find out why a load spike has occurred.
- Even then there is some guesswork involved. It would be much nicer if the OS would just tell us why the system was slow or in other words which resource was contented and how much.
- This is where pressure stall information comes in. Pressure stall information was first introduced in kernel 4.20 (so also available on self-hosted). For each major resource (cpu, memory and IO) it shows the percentage of the time that processes were not able to run due the resource not being …
=> [obs] Dashboard for psi metrics

components/ws-manager/pkg/manager/monitor.go
Remove the PVC object if the workspace pod could not create or the workspace pod never reached a running state.
Fixes #13282
- Create 110 pods to reach the per-node max pod limit
```console
for i in {1..110}; do kubectl run test-${i} --image ubuntu -- sleep 3600; done
```
- Enable PVC feature flag.
- Create a workspace, and make sure the workspace pod failed to up.
- Waits for 30 minutes, and the workspace pod is terminated and done.
- The PVC object is gone as well.
```release-note
[experimental] remove PVC object if the workspace pod fails to up
```
None
=> ws-manager: remove PVC object if the workspace pod fails to up

operations/observability/mixins/meta/rules/usage.yaml
See context in https://gitpod.slack.com/archives/C03QEED3LLE/p1664864607210619
Fixes #
```release-note
NONE
```
=> [usage] Fix alerting for GitpodUsageTooLongSinceLastSuccessfulLedgerReconciliation

components/usage/pkg/stripe/stripe.go
Ensure that the `queriesForCustomersWithAttributionIDs` is stable by sorting the the attributionIDs before mapping them to queries.
Iteration of map keys is not stable in Go.
```bash
cd components/usage/pkg/stripe
while true; do go test . --count=1; done 
```
The tests should pass consistently as opposed to `main` on which there will be occasional failures.
```release-note
NONE
```
=> [usage] Make function output stable to fix flaky test

components/dashboard/src/components/UsageView.tsx
Fix off-by-one error on selected Usage range (end date).
Explanation:
- `new Date(year, month, 0)` results in the last day of the previous month (e.g. `2022-09-30T00:00:00.000Z`)
- But, using this date as an "end" for a selected range omits all the data from the 24 hours between `2022-09-30T00:00:00.000Z` to `2022-10-01T00:00:00.000Z`
- A better "end" for the selected range is `new Date(year, month)`, i.e. the start of the next month, which results in `2022-10-01T00:00:00.000Z`
Fixes https://github.com/gitpod-io/gitpod/issues/13521
In a Node.js or browser console, run this to verify:
```js
const today = new Date();
const startDate = new Date(today.getFullYear(), today.getMonth() - 1);
// 2022-09-01T00:00:00.000Z -- OK
const oldEndDate = new Date(today.getFullYear(), today.getMonth(), 0); …
```
=> [dashboard] Fix off-by-one error on usage range end date

operations/observability/mixins/meta/dashboards/components/usage.json
Removes the current Gauge, and instead shows this graph which unifies the two.
Fixes #
```release-note
NONE
```
=> [usage] Simplify dashboard by showing gauge and history in the same graph

components/dashboard/src/admin/ProjectsSearch.tsx, components/dashboard/src/admin/TeamsSearch.tsx, components/dashboard/src/admin/UserSearch.tsx, components/dashboard/src/admin/WorkspacesSearch.tsx
When navigating to the admin dashboard, we no longer automatically running an empty search on load.
Fixes #13334 
```release-note
NONE
```
=> [admin] don't run an empty search on load

components/dashboard/src/settings/SelectIDEModal.tsx
This PR solves the issue #13497 as suggested over there : 2 rows, 4 column style on-boarding IDE selector window
Fixes #13497
```release-note
NONE
```
=> Two rows of 4 option on onboarding IDE selector

.werft/installer-tests.ts, install/infra/modules/gke/output.tf, install/infra/modules/k3s/dns.tf, install/infra/modules/k3s/local.tf, install/infra/modules/k3s/main.tf, install/infra/modules/k3s/output.tf, install/infra/modules/k3s/variables.tf, install/infra/modules/tools/cloud-dns-ns/main.tf, install/infra/single-cluster/k3s/cluster.tf, install/infra/single-cluster/k3s/local.tf, install/infra/single-cluster/k3s/output.tf, install/infra/single-cluster/k3s/tools.tf, install/infra/single-cluster/k3s/variables.tf, install/tests/Makefile, install/tests/main.tf, install/tests/output.tf
This is the first of a 3 part PR series that uses the terraform single-cluster setup to run the automated tests instead of a standalone `main.tf`. Since `k3s` doesn't really have a reference architecture the module we are using is quite rough and had some hacky DNS setup method. This PR cleans it up to add a proper managed DNS entry and adds the NS record to the DNS project. This still doesn't make k3s module usable for a outside user. We will be tackling that issue in the `k3s reference architecture` task.
Here are the other two PRs:
Fixes #
```
werft run github -j .werft/k3s-installer-tests.yaml -a skipTests=true
```
```release-note
NONE
```
=> [terraform] cleaning up k3s module to use for tests

components/ee/db-sync/src/commands.ts, components/ee/db-sync/src/config.ts
Optionally read DB credentials from env vars ([commit without formatting](https://github.com/gitpod-io/gitpod/pull/13573/commits/15bb1f3857868132557550d326369bd1e889292a)).
Fixes #
```release-note
NONE
```
=> [db-sync] Optionally read DB credentials from env vars

components/ws-daemon/debug.Dockerfile, components/ws-daemon/leeway.Dockerfile, components/ws-daemon/pkg/content/initializer.go
Improve the download of prebuild from the remote content storage using multiple connections.
fixes https://github.com/gitpod-io/gitpod/issues/12345
- Add the role `new-workspace-cluster` to your account
- Check the `persistent_volume_claim` is not checked
- Deploy an ephemeral cluster
- Open a workspace using a prebuild
- Remove the role `new-workspace-cluster` from your account 
- Open a workspace using a the same prebuild
- Compare the times.
```release-note
NONE
```
=> [ws-daemon] Improve download speed of snapshots

components/content-service/pkg/initializer/git.go, test/tests/components/ws-manager/additional_repositories_test.go
When we open a workspace from a branch and the repository contains a .gitpod.yml file with `additionalRepositories`, we should not assume the branch exists in those repositories. Also, when we specify a branch in one of the `additionalRepositories`, we should be able to use that branch.
Fixes #13527
Fixes #13512
Reverts #11895
- Open a workspace using
- https://github.com/gitpod-io/gitpod-test-repo/tree/aledbf/test-additional-repositories
- https://github.com/gitpod-io/gitpod-test-repo/tree/aledbf/test-additional-repositories-with-branches
```release-note
NONE
```
=> [content-service] Revert #11895

components/server/ee/src/workspace/workspace-factory.ts, components/server/src/workspace/config-provider.ts
Instead of having to enable feature flag per user via admin panel, this allows to enable it via ConfigCat instead, as well as will allow us to roll out this feature to more users via configCat. 
Fixes #12745
Open preview env
Add your user id to ConfigCat non production env
Open new workspace
In terminal: `ls -la /.workspace/.gitpod/` and you should see `pvc` file in there, indicating this workspace is running using PVC feature.
```release-note
none
```
=> allow to enable PVC feature flag for user via ConfigCat

dev/loadgen/pkg/loadgen/executor.go
Make the start workspace timeout the same as the ws-manager start workspace timeout.
Otherwise, sometimes we hit the context deadline when we wait for the auto-scaler to scale up the node.
Fixes #
None
```release-note
None
```
None
=> loadgen: make the start workspace timeout same as the ws-manager start workspace timeout

components/ws-manager/pkg/manager/manager.go
Potential workaround for random mount volume failures. 
Fixes #13353 
It is very hard to repro this issue.
So another way to test this PR is to ensure opening workspace works. 
```release-note
none
```
=> [pvc] potential workaround for mount volume failure

components/dashboard/src/Setup.tsx
Fix wording to include `Bitbucket`.
Fixes #9873
```release-note
NONE
```
=> [dashboard] Fix integrations wording

components/proxy/conf/Caddyfile, components/public-api-server/pkg/server/server.go
* Part of https://github.com/gitpod-io/gitpod/issues/13574
Ensure that gRPC traffic is still routed to the gRPC server
```
gpctl api workspaces get 123 --address api.mp-caddy-r9ed2436f9c.preview.gitpod-dev.com:443 --token foo
FATA[0000] failed to retrieve workspace (ID: 123)        error="rpc error: code = PermissionDenied desc = insufficient permission to access workspace"
```
Permission denied is expected, we're supplying a dummy token. But we got an application level response - this means it works.
Test that HTTP routing works to the HTTP server
```
curl https://api.mp-caddy-r9ed2436f9c.preview.gitpod-dev.com/test
test
```
```release-note
NONE
```
=> [proxy] Handle both gRPC and HTTP requests against public-api

components/gitpod-db/src/typeorm/entity/db-snapshot.ts, components/gitpod-db/src/typeorm/migration/1664460477008-DropLayoutDataTable.ts, components/gitpod-db/src/typeorm/migration/1664531268399-RemoveSnapshotLayoutDataColumn.ts
Remove the `d_b_layout_data` table and  the `layoutData` column from the `d_b_snapshot` table.
See ([Slack thread](https://gitpod.slack.com/archives/C01KGM9BH54/p1664290138597739)) for additional context.
⚠️ Merge and deploy https://github.com/gitpod-io/gitpod/pull/13519 first. ⚠️ 
Part of #9198 
Follow up to https://github.com/gitpod-io/gitpod/pull/13519
```release-note
NONE
```
=> [db] Drop `d_b_layout_data` table

components/dashboard/src/Menu.tsx, components/dashboard/src/components/PillMenuItem.tsx, components/dashboard/src/projects/Projects.tsx, components/dashboard/src/teams/teams-context.tsx
A quick prototype of how to simplify user accounts by removing the ability to create projects which belong to an individual account instead of a team, and moving the workspaces list to the left side of the nav bar.   
https://www.loom.com/share/b5d8544f7a864912a9d75ba04e921dc8
Fixes #
```release-note
Deprecation of the ability to create projects under an individual account for new users.
```
=> [dashboard] Deprecate the creation of projects under individual accounts

components/gitpod-db/src/typeorm/migration/1664894040785-AddLastModifiedToAuthCodeTable.ts
Add a `_lastModified` column to  the `d_b_oauth_auth_code_entry` table.
This is so that we can set the table up to be synced with `db-sync` in a later PR.
Part of #9198 
```release-note
NONE
```
=> [db] Add a `_lastModified` column to the `d_b_oauth_auth_code_entry` table

components/gitpod-cli/cmd/info.go
Adds a `gp info` command, to print workspace details. For now, this includes:
- Workspace ID
- Instance ID
- Workspace class
- Workspace URL
- Cluster host
The intention is for this to replace the use of the matching environment variables (see #10797 for more details).
Includes a `--json` flag to print as JSON, allowing e.g. for parsing the output in scripts.
Fixes #10797
```bash
$ cd components/gitpod-cli
$ go run . info
Workspace ID    : gitpodio-gitpod-4q1200dvfcf                            
Instance ID     : 8a6188a3-4c7f-49fe-aa4d-db968c11e183                   
Workspace class : Large: Up to 8 vCPU, 16GB memory, 50GB disk            
Workspace URL   : https://gitpodio-gitpod-4q1200dvfcf.ws-eu67.gitpod.io  
Cluster host    : ws-eu67.gitpod.io                                      
$ …
```
=> feat(gitpod-cli): Create `gp info` command

components/ee/agent-smith/go.mod, components/ee/agent-smith/go.sum, components/gitpod-cli/go.mod, components/gitpod-cli/go.sum, components/gitpod-protocol/go/go.mod, components/gitpod-protocol/go/go.sum, components/gitpod-protocol/go/reconnecting-ws.go, components/ide/code/codehelper/go.mod, components/ide/code/codehelper/go.sum, components/ide/jetbrains/image/status/go.mod, components/ide/jetbrains/image/status/go.sum, components/local-app/go.mod, components/local-app/go.sum, components/public-api-server/go.mod, components/public-api-server/go.sum, components/supervisor/go.mod, components/supervisor/go.sum, components/supervisor/hot-deploy.sh, components/supervisor/pkg/ports/exposed-ports.go, components/supervisor/pkg/supervisor/supervisor.go, test/go.mod, test/go.sum
This PR adds jitteriness to the exponential backoff on reconnection to the server and port exposure. It should help to prevent synchronous spiking of port exposure on the webapp deployment.
Fixes #
- Start a workspace and observe it logs `kubectl logs ws-.... -f > ws.log` from dev workspace for this PR
- Scale down servers `kubectl scale --replicas=0 deployment server` from dev workspace for this PR
- Try to trigger the port exposure with `curl lama.sh | sh -s -- -p 3333` from a test worksapce
- Observe in logs that a workspace is trying to reconnect to the server and expose port with random exponential backoff
- Scale up and check that workspace is reconnected `kubectl scale --replicas=1 deployment server` from dev workspace for this PR
- Do it again if you wan to be sure
```release-note …
```
=> randomize exponential backoffs

components/server/ee/src/workspace/gitpod-server-impl.ts
This change only shows usage notifications to team owners.
Fixes #13187
1. Join this team that has reached its usage limit[[1](https://lau-limit-13187.preview.gitpod-dev.com/teams/join?inviteId=db6f3336-d203-498f-94e4-d2536cf2cbd7)].
2. You should not be able to see the notifications.
```release-note
NONE
```
=> [usage] Only show notification to team owners

components/usage/go.mod, components/usage/go.sum, components/usage/pkg/stripe/reporter.go, components/usage/pkg/stripe/stripe.go
Report metrics when stripe client makes calls
* Relates to https://github.com/gitpod-io/gitpod/issues/13157
```release-note
NONE
```
=> [stripe] Report metrics from client calls in Go

components/ws-daemon/pkg/cpulimit/cfs.go, components/ws-daemon/pkg/cpulimit/dispatch.go
Stop logging cpu limit error when the cgroup cannot be found. This pis caused by a delay between the pod disappearing and the dispatch being informed about it. It just pollutes the log and does not help us identifying errors.
n.a.
```release-note
None
```
=> [ws-daemon] Stop logging cpu limit error

components/server/ee/src/billing/entitlement-service-chargebee.ts
The result is not awaited and so the check if the user is on the  free tier is performed against the promise and not against the boolean which makes the returned result always false.
n.a.
```release-note
None
```
=> [server] Fix network connections not limited

components/gitpod-cli/cmd/top.go
Updates `gp top` table output to match `gp info`, follow up from discussion in https://github.com/gitpod-io/gitpod/pull/13537#discussion_r987641981.
Also moves the workspace class to the table. Alternatively we could remove the workspace class from the output, as it's also shown in `gp info` now. Personally I think it'd be nice to keep it in `gp top` as well as it's relevant info, and it would be a breaking change to remove it from e.g. the `--json` output.
Original:
New:
Fixes #
```release-note
Gitpod CLI: `gp top` table output updated to match `gp info`
```
=> chore(gitpod-cli): Update top table output format

install/tests/Makefile
Previously we added a small feature that would backup the secret for TLS certificate so it can be reused at least for the same subdomain. But this feature was broken and was causing the test to fail. Along with this change, we broke the Github authentication secret creation as well. This PR basically cleans up the `make` target to `kots-install` a little bit by creating separate targets for both secret creations. 
Alongside, before destroying Gitpod, we back up the secret for certificate to a GCS bucket which is retrieved when recreating a setup with the same subdomain name. These secrets will get destroyed after 90 days.
Fixes #
Try running a test using:
```
werft run github -j .werft/k3s-installer-tests.yaml -a subdomain=test-k3s
```
```release-note
NONE
``` …
=> [installer-tests] Cleanup secret creation on Gitpod install

components/content-service/pkg/storage/gcloud.go
Change default expiration from three years ago. We have up to 50GB backups now
```release-note
NONE
```
=> [ws-daemon] Adjust SignedURL expiration

components/ws-daemon/pkg/content/initializer.go
Reduce verbosity while downloading content with aria2c and enabling retries after five seconds.
```release-note
NONE
```
=> [ws-daemon] Improve download options

components/content-service/pkg/layer/provider.go
Fixes https://github.com/gitpod-io/gitpod/issues/13531
Open preview env
Enable PVC flag
Open workspace that has no .gitpod.yml file in repo, eg: https://github.com/utam0k/utam0k.github.io
```release-note
none
```
=> [pvc] fix when opening repo with no .gitpod.yml

test/tests/components/ws-manager/content_test.go
Add integration test that tests PVC against non gitpodified repo.
Fixes #13591
```release-note
none
```
=> [pvc] add a test for non gitpodified repo

dev/loadgen/configs/prod-benchmark-pvc.yaml, dev/loadgen/configs/prod-benchmark.yaml, dev/loadgen/configs/workspace-preview-benchmark-pvc.yaml, dev/loadgen/configs/workspace-preview-benchmark.yaml
Test against a repo without .gitpod.yml
Fixes https://gitpod.slack.com/archives/C02F19UUW6S/p1664982541052409?thread_ts=1664974807.201539&cid=C02F19UUW6S
Run loadgen test
```release-note
None
```
None
=> loadgen: test against a repo without .gitpod.yml

.werft/aks-installer-tests.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/k3s-installer-tests.yaml
This is a small quality of life improvement for the self hosted terraform tests.
Unnecessary log chatter is a source of distraction while debugging failed CI jobs. While looking at werft failures npx emits the following message:
[gitpod-custom-alt-stream-exec-logs.2](https://werft.gitpod-dev.com/job/gitpod-custom-alt-stream-exec-logs.2)
```
Could not find license, skipping replicated license cleanup
FailedSliceError: create-gcp-infra
at new FailedSliceError (/workspace/.werft/util/werft.ts:8:9)
at Werft.fail (/workspace/.werft/util/werft.ts:117:15)
at /workspace/.werft/installer-tests.ts:291:19
at step (/workspace/.werft/installer-tests.ts:33:23)
at Object.next (/workspace/.werft/installer-tests.ts:14:53)
at fulfilled (/workspace/.werft/installer-tests.ts:5:58)
at …
```
=> [installer-tests] disable npm version update notice

components/dashboard/src/AppNotifications.tsx, components/dashboard/src/admin/BlockedRepositories.tsx, components/dashboard/src/admin/WorkspacesSearch.tsx, components/dashboard/src/components/ErrorMessage.tsx, components/dashboard/src/projects/Projects.tsx
`<Alert>` is already a container node. There is no need to double-encapsulate contents inside another container:
```html
<Alert>This is fine</Alert>
<Alert><span>This is unnecessary</span></Alert>
<Alert><div>This too</div></Alert>
<Alert><p>This is actually problematic in dark theme</p></Alert>
```
Fixes:
1. Visit `/new` and create a user-owned project (i.e. under your Personal Account)
2. Create a random team (this seems to be required for the Personal Account to show up in the top-left dropdown)
3. In the dropdown, select your Personal Account
4. Observe the warning in both light and dark theme
Also:
- Check other alerts throughout the app
```release-note
NONE
```
=> [dashboard] Don't double-encapsulate Alert contents in <span/> or <p/>

components/gitpod-db/src/typeorm/auth-code-repository-db.ts, components/gitpod-db/src/typeorm/entity/db-oauth-auth-code.ts, components/gitpod-db/src/typeorm/migration/1664974727836-ChangeOauthCodePKType.ts
In order to de-risk the process of swapping the primary key in the `d_b_oauth_auth_code_entry` table, this PR stops the primary key from auto-incrementing and instead sets its value manually when persisting new rows.
We want to switch the primary key to one that is suitable for `db-sync` to be able to sync the table between regions.
See [this comment](https://github.com/gitpod-io/gitpod/pull/13583#issuecomment-1268320895) for more context.
Part of #9198 
1. Run the local-companion app `local-app` against the preview environment:
```bash
GITPOD_HOST=<preview url> ./local-app test
```
2. Run through the auth flow.
3. See that the new rows in the `d_b_oauth_auth_code_entry` table have their `id` column set and that the type of the column is now a `char(36)` and no longer auto-increments. …
=> [db] Change the type of the primary key in the `d_b_oauth_auth_code_entry` table

components/gitpod-db/src/typeorm/auth-code-repository-db.ts
Remove the code that writes to the `uid` field so that the field can safely be removed by a migration.
This field is no longer necessary now that the `id` field has been converted to a type that stores uids in https://github.com/gitpod-io/gitpod/pull/13616
Part of #9198 
```release-note
NONE
```
=> [db] Stop writing to the `uid` field of the `d_b_oauth_auth_code_entry` table

components/gitpod-db/src/typeorm/team-db-impl.ts
Throw more accurate errors such that they don't show up as generic 500 errors in metrics
* Relates to https://github.com/gitpod-io/gitpod/issues/13125
```release-note
NONE
```
=> [server] Throw specific errors when interacting with teams

components/usage-api/buf.gen.yaml, components/usage-api/generate.sh
Results in exactly the same generated output, but it's more readable and can be grouped together with other codegen.
Fixes #
```
cd components/usage-api
./generate.sh
```
```release-note
NONE
```
=> [usage] Use buf for ts_proto plugin codegen

components/gitpod-db/src/typeorm/migration/1665062302891-ResetAuthCodePrimaryKeys.ts
Reset the primary keys in the `d_b_oauth_auth_code_entry` table to random uuids.
The type of the primary key column was changed in https://github.com/gitpod-io/gitpod/pull/13616 to allow storing uids, but the field now contains a mix of integer values (for existing records) and uids (for new records). In order to be able to sync the table with `db-sync` we need to replace the integer values with uuids.
The value of the primary key for each record doesn't matter so long as it is unique across both EU and US databases, so resetting the primary key values of all rows will work fine.
Part of #9198 
```release-note
NONE
```
=> [db] Reset primary keys in `d_b_oauth_auth_code_entry`

components/ws-manager-bridge/src/bridge.ts, components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
Adds `gitpod_ws_instances_marked_stopped_total` counter for instances marked as stopped.
Fixes #12959
Will test in prod while `in validation` to be able to gather more data compared to in a preview environment.
```release-note
NONE
```
=> [metric] Add Prometheus metric for instances marked as stopped

components/ws-manager/pkg/manager/monitor.go
This reverts commit 28fae90078c351207f3f0f48ab7fc6154cc4e5ce.
Related #13282
```release-note
None
```
None
=> Revert "ws-manager: remove PVC object if the workspace pod fails to up"

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/server/configmap.go, install/installer/pkg/config/v1/experimental/experimental.go
Enable `protected_secrets` by default for `server`, unless explicitly set to false in the installer config.
Change the data type EnableProtectedSecrets to the pointer to prevent a case that `enableProtectedSecrets = false` if the user’s config is below, which will disable the protected secrets.
```console
experimental:
workspace:
```
@MrSimonEmms , halp? :point_up:  above two tasks...I am bamboozled.~
Fixes https://github.com/gitpod-io/gitpod/issues/13632
Enabled out of the box
1. Disable `protected_secrets` for non-production in configcat
2. Start a workspace in the preview environment https://kylos101-eb280e47347.preview.gitpod-dev.com/workspaces
3. `kubectl describe pod <workspace>`, secrets should back values within the pod env vars, rather than plain strings. You could open the …
=> [installer] enable protected_secrets by default

components/ide/jetbrains/backend-plugin/build.gradle.kts
Update gradle plugins from JetBrains Backend-Plugin
Fixes [#12786](https://github.com/gitpod-io/gitpod/issues/12786)
1. Check if the Weft build passes.
2. Connect to the Preview Environment of this PR and open two workspaces: One with Stable IntelliJ IDEA and another with EAP IntelliJ IDEA.
3. Check if there are no errors about the plugin in the logs.
```release-note
NONE
```
=> Update gradle plugins from JetBrains Backend-Plugin

components/gitpod-db/src/tables.ts
Add the `d_b_oauth_auth_code_entry` table to `db-sync` config.
Follows up on PRs to prepare the table to be synced:
* https://github.com/gitpod-io/gitpod/pull/13616
* https://github.com/gitpod-io/gitpod/pull/13584
Part of #9198 
```release-note
NONE
```
=> [db-sync] Add `d_b_oauth_auth_code_entry` to db-sync

components/gitpod-protocol/data/gitpod-schema.json, components/gitpod-protocol/go/gitpod-config-types.go, components/gitpod-protocol/src/protocol.ts, components/ide/jetbrains/backend-plugin/hot-deploy.sh, components/server/src/ide-service.ts, test/tests/ide/jetbrains/gateway_test.go
Add missing Gitpod configurations for RubyMine and WebStorm.
- RubyMine
1. Open the preview environment of this PR
2. Create a workspace from the branch of this PR: https://github.com/gitpod-io/template-ruby-on-rails-postgres/pull/8
3. Check if the workspace opens with the project pre-indexed.
- WebStorm
1. Open the preview environment of this PR
2. Create a workspace from the branch of this PR: https://github.com/gitpod-io/template-typescript-react/pull/13
3. Check if the workspace opens with the project pre-indexed.
```release-note
NONE
```
=> Add missing Gitpod configurations for RubyMine and WebStorm

components/gitpod-db/src/typeorm/migration/1665054816691-RemoveUidFieldFromAuthCodeTable.ts
Drop the `uid` column on `d_b_oauth_auth_code_entry`.
The column is no longer used as of https://github.com/gitpod-io/gitpod/pull/13643.
⚠️ Merge and deploy https://github.com/gitpod-io/gitpod/pull/13643 first ⚠️ 
Part of #9198 
```release-note
NONE
```
=> [db] Drop `uid` column on `d_b_oauth_auth_code_entry`

components/usage-api/go/v1/billing.pb.go, components/usage-api/go/v1/billing_grpc.pb.go, components/usage-api/typescript/src/usage/v1/billing.pb.ts, components/usage-api/usage/v1/billing.proto
This will allow us to move the lookup of customers to a single place and improve our ability to respond to it consistently.
* Part of https://github.com/gitpod-io/gitpod/issues/13177
builds
```release-note
NONE
```
=> [usage] Add GetStripeCustomer to BillingService

components/common-go/process/process.go, components/common-go/process/process_test.go, components/supervisor/cmd/init.go, components/supervisor/go.mod, components/supervisor/go.sum, components/supervisor/pkg/supervisor/config.go, components/supervisor/pkg/supervisor/supervisor.go, components/supervisor/pkg/terminal/service.go, components/supervisor/pkg/terminal/terminal.go, components/supervisor/pkg/terminal/terminal_test.go
Changes the shutdown logic so that on SIGTERM or SIGINT on the `supervisor init` process we are sending SIGTERM to `supervisor` which in turn sends SIGTERM on all its terminal processes.
When supervisor finished we iterate over all of `init`'s child processes until the grace period is up.
Fixes #13365
Start a workspace https://se-supervi88c18dbe3b.preview.gitpod-dev.com/#https://github.com/svenefftinge/termination-test
Run 
```
./ignoresigterm > out_disown.txt &
disown $1
./ignoresigterm > out_bg.txt &
./ignoresigterm > out.txt
```
and stop the workspace.
With this preview environment you should see log output like below in all three files
```
awaiting signal
Received signal
terminated
Ignored for 0 seconds.
Ignored for 1 seconds.
Ignored for 2 seconds.
Ignored for 3 seconds.
Ignored for …
```
=> [supervisor] shutdown processes gracefully

components/gitpod-db/src/typeorm/entity/db-oauth-auth-code.ts
Remove the `uid` field from the oauth auth code entity.
This should have been done as part of https://github.com/gitpod-io/gitpod/pull/13644.
Part of #9198 
Make sure that a user can connect with VS Code Desktop and IntelliJ IDEA.
```release-note
NONE
```
=> [db] Remove `uid` field from entity

.github/workflows/jetbrains-updates-template.yml
For consistency with the other jobs / PRs
Fixes #
```release-note
```
=> chore: add jetbrains label to automated PRs

WORKSPACE.yaml
Update code to `1.72.0`
```release-note
Release VS Code Browser `1.72`
```
=> Build stable image for VS Code Browser 1.72

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/workspace/ide/constants.go
Updates the stable image of VS Code Browser to `1.72.0`
Fixes #
Open the preview environment, select VS Code Browser (non-`latest`) and in the <kbd>About</kbd> dialog check that we are on `1.72`.
```release-note
NONE
```
=> Update stable to `1.72.0`

components/server/ee/src/billing/billing-mode.ts
Use the cost center's billingStrategy to determine if a UBP team is paying.
Fixes #
```release-note
NONE
```
=> [server] don't rely on stripe for billingmode

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/migrations/job.go
Add `common.DefaultEnv` into the environment of the `migrations` job.
We want the the database migration job to have access to the `INSTALLATION_SHORTNAME` environment variable so that we can make use of it in upcoming migration scripts.
Part of #9198 
Get a `versions.yaml` for use with the installer:
```
docker run -it --rm "eu.gcr.io/gitpod-core-dev/build/versions:main.5066" cat versions.yaml > versions.yaml
```
Then invoke the installer as:
```
go run . render --debug-version-file versions.yaml --config /path/to/config
```
The migration job now has additional env vars defined:
```yaml
- name: GITPOD_DOMAIN
value: gitpod.example.com
- name: GITPOD_INSTALLATION_SHORTNAME
value: default
- name: GITPOD_REGION
value: local
- name: HOST_URL
value: https://gitpod.example.com
- name: …
```
=> [installer] Add default environment to the migration job

.werft/aks-installer-tests.yaml, .werft/cleanup-installer-tests.yaml, .werft/eks-installer-tests.yaml, .werft/k3s-installer-tests.yaml
This fixes the indentation of `nodeAffinity` so that it a sub-key of `affinity`
No issue - noticed this when working on other things.
Haven't tested sorry - seems safe 😅
```release-note
NONE
```
N/A
=> Fix indentation so nodeAffinity is used

operations/observability/mixins/meta/dashboards/components/ws-manager-bridge.json
This adds the panel for the metric `gitpod_ws_instances_marked_stopped_total`
Relates #12959
[Preview panel](https://3000-gitpodio-gitpod-h1dn5pqupod.ws-eu70.gitpod.io/d/ws-manager-bridge/gitpod-component-ws-manager-bridge?orgId=1&refresh=30s), but without any data.
```release-note
NONE
```
=> [grafana] Add Grafana panel for instances_marked_stopped

.werft/jobs/build/deploy-to-preview-environment.ts, .werft/jobs/build/prepare.ts, .werft/util/certs.ts, .werft/util/preview.ts, .werft/vm/vm.ts, dev/preview/infrastructure/harvester/provider.tf, dev/preview/infrastructure/harvester/svc.tf, dev/preview/infrastructure/harvester/variables.tf, dev/preview/infrastructure/harvester/vm.tf, dev/preview/install-k3s-kubeconfig.sh, dev/preview/ssh-vm.sh, dev/preview/util/download-and-merge-harvester-kubeconfig.sh, dev/preview/util/install-vm-ssh-keys.sh, dev/preview/util/setup-access.sh, dev/preview/workflow/lib/common.sh, dev/preview/workflow/lib/terraform.sh, dev/preview/workflow/preview/deploy-harvester.sh
This PR executes the TF workflow introduced in https://github.com/gitpod-io/gitpod/pull/12981 and https://github.com/gitpod-io/gitpod/pull/13319 in the context of werft.
Create job: https://werft.gitpod-dev.com/job/gitpod-custom-aa-preview-tf-werft-2.35
Delete job: https://werft.gitpod-dev.com/job/gitpod-custom-aa-preview-tf-werft-2.36
Will remove the manifests at a following PR.
Fixes https://github.com/gitpod-io/ops/issues/5224
```release-note
NONE
```
=> Preview vm create and delete uses the new TF flow

.werft/platform-trigger-werft-cleanup.sh
We introduced a static build nodepool in https://github.com/gitpod-io/ops/pull/5281 but it stays cordoned off and the instance never gets terminated, since it cannot scale down. 
This PR waits until there are no more pods with werft jobs on the node (after it's cordoned) and deletes the GCE instance. This will force its recreation with a fresh local volume.
Fixes #
```release-note
NONE
```
=> Delete cordoned node once it's empty during werft cleanup

components/dashboard/src/Menu.tsx, components/dashboard/src/components/UsageBasedBillingConfig.tsx, components/dashboard/src/images/check-circle.svg, components/dashboard/src/index.css, components/dashboard/src/settings/Billing.tsx, components/dashboard/src/teams/TeamBilling.tsx, components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Update billing page layout for usage-based teams and personal accounts.
Fixes https://github.com/gitpod-io/gitpod/issues/13405
2. Check the Team Billing UI
3. Upgrade the team by adding a credit card
4. Check the Team Billing UI again
5. Go to `/billing` (your individual billing settings)
6. Check your User Billing UI
7. Upgrade your user by adding a credit card
8. Check your User Billing UI again
```release-note
NONE
```
=> [Usage-based] Update billing page layout for teams and personal accounts

components/gitpod-db/src/typeorm/workspace-db-impl.ts, components/gitpod-db/src/workspace-db.ts, components/server/src/workspace/garbage-collector.ts
Incrementally removes Probe workspaces. This was originally done in https://github.com/gitpod-io/gitpod/pull/13477 but later rolled back in https://github.com/gitpod-io/gitpod/pull/13572 because it locked the table.
The approach here limits the deletes to 100 at a time to make it incremental.
Once we stop seeing the log `wsgc: successfully deleted ${deletes.length} Probe workspaces` (or it says 0), we can remove this again. If we land this approach, I'll cut a ticket to track the removal as well.
Fixes #
```release-note
NONE
```
=> [server] Garbage collect probe workspaces

components/public-api-server/go.sum, components/public-api-server/pkg/auth/auth.go, components/public-api-server/pkg/auth/auth_test.go, components/public-api-server/pkg/auth/context.go, components/public-api-server/pkg/auth/context_test.go, components/public-api-server/pkg/auth/middleware.go, components/public-api-server/pkg/auth/middleware_test.go, components/public-api-server/pkg/server/integration_test.go, components/public-api-server/pkg/server/server.go
Adds authentication interceptors for [connect](https://connect.build/) API on public-api.
This is a pre-cursor to refactoring existing handlers to use connect.
* Part of https://github.com/gitpod-io/gitpod/issues/13574
* Unit tests
```bash
➜ curl \
--header 'Content-Type: application/json' \
--data '{"workspaceId": "123"}' \
https://api.mp-public-8c1701f31b.preview.gitpod-dev.com/gitpod.v1.WorkspacesService/GetWorkspace | jq
{
"code": "unauthenticated",
"message": "empty authorization header: missing access token"
}
➜ curl \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer foo' \
--data '{"workspaceId": "123"}' \
https://api.mp-public-8c1701f31b.preview.gitpod-dev.com/gitpod.v1.WorkspacesService/GetWorkspace | jq
{
"code": "unimplemented",
"message": …
```
=> [public-api] Authentication interceptors for connect API

components/dashboard/src/contexts/FeatureFlagContext.tsx, components/dashboard/src/settings/Preferences.tsx, components/server/src/workspace/workspace-starter.ts
Workspace classes are now coupled to usage based pricing, so we should remove the feature flag. See [slack](https://gitpod.slack.com/archives/C02F19UUW6S/p1665176858966609) for additional context.
n.a.
```release-note
None
```
=> Remove workspace class feature flag

.github/workflows/code-nightly.yaml
It like does stuff to make VS Code Browser Insiders up-to-date with Insiders again.
```release-note
NONE
```
=> Update `code-nightly.yml` to pull from `gp-code/main` again

operations/observability/mixins/workspace/rules/nodes.yaml
The alert is quite noisy, so its utility is limited and we have the network limiting dashboard now.
See https://gitpod.slack.com/archives/C03QZ1NH517/p1665084593942539
```release-note
None
```
=> [obs] Remove NetworkConnectionsTooHigh alert

components/gitpod-db/src/typeorm/team-db-impl.ts
Block changing role on teams of size 1 (or less).
Fixes https://github.com/gitpod-io/gitpod/issues/11452
```release-note
[teams] Disallow removing all Owners from a team
```
=> [server]  Disallow removing all Owners from a team

dev/preview/workflow/lib/terraform.sh
Adds a lock-timeout so jobs can wait a bit for the lock to get released, instead of failing immediately and a general timeout on `apply`. 
Fixes #
```release-note
NONE
```
=> Add a lock timeout for plan/apply and general timeout on apply

install/installer/pkg/common/common.go, install/installer/pkg/components/agent-smith/daemonset.go, install/installer/pkg/components/blobserve/deployment.go, install/installer/pkg/components/content-service/deployment.go, install/installer/pkg/components/image-builder-mk3/deployment.go, install/installer/pkg/components/registry-facade/daemonset.go, install/installer/pkg/components/server/deployment.go, install/installer/pkg/components/ws-daemon/daemonset.go, install/installer/pkg/components/ws-manager-bridge/deployment.go, install/installer/pkg/components/ws-manager/deployment.go, install/installer/pkg/components/ws-proxy/deployment.go, install/installer/pkg/config/v1/config.go
Fixes https://github.com/gitpod-io/gitpod/issues/13381
Fixes https://github.com/gitpod-io/gitpod/issues/13385
- Configure the installer setting 
```
tracing:
secretName: XXXXX
```
and verify the env variables`JAEGER_USER` and `JAEGER_PASSWORD` are configured.
```release-note
Add option to add authentication to Jaeger and configure default tags with `metadata.shortName` and `metadata.region`
```
=> Add option to add authentication to Jaeger and custom tags

components/server/ee/src/billing/entitlement-service-ubp.ts
[See (internal) context](https://gitpod.slack.com/archives/C02EN94AEPL/p1665330076083099?thread_ts=1665177158.389409&cid=C02EN94AEPL)
Fixes #
```release-note
NONE
```
=> [server] Use CostCenter to determine if user has paid subscription

.github/CODEOWNERS
Renames the team handle of the Delivery and Operations Experience Team in `CODEOWNERS`.
https://github.com/orgs/gitpod-io/teams/engineering-delivery-operations-experience
```release-note
NONE
```
=> Rename Self-Hosted Team in CODEOWNERS

operations/observability/mixins/platform/rules/argocd/servicemonitor.yaml
Add service monitors to be imported by satellite to retrieve metrics from argocd
Fixes https://github.com/gitpod-io/ops/issues/5296
```release-note
NONE
```
=> add servicemonitors for argocd

dev/preview/BUILD.yaml, dev/preview/workflow/lib/ensure-gcloud-auth.sh, dev/preview/workflow/preview/build.sh, dev/preview/workflow/preview/deploy-gitpod.sh
This is a step towards https://github.com/gitpod-io/ops/issues/5766. It introduces two new leeway scripts, one to build the installer and one to run it.
The build script ensures that you're logged into GCP so that Leeway can use the remote cache - there's an issue to remove this requirement in the future #13714.
It doesn't actually try to install Gitpod yet - it just generates a config file to show that we're able to invoke the installer. I will follow up with other PRs.
Things I'll do in follow-up PRs
- It doesn't use the cache for some components (e.g. dashboard) where I would expect it too. Follow up issue here https://github.com/gitpod-io/gitpod/issues/13767
- Downloading the remote cache takes more than 4 minutes. Follow up issue here https://github.com/gitpod-io/ops/issues/5814
- …
=> Add leeway dev/preview:build and dev/preview:deploy-gitpod

components/supervisor/pkg/ports/exposed-ports.go, components/supervisor/pkg/supervisor/supervisor.go
Expose ports locally in supervisor (private is default available in ws-proxy)
**Context**
`ws-proxy` served every port in private, the user can access them or not is depending on if the ports are served.
This means auto `openPort` with private (call server API) in supervisor makes no sense (they are already in `private` state). So we can do it in supervisor locally
**Result**
With this PR, we can reduce 99% of useless requests, 99% comes from **Affect** section below
**Affect**
> _(Ignore `.gitpod.yml` ports defined with public)_
From Grafana, we can see today's `openPorts` calling total is around 60k, but users only change ports visibility (via vscode) 314 times today.
|Grafana|
|-|
|<img width="1920" alt="image" src="https://user-images.githubusercontent.com/20944364/193014963-a6091507-3 …
=> [supervisor] local exposed

install/tests/Makefile
This pull request enhances diagnostics collection when a Gitpod self-hosted run fails. As the infrastructure is torn down at the end of a failed test, the underlying cause of test failures cannot be diagnosed against the infrastructure directly so collecting various diagnostic information provides an option for post-hoc analysis. This collection should reduce the number of CI runs needed to locate and fix installation failures.
```bash
gsutil cat gs://nightly-tests/nightly-tests-errors/24ac6-k3s/pods.json \
| jq -r '[.items[] | select(.status.conditions[] | any(. == "False")) | {metadata, status}]'
```
```release-note
NONE
```
=> [installer/tests] upload diagnostics when installation fails

WORKSPACE.yaml
Update code to `1.72.1` (update Insiders to build stable images)
```release-note
NONE
```
=> Build images for 1.72.1

components/ws-manager/pkg/manager/manager.go, components/ws-manager/pkg/manager/status.go
Ignore the FailedMount event with the message contains `MountVolume.MountDevice failed for volume`.
The ws-manager catches the [FailedMount event](https://github.com/gitpod-io/gitpod/blob/65e99997bc3837f360b23d0dc181ef096dd3febf/components/ws-manager/pkg/manager/status.go#L615-L627) and writes the error message into the workspace [Conditions.Failed](https://github.com/gitpod-io/gitpod/blob/65e99997bc3837f360b23d0dc181ef096dd3febf/components/ws-manager/pkg/manager/status.go#L322).
Then the [workspace pod is stopped](https://github.com/gitpod-io/gitpod/blob/65e99997bc3837f360b23d0dc181ef096dd3febf/components/ws-manager/pkg/manager/monitor.go#L275-L298), and the [workspace failed message](https://github.com/gitpod-io/gitpod/blob/65e99997bc3837f360b23d0dc181ef096dd3febf/components/ws-manager/p …
=> Skip "MountVolume.MountDevice failed for volume"

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/workspace/ide/constants.go
Updates the stable image of VS Code Browser to `1.72.1`
Fixes #
Open the preview environment, select VS Code Browser (non-`latest`) and in the <kbd>About</kbd> dialog check that we are on `1.72.1`.
```release-note
NONE
```
=> Update stable to `1.72.1`

.werft/jobs/build/job-config.ts, .werft/jobs/build/self-hosted-upgrade-tests.ts, install/tests/Makefile
This PR adds an extra flag `version` to the werft command to spin up self-hosted preview environments. Considering different teams might want to test specific versions of Gitpod self-hosted, this would be an improvement in experience. This PR also fixes a small bug that ran integration tests when running preview.
Once the PR is merged, if the user wants to create a GKE cluster with Gitpod 2022.8.0 installed, they can simply do:
```
/werft run with-sh-preview version=2022.8.0 channel=stable
werft run github -j .werft/build.yaml -a with-sh-preview=true -a channel=stable -a version=2022.8.0
```
Considering that the users were having issues finding the werft job that gets spun up from the first job, I have also added a URL to the new werft job in the results tab of the first.
Fixes #
You can …
=> [self-hosted-preview] Support version specification in preview

.werft/util/certs.ts, dev/preview/infrastructure/harvester/variables.tf
Cert replace forces the default values of the cpu/memory to change, so set them always. 
Will move this later in a common place.
Fixes #
```release-note
NONE
```
=> [Preview env] Fix cert recreation

.werft/util/preview.ts
If there's a `preview` anywhere in the name of the branch/preview env, it will get replaced and the delete will fail. This handles the prefix properly.
Fixes #
```release-note
NONE
```
=> Fix preview name prefix

components/proxy/conf/Caddyfile, components/public-api-server/pkg/apiv1/prebuild.go, components/public-api-server/pkg/apiv1/prebuild_test.go, components/public-api-server/pkg/apiv1/workspace.go, components/public-api-server/pkg/apiv1/workspace_test.go, components/public-api-server/pkg/proxy/errors.go, components/public-api-server/pkg/proxy/errors_test.go, components/public-api-server/pkg/server/integration_test.go, components/public-api-server/pkg/server/server.go, dev/gpctl/cmd/public-api.go
In this PR, we 1-1 map the old implementation in gRPC to the new implementation with Connect. Changes are deliberately not made to streamline the tests and simplify to keep the PR cleaner.
In general, the changes are the following (see [docs](https://connect.build/docs/go/grpc-compatibility#migration))
1. Use the generated ServiceHandlers
2. Wrap requests and responses in `connect.NewRequest` or `connect.NewResponse`
3. Use Connects error codes
4. Use HTTP server in tests
This PR also changes default routing of `api.<domain>` requests to the HTTP server, this has the following effect:
* Connect handlers handle both gRPC and HTTP traffic - this is fine, as Connect is designed for this
* Depending on the rollout sequencing, there can be a brief period where requests would fail. This is OK, …
=> [public-api] Refactor to use connect handlers, route to HTTP server

dev/loadgen/README.md, dev/loadgen/cmd/benchmark.go, dev/loadgen/configs/prod-benchmark-pvc.yaml, dev/loadgen/configs/prod-benchmark.yaml, dev/loadgen/configs/workspace-preview-benchmark-pvc.yaml, dev/loadgen/configs/workspace-preview-benchmark.yaml
Support custom workspace timeout.
Related to #12747
Run loadgen and check the workspace pod annotation `gitpod/customTimeout` matches to the config setting.
```release-note
None
```
None
=> loadgen: support custom workspace timeout

.werft/jobs/build/deploy-to-preview-environment.ts, .werft/jobs/build/installer/installer.ts, .werft/jobs/build/job-config.ts
Don't really see any reason to have to opt-in to it. It causes a good deal of friction when we forget.
Fixes #
Preview
```release-note
NONE
```
=> [preview] Include with-payment in default configuration

.github/CODEOWNERS
Because we should assign ownership to teams, not individuals
Fixes #
```release-note
NONE
```
=> [codeowners] Make WebApp codeowners of ws-manager-bridge-api

install/infra/modules/aks/local.tf, install/infra/modules/aks/output.tf, install/infra/modules/eks/local.tf, install/infra/modules/eks/output.tf, install/infra/modules/eks/providers.tf, install/infra/modules/eks/variables.tf, install/infra/modules/tools/cloud-dns-ns/main.tf, install/infra/single-cluster/aws/output.tf, install/infra/single-cluster/azure/cluster.tf, install/infra/single-cluster/azure/output.tf, install/infra/single-cluster/gcp/cluster.tf, install/infra/single-cluster/gcp/output.tf, install/infra/single-cluster/gcp/terraform.tfvars, install/infra/single-cluster/gcp/tools.tf, install/tests/main.tf
This PR is the second of the 3 part PR that uses terraform reference architecture to run tests. The main goal of this PR is to align all the reference architecture modules so these can be invoked in a standard manner using the `make` targets. Other than a bunch of linting fixing, the `name_servers` output had a standardization fix.
Here are the other two PRs:
Fixes #
```release-note
NONE
```
=> [terraform] prepare terraform modules to use for tests

dev/preview/infrastructure/harvester/variables.tf
Removed this, but forgot to readd it in last PR and deleting fails right now.
Fixes #
https://werft.gitpod-dev.com/job/gitpod-custom-platform-artificial-job-557d32093681636f3ad2.0/logs
```tf
STDERR: ╷
│ Error: No value for required variable
│
│   on variables.tf line 28:
│   28: variable "vm_storage_class" {
│
│ The root module input variable "vm_storage_class" is not set, and has no
│ default value. Use a -var or -var-file command line argument to provide a
│ value for this variable.
╵
ERROR: Terraform plan failed
```
```release-note
NONE
```
=> Re-add default value for storage class

install/infra/modules/aks/kubernetes.tf, install/infra/modules/aks/local.tf, install/infra/modules/aks/variables.tf
This pull request breaks up the AKS workloads into separate services, regular workspace, and headless workspace node pools. It also plumbs through machine type and node pool max instance counts.
See https://github.com/gitpod-io/gitpod/issues/12740
Create a self-hosted preview with werft:
```
werft run github -j .werft/aks-installer-tests.yaml -a deps=external -a preview=true
```
Then configure the git integration, run a workspace, and ensure that imagebuilds/regular workspaces run on separate nodes.
```release-note
[terraform/aks] Separate workloads into different pools, expose terraform variables for max node pool counts
```
=> [terraform/aks] Implement separate nodepool types, node pool max sizes, machine types

components/proxy/conf/Caddyfile, components/proxy/plugins/corsorigin/cors_origin.go
Extends our CORS plugin configuration to specify AllowedOrigins. This is done because the `BaseDomain` subdirective does not work (see https://github.com/gitpod-io/gitpod/pull/13740 for why), and in this case because we're enabling the cors for the sub-domain (api.<domain>) but allowing traffic from the root domain, we cannot use the `BaseDomain` directive anyway.
* Part of https://github.com/gitpod-io/gitpod/issues/13574
Test we get the expected `Access-Control-Allow-*` headers when Origin is GITPOD_DOMAIN
```
curl https://api.mp-proxy-c2a55ca9ff1.preview.gitpod-dev.com/ \
-H "Origin: https://mp-proxy-c2a55ca9ff1.preview.gitpod-dev.com" \
-H "Access-Control-Request-Method: POST" \
-H "Access-Control-Request-Headers: X-Requested-With" \
-X OPTIONS -i
HTTP/2 204 …
```
=> [proxy] Enable CORS for api.<domain> from https://<domain> origin

.werft/installer-tests.ts, install/tests/tests.sh
So far we have been trying to run all the integration tests every night and this caused several timeout issues and we noticed some tests affecting the setup in a way that other tests ended up failing. So this is the first step towards making the tests pass. This PR splits up the tests team wise (IDE, workspaces, and webapp). Every night, against each of the architecture one of the tests run and send slack alert to the corresponding team channel. If one wants to explicitly specify a test suite they can use the annotation `testSuite` with one of these values: `ide`, `workspaces`, `webapp`.
Alongside the PR also increases the timeout of each test to the maximum value. This ensure each test gets as much time as possible and if it get stuck, the process will be killed by the hard timeout of …
=> [installer-tests] Splitting the integration tests

.werft/installer-tests.ts
This commit dumps the installer tests configuration at the beginning of the job. If unforeseen errors arise it will be simpler to determine if the tests are aborting early.
Fixes #
```
werft run github -j .werft/k3s-installer-tests.yaml  -a domain=tests.doptig.com 
```
[gitpod-custom-alt-installer-tests-log-job-config.0](https://werft.gitpod-dev.com/job/gitpod-custom-alt-installer-tests-log-job-config.0)
```release-note
NONE
```
=> [installer-tests] dump config at start of test

components/dashboard/src/components/UsageBasedBillingConfig.tsx, components/gitpod-protocol/src/gitpod-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/gitpod-server-impl.ts
Adjust Stripe usage limits to spec
Part of https://github.com/gitpod-io/gitpod/issues/13389
~~Depends on https://github.com/gitpod-io/gitpod/pull/13798~~
2. Go to team billing
3. There shouldn't be a visible usage limit
4. Upgrade the team by adding a payment method
5. The default usage limit should be `1000 * team_size` (but you can set it to any value)
6. Go to your individual billing settings
7. The usage limit should be `500` (not editable)
8. Upgrade by adding a payment method
9. The usage limit should now be `1000`, and you should be able to set any value >= 1000 (but not < )
10. Cancel your individual user subscription
11. The limit should be back to `500` (not editable)
```release-note
NONE
``` …
=> [Usage-based] Adjust Stripe usage limits to spec

.github/workflows/jetbrains-update-plugin-platform.yml, .gitpod.yml, components/BUILD.yaml, components/ide/jetbrains/gateway-plugin/.gitignore, components/ide/jetbrains/gateway-plugin/BUILD.yaml, components/ide/jetbrains/gateway-plugin/build.gradle.kts, components/ide/jetbrains/gateway-plugin/gradle-latest.properties, components/ide/jetbrains/gateway-plugin/gradle-stable.properties, components/ide/jetbrains/gateway-plugin/gradle.properties, components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/latest/GitpodConnector.kt, components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/latest/GitpodConnectorView.kt, components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/stable/GitpodConnector.kt, components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/stable/GitpodConnectorView.kt, components/ide/jetbrains/gateway-plugin/src/main/resources-latest/META-INF/extensions.xml, components/ide/jetbrains/gateway-plugin/src/main/resources-stable/META-INF/extensions.xml, components/ide/jetbrains/gateway-plugin/src/main/resources/META-INF/plugin.xml
Allows us to build `stable` and `latest` versions of the JB Gateway Plugin simultaneously and fix our JB Gateway Integration Tests.
We used the code of these two PRs as reference: [#10595](https://github.com/gitpod-io/gitpod/pull/10595/files), [#13018](https://github.com/gitpod-io/gitpod/pull/13018/files).
Note: We are using platform version 223.4x instead of 223.6x for EAP version due to [this issue](https://github.com/JetBrains/gradle-intellij-plugin/is).
Fixes #13581
- Download the latest build from this branch from the [marketplace](https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions/dev)
- Install it in EAP gateway
- Observe that everything works as expected
- Download the stable version built from this branch from the …
=> feat(gateway-plugin): allow spearate builds for stable and latest

.werft/jobs/build/installer/installer.ts, components/usage/pkg/apiv1/usage_test.go, components/usage/pkg/db/cost_center.go, components/usage/pkg/db/cost_center_test.go, install/installer/pkg/components/usage/configmap.go, install/installer/pkg/components/usage/configmap_test.go
Enforces usage limit values for users & teams.
Adds a new piece of config for the default value of UsersOnStripe. When this rolls out, it will be 0 (due to missing config) but because we set it on the `server` side, this is okay and the check here will simply check if new limit is > 0. We'll add the config to ensure it does not prevent setting lower in subsequent PR.
Fixes #
```release-note
NONE
```
=> [usage] Validate spending limits in UpdateCostCenter

operations/observability/mixins/IDE/rules/opensvx.yaml
Inspired by https://github.com/gitpod-io/gitpod/pull/13766, this PR updates PrometheusRules from the IDE team to make sure they work as expected with the new Centralized alerting infrastructure.
Work done while pairing with @felladrin  🙂 
Fixes https://github.com/gitpod-io/ops/issues/5599
```release-note
NONE
```
=> Adjust IDE alerts to work with centralized alerting

WORKSPACE.yaml
Bring commits to `1.72`
- Responsive PortsView https://github.com/gitpod-io/openvscode-server/commit/e5089bafb51f28d7a8e5a125f5b4e4b9a63462e8
- Compile bug fixing https://github.com/gitpod-io/openvscode-server/commit/8d1a8793eaf27255dccb3e2562fa423bae0b9c97
Fixes #
- Start a workspace in preview env with **Latest Code**
- Check if portsView is responsive and Code Browser works basically
```release-note
VSCode Browser/Desktop: Responsive portsView
```
=> [code] build stable code image to bring responsive PortsView

components/ide/jetbrains/backend-plugin/gradle-latest.properties, components/ide/jetbrains/backend-plugin/launch-dev-server.sh, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortForwardingService.kt, components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
Now that we have EAP IDEs build 223.6x available in gitpod.io, we need to update the back-end plugin with the support for the new Port Forwarding API.
In the current state of this PR, the plugin compiles and makes the auto-forwarding work again for EAP IDEs.
In a follow-up PR we should:
- Ensure the usage of port name/description columns is working.
- Remove the unused function overrides from `object: ForwardedPortListener`.
- Confirm there's no other way to dispose the forwarded ports listeners (currently we use a map for it).
- Confirm if ports are removed from the UI when programatically removed.
- Fixes #13761
1. Open the preview environment of this PR: https://jetbrains-d939b7c0c7.preview.gitpod-dev.com/workspaces
2. In the account preferences, select the _Latest_ JetBrains IntelliJ …
=> Fix the auto-port-forwarding on JetBrains EAP IDEs

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/workspace/ide/constants.go
Fixes #13778
- Open workspace with **Stable Code** in Firefox / Arc Browser in preview env
- Check if portsView address will NOT open twice
```release-note
VSCode: Fix portsView address open twice in some browsers
```
=> [code] fix portsView address open twice #13778

components/ws-manager/pkg/manager/probe.go, test/pkg/integration/workspace.go, test/tests/components/ws-manager/prebuild_test.go
This PR fixes some issue from `ws-manager`
1. `ws-manager` do not follow redirect when it run ide ready probe
2. `ws-manager` will check ide ready response, it include `ok` status
3. using `/_supervisor/v1/status/ide/wait/true` API in order to reduce request
And do some minor change for integration test
1. using workspaceId as `servicePrefix`, because `ws-proxy` will check the hostname regex
2. refactor some workspace integration-test, to make it pass
Fixes #
integration test should pass
1. start a workspace in preview environment, it should work as before
```release-note
NONE
```
=> [ws-manager] Do not follow redirect when ready probe

operations/observability/mixins/workspace/dashboards/success-criteria.json
Fix new workspace does not show workspace success rate because no workspace failed in metric `gitpod_ws_manager_workspace_stops_total`.
Partially #12364
was:
is:
```release-note
None
```
None
=> obs: fix new workspace does not shown workspace success rate

components/ws-manager/pkg/manager/create.go
`NODE_EXTRA_CA_CERTS` is a variable used inside gitpod, but it was encrypted.
Fixes #13735
- Open a workspace on https://c16f5-aws.tests.gitpod-self-hosted.com/workspaces
```release-note
Fix an issue with a workspace not starting with a self-signed cluster
```
=> ws-manager: `NODE_EXTRA_CA_CERTS` is the value of the gitpod internals

WORKSPACE.yaml
Update code to `1.72.2`
```release-note
NONE
```
=> Build stable images for `1.72.2`

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/workspace/ide/constants.go
Updates the stable image of VS Code Browser to `1.72.2` (https://github.com/microsoft/vscode/releases/tag/1.72.2)
A part of https://github.com/gitpod-io/gitpod/issues/13410
Open the preview environment, select VS Code Browser (non-`latest`) and in the <kbd>About</kbd> dialog check that we are on `1.72.2`.
```release-note
NONE
```
=> Update stable to `1.72.2`

components/dashboard/src/contexts/FeatureFlagContext.tsx, components/gitpod-protocol/src/experiments/configcat.ts, components/gitpod-protocol/src/experiments/types.ts, components/server/ee/src/billing/billing-mode.ts, components/server/ee/src/workspace/workspace-factory.ts, components/server/src/workspace/config-provider.ts, components/server/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/workspace-starter.ts
Before we land this, we need to adjust our existing feature flag configuration to use `team_id CONTAINS <list of IDs>` such that it continues to work 
In this change, we entirely remove the ability to supply a list of teams to configcat. We're doing this because it creates confusion on how the flag actually behaves. In the cases where we need to evaluate against multiple teams, we loop over them. This doesn't actually incur any extra network overhead as the flags are cached by the client so while the firs call may require a fetch (which it did before also), the subsequent calls will be resolved using a local cache.
Fixes #
* On preview, create a team and add it to Configcat's UBP config for non-prod as `user_id ONE OF <your team ID>.
* Wait for the flag to propagate (around 3 minutes)
* …
=> [configcat] Do not supply lists to configcat evaluations

components/dashboard/src/projects/Prebuild.tsx, components/gitpod-protocol/src/protocol.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/ee/src/workspace/workspace-factory.ts, components/server/src/container-module.ts, components/server/src/workspace/open-prebuild-prefix-context-parser.ts
_(Werft was having too much trouble with https://github.com/gitpod-io/gitpod/pull/13706 hence the new PR 👇)_
This PR enables users to open a specific prebuildm, and integrates this capability on the dashboard.
1. Make sure there's a prebuild and a newer commit on the same branch
2. Go the prebuild view
3. Open the specific prebuild and observe it's the correct state
```release-note
[prebuild] Add support for opening specific prebuilds
```
=> [prebuild] Support opening a specfic prebuild

operations/observability/mixins/IDE/rules/ssh-gateway.yaml
Add a Prometheus alert rule for SSH Gateway - monitor for Connection issues.
```release-note
NONE
```
=> Add a Prometheus alert rule for SSH Gateway

.werft/installer-tests.ts, install/infra/modules/k3s/main.tf, install/infra/modules/k3s/output.tf, install/tests/Makefile, install/tests/manifests/aws-terraform.tfvars, install/tests/manifests/azure-terraform.tfvars, install/tests/manifests/gcp-terraform.tfvars, install/tests/manifests/k3s-terraform.tfvars, install/tests/manifests/managed-dns.tf, install/tests/manifests/tf-backend.tf
This PR changes the `installer-tests.ts` and the `Makefile` being called from it, to use the single-cluster reference architecture to run the integration tests. This is the third of a 3 part PR series. This PR requires the other two PRs to be gone in first and that would reduce the file changes in this file to very few in number.
The two preceding PRs are: **TO BE REVIEWED BEFORE REVIEWING THIS PR**
The following are the test runs:
k3s: https://werft.gitpod-dev.com/job/gitpod-custom-nvn-add-tf-tests.31 :heavy_check_mark:
gke: https://werft.gitpod-dev.com/job/gitpod-custom-nvn-add-tf-tests.32 :heavy_check_mark:
aks: https://werft.gitpod-dev.com/job/gitpod-custom-nvn-add-tf-tests.33 :heavy_check_mark:
eks: https://werft.gitpod-dev.com/job/gitpod-custom-nvn-add-tf-tests.34 :heavy_check_mark: …
=> [installer-tests] Use reference architecture to run integration tests

components/server/ee/src/billing/billing-mode.ts
We wouldn't ask ConfigCat for the feature flag value if there were no teams associated. This fixes that.
Fixes #13886 
1. Onboard your preview user to the feature
2. See the UI offers switching to UBP
3. Check that once you create a team on no plan, you can still upgrade to UBP
```release-note
NONE
```
=> [usage] Check UBP even without any teams

install/installer/pkg/components/usage/deployment.go
Ensure that deployment restarts when config changes.
Fixes #
```release-note
NONE
```
=> [usage] Set configmap hash on deployment

install/tests/Makefile
Since we use the dev image which already has the kots pre-installed, there is no necessity for the installation of kots when running automated installer tests. This PR removes this extra step.
Fixes #
```release-note
NONE
```
=> [installer-tests] remove duplicate kots install from Makefile

components/server/ee/src/billing/billing-mode.ts
We're not using pattern matching on team names in prod, but do so in dev for ease of testing.
Let's keep it in until we found a better way to handle it. :+1: 
Fixes #
```release-note
NONE
```
=> [server] BillingMode: pass team.name

.github/CODEOWNERS
Rename "Platform" team to "DevX" team
Fixes #https://gitpod.slack.com/archives/C01KGM9EBD4/p1665760161797129
```release-note
NONE
```
=> Rename "Platform" team to "DevX" team

operations/observability/mixins/platform/rules/argocd/servicemonitor.yaml
@liam-j-bennett I've taken another look at the configuration and I've noticed that we're deploying the servicemonitor in a different namespace from where ArgoCD is deployed. To fix this we can define a NamespaceSelector.
I've tried this change manually and noticed that this fixed the issue 🙂 
Fixes #
```release-note
NONE
```
=> Add Namespace Selector for ArgoCD ServiceMonitors

components/dashboard/src/settings/settings-menu.ts
Render UBP menu entries if users can upgrade.
Fixes #13886
```release-note
NONE
```
=> [dashboard] UBP: Render relevant menu entries if users can upgrade

components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts, components/gitpod-db/src/typeorm/migration/1665071320428-AddColumnToWorkspaceClusterTable.ts, components/gitpod-db/src/typeorm/workspace-cluster-db-impl.ts, components/gitpod-protocol/src/workspace-cluster.ts, components/ws-manager-api/typescript/src/client-provider.spec.ts, components/ws-manager-bridge/src/cluster-service-server.ts
To do that we will introduce a new field in the table called `applicationCluster` which records the name of the application cluster to which the record belongs. Thus, for each workspace cluster there will be two rows in Gitpod SaaS:
| name | applicationCluster …
=> [db] Add `applicationCluster` field to `d_b_workspace_cluster` table

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/cleanup-installer-tests.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environment.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile
Update the dev image to use the latest version of the `workspace-full` image.
Also runs the `kots` installation with `sudo` now that the `kots` installation script has changed to require this.
```release-note
NONE
```
=> [dev] Update dev image

install/installer/pkg/config/v1/envvars.go
It's possible that this can contain sensitive data
Fixes #
Install via KOTS
```release-note
[installer]: remove logging of envvar obj
```
=> [installer]: remove logging of envvar obj

.werft/jobs/build/prepare.ts, .werft/util/certs.ts, .werft/vm/vm.ts
https://github.com/gitpod-io/gitpod/pull/13627 introduced the ability to stream logs from subprocesses. This PR makes the calls to the TF scripts use that.
Verified that the streaming works in:
https://werft.gitpod-dev.com/job/gitpod-custom-aa-stream-tf.0
https://werft.gitpod-dev.com/job/gitpod-custom-aa-stream-tf.1
Fixes #
```release-note
NONE
```
=> Stream logs from TF executions

operations/observability/mixins/self-hosted/dashboards.libsonnet, operations/observability/mixins/self-hosted/dashboards/argocd/argocd.json
Adds a dashboard for monitoring ArgoCD itself and also applications managed by it
A preview of the dashboard can be [seen here](https://grafana.gitpod.io/d/argocd-apps/argocd?orgId=1&from=now-1h&to=now&refresh=30s&var-datasource=VictoriaMetrics&var-namespace=All&var-interval=5m&var-grouping=name&var-cluster=https:%2F%2F34.77.248.243&var-health_status=All&var-sync_status=All&var-environment=All)
Fixes https://github.com/gitpod-io/ops/issues/5298
```release-note
NONE
```
=> Add dashboard for ArgoCD applications' state

.werft/jobs/build/installer/installer.ts, .werft/jobs/build/installer/post-process.sh
Fix the broken installation short name in preview environments.
The commit was cherry-picked from a larger PR (https://github.com/gitpod-io/gitpod/pull/13866).
Indirectly related to #13800.
In the preview environment run:
``` bash
kubectl exec deploy/ws-manager-bridge -- env | grep GITPOD_INSTALLATION_SHORTNAME
```
The value is set to `"dev"` as opposed to `""`.
```release-note
NONE
```
=> [preview] Fix broken shortname assignment in preview envs

.github/workflows/jetbrains-update-plugin-platform-template.yml, .github/workflows/jetbrains-updates-template.yml
This PR brings two changes:
- Change also the `pluginSinceBuild` Gradle property when updating JetBrains Plugins via GitHub Action. Previously, we were updating only the `platformVersion` which could cause incompatibilities with old JetBrains Gateway versions.
- Comment out the line `team-reviewers: "engineering-ide"`, to avoid the action failing (when it's actually creating the Pull Request properly). (See https://github.com/gitpod-io/gitpod/issues/12194)
| Screenshot from the error on slack when `team-reviewers: "engineering-ide"` is set |
| --- |
| <img width="439" alt="image" src="https://user-images.githubusercontent.com/418083/196166436-bdd82f50-d96d-4a18-89b3-9d13df220a02.png"> |
Optional: Click "Run Workflow" (targeting the `jetbrains/update-also-plugin-since-build-property` …
=> Change also "pluginSinceBuild" property when updating JetBrains Plugins via GitHub Action

components/ws-daemon/nsinsider/main.go, components/ws-daemon/pkg/daemon/daemon.go, components/ws-daemon/pkg/netlimit/config.go, components/ws-daemon/pkg/netlimit/netlimit.go, install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/ws-daemon/configmap.go, install/installer/pkg/config/v1/experimental/experimental.go
Provide an option to drop traffic if network connections go over the configured limit. Also changes to the netlimit configuration can now be applied without having to restart ws-daemon.
n.a.
- Ensure that ws-daemon config map looks like this
```
"netlimit": {
"enabled": true,
"enforce": true,
"connectionsPerMinute": 1000,
"bucketSize": 1000
},
```
- Open workspace in [preview environment](https://fo-enforce-limiting.preview.gitpod-dev.com/workspaces)
- Workspace should have label gitpod.io/netConnLimitPerMinute
- SSH into preview vm and find workspace ring 0 process
- Use the process id to enter the network namespace
- Check that nftable rules will drop traffic 
- Edit the config map of ws-daemon e.g. change connections per minute
- Wait ~1 minute for changes to propagate
- Start new …
=> Provide option to enforce network connection rate limiting

.werft/jobs/build/build-and-publish.ts, .werft/jobs/build/job-config.ts, WORKSPACE.yaml, components/ide/jetbrains/gateway-plugin/BUILD.yaml
This PR remove `jbMarketplacePublishTrigger` to avoid publishing builds which have no relevant changes in the gw
Relate #13654
It need merge to main, and see what is effect
```release-note
NONE
```
=> [werft] only publish jetbrains gateway plugin when relevant file changes

.werft/jobs/build/deploy-to-preview-environment.ts, dev/preview/infrastructure/harvester/cert.tf
This PR activates the ZeroSSL certificate issuer that's introduced in https://github.com/gitpod-io/ops/pull/5970.
Letsencrypt is amazing - but ZeroSSL has no rate limit.
Fixes https://github.com/gitpod-io/ops/issues/5571
```release-note
NONE
```
=> Use SSL Certs from ZeroSSL in Preview Envs

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/ws-manager-bridge/objects.go, install/installer/pkg/components/ws-manager-bridge/types.go
<details>
To do that we will introduce a new field in the table called `applicationCluster` which records the name of the application cluster to which the record belongs. Thus, for each workspace cluster there will be two rows in …
=> [installer] Add `applicationCluster` to statically configured workspace clusters

.werft/jobs/build/installer/installer.ts, .werft/jobs/build/installer/post-process.sh
Reverts gitpod-io/gitpod#13953
Due to a new certificate error when starting workspaces in preview environments:
[More context in Slack](https://gitpod.slack.com/archives/C032A46PWR0/p1666109181630429) (internal)
=> Revert "[preview] Fix broken shortname assignment in preview envs"

components/content-service/pkg/initializer/git.go
Fix invalid return statement in `defer`
```release-note
NONE
```
=> [content-service] Fix invalid defer return

components/content-service/pkg/git/git.go, components/content-service/pkg/initializer/git.go, components/content-service/pkg/initializer/prebuild.go
against submodule update problems, and awry fetch situations.
This PR 
- makes the prebuild content initializer more robust against submodule issues, by adopting the same error behaviour of the Git initializer,
- removes the "fetch all branches and tags" behaviour in the prebuild initializer which was intended to ensure that we can checkout the clone target. Instead, we make a dedicated (no submodule recursing) fetch for the clone target.
works on #9280
- run the workspace integration tests to make sure we didn't break anything
- deploy in production as see if the "content init failed" failures go down.
```release-note
NONE
```
=> [content-service] Make prebuild initializer more robust

.werft/workspace-run-integration-tests.sh
NONE
Run a job
```
werft run github -j ./.werft/workspace-run-integration-tests.yaml
```
```release-note
NONE
```
=> test: Show a commit hash on the nightly job

components/gitpod-db/src/typeorm/migration/1666162573134-RecreateStripeCustomersTable.ts
Recreates it, because I've accidentally named the PK with underscore case.
Fixes #
```release-note
NONE
```
=> [stripe] Recreate d_b_stripe_customer table

components/public-api-server/pkg/server/metrics.go, components/public-api-server/pkg/server/metrics_test.go, components/public-api-server/pkg/server/server.go
Reports client & server metrics on requests started and completed. Currently only applies to Unary calls, but can be extended.
Fixes #
```release-note
NONE
```
=> [public-api] Add client/server metrics interceptor

dev/gpctl/cmd/clusters-list.go
<details>
To do that we will introduce a new field in the table called `applicationCluster` which records the name of the application cluster to which the record belongs. Thus, for each workspace cluster there will be two rows in …
=> [gpctl] Show application cluster in `gpctl clusters list` output

components/ws-manager-bridge/BUILD.yaml, components/ws-manager-bridge/src/bridge.ts, components/ws-manager-bridge/src/container-module.ts, components/ws-manager-bridge/src/workspace-instance-controller.ts
Preparations in order to work on #6770:
- make telepresence work again
- fix a bug in how we configure preview envs ([commit](https://github.com/gitpod-io/gitpod/pull/13866/commits/97733893fe9580e455b5c115b87c1d0d5626726a))
- extract `WorkspaceInstanceController` from `Bridge` (code move only, zero function change)
Context: #6770
- open [a workspace on this PR](https://github.com/gitpod-io/gitpod/pull/13866) and see that the `ws-manager-bridge` deployment run without issues
- check logs of `ws-manager-bridge` and not that there are no errors
- start a workspace and notice how everything works as expected.
```release-note
NONE
```
=> [bridge] Extract WorkspaceInstanceController

components/server/ee/src/prebuilds/incremental-prebuilds-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/ee/src/workspace/workspace-factory.ts
Follow-up to https://github.com/gitpod-io/gitpod/pull/13801: Don't fetch the repository config a second time when starting incremental prebuilds
Fixes https://github.com/gitpod-io/gitpod/pull/13801#discussion_r998170168
> And this has the unfortunate consequence of calling `fetchConfig` twice now [[1](https://github.com/gitpod-io/gitpod/blob/9dffa5d337eb4ed1787084d1aa90f6cee2a7560d/components/server/ee/src/workspace/workspace-factory.ts#L118), [2](https://github.com/gitpod-io/gitpod/blob/9dffa5d337eb4ed1787084d1aa90f6cee2a7560d/components/server/ee/src/prebuilds/incremental-prebuilds-service.ts#L76)]. This could be resolved by allowing to pass an optional `config` to `findGoodBaseForIncrementalBuild`.
1. Incremental prebuilds should still work
```release-note
NONE
``` …
=> [server] Don't fetch the repository config a second time when starting incremental prebuilds

components/gitpod-db/src/tables.ts, components/gitpod-db/src/typeorm/migration/1666082193187-AddStripeCustomerTable.ts
Enable db-sync for d_b_stripe_customer
* Depends on https://github.com/gitpod-io/gitpod/pull/13936 being rolled out
```release-note
NONE
```
/hold blocked by https://github.com/gitpod-io/gitpod/pull/13936
=> [stripe] Add d_b_stripe_customer to db-sync

components/server/ee/src/workspace/gitpod-server-impl.ts
When feature flag is enabled, calls to create stripe customer are delegated to the BillingService.
Fixes #
Feature flag
Preview env
```release-note
NONE
```
=> [sever] Delegate stripe customer create to usage (behind feature flag)

.pre-commit-config.yaml
We have [GitGuardian check running](https://github.com/gitpod-io/gitpod/pull/13994/checks?check_run_id=8980721379), but this is on push and only notifies if sensitive data has already been committed.
This PR adds [`gitleaks`](https://github.com/zricethezav/gitleaks) pre-commit hook, which would prevent committing most sensitive data and leaking it through a commit. It's been in use for months in the [`observability`](https://github.com/gitpod-io/observability/blob/main/.pre-commit-config.yaml) repo
```bash
pre-commit run gitleaks --all-files
[INFO] Initializing environment for https://github.com/zricethezav/gitleaks.
[INFO] Installing environment for https://github.com/zricethezav/gitleaks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Detect …
```
=> Add gitleaks pre-commit hook

components/usage/pkg/db/dbtest/stripe_customer.go, components/usage/pkg/db/errors.go, components/usage/pkg/db/stripe_customer.go, components/usage/pkg/db/stripe_customer_test.go
Adds golang model for StripeCustomer and implements Creation and lookup by Stripe Customer ID and AttributionID
* Part of https://github.com/gitpod-io/gitpod/issues/13935
unit tests
```release-note
NONE
```
=> [usage] Add StripeCustomer db model

operations/observability/mixins/self-hosted/dashboards.libsonnet
After https://github.com/gitpod-io/gitpod/pull/13879, it was strange to me that we didn't see that dashboard in production. After some investigation I found this mistake 😅 
```release-note
NONE
```
=> Fix ArgoCD dashboard name

components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/latest/GitpodConnector.kt, components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/stable/GitpodConnector.kt
Update Gitpod Gateway Connector to match the latest API.
This fixes the "Learn More"/"More" button behavior, on the home screen of JetBrains Gateway, so clicking them will open https://www.gitpod.io/docs/ides-and-editors/jetbrains-gateway on browser.
|JetBrains Gatway Stable | JetBrains Gateway EAP |
| --- | --- |
| <img width="1077" alt="image" src="https://user-images.githubusercontent.com/418083/196495083-26156ee9-213a-4563-9645-0ad829edc897.png">| <img width="1077" alt="image" src="https://user-images.githubusercontent.com/418083/196494236-62c29efe-ec68-4955-bce2-8b628c083c90.png"> |
Follow-up for #13948
1. Download the Stable Build of the plugin from [here](https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions/Dev/239954), install it on Stable Gateway (2022.2) and check …
=> Fix the "Lean More" button behavior from JetBrains Gateway home screen

install/kots/manifests/gitpod-http-proxy-settings.yaml, install/kots/manifests/gitpod-kots-config.yaml, install/kots/manifests/kots-config.yaml
Add a checkbox to enable the HTTP proxy settings. The values are still taken from the KOTS CLI input variables, but will not be applied until the option is configured
Fixes #13682
Install via KOTS. Run the command `kubectl get deployments.apps -n gitpod blobserve -o yaml | grep -i HTTP_PROXY -a2` - unless you have the checkbox enabled, this should return nothing.
```release-note
[kots]: put the HTTP Proxy settings behind a KOTS config bool
```
=> [kots]: put the HTTP Proxy settings behind a KOTS config bool

install/tests/Makefile
In a previous PR, we have changed the way variables were fed to the terraform modules(via a `terraform.tfvars` file). This changed the variable corresponding to domain name from `TF_VAR_domain` to `DOMAIN`. There was still one reference to the old variable left, which went unnoticed since it is only used when running integration tests. This PR fixes it.
Fixes #
You can run a test setup like described in this [internal doc](https://www.notion.so/gitpod/Self-hosted-automated-preview-and-test-pipelines-fdc5a202e67b4197aa00d93b98d57927#7ef38c2da4714639a117d0ba61f2e8ca)
```release-note
NONE
```
=> [installer-tests] Fix the variable name corresponding domain

.github/workflows/public-api.yml, components/public-api/buf.yaml, components/public-api/generate.sh
This change introduces a new Github Action which uses [buf](https://docs.buf.build/introduction) to do the following:
* Enforce style of API definitions for the Public API (`buf lint`)
* Enforce changes are compatible - they will not break older clients (`buf breaking`)
All API definitions in `components/public-api` are subject to this rule, unless they are specified in the `components/public-api/experimental` package in which case the breaking detector does not apply.
You can see an example of how the error is reported in this [PR](https://github.com/gitpod-io/gitpod/pull/14009/files)
Fixes #
Run `cd components/public-api && ./generate.sh`. The `generate.sh` command checks against main, so either you need to point it at another base branch, like (`mp/buf-breaking-demo-1` from this [demo …
=> [actions] Detect breaking Public API changes

components/gitpod-protocol/src/workspace-cluster.ts, components/ws-manager-api/typescript/src/client-provider-source.ts
<details>
To do that we will introduce a new field in the table called `applicationCluster` which records the name of the application cluster to which the record belongs. Thus, for each workspace cluster there will be two rows in …
=> [ws-manager] Make cluster selection filter by application cluster

components/usage/pkg/apiv1/billing.go
Starts to use the StripeCustomers table to answer lookup queries, but also populates the DB when it's not yet available in the DB.
Fixes #
```release-note
NONE
```
=> [stripe] Populate Stripe Customers from searches, use as lookup

components/public-api/typescript/package.json
Unneeded, and it actively breaks the ability for a client to do `npm install @gitpod/public-api`
Fixes #
```release-note
NONE
```
=> [public-api] Remove dependency on @gitpod/gitpod-protocol

components/gitpod-protocol/src/billing-mode.ts, components/server/ee/src/billing/billing-mode.spec.db.ts, components/server/ee/src/billing/billing-mode.ts
Fixes #13999
- [login](https://gpl-13999-036cd0bbeb.preview.gitpod-dev.com/workspaces)       
- create team `somethingsomething`
- create team `Gitpod-something`
- note how in [your personal billing settings](https://gpl-13999-036cd0bbeb.preview.gitpod-dev.com/billing) you set usage-based relevant sections (e.g. workspace-class selector)
```release-note
NONE
```
=> UBP: Don't block early access because of an unpaid team membership

components/dashboard/src/components/UsageBasedBillingConfig.tsx
This will update the progress indicator height in the billing page. See [relevant discussion](https://gitpod.slack.com/archives/C027AUU7BC3/p1666271013855189) (internal).
|-|-|
| <img width="1440" alt="Screenshot 2022-10-20 at 7 05 19 PM" src="https://user-images.githubusercontent.com/120486/197000900-2ef14c98-bf91-498e-98df-6e350aae4782.png"> | <img width="1440" alt="Screenshot 2022-10-20 at 7 05 33 PM" src="https://user-images.githubusercontent.com/120486/197000906-793456df-2bde-45f9-bb2b-7397992eede0.png"> |
Go to usage for a personal account or a team.
```release-note
Update balance used progress indicator height
```
=> Update balance used progress indicator height

components/supervisor/pkg/supervisor/ssh.go
Fixes https://github.com/gitpod-io/gitpod/issues/13793
1. Connect to vscode desktop and  run `Open in Integrated Terminal` from context menu in explorer on some folder
2. Check terminal opens in the specified folder
3. Check connecting using ssh opens the workspace folder by defaul
```release-note
NONE
```
=> Fixes "Open in Integrated Terminal" won't work in VS Code

dev/ready-probe-labeler/main.go
Rely on the readiness probe instead of adding artificial wait.
- workspaces should open without issues
```release-note
NONE
```
=> Remove node labeler waits

components/public-api/typescript/package.json, components/public-api/typescript/src/gitpod/experimental/v1/index.ts
Adds missing entry point
```release-note
NONE
```
=> Add missing entrypoint

WORKSPACE.yaml, components/gitpod-cli/cmd/ports-list.go, components/gitpod-protocol/go/gitpod-service.go, components/supervisor/pkg/ports/ports-config.go, components/supervisor/pkg/ports/ports.go, components/supervisor/pkg/ports/ports_test.go
Related PR https://github.com/gitpod-io/openvscode-server/pull/444
- Fixes https://github.com/gitpod-io/gitpod/issues/7764
- Open workspace in preview env with ports opened. Example repo https://github.com/mustard-mh/test/tree/hw/logs-ports
- Check if ports are sorted in PortsView
- Check if ports are sorted in `gp-cli`
- Update `.gitpod.yml` ports order should change order in portsView too (if file change is detect, you can change name after order change to see if it is detect or not)
- First respect to `.gitpod.yml` 's ports define
- Others' are sorted by port number ASC
- Filter with ports that are not served and defined in `gitpod.yml`
```release-note
Display sorted ports with both `gp-cli` and VSCode Browser `PortsView`
```
Valid options …
=> Respond PortsStatus with sorted ports

components/server/src/workspace/config-provider.ts
Fixes #
Fixes [internal chat](https://gitpod.slack.com/archives/C01KGM9BH54/p1666285436242979)
- Open https://github.com/gitpod-io/empty workspace in preview env
- Check if port 3000 list in `gp ports list` or PortsView
```release-note
Fixes port 3000 becomes the default config of ports if there is no `.gitpod.yml` file
```
=> [server] remove port 3000 from default config

components/content-service/pkg/initializer/git.go, test/tests/workspace/git_hooks_test.go
It is not expected that hooks will be executed at checkout, i.e. prebuild, etc.
Fixes https://github.com/gitpod-io/ops/issues/5740
There are two way to check this PR
1. Open https://github.com/gitpod-io/gitpod-test-repo/tree/husky and check if not exist `output.txt`
- https://to-git-hooks.preview.gitpod-dev.com/#https://github.com/gitpod-io/gitpod-test-repo/tree/husky
2. Run the integration test
```release-note
Fix a bug that a workspace is not started when there was a checkout hook
```
No
=> content-service: Ignore git hooks when checkout 

install/kots/manifests/gitpod-log-collector.yaml
Add DB migration job to FluentBit ephemeral log collector
Install via KOTS, create a support bundle and search for `migrations-xxx.migrations` in the fluent bit logs
```release-note
[kots]: add db migration job to fluent bit logger
```
=> [kots]: add db migration job to fluent bit logger

components/dashboard/src/contexts/FeatureFlagContext.tsx, components/dashboard/src/start/CreateWorkspace.tsx, components/gitpod-db/src/accounting-db.spec.db.ts, components/gitpod-protocol/src/protocol.ts, components/server/ee/src/container-module.ts, components/server/ee/src/prebuilds/incremental-prebuilds-service.ts, components/server/ee/src/prebuilds/prebuild-manager.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/ee/src/workspace/workspace-factory.ts
In https://github.com/gitpod-io/gitpod/pull/13997, we randomly reverted a few changes in the hopes of resolving #13991.
However, it turns out that these changes were completely unrelated to the bug ([internal source](https://gitpod.slack.com/archives/C02EN94AEPL/p1666180322859469?thread_ts=1666176705.450389&cid=C02EN94AEPL)).
Thus, we can safely re-merge this PR that was already tested and approved.
Part of https://github.com/gitpod-io/gitpod/issues/12582
See [original PR](https://github.com/gitpod-io/gitpod/pull/13801)
```release-note
NONE
```
=> Re-add "Use Last Successful Prebuild"

dev/preview/previewctl/cmd/get_name.go, dev/preview/previewctl/cmd/root.go, dev/preview/previewctl/pkg/preview/preview.go, dev/preview/previewctl/pkg/preview/preview_test.go
Refactor a bit `previewctl get-name`
Fixes #
```release-note
NONE
```
=> Refactor previewctl get-name

WORKSPACE.yaml
- Upstream changes
- https://github.com/gitpod-io/openvscode-server/commit/b46c7b1d62b8a86ccd08948ec201d38c7734bb59
- https://github.com/gitpod-io/openvscode-server/commit/a1873c7c6dd518a46d25738d568716a16d364b27
- https://github.com/gitpod-io/openvscode-server/commit/5e03841f0f85c4d00bfeb771f9b5895626a82c15
- Related https://github.com/gitpod-io/gitpod/issues/13410
```release-note
NONE
```
=> [code] build stable code image `1.72.3`

.github/workflows/code-nightly.yml, WORKSPACE.yaml, components/ide/code/BUILD.yaml, components/ide/code/leeway.Dockerfile
Adds the `io.gitpod.ide.commit` and `io.gitpod.ide.version` labels to all images for VS Code built inside of this repository. This will allow us to add an interface on Server API through [`ide-service`](https://github.com/gitpod-io/gitpod/tree/main/components/ide-service).
1. Go to the Werft job results [[link](https://werft.gitpod-dev.com/job/gitpod-build-ft-add-ide-versions.0/results)]
2. Copy the third docker image link
3. Install [OCI tool](https://github.com/csweichel/oci-tool) within a workspace (could also do locally): `go install github.com/csweichel/oci-tool@latest`
4. Execute `oci-tool fetch image IMAGE_FROM_STEP_2 | jq .config.Labels` and check whether both attributes are present
```release-note
NONE
``` …
=> Tag VS Code images with `version`

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/workspace/ide/constants.go
This PR is follow up #14055 just change stable code image
Fixes #
1. Open a workspace with stable code
2. Check if commitHash is 4eb2aeb56544f66b029ff76d46e2fa5f863fbb6c and version is 1.72.3 in About
3. Install [OCI tool](https://github.com/csweichel/oci-tool) within a workspace (could also do locally): go install github.com/csweichel/oci-tool@latest
4. Execute `oci-tool fetch image eu.gcr.io/gitpod-core-dev/build/ide/code:commit-8297f570ac1ace9507d7637dfdfed947fb7bb8ad | jq .config.Labels` and check whether both attributes are present
```release-note
NONE
```
=> [code] update stable code image

.werft/ide-integration-tests-startup.yaml, .werft/installer-tests.ts, install/tests/Makefile, test/go.mod, test/go.sum, test/run.sh, test/tests/ide/ssh/main_test.go, test/tests/ide/ssh/ssh_gateway_test.go
This PR introduces SSH gateway integration tests.
Created during an IDE mob programming session 🎉
Fixes #
- Exec `werft run github -j .werft/ide-integration-tests-startup.yaml`
- See werft result of ssh test
(Already tested [here](https://werft.gitpod-dev.com/job/gitpod-build-afalz-ssh-gateway-integration-tests.13), but you can test it again 👍 )
```release-note
NONE
```
=> feat: add integration tests for ssh gateway

components/public-api/typescript/package.json, components/public-api/typescript/src/index.ts
Fix entrypoint
```release-note
NONE
```
=> Fix entrypoint

components/gitpod-cli/cmd/ports-list.go
This PR fix safe access to `port.Exposed.*` for both `Url` and `Visibility`.
Also, I've refactored the existing logic to determine the status, to be more readable and to follow the [vscode implementation](https://github.com/gitpod-io/openvscode-server/blob/gp-code/main/extensions/gitpod-shared/src/workspacePort.ts#L116-L140)
```
gp ports list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x97c5ae]
goroutine 1 [running]:
github.com/gitpod-io/gitpod/gitpod-cli/cmd.glob..func12(0xfb5fe0, {0xac9654, 0x0, 0x0})
github.com/gitpod-io/gitpod/gitpod-cli/cmd/ports-list.go:86 +0x3ae
github.com/spf13/cobra.(*Command).execute(0xfb5fe0, {0xff6aa8, 0x0, 0x0})
github.com/spf13/cobra@v1.1.3/command.go:856 +0x663 …
```
=> fix(gitpod-cli): ports list safe access to exposed url

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/workspace/ide/constants.go
- Nightly job done https://github.com/gitpod-io/gitpod/actions/runs/3300317143/jobs/5444678760
Fixes #
- Open workspace in preview env with stable code
- Check version is `1.72.3`
- Exec command by vscode command panel **Reset view locations**
- Check if default portsView location is correct (should exists next to **Terminals**)
```release-note
Fixes default location of PortsView incorrect
```
=> [code] update stable code to amend default location of portsView

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/cleanup-installer-tests.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environment.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile
Add the latest version of the [`fish` shell](https://fishshell.com/) to the Gitpod dev image.
`fish` is installed as part of the [base image](https://github.com/gitpod-io/workspace-images/blob/99de871d7ff8b7d914f34fff166398673202d63d/base/Dockerfile#L30), but that version is now 4 minor versions out of date and missing several features.
Fixes #
```release-note
NONE
```
=> [dev] Add latest version of `fish` shell to image

components/ws-manager/pkg/manager/probe.go
Simplify checks
xref #14108
```release-note
NONE
```
=> [ws-manager] Refactor workspace probes

components/ws-manager-bridge/src/app-cluster-instance-controller.ts, components/ws-manager-bridge/src/container-module.ts, components/ws-manager-bridge/src/main.ts
Introduces `AppClusterWorkspaceInstanceController` to garbage-collect workspace instance that failed to start on the application cluster side of the instance lifecycle:
Prerequisite: https://github.com/gitpod-io/gitpod/pull/13866
Contributes to: #6770 
- start workspace on a context that triggers an image build ([example](https://github.com/geropl/gitpod-test-repo/tree/gpl/docker-build-10mins))
- note how the workspace starts as expected
```release-note
reliably close Workspaces which fail to start for whatever reason
```
=> [bridge] Introduce AppClusterWorkspaceInstanceController

components/server/src/workspace/workspace-starter.ts
Fixes #14030
1. open a workspace on this PR
1. make sure `user_pvc` is enabled for your user in ConfigCat
1. after changing the rule, `kubectl rollout restart deployment/server`
1. [login](https://gpl-14030-pvc.preview.gitpod-dev.com/workspaces)
4. start a workspace
5. check the workspace pod, and verify that the label `gitpod.io/pvcFeature: "true"` is present :heavy_check_mark: 
6. stop the workspace
7. start and stop that workspace another time
8. manipulate the DB:
1. Find the instances of your wrokspacId: `select id, creationTime, status from d_b_workspace_instance WHERE workspaceId = ' ... ';`
2. Set the latest instance to `failed`; `UPDATE d_b_workspace_instance SET status = JSON_SET(status, "$.conditions.failed", 'test') WHERE id = ' ... ';`
9. Start your workspace again, and see …
=> [server] Restart PVC workspace from latest valid backup

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/cleanup-installer-tests.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environment.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-artificial-job.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile, dev/preview/previewctl/cmd/credentials.go
Fix an issue with passing a variable + trigger rebuild of the image so it's available in werft.
Fixes #
```release-note
NONE
```
=> Fix previewctl SA, rebuild and update docker image

install/installer/scripts/kots-install.sh, install/kots/manifests/gitpod-installation-status.yaml, install/kots/manifests/gitpod-installer-job.yaml
Print the installer version to the kots-install script
Install via KOTS
```release-note
[installer]: print the installer version to the kots-install script
```
=> [installer]: print the installer version to the kots-install script

.werft/jobs/build/const.ts, .werft/jobs/build/prepare.ts, .werft/util/certs.ts, .werft/vm/vm.ts, dev/preview/infrastructure/harvester/provider.tf, dev/preview/infrastructure/harvester/variables.tf
Use `previewct get-credentials` to populate a single kubeconfig and target contexts explicitly in tf.
Fixes #
https://werft.gitpod-dev.com/job/gitpod-custom-aa-use-previewctl-get-creds.6/results
```release-note
NONE
```
=> Use `previewct get-credentials` in werft job

components/dashboard/leeway.Dockerfile
This PR downgrades Caddy for dashboard, due to either an issue with Caddy itself, or with the config written for previous version. 
Here is what's happen: requests for static resources get a 308 response unexpectedly, see 
Fixes #14116
Auth popup window should be closed automatically on login/signup.
```release-note
NONE
```
=> [dashboard] revert Caddy bump

components/ws-manager/pkg/manager/create.go, components/ws-manager/pkg/manager/manager.go, components/ws-manager/pkg/manager/testdata/cdwp_admission.golden, components/ws-manager/pkg/manager/testdata/cdwp_class.golden, components/ws-manager/pkg/manager/testdata/cdwp_empty_resource_req.golden, components/ws-manager/pkg/manager/testdata/cdwp_envvars.golden, components/ws-manager/pkg/manager/testdata/cdwp_fullworkspacebackup.golden, components/ws-manager/pkg/manager/testdata/cdwp_imagebuild.golden, components/ws-manager/pkg/manager/testdata/cdwp_imagebuild_template.golden, components/ws-manager/pkg/manager/testdata/cdwp_no_ideimage.golden, components/ws-manager/pkg/manager/testdata/cdwp_prebuild.golden, components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template.golden, components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template_override_resources.golden, components/ws-manager/pkg/manager/testdata/cdwp_readinessprobe.golden, components/ws-manager/pkg/manager/testdata/cdwp_sshkeys.golden, components/ws-manager/pkg/manager/testdata/cdwp_sys_envvars.golden, components/ws-manager/pkg/manager/testdata/cdwp_tasks.golden, components/ws-manager/pkg/manager/testdata/cdwp_template.golden, components/ws-manager/pkg/manager/testdata/cdwp_timeout.golden, components/ws-manager/pkg/manager/testdata/cdwp_userns.golden, components/ws-manager/pkg/manager/testdata/cdwp_with_ephemeral_storage.golden, components/ws-manager/pkg/manager/testdata/cdwp_withaffinity_regular.golden, components/ws-manager/pkg/manager/testdata/cdwp_withaffinityheadless.golden
Enable protected secrets by default. This is the part for the workspace side. Once this change is deployed we can also change it on web app side.
Related to https://github.com/gitpod-io/gitpod/issues/13634
- Open workspace in preview environment and check that protected secrets are still used
```release-note
None
```
=> Enable protected secrets by default

dev/preview/BUILD.yaml
TODO. Preview environments created in Werft works as expected, but from a workspace I get the following error:
```
leeway run dev/preview:create-preview
... a lot of output ...
/workspace/gitpod/dev/preview/infrastructure/harvester /workspace/gitpod/dev/preview
harvester_ssh_key.harvester_ssh_key: Creating...
╷
│ Error: Post "https://mads-add-l356b6c92d4.kube.gitpod-dev.com:6443/apis/harvesterhci.io/v1beta1/namespaces/preview-mads-add-l356b6c92d4/keypairs": EOF
│ 
│   with harvester_ssh_key.harvester_ssh_key,
│   on vm.tf line 59, in resource "harvester_ssh_key" "harvester_ssh_key":
│   59: resource "harvester_ssh_key" "harvester_ssh_key" {
```
Part of https://github.com/gitpod-io/ops/issues/5766
Part of https://github.com/gitpod-io/ops/issues/5892
```sh
leeway run …
```
=> Add dev/preview:create-preview

components/dashboard/src/components/UsageBasedBillingConfig.tsx, components/dashboard/src/index.tsx
Fixes #
```release-note
NONE
```
=> [dashboard] Fix display of billing period boundaries by using only UTC times - using dayjs

components/dashboard/src/components/UsageBasedBillingConfig.tsx, components/dashboard/src/index.tsx
Fix display of billing period boundaries in the dashboard by using only UTC times.
(Note: I did try to use `dayjs` for this, but couldn't figure out how to "force" everything to be UTC, so I fell back on the native Date type. Happy to switch to `dayjs` if you know how to achieve exactly the same result. 👍)
Fixes #
1. Upgrade to usage-based billing
2. Billing period boundaries shown in your billing UI should be correct
```release-note
NONE
```
=> [dashboard] Fix display of billing period boundaries by using only UTC times

components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts, components/gitpod-db/src/typeorm/migration/1666616345054-AddLastModifiedToWorkspaceClusterTable.ts
Add a `_lastModified` column to `d_b_workspace_cluster` table so that it can be synced with `db-sync` in a later PR.
Part of #9198 and https://github.com/gitpod-io/gitpod/issues/13800
```release-note
NONE
```
=> [db] Add `_lastModified` column to `d_b_workspace_cluster` table

components/dashboard/src/Menu.tsx
When you have Projects under your 'Personal Account' (now being deprecated), but you have no Teams yet, we currently show only a "New Team →" button, with no way to access the projects under your 'Personal Account'. 🐞 
This PR makes Gitpod show your 'Personal Account' menu entry again when you're in that specific case (but not if you don't have any Projects there).
Fixes https://github.com/gitpod-io/gitpod/issues/14002
1. Log in to the preview environment
2. Visit `/new` to create a Project under your 'Personal Account' manually
3. Your 'Personal Account' should be accessible from the top menu's "account selector" (without you having to create a team first)
```release-note
NONE
```
=> [dashboard] Keep showing 'Personal Account' menu entry if you have personal projects but no team yet

components/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go
- Add a handler when the workspace has gone
- Fix the problem with nice value not being applied
Relates: https://github.com/gitpod-io/gitpod/issues/14103
Fix: https://github.com/gitpod-io/gitpod/issues/11986
1. Open a workspace
2. Check if all target process are changed a nice value
```release-note
A bit faster IDE startup
```
=> ws-daemon: Fix the problem with nice value not being applied

components/content-service/pkg/git/git.go, components/content-service/pkg/initializer/git.go, components/content-service/pkg/initializer/initializer.go
When using PVC, we run content-init from inside the supervisor, which runs as root user.
This causes git clone to run as root, causing cloned repo to be owned by root. 
Workaround was to do chown as the end of clone, but on big repos it is slow.
This allows to run git op as gitpod user instead, thus not needing to do chown at the end.
Fixes #12892
Open and close all kind of various ways of opening a workspace.
This code should only affect PVC code path, so to properly test you need to enable PVC feature flag on your account first.
```release-note
none
```
=> [pvc] run git commands as gitpod user when using pvc

components/public-api-server/pkg/server/metrics.go
The label `service` is used by k8s prometheus exporter. This results in our `service` label being re-exported as `exported_service` which is not ideal. Renaming to `package` avoids this collision.
[See here](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22code%22,%22expr%22:%22connect_server_handled_seconds_count%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D)
Fixes #
```release-note
NONE
```
=> [public-api] Export metrics with package label instead of service

.gitpod.yml, .werft/aks-installer-tests.yaml, .werft/build.yaml, .werft/cleanup-installer-tests.yaml, .werft/debug.yaml, .werft/eks-installer-tests.yaml, .werft/gke-installer-tests.yaml, .werft/ide-integration-tests-startup.yaml, .werft/k3s-installer-tests.yaml, .werft/platform-delete-preview-environment.yaml, .werft/platform-delete-preview-environments-cron.yaml, .werft/platform-trigger-artificial-job.yaml, .werft/platform-trigger-werft-cleanup.yaml, .werft/workspace-run-integration-tests.yaml, dev/image/Dockerfile, dev/preview/previewctl/pkg/preview/preview.go, dev/preview/previewctl/pkg/preview/preview_test.go
Fix previewctl get-name
Fixes https://gitpod.slack.com/archives/C032A46PWR0/p1666639857490139
```release-note
NONE
```
=> Fix previewctl get-name and update image

components/ide/jetbrains/backend-plugin/gradle-latest.properties, components/ide/jetbrains/backend-plugin/gradle-stable.properties, components/ide/jetbrains/backend-plugin/launch-dev-server.sh, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIHelper.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodClientProjectSessionTracker.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodGlobalPortForwardingService.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodTerminalService.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodCLIHelperImpl.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodGlobalPortForwardingServiceImpl.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortForwardingService.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortsActionCopyUrl.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodCLIHelperImpl.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodClientProjectGuestSessionTracker.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodGlobalPortForwardingServiceImpl.kt, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodTerminalGuestService.kt, components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml, components/ide/jetbrains/backend-plugin/src/main/resources-stable/META-INF/extensions.xml, components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
This PR updates the Platform Version from JetBrains Backend Plugin to the latest version.
Checklist for EAP IDEs in v223.7x:
6. Repeat the same steps above, but now using the _Stable_ version of IntelliJ IDEA
```release-note
NONE
```
_This PR was created automatically with GitHub Actions using [this](https://github.com/gitpod-io/gitpod/blob/main/.github/workflows/jetbrains-update-plugin-platform-template.yml) template._
=> Update Platform Version from JetBrains Backend Plugin

dev/preview/infrastructure/harvester/provider.tf
Harvester released a new version of the provider, which is not compatible with the version of harvester we run: https://github.com/harvester/terraform-provider-harvester/releases/tag/v0.6.0
Fixes https://gitpod.slack.com/archives/C032A46PWR0/p1666691304322049
```release-note
NONE
```
=> Pin harvester tf provider version

components/server/ee/src/user/stripe-service.ts, components/server/ee/src/workspace/gitpod-server-impl.ts
We're removing the feature flag (by defaulting to the featureFlag true behaviour) and corresponding old implementation.
Metrics show this has worked well in production.
Fixes #
```release-note
NONE
```
=> [server] Remove createStripeCustomer, handled by usage instead

dev/preview/workflow/preview/build.sh
It turns out that the "cache miss" we were seeing from Gitpod Workspaces is due to some of our packages being sensitive to a "dirty filesystem". As a temporary solution I'm using `git clean` (see comment in code) but we should go through each component and see if we can make sure it isn't impacted by the occurrence of files that we have in .gitignore (such as build folders) - I have created an issue (https://github.com/gitpod-io/gitpod/issues/14157) and proposed it for next week.
This PR also adds a few more build arguments to align with the Leeway invocation performed by Werft to make it easier to merge the two as part of https://github.com/gitpod-io/ops/issues/5894
Fixes https://github.com/gitpod-io/gitpod/issues/13767
```sh
gcloud auth login --no-launch-browser
leeway run …
```
=> dev/preview:build: Clean git repository before performing build

.github/workflows/jetbrains-update-backend-latest.yml
Creates a new GHA workflow to update the backend-plugin image's latest tag.
Fixes #
We will manually test by dispatching the workflow once merged, nobody is using this tag at the moment
```release-note
NONE
```
=> feat: add gha job to update backend-plugin latest image

components/dashboard/src/projects/Project.tsx, components/server/ee/src/workspace/workspace-factory.ts
Made this PR in an effort to address some issues I ran into with prebuilds.
I don't know how to test the changes I made in `workspace-factory.ts`. The original pull request that had changes to that block of code (#13768) didn't have any unit tests, so I wasn't sure where to add some.
Fixes #14017
- Create new prebuild
- Open workspace from either the branches tab or the specific prebuild page
- Prebuild should load correctly and the branch should be checked out in git
```release-note
```
=> Fix prebuild open

components/dashboard/src/components/UsageView.tsx, components/dashboard/src/settings/settings-menu.ts, components/dashboard/src/settings/settings.routes.ts
1. Users who are flagged for UBP can now see the `Personal usage` tab under `Billing`.
2. Headers for the Usage pages are now either `Team usage` or `Personal usage`
| User settings | Team usage | Personal usage | 
| - | - | - |
| <img width="162" alt="Screenshot 2022-10-25 at 16 58 47" src="https://user-images.githubusercontent.com/8015191/197809183-a70e4292-4de4-4899-8697-d8d959962b4d.png"> | <img width="147" alt="Screenshot 2022-10-25 at 16 59 05" src="https://user-images.githubusercontent.com/8015191/197809244-cb80011e-881c-4f35-b71c-78107c038a9d.png"> | <img width="188" alt="Screenshot 2022-10-25 at 16 59 35" src="https://user-images.githubusercontent.com/8015191/197809370-bec66e0c-eeec-409a-9df2-0bb0ee5bb4f7.png"> |
Fixes #13968
1. Create a user
2. Add the userId to the Non-prod …
=> [usage] Personal usage tab

.werft/jobs/build/installer/installer.ts, components/usage/pkg/server/server.go, install/installer/pkg/components/usage/configmap.go, install/installer/pkg/components/usage/configmap_test.go, install/installer/pkg/components/usage/objects.go, install/installer/pkg/config/v1/experimental/experimental.go
Loads Stripe Price ID configuration from installer config. These fields are already defined in https://github.com/gitpod-io/ops/commit/a5855e723fe7b703d81b5f09a4869fef186b5581
The prices IDs are only loaded into the deployment, but do not get used. This allows us to validate it before we make code changes to start using them.
Fixes #14115 
1. Preview configmap for usage contains the price IDs
```release-note
NONE
```
=> [usage] Configure Stripe Price IDs through installer

operations/observability/mixins/workspace/dashboards/registry-facade-blobsource.json
=> [registry-facade] Add new blobSource dashboard

components/dashboard/src/projects/Prebuilds.tsx
When our system decides to cancel a prebuild automatically, it also mentions the specific cancellation reason in `prebuild.error`:
https://github.com/gitpod-io/gitpod/blob/c87781b6d2932f7f779358ef71b9923c44dfc741/components/server/ee/src/prebuilds/prebuild-manager.ts#L224-L225
https://github.com/gitpod-io/gitpod/blob/c87781b6d2932f7f779358ef71b9923c44dfc741/components/server/ee/src/prebuilds/prebuild-manager.ts#L230-L231
https://github.com/gitpod-io/gitpod/blob/c87781b6d2932f7f779358ef71b9923c44dfc741/components/server/ee/src/prebuilds/prebuild-manager.ts#L235-L236
Also, we used to display this exact message below the Prebuild Logs, so that users could be aware why exactly their prebuild got cancelled:
https://github.com/gitpod-io/gitpod/blob/31332971069a926428151aae2eacac947ed2db21/compon …
=> [dashboard] Display specific Prebuild cancellation reason in Prebuild Status again

.werft/platform-delete-preview-environment.ts
https://github.com/gitpod-io/gitpod/pull/14091 changed the configurations of the tf providers, but forgot the change the delete job to populate the correct kube contexts.
Fixes https://werft.gitpod-dev.com/job/gitpod-custom-head.3147
```tf
╷
│ Error: context "harvester" does not exist
│
│   with provider["registry.terraform.io/harvester/harvester"].harvester,
│   on provider.tf line 25, in provider "harvester":
│   25: provider "harvester" {
│
╵
╷
│ Error: Provider configuration: cannot load Kubernetes client config
│
│   with provider["registry.terraform.io/hashicorp/kubernetes"].harvester,
│   on provider.tf line 37, in provider "k8s":
│   37: provider "k8s" {
│
│ context "harvester" does not exist
╵
```
```release-note
NONE
```
Valid options …
=> Fix preview delete job

components/server/ee/src/billing/billing-mode.ts, components/server/ee/src/billing/entitlement-service-ubp.ts, components/server/ee/src/container-module.ts, components/server/src/container-module.ts, components/server/src/user/usage-service.ts, components/server/src/user/user-service.ts
Mitigate the fact that `usage` is not deployed with self-hosted, yet, by mocking it away until we properly fixed it with #14129.
Context: #14129
- [sign up](https://gpl-14129-sh-usage-2.preview.gitpod-dev.com/workspaces)
- start a workspace: works :heavy_check_mark: 
- join this team: https://gpl-14129-sh-usage-2.preview.gitpod-dev.com/teams/join?inviteId=04798381-69fc-498c-8f50-d39b6015abf1
- start [this workspace](https://gpl-14129-sh-usage-2.preview.gitpod-dev.com/#https://github.com/geropl/gitpod-test-repo): works  :heavy_check_mark: 
```release-note
NONE
```
=> Unblock Self-Hosted release by introducing UsageServiceMock (II)

operations/observability/mixins/self-hosted/dashboards.libsonnet, operations/observability/mixins/self-hosted/dashboards/observability/observability.json
This PR adds a minimal dashboard for monitoring our observability stack itself.
Can be seen [here](https://grafana.gitpod.io/d/1hcljDH4k/observability?orgId=1&var-cluster=All)
Fixes #
```release-note
NONE
```
=> Add minimal dashboard for the observability stack

.werft/jobs/build/prepare.ts, dev/preview/BUILD.yaml
Use `leeway run dev/preview:create-preview` in our Werft job.
Fixes https://github.com/gitpod-io/ops/issues/5893
That it works in Werft ([job](https://werft.gitpod-dev.com/job/gitpod-build-mads-use-create-preview-in-werft.10), [preview environment](https://mads-use-cc85c4e71e3.preview.gitpod-dev.com/workspaces))
```
werft job run github
```
That it works in workspaces
```sh
leeway run dev/preview:create-preview
leeway run dev/preview:delete-preview
```
```release-note
NONE
```
=> Use dev/preview:create-preview in Werft

components/ide/jetbrains/backend-plugin/launch-dev-server.sh, components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt
Fix `gp open` command to open files in JetBrains Client instead of the backend IDE.
These changes also affects `gp preview` command, so it needs to be tested.
2. Choose the  _Stable_  version of IntelliJ IDEA as your preferred editor
6. Run `gp open .gitignore` and confirm it opens the .gitignore file in the editor
7. Run `gp open --wait .gitpod.yml` and confirm it opens Gitpod Configuration file and will only exit the command line when you click "Release" on the top bar displayed in the editor
8. Run `gp preview https://gitpod.io` and confirm Gitpod …
=> Fix 'gp open' command to open files in JetBrains Client instead of the backend IDE

operations/observability/mixins/self-hosted/dashboards/observability/observability.json
Added a simple Alertmanager panel (just for central AM, while we move to centralised) and added some QOL links for going to the in-depth dashboards (keeps timestamps and arguments)
```release-note
NONE
```
=> Add AM and some QOL to the observability dashboard

components/server/src/prometheus-metrics.ts, components/server/src/workspace/workspace-starter.ts
Add a metric `gitpod_server_image_builds_started_total` to count the number of image builds started by `server`.
Part of #12960 
* Port-forward to the server metrics port: `kubectl port-forward deploy/server 9500:9500`
* Hit the `server` metrics endpoint at `:9500/metrics` and look for the `gitpod_server_image_builds_started_total` metric.
* Start an image build
* See the counter increase.
```release-note
NONE
```
=> [server] Add counter metric for image build starts

components/gitpod-protocol/go/gitpod-service.go, components/gitpod-protocol/go/mock.go
Makes the Golang interface to Server an `io.Closer`. This is needed to be able to use the Interface type, but allow for closing the API connection in a Go idiomatic way.
This is used in https://github.com/gitpod-io/gitpod/pull/13750
Fixes #
```release-note
NONE
```
=> [gitpod-protocol] Make APIInterface an io.Closer

components/image-builder-mk3/pkg/orchestrator/orchestrator.go
Increment the `gitpod_image_builder_builds_started_total` counter when the image builder starts a build.
This metric was already configured and registered but never used.
Part of https://github.com/gitpod-io/gitpod/issues/12960
* Port forward to the image builder in the preview environment.
* Hit the metrics endpoint
* Trigger an image build
* See the counter increase.
```release-note
NONE
```
=> [image-builder] Increment metric on build start

operations/observability/mixins/meta/rules/login-slo.yaml, operations/observability/mixins/meta/rules/messagebus.yaml, operations/observability/mixins/meta/rules/meta-nodes.yaml, operations/observability/mixins/meta/rules/server.yaml, operations/observability/mixins/meta/rules/usage.yaml
To ensure we continue to receive the alerts with Cluster information, we've gotta group by cluster.
Right now, the cluster label does not exist on the leaf Prometheus instances (in monitoring-satellite) but it doesn't affect the metrics - it's aggregated away
Fixes https://github.com/gitpod-io/ops/issues/5598
```release-note
NONE
```
=> [alerts] Group by cluster, where relevant, ahead of centralizing rule evaluation

components/usage/pkg/scheduler/reset_usage_job.go, components/usage/pkg/server/server.go, install/installer/pkg/components/usage/configmap.go, install/installer/pkg/components/usage/configmap_test.go
Initial setup for usage reset job. Currently does nothing but logs when it's triggered. 
Config in the installer will be added in subsequent PR.
* Part of https://github.com/gitpod-io/gitpod/issues/14178
```release-note
NONE
```
=> [usage] Setup usage reset job

WORKSPACE.yaml
Update code to `1.72.3` (but to the tip of the release branch once again)
Although I'm a bit skeptical about the need for these tests (only 15 lines have changed), here they are:
```release-note
NONE
```
=> Generate image to to reflect latest upstream changes

.github/workflows/jetbrains-update-backend-latest.yml
Update the GHA workflow fixing the gcloud auth for the job
Fixes #
We tested by triggering the workflow manually
```release-note
NONE
```
=> fix: gcloud auth for jetbrains backend-plugin gha workflow

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/shortname/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/ide-service/ide_config_configmap.go
With this PR:
- prev env will continue to allow testing branch-specific changes of the `backend-plugin`
- prev env will use latest images of the JetBrains IDEs
- SH installations will also use latest images of the JetBrains IDEs
<details>
<summary>Already tested ✅</summary>
```json
{
"supervisorImage": "eu.gcr.io/gitpod-core-dev/build/supervisor:commit-96916c5a955b991a94b23aabe5cdbd9fd7881dba",
"ideOptions": {
"options": {
"code": {
"orderKey": "00",
"title": "VS Code",
"type": "browser",
"logo": "https://ide.example.com/image/ide-logo/vscode.svg",
"label": "Browser",
"image": "eu.gcr.io/gitpod-core-dev/build/ide/code:commit-96916c5a955b991a94b23aabe5cdbd9fd7881dba",
"latestImage": "eu.gcr.io/gitpod-core-dev/build/ide/code:nightly"
},
"code-desktop": {
"orderKey": "02",
"title": "VS …
```
=> [Preview Environment] Use latest jetbrains images

components/dashboard/src/components/BillingAccountSelector.tsx, components/dashboard/src/components/UsageBasedBillingConfig.tsx
In some rare edge cases, it can happen that Gitpod fails to get your Stripe subscription details (for example, one of these cases can be that a Stripe customer has two active Subscriptions for some reason, but there could exist other rare edge cases).
In these cases, Gitpod's backend throws an error. However, until now, the front-end only logged this error to the console, without showing it visibly in the UI. This PR fixes the latter, by visibly showing any such error message in the UI, so that users are at least aware that something went wrong.
Fixes https://github.com/gitpod-io/gitpod/issues/14034
1. Upgrade your team to usage-based
2. In the Stripe test dashboard, manually create a duplicate Subscription for your team's Customer (pick any subscription details)
3. Visit your team's …
=> [dashboard] Better surface errors when Gitpod fails to get your Stripe subscription details

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/shortname/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/ide-service/ide_config_configmap.go
Adding https://github.com/gitpod-io/gitpod/pull/14130 to this release
```release-note
NONE
```
=> chore(prev-env): use latest jetbrains images

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/shortname/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/workspace/ide/constants.go
Updates the stable image of VS Code Browser to `1.72.3` (5aeda8f2f6c0f8fb0c4f3929a281c999be7c6dcf)
A part of https://github.com/gitpod-io/gitpod/issues/13410
Open the preview environment, select VS Code Browser (non-`latest`) and in the <kbd>About</kbd> dialog check that we are on `1.72.3` with the commit `15e7467806334e6bdd73dfbdefebaec2c3c2efeb`.
```release-note
NONE
```
=> Update stable `1.72.3` to match latest upstream 

operations/observability/mixins/self-hosted/dashboards/argocd/argocd.json
Add a a filter for ArgoCD dashboard, so team's can filter and see only the apps that they own.
Fixes #
```release-note
NONE
```
=> Add 'team' as a filter to ArgoCD dashboard

components/server/ee/src/prebuilds/prebuild-manager.ts, components/server/src/config.ts, install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/shortname/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/server/configmap.go, install/installer/pkg/components/server/types.go, install/installer/pkg/config/v1/experimental/experimental.go
Actually add `inactivityPeriodForRepos` to the `server-config` ConfigMap in the installer.
Follow-up to https://github.com/gitpod-io/gitpod/pull/9976 so that we can actually enable this in production.
Fixes https://github.com/gitpod-io/gitpod/pull/9976
1. Should build and pass tests
```release-note
NONE
```
=> [installer] Actually add 'inactivityPeriodForReposInDays' to server configmap

components/server/src/prometheus-metrics.ts, components/server/src/workspace/workspace-starter.ts
Revert #14185.
The metric was added incorrectly and is actually incrementing on all workspace starts, not just image builds.
The metric is re-added correctly in #14204 
Part of #12960 
```release-note
NONE
```
=> [server] Revert #14185

components/dashboard/src/Menu.tsx, components/dashboard/src/projects/Projects.tsx
Following up from https://github.com/gitpod-io/gitpod/pull/13920, to update the correct line of code.
See instructions in https://github.com/gitpod-io/gitpod/pull/13920.
```release-note
NONE
```
=> Update team creation link in projects

components/image-builder-mk3/pkg/orchestrator/orchestrator.go, components/ws-manager/pkg/manager/manager.go
Without an explicit conversion, the log will contain the Base64 representation
- Check ws-manager logs and search for the `status` field. The value should be readable
```release-note
NONE
```
=> Log JSON as strings not an array of bytes

components/ws-manager/pkg/manager/probe.go
Disable keep-alive in http client connections
- Run loadgen
- Run pprof against ws-manager
- Check there are no `net/http.(*persistConn).writeLoop` references in the goroutines
```release-note
NONE
```
=> [ws-manager] Configure http client timeouts

components/gitpod-protocol/go/gitpod-service.go, components/gitpod-protocol/go/mock.go
Adds Team RPCs to Go gitpod protocol library
Fixes #
```release-note
NONE
```
=> [gitpod-protocol] Add createTeam, joinTeam, getTeamMembers to Go lib

operations/observability/mixins/self-hosted/rules/cardinality-analysis/promrules.yaml
Creates recording rules so Prometheus intances pre-compute queries that can be used for cardinality analysis
Fixes #
```release-note
NONE
```
=> Add intial prometheus rules for cardinality analysis

operations/observability/mixins/meta/rules/server.yaml
While working on https://github.com/gitpod-io/ops/pull/6338 I've noticed that Prometheus-operator was having a hard time reconciling PrometheusRules. I've checked the logs and found this:
This PR fixes the problematic alert. `avg_over_time` is not an aggregation function, so there's no need to use `by(cluster)`
Fixes #
```release-note
NONE
```
=> Fix ServerEventLoopLagTooHigh alert

components/ws-daemon/pkg/iws/iws.go
Don't record the error log from getResourceInfo when the workspace has gone to avoid noisy
Fixes https://github.com/gitpod-io/gitpod/issues/12330
Open and close the workspace and check if there isn't noisy error log from the workspace pod.
```release-note
Reduction of noise error logs
```
=> IWS: Don't record the error log from getResourceInfo when the workspace has gone.

components/dashboard/src/App.tsx, components/dashboard/src/Menu.tsx
This is a small clean-up and should remove unnecessary calls to server.
Dashboard should load as usual. 
```release-note
NONE
```
=> [dashboard] avoid unbound getUserProjects calls

components/dashboard/src/Menu.tsx
Following up from https://github.com/gitpod-io/gitpod/pull/14161, this will make sure the team scope selector becomes deactivated when visiting personal usage. See [relevant discussion](https://gitpod.slack.com/archives/C027AUU7BC3/p1666880393674419?thread_ts=1666879099.675049&cid=C027AUU7BC3) (internal).
Fixes https://github.com/gitpod-io/gitpod/issues/13968
```release-note
Deactivate team scope selector on personal usage
```
=> Deactivate team scope selector on personal usage

components/usage/pkg/apiv1/usage.go, components/usage/pkg/db/cost_center.go, components/usage/pkg/db/cost_center_test.go
* Implements ResetUsage to initially only report how many Cost centers it finds with expired NextBillingTime
* Implements underlying SQL search
* Tested SQL query against prod. On the full CostCenter dataset this takes ~4 secs.
* We can add an index on NextBillingTime to speed this up
* This RPC doesn't yet get invoked by the ResetUsage Job, to test, we'll invoke it manually through grpcurl.
* https://github.com/gitpod-io/gitpod/issues/14178
```release-note
NONE
```
=> [usage] List cost centers with expired billing time

operations/observability/mixins/IDE/dashboards.libsonnet, operations/observability/mixins/IDE/dashboards/components/openvsx-mirror.json
Fixes #
See https://grafana.gitpod.io/d/WI_x6hN4k/openvsx-mirror-server?orgId=1
```release-note
NONE
```
=> [observability] add dashboard for openvsx mirror

components/content-service/pkg/initializer/prebuild.go, test/tests/components/ws-manager/prebuild_test.go
If we initialize the workspace from an outdated prebuild, we
want the regular workspace tasks (including init) to run.
Related to https://github.com/gitpod-io/gitpod/issues/12582
Start a workspace on an an outdated prebuild and see that the init task runs.
```release-note
NONE
```
=> [content-service] incremental workspace init

operations/observability/mixins/self-hosted/rules/argocd/prometheusRules.yaml
To make navigation and debugging easier :)
Fixes #
```release-note
NONE
```
=> Add dashboard URL button to argocd alerts

operations/observability/mixins/self-hosted/rules/observability-stack/alertmanager.yaml, operations/observability/mixins/self-hosted/rules/observability-stack/kube-state-metrics.yaml, operations/observability/mixins/self-hosted/rules/observability-stack/prometheus-operator.yaml, operations/observability/mixins/self-hosted/rules/observability-stack/prometheus.yaml
This PR does 2 things:
* Move alerts for the observability stack to a folder owned by @gitpod-io/engineering-delivery-operations-experience
* Add one alert that notifies #team-delivery-operations-experience-alerts in slack when Prometheus restarts
@liam-j-bennett, I'm curious about what do you think about this new alert since I'm also unsure about it 😬.
This won't give us any false-positive, but will only trigger after a problem occurs. It's a reactive approach. Do we want something that is more proactive? I'm not sure about how we'd avoid false positives here
Fixes #
```release-note
NONE
```
=> Adjust ownership of alerts related to the observability-stack and add alert for Prometheus restarting

.werft/observability/manifests/monitoring-satellite.yaml, operations/observability/mixins/self-hosted/rules/cardinality-analysis/promrules.yaml
After https://github.com/gitpod-io/gitpod/pull/14235, we got alerted about [failures in rule evaluation](https://gitpod.slack.com/archives/C03MWBB5MP1/p1666879535467859). After some [investigation](https://groups.google.com/g/prometheus-users/c/ydz4E6HmI38), I've came up with a fix
* Connect to the cluster from the preview environment of this PR
* Open Prometheus UI via `kubectl port-forward -n monitoring-satellite prometheus-k8s-0 9090`
* Query the metric `metric:timeseries_total`, you should see results
```release-note
NONE
```
=> Fix timeseries_total recording rule

components/supervisor/cmd/init.go
[supervisor] remove unnecessary close channel
Fixes #14014
1. start workspace with this branch in gitpod.io, connect to preview environment via kubectl
2. start a workspace in preview environment, it should work
3. use `kubectl get pods -l component=workspace` to get workspace pod name
4. use `kubectl logs ws-xxxxxx -f` to see workspace log
5. stop your workspace, and observe log, there should not have `panic: close of closed channel` error output
```release-note
NONE
```
=> [supervisor] remove unnecessary close channel

components/dashboard/src/projects/Project.tsx, components/gitpod-protocol/src/teams-projects-protocol.ts, components/server/ee/src/prebuilds/prebuild-manager.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/src/projects/projects-service.ts, components/server/src/workspace/gitpod-server-impl.ts
With this PR we introduce a warning message on the Project overview when it is considered inactive. A `Resume prebuilds` action allows to trigger a new prebuild on the default branch.  
Fixes #9232
1. Create a project and start a workspace for it. 
2. Use this statement to set the project inactive
`update d_b_project_usage set lastWorkspaceStart = '2021-10-21T13:02:40.674Z';`
3. Check the project page for the warning.
4. Select the resume action.
```release-note
Show warning for inactive projects and allow to resume prebuilds again. 
```
=> Add message: Prebuilds have been paused

.github/CODEOWNERS, operations/observability/mixins/platform/rules/kubernetes/kubernetes.yaml
https://github.com/gitpod-io/ops/pull/6259 enables autoscaling on the only nodepool that doesn't have it still, which renders these alerts obsolete.
Fixes #
```release-note
NONE
```
=> Remove Kube*Overcommit alerts

operations/observability/mixins/self-hosted/dashboards.libsonnet, operations/observability/mixins/self-hosted/dashboards/observability/cardinality-management-overview.json
To better understand what is the state of high-cardinality of metrics that we produce, we're creating dashboards inspired by [Grafana's blogpost](https://grafana.com/docs/grafana-cloud/billing-and-usage/control-prometheus-metrics-usage/cardinality-management/).
This PR is far from completing all that is covered in the mentioned blogpost, but already provides some value.
The dashboard can be seen [here](https://grafana.gitpod.io/d/IZrNF0H4k/cardinality-management-overview?orgId=1&var-datasource=VictoriaMetrics&var-cluster=All) 🙂 
Fixes #
```release-note
NONE
```
=> Create initial dashboard for cardinality management

operations/observability/mixins/self-hosted/dashboards/observability/observability.json
https://github.com/gitpod-io/gitpod/pull/14168 introduced a dashboard focused on the health of our observability stack and it was created manually in Grafana. When backporting the JSON we missed to create a datasource variable, and now we're getting errors opening [the dashboard](https://grafana.gitpod.io/d/1hcljDH4k/observability?orgId=1)
This PR just created the variable, so the dashboard loads successfully.
Fixes #
```release-note
NONE
```
=> Fix missing datasource variable

components/docker-up/docker-up/main.go, components/docker-up/runc-facade/main.go, components/image-builder-bob/cmd/runc-facade/main.go
Fixes https://github.com/gitpod-io/gitpod/issues/12365
Open a workspace and run docker-compose following README
https://utam0k-run30561c5246.preview.gitpod-dev.com/#https://github.com/spearki/gitpod-runc-issue-repro
```console
$ ./generate.sh 20 > docker-compose.yml
$ docker compose up -d --force-recreate
```
```release-note
More stable docker-compose behavior with lots of containers
```
=> runc-facade: squashes rare runc errors

.github/workflows/code-nightly.yml
Makes sure our Insiders versions are pulled from the release branches every night.
A part of #14272 
```release-note
NONE
```
=> Update nightly job to point to `1.73`

.werft/jobs/build/job-config.ts, .werft/jobs/build/prepare.ts, dev/preview/BUILD.yaml, dev/preview/infrastructure/harvester/cert.tf, dev/preview/infrastructure/harvester/variables.tf
Add annotations:
- `cert-issuer` - ability to choose the issuer for the cert of the preview env. `[zerossl, letsencrypt]`
- `recreate-preview` - nuke the whole preview infra and recreate from scratch (including deps). Should be used sparingly, does not replace `with-clean-slate-deployment`
- `recreate-vm` == `with-clean-slate-deployment`, but shorter
Fix a small issue with passing `with-clean-slate-deployment` - where the VM would get recreated twice, since the flag is set for both applies.
Fixes https://gitpod.slack.com/archives/C032A46PWR0/p1667198847703189
```release-note
NONE
```
=> [preview] Add config option for cert-issuer

.werft/util/certs.ts
Forgot to set one var.
Fixes https://github.com/gitpod-io/gitpod/pull/14282
```release-note
NONE
```
=> [preview] configure cert-issuer p2

components/dashboard/src/components/ContextMenu.tsx, components/dashboard/src/workspaces/WorkspaceEntry.tsx
Currently when downloading a workspace it misses the `.tar` file extension. This uses the html native `download` property to add the `.tar` extension
Fixes #7955
(taken from #7955)
- Go to https://gitpod.io/workspaces
- Toggle the right options menu of a workspace in the list
- Select `Download Workspace`
```release-note
Fixed missing .tar file extension from a downloaded workspace
```
=> Add .tar extension to downloaded workspace

components/public-api-server/go.mod, components/public-api-server/go.sum, components/public-api-server/pkg/proxy/conn.go, components/public-api-server/pkg/proxy/conn_test.go, components/public-api-server/pkg/proxy/prometheusmetrics.go, components/public-api-server/pkg/server/server.go
Adds a connection pool implementation for `ServerConnectionPool`. This pool caches connections by their token. The cache is an LRU.
Initially, the LRU size is set to 3k which is derived from existing WS connection count on server.
There are metrics to track the cache hit rate, as well as how full the cache is.
* Part of https://github.com/gitpod-io/gitpod/issues/13574
* Depends on https://github.com/gitpod-io/gitpod/pull/14171
Unit test
```release-note
NONE
```
=> [public-api] Implement connection pool with LRU cache

components/usage/pkg/scheduler/reset_usage_job.go, components/usage/pkg/server/server.go
Periodic job triggers Reset Usage RPC.
* Part of https://github.com/gitpod-io/gitpod/issues/14178
```release-note
NONE
```
=> [usage] Start triggering ResetUsage RPC

components/server/src/code-sync/code-sync-service.ts, components/server/src/prometheus-metrics.ts, components/server/src/websocket/websocket-connection-manager.ts, operations/observability/mixins/meta/dashboards/components/meta-overview.json, operations/observability/mixins/meta/dashboards/components/server.json
Pushing the User ID into metric labels results in unbounded cardinality for the metric. See [thread](https://gitpod.slack.com/archives/C02EN94AEPL/p1666904970956639)
If needed, we can use `gitpod_server_api_calls_total` instead.
Fixes Unbounded metrics cardinality
```release-note
NONE
```
/hold for review from team IDE
=> [server] Remove gitpod_server_api_calls_user_total metric

operations/observability/mixins/self-hosted/dashboards/observability/cardinality-management-overview.json
With the addition of [cardinality-exporter](https://github.com/ArthurSens/cardinality-exporter), we're now able to extend our dashboard with per-label cardinality information.
You can import the dashboard in our Grafana and see it there 🙂 
```release-note
NONE
```
=> Extend cardinality dashboard with labels information

components/gitpod-protocol/go/gitpod-service.go, components/gitpod-protocol/go/mock.go
Adds support for `getGenericInvite` in the Go client for gitpod-protocol (server)
A couple of drive-by fixes to define (and use) function names as per existing pattern.
Fixes #
* Builds on CI. Unused anywhere currently but needed for https://github.com/gitpod-io/gitpod/pull/14152
```release-note
NONE
```
=> [gitpod-protocol] Add getGenericInvite to golang client

operations/observability/mixins/workspace/dashboards.libsonnet, operations/observability/mixins/workspace/dashboards/node-psi.json, operations/observability/mixins/workspace/dashboards/workspace-psi.json
This dashboard shows pressure stall information for workspaces. See https://grafana.gitpod.io/d/aq5CzlHVz/workspace-pressure-stall-information?orgId=1&var-datasource=VictoriaMetrics&var-cluster=eu73&var-node=workspace-ws-eu73-pool-v5bp&var-workspace=All
Fixes https://github.com/gitpod-io/ops/issues/3070
```release-note
None
```
=> Dashboard for workspace psi metrics

components/ws-manager/pkg/manager/manager.go
Remove PVC once the workspace pod is unschedulable.
Fixes #13282
Case 1.
- Create 100 pods to reach the per-node max pod limit
```console
for i in {1..100}; do kubectl run test-${i} --image ubuntu -- sleep 3600; done
```
- Enable PVC feature flag.
- Create a workspace, and make sure the workspace pod fails to up.
- Waits for 10 minutes: the workspace pod finalizer is removed, and the PVC object is gone.
- Waits for 30 minutes: the workspace pod is deleted.
```release-note
None
```
None
=> ws-manager: remove PVC once the workspace pod is unschedulable

components/gitpod-protocol/go/gitpod-service.go, components/gitpod-protocol/go/mock.go
Extends gitpod-protocol client with getTeams
* Part of https://github.com/gitpod-io/gitpod/issues/14310
Builds. Unused yet, will be used by https://github.com/gitpod-io/gitpod/pull/14301
```release-note
NONE
```
=> [gitpod-protocol] Add support for getTeams to golang client

components/gitpod-db/src/typeorm/migration/1666611052662-ChangeWorkspaceClusterTablePK.ts
Change the primary key of the `d_b_workspace_cluster` table from a key on just the `name` field to a composite key on `name` and `applicationCluster`.
<details>
To do that we will introduce a new field in the table called …
=> [db] Change the primary key of the `d_b_workspace_cluster` table

.github/workflows/jetbrains-auto-update-template.yml
Fix the IDE version to download in GitHub Action.
This change is required because the 'patch' number can differ from the Snapshot. For example:
- Snapshot: 223.7255.1
- IDE Build Number: 223.7255.83
- https://github.com/gitpod-io/gitpod/issues/13654
No need to test. See the dry-run of the build [here](https://github.com/gitpod-io/gitpod/actions/runs/3368013104).
```release-note
NONE
```
=> [JetBrains] Fix the IDE version to download in GitHub Action

.github/workflows/jetbrains-auto-update.yml
Run the GitHub Action only when `backend-plugin/gradle-latest.properties` changes.
Because now we update the Latest IDE Images based on the `platformVersion` described in that file.
- https://github.com/gitpod-io/gitpod/issues/13654
It can only be tested after merged into `main` branch and having a change on `components/ide/jetbrains/backend-plugin/gradle-latest.properties` file.
```release-note
NONE
```
=> [JetBrains] Run the GitHub Action only when `backend-plugin/gradle-latest.properties` changes

.github/workflows/jetbrains-auto-update.yml
Set the GitHub Action to run also on schedule because some IDEs may be updated to the same version of `gradle-latest.properties` only a few days later.
- https://github.com/gitpod-io/gitpod/pull/14318
No tests needed. It was the same before we merged [the last PR about this file](https://github.com/gitpod-io/gitpod/pull/14318).
```release-note
NONE
```
=> [JetBrains] Set the GitHub Action to run also on schedule

components/server/src/prometheus-metrics.ts, components/server/src/workspace/workspace-starter.ts
Add a counter for completed image builds `gitpod_server_image_builds_completed_total` to `server` with dimensions for successful and failed image builds.
Increment the relevant counter when an image build succeeds or fails. 
Part of https://github.com/gitpod-io/gitpod/issues/12960
(tbd once preview envs are working again).
```release-note
NONE
```
=> [server] Add metric for completed image builds

components/public-api-server/go.mod, components/public-api-server/go.sum, components/public-api-server/pkg/apiv1/team.go, components/public-api-server/pkg/apiv1/team_test.go, components/public-api-server/pkg/proxy/errors.go, components/public-api-server/pkg/proxy/errors_test.go, components/public-api-server/pkg/server/server.go
Implements TeamsService.CreateTeam by delegating to server.
* Depends on https://github.com/gitpod-io/gitpod/pull/14151
* Depends on https://github.com/gitpod-io/gitpod/pull/14170
* Depends on https://github.com/gitpod-io/gitpod/pull/14273
* Part of https://github.com/gitpod-io/gitpod/issues/14309
UI uses this RPC in 
* https://github.com/gitpod-io/gitpod/pull/14232
1. Open up preview, log-in
2. Obtain a token by running the below in the browser console
```javascript
```
3. Set your credentials on the command line:
```bash
BEARER_TOKEN="<token>"
```
5. Hit the endpoint, …
=> [public-api] Implement experimental TeamsService.CreateTeam

components/dashboard/BUILD.yaml, components/dashboard/package.json, components/dashboard/src/contexts/FeatureFlagContext.tsx, components/dashboard/src/projects/NewProject.tsx, components/dashboard/src/service/public-api.ts, components/dashboard/src/teams/NewTeam.tsx
* Depends on https://github.com/gitpod-io/gitpod/pull/14152
* Fixes https://github.com/gitpod-io/gitpod/issues/14309
The feature is enabled behind a feature flag.
* Use preview
* Create a new team (with DevTools open)
* Observe the request goes to `api.<domain>`
* Validate create workflow continues to behave the same
```release-note
NONE
```
=> [dashboard] Use public-api to CreateTeams

components/public-api-server/go.mod, components/public-api-server/go.sum, components/public-api-server/pkg/apiv1/team.go, components/public-api-server/pkg/apiv1/team_test.go
Needed to show on the Team Member's view when a member joined.
Server stores them as ISO8601 so had to use a library. We already use that library in the usage component so we know it works.
Fixes #
unit tests
```release-note
NONE
```
=> [public-api] Implement member_since on TeamMember

components/usage/pkg/apiv1/billing.go, components/usage/pkg/server/server.go, components/usage/pkg/stripe/stripe.go, components/usage/pkg/stripe/stripe_test.go, install/installer/pkg/components/usage/configmap.go
Implements CreateStripeSubscription.
Follow-up: Plug it into server with a feature flag.
Depends on #14124
Fixes #13198
1. Go to the [preview env](https://lau-create12ffe4ff15.preview.gitpod-dev.com/).
2. Create a team with the name `Gitpod` in it (make sure to use the capital 'G').
3. Go to the team's Billing page.
4. Upgrade plan. 
```release-note
NONE
```
=> [usage] Implement CreateStripeSubscription

components/gitpod-db/src/workspace-cluster-db.spec.db.ts
Add stronger assertions to the the database tests for the workspace cluster db.
Now that the primary key for the table is a composite of (`name`, `applicationCluster`), add tests that operations work as expected with rows that share the same `name`.
Part of #14136 
unit tests
```release-note
NONE
```
=> [db] Add extra assertions to workspace cluster db tests

components/dashboard/src/components/UsageView.tsx
This uses the `displayName` instead of the `id`
Note: This shows `Default` because it's using the preview env config.
Relates #13362
1. Join [this team](https://lau-creditaf7e9c5013.preview.gitpod-dev.com/teams/join?inviteId=d5300183-4b74-4c03-977b-91634a09c7f4) OR create your own team with the name "Gitpod" (uppercase 'G') and run some workspaces.
2. Check out the /usage page and see the workspace class name.
```release-note
NONE
```
=> [usage] Use workspaceClass displayName in Usage view

components/ws-daemon/debug.Dockerfile, components/ws-daemon/leeway.Dockerfile
Address openssl CVE issue
- Check openssl version in ws-daemon is 3.0.2
```release-note
NONE
```
=> [ws-daemon] Force build of container image

dev/loadgen/.gitignore, dev/loadgen/README.md, dev/loadgen/cmd/benchmark.go, dev/loadgen/cmd/run.go, dev/loadgen/pkg/loadgen/executor.go
Updates `loadgen [benchmark|run]` to allow parallel runs:
- Results now save to a unique directory under `results/`, e.g.:
```
/workspace/gitpod/dev/loadgen/results/
benchmark-0cb17d13-7715-4480-85e1-b0111c487e3d/
benchmark-result.json
stats.json
run-b0805a7e-8db9-4448-9201-f4dd279ad447/
stats.json
```
- Add a new `loadgen-session-id` annotation to started workspaces. This is used to identify which workspaces belong to which `loadgen` session, and used as a filter when calling ws-manager APIs, so that each loadgen only looks at its own workspaces
Fixes #14213
- Open a new workspace
- Setup loadgen and run `loadgen benchmark` twice against the same cluster
- Cancel one `loadgen`, observe it shuts down only workspaces created by this loadgen, and exits when done (does not get stuck waiting …
=> [loadgen] Allow parallel runs

components/image-builder-bob/cmd/root.go
This is useful for debugging issues with the build. By default, `image-builder-bob` pod disappears almost instantly, making hard to find the reason. 
- Enable LOG_LEVEL=debug in `image-builder-mk3`.
- Trigger a build that fails
- Check `image-builder-bob` pod stays alive for 1m. Inspect the log of the pod.
```release-note
NONE
```
=> [image-builder-bob] Enable wait if error in debug mode

components/ws-manager/pkg/manager/create.go
Adds init container when using PVC to ensure that PVC mounted folder has proper permissions (k8s mounts folder as root)
Fixes #14003 
Enable PVC
Open workspace. 
`ls -la /` and verify that `/workspace` is owned by `gitpod:gitpod` now.
```release-note
none
```
=> [pvc] add init container to workspace to chown pvc mount folder

components/public-api/gitpod/experimental/v1/teams.proto, components/public-api/go/experimental/v1/teams.pb.go, components/public-api/go/experimental/v1/teams_grpc.pb.go, components/public-api/go/experimental/v1/v1connect/teams.connect.go, components/public-api/typescript/src/gitpod/experimental/v1/teams_connectweb.ts, components/public-api/typescript/src/gitpod/experimental/v1/teams_pb.ts
Defines GetTeam RPC.
I've been holding off on adding this one as `server` currently doesn't have an equivalent, however, in the Public API we made TeamMembers a property of Teams, to reduce the number of first class domain objects.
This has the consequence that when we're listing team members in the dashboard, we need to lookup the Team (by ID) as we cannot lookup the TeamMembers by TeamID directly. That's okay, we expected a `Get` method makes sense anyway.
Fixes #
```release-note
NONE
```
=> [public-api] Define experimental GetTeam RPC

operations/observability/mixins/meta/rules/public-api.yaml
* Sends alerts to webapp slack for now
Fixes #
```release-note
NONE
```
=> [public-api] Add alerts for no metrics and failing RPCs

components/usage/pkg/apiv1/usage.go, components/usage/pkg/db/cost_center.go, components/usage/pkg/db/cost_center_test.go, components/usage/pkg/db/dbtest/cost_center.go
Reset during ResetUsage RPC.
Also resets usage when fetching a CostCenter, in case it has just expired.
* Part of https://github.com/gitpod-io/gitpod/issues/14178
Unit tests
```release-note
NONE
```
/hold
=> [usage]Actually reset usage during ResetUsage RPC

components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts, components/gitpod-db/src/typeorm/migration/1667375160684-AddDeletedColumnToWorkspaceClusterTable.ts, components/gitpod-db/src/workspace-cluster-db.spec.db.ts
Add a `deleted` column to the `d_b_workspace_cluster` table. This will allow rows to be soft-deleted in a follow-up PR.
Part of #9198 and #13800 
```release-note
NONE
```
=> [db] Add a `deleted` column to the `d_b_workspace_cluster` table

components/ws-manager-bridge/src/cluster-service-server.ts
When registering a new workspace cluster take the `applicationCluster` for the new ws cluster from config as happens elsewhere in this module rather than from the environment.
Part of #9198 
```release-note
NONE
```
=> [ws-manager-bridge] Take the applicationCluster from config

components/gitpod-protocol/go/gitpod-service.go, components/gitpod-protocol/go/mock.go, components/gitpod-protocol/src/gitpod-service.ts, components/server/src/auth/rate-limiter.ts, components/server/src/workspace/gitpod-server-impl.ts
Adds support for looking up teams by ID. While this is currently not used by dashboard, it's needed to support `GetTeam` RPC on the Public API.
This is because the Public API does not surface the TeamMembers as a first class resorouce, rather, it's a property of a Team. As a result, when for example listing TeamMembers in the dashboard, we need to `GetTeam`. This PR makes that lookup direct, rather than listing teams and filtering.
* Part of https://github.com/gitpod-io/gitpod/issues/14335
```release-note
NONE
```
=> [server, gitpod-protocol] Add getTeam

components/public-api-server/pkg/apiv1/team.go, components/public-api-server/pkg/apiv1/team_test.go
Implements experimental `TeamsService.ListTeams`
* Part of https://github.com/gitpod-io/gitpod/issues/14310
* Depends on https://github.com/gitpod-io/gitpod/pull/14300
* Depends on https://github.com/gitpod-io/gitpod/pull/14152
* Used in https://github.com/gitpod-io/gitpod/pull/14313
Unit tests.
1. Open up preview, log-in
2. Obtain a token by running the below in the browser console
```javascript
"function:getTeams",
```
3. Set your credentials on the command line:
```bash
BEARER_TOKEN="<token>"
```
4. Create a couple of teams, adjusting the `<team_name_X>` variable
```
curl \ …
```
=> [public-api] Implement experimental ListTeams

dev/kubecdl/main.go
According to https://cloud.google.com/sdk/gcloud/reference/topic/filters#Operator-Terms
The operators `=` and `:` are deprecated.
If we want to test equality, we should use `key <= value AND key >= value`.
Fixes #
Create two cluster name
- ephemeral-74
- ephemeral-74-1
Download the kubeconfig
```console
kubecdl ephemeral-74
kubecdl ephemeral-74-1
```
Then, run these commands without hitting the error `x509: certificate signed by unknown authority`. 
```console
kubectx ephemeral-74
kubectx ephemeral-74-1
```
```release-note
None
```
None
=> kubecdl: use label filter to find the exact cluster

components/dashboard/src/teams/JoinTeam.tsx, components/gitpod-db/src/team-db.ts, components/gitpod-db/src/typeorm/team-db-impl.ts, components/server/src/workspace/gitpod-server-impl.ts
The current semantics (and also error handling complexity) doesn't make it worth to fail the request when joining a team you're already a member of. After all, the desired outcome is achieved so we can treat it as a success.
Fixes #
1. Preview
2. Join team you're already a member of
3. See no error, transition to the team.
```release-note
NONE
```
=> [server] Do not fail joining a team you're already a member of

operations/observability/mixins/self-hosted/dashboards/observability/cardinality-management-overview.json
I'm adding links to the cardinality tables, so one can quickly jump from an overview to a detailed query with Grafana Explore
Fixes #
```release-note
NONE
```
=> Add links to explore cardinality metrics

components/dashboard/src/contexts/FeatureFlagContext.tsx
Logs showed
```
ConfigCatLogger.js:36 ConfigCat - ERROR - Evaluating getValue('usePublicApiTeamsService') failed.
```
Fixes #
```release-note
NONE
```
=> [dashboard] Fix public api feature flag name

components/gitpod-db/src/typeorm/workspace-cluster-db-impl.ts, components/gitpod-db/src/workspace-cluster-db.spec.db.ts
Soft delete records in the `d_b_workspace_cluster` table. This will allow the table to be synced by `db-sync` in a subsequent PR.
Part of #9198 and #13800.
Follow up to https://github.com/gitpod-io/gitpod/pull/14340.
Database unit tests.
```release-note
NONE
```
=> [db] Soft delete records in the `d_b_workspace_cluster` table

components/server/ee/src/workspace/gitpod-server-impl.ts
Uses the CreateStripeSubscription RPC behind a feature flag.
Relates #13198
I tested by: 
1. `kubectl port-forward server 9500:9500`
2. `curl localhost:9500/metrics`
3. Created subscription from a user behind the feature flag and another user that isn't.
4. The one that isn't feature flagged incremented the `gitpod_server_stripe_client_requests_completed_duration_seconds` metric.
```release-note
NONE
```
=> [usage] Use createStripeSubscription behind feature flag

components/gitpod-db/src/tables.ts
Add the `d_b_workspace_cluster` table to the `db-sync` config to start syncing the table.
<details>
To do that we will introduce a new field in the table called `applicationCluster` which records the name of the application cluster …
=> [db-sync] Add the `d_b_workspace_cluster` table to sync config

components/blobserve/pkg/blobserve/blobspace.go, install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/shortname/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/blobserve/configmap.go
Remove useless replacement, since files is not exists. See also [error reporting](https://console.cloud.google.com/errors/detail/COaqrub2ydGFxQE;service=blobserve;time=PT6H?project=gitpod-191109)
Fixes #
- Get blobserve logs by `kubectl get logs <pod_of_blobserve>`
- Should have no errors like `Blobspace::AddFromTar error while trying to modify file`
```
kubectl logs blobserve-84855bd74-gw7vx | grep AddFromTar
```
```release-note
NONE
```
=> [blobserve] remove not exists file replacement

components/ide/jetbrains/gateway-plugin/build.gradle.kts
As discussed, now that we publish only when relevant changes are found, we can automate the stable release. We will stop using `Nightly` from now and consider removing the channel until we need it again.
Fixes #9101
N/A
```release-note
NONE
```
=> [JetBrains Gateway Plugin] Publish automatically to stable channel

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/shortname/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/workspace/ide/constants.go
Updates the stable image of VS Code Browser to `1.73.0`
A part of https://github.com/gitpod-io/gitpod/issues/14272.
Open the preview environment, select VS Code Browser (non-`latest`) and in the <kbd>About</kbd> dialog check that we are on `1.73.0`.
```release-note
NONE
```
=> Update stable to `1.73`

components/server/ee/src/prebuilds/bitbucket-server-service.ts, components/server/src/bitbucket-server/bitbucket-server-api.ts
Extends logging around webhook installation to enable investigation of #13998.
Related #13998
```release-note
NONE
```
=> [bitbucket-server] improve logging of webhook installation

components/gitpod-protocol/go/gitpod-service.go, components/gitpod-protocol/go/mock.go
Will be needed to ResetTeamInvite by PublicAPI
* Part of https://github.com/gitpod-io/gitpod/issues/14384
```release-note
NONE
```
=> [gitpod-protocol] Add ResetGenericInvite to golang client

install/installer/pkg/components/usage/configmap.go, install/installer/pkg/components/usage/configmap_test.go, install/installer/pkg/config/v1/experimental/experimental.go
Makes reset usage configurable through the installer config.
Fixes #
```release-note
NONE
```
=> [usage] Make reset usage task configurable through installer

components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/ShareWorkspaceSnapshotAction.kt
Very small PR to align how we interact with the clipboard in JetBrains backend-plugin. In a recent PR created by @felladrin [[1]](https://github.com/gitpod-io/gitpod/pull/14356/files#diff-5502e07b0ac56646b7243f5e9e77d4f82aac6b45bbb6cb69cf3ebf907b472cc2R12), we use `CopyPasteManager` from the intellij package. In the snapshot action we use one from `java.awt.Toolkit`. They both work but it's good to have a single approach for something like this.
N/A
In prev env this cannot be tested due to plan limitations. In prod:
I've already tested with the following steps and it works, but for testing again:
1. Start a workspace for this branch
2. run `launch-dev-server.sh` from `backend-plugin`
3. Connect to the IDE and create a snapshot
4. Verify that the copy to clipboard of the snapshot URL works …
=> [Jetbrains] Use single copy to clipboard approach

install/preview/entrypoint.sh, install/preview/prettylog/main.go
With the removal of `-x` option in bash, We can't rely on the
commands anymore and instead have to start using `echo` messages
to match statuses in `prettylog`.
This PR updates the remaining statuses on the
same.
Fixes #
Run `docker run -p 443:443 --privileged --name gitpod -it  --mount type=volume,source=gitpod,destination=/var/gitpod eu.gcr.io/gitpod-core-dev/build/local-preview:tar-update-success-messages.1`
```release-note
[local-preview] Update status messages to depend on echo's
```
=> [local-preview] Update status messages to depend on echo's

components/dashboard/src/App.tsx, components/dashboard/src/service/public-api.ts, components/dashboard/src/teams/JoinTeam.tsx, components/public-api-server/pkg/apiv1/team_test.go
* Part of https://github.com/gitpod-io/gitpod/issues/14352
* Depends on https://github.com/gitpod-io/gitpod/pull/14328
1. Sing in to Preview
2. Open up dev console
3. Join team with this invite: https://mp-dash-join-team.preview.gitpod-dev.com/teams/join?inviteId=455eb032-3c0d-4df0-ae2e-7090e601ba28
4. Observe HTTP request made to `JoinTeam` targeting `api.<preview_domain>`
```release-note
NONE
```
=> [dashboard] Use public-api to JoinTeam

components/public-api-server/pkg/apiv1/workspace_test.go
Follow-up to https://github.com/gitpod-io/gitpod/pull/14392#discussion_r1012742556
Fixes #
unit tests
```release-note
NONE
```
=> [public-api] Cleanup Workspace Service tests

dev/preview/previewctl/cmd/get_name.go, dev/preview/previewctl/cmd/install_context.go, dev/preview/previewctl/cmd/list_previews.go, dev/preview/previewctl/cmd/root.go, dev/preview/previewctl/cmd/ssh_vm.go, dev/preview/previewctl/pkg/preview/preview.go
* Fix the passing of the branch flag used in subcommands
* The flag is bound to the variable when the command is executed. Passing it to the function that creates the command, means that it's empty. 
* Rename the the `Preview` struct. `preview.Preview` -> `preview.Config`
* Doesn't stutter 
Fixes #
```release-note
NONE
```
=> [previewctl] fix branch flag and rename structs

test/tests/components/ws-manager/dotfiles_test.go
Test dotfile support
Fixes https://github.com/gitpod-io/gitpod/issues/13973
```release-note
None
```
=> Test dotfile support

components/BUILD.yaml
In https://github.com/gitpod-io/gitpod/pull/14183 the agent smith token was passed to `leeway run components:add-smith-token` as a leeway argument using `-DTOKEN=...` instead of an environment variable. It turns out that Leeway does variable interpolation only when using the full `${VARIABLE}` syntax so $TOKEN was evaluated by bash instead and contains the empty string.
Follow up to https://github.com/gitpod-io/gitpod/pull/14183
Verified that the token is now in the DB (before this change it was empty)
```
kubectl port-forward statefulsets/mysql 3306:3306
export DB_USERNAME=$(kubectl get secrets mysql -o jsonpath="{.data.username}" | base64 -d)
export DB_PASSWORD=$(kubectl get secrets mysql -o jsonpath="{.data.password}" | base64 -d)
mysql -u${DB_USERNAME} -p${DB_PASSWORD} -h 127.0.0.1 …
```
=> Use proper variable interpolation in Leeway script

components/dashboard/src/service/public-api.ts, components/dashboard/src/teams/Members.tsx
Retrieve team members from Public API, behind an experiment.
Fixes #
1. Log in to preview, open up dev console.
2. Join my team: https://mp-dash-mec45944a41b.preview.gitpod-dev.com/teams/join?inviteId=7ea48015-a4cf-4197-b2f3-b3099d079468
3. Navigate to team members, observe request is made against `GetTeam`
4. The Members page continues to work as before
```release-note
NONE
```
=> [dashboard] Fetch team members using public API

.github/workflows/code-nightly.yml
ref https://github.com/gitpod-io/gitpod/issues/14272
```release-note
NONE
```
=> [code] Point back to main

operations/observability/mixins/IDE/dashboards/components/openvsx-mirror.json
Add max value (100%) for MEM and CPU usage, to avoid auto calculate failed (turn out to max 1000% sometimes)
Fixes #
No need
```release-note
NONE
```
=> [observability] add max value for mem and cpu

components/registry-facade/pkg/registry/blob.go, components/registry-facade/pkg/registry/metrics.go
We don't have enough details about the base reference and additionally improve the `BlobDownloadCounter` metric to get details about the result of the operation
xref: https://github.com/gitpod-io/gitpod/issues/14264
```release-note
NONE
```
=> [registry-facade] Add additional GetBlob error logs

operations/observability/mixins/workspace/dashboards.libsonnet, operations/observability/mixins/workspace/dashboards/registry-facade-blobsource.json
[check temporal dashboard URL](https://grafana.gitpod.io/d/-5J1T3S4k/registry-facade-download-bytes?orgId=1&refresh=30s&from=now-24h&to=now&var-cluster=us73)
```release-note
NONE
```
=> Fix registry facade blobSource dashboard and add link

.github/CODEOWNERS, install/installer/pkg/components/components-webapp/components.go, install/installer/pkg/components/toxiproxy/configmap.go, install/installer/pkg/components/toxiproxy/constants.go, install/installer/pkg/components/toxiproxy/objects.go, install/installer/pkg/components/toxiproxy/objects_test.go, install/installer/pkg/config/v1/experimental/experimental.go
Add a new `experimental.webapp.slowDatabase` experimental flag to the installer. When the new flag is set, render an empty placeholder Toxiproxy configmap.
As part of #9198, [Toxiproxy](https://github.com/Shopify/toxiproxy) will be used to inject latency into database connections to allow us to measure and test the UX of working with a distant database (eg a US database from the EU).
The new component is a placeholder, rendering an empty configmap. In subsequent PRs, the component will be extended to add a Toxiproxy deployment, service and config file.
Part of #9198 
Installer unit tests.
```release-note
NONE
```
=> [installer] Add a placeholder for an experimental toxiproxy component

.github/workflows/jetbrains-update-plugin-platform-template.yml
Use Large VM for Preview Environments related to JetBrains IDEs. Otherwise, due to a lack of memory, the workspace gets stuck, ruining the test.
Check this PR as an example:
- https://github.com/gitpod-io/gitpod/pull/14349/
No need to test. It's just an addition of Werft Annotation for future PRs.
```release-note
NONE
```
=> [GitHub Action] Use Large VM for Preview Environments related to JetBrains IDEs

components/public-api-server/pkg/auth/context.go, components/public-api-server/pkg/auth/context_test.go, components/public-api-server/pkg/auth/middleware.go, components/public-api-server/pkg/auth/middleware_test.go, components/public-api-server/pkg/proxy/conn.go, install/installer/pkg/components/public-api-server/configmap.go, install/installer/pkg/components/public-api-server/configmap_test.go
Cookies on the request are sent downstream to Server to use as authentication. We support both Access Tokens, and Cookies.
Fixes #
Unit tests
See it on dashboard in [this PRs preview](https://github.com/gitpod-io/gitpod/pull/14403).
```release-note
NONE
```
=> [public-api] Proxy Cookies to downstream for auth

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/shortname/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/ide-metrics/configmap.go, operations/observability/mixins/IDE/dashboards/components/code-browser.json
Add galleryHost label
```release-note
NONE
```
=> Add galleryHost label

components/dashboard/src/service/public-api.ts
Using existing Cookies to authenticate against Public API
* Depends on https://github.com/gitpod-io/gitpod/pull/14398
1. Open up preview
2. Sign in, open up console
3. Create Team, notice the request to HTTP `CreateTeam`, observe it's sending Cookies and receives an OK response
```release-note
NONE
```
=> [dashboard] Authenticate with Public API using Cookies instead of Tokens

components/public-api-server/pkg/proxy/conn.go, components/public-api-server/pkg/proxy/conn_test.go, install/installer/pkg/components/public-api-server/configmap.go, install/installer/pkg/components/public-api-server/configmap_test.go
Turns out that the `api/v1` endpoint doens't accept Cookies
And that the `api/gitpod` endpoint doens't accept Bearer Tokens ...
Fixes #
unit
```release-note
NONE
```
=> [public-api] Parametrize connection URL based on token

.werft/jobs/build/deploy-to-preview-environment.ts, .werft/jobs/build/installer/installer.ts, .werft/jobs/build/job-config.ts, dev/preview/workflow/preview/deploy-gitpod.sh
Add support for new `with-slow-database` annotation on Werft jobs that build preview environments.
If the new `with-slow-database`  annotation is set on the job, pass the new `experimental.webapp.slowDatabase=true` flag to the installer.
Support for the experimental installer flag is added in the dependent PR (https://github.com/gitpod-io/gitpod/pull/14359).
Part of #9198 
Depends on https://github.com/gitpod-io/gitpod/pull/14359
Create a preview environment from this branch with:
```bash
werft run github -j .werft/build.yaml -a with-preview=true -a with-clean-slate-deployment=true -a with-slow-database=true
```
In the preview environment notice that the placeholder `toxiproxy` configmap is present.
Recreate the preview environment without the `with-slow-database` annotation:
```bash …
```
=> [preview] Add support for new `with-slow-database` annotation

operations/observability/mixins/IDE/dashboards/components/openvsx-mirror.json
This PR Adjusting openvsx-mirror dashboard
1. add max value for gc overhead
2. remove `JVM - Quartz Jobs`
3. filter CLIENT_ERROR for error
Fixes #
```release-note
NONE
```
=> [observability] Adjusting openvsx-mirror dashboard

components/dashboard/src/teams/Members.tsx, components/public-api-server/pkg/apiv1/team.go, components/public-api-server/pkg/apiv1/team_test.go
Dashboard uses Public API when resetting team invitations.
* Fixes https://github.com/gitpod-io/gitpod/issues/14384
1. Preview env, open dev console
2. Create a team
3. Reset team invitation, observe request made to `ResetTeamInvitation`, observe OK response
```release-note
NONE
```
=> [dashboard] ResetTeamInvitation uses Public API

install/installer/scripts/kots-install.sh
This PR fixes the issue when a custom docker config json file is uploaded by the user.
Fixes https://github.com/gitpod-io/gitpod/issues/14365
```release-note
[kots] merge custom docker config correctly
```
=> [kots] merge custom docker config correctly

WORKSPACE.yaml
[code] build stable image to add gallery metrics
Fixes #
check ide-metrics it should be contain correct galleryHost
```release-note
NONE
```
=> [code] build stable image to add gallery metrics

operations/observability/mixins/IDE/dashboards/components/code-browser.json, operations/observability/mixins/IDE/dashboards/components/openvsx-mirror.json
This PR adjusting openvsx-mirror and code-browser dashboard
for openvsx-mirror
1. add max value for error ratio
2. include CLEIENT_ERROR in `failure ratio by status code`
for code-browser rename  `galleryHost` to `gallery`
Fixes #
```release-note
NONE
```
=> [observability] Adjusting openvsx-mirror and code-browser dashboard

install/installer/pkg/components/toxiproxy/constants.go, install/installer/pkg/components/toxiproxy/deployment.go, install/installer/pkg/components/toxiproxy/objects.go, install/installer/pkg/components/toxiproxy/objects_test.go
https://github.com/gitpod-io/gitpod/pull/14359 added support for the new `experimental.webapp.slowDatabase` config setting, installing a placeholder configmap when the flag was set. This PR builds on that by rendering a [Toxiproxy](https://github.com/Shopify/toxiproxy) deployment when the flag is set.
Subsequent PRs will add a service and a real configmap in addition to the deployment.
Part of #9198
* Run `previewctl install-context` on this branch. This sets your kube context to the preview environment for this branch (one that was created with the new `with-slow-database` annotation).
* `kubectl get pods` shows a `toxiproxy` pod running in the cluster.
* Port-forward to the `toxiproxy` pod: `kubectl port-forward deploy/toxiproxy 8474:8474`
* Run `docker run --net=host --rm …
=> [installer] Add a toxiproxy deployment behind the experimental `slowDatabase` flag.

dev/jetbrains-test/gradle/wrapper/gradle-wrapper.properties
In other components from Gitpod we're using Gradle v7.3.1. So we'll also use in `jetbrains-test`.
This fixes this warning  [[Reported Internally](https://gitpod.slack.com/archives/C01KGM9BH54/p1667565060291469)] from VS Code:
Open this branch in gitpod.io using VS Code and confirm if there's no warning about Gradle.
```release-note
NONE
```
=> [JetBrains] Update Gradle to the same version used in other components (v7.3.1)

install/installer/pkg/components/toxiproxy/constants.go, install/installer/pkg/components/toxiproxy/deployment.go, install/installer/pkg/components/toxiproxy/objects.go, install/installer/pkg/components/toxiproxy/objects_test.go, install/installer/pkg/components/toxiproxy/service.go
https://github.com/gitpod-io/gitpod/pull/14423 added a Toxiproxy deployment behind the new experimental `webapp.slowDatabase` installer config flag.
This PR builds on that to add a kubernetes service in addition to the deployment.
Part of #9198.
Depends on https://github.com/gitpod-io/gitpod/pull/14423.
1. In the preview environment for this branch, `kubectl get svc` shows a `toxiproxy` service.
2. Port-forward to the service: `kubectl port-forward svc/toxiproxy 8474:8474`.
3. Run `Run docker run --net=host --rm --entrypoint="/toxiproxy-cli" -it ghcr.io/shopify/toxiproxy:2.5.0 list`.
This shows that the service is correctly sending traffic to the `toxiproxy` deployment.
```release-note
NONE
``` …
=> [installer] Add a toxiproxy service behind the experimental `slowDatabase` flag

components/dashboard/src/Pagination/Pagination.tsx, components/dashboard/src/Pagination/PaginationNavigationButton.tsx
Changed the design of pagination component to match more with the current theme
Dark Mode:
Light Mode:
Disabled Dark Mode:
Disabled Light Mode:
Hover Dark Mode:
Hover Light Mode:
Fixes #12537, #12027
Go to any page which has some pagination involved and check the pagination buttons 
```release-note
Improve pagination usability
```
=> Pagination design fixes

scripts/ws-deploy.sh
I always have to set this because it slows down the deployment.
n.a.
n.a.
```release-note
None
```
=> [workspace] Don't run tests when using debug.sh

dev/loadgen/configs/prod-benchmark-pvc.yaml, dev/loadgen/configs/prod-benchmark.yaml, dev/loadgen/configs/workspace-preview-benchmark-pvc.yaml, dev/loadgen/configs/workspace-preview-benchmark.yaml
Move workspace stress repository to the [gitpod-io org](https://github.com/gitpod-io/workspace-stress)
Fixes https://github.com/gitpod-io/gitpod/issues/11485
```release-note
None
```
=> [loadgen] Move workspace stress repository

components/registry-facade-api/go/config/config.go, components/registry-facade/pkg/registry/registry.go, install/installer/pkg/components/registry-facade/configmap.go, install/installer/pkg/config/v1/experimental/experimental.go
Refactor `registry-facade` Redis connection removing support for `sentinel` and at the same time adding support for TLS connections.
The goal is to simplify the code and avoid some of the `go-redis` issues with context timeouts.
xref: https://github.com/gitpod-io/ops/pull/5949
- Use the same instructions from https://github.com/gitpod-io/ops/pull/5949
```release-note
NONE
```
=> [registry-facade] Remove redis sentinel and add TLS support

install/installer/pkg/components/toxiproxy/configmap.go, install/installer/pkg/components/toxiproxy/constants.go, install/installer/pkg/components/toxiproxy/deployment.go, install/installer/pkg/components/toxiproxy/service.go, install/installer/pkg/components/toxiproxy/types.go
Configure Toxiproxy using a configmap containing a toxiproxy configuration file. 
The config file sets up an upstream for the mysql database.
Builds on:
https://github.com/gitpod-io/gitpod/pull/14359
https://github.com/gitpod-io/gitpod/pull/14423
https://github.com/gitpod-io/gitpod/pull/14430
Part of #9198 .
Depends on https://github.com/gitpod-io/gitpod/pull/14423 and https://github.com/gitpod-io/gitpod/pull/14430.
1. In the preview environment for this PR, port forward to the `mysql` Toxiproxy proxy:
```
kubectl port-forward svc/toxiproxy 3306:3306
```
2. Connect to the database through Toxiproxy with eg, `mycli -u gitpod gitpod`.
These two steps show that Toxiproxy has been configured to listen on port 3306 and proxy the upstream `mysql` instance.
```release-note
NONE
```
If enabled …
=> [installer] Add a configmap for Toxiproxy behind the experimental `slowDatabase` flag

components/server/ee/src/prebuilds/gitlab-app.ts
To avoid provoking permanent deactivation of the webhooks we need to stop responding with status 401. In future we need to make the Unauthorized situation fixable from Gitpod.
Fixes #13985
1. Do a manual test with a GitLab project, including pushing to a repo and verifying that a prebuild was triggered. 
2. Delete your test account.
3. Push a change to the test repo, and verify that Gitpod is not responding with code 401. See: https://gitlab.com/YOUR_ACCOUNT/TEST_REPO/-/hooks/WEBHOOK_ID/edit
```release-note
Gitlab webhooks: play nice, don't respond with code 401.
```
=> [gitlab/webhook] return code 200 on Unauthorized

components/ide/jetbrains/backend-plugin/build.gradle.kts, components/ide/jetbrains/gateway-plugin/build.gradle.kts
Tiny PR to improve code readability and ensure Backend and Gateway plugins have the same code.
Environment Name can never be null, as it has a default value set in `gradle.properties`, but it can be overridden as an empty string, so we need to check if it's not blank.
And the other code was hard to read. Although there's a repeated string now, it's easier to understand that it will exclude its opposite ("stable" <-> "latest").
No need to test.
But if you want to test, you can use the preview environment and confirm if both Stable and EAP IntelliJ IDE opens correctly and displays a terminal as soon as you open the workspace.
```release-note
NONE
```
=> [JetBrains] Improve code readability

components/ws-daemon/cmd/run.go, components/ws-daemon/debug.Dockerfile, components/ws-daemon/leeway.Dockerfile, components/ws-daemon/pkg/cgroup/plugin_iolimit_v1.go, components/ws-daemon/pkg/content/hooks.go
Without LVM devices and special files (symlinks), we cannot enforce disk quotas.
In installations without LVM this is a NOOP.
- Create an ephemeral cluster using LVM
- Run `fallocate -l 100G /workspace/should-fail`
- Should return with an error
```release-note
NONE
```
=> [ws-daemon] Create missing LVM device and special files

components/public-api-server/pkg/proxy/errors.go, components/public-api-server/pkg/proxy/errors_test.go
Return Permission Denied when a blocked user error is returned by server/
Fixes #
```release-note
NONE
```
=> [public-api] Handle blocked user error

components/dashboard/src/admin/Property.tsx, components/dashboard/src/admin/UserDetail.tsx, components/dashboard/src/settings/Plans.tsx, components/gitpod-protocol/src/billing-mode.ts, components/server/ee/src/billing/billing-mode.spec.db.ts, components/server/ee/src/billing/billing-mode.ts
If users are already member of a paid Chargebee team, and not part of a UBP team yet, their move to UBP (free tier) is blocked. This PR shows the team names of those who are actually blocking.
We can use this in two ways:
1. understand their state better ourselves when operating Gitpod (admin dashboard)
2. explain in the docs how people can understand themselves (personal billing page)
Fixes #12758
- [signup](https://gpl-12758-list-plans.preview.gitpod-dev.com/workspaces)
- Join [this team](https://gpl-12758-list-plans.preview.gitpod-dev.com/teams/join?inviteId=bb2a82a0-6392-49c0-aa9e-0f6a194b9367)
- add your user id to ConfigCat [here](https://app.configcat.com/08da1258-64fb-4a8e-8a1e-51de773884f6/08da1258-6541-4fc7-8b61-c8b47f82f3a0/08da1258-6512-4ec0-80a3-3f6aa301f853)
- go to admin …
=> Show Team Seats that block individuals from being in the Usage-Based Free tier

install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/shortname/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/versions.yaml, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/toxiproxy/configmap.go, install/installer/pkg/components/toxiproxy/constants.go, install/installer/pkg/components/toxiproxy/deployment.go, install/installer/pkg/components/toxiproxy/objects_test.go, install/installer/pkg/config/versions/versions.go
As part of #9198 we will run a [Toxiproxy](https://github.com/Shopify/toxiproxy/) instance in the application cluster to allow us to simulate a high-latency connection to the Gitpod database.
https://github.com/gitpod-io/gitpod/pull/14473 added a new component, `toxic-config`, intended to run as a sidecar container in a Kubernetes pod alongside Toxiproxy, that configures a given proxy with a [latency toxic](https://github.com/Shopify/toxiproxy/blob/master/README.md#latency).
This PR makes that new component run as a sidecar in the Toxiproxy component to ensure that the `mysql` component is configured with latency.
Part of #9198 
1. Port forward to Toxiproxy:
```
kubectl port-forward svc/toxiproxy 8474:8474
```
2. Verify that the sidecar container successfully configured the `mysql` proxy: …
=> [installer] Run the `toxic-config` component as a sidecar in the Toxiproxy pod

components/public-api-server/pkg/apiv1/team_test.go, components/public-api-server/pkg/apiv1/workspace_test.go, components/public-api-server/pkg/proxy/errors.go, components/public-api-server/pkg/proxy/errors_test.go
Improves handling of websocket errors. Instead of parsing strings, we use the underlying websocket error types.
* Relates to https://github.com/gitpod-io/gitpod/issues/14482, but does not fix it (yet)
Unit
```release-note
NONE
```
=> [public-api] Properly extract errors from Websocket RPC

components/dashboard/src/components/CheckBox.tsx, components/dashboard/src/projects/Project.tsx, components/dashboard/src/projects/ProjectSettings.tsx, components/dashboard/src/start/CreateWorkspace.tsx, components/gitpod-protocol/src/gitpod-service.ts, components/gitpod-protocol/src/protocol.ts, components/gitpod-protocol/src/teams-projects-protocol.ts, components/server/ee/src/prebuilds/bitbucket-app.ts, components/server/ee/src/prebuilds/bitbucket-server-app.ts, components/server/ee/src/prebuilds/github-app.ts, components/server/ee/src/prebuilds/github-enterprise-app.ts, components/server/ee/src/prebuilds/prebuild-manager.ts, components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/ee/src/workspace/workspace-factory.ts, components/server/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/workspace-factory.ts
Introduces a project setting that allows for starting workspaces on the successful prebuild on the direct linear commit history. Enabling this will always skip the "prebuild-in-progress" view.
It also allows specifying the number of commits to skip in between prebuilds.
Fixes #12583
- create a team & project
- go to the settings and enable 'incremental prebuilds' set the number of commits to 1
- start a workspace.
- push a commit (no config change!) and verify that no prebuild is running
- start a workspace and verify that it is based on the first prebuild
- push a commit (no config change!) and verify that a prebuild gets triggered
- push a commit that changes the init task in the gitpod.yml and verify that a prebuild gets triggered
```release-note
Introduced a new project setting that …
```
=> [server] incremental workspaces

components/dashboard/src/admin/ProjectsSearch.tsx, components/dashboard/src/admin/TeamsSearch.tsx, components/dashboard/src/admin/UserSearch.tsx, components/dashboard/src/admin/WorkspacesSearch.tsx
Fixes the broken admin search
Fixes #13749
```release-note
NONE
```
=> fix admin search

.werft/jobs/build/deploy-to-preview-environment.ts, .werft/jobs/build/installer/installer.ts, .werft/jobs/build/job-config.ts, dev/preview/workflow/preview/deploy-gitpod.sh
Currently, Analytics in preview environments are broken through werft as we need to pass the write key through attributes which means we would leak it.
This PR fixes that by instead updating weft to read them from a Kubernetes secret (This is already added into the cluster. See https://github.com/gitpod-io/ops/pull/6614). This means users now enable analytics by using setting `analytics: segment` and we read `segment-staging-write-key` to make it work. This secret is set to the staging segment source right now.
Fixes https://github.com/gitpod-io/gitpod/issues/14509
Run the following and see analytic events in the `staging trusted` segment source.
```
leeway run dev/preview:build
leeway run dev/preview:create-preview …
```
=> [werft] Update previews to use analytics token from secret

.gitpod.yml, scripts/branch-namespace.sh
The script was back from the time when preview environments were hosted in core-dev in separate namespaces. We no longer have core-dev-based preview environments, so the script is no longer needed.
No issue, just tidying.
Before
After
```release-note
NONE
```
N/A
=> Remove legacy branch-namespace script

components/server/ee/src/user/stripe-service.ts, components/server/ee/src/user/user-deletion-service.ts
These are the definitely-valuable parts salvaged from my [proration effort](https://github.com/gitpod-io/gitpod/pull/14148) (which ended up not working out):
- Immediately issue a final invoice when cancelling Stripe subscriptions from Gitpod (currently, we're letting Stripe wait until the end of the month)
- When deleting a user account, also cancel any individual Stripe subscription (we forgot to do this until now)
Fixes #
2. Go to `/billing`
3. Upgrade your user to usage-based billing by adding a payment method
4. Then, delete your user -- this should both:
a. automatically cancel your individual Stripe subscription (double-check in the Stripe dashboard)
b. immediately issue a final invoice (it's going to be in draft for 1h, but at least …
=> Minor improvements to the Stripe subscription cancellation flow

.werft/jobs/build/deploy-to-preview-environment.ts
Fixes failing werft jobs on main due to 
```
/workspace/node_modules/ts-node/src/index.ts:513
return new TSError(diagnosticText, diagnosticCodes)
^
TSError: ⨯ Unable to compile TypeScript:
.werft/jobs/build/deploy-to-preview-environment.ts(9,10): error TS2459: Module '"./installer/installer"' declares 'Analytics' locally, but it is not exported.
```
Fixes #
```release-note
NONE
```
=> [ci] Fix werft job definition

components/dashboard/src/admin/WorkspaceDetail.tsx, components/dashboard/src/workspaces/WorkspaceEntry.tsx
Remove download workspace button from admin.
Fixes https://github.com/gitpod-io/gitpod/issues/14381 https://github.com/gitpod-io/gitpod/issues/14382
1. Go to **/admin/workspaces**.
2. Search for a workspace.
3. Notice the _Download Workspace_ button is now missing.
```release-note
Remove download workspace button from admin
```
=> Remove download workspace button from admin

.github/CODEOWNERS, components/BUILD.yaml, components/toxic-config/BUILD.yaml, components/toxic-config/README.md, components/toxic-config/go.mod, components/toxic-config/go.sum, components/toxic-config/leeway.Dockerfile, components/toxic-config/main.go
As part of #9198 we will run a [Toxiproxy](https://github.com/Shopify/toxiproxy/) instance in the application cluster to allow us to simulate a high-latency connection to the Gitpod database. Installation and configuration of this Toxiproxy instance is done in some preceding PRs:
* https://github.com/gitpod-io/gitpod/pull/14359
* https://github.com/gitpod-io/gitpod/pull/14388
* https://github.com/gitpod-io/gitpod/pull/14423
* https://github.com/gitpod-io/gitpod/pull/14430
* https://github.com/gitpod-io/gitpod/pull/14437
Toxiproxy allows declarative configuration of proxies via a config file, but configuration of [toxics](https://github.com/Shopify/toxiproxy/blob/master/README.md#toxics) has to be done dynamically while Toxiproxy is running.
This PR adds a new component `toxic-config`, …
=> Add `toxic-config` component to configure Toxiproxy instances with latency toxics

.github/pull_request_template.md, .werft/ide-integration-tests-startup.sh, .werft/jobs/build/job-config.ts, test/run.sh
Split IDE tests into `vscode`, `jetbrains`, `ssh` to allow running specific IDE-related tests only for faster feedback loop. It remains possible just using `ide` to trigger all of them.
Fixes #14481 
Already tested in: https://werft.gitpod-dev.com/job/gitpod-custom-afalz-14481-split-ide-integration-tests-2.1/raw
To test again:
1. start a workspace for this branch
2. run `werft run github -s .werft/jobs/build/job-config.ts -s .werft/jobs/build/trigger-integration-tests.ts  -j .werft/build.yaml`
3. check the werft logs to make sure only jetbrains tests ran ('jetbrains' is set as annotation to this PR)
```release-note
NONE
```
=> [Integration Tests] Allow running specific IDE suite

components/dashboard/src/projects/NewProject.tsx, components/dashboard/src/teams/NewTeam.tsx
Show error message without error code
Fixes https://github.com/gitpod-io/gitpod/issues/14482
1. Preview
2. Create one team
3. Create a team with duplicate name, observe error shown doesn't contain error code
```release-note
NONE
```
=> [dashboard] Handle create team errors from Public API better

.github/CODEOWNERS, .github/workflows/jetbrains-update-plugin-platform-template.yml
We want PRs related to EAP JetBrains Backend Plugin SDK updates (like [PR#14349](https://github.com/gitpod-io/gitpod/pull/14349)) to be automatically accepted.
This PR makes it take the output from [Create Pull Request](https://github.com/peter-evans/create-pull-request) and pass it to [Auto Approve](https://github.com/marketplace/actions/auto-approve), which in turn approves it, so the automatically-created PR should be approved right away, and if the Werft Build passes, @roboquat will merge it without any human interaction.
- Resolves https://github.com/gitpod-io/gitpod/issues/14480
Couldn't think of a way to test it. We'll need to see how it behaves when a new EAP IntelliJ SDK version is released.
```release-note
NONE
```
=> [JetBrains EAP] Auto-approve PRs created for updating Backend Plugin's SDK

install/tests/cleanup.sh
In [this werft job](https://werft.gitpod-dev.com/job/gitpod-cleanup-installer-tests-main.135) we have several CI jobs that aren't getting cleaned up (and may have been lingering for a while) but the CI job is passing.
This came up because I have a preview environment that passed the 10 hour threshold yesterday that hasn't been cleaned up so closer inspection is warranted. After we dig into this issue we need to confirm that we don't have stale self-hosted preview environments burning cloud spend.
TBD
```release-note
NONE
```
=> [installer-tests] Fail cleanup job when any environment  cleanup fails

dev/BUILD.yaml, dev/preview/BUILD.yaml
This introduces a single top-level command `leeway run dev:preview` which delegates to our other Leeway scripts in `dev/preview`. I also changed `dev/preview:create-preview` so that it ensures the kubectx is installed (https://github.com/gitpod-io/gitpod/issues/14468).
With this PR you can open a Gitpod workspace and simply run `leeway run dev:preview` and it will Build Gitpod, create a preview environment, and deploy to it.
Fixes https://github.com/gitpod-io/gitpod/issues/14361
Fixes https://github.com/gitpod-io/gitpod/issues/14468
```sh
```
```release-note
NONE
```
N/A
=> Introduce a single Leeway entrypoint script

.github/workflows/jetbrains-update-plugin-platform-template.yml, .github/workflows/jetbrains-updates.yml
Requires https://github.com/gitpod-io/gitpod/pull/14534 to be merged
In PRs where we update JB SDK versions, we should trigger the jetbrains integration tests. Especially now that we've decided to [auto-approval](https://github.com/gitpod-io/gitpod/pull/14527) for backend-latest updates.
Relates #14481
N/A
```release-note
NONE
```
=> [JetBrains] Run jetbrains integration tests when creating automated PR for JB updates

dev/BUILD.yaml, dev/preview/BUILD.yaml
`leeway run dev/preview:create-preview` is used in Werft where the contexts are installed separately, so moving it to `dev:preview` is better for now - this was motivated by a build failing on one of my branches because `previewctl install-context timed out in Werft`.
No issue, follow up on https://github.com/gitpod-io/gitpod/pull/14399
See job [herre](https://werft.gitpod-dev.com/job/gitpod-build-mads-move-install-context-to-in-workspace-scr.1)
```sh
werft job run github -a with-preview=true
```
```release-note
NONE
```
N/A
=> Move previewctl install-context to `leeway run dev:preview`

operations/observability/mixins/IDE/dashboards/components/openvsx-mirror.json
Thread
|  Server latency  |  Client lantency  |
|---|---|
|  <img width="844" alt="image" src="https://user-images.githubusercontent.com/20944364/200764408-cdbd0db3-cf5e-4982-a70a-127b61ab6d4d.png"> |  <img width="822" alt="image" src="https://user-images.githubusercontent.com/20944364/200764353-b1439152-30ee-46d8-8bd3-555f9800eda0.png"> |
Fixes #
[Check here](https://grafana.gitpod.io/d/fYpeQ2vVk/openvsx-mirror-test?orgId=1&refresh=30s)
```release-note
NONE
```
=> [observability] add threads and latency charts

components/content-service-api/typescript/BUILD.yaml, components/content-service-api/typescript/package.json, components/gitpod-protocol/BUILD.yaml, components/server/src/code-sync/code-sync-service.ts, components/server/src/container-module.ts, components/server/src/storage/content-service-client.ts, components/server/src/util/content-service-sugar.ts, components/server/src/workspace/gitpod-server-impl.ts, components/server/src/workspace/headless-log-service.ts, components/usage-api/typescript/BUILD.yaml
Moves `sugar.ts` into server, which is the only user of those definitions. This removes the dependency of `content-service` on `gitpod-protocol`
Removes publish step for `usage-api`, we don't need to publish these definitions to NPM anyway. This removes the dependency on `gitpod-protocol` which contains the publishing scripts.
Fixes #
CI passes
```release-note
NONE
```
=> [server] Break dependency of content-service on gitpod-protocol, and usage-api on gitpod-protocol

components/openvsx-proxy/pkg/errorhandler.go, components/openvsx-proxy/pkg/handler.go, components/openvsx-proxy/pkg/modifyresponse.go, components/openvsx-proxy/pkg/prometheus.go
We produce to many useless logs in OpenVSX proxy for each request. Instead let's use debug by default and if we need more verbose logging we can enable it via configmap log level option.
Fixes #
```release-note
NONE
```
=> [openvsx-proxy] switch to debug instead of info

dev/preview/workflow/preview/deploy-gitpod.sh, install/installer/cmd/testdata/render/aws-setup/output.golden, install/installer/cmd/testdata/render/azure-setup/output.golden, install/installer/cmd/testdata/render/customization/output.golden, install/installer/cmd/testdata/render/external-registry/output.golden, install/installer/cmd/testdata/render/gcp-setup/output.golden, install/installer/cmd/testdata/render/http-proxy/output.golden, install/installer/cmd/testdata/render/insecure-s3-setup/output.golden, install/installer/cmd/testdata/render/minimal/output.golden, install/installer/cmd/testdata/render/shortname/output.golden, install/installer/cmd/testdata/render/statefulset-customization/output.golden, install/installer/cmd/testdata/render/use-pod-security-policies/output.golden, install/installer/cmd/testdata/render/workspace-requests-limits/output.golden, install/installer/pkg/components/public-api-server/configmap_test.go, install/installer/pkg/components/public-api-server/deployment.go, install/installer/pkg/components/public-api-server/deployment_test.go, install/installer/pkg/components/public-api-server/networkpolicy_test.go, install/installer/pkg/components/public-api-server/objects.go, install/installer/pkg/components/public-api-server/objects_test.go, install/installer/pkg/config/v1/experimental/experimental.go
This change will result in the Public API deployment, service, config and role bindings being deployed without requiring experimental configuration to be specified. This effectively results in all installations having the Public API deployed.
Fixes #
```release-note
[public-api] Deploy API server in all installations
```
=> [installer] Deploy Public API without experimental config

components/dashboard/src/teams/TeamSettings.tsx, components/gitpod-protocol/src/gitpod-service.ts, components/server/src/workspace/gitpod-server-impl.ts
It doesn't seem to be needed at all, and it doesn't really make sense anyway.
Fixes #
1. Preview
2. Create team
3. Delete team
```release-note
NONE
```
=> [server] Remove userId from deleteTeam() rpc

components/gitpod-cli/cmd/ports-await.go, components/supervisor/pkg/ports/served-ports.go
Enable error log `error while observing served ports` in scenarios when only IPV4 or IPV6 are available
fixes https://github.com/gitpod-io/gitpod/issues/14556
- Check if IPV4 or IPV6 is not available
- Check workspace logs
```release-note
NONE
```
=> [supervisor] Only poll supported protocols

components/server/ee/src/workspace/gitpod-server-impl.ts, components/server/ee/src/workspace/snapshot-service.ts, components/ws-manager-api/go/mock/mock.go, components/ws-manager-api/typescript/src/core_grpc_pb.d.ts, components/ws-manager-api/typescript/src/core_grpc_pb.js, components/ws-manager-api/typescript/src/core_pb.d.ts, components/ws-manager-api/typescript/src/core_pb.js, components/ws-manager-api/typescript/src/promisified-client.ts
Adds the server part to https://github.com/gitpod-io/gitpod/pull/14374
contributes to #14159
1) Enable PVC 
2) start workspace 
3) take snapshot
4) start snapshot
```release-note
NONE
```
=> [server] snapshots for PVC workspaces

components/ide/jetbrains/backend-plugin/gradle-latest.properties
This PR updates the Platform Version from JetBrains Backend Plugin to the latest version.
```release-note
NONE
```
_This PR was created automatically with GitHub Actions using [this](https://github.com/gitpod-io/gitpod/blob/main/.github/workflows/jetbrains-update-plugin-platform-template.yml) template._
=> [JetBrains] Update Platform Version from JetBrains Backend Plugin

components/image-builder-mk3/pkg/orchestrator/orchestrator.go
Increment the `gitpod_image_builder_builds_done_total` counter when the image builder completes a build.
This metric was already configured and registered but never used.
Part of https://github.com/gitpod-io/gitpod/issues/12960
* Port forward to the image builder in the preview environment (`kubectl port-forward svc/gitpod-image-builder-mk3 9500:9500`)
* Hit the metrics endpoint (`:9500/metrics`).
* Trigger an image build.
* See the `gitpod_image_builder_builds_done_total` counter increase on completion, with the appropriate label on success or failure.
```release-note
NONE
```
=> [image-builder] Increment metric on build completions

components/ws-manager/pkg/manager/create.go
Context: https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/#allow-users-to-skip-recursive-permission-changes-on-mount
Might improve workspace opening times in some scenarios.
Fixes #
```release-note
none
```
=> [pvc] set FSGroupChangePolicy
