- WORKSPACE.yaml
Update code to `1.73.1`
```release-note
NONE
```
> Update code insiders to 1.73.1

- .werft/observability/manifests/monitoring-satellite.yaml
In https://github.com/gitpod-io/gitpod/pull/13850, we split workspace alerts into 2 different folders but forgot to update their paths in the configuration used for previews.
This PR fixes the import pathes.
Fixes #
```release-note
NONE
```
> Fix workspace alerts path

- components/dashboard/src/teams/TeamSettings.tsx
Use DeleteTeam from PublicAPI (implemented in https://github.com/gitpod-io/gitpod/pull/14573) when deleting teams
* Depends on https://github.com/gitpod-io/gitpod/pull/14573
1. Preview
2. Create team
3. Delete team
```release-note
NONE
```
> [dashboard] Use PublicAPI to DeleteTeam

- operations/observability/mixins/meta/rules/public-api.yaml
Looks like it is a copy-paste mistake 😛 
The resource name conflicts with [this one](https://github.com/gitpod-io/gitpod/blob/9a3afd75377ba2aa4af354a7d047a050643bd1cc/operations/observability/mixins/meta/rules/server.yaml#L11)
```release-note
NONE
```
> Fix conflicting PrometheusRules

- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
Updates the stable image of VS Code Browser to `1.73.1` (https://github.com/microsoft/vscode/releases/tag/1.73.1)
A part of https://github.com/gitpod-io/gitpod/issues/14272
Open the preview environment, select VS Code Browser (non-`latest`) and in the <kbd>About</kbd> dialog check that we are on `1.73.1`.
```release-note
NONE
```
> Update stable to `1.73.1`

- .github/CODEOWNERS
- .github/workflows/jetbrains-update-plugin-platform-template.yml
- Auto-approve also PRs related to EAP Gateway Plugin updates.
- Also label the created PR with "[editor: jetbrains](https://github.com/gitpod-io/gitpod/labels/editor%3A%20jetbrains)".
- Remove Code Owner from `/components/ide/jetbrains/gateway-plugin/gradle-latest.properties`
- No need to test.
- Check how auto-approval worked for the Backend Plugin: https://github.com/gitpod-io/gitpod/pull/14583
```release-note
NONE
```
> [JetBrains] Auto-approve also EAP Gateway Plugin updates

- .github/workflows/jetbrains-update-plugin-platform-template.yml
In my [last PR](https://github.com/gitpod-io/gitpod/pull/14584), I didn't notice that an additional step was required to check and approve the PR created for Gateway Plugin.
For this reason, the _Auto Approve_ step was skipped (see [here](https://github.com/gitpod-io/gitpod/actions/runs/3438249496/jobs/5734064215)).
This PR fixes it.
- https://github.com/gitpod-io/gitpod/pull/14584
Check the step added in the code changes. Check also the ID of both changed steps.
```release-note
NONE
```
> [JetBrains] Add a step to check and approve the PR created for Gateway Plugin

- components/ws-manager/cmd/run.go
- components/ws-manager/pkg/manager/pod_controller.go
For some reason, we are not currently monitoring for events of pod erasure, i.e., workspace deletion. This prevents the ws-manager subscriber from sending the event that the workspace is stopped. This is the fix for that.
Part of https://github.com/gitpod-io/gitpod/issues/13197
Run the integration test and log subscribe log
(Later I will give a PR about the integration test that contains code that will not work without this modification)
```release-note
None
```
> ws-manager: Monitor a event about deleting a pod

- components/server/src/workspace/workspace-starter.ts
https://github.com/gitpod-io/gitpod/pull/14296 added a `gitpod_server_image_builds_completed_total` counter metric, but the metric's "failed" dimension was incorrectly incremented when an image build failed for user errors, rather than just for system errors as intended. 
This PR excludes image build failures that look like they were due to user error from the metric.
Part of https://github.com/gitpod-io/gitpod/issues/12960.
```release-note
NONE
```
> [server] Don't count user errors in failed image builds metrics

- components/server/ee/src/workspace/gitpod-server-impl.ts
The current logic when `allowUsingPreviousPrebuilds` was enabled would always use a previous prebuild because the history doesn't look at the current commit. 
This change makes it so that the previous prebuild logic only is used when there is no prebuild for the current commit.
Fixes #
You can test it by 
- creating a project 
- pushing two commits on the same branch so that both commits get prebuilds
- enable the project setting for `allowUsingPreviousPrebuilds`
- start a workspace on the branch and verify that it in fact starts with a full prebuild and the init task doesn't run.
```release-note
NONE
```
> fix incremental workspaces

- dev/preview/workflow/preview/build.sh
- dev/preview/workflow/preview/deploy-gitpod.sh
This PR changes `leeway run dev:preview` and related scripts such that we produce a new unique `version` every time.
Fixes https://github.com/gitpod-io/gitpod/issues/14474
Part of https://github.com/gitpod-io/ops/issues/5747
The happy path (in workspace)
```sh
```
Verifying that we handle the case where people directly invoke `leeway run dev/preview:deploy-gitpod` in a workspace where they haven't yet built it.
```
rm -f /tmp/local-dev-version
leeway run dev/preview:deploy-gitpod
ERROR: VERSION is not set and no fallback version exists in /tmp/local-dev-version.
INFO: Please run leeway run dev/preview:build or set VERSION
```
And a quick test that this didn't break Werft ([job](https://werft.gitpod-dev.com/job/gitpod-build-mads-hartmann-build-sh-should-bump-14474.1)) …
> Building locally will produce a unique version every time

- components/ide/jetbrains/backend-plugin/launch-dev-server.sh
Fix JDWP error "_transport error 202: socket creation failed: Address family not supported by protocol_" by setting an IPv4 address.
Error details:
```
Picked up JAVA_TOOL_OPTIONS:  -Xmx12884m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:44444
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
ERROR: transport error 202: socket creation failed: Address family not supported by protocol
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c:734]
```
See [internal discussion](https://gitpod.slack.com/archives/C02CBKZEVS8/p1668175666969379).
- Open the branch of this PR in …
> [JetBrains] Fix JDWP error triggered when running `launch-dev-server.sh`

- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/server/server.go
This wires up TokensService with the public API.
Relates #14602
```release-note
NONE
```
> [public api] Wire up UnimplementedTokensService

- .werft/build.yaml
- test/tests/ide/jetbrains/gateway_test.go
[integration-test] support jetbrains integration test in build job
Fixes #
see this werft job, it can start jetbrains integration test https://werft.gitpod-dev.com/job/gitpod-custom-pd-inte.1
```release-note
NONE
```
> [integration-test] support jetbrains integration test in build job

- operations/observability/mixins/IDE/rules/vscode.yaml
[observability] add vscode install extension failure alert rule
Fixes #
```release-note
NONE
```
> [observability] add vscode install extension failure alert rule

- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortForwardingServiceImpl.kt
In https://github.com/gitpod-io/gitpod/pull/14408 I forgot to add the loop which restarts the observation on Ports from the Supervisor in case of an exception in the Supervisor (e.g. momentaneous connection loss). This PR fixes it. Besides that, it now uses a coroutine instead of a thread for it.
- https://github.com/gitpod-io/gitpod/pull/14408
I'm unsure about how it can be tested. It would need to have an error or disconnection from Supervisor's side.
But you can verify that ports are being forwarded automatically and are being displayed in the Ports View. It shows the service continues working as expected.
```release-note
NONE
```
> [JetBains] Fix to continuously observe ports while Gitpod Port Forwarding Service is active

- components/ws-manager/pkg/manager/monitor.go
- components/ws-manager/pkg/manager/probe.go
Disable KeepAlive in dial configuration and reduce timeouts.
- Workspaces should open without issues
- Integration tests must pass
- 
```release-note
NONE
```
> [ws-manager] Adjust probe timeouts and refactor probe map

- .github/workflows/jetbrains-update-backend-latest.yml
- .gitpod.yml
- .werft/aks-installer-tests.yaml
- .werft/build.yaml
- .werft/cleanup-installer-tests.yaml
- .werft/debug.yaml
- .werft/eks-installer-tests.yaml
- .werft/gke-installer-tests.yaml
- .werft/ide-integration-tests-startup.yaml
- .werft/jobs/build/build-and-publish.ts
- .werft/jobs/build/job-config.ts
- .werft/jobs/build/prepare.ts
- .werft/k3s-installer-tests.yaml
- .werft/platform-delete-preview-environment.ts
- .werft/platform-delete-preview-environment.yaml
- .werft/platform-delete-preview-environments-cron.yaml
- .werft/platform-trigger-artificial-job.yaml
- .werft/platform-trigger-werft-cleanup.yaml
- .werft/workspace-run-integration-tests.yaml
- components/supervisor/hot-deploy.sh
- dev/image/Dockerfile
- dev/preview/BUILD.yaml
- dev/preview/workflow/preview/build.sh
Required for: https://github.com/gitpod-io/gitpod/pull/14524
```release-note
NONE
```
> Update base image and leeway

- components/gitpod-cli/cmd/ports.go
- components/gitpod-cli/cmd/tasks.go
Running unknown subcommands of `ports` and `tasks` would not return any output which is an odd and confusing behaviour.
The reason being that the helper is only triggered when there are no args. Unknown subcommands that don't match registered subcommands are considered arguments and the helper is only displayed when there are no arguments.
Fixes #
1. Start a workspace 
2. Run `gp ports XXX` observe how the helper and an error are displayed
3. Run `gp ports list` to make sure subcommands continue to work
4. Run `gp tasks XXX` observe how the helper and an error are displayed
5. Run `gp tasks list` to make sure subcommands continue to work
```release-note
[Gitpod CLI] Display helper for unknown subcommands
``` …
> [Gitpod CLI] Display helper for unknown subcommands

- test/pkg/agent/daemon/main.go
- test/pkg/agent/workspace/main.go
- test/pkg/integration/agent.go
- test/pkg/integration/apis.go
- test/pkg/integration/cgroup.go
- test/pkg/integration/common/port_forward.go
- test/pkg/integration/git-client.go
- test/pkg/integration/integration.go
- test/pkg/integration/workspace.go
- test/run.sh
- test/tests/components/server/server_test.go
- test/tests/components/ws-manager/additional_repositories_test.go
- test/tests/components/ws-manager/content_test.go
- test/tests/components/ws-manager/dotfiles_test.go
- test/tests/components/ws-manager/multi_repo_test.go
- test/tests/components/ws-manager/prebuild_test.go
- test/tests/components/ws-manager/protected_secrets_test.go
- test/tests/components/ws-manager/tasks_test.go
- test/tests/components/ws-manager/wsmanager_test.go
- test/tests/ide/vscode/python_ws_test.go
- test/tests/workspace/cgroup_v2_test.go
- test/tests/workspace/contexts_test.go
- test/tests/workspace/docker_test.go
- test/tests/workspace/example_test.go
- test/tests/workspace/git_hooks_test.go
- test/tests/workspace/git_test.go
- test/tests/workspace/k3s_test.go
- test/tests/workspace/mount_proc_test.go
Enables workspace integration tests to run in parallel. As a result of these improvements, the test takes about 20 minutes for large-vm and less than 30 minutes for regular vm.
To this end, I have done the following.
- Add the API for shutdown in the integration agent to be able to retry
- Run the test to restart ws-manager separately
- Make the parts that communicate with ws-manager, especially the part that monitors workspace status, less fragile
Fixes [13197](https://github.com/gitpod-io/gitpod/issues/13197)
```console
$ run.sh workspace
```
```release-note
NONE
```
Sorry for this too big PR :bow:  There should be no major changes in each test case; review specifically under `pkg/`.
> test: Enables workspace integration tests to run in parallel

- components/dashboard/src/components/UsageBasedBillingConfig.tsx
Adjusts the link from billing to pass the cycle start and end dates when opening the usage view.
Fixes #
Go to billing and click the button "View Usage"
Verify that the usage view shows usage for the current billing cycle.
```release-note
NONE
```
> [usage] open usage for cycle

- components/supervisor/cmd/init.go
[supervisor] don't swallow supervisor exit error
Fixes #14293 
Open https://github.com/mustard-mh/test/tree/hw/test-alpine in preview environment, it should failed with a message
```release-note
[supervisor] don't swallow supervisor exit error
```
> [supervisor] don't swallow supervisor exit error

- components/dashboard/src/Menu.tsx
- components/dashboard/src/settings/settings-menu.ts
- components/dashboard/src/settings/settings.routes.ts
Moves personal `usage` action from settings to to avatar context menu:
Fixes #14636
```release-note
NONE
```
> [dashboard] usage in avatar menu

- components/common-go/experiments/configcat.go
- components/common-go/experiments/types.go
- components/openvsx-proxy/go.mod
- components/openvsx-proxy/go.sum
- components/openvsx-proxy/pkg/config.go
- components/openvsx-proxy/pkg/errorhandler.go
- components/openvsx-proxy/pkg/handler.go
- components/openvsx-proxy/pkg/modifyresponse.go
- components/openvsx-proxy/pkg/openvsxproxy_test.go
- components/openvsx-proxy/pkg/run.go
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/go.mod
- install/installer/go.sum
- install/installer/pkg/components/openvsx-proxy/configmap.go
- install/installer/pkg/components/openvsx-proxy/statefulset.go
[openvsx-proxy] support dynamic upstream url, and support disabled cache
Fixes #
1. start a workspace in this preview environment, and change configcat `openvsx_proxy_upstream` to like 
`vscode_client_id` contain `insider` -> our mirror openvsx-proxy
other -> `https://open-vsx.org`
2. check the log, if upstream is our mirror, it should never hit the cache
3. use `EDITOR='code --wait' kubectl edit statusfulset openvsx-proxy`, to remove environment variable `CONFIGCAT_SDK_KEY`
4. check everything still can work, i.e. it should always using open-vsx.org as upstream, self-hosted should have no effect
if you see request in chrome dev tool, if there has response header `Via: 1.1 google` it using our mirror
```release-note
NONE
``` …
> [openvsx-proxy] support dynamic upstream url, and support disabled cache

- .github/workflows/code-nightly.yml
- .github/workflows/jetbrains-auto-update-template.yml
- .github/workflows/jetbrains-integration-test.yml
- .github/workflows/jetbrains-update-backend-latest.yml
- .gitpod.yml
- .werft/aks-installer-tests.yaml
- .werft/build.yaml
- .werft/cleanup-installer-tests.yaml
- .werft/debug.yaml
- .werft/eks-installer-tests.yaml
- .werft/gke-installer-tests.yaml
- .werft/ide-integration-tests-startup.yaml
- .werft/k3s-installer-tests.yaml
- .werft/platform-delete-preview-environment.yaml
- .werft/platform-delete-preview-environments-cron.yaml
- .werft/platform-trigger-artificial-job.yaml
- .werft/platform-trigger-werft-cleanup.yaml
- .werft/workspace-run-integration-tests.yaml
- dev/image/Dockerfile
Fix leeway error building provenance sha256 hash 
xref: https://github.com/gitpod-io/gitpod/pull/14524
- Open `https://gitpod.io/#https://github.com/gitpod-io/gitpod/pull/14524`
- In a terminal update leeway running `wget https://github.com/gitpod-io/leeway/releases/download/v0.4.1/leeway_0.4.1_Linux_x86_64.tar.gz && tar zxpvf leeway_0.4.1_Linux_x86_64.tar.gz`
- Run the failing task `./leeway build components/ide/jetbrains/image:download-rider-latest`
```release-note
NONE
```
> Update leeway to v0.4.1

- components/ee/db-sync/src/export.ts
- components/ee/db-sync/src/replication.ts
This intended to be a small and pragmatic fix to db-sync to make it more reliable before we can retire it completely.
Before, it would always sync from ´[previousRun, ...now`. Also, it was using the local processes clock, which is obviously out-of-sync with the DB's.
This PR addresses this by:
- introducing an upperBound of "now - 5s" for SyncPeriods
- use the DB's clock to establish that SyncPeriod
- (fix a minor comparison error in export.ts which made us double-sync on millisecond matches)
Fixes #14560 
- `leeway build components/gitpod-db:dbtest-init`
- `(components/ee/db-sync && yarn db-test)`
```release-note
NONE
```
> [db-sync] Introduce SyncPeriod (with upper limit now - 5s)

- install/tests/Makefile
When interacting with clusters created by the CI pipelines it may be necessary to manually configure the gitpod configuration and run the `kots-install` make target. This commit adds some documentation for the steps needed to initialize the GitHub SCM integration outside of a werft job or CI run.
This assumes that you have a cluster running but gitpod is not installed.
```bash
export cloud=gcp
export DOMAIN="tests.gitpod-self-hosted.com"
export GCP_ZONE="europe-west1-d"
export TF_VAR_TEST_ID="some-lovely-cluster-name"
make get-github-config generate-kots-config install-kots
```
```release-note
NONE
```
> [install/tests] Document integration test scm setup steps

- install/tests/Makefile
The `generate-kots-config` target depended on the `tf-init` and `tf-output` targets,  but this was only used for external Gitpod dependencies. When using an in-cluster installation this init is not necessary; having `generate-kots-config` perform the lookup when unneeded makes the incluster setup more cumbersome than necessary. This commit pushes the makefile dependency down to the targets that actually consume terraform outputs.
gcloud configuration:
```json
gcloud config list --format=json
{
"compute": {
"region": "europe-west1",
"zone": "europe-west1-b"
},
"core": {
"account": "user-gp-sje-instaly-gcp@sh-automated-tests.iam.gserviceaccount.com",
"disable_usage_reporting": "True",
"project": "sh-automated-tests"
}
}
```
Setup steps:
```bash
export TF_VAR_TEST_ID=sje-instaly-gcp
export …
```
> [installer-tests] Only initialize terraform when needed for kots config

- components/supervisor/cmd/init.go
this is a follow up for #14650, we ignore all signal error, include `signal: terminal`, `signal: kill` ... to get rid of some noise
Fixes #
```release-note
NONE
```
> [supervisor] ignore all signal error

- .werft/jobs/build/installer/post-process.sh
Enable ws-daemon cpu limiting in preview environments so that it does not have to be manually activated every time when someone wants to work on cpu limiting
n.a.
1. generate a config like so: ./installer init > config.yaml
2. generate a k8s manifest like so: ./installer render -n $(kubens -c) -c config.yaml > k8s.yaml
3. fake a license and feature file like so: echo "foo" > /tmp/license && echo '"bar"' > /tmp/defaultFeatureFlags
4. call this script like so: ./.werft/jobs/build/installer/post-process.sh 1234 5678 2 your-branch-just-dashes
```release-note
None
```
> [preview] Enable ws-daemon cpu limiting

- components/ws-manager/pkg/manager/create.go
Since we are now using init container to fix `/workspace` ownership, there is no need to mess with fsGroup anymore and it prevents k8s from running chown behind the scenes when mounting PVC. (so it would mount pvc faster).
Fixes #
```release-note
none
```
> [pvc] remove fsgroup

- components/image-builder-mk3/go.mod
- components/image-builder-mk3/go.sum
- components/image-builder-mk3/pkg/auth/auth.go
- components/registry-facade/cmd/run.go
ECR requires regular secret rotation. This PR adds live-reloading of the authentication credentials used to pull/push from the Gitpod image registry.
Works towards #12104
1. Make sure your installation uses an external registry (not the built-in one)
2. Start a workspace to ensure the image build works
3. Change the external registry's authentication secret
4. Start a new workspace to see the effect of the auth change
```release-note
NONE
```
> [image-builds] Dynamically reload auth config

- components/ws-manager/pkg/manager/create.go
- components/ws-manager/pkg/manager/testdata/cdwp_admission.golden
- components/ws-manager/pkg/manager/testdata/cdwp_affinity.golden
- components/ws-manager/pkg/manager/testdata/cdwp_class.golden
- components/ws-manager/pkg/manager/testdata/cdwp_class_notfound.golden
- components/ws-manager/pkg/manager/testdata/cdwp_customcerts.golden
- components/ws-manager/pkg/manager/testdata/cdwp_debug_workspace_pod.golden
- components/ws-manager/pkg/manager/testdata/cdwp_empty_resource_req.golden
- components/ws-manager/pkg/manager/testdata/cdwp_envvars.golden
- components/ws-manager/pkg/manager/testdata/cdwp_fullworkspacebackup.golden
- components/ws-manager/pkg/manager/testdata/cdwp_imagebuild.golden
- components/ws-manager/pkg/manager/testdata/cdwp_imagebuild_template.golden
- components/ws-manager/pkg/manager/testdata/cdwp_no_ideimage.golden
- components/ws-manager/pkg/manager/testdata/cdwp_prebuild.golden
- components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template.golden
- components/ws-manager/pkg/manager/testdata/cdwp_prebuild_template_override_resources.golden
- components/ws-manager/pkg/manager/testdata/cdwp_readinessprobe.golden
- components/ws-manager/pkg/manager/testdata/cdwp_secrets.golden
- components/ws-manager/pkg/manager/testdata/cdwp_sshkeys.golden
- components/ws-manager/pkg/manager/testdata/cdwp_sys_envvars.golden
- components/ws-manager/pkg/manager/testdata/cdwp_tasks.golden
- components/ws-manager/pkg/manager/testdata/cdwp_template.golden
- components/ws-manager/pkg/manager/testdata/cdwp_timeout.golden
- components/ws-manager/pkg/manager/testdata/cdwp_userns.golden
- components/ws-manager/pkg/manager/testdata/cdwp_with_ephemeral_storage.golden
- components/ws-manager/pkg/manager/testdata/cdwp_withaffinity_regular.golden
- components/ws-manager/pkg/manager/testdata/cdwp_withaffinityheadless.golden
By default, pod accepts SIGKILL 30 seconds after receiving SIGTERM.
This means that workspace processes must be processed for termination within 30 seconds.
This may be too short for large software such as dockerd, which will clean up the overlay directory and other files when it receives a SIGTERM. (maybe)
https://github.com/moby/moby/blob/0910306bf970603ce787466a98e4294ba81af841/cmd/dockerd/trap/trap.go#L41
If the cleanup is not done in time within 30 seconds, the container's overlay directory will remain uncluttered and causes https://github.com/gitpod-io/gitpod/issues/11183
Therefore, set this to 3 minutes, which gives you a little more time. There is currently no basis for this number, so we are looking for great ideas.
Mitigation https://github.com/gitpod-io/gitpod/issues/11183 …
> ws-manager: Allow extra time for workspace to receive SIGKILL

- components/gitpod-protocol/go/gitpod-service.go
- components/gitpod-protocol/go/mock.go
Add Project APIs to Golang bindings for server, such that they can be used from public-api.
* Relates to https://github.com/gitpod-io/gitpod/issues/14606
CI builds
```release-note
NONE
```
> [gitpod-protocol] Add project APIs to Golang client

- dev/BUILD.yaml
Fixes #
```release-note
NONE
```
> Don't require input for tf when running `leeway dev:preview`

- dev/BUILD.yaml
Ask for `gcloud login` at the beginning of the build. This login is required in the middle of the build. Asking at the beginning prevents surprises when people start the build, background the Gitpod workspace, and then come back to it later only to be surprised that the build was waiting for input. 
Fixes #
a) Run `leeway run dev:preview` on a fresh workspace. 
b) Logout via `rm -rf ~/.config/gcloud/` and run `leeway run dev:preview`
```release-note
NONE
```
> Ask for gcloud login at the beginning of the build

- components/ide/jetbrains/image/hot-deploy.sh
- components/ide/jetbrains/image/status/main.go
Fixes #
- Configure IntelliJ
- Start a workspace on https://github.com/akosyakov/parcel-demo/tree/jb-proxy-test
- Check that proxy settings are configured in the settings view of marketplace for the host.
- That jap buddy plugin is installed already.
- Also you can check output of tinyproxy running in the terminal.
```release-note
[JetBrains] Preconfigure global settings for JB backend.
```
> [jb] sync initial options

- components/common-go/experiments/flags.go
- components/public-api-server/go.mod
- components/public-api-server/go.sum
- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/apiv1/tokens_test.go
- components/public-api-server/pkg/server/integration_test.go
- components/public-api-server/pkg/server/server.go
- Makes feature flag available to the Tokens Service
- Use it in CreatePersonalAccessToken RPC
Relates #14602
Unit tests:
In `/components/public-api-server/pkg/apiv1` run `go test .`
Note: This test currently tests the path where someone is not feature-flagged.
```release-note
NONE
```
> [public api] Use personal access tokens feature flag in Tokens Service

- components/gitpod-db/src/typeorm/auth-code-repository-db.ts
Debugging https://github.com/gitpod-io/gitpod/issues/14464
```release-note
NONE
```
> [server] add logs to debug persistence error with userId

- components/openvsx-proxy/pkg/errorhandler.go
- components/openvsx-proxy/pkg/modifyresponse.go
For _Status Code of Request_ [[1]](https://grafana.gitpod.io/d/HNOvmGpxgd/openvsx-proxy?orgId=1&refresh=5s&from=now-1h&to=now&viewPanel=4)
Fixes #
- Make sure extensions related things not broken (install, uninstall, search)
```release-note
NONE
```
> [openvsx-proxy] re-enable requests_total metric

- components/common-go/experiments/flags.go
- components/public-api-server/pkg/apiv1/tokens_test.go
Ensures we have coverage for both cases of the feature flag. Currently returns unimplemented, but will be extended in future PRs.
Fixes #
```release-note
NONE
```
> [public-api] Add test for CreateToken when feature flag enabled

- operations/observability/mixins/self-hosted/rules/pyrra/service.yaml
- operations/observability/mixins/self-hosted/rules/pyrra/servicemonitor.yaml
We recently added an SLO for Pyrra itself, but we've noticed that [we're not collecting the necessary metrics yet](https://pyrra.gitpod.io/objectives?expr={__name__=%22pyrra-reconciliations%22,%20namespace=%22monitoring-central%22,%20team=%22delivery-operations-experience%22}&grouping={}&from=1668433035343&to=1668436635343) (Notice the `No data` in the dashboards). This PR creates the necessary resources to collect those metrics.
https://github.com/gitpod-io/ops/pull/6726 will deploy them into the monitoring-central cluster
Fixes #
You can manually deploy those resources to our monitoring-central cluster and notice that we'll start collecting metrics from Pyrra.
```release-note
NONE
``` …
> Create resources to monitor Pyrra

- operations/observability/mixins/IDE/rules/opensvx.yaml
Alert when using openvsx-mirror and upstream is down
See also [Grafana Explore](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%28rate%28http_client_requests_seconds_count%7Bcluster%3D%5C%22openvsx-mirror-us01%5C%22,outcome%21~%5C%22SUCCESS%7CREDIRECTION%7CCLIENT_ERROR%5C%22%7D%29%5B2m%5D%29%2Fsum%28rate%28http_client_requests_seconds_count%7Bcluster%3D%5C%22openvsx-mirror-us01%5C%22%7D%29%5B2m%5D%29%20%3E%200.01%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D)
- Runbooks PR …
> [observability] add alert for upstream down

- components/gitpod-db/src/typeorm/migration/1668531007092-CreatePersonalAccessTokenTable.ts
Creates `d_b_personal_access_token` with the following schema
-- | field | type
-- | -- | --
primary key | id | varchar
idx | user_id | varchar
idx | hash | varchar
  | name | varchar
  | description | text
  | scopes | text
  | expiration_time | timestamp
  | created_at | timestamp
idx | last_modified | timestamp
  | deleted | boolean
Part of #14602
1. Connect to the preview environment DB[[1](https://www.notion.so/gitpod/Accessing-the-database-242e9fa0fef642128380a10d800d3b99#cd03b2615336429aa11833c44bf4745c)] 
2. `describe d_b_personal_access_token;`
```release-note
NONE
```
> [db] Create d_b_personal_access_token

- components/dashboard/src/workspaces/WorkspaceEntry.tsx
Following up from https://github.com/gitpod-io/gitpod/pull/14393. this will fix the workspace download menu style so that the menu option looks disabled when using dark theme.
1. Open a new workspace
2. Go to the workspaces list
3. Click on the more actions button
4. Notice the _Download_ option looks disabled
|-|-|
| ![dropdown-before](https://user-images.githubusercontent.com/120486/202030741-56a6b3dd-f658-45c4-8d1b-9d606e527748.png) | ![dropdown-after](https://user-images.githubusercontent.com/120486/202030752-4d19767c-837e-4d4b-a60a-37f400f577b9.png) |
```release-note
Update workspace download menu style
```
> Update workspace download menu style

- .github/CODEOWNERS
Update the CODEOWNERS file for the new `slowserver` component added in https://github.com/gitpod-io/gitpod/pull/14671.
Part of #9198 
```release-note
NONE
```
> Update CODEOWNERS for the slowserver component

- install/installer/pkg/components/slowserver/deployment.go
- install/installer/pkg/components/slowserver/render_test.go
https://github.com/gitpod-io/gitpod/pull/14671 added a new `slow-server` deployment for experimenting with high-latency database connections.
This PR makes a couple of small changes to the `slow-server` deployment:
* Uses the same replica count as defined for the `server` deployment.
* Uses the same resources as defined for the `server` deployment.
Part of #9198 
Installer unit tests.
```release-note
NONE
```
> [installer] Have `slow-server` take replica count and resource limits from `server`

- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/apiv1/tokens_test.go
Basic stubs for Tokens Service. Does the following:
* Basic argument validation
* Fetches the user, and ensures the user is allowed to access the feature
* If allowed, returns Unimplemented.
* If not, returns PermissionDenied
* Part of https://github.com/gitpod-io/gitpod/issues/14280
* Depends on https://github.com/gitpod-io/gitpod/pull/14713
Unit tests
```release-note
NONE
```
/hold for dependency on https://github.com/gitpod-io/gitpod/pull/14713
> [public-api] Add Tokens RPC stubs

- components/gitpod-db/src/tables.ts
Enable dbsync for `d_b_personal_access_token`
Part of #14602
```release-note
NONE
```
> [public api] Enable dbsync for d_b_personal_access_token

- .werft/build.yaml
Optionally install leeway from git. This is helpful to test new versions of leeway before releasing them.
Fixes #
`werft run github -a leeway-from-git=true` from CI to bypass job protection.
```release-note
NONE
```
> Optionally consume Leeway from git

- components/common-go/db/types.go
- components/server/ee/src/user/stripe-service.ts
- components/usage/pkg/apiv1/usage.go
- components/usage/pkg/db/cost_center.go
- components/usage/pkg/db/cost_center_test.go
- components/usage/pkg/stripe/stripe.go
- components/usage/pkg/stripe/stripe_test.go
Fixes https://github.com/gitpod-io/gitpod/issues/14700
2. Upgrade that team to usage-based on Stripe by adding a payment method (e.g. 4242 4242 4242 4242, 4/24, 424)
3. Once active, the Billing UI should show the dates "(today) - (today + 1 month)"
a. It should **not** show "(first day of month)" or "(last day of month)" as was the case before
a. Hint: You can hover over the billing cycle dates to see the exact millisecond (both boundaries should be on the same second, one month apart)
```release-note
NONE
```
> [Usage-based] Untie paid Stripe subscriptions from calendar months

- dev/BUILD.yaml
- dev/preview/workflow/lib/git.sh
- dev/preview/workflow/preview/preview.sh
This PR ensures that `leeway run dev:preview` fails gracefully when executed from the main branch.
Fixes https://github.com/gitpod-io/gitpod/issues/14729
```sh
git checkout mads/no-dev-preview-on-main
git checkout main
git merge mads/no-dev-preview-on-main
```
```release-note
NONE
```
N/A
> Fail gracefully when executed from main

- dev/preview/workflow/preview/deploy-gitpod.sh
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/usage/configmap.go
- install/installer/pkg/components/usage/configmap_test.go
- install/installer/pkg/components/usage/objects.go
- install/installer/pkg/components/usage/objects_test.go
- install/installer/pkg/config/v1/experimental/experimental.go
This PR will deploy the usage component by default in all installations.
It uses the following defaults:
* Usage Ledger schedule - 15m
* Reset Usage schedule - 15m
* WorkspaceClass Credit cost - default: 0.1666666667
* No Stripe API Key, No Stripe prices
* This will effectively disable stripe integration, and the BillingService
Related to https://github.com/gitpod-io/gitpod/issues/14129
Usage component is deployed in preview
```release-note
NONE
```
> [usage] Deploy usage by default

- WORKSPACE.yaml
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
Fixes https://github.com/gitpod-io/gitpod/issues/14714
1. Select vscode web stable
2. Open a workspace
3. Open `gitpod.yml` file with vscode extensions configured
4. Check there's no misleading error telling extension is not in marketplace
```release-note
NONE
```
> [code] Update code

- .gitpod.yml
- .werft/aks-installer-tests.yaml
- .werft/build.yaml
- .werft/cleanup-installer-tests.yaml
- .werft/debug.yaml
- .werft/eks-installer-tests.yaml
- .werft/gke-installer-tests.yaml
- .werft/ide-integration-tests-startup.yaml
- .werft/k3s-installer-tests.yaml
- .werft/platform-delete-preview-environment.yaml
- .werft/platform-delete-preview-environments-cron.yaml
- .werft/platform-trigger-artificial-job.yaml
- .werft/platform-trigger-werft-cleanup.yaml
- .werft/workspace-run-integration-tests.yaml
- dev/image/Dockerfile
Fixes https://github.com/gitpod-io/leeway/pull/119
```release-note
NONE
```
> Update leeway to v0.5.1 and docker images

- dev/preview/workflow/lib/common.sh
- dev/preview/workflow/lib/git.sh
- dev/preview/workflow/preview/preview.sh
Log a warning if the active branch doesn't exist on GitHub.
Fixes https://github.com/gitpod-io/gitpod/issues/14734
```
$ leeway run dev:preview
WARN: Your branch doesn't exist on GitHub. Your preview environment might get garbage collected at any time. To avoid this please push your branch.
$ git push -u origin mads/log-warnning-when-branch-isnt-pushed
$ leeway run dev:preview
```
```release-note
NONE
```
N/A
> Log a warning if branch isn't pushed

- components/ide/jetbrains/image/gha-update-image/index.js
Fix Github Action to search for a Build Artifact when updating the Stable Backend Plugin SDK
Because in https://www.jetbrains.com/intellij-repository/snapshots they only list artifacts which _ID_ is _BUILD_.
| | |
| --- | --- |
| <img width="275" alt="image" src="https://user-images.githubusercontent.com/418083/202172526-82df0439-7697-4fa1-908a-18d8854d0816.png"> | <img width="417" alt="image" src="https://user-images.githubusercontent.com/418083/202172435-d353d6d1-74e5-4928-9f76-f345e36c45ba.png"> |
- Fixes https://github.com/gitpod-io/gitpod/issues/14676
Checkout the branch of this PR and run the script manually to see the results.
```
$ node index.js 
All IDEs are in the same major version: 2022.2
{
majorVersion: '2022.2',
currentPlatformVersion: '222.4459-EAP-CANDIDATE-SNAPSHOT', …
```
> [JetBrains] Fix Github Action to search for a Build Artifact when updating the Stable Backend Plugin SDK

- components/dashboard/src/components/UsageBasedBillingConfig.tsx
- components/gitpod-protocol/BUILD.yaml
- components/gitpod-protocol/package.json
- components/gitpod-protocol/src/gitpod-service.ts
- components/gitpod-protocol/src/usage.ts
- components/server/ee/src/workspace/gitpod-server-impl.ts
- components/server/src/workspace/gitpod-server-impl.ts
The JSON-RPC protocol cannot handle JavaScript Date. This PR translates them to an iso string
Fixes #14743
```release-note
NONE
```
> [JSON-RPC] don't pass non-JSON data

- .github/workflows/jetbrains-update-plugin-platform-template.yml
- .github/workflows/jetbrains-update-plugin-platform.yml
Auto-update also the Stable Gateway Plugin.
References:
- [GitHub Actions Expressions: contains](https://docs.github.com/en/actions/learn-github-actions/expressions#contains)
- https://github.com/gitpod-io/gitpod/issues/13654
I've already run in, and you can see the results here: https://github.com/gitpod-io/gitpod/actions/runs/3480056231
The action created this PR: https://github.com/gitpod-io/gitpod/pull/14745 (note it didn't target the main branch, as it was a test.)
It was tested with the following steps:
1. Accessed https://github.com/gitpod-io/gitpod/actions/workflows/jetbrains-update-plugin-platform.yml
2. Ran the workflow targeting branch `felladrin/auto-update-stable-gateway-plugin`
```release-note
NONE
```
> [JetBrains] Auto-update also the Stable Gateway Plugin

- components/dashboard/src/service/public-api.ts
- components/dashboard/src/settings/PersonalAccessTokens.tsx
Currently there are no tokens created yet, but this change will at least start making that request to Pub API so that we can validate everything works as expected early.
The change is behind a feature flag, so should be risk-free to include in prod.
Fixes #
```release-note
NONE
```
> [dashboard] Extremely basic listing of Personal Access Tokens in the UI

- components/dashboard/src/start/StartWorkspace.tsx
In the past, the "Go to Dashboard" buttons on the "StartWorkspace" page always sent you to `/workspace`. This solved use-cases like "stop and delete workspace".
Because we recently changed the default page of the SPA to your current project (?), this is no longer the case, and when hitting that button, users are sent to the teams "Project Overview" page. This does not feel sensible, as there is no action for users to perform on that page that would make sense in that context.
This PR makes the mapping "Go to Dashboard" -> `/workspaces` explicit to restore the old behavior.
Fixes #
```release-note
fix 'Go to Dashboard' buttons on StartWorkspace
```
> [dashboard] StartWorkspace: Map "Go to Dashboard" to /workspaces (again)

- components/ide/jetbrains/backend-plugin/gradle.properties
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/optional/GitpodForceUpdateMavenProjectsActivity.kt
- components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/maven.xml
- components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
Currently, repositories using Maven Wrapper may fail to be loaded as a Maven Project if they are prebuilt with some specific file combination and then opened in JetBrains IntelliJ IDEA in Gitpod.
In summary:
- When you use a prebuild of a repository containing a `.xml` file inside `.idea` folder, it won't load the Maven Projects correctly.
_You can see this behaviour by [selecting Stable IntelliJ IDEA](https://gitpod.io/preferences) and starting a workspace from [this URL](https://gitpod.io/#prebuild/https://github.com/gitpod-io/spring-petclinic/tree/felladrin/prebuilt-maven-project-without-iml-file)._
- There's no problem if the repository has no `.idea` folder.
_You can see this behaviour by [selecting Stable IntelliJ IDEA](https://gitpod.io/preferences) and starting a workspace from …
> [JetBrains] Ensure prebuilt workspaces using Maven Wrapper are properly initialized in IntelliJ IDEA

- .werft/jobs/build/self-hosted-upgrade-tests.ts
- install/infra/modules/tools/external-dns/main.tf
This is a small PR that sets the flag `deleteOnFail` to the upgrade tests. This avoids the from scratch recreation if any failure occurs during the release tests.
I am also sneaking in a small change to the external-dns charts. It turns out that external-dns setup is failing everyday due to the wrong chart source. This fixes the issue.
Fixes #
From your workspace, run:
```
werft run github -j .werft/build.yaml -a with-sh-preview=true
```
```release-note
NONE
```
> [installer-tests] fix upgrade test behavior to not delete on failure

- .github/sync.yml
- .github/workflows/dashboard-sync.yml
To continue experiments with a monorepo for monitoring central, this Github Action will synchronize dashboards in gitpod-io/monitoring-central every time they change in gitpod-io/gitpod.
Docs for the action used can be seen here: https://github.com/marketplace/actions/repo-file-sync-action
Unfortunately, we need to merge it to main to be able to test 😓 
-->
```release-note
NONE
```
> Add GH Action to sync dashboards

- components/gitpod-protocol/go/gitpod-service.go
- components/supervisor/pkg/ports/ports-config.go
- components/supervisor/pkg/ports/ports-config_test.go
- components/supervisor/pkg/ports/ports.go
- components/supervisor/pkg/ports/ports_test.go
- Localify struct of ports sort - move sort property exists in supervisor only to address https://github.com/gitpod-io/gitpod/pull/13788#discussion_r1001082758
- Don't filter not served ports
- Add test cases for issue https://github.com/gitpod-io/gitpod/issues/14248 in case of regression
- Disable workspace config ports
Fixes https://github.com/gitpod-io/gitpod/issues/14248
- Follow PR https://github.com/gitpod-io/gitpod/pull/13788
- And check if functions of ports working
**Disable workspace config ports**
- Open workspace with ports already defined in .gitpod.yml
- Change order after workspace started
- Check if order align only with current `.gitpod.yml`
```release-note
Show not-served ports in gp-cli `ports` command, browser Ports view and desktop ExposedPorts view
```
If enabled …
> Improve ports respond in supervisor

- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/public-api-server/deployment.go
- install/installer/pkg/components/public-api-server/objects_test.go
Now that the public API server makes connections to the Gitpod database, it needs the same init container as other database-accessing components to ensure that that main container does not start before the database is available.
Fixes #
Preview environments for other branches show the `public-api-server` pod restarting several times before entering a `Running` state while it tries and fails to establish a database connection.
In the preview for this PR there are no restarts for the `public-api-server` pod.
```release-note
NONE
```
> [public-api-server] Add database waiter init container

- test/pkg/integration/workspace.go
- test/tests/components/ws-daemon/cpu_burst_test.go
> Fix workspace integration test suite and reduce log verbosity

- gitpod-ws.code-workspace
This adds previewctl to the VSCode workspace file. This means all the go tooling will now work as well as it does with all our other Go "modules".
No issue but was going to work on previewctl so thought I'd get this in first.
Open a workspace. Go to definition etc. should work now.
```release-note
NONE
```
N/A
> Add previewctl to code workspace

- components/ide/code/codehelper/main.go
- components/supervisor/pkg/supervisor/supervisor.go
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
Add logging for IDE startup (code browser)
See also [[internal chat]](https://gitpod.slack.com/archives/C01KGM9BH54/p1668757178295269?thread_ts=1668748433.738219&cid=C01KGM9BH54)
Fixes #
- Start workspace in prev env with latest code
- Check workspace log, should contains `phase start`
```release-note
NONE
```
> Add logging for code startup perf issues

- components/dashboard/src/projects/ProjectSettings.tsx
Fix the condition for when to show the select workspace class setting on projects
Fixes #14800
Create a project starting with "Gitpod" and verify that the setting is visible.
Create a project not starting with "Gitpod" and verify that the setting is not visible.
```release-note
NONE
```
> [dashboard] fix condition for workspace classes

- install/installer/cmd/testdata/render/vsxproxy-pvc/config.yaml
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/pkg/components/openvsx-proxy/statefulset.go
- install/installer/pkg/config/v1/config.go
Currently, OpenVSXProxy is the only non-optional component that needs PVC's to get things working. The usage of a PVC in AWS reference architecture, means that components can't get restarted in a different zone anymore as PVC's with EBS are specific to a zone.
As EKS reference architecture does not enable any other component that uses PVC's (i.e minio), This is a problem specific to `OpenVSXProxy`.
By disabling this, OpenVSXProxy's redis now will have lost the cache once a restart occurs which does not seems like a big deal for self-hosted customers.
Fixes https://github.com/gitpod-io/gitpod/issues/14529
```release-note
[openVSXProxy] Mark the usage of PVC optional
``` …
> [openVSXProxy] Mark the usage of PVC optional

- components/server/ee/src/user/stripe-service.ts
- components/server/ee/src/workspace/gitpod-server-impl.ts
- components/server/src/config.ts
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/server/configmap.go
- install/installer/pkg/components/server/constants.go
- install/installer/pkg/components/server/deployment.go
Removes feature flag (and false code-path) for creating subscription on usage.
Also removes reading of Stripe config in server, unused.
Fixes #
```release-note
NONE
```
> [server] Remove createSubscriptionOnUsage feature flag

- .gitpod.yml
- .werft/aks-installer-tests.yaml
- .werft/build.yaml
- .werft/cleanup-installer-tests.yaml
- .werft/debug.yaml
- .werft/eks-installer-tests.yaml
- .werft/gke-installer-tests.yaml
- .werft/ide-integration-tests-startup.yaml
- .werft/k3s-installer-tests.yaml
- .werft/platform-delete-preview-environment.yaml
- .werft/platform-delete-preview-environments-cron.yaml
- .werft/platform-trigger-artificial-job.yaml
- .werft/platform-trigger-werft-cleanup.yaml
- .werft/workspace-run-integration-tests.yaml
- dev/image/Dockerfile
Install [tmux](https://github.com/tmux/tmux) and  [tmuxinator](https://github.com/tmuxinator/tmuxinator) into the dev image.
```release-note
NONE
```
> [dev] Install `tmux` and  `tmuxinator` into the dev image

- .gitpod.yml
- .werft/aks-installer-tests.yaml
- .werft/build.yaml
- .werft/cleanup-installer-tests.yaml
- .werft/debug.yaml
- .werft/eks-installer-tests.yaml
- .werft/gke-installer-tests.yaml
- .werft/ide-integration-tests-startup.yaml
- .werft/k3s-installer-tests.yaml
- .werft/platform-delete-preview-environment.yaml
- .werft/platform-delete-preview-environments-cron.yaml
- .werft/platform-trigger-artificial-job.yaml
- .werft/platform-trigger-werft-cleanup.yaml
- .werft/workspace-run-integration-tests.yaml
- dev/image/Dockerfile
This bumps the version of Leeway to v0.5.2. That version of Leeway contains a fix for how Leeway deals with ephemeral packages in the transitive dependencies of Go packages. See [commits in changelog](https://github.com/gitpod-io/leeway/releases/tag/v0.5.2).
No issue, needed for https://github.com/gitpod-io/gitpod/pull/14770
The Leeway change was previously tested on our build using the `leewayfromgit` Werft attribute.
```release-note
NONE
```
N/A
> Use Leeway v0.5.2

- .github/CODEOWNERS
- install/installer/cmd/render.go
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/kind-ide/config.yaml
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/config.yaml
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/config.yaml
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/kind-workspace/config.yaml
- install/installer/cmd/testdata/render/kind-workspace/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/components-ide/components.go
- install/installer/pkg/components/components-webapp/components.go
- install/installer/pkg/components/components.go
- install/installer/pkg/config/v1/config.go
- install/installer/pkg/config/v1/validation.go
Separate the IDE/WebApp components from the Meta `kind`. The Meta kind remains as-is to avoid breaking the deployments until this is promulgated.
Fixes #14427
```release-note
[installer]: create a WebApp and IDE installation "kind"
```
> [installer]: create a WebApp and IDE installation "kind"

- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
Update output.golden files (from IDE) to fix the build pipeline.
Golden file updated by running `cd /workspace/gitpod/install/installer && make generateRenderTests`.
- https://werft.gitpod-dev.com/job/gitpod-build-main.5698
Confirm that Werft build passed: https://werft.gitpod-dev.com/job/gitpod-build-ide-update-output-golden-file.1
```release-note
NONE
```
> Update output.golden files (from IDE) to fix the build pipeline

- components/public-api-server/pkg/auth/personal_access_token.go
- components/public-api-server/pkg/auth/personal_access_token_test.go
- components/public-api-server/pkg/auth/signature.go
Introduces generation & validation of **Personal Access Tokens** (PAT).
A PAT is used as a stand-in for a user, inheriting their identity.
A PAT looks like `gitpod_pat_ko8KC1tJ-GkqIwqNliwF4tBUk2Jd5nEe9qOWqYfobtY.6ZDQVanpaTKj9hQuji0thCe8KFCcmEDGpsaTkSSb` (this is a random token, not having access to anything).
It is composed out of the following:
* Prefix `gitpod_pat_`
* Signature `ko8KC1tJ-GkqIwqNliwF4tBUk2Jd5nEe9qOWqYfobtY`
* Value `6ZDQVanpaTKj9hQuji0thCe8KFCcmEDGpsaTkSSb`
A PAT has the following cryptographic properties:
* Signature is an HS256 signature (HMAC with SHA-256), Raw Base64 URL encoded
* Value is a random value with 172 bits of entropy
* Prefix can be used for code-scanning
The signature generation requires a secret key. 
When validating a token, we do the following:
* …
> [public-api] Generate & Parse Personal Access Tokens

- components/proxy/conf/Caddyfile
As part of #9198 we want to send a subset of websocket traffic from the dashboard to an instance of `server` that runs with a higher latency connection to the Gitpod database.
This PR changes the `proxy` `Caddyfile` to reverse proxy traffic to the new `slow-server` deployment depending on the value of the `Sec-WebSocket-Protocol` header that is sent by the browser websocket client during the websocket connection handshake.
https://github.com/gitpod-io/gitpod/pull/14752 demonstrates an approach that allows to selectively set the value of this header for some users, based on the value of a feature flag.
Part of #9198 
In the browser console, establish a new websocket connection to the Gitpod JSON RPC API:
```js
const sock = new WebSocket('wss://af-use-slofc5943d8fc.preview.gitpod-dev.com/api …
```
> [proxy] Proxy websocket traffic to `slow-server` deployment according to `Sec-WebSocket-Protocol` header

- components/gitpod-db/go/personal_access_token.go
- components/gitpod-db/go/personal_access_token_test.go
DB model for `d_b_personal_access_token`.
Depends on https://github.com/gitpod-io/gitpod/pull/14731
Part of #14602
Unit tests
```release-note
NONE
```
> [public api] personal access token db model

- components/ide/code/codehelper/main.go
- components/ide/code/startup.sh
Replace `product.json` only for browser code frontend to save duration of ide ready
See also [internal chat](https://gitpod.slack.com/archives/C01KGM9BH54/p1668876572304729?thread_ts=1668748433.738219&cid=C01KGM9BH54)
Fixes #
- Open workspace in prev env with latest code
- Check if everything related to extension gallery is working well
- extension search / install all to with our openvsx-proxy
- extension detail page click to vote star and marketplace will jump to open-vsx.org without ask to trust URL
```release-note
NONE
```
> [codehelper] replace product.json only

- .werft/jobs/build/job-config.ts
- .werft/jobs/build/prepare.ts
- dev/preview/BUILD.yaml
* Add `storage-class` annotation for preview envs
* Pass less vars to `dev/preview:create-preview` from werft
Fixes #
Run a job, passing the storage class
```bash
werft run github -a with-preview=true -a storage-class=longhorn-gitpod-k3s-202211180921-onereplica
```
Check the storage class:
```bash
k -n preview-aa-less-create-vars get pvc
NAME                                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                                  AGE
aa-less-create-vars-storage-994p7   Bound    pvc-e432f615-706c-4df8-bddc-c2d5e3f7ceb6   30Gi       RWO            longhorn-onereplica                           4m12s
aa-less-create-vars-system-94xvs    Bound    pvc-f1975c4b-27ec-4140-bc49-0c3bcc664a07   200Gi      RWO …
```
> Add `storage-class` annotation for preview envs, and pass less vars to `create-preview`

- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
commit hash comes from PR https://github.com/gitpod-io/gitpod/pull/14821 job https://werft.gitpod-dev.com/job/gitpod-build-hw-code-prod.0
Fixes #
- Open workspace in preview env with stable code https://werft.gitpod-dev.com/job/gitpod-custom-hw-vscode.1/logs
- Check if everything goes well
```release-note
NONE
```
> [code] update stable code

- operations/observability/mixins/workspace/rules/central/workspaces.yaml
With the number of workspaces we are running now this alert fires too often without anything being amiss.
n.a.
```release-note
None
```
> Update StuckOnStopping alert

- components/public-api/go/config/config.go
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/public-api-server/configmap.go
- install/installer/pkg/components/public-api-server/configmap_test.go
- install/installer/pkg/components/public-api-server/constants.go
- install/installer/pkg/components/public-api-server/deployment.go
- install/installer/pkg/components/public-api-server/deployment_test.go
- install/installer/pkg/components/public-api-server/objects_test.go
- install/installer/pkg/config/v1/experimental/experimental.go
Adds config to Public API to load a secret reference to Personal Access Token signing key. 
Fixes #
CI
```release-note
NONE
```
> [installer] Configure personal access token signing key

- components/dashboard/src/components/UsageBasedBillingConfig.tsx
Following up from https://github.com/gitpod-io/gitpod/pull/14705, this will :a: update the usage period date format, moving away from the fixed month-based named period, and :b: use a more appropriate dash punctuation mark ([En Dash](https://en.wiktionary.org/wiki/en_dash)) for separating the date range.
1. Enable UBP flag. //TODO: We definitely need a link to describe how to enable a feature flag.
2. Go to `/billing`
3. Notice the difference in current period date format
|-|-|
| <img width="609" alt="billing-before" src="https://user-images.githubusercontent.com/120486/203112420-363e3db4-cff3-442f-9f30-73b583e69a6f.png"> | <img width="609" alt="billing-after" src="https://user-images.githubusercontent.com/120486/203112425-11042bd5-ac12-4eac-86a9-68fcaae920e2.png"> | …
> Update usage period date format

- components/dashboard/src/workspaces/WorkspaceEntry.tsx
This will restore the removed workspace download functionality.
See [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1668813874167919) (internal). Cc @kylos101 @atduarte @jldec 
1. Open a new workspace
2. Stop the workspace
3. Go to the workspaces list
4. Notice the download menu in the workspace more actions dropdown exists
5. Download the stopped workspace
```release-note
Revert removing the workspace download feature
```
> Revert removing the workspace download feature

- test/tests/components/ws-manager/content_test.go
- test/tests/components/ws-manager/prebuild_test.go
- test/tests/components/ws-manager/tasks_test.go
Disable the PVC integration test because we stop proceeding with the PVC feature now.
#7901
Run the workspace integration test.
```release-note
None
```
> test: disable the PVC integration test

- components/gitpod-db/src/typeorm/migration/1669104291275-PersonalAccessTokenIndexCreatedAt.ts
Such that we can by default sort listed tokens by creation time
* Part of https://github.com/gitpod-io/gitpod/issues/14610
CI
```release-note
NONE
```
> [db] Add index to d_b_personal_access_token on createdAt

- dev/preview/workflow/preview/preview.sh
Prompt on preview create if branch is not in remote
Fixes https://gitpod.slack.com/archives/C032A46PWR0/p1669106126384279?thread_ts=1669105961.391109&cid=C032A46PWR0
```bash
👾 /workspace/gitpod leeway run dev:preview           
WARN: Your branch doesn't exist on GitHub. Your preview environment WILL get garbage collected after AT MOST 1h. To avoid this please push your branch.
I've read 👆 and I understand the implications. [y/n]: n
Aborted
```
```release-note
NONE
```
> Prompt on preview create if branch is not in remote

- components/gitpod-db/go/dbtest/personal_access_token.go
- components/gitpod-db/go/pagination.go
- components/gitpod-db/go/personal_access_token.go
- components/gitpod-db/go/personal_access_token_test.go
- components/public-api-server/BUILD.yaml
- components/public-api-server/pkg/apiv1/pagination.go
- components/public-api-server/pkg/apiv1/pagination_test.go
- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/apiv1/tokens_test.go
- components/usage/BUILD.yaml
- gitpod-ws.code-workspace
Implements ListPersonalAccessTokens.
* Part of https://github.com/gitpod-io/gitpod/issues/14610
* Depends on https://github.com/gitpod-io/gitpod/pull/14835
Unit tests
```release-note
NONE
```
> [public-api] Implement list personal access tokens

- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/apiv1/tokens_test.go
- components/public-api-server/pkg/server/server.go
Creates a signer and uses the Personal Access Token signing key in Public API.
* Depends on https://github.com/gitpod-io/gitpod/pull/14823
```release-note
NONE
```
/hold for dependency on https://github.com/gitpod-io/gitpod/pull/14823
> [public-api] Use personal access token signing key

- components/dashboard/src/contexts/FeatureFlagContext.tsx
Use the name that matches the flag as defined in ConfigCat.
Part of #9198 
```release-note
NONE
```
> [dashboard] Use correct feature flag name for `slow_database` feature flag

- components/dashboard/src/projects/Prebuilds.tsx
This will truncate the branch name on the prebuilds page.
1. Create a team and a project
2. Trigger a prebuild with a branch using a long branch name
3. Go to the prebuilds page and notice the branch name truncating
|-|-|
| <img width="1440" alt="prebuilds-list-before" src="https://user-images.githubusercontent.com/120486/203317482-89294270-8ffd-4346-9c29-9f044a7d4057.png"> | <img width="1440" alt="prebuilds-list-after" src="https://user-images.githubusercontent.com/120486/203317489-ac9132e6-f3e7-4d55-b40b-4b9e794680c5.png"> |
```release-note
Truncate branch name on prebuilds page
```
> Truncate branch name on prebuilds page

- components/gitpod-db/go/dbtest/personal_access_token.go
- components/gitpod-db/go/personal_access_token.go
- components/gitpod-db/go/personal_access_token_test.go
- components/public-api-server/go.mod
- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/apiv1/tokens_test.go
- components/public-api-server/pkg/auth/personal_access_token.go
Implements creation of Personal Access Tokens API
* Part of https://github.com/gitpod-io/gitpod/issues/14602
unit tests
```release-note
NONE
```
> [public-api] Create Personal Access Token implementation

- components/dashboard/src/App.tsx
- components/dashboard/src/contexts/FeatureFlagContext.tsx
- components/dashboard/src/service/service.tsx
- components/gitpod-protocol/src/messaging/browser/connection.ts
Allow websocket connections from the dashboard to the server to specify a [Sec-WebSocket-Protocol](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-WebSocket-Protocol) header indicating whether the connection should use a high-latency database connection, according to the value of a feature flag.
At a high level, the architecture looks like this:
Together with the dependency #14778 which handles the proxying of websocket upgrade requests to the `slow-server` backend based on the presence of the `Sec-WebSocket-Protocol` header, this PR gives us a means to roll out higher-latency dashboard to server websocket connections to selected internal users.
Part of #9198 
```release-note
NONE
``` …
> [dashboard/protocol] Pass `slow-database` `Sec-WebSocket-Protocol` header to websocket connections from dashboard

- components/gitpod-db/go/personal_access_token.go
- components/gitpod-db/go/personal_access_token_test.go
- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/apiv1/tokens_test.go
Implements GetPersonalAccessToken
Fixes #
Unit tests `personal_access_token_test.go` and `tokens_test.go`
```release-note
NONE
```
> [pat] Implement GetPersonalAccessToken

- .gitpod.yml
- .werft/aks-installer-tests.yaml
- .werft/build.yaml
- .werft/cleanup-installer-tests.yaml
- .werft/debug.yaml
- .werft/eks-installer-tests.yaml
- .werft/gke-installer-tests.yaml
- .werft/ide-integration-tests-startup.yaml
- .werft/jobs/build/prepare.ts
- .werft/k3s-installer-tests.yaml
- .werft/platform-delete-preview-environment.ts
- .werft/platform-delete-preview-environment.yaml
- .werft/platform-delete-preview-environments-cron.yaml
- .werft/platform-trigger-artificial-job.yaml
- .werft/platform-trigger-werft-cleanup.yaml
- .werft/workspace-run-integration-tests.yaml
- dev/BUILD.yaml
- dev/image/BUILD.yaml
- dev/image/Dockerfile
- dev/leeway.Dockerfile
- dev/preview/previewctl/BUILD.yaml
This PR removes `previewctl` from the Dockerfile in favour of installing it in prebuilds through an `init` task.
`leeway run dev/preview/previewctl:install` will now build and copy the binary over to `/workspace/preview/bin`. `/workspace/bin` has been created and added to the $PATH.
This makes it much easier for us to iterate on `previewctl` as we won't have to rebuild the dev image and update all references to it (triggering review from every team) for every change we make.
Fixes https://github.com/gitpod-io/gitpod/issues/14149
That preview environments from Werft still works ([example](https://werft.gitpod-dev.com/job/gitpod-build-mads-dont-include-previewctl-in-image.14))
```
werft job run github -a with-preview=true
```
That `previewctl` is available in workspaces
```
which previewctl …
```
> Don't include previewctl in dev image

- components/common-go/experiments/configcat.go
This change normalizes the behaviour between our NodeJS client, and the Golang one. We set the UserID on both the User Identifier property, but also the custom attribute, to avoid unexpected surprises for feature flag operators
Fixes #
```release-note
NONE
```
> [configcat] Set UserID as a custom attribute on configcat user data

- components/public-api-server/pkg/auth/personal_access_token.go
At cost 16, we're taking 4.5 secs on average to compute the hash. At cost 10, we're taking on average 100ms which is acceptable.
Fixes #
```release-note
NONE
```
> [pat] Reduce bcrypt cost to 10

- test/run.sh
Support namespace overwrites from env var.
The self-hosted env which installed the gitpod components into the `gitpod` namespace rather than `default` namespace.
Provide a way to overwrite the namespace variable from env var.
After that, we could run the integration test against the workspace test by
```console
export NAMESPACE=gitpod
./run.sh workspace
```
Fixes #
```release-note
None
```
> test: support namespace overwrites from env var

- test/tests/components/ws-manager/dotfiles_test.go
When running the integration test against self-hosted env, which default Gitpod components are in gitpod namespace rather than default namespace.
Remove the hardcode namespace in the integration test.
Fixes #
```release-note
None
```
> test: remove hardcode namespace

- components/dashboard/src/App.tsx
- components/dashboard/src/settings/PersonalAccessTokens.tsx
- components/dashboard/src/settings/settings-menu.ts
Changes name as per designs
Fixes #
```release-note
NONE
```
> [dashboard] Rename Personal Access Tokens settings entry to Access Tokens

- components/gitpod-protocol/src/experiments/configcat-server.ts
Set a timeout value when constructing the configcat client.
See:
https://configcat.com/docs/sdk-reference/js/#auto-polling-default
Relates to https://github.com/gitpod-io/gitpod/pull/14856#discussion_r1030153466
```release-note
NONE
```
> [protocol] Set `requestTimeoutMs` in configcat client

- components/server/src/container-module.ts
- components/server/src/feature-flag/featureflag-controller.ts
- components/server/src/server.ts
Add a server endpoint to test the value of the `slow_database` feature flag for the currently authenticated user.
The endpoint sets the `X-Gitpod-Slow-Database` header in the response to either `true` or `false` according to the value of the feature flag.
The intention is that this endpoint can be used by the Caddy proxy to 'pre-flight' requests to server, sending the actual request to either `server` or `slow-server` as needed.
Part of #9198 
0. Log in to the preview environment.
1. Hit https://af-feature1eafc027eb.preview.gitpod-dev.com/api/feature-flags/slow-database and inspect the response headers. The `X-Gitpod-Slow-Database` header should be set to `false` as the feature flag is not enabled for you.
2. Change the targeting rule for the `slow_database` feature flag (non-production …
> [server] Add `api/feature-flags/slow-database` endpoint

- components/gitpod-db/go/dbtest/conn.go
- components/gitpod-db/go/personal_access_token.go
- components/gitpod-db/go/personal_access_token_test.go
- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/apiv1/tokens_test.go
Implements regenerate token
Fixes https://github.com/gitpod-io/gitpod/issues/14611
```release-note
NONE
```
> [public-api] Implement regenerate token

- components/public-api-server/pkg/apiv1/project.go
- components/public-api-server/pkg/apiv1/project_test.go
- components/public-api-server/pkg/server/server.go
* Depends on https://github.com/gitpod-io/gitpod/pull/14624
* Depends on https://github.com/gitpod-io/gitpod/pull/14645
1. Preview, sign in with Github and give perms to Read Repo
2. Obtain an Access Token by running the following in the console, after logging in
```typescript
"function:createProject",
"function:getTeams",
"function:getTeam",
```
3. Setup the token as env variable `BEARER_TOKEN="<token>"` in your terminal
4. Create a team programmatically
```bash
curl \
--header 'Content-Type: application/json' \
--header "Authorization: Bearer $BEARER_TOKEN" \
--data '{ …
```
> [public-api] Implement ProjectsService.CreateProject

- components/gitpod-db/go/personal_access_token.go
- components/gitpod-db/go/personal_access_token_test.go
- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/apiv1/tokens_test.go
Implements delete token
Fixes https://github.com/gitpod-io/gitpod/issues/14613
```release-note
NONE
```
> [public-api] Implement delete token

- .werft/jobs/build/installer/post-process.sh
- test/tests/components/ws-daemon/cpu_burst_test.go
Partially revert the change of PR #14786.
Fix an error when running the integration test against the self-hosted environment.
`json: cannot unmarshal string into Go struct field .cpuLimit.limit of type int64`.
According to the [values](https://github.com/gitpod-io/ops/blob/2e6d65c4269da96c5eda85da5363586e3f41839f/deploy/workspace/installer-values.yaml#L49-L50), it's string based. So, quote the values in the preview environment.
Fixes https://github.com/gitpod-io/gitpod/pull/14786/files#r1029984960
Run the integration test on the self-hosted environment.
```release-note
None
```
> test: fix unmarshal string to int64 failed

- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/apiv1/tokens_test.go
Retrieves teams for the current user to check if the feature flag is enabled for a whole team.
When fetching a team fails, we do not check against teams and continue as before.
Fixes #
```release-note
NONE
```
> [pat] Check personal access tokens enabled feature flag against teams

- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/apiv1/tokens_test.go
- components/public-api/gitpod/experimental/v1/tokens.proto
- components/public-api/go/experimental/v1/tokens.pb.go
- components/public-api/typescript/src/gitpod/experimental/v1/tokens_pb.ts
Hardens Personal Access Token name validation. See regex for allowed format.
Fixes #
Unit tests
```release-note
NONE
```
> [pat] Harden Personal Access Token name validation

- dev/preview/previewctl/BUILD.yaml
- dev/preview/previewctl/cmd/install_context.go
- dev/preview/workflow/preview/preview.sh
Adds a `--retry <count>` flag to `previewctl install-context` and uses it in `leeway run dev:preview`. 
Also fixed one bug when using `leeway run dev/preview/previewctl:install` multiple times.
Fixes https://github.com/gitpod-io/gitpod/issues/14759
```sh
```
```release-note
NONE
```
N/A
> Add retry option to install-context

- .werft/jobs/build/installer/post-process.sh
- .werft/jobs/build/public-api/personal-access-token-signing-key.yaml
- dev/preview/workflow/preview/deploy-gitpod.sh
[werft] add public api token service support for preview environment
This PR add post-process setp to werft job , it will automatic inject a signing-key into preview environment
Fixes #
1. open this PR in gitpod.io, and run `werft run github -a with-preview=1` [see this job](https://werft.gitpod-dev.com/job/gitpod-build-hw-preview-pat.4)
2. open preview environment to check token service is configure.
```release-note
NONE
```
> [werft] add public api token service support for preview environment

- components/gitpod-db/go/dbtest/personal_access_token.go
- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/apiv1/tokens_test.go
Adds the missing piece to CreatePerosonalToken which validates scopes for the token.
We operate in one of two modes:
* Token has no scopes, and therefore no permission
* Token has access to all functions, and default resource. This gives the token the ability to do anything the user can.
Any other option is rejected.
Fixes #
Unit tests
```release-note
NONE
```
> [pat] Validate and enforce scopes for PATs

- components/gitpod-db/src/typeorm/migration/1669237520073-PersonalAccessTokenRemoveDescriptionColumn.ts
Removes description column `d_b_personal_access_token` table
* Depends on https://github.com/gitpod-io/gitpod/pull/14901
* Fixes https://github.com/gitpod-io/gitpod/issues/14900
Unit tests execute migrations, CI passes
```release-note
NONE
```
/hold depends on https://github.com/gitpod-io/gitpod/pull/14901
> [db] Drop description column from d_b_personal_access_token

- components/public-api-server/pkg/apiv1/pagination.go
- components/public-api-server/pkg/apiv1/pagination_test.go
- components/public-api-server/pkg/apiv1/project.go
- components/public-api-server/pkg/apiv1/project_test.go
Implements ListProjects API on Public API.
The API is modal, depending on which arguments are supplied.
* If userID is supplied, we use `getUserProjects` from server
* If teamID is supplied, we use `getTeamProjects` from server
* Both are not allowed
* Fixes https://github.com/gitpod-io/gitpod/issues/14896
Unit tests
```release-note
NONE
```
> [public-api] Implement ProjectsService.ListProjects

- components/dashboard/src/components/UsageBasedBillingConfig.tsx
This is the minimal change that displays free accounts with more than 500 credits as "Professional Open Source" plans.
We don't really have a great place to store such information explicitly atm and I don'T think it is worth introducing something at this point (we can do later).
This PR does not include any automatic updates for existing professional open-source users. Will do this in a follow up PR.
See #14819 
Increase the usage limit (> 500) using the admin dashboard and verify that under billing the user is shown to be on the "Professional Open Source" Plan.
```release-note
NONE
```
> [dashboard] display professional OS

- test/tests/components/ws-daemon/cpu_burst_test.go
Increase timeout for cpu limit test until we can analyze the flakiness
n.a.
```
go test -run ^TestCpuBurst$ github.com/gitpod-io/gitpod/test/tests/components/ws-manager -count=1 -namespace=default -kubeconfig=/home/gitpod/.kube/config -v -timeout=20m
```
```release-note
None
```
> Increase timeout for cpu limit test

- components/image-builder-mk3/pkg/orchestrator/orchestrator.go
- components/ws-manager/pkg/manager/manager.go
Log JSON as an object instead of a string.
Fixes #14219
- Update the ws-manager deployment LOG_LEVEL to DEBUG
- Check the ws-manager log
Here is an example log output https://cloudlogging.app.goo.gl/GtxqVmV7w7Y564qR9
```release-note
None
```
> Log JSON as an object instead of a string

- components/dashboard/src/App.tsx
- components/dashboard/src/components/CheckBox.tsx
- components/dashboard/src/components/InputWithCopy.tsx
- components/dashboard/src/settings/PersonalAccessTokens.tsx
- components/dashboard/src/settings/settings-menu.ts
- components/dashboard/src/settings/settings.routes.ts
- components/dashboard/src/utils.ts
- components/dashboard/src/workspaces/ConnectToSSHModal.tsx
Fixes https://github.com/gitpod-io/gitpod/issues/14615
```release-note
NONE
```
> [public-api] Create token UI

- components/gitpod-db/go/cost_center.go
We previously decided to always reset usage limit of cost centers to their configured defaults when running the free billing cycle renewal (billingStrategy: other). This was a simple way to clean up some legacy values in the DB.
This PR changes the code to keep whatever is configured, because we now can adjust the usage limit on these cost centers and don't want the usage component to revert those changes every month.
Fixes #
```release-note
NONE
```
> [usage] don't reset usage limit

- components/dashboard/src/Menu.tsx
- components/dashboard/src/components/BillingAccountSelector.tsx
- components/dashboard/src/components/UsageBasedBillingConfig.tsx
- components/dashboard/src/projects/NewProject.tsx
- components/dashboard/src/teams/TeamBilling.tsx
- components/dashboard/src/teams/TeamSettings.tsx
Fetches team members from Public API.
Fixes #
Preview, load the following:
* New Project
* Team Settings
* Billing Account Selector
* UBP
```release-note
NONE
```
> [dashboard] Use Public API when fetching team members

- components/dashboard/src/settings/PersonalAccessTokens.tsx
- components/dashboard/src/settings/TokenEntry.tsx
Second part to the list tokens view. This shows the list with token (without edit/regenerate/delete functions).
Fixes #14860 
[Preview env](https://lau-list-t8fb5bd3e6f.preview.gitpod-dev.com/personal-tokens).
```release-note
NONE
```
> [pat] List view with tokens

- components/dashboard/src/components/CheckBox.tsx
We've recently introduced a `className` property in the `CheckBox` component, in order to allow for custom classes:
https://github.com/gitpod-io/gitpod/blob/dfc399b13c5b4f191037ae4ea3b7d36190c59eb6/components/dashboard/src/components/CheckBox.tsx#L29
Unfortunately, we didn't add a space between `max-w-2xl` and the `className` properties. This caused both `max-w-2xl` and `mt-4` classes to stop working in the default case.
Fixes #
1. Look at any dashboard page that has checkboxes, e.g. `/notifications`
2. There should be some vertical spacing above each checkbox
```release-note
NONE
```
> [dashboard] Fix CheckBox component style regression

- dev/preview/BUILD.yaml
- dev/preview/workflow/preview/deploy-gitpod.sh
- dev/preview/workflow/preview/preview.sh
* Reduce the dependencies required when deploying in preview envs
* Build the installer and use the binary, instead of relying on pushing it to docker
* Use local `versions.yaml`, instead of relying on docker-versions
<details>
<summary>Before</summary>
```
leeway build dev/preview:deploy-dependencies --dont-test -Dversion=test   
59.40s user 
12.35s system 96% cpu 
1:14.59 total
🔧  build                      components/gitpod-db/go:init-testdb                                    (version b72dd9c3c1de3fb4d09693fce5dd31ae91030225)
🔧  build                      components/gitpod-db:dbtest-init                                       (version 53913f13103e6b342b40c47311f04de838af412c)
🔧  build                      components/ws-manager:app                                              (version …
```
> Build less package when deploying gitpod from local 

- components/dashboard/src/App.tsx
- components/dashboard/src/settings/PersonalAccessTokens.tsx
- components/dashboard/src/settings/TokenEntry.tsx
- components/dashboard/src/settings/settings-menu.ts
- components/dashboard/src/settings/settings.routes.ts
Add `delete`, `regenerate` and `edit` UI 
~~(edit not implemented yet)~~
Fixes https://github.com/gitpod-io/gitpod/issues/14618
Fixes https://github.com/gitpod-io/gitpod/issues/14616
Relates https://github.com/gitpod-io/gitpod/issues/14612
```release-note
NONE
```
|Delete| Edit|
|-|-|
|<img width="1489" alt="image" src="https://user-images.githubusercontent.com/20944364/203861225-257b11c1-02d8-4eec-b126-72dc5d4c4e17.png">|<img width="1489" alt="image" src="https://user-images.githubusercontent.com/20944364/203861299-bae7b093-4cbe-470a-ba05-3af02082ca87.png">|
|Regenerate| Result |
|-|-|
|<img width="1489" alt="image" …
> [public-api] Add Delete, Regenerate, and Update PAT UI

- components/server/src/feature-flag/featureflag-controller.ts
Make the `api/feature-flags/slow-database` return code `200` and set the `X-Gitpod-Slow-Database` header consistently.
We don't need to distinguish between response codes for the reverse proxy 'pre-flight' added in #14897  and in fact having the endpoint return non-success codes is actively unhelpful when using the Caddy [forward_auth](https://caddyserver.com/docs/caddyfile/directives/forward_auth) directive.
See https://github.com/gitpod-io/gitpod/pull/14897#discussion_r1030654402 for more context. 
Part of #9198 
```release-note
NONE
```
> [server] Change response codes returned from `api/feature-flags/slow-database` endpoint

- components/dashboard/src/settings/PersonalAccessTokens.tsx
Minor change to update copy-to-clipboard button text case in the personal access tokens settings.
1. Go to /personal-tokens
2. Create a new token
3. Notice that the copy-to-clipboard button is using proper title case
```release-note
NONE
```
> Update copy-to-clipboard button text case

- components/dashboard/src/settings/settings-menu.ts
Following up from https://github.com/gitpod-io/gitpod/pull/14881#discussion_r1030208822, this will move update the access tokens menu order.
Cc @easyCZ because https://github.com/gitpod-io/gitpod/pull/14881
> | BEFORE | AFTER |
> |-|-|
> | <img width="340" alt="sidebar-before" src="https://user-images.githubusercontent.com/120486/203512776-f5268d61-52a7-45f5-b048-e11fb8e36154.png"> | <img width="340" alt="sidebar-after" src="https://user-images.githubusercontent.com/120486/203512793-d1006544-5a48-4f07-b4ac-20007d2777c0.png"> |
1. Go to user settings.
2. Notice the _Access Tokens_ menu order.
```release-note
Update access tokens menu order
```
> Update access tokens menu order

- .github/CODEOWNERS
We've been asked to use the fully qualified team name, like other teams.
Fixes #
```release-note
NONE
```
> Make Team Name Fully Qualified

- components/dashboard/src/Menu.tsx
- components/dashboard/src/settings/settings.routes.ts
This will change the personal access tokens URL path from **/personal-tokens** to **/tokens**, for brevity and following the pattern used for environment variables, see **/variables**.
1. Go to user settings
2. Open access tokens
3. Notice the new URL path (/tokens)
```release-note
NONE
```
> Change personal access tokens URL path

- install/installer/pkg/components/toxiproxy/deployment.go
Set these to more realistic values for simulating a connection to a US west coast database.
Part of #9198 
Closes https://github.com/gitpod-io/gitpod/issues/14958
```release-note
NONE
```
> [installer] Set latency and jitter values for Toxiproxy mysql proxy

- operations/observability/mixins/IDE/dashboards.libsonnet
[observability] add IDE startup time dashboard
Fixes #
```release-note
NONE
```
> [observability] add IDE startup time dashboard

- WORKSPACE.yaml
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
[code] switch download extension logic to vscode
Fixes #
Use https://github.com/iQQBot/test.test/tree/vsix repo start a workspace and restart extensions should be quickly available in both cases.
```release-note
NONE
```
> [code] switch download extension logic to vscode

- .gitpod.yml
Since https://github.com/gitpod-io/gitpod/pull/14893 has been merged we are no longer using GCP_ADC_FILE. Now we want to get revoke the credentials for everyone and remove the environment variable.
This PR extends `.gitpod.yml` so this happens automatically.
Part of https://github.com/gitpod-io/security/issues/79
1. Go to https://gitpod.io/variables and see your GCP_ADC_FILE environment variable
2. Open a workspace off this branch
3. Refresh https://gitpod.io/variables
4. Open a new workspace (to verify it handles it well when the environment variable isn't set) 
```release-note
NONE
```
N/A
> Auto remove GCP_ADC_FILE

- components/gitpod-db/src/container-module.ts
- components/gitpod-db/src/index.ts
- components/gitpod-db/src/personal-access-token-db.ts
- components/gitpod-db/src/typeorm/entity/db-personal-access-token.ts
- components/gitpod-db/src/typeorm/personal-access-token-db-impl.ts
Adds DB model into server to read PATs.
This is needed to be able to authenticate, and authorize, requests containing the PAT
* Part of https://github.com/gitpod-io/gitpod/issues/14912
```release-note
NONE
```
> [db] Define PersonalAccessToken model for TypeORM

- components/gitpod-db/go/cost_center.go
- components/gitpod-db/go/cost_center_test.go
- components/usage/pkg/apiv1/usage.go
Fetch the cost center from db immediately before deciding to resetting the usage. So that the time window in which a parallel resetting for the same cost center could happen is minimized.
We saw eight cases in Nopvember where thsi happened. But teh likely hood was very high due to:
- no resetting scheduler was active (so every cost center was outdated at some point)
- we fetch the cost center first and do quite some computation before inserting the update.
Fixes #14973
```release-note
NONE
```
> [usage] reduce possibility for races in ResetUsage

- components/proxy/conf/Caddyfile
Websocket `Upgrade` requests can hit either `/api/gitpod` (from `server`) or `/api/v1` (from the public API).
This matcher change ensures that websocket requests to `api/v1` are handled by the matcher block intended to handle websocket requests rather than the block for `api/*` requests.
Websocket `Upgrade` requests to `api/v1` worked without this change because the handler for `api/*` handled those requests correctly, but this won't be the case after https://github.com/gitpod-io/gitpod/pull/14897 (which makes changes to the `/api/*` handler) lands.
Part of #9198 
The public API RPCs that delegate to `server` over the JSON-RPC API still work.
```release-note
NONE
``` …
> [proxy] Match `/api/v1` in the `@backend_wss` matcher

- components/proxy/conf/Caddyfile
Before handling `server` `/api` requests, make a 'pre-flight' request to `/api/feature-flags/slow-database` (on `server`) and use the `X-Gitpod-Slow-Database` header in the response to decide where to send the actual request; either to the regular `server` service or the new `slow-server` service.
This allows us to use a feature flag to simulate the performance of these endpoints when they use a higher latency database connection.
Part of #9198 
Closes https://github.com/gitpod-io/gitpod/issues/14960.
0. Log in to the preview environment.
1. Hit https://af-proxy-a5b2f4cfb56.preview.gitpod-dev.com/api/version and inspect the response timings. 
2. Change the targeting rule for the `slow_database` feature flag (non-production environment) to this (replacing the user id with your user id in …
> [proxy] Pre-flight requests to server /api/* endpoints

- components/public-api-server/go.mod
- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/auth/personal_access_token.go
- components/public-api-server/pkg/auth/personal_access_token_test.go
Originally wanted to use bcrypt, however bcrypt generated hashes also encode the salt with multiple rounds in the token. This means that a value, which is hashed by bcrypt does not hash to the same value the next time. As a result, we can't lookup that hashed value in the db.
Instead, we're hashing it with sha256, which is sufficient given we're also generating the token value so the seed itself is already random, and prevents rainbow table attacks.
As a follow up, I will deleteexisting tokens from the DB by setting `deleted` to true, and db-sync cleaning up.
Fixes #
Unit
Preview
1. Generate a new token
```release-note
NONE
```
> [pat] Store hash as sha256 instead of bcrypt

- WORKSPACE.yaml
- components/ide/code/codehelper/main.go
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
[code-helper] remove download vsix logic
It's a part for https://github.com/gitpod-io/gitpod/pull/14927
Fixes #
Use https://github.com/iQQBot/test.test/tree/vsix repo start a workspace and restart extensions should be quickly available in both cases.
```release-note
NONE
```
> [code-helper] remove download vsix logic

- .werft/aks-installer-tests.yaml
- .werft/eks-installer-tests.yaml
- .werft/gke-installer-tests.yaml
- .werft/k3s-installer-tests.yaml
The intent of this change is to reduce noise in Slack for each product team's `job` channel. 
Why?
* Self-hosted test automation runs is generally only needed once a month, as part of our self-hosted release process. 
* Teams have generic test suites that run tests for their components as part of separate jobs. [[1](https://github.com/gitpod-io/gitpod/blob/116ea559bc0979227467c9e30c717e786c2bee97/.werft/workspace-run-integration-tests.yaml#L74-L75)][[2](https://github.com/gitpod-io/gitpod/blob/116ea559bc0979227467c9e30c717e786c2bee97/.werft/ide-integration-tests-startup.yaml#L67-L68)]
Fixes # n/a
After this is merged, the self-hosted tests won't run on a schedule, and `job` Slack channels will have less threads. The tests can still be run manually, and will output to Slack. …
> [tests] Stop running self-hosted tests daily

- components/common-go/log/log.go
[common] Improve log time accuracy
Before our log time accuracy is second, it will cause random order in gcp error (same second), this PR up time accuracy to nano sec.
Fixes #
1. open this PR in gitpod.io
2. cd `components/supervisor/`
3. run `go run . run`
4. it will print an error, and the time should be nano sec.
|  before | after  |
|---|---|
|  <img width="775" alt="image" src="https://user-images.githubusercontent.com/8299500/204461286-3abc1f5f-cb72-4bc4-8e87-b7ee6ce3c135.png"> | <img width="756" alt="image" src="https://user-images.githubusercontent.com/8299500/204461248-3920d4db-c4d9-458b-9c2d-db8adb4a1458.png">  |
```release-note
NONE
```
> [common] Improve log time accuracy

- components/dashboard/src/components/UsageView.tsx
- components/dashboard/src/projects/NewProject.tsx
- components/dashboard/src/teams/NewTeam.tsx
Minor style changes for the beta notice for Teams & Projects, following the style used for Usage.
This will also:
1. Include a hyperlink to the **[Gitpod Releases](https://www.gitpod.io/docs/help/public-roadmap/release-cycle)** page directly on the beta pill component.
2. Update the beta notice on the usage page to follow the same pattern.
|-|-|
| <img width="446" alt="teams-before" src="https://user-images.githubusercontent.com/120486/204368089-d2cb139c-8fe3-42db-8289-edb9d290d44e.png"> | <img width="446" alt="teams-after" src="https://user-images.githubusercontent.com/120486/204368093-e4402b81-c19d-49ed-bae6-2b125193608e.png"> |
| <img width="463" alt="projects-before" src="https://user-images.githubusercontent.com/120486/204368100-761aaec0-f8f0-44e9-8043-1b195c70dc3a. …
> Update beta label on teams, projects, and usage

- components/gitpod-db/go/personal_access_token.go
- components/gitpod-db/go/personal_access_token_test.go
Currently with 1 deleted token, we'd return { Results: [], Total: 1 }. This fixes that.
Fixes #
```release-note
NONE
```
> [pat] Do not list deleted PATs

- components/dashboard/src/components/UsageBasedBillingConfig.tsx
- components/dashboard/src/settings/Billing.tsx
- components/dashboard/src/teams/TeamUsageBasedBilling.tsx
Tiny PR with tweaks to the user and team billing pages, to replace "usage-based" with "pay-as-you-go".  
Fixes #14475
Check that there is no mention of "Usage-based" in user and team billing settings. 
```release-note
Replace "usage-based" with "pay-as-you-go" in user and team billing pages.
```
https://github.com/gitpod-io/website/issues/3004
> Replace usage-based with pay-as-you-go in billing pages

- components/proxy/conf/Caddyfile
In https://github.com/gitpod-io/gitpod/pull/14778 and https://github.com/gitpod-io/gitpod/pull/14752, latency was added to websocket connections to `server` from the dashboard by testing the value of the `slow_database` feature flag on the client side and setting an appropriate header during the websocket connection upgrade handshake.
This approach works for connections to `server` from the dashboard but not for other websocket connections to `server`.
This PR moves the evaluation of the feature flag from the dashboard client to `proxy`, using a 'pre-flight' check just like the one added in https://github.com/gitpod-io/gitpod/issues/14960 for regular HTTP requests to `server` `/api*` requests.
The client side code to check the value of the feature flag will be removed by …
> [proxy] Add latency to all websocket connections to server

- components/dashboard/src/App.tsx
- components/dashboard/src/contexts/FeatureFlagContext.tsx
- components/dashboard/src/service/service.tsx
- components/gitpod-protocol/src/messaging/browser/connection.ts
Reverts https://github.com/gitpod-io/gitpod/pull/14752.
The logic of checking the feature flag has moved (in https://github.com/gitpod-io/gitpod/pull/15035) to the backend (`proxy`) so we don't need this logic on the dashboard anymore.
Part of #9198 and https://github.com/gitpod-io/gitpod/issues/14964.
```release-note
NONE
```
> [dashboard] Remove client side eval of `slow_database` flag

- components/proxy/conf/Caddyfile
Reinstate https://github.com/gitpod-io/gitpod/pull/14974 after it was reverted in https://github.com/gitpod-io/gitpod/pull/15040.
Fixes #
```release-note
NONE
```
> [proxy] Match /api/v1 in the @backend_wss matcher

- components/supervisor/pkg/supervisor/supervisor.go
- components/supervisor/pkg/supervisor/tasks.go
- components/supervisor/pkg/supervisor/tasks_test.go
We suspect that competition for resources between tasks and IDE starting at the same time can delay IDE startup.
Since IDE startup is fast we try to delay start of tasks for max 1s to give an opportunity for IDE to start.
Fixes #
Check that a workspace can start with tasks, VS Code Browser and IntelliJ IDEA. (test for regressions)
```release-note
NONE
```
> [supervisor] give 1s window between content and tasks for IDE startup

- components/server/src/config.ts
- dev/preview/workflow/preview/deploy-gitpod.sh
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/server/configmap.go
- install/installer/pkg/components/server/constants.go
- install/installer/pkg/components/server/deployment.go
- install/installer/pkg/components/server/types.go
Setup configuration to mount pat signing key to server, such that we can use the key to validate PAT signatures
* Part of https://github.com/gitpod-io/gitpod/issues/14912
1. Get preview k8s context
2. Get config map `kubectl get cm server-config -o yaml`
3. Observe it contains `"patSigningKeyFile": "/secrets/personal-access-token-signing-key",`
```release-note
NONE
```
> [server, installer] Configure PAT signing key

- components/server/ee/src/prebuilds/prebuild-manager.ts
- components/server/src/config.ts
- components/server/src/workspace/prebuild-rate-limiter.ts
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/server/configmap.go
- install/installer/pkg/components/server/types.go
- install/installer/pkg/components/slowserver/configmap.go
Effectively changes the rate limiter from being
```
Limit:  50,
Period: 60,
```
to be
```
Limit:  100,
Period: 600,
```
Fixes #14791 
- setup a project
- change the server ConfigMap to be set to `limit: 2`, and `kubectl rollout restart deployment/server`
- trigger 3 prebuilds on that project withing 5 minutes
- notice how the 3rd gets rejected (you can use the `...project/events` endpoint for that)
```release-note
Make PrebuildRateLimiter more configurable
```
> [server, installer] Make PrebuildRateLimiter period configurable

- components/dashboard/src/settings/PersonalAccessTokens.tsx
Removes usage of `Personal` or `PAT` from user facing elements to stay consistent with Access Tokens name in menu item
Fixes #
```release-note
NONE
```
> [pat] Remove 'Personal' from PATs to stay consistent with menu item

- components/gitpod-db/src/typeorm/auth-code-repository-db.ts
This PR seeks to gain more insight into #14464 
Context: #14464 
- see that the build works
```release-note
NONE
```
> [server] Print more details on auth error

- components/gitpod-db/go/personal_access_token.go
- components/gitpod-db/go/personal_access_token_test.go
Additional argument validation
Fixes #
Unit tests
```release-note
NONE
```
> [pat] Harden retrieval of PATs and check for nil UUIDs

- components/dashboard/src/start/CreateWorkspace.tsx
- components/gitpod-protocol/src/context-url.spec.ts
- components/gitpod-protocol/src/context-url.ts
- components/gitpod-protocol/src/messaging/error.ts
- components/gitpod-protocol/src/protocol.ts
- components/server/ee/src/prebuilds/prebuild-manager.ts
- components/server/ee/src/prebuilds/start-prebuild-context-parser.ts
Throw an error when attempting to start a prebuild on a repository without a corresponding project.
Also _(reviving https://github.com/gitpod-io/gitpod/pull/15024)_ disable the deprecated `#prebuild/` context URL prefix, because it doesn't know about projects (and thus ignores any project details, settings, or safeguards).
The supported ways to start a prebuild are:
- Creating a Project
- Pushing commits to a Project branch
- Clicking on a `Run Prebuild` button in the UI
Fixes https://github.com/gitpod-io/gitpod/issues/9898 https://github.com/gitpod-io/gitpod/issues/4353
1. Should build
2. Using the deprecated `#prebuild/` URL prefix should no longer work
```release-note
Disable running prebuilds without a project + disable the deprecated '#prebuild/' URL prefix
``` …
> Disable running prebuilds without a project

- components/common-go/experiments/configcat.go
To remove the [following logs](https://console.cloud.google.com/logs/query;query=jsonPayload.message%3D%22fetching%20from%20https:%2F%2Fcdn-global.configcat.com%22;timeRange=PT3H;cursorTimestamp=2022-11-30T13:32:54.517479136Z?authuser=0&project=gitpod-191109)
Fixes #
```release-note
NONE
```
> [configcat] Log at error level only in Golang client

- gitpod-ws.code-workspace
This makes the path to the prettier config absolute because the relative config would look it up relative to the current package.
Fixes #
Verify that formating changes get applied on save.
```release-note
NONE
```
> fix path to prettier config

- components/server/src/auth/bearer-authenticator.ts
- components/server/src/config.ts
Uses PAT signing key to validate tokens
* Depends on https://github.com/gitpod-io/gitpod/pull/15037
* Part of https://github.com/gitpod-io/gitpod/issues/14912
1. Preview
2. Create PAT
3. Execute the following:
```bash
curl 'https://api.mp-server-3b46e8956e.preview.gitpod-dev.com/gitpod.experimental.v1.TokensService/ListPersonalAccessTokens' \
-H 'accept: application/json' \
-H 'content-type: application/json' \
-H 'Authorization: Bearer <PAT>' \
--data-raw '{}'
```
4. Try changing the token a bit to ensure it fails to validate
```release-note
NONE
```
> [server] Validate PAT signature

- components/ws-daemon/pkg/content/service.go
Add the necessary information.
Investigation for https://github.com/gitpod-io/gitpod/issues/15049
Works fine
```release-note
None
```
> ws-daemon: Enhause the traces for DisposeWorkspace

- components/gitpod-db/src/typeorm/migration/1669888999897-PersonalAccessTokenFixLastModifiedAutoUpdate.ts
In https://github.com/gitpod-io/gitpod/pull/15015#discussion_r1036347016, we've identified that the table has the on-update extra property on the wrong column. This migraiton moves it to the `_lastModified` column, and removes it from teh `expirationTime` column
Fixes #
CI runs the migrations on a local DB, tests in the public api use those migrations to run unit tests
```release-note
NONE
```
> [pat] Apply on-update property to _lastModified column, remove from expirationTime

- components/gitpod-db/src/typeorm/migration/1669892320740-PersonalAccessTokenFixExpirationTimeAutoUpdate.ts
Previous [PR](https://github.com/gitpod-io/gitpod/pull/15093/files) wouldn't fix it on a DB which already has existing data
Fixes #
1. On this PR, in a workspace `leeway build components/gitpod-db/go:init-testdb`
2. Connect to the local db `mysql -h 127.0.0.1 -P 23306 -u root -D gitpod --select-limit=200 --safe-updates -p`, `pw: test`
3. `mysql> show columns from d_b_personal_access_token;`
```
+----------------+--------------+------+-----+----------------------+--------------------------------+
| Field          | Type         | Null | Key | Default              | Extra                          |
+----------------+--------------+------+-----+----------------------+--------------------------------+
| id             | varchar(255) | NO   | PRI | NULL                 | …
```
> [pat] Fix expiration time auto-udpate

- components/dashboard/src/settings/PersonalAccessTokens.tsx
This will update spacing between elements in the token regeneration modal, following the proposal in https://github.com/gitpod-io/gitpod/issues/15104#issuecomment-1333805855.
Fixes https://github.com/gitpod-io/gitpod/issues/15104
1. Create a new access token
2. Go to the access tokens list
3. Click on more actions to regenerate a token or regenerate via the token edit page
4. Notice the spacing in the modal
From https://github.com/gitpod-io/gitpod/issues/15104#issuecomment-1333805855:
> | BEFORE | AFTER |
> |-|-|
> | <img width="536" alt="modal-before" src="https://user-images.githubusercontent.com/120486/205071027-2aca7750-c54e-44c1-840e-85925521b9ea.png"> | <img width="536" alt="modal-after" src="https://user-images.githubusercontent.com/120486/205071034-2c70d4d0-20b3-499b-814f-9e05c67eb …
> Update spacing in token regeneration modal

- components/proxy/conf/Caddyfile
Pre-flight requests to `server` `/auth/*` endpoints in order to decide whether to send the actual request to `server` or `slow-server` depending on the value of the `slow_database` feature flag.
This change will affect requests to following paths on `server`:  `/auth/github/callback /auth /auth/* /apps /apps/*`
The pre-flight approach taken here is the same as we use for other `api/*` endpoints (https://github.com/gitpod-io/gitpod/pull/14897) and websocket connections (https://github.com/gitpod-io/gitpod/pull/15035).
Part of #9198 and https://github.com/gitpod-io/gitpod/issues/14965
1. Open the preview environment and start a workspace.
2. Take the instance id of the running workspace from the application db.
3. Hit  https://af-add-lat37f4cc0217.preview.gitpod-dev.com/api/auth/workspace-co …
> [proxy] Pre-flight server authentication related endpoints to add additional latency

- components/proxy/conf/Caddyfile
Extract some request matchers that are duplicated between different `handle` blocks into a snippet.
Part of #9198 
Existing behaviour with request to pre-flights based on  the `slow_database` feature flag is preserved.
```release-note
NONE
```
> [proxy] Extract common request matchers to a snippet

- components/gitpod-protocol/go/gitpod-config-types.go
- components/gitpod-protocol/go/scripts/generate-config.sh
In context of https://github.com/gitpod-io/gitpod/pull/15062 we need to pass config from server to ide-service.
But because of current code generator we cannot unmarshall it and marshall back additional tasks.
This PR simplifies code generated output that it has only types and rely on default go logic for marshalling.
Related to https://github.com/gitpod-io/gitpod/issues/9189
Start a workspace with IntelliJ and VS Code with .gitpod.yml with extensions/plugins/ports and see whether UI respect it.
```release-note
NONE
```
> [go] clean up gen of go types

- components/gitpod-db/go/personal_access_token.go
- components/gitpod-db/go/personal_access_token_test.go
- components/public-api-server/pkg/apiv1/tokens_test.go
MySQL would return 0 RowsModified when the updated values already match. Here, we solve it by not checking for the udpated rows and instead rely on the Get to return the not found.
Fixes https://github.com/gitpod-io/gitpod/issues/15105
Unit regression tests + 
1. Preview
2. Create PAT
3. Click edit PAT
4. Make no changes to it, press click Update
5. There's no Error.
```release-note
NONE
```
> [pat] API allows update which does not change any data

- operations/observability/mixins/self-hosted/rules/argocd/servicemonitor.yaml
Similar to https://github.com/gitpod-io/ops/pull/6900, this PR updates the serviceMonitor that is imported to our cluster with ArgoCD so we drop all metrics that we don't need.
Fixes #
```release-note
NONE
```
> Drop unused ArgoCD Metrics

- operations/observability/mixins/workspace/rules/central/nodes.yaml
- operations/observability/mixins/workspace/rules/central/workspaces.yaml
1. add image build alerts
2. simplify alerts for stopped regular workspaces
3. reduce frequency of normalized load average alerts, to make them actionable in  [#team-workspace-alerts](https://gitpod.slack.com/archives/C03QZ1NH517)
To recap, warnings should go to [#team-workspace-alerts](https://gitpod.slack.com/archives/C03QZ1NH517), and criticals should trigger pager duty. Critical alerts must also have a related runbook, Warnings do not.
The runbook for the critical alert: https://github.com/gitpod-io/runbooks/pull/408 <-- must be approved and merged before removing this PR's hold.
Fixes # n/a
1. [Observe how this would have triggered for EU this week, but, not US](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:% …
> [obs] improve workspace alerts

- components/usage/pkg/apiv1/pricer.go
- components/usage/pkg/apiv1/pricer_test.go
Removes the dependency on a workspace class named `default`
Fixes #
```release-note
NONE
```
> [usage] remove dependency on workspace class name

- components/dashboard/src/settings/PersonalAccessTokens.tsx
From
To
Fixes #
```release-note
NONE
```
> [pat] Change title from Personal Access Tokens to Access Tokens

- components/ide/jetbrains/backend-plugin/build.sh
Fail build if any of script steps are ended with error.
PR initially created at https://github.com/gitpod-io/gitpod/pull/14530, but moved here due to the necessity of a rebase for Werft Build to succeed.
Just check if Werft Build succeeds.
```release-note
NONE
```
- Close https://github.com/gitpod-io/gitpod/pull/14530 as complete.
> [JetBrains] Fail build on error

- components/supervisor/frontend/src/ide/supervisor-service-client.ts
- components/supervisor/frontend/src/index.ts
Makes sure that supervisor-frontend only check for ide and content readiness once.
fix #14782
- Open a new window with devtools.
- In this window start a workspace with IntelliJ and check that both VS Code and IntelliJ can be opened.
- Check in devtool that we send only successful request for ide and content readiness.
```release-note
NONE
```
> singleton SupervisorServiceClient

- components/ide-service/pkg/server/server.go
- components/ide-service/pkg/server/testdata/resolve_ws_config_regular_with_intellij_config.golden
- components/ide-service/pkg/server/testdata/resolve_ws_config_regular_with_intellij_config.json
[ide-service] only add warm task when workspace type is prebuild
Fixes #
```release-note
NONE
```
> [ide-service] only add warm task when workspace type is prebuild

- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/optional/GitpodForceUpdateMavenProjectsActivity.kt
Currently, when we open a prebuilt branch that has `.idea/runConfigurations` folder but doesn't have a `.idea/misc.xml` [[1](https://github.com/Gitpod-Samples/spring-petclinic/tree/update-idea-folder)] on JetBrains IDE v2022.3 (EAP), it loads like this:
The file `.idea/misc.xml` pre-defines which JDK to use, and Maven depends on the info about JDK. When the repository doesn't have this file, Maven doesn't know which JDK to use until we finish setting it up to work correctly. Due to race condition, it happens that the `forceUpdateAllProjectsOrFindAllAvailablePomFiles()` is called before the JDK is appropriately setup [[1](https://github.com/gitpod-io/gitpod/blob/edff61c347adbd1c12e861b68a91eda545980353/components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/Gitpod …
> [JetBrains] Refresh files before updating Maven projects

- components/dashboard/src/admin/UserDetail.tsx
Removes the possibility to change the professional open-source status.
This is because it would only take effect until UBP GA. In the future we can flxibly adjust the usage Limit.
Fixes #15095
```release-note
NONE
```
> [dashboard] remove admin alter OSS plan

- .github/workflows/jetbrains-auto-update-template.yml
- WORKSPACE.yaml
- components/ide/jetbrains/image/BUILD.js
- components/ide/jetbrains/image/leeway.Dockerfile
Implements https://github.com/gitpod-io/gitpod/pull/14055 for the JetBrains Backend images with the difference being we don't label the images with `io.gitpod.ide.commit`, because we don't have access to that.
```release-note
NONE
```
> Label JetBrains IDE images with their versions

- components/ide-service-api/go/config/ideconfig.go
- components/ide-service/go.mod
- components/ide-service/pkg/ocitool/resolve.go
- components/ide-service/pkg/ocitool/resolve_test.go
- components/ide-service/pkg/server/ideconfig.go
Adds versions to all IDEs when talking to the WebSocket IDE service API. This will enable the Dashboard to know what version all IDEs are at.
Fixes #
```release-note
NONE
```
> Add IDE versions to ide service

- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/pkg/components/server/deployment.go
- install/installer/pkg/components/slowserver/deployment.go
- install/installer/pkg/components/ws-manager-bridge/configmap.go
- install/installer/pkg/components/ws-manager-bridge/deployment.go
- install/installer/pkg/components/ws-manager-bridge/objects.go
- install/installer/pkg/components/ws-manager-bridge/objects_test.go
- install/installer/pkg/components/ws-proxy/deployment.go
This PR removes the `ws-manager-client-tls` mounts from WebApp/Meta deployments. Their presence causes issues in dedicated deployments where we run pure meta installations.
This PR is stacked on #15132  to facilitate its use before merging.
See installer fixture tests.
```release-note
NONE
```
> [installer] Don't mount ws-manager-client-tls in meta/webapp deployments

- components/dashboard/src/settings/PersonalAccessTokens.tsx
`Generate an access token` 
Fixes #15140
see /tokens in preview
```release-note
NONE
```
> Fix grammar in PersonalAccessTokens.tsx

- components/usage/pkg/apiv1/billing.go
- components/usage/pkg/apiv1/billing_test.go
Allow invoices with multiple items.
The plans for individuals have a fixed amount of credits, which results in multi-line invoices (see test data).
Fixes https://github.com/gitpod-io/gitpod/issues/15134
```release-note
NONE
```
> [usage] support multiple entries on invoices

- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/kind-workspace/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/common/constants.go
- install/installer/pkg/components/image-builder-mk3/networkpolicy.go
- install/installer/pkg/components/usage/networkpolicy.go
As part of #9198, a deployment called `slow-server` was added, identical to `server` but with a higher latency connection to the database.
This PR adds the `slow-server` component to the `image-builder-mk3` and `usage` component network policy ingress rules, so that ingress to those two components works for `slow-server` just as it does for the `server` component.
This means that workspace startup works correctly for workspaces started by `slow-server`.
Fixes https://github.com/gitpod-io/gitpod/issues/15027
1. Log into the preview environment.
2. Update the configcat targeting rule for the `slow_database` (non-production) feature flag for your user id.
3. Wait for 3 minutes for configcat to pull the new config or until `/api/feature-flags/slow-database` starts setting …
> [installer] Add `slow-server` to network policy ingress rules

- install/installer/cmd/testdata/render/README.md
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/kind-workspace/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/registry-facade/daemonset.go
When only the container of the registry-facade was broken, the ready-nobel of the node was not disappearing because when the registry-facade container restarts, other containers even in the same pod don't restart.
[Kubernetes docs about that](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-has-network:~:text=Indicates%20whether%20the%20container%20is%20running.%20If%20the%20liveness%20probe%20fails%2C%20the%20kubelet%20kills%20the%20container%2C%20and%20the%20container%20is%20subjected%20to%20its%20restart%20policy.%20If%20a%20container%20does%20not%20provide%20a%20liveness%20probe%2C%20the%20default%20state%20is%20Success)
This PR monitors the state of the registry-facade with the node-labeler's liveness probe. If the registry-facade container is not ready, the …
> registry-facade: Ensure that node-labeler always monitors the registr-facade container

- components/dashboard/src/contexts/FeatureFlagContext.tsx
- components/dashboard/src/settings/Plans.tsx
- components/dashboard/src/settings/Teams.tsx
Once UBP has been enabled for a user:
Fixes https://github.com/gitpod-io/gitpod/issues/14940
1. Upgrade to a paid Chargebee plan in https://jx-disable-chargebee.preview.gitpod-dev.com/plans
2. Buy a legacy Team Plan in https://jx-disable-chargebee.preview.gitpod-dev.com/teams
3. Once it's active, assign yourself one seat of this Team Plan
4. Now, create a team called "Gitpod [Something]" to unlock usage-based
5. If you now go to https://jx-disable-chargebee.preview.gitpod-dev.com/plans, you can no longer upgrade to any Chargebee paid plan -- you can only cancel by going into `billing` ⏩
6. If you go to https://jx-disable-chargebee.preview.gitpod-dev.com/teams, you can no longer create a new legacy Team Plan -- you can only cancel by going into `billing` ⏩
```release-note
[gitpod.io] …
```
> [UBP] Disable subscriptions to old plans after UBP has been enabled

- components/dashboard/src/projects/Prebuild.tsx
- components/dashboard/src/projects/Prebuilds.tsx
- components/dashboard/src/projects/Project.tsx
- components/server/ee/src/prebuilds/prebuild-manager.ts
Make the 'Run Prebuild' button actually do what it says 100% of the time.
Fixes https://github.com/gitpod-io/gitpod/issues/15144
1. Create a Team
2. Create a Project (this runs a first prebuild)
3. When the prebuild has finished successfully, try to re-trigger the prebuild -- this should always work (i.e. it should always start a new prebuild, and not redirect you to an older successful prebuild)
```release-note
Always allow running new prebuilds, regardless of any previous prebuild state
```
> Always allow running new prebuilds, regardless of any previous prebuild state

- components/gitpod-db/go/cost_center.go
- components/usage/pkg/apiv1/billing.go
Increment the billing cycle on after finalize invoice webhook.
Fixes #14992
```release-note
NONE
```
> [usage] increment cycle on finalize invoice

- components/dashboard/src/components/UsageBasedBillingConfig.tsx
- components/server/src/user/user-service.ts
This change removes the requirement for a team to have an active stripe subscription in order to see their balance and start workspaces. 
It only depends on whether they have credits available. This change allows to grant a spending limit and/or credits to teams that are still on the internal `other` strategy.
Fixes #15137
```release-note
NONE
```
> [ubp] allow usage of team without stripe sub

- components/server/src/auth/authenticator.ts
- components/server/src/auth/generic-auth-provider.ts
- components/server/src/prometheus-metrics.ts
The intention here is to make our reporting and alerting more precise, as mentioned in #15175 .
Fixes #15175
```release-note
NONE
```
> [server] IAM: Report missing session info as client error

- .gitpod.yml
- dev/preview/workflow/preview/configure-workspace.sh
Fix a check in configure-workspace and add a flag for signalling installation of the context.
Fixes #
```release-note
NONE
```
> dev/preview:configure-workspace fix

- operations/observability/mixins/IDE/dashboards.libsonnet
- operations/observability/mixins/IDE/dashboards/components/ide-service.json
Add IDE Service Dashboard to Grafana. It's separated into two categories: Client and Server.
1. Go to Grafana.
2. Create a new (temporary) dashboard.
3. Copy & paste the JSON content at "Dashboard Settings >> JSON Model".
4. Check if the panels are displayed like the screenshot above.
5. Delete the temporary dashboard.
```release-note
NONE
```
> [observability] Add IDE Service Dashboard

- components/dashboard/src/settings/PersonalAccessTokens.tsx
Pagination with 50 entries per page.
Fixes #15098 
[Preview env](https://lau-list-p203b8d58fc.preview.gitpod-dev.com/tokens)
Pagination is a bit cumbersome to test.
1. Change [this](https://github.com/gitpod-io/gitpod/blob/20b06ef1bbeca0905ec0c33670c1581df807d67d/components/dashboard/src/settings/PersonalAccessTokens.tsx#L84) to a low number (e.g. 2).
2. Run `yarn telepresence` in `components/dashboard`.
3. See the pagination.
```release-note
NONE
```
> [pat] Paginate list tokens view

- .github/workflows/code-nightly.yml
Point the workflow to https://github.com/gitpod-io/gitpod/issues/14977
```release-note
NONE
```
> Point code nightly worklow to the release branch

- components/gitpod-protocol/src/admin-protocol.ts
- components/gitpod-protocol/src/gitpod-service.ts
Probably accidentally put in the GitpodServer
Fixes #
```release-note
NONE
```
> [server] Move admin endpoints on GitpodServer to AdminServer

- operations/observability/mixins/self-hosted/rules/argocd/servicemonitor.yaml
- operations/observability/mixins/self-hosted/rules/pyrra/servicemonitor.yaml
Following [the RFC](https://www.notion.so/gitpod/Monitoring-central-Migration-to-Grafana-Cloud-6c29eb19a8c445aa84d680ba1c68bc66#febbbbc524a14614b7cd9c45e1af3bdc), we can decrease metric costs by reducing the frequency that we scrape metrics endpoints.
This PR updates all our ServiceMonitors that are imported by different monitoring-satellites to 60s.
Fixes #
```release-note
NONE
```
> Increase scrape interval to decrease datapoints per minute

- components/gitpod-db/go/workspace_instance.go
- components/usage/pkg/apiv1/pricer_test.go
- components/usage/pkg/apiv1/usage.go
- components/usage/pkg/apiv1/usage_test.go
We have three workspace instances in prod that don't have a stoppingTime but a stoppedTime. I think falling back to stoppedTime in case stoppingTime is not set makes sense (after all they never were in a stopping phase, because they errored) and also makes the component more robust.
Fixes #
```release-note
NONE
```
> [usage] handle no stopping but stopped time

- components/dashboard/src/settings/SelectIDE.tsx
- components/gitpod-protocol/src/ide-protocol.ts
This PR is simply adding versions below the icons of all IDEs in the IDE switcher component (used during on-boarding and always available in the user preferences). 
This is partially a lie because we don't associate VS Code Desktop with a version, but it holds true for the rest.
It's a relatively easy win because we:
1. Already tag all newly-built IDE images with their version strings (https://github.com/gitpod-io/gitpod/pull/15082, https://github.com/gitpod-io/gitpod/pull/14055)
2. We already implemented the functionality in [`ide-service`](https://github.com/gitpod-io/gitpod/tree/main/components/ide-service) so that it returns the IDE versions along the IDE options (https://github.com/gitpod-io/gitpod/pull/15081)
With this we can do two things at once:
- keep our users informed what …
> Add IDE versions to the dashboard

- components/common-go/experiments/flags.go
- components/public-api-server/pkg/apiv1/oidc.go
- components/public-api-server/pkg/apiv1/oidc_test.go
- components/public-api-server/pkg/server/server.go
Adds stub RPCs for OIDCService.
When the user is part of the experiment, the service returns Unimplemented (for now). Otherwise, it returns Unathorized.
Part of the following:
* https://github.com/gitpod-io/gitpod/issues/15150
* https://github.com/gitpod-io/gitpod/issues/15152
* https://github.com/gitpod-io/gitpod/issues/15153
* https://github.com/gitpod-io/gitpod/issues/15154
* https://github.com/gitpod-io/gitpod/issues/15155
unit tests
```release-note
NONE
```
> [oidc] Add stub RPCs

- components/gitpod-db/go/cost_center.go
- components/usage/pkg/apiv1/billing.go
We receive finalize invoice events also before a cost center is expired. For instance when a user first subscribes but also when a user cancels their plan. The `IncrementBillingCycle` method should just skip in such cases, also we should not return an error once the usage has been recorded in the DB.
Fixes #15203
```release-note
NONE
```
> [usage] make increment billing cycle more robust

- .werft/jobs/build/deploy-to-preview-environment.ts
- .werft/jobs/build/prepare.ts
- .werft/platform-delete-preview-environment.ts
- .werft/platform-delete-preview-environments-cron.ts
- .werft/platform-delete-preview-environments-cron.yaml
- .werft/util/preview.ts
- .werft/vm/vm.ts
- dev/preview/previewctl/BUILD.yaml
- dev/preview/previewctl/cmd/stale.go
- dev/preview/previewctl/cmd/workspaces.go
- dev/preview/previewctl/pkg/preview/status.go
- dev/preview/workflow/preview/configure-workspace.sh
Part 3 in https://github.com/gitpod-io/ops/issues/5226
Updates the werft jobs to use `previewctl list stale`
https://werft.gitpod-dev.com/job/gitpod-custom-aa-prev-clean-up-refactor-werft.5
Fixes https://github.com/gitpod-io/ops/issues/5226
```release-note
NONE
```
> preview delete cron use previewctl list stale

- components/dashboard/src/Menu.tsx
- components/dashboard/src/contexts/FeatureFlagContext.tsx
- components/dashboard/src/projects/Events.tsx
- components/dashboard/src/projects/Prebuild.tsx
- components/dashboard/src/projects/Prebuilds.tsx
- components/dashboard/src/projects/Project.tsx
- components/dashboard/src/projects/Projects.tsx
- components/dashboard/src/service/public-api.ts
- components/gitpod-protocol/go/gitpod-service.go
Behind a feature flag, list projects using Public API
Fixes https://github.com/gitpod-io/gitpod/issues/14896
Preview
1. Add a project
2. See the project is listed
3. Check request is made against Public API
```release-note
NONE
```
> [dashboard] List projects using Public API

- components/server/ee/src/workspace/gitpod-server-impl.ts
If I had previsously signed up I cannot resubscribe because of this error. Let's have people reach out for currency changes.
Fixes #15211
```release-note
NONE
```
> [server] don't fail on currency change

- .gitpod.yml
- .werft/aks-installer-tests.yaml
- .werft/build.yaml
- .werft/cleanup-installer-tests.yaml
- .werft/debug.yaml
- .werft/eks-installer-tests.yaml
- .werft/gke-installer-tests.yaml
- .werft/ide-integration-tests-startup.yaml
- .werft/k3s-installer-tests.yaml
- .werft/platform-delete-preview-environment.yaml
- .werft/platform-delete-preview-environments-cron.yaml
- .werft/platform-trigger-artificial-job.yaml
- .werft/platform-trigger-werft-cleanup.yaml
- .werft/workspace-run-integration-tests.yaml
- dev/image/Dockerfile
Bumps Leeway to version 0.7.1. The previous version was 0.5.2 so this includes quite a few changes. Most of them is about cleaning up unused features and code, but some notable changes are:
1. in [0.6.0](https://github.com/gitpod-io/leeway/releases/tag/v0.6.0) we "Log go mod download only when verbose" which will drastically reduce the logs you see in Werft (@sagor999 you'll like this I think as you created the [original report of this issue](https://github.com/gitpod-io/leeway/issues/107) - and thanks to @csweichel for making the fix in Leeway)
2. In [0.7.1](https://github.com/gitpod-io/leeway/releases/tag/v0.7.1) Enable running Leeways scripts in parallel. This is needed for https://github.com/gitpod-io/gitpod/issues/14707 and https://github.com/gitpod-io/gitpod/issues/14704
Part of …
> Use Leeway version v0.7.1

- .github/workflows/jetbrains-auto-update-template.yml
- components/ide/jetbrains/backend-plugin/leeway.Dockerfile
- components/ide/jetbrains/cli/cmd/root.go
- components/ide/jetbrains/image/BUILD.js
- components/ide/jetbrains/image/create-supervisor-config.js
- components/ide/jetbrains/image/hot-deploy.sh
- components/ide/jetbrains/image/leeway.Dockerfile
- components/ide/jetbrains/image/resolve-latest-ide-version.sh
- components/ide/jetbrains/image/status/main.go
- components/ide/jetbrains/image/supervisor-ide-config_clion-latest.json
- components/ide/jetbrains/image/supervisor-ide-config_goland-latest.json
- components/ide/jetbrains/image/supervisor-ide-config_goland.json
- components/ide/jetbrains/image/supervisor-ide-config_intellij-latest.json
- components/ide/jetbrains/image/supervisor-ide-config_intellij.json
- components/ide/jetbrains/image/supervisor-ide-config_phpstorm-latest.json
- components/ide/jetbrains/image/supervisor-ide-config_phpstorm.json
- components/ide/jetbrains/image/supervisor-ide-config_pycharm-latest.json
- components/ide/jetbrains/image/supervisor-ide-config_pycharm.json
- components/ide/jetbrains/image/supervisor-ide-config_rider-latest.json
- components/ide/jetbrains/image/supervisor-ide-config_rider.json
- components/ide/jetbrains/image/supervisor-ide-config_rubymine-latest.json
- components/ide/jetbrains/image/supervisor-ide-config_rubymine.json
- components/ide/jetbrains/image/supervisor-ide-config_webstorm-latest.json
- components/ide/jetbrains/image/supervisor-ide-config_webstorm.json
This PR changes the file structure for JetBrains IDE images. The previous structure would allow only a single IDE to be stored, with the new approach we can layer multiple IDEs without risk of overriding each other.
Related to https://github.com/gitpod-io/gitpod/issues/6740
1. For *stable*, start a workspace for a couple of JB IDE and make sure they work as expected, including customizations done via the backend-plugin to the Backend Control Center, or custom actions are visible, meaning the plugin is loaded correctly.
2. For *latest*, TODO
```release-note
NONE
```
> allow to layout multiple JB product layers in the same image

- WORKSPACE.yaml
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
Update code to `1.74.0`
A part of https://github.com/gitpod-io/gitpod/issues/14977
```release-note
NONE
```
> Update Code to `1.74.0`

- components/content-service/pkg/archive/tar.go
For details see https://github.com/gitpod-io/gitpod/issues/11183
Fixes https://github.com/gitpod-io/gitpod/issues/11183
1. Run these tests :point_down: 
- Open a workspace. In the terminal execute:
```
touch basic
sudo touch root-file
touch executable-file
chmod +x executable-file
touch suid-file
chmod 2555 suid-file
mkdir suid-directory
chmod g+s suid-directory
```
- Check the output of `ls -lat`, should be similar to
```
drwxr-x--- 8 gitpod gitpod 4096 Apr 28 17:31 .
-r-xr-sr-x 1 gitpod gitpod    0 Apr 28 17:31 suid-file
drwxr-sr-x 2 gitpod gitpod    6 Apr 28 17:31 suid-directory
-rwxr-xr-x 1 gitpod gitpod    0 Apr 28 17:30 executable-file
-rw-r--r-- 1 root   root      0 Apr 28 17:30 root-file
-rw-r--r-- 1 gitpod gitpod    0 Apr 28 17:30 basic
```
- Stop and open the workspace
- Open a …
> [content-service] Prevent permission denied during content init

- install/installer/cmd/render_test.go
Switch the golden files comparison to use `cmp.Diff` - this produces a more readable diff for golden files.
**Important** - this does not use the FixtureTest in `common-go/testing/fixtures.go` as suggested - that is designed around the config being a JSON file, whereas the Installer requires it to be YAML and is injected as a string that the Installer reads, not a struct. Whilst we could make this change, it's probably not massively useful to the `components` and would require a lot of changes which may introduce problem.
Fixes #12578
1. change an `output.golden` file (eg add "err" to the end of the file)
2. run `go test ./cmd/...`
3. read the failure diff
4. stash the change and rerun - should see no failure
```release-note
NONE
```
Valid …
> [installer]: improve the comparison method for the golden files

- components/dashboard/src/components/UsageLimitReachedModal.tsx
- components/dashboard/src/start/CreateWorkspace.tsx
- components/dashboard/src/start/StartPage.tsx
- components/gitpod-protocol/src/util/gitpod-host-url.ts
Generalizes the pay wall on start and create ws and changes the link to point to /billing
Fixes #15188
```release-note
NONE
```
> [dashboard] consistent pay wall

- components/gitpod-protocol/src/messaging/client-call-metrics.ts
- components/gitpod-protocol/src/util/grpc.ts
- components/gitpod-protocol/src/util/nice-grpc.ts
add grpc_client_handling_seconds metrics for nice-grpc
Fixes #
1. start a workspace from this branch in gitpod.io
2. run `./dev/preview/portforward-monitoring-satellite.sh -c harvester`
3. go to grafana, using explore query `grpc_client_handling_seconds_bucket{grpc_service="ide_service_api.IDEService"}`
4. you should see some metrics
```release-note
NONE
```
> add grpc_client_handling_seconds metrics for nice-grpc

- components/dashboard/src/projects/Projects.tsx
- components/public-api-server/pkg/apiv1/project.go
- components/public-api-server/pkg/apiv1/project_test.go
* Depends on https://github.com/gitpod-io/gitpod/pull/14938
* Fixes https://github.com/gitpod-io/gitpod/issues/15199
1. Preview
2. Create a project
3. Delete the project
4. Observe project is deleted
5. Observe request (in the Network tab) was made against the Public API
```release-note
NONE
```
/hold for dependency on https://github.com/gitpod-io/gitpod/pull/14938
> [public-api] Implement ProjectsService.DeleteProject

- dev/preview/workflow/preview/preview.sh
Run `dev/preview:create-preview` and `dev/preview:build` in parallel. Add `dev/preview:deploy-monitoring-satellite` and run it in parallel with `dev/preview:deploy-gitpod`
Fixes https://github.com/gitpod-io/gitpod/issues/14707
Fixes https://github.com/gitpod-io/gitpod/issues/14704
`leeway run dev:preview` should still work, but scripts should run in parallel where possible.
```sh
```
```release-note
NONE
```
N/A
> Parallelise dev:preview and deploy monitoring satellite automatically

- components/dashboard/src/components/UsageView.tsx
- components/dashboard/src/projects/NewProject.tsx
- components/dashboard/src/teams/NewTeam.tsx
Following the changes to graduate Teams, Projects, and Billing from beta and early access, this will remove these labels from the dashboard. See [relevant discussion](https://gitpod.slack.com/archives/C027AUU7BC3/p1670507118066149) (internal).
See relevant docs: 
- [Teams](https://www.gitpod.io/docs/configure/teams)
- [Projects](https://www.gitpod.io/docs/configure/projects)
- [Billing](https://www.gitpod.io/docs/configure/billing)
1. Try creating a new **team** and notice there's no beta label anymore.
2. Try creating a new **project** and notice there's no beta label anymore.
3. Create a team and go to team usage and notice there's no early access label anymore.
```release-note
Remove beta and early access labels for Teams, Projects, and Billing
``` …
> Remove beta and early access labels for Teams, Projects, and Billing

- .gitpod.yml
- .werft/aks-installer-tests.yaml
- .werft/build.yaml
- .werft/cleanup-installer-tests.yaml
- .werft/debug.yaml
- .werft/eks-installer-tests.yaml
- .werft/gke-installer-tests.yaml
- .werft/ide-integration-tests-startup.yaml
- .werft/k3s-installer-tests.yaml
- .werft/platform-delete-preview-environment.yaml
- .werft/platform-delete-preview-environments-cron.yaml
- .werft/platform-trigger-artificial-job.yaml
- .werft/platform-trigger-werft-cleanup.yaml
- .werft/workspace-run-integration-tests.yaml
- dev/image/Dockerfile
This moves the Leeway cache and build directory to `/var/tmp` - see https://github.com/gitpod-io/gitpod/issues/15060 for the reasoning behind this.
Fixes https://github.com/gitpod-io/gitpod/issues/15060
```release-note
NONE
```
> Set LEEWAY_CACHE_DIR and LEEWAY_BUILD_DIR

- components/dashboard/src/components/UsageBasedBillingConfig.tsx
Append "excluding VAT" to prices on billing pages
```release-note
Quote Gitpod prices as excluding VAT. 
```
> Append "excluding VAT" to prices on billing pages

- dev/preview/workflow/config/monitoring-satellite.yaml
Since we're no longer using the Prometheus integration with Kubescape anywhere anymore, there's no reason to keep it in preview environments as well.
There are a couple of issues and PRs for extra context[[1](https://github.com/gitpod-io/ops/pull/7329)][[2](https://github.com/gitpod-io/ops/pull/7065)][[3](https://github.com/gitpod-io/security/issues/84)]
Fixes #
```release-note
NONE
```
> Remove Kubescape from preview environments

- components/common-go/experiments/configcat.go
- components/common-go/experiments/flags.go
- components/common-go/experiments/types.go
- components/supervisor/BUILD.yaml
- components/supervisor/go.mod
- components/supervisor/go.sum
- components/supervisor/pkg/metrics/reporter.go
- components/supervisor/pkg/ports/exposed-ports.go
- components/supervisor/pkg/ports/ports-config.go
- components/supervisor/pkg/ports/ports-config_test.go
- components/supervisor/pkg/serverapi/publicapi.go
- components/supervisor/pkg/supervisor/git.go
- components/supervisor/pkg/supervisor/supervisor.go
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/insecure-s3-setup/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/ide-metrics/configmap.go
- NON Production [ConfigCat](https://app.configcat.com/08da1258-64fb-4a8e-8a1e-51de773884f6/08da1258-6541-4fc7-8b61-c8b47f82f3a0/08da1258-6512-4ec0-80a3-3f6aa301f853)
We tested the following cases:
```release-note
NONE
```
> Use public api in supervisor

- install/installer/pkg/config/v1/config.md
- install/installer/scripts/structdoc.go
1. fixes the config struct documentation script as the presence of env reflect tags had broken it
1. update the config docs
Run `make config-doc`
```release-note
NONE
```
> [installer]: fix config struct documentation

- operations/observability/mixins/IDE/dashboards/components/browser-overview.json
- operations/observability/mixins/IDE/dashboards/components/code-browser.json
- operations/observability/mixins/IDE/dashboards/components/ide-service.json
- operations/observability/mixins/IDE/dashboards/components/openvsx-mirror.json
- operations/observability/mixins/cross-teams/dashboards/gitpod-connect-server.json
- operations/observability/mixins/cross-teams/dashboards/gitpod-grpc-client.json
- operations/observability/mixins/cross-teams/dashboards/gitpod-grpc-server.json
- operations/observability/mixins/meta/dashboards/components/meta-overview.json
- operations/observability/mixins/meta/dashboards/components/server-garbage-collector.json
- operations/observability/mixins/meta/dashboards/components/server.json
- operations/observability/mixins/meta/dashboards/components/usage.json
- operations/observability/mixins/meta/dashboards/components/ws-manager-bridge.json
- operations/observability/mixins/self-hosted/dashboards/argocd/argocd.json
- operations/observability/mixins/self-hosted/dashboards/observability/cardinality-management-overview.json
- operations/observability/mixins/workspace/dashboards/components/agent-smith.json
- operations/observability/mixins/workspace/dashboards/coredns.json
- operations/observability/mixins/workspace/dashboards/node-problem-detector.json
- operations/observability/mixins/workspace/dashboards/registry-facade-blobsource.json
- operations/observability/mixins/workspace/dashboards/workspace-psi.json
[observability] fix datasource in preview environment
This PR change hard code `P4169E866C3094E38` to variable `${datasource}` to make preview environment also work
Fixes #
1. open this branch in gitpod.io
2. run `./dev/preview/portforward-monitoring-satellite.sh -c harvester`
3. go to preview environment grafana
4. check every dashboard, it should work
```release-note
NONE
```
> [observability] fix datasource in preview environment

- operations/observability/mixins/IDE/dashboards/components/ide-service.json
Adding a widget for client latency metrics 
Co-authored-by: Victor Nogueira <victor@gitpod.io>
Fixes #
Manually tested in https://grafana.gitpod.io/d/iCuCOPFVz/ide-service?orgId=1&from=now-1h&to=now
```release-note
NONE
```
> [ide-service]: update grafana dashboard

- install/installer/scripts/kots-install.sh
Reports in [Discord](https://discord.com/channels/816244985187008514/1046633264514863116/1046633264514863116) of people having issues where the `/tmp/gitpod.config.yaml` file already exists, meaning the `config init` fails.
This uses `--overwrite` to avoid that problem entirely
Install via KOTS
```release-note
[installer]: make the kots install overwrite the config if exists
```
> [installer]: make the kots install overwrite the config if exists

- components/dashboard/src/settings/PersonalAccessTokens.tsx
Follow up from https://github.com/gitpod-io/gitpod/pull/15201.
See also relevant discussion in https://github.com/gitpod-io/gitpod/pull/15201#issuecomment-1341137103 and follow-up issue to improve the label component in https://github.com/gitpod-io/gitpod/issues/15218.
|-|-|
| <img width="311" alt="label-before" src="https://user-images.githubusercontent.com/120486/206210389-8c436caa-1db9-4767-bfaa-7274d0f53dbb.png"> | <img width="311" alt="label-after" src="https://user-images.githubusercontent.com/120486/206210410-d0b5d770-d550-4050-9c66-c7455fd12783.png"> |
1. Go to /tokens
2. Notice the label visual update
```release-note
NONE
```
> Update beta label on access  tokens

- components/dashboard/package.json
- components/dashboard/src/components/Tooltip.tsx
- components/dashboard/src/settings/TokenEntry.tsx
- yarn.lock
Adds a tooltip w/ the full expiration date of a Personal Access Token for expired tokens.
The positioning currently used for tooltips results in some potential inherited styling issues. For the PAT expired tooltip, it wasn't displaying due to a parent container using the `truncate` class (which it needs to and is ok). A class of these types of bugs can be resolved by rendering the Tooltip outside of the DOM hierarchy the of the React component structure via React Portals (I used `react-portal` for this). This appends the node to the `document.body`. I also used `react-popper`, which assists in calculating the positioning of the tooltip in comparison to the target that shows it on hover. The `react-datepicker` library we use also uses `react-popper`, and I've used it in the past and been …
> Adding a tooltip w/ full expiration date

- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-workspace/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/ws-daemon/daemonset.go
Follow up https://github.com/gitpod-io/gitpod/pull/15053
Fixes #
https://loom.com/share/6b0935660168482d88c92680293b77e9
- Node label, gitpod.io/ws-daemon_ready_ns_default disappears when deleting a ws-daemon container and turn on when registry-facade comes back
- Node label, gitpod.io/ws-daemon_ready_ns_default disappears when deleting a ws-daemon pod and turns on when rws-daemon come back
```release-note
Do not land workspaces on the node with broken ws-daemon
```
> ws-daemon: Do not land workspaces on the node with broken ws-daemon

- components/dashboard/src/projects/ProjectSettings.tsx
- components/gitpod-protocol/src/protocol.ts
Allow selecting the workspace class for prebuilds
Fixes #14811
- [join this team](https://sefftinge-ab2f42f948.preview.gitpod-dev.com/teams/join?inviteId=46a123e8-225d-4631-9bf4-ff786b2f31c6)
- [start a workspace on this branch](https://sefftinge-ab2f42f948.preview.gitpod-dev.com/#https://github.com/svenefftinge/2048-in-terminal/tree/se/ws-class)
- Verify that the `prebuild.txt` contains information about using a small workspace class
- Verify that running `gp info` reveals that the workspace is running in a default workspace class
```release-note
Allow setting workspace class for prebuilds
```
> [dashboard] allow setting ws class for prebuilds

- components/dashboard/src/Analytics.tsx
- components/server/src/analytics.ts
- components/server/src/workspace/gitpod-server-impl.ts
This PR introduces cookieless tracking for the webapp and server. This is done so that users are identified consistently throughout the website and the webapp when [#2938](https://github.com/gitpod-io/website/pull/2938) on the website is merged. The following changes are introduced:
- users that expressed their consent to tracking on the website (which leads to the `gp-analytical` cookie to be set for the `.gitpod.io` domain) continue to be tracked with the anonymous ID that can be read from the `ajs_anonymous_id` cookie
- users that did not express consent to tracking are tracked through a cookieless ID that is created by hashing a combination of the user's IP, user agent, and today's date. If the IP or user agent are not available (might happen in preview environments as the IP …
> [Analytics] adopt cookieless ID on dashboard and server

- .werft/jobs/build/job-config.ts
- dev/preview/BUILD.yaml
Fixes #
```release-note
NONE
```
> Default to letsencrypt cert isuser

- components/common-go/experiments/configcat.go
- components/common-go/experiments/flags.go
- components/common-go/experiments/types.go
- components/supervisor/BUILD.yaml
- components/supervisor/go.mod
- components/supervisor/go.sum
- components/supervisor/pkg/metrics/reporter.go
- components/supervisor/pkg/ports/exposed-ports.go
- components/supervisor/pkg/ports/ports-config.go
- components/supervisor/pkg/ports/ports-config_test.go
- components/supervisor/pkg/serverapi/publicapi.go
- components/supervisor/pkg/supervisor/git.go
- components/supervisor/pkg/supervisor/supervisor.go
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/ide-metrics/configmap.go
Review only commit https://github.com/gitpod-io/gitpod/pull/15274/commits/e081051ad939278d68faa63642fd1a8c38c362fe
Test also
```golang
package main
import (
"fmt"
)
var t TestInterface
var t2 TestInterface
func main() {
t = NewImplement()
t.Echo("hello")
t2 = NewImplement2()
t2.Echo("hello")
}
type TestInterface interface {
Echo(something string)
}
type Implement struct {
hello *string
}
func NewImplement() *Implement {
return nil
}
func NewImplement2() TestInterface {
return nil
}
var _ TestInterface = (*Implement)(nil)
// Echo implements TestInterface
func (s *Implement) Echo(something string) {
if s == nil {
fmt.Println("s is nil")
return
}
fmt.Println(*s.hello, something)
}
```
Fixes #
- Open workspace with repo that will buildimage i.e. https://github.com/gitpod-io/openvscode-server …
> Fix supervisor panic when tkns and publicapi Service is nil

- components/iam/go.mod
- components/iam/go.sum
- components/iam/pkg/oidc/router.go
- components/iam/pkg/server/server.go
Fixes #
Run locally with `cd components/iam && go run main.go run` and visit localhost:9002/oidc/start and observe hello printed
```release-note
NONE
```
> [iam] Setup chi mux for routing

- components/ide/jetbrains/backend-plugin/hot-deploy.sh
Add "Rider" and "CLion" IDEs to backend-plugin/hot-deploy.sh
Open a PR in Gitpod which has a preview environment, and confirm if backend-plugin/hot-deploy.sh works as expected.
```release-note
NONE
```
> Add "Rider" and "CLion" IDEs to backend-plugin/hot-deploy.sh

- components/gitpod-db/src/typeorm/code-sync-resource-db.spec.db.ts
- components/gitpod-db/src/typeorm/code-sync-resource-db.ts
Updates `/v1/collection` endpoint response
Ref: https://github.com/microsoft/vscode/pull/168115 `src/vs/platform/userDataSync/common/userDataSyncStoreService.ts`
```release-note
NONE
```
> [code-sync] Update `/v1/collection` endpoint response

- components/dashboard/src/contexts/FeatureFlagContext.tsx
- components/dashboard/src/projects/ProjectSettings.tsx
- components/dashboard/src/projects/RemoveProjectModal.tsx
Adds a "Remove Project" button on the project settings page.
Clicking the button brings up the same modal that is shown from the Projects list page when using the context menu action for removing.
To help keep this PR small I'll open a followup one that updates the Projects list page use the new `<RemoveProjectModal/>` component, along with a few other improvements for that page.
Fixes #14251
**Preivew Env:** https://bmh-deleted93c550a0b.preview.gitpod-dev.com/
* Create a new Project
* Navigate to the Settings page for that project
* Scroll to the bottom and click the `Remove Project` button
* You should see a confirmation modal that you can dismiss, or proceed with.
* After the project is deleted you should get navigated to the Projects list page
```release-note
Projects can now be …
```
> Add a remove project button on the project settings page

- test/tests/components/ws-manager/dotfiles_test.go
see [internal chat](https://gitpod.slack.com/archives/C01KGM9BH54/p1670903443620399)
Fixes #
Check werft test result https://werft.gitpod-dev.com/job/gitpod-build-hw-dotfile.2 or 
- Exec `cd test/tests/components/ws-manager` and `go test -v ./... -run TestDotfiles -kubeconfig=/home/gitpod/.kube/config -username gitpod-integration-test` for dotfile test
- Or exec `werft run github -j .werft/workspace-run-integration-tests.sh` for all
```release-note
NONE
```
> [test] fix dotfile test failed

- components/server/src/ide-service.ts
During deployment of ide-service, server by using nice-grpc is struggling to connect to new instances of ide-service. We are investigating separately what is going wrong, but for now we also want to increase overall timeout from 30 to 90 sec to reduce a risk of failed workspace startups. See [internal discussion](https://gitpod.slack.com/archives/C03QM0ZHF5Z/p1670926091722999).
Fixes #
```release-note
NONE
```
> [server] increate request timeout to ide-service to 5 sec

- components/gitpod-db/go/dbtest/oidc_client_config.go
- components/gitpod-db/go/oidc_client_config.go
- components/gitpod-db/go/oidc_client_config_test.go
- components/gitpod-db/src/typeorm/migration/1670850042413-CreateOIDCClientConfigTable.ts
Initial db setup for OIDC Client Config
* Relates to https://github.com/gitpod-io/gitpod/issues/15150
Unit tests
```release-note
NONE
```
> [oidc] Setup db

- components/common-go/experiments/configcat.go
- components/common-go/experiments/types.go
Despite having a levelled configcat logger, it doesn't actually check the level in our wrapper before logging.
This change eliminates logs whenever a new set of flags is fetched. See [logs here](https://console.cloud.google.com/logs/query;query=%22fetching%20from%22;timeRange=PT1H;cursorTimestamp=2022-12-13T14:37:15.749007537Z?authuser=0&project=gitpod-191109)
Fixes #
```release-note
NONE
```
> [configcat] Stop logging info messages

- components/iam/pkg/config/config.go
- components/iam/pkg/server/server.go
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/common/common.go
- install/installer/pkg/common/constants.go
- install/installer/pkg/components/iam/configmap.go
- install/installer/pkg/components/iam/deployment.go
This PR mounts database config as a secret onto IAM. We've previously used ENV variables to pass all of this information, but files are much safer and prevent env enumeration.
Changes:
1. Make it possible to get the DB env as a Volume and Volume Mount
2. Bind these to the IAM component
3. Extend IAM config to inject the path to the mounted volume
This change does not yet use the mounted secrets. We'll first validate this works before:
* Adding tests to the volume and volume mount injection
* Using the mounted files
Fixes #
Preview
1. IAM component has the the secret mounted under `/secrets/database-config`
```
➜ k exec iam-5c8c575cbc-2vm7k -it -- /bin/sh
Defaulted container "iam" out of: iam, kube-rbac-proxy, database-waiter (init)
/ $ ls /secrets/
database-config
/ $ ls …
```
> [iam] Mount database secret as a file

- .gitpod.yml
This adds @akosyakov's extension `gitpod-monitor` to the list of vscode extensions we use in the repository. The extension is a great way to inform users of the load they're workspace is under, helping identify resource-heavy tasks that might be worth optimising.
Fixes https://github.com/gitpod-io/gitpod/issues/15061
Open a workspace, see the extension as the bottom:
```release-note
NONE
```
N/A
> Add gitpod-monitor by default

- components/common-go/experiments/configcat.go
- components/common-go/experiments/types.go
This reverts commit fbac9a213f6406a704d669245c0fb892a1e6cb16.
Can panic on request https://console.cloud.google.com/logs/query;query=resource.labels.pod_name%20:%20%2528%22public-api-server%22%2529;timeRange=PT1H;cursorTimestamp=2022-12-14T10:02:23.880147315Z?authuser=0&project=gitpod-191109
Fixes #
```release-note
NONE
```
> Revert "[configcat] Stop logging info messages"

- .github/workflows/poc-build.yml
Add a Proof of Concept to run our main build in GitHub actions. The intention is to get this PoC into the hands of our colleagues for a more informed discussion. 
For details, see:
https://www.notion.so/gitpod/Main-Build-via-GitHub-Actions-PoC-5d157d5f4c604a3a89d4e35ee26da3a7
Fixes https://github.com/gitpod-io/ops/issues/5749
See https://www.notion.so/gitpod/Main-Build-via-GitHub-Actions-PoC-5d157d5f4c604a3a89d4e35ee26da3a7
```release-note
NONE
```
> Add PoC to build in GitHub actions

- components/ide/jetbrains/launcher/main.go
See [logs](https://console.cloud.google.com/logs/query;query=%22panic:%20runtime%20error:%20slice%20bounds%20out%20of%20range%20%5B:-1%5D%22%0A%22resolveUserEnvs%22;timeRange=P2D;pinnedLogId=2022-12-14T09:37:40.193710526Z%2Fit75m546wgdrp87t;lfeCustomFields=resource%252Flabels%252Fpod_name;cursorTimestamp=2022-12-14T09:34:11.535276598Z?project=workspace-clusters). Also adding logging to help us investigate the root cause.
Fixes #
```release-note
NONE
```
> [jb-launcher] no panic on resolving user env vars

- install/installer/cmd/testdata/render/kind-workspace/output.golden
- install/installer/pkg/components/image-builder-mk3/deployment.go
Update image-builder-mk3 node affinity to `gitpod.io/workload_workspace_services` for workspace installs.
Should not have an effect for gitpod.io, but removes dependency of `gitpod.io/workload_meta` label in workspace clusters for image builder, e.g. needed for dedicated. Context: https://github.com/gitpod-io/gitpod/issues/7845#issuecomment-1351330180
Verified that the `gitpod.io/workload_workspace_services` label is present on the `services` nodes (which run the image-builder) in workspace clusters.
```release-note
NONE
```
> [image-builder] Change affinity in ws clusters

- components/dashboard/src/Menu.tsx
Not sure if the code changes here will work, but this will attempt to fix https://github.com/gitpod-io/gitpod/issues/11588.
Any hints or help is appreciated. 🏀 
See [relevant discussion](https://gitpod.slack.com/archives/C01KPEPNBD0/p1671022341946149) (internal). Cc @loujaybee 
Fixes https://github.com/gitpod-io/gitpod/issues/11588
1. Join a team as a non-owner and notice that the team _Usage_ tab is no longer visible for you.
```release-note
Show team usage tab only for team owners
```
> Show team usage tab only for team owners

- components/dashboard/src/App.tsx
- components/dashboard/src/hooks/use-analytics-tracking.ts
- components/dashboard/src/theme-context.tsx
This was a result of going through the `<App/>` component to get an understanding for how to plug in some new setup flows, and finding a few things aiming at cleaning up / improving the component to make it a bit easier to reason about and maintain. Made the following changes:
* Moved location/analytics tracking hooks into a new `useAnalyticsTracking()` hook
* Moved the theme defaulting/local storage tracking hook into the `ThemeContextProvider` with the rest of the theme-related setup/state management.
* Wrapped `hashchange` event listener w/ `useEffect()` so we don't subscribe w/ a new listener on each render.
**Preview Env:** https://bmh-top-app-updates.preview.gitpod-dev.com
Visually, nothing should change for the end user. Loading up the dashboard should exercise the changes. 
* You …
> Dashboard App component cleanup

- components/gitpod-db/src/typeorm/auth-code-repository-db.spec.db.ts
- components/gitpod-db/src/typeorm/auth-code-repository-db.ts
`AuthCodeRepositoryDB.getByIdentifier` didn't join with d_b_user table, this PR fixes issues with OAuth2Server integration (+ desktop IDEs)
Fixes #14464
Beyond the db-test included, one would need to connect to the preview environment using a desktop IDE. No `userId` errors in SQL statements should be logged. 
```release-note
NONE
```
> Fix AuthCodeRepositoryDB.getByIdentifier

- components/gitpod-db/go/cost_center.go
- components/gitpod-db/go/cost_center_test.go
When calling `gorm.Save` concurrently, we see duplicate entry errors
because gorm is only trying to update and if that doe not succeed does
an insert.
Fixes #15346
```release-note
NONE
```
> [db] handle race in `gorm.Save`

- components/iam/pkg/server/server.go
- components/public-api-server/pkg/server/server.go
Fixing issue where the proper error wasn't rendered.
```release-note
NONE
```
> 🧹 fix typo and copy-paste-error

- dev/preview/previewctl/cmd/stale.go
Artificial jobs don't have branches, therefore do a full check. Ideally it gets cleaned up by the artificial job itself, otherwise it will get cleaned up the stale job.
Also increase the timeout for installing the context to 10m
Fixes #
```release-note
NONE
```
> Skip stale branch check for artificial jobs

- components/server/src/analytics.ts
- components/server/src/express-util.ts
- components/server/src/websocket/websocket-connection-manager.ts
Fixes extraction of (masked) client IP for websocket connections.
Turns this output
into this
Follow-up for: https://github.com/gitpod-io/gitpod/pull/14978
- turn on debug logging with: `gpctl debug log server`
- visit the [preview env's dashboard](https://gpl-analytics.preview.gitpod-dev.com/workspaces)
- check server logs, and notice these lines:
```release-note
NONE
```
> [server] Fix clientIp extraction for analytics

- components/supervisor/pkg/supervisor/tasks.go
Following up from a relevant discussions[[1](https://gitpod.slack.com/archives/C02EN94AEPL/p1653324863539719)][[2](https://gitpod.slack.com/archives/C02EN94AEPL/p1671105716932369)] (internal), this will replace the prebuild duration message emoji from 🎉 to ⏱️ to help disassociate the prebuild status (`SUCCESS`, `FAIL`) for from the prebuild task status.
```
// BEFORE 
🎉 Well done on saving 7 minutes
// AFTER
⏱️ Well done on saving 7 minutes
```
See parallel fix https://github.com/gitpod-io/website/pull/3164. 🏓 
Follow-up improvements could include:
- https://github.com/gitpod-io/gitpod/issues/9994
- https://github.com/gitpod-io/gitpod/issues/9111
Run a prebuild with a task that fails, causing a prebuild to fail, but notice the prebuilds duration message is using a different emoji that …
> Replace prebuild duration message emoji

- components/gitpod-db/go/conn.go
- components/gitpod-db/src/config.ts
- components/gitpod-db/src/wait-for-db.ts
- components/public-api-server/pkg/server/server.go
- components/service-waiter/cmd/database.go
- components/usage/pkg/server/server.go
- install/installer/pkg/common/common.go
- install/installer/pkg/common/constants.go
- install/installer/pkg/components/database/init/constants.go
- install/installer/pkg/components/database/init/job.go
- install/installer/pkg/config/v1/config.go
- install/installer/pkg/config/v1/validation.go
This allows Gitpod to directly created SSL encrypted connections to MySQL databases.
For testing :point_down: there are two environments:
- preview on this branch (w/o SSL)
- the AWS release test instance (deployed from this branch with the `deps: external` flag) with external RDS with SSL.
- It uses the default jobs config, with two changes:
- a `secret` named `database-ssl` and an attribute `ca.crt` that contains the cert (chain) to validate the RDS certificate
- the installer config slightly adjust to:
```
database:
inCluster: false
external:
...
ssl:
customCa:
kind: secret
name: database-ssl
```
Fixes #12012
- sign in and start a workspace in the [preview env](https://gpl-12012-ssl.preview.gitpod-dev.com/workspaces) (w/o SSL): works as expected
- sign in and ~start a workspace~* got …
> [installer, gitpod-db] Introduce database.ssl.ca

- components/ee/payment-endpoint/BUILD.yaml
- components/ee/payment-endpoint/package.json
- components/ee/payment-endpoint/src/accounting/team-subscription-service.ts
- components/ee/payment-endpoint/src/accounting/team-subscription2-service.ts
- components/ee/payment-endpoint/src/chargebee/subscription-handler.ts
- components/ee/payment-endpoint/src/chargebee/ubp-reset-on-cancel.ts
- components/ee/payment-endpoint/src/config.ts
- components/ee/payment-endpoint/src/container-module.ts
- components/licensor/typescript/ee/src/api.ts
- components/server/src/container-module.ts
- components/usage/pkg/apiv1/usage.go
- install/installer/pkg/common/constants.go
- install/installer/pkg/components/usage/networkpolicy.go
Creates a credit note for negative balance for users that are canceled (team slot or individual), so that those users start with a zero balance.
I've tested teamsubscription, teamsubscription2, individual subscription.
Fixes #15055
- create a team "Chargebee something" and sign up with chargebee
- create usage with one of the team's users
- cancel chargebee
- verify the usage has been reset.
Note: the `AddUsageCreditNote` endpoint uses entire credits and can't handle creditcents. So if balance is 12.34 the credit note will be 12.
```release-note
NONE
```
> [ubp] reset usage on chargebee cancellation

- WORKSPACE.yaml
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
Update code to `1.74.1`
https://github.com/gitpod-io/gitpod/issues/14977
```release-note
NONE
```
> Update code to `1.74.1`

- components/dashboard/src/components/ConfirmationModal.tsx
- components/dashboard/src/projects/ProjectListItem.tsx
- components/dashboard/src/projects/ProjectSettings.tsx
- components/dashboard/src/projects/Projects.tsx
- components/dashboard/src/teams/teams-context.tsx
This is a followup PR to #15316 to share some updates made there with extracting a remove project modal. A couple other related updates on the Project list page are included.
* Simplify project list by extracting a `<ProjectListItem/>` component. This let us drop a bunch of state management we were doing around which project to remove.
* Memoized the sorting/filtering of projects so it only occurs when a relevant value changes instead of every render.
* Added a flag to track projects having been loaded to avoid a content flash on initial page load
Preview Env: https://bmh-projec70ae423ab3.preview.gitpod-dev.com/
* Navigate to your personal, or a team's Projects list.
* Try and Remove a project via the overflow menu action.
* It should open a confirmation modal like it used to (this is …
> Project list page updates

- components/ws-manager/pkg/manager/manager.go
We cannot expect any latency or that the load on the API server can provide time guarantees for object persistence.
```
default     0s          Normal    Scheduled                pod/ws-5d18c42e-c8eb-4db5-af28-4e9161927998           Successfully assigned default/ws-5d18c42e-c8eb-4db5-af28-4e9161927998 to i-09682c625b5eeb3fb.eu-central-1.compute.internal
default     0s          Normal    Pulling                  pod/ws-5d18c42e-c8eb-4db5-af28-4e9161927998           Pulling image "reg.doptig10.gitpod.cloud:20000/remote/5d18c42e-c8eb-4db5-af28-4e9161927998"
default     0s          Normal    Pulled                   pod/ws-5d18c42e-c8eb-4db5-af28-4e9161927998           Successfully pulled image "reg.doptig10.gitpod.cloud:20000/remote/5d18c42e-c8eb-4db5-af28-4e9161927998" in 97.809814ms …
```
> Wait for the  workspace secret before creating the workspace pod

- components/dashboard/src/settings/SelectIDE.tsx
This will update the beta notice for the JetBrains integration, making the beta label more prominent. 
See [relevant discussion](https://gitpod.slack.com/archives/C02CBKZEVS8/p1671112085737199?thread_ts=1671106002.085899&cid=C02CBKZEVS8) (internal). Cc @akosyakov @loujaybee @easyCZ 
> Benefits:
> - Making beta notice more prominent.
> - Better UX (colors, structure, etc)
> - Linking to the Gitpod releases page.
> - Reusing the PillLabel component.
> - Using similar pattern as in #15017.
>     - X feature is in BETA · Send Feedback
>     - Y integration is in BETA · Send Feedback
|-|-|
| <img width="682" alt="beta-before" src="https://user-images.githubusercontent.com/120486/207886527-04471396-d199-458c-b441-cdeabc876146.png"> | <img width="682" alt="beta-after" …
> Update beta notice for the JetBrains integration

- components/blobserve/README.md
- components/image-builder-bob/README.md
- components/image-builder-mk3/README.md
Update READMEs to describe about IAM policy for image-builder-bob, image-builder-mk3, registry-facade, and blobserve.
Relates #14914
Try hhttps://g52001c706cb2d5a7c6f718.workspace-preview.gitpod-io-dev.com/
- Trigger an image build
Also, you can check each detailed permission here
https://policysim.aws.amazon.com/home/index.jsp#users/toru-test
```release-note
NONE
```
> Update READMEs to describe about IAM policy

- components/dashboard/src/components/UsageBasedBillingConfig.tsx
Change the link when subscribing to the cost estimator
Fixes #15283
See also https://github.com/gitpod-io/website/pull/3166
```release-note
NONE
```
> [dashboard] link to website's cost estimator

- components/gitpod-protocol/go/gitpod-service.go
- components/gitpod-protocol/src/gitpod-service.ts
- components/server/src/ide-service.ts
- components/server/src/workspace/gitpod-server-impl.ts
- components/server/src/workspace/workspace-starter.ts
Introduces optional IDE and workspace class arguments on workspace start.
This is a precursor for https://github.com/gitpod-io/gitpod/issues/15287
Fixes #
```release-note
NONE
```
> [server] Allow options on ws start (1/2)

- components/ide/jetbrains/launcher/hot-deploy.sh
Addressing a todo comment left today in a previous PR: loop though IDEs instead of repeating the same commands over and over
Fixes #
Manually tested already ✅ 
To test again, run the script (you need a preview environment)
```release-note
NONE
```
> [launcher] hot-deploy loops through all ides

- .github/CODEOWNERS
Set refresh-credential code owner to the workspace team.
Related to #12104
```release-note
None
```
None
> Set refresh-credential code owner to the workspace team

- .github/CODEOWNERS
> [CODEOWNERS] Make WebApp code owners of `iam` and `iam-api`

- test/report.sh
I forgot to attach this script when I send out https://github.com/gitpod-io/gitpod/pull/15386
Follow-up: https://github.com/gitpod-io/gitpod/pull/15386
```console
./run.sh -r report.csv -s workspace 
cat report.csv
```
```release-note
NONE
```
> test: Add the script to create QA report

- components/ws-manager-api/go/config/config.go
- components/ws-manager/cmd/run.go
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-workspace/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/common/constants.go
- install/installer/pkg/components/image-builder-mk3/configmap.go
- install/installer/pkg/components/image-builder-mk3/constants.go
- install/installer/pkg/components/image-builder-mk3/deployment.go
- install/installer/pkg/components/image-builder-mk3/objects.go
- install/installer/pkg/components/image-builder-mk3/tlssecret.go
- install/installer/pkg/components/ws-manager/configmap.go
- install/installer/pkg/components/ws-manager/deployment.go
Enable TLS on the `image-builder-mk3` service, in workspace clusters only. See https://github.com/gitpod-io/ops/issues/6905#issuecomment-1326586653 for more context behind this change.
Opted to keep `insecure` connections for image-builder in **application** clusters, because:
- The image-builder-mk3 NetworkPolicy was only changed in workspace clusters to allow all ingress.
- Workspace components should get removed soon from the application cluster once image builds move to workspace clusters, did not want to make server/application cluster changes which would get removed soon again.
- Also simplifies the rollout of this change, as it's now a workspace-only change.
No need to mount image-builder TLS certs on `server`, as server proxies through `ws-manager` to call the image-builder api in …
> [image-builder] Enable TLS in workspace clusters

- components/supervisor/go.mod
- components/supervisor/go.sum
- components/supervisor/pkg/terminal/terminal.go
Set default cols and rows when creating a pty
Align attributes with node-pty
Related https://github.com/gitpod-io/gitpod/issues/8055
- Use the test from [here](https://github.com/gitpod-io/gitpod/issues/8055#issuecomment-1339590402) with the sourcegraph binary
- Open some repo with lots of taks to check nothing regressed;
```release-note
NONE
```
> Set default cols and rows when creating pty

- install/installer/third_party/charts/minio/Chart.yaml
- install/installer/third_party/charts/mysql/Chart.yaml
- install/installer/third_party/charts/rabbitmq/Chart.yaml
This PR updates the `repository` field for third_party charts to use full index so that we don't loose out on older version charts as they get truncated.
As per https://github.com/bitnami/charts/issues/10833
Fixes #
```release-note
[installer] Update third_party charts to use full index
```
> [installer] Update third_party charts to use full index

- .github/CODEOWNERS
Changes to common-go can affect all go components of Gitpod, and can potentially break all of them. This PR suggests to reduce an ownership to staff engineers to indicate that they should be reviewed carefully but at the same time give each team a person within a team to unblock.
An alternative to give ownership to everybody.
Fixes #
```release-note
NONE
```
> reduce ownership of common-go to staff engineers

- components/gitpod-db/go/dbtest/encryption.go
- components/gitpod-db/go/encryption.go
- components/gitpod-db/go/encryption_test.go
Builds on top of https://github.com/gitpod-io/gitpod/pull/15381, to provide support for multiple ciphers from config. This behaviour matches what Server already does in `encryption-engine.ts` and `encryption-service.ts`
* Part of https://github.com/gitpod-io/gitpod/issues/15150
* Depends on https://github.com/gitpod-io/gitpod/pull/15381
Unit tests
```release-note
NONE
```
/hold for dependency on https://github.com/gitpod-io/gitpod/pull/15381
> [db] Support cipher-set in go

- components/ws-manager/pkg/manager/metrics.go
Fixes https://github.com/gitpod-io/gitpod/issues/15231
I created the preview env which has the below changes to test.
https://to-dup-stopped.preview.gitpod-dev.com/workspaces
```diff
gitpod /workspace/gitpod (to/dup-stopped) $ git diff
diff --git a/components/ws-daemon/pkg/iws/iws.go b/components/ws-daemon/pkg/iws/iws.go
index bda1e587f..95e1c3d09 100644
--- a/components/ws-daemon/pkg/iws/iws.go
+++ b/components/ws-daemon/pkg/iws/iws.go
@@ -155,7 +155,7 @@ func (wbs *InWorkspaceServiceServer) Start() error {
return xerrors.Errorf("cannot create ServiceLocDaemon: %w", err)
}
-       socketFN := filepath.Join(wbs.Session.ServiceLocDaemon, "daemon.sock")
+       socketFN := filepath.Join(wbs.Session.ServiceLocDaemon, "invalid.sock")
if _, err := os.Stat(socketFN); err == nil {
// a former …
```
> ws-manager: Prevent duplication of stop metrics

- components/common-go/namegen/workspaceid.go
- components/common-go/namegen/workspaceid_test.go
- components/public-api-server/pkg/apiv1/workspace.go
- components/public-api-server/pkg/apiv1/workspace_test.go
Adds validation to Workspace IDs on the API level
Fixes #
Unit tests
```release-note
NONE
```
> [public-api] Validate Workspace IDs

- components/gitpod-db/src/team-db.spec.db.ts
- components/gitpod-db/src/typeorm/team-db-impl.ts
Adjusting the `findTeams` query to use the `searchTerm` for either `team.name` or `team.slug`.
Searching by team-slug
Fixes #12982
**Preview Env:** https://bmh-searche1a0adc542.preview.gitpod-dev.com/
* Create a team named something like `Test Team`
* Go to Admin/Teams and search for the team by it's slug, `test-team`
* The team should display in the results
```release-note
The Admin Teams search will also search by team slug in addition to team name.
```
> adding team.slug to findTeams query

- components/dashboard/src/contexts/FeatureFlagContext.tsx
Setup the feature flag
Fixes #
```release-note
NONE
```
> [dashboard] Add feature flag to use Public API Workspaces Service

- components/gitpod-db/go/conn.go
- components/gitpod-db/go/conn_test.go
- components/public-api-server/pkg/server/server.go
- components/usage/pkg/server/server.go
Minor refactor to make it easier to stay consistent
Fixes #
```release-note
NONE
```
> [gitpod-db] Helper to construct db connection params from env

- WORKSPACE.yaml
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
Update code to `1.74.2`
```release-note
NONE
```
> Update Code to 1.74.2

- components/BUILD.yaml
- components/ipfs/ipfs-cluster/BUILD.yaml
- components/ipfs/ipfs-cluster/README.md
- components/ipfs/ipfs-cluster/leeway.Dockerfile
- components/ipfs/kubo/BUILD.yaml
- components/ipfs/kubo/README.md
- components/ipfs/kubo/leeway.Dockerfile
We manually build and publish the IPFS images to 
- https://hub.docker.com/r/aledbf/go-ipfs
- https://hub.docker.com/r/aledbf/ipfs-cluster
Move the Dockerfiles to Gitpod monorepo, and build and publish it by leeway+werft.
Related to https://github.com/gitpod-io/gitpod-packer-gcp-image/issues/199
Check the container image located in GCP container registry.
```release-note
None
```
None
> Move IPFS docker build to Gitpod monorepo

- WORKSPACE.yaml
Fixes an issue raised upstream where on the web version of VS Code the ports tab is shown. The problem is we don't use that one and have our own ports tab so having two makes everything confusing. This PR reverts the behavior in disabling the native port sview for us on the web.
The OVSCS PR: https://github.com/gitpod-io/openvscode-server/pull/476
```release-note
NONE
```
> Hide VS Code Browser's native ports tab

- components/supervisor/pkg/supervisor/supervisor.go
Alerts based on supervisor metrics are false positive when @gitpod-io/engineering-workspace is running load tests.
We cannot filter ephemeral workspace clusters in Grafana because supervisor metrics are aggregated in IDE proxy, i.e. in the application cluster. This PR disables metrics reporting from supervisor for ephemeral clusters.
[Internal thread](https://gitpod.slack.com/archives/C0201TXMV54/p1671697846070169)
Fixes #
Check that metrics are still reported in preview envs.
```release-note
NONE
```
> [supervisor] don't report metrics for ephemeral clusters

- components/iam/pkg/server/server.go
Reads encryption keys on component startup. Keys are not yet used.
Fixes #
```release-note
NONE
```
> [iam] Read db encryption keys on component startup

- components/content-service/cmd/test.go
- components/content-service/pkg/storage/s3.go
- components/content-service/pkg/storage/s3_test.go
- components/content-service/pkg/storage/suite_test.go
- components/dashboard/src/components/UsageLimitReachedModal.tsx
- components/iam/pkg/oidc/demo.go
- components/iam/pkg/oidc/oauth2.go
- components/ide/jetbrains/image/create-supervisor-config.js
- components/ide/jetbrains/image/resolve-latest-ide-version.sh
- components/ide/jetbrains/launcher/leeway.Dockerfile
- components/ide/jetbrains/launcher/main_test.go
- components/ide/jetbrains/launcher/testdata/.gitpod.yml
- components/ipfs/ipfs-cluster/leeway.Dockerfile
- components/ipfs/kubo/leeway.Dockerfile
- components/refresh-credential/cmd/root.go
- components/refresh-credential/leeway.Dockerfile
- components/refresh-credential/main.go
- components/refresh-credential/pkg/config/config.go
- components/refresh-credential/pkg/ecr/updater.go
- install/installer/pkg/components/image-builder-mk3/tlssecret.go
- install/installer/pkg/components/refresh-credential/common.go
- install/installer/pkg/components/refresh-credential/common_test.go
- install/installer/pkg/components/refresh-credential/constants.go
- install/installer/pkg/components/refresh-credential/cronjob.go
- install/installer/pkg/components/refresh-credential/objects.go
- install/installer/pkg/components/refresh-credential/role.go
- install/installer/pkg/components/refresh-credential/rolebinding.go
Fix the License filename in headers (`License-AGPL.txt` -> `License.AGPL.txt`)
- Left-overs from https://github.com/gitpod-io/gitpod/pull/15241
Check if there's only one line changed per file:
```
// See License.AGPL.txt in the project root for license information.
```
```release-note
NONE
```
> Fix the License filename in headers

- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/iam/networkpolicy.go
- install/installer/pkg/components/iam/objects.go
Adds a network policy to allow ingress for the `iam` component.
Part of https://github.com/gitpod-io/gitpod/issues/14955 (OIDC client implementation)
Relates to SSO Epic https://github.com/gitpod-io/gitpod/issues/7761
Check that the network policy is configured.
```release-note
NONE
```
> [iam] Allow ingress to /iam

- dev/preview/workflow/preview/deploy-gitpod.sh
- install/installer/pkg/components/iam/configmap.go
- install/installer/pkg/components/iam/constants.go
- install/installer/pkg/components/iam/deployment.go
- install/installer/pkg/components/iam/oidc.go
- install/installer/pkg/config/v1/experimental/experimental.go
Based on #15482
Injects config from `werft` namespace.
Part of https://github.com/gitpod-io/gitpod/issues/14955 (OIDC client implementation)
Relates to SSO Epic https://github.com/gitpod-io/gitpod/issues/7761
Verify that the config (stored internally in `werft` namespace) is injected into the preview env.
```release-note
NONE
```
> [iam] add preview env config

- components/proxy/conf/Caddyfile
- dev/preview/workflow/preview/deploy-gitpod.sh
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/iam/configmap.go
- install/installer/pkg/components/iam/constants.go
- install/installer/pkg/components/iam/deployment.go
- install/installer/pkg/components/iam/networkpolicy.go
- install/installer/pkg/components/iam/objects.go
- install/installer/pkg/components/iam/oidc.go
- install/installer/pkg/config/v1/experimental/experimental.go
Based on #15481
Part of https://github.com/gitpod-io/gitpod/issues/14955 (OIDC client implementation)
Relates to SSO Epic https://github.com/gitpod-io/gitpod/issues/7761
Verify that `/iam/oidc/start` is reachable.
```release-note
NONE
```
> [iam] add proxy route /iam/*

- .github/workflows/poc-build.yml
- dev/preview/previewctl/cmd/report.go
- dev/preview/previewctl/cmd/root.go
This adds a very simple Job Summary to do the deploy job. For now it just includes the name and URL where the Gitpod installation is reachable. In the future it could include any relevant configuration options for Gitpod that were selected for the preview environment.
I also adds a simple Job Summary to the monitoring job.
Fixes https://github.com/gitpod-io/gitpod/issues/15487
Fixes https://github.com/gitpod-io/gitpod/issues/15495
See the result [here](https://github.com/gitpod-io/gitpod/actions/runs/3765182576).
```release-note
NONE
```
N/A
> GH PoC: Add Job Summary to install job

- operations/observability/mixins/workspace/dashboards/components/image-builder.json
Fix cluster and job variables and pane parameters such that the dashboard is usable again.
Fixes https://github.com/gitpod-io/gitpod/issues/15496
<details><summary>Check out these screenshots</summary>
</details>
```release-note
NONE
```
> [obs] fix image-builder-mk3 dashboard

- components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodStartWorkspaceView.kt
Example Repo. URL Changes with new selection. Would not change if user has changed the text field. 
**Demo Video**:
https://user-images.githubusercontent.com/55068936/209700323-e81446c5-22b9-445b-b0bd-32cc356dc8ac.mov
Currently, It only shows `https://github.com/gitpod-samples/spring-petclinic` doesn't matter which IDE you select (IntelliJ/PyCharm/WebStorm/etc.)
```release-note
Customised example repositories on the basis of selected IDE options 
```
> chore: repository template for JetBrains IDEs

- .gitpod.yml
Don't run GoLand Prebuild during workspace initialization anymore.
This prevents the workspace starting up with changed `go.sum` files.
| --- | --- |
| <img width="343" alt="image" src="https://user-images.githubusercontent.com/418083/209375895-2c3137fa-0b12-4b76-b991-f8bb4334f560.png"> | <img width="339" alt="image" src="https://user-images.githubusercontent.com/418083/209375595-43cb25b9-101b-4a2a-b0dd-29d01849efe5.png"> |
This also reduces the time, from ~35 minutes to ~9 minutes, to prebuild Gitpod repository.
- https://github.com/gitpod-io/gitpod/pull/15497
1. Check if Werft Build succeeds.
2. Open a workspace from this PR in gitpod.io (https://gitpod.io/#https://github.com/gitpod-io/gitpod/pull/15529) ([which has already been …
> Fix the issue of modified `go.sum` files when Gitpod Repo workspace starts

- dev/preview/workflow/preview/deploy-gitpod.sh
We're using always the latest fluent-bit helm chart and a new version with [fluent-bit v2.0.8](https://fluentbit.io/announcements/v2.0.8/)  got released yesterday and matches with the time the issue started occuring. It contains a change around StackDriver logging, which seems to be the one causing the problem:
```
[Stackdriver (Output)](https://docs.fluentbit.io/manual/pipeline/outputs/stackdriver/)
Add Cache token expiration and use it when using cached tokens (#6453)
```
This PR pins the helm chart to the previous version and seems to solve the problem (tested in a preview env). Will investigate another time if there is some configuration we can provide to the newer version of fluent-bit so it doesn't break.
Fixes https://github.com/gitpod-io/gitpod/issues/15530
```release-note
NONE …
```
> Use older version for fluent-bit in preview envs

- components/common-go/namegen/workspaceid.go
- components/common-go/namegen/workspaceid_test.go
Fixes the regex pattern for workspace ID validator :wrench:
On [this another example Repo.](https://github.com/Siddhant-K-code/cal.com)
|Before|After|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/55068936/210164115-8da21d94-c7d6-4261-948f-4fedf1326fee.png)|![image](https://user-images.githubusercontent.com/55068936/210164179-c6a73238-f4f7-4f82-a510-bfc7e6815e2b.png)|
Fixes Internal Conversations[[1](https://gitpod.slack.com/archives/C0201TXMV54/p1672373060710899)], [[2](https://gitpod.slack.com/archives/C01KGM9BH54/p1672488304693609)]
- Open [Preview](https://fix-workspf72253ab47.preview.gitpod-dev.com/workspaces)
- Open Following Repo. to VS Code Desktop:
- …
> fix: regex of workspace ID validator

- install/infra/single-cluster/azure/README.md
The cloud provider name was wrong, I corrected it, from AWS to AKA.
The cloud provider name was wrong, I corrected it, from AWS to AKA.
Fixes #
Update terraform configuration documentation
```release-note
NONE
```
> Wrong cloud provider

- components/dashboard/src/service/public-api.ts
- components/dashboard/src/start/StartWorkspace.tsx
- components/dashboard/src/workspaces/WorkspaceEntry.tsx
- components/dashboard/src/workspaces/Workspaces.tsx
- components/public-api-server/pkg/apiv1/workspace.go
- components/public-api-server/pkg/apiv1/workspace_test.go
Implements StopWorkspace on public API, and uses it from dashboard - behind an expeirment.
* Depends on https://github.com/gitpod-io/gitpod/pull/15458
1. Preview
2. Start a workspace
3. Stop it from the list workspaces view
4. Stop it from started workspace view (when not using in-browser VS Code)
5. Observe that for both the request is made against `api.gitpod.io` and it's HTTP with JSON (dev tools)
```release-note
NONE
```
> [public-api] Implement StopWorkspace and use from Dashboard

- components/iam/pkg/apiv1/oidc_config.go
- components/iam/pkg/apiv1/oidc_config_test.go
- components/iam/pkg/server/server.go
Adds unimplemented CreateOIDCConfig RPC, together with a test setup. Binds db and cipher into the struct.
Fixes #
1. IAM components starts up OK
2. Unit tests
```release-note
NONE
```
> [iam] Add unimplemented CreateOIDCConfig RPC

- components/dashboard/src/Menu.tsx
- components/dashboard/src/teams/Members.tsx
On narrow screens, most avatars tend to shrink horizontally (which looks bad) until width 0 is reached (which makes them disappear). This is both awkward-looking and can break major functionality (e.g. no access to the top right avatar menu on mobiles).
| | BEFORE | AFTER |
| --- | --- | --- |
| **Top-Right Avatar Menu** | <img width="376" alt="Screenshot 2022-12-26 at 15 30 44" src="https://user-images.githubusercontent.com/599268/209559391-54825346-d4b2-4c29-9100-2edc49155746.png"> | <img width="376" alt="Screenshot 2022-12-26 at 15 30 21" src="https://user-images.githubusercontent.com/599268/209559389-c49f3242-1bad-4068-9db6-b994f05172f6.png"> |
| **Team Members List** | <img width="478" alt="Screenshot 2022-12-26 at 15 32 47" …
> [dashboard] Prevent avatars from shrinking out of existence on narrow screens

- install/installer/pkg/components/ws-daemon/configmap.go
OOM scores specified in the installer config did not end up in the configmap for ws-daemon.
n.a.
- Open workspace in gitpod ops repository
- Download installer `docker run --entrypoint sh --rm eu.gcr.io/gitpod-core-dev/build/installer:fo-set-oom-scores.0 -c "cat /app/installer" > gitpod-installer`
- `sudo chmod +x ./gitpod-installer`
- `./gitpod-installer render --config deploy/workspace/installer-values.yaml --use-experimental-config > /tmp/render.yaml`
- Check that values were applied
```release-note
Fixed an issue where oom scores for workspace processes were not applied correctly
```
> Ensure that oom scores are applied

- dev/preview/previewctl/cmd/stale.go
- dev/preview/previewctl/pkg/preview/status.go
Currently, all preview environments for branches that haven't had recent commits are considered stale and cleaned up no matter they are in use. This results in people rerunning `/werft build` over and over again and being surprised that they don't get a preview environment or that it dies in the middle of using it.
This change makes it so that all branches that have had a commit in the past 30 days are considered. And also adjusts the activity check on those branches by not treating workspace instances as activity as that includes prebuilds and would create false positive activity (i.e. prebuilds could keep a preview environment active forever).
Fixes https://github.com/gitpod-io/ops/issues/7576
```release-note
NONE
``` …
> [previewctl] change staleness logic

- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodTerminalService.kt
This PR changes the following:
- Avoid shutting down terminals when closing JetBrains Client.
- Open terminals for each Gitpod Task Terminal running and close them when JetBrains Client gest closed. We need to do this because clicking "Disconnect" is different from clicking "X" button from JetBrains Client Window [[1](https://github.com/gitpod-io/gitpod/issues/12126#issuecomment-1367325029)]. Now the terminals are behaving the same as in VS Code.
- Replace the use of `application.executeOnPooledThread` (thread) with `lifetime.launch` (coroutine).
Making the `GitpodTerminalService` class extend `Disposable` opens doors for us to use the `defineNestedLifetime()` method inside the class.
This method creates a LifetimeDefinition that is automatically terminated whenever the class is disposed. …
> [JetBrains] Avoid shutting down terminals when closing the client

- components/ws-manager/pkg/manager/metrics.go
That metric is not needed, as we get same data from `workspace_stops_total{reason=failed}`
Fixes #
```release-note
none
```
> [ws-manager] remove unneeded metric

- components/ws-manager-api/go/config/config.go
- components/ws-manager/cmd/run.go
- components/ws-manager/pkg/manager/manager.go
- components/ws-manager/pkg/manager/manager_ee.go
- install/installer/pkg/components/ws-manager/configmap.go
A short-term solution for upgrading the ws-manager within a cluster rather than traffic shift to a new cluster.
Before upgrading the ws-manager to a newer one, we will
- update the ws-manager ConfigMap `"maintenanceMode": true,`.
- the other component will check if is there any workspace backing content to remote _or_ takes a snapshot. If none, replace the ws-manager with a newer one.
- after rolling out the ws-manager finished, update the ws-manager ConfigMap `"maintenanceMode": false,`.
While the maintenance mode is enabled, the user can't start the workspace, stop the workspace, or take snapshots. Also, during the maintenance mode, the workspace would not time out.
Suppose there is workspace time out during the maintenance mode. After maintenance mode is disabled, the ws-manager needs …
> ws-manager: maintenance mode

- components/dashboard/src/components/RepositoryFinder.tsx
Bug Fix: This PR propose change to trim url while staring a new workspace from dashboard.
|Before|After **_(ignore UI Change)_**|
|:---:|:---:|
|<video src="https://user-images.githubusercontent.com/55068936/210498585-b0888eb5-15de-42e0-a6c6-7cff3b866c24.mov">|<video src="https://user-images.githubusercontent.com/55068936/210498644-90423345-0cbc-4158-912b-6c26b4f2426a.mov">|
Fixes #12079
- Open [Preview](https://fix-12079.preview.gitpod-dev.com)
- Open [/workspaces](https://fix-12079.preview.gitpod-dev.com/workspaces)
- Click on New Workspace Button
- Type `       https://github.com/gitpod-io/empty` in Repo. URL text box. It will start a new workspace without any error (_repeat same in prod. to exp. the difference_)
```release-note
NONE …
```
> fix: trim repo url while open new workspace

- components/dashboard/src/workspaces/WorkspaceEntry.tsx
- components/dashboard/src/workspaces/Workspaces.tsx
- components/dashboard/src/workspaces/workspace-model.ts
- components/public-api-server/pkg/apiv1/workspace.go
- components/public-api-server/pkg/apiv1/workspace_test.go
Implements DeleteWorkspace RPC on the Public API, and uses it (behind an experiment) from Dashboard.
* Depends on https://github.com/gitpod-io/gitpod/pull/15554
1. Preview
2. Delete workspace
3. Observe the request goes to public API
4. Dashboard works as before
```release-note
NONE
```
/hold for dependency on https://github.com/gitpod-io/gitpod/pull/15554
> [public-api] Define DeleteWorkspace

- components/gitpod-db/package.json
- components/server/package.json
- yarn.lock
Bump Package `@jmondi/oauth2-server`
Fixes [**GitHub Advisories**](https://github.com/advisories/GHSA-27h2-hvpr-p74q) 
Related: 
- https://github.com/jasonraimondi/ts-oauth2-server/pull/74
Will address this in followup PRs;
- No release created yet: https://github.com/twilio/twilio-node/pull/847
- No Bump yet:
https://github.com/probot/probot/pull/1780
```release-note
NONE
```
> bump: package `@jmondi/oauth2-server`

- components/public-api/go/README.md
- components/public-api/go/client/client.go
- components/public-api/go/client/client_test.go
- components/public-api/go/client/interceptors.go
- components/public-api/go/client/interceptors_test.go
- components/public-api/go/examples/client_example.go
- components/public-api/go/examples/teams_example.go
- components/public-api/go/go.mod
Adds a thin wrapper around Go public-api client construction. The contructor accepts options to parametrize the client.
Includes runnable (compile time verified) examples of use
Fixes #
Unit tests
```release-note
NONE
```
> [public-api] Thin wrapper for improved usability

- components/ws-manager/pkg/manager/manager.go
- components/ws-manager/pkg/manager/metrics.go
- components/ws-manager/pkg/manager/status.go
- components/ws-manager/pkg/manager/testdata/status_brokenScheduler_UNKNOWN00.golden
- components/ws-manager/pkg/manager/testdata/status_cannotPull_004_CREATING00.golden
- components/ws-manager/pkg/manager/testdata/status_cannotPull_005_STOPPED00.golden
- components/ws-manager/pkg/manager/testdata/status_contentInitFailed_005_STOPPED00.golden
- components/ws-manager/pkg/manager/testdata/status_errimgpull.golden
- components/ws-manager/pkg/manager/testdata/status_errimgpull_CREATING01.golden
- components/ws-manager/pkg/manager/testdata/status_failedBeforeStopping_explicitFail.golden
- components/ws-manager/pkg/manager/testdata/status_failedLogs_RUNNING00.golden
- components/ws-manager/pkg/manager/testdata/status_failedPending_evicted_UNKNOWN01.golden
- components/ws-manager/pkg/manager/testdata/status_failedPending_evicted_UNKNOWN02.golden
- components/ws-manager/pkg/manager/testdata/status_failedWorkspaceMount_PENDING00.golden
- components/ws-manager/pkg/manager/testdata/status_headlessTaskFailed_STOPPING00.golden
- components/ws-manager/pkg/manager/testdata/status_headless_STOPPING00.golden
- components/ws-manager/pkg/manager/testdata/status_ideFailedToStart_005_RUNNING00.golden
- components/ws-manager/pkg/manager/testdata/status_prebuildSuccess2_CREATING01.golden
- components/ws-manager/pkg/manager/testdata/status_prebuildSuccess2_CREATING02.golden
- components/ws-manager/pkg/manager/testdata/status_regularStart_Initializing00.golden
- components/ws-manager/pkg/manager/testdata/status_stuckInStopping_RUNNING00.golden
- components/ws-manager/pkg/manager/testdata/status_stuckInStopping_STOPPING00.golden
- components/ws-manager/pkg/manager/testdata/status_workspace_startup_failed.golden
- components/ws-manager/pkg/manager/testdata/status_wsstartup_Creating00.golden
- components/ws-manager/pkg/manager/testdata/status_wsstartup_Creating01.golden
Increase the metric `workspace_starts_failure_total` when the workspace stops and the pod's annotation "gitpod/never-ready" exist. It means the workspace pod never went into the running state, probably because
- the workspace pod can't allocate to the workspace node
- content initialization failure
- the workspace pod is never ready
Increase the metric workspace_stop_total when the workspace stops and the pod's annotation "gitpod/never-ready" does not exist. So, the metric `workspace_stop_total` does not increase on the start failure.
Fixes #15335
1. Port-forward the ws-manager metric port 9500.
```console
kubectl port-forward svc/gitpod-ws-manager 9500:9500
```
2. From a harvester preview VM, start a workspace, write some data, and stop the workspace.
3. Check the metrics …
> Fix the metric workspace_starts_failure_total

- components/ws-manager/pkg/manager/metrics.go
The ephemeral local storage out of space should not be counted in `workspace_stops_total{reason="failed"}`.
Adding a new reason `out-of-space` to track the number of workspace pods ever running into an out-of-space error.
Partial #15562
1. Open the workspace, and make the ephemeral local storage out of space.
```console
fallocate -l 25G /var/tmp/test1
```
2. Port-forward ws-manager metric port 9500
```console
kubectl port-forward <ws-manager-pod-name> 9500:9500
```
3. Get the metric, the metric `gitpod_ws_manager_workspace_stops_total{reason="out-of-space"}` should increase by one.
```release-note
None
```
> ws-manager: add new reason `out-of-space` for workspace_stops_total metric

- components/blobserve/cmd/run.go
- components/blobserve/go.mod
AWS ECR requires regular secret rotation.
This PR adds hot-reloading authentication credentials to pull images from the Gitpod container registry.
Similar code change https://github.com/gitpod-io/gitpod/pull/14679/files#diff-9efd0bd7f5ebc628c240ccf20295bf47583097f0d6f426826a0dc5d18b96a096 for reference.
Fixes #15426
1. Open the workspace preview
2. Update the secret `gcp-sa-registry-auth` with another docker credential
3. Watch the blobserve log, and check the below log display
```console
"message":"reloading file after change","path":"/mnt/pull-secret/pull-secret.json"
``` 
```release-note
None
```
None
> blobserve: dynamically reload Docker auth config

- components/gitpod-db/go/dbtest/oidc_client_config.go
- components/gitpod-db/go/oidc_client_config.go
- components/iam/pkg/apiv1/oidc_config.go
- components/iam/pkg/apiv1/oidc_config_test.go
Super basic implementation of CreateClientConfig RPC. Doesn't yet handle validation and mostly accepts the config from the client.
* Part of https://github.com/gitpod-io/gitpod/issues/15150
Unit tests
```release-note
NONE
```
> [iam] Implement basic OIDC CreateClientConfig RPC

- install/installer/cmd/root.go
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/config.yaml
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/kind-workspace/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/go.mod
- install/installer/go.sum
- install/installer/pkg/components/database/incluster/helm.go
- install/installer/pkg/components/minio/helm.go
- install/installer/pkg/components/rabbitmq/helm.go
- install/installer/third_party/charts/docker-registry/Chart.yaml
- install/installer/third_party/charts/minio/Chart.yaml
- install/installer/third_party/charts/mysql/Chart.yaml
- install/installer/third_party/charts/rabbitmq/Chart.yaml
This updates all Helm dependencies in the Installer (Docker registry, Minio, MySQL, RabbitMQ) to the latest versions. This PR has more commits than is strictly necessary, but have done it like this to ensure that the changes to the golden files are human-readable.
All of these dependency upgrade change the major version of the Helm chart. The Bitnami charts change how the image block works, so the previous way of defining the custom pull registry no longer works - in retrospect, I wish I'd done the original definition in the way I've done it here. The first two commits ([1](https://github.com/gitpod-io/gitpod/pull/15568/commits/0a9c537b854b971017c67b59e23be02720b63c9e) and [2](https://github.com/gitpod-io/gitpod/pull/15568/commits/853b6fd9a0835cf2bbdced5d0d81032fb6fb3986)) address this by …
> Update Helm dependencies in Installer

- components/dashboard/src/components/BillingAccountSelector.tsx
- components/dashboard/src/settings/EnvironmentVariables.tsx
- components/dashboard/src/settings/Integrations.tsx
- components/dashboard/src/settings/PersonalAccessTokens.tsx
- components/dashboard/src/settings/Preferences.tsx
- components/dashboard/src/settings/SSHKeys.tsx
This PR Propose changes to Settings Dashboard for having `Learn More` section under required settings to make user learn about the feature or about how that actually works by linking it to our documentation. (Design Suggestions & Placeholder position suggestions are welcomed 🙏🏽 cc: @gtsiolis)
Fixes #
- Open [Preview](https://dashboard-074a33b924.preview.gitpod-dev.com/)
- Go to `/settings` & See following 👀
- Learn More section on `/preferences`
- Learn More section on `/integrations`
- Learn More section on `/keys`
- Learn More section on `/variables`
- Learn More section on `/billing`
- Learn More & Send Feedback section on `/tokens`
```release-note
NONE
``` …
> Learn more section under each settings

- components/iam/pkg/config/config.go
- components/iam/pkg/oidc/router.go
- components/iam/pkg/oidc/router_test.go
- components/iam/pkg/oidc/service.go
- components/iam/pkg/oidc/service_test.go
- components/iam/pkg/server/server.go
- components/server/src/iam/iam-session-app.ts
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/iam/configmap.go
Based on #15472
This change set enables sending of the ID token (+ claims) to the /session endpoint of server.
As the server is still in charge of creating an HTTP session, it will response with the `Set-Cookie` header, which will be forwarded with the HTTP redirect to the client.
Part of #14954
Belongs to epic #7761
```release-note
NONE
```
> [OIDC] Call /session endpoint to create a session

- components/dashboard/src/components/UsageBasedBillingConfig.tsx
- components/usage/pkg/apiv1/billing.go
- components/usage/pkg/stripe/stripe.go
Show a button to the stripe portal for customers who have cancelled their subscription, so they can download invoices later.
Fixes #15236
- after login go to billing and verify there is no button for previous invoices.
- subscribe
- cancel and verify there is now a button to go to the portal and see previous invoices.
```release-note
NONE
```
> [dashboard] access invoices after cancellation

- yarn.lock
When opening a workspace on `g/g` you'd find these yarn.lock changes. Perhaps some PR was missing them on merge. 
```release-note
NONE
```
> missing yarn.lock changes

- dev/preview/infrastructure/harvester/certificate-zerossl.tf
Preview environment infrastructure creating is failing off main with the following error ([example job](https://werft.gitpod-dev.com/job/gitpod-build-wv-image-build-retry-preparing.1))
```
Error: Error retrieving available secret manager secret versions: googleapi: Error 403: Permission 'secretmanager.versions.get' denied for resource 'projects/gitpod-core-dev/secrets/zerossl-eab/versions/latest' (or it may not exist).
```
As a temporary workaround I have changed the terraform definition so that it only tries to read the secret if it is needed. ZeroSSL is the fallback provider, so for normal use-cases it won't be needed.
Part of https://github.com/gitpod-io/gitpod/issues/15146
`werft job run github -a with-preview` shows that terraform is succesful. It fails at a later point which I'll …
> Only load zerossl-eab secret when needed

- components/dashboard/debug.sh
- components/server/src/workspace/gitpod-server-impl.ts
Fixes image build logs from showing up in the dashboard if the build is delayed.
When a workspace's image build is delayed (due to e.g. waiting for a node to scale up), the workspace instance stays in a `preparing` state, it only moves to `building` once the build is actually running. Previously, the logic would stop retrying for build logs if it's not in a `building` state, this PR changes it to also wait for build logs while in a `preparing` state
Fixes #14862
In a preview environment:
- Cordon the preview environment's node
- Create a new image build (e.g. `https://<your-preview-env>.preview.gitpod-dev.com/#imagebuild/github.com/gitpod-io/gitpod`
- Wait a few minutes (an image build workspace gets created, but gets stuck in a pending state)
- Uncordon the node
- Observe that the image …
> [server] Wait for image build logs in preparing state

- .werft/util/preview.ts
- .werft/vm/vm.ts
- dev/preview/infrastructure/harvester/variables.tf
The terraform variable defaulted to zerossl but it should have been letsencrypt. This PR fixes that. Also contains minor improvements around error diagnostics.
Part of https://github.com/gitpod-io/gitpod/issues/15146
Triggered manually:
https://werft.gitpod-dev.com/job/gitpod-custom-mads-fix-delete-preview.2
```release-note
NONE
```
N/A
> Fix preview environment deletion

- components/gitpod-cli/cmd/timeout-extend.go
- components/gitpod-cli/cmd/timeout-show.go
- Open Preview
- Open Any Workspace
- Run `gp timeout extend` and `gp timeout show`
```release-note
NONE
```
> chore: descriptive output Gitpod CLI

- components/dashboard/src/provider-utils.tsx
This marks the authentication provider icons (GitHub, GitLab, Bitbucket) on the login and new project pages as [decorative](https://www.w3.org/WAI/tutorials/images/decorative/) by setting `alt=""` on the `img` element.
Setting an alternative text is good for icons but the authentication provider icons are currently directly paired with the UI text `Continue with {provider}` where `{provider}` is one of the providers, so screen readers would announce `GitLab Continue with GitLab`, which is currently redundant.
No visual changes intended.
#3841 for the broader effort to reduce warnings
1. Go to the login page
2. Open your browser’s DevTools
3. Use the element picker
4. Click on one of the authentication provider icons
5. See that the `alt` attribute is set to an empty string
```release-note …
```
> Mark auth provider icons as decorative

- components/dashboard/src/components/BillingAccountSelector.tsx
_This PR was previously opened as https://github.com/gitpod-io/gitpod/pull/15594, read why we needed a new PR there: https://github.com/gitpod-io/gitpod/pull/15594#issuecomment-1373977394_
This improves the readability of the **Personal Account** billing account type label in dark mode if the account is selected as default billing account, because the label only had a contrast of 2.31 against the white background.
Currently, the text is actually kind of hard to read in dark mode on my 13.5" display.
Using `gray-600` here gets us a 6.99 color contrast, however we could also use `gray-500` to maintain the visual color hierarchy as seen in light mode and when not selected. While that would only get us to 4.4 contrast ratio, it’s definitely way more legible than `gray-400`.
| Billing account …
> Improve readability of label in billing settings

- components/ws-manager/pkg/manager/manager.go
- components/ws-manager/pkg/manager/metrics.go
We observed that duplicated logs exist in the GCP log.
To help us analyze the log quickly and save money 💸, we output the log when there is a state change.
Related to #15562
1. From a harvester preview VM, start a workspace, write some data, and stop the workspace.
2. After the workspace is stopped (workspace content is backed up), scale MinIO to zero.
```console
kubectl scale --replicas=0 deploy/minio
```
3. Stream the ws-manager log
```console
kubectl logs -f -l component=ws-manager
```
4. Reopen the workspace, and check the log message `"message":"workspace failed"` outputs when there is a state change.
```release-note
None
```
> ws-manager: avoid duplicate logs

- components/dashboard/src/app/AppRoutes.tsx
- components/dashboard/src/components/RepositoryFinder.tsx
- components/dashboard/src/components/SelectIDEComponent.tsx
- components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
- components/dashboard/src/start/CreateWorkspace.tsx
- components/dashboard/src/start/start-workspace-options.ts
- components/dashboard/src/workspaces/StartWorkspaceModal.tsx
- components/dashboard/src/workspaces/Workspaces.tsx
- components/dashboard/src/workspaces/start-workspace-modal-context.tsx
- components/gitpod-protocol/src/util/gitpod-host-url.ts
This change allows for starting new workspaces with an option dialog where users can select the IDE and workspace class.
The URL param is `showOptions=true` as in:
`https://gitpod.io?showOptions=true#<context-url>`
Fixes #15566
Open this PR using the following link: 
- https://se-show-options.preview.gitpod-dev.com/?showOptions=true#https://github.com/gitpod-io/gitpod/pull/15567
It's also possible to preselect certain values:
- https://se-show-options.preview.gitpod-dev.com/?showOptions=true&editor=intellij#https://github.com/gitpod-io/gitpod/pull/15567
```release-note
Support start-with-options URL, for prompting users about the preferred IDE and workspace class when opening a fresh workspace.
``` …
> [dashboard] support start-with-options URL

- components/blobserve/go.mod
- components/blobserve/go.sum
- components/image-builder-bob/go.mod
- components/image-builder-bob/go.sum
- components/image-builder-mk3/go.mod
- components/image-builder-mk3/go.sum
- components/ipfs/kubo/BUILD.yaml
- components/registry-facade/go.mod
- components/registry-facade/go.sum
- components/ws-daemon/go.mod
- components/ws-daemon/go.sum
- components/ws-daemon/seccomp-profile-installer/go.mod
- components/ws-daemon/seccomp-profile-installer/go.sum
- install/installer/go.mod
- install/installer/go.sum
Preparation for generation 82, update dependencies:
- `containerd` 1.6.14 -> 1.6.15
- `ipfs/kubo` 0.16.0 -> 0.17.0
Separate PR to update both in gitpod-packer-gcp-image as well: https://github.com/gitpod-io/gitpod-packer-gcp-image/pull/207
```release-note
NONE
```
> Update containerd and ipfs/kubo

- components/iam/pkg/oidc/oauth2.go
- components/iam/pkg/oidc/router.go
- components/iam/pkg/oidc/router_test.go
- components/iam/pkg/oidc/service.go
- components/iam/pkg/oidc/service_test.go
This addresses https://github.com/gitpod-io/gitpod/pull/15440#discussion_r1053534414
... to separate error handling in the two separate cases – `/start` and `/callback`. The different expectations are covered in tests.
Follow up to #15440
```release-note
NONE
```
> [iam/sso] refactor client config middleware

- components/iam/pkg/oidc/service.go
- components/iam/pkg/oidc/service_test.go
Given that some OIDC client configurations will be fetched on frontend to render a login page, it makes sense to allow direct selection of the OIDC client by id: `GET /iam/oidc/start?id=UUID`
Depends on #15628
Part of #7761
```release-note
NONE
```
> [iam/sso] select config by ID on /start

- components/common-go/experiments/types_test.go
The `TestNewClient_WithoutEnvSet`  test fails when run (via `go test`) from a gitpod workspace because gitpod workspaces have the `GITPOD_HOST` env var set, causing the `NewClient` call to return a `ConfigCatClient` rather than a `alwaysReturningDefaultValueClient` struct as expected.
Having the test fail from within a workspace means that running `telepresence` for components that have `common-go` as a dependency doesn't work as `common-go` can't be built.
Clear the env var before the test runs to avoid this.
Fixes #
```release-note
NONE
```
> [common-go] Clear `GITPOD_HOST` environment variable before test

- operations/observability/mixins/workspace/dashboards/components/image-builder.json
Add image build rates (and their outcome) to the image builder dashboard:
Allows us to better observe the traffic shift of image builds from webapp to workspace clusters
```release-note
NONE
```
> [observability] Add image build rate panels

- components/iam/pkg/apiv1/oidc_config_test.go
starting test server after usage_test.go
Fixes #15643
```release-note
NONE
```
> [iam] try to fix flaky test

- components/supervisor/cmd/init.go
- components/supervisor/pkg/supervisor/supervisor.go
Show user friendly error and reason for failure if user uses base image that does not include `git`.
Otherwise workspace will be stuck in `content initialization` phase forever, which is a bad user experience.
(We do require base image to have git and gitpod user, but end user may forget about those requirements).
This is how the error will be presented to the user:
Fixes #
Open a repo that uses this gitpod dockerfile:
```
FROM ubuntu
RUN apt update
```
Notice it will fail with user friendly error explaining why.
```release-note
none
```
> show user friendly error if git is not found

- components/gitpod-protocol/src/teams-projects-protocol.ts
- components/server/src/workspace/gitpod-server-impl.ts
Validates arguments of setTeamMemberRole call
Fixes #
```release-note
NONE
```
> [server] Validate fields for setTeamMemberRole

- components/licensor/ee/pkg/licensor/licensor.go
- components/licensor/ee/pkg/licensor/licensor_test.go
- components/licensor/main.go
This begins the deprecation of the licensor by setting the default and fallback licences to having a full complement of features and with no restrictions on the number of users.
Fixes #15640
Check the licence page in the preview environment. Below is proof from my own test environment
```release-note
[licensor]: remove limits on licence user numbers and feature sets
```
> [licensor]: remove limits on licence user numbers and feature sets

- components/dashboard/src/Login.tsx
Align the new updated message on Login Page with new product description with [website message](https://www.gitpod.io/#:~:text=Spin%20up%20fresh%20cloud%20development%20environments%0Afor%20each%20task%2C%20fully%20automated%2C%20in%20seconds.)
|Old|New|
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/55068936/211495303-0430c54f-2a21-4e53-8f55-66beef1d4b52.png)|![image](https://user-images.githubusercontent.com/55068936/211495350-05f751c1-5bce-43c0-b1c0-997de963cf03.png)|
- Open Preview 
- Go to `/login` or `workspaces` (if you are not logged in)
```release-note
NONE
```
> [dashboard - login] align login page product desc.

- components/dashboard/src/start/StartWorkspace.tsx
- components/gitpod-protocol/src/util/gitpod-host-url.ts
- components/server/src/user/user-controller.ts
When testing `slow-server` we noticed that sometimes fetching of workspace-cookies would not work, but sent us into a dead-end redirect.
Analysis of logs showed that this might happen to some people regularly ([link](https://github.com/gitpod-io/gitpod/issues/15328#issuecomment-1373736924)), and might be related to outdated code: e.g. the handler we use (no longer?) supports handling redirects.
This PR removes that redirect logic, and replaces it with a re-try.
Context: #15328
```release-note
NONE
```
> Improve /auth/workspace-cookie fetching

- components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt
This PR propose changes to providing user options to open Usage Page, Open Feedback Issue, Help page of website directly from JetBrains Gateway.
|Old|New|
|:---:|:---:|
|<img width="928" alt="image" src="https://user-images.githubusercontent.com/55068936/211487681-02944cc8-0f23-467c-b603-c2733d02a223.png">|<img width="951" alt="image" src="https://user-images.githubusercontent.com/55068936/211484102-14f3c2f6-2514-4ea7-a29d-0cce32052184.png">|
Fixes #
- Open JetBrains Gateway
- Install [Dev Version of this preview for Open Gitpod Plugin](https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions/Dev/275087)
- Click on Settings Gear Icon above `New Worksapce` Button
- See :eyes: new options :sparkles:
```release-note
Menu Options …
```
> [JetBrains-Gateway] Menu Options for Usage, Feedback, Help in JB Gateway Plugin

- components/server/src/workspace/gitpod-server-impl.ts
To ensure we fail early on bogus values. This is also a necessary pre-cursor to use an authorization system as we need to guarantee consistency of records
Fixes #
1. Interact with teams in preview
2. Make a request using the ws protocol with non-uuid values
```release-note
[server] Validate userID and teamID is a UUID on Team operations
```
> [server] Validate userID, teamID is a UUID on team operations

- components/dashboard/src/service/public-api.ts
- components/proxy/conf/Caddyfile
As step 7 for [internal chat](https://gitpod.slack.com/archives/C04HBF1GWJ0/p1673335543513649)
Fixes #
- ✅  All public apis in preview env dashboard should works, and request should be like gitpod.io/public-api/xxx
- ✅  Change main cookie domain to `hw-pub-proxyy.preview.gitpod-dev.com`, public API should work still
```release-note
NONE
```
> Add proxy route for public-api

- components/iam/pkg/oidc/service.go
This is a fix-up for #15577, where we wanted to get rid of the returned error if test config was not found.
```release-note
NONE
```
> [iam] (actually) don't fail if test config is missing

- components/server/src/iam/iam-oidc-create-session-payload.ts
- components/server/src/iam/iam-session-app.spec.ts
- components/server/src/iam/iam-session-app.ts
During the OIDC flow, the `iam` component does a `POST` request to the server internally which should ensure a HTTP session is created to proceed with. This PR comes with the implementation of an account look-up.
To simplify things, I decided to map `authProviderId` to `issuerID` and `authId` to `subject`. There is no complete mapping of auth providers to OIDC clients included, as it might be not required and potentially wrong.
Based on #15629
Part of #7761
Fixes #14954
```release-note
NONE
```
> [oidc] find/create User account

- .github/CODEOWNERS
Update codeowners for ws-manager-api.
Fixes # n/a
n/a
```release-note
NONE
```
> [.githhub] update ws-manager-api codeowner

- WORKSPACE.yaml
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
Update code to `1.74.3`
A part of #14977 
```release-note
NONE
```
> VS Code `1.74.3`

- components/dashboard/src/projects/Project.tsx
- components/dashboard/src/projects/ProjectListItem.tsx
- components/gitpod-protocol/src/util/gitpod-host-url.ts
Adds a secondary "New Workspace ..." button the projects list on a team and the branches list on a project.
Fixes #
```release-note
Added a secondary button to start workspaces on projects and branches with options.
```
> [dashboard] add "with-options" buttons

- components/public-api/go/examples/workspaces_example.go
Examples of `public-api` Go Client for Workspace & Teams. Also https://github.com/gitpod-io/website/pull/3196
Fixes #
```release-note
NONE
```
> [public-api] examples: teams & workspaces examples in go

- .github/CODEOWNERS
- dev/preview/workflow/preview/deploy-gitpod.sh
- install/installer/pkg/components/components-webapp/components.go
- install/installer/pkg/components/openfga/constants.go
- install/installer/pkg/components/openfga/deployment.go
- install/installer/pkg/components/openfga/objects.go
- install/installer/pkg/components/openfga/service.go
- install/installer/pkg/config/v1/experimental/experimental.go
Deploys [OpenFGA](openfga.dev) when experimental.webapp.openfga.enabled is set to true.
Initially deploys OpenFGA in a `in-memory` mode.
* Part of https://github.com/gitpod-io/gitpod/issues/15634
1. Kubectx for preview
2. Observe `openfga` deployment exists and runs
```release-note
NONE
```
> [openfga] Deploy when experimental.webapp.openfga.enabled is true

- components/ide/jetbrains/gateway-plugin/BUILD.yaml
Use separate folders for caching Gradle dependencies from Stable and Latest JetBrains Gateway Plugin.
This prevents failures on Werft Build when the Stable and Latest have the same platform version (which happens after every major release from JetBrains IntelliJ) [[1](https://github.com/gitpod-io/gitpod/pull/15646#issuecomment-1378460217)].
It's the same strategy we used on JetBrains Backend Plugin [[1](https://github.com/gitpod-io/gitpod/blob/245cb43a7d48aa40c32d9ffb4c530b98ac5420b8/components/ide/jetbrains/backend-plugin/build.sh#L13)].
- https://github.com/gitpod-io/gitpod/pull/15646#issuecomment-1378460217
Confirm if Werft Build passes.
```release-note
NONE
```
> Use separate folders for caching Gradle dependencies from Stable and Latest JetBrains Gateway Plugin

- dev/preview/infrastructure/gce/certificate-letsencrypt.tf
- dev/preview/infrastructure/gce/certificate-zerossl.tf
- dev/preview/infrastructure/gce/cloudinit.yaml
- dev/preview/infrastructure/gce/dns.tf
- dev/preview/infrastructure/gce/namespace.tf
- dev/preview/infrastructure/gce/provider.tf
- dev/preview/infrastructure/gce/proxy.tf
- dev/preview/infrastructure/gce/startup-script.sh
- dev/preview/infrastructure/gce/variables.tf
- dev/preview/infrastructure/gce/vm.tf
This PR adds GCE Infra required to run preview envs. Other PRs will follow with leeway/werft integration and a tidying up of the terraform for both harvester/gce and a small change in `previewctl install-context`
* The VM is created directly from the VMI from ws clusters
* Separated the original cloud-init into 2 (gce only for now):
* cloud-init to set-up the machine (docker, disable services)
* startup-script to install k3s - will try to get this one to execute in tf with remote exec - so k3s installation is synchronous
* Disable and stop `load-workspace-full.service` for both harvester and gce
* This seems that has been running always, and pulls a couple of GB of images (workspace-full) on every machine start. Should considerably speed up preview env startup as we don't need those …
> Preivew env GCE infra

- components/dashboard/src/components/SelectIDEComponent.tsx
Fixes the missing entry for latest editors.
Fixes #15693
Start a worksapce from workspaces dashboard and verify you see the latest editors in the drop down.
```release-note
NONE
```
> [dashboard] list latest editor if available

- dev/preview/workflow/preview/deploy-gitpod.sh
[preview] add missing workspace class template
Fixes #
1. start workspace in this prev environment
2. run `export | grep SEGMENT` it should show segment key
```release-note
NONE
```
> [preview] add missing workspace class template

- install/installer/pkg/components/openfga/constants.go
- install/installer/pkg/components/openfga/deployment.go
- install/installer/pkg/config/v1/experimental/experimental.go
Adds a cloud-sql-proxy sidecar to the `openfga` deployment, if a CloudSQL config is specified.
We require that the `openfga` deployment talks to a database in a _single_ region. That means we can't use the existing cloud-sql-proxy because that is configured to talk to a regional instance.
* Part of https://github.com/gitpod-io/gitpod/issues/15634
Not really testable in preview, will need to validate on staging with config.
```release-note
NONE
```
> [openfga] Configure cloud-sql-proxy sidecar

- components/supervisor/pkg/serverapi/publicapi.go
Use workspaceStatus stream rpc in supervisor
Requires https://github.com/gitpod-io/gitpod/pull/15451
Open a workspace and check port view updates successfully when changing port state to public/private
```release-note
NONE
```
> Use workspaceStatus stream rpc in supervisor

- components/dashboard/src/contexts/FeatureFlagContext.tsx
See https://gitpod.slack.com/archives/C0463A2KQUU/p1673436459139739 for details
Fixes #
```release-note
[dashboard] Default use public API when interacting with Teams
```
> [dashboard] Enable Public API Teams service by default

- install/installer/pkg/components/openfga/deployment.go
* Depends on https://github.com/gitpod-io/gitpod/pull/15692
```release-note
NONE
```
> [openfga] Configure CloudSQL datastore

- components/ide/jetbrains/gateway-plugin/build.gradle.kts
Signed-off-by: 勇里 <yongli.zzp@antgroup.com>
when I runIde with 2022.3.1 IDEA ,it shows 
the log shows :
JNA library is not available
see the issue  at https://youtrack.jetbrains.com/issue/IDEA-265943/Due-to-JNA-outdate-runIde-failed-on-Apple-silicon-with-IC-2020.3.3#focus=Comments-27-6739382.0-0 
need to update org.jetbrains.intellij to 1.11.0 
after change the version ,the runIde task is ok.
Fixes #
```release-note
fix-IDEA2022.3-gradle-runIde
```
> [JetBrains-Gateway] fix-IDEA2022.3-gradle-runIde

- components/public-api/go/config/config.go
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/iam/networkpolicy.go
- install/installer/pkg/components/public-api-server/configmap.go
- install/installer/pkg/components/public-api-server/configmap_test.go
This PRs comes with the installer changes for OIDC enablement:
* required ingress rule to support calling OIDC service from PAPI
* OIDC service address configuration
Part of #15150
```release-note
NONE
```
> [installer] Enable service OIDC service calls from PAPI

- install/installer/pkg/components/openfga/deployment.go
Fixes #
```release-note
NONE
```
> [openfga] Fix database name interpolation into datastore uri

- components/dashboard/src/contexts/FeatureFlagContext.tsx
See https://gitpod.slack.com/archives/C0463A2KQUU/p1673436459139739 for details
Fixes #
```release-note
NONE
```
> [api] usePublicApiProjectsService defaults to true

- operations/observability/mixins/cross-teams/dashboards/gitpod-overview.json
Use the right y-axis for image build workspaces in the Grafana overview dashboard. Makes these workspaces stand out more, as they're usually hidden due to the amount of regular workspaces. Would let us detect lingering image build workspaces.
In an attempt to make it more visible that image builds use the right y-axis, made the lines dashed and staircased, but open to other suggestions 🙏 
See https://grafana.gitpod.io/d/y5txMP2Vk/gitpod-overview-duplicate-wouter?from=now-1h&to=now
See copy of overview dashboard with these changes here: https://grafana.gitpod.io/d/y5txMP2Vk/gitpod-overview-duplicate-wouter?from=now-1h&to=now
```release-note
NONE
```
> Switch image builds y-axis on Gitpod/Overview dashboard

- components/image-builder-bob/pkg/builder/builder.go
Increase log size to 4MB to prevent log clipping. See #7147  for details and discussion.
Fixes #7147 
See issue #7147 
```release-note
none
```
> increase buildkit log size to 4MB

- components/ws-manager/pkg/manager/status.go
- test/pkg/integration/workspace.go
For some reason, the pod is killed with unknown container status and no taints on the underlying node.
Therefore, we skip extracting the failure from the terminated message.
Fixes #12021
Ensure the workspace integration test pass.
I ran the integration test three times
- https://werft.gitpod-dev.com/job/gitpod-custom-jenting-12021.15
- https://werft.gitpod-dev.com/job/gitpod-custom-jenting-12021.16
- https://werft.gitpod-dev.com/job/gitpod-custom-jenting-12021.17
```release-note
None
```
> ws-manager: skip failure from terminated message

- components/dashboard/src/data/projects/fetchers.ts
Fixes an issue where a new project and project sorting would get sorted to the end of the projects list if there was no prebuild yet ([found here](https://github.com/gitpod-io/gitpod/pull/15676#discussion_r1066733079)).
Now, if there's no latest prebuild for a project, the project's creation time will be used for sorting.
**Preview Env:** https://bmh-new-pr441f0eae67.preview.gitpod-dev.com/
To test this, you have to be kinda quick 😄 .
* Create a team
* Create a project
* Create a 2nd project. After it's created, you can hit the browser back button to get back to the projects list w/o a page reload. The new project should be sorted first, even if it doesn't have a prebuild yet.
```release-note
NONE
``` …
> Use project creation time to sort when no prebuild

- test/tests/components/ws-daemon/cpu_burst_test.go
- test/tests/components/ws-daemon/fuse_device_test.go
- test/tests/components/ws-daemon/io_limiting_test.go
- test/tests/components/ws-daemon/network_limiting_test.go
- test/tests/components/ws-daemon/process_priority_test.go
- test/tests/components/ws-daemon/workspace_resource_info_test.go
test: Add some stub tests for ws-daemon
Follow-up https://github.com/gitpod-io/gitpod/pull/15494
```release-note
NONE
```
> test: Add some stub tests for ws-daemon

- components/gitpod-cli/cmd/docs.go
Open documentation from gitpod cli: `gp docs`
**Demo Video:**
https://user-images.githubusercontent.com/55068936/212272075-0225777c-6f0a-4404-9166-02af92703141.mov
Fixes #
- Open [Preview](https://feat-gitpod-cli.preview.gitpod-dev.com/workspaces)
- Open any workspace (`/empty`)
- run `gp docs`
```release-note
feat: `gp docs` in gitpod cli
```
- Req. Addition of [Gitpod CLI](https://www.gitpod.io/docs/references/gitpod-cli#gitpod-cli)
> feat: `gp docs` in gitpod cli

- components/gitpod-cli/cmd/rebuild.go
- components/gitpod-cli/pkg/utils/parseGitpodConfig.go
- components/gitpod-cli/pkg/utils/trackEvent.go
We're introducing a new command to gp cli, to facilitate users in testing the the build and run of custom Docker workspace images.
Note: if the user closes the terminal via the IDE once they are inside the debug container, the event won't be sent.
Relates to #7671
1. Start a workspace https://ide-gp-build.preview.gitpod-dev.com/#https://github.com/gitpod-io/empty
2. Run `gp rebuild` and observe error message
3. Specify a custom dockerfile (both using `image: xxx` or `image.file`
4. If you specify a non-existing file, and re-run, observe the error
5. Check in Segment Staging Trusted that `gp_command` is being sent with the following fields:
- errorCode
6. Configure a real image and re-run, exit the container
7. Check in Segment Staging Trusted that `gp_command` is being sent with the …
> [Gitpod CLI] `gp rebuild`

- components/public-api/typescript/package.json
Currently, we are using default version of `package.json` which shows public-API package as `UNLICENSED`. This PR propose changes to make it AGPL-3.0:
Fixes #
```release-note
NONE
```
No
> License: Public API npm package

- components/public-api-server/pkg/server/server.go
https://gitpod.slack.com/archives/C02EN94AEPL/p1673864498760149
Fixes #
```release-note
NONE
```
> [public-api] Set proxy connection pool to size 500

- components/dashboard/src/service/service.tsx
- components/dashboard/src/start/StartWorkspace.tsx
- components/gitpod-protocol/src/frontend-dashboard-service.ts
- components/gitpod-protocol/src/util/gitpod-host-url.ts
Step 3 of [internal chat](https://gitpod.slack.com/archives/C04HBF1GWJ0/p1673335543513649)
Changes make it has two websocket to server (dashboard / supervisor) when workspace started, supervisor one will be removed after [supervisor PR](https://github.com/gitpod-io/gitpod/pull/15663) deploy
Add hold in case we need further update
TODO:
Fixes #
Make sure we can start workspace in preview env
And test with PR https://github.com/gitpod-io/gitpod/pull/15663 (supervisor implement
```release-note
NONE
```
> [dashboard] support supervisor frontend server

- components/dashboard/src/teams/TeamSettings.tsx
- components/gitpod-db/src/team-db.ts
- components/gitpod-db/src/typeorm/team-db-impl.spec.db.ts
- components/gitpod-db/src/typeorm/team-db-impl.ts
- components/gitpod-protocol/src/gitpod-service.ts
- components/server/src/auth/rate-limiter.ts
- components/server/src/workspace/gitpod-server-impl.ts
Allow updating the team's name
fixes #5067
rename team name
```release-note
Allow renaming teams
```
> Allow Renaming Teams

- .werft/platform-delete-preview-environment.yaml
Adds resource requirements for preview delete job - this will make the nodepool scale up if many are launched concurrently.
Fixes #
```release-note
NONE
```
> Add resource requirements for preview delete job

- components/ide-proxy/conf/Caddyfile
- components/proxy/conf/Caddyfile
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/proxy/templates/configmap/vhost.payment-endpoint.tpl
Stop setting the `X-Real-IP` header on upstream requests from Caddy.
The value of the header was being set to the IP address of a machine inside GCP rather than the the actual client IP address.
To ensure that the header contains the actual client IP address, this header will be set at the GCP load balancer and so should not be set at the Caddy proxy.
The value of `X-Real-IP` was not used anywhere so it is safe to stop setting this at the Caddy proxy.
Part of https://github.com/gitpod-io/gitpod/issues/15600
* `proxy` and `ideproxy` run without error in the preview environment. 
* It is still possible to start and interact with workspaces in the preview environment.
```release-note
NONE
``` …
> [proxy, ideproxy] Stop setting `X-Real-IP` header on upstream requests from Caddy

- components/supervisor/pkg/ports/exposed-ports.go
- components/supervisor/pkg/serverapi/publicapi.go
- components/supervisor/pkg/supervisor/supervisor.go
Address plan https://github.com/gitpod-io/gitpod/pull/15723#issuecomment-1381444444
- Change our interface -> we don't need instanceID or workspaceID in supervisor as it only works for current workspace itself.
- Listen to server/pubcli API instanceUpdates inside, once Service created.
- Add subscriber once outside call InstanceUpdates
Fixes #
Related https://github.com/gitpod-io/gitpod/issues/15383
Check if instance updates works as before (check **How to Test** section of PR https://github.com/gitpod-io/gitpod/pull/15723)
```release-note
NONE
```
> [supervisor] improve instance updates

- components/dashboard/src/components/Alert.tsx
- components/dashboard/src/components/ConfirmationModal.tsx
- components/dashboard/src/teams/TeamSettings.tsx
- components/dashboard/src/workspaces/WorkspaceEntry.tsx
- added a variable `currentChanges` to check for pending changes, default: `false`.
- checking for latest changes and respectively update `currentChanges`
- in `ConfirmationModal`, passed a prop for alert message.
- added another property `warningHead`, to make the content bold other then `warningText` which have font-weight normal, For example `Warning`, `Pending Changes`. 
Fixes #15669 
- Add a workspace that contains some changes!
- try to delete the workspace
```release-note
None
```
> [feat] : Warning alert in workspace delete confirmation model for pending changes

- .github/pull_request_template.md
- .github/workflows/poc-build.yml
- .werft/build.ts
- .werft/jobs/build/job-config.ts
This PR aims to make it super easy to opt into running the build in GitHub Actions instead of Werft.
For this, this PR introduces the flag:
```
[ ] /werft with-github-actions
```
which gets interpreted by both GHA and Werft:
Jobs from the GitHub Actions Workflow (named "PoC-build" in the screenshot)  will run on the PR:
The Werft Build will show as "running" and "passing", but perform a no-op:
The Werft build will run normally.
The GHA Jobs will be shown as "skipped":
Fixes [#15748](https://github.com/gitpod-io/gitpod/issues/15748)
* check/uncheck the `werft with-github-actions` on this PR.
* Run `werft run github -a with-github-actions=true` to test the changes in Werft. Triggering the job via CLI is necessary to make job protection happy.
* I'd prefer to run GHA and Werft simultaneously …
> Optional GHA-Builds via argument '/werft with-github-actions'

- operations/observability/mixins/meta/rules/content-service.yaml
- operations/observability/mixins/meta/rules/dashboard.yaml
- operations/observability/mixins/meta/rules/db-sync.yaml
- operations/observability/mixins/meta/rules/db.yaml
- operations/observability/mixins/meta/rules/messagebus.yaml
- operations/observability/mixins/meta/rules/payment-endpoint.yaml
- operations/observability/mixins/meta/rules/proxy.yaml
- operations/observability/mixins/meta/rules/server.yaml
- operations/observability/mixins/meta/rules/usage.yaml
- operations/observability/mixins/meta/rules/ws-manager-bridge.yaml
Groups CPU alerts by their deployment. To do this, a new alert is introduced for each of the original selectors as we cannot target a deployment as a collection of resources for an aggregate metric.
This change should reduce noise in the alerts channel, as we only consider it as firing if the aggregate of the pods has increased.
Fixes #
```release-note
NONE
```
> [webapp] Group CPU alerts by deployment

- components/dashboard/src/projects/Projects.tsx
We are going to apply an automated transition. No need to confuse users with this message.
Fixes #
```release-note
NONE
```
> [dashboard] remove deprecation warning on user /projects

- components/public-api-server/pkg/apiv1/oidc.go
- components/public-api-server/pkg/apiv1/project.go
- components/public-api-server/pkg/apiv1/team.go
- components/public-api-server/pkg/apiv1/team_test.go
- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/apiv1/user.go
- components/public-api-server/pkg/apiv1/validation.go
- components/public-api-server/pkg/apiv1/workspace.go
So far the validation functions have been largely co-located with the handler implementation. This change moves them to a dedicated file. This allows for re-use across packages, where relevant, and makes it slightly more discoverable. Subsequent PR will unify UUID parsing a bit to reduce repetition.
Fixes #
unit tests
```release-note
NONE
```
> [papi]  Refactor validation functions to a file

- components/ws-manager-bridge/src/bridge.ts
Fixes https://github.com/gitpod-io/security/issues/113
```release-note
NONE
```
> [ws-manager-bridge] Stop logging status.auth field

- components/ws-manager-bridge/ee/src/prebuild-updater-db.ts
- components/ws-manager-bridge/src/bridge.ts
Fixes https://github.com/gitpod-io/security/issues/113
```release-note
NONE
```
> [ws-manager-bridge] Stop logging workspacestatus.auth for prebuilds

- .github/workflows/build.yml
This PR renames the build from "PoC-Build" to "Build" to reflect the fact that it's no longer PoC. 
It's still experimental, but that does not need to be communicated via its name. Instead, we communicate this in the PR-description-checkbox that's used to trigger the build.
Fixes #
```release-note
NONE
```
> Rename GHA-Build from PoC-Build to Build

- components/registry-facade/pkg/registry/registry.go
- install/installer/pkg/components/registry-facade/daemonset.go
Fix configuration when only Redis is enabled
extracted from https://github.com/gitpod-io/gitpod/pull/15132
```release-note
NONE
```
> Redis could be enabled without IPFS

- .werft/jobs/build/deploy-to-preview-environment.ts
- .werft/jobs/build/installer/installer.ts
- .werft/jobs/build/job-config.ts
- dev/preview/workflow/preview/deploy-gitpod.sh
This adds the initial step towards a setup mode trigger. The motivation is to provide a way for iterative work on Dedicated setups. 
Trigger a new build of a preview env using `werft` from within a workspace. GH integration doesn't use the same version of `/workspace/gitpod/.werft/jobs/build/job-config.ts`, thus it wont work with the `/werft` comment. 
```
$ werft run github -j .werft/build.yaml -a with-preview=true -a with-clean-slate-deployment=true -a with-dedicated-emulation=true
```
The custom build should not contain any auth providers, thus they'd need to be created in the app.
```release-note
NONE
```
> [werft] add `with-dedicated-emulation` switch

- .github/workflows/build.yml
- components/BUILD.yaml
This PR modified the GHA build to build the same components as the Werft build.
Instead of calling the [Leeway default target](https://github.com/gitpod-io/gitpod/blob/main/WORKSPACE.yaml#L2), it introduces a new target named `components:all-ci` so it can:
* also build `dev:all` (The Werft job does this with an [additional call of `leeway build`](https://github.com/gitpod-io/gitpod/blob/ef72a6901cc756bdf58478d3094d846fc90558d2/.werft/jobs/build/build-and-publish.ts#L37-L40).
* export files `previewctl` and `versions.yaml`.
Fixes https://github.com/gitpod-io/gitpod/issues/15759
```release-note
NONE
``` …
> Build all components

- components/dashboard/src/start/StartWorkspace.tsx
We've recently introduced `gp rebuild` to help users debug their custom workspace image. In the future it will do more. We hope to reduce the number of image build failures caused by config changes that could have been caught in a workspace, before pushing.
Relates #7671
1. Start a workspace for https://ide-gp-rebbd1841bbcb.preview.gitpod-dev.com/?workspaceClass=default&editor=code#https://github.com/andreafalzetti/gitpod-experiments/tree/imagebuild-broken
2. Observe the message educating about the use of `gp rebuild` underneath the logs 
```release-note
NONE
```
> [Dashboard] Suggest using `gp rebuild` when image build fails

- components/dashboard/src/start/StartWorkspace.tsx
Follow-up PR addressing feedback from: https://github.com/gitpod-io/gitpod/pull/15774
Fixes #
```release-note
NONE
```
> dashboard: update gp rebuild copy

- WORKSPACE.yaml
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
Updates VS Code Stable to the same version `1.74.3` but with [cherry picked commits](https://github.com/gitpod-io/openvscode-server/commits/gp-code/release/1.74) from @jeanp413 and @filiptronicek about `gp-run`.
| with feature flag enabled | without |
|-|-|
|<img width="150" alt="Screenshot 2023-01-13 at 18 43 04" src="https://user-images.githubusercontent.com/2318450/212415009-6c7eb6d7-4d57-4775-973e-5a70757b6410.png"> | <img width="150" alt="Screenshot 2023-01-13 at 20 38 23" src="https://user-images.githubusercontent.com/2318450/212415005-08399a43-1435-41bb-9e10-4ca368456e3d.png">|
Related #15490 
This feature is behind FG in Configcat `ide_service_experimental_rungp`.
1. Using VS Code Browser stable, start a workspace: https://ide-debug-ws-code.preview.gitpod-dev.com/?editor=code-lates …
> [Code][Inner Loop] Add Codelens for launching debug workspace window

- components/server/src/express-util.ts
Use a new `X-Real-IP` header for cookieless tracking rather than relying on the `X-Forwarded-For` header that the GCP loadbalancer sets by default. The `X-Forwarded-For` header is truncated by Caddy [[1](https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#defaults)], removing the true client IP and leaving just the IP of the GCP LB.
By defining a new custom header at the LB and setting it to the client IP, we ensure that Caddy forwards it to `server` without modification.
If we decide to go ahead with this approach we need to configure the `X-Real-IP` header on the production loadbalancer just as has already been done for the staging loadbalancer.
Fixes #15600
* Take the image of `server` built on this branch and use it to update the `image` of the `server` deployment in …
> [server] Correctly record client IP for analytics purposes 

- components/gitpod-cli/cmd/rebuild.go
- components/gitpod-cli/pkg/utils/trackEvent.go
Follow up PR of things we overlooked in the [initial PR](https://github.com/gitpod-io/gitpod/pull/15638):
1. add event `outcome`, 
2. use the tmp dockerfile
3. build from checkout location context (using `.` won't work if the user is inside a sub-directory)
4. the Stderr coming from `docker run` should not be propagated outside of the container because it can be anything (e.g user typing `exit 1`) which currently gets logged as an error from `gp rebuild`
5. return an explicit `nil` error when there is not real error
| success event | user error | system error |
|-|-|-
| <img width="762" alt="Screenshot 2023-01-17 at 22 27 53" src="https://user-images.githubusercontent.com/2318450/213076651-5350fa25-1e88-447a-8b17-46b471c2a809.png"> | <img width="754" alt="Screenshot 2023-01-17 at 22 27 …
> [Gitpod CLI] `gp rebuild` improvements

- components/gitpod-db/go/dbtest/oidc_client_config.go
- components/gitpod-db/go/oidc_client_config.go
- components/gitpod-db/src/typeorm/migration/1673944879912-AddOrganizationIDToOIDCClientConfig.ts
* Part of https://github.com/gitpod-io/gitpod/issues/15708
```release-note
NONE
```
> [db] Add organisationId to d_b_oidc_client_config + indices

- dev/preview/previewctl/cmd/stale.go
- dev/preview/previewctl/cmd/workspaces.go
Fixes #
```release-note
NONE
```
> [previewctl] point to infra dir by default for stale

- operations/observability/mixins/meta/rules/dashboard.yaml
- operations/observability/mixins/meta/rules/db-sync.yaml
- operations/observability/mixins/meta/rules/db.yaml
- operations/observability/mixins/meta/rules/payment-endpoint.yaml
- operations/observability/mixins/meta/rules/proxy.yaml
- operations/observability/mixins/meta/rules/ws-manager-bridge.yaml
Names clashed with each other, copy-paste mistake 
Fixes #
```release-note
NONE
```
> [obs] Fix webapp monitoring rule names

- operations/observability/mixins/meta/rules/content-service.yaml
- operations/observability/mixins/meta/rules/dashboard.yaml
- operations/observability/mixins/meta/rules/db-sync.yaml
- operations/observability/mixins/meta/rules/db.yaml
- operations/observability/mixins/meta/rules/messagebus.yaml
- operations/observability/mixins/meta/rules/payment-endpoint.yaml
- operations/observability/mixins/meta/rules/proxy.yaml
- operations/observability/mixins/meta/rules/server.yaml
- operations/observability/mixins/meta/rules/usage.yaml
- operations/observability/mixins/meta/rules/ws-manager-bridge.yaml
* Changes the metric to `avg`. Sum was incorrect as it would add up all pods together. Average is what we're after
* Updates thresholds for each service, based on existing data over the last 30 days
Fixes #
https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22avg%28rate%28container_cpu_usage_seconds_total%7Bcontainer%21%3D%5C%22POD%5C%22,%20pod%3D~%5C%22ws-manager-bridge-.%2A%5C%22%7D%5B5m%5D%29%29%20by%20%28cluster%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-30d%22,%22to%22:%22now%22%7D%7D
Adjust the pod name selector …
> [obs] Adjust CPU alert thresholds for webapp services

- install/installer/README.md
- install/installer/pkg/config/README.md
Takes the discussion with @corneliusludmann (see [Notion](https://www.notion.so/gitpod/Installer-Configuration-Contract-c2a82878089e4ce5b2edccb6c92b7c4c)) and formalises as our requirements for the config surface
Fixes #15121
```release-note
NONE
```
> [installer]: define the rules around the configuration

- dev/preview/workflow/preview/deploy-gitpod.sh
Forgot to remove the config from preview.
Fixes #
```release-note
NONE
```
> Remove openfga from preview config

- components/gitpod-cli/cmd/timeout-set.go
- components/gitpod-cli/cmd/timeout-show.go
- components/gitpod-protocol/go/gitpod-service.go
- components/gitpod-protocol/go/mock.go
- components/gitpod-protocol/src/gitpod-service.ts
- components/server/ee/src/user/user-service.ts
- components/server/ee/src/workspace/gitpod-server-impl.ts
- components/server/src/user/user-service.ts
- components/server/src/workspace/workspace-starter.ts
Makes setWorkspaceTimout handle arbitrary poistive duration strings, matching the format <\D+[mhd]>, which is compatible with go's time Duration.
Fixes #9038
- Verify that extending timouts still work as before
- try `gp timeout set 4h` 
```release-note
A new CLI command `gp timeout set` allows to set the workspace timeout to arbitrary durations.
```
> [server, cli] Allow flexible workspace timeouts

- components/content-service/pkg/storage/storage.go
- components/gitpod-protocol/src/billing-mode.ts
- install/installer/cmd/mirror_list.go
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-workspace/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/cluster/affinity.go
- install/installer/pkg/common/storage.go
- install/installer/pkg/components/blobserve/deployment.go
- install/installer/pkg/components/image-builder-mk3/deployment.go
- install/installer/pkg/components/ws-manager/deployment.go
- install/installer/pkg/components/ws-proxy/constants.go
- install/installer/pkg/components/ws-proxy/deployment.go
- install/installer/pkg/components/ws-proxy/objects.go
- install/installer/pkg/config/v1/config.go
- install/installer/pkg/config/v1/envvars.go
- install/installer/pkg/config/v1/envvars_test.go
- Fix service port mappings to allow the use of TargetGroupBinding (AWS
- Change node labels
- Fix image-builder-mk3 affinity label to run in the services node pool
fixes https://github.com/gitpod-io/gitpod/issues/15131
```release-note
NONE
```
> Change services node label

- dev/preview/infrastructure/scripts/bootstrap-k3s.sh
- install/infra/modules/aks/kubernetes.tf
- install/infra/modules/eks/kubernetes.tf
- install/infra/modules/gke/cluster.tf
- install/infra/modules/k3s/main.tf
- install/installer/docs/overview.md
- install/installer/pkg/config/README.md
- install/preview/entrypoint.sh
Required after https://github.com/gitpod-io/gitpod/pull/15132
```release-note
NONE
```
> Update services node pool labels

- components/gitpod-db/go/oidc_client_config.go
- components/gitpod-db/go/oidc_client_config_test.go
Initial, basic unpaginated implementation of list oidc client configs. Pagination will be added in subsequent PR.
* Part of https://github.com/gitpod-io/gitpod/issues/15153
* Used in https://github.com/gitpod-io/gitpod/pull/15852
Unit tests
```release-note
NONE
```
> [db] Implement basic list oidc client configs

- .github/actions/preview-create/Dockerfile
- .github/actions/preview-create/entrypoint.sh
- .github/actions/preview-create/metadata.yml
- .github/workflows/build.yml
This introduces a custom action that's a wrapper around our Leeway script. This will make it easier to use as a building block in other workflows. We can then later simplify the "implementation" without requiring users of our action to change anything. See [Migration strategy for preview-dependent Werft jobs](https://www.notion.so/gitpod/Migration-strategy-for-preview-dependent-Werft-jobs-6aaeb1a22c0b4f0696827fdc27e55a3e) for more context.
Part of https://github.com/gitpod-io/ops/issues/7795
See the latest Build Workflow [here](https://github.com/gitpod-io/gitpod/actions/runs/3949349883)
```release-note
NONE
``` …
> [PoC] Custom GitHub Action to create preview environments

- components/server/src/one-time-secret-server.ts
- components/server/src/user/user-controller.ts
- components/server/src/workspace/workspace-starter.ts
Add `OneTimeSecretServer.serveToken` and rename existing API.
Part of https://github.com/gitpod-io/gitpod/pull/15805
```release-note
NONE
```
> [server] Add OneTimeSecretServer.serveToken

- components/public-api-server/pkg/apiv1/oidc.go
- components/public-api-server/pkg/apiv1/oidc_test.go
- components/public-api-server/pkg/apiv1/validation.go
Forwards Organization ID to IAM OIDC service
* Part of https://github.com/gitpod-io/gitpod/issues/15708
Unit tests
```release-note
NONE
```
> [oidc] Propagate OrganizationID to IAM component

- components/iam/pkg/apiv1/oidc_config.go
- components/iam/pkg/apiv1/oidc_config_test.go
Uses the OrganizationID from the CreateOIDCClientConfig RPC to store it in the DB.
* Part of https://github.com/gitpod-io/gitpod/issues/15708
Unit tests
```release-note
NONE
```
> [iam] Store OrganizationID with OIDC Client Configs

- components/public-api-server/pkg/apiv1/validation.go
Reduces duplicated validation checks, functionally remains the same
Fixes #
```release-note
NONE
```
> [public-api] Reduce duplication in validation functions

- install/installer/cmd/render.go
- install/installer/cmd/testdata/render/overrides-inline/config.yaml
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/pkg/config/v1/experimental/experimental.go
- install/installer/pkg/postprocess/override.go
> This is an `experimental` feature until Gitpod Dedicated hits general availability. At that point, this should be refactored or removed if not required.
This is a proposal for how to override the generated manifests. This is something required for Gitpod Dedicated. There will the requirement for differences between Dedicated and Gitpod.io, depending upon which cloud provider it's installed in. These will likely be arbitrary and will need to be implemented quickly.
Unlike the [customizations](https://www.gitpod.io/docs/configure/self-hosted/latest/advanced/customization), there will be no limitation on what can be applied. To that end, there is now a new `overrides` array. As with the customizations, it will match resource by `APIVersion`, `Kind` and `Metadata.Name` - it is …
> [installer]: add override option to arbitrarily change the output

- components/dashboard/src/hooks/use-user-and-teams-loader.ts
Fixes a bad redirect that is happening when you've had a team selected in a previous session and you then load the page on gitpod.io.
Fixes #
Create a team and select it (go to its projects page).
reload te page on the preview environments default route (`/`) and verify that you end up on /workspaces and not get send back to the team's projects list.
```release-note
NONE
```
> [dashboard] never redirect to projects from /

- components/public-api/go/config/config.go
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/public-api-server/configmap.go
- install/installer/pkg/components/public-api-server/configmap_test.go
- install/installer/pkg/components/public-api-server/deployment.go
- install/installer/pkg/components/public-api-server/deployment_test.go
Mounts database secret as a volume/volume-mount onto Public API. This will allow the public-api to access the secret from files, including the db-decryption key which can then be used to merge the `iam` component with `public-api` ([thread](https://gitpod.slack.com/archives/C02EN94AEPL/p1674073546820559))
Config remains unused, will be used in subsequent PRs
Fixes #
* Unit tests
* Preview deploys public-api and the deployment starts
```release-note
NONE
```
> [installer] Mount database secret to Public API

- install/installer/cmd/testdata/render/telemetry/config.yaml
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/pkg/components/gitpod/cronjob.go
- install/installer/pkg/config/v1/config.go
- install/installer/pkg/config/v1/deprecations.go
- install/installer/pkg/config/v1/experimental/experimental.go
> This depends upon #15773
Promote the telemetry config from `experimental`  to the mainline
Fixes #15836
No changes in render tests except config change
```release-note
[installer]: promote experimental telemetry config
```
> [installer]: promote experimental telemetry config

- install/installer/cmd/testdata/render/agent-smith/config.yaml
- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/pkg/components/agent-smith/configmap.go
- install/installer/pkg/config/v1/config.go
- install/installer/pkg/config/v1/deprecations.go
- install/installer/pkg/config/v1/experimental/experimental.go
> This depends upon #15773
Promote the agent-smith config from `experimental` to the mainline
Fixes #15837
No changes in render tests except config change
```release-note
[installer]: promote experimental agent-smith config
```
> [installer]: promote experimental agent-smith config

- .github/CODEOWNERS
Makes webapp condeowners of the component
Solves https://github.com/gitpod-io/gitpod/pull/15876#pullrequestreview-1261621534
Fixes #
```release-note
NONE
```
> [spicedb] Make webapp codeowners of spicedb component

- install/installer/pkg/components/spicedb/deployment.go
Left-over from the move from OpenFGA to SpiceDB. SpiceDB doesn't have an HTTP endpoint for the liveness probe
Fixes #
```release-note
NONE
```
> [spicedb] Remove liveness probe

- components/gitpod-db/go/oidc_client_config.go
- components/public-api-server/pkg/apiv1/oidc.go
- components/public-api-server/pkg/apiv1/oidc_test.go
- components/public-api-server/pkg/server/server.go
Initial implementation of listing OIDC client configs.
Pagination, and populating the response more fully will come in subsequent PRs
* Depends on https://github.com/gitpod-io/gitpod/pull/15851
* Part of https://github.com/gitpod-io/gitpod/issues/15153
```release-note
NONE
```
> [oidc] List client configs basic API implementation

- components/iam/pkg/oidc/oauth2.go
- components/iam/pkg/oidc/router.go
- components/iam/pkg/oidc/router_test.go
- components/iam/pkg/oidc/service.go
- components/iam/pkg/oidc/service_test.go
- components/iam/pkg/server/server.go
- components/server/src/iam/iam-session-app.ts
With DB persistence of OIDC client configs in place, these changes enable actually using them after creation via API.
1. API calls look like this (curl style) 
```sh
curl 'https://api.at-oidc-proxy.preview.gitpod-dev.com/gitpod.experimental.v1.OIDCService/CreateClientConfig' \
-H 'content-type: application/json' \
-H 'Authorization: Bearer gitpod_pat_READACTED' \
--data '{"config": { "organizationId": "d3b6708c-360f-41d0-8d1a-cc716b8cf686", "oidcConfig": {"issuer": "https://accounts.google.com"}, "oauth2Config": {"scopesSupported": ["openid", "email", "profile"], "clientId": "REDACTED.apps.googleusercontent.com", "clientSecret": "GOCSPX-REDACTED-t"} }}'
```
2. Responses look like this
```json
{"config":{"id":"b8da1816-e45c-49a7-ab45-f56297123861","organizationId":"d3b6708c-360f-41d0-8d1a-c …
```
> [iam/oidc] Read OIDC config from DB

- operations/observability/mixins/workspace/rules/central/nodes.yaml
This alert has no direct impact on the user, so it should be at the WARN level.
e.g. If a scale-up failure is affecting users, the InstanceStartFailures alert should go off because users' workspace cannot launch any cluster due to a lack of resources.
https://github.com/gitpod-io/gitpod/blob/7706df3313e91bb36d4e51915f3fd8d6595b0d3e/operations/observability/mixins/meta/rules/server.yaml#L36-L45
Fixes https://github.com/gitpod-io/gitpod/issues/15863
```release-note
NONE
```
> obs: Make AutoscaleFailure ago down to warning level

- dev/preview/infrastructure/outputs.tf
- dev/preview/workflow/lib/common.sh
- dev/preview/workflow/lib/terraform.sh
- dev/preview/workflow/preview/deploy-harvester.sh
- dev/preview/workflow/preview/determine-env.sh
```
Choose your infra provider
1) harvester
2) gce
#? 2
You have chosen [gce], but in the state we have [harvester]. Continuing will destroy and recreate your environment. Are you sure? [y/n]: n
Aborted
```
Fixes https://github.com/gitpod-io/ops/issues/7802
```release-note
NONE
```
> Option to choose between infra provider when running `leeway run dev:preview`

- components/ws-proxy/pkg/proxy/config.go
- components/ws-proxy/pkg/proxy/routes.go
- components/ws-proxy/pkg/proxy/routes_test.go
- components/ws-proxy/pkg/proxy/workspacerouter.go
- components/ws-proxy/pkg/proxy/workspacerouter_test.go
- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-workspace/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/constants.go
- install/installer/pkg/components/ws-proxy/configmap.go
It is a prerequisite to https://github.com/gitpod-io/gitpod/pull/15795. Based on Pudong's work from https://github.com/gitpod-io/gitpod/pull/15687.
Fixes #
It is not possible to test new functionality yet. Only in context of https://github.com/gitpod-io/gitpod/pull/15795. Review code and tests. Test for regressions, i.e. start a workspace, start something inside and check that you can access it.
```release-note
NONE
```
> [ws-proxy] support ports location for debug workspace

- dev/preview/workflow/preview/determine-env.sh
Follow-up-fix for #15894:
At the initial creation of a preview env, `terraform output` outputs:
Thus, the check `[[ -z "${state_output}" ]]` is true even though we're not getting a valid value.
This PR tightens the check to only accept valid values.
If did not find args for `terraform output` that would make it skip this warning message. 
Fixes #15894
```release-note
NONE
```
> Preview Env Bugfix

- components/dashboard/src/start/StartWorkspace.tsx
Cleanup old code in StartWorkspace.tsx
1. Start a workspace and check vscode web ide loads sucessfully
```release-note
NONE
```
> Cleanup old code in StartWorkspace.tsx

- components/dashboard/src/service/service.tsx
- components/dashboard/src/start/StartWorkspace.tsx
- components/gitpod-protocol/src/frontend-dashboard-service.ts
- components/supervisor/frontend/src/regular.ts
- components/supervisor/frontend/src/shared/frontend-dashboard-service.ts
- components/supervisor/frontend/src/shared/loading-frame.ts
- add docs and security notes
- remove implementation methods from the interface
- fix a regression with opening desktop IDEs on the workspace origin
- allow to access the interface from other locations for the same workspace, i.e. for dev and debug modes
Changes are backward compatible and does not require coordinated deployment. But a follow up clean up PR is required after both supervisor and dashboard are deployed.
Fixes #
Start a workspace with IntelliJ IDEA, check that you can open VS Code Browser and IntelliJ IDEA. While redirection got IntelliJ the origin should be gitpod, not workspace.
```release-note
NONE
``` …
> polish IDEFrontendDashboardService

- components/server/src/prometheus-metrics.ts
- components/server/src/workspace/workspace-starter.ts
- install/installer/cmd/testdata/render/overrides-inline/output.golden
Track workspace start failures due to resource exhaustion.
* Add a new `resourceExhausted` reason for ws failures.
* Throw on resource exhaustion when trying to start a workspace rather than trying the next cluster as we do for other grpc errors.
* Construct a StartInstanceError with the `resourceExhausted` reason when the exception is handled.
This gives us a new "resourceExhausted" dimension on the `gitpod_server_instance_starts_failed_total` metric that can be used to track start failures due to resource exhaustion.
Part of https://github.com/gitpod-io/gitpod/issues/15083
It's hard to test resource exhaustion in a preview environment. 
* I edited https://github.com/gitpod-io/gitpod/blob/c28bef7cecaa2bc1061cba617c84319e9bbd14c9/components/common-go/grpc/ratelimit.go#L160 to always …
> [server] Track workspace start failures due to resource exhaustion as part of the `gitpod_server_instance_starts_failed_total` metric

- .github/pull_request_template.md
- .github/workflows/build.yml
This PR:
* adds a flag to specify the leeway build target in the PR description.
* adds a flag to disable the leeway cache.
* adds `set -x` so the `leeway build` command is printed in full in the build logs.
* adds a step for flag parsing not to clutter the "leeway" step. Parsing is now done in bash - we may want to refactor that to something more robust later.
These changes help to test the build, because they allow building individual components explicitly, without the cache getting in the way or the large dependency tree causing long wait times.
* Changing the leeway target bars risks: It breaks preview environments (because `installer` and `values.yaml` are no longer available) and if the build no longer builds all components, it no longer guarantees that the main build won't fail. …
> Simplify testing leeway in GHA builds

- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
This should fix the build.
```release-note
NONE
```
> [installer] regenerate render tests

- .github/workflows/build.yml
- .werft/build.yaml
- components/gitpod-db/BUILD.yaml
Start a MySQL-Container alongside the GHA build. It's used by Database-Unit-Test.
Fixes #15823
Successful Werft build: https://werft.gitpod-dev.com/job/gitpod-build-meysholdt-support-running-tests-15823.15/logs
Successful GHA build: https://github.com/gitpod-io/gitpod/actions/runs/3968144594/jobs/6800934542
```release-note
NONE
```
leeway-target=components/gitpod-db:dbtest-init 
> Add MySQL service

- .github/pull_request_template.md
- .github/workflows/build.yml
* Add support for the `no-test` flag.
* Export Test Coverage Reports as build artifacts.
Fixes #15769
* Build with TestCoverageReport: https://github.com/gitpod-io/gitpod/actions/runs/3968343938 
* Build with No-test: https://github.com/gitpod-io/gitpod/actions/runs/3968284554/jobs/6801254201
```release-note
NONE
```
leeway-target=components/ws-manager:app
> Add support for unit tests

- components/public-api-server/go.mod
- components/public-api-server/go.sum
- components/public-api-server/pkg/apiv1/oidc.go
- components/public-api-server/pkg/apiv1/oidc_test.go
- components/public-api-server/pkg/server/server.go
- components/public-api/go/config/config.go
Shifts handling of Create OIDC Client config directly to Public API, rather than delegating to IAM.
The implementation will be removed from AIM in subsequent PRs, once we validate this works.
* Related to https://github.com/gitpod-io/gitpod/issues/15860
Unit tests
```release-note
NONE
```
> [oidc] Move create RPC directly to public-api

- components/gitpod-db/go/oidc_client_config.go
- components/gitpod-db/go/oidc_client_config_test.go
- components/public-api-server/pkg/apiv1/oidc.go
- components/public-api-server/pkg/apiv1/oidc_test.go
Implements Get OIDC Client Config API
* Fixes https://github.com/gitpod-io/gitpod/issues/15152
* Depends on https://github.com/gitpod-io/gitpod/pull/15925
* Unit tests
```release-note
NONE
```
/hold for dependency on https://github.com/gitpod-io/gitpod/pull/15925
> [oidc] Implement Get OIDC Client Config API

- .github/workflows/build.yml
This PR adds license validation to the build and reports errors as follows:
Error on workflow-level:
Error on job-level:
Fixes #15758
```release-note
NONE
```
> Run license header checks

- components/server/src/config.ts
- components/server/src/workspace/gitpod-server-impl.ts
- dev/preview/workflow/preview/deploy-gitpod.sh
- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/server/configmap.go
- install/installer/pkg/components/server/types.go
- install/installer/pkg/config/v1/experimental/experimental.go
Add option `showSetupModal` (default: true) to suppress the self-hosted setup-modal. Defaults to `true` for backwards compatibility.
Hopefully we can fade out that thing entirely at some point. :crossed_fingers: 
Fixes #
1. Start [workspace on this branch](https://gitpod-io/#https://github.com/gitpod-io/gitpod/pull/15929) and `kubectl port-forward deployment/server 9000:9000 &`
2. Obtain OTS key: `curl -X POST localhost:9000/admin-user/login-token/create`
3. Use the result to construct your login URL: `https://gpl-test-dedicated.preview.gitpod-dev.com/api/login/ots/admin-user/:yourOtsKey` and visit it
4. You should be logged in as `admin-user` :checkered_flag: (and not blocked by the setup modal)
```release-note
NONE
```
Experimental feature to run the build with GitHub Actions (and not …
> [dedicated] Never show the self-hosted setup modal (by adding option showSetupModal: true)

- components/server/src/user/user-controller.ts
In context of the OTS-based login into the pre-seeded admin account on Dedicated previews, this changes the redirect to `/teams/new`. Reasons are:
* Currently, that's the first move an installer would take anyway, so let's automate.
* We want to avoid to be bothered with onboarding that happens for new users, e.g. config of IDE preferences.
```release-note
NONE
```
> [server] redirect to /teams/new after /login/ots/admin-user

- components/registry-facade/pkg/registry/blob.go
Prevent griping about errors.
Follow up https://github.com/gitpod-io/gitpod/pull/15729
```release-note
None
```
> registry-facade: Record errors with in the blob retry mechanism as warn log

- components/server/src/container-module.ts
- components/server/src/workspace/gitpod-server-impl.ts
- components/server/src/workspace/workspace-starter.ts
Removes the `movedImageBuilder` ConfigCat flag, always building images in workspace clusters, as the flag has been enabled at 100% for over a week now.
Also updates dependency injection to bind `ImageBuilderClientProvider ` to a `WorkspaceClusterImagebuilderClientProvider`.
Tested that this still works for single-install clusters (i.e. a `full` install), as the `WorkspaceClusterImagebuilderClientProvider` will create a client for its own cluster (tested below).
Fixes https://github.com/gitpod-io/gitpod/issues/9143
Tested as follows:
* Create `-f full` [workspace-preview](https://github.com/gitpod-io/workspace-preview) cluster, and ran a successful image build.
* Create a `-f meta` (doesn't contain ws components) with a `-f workspace` workspace-preview cluster, and ran a successful image …
> [server] Cleanup movedImageBuilder flag

- components/dashboard/src/components/RepositoryFinder.tsx
- components/dashboard/src/projects/Project.tsx
- components/dashboard/src/projects/ProjectListItem.tsx
- components/dashboard/src/workspaces/StartWorkspaceModal.tsx
This adjusts the Start Workspace UI from the Projects list page and Branches page to open in a modal vs. redirecting to a new page. This allows the modal to be closed, and avoids losing your context of what you were doing when you opened it.
While in here, I also noticed the RepositoryFinder component was continuously making calls to `getSuggestedContextURLs` due to a `useEffect()` dep that it mutate, so I corrected that was well.
I added an option to the StartWorkspaceModal to allow the `contextUrl` to be changed even if passed in, as locking it felt unnecessary here, although we do default it to the project's url.
Fixes #15696
* On the preview environment, create a new team and project
* On the Projects list page, click the overflow menu, and select `New Workspace...`
* It should open …
> Open start workspace in modal from projects list

- operations/observability/mixins/meta/rules/public-api.yaml
- operations/observability/mixins/meta/rules/usage.yaml
Fixes https://github.com/gitpod-io/gitpod/issues/15202
```release-note
NONE
```
> [alerts] Reduce trigger duration for Stripe Webhook Failure alert

- components/server/src/config.ts
- components/server/src/container-module.ts
- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/server/configmap.go
- install/installer/pkg/components/server/types.go
- install/installer/pkg/components/slowserver/configmap.go
Removes `imageBuilderAddr` from server's config, as with https://github.com/gitpod-io/gitpod/pull/15826 server always uses a workspace cluster image builder client, no in-cluster client, the field is no longer used.
Fixes https://github.com/gitpod-io/gitpod/issues/9143
Tested running a successful image build in the following setups:
* A `-f full` workspace-preview cluster
* A `-f full` with a `-f workspace` workspace-preview cluster
* A `-f meta` with a `-f workspace` workspace-preview cluster
```release-note
NONE
```
> [server] Remove image builder address config

- components/dashboard/src/teams/NewTeam.tsx
Ensure that the team name is preserved between renders.
Using a simple variable to store the team name meant that the team name was forgotten every time the component re-rendered. By using local component state the value of the team name is preserved between renders (a render occurs when the error message state is set).
Fixes #
* Try to create a new team using the same name as an existing team.
* Click the **Create Team** button repeatedly.
* Notice that the error message is the same after each click: `"A team with this name already exists"`.
Without these changes on each click after the first, the error would change to `"Name is a required argument when creating a team."` due to the state being wiped when an error message is set.
```release-note
NONE
```
Experimental feature to run the …
> [dashboard] Fix team creation view losing team name state

- components/ide/jetbrains/gateway-plugin/gradle-latest.properties
Update JetBrains Plugin to support Gateway v2023.1.
No code changes were needed for it to work on the new version.
1. Ensure you have the Gateway 2023.1 (EAP) installed from [JetBrains Toolbox App](https://www.jetbrains.com/toolbox-app/) and have it up-to-date.
3. Create a new workspace from the Gateway (it's ok to use the pre-selected IDE and Repository) and confirm if JetBrains Client can connect to it.
```release-note
Added support to JetBrains Gateway v2023.1
```
> [JetBrains] Update plugin to support Gateway v2023.1

- dev/preview/workflow/preview/deploy-gitpod.sh
Fix and follow-up for:
https://github.com/gitpod-io/gitpod/pull/15929
Fixes #
```release-note
NONE
```
> [dev] Dedicated: Don't show SetupModal

- components/dashboard/src/admin/BlockedRepositories.tsx
- components/dashboard/src/admin/ProjectsSearch.tsx
- components/dashboard/src/admin/TeamsSearch.tsx
- components/dashboard/src/admin/UserSearch.tsx
- components/dashboard/src/admin/WorkspacesSearch.tsx
Signed-off-by: Deepayan Mukherjee <deepayanmukherjee1312@gmail.com>
Removed the rotating magnifier icon for loading and added a spinner animation
Fixes #15616 
```release-note
NONE
```
> Added search loader

- components/gitpod-db/src/user-db.ts
Use a valid UUID for the one-time admin user added by https://github.com/gitpod-io/gitpod/pull/15805.
A valid UUID is required for the admin user to able to interact with the public/server API to set up SSO.
See some [internal discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1674478515382859?thread_ts=1674466010.292799&cid=C02EN94AEPL).
Fixes #
1. Start [workspace on this branch](https://gitpod-io/#https://github.com/gitpod-io/gitpod/pull/15805) and `kubectl port-forward deployment/server 9000:9000`
2. Obtain OTS key: `curl -X POST localhost:9000/admin-user/login-token/create`
3. Use the result to construct your login URL: `https://<preview-domain>/api/login/ots/admin-user/:yourOtsKey` and visit it.
It should now be possible to configure an OICD client (`Settings | OIDC`). …
> [db] Use a valid UUID for the admin user

- .github/actions/delete-preview/Dockerfile
- .github/actions/delete-preview/entrypoint.sh
- .github/actions/delete-preview/metadata.yml
- .github/workflows/preview-env-delete.yml
This PR introduces
1. A new custom action to delete preview environments
2. A new workflow (triggered manually) which uses the action to delete a preview environment
Part of https://github.com/gitpod-io/gitpod/issues/15866
You can only test newly introduced workflow_dispatch workflows once they're on main. So this is a best effort implementation and I I'll verify if it works on main after the PR is merged.
```release-note
NONE
```
N/A
> Introduce action and workflow to delete preview

- components/proxy/conf/Caddyfile
Routes `/iam/*` requests to `public-api-server`. Handlers are mounted on the `public-api-server` in https://github.com/gitpod-io/gitpod/pull/15939
* Depends on https://github.com/gitpod-io/gitpod/pull/15939
* Part of https://github.com/gitpod-io/gitpod/issues/15860
1. Preview
2. Access preview on `https://mp-proxy-r093a737b1c.preview.gitpod-dev.com/iam/oidc/start`
3. Observe 404 - no valid config - expected as we didn't specify OIDC details, but it means the endpoint is being handled by public-api
```release-note
NONE
``` …
> [proxy] Route /iam/* to public-api-server

- components/server/src/config.ts
- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/kind-workspace/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/server/configmap.go
- install/installer/pkg/components/server/types.go
- install/installer/pkg/components/ws-proxy/configmap.go
- install/installer/pkg/components/ws-proxy/deployment.go
Remove usages of the `withoutWorkspaceComponents` flag that are no longer needed:
* Inside `server` config: was used to determine whether image builds should go to workspace clusters, which is now always enabled.
* Inside `ws-proxy`: this was a left-over from testing the removal of ws components from application clusters, where initially we were still running `ws-proxy` in the application clusters. This is not the case anymore and the flag usage therefore can be removed here.
Tested starting a workspace in the following setups:
A `-f full` workspace-preview cluster
A `-f full` with a `-f workspace` workspace-preview cluster
A `-f meta` with a `-f workspace` workspace-preview cluster
```release-note
NONE
``` …
> Cleanup withoutWorkspaceComponents flag usage

- .github/CODEOWNERS
Create codeowner entries for ws-manager-mk2
n.a.
n.a.
```release-note
None
```
> [ws-manager-mk2] Create code owners entries

- install/installer/cmd/testdata/render/message-bus-password/output.golden
The golden files somehow ended up out-of-sync. 
This PR is the result of re-running `make generateRenderTests`.
Fixes #
```release-note
NONE
```
> Run `make generateRenderTests`

- components/supervisor/pkg/serverapi/publicapi.go
Do not log error when it has `Canceled` code
```release-note
NONE
```
> [supervisor] Do not log error when it has Canceled code

- components/workspace-rollout-job/cmd/root.go
This PR updates the Version field in root to
be set correctly and also use the same with
the cobra CLI.
`-v` flag should give the relevant build commit output
```bash
gitpod /workspace/gitpod/components/workspace-rollout-job (tar/ws-rollout-version) $ docker run eu.gcr.io/gitpod-core-dev/build/workspace-rollout-job:commit-3db17158fe4b68b642d634932b26c4d1c5b5eb84 -v
version commit-3db17158fe4b68b642d634932b26c4d1c5b5eb84
```
```release-note
[ws-rollout] Fix Build Versioning
``` …
> [ws-rollout] Fix Build Versioning

- .github/pull_request_template.md
- .github/workflows/build.yml
- .werft/jobs/build/job-config.ts
- .werft/jobs/build/prepare.ts
- dev/preview/previewctl/pkg/preview/util.go
Adds the `with-gce-vm` option for both GHA and werft
Fixes https://github.com/gitpod-io/ops/issues/7803
```release-note
NONE
```
> preview env `with-gce-vm` option

- .github/workflows/build.yml
Define concurrency groups for the build jobs in order to limit concurrent jobs from running at the same time for the same branch/pr. Multiple triggers of the job will cancel the previous runs, essentially leaving only the last one active.
Only the `infrastructure` job will not cancel the previous ones, as we don't want to interrupt the terraform mid-run. It will wait it out until the last one is done and will get triggered after.
Fixes #
```release-note
NONE
```
> Define concurrency groups for the build

- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/message-bus-password/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/image-builder-mk3/networkpolicy.go
- install/installer/pkg/components/ws-manager-mk2/constants.go
Rename mk2's TLS secrets to be unique from mk1's. Otherwise one will overwrite the other
Also add ws-manager-mk2 to image builder network policy.
```release-note
NONE
```
> [ws-manager-mk2] Rename TLS secrets

- dev/preview/previewctl/cmd/install_context.go
- dev/preview/previewctl/pkg/k8s/context.go
- dev/preview/previewctl/pkg/k8s/vm.go
- dev/preview/previewctl/pkg/preview/context.go
- dev/preview/previewctl/pkg/preview/preview.go
- dev/preview/previewctl/pkg/preview/status.go
- dev/preview/workflow/preview/determine-env.sh
Handle context installation when switching infra.
Fixes #
```release-note
NONE
```
> Handle context installation when switching underlying infra

- dev/preview/workflow/preview/deploy-gitpod.sh
No longer needed
Fixes #
```release-note
NONE
```
> [oidc] Remove static preview config

- .werft/jobs/build/build-and-publish.ts
Currently the main build is failing because the Replicated API key has been removed. This PR comments this step out, hence making the build pass. Since replicated is not a preferred distribution mode, we need not necessarily test it.
Fixes #
```release-note
NONE
```
> Temporarily deactivate kots publish step

- .werft/cleanup-installer-tests.yaml
- .werft/jobs/build/build-and-publish.ts
This removes a regression introduced in #16008 . This PR removed the unused function `publishToKots`
Fixes #
```release-note
NONE
```
> Remove the unused publishToKots function

- components/dashboard/src/index.tsx
This PR fixes this for dev builds👇 
Removes a redundant rendering of `ReactQueryDevtools`. In #15908 rendering `ReactQueryDevtools` was shifted into a `GitpodQueryClientProvider` component, but I forgot to remove the entry in this file.
The devtools only show up in a dev build - but to test that, w/ a dev build loaded, ensure only 1 of the react-query devtools renders. You can resize the tool window and see if there's one rendered underneath it to verify.
```release-note
NONE
```
> removing duplicated ReactQueryDevtools component

- components/server/src/session-handler.ts
Narrow cookie scope to gitpod domain only
1. Check public api still works in dashboard
2. Check you cannot create a ws connection from workspace origin
```release-note
NONE
```
> Narrow cookie scope to gitpod domain only

- components/ws-daemon/pkg/daemon/daemon.go
- components/ws-proxy/cmd/run.go
- components/ws-proxy/pkg/config/config.go
- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-workspace/output.golden
- install/installer/cmd/testdata/render/message-bus-password/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/ws-proxy/configmap.go
- install/installer/pkg/components/ws-proxy/role.go
Ensure the workspace info provider of ws-proxy is deactivated if the useWsmanagerMk2 is not enabled. For context see https://gitpod.slack.com/archives/C02F19UUW6S/p1674571144523329. Also ensured that the controller manager for ws-daemon is disabled as well.-
n.a.
I was not able to get a preview environment due to the 429 registry issue currently affecting preview environments. I tested with workspace-preview instead. 
```release-note
None
```
> [ws-manager-mk2] Ensure workspace CRD info provider is deactivated

- dev/preview/previewctl/cmd/create.go
- dev/preview/previewctl/cmd/root.go
Aliases `leeway run dev:preview` into `previewctl create`. 
I can never remember the leeway command, and `previewctl` has help text support so I can easily discover what to run.
Fixes #
1. `go run main.go create` on a branch, observe 
```release-note
NONE
```
> [previewctl] Add create command as alias to leeway run preview:dev

- .werft/jobs/build/prepare.ts
- .werft/vm/vm.ts
Fixes #
```release-note
NONE
```
> Replace for gce vm

- components/server/src/config.ts
- components/server/src/session-handler.ts
Fixes #
```release-note
NONE
```
> [server] Rename cookie to v2 for proper rollout

- components/server/src/config.ts
- components/server/src/session-handler.ts
Fixes #
```release-note
NONE
```
> [cleanup] After cookie migration

- operations/observability/mixins/meta/dashboards/components/server.json
Uses automated Grafana migration to migrate panels to a more-performant visualization
Updates labels on high-cardinality series to be on the right hand side, to ensure that the height of the graphs remains the same, and makes visual comparison easier.
Further cleanup will follow in subsequent PRs, including grouping it into more sections.
Fixes #
Example from staging
```release-note
NONE
```
> [dashboard] Migrate server dashboard to timeseries visualization

- operations/observability/mixins/meta/rules/server.yaml
Because all of these status codes are user-caused, rather than system caused.
Fixes #
```release-note
NONE
```
> [alerts] Exclude all of 2xx, 3xx, 4xx from JSON RPC API Error Rates

- install/installer/cmd/testdata/render/gcp-setup/config.yaml
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/pkg/components/database/cloudsql/constants.go
- install/installer/pkg/components/database/cloudsql/global.go
- install/installer/pkg/components/database/cloudsql/objects.go
- install/installer/pkg/config/v1/config.go
We need support for a second cloud-sql-proxy which can point to a global DB instance. This is temporary while we progress the removal of db-sync, and also progress rollout of fine grained permissions.
* Add `cloudSQLGlobal` config to `database` config
* If `cloudSQL` is configured, and `cloudSQLGlobal` is also configured, we render the following:
* cloudsql-global deployment
* cloudsql-global service
* cloudsql-global rolebinding
* cloudsql-global service-account	
Fixes #
See unit tests (and generated files)
```release-note
NONE
``` …
> [installer] Global cloud-sql-proxy

- install/installer/pkg/components/spicedb/deployment.go
We use a `cloudsql-global` instead of the side-car.
Fixes #
```release-note
NONE
```
> [spicedb] Remove cloud-sql-proxy sidecar

- dev/preview/workflow/preview/deploy-gitpod.sh
- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/message-bus-password/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/database/incluster/init/03-create-authorization-db.sql
- install/installer/pkg/components/database/init/files/01-create-authorization-db.sql
- install/installer/pkg/components/spicedb/constants.go
- install/installer/pkg/components/spicedb/deployment.go
- install/installer/pkg/components/spicedb/migrations.go
- install/installer/pkg/components/spicedb/objects.go
- install/installer/pkg/config/v1/experimental/experimental.go
Configures and deploys spice db in preview envs
Fixes https://github.com/gitpod-io/gitpod/issues/15951
1. Preview
2. 
```
kubectl get po 
...
spicedb-5569847b47-bccnh             1/1     Running     1 (14m ago)   15m
...
```
```release-note
NONE
```
> [db] Enable spicedb in preview envs

- .github/actions/delete-preview/Dockerfile
- .github/actions/delete-preview/entrypoint.sh
- .github/actions/delete-preview/metadata.yml
- .github/actions/deploy-gitpod/entrypoint.sh
- .github/actions/deploy-gitpod/metadata.yml
- .github/actions/deploy-monitoring-satellite/Dockerfile
- .github/actions/deploy-monitoring-satellite/entrypoint.sh
- .github/actions/deploy-monitoring-satellite/metadata.yml
- .github/actions/preview-create/Dockerfile
- .github/actions/preview-create/entrypoint.sh
- .github/actions/preview-create/metadata.yml
- .github/pull_request_template.md
- .github/workflows/build.yml
- components/BUILD.yaml
- dev/BUILD.yaml
- dev/preview/previewctl/BUILD.yaml
- dev/preview/previewctl/leeway.Dockerfile
With this PR our custom GitHub Actions for managing preview environments will now download previewctl from a Docker image instead of using Leeway to build it. This is a step towards eventually being able to use smaller base images for these actions as they then won't need to have all the build tools available.
I also used this as an opportunity to change the structure of the jobs a little bit.
Fixes https://github.com/gitpod-io/gitpod/issues/15970
See the GH actions run
```release-note
NONE
```
> Download previewctl from Docker image

- .github/workflows/build.yml
This changes the GitHub Actions build so that it is triggered on pushes to main too. It will only build previewctl however, and not Gitpod. This is needed to make the previewctl Docker image available. I could have added it to the Werft build but I'd rather move ahead with GH actions and this is a good way to start sending a bit of load to the self-hosted runners.
No specific issue
```release-note
NONE
```
N/A
> Build previewctl using GitHub actions

- .github/workflows/build.yml
Outputs are strings so we have to check explicitly. Previously the outputs would be "false" which is a non-empty string so it evaluates to true. See this job from main [here](https://github.com/gitpod-io/gitpod/actions/runs/4015920217/jobs/6898269981). The screenshots show the output values and that it decided to run the guarded jobs anyway.
N/A
I enabled GH on this PR but didn't enable preview, so it should be skipped.
```release-note
NONE
```
> Outputs are strings so we have to check explicitly

- .github/actions/delete-preview/entrypoint.sh
- dev/preview/previewctl/BUILD.yaml
Fixes minor regression in the delete-preview action. See error [here](https://github.com/gitpod-io/gitpod/actions/runs/4015673449/jobs/6897686910). Depends on https://github.com/gitpod-io/gitpod/pull/16051 so that we start publishing the previewctl image from main.
No issue
Triggered a job manually [here](https://github.com/gitpod-io/gitpod/actions/runs/4016198016/jobs/6898894723) after having run `leeway build dev/preview/previewctl:docker -Dversion=main.1063` manually.
```release-note
NONE
```
N/A …
> Fix delete-preview action

- components/dashboard/src/admin/UserDetail.tsx
When dealing with abuse checking what was the phone number used for account verification can be helpful. As such, this PR adds it in line with account email.
N/A
- From a gitpod workspace, open preview (`leeway run dev:preview`)
- Signup in the url provided
- Unblock the user if needed (`leeway run components:unblock-user`) 
- Make it admin (`leeway run components:make-user-admin`)
- Check the admin user page
- Update DB [[1](https://www.notion.so/gitpod/How-we-develop-e8ce7e562478458a9223eb9b797415b2#c82bfeb6cbae46c79bfa2aee72769bed)] (`SET SQL_SAFE_UPDATES = 0; UPDATE d_b_user SET verificationPhoneNumber = '930000000'`)
- See change
```release-note
NONE
``` …
> [admin] Add phone number to user page

- components/ws-manager-api/go/config/config.go
- components/ws-manager-mk2/main.go
- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-workspace/output.golden
- install/installer/cmd/testdata/render/message-bus-password/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/ws-manager-mk2/configmap.go
- install/installer/pkg/components/ws-manager-mk2/constants.go
- install/installer/pkg/components/ws-manager-mk2/deployment.go
Configure readiness and liveness probes for ws-manager-mk2, using the controller manager's health probe endpoints.
Open preview env, check health probes are working on the ws-manager-mk2 deployment
```release-note
NONE
```
> [ws-manager-mk2] Configure health probes

- install/installer/pkg/components/spicedb/networkpolicy.go
- install/installer/pkg/components/spicedb/objects.go
Restricts access to only public-api and server
Fixes #
```release-note
NONE
```
> [spicedb] Add network policy

- install/installer/pkg/components/spicedb/deployment.go
We don't want to report telemetry to telemetry.spicedb.com
Fixes #
```release-note
NONE
```
> [spicedb] Disable remote telemetry

- operations/observability/mixins/meta/dashboards/components/server.json
Does the following:
* Mostly removes grouping by pod, we can always get by pod details by going into the dashboard and adjusting the query, but it doesn't help us see the big picture
* Removes CPU/Memory section, there are dedicated dashboards for k8s workloads
* Breaks latency out into two graphs, removes 80th precentile one
* Splits errors into User & System
* Removes background from lines, they overlay on high cardinality series and make it impossible to see anything below
Fixes #
```release-note
NONE
``` …
> [grafana] Cleanup server component dashboard

- dev/preview/workflow/preview/deploy-gitpod.sh
- install/installer/pkg/components/slowserver/deployment.go
- install/installer/pkg/components/slowserver/objects.go
- install/installer/pkg/components/slowserver/render_test.go
- install/installer/pkg/components/toxiproxy/objects.go
- install/installer/pkg/components/toxiproxy/objects_test.go
- install/installer/pkg/config/v1/experimental/experimental.go
Allow us to point slow-server to different DBs.
Fixes #
```release-note
NONE
```
> [slow-server] Change flag from bool to string (DB_HOST)

- install/installer/pkg/config/v1/experimental/experimental.go
Unused, we use the `database.cloudSqlGlobal` config instead, related ops removal - https://github.com/gitpod-io/ops/pull/8023
Fixes #
```release-note
NONE
```
> [spicedb] Remove dedicated cloud-sql-proxy config

- components/gitpod-db/src/container-module.ts
- components/gitpod-db/src/typeorm/synchronizer.spec.db.ts
- components/gitpod-db/src/typeorm/synchronizer.ts
- components/gitpod-db/src/typeorm/typeorm.ts
- components/gitpod-db/src/user-to-team-migration-service.spec.db.ts
- components/gitpod-db/src/user-to-team-migration-service.ts
- components/server/src/user/user-service.ts
1) We only want to migrate users to team-only attribution if they are not on a chargebee plan, because chargebee plans are always personal and cannot be migrated to a team.
2) We only want to migrate users once, so the operation needs to be synchronized
```release-note
NONE
```
> [server] synchronize migration and only migrate users without chargebee plan

- .github/workflows/build.yml
Only create infra if GHA is enabled on the PR.
No issue, but saw in this PR https://github.com/gitpod-io/gitpod/pull/16063 that it tried to create the infra even though GHA wasn't enabled (only preview was).
In this PR I have enabled preview but not GHA, so it should not create the infra.
```release-note
```
> Only create infra if gha is enabled

- .github/CODEOWNERS
No need to require review from SID when changes are made to deploy-gitpod.sh - that scrips is shared between teams.
No issue
N/A
```release-note
NONE
```
N/A
> deploy-gitpod is shared by everyone

- install/installer/pkg/components/spicedb/constants.go
- install/installer/pkg/components/spicedb/deployment.go
- install/installer/pkg/components/spicedb/objects.go
- install/installer/pkg/components/spicedb/secret.go
- install/installer/pkg/config/v1/experimental/experimental.go
Configure, or create, a secret to be used as a pre-shared key for accessing spicedb
Fixes #
```release-note
NONE
```
> [spicedb] Configure preshared key

- install/installer/BUILD.yaml
- install/installer/pkg/components/spicedb/constants.go
- install/installer/pkg/components/spicedb/data/bootstrap.yaml
- install/installer/pkg/components/spicedb/deployment.go
- install/installer/pkg/components/spicedb/objects.go
- install/installer/pkg/components/spicedb/schema.go
Includes spicedb schema in installer files to bootstrap the schema on startup
Fixes #
1. Preview
2. See logs for `spicedb`
3. `{"level":"info","filePath":"/bootstrap/bootstrap.yaml","schemaDefinitionCount":6,"time":"2023-01-27T10:17:58Z","message":"adding schema definitions"}`
```release-note
NONE
```
> [spicedb] Bootstrap schema

- install/installer/cmd/testdata/render/kind-workspace/output.golden
- install/installer/pkg/components/ws-proxy/objects.go
> Remove scenario assuming workspace clusters run in GCP

- components/ws-daemon/pkg/content/service.go
- components/ws-daemon/pkg/controller/controller.go
- components/ws-daemon/pkg/controller/workspace_operations.go
- components/ws-daemon/pkg/daemon/daemon.go
- components/ws-daemon/pkg/internal/session/workspace.go
- components/ws-manager-api/go/crd/v1/workspace_types.go
- components/ws-manager-mk2/controllers/status.go
- components/ws-manager-mk2/controllers/workspace_controller.go
- components/ws-manager-mk2/debug.sh
- components/ws-manager-mk2/service/manager.go
Workspaces that have been started by ws-manager-mk2 can now be stopped and successfully backed up.
n.a.
- Open workspace in [preview environment](https://fo-mk2-dispose-ws.preview.gitpod-dev.com/workspaces)
```release-note
None
```
> [ws-manager-mk2] Support backup of workspaces

- .github/actions/delete-preview/entrypoint.sh
- .github/workflows/preview-env-delete.yml
Trigger the "Delete preview environment" workflow when branches are deleted.
No issue, see internal discussion [here](https://gitpod.slack.com/archives/C032A46PWR0/p1674827280011619?thread_ts=1674826607.497579&cid=C032A46PWR0).
Triggered the job from this branch to verify that the "workflow_dispatch" hasn't broken - it seemed to work just fine ([link](https://github.com/gitpod-io/gitpod/actions/runs/4044681307/jobs/6955145260))
Once on main I can test if it gets triggered properly when branches are deleted and verify that the `github.event.ref` gets sanitized correctly. 
```release-note
NONE
```
N/A
If enabled …
> Trigger preview deletion on branch deletion

- components/ws-manager/pkg/manager/manager.go
- components/ws-manager/pkg/manager/manager_test.go
During scale-up events,` ws-manager ` tries to connect to pods that are not ready yet.
```release-note
NONE
```
> Do not try to connect to not ready ws-daemon pods

- components/workspace-rollout-job/cmd/root.go
- components/workspace-rollout-job/pkg/analysis/analyzer.go
When given a non-usable `--prometheus-url`, We start the rollout without verifying if the prometheus is reachable or not. This is a problem as we will be unable to get the metrics from prometheus and hence the rollout will be reverted later causing unnecessary time waste.
This can be prevented by performing a simple check to see if the prometheus is reachable or not. `up` query is used instead of key metrics as we can't be sure of their existence.
Fixes #
Testing by passing a unreachable prometheus URL
```bash
gitpod /workspace/gitpod/components/workspace-rollout-job (tar/ws-rollout-prom-init) $ go run . --new-cluster g2c4ec3d5cb --old-cluster gfd9876cfe2 --prometheus-url http://localhos:9090
INFO[0000] Starting workspace-rollout-job …
```
> [ws-rollout] Add prometheus init check

- .github/workflows/code-nightly.yml
Point code nightly worklow to the release/1.75 branch
```release-note
NONE
```
> Point code nightly worklow to the release/1.75 branch

- components/dashboard/src/Menu.tsx
- components/dashboard/src/admin/TeamsSearch.tsx
- components/dashboard/src/admin/admin-menu.ts
- components/dashboard/src/app/AppRoutes.tsx
- components/dashboard/src/components/BillingAccountSelector.tsx
- components/dashboard/src/components/UsageBasedBillingConfig.tsx
- components/dashboard/src/components/UsageLimitReachedModal.tsx
- components/dashboard/src/components/UsageView.tsx
- components/dashboard/src/contexts/FeatureFlagContext.tsx
- components/dashboard/src/hooks/use-user-and-teams-loader.ts
- components/dashboard/src/projects/NewProject.tsx
- components/dashboard/src/projects/ProjectSettings.tsx
- components/dashboard/src/projects/RemoveProjectModal.tsx
- components/dashboard/src/settings/Plans.tsx
- components/dashboard/src/settings/Teams.tsx
- components/dashboard/src/settings/settings-menu.ts
- components/dashboard/src/settings/settings.routes.ts
- components/dashboard/src/start/CreateWorkspace.tsx
- components/dashboard/src/teams/JoinTeam.tsx
- components/dashboard/src/teams/Members.tsx
- components/dashboard/src/teams/NewTeam.tsx
- components/dashboard/src/teams/TeamBilling.tsx
- components/dashboard/src/teams/TeamSettings.tsx
- components/dashboard/src/teams/TeamUsageBasedBilling.tsx
- components/gitpod-db/src/typeorm/team-db-impl.ts
- components/server/src/user/user-controller.ts
- components/server/src/workspace/gitpod-server-impl.ts
Renames all user visible occurences of the term team to organization
Fixes #
check the UI and verify that we are talking about organizations everywhere.
```release-note
teams are now called organizations
```
TODO
> [dashboard] user visible rename team->organization

- .github/workflows/build.yml
The previewctl hash that we store as output doesn't match the hash that was built because I had forgotten to pass in the `-Dversion` argument 🤦 
No issue
See screenshot. Will also run this PR with preview and GHA enabled to check.
```release-note
NONE
```
N/A
> Pass in -Dversion so hash matches

- .github/workflows/permissions.yml
- install/installer/BUILD.yaml
- install/installer/pkg/components/spicedb/data/schema.yaml
- install/installer/pkg/components/spicedb/schema.go
Adds a github action which validates SpiceDB schema against the defined schema and assertions
Fixes #
Example failure - https://github.com/gitpod-io/gitpod/actions/runs/4044919425/jobs/6955679551
See success in CI run results
```release-note
NONE
```
> [spicedb] Add github action to validate schema

- .github/actions/deploy-gitpod/entrypoint.sh
- .github/actions/deploy-gitpod/metadata.yml
- .github/actions/preview-create/entrypoint.sh
- .github/actions/preview-create/metadata.yml
- .github/workflows/build.yml
- .github/workflows/preview-env-check-regressions.yml
- .github/workflows/preview-env-delete.yml
This PR extends the preview regression check workflow so that it actually creates and then deletes the preview environment. For now it still has to be triggered manually.
I'll follow this up with a PR which triggers the workflow after each successful GHA build on main (which means we have to start running the GHA job on main too)
Part of https://github.com/gitpod-io/gitpod/issues/15869
- ✅ Workflow which ran as part of this PR [here](https://github.com/gitpod-io/gitpod/actions/runs/4052762337)
- ✅ Workflow that I triggered manually [here](https://github.com/gitpod-io/gitpod/actions/runs/4053074960/jobs/6973258362)
```release-note
NONE
```
N/A
If enabled …
> Implement basic preview environment regression check

- install/installer/pkg/components/server/deployment.go
- install/installer/pkg/components/slowserver/deployment.go
- install/installer/pkg/components/spicedb/objects.go
Pass config for interaction with spicedb into server
Fixes #
```release-note
NONE
```
> [server] Add config for interacting with spicedb

- .github/workflows/permissions.yml
- .github/workflows/public-api.yml
Fixes #
```release-note
NONE
```
> [public-api] Only run breaking detector when public api defs change

- .github/actions/preview-create/entrypoint.sh
- .github/actions/preview-create/metadata.yml
- .github/workflows/build.yml
- .werft/jobs/build/prepare.ts
- dev/preview/infrastructure/modules/gce/proxy.tf
- dev/preview/infrastructure/modules/gce/variables.tf
- dev/preview/infrastructure/modules/gce/vm.tf
- dev/preview/infrastructure/modules/harvester/variables.tf
- dev/preview/infrastructure/modules/harvester/vm.tf
- dev/preview/infrastructure/preview.tf
- dev/preview/infrastructure/variables.tf
- dev/preview/previewctl/BUILD.yaml
* adds support for `with-large-vm`
* changes the logic so it's a flag in TF, not configured in werft/gha
* also change the gce default machine type (`n2` -> `n2d`), as that's what we use in prod
Fixes https://github.com/gitpod-io/gitpod/issues/15768
```release-note
NONE
```
> GHA support `with-large-vm`

- components/proxy/Dockerfile
- components/proxy/conf/Caddyfile
- components/proxy/conf/workspace-handler.full
- components/proxy/conf/workspace-handler.meta
- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/azure-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/message-bus-password/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/proxy/deployment.go
Removes an existing dependency `proxy` -> `ws-proxy`
Contributes to: https://github.com/gitpod-io/gitpod/issues/16095
- start a workspace in preview, and notice how that works :tm:  :heavy_check_mark: 
- `kubectl edit deployment proxy`
- set env var `WORKSPACE_HANDLER_FILE` to meta, and wait for `proxy` to restart
- open a tab on `https://gitpodsampl-templategol-s86kbhqyljp.ws-dev.gpl-decoupff9f3d899e.preview.gitpod-dev.com/` (made up workspaceId), and notice the redirect o `/start?not_found=true...` :heavy_check_mark: 
- open a tab on `https://9001-gitpodsampl-templategol-s86kbhqyabc.ws-dev.gpl-decoupff9f3d899e.preview.gitpod-dev.com/test` and notice the `404` :heavy_check_mark: 
```release-note
NONE
``` …
> [proxy] Remove dependency on ws-proxy for "Meta" installation

- .github/workflows/build.yml
- dev/preview/previewctl/BUILD.yaml
This builds Gitpod on main using GitHub Actions. We're still building with Werft too of course. I changed the versioning scheme we use in GHA to contain `gha` so that we have separate "streams" for the werft "main.xxx" and GHA "main-gha.xxx" versions.
Enabling this has two functions
1. By running the main build on GHA I can trigger the preview environment regression check workflow after each successful main build. This is what I have been working towards in https://github.com/gitpod-io/gitpod/issues/15869
1. We start to load test our self-hosted runners a little bit 
Part of https://github.com/gitpod-io/gitpod/issues/15869
I'm not enabling GHA on this PR to ensure that the flag is still respected and that we don't start building Gitpod in GHA on all PRs.
Once merged on main I'll see if …
> Build Gitpod with GHA on main (too)

- components/dashboard/src/Menu.tsx
The link on the personal projects needs to point to /projects
Fixes #
```release-note
NONE
```
> [dashboard] fix link for personal projects

- components/gitpod-db/src/typeorm/migration/1643986994402-OAuthRevision.ts
... and let it not unblock subsequent migrations on d_b_auth_provider_entry table.
This is required to unblock PR https://github.com/gitpod-io/gitpod/pull/16112
```release-note
NONE
```
> [db-migrations] patch OAuthRevision migration

- components/dashboard/src/teams/JoinTeam.tsx
Fixes the broken org joining.
Fixes #16135
Join here -> https://sefftinge-f0ccb32c12.preview.gitpod-dev.com/orgs/join?inviteId=ad811780-d6cd-4a06-86ed-b72db1f5f89e
```release-note
NONE
```
> [dashboard] fix org joining

- components/dashboard/src/components/UsageView.tsx
Minor style changes for the credits element in the usage page.
|-|-|
| ![credits-before](https://user-images.githubusercontent.com/120486/215616225-12c16baf-3e56-4f2e-ad16-44607bd0b1b4.png) | ![credits-after](https://user-images.githubusercontent.com/120486/215616175-cbf9e3b6-a3e8-4c10-be55-d67547105931.png) |
Related Issue(s)
Related to https://github.com/gitpod-io/gitpod/issues/15411.
Check the changes in the credits element in the usage page.
```release-note
NONE
``` …
> Update usage credits element

- install/installer/pkg/components/spicedb/objects.go
- install/installer/pkg/components/spicedb/role.go
- install/installer/pkg/components/spicedb/rolebinding.go
Needed to be able to use [disptaching](https://authzed.com/blog/spicedb-architecture/). For that, we need to allow spicedb to discover endpoints, to be able to reach the other spicedb replicas.
Based on [example](https://github.com/authzed/examples/blob/main/kubernetes/example.yaml)
Fixes #
```release-note
NONE
```
> [spicedb] Add role & rolebinding to watch endpoints

- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/ide-config/config.yaml
- install/installer/cmd/testdata/render/ide-config/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/pkg/components/ide-metrics/deployment.go
- install/installer/pkg/components/ide-proxy/service.go
- install/installer/pkg/components/ide-proxy/service_test.go
- install/installer/pkg/components/ide-service/ide_config_configmap.go
- install/installer/pkg/components/openvsx-proxy/service.go
- install/installer/pkg/components/openvsx-proxy/service_test.go
- install/installer/pkg/config/v1/config.go
- install/installer/pkg/config/v1/deprecations.go
- install/installer/pkg/config/v1/experimental/experimental.go
This deprecates the IDE experimental configuration and moves this into the main config section.
- A new `Proxy` type is created to make the proxy configuration generic (there's a few `experimental` features that require proxy config)
- OpenVSX Proxy is moved under `openVSX` object
- IDE Proxy is moved to `components.ide.proxy`
- IDE ResolveLatest is moved to `components.ide.resolveLatest`
- IDE Metrics is moved to `components.ide.metrics`
**Important**. As part of the [config rules](https://github.com/gitpod-io/gitpod/tree/main/install/installer/pkg/config), the `IDE` in the `components` object refers to the IDEs themselves, not to @gitpod-io/engineering-ide (which is what it referred to in the `experimental` section. In future, this might be extended to have VSCode/Jetbrains specific …
> [installer]: deprecate experimental IDE config

- components/dashboard/src/components/DropDown2.tsx
- Initially work `toggleDropDown()` was called on `" "` space, removed that.
- When the input is empty, space is used to toggle the dropdown else space is getting concatenated to the input.
[Screencast from 19-01-23 06:25:46 PM IST.webm](https://user-images.githubusercontent.com/76901313/213448491-6c9c13ff-7ad9-4c2f-8be8-067f2a315e6a.webm)
Fixes #15690 
```release-note
[fix] : workspace options model closes on entering space(" ")
```
> [fix] : workspace options model closes on space

- .github/workflows/build.yml
We don't want/need to cancel previewctl builds on main. 
No issue, noticed a build got canceled on main.
Can't really test until this is on main but the condition is the same as we use for build-gitpod and that worked (see example [here](https://github.com/gitpod-io/gitpod/actions/runs/4054764294) where previewctl got canceled by build gitpod didn't)
```release-note
NONE
```
N/A
> Don't cancel previewctl builds on main

- components/proxy/conf/workspace-handler.meta
Fix-up for: https://github.com/gitpod-io/gitpod/pull/16104
- start a workspace in preview, and notice how that works :tm:  :heavy_check_mark: 
- `kubectl edit deployment proxy`
- set env var `WORKSPACE_HANDLER_FILE` to meta, and wait for `proxy` to restart
- open a tab on `https://gitpodsampl-templategol-s86kbhqyljp.ws-dev.gpl-decoupff9f3d899e.preview.gitpod-dev.com/` (made up workspaceId), and notice the redirect o `/start?not_found=true...` :heavy_check_mark: 
- open a tab on `https://9001-gitpodsampl-templategol-s86kbhqyabc.ws-dev.gpl-decoupff9f3d899e.preview.gitpod-dev.com/test` and notice the `404` :heavy_check_mark: 
```release-note
NONE
```
If …
> [proxy] Fix meta workspace-handler

- .github/workflows/preview-env-gc.yml
We're migrating our jobs to GitHub Actions. This is a step towards https://github.com/gitpod-io/gitpod/issues/15870 - for now I'm just introducing a new workflow that we can manually trigger so I can iterate on the implementation in a new branch.
Part of https://github.com/gitpod-io/gitpod/issues/15870
N/A
```release-note
NONE
```
N/A
> Introduce empty preview environment garbage collection job

- .github/workflows/preview-env-check-regressions.yml
Following up on https://github.com/gitpod-io/gitpod/pull/16123 this PR changes `Preview environment regression check` so that it gets triggered whenever the `Build` job completes.
We still maintain the ability to manually run the job as that makes debugging and working on the workflow so much easier.
Part of https://github.com/gitpod-io/gitpod/issues/15869
- ✅ Verify that I can still manually run the job ([job here](https://github.com/gitpod-io/gitpod/actions/runs/4062936632))
- To verify that the workflow gets triggered (and works) after each successful build on main we'll have to merge this PR and then check.
```release-note
NONE
```
N/A
If enabled …
> Run regression check after each successful main build

- .github/workflows/jetbrains-update-plugin-platform-template.yml
Motivated by review of  https://github.com/gitpod-io/gitpod/pull/16024 and https://github.com/gitpod-io/gitpod/pull/15460
Fixes #
```release-note
NONE
```
> [jb] clarify how to test platform updates

- components/ws-manager-mk2/config/manager/manager.yaml
- components/ws-manager-mk2/config/samples/workspace_v1_workspace.yaml
- components/ws-manager-mk2/controllers/create.go
- components/ws-manager-mk2/controllers/workspace_controller.go
- components/ws-manager-mk2/controllers/workspace_controller_test.go
- components/ws-manager-mk2/service/manager.go
Get repository root from initializer
n.a.
- Open workspace
- Correct repository root should be set
```release-note
None
```
> Get repository root from initializer

- components/common-go/namegen/workspaceid.go
- components/common-go/namegen/workspaceid_test.go
Fix TestGenerateWorkspaceID failed with `aquamarine-tyrannosaurus-80wyuzuiizv` , see also [GH Action](https://github.com/gitpod-io/gitpod/actions/runs/4059518881/jobs/6987644369)
https://github.com/gitpod-io/gitpod/blob/2d707b214c863b52652da2f810586415654a3357/components/common-go/namegen/workspaceid.go#L24
The regexp for valid workspaceId should equal to `ws-proxy` otherwise you not able to open your workspace.
https://github.com/gitpod-io/gitpod/blob/25887cff15f4879e40b183445bedbac9e45dae5e/components/ws-proxy/pkg/proxy/workspacerouter.go#L29
And for `generateWorkspaceID` function, it also limited
1. we only allow 3 segment
2. each segment has at least 2 characters, and max is 16
https://github.com/gitpod-io/gitpod/blob/4f2ff28842d7dcefbb7fbb1e9f0474c8c3b7319a/components/gitpod-protocol/ …
> Make sure generated workspace id align to regexp

- dev/preview/workflow/preview/deploy-gitpod.sh
* Depends on https://github.com/gitpod-io/ops/pull/8142/files
* Avoids spicedb secret changing between deploys to preview
```release-note
NONE
```
/hold for dependency
> [spicedb] Use a secret in preview envs

- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/pkg/common/common.go
- install/installer/pkg/components/server/deployment.go
- install/installer/pkg/components/slowserver/deployment.go
- install/installer/pkg/components/ws-manager-bridge/deployment.go
- install/installer/pkg/components/ws-manager-bridge/objects.go
- install/installer/pkg/components/ws-manager-bridge/objects_test.go
- install/installer/pkg/config/v1/experimental/experimental.go
Context: https://github.com/gitpod-io/gitpod/pull/15276
```release-note
NONE
```
> [installer] Replace flag withoutWorkspaceComponents with 'Kind != "Full"'

- .github/pull_request_template.md
- .github/workflows/build.yml
- components/gitpod-protocol/scripts/publish.js
GHA option to publish packages to npm
Fixes https://github.com/gitpod-io/gitpod/issues/15767
https://github.com/gitpod-io/gitpod/actions/runs/4073775749/jobs/7018111520
```
leeway build components:all --cache remote -Dversion=aa-publish-to-npm-gha.1442 -DSEGMENT_IO_TOKEN=*** -DpublishToNPM=true -DnpmPublishTrigger=1675251682713 --coverage-output-path=/__w/gitpod/gitpod/test-coverage-report --report report.html
```
```release-note
NONE
```
> GHA Publish to NPM

- .github/workflows/preview-env-gc.yml
- dev/preview/previewctl/cmd/stale.go
Implements the preview GC workflow and schedules it on a cron. Had to fix a minor bug in previewctl.
Part of https://github.com/gitpod-io/gitpod/issues/15870
Part of https://github.com/gitpod-io/gitpod/issues/15871
Manually triggered the job on this branch [here](https://github.com/gitpod-io/gitpod/actions/runs/4074759722). To create stale preview environments I simply ran `leeway run dev:preview` on a branch which I hadn't pushed.
```release-note
NONE
```
N/A
> Implement 'Delete unused preview environments' workflow

- components/ide/jetbrains/gateway-plugin/gradle-stable.properties
This PR updates the Platform Version from JetBrains Gateway Plugin (Stable) to the latest version.
- You should use Gateway version corresponding to plugin qualifier, i.e. for stable plugin test with released, for latest test with EAP.
- It could be that a new Gateway is not published for the given SDK yet then wait for it to be published. You can check the build version in the About dialog.
- You can …
> [JetBrains] Update Platform Version from JetBrains Gateway Plugin (Stable)

- components/ide/jetbrains/gateway-plugin/gradle-latest.properties
This PR updates the Platform Version from JetBrains Gateway Plugin (EAP) to the latest version.
- You should use Gateway version corresponding to plugin qualifier, i.e. for stable plugin test with released, for latest test with EAP.
- It could be that a new Gateway is not published for the given SDK yet then wait for it to be published. You can check the build version in the About dialog.
- You can …
> [JetBrains] Update Platform Version from JetBrains Gateway Plugin (EAP)

- WORKSPACE.yaml
- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/ide-config/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/message-bus-password/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
Update code to `1.75.0`
A part of https://github.com/gitpod-io/gitpod/issues/16114
```release-note
NONE
```
> [code] New vscode release 1.75

- components/dashboard/src/workspaces/WorkspacesNew.tsx
Reflect breaking changes of https://github.com/gitpod-io/website/pull/3326
Fixes #
```release-note
NONE
```
> :seedling: reflect docs breaking changes

- components/server/ee/src/prebuilds/github-app.ts
`pull_request.synchronize` events of Gitpod's GH App are generating noise, but the do not provide any value.
There is a general `push` event handler which takes care of the same thing basically. And what's more, both are receive when the author pushes updates to a PR's branch, which does mean we need to deduplicate on our end.
Check this DB query if you need to see the events rushing in, to verify they are always dupes:
```
select * from d_b_webhook_event   order by creationTime DESC limit 100;
```
To reviewers, if you read `handlePullRequest` you'll find no special handling for PRs in general. The relevant information bit is `contextURL: payload.pull_request.html_url`, which has an in equivalent in `push` event handler. 
Unsubscribing from `pull_request.synchronize` should be zero risk. …
> [gh-app] unsubscribe from pull_request.synchronize

- components/dashboard/src/components/ContextMenu.tsx
- components/dashboard/src/components/ItemsList.tsx
- components/dashboard/src/workspaces/WorkspaceEntryNew.tsx
- components/dashboard/src/workspaces/WorkspaceOverflowMenu.tsx
The below issues propose improvement for the UX of the Workspace Entry Components, by keeping the hovered effect ( the background colors ) of the workspace items till the `WorkspaceOverflowMenu` is expanded. Please refer the below images for reference of the improvement.
https://user-images.githubusercontent.com/72302948/216030419-a1c4f4c6-9ce0-4beb-bd63-d1a2cd4a58a9.mov
* Closes #4635  
* Check a fix from #12033
- Change your directory from /gitpod to /gitpod/component/dashboard
- Add your host and token as given in the readme
- Start the development server by `yarn run start` and check on `http://localhost:3000` for checking the dashboard
```release-note
Improve the ItemsList and ContextMenu components
```
> [FIX] Improved UX for Workspace Entry Component

- components/server/ee/src/workspace/gitpod-server-impl.ts
- components/server/src/workspace/gitpod-server-impl.ts
* Uses `guardTeamOperation` for Team/Org related RPCs
* Also returns the members, which are fetched as part of the guard to be used subsequently
* Returns UNATHORIZED when fetching an Org ID which doesn't exist
Fixes #
```release-note
NONE
```
> [server] Cleanup Organization RPCs authorization checks

- components/server/ee/src/workspace/gitpod-server-impl.ts
- components/server/src/authorization/perms.ts
- components/server/src/workspace/gitpod-server-impl.ts
Adds fine-grained operations to teams, pre-cursor to actually start checking for the permissions. For now, these are logged, when the feature flag is enabled.
* Part of https://github.com/gitpod-io/gitpod/issues/16102
* Depends on https://github.com/gitpod-io/gitpod/pull/16186
```release-note
NONE
```
/hold for dependency
> [server] Extend guardTeamResource with fine-grained ops

- .github/workflows/build.yml
Fixes #
```release-note
NONE
```
> Don't publish npm packages from gha action on main

- components/ide-service/pkg/server/server.go
Always send IdeImageLayers in ide-service
Start a prebuild check it runs successfully
```release-note
NONE
```
> [ide-service] Always send IdeImageLayers

- components/server/ee/src/prebuilds/github-app.ts
Reverts gitpod-io/gitpod#16193
Reverting after internal discussion. Turns out we might miss webhook events in certain cases, where the config is default.
```release-note
NONE
```
> Revert "[gh-app] unsubscribe from pull_request.synchronize"

- components/ws-manager-mk2/main.go
- install/installer/pkg/components/ws-manager-mk2/deployment.go
- install/installer/pkg/components/ws-manager-mk2/role.go
Configure leader election on the ws-manager-mk2 controller manager. Requires additional role policy rules to manage leases, these rules are taken from the generated [`leader_election_role.yaml`](https://github.com/gitpod-io/gitpod/blob/main/components/ws-manager-mk2/config/rbac/leader_election_role.yaml) by kubebuilder
Open preview env, check logs of `ws-manager-mk2` to confirm a leader-election lease has been successfully acquired
```release-note
NONE
``` …
> [ws-manager-mk2] Configure leader election

- .github/CODEOWNERS
- .github/workflows/ide-integration-tests.yml
Scaffolding for running IDE integration test jobs.
Part of https://github.com/gitpod-io/gitpod/issues/15874
Can only be tested on main 😢 
```release-note
NONE
```
N/A
> Add scaffolding for IDE integration tests

- components/server/package.json
- components/server/src/authorization/spicedb.ts
- components/server/src/container-module.ts
- yarn.lock
Adds basic spicedb client. We'll likely need to adjust a few things, but this helps keep subsequent changes smaller, and it ensures we land the spicedb dependency without too many other changes.
* Part of https://github.com/gitpod-io/gitpod/issues/16102
1. Server comes up in preview
```release-note
NONE
```
> [server] Add spicedb client

- components/server/ee/src/workspace/gitpod-server-impl.ts
- components/server/src/authorization/checks.ts
- components/server/src/authorization/perms.ts
- components/server/src/container-module.ts
- components/server/src/prometheus-metrics.ts
- components/server/src/workspace/gitpod-server-impl.ts
Behind an experiment, performs authorization checks for Organizaitons against SpiceDB, and reports the outcome. Whether the outcome matches, or not, we always return the result of the existing authorization check.
Effectively, this change allows us to being checking perms against spicedb, without affecting the system, only collecting data.
We do not yet create any relationships against spicedb. As a result, all of these checks will return "NO_PERMISSION" initially. That's desired. We want to have the checks in place, and incrementally start adding these relationships, either from a batch job, or when resources are actually created. This will be done in subsequent PR(s).
* Part of https://github.com/gitpod-io/gitpod/issues/16103
* Depends on https://github.com/gitpod-io/gitpod/pull/16197 …
> [server] Perform authorization checks for Orgs against spicedb

- install/installer/pkg/components/spicedb/networkpolicy.go
To use dispatching, we need an instance of SpiceDB to talk a sibling replica to utilize caches. For that, we need to enable ingress
Fixes #
```release-note
NONE
```
> [spicedb] Enable ingress policy for dispatch endpoint, from sibling

- components/dashboard/src/app/AppRoutes.tsx
- components/dashboard/src/components/UsageView.tsx
- components/dashboard/src/teams/TeamBilling.tsx
- components/dashboard/src/teams/TeamSettings.tsx
This is a follow up fix that ensures page state is evicted and refreshed when the user changes the org.
Fixes #
```release-note
NONE
```
> [dashboard] state must evict when org changes

- install/installer/pkg/components/spicedb/deployment.go
Turns that flag is needed, otherwise the dispatch server is not started, even if the endpoint is provided.
Fixes #
```release-note
NONE
```
> [spicedb] Actually enable running dispatch server

- components/gitpod-db/src/typeorm/migration/1675694207999-WorkspaceClusterRegion.ts
DB migration. adding a region column to `d_b_workspace_cluster`
Fixes #
```release-note
NONE
```
> [gitpod-db] Add region for cluster selection

- install/installer/pkg/components/spicedb/deployment.go
Lowers frequency of readiness check, ensures we reference the port as a const
Fixes #
```release-note
NONE
```
> [spicedb] Adjust readiness probe frequency

- components/dashboard/src/components/UsageBasedBillingConfig.tsx
Minor semantics update for the billing section header.
See [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1675717801989549?thread_ts=1675450979.289809&cid=C01KPEPQYE6) (internal). Cc @selfcontained 
Go to billing settings.
1. There should be no visual difference.
2. The section subheading should now use a `<p>` element instead of an `<h2>` element.
```release-note
NONE
```
> Update settings section header semantics

- operations/observability/mixins/meta/rules/server.yaml
Why? This alert fires too often / is generally a false positive. 
In other words, in it's current form, it's not a signal of a system failure.
Refer to this internal thread for background: https://gitpod.slack.com/archives/C02EN94AEPL/p1675672440834989?thread_ts=1675503506.839219&cid=C02EN94AEPL
Fixes # n/a
n/a
```release-note
NONE
```
> [obs] Temporarily avoid imageBuildFailure reason for InstanceStartFailures alert

- components/common-go/namegen/workspaceid.go
- components/ws-proxy/pkg/proxy/workspacerouter.go
Have a shared regex pattern in `common-go`, and reuse in `ws-proxy`
Fixes https://github.com/gitpod-io/gitpod/pull/16144#discussion_r1095480371
Make sure workspace can be started
```release-note
NONE
```
> Reuse the same workspace patterns

- components/ws-manager-api/go/crd/v1/workspace_types.go
- components/ws-manager-mk2/controllers/workspace_controller.go
- components/ws-manager-mk2/main.go
- components/ws-manager-mk2/pkg/activity/activity.go
- components/ws-manager-mk2/service/manager.go
- components/ws-manager-mk2/ws-manager-mk2.code-workspace
Splitting out from https://github.com/gitpod-io/gitpod/pull/16122
This PR implements `MarkActive` in ws-manager-mk2.
Also contains some drive-by improvements (vscode workspace, remove error log in reconciler if resource is not found, this is normal and happens on deletion)
Open in preview env, check that the `FirstUserActivity` condition gets set on the workspace CR when opening a workspace.
```release-note
NONE
```
> [ws-manager-mk2] Implement MarkActive

- components/common-go/kubernetes/kubernetes.go
- components/ws-manager-mk2/controllers/status.go
- components/ws-manager-mk2/controllers/workspace_controller.go
- components/ws-manager-mk2/service/manager.go
Cleanup: use existing k8s utils from common-go, and extract some new common util functions in mk2 to common-go.
Stacked PR on https://github.com/gitpod-io/gitpod/pull/16181, adding hold.
Relates to #11416
```release-note
NONE
```
> [ws-manager-mk2] Extract ctrl utils to common-go

- components/dashboard/src/app/AppRoutes.tsx
- components/dashboard/src/components/ConfirmationModal.tsx
- components/dashboard/src/components/Modal.tsx
- components/dashboard/src/components/PageWithSubMenu.tsx
- components/dashboard/src/components/forms/InputField.tsx
- components/dashboard/src/components/forms/SelectInputField.tsx
- components/dashboard/src/components/forms/TextInputField.tsx
- components/dashboard/src/contexts/FeatureFlagContext.tsx
- components/dashboard/src/data/auth-providers/delete-org-auth-provider-mutation.ts
- components/dashboard/src/data/auth-providers/org-auth-providers-query.ts
- components/dashboard/src/data/auth-providers/upsert-org-auth-provider-mutation.ts
- components/dashboard/src/data/billing-mode/org-billing-mode-query.ts
- components/dashboard/src/data/organizations/org-members-query.ts
- components/dashboard/src/hooks/use-onblur-error.ts
- components/dashboard/src/hooks/useId.ts
- components/dashboard/src/menu/Menu.tsx
- components/dashboard/src/teams/GitIntegrationsPage.tsx
- components/dashboard/src/teams/OrgSettingsPage.tsx
- components/dashboard/src/teams/TeamBilling.tsx
- components/dashboard/src/teams/TeamSettings.tsx
- components/dashboard/src/teams/git-integrations/GitIntegrationListItem.tsx
- components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
- components/dashboard/src/teams/git-integrations/GitIntegrations.tsx
- components/dashboard/src/teams/git-integrations/GitIntegrationsList.tsx
- components/dashboard/src/teams/teams-context.tsx
- components/dashboard/src/workspaces/StartWorkspaceModal.tsx
- components/gitpod-protocol/src/gitpod-service.ts
This PR adds a new **Git Integrations** page to the Organization Settings area that is behind the `orgGitAuthProviders` feature flag, which is off in prod, but on otherwise. It's largely like the Integrations found under Personal Settings, but refactored to plug in react-query, and be a bit more idiomatic React. This helped simplify some of the state management that was happening. It's still quite a bit of code though for these new views. While refactoring, I tried to pave some ground for simplifying a few things going forward:
|   |  |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/367275/216502699-ddb4ac08-1dd9-4e2b-8e80-cc094d797c07.png)  | ![image](https://user-images.githubusercontent.com/367275/216502732-382aa3f1-6acc-4d41-98d2-cbb55e186030.png …
> git auth under team settings

- dev/preview/previewctl/cmd/stale.go
- dev/preview/previewctl/cmd/workspaces.go
- dev/preview/previewctl/pkg/preview/status.go
- dev/preview/previewctl/pkg/preview/util.go
This changes the staleness heuristics so that we now use the following rules
1. If the preview environments was created in the last 48 hours we consider it active
2. If there is a branch for the preview environment and it was a commit in the last 48 hours we consider it active
This means that we no longer consider a preview environment stale just because the branch doesn't exist. This is okay because preview environments are being deleted when branches are deleted now by [preview-env-delete.yml](https://github.com/gitpod-io/gitpod/blob/main/.github/workflows/preview-env-delete.yml), so checking for missing branches is less important now. Should that trigger fail, we'll still delete the preview environments once the 48 hours are up.
There are two motivations for this.
1. With our new …
> Simplify preview environment staleness check

- components/gitpod-cli/cmd/info.go
Added workspaceContextUrl to gp-cli. 
I've appended the workspaceContextUrl response from the supervisor API to the `gp info` command. See #14923
Fixes #14923
- Run gitpod in gitpod --> [gitpod.io#https://github.com/Kwok-he-Chu/gitpod/tree/add-workspacecontexturl-to-gpicli](gitpod.io#https://github.com/Kwok-he-Chu/gitpod/tree/add-workspacecontexturl-to-gpicli)
- Run `cd components/gitpod-cli`
- Run `go run . 'info'`
- Verify whether the WorkspaceContextUrl is shown
```release-note
Added `Workspace Context Url` to `gp info`
```
The documentation can be found [here](https://www.gitpod.io/docs/references/gitpod-cli#info). From what I see, we do not need to update it. However it would be nice to complete the list. I can forward a documentation request if needed to append the following 5 (+1) …
> Add workspacecontexturl to gpcli

- components/dashboard/src/components/DropDown2.tsx
- components/dashboard/src/components/SelectIDEComponent.tsx
- components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
[screen-capture (1).webm](https://user-images.githubusercontent.com/77020164/213983420-7dfbdc0a-7714-40fc-a563-07684a6e1186.webm)
Fixes #15912
```release-note
[fix] :Preselect editor and class on the new workspace modal on first load
```
> [fix] :Preselect editor and class on the new workspace modal on first load

- install/installer/pkg/components/public-api-server/deployment.go
- install/installer/pkg/components/spicedb/deployment.go
- install/installer/pkg/components/spicedb/rolebinding.go
Binds metrics server, and adds kube-rbac-proxy sidecar to allow us to scrape metrics.
Fixes #
```release-note
NONE
```
> [spicedb] Add kube-rbac-proxy to expose metrics endpoint

- components/dashboard/src/menu/Menu.tsx
Small fix for a problem I introduced earlier, where the menu would start to scroll.
We should handle small viewports properly, so this is just a fix for the current state so we can deploy dashboard again.
Fixes https://github.com/gitpod-io/gitpod/issues/16274
```release-note
NONE
```
> [dashboard] small fixes

- .github/actions/deploy-gitpod/entrypoint.sh
- .github/actions/deploy-gitpod/metadata.yml
- .github/pull_request_template.md
- .github/workflows/build.yml
Doesn't have an issue, but drive by fixing stuff needed to enable GHA as main build. Mostly things missing for the [installer options](https://github.com/gitpod-io/gitpod/blob/main/.werft/jobs/build/installer/installer.ts#L25) (added as a toggle block) and an option to publish to JB marketplace.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details> …
> Add missing options to gha build

- WORKSPACE.yaml
- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/ide-config/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/message-bus-password/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
Cherry pick firefox webview workaround 
https://github.com/gitpod-io/openvscode-server/commit/f0243d2812ae21ca28befe7fb98ef4c2ce641916
- Check webviews work in firefox
```release-note
NONE
```
> [code] Cherry pick firefox webview workaround

- components/dashboard/src/App.tsx
- components/dashboard/src/teams/TeamSettings.tsx
When the org changes, we're best of forcing a re-render of the app to ensure clean state inside of components. This sets a `key` to the org id (w/ a fallback for when there is no org) on the `<AppRoutes/>` component.
* Create at least 2 orgs
* Visit the General Org Settings for one org.
* Switch orgs w/ the switcher, and ensure the UI updates to show the currently selected org
* It would be worthwhile to click around a few other places in the UI, and change orgs from them.
```release-note
NONE
```
<details>
</details>
<details> …
> Re-render app on org change

- components/server/ee/src/billing/billing-mode.spec.db.ts
- components/server/ee/src/billing/billing-mode.ts
Fixes https://github.com/gitpod-io/gitpod/issues/16231
- `leeway run components/gitpod-db:init-testdb`
- `(cd components/server && yarn db-test)`
```release-note
Fix evaluation of BillingMode: Ignore old "free" subscription entries
```
> [server] Ignore old FREE/FREE_50 when evaluating BillingMode

- .github/workflows/code-nightly.yml
Point code nightly worklow back to main branch
```release-note
NONE
```
> [code] Point code nightly worklow back to main branch

- components/gitpod-cli/cmd/rebuild.go
- components/ide/code/codehelper/.gitignore
- components/ide/code/codehelper/main.go
- fix checkout and workspace locations
- don't generate dockerfile if image is specified to avoid sending build context to daemon over and over
- only do inline replacements for VS Code Server in debug mode
Fixes #
- Start a workspace, try to use image and dockerfile and verify that rebuild works in both cases.
- While using an image you should not see anymore transferring build context to daemon.
- Try to change a workspace location in .gitpod.yml, start using gp rebuild, check that checkout and workspace locations are proper.
```release-note
NONE
```
<details>
</details>
<details> …
> small improvements for gp rebuild

- .github/CODEOWNERS
See https://github.com/gitpod-io/gitpod/pull/16273#issuecomment-1421924006
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [image-builder-api] Update CODEOWNERS

- components/dashboard/src/feedback-form/FeedbackComponent.tsx
Currently the emoji order is from good to bad which seems weird.
| Before Change      | 
| ----------- | 
| <img src="https://user-images.githubusercontent.com/666176/217501912-3b69c895-08e6-4192-8810-add1a1c938ff.png"  width="300">
This PR changes it go from bad to good. This change can have an impact on scores.
See [relevant discussion](https://gitpod.slack.com/archives/C01KPEPNBD0/p1675824030623679) (internal). Cc @mbrevoort @chrifro 
N/A
```release-note
NONE
> Reverse order of Feedback emojis

- components/gitpod-db/go/conn.go
Else we log the SQL query for every NotFound error, [see logs](https://cloudlogging.app.goo.gl/g9Co9dSinbpjSbeZ9)
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [gorm] Ignore NotFound errors when logging

- .github/CODEOWNERS
Our team is smaller now so we should change ws-manager-api code owners to include all of team workspace.
n.a.
n.a.
```release-note
None
```
<details>
</details>
<details>
</details>
> Change ws-manager-api code owners

- components/gitpod-cli/cmd/rebuild.go
With recent changes VS Code Desktop support broke for gp rebuild and JB was not tested yet. This PR disables them for now.
Fixes #
- Start a workspace with VS Code Desktop.
- Use gp rebuild.
- Check that you can access the debug workspace.
```release-note
NONE
```
<details>
</details>
<details>
</details>
> gp rebuild: disable desktop IDEs

- components/gitpod-db/src/typeorm/migration/1675744891502-WorkspaceOrganizationId.ts
This is the first change towards organization-owned workspaces. This PR
- adds `organizationId` to `d_b_workspace`
- updates existing workspaces based on the attribution id of their instances (if it's a team attribution)
In prod the column is already created on both databases, so also the migration doesn't run there. We are going to run the migration manually.
See #16177
```release-note
NONE
```
> [db] d_b_workspace get organizationId

- components/ws-daemon/pkg/daemon/daemon.go
- components/ws-manager-mk2/BUILD.yaml
- components/ws-manager-mk2/controllers/create.go
- components/ws-manager-mk2/controllers/status.go
- components/ws-manager-mk2/controllers/suite_test.go
- components/ws-manager-mk2/controllers/workspace_controller.go
- components/ws-manager-mk2/go.mod
- components/ws-manager-mk2/go.sum
- components/ws-manager-mk2/main.go
- components/ws-manager-mk2/pkg/proxy/imagebuilder.go
Make ws-manager-mk2 work in ephemeral clusters
- Support tls for image builder proxy
- Resolve port bind conflict (ws-daemon controller manager tried to bind to port 8080 which is also the port the grpc service binds to). We will expose metrics from the already existing ws-daemon metric endpoint instead (to be added later).
- Ensure that owner token and workspace url are set even if there is a conflict updating the workspace CR
n.a.
- Create ephemeral cluster (did not see the port bind issue in preview environments). Use [this branch](https://github.com/gitpod-io/ops/pull/8240) when creating the cluster.
- ws-daemon should start up 
- You should not see tls errors during startup
```release-note
None
``` …
> [ws-manager-mk2] Support deployment to ephemeral clusters

- components/server/package.json
- components/server/src/workspace/gitpod-server-impl.ts
- components/server/src/workspace/region-service.ts
- components/server/src/workspace/workspace-starter.ts
- yarn.lock
Behind an experiment, attempts to guess the region where the user is, to select the appropriate WS cluster.
WS clusters do not have the region property set, yet. This means nothing changes in the current scheduling. Once we set them, and enable the experiment, we can determine which region the workspace should belong to.
Not too happy with this static approach, but see [thread](https://gitpod.slack.com/archives/C02EN94AEPL/p1675852587321389) for more details.
Fixes #
```release-note
NONE
```
<details>
</details>
<details> …
> [server] Guess workspace region

- components/gitpod-protocol/src/typings/globals.ts
- components/supervisor/frontend/src/index.ts
Add open desktop ide entrypoint for browser code to avoid open in desktop IDE alert with workspace origin
Fixes #
- Open workspace in preview env with latest browser code
- Quick action with `Open in VS Code` should alert with `gitpod.io` or no alerts (configured in browser)
[Tested](https://github.com/gitpod-io/gitpod/pull/16260#pullrequestreview-1289144751)
```release-note
NONE
```
> Add open desktop ide entrypoint for browser code

- WORKSPACE.yaml
- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/ide-config/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/message-bus-password/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
https://github.com/gitpod-io/openvscode-server/commit/5d4e782a382339b3e25d6b426901fb06f51ecc85
Fixes #
No need to test, but confirm that Latest Browser Code work, and commit hash in `About` should be equal to `5d4e782a382339b3e25d6b426901fb06f51ecc85`
```release-note
NONE
```
<details>
</details>
<details>
</details>
> Update stable Browser Code to add open desktop IDE command

- components/gitpod-db/.vscode/launch.json
- components/gitpod-db/go/workspace.go
- components/gitpod-db/src/typeorm/entity/db-workspace.ts
- components/gitpod-db/src/typeorm/transformer.ts
- components/gitpod-db/src/user-to-team-migration-service.ts
- components/gitpod-db/src/workspace-db.spec.db.ts
- components/gitpod-protocol/src/protocol.ts
- components/server/ee/src/prebuilds/prebuild-manager.ts
- components/server/ee/src/workspace/workspace-factory.ts
- components/server/src/workspace/gitpod-server-impl.ts
- components/server/src/workspace/workspace-factory.ts
- components/server/src/workspace/workspace-starter.ts
Adds the application logic to set the organization id when a workspace is being created
See #16177
```release-note
NONE
```
> [server] set organizationid on workspace creation

- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/ide-config/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/message-bus-password/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
Update `gitpod-web` extension to improve open desktop ide prompt
Fixes #
1. start a workspace using vscode desktop in preview environment
2. click `Open in VSCode Desktop` button, check the prompt should direct under preview environment domain.
3. click `Open in browser` button, wait vscode load finish, Click left bottom Gitpod icon, select `Open in VS Code`, check the prompt should direct under preview environment domain.
```release-note
Improve prompt for `Open in VSCode` action in Browser Code
```
<details>
</details>
<details> …
> Update gitpod-web extension to improve open desktop ide prompt

- .github/CODEOWNERS
Discussed with @kylos101 and follow up from https://github.com/gitpod-io/gitpod/pull/16291#issuecomment-1422325073 - change image-builder-api CODEOWNERS to team workspace.
n/a
n/a
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [image-builder-api] Update codeowners to ws team

- components/supervisor/openssh/leeway.Dockerfile
We are not affected by CVE-2023-25136 but we should keep up to date.
```release-note
NONE
```
<details>
</details>
<details>
</details>
> Update openssh to v9.2

- dev/gpctl/cmd/clusters-register.go
Because the region of a cluster is loosely (stringly) typed, there's a risk we get it wrong. This change provides a hint on the values to use for a region, and at least ensures it is all lowercase.
* Related change https://github.com/gitpod-io/gitpod/pull/16303
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [gpctl] Ensure region is all lowercase, provide cmd help

- components/public-api-server/pkg/apiv1/oidc.go
- components/public-api-server/pkg/apiv1/oidc_test.go
As part of #15960, this should help to identify issues with entered OIDC client config and/or the service an Org admin wants to connect with. Non reachable services are a common source of errors when connecting to 3rd party services. An early check helps to identify problems early on. 
Part of #15960
1. Try to create an OIDC client with unreachable issuer,
see there is an error logged on JS console and network tab, e.g.
```
{"code":"invalid_argument","message":"Get \"https://accounts.foobaar.com\": dial tcp: lookup accounts.foobaar.com on 10.43.0.10:53: no such host"}
```
2. Verify, creating of OIDC clients with reachable issuer (e.g. `https://accounts.google.com`) works.
```release-note
NONE
``` …
> [OIDC] Check issuer URL for reachability

- components/gitpod-db/src/container-module.ts
- components/gitpod-db/src/long-running-migration/long-running-migration.spec.db.ts
- components/gitpod-db/src/long-running-migration/long-running-migration.ts
- components/gitpod-db/src/long-running-migration/workspace-organizationid-migration.spec.db.ts
- components/gitpod-db/src/long-running-migration/workspace-organizationid-migration.ts
- components/gitpod-db/src/typeorm/entity/db-long-running-migration.ts
- components/gitpod-db/src/typeorm/migration/1675863598550-LongRunningMigration.ts
- components/server/src/server.ts
This PR introduces a long-running migration and small service that manages and executes it.
This relies on new workspaces getting an organizationId see #16261
See #16177
```release-note
NONE
```
> [db] long running migration for filling the organizationid in workspaces

- components/gitpod-cli/cmd/sync-await.go
A copy from https://github.com/gitpod-io/gitpod/pull/16330
Fix `gp sync-await` command cannot interrupt problem. 
Fixes https://github.com/gitpod-io/gitpod/pull/16330
- Exec command `gp sync-await a`
- Interrupt command `Ctrl+C`
- Exec command `gp sync-await a` and `gp sync-done a`, make sure first command respond ok
```release-note
NONE
```
<details>
</details>
<details>
</details> …
> [gp-cli] fix sync-await cannot interrupt

- components/gitpod-db/src/long-running-migration/workspace-organizationid-migration.ts
Reduces the batch size of the workspace migration to only handle workspaces created within an hour at most.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [gitpod-db] reduce migration batch size

- components/ws-manager-api/go/config/config.go
- components/ws-manager-mk2/controllers/status.go
- components/ws-manager-mk2/controllers/timeout_controller.go
- components/ws-manager-mk2/controllers/workspace_controller.go
- components/ws-manager-mk2/main.go
- install/installer/pkg/components/ws-manager-mk2/configmap.go
Implements workspace timeouts. 
Depends on https://github.com/gitpod-io/gitpod/pull/16181 to mark user activity.
**Differences with mk1:**
* Check for timeouts using a controller instead of a loop running on a timer:
* Use a (new) controller to monitor workspaces and add the `Timeout` condition, instead of a timer running every 15 seconds checking all workspaces in a separate goroutine.
* The new `timeout_controller` requeues reconcile events, such that each workspace gets reconciled every 15 seconds.
* It's implemented as a separate controller than the `workspace_controller`, to keep the reconcile loop light-weight, as it runs every 15 seconds for each workspace. Both controllers share the same k8s cache provided by the controller manager.
* Handling pod restarts for in-memory cache of …
> [ws-manager-mk2] Workspace timeouts

- components/gitpod-cli/cmd/timeout-set.go
- components/gitpod-cli/cmd/timeout-show.go
- components/gitpod-protocol/go/gitpod-service.go
- components/gitpod-protocol/java/src/main/java/io/gitpod/gitpodprotocol/api/entities/SetWorkspaceTimeoutResult.java
- components/gitpod-protocol/src/gitpod-service.ts
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/ExtendWorkspaceTimeoutAction.kt
- components/server/ee/src/workspace/gitpod-server-impl.ts
This PR adds 5 workspace timeout-related features:
- a dialog in JetBrains IDEs so that one can make the workspace timeout anything they desire 
- `humanReadableDuration` as a parameter of `SetWorkspaceTimeoutResult`, so that clients can echo the server-interpreted time duration of the timeout extension.
- a hard limit of 24 hours for timeouts
- better timeout validation: durations like `2H` or `20M` are now allowed, while values like `0xfd` have been excluded
- a prettier time output when setting a timeout with `gp timeout set`
Following https://github.com/gitpod-io/gitpod/pull/15815
Fixes https://github.com/gitpod-io/gitpod/issues/16107
1. Open the preview environment
2. Select IntelliJ IDEA as your IDE of choice
3. Open any new workspace
4. Hit <kbd>Shift</kbd> twice and find `Gitpod: …
> Workspace Timeout improvements (JetBrains)

- components/gitpod-db/.vscode/launch.json
- components/gitpod-db/src/user-to-team-migration-service.spec.db.ts
- components/gitpod-db/src/user-to-team-migration-service.ts
Turns out that MYSQL doesn't the optimize subquery in the IN clause of the UPDATE statement, and hence, the entire d_b_workspace table is being scanned.
This PR rewrites the update to use a JOIN, which will be optimized using the indices on d_b_workspace.id and d_b_workspace_instance.workspaceid and the UPDATE statement should be faster.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details> …
> [db] optimize workspace update

- gitpod-ws.code-workspace
- scripts/update-gitpod-ws.code-workspace.js
Updates the vs code workspace to include all leeway components that contain either a `go.mod` or a `package.json` file alphabetically sorted.
The reason for this change is that there is currently no ordering nor strategy to what is included and what is not. Just including all components might be ok if it doesn't pay a too big toll on the performance of the workspace/language servers.
Fixes #
start a workspace on this PR and check the VS Code experience
```release-note
NONE
``` …
> update vscode workspace folders

- components/dashboard/src/menu/Menu.tsx
Removes the `isMinimalUI` function, always showing all navigation menu items.
See [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1675800615601449) (internal). Cc @selfcontained @atduarte @mbrevoort 
Try adding a new :a: organization or :b: project and notice the navigation stays there.
```release-note
Always show all navigation menu items
```
<details>
</details>
<details>
</details>
Valid …
> Always show all navigation menu items

- components/gitpod-protocol/src/util/gitpod-host-url.ts
[gitpod-protocol] add back gitpod-host-url bill and setting
because vscode extension still need it
https://github.com/gitpod-io/gitpod-code/blob/57f10d5fd6d6a325b6d991b96a30fef9eb42ec03/gitpod-shared/src/features.ts#L242
https://github.com/gitpod-io/gitpod-code/blob/57f10d5fd6d6a325b6d991b96a30fef9eb42ec03/gitpod-shared/src/features.ts#L242
or we want to remove this form vscode extension?
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
If …
> [gitpod-protocol] add back gitpod-host-url bill and setting

- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/ide-config/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/message-bus-password/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
changes https://github.com/gitpod-io/gitpod-code/commit/57f10d5fd6d6a325b6d991b96a30fef9eb42ec03
Fixes https://github.com/gitpod-io/gitpod/issues/16283
- Open workpace in preview env
- Exec `/.supervisor/supervisor notify test --actions=open` to trigger notification in browser code / desktop code multiple times
- It should work and with correct selected action respond
```release-note
NONE
```
<details>
</details>
<details>
</details> …
> [gitpod-web-extension] fix supervisor notify request not await

- components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts
- components/gitpod-db/src/typeorm/workspace-cluster-db-impl.ts
- components/gitpod-db/src/workspace-cluster-db.spec.db.ts
- components/gitpod-protocol/src/gitpod-service.ts
- components/gitpod-protocol/src/workspace-cluster.ts
- components/server/src/workspace/gitpod-server-impl.ts
- components/server/src/workspace/region-service.ts
- components/server/src/workspace/workspace-cluster-imagebuilder-client-provider.ts
- components/server/src/workspace/workspace-starter.ts
- components/ws-manager-api/typescript/src/client-provider.spec.ts
- components/ws-manager-api/typescript/src/client-provider.ts
- components/ws-manager-bridge/src/cluster-service-server.ts
Adds high level geographic regions as possible WorkspaceRegions. This achieves the following:
* We can fail early, if we attempt to register a cluster with an invalid region value
* We get better type-safety when dealing with regions
* It actually encodes somewhere what are the possible values for a region
As a drive-by,
* Fixes querying for WS clusters with a region filter, this was missed in https://github.com/gitpod-io/gitpod/pull/16136
* Updates tests to also use the same values
* Part of https://github.com/gitpod-io/gitpod/issues/16271
```release-note
NONE
```
<details>
</details>
<details> …
> [server] Typed workspace region

- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/ide-config/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/message-bus-password/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/components-webapp/components.go
- install/installer/pkg/components/redis/constants.go
- install/installer/pkg/components/redis/deployment.go
- install/installer/pkg/components/redis/objects.go
- install/installer/pkg/components/redis/service.go
Deploys redis into application cluster.
* No persistence
* Single instance setup
Fixes #
1. Redis comes up in preview k8s
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [redis] Deploy component

- components/supervisor/cmd/init.go
- components/supervisor/cmd/root.go
- components/supervisor/cmd/run.go
supervisor: only write /dev/termination-log in `init` or `run` command
Fixes #
```release-note
NONE
```
> supervisor: only write /dev/termination-log in `init` or `run` command

- dev/gpctl/cmd/clusters-list.go
Adds Region to the list of clusters
* Depends on https://github.com/gitpod-io/gitpod/pull/16343
* Part of https://github.com/gitpod-io/gitpod/issues/16271
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold for dependency PR
> [gpctl] Expose region in cluster list

- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/ide-config/output.golden
- install/installer/cmd/testdata/render/kind-ide/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/message-bus-password/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/workspace/ide/constants.go
[vscode] allow user custom workspace timeout
Review should happen in https://github.com/gitpod-io/gitpod-code/pull/2, this PR only update `gitpod-web` extension
Fixes #16157
```release-note
Allow user custom workspace timeout in vscode.
```
> [vscode] allow user custom workspace timeout

- components/dashboard/src/app/AppRoutes.tsx
- components/dashboard/src/menu/OrganizationSelector.tsx
- components/dashboard/src/projects/Events.tsx
- components/dashboard/src/projects/Prebuild.tsx
- components/dashboard/src/projects/Prebuilds.tsx
- components/dashboard/src/projects/Project.tsx
- components/dashboard/src/projects/ProjectVariables.tsx
- components/dashboard/src/projects/project-context.tsx
Redirects to the right project (and org) for project URLs that don't exist.
Fixes redirect fro /tokens and /tokens/create
Fixes #16243
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [dashboard] fixing redirects

- components/dashboard/src/app/AppRoutes.tsx
- components/dashboard/src/app/OrgRequiredRoute.tsx
- components/dashboard/src/data/organizations/org-members-query.ts
- components/dashboard/src/teams/OrgSettingsPage.tsx
- components/dashboard/src/teams/SSO.tsx
- components/dashboard/src/teams/TeamBilling.tsx
- components/dashboard/src/teams/TeamSettings.tsx
- components/dashboard/src/teams/teams-context.tsx
This shifts the loading state and role check that happens on each org settings page into the `<OrgSettingsPage/>` component. This has the additional benefit of not reloading the same data on each page before we render it.
I've also swapped what was happening in the `useIsOwnerOfCurrentTeam` hook to a newer react-query backed `useCurrentOrgMember` hook. I have a todo to also deprecate the `useTeamMemberInfos` hook in favor of the react-query equivalent. In general not managing that state manually, and deferring to react-query for that will help simplify things, and avoid stale state, or having to manually refresh it in many places.
The changes here are scoped to the Org Settings pages. Opening each and verifying they load as expected should be sufficient.
* Create an Org
* Visit the Org …
> Move loading state and role check into OrgSettingsPage

- components/server/ee/src/billing/entitlement-service-license.ts
- components/server/ee/src/billing/entitlement-service-ubp.ts
- components/server/ee/src/prebuilds/prebuild-manager.ts
- components/server/src/billing/entitlement-service.ts
- components/server/src/user/user-service.ts
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [server] Don't start a prebuild if the usage limit got reached

- components/gitpod-cli/cmd/open.go
See [internal chat](https://gitpod.slack.com/archives/C01KGM9BH54/p1676267186476299?thread_ts=1676229689.327049&cid=C01KGM9BH54)
Fixes #
- Exec `gp open a.ts`, should work without another file opened
- Exec `gp open a.ts -w` should wait until you close this file and command can be interrupted
```release-note
NONE
```
<details>
</details>
<details>
</details> …
> [gp-cli] fix gp open cmd open another file

- README.md
- gitpod-ws.code-workspace
1. Add a Go workspace for `ws-manager-mk2`
2. Document in general why they are helpful (TIL)
[Related internal thread](https://gitpod.slack.com/archives/C032A46PWR0/p1676022566280669?thread_ts=1676021011.423679&cid=C032A46PWR0)
Fixes # n/a
Open a Gitpod for this branch, and observe that IntelliSense works for `ws-manager-mk2`.
```release-note
NONE
```
<details>
</details>
<details>
</details> …
> [devx] Go workspace for ws-manager-mk2 & related docs

- components/ws-manager-bridge/src/cluster-service-server.ts
- components/ws-manager-bridge/src/cluster-sync-service.ts
- components/ws-manager-bridge/src/config.ts
- components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
Fix preview env ws-manager-bridge crash loop
<details>
<summary>
Error Log
</summary>
<pre>
<code>
gitpod /workspace/gitpod/components/gitpod-cli (hw/fix-gp-open) $ kubectl get pods
NAME                                      READY   STATUS             RESTARTS       AGE
agent-smith-t628n                         2/2     Running            0              44m
blobserve-55874b8f89-2mnwm                2/2     Running            0              44m
content-service-69479c77b6-qpxlc          2/2     Running            0              44m
dashboard-c65446588-tdbpb                 1/1     Running            0              44m
fluent-bit-s76lj                          1/1     Running            0              45m
ide-metrics-8556bf4dbf-5hsfz              2/2     Running            0              44m …
> [ws-manager-bridge] fix incorrect module import

- components/gitpod-cli/cmd/timeout-set.go
- components/gitpod-cli/cmd/timeout-show.go
See [internal chat](https://gitpod.slack.com/archives/C03EG2PND38/p1676279217285779?thread_ts=1676278690.771969&cid=C03EG2PND38)
Fixes #
- Open this PR in gitpod
- Change input of `res.HumanReadableDuration` to empty string `""`
- Exec `gp timeout show` and `gp timeout set 3h` should work
```release-note
NONE
```
<details>
</details>
<details>
</details> …
> [gp-cli] fix empty human readable timeout

- .github/actions/deploy-gitpod/entrypoint.sh
- .github/workflows/build.yml
Fixes 
```bash
[dev/preview/previewctl:docker] Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%22__GIT_COMMIT%22%3A%22be8f9e30c5d8de8922330cbe79ebe5c188e0fb8c%22%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&pull=1&rm=1&shmsize=0&t=4e35ad8f7e7220672852718c1fbf72e6b8c5f1bc&target=&ulimits=null&version=1": dial unix /var/run/docker.sock: connect: permission denied
[dev/preview/previewctl:docker] package build failed
[dev/preview/previewctl:docker] Reason: exit status 1
☁️  uploading build artifacts to remote cache
```
and 
```bash
/entrypoint.sh: …
```
> Fix preview gha build

- components/server/ee/src/server.ts
- components/server/src/config.ts
- components/server/src/server.ts
- install/installer/cmd/testdata/render/agent-smith/output.golden
- install/installer/cmd/testdata/render/aws-setup/output.golden
- install/installer/cmd/testdata/render/custom-pull-repository/output.golden
- install/installer/cmd/testdata/render/customization/output.golden
- install/installer/cmd/testdata/render/external-registry/output.golden
- install/installer/cmd/testdata/render/gcp-setup/output.golden
- install/installer/cmd/testdata/render/http-proxy/output.golden
- install/installer/cmd/testdata/render/ide-config/output.golden
- install/installer/cmd/testdata/render/kind-meta/output.golden
- install/installer/cmd/testdata/render/kind-webapp/output.golden
- install/installer/cmd/testdata/render/message-bus-password/output.golden
- install/installer/cmd/testdata/render/minimal/output.golden
- install/installer/cmd/testdata/render/overrides-inline/output.golden
- install/installer/cmd/testdata/render/pod-config/output.golden
- install/installer/cmd/testdata/render/shortname/output.golden
- install/installer/cmd/testdata/render/statefulset-customization/output.golden
- install/installer/cmd/testdata/render/telemetry/output.golden
- install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
- install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
- install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
- install/installer/pkg/components/server/types.go
Allow to disable long running jobs vis config
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [server] disable long migrations via config

- install/installer/pkg/components/server/configmap.go
- install/installer/pkg/config/v1/config.md
- install/installer/pkg/config/v1/experimental/experimental.go
Adds two optional arguments to the installer, that allow to disable server jobs.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [installer] args to disable jobs

- test/tests/ide/jetbrains/gateway_test.go
Fixes #
See result here https://werft.gitpod-dev.com/job/gitpod-build-hw-jb-int.1/logs
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [test] update JetBrains RubyMine test repo

- components/ws-manager-mk2/controllers/status.go
- components/ws-manager-mk2/controllers/suite_test.go
- components/ws-manager-mk2/controllers/workspace_controller.go
- components/ws-manager-mk2/controllers/workspace_controller_test.go
- components/ws-manager-mk2/service/manager.go
- components/ws-manager-mk2/ws-manager-mk2.code-workspace
Create/update tests for the workspace controller, using the EnvTest suite.
Also contains some cleanup using e.g. `controllerutil` to manage finalizers.
Relates to #11416
```
cd components/ws-manager-mk2
go test ./...
```
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [ws-manager-mk2] Controller env tests

- components/gitpod-db/src/long-running-migration/long-running-migration.ts
- components/gitpod-db/src/long-running-migration/workspace-organizationid-migration.spec.db.ts
- components/gitpod-db/src/long-running-migration/workspace-organizationid-migration.ts
This change adds logs around the migration job as well as adding a bit of waiting between repeated db queries.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [migrations] added logs and air

- .github/CODEOWNERS
As discussed we will change the registry-facade-api ownership to all members of team workspace.
n.a.
n.a.
```release-note
None
```
<details>
</details>
<details>
</details>
> [codeowners] Update registry-facade-api owner

- components/image-builder-bob/leeway.Dockerfile
Update buildkit to the latest stable version
```release-note
NONE
```
<details>
</details>
<details>
</details>
> Update buildkit container image

- components/ws-daemon/pkg/controller/controller.go
- components/ws-manager-api/go/crd/v1/workspace_types.go
- components/ws-manager-mk2/controllers/create.go
- components/ws-manager-mk2/controllers/status.go
- components/ws-manager-mk2/controllers/workspace_controller.go
- components/ws-manager-mk2/controllers/workspace_controller_test.go
- components/ws-manager-mk2/service/manager.go
- Handle `Abort` workspace stop policy.
- Handle grace period in workspace stop request.
- Add termination timeout seconds to workspace Pods.
- Return `FinalBackupComplete` condition in API calls
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [ws-manager-mk2] Aborted condition, grace period

- components/gitpod-protocol/src/attribution.ts
- components/gitpod-protocol/src/gitpod-service.ts
- components/gitpod-protocol/src/protocol.ts
- components/server/ee/src/billing/entitlement-service-chargebee.ts
- components/server/ee/src/billing/entitlement-service-license.ts
- components/server/ee/src/billing/entitlement-service-ubp.ts
- components/server/ee/src/billing/entitlement-service.ts
- components/server/ee/src/prebuilds/prebuild-manager.ts
- components/server/ee/src/workspace/gitpod-server-impl.ts
- components/server/src/billing/entitlement-service.ts
- components/server/src/user/user-service.ts
- components/server/src/workspace/gitpod-server-impl.ts
- components/server/src/workspace/workspace-starter.ts
Adds `organizationId` to the create workspace options. Also removes dependencies on implicit org retrieval from some of the create Workspace logic.
Part of https://github.com/gitpod-io/gitpod/issues/16362
Start workspaces and verify that the usage attribution is the same as it usually is.
```release-note
NONE
```
<details>
</details>
<details>
</details> …
> [server] pass organizationId to create ws

- components/dashboard/src/user-settings/EnvironmentVariableEntry.tsx
- components/dashboard/src/user-settings/EnvironmentVariables.tsx
The below issues propose improvement for the UX of the Environment Variable Components in Settings, by keeping the hovered effect ( the background colors ) of the workspace items till the ItemOverflowMenu is expanded. Please refer the below graphics for reference of the improvement.
https://user-images.githubusercontent.com/72302948/217173813-084a8f18-92b9-46a0-af3c-3d5698c42e80.mov
* Fixes #4635 
- Change your directory from /gitpod to /gitpod/component/dashboard
- Add your host and token as given in the readme
- Start the development server by `yarn run start` and check on `http://localhost:3000` for checking the dashboard
```release-note
Added Environment Variable Entry Component and associated it with Item List Context Menu, with ChangeMenuState Function, to keep the hovered effect …
```
> feat: Improved UX for Environment Variable Item List ( Settings )

- components/dashboard/src/Login.tsx
* Closes #3841 's Login Page Errors 
- Fixes the lint issues in Login.tsx page
- Fixes the absence of alt text for images in the welcome login page
- Fixed the missing dependency of hostFromContext while fixing the multiple render bug!
- Additional Improvement
- The urlHash i.e. domain/#`https://github.com/P......` part is calculated thrice in each page load to find the hostProvider, hence I've fixed it to just be calculated once by maintaining appropriate states while fixing the missing dependency issue!
| Before (the hash calc function runs thrice) | After (the function runs once) |
|:-----|:--------:|
| ![before](https://user-images.githubusercontent.com/73993394/216068361-885a71d4-34ff-4d4a-90c1-27a4d5e08cba.gif) | ![after](https://user-images.githubusercontent.com/73993394/216201261-2 …
> [dashboard] Fix Dashboard lint errors for Login.tsx

- components/gitpod-db/src/auth-provider-entry-db.ts
- components/gitpod-db/src/typeorm/auth-provider-entry-db-impl.ts
- components/server/src/auth/auth-provider-service.ts
- components/server/src/auth/login-completion-handler.ts
Filters out org auth providers from user's own auth providers. I went with filtering at the `findByUserId` db query level. This seemed like the best route to treat the two different versions of auth providers the way we want, but please let me know if I'm missing anything. Here's the places I could see that would be effected by this change:
---
I believe these places would function like we want if they don't get org auth providers.
* `server.getOwnAuthProviders()`
* `server.deleteOwnAuthProvider()`
* `server.updateOwnAuthProvider()`
This spot will need to be tweaked so that it accounts for org auth providers not being returned from a `findByUserId()` call. ATM I have some comments around how I believe we could address it. I haven't included that change in this PR though.
* …
> filter out org auth providers from user providers

- components/ws-manager-mk2/controllers/create.go
- components/ws-manager-mk2/service/manager.go
Support class and network limiting and pressure stall information.
n.a.
- Check that workspace pod has cpu limiting and network limiting annotations applied
```release-note
None
```
<details>
</details>
<details>
</details>
> [ws-manager-mk2] Support class|network limiting and PSI

- components/ws-manager-api/go/crd/v1/workspace_types.go
- components/ws-manager-api/go/crd/v1/zz_generated.deepcopy.go
- components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml
- components/ws-manager-mk2/controllers/create.go
- components/ws-manager-mk2/service/manager.go
Support system environment variables. Depends on https://github.com/gitpod-io/gitpod/pull/16372
n.a.
- Open workspace in [preview environment](https://fo-adv-2.preview.gitpod-dev.com/workspaces)
- Check that workspace CR contains a section for system environment variables and user environment variables
- Check that these environment variables have been defined for the workspace pod
```release-note
None
```
<details>
</details>
<details>
</details> …
> [ws-manager-mk2] Support system environment variables

- components/ws-daemon/pkg/controller/controller.go
If content init or dispose fails (e.g. backup not found during init), update the workspace status with the failure condition, otherwise the workspace gets stuck in the init or stopping state.
1. Start workspace
2. Manually delete the workspace resource `kubectl delete ws <name>`
3. This causes the workspace to immediately stop without backup (will get fixed in https://github.com/gitpod-io/gitpod/pull/16400)
4. Restart the workspace
5. Workspace content init should fail as there's no backup
6. On the dashboard, you should see the workspace init failure, instead of stuck on "Starting"
```release-note
NONE
```
<details> …
> [ws-manager-mk2] Fix stuck on init/dispose failure

- components/ws-manager-mk2/controllers/create.go
- components/ws-manager-mk2/main.go
Fixes workspace creation using unset status fields, causing e.g. the workspace URL env var to be empty.
Instead, on creation of the workspace container, construct the URL and headless status directly.
- Create workspace in preview env
- Run `gp info` and see the workspace URL is not empty
```release-note
NONE
```
<details>
</details>
<details>
</details> …
> [ws-manager-mk2] Fix workspace URL not set in env

- components/ws-manager-api/go/crd/v1/workspace_types.go
- components/ws-manager-mk2/controllers/create.go
- components/ws-manager-mk2/controllers/status.go
- components/ws-manager-mk2/controllers/workspace_controller.go
- components/ws-manager-mk2/controllers/workspace_controller_test.go
- components/ws-manager-mk2/service/manager.go
- Add finalizer on the Workspace resource as well - such that deleting the workspace resource directly (instead of the Pod) still gracefully stops the workspace.
- Handle deleting the workspace resource, by propagating the deletion to the Pod, which then continuous deletion as normal.
- Once the workspace transitions to a `Stopped` phase, remove the finalizer on the workspace and finish deletion.
- `kubectl delete ws <name>`
- Observe the workspace gracefully shuts down with a backup, and eventually disappears from the cluster in `kubectl get ws`.
```release-note
NONE
```
<details> …
> [ws-manager-mk2] Add finalizer on workspace, handle ws deletion

- components/gitpod-db/src/auth-provider-entry.spec.db.ts
- components/gitpod-db/src/typeorm/auth-provider-entry-db-impl.ts
Fixes #16412
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [gitpod-db] Fix AuthProviderEntryDBImpl.findByUserId

- components/ide/jetbrains/image/resolve-latest-ide-version.sh
[jetbrains] make sure ide version is correct
Fixes #
1. run `bash ./components/ide/jetbrains/image/resolve-latest-ide-version.sh IIU`
the output should be `{"IDE_BUILD_VERSION": "223.8617.56", "IDE_VERSION": "2022.3.2"}`
```release-note
NONE
```
<details>
</details>
<details>
</details>
> [jetbrains] make sure ide version is correct

- components/dashboard/src/admin/ProjectDetail.tsx
- components/dashboard/src/admin/TeamDetail.tsx
- components/dashboard/src/admin/UserDetail.tsx
- components/dashboard/src/admin/UserSearch.tsx
- components/dashboard/src/admin/WorkspaceDetail.tsx
- components/dashboard/src/admin/WorkspacesSearch.tsx
- Fixes page layout for workspace and project pages.
- Add top margin to user, workspace, project, and organization pages.
- Fix column header alignment for user and workspace pages, and add missing sorting icons.
Fixes #16408 
```release-note
Update spacing layout for user, workspace, project, and organization in the admin dashboard
```
<details>
</details>
<details>
</details> …
> Update layout for admin dashboard pages

- components/dashboard/src/components/ContextMenu.tsx
- components/dashboard/src/components/org-icon/OrgIcon.tsx
- components/dashboard/src/components/org-icon/consistent-classname.test.ts
- components/dashboard/src/components/org-icon/consistent-classname.ts
- components/dashboard/src/components/org-icon/styles.css
- components/dashboard/src/data/billing-mode/user-billing-mode-query.ts
- components/dashboard/src/menu/Menu.tsx
- components/dashboard/src/menu/OrganizationSelector.tsx
- components/dashboard/tailwind.config.js
Updates the Org Selector to include the following links if available:
* Members
* Usage
* Settings
| Light Mode      | Dark Mode |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/367275/218192615-62cdfe10-e36f-4223-b86e-4686a041462b.png)      | ![image](https://user-images.githubusercontent.com/367275/218192772-23262a75-4858-4590-8da6-a07dbca6c953.png)      |
In addition, and to help call out the org entries in the selector, there are now icons for the orgs that use one of 9 available background gradients. This will help serve as a fallback/placeholder for when we add the ability to upload logos for an org.
The background gradient used is pegged to the corresponding `id` of the org, so it will be consistent across visits to the site. I've added some unit …
> Add nav items and icons to org selector
