gitpod-io/gitpod

components/public-api-server/go.mod
components/public-api-server/go.sum
components/public-api-server/pkg/oidc/oauth2.go
components/public-api-server/pkg/oidc/router_test.go
components/public-api-server/pkg/oidc/service.go
components/public-api-server/pkg/oidc/service_test.go
components/public-api-server/pkg/oidc/state_jwt.go
components/public-api-server/pkg/oidc/state_jwt_test.go
components/public-api-server/pkg/server/server.go

After this PR is merged, the state param of the OIDC/OAuth2 gets signed and verified. Validating of integrity is crucial, as this piece of information contains the ID of the OIDC client to continue with when Gitpod receives the callback from a 3rd party. Tests should show that expiration time is checked and signature validation is effective.
Part of #15956
See [internal post](https://gitpod.slack.com/archives/C02EN94AEPL/p1674209948602029?thread_ts=1674207266.608869&cid=C02EN94AEPL) for test credentials. 
1. Create new Org
2. Create new SSO client under settings
3. Select `Login` from actions menu (three dot button) 
4. Copy the full URL (starting with `https://accounts.google.com/o/oauth2/v2/auth/oauthchooseaccount?`) from browser's location bar.
5. Now, first see a working login into …

[oidc] encode and validate state params

---

components/dashboard/src/admin/WorkspaceDetail.tsx
components/dashboard/src/admin/WorkspacesSearch.tsx
components/dashboard/src/app/AppRoutes.tsx
components/dashboard/src/components/Tooltip.tsx
components/dashboard/src/workspaces/WorkspaceEntry.tsx
components/dashboard/src/workspaces/Workspaces.tsx

* Cleans up some filenames to remove the `New` from them after refactoring the Workspaces list components.
* Added a tooltip to the branch name as a small improvement for when it's cut off and you can't tell what the branch is.
* Verify Workspaces list view renders correctly.
* Hover over the branch name in the workspaces list and ensure there's a tooltip.
```release-note
NONE
```
<details>
</details>
<details>
</details> …

Rename "New" files back - add Tooltip to ws branch

---

operations/observability/mixins/cross-teams/dashboards.libsonnet
operations/observability/mixins/cross-teams/dashboards/gitpod-applications.json

A general purpose dashboard to show resource usage by applications - different `jobs` in k8s.
Design choices:
* Aggregated, with drill-down options in variables
* Always group by job, to keep the dashboard series count sane
**Why:**
We do not currently have at a glance way to understand the following:
* How many replicas of a thing are we running across all clusters?
* What's the aggregate CPU usage?
* What's the aggregate Mem usage?
This also allows us to decompose the overloaded `components / server` dashboards to shift the resource metrics into this general graph (and be used by other components also)
[You can play with this here](https://grafana.gitpod.io/d/AJKH-pJ4k/kubernetes-applications?var-cluster=All&var-node=All&var-pod=All&orgId=1&from=now-6h&to=now&var-job=All)
Fixes # …

[dashboard] k8s applications

---

components/dashboard/src/components/ContextMenu.tsx
components/dashboard/src/components/org-icon/OrgIcon.tsx
components/dashboard/src/menu/OrganizationSelector.tsx

Making a few adjustments to the org selector menu after some design reviews.
* Adding a checkmark to the selected org
* Fixing some cursor hover styles
* Preventing icon from shrinking with longer org names
The changes should all be visually verifiable.
```release-note
NONE
```
<details>
</details>
<details>
</details>

Small adjustments to org selector menu

---

operations/observability/mixins/meta/rules/ws-manager-bridge.yaml

You can explore the past trend [with this explore page](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%28rate%28process_cpu_seconds_total%7Bjob%3D%5C%22ws-manager-bridge%5C%22%7D%5B5m%5D%29%29%20by%20%28cluster%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D)
Fixes #
```release-note
NONE
```
<details>
</details> …

[ws-man-bridge] Adjust CPU alert to provide better signal

---

components/dashboard/src/components/DropDown2.tsx

Decrease the context dropdown element min height.
See [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1675276439778439) (internal). Cc @mbrevoort 
Open the new workspace modal (`CMD`+`N`) and notice the context dropdown element height is no fitting the content of the repository name.
|-|-|
| <img width="532" alt="dropdown-before" src="https://user-images.githubusercontent.com/120486/218744517-9610aa0a-a2f2-4aa7-83c5-d1e82ff2447c.png"> | <img width="532" alt="dropdown-after" src="https://user-images.githubusercontent.com/120486/218744526-6ee2ae27-0467-4c39-a6a5-87a080d3749f.png"> |
```release-note
Update context dropdown element height
```
Run …

Update context dropdown element height

---

components/ws-manager-mk2/controllers/status.go

Deployed condition was being repeatedly set with the latest timestamp
Observe the workspace isn't repeatedly reconciled by the controller
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Fix deployed condition being repeatedly set

---

components/dashboard/src/admin/License.tsx
components/dashboard/src/admin/Settings.tsx
components/dashboard/src/admin/admin.routes.ts
components/dashboard/src/menu/Menu.tsx

- Updates the Settings and License page layout to re-use the left sub-menu for better UX.
Fixes #16399 
```release-note
Update the Settings and License page layouts for the admin dashboard
```
<details>
</details>
<details>
</details>

UX: Re-use left sub-menu for Settings and License page on admin dashboard

---

.github/CODEOWNERS
components/gitpod-protocol/src/typings/globals.ts
components/supervisor/frontend/src/ide/ide-metrics-service-client.ts
components/supervisor/frontend/src/index.ts
components/supervisor/frontend/src/shared/frontend-dashboard-service.ts
components/supervisor/frontend/webpack.config.js

Fixes #
Relates https://github.com/gitpod-io/security/issues/121
- Open workspace in preview env with latest browser code
- Check localStorage if `credentials.providers` is encrypted
**compatible#1**
- Close workspace and change default IDE to stable browser code
- Re-open workspace, check if everything is alright (compatible)
**compatible#2 old workspace reopen**
- Copy credentials.provider from production and set
- Re-open workspace use stable browser code
- Check if it encrypted again and the decrypted value is the same with just copied value
----
✅ Use latest browser code to start a workspace in preview env confirmed that it's encrypted, change it's value (add copy and change service name) refresh still exists, restart workspace still exists
|Change Value|Restart Workspace|
|:-:|:-:| …

Add encryption endpoint in supervisor frontend

---

operations/observability/mixins/workspace/rules/central/workspaces.yaml

For the last 30 days:
This new **GitpodImagebuildDoneSuccess** would have triggered once, on January 26 if set to 2h, instead of 4h.  A customer was potentially struggling with the outer loop. [We hit a 60% error rate in Pyrra briefly for image builds done](https://pyrra.gitpod.io/objectives?expr={__name__=%22workspace-imagebuild-buildsdone-success-ratio%22,%20namespace=%22monitoring-central%22,%20team=%22workspace%22}&grouping={}&from=1673297716785&to=1675716916785).
This new **GitpodImagebuildStartSuccess** would have fired once, on Jan 8, [when GCP was having scaling issues](https://gitpod.slack.com/archives/C01TNS8EVQT/p1673173223060219), and would have been correct to do so.
Also, removed the warnings, as Pyrra sends them now for SLOs to #team-workspace-alerts when error budgets …

[obs] Refactor alerts for image builds

---

components/BUILD.yaml

This PR removes the KOTS lint step from the build deps. This is currently causing main builds to fail. For more info, follow this [internal discussion
](https://gitpod.slack.com/archives/C032A46PWR0/p1676564142356829)
Fixes #
```release-note
NONE
```
No
<details>
</details>
<details>
</details>

Remove KOTS lint from main build deps

---

components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/suite_test.go
components/ws-manager-mk2/controllers/timeout_controller.go
components/ws-manager-mk2/controllers/timeout_controller_test.go
components/ws-manager-mk2/controllers/workspace_controller_test.go

Add tests for the timeout controller:
* Uses `ginkgo`'s `DescribeTable` to table-test specific timeout testcases
* Tests reconciliation requeue logic to periodically check for timeouts for each workspace
```
cd components/ws-manager-mk2
go test ./...
```
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[ws-manager-mk2] Timeout controller tests

---

components/dashboard/leeway.Dockerfile
components/ide-proxy/Dockerfile
components/proxy/Dockerfile

https://github.com/caddyserver/caddy/releases/tag/v2.6.4
```release-note
NONE
```
<details>
</details>
<details>
</details>

Update Caddy to address some memory regressions

---

operations/observability/mixins/meta/rules/server.yaml

See expression [grafana ](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%28increase%28gitpod_server_api_calls_total%7Bmethod%3D%5C%22startWorkspace%5C%22,%20statusCode%3D~%5C%225.%2A%5C%22%7D%5B1m%5D%29%29%20by%20%28method,%20statusCode%29%20%3E%205%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true,%22hide%22:false%7D,%7B%22refId%22:%22B%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22gitpod_ws_manager_bridge_workspace_instance_update_completed_seconds_count%22,%22legendFormat% …

[alert] Page on failing workspace starts

---

components/dashboard/src/App.tsx
components/dashboard/src/app/AppRoutes.tsx
components/dashboard/src/contexts/FeatureFlagContext.tsx
components/dashboard/src/projects/NewProject.tsx
components/dashboard/src/projects/Project.tsx
components/dashboard/src/projects/ProjectListItem.tsx
components/dashboard/src/projects/Projects.tsx
components/dashboard/src/projects/projects.routes.ts
components/dashboard/src/start/CreateWorkspace.tsx
components/dashboard/src/workspaces/CreateWorkspacePage.tsx
components/dashboard/src/workspaces/start-workspace-modal-context.tsx
components/server/src/gitlab/gitlab-file-provider.spec.ts

Introduces a new CreateWorkspacePage on which the options are shown and can be changed.
The page is only activated for users who are in team-only mode already (change your email to `toa@gitpod.io` in user settings and reload the dashboard to activate it). There is also a feature flag that can enable it for other users (currently false everywhere). 
This also moves /new to /projects/new so /new can be used for creating new workspaces.
**Without the feature flag there will be no difference in starting workspaces, with one exception: `/new` works for everybody**
Fixes #16362
1) Try starting workspaces in different ways. Should all work as usual.
2) Change the user email to `toa@gitpod.io` and reload the browser to active org only attribution.
3) All workspace creations now go to a new create …

[dashboard] Always start with options

---

WORKSPACE.yaml
install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/workspace/ide/constants.go

https://github.com/gitpod-io/openvscode-server/commit/fe9b682a4c73aa60ca263898c604f782a5447fd9
Bring encryption to browser code tokens
commit hash from https://werft.gitpod-dev.com/job/gitpod-build-hw-code-stable.6/results
Fixes https://github.com/gitpod-io/security/issues/121
Tested here https://github.com/gitpod-io/gitpod/pull/16404
```release-note
NONE
```
<details>
</details>
<details>
</details>
Valid …

Update browser code

---

components/supervisor/frontend/src/ide/supervisor-service-client.ts
components/supervisor/frontend/src/index.ts

[supervisor-frontend] only send heartbeat when logged user is owner
Fixes #
1. start a workspace in this preview environment
2. check heartbeat is working
3. share this workspace
4. use another user to open this shared workspace
5. check network, it should not send heartbeat
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[supervisor-frontend] only send heartbeat when logged user is owner

---

components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go

Gitpod dedicated uses multiple NVME drives.
```release-note
NONE
```
<details>
</details>
<details>
</details>

Apply I/O limiting to all nvme drivers

---

.github/workflows/build.yml

CI=true is a var set by GHA. Unsetting it for the build, [as yarn builds treat warnings as errors if that var is set to true](https://github.com/gitpod-io/gitpod/actions/runs/4202509092)
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

Unset CI for leeway build

---

components/supervisor/pkg/config/gitpod-config.go

This reverts commit 224077d6569960e643c553d916cd45cf7d8b3f2c.
It seems to break watch readiness contract, since we always report it now before event trying to watch. I suggest we revert, and then someone can find a better way with less noisy logging.
See internal discussion: https://gitpod.slack.com/archives/C01KGM9BH54/p1676644967865359
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details> …

Revert "[supervisor] improve config watch logging"

---

dev/preview/workflow/preview/preview.sh

Adds a default value for `DB_HOST` to make `leeway run dev:preview` work again.
```bash
```
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dev:preview] Add DB_HOST default

---

components/blobserve/go.mod
components/blobserve/go.sum
components/common-go/go-update-wc-deps.sh
components/ide-service/go.mod
components/ide-service/go.sum
components/image-builder-bob/go.mod
components/image-builder-bob/go.sum
components/image-builder-mk3/go.mod
components/image-builder-mk3/go.sum
components/registry-facade/go.mod
components/registry-facade/go.sum
components/ws-daemon/go.mod
components/ws-daemon/go.sum
components/ws-daemon/seccomp-profile-installer/go.mod
components/ws-daemon/seccomp-profile-installer/go.sum
install/installer/go.mod
install/installer/go.sum

We update buildkit, and containerd almost weekly, hence the convenience script to do updates.
Updates:
* `buildkit` v0.11.2 -> v0.11.3
* `containerd` v1.6.16 -> v1.6.18
Fixes # n/a
```
cd components/common-go
./go-update-wc-deps.sh
```
[Workspace integration tests pass](https://werft.gitpod-dev.com/job/gitpod-build-kylos101-gen88.3).
```release-note
NONE
```
<details>
</details>
<details>
</details>
Valid options …

Update dependencies for workspace cluster generation 88

---

components/docker-up/docker-up/main.go
components/ws-daemon/nsinsider/main.go

[workspace] change iface name to eth0
part of #16363
Fixes #
Test in #16363
```release-note
NONE
```
<details>
</details>
<details>
</details>

[workspace] change iface name to eth0

---

components/gitpod-cli/cmd/env.go
components/gitpod-cli/pkg/supervisor/client.go
components/gitpod-protocol/go/gitpod-service.go
components/gitpod-protocol/go/mock.go
components/gitpod-protocol/src/gitpod-service.ts
components/gitpod-protocol/src/protocol.ts
components/server/ee/src/prebuilds/prebuild-manager.ts
components/server/src/auth/rate-limiter.ts
components/server/src/container-module.ts
components/server/src/workspace/env-var-service.spec.ts
components/server/src/workspace/env-var-service.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/workspace-starter.ts

`gp env` reflects workspace env vars, not only user env vars, i.e. as well coming from projects and context URL.
fix #12208
```release-note
`gp env` reflects workspace env vars, not only user env vars, i.e. as well coming from projects and context URL.
```
<details>
</details>
<details>
</details>

gp env to respect workspace env vars

---

components/dashboard/src/contexts/FeatureFlagContext.tsx

Just adds the feature flag. No use of it in this PR.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] add switchToPAYG feature flag

---

components/gitpod-cli/cmd/rebuild.go
components/supervisor/local-hot-swap.sh
components/supervisor/pkg/supervisor/services.go

- REPO_ROOT should point to the checkout location
- THEIA_WORKSPACE_ROOT should point to the workspace location from .gitpod.yml
Fixes #
You can see it is broken by running `gp rebuild` for gitpod-io/gitpod. With this PR it should work, i.e. open some repo, change `workspaceLocation` in .gitpod.yml and see whether it works with `gp rebuild`.
```release-note
NONE
```
<details>
</details>
<details>
</details>
Valid …

[rebuild] map workspace location properly

---

WORKSPACE.yaml
components/docker-up/BUILD.yaml
components/docker-up/dependencies.sh

Context: https://github.com/gitpod-io/gitpod/pull/16368#issuecomment-1437114679
The related Docker Compose release: https://github.com/gitpod-io/compose/releases/tag/v2.16.0-gitpod.0
Also, refactored source of truth for Docker Compose version to WORKSPACE.yaml for consistency and consideration when changing Docker version for the future.
Fixes # n/a
1. `docker-compose --version` matches https://github.com/gitpod-io/compose/releases/tag/v2.16.0-gitpod.0
2. https://github.com/gitpod-samples/template-docker-compose works in the preview environment (you should see image pulls and containers running)
3. `docker run hello-world` works
```release-note
NONE
``` …

[docker-up] update Docker Compose

---

components/gitpod-protocol/src/protocol.ts

Adding a few new optional profile fields that we'll collect during some upcoming onboarding flow changes.
* `companyWebsite` We'll be asking for a user's company website instead of company. Rather than re-purposing `company`, creating a new field as we experiment here.
* `jobRole` This will be a response to us asking what a user's role is at their job. It will be a string value that we'll map to a list of options, such as `frontend`, `backend`, data_analytics`, etc (actual list still tbd, but we'll keep this as a flexible string.
* `jobRoleOther` - When user selects "Other" as their jobRole, we'll allow them to optionally provide a freeform value here.
* `signupGoals` - This will be a response to us asking the user what they hope to accomplish when signing up with Gitpod. It will also be …

adding new profile fields for new onboarding flow

---

components/dashboard/src/app/AppRoutes.tsx
components/dashboard/src/contexts/FeatureFlagContext.tsx
components/dashboard/src/onboarding/UserOnboarding.tsx
components/dashboard/src/workspaces/Workspaces.tsx

Stubbing out a placeholder for the new onboarding flow. It's gated behind the `newSignupFlow` feature flag, which is off everywhere atm. When this is enabled, we'll also suppress existing onboarding flows, like IDE Selection, and Profile info nudging.
This PR shouldn't change any of the user experience.
* Login as a new user in the preview environment
* Verify you still see the IDE Selection after you login.
```release-note
NONE
```
<details>
</details>
<details>
</details> …

Prep for new onboarding flow

---

components/dashboard/src/AppNotifications.tsx
components/dashboard/src/teams/TeamBilling.tsx
components/dashboard/src/user-settings/ChargebeeTeams.tsx
components/dashboard/src/user-settings/Plans.tsx
components/gitpod-protocol/src/accounting-protocol.ts
components/gitpod-protocol/src/gitpod-service.ts
components/gitpod-protocol/src/plans.ts
components/server/ee/src/billing/billing-mode.ts
components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/reset-chargebee-test-subs.sh
components/server/src/workspace/gitpod-server-impl.ts

This PR introduces new app-level notifications by re-using and slightly extending the existing `getNotifications` mechanism.
Those are nudges to switch from old Chargebee:
- Personal Subscriptions
- owned Team Subscriptions
- (co-) owned Team Subscriptions 2
This is feature flagged mostly for piece of mind. :lotus_position: 
Fixes #
- Start [a workspace on this branch](https://gitpod.io/#https://github.com/gitpod-io/gitpod/pull/16490)
- get your user ID (from websocket responses, for instance)
- `cd components/server && USER_ID="" ./reset-chargebee-test-subs.sh`
- Notice the sticky notification following you on each page :heavy_check_mark: 
```release-note
add app-level notifications for switching to Pay-as-you-go
```
Experimental feature to run the build with GitHub Actions (and not in …

[dashboard, server] App-level notifications to switch to Pay-as-you-go

---

components/dashboard/src/AppNotifications.tsx

The old code worked with Ctrl+Click, but not without modifier. :see_no_evil: 
I opted to keep things simple, and always just use the plain link (instead of the router for relative URLs) and always open in the same tab. :lotus_position: 
I developed this using frontend injection bc preview envs don't work, so you have to trust me. :wink: 
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[dashboard] Fix link in notification

---

components/ws-daemon/pkg/controller/controller.go
components/ws-manager-mk2/controllers/timeout_controller.go
components/ws-manager-mk2/controllers/workspace_controller.go
operations/observability/mixins/workspace/dashboards/components/ws-manager-mk2.json

Add Grafana dashboard for mk2:
Mostly a copy of mk1's dashboard, with an additional "Controller Manager" section with controller metrics
Also filters out ws-manager-mk2 Pods from mk1's dashboard
Try in https://grafana.gitpod.io/d/-k3kIb14k/ws-manager-mk2-wip?orgId=1&refresh=30s&from=now-2d&to=now
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[ws-manager-mk2] Add Grafana dashboard

---

dev/preview/workflow/lib/k8s-util.sh
dev/preview/workflow/preview/deploy-gitpod.sh
dev/preview/workflow/preview/deploy-monitoring-satellite.sh

Apply gitpod/monitoring-satellite resources only if there's a diff with the one in the cluster. Fixes some issues where resources exist when applied twice, and also should speed up the process somewhat
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[preview] Apply gitpod/monitoring-satellite resources if there's diff

---

components/gitpod-messagebus/src/messagebus.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/messagebus-integration.ts

Fixes https://github.com/gitpod-io/ops/issues/8409
```release-note
NONE
```
<details>
</details>
<details>
</details>

Reduce super-noisy traces

---

components/server/ee/src/workspace/gitpod-server-impl.ts

Related to: https://github.com/gitpod-io/ops/issues/8388
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Send users to "/switch-to-payg?..." if switchToPAYG is set

---

components/content-service/pkg/initializer/prebuild.go
components/content-service/pkg/initializer/snapshot.go

Fix error logs
```release-note
NONE
```
<details>
</details>
<details>
</details>

[content-service] Fix error logging

---

components/dashboard/src/projects/Project.tsx
components/dashboard/src/projects/ProjectListItem.tsx

Always Open Project Context URLs (i.e. Repository URL of GitHub/GitLab/Bitbucket URLs) in new tab to not loose context of Gitpod Dashboard.
Fixes #
- Go to `/projects` or `/projects/<YOUR_PROJECT_NAME>`
- Find your Repository URL & Click on it :smile:
```release-note
NONE
```
<details>
</details>
<details>
</details>
> …

[Dashboard] Open Project Context URLs in new tab

---

dev/ready-probe-labeler/main.go

While we wait for the readiness probe, ensure the node does not have the label.
```release-note
NONE
```
<details>
</details>
<details>
</details>

Improve ready probe labeler

---

install/installer/pkg/components/slowserver/deployment.go
install/installer/pkg/components/slowserver/render_test.go

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[installer] Fix slowserver replicas (to 1)

---

components/gitpod-cli/cmd/rebuild.go

We don't want to introduce a new naming for workspace in workspace. This PR removes `debug` workspace notion from the output
Fixes #
- Run `go run . rebuild` to test.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[rebuild] remove notion of debug workspace from output

---

operations/observability/mixins/workspace/dashboards.libsonnet

Forgot to import the dashboard 🤦 
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Import dashboard

---

dev/preview/infrastructure/modules/gce/cloudinit.yaml
dev/preview/workflow/preview/deploy-monitoring-satellite.sh

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[preview] Don't disable workspace-full prepull on gce vms

---

install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/workspace/ide/constants.go

This PR adds an experiment to improve discoverability of `gp rebuild` feature in VS Code interface:
- via a notification on save of .gitpod.yml or Dockerfile
- UI actions in code lenses, editor context and inline menus
[gitpod-code commit on master](https://github.com/gitpod-io/gitpod-code/commit/8612f777fb5c44227ca6f2b91f40fa0929637e22)
Fixes https://github.com/gitpod-io/gitpod/issues/16299
- Start a workspace and verify that you don't have new features.
- For fast startup you can use this context: https://github.com/akosyakov/parcel-demo/tree/tiny
- Enable `gitpod_experiments_rebuildHints` feature flag for your user in Configcat.
- Reload the window and verify that you have new features now.
```release-note
NONE
```
Experimental feature to run the build with GitHub Actions (and not in …

[gitpod-code] gp rebuild hints experiment

---

components/ws-daemon/pkg/controller/workspace_controller.go
components/ws-manager-api/go/crd/v1/workspace_types.go
components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/timeout_controller.go
components/ws-manager-mk2/controllers/timeout_controller_test.go
components/ws-manager-mk2/controllers/workspace_controller_test.go
components/ws-manager-mk2/service/manager.go

Remove `Headless` from the workspace status, and instead introduce a `IsHeadless()` function on the `Workspace` type which uses the spec to determine if it's headless. Fixes a race where the status might not yet be set after creation, causing `Headless` to be false
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Remove headless from status

---

install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/workspace/ide/constants.go

Related https://github.com/gitpod-io/gitpod/issues/16376#
1. Check port status bar distinguishes between public and private ports
```release-note
NONE
```
<details>
</details>
<details>
</details>

Update gitpod-web extension

---

components/gitpod-cli/cmd/init.go

Fix panic `gp init -i`
Related https://github.com/gitpod-io/gitpod/issues/16335
- Run `gp init -i` it should work
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gp-cli] fix gp init panic

---

components/dashboard/package.json
components/dashboard/src/app/AppRoutes.tsx
components/dashboard/src/contexts/ConfettiContext.tsx
components/dashboard/src/index.tsx
components/dashboard/src/onboarding/StepOrgInfo.tsx
components/dashboard/src/onboarding/UserOnboarding.tsx
yarn.lock

* Updates the `Company Website` input to accept any string that validates as a url and not use an `<input type="url"/>`, as it's more restrictive then we'd like. Also updated the placeholder to `example.com`
* Adds a `ConfettiContextProvider` to drop confetti on demand from any component. The end of the new onboarding flow drops confetti now with this change.
```ts
const { showConfetti } = useConfetti();
// walla, drop confetti
showConfetti();
```
Confetti will automatically hide after it's all been dropped. You can also manually hide it, or inspect the current status of it's it being shown via additional props returned from the `useConfetti()` hook.
```ts
const { isConfettiShowing, showConfetti, hideConfetti } = useConfetti();
```
* 2 new dependencies were added for this PR as well.
* …

Add confetti after new onboarding flow

---

components/server/ee/src/billing/billing-mode.spec.db.ts
components/server/ee/src/billing/billing-mode.ts

Fixes #
- start [a workspace](https://gitpod.io/#https://github.com/gitpod-io/gitpod/pull/16552)
- `leeway run components/gitpod-db:init-testdb`
- `(cd components/server && yarn db-test)`
```release-note
NONE
```
<details>
</details>
<details>
</details>

[payment] Adjust BillingMode for PAYG transition

---

operations/observability/mixins/workspace/dashboards/components/ws-manager-mk2.json

Add workqueue depth and workqueue work duration panels to the mk2 dashboard:
Work duration metrics aren't scraped yet but get enabled here: https://github.com/gitpod-io/ops/pull/8444
View here: https://grafana.gitpod.io/d/ws-manager-mk2/gitpod-component-ws-manager-mk2?orgId=1&from=now-30d&to=now
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[ws-manager-mk2] Add queue depth and work duration panels

---

components/gitpod-cli/cmd/rebuild.go
components/gitpod-cli/rebuild.sh
components/supervisor/.vscode/launch.json
components/supervisor/pkg/config/gitpod-config.go
components/supervisor/pkg/config/gitpod-config_analytics_test.go
components/supervisor/pkg/config/gitpod-config_test.go
components/supervisor/pkg/ports/ports-config_test.go
components/supervisor/pkg/supervisor/supervisor.go
components/supervisor/validate.sh
dev/ide/example/workspace/.gitpod.yml
dev/ide/example/workspace/Dockerfile

Adds `gitpod_image_file_changed` to report when gitpod Dockerfile is changed debounced by 5 secs.
fix https://github.com/gitpod-io/gitpod/issues/6898
Verify from sources:
- Run `components/supervisor/validate.sh --log trace` to start a workspace.
- In a new workspace change .gitpod.yml and Dockerfile.
- Inspect validate logs that changes are detected by file watchers and events are logged in 5 secs after last change is saved.
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[supervisor] analyze image file changes

---

components/gitpod-db/src/typeorm/migration/1677247435979-WorkspaceSessionIndexes.ts

Fixes #
- notice how the preview env gets deployed with migrations applied successfully.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[db] Add index workspace.ind_ownerId_type_creationTime

---

components/dashboard/src/service/service.tsx

See [internal chat](https://gitpod.slack.com/archives/C01KGM9BH54/p1677142029929329?thread_ts=1676985970.685469&cid=C01KGM9BH54)
Fixes #
No need
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] don't show connection status alert in iframe

---

components/gitpod-cli/cmd/rebuild.go
components/supervisor/pkg/supervisor/supervisor.go

[inner-loop] run Isolated docker in debug workspace
Fixes #
1. start a workspace preview env 
2. try `gp rebuild`
3. in debug workspace, try use docker, it should Isolated with regular workspace
```release-note
[inner-loop] run Isolated docker in debug workspace
```
<details>
</details>
<details>
</details>

[inner-loop] run Isolated docker in debug workspace

---

components/dashboard/src/user-settings/ProfileInformation.tsx

This drops the Company field from the User Profile form. We don't collect it anymore on signup, and it isn't something that we surface anywhere either.
Fixes #16560
* https://bmh-remove162dc12152.preview.gitpod-dev.com/user/account
* Open the user profile and ensure there's no Company input field
* Try and update your profile to make sure that works still.
```release-note
NONE
```
<details>
</details>
<details>
</details> …

Removing company input field from profile form

---

components/ee/payment-endpoint/src/github/subscription-mapper.ts
components/ee/payment-endpoint/src/github/subscription-reconciler.ts

For years already, we don't store "free" subscriptions in the DB anymore, but assume those implicitly - except for those synced from GitHub. This gets in our way now as we want to move to Pay-as-you-go ([epic](https://github.com/gitpod-io/ops/issues/8319)).
This PR stops the syncing of GitHub subscriptions of those plans. Next step afterwards is to remove them from the database.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[payment] GitHub: Ignore all "free tier" plans

---

components/ws-daemon/pkg/controller/workspace_operations.go
components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/workspace_controller.go

Note: This depends on https://github.com/gitpod-io/gitpod/pull/16471
Ensures that prebuilds can initialize successfully (before storage access was missing) and stopping successfully (by ensuring workspaces enter stopped phase once backup has been taken and deleting the prebuild pod so that workspace CR deletion can be performed)
n.a.
- Create project in [preview environment](https://fo-mk2-prebuilds.preview.gitpod-dev.com/)
- Start prebuild
- Prebuild should initialize and run successfully and enter stopped phase once completed. Afterwards the workspace CR should be deleted.
```release-note
None
```
<details>
</details> …

[ws-manager-mk2] Ensure prebuilds can start and stop

---

components/ws-manager-mk2/controllers/create.go

Fix workspace container detection. Depends on https://github.com/gitpod-io/gitpod/pull/16413. Without working workspace container detection resource constraints will not be applied to the workspace container.
n.a.
- Open workspace
- Perform [common runtime tests](https://www.notion.so/Common-runtime-tests-4e3b05c3b81e4ff6810572aee66ffad3)
```release-note
None
```
<details>
</details>
<details>
</details>
Valid …

[ws-manager-mk2] Fix workspace container detection

---

components/ws-manager-mk2/controllers/workspace_controller.go

Reduce duplicate delete pod calls
n.a.
n.a.
```release-note
None
```
#
<details>
</details>
<details>
</details>

[ws-manager-mk2] Reduce duplicate delete pod calls

---

components/dashboard/src/onboarding/UserOnboarding.tsx

Adds tracking for the `ide_configuration_changed` during onboarding. 
I intentionally avoided re-using the `updateUserIDEInfo()` function for now in `components/dashboard/src/user-settings/SelectIDE.tsx` as I'd like to shift to moving these kinds of api calls (and associated tracking) to react query mutations. I couldn't quite put this in a new mutation yet though, as there's some dependency on decoupling our onboarded logic check from an IDE being set, and also setting the new `onboardedTimestamp` value, but then we should be able to clean this up a bit.
* Run through the onboarding flow - https://bmh-onboarb9a608477f.preview.gitpod-dev.com/workspaces?onboarding=force
* Check Segment in the Staging Trusted source for the `ide_configuration_changed` event after you've completed …

Track ide changed event during onboarding

---

components/dashboard/src/onboarding/StepOrgInfo.tsx
components/dashboard/src/onboarding/exploration-reasons.ts
components/dashboard/src/onboarding/job-roles.ts
components/dashboard/src/onboarding/signup-goals.ts

Adjusting some of the copy on the final step of onboarding to help readability.
| I work in... | Overview |
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/367275/221313352-c34eb987-9a94-409e-88d4-b2d73c9e7f98.png) | ![image](https://user-images.githubusercontent.com/367275/221313218-26d83191-1199-41e6-a58a-bb98c1904206.png) |
* https://bmh-onboar95e6040ace.preview.gitpod-dev.com/workspaces?onboarding=force
* Check step 3 of the onboarding flow.
```release-note
NONE
```
<details>
</details>
<details> …

Adjusting onboarding copy for better readability

---

components/dashboard/src/data/workspaces/create-workspace-mutation.ts
components/dashboard/src/workspaces/CreateWorkspacePage.tsx

A few followup tasks from #16391 that added a new dedicated create workspace page. That page is still behind a flag, `start_with_options`, which is off everywhere. There were a few pieces of feedback on the initial review that this PR aims to address as an iteration.
* Shifts `createWorkspace` api call into a react query mutation. This allows us to drop tracking creating/error state manually.
* Handling closing of the existing workspaces modal (shifted it's rendering so it just overlays content instead of replacing too so it's less jarring)
* Adding "Cancel" button to existing workspaces modal for a consistent UX.
* Preview env: https://bmh-create09111b296b.preview.gitpod-dev.com/workspaces
* You'll need to have the `start_with_options` feature flag enabled for your user in non-prod.
* …

Followup Tasks for new Create Workspace page

---

components/ws-proxy/pkg/sshproxy/forward.go

[ssh-gateway] support stderr forward in shell session
Fixes #
1. start a workspace in preview env
2. copy ssh connection string
3. run `ssh 'workspaceId#ownerToken@host' 'ls ---- || sleep 2'`
4. it should be output stderr
```
ls: unrecognized option '----'
Try 'ls --help' for more information.
```
there still have issue if command too quick finish, gateway don't have enough time to forward message, but that not part for this PR, so add `sleep 2` to bypass this issue.
```release-note
[ssh-gateway] support stderr forward in shell session
```
<details>
</details>
<details>
Add desired …

[ssh-gateway] support stderr forward in shell session

---

.github/workflows/code-nightly.yml

Point code nightly to release branch
```release-note
NONE
```
<details>
</details>
<details>
</details>

[code] point code nightly to release branch

---

components/dashboard/src/onboarding/StepOrgInfo.tsx
components/dashboard/src/onboarding/company-size.ts
components/dashboard/src/onboarding/exploration-reasons.ts
components/gitpod-protocol/src/protocol.ts

Adding a `Company Size` question to the onboarding flow when a user selects their exploring `For work`.
* Adds `companySize` to user profile that we save, and send to Segment.
| overview | options |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/367275/221991819-ffe8479b-5abf-4526-9187-937c618dc151.png) | ![image](https://user-images.githubusercontent.com/367275/221991867-9cf514d8-1a60-46fd-8a50-195958329131.png)
* Go through the onboarding flow: `https://<tbd>.preview.gitpod-dev.com/workspaces`
* On Step 3, select "I'm exploring Gitpod" "For work"
* Ensure the Company size field shows up. You should not be able to submit w/o a value here if you select "For Work"
* Select a value
* Hit Continue
* You can verify your selection persisted by forcing the onboarding flow …

Adding a company size question to new user onboarding flow

---

components/server/ee/src/user/stripe-service.ts

Ensures the error returned is a UserError, rather than a ServerError. See [reported errors in grafana](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%28increase%28gitpod_server_api_calls_total%7Bmethod%3D%5C%22getStripePortalUrl%5C%22,%20statusCode%3D~%5C%225.%2A%5C%22%7D%5B10m%5D%29%29%20by%20%28statusCode%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-6h%22,%22to%22:%22now%22%7D%7D)
Fixes #
```release-note
NONE
``` …

[stripe] Return NotFound for non-existent attribution IDs

---

operations/observability/mixins/workspace/dashboards/components/ws-daemon.json
operations/observability/mixins/workspace/dashboards/components/ws-manager-mk2.json

* In the ws-manager-mk2 grafana dashboard, show workspace start failures:
* In the ws-daemon grafana dashboard, add panels for controller-manager metrics (similar to what's added to ws-manager-mk2):
n/a
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Show start failures in dashboard, show daemon ctrl metrics

---

components/ws-manager-api/go/crd/v1/workspace_types.go
components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml
components/ws-manager-mk2/controllers/workspace_controller.go

Finalise cleanup of headless field in status. Replaced by `workspace.IsHeadless()`
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Remove headless field

---

components/ws-manager-mk2/controllers/metrics.go
components/ws-manager-mk2/controllers/suite_test.go
components/ws-manager-mk2/controllers/workspace_controller.go
components/ws-manager-mk2/controllers/workspace_controller_test.go

- Refactor how metrics are recorded. Fixes some condition changes being ignored.
- Instead of only checking for metric updates on a workspace's phase change, now keep track of a struct per workspace that contains which conditions have been recorded, and diff on each reconcile. This ensures we notice a condition change even when the phase doesn't change 
- Add unit testing for metrics 
```
cd components/ws-manager-mk2
go test ./...
```
```release-note
NONE
```
<details>
</details>
<details> …

[ws-manager-mk2] Refactor metric collection and add tests

---

install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-workspace/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/common/toleration.go
install/installer/pkg/components/registry-facade/daemonset.go
install/installer/pkg/components/ws-daemon/daemonset.go

GPU support in dedicated runs in a separated node groups defined with taints to avoid scheduling workload not related to GPUs, avoiding the additional cost.
The additional tolerations in the daemonsets have no side effect with existing deployments.
```release-note
NONE
```
<details>
</details>
<details>
</details> …

Allow registry-facade and ws-daemon to run in dedicated GPU node pools

---

components/supervisor/pkg/serverapi/publicapi.go

See [grafana](https://grafana.gitpod.io/explore?orgId=1&left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%28grpc_client_handled_total%7Bgrpc_code%3D%5C%22PermissionDenied%5C%22,%20job%3D%5C%22ide-metrics%5C%22%7D%29%20by%20%28grpc_code,%20grpc_method%29%22,%22legendFormat%22:%22__auto%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D)
Those three increase are caused by three different workspaces. 
Fixes #
Find no way to test, we can approve to see if grafana goes well
[gcp log](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-02-28T08:35:09.76598702 …

[supervisor] instance update fatal if no permission

---

components/dashboard/src/onboarding/StepOrgInfo.tsx
components/dashboard/src/onboarding/company-size.ts

Updates the onboarding company size labels.
* Biggest callout, I noticed our label for `less than 50` was wrong, as it reads that it excludes 50. Rather than lengthen it to `less than or equal to 50`, figured I'd simplify the option labels some. I did opt to correct the value for that first option so it isn't incorrect as well, but this will mean a slight change in the value we're sending from the ~ 24 hours it was live where it equaled `less_than_50`, now it will be `1_to_50`
* https://bmh-companb28805c983.preview.gitpod-dev.com/workspaces?onboarding=force
* Check onboarding flow on preview environment, 
* Select `For work` for the `I'm exploring Gitpod...` question
* Ensure Company Size labels are updated
```release-note
NONE
```
Experimental feature to run the build with GitHub Actions …

Updating company size labels

---

components/dashboard/src/projects/ProjectSettings.tsx

Fixes a bug where Project Settings doesn't load sometimes. If you hard refresh the Project Settings page you would get a mostly white page, discovered in #16540. The bug was due to this page needing to use a new hook for finding the project vs. having it in context already.
Related to #16540
* https://bmh-projec87461fc221.preview.gitpod-dev.com/workspaces
* Create a project.
* Navigate to the Project Settings page.
* Hard refresh the page. It should load correctly now.
```release-note
Fixed a bug where the Project Settings page sometimes wouldn't load correctly.
```
<details>
</details>
<details> …

Pull project from useCurrentProject()

---

components/gitpod-protocol/src/messaging/error.ts
components/server/src/websocket/websocket-connection-manager.ts

* Log user errors as info, helps with filtering for actual system erorrs
* For non-specific errors, throw a generic server error rather than leaking error details
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Log user errors as info

---

components/gitpod-protocol/src/team-subscription-protocol.ts
components/server/ee/src/workspace/gitpod-server-impl.ts

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Only show notifications for not-cancelled subscriptions

---

components/dashboard/src/components/Header.tsx
components/dashboard/src/components/Separator.tsx
components/dashboard/src/index.css
components/dashboard/src/menu/Menu.tsx
components/dashboard/src/onboarding/UserOnboarding.tsx

This makes some updates to the top nav menu so it's more responsive, stems from a discussion @gtsiolis and I had about improving responsiveness. Main changes are:
* Gitpod Logo Hidden - Done to reduce the visual elements in the header for mobile. We probably have room for it if we want to keep it though.
* `Workspaces | Projects` menu items shifted down to their own row
* `Admin | Feedback` links moved into User Menu
| a | b |
|--|--|
| ![image](https://user-images.githubusercontent.com/367275/222014013-59a2a186-448e-4791-b860-75cceff9cce2.png) | ![image](https://user-images.githubusercontent.com/367275/222014076-bbe990f9-350f-4955-bea2-ee34a1fce036.png) |
Relates to #4050
* https://bmh-respon75dad9d5f5.preview.gitpod-dev.com/workspaces
* Load the preview in your browser, try adjust …

Making top nav menu responsive

---

components/ws-manager-mk2/controllers/create.go
components/ws-manager-mk2/controllers/workspace_controller.go
operations/observability/mixins/workspace/dashboards/components/ws-manager-mk2.json

Fixes an issue where, if the controller fails to increment and store `workspace.Status.PodStarts` upon creating the Pod (e.g. due to a conflict), the workspace will briefly re-create the Pod in the Stopped phase (as it believes the Pod hadn't been created yet).
Was caught by the metric tests failing in https://github.com/gitpod-io/gitpod/actions/runs/4302950638/jobs/7502085462, and reproduced locally by not incrementing PodStarts.
Fixed by retrying the PodStarts update on conflict
Part of #16247 
Run ws-manager-mk2 unit tests
```release-note
NONE
```
<details>
</details>
<details> …

[ws-manager-mk2] Fix race where pod gets recreated in Stopped phase

---

WORKSPACE.yaml
install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/workspace/ide/constants.go

Update Gitpod's VS Code Browser stable to `1.76.0`.
A part of #16587 
- Switch to VS Code Browser Insiders in user preferences.
```release-note
NONE
```

Update VS Code Browser to `1.76`

---

components/gitpod-protocol/src/gitpod-service.ts
components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/src/auth/rate-limiter.ts
components/server/src/workspace/gitpod-server-impl.ts

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Implement tsAddMembersToOrg

---

dev/preview/workflow/lib/k8s-util.sh
dev/preview/workflow/preview/deploy-gitpod.sh
dev/preview/workflow/preview/deploy-monitoring-satellite.sh

This reverts commit c487681a82436e31232b3b42e27ef9f3803d2c33.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

Revert "Apply gitpod resources if there's diff (#16517)"

---

.github/workflows/preview-env-check-regressions.yml
test/pkg/integration/workspace.go
test/tests/smoke-test/main_test.go
test/tests/smoke-test/smoke_test.go

We want to improve gitpod to be more reliable, in case someone changes the common path, but does not verify, we want to run a simple smoke test for each successful main build
This test only contains
- start a private repo workspace with image build and stop it.
Part of #16196
1. go to [github action](https://github.com/gitpod-io/gitpod/actions/workflows/preview-env-check-regressions.yml) , run this action from this branch
2. make sure the test is pass.
e.g. https://github.com/gitpod-io/gitpod/actions/runs/4253507307
FYI, I change some code for wait image build, and already run integration test for workspace and ide, make sure it don't break anything (some failed are expected)
```release-note
NONE
``` …

happy smoke test

---

.github/workflows/preview-env-check-regressions.yml

[github-action] fix rebase misstake
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[github-action] fix rebase misstake

---

components/dashboard/src/user-settings/Preferences.tsx
components/gitpod-protocol/src/gitpod-service.ts
components/gitpod-protocol/src/protocol.ts
components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/src/auth/rate-limiter.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/workspace-starter.ts

[dashboard, server] Add global custom timeout preference
Closes https://github.com/gitpod-io/gitpod/issues/16200
1. try enabling billing with your account, otherwise custom workspace timeout will disabled.
2. setting custom timeout in preference
3. start a workspace, use `kubectl describe pod ws-{instanceID}` to check your workspace timeout and closed timeout.
```
annotations `gitpod/customTimeout` is your workspace timeout.
```
```release-note
[dashboard, server] Add global custom timeout preference
```
<details>
</details>
<details> …

[dashboard, server] Add global custom timeout preference

---

install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/kind-webapp/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/redis/deployment.go

Fixes #
Redis reaches ready in preview
```release-note
NONE
```
<details>
</details>
<details>
</details>

[redis] Fix readiness probe (again)

---

components/ws-daemon/pkg/container/containerd.go
install/installer/cmd/config_files_containerd.go
install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/kind-webapp/output.golden
install/installer/cmd/testdata/render/kind-workspace/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/ws-daemon/configmap.go
install/installer/pkg/components/ws-daemon/daemonset.go
install/installer/pkg/config/v1/config.go
install/installer/pkg/containerd/k3s.go
install/installer/pkg/containerd/location.go

Mounting only the socket makes ws-daemon unavailable if containerd restarts:
- [current behavior](https://www.loom.com/share/9e750f927d8c4a11a30414c05c18bfa9)
- [with the change](https://www.loom.com/share/d1b6206c89474bbfb5e857bc36b75f30)
Fixes https://github.com/gitpod-io/gitpod-dedicated/issues/874
- Restart `containerd` and check` ws-daemon` stays in ready
- Kill `ws-daemon` pod, and while is still starting, restart containerd. Check the pod to get ready state and not crash loop:
```
kubectl delete pods --force -l component=ws-daemon;sleep 2; \
systemctl restart containerd;sleep 5; \
kubectl logs -l component=ws-daemon -c ws-daemon -f
```
- Workspaces should open after the previous test
```release-note
NONE
```
Experimental feature to run the build with …

[ws-daemon] Check connection to containerd socket

---

.github/CODEOWNERS

In the interest of reducing unnecessary required PR reviews form SID I'd like to remove us as the default owners of `install/installer`
A recent example PR is https://github.com/gitpod-io/gitpod/pull/16633 where `install/installer/pkg/common` was changed. There are no explicit CODEOWNERS for  that folder, so i falls back to the owner of `install/installer` which is us. 
We could add an entry of `install/installer/pkg/common <blank>` to CODEOWNERS to remove us, but I'd rather remove us as the default owner so we don't have to list ever current (and future) folder in install/installer where we have shared ownership.
N/A
N/A
```release-note
NONE
``` …

Remove SID as default owner of installer/installer

---

components/dashboard/src/user-settings/AuthEntryItem.tsx
components/dashboard/src/user-settings/IntegrationItemEntry.tsx
components/dashboard/src/user-settings/Integrations.tsx

The below issues propose improvement for the UX of Integration Settings, by keeping the hovered effect ( the background colors ) of the workspace items till the ItemOverflowMenu is expanded. Please refer the below graphics for reference of the improvement.
https://user-images.githubusercontent.com/72302948/222713089-d453bd89-33c0-48fc-9902-f66cf17aa8d4.mov
Fixes #4635 
- Change your directory from /gitpod to /gitpod/component/dashboard
- Add your host and token as given in the readme
- Start the development server by yarn run start and check on http://localhost:3000 for checking the dashboard
```release-note
Added `Auth Entry Component` along with `Integration Entry Component` linking with `Integrations.tsx` and associated it with Item List Context Menu, with ChangeMenuState Function, to …
```

fix: Improved Integrations UX

---

components/server/ee/src/workspace/gitpod-server-impl.ts

Fixes https://github.com/gitpod-io/ops/issues/8388
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Polish notification texts

---

.github/workflows/preview-env-check-regressions.yml

[integration-test] only send slack notification when test is failure
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[integration-test] only send slack notification when test is failure

---

components/server/src/express-util.ts
components/server/src/server.ts

The follow logs are always logged in pairs. We reduce the verbosity of one, and attach the origin as structured data on the log.
```
Origin header check not applied because of empty Origin header! 
Websocket connection attempt with non-matching Origin header: ...
```
There are [4.5M occurrences of the former](https://console.cloud.google.com/errors?referrer=search&project=gitpod-191109)
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
If …

[server] Log empty origin header in debug, attach origin to other log

---

components/server/src/github/file-provider.ts

[See logs here](https://console.cloud.google.com/logs/query;query=resource.labels.pod_name%20:%20%2528%22server%22%2529%0A%22unexpected%20response%20typ%22;timeRange=PT1H;cursorTimestamp=2023-03-02T11:21:29.807Z?authuser=0&project=gitpod-191109)
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[github] Improve log entries when retrieving github files

---

components/dashboard/src/components/ErrorBoundary.tsx
components/dashboard/src/workspaces/Workspaces.tsx
components/gitpod-protocol/src/gitpod-service.ts
components/server/src/auth/rate-limiter.ts
components/server/src/prometheus-metrics.ts
components/server/src/workspace/gitpod-server-impl.ts

Adding a method for the dashbaord to report an error boundary via a new `reportErrorBoundary` rpc method. Internaly it:
* does a `log.info()` call w/ some metadata about the error (`url`, `message` and `userId`)
* increments a new prometheus counter, `gitpod_dashboard_error_boundary_total`, which has a `url` label.
I was able to manually test this by forwarding the metrics server port to my workspace, and curl'ing the `/metrics` endpoint (hat-tip @geropl for the pointer).
```
kubectl port-forward deployment/server 9500 &
```
```
curl localhost:9500/metrics
```
After manually "breaking" it a few times by injecting some code that throws errors in a component render, was able to see the counters increment, and verify the `url` label is set as expected.
``` …
```

Report ErrorBoundary from Dashboard

---

components/gitpod-protocol/src/gitpod-service.ts
components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/src/auth/rate-limiter.ts
components/server/src/workspace/gitpod-server-impl.ts

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Implement cancelTeamSubscription

---

components/server/ee/src/prebuilds/github-app.ts

Avoid logging prebuild errors which are caused by legacy prebuild setup as errors
[See errors here](https://console.cloud.google.com/logs/query;query=resource.labels.pod_name%20:%20%2528%22server%22%2529%0A%22Running%20prebuilds%20without%20a%20project%20is%20no%20longer%20supported.%22;timeRange=PT1H;cursorTimestamp=2023-03-02T11:03:31.770Z?authuser=0&project=gitpod-191109)
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[prebuild] Log github app user errors as info

---

components/ws-manager-mk2/controllers/workspace_controller.go
components/ws-manager-mk2/controllers/workspace_controller_test.go
components/ws-manager-mk2/service/manager.go
install/installer/pkg/components/ws-manager-mk2/role.go

Protect environment secrets
n.a.
- Set environment variable in user preferences
- Create workspace
- Check that workspace CR contains reference to the secret
- Check that secret is deleted after workspace has started
- Check environment variables in workspace
```release-note
None
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Protect environment secrets

---

install/installer/pkg/components/image-builder-mk3-wsman/deployment.go

Fixes preview environments not getting ready because image cannot be pulled
n.a.
- Create preview environment. It should get ready.
```release-note
None
```
<details>
</details>
<details>
</details>

[image-builder] Set correct image name

---

components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/workspace_controller.go
components/ws-manager-mk2/main.go
dev/loadgen/pkg/loadgen/executor.go
dev/loadgen/pkg/observer/success.go

* Enable tracing for ws-manager-mk2
* Add additional (debug) logging
View ws-manager-mk2 traces in EU jaeger instance. Deployed and tested from an ephemeral cluster
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Enable tracing, add debug logs

---

components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/service/manager.go
install/installer/pkg/components/ws-manager-mk2/configmap.go

Fixes the first reconciliation of a workspace setting its phase to `Stopped` briefly, because there are 0 pods and no ContentReady condition, so `isDisposalFinished()` was returning true. Now only check for `isDisposalFinished` if in a `Stopping` state, so we don't transition to `Stopped` for a tick after workspace creation
Run unit tests, or create a workspace and observe the debug logs from the controller not setting the workspace status to Stopped in the first reconciliation
```release-note
NONE
```
<details>
</details>
<details> …

[ws-manager-mk2] Fix stopped status

---

components/dashboard/src/AppNotifications.tsx
components/dashboard/src/SwitchToPAYG.tsx
components/dashboard/src/app/AppRoutes.tsx
components/dashboard/src/components/org-icon/OrgIcon.tsx
components/dashboard/src/menu/OrganizationSelector.tsx
components/server/ee/src/workspace/gitpod-server-impl.ts

Changes:
- made re-entry safe
- check: old subscription already cancelled
- check: stripe subscription already exists
- cancel all kinds of subscriptions
- migrate members for TeamSubscription
- choose org for TeamSubscription
- don't show notification on PAYG page
- show confetti at the end :-)
Fixes https://github.com/gitpod-io/ops/issues/8564
```release-note
NONE
```
<details>
</details>
<details>
</details> …

Switch to Pay-as-you-go

---

components/ws-manager-api/go/crd/v1/workspace_types.go
components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml

Add validation on the duration field. The `format=duration` annotation is too lenient and still accepts some duration formats that can't be parsed by `time.ParseDuration`, so instead we can set a regex as described in https://github.com/kubernetes/apiextensions-apiserver/issues/56
Fixes an invalid duration breaking the controller list/watch, stopping reconciliation of all workspace resources.
In a preview env:
- `gp set timeout 2h`, try for various timeout values/units, and observe all succeed
- `kubectl edit workspace <name>` and manually set an invalid timeout value in `spec.timeout.time`, and check that the update gets rejected by the API server
```release-note
NONE
``` …

[ws-manager-mk2] Add duration validation

---

install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/workspace/ide/constants.go

bump up gitpod-code to pick up fixes for rebuild hints
- GH action: https://github.com/gitpod-io/gitpod-code/actions/runs/4346862414
Fixes #
- You can test it by starting a workspace on gitpod.io from a commit associated with GH action, then configured couple teams on gitpod.io and check that you still have hints.
- In preview envs you should not have any hints by default.
```release-note
NONE
```
<details>
</details>
<details>
</details> …

bump up gitpod-code to pick up fixes for rebuild hints

---

components/gitpod-cli/cmd/git-track-command.go

instead of workspaceInstanceId to allow cross events matching in Mixpanel
Fixes #
- Run validate.sh from components/supervisor
- In started workspace use git push/fetch etc.
- Open Mixpanel for Gitpod go to Events view and filter out by `git_comman` event with `instanceId` property matching to instance id from `gp info`. 
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[gp] track git event with instanceId

---

components/server/src/auth/rate-limiter.ts

The sendHartbeat was in the default bucket, which means it added to a limit of 60,000 calls per user minute. This PR changes it to 10 calls per minute per user. Reduces the amount of allowed heartbeat calls to 10 per minute per user
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] lower the heartbeat limit

---

components/ws-manager/pkg/manager/pod_controller.go

Use context from the reconciler
```release-note
NONE
```
<details>
</details>
<details>
</details>

Reuse context from the reconciler

---

components/registry-facade/cmd/setup.go

Temporal solution for dedicated. The issue is related to the installer with the field `customCACertificates` and what `registry-facade` uses as CA.
```release-note
NONE
```
<details>
</details>
<details>
</details>

Update containerd self-signed certificate configuration

---

components/server/src/auth/rate-limiter.ts

Fixes a typo
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] fix typo in rate limiter

---

components/dashboard/src/data/current-user/may-set-timeout-query.ts
components/dashboard/src/user-settings/Preferences.tsx

Making a few updates and some cleanup for the User Preferences page.
* Pulling the result of if a user may set a timeout into react-query so it's cached
* Wrap Dotfiles and Timeout inputs w/ forms - allows enter key to submit
* Drop in new Button components
* Fix how we update when setting `dotfilesRepo` so we don't mutate state directly
* Go to the User Preferences page
* Try setting and clearing your dotfiles repo
* Try setting and clearing a custom timeout
```release-note
NONE
```
<details>
</details>
<details> …

User Preferences page cleanup

---

components/ide-metrics-api/go/config/config.go
components/ide-metrics/config-example.json
components/ide-metrics/pkg/server/server.go
components/ide-metrics/pkg/server/server_test.go
components/supervisor/pkg/metrics/reporter.go
install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/ide-metrics/configmap.go

Add `x-client` a global setting in ide-metrics
Fixes #
Check also test results https://github.com/gitpod-io/gitpod/pull/16701#issuecomment-1457867144
- Open workspace in preview env https://hw-metrics-client.preview.gitpod-dev.com/workspaces
- `ide-metrics` in preview env should correctly setup `metric_client` for supervisor public api metrics
**debug mode**
- Exec commands below
```
cd components/ide-metrics
go run main.go run --config config-example.json --json-log=false --verbose
curl -X "POST" "http://localhost:3000/metrics-api/metrics/counter/add/gitpod_test_counter" \
-H 'x-client: vscode' \
-H 'Content-Type: application/json; charset=utf-8' 
```
- `/metrics` endpoint at port 9500 should have `metric_client` field with vscode
```release-note
NONE
``` …

Add `x-client` in ide-metrics component

---

components/ws-daemon/pkg/controller/workspace_controller.go
components/ws-daemon/pkg/controller/workspace_operations.go
components/ws-manager-mk2/service/manager.go

- Change the snapshot name to be in the format snapshot-[timestamp].tar as was the case with mk1
- During prebuild updates ws-manager-mk2 sends an empty boolean if no condition is set (e.g. for aborted). On ws-manager-bridge in Typescript this is interpreted as true :grimacing:  which leads to ws-manager-bridge thinking that the prebuild has been aborted even though that is not the case
- ws-manager-bridge uses the stopping phase to determine the status of the prebuild and ignores updates for the stopped phase. This means we need to set the snapshot url during the stopping phase otherwise ws-manager-bridge does not register that the snapshot url is available
n.a.
- Start prebuild in [preview environment](https://fo-mk2-preca90815df7.preview.gitpod-dev.com/workspaces) …

[ws-manager-mk2] Fix prebuild update events

---

.github/workflows/build.yml

Tidy up the build, and skip job if pr got edited, but there were no checkbox changes
[Job that got skipped](https://github.com/gitpod-io/gitpod/actions/runs/4262912120)
No issue, pulling changes from a bigger PR so it's easier to review later.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gha] tidy up the build, and skip job if pr got edited, but there were no checkbox changes

---

components/supervisor/frontend/src/ide/supervisor-service-client.ts

[supervisor-frontend] only wait supervisor close in debug workspace
and if workspace already stopped, it actually return 302, this PR also add this condition, otherwise, if browser not receive 502 and workspace already closed, it will retry every 1 sec.
Fixes #
1. open a workspace in preview env
2. check network it should not have `supervisor/willShutdown/true` api call in regular workspace
3. try `gp rebuild` it should be work as before
```release-note
NONE
```
<details>
</details>
<details>
</details>
If …

[supervisor-frontend] only wait supervisor close in debug workspace

---

components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
components/dashboard/src/components/UsageBasedBillingConfig.tsx
components/dashboard/src/components/UsageView.tsx
components/dashboard/src/data/workspaces/workspace-classes-query.ts
components/dashboard/src/user-settings/selectClass.tsx

Cache the supportedWorkspaceClasses on the client
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] cache get SupportedWorkspaceClasses

---

.github/workflows/code-nightly.yml

```release-note
NONE
```
<details>
</details>
<details>
</details>

[code] Point back to main branch

---

components/public-api-server/pkg/apiv1/identityprovider_test.go

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[public-api] Fix GetIDToken test

---

.github/CODEOWNERS

Currently (if my understanding of basic algebra is correct), our [`CODEOWNERS` section](https://github.com/gitpod-io/gitpod/blob/main/.github/CODEOWNERS#L118) for GitHub Action workflows only catches one file - https://github.com/gitpod-io/gitpod/blob/main/.github/workflows/ide-integration-tests.yml. This PR includes the rest that we own
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details> …

Add missing IDE GH Actions to `CODEOWNERS`

---

.github/workflows/comment-ops.yaml

* Fix typo in the dispatched workflow
* Update the comment, instead of adding a new one
* Only trigger if `recreate-vm` is in the comment
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gha] fix comment ops

---

.github/workflows/comment-ops.yaml

`gh` is not available in the self-hosted runner 🙄 
instead of installing it or including it in the runner's image, use the api to grab the run id.
also 🤮 
```
await new Promise(r => setTimeout(r, 5000));
```
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gha] fix comment ops gh url

---

.github/workflows/comment-ops.yaml

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gha] fix comment ops p4

---

.github/pull_request_template.md
.github/workflows/build.yml
.werft/build.ts
.werft/jobs/build/job-config.ts

Enable GHA by default, with werft as an additional option.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gha] enable gha build by default

---

.github/workflows/build.yml

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

fix gha build-gitpod

---

components/dashboard/src/SwitchToPAYG.tsx

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[switch-to-payg] Fix cancellation call for TS2

---

components/dashboard/src/Pagination/Pagination.tsx
components/dashboard/src/components/UsageView.tsx
components/dashboard/src/data/usage/usage-query.ts

Fixes a bug where when on the usage view we send the same request every second and also moves the usage fetching to a react query that is cached 10 mins.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] cache usage queries

---

install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/kind-webapp/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/redis/constants.go
install/installer/pkg/components/redis/deployment.go

Adds a prometheus-exporter as a sidecar to the redis deployment
Fixes #
Both redis, and the exporter sidecar come up in preview
```release-note
NONE
```
<details>
</details>
<details>
</details>

[redis] Add prometheus exporter

---

install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/kind-webapp/output.golden
install/installer/cmd/testdata/render/kind-workspace/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/common/common.go

Adds env variable configuration for OpenTelemetry. Most config options are 1-1 mapped with the distinction on Username/Password authentication. Given we use a OTEL Collector in SaaS, we don't need to (and indeed do not) set these anyway.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

[installer] Add OpenTelemetry env variables to tracing

---

components/dashboard/src/teams/Members.tsx

Fixes a bug that I introduced recently, where as an woner I could not leave an org anymore. This should only be the case if Im the sole owner of the org.
Fixes #16753
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] remaining owner cannot leave org

---

.github/workflows/build.yml

What it says on the tin.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gha] don't build preview on main

---

.werft/workspace-run-integration-tests.sh

W/o this change, it tries using GHA and fails.
This is a short term change to unblock our release. Later this week or early next we'll migrate to Github Actions (once the secrets are added to the mono repo).
Fixes # n/a
Trigger tests using the werft CLI via this branch like so:
```
./.werft/workspace-run-integration-tests.yaml \
> -a with-integration-tests=workspace \
> -a with-large-vm=true \
> -a with-gce-vm=true \
> -a with-werft=true
```
Example: https://werft.gitpod-dev.com/job/gitpod-custom-kylos101-werft-wk-int-tests.0/raw
```release-note
NONE
```
<details>
</details>
<details>
Add desired feature flags to the end …

[tests] continue running workspace integ tests on werft for the short term

---

WORKSPACE.yaml
install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/workspace/ide/constants.go

This PR aligns CSP policies between workspaces started regularly and via gp rebuild to allow redirection to arbitrary custom schemes.
When VS Code Server is running from sources it has very strict CSP policies, i.e. with gp rebuild. Regular workspace though does not have any. The trouble with CSP policies that they should specify exactly which custom schemes are supported. In our case we don't actually know them in advance since IDEs can change.
Fixes #
- Run components/supervisor/validate.sh
- In opened workspace that actions `Open With VS Code Desktop` are working now.
Important: It does not add support of opening VS Code Desktop as default IDE!
```release-note
NONE
``` …

[rebuild] fix open with VS Code Desktop actions

---

components/dashboard/src/data/workspaces/resolve-context-query.ts
components/dashboard/src/workspaces/CreateWorkspacePage.tsx
components/gitpod-protocol/src/gitpod-service.ts
components/server/src/auth/rate-limiter.ts
components/server/src/workspace/gitpod-server-impl.ts

The new workspace page now resolves the given contextURl and uses the resulting context to lookup the project and preselect the right workspace class.
Going forward we can display more information from the context object and the project.
Fixes #16727
- Configure a project and choose a small workspace size for its workspaces.
- try starting a workspace on that project and verify that the new workspace page has the small workspace class preselected
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[dashboard] make new workspace aware of project

---

components/server/src/config.ts
components/server/src/user/user-controller.ts
install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/kind-webapp/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/server/configmap.go
install/installer/pkg/components/server/constants.go
install/installer/pkg/components/server/deployment.go
install/installer/pkg/components/server/types.go

We mount the `admin-credentials` secret onto server, and provide the file path. If that secret does not exist, we do not fail (marked as optional) and the login-as-admin feature remains disabled.
* Part of https://github.com/gitpod-io/gitpod/issues/16223
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Mount admin-credentials 

---

components/dashboard/src/teams/Members.tsx

replaced "no members found" with a spinner
Replaced the "no members found" with a spinner
Fixes #16241
```release-note
Show loading spinner when fetching organization members
```

Show loading spinner when loading team members

---

components/supervisor/pkg/serverapi/publicapi.go

There is no support for TLSv1.3 in dedicated.
` Err: connection error: desc = \"transport: authentication handshake failed: tls: server selected unsupported protocol version 303\"","serviceContext":`
```release-note
NONE
```
<details>
</details>
<details>
</details>

Allow TLS v1.2

---

components/dashboard/src/user-settings/PageWithSettingsSubMenu.tsx

Ensures the settings menu gets rerendered when the dependent state changes.
Fixes #
ensure the billing menu is shown in user settings
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] fix missing billing entry

---

components/ws-manager-api/go/config/config.go
components/ws-manager-mk2/controllers/maintenance_controller.go
components/ws-manager-mk2/controllers/suite_test.go
components/ws-manager-mk2/controllers/workspace_controller.go
components/ws-manager-mk2/main.go
components/ws-manager-mk2/pkg/maintenance/maintenance.go
components/ws-manager-mk2/service/manager.go
install/installer/pkg/components/ws-manager-mk2/configmap.go
install/installer/pkg/components/ws-manager-mk2/constants.go

Add maintenance mode for ws-manager-mk2:
* Create `ws-manager-mk2-maintenance-mode` ConfigMap, which contains a boolean that enables/disables maintenance mode.
* This ConfigMap is deployed by the installer
* Create a new maintenance `reconciler` that watches this ConfigMap for changes, and keeps track of whether maintenance mode is enabled
* The controller manager only watches the maintenance ConfigMap events using a label filter
* The API service returns `FailedPrecondition` on the following requests when maintenance mode is enabled:
* `StartWorkspace`
* `StopWorkspace`
* `TakeSnapshot`
* The workspace reconciler stops reconciling in maintenance mode, to prevent starting a workspace shutdown and triggering a backup
* Any events during maintenance mode get requeued after a minute, such …

[ws-manager-mk2] Maintenance mode

---

.github/workflows/build.yml

What it says
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gha] fix concurrency groups and preview name for multiple events

---

components/dashboard/src/workspaces/CreateWorkspacePage.tsx

Keeps the button state disabled when a workspace was started, so that user's canot start multiple workspaces by clicking multiple times.
Fixes #16752
Try creating more than one workspace from within the create workspace page by hammering any of the "Create Workspace" buttons.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] keep start button disabled

---

components/server/ee/src/workspace/gitpod-server-impl.ts

When following the link to `Switch to pay-as-you-go` here ...
... the Org context is changed accordingly, see 
Fixes #16776
1. create a couple of Orgs
2. use the `/components/server/reset-chargebee-test-subs.sh` script (needs proper kubectx) and create a TS2 setup of one of the Orgs
3. switch context to the other Org
4. check that the notification's URL includes the `org` param
5. see that the context is switch to the target Org
```release-note
NONE
```
<details>
</details>
<details>
</details>
If enabled …

[Switch to PAYG] Switch Org context for TS2 links

---

components/dashboard/src/components/UsageLimitReachedModal.tsx
components/dashboard/src/workspaces/CreateWorkspacePage.tsx

Allow closing the limit reached modal when starting a workspace from the new create workspace page.
Fixes #
create an org without credits and try starting a workspace within. See a dialog telling you about limit reached and try closing it.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] closeable limit-reached-modal

---

components/dashboard/src/App.tsx
components/dashboard/src/data/organizations/orgs-query.ts
components/dashboard/src/data/setup.tsx

Excludes the orgs query from being cached across reloads.
Fixes #16743
Create an org invite someone, when they have joined reload the members page and verify that the members list is correct
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] reloading browser reloads the orgs

---

components/dashboard/src/SwitchToPAYG.tsx

Goal is to warn the user about the monthly limit, and prevent them from being blocked by it.
Fixes https://github.com/gitpod-io/gitpod/issues/16778
I'm not sure.
```release-note
NONE
```
<details>
</details>
<details>
</details>

Update Switch to PAYG success subtitle

---

components/gitpod-db/src/typeorm/workspace-db-impl.ts
components/gitpod-db/src/workspace-db.ts
components/ws-manager-bridge/src/workspace-instance-controller.ts

Because the installation variable cost me about 15 minutes of confusion...
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-man-bridge] Correct name for Workspace Instance Controller var

---

.github/pull_request_template.md
.github/workflows/build.yml

* `dev:all` is not part of `components:all` - it builds the docker images and we never had until now
* `components:all` is never used in the OG werft build - leeway is run without a target
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gha] fix build + docker build

---

components/dashboard/src/App.tsx
components/server/src/workspace/gitpod-server-impl.ts

Fixes the permissions for remobing org members
Fixes #16794
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] allow members to leave

---

.github/workflows/build.yml

Too many docker containers. Goes with https://github.com/gitpod-io/ops/pull/8672
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gha] mount /var/tmp to 'host'

---

components/dashboard/src/admin/TeamDetail.tsx
components/dashboard/src/projects/Prebuilds.tsx
components/dashboard/src/projects/Project.tsx
components/dashboard/src/projects/Projects.tsx
components/dashboard/src/workspaces/WorkspacesSearchBar.tsx

Moving changes from https://github.com/gitpod-io/gitpod/pull/16499.
> Minor follow up from https://github.com/gitpod-io/gitpod/pull/16439 to apply the same search input style on project pages, Branches & Prebuilds.
```release-note
Update search input style on project pages
```
<details>
</details>
<details>
</details>

Update search input style on project pages

---

install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/workspace/ide/constants.go

Upgrade web extension
Fixes https://github.com/gitpod-io/gitpod/issues/13819
- Open workspace in preview env with MacOS Safari https://hw-test-web.preview.gitpod-dev.com/workspaces
- PortsView icons should show
```release-note
Fix PortsViews icons don't show up in Safari
```
<details>
</details>
<details>
</details>

Upgrade web extension

---

dev/gpctl/BUILD.yaml
dev/gpctl/cmd/users-block.go
dev/gpctl/cmd/users.go
dev/gpctl/go.mod
dev/gpctl/go.sum

Add `gpctl users block` command
```release-notes
NONE
```

[gpctl] Add users block command

---

components/supervisor/pkg/metrics/reporter.go
components/supervisor/pkg/serverapi/metrics.go
components/supervisor/pkg/serverapi/publicapi.go
install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/ide-metrics/configmap.go

Add custom supervisor metrics
```release-note
NONE
```
<details>
</details>
<details>
</details>

Add custom supervisor metrics

---

components/gitpod-db/BUILD.yaml
dev/image/Dockerfile

Without this change, the local DB gets stuck in connecting
```
[components/gitpod-db:dbtest-init] waiting for DB...
[components/gitpod-db:dbtest-init] mysqladmin: [Warning] Using a password on the command line interface can be insecure.
[components/gitpod-db:dbtest-init] waiting for DB...
[components/gitpod-db:dbtest-init] mysqladmin: [Warning] Using a password on the command line interface can be insecure.
[components/gitpod-db:dbtest-init] waiting for DB...
[components/gitpod-db:dbtest-init] mysqladmin: [Warning] Using a password on the command line interface can be insecure.
[components/gitpod-db:dbtest-init] waiting for DB...
[components/gitpod-db:dbtest-init] mysqladmin: [Warning] Using a password on the command line interface can be insecure.
[components/gitpod-db:dbtest-init] …
```

[dev-image] Set DB_HOST to 127.0.0.1 by default

---

components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts
components/gitpod-db/src/typeorm/migration/1678365331415-WorkspaceClustersNamePK.ts
components/gitpod-db/src/typeorm/workspace-cluster-db-impl.ts
components/gitpod-db/src/workspace-cluster-db.spec.db.ts

We no longer need the applicationCluster column. Prior to removing it, we need to adjust the PK to be on the `name` property again.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[migrations] Make workspace cluster name the PK, drop composite PK on (name, appCluster)

---

components/dashboard/src/experiments/client.ts

* Part of https://github.com/gitpod-io/gitpod/issues/16821
1. Feature flags load in preview
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] Use proxy endpoint to fetch feature flags

---

components/ws-manager-bridge/src/cluster-service-server.ts
components/ws-manager-bridge/src/cluster-sync-service.ts

https://gitpod.slack.com/archives/C02F19UUW6S/p1678715506560899
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

Remove workspace_classes_backend feature flag

---

components/dashboard/src/components/RepositoryFinder.tsx
components/dashboard/src/start/start-workspace-options.ts
components/dashboard/src/workspaces/CreateWorkspacePage.tsx

- Allow starting workspaces without using the mouse
- Support all kinds of contextURLs
Fixes #16754
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] give start workspace button focus

---

.github/workflows/build.yml

https://github.com/gitpod-io/gitpod/pull/16829 doesn't seem to work as expected - so for now always build gitpod
This should prevent skipped jobs to count as passed and prs to get merged when they shouldn't
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gha] don't skip gitpod build

---

components/node-labeler/cmd/run.go

```release-note
NONE
```
<details>
</details>
<details>
</details>

[node-labeler] Do not return an error if the node does not exist

---

components/node-labeler/cmd/run.go

* Return early from reconciliation if the node already has the ready label for that pod.
* Prevents build up of reconcile queue
* Fixes the `ready_seconds` metric being recorded for pod reconciliations where the node was already ready
Run integration tests
```release-note
NONE
```
<details>
</details>
<details>
</details>

[node-labeler] Skip checks if label already present

---

components/dashboard/src/components/UsageBasedBillingConfig.tsx
components/server/ee/src/workspace/gitpod-server-impl.ts
components/usage/pkg/apiv1/billing.go
components/usage/pkg/stripe/stripe.go

Additional credit card verification by placing a hold on the provided card before subscribing.
Fixes #
- use credit card: 4000000000000341 and see it failing
- use credit card: 4242424242424242 and see it succeeding
```release-note
NONE
```
<details>
</details>
<details>
</details>

[billing] place a hold on cards before subscribing

---

components/server/src/config.ts
components/server/src/installation-admin/installation-admin-controller.ts
components/server/src/user/user-controller.ts
install/installer/pkg/components/server/configmap.go
install/installer/pkg/components/server/constants.go
install/installer/pkg/components/server/deployment.go

No longer needed, as it's super-seeded by the admin-credentials file flow
* Depends on https://github.com/gitpod-io/gitpod/pull/16760/files
* Part of https://github.com/gitpod-io/gitpod/issues/16223
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Remove admin OTS create/use flow

---

components/gitpod-db/src/typeorm/entity/db-workspace-cluster.ts
components/gitpod-db/src/typeorm/workspace-cluster-db-impl.ts
components/gitpod-db/src/workspace-cluster-db.spec.db.ts
components/gitpod-protocol/src/workspace-cluster.ts
components/image-builder-api/typescript/src/sugar.ts
components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/src/user/user-deletion-service.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/workspace-cluster-imagebuilder-client-provider.ts
components/server/src/workspace/workspace-starter.ts
components/ws-manager-api/typescript/src/client-provider-source.ts
components/ws-manager-api/typescript/src/client-provider.spec.ts
components/ws-manager-api/typescript/src/client-provider.ts
components/ws-manager-bridge/src/bridge-controller.ts
components/ws-manager-bridge/src/cluster-service-server.ts
components/ws-manager-bridge/src/cluster-sync-service.ts

We are no longer using the applicationCluster property, this removes it from the TypeORM model entirely.
Migration to drop the column will follow once there's no usage.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

Remove usage of applicationCluster column from WorkspaceCluster

---

components/dashboard/src/SwitchToPAYG.tsx
components/dashboard/src/hooks/use-local-storage.ts

This PR fixes superfluous and expensive calls to server (e.g. `getAccountStatement` 7 -> 2), but also ensures `server.subscribeToStripe` is called just a single time.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[Switch to PAYG] Deduplicate calls to server.subscribeToStripe

---

.github/workflows/build.yml
.github/workflows/preview-env-check-regressions.yml
dev/preview/workflow/lib/k8s-util.sh
dev/preview/workflow/preview/deploy-gitpod.sh

Fixes:
* https://github.com/gitpod-io/gitpod/pull/16517#issuecomment-1452424003
* added serve-side apply
* https://gitpod.slack.com/archives/C032A46PWR0/p1678732041625199
* `rollout status` will wait for the resources, not individual pods
* https://github.com/gitpod-io/gitpod/actions/runs/4415644835
* fix getting the secret from secret manager
* https://gitpod.slack.com/archives/C032A46PWR0/p1678800928661759
*  don't cancel the configuration job
* https://gitpod.slack.com/archives/C032A46PWR0/p1678867131515719
* don't cancel build-gitpod as it confuses tide
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
Add desired feature flags to …

[preview] fix wait, diff-apply, regression-check slack

---

components/server/src/express-util.ts
components/server/src/server.ts

Removes unnecessary lines that spill the logs: [link](https://cloudlogging.app.goo.gl/6fdRCFzVj1hrfvvg7)
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Tone down unnecessary logging around websocket verifyClient

---

components/gitpod-db/src/typeorm/migration/1678796232269-DropApplicationClusterFromWorkspaceClusters.ts

All application usage removed in https://github.com/gitpod-io/gitpod/pull/16824
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[db] Drop applicationCluster column from d_b_workspace_cluster

---

components/ws-manager-bridge/src/cluster-service-server.ts
components/ws-manager-bridge/src/cluster-sync-service.ts

This reverts commit afb724660182fcd480dc2e7fc06c45291b0023ad.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

Revert "Remove workspace_classes_backend feature flag (#16825)"

---

components/node-labeler/debug.sh

Add `debug.sh` script for the node-labeler component
Run it!
```release-note
NONE
```
<details>
</details>
<details>
</details>

[node-labeler] Add debug.sh script

---

components/ws-manager/pkg/manager/monitor.go

Log timeout and reason when a workspace times out.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager] Log timeout

---

components/dashboard/src/components/Alert.tsx
components/dashboard/src/components/EmptyMessage.tsx
components/dashboard/src/components/Modal.tsx
components/dashboard/src/components/UsageBasedBillingConfig.tsx
components/dashboard/src/teams/GitIntegrationsPage.tsx
components/dashboard/src/teams/OrgSettingsPage.tsx
components/dashboard/src/teams/SSO.tsx
components/dashboard/src/teams/TeamBilling.tsx
components/dashboard/src/teams/TeamSettings.tsx
components/dashboard/src/teams/TeamUsageBasedBilling.tsx
components/dashboard/src/teams/git-integrations/GitIntegrationListItem.tsx
components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
components/dashboard/src/teams/git-integrations/GitIntegrations.tsx
components/dashboard/src/teams/git-integrations/GitIntegrationsList.tsx

Some cleanup around the Org Settings pages.
Each page now updates the main head accordingly
| Settings | SSO | Git Integrations | Billing |
| -- | -- | -- | -- |
| ![image](https://user-images.githubusercontent.com/367275/225173162-68068cc8-5c0f-45e1-9bdf-fe5fb6692c8d.png) | ![image](https://user-images.githubusercontent.com/367275/225173232-894f0e76-8a25-485e-aa63-b593d05ab461.png) | ![image](https://user-images.githubusercontent.com/367275/225173325-b5b84040-4d61-4916-a5eb-0819f06aa0be.png) | ![image](https://user-images.githubusercontent.com/367275/225173461-d671a585-bca7-4a10-8da2-91b15b766541.png) |
* `<ModalFooter error="error message" warning="warning message" />`
* only 1 shows at a time. `error` takes precedence.
* Pinned above the footer (would like to have it animate/slide up …

Org Settings Page Header updates & cleanup

---

install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/ide-metrics/configmap.go

Allow vscode desktop error report
Related https://github.com/gitpod-io/gitpod-vscode-desktop/pull/39
```release-note
NONE
```
<details>
</details>
<details>
</details>

Allow vscode desktop error report

---

components/server/src/auth/auth-provider-service.ts
components/server/src/auth/authenticator.ts

We need to make sure that login with organizational Git Auth is not permitted. Those organizational Git Auth providers are limited to be used for Git operations and API calls only.
Fixes #16873
1. Create an org
2. Create Git Auth for that org (doesn't need to be a valid Git provider, a random but reachable GitLab would work)
3. Try to login by navigating to `/api/login?host=some-gitlab.com`
4. See no redirect attempt to the Git provider happens.
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[org] Disallow logins with organizational Git Auth

---

WORKSPACE.yaml
install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/workspace/ide/constants.go

Update code to https://github.com/microsoft/vscode/releases/tag/1.76.2
A part of https://github.com/gitpod-io/gitpod/issues/16587
```release-note
NONE
```

Update VS Code Browser to `1.76.2`

---

components/server/src/github/file-provider.ts

The old accept header is not listed in [Github's media types](https://docs.github.com/en/rest/overview/media-types?apiVersion=2022-11-28), the new one is
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Fix file provider accept header

---

components/dashboard/src/start/StartWorkspace.tsx
components/gitpod-cli/cmd/ports-await.go
components/gitpod-cli/cmd/ports-expose.go
components/gitpod-cli/cmd/validate.go
components/supervisor/validate.sh
install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-ide/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/workspace/ide/constants.go

[gitpod-cli] change `gp rebuild` to `gp validate`
Fixes #16389
1. start a workspace in this preview env
2. try `gp rebuild --help` it will only show `--prebuild` and `--log` flag, and a deprecated tips
3. try `gp validate` it should work
```release-note
[gitpod-cli] change `gp rebuild` to `gp validate`
```
<details>
</details>
<details>
</details>

[gitpod-cli] change `gp rebuild` to `gp validate`

---

.github/workflows/preview-env-check-regressions.yml

[smoke-test] fix send slack notification
We want to send slack notification if test is failed, but the secret only fetch if task success, so failed message won't sent.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[smoke-test] fix send slack notification

---

operations/observability/mixins/IDE/dashboards/components/supervisor.json

Check also [grafana](https://grafana.gitpod.io/d/1eOk3B-Vk/supervisor?orgId=1) if it still exists
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[observability] add superviosr dashboard

---

.github/workflows/preview-env-check-regressions.yml
dev/preview/workflow/preview/deploy-gitpod.sh

Fixes 
https://github.com/gitpod-io/gitpod/pull/16842#issuecomment-1473163233
```release-note
NONE
```
<details>
</details>
<details>
</details>

[preview] pass context to rollout status

---

.github/workflows/ide-integration-tests.yml

Moving from https://github.com/gitpod-io/gitpod/pull/16886 so the other one can get merged.
Fixes 
https://github.com/gitpod-io/gitpod/pull/16888#issuecomment-1473371833
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gha] fix ide integration tests

---

components/common-go/grpc/ratelimit.go
components/common-go/grpc/ratelimit_test.go

Support gRPC rate limiting on keys that are enums
Allows us to rate limit by workspace type here https://github.com/gitpod-io/ops/issues/6831
Tested in a preview env, by configuring a rate limit on ws-manager-mk2's `SetTimeout` endpoint, key-ed on the `type` enum field:
```
"/wsman.WorkspaceManager/SetTimeout": {
"block": true,
"bucketSize": 1,
"refillInterval": "30s",
"key": "type",
"keyCacheSize": 10
}
```
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[common-go] Support rate limiting by enum key

---

components/ws-daemon/pkg/controller/workspace_controller.go
components/ws-manager-api/go/crd/v1/workspace_types.go
components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/timeout_controller.go
components/ws-manager-mk2/service/manager.go

Refactor workspace status conditions to have less repetition.
n.a.
```release-note
None
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Refactor workspace status conditions

---

components/ws-manager-api/go/crd/v1/workspace_types.go
components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_workspaces.yaml
components/ws-manager-mk2/controllers/workspace_controller.go
components/ws-manager-mk2/main.go

Small fixes/improvements:
* Show workspace type by default in `kubectl get ws`
* Only remove finalizer once secrets deletion succeeded
* Check for empty namespaces in config on startup
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Check empty ns, delete secrets before finalizer

---

components/ws-daemon/pkg/controller/workspace_controller.go
components/ws-manager-mk2/controllers/status.go

Don't dispose image builds
Create an image build, and observe it doesn't run disposal once completed, and the image build workspace goes to stopping and then disappears from the cluster. Tested in workspace-preview
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Don't dispose image builds

---

components/ws-daemon/pkg/controller/snapshot_controller.go
components/ws-daemon/pkg/controller/workspace_controller.go
components/ws-daemon/pkg/daemon/daemon.go
components/ws-manager-api/go/crd/v1/snapshot_types.go
components/ws-manager-mk2/config/crd/bases/workspace.gitpod.io_snapshots.yaml
components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/suite_test.go
components/ws-manager-mk2/controllers/workspace_controller.go
components/ws-manager-mk2/main.go
install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-workspace/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/ws-daemon/clusterrole.go

Emit events for workspaces and snapshots. Depends on https://github.com/gitpod-io/gitpod/pull/16896
```
kubectl get events | rg workspace/
108s        Normal    Creating            workspace/064b1210-53d1-42df-9ac5-a00dbc60a22f                      
107s        Normal    Initializing        workspace/064b1210-53d1-42df-9ac5-a00dbc60a22f                      
104s        Normal    Running             workspace/064b1210-53d1-42df-9ac5-a00dbc60a22f                      
0s          Normal    Stopping            workspace/064b1210-53d1-42df-9ac5-a00dbc60a22f                      
0s          Normal    Deleting            workspace/064b1210-53d1-42df-9ac5-a00dbc60a22f
```
```
20m         Warning   Failed         workspace/32739418-0e1e-43a0-ba82-090050686b64    Content init failed: cannot …
```

[ws-manager-mk2] Emit events for workspaces and snapshots

---

components/gitpod-db/src/typeorm/migration/1679312926829-OrganizationSlugIndex.ts

Part of #16856
```release-note
NONE
```
<details>
</details>
<details>
</details>

[orgs] Add index for slug

---

components/dashboard/src/components/UsageBasedBillingConfig.tsx

Fixes https://github.com/gitpod-io/gitpod/issues/16524
- use https://www.notion.so/gitpod/Rapid-frontend-development-without-a-preview-environment-69d13efd271e4c66b6b33f31bc7bb3e1 to inject this to staging
- create a new org
- go to /billing and signup with Stripe
- note how you end up with one subscription only :heavy_check_mark: 
- (yes, no proof, but it's hard to reliably re-create the core issue. If you have ideas, please share! :bulb: )
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[dashboard] Guard subscribeToStripe against multiple calls

---

components/dashboard/src/components/Modal.tsx
components/dashboard/src/components/modal.css
components/dashboard/src/teams/GitIntegrationsPage.tsx
components/dashboard/src/teams/OrgSettingsPage.tsx
components/dashboard/src/teams/SSO.tsx
components/dashboard/src/teams/TeamBilling.tsx
components/dashboard/src/teams/TeamSettings.tsx
components/dashboard/src/teams/git-integrations/GitIntegrationListItem.tsx
components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
components/dashboard/src/teams/git-integrations/GitIntegrations.tsx
components/dashboard/src/teams/git-integrations/GitIntegrationsList.tsx
components/dashboard/src/teams/sso/OIDCClientConfigModal.tsx
components/dashboard/src/teams/sso/OIDCClientListItem.tsx
components/dashboard/src/teams/sso/OIDCClients.tsx

* Swap org settings page heading back so it's the same for all pages ([discussed here](https://github.com/gitpod-io/gitpod/pull/16868#discussion_r1138564211))
* Updated SSO & Git Auth page headings for consistency
* SSO client api error message details included in Modal alerts
SSO clients list items updated so issuer URL is more prominent than ID.
Made some updates so modal alerts can be closeable, and animate in if so. If they're not closeable they render statically between the modal body and footer.
| Non-Closeable | Closeable |
| <img width="537" alt="image" src="https://user-images.githubusercontent.com/367275/226069501-f49a6fae-d968-4423-8c02-6f714c381839.png"> | ![Screen Recording 2023-03-17 at 5 33 39 PM](https://user-images.githubusercontent.com/367275/226070423 …

Org Settings and Modal alert updates

---

components/dashboard/src/workspaces/CreateWorkspacePage.tsx

Fixes a bug when using a snapshot context url with the new create workspace page. Needed to make the logic that checks for a matching project a bit more resilient to missing properties on the workspace context object.
Fixes #16926
* Create a Workspace
* Create a Snapshot from your workspace
* Load the Snapshot URL and ensure it doesn't render an error page like in the issue.
```release-note
NONE
```
<details>
</details>
<details>
</details> …

check for repository property on context

---

dev/preview/workflow/lib/k8s-util.sh

Fixes 
```bash
Apply failed with 4 conflicts: conflicts with "kubectl-client-side-apply" using apps/v1:
- .spec.template.spec.containers[name="agent-smith"].env
- .spec.template.spec.containers[name="agent-smith"].env[name="KUBE_NAMESPACE"].valueFrom.fieldRef
- .spec.template.spec.containers[name="agent-smith"].env[name="NODENAME"].valueFrom.fieldRef
- .spec.template.spec.containers[name="kube-rbac-proxy"].env[name="IP"].valueFrom.fieldRef
```
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[preview] diff-apply server side force conflicts

---

components/ide/jetbrains/backend-plugin/gradle-latest.properties
components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodMetricControlProvider.kt
components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodTerminalService.kt
components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/LatestGitpodIgnoredPortsForNotificationServiceImpl.kt
components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/LatestGitpodMetricControlProvider.kt
components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/LatestGitpodTerminalService.kt
components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/StableGitpodIgnoredPortsForNotificationServiceImpl.kt
components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/StableGitpodMetricControlProvider.kt
components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/StableGitpodTerminalService.kt
components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
components/ide/jetbrains/backend-plugin/src/main/resources-stable/META-INF/extensions.xml
components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
components/supervisor-api/java/build.gradle

Update the major version of the backend plugin to unblock auto upgrade of latest images.
Fixes #
- you should see custom metrics in the backend control center, i.e. workspace CPU
- configured tasks should be attached
- there should not be notifications about internal IDE ports
- Start a Gitpod workspace for this PR with IntelliJ.
- Run `./launch-dev-server.sh u` from `components/ide/jetbrains/backend-plugin/`
- Copy Gitpod link from output and open in Browser.
- Do tests similar for stable.
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[jb] bump up major platform version of backend plugin

---

dev/preview/workflow/preview/deploy-gitpod.sh

Fixes resources that exist in multiple namespaces under the same name (e.g. `ws-manager-mk2`'s role) only getting deployed in one namespace
Create preview env
```release-note
NONE
```
<details>
</details>
<details>
</details>

[preview] Fix deploy of resources in multiple ns

---

components/dashboard/src/start/StartWorkspace.tsx

- Removes the latest ide alert warning on the workspace timeout page and only shows it during workspace (re)start.
Relates #11035
- Open workspace in preview env with a **latest** editor https://hide-editor-alert.preview.gitpod-dev.com/workspaces
- Alert should show during starting workspace
- Stop to see if the latest ide alert does not show up
- Open again with a stable editor
- Alert should not show during starting workspace
- Stop should have no alert
```release-note
Removes the latest ide alert warning on the workspace timeout page
```
<details>
</details>
<details>
Add desired …

Hide the latest ide alert warning on workspace timeout

---

components/ws-manager-mk2/BUILD.yaml
components/ws-manager-mk2/go.mod
components/ws-manager-mk2/go.sum
components/ws-manager-mk2/main.go

Use the standard common-go logger for mk2. Fixes a couple of things:
- No longer logs to stderr, which is interpreted as error logs on google cloud logging
- Add service context fields
- Log in json format instead of console
Part of #11416
Inspect ws-manager-mk2 logs
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Use common-go/log

---

.github/ISSUE_TEMPLATE/epic.yml

I've recently been updating IDE team epics with @laushinka and we were looking back at this template for inspiration, however noticed a few things that I think would improve the template generally. Example implementation of the template: 
- https://github.com/gitpod-io/gitpod/issues/9038
Some changes / reasoning. 
- **Make clear this is for user-facing work, not tech debt or investigations/discovery** -  I believe the fields / properties required for those types of work are too different from this template that it would not be of value. We should consider making more epic template for these different types of epics. 
- **Remove (almost all) placeholders** I wasn't sure how much the placeholders were adding value to the template, they make it feel quite overwhelming to me. 
- **Make all …

Refresh + simplify the epic template

---

operations/observability/mixins/cross-teams/dashboards.libsonnet
operations/observability/mixins/cross-teams/dashboards/redis.json

Requires https://github.com/gitpod-io/gitpod/pull/16927 to get data in staging/prod
See it in [staging](https://grafana.gitpod-staging.com/d/xDLNRKUWz/components-redis?orgId=1&refresh=30s)
Fixes https://github.com/gitpod-io/gitpod/issues/16684
```release-note
NONE
```
<details>
</details>
<details>
</details>

[redis] Add grafana dashboard

---

install/installer/cmd/testdata/render/agent-smith/output.golden
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/custom-pull-repository/output.golden
install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden
install/installer/cmd/testdata/render/http-proxy/output.golden
install/installer/cmd/testdata/render/ide-config/output.golden
install/installer/cmd/testdata/render/kind-meta/output.golden
install/installer/cmd/testdata/render/kind-webapp/output.golden
install/installer/cmd/testdata/render/message-bus-password/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/overrides-inline/output.golden
install/installer/cmd/testdata/render/pod-config/output.golden
install/installer/cmd/testdata/render/shortname/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/cmd/testdata/render/telemetry/output.golden
install/installer/cmd/testdata/render/use-pod-security-policies/output.golden
install/installer/cmd/testdata/render/vsxproxy-pvc/output.golden
install/installer/cmd/testdata/render/workspace-requests-limits/output.golden
install/installer/pkg/components/redis/constants.go
install/installer/pkg/components/redis/deployment.go
install/installer/pkg/components/redis/objects.go
install/installer/pkg/components/redis/rolebinding.go

Adds role and kube-rbac-proxy such that metrics can be scraped
Fixes https://github.com/gitpod-io/gitpod/issues/16684
1. Redis & side-cars come up in preview env
```release-note
NONE
```
<details>
</details>
<details>
</details>

[redis] Add role-binding & rbac proxy to scrape metrics

---

install/installer/pkg/components/cluster/certmanager.go
install/installer/pkg/config/v1/experimental/experimental.go

context: [internal thread](https://gitpod.slack.com/archives/C01KLC56NP7/p1679409826882809?thread_ts=1679404588.580769&cid=C01KLC56NP7)
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[installer] Allow to override the namespace where certmanager is installed

---

install/installer/pkg/components/image-builder-mk3-wsman/deployment.go
install/installer/pkg/components/ws-manager-mk2/tlssecret.go

Fixes ws-manager-mk2 certs not becoming ready. https://github.com/gitpod-io/gitpod/pull/16793 refactored all cert issuer kinds to ClusterIssuerKind (except for mk2)
Tested in a preview env with mk2 enabled
```release-note
NONE
```
<details>
</details>
<details>
</details>

[installer] Fix ClusterIssuerKind for mk2

---

.github/workflows/jetbrains-update-plugin-platform-template.yml
.github/workflows/jetbrains-update-plugin-platform.yml

It removes limiting auto update by major version that we get new PRs whenever there are SDK for new EAP versions
Fixes #
merge and run on main
```release-note
NONE
```
<details>
</details>
<details>
</details>

[jb] allow to auto update platform for next EAP

---

.github/workflows/jetbrains-update-plugin-platform-template.yml

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[jb] ensure to publish GW plugins on upgrade

---

components/dashboard/src/components/BillingAccountSelector.tsx

We've observed a high number of calls to `listAvailableUsageAttributionIds`. This PR is to fix the frontend part causing the many calls to server.
1. Navigate to `/user/billing`, make sure you are not redirected 
2. Check the WebSocket comms for `listAvailableUsageAttributionIds`
```release-note
NONE
```
<details>
</details>
<details>
</details>

[billing page] Fix erratic calls to listAvailableUsageAttributionIds

---

.github/CODEOWNERS

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

cross-team observability shouldn't require every teams' review

---

operations/observability/mixins/cross-teams/dashboards/redis.json

See it [here](https://grafana.gitpod-staging.com/d/xDLNRKUWz/components-redis?orgId=1&refresh=30s&from=now-6h&to=now), with data
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[redis] Adjust dashboard to include variables for instances

---

components/server/src/auth/rate-limiter.ts

Not necessary anymore since we rolled out https://github.com/gitpod-io/ops/pull/8744.
Fixes https://github.com/gitpod-io/gitpod/issues/16880
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Lift ratelimit on sendHeartBeat

---

components/server/src/user/user-service.ts
components/server/src/workspace/gitpod-server-impl.ts

Fixes https://github.com/gitpod-io/gitpod/issues/16936
- follow [this link](https://gpl-16936-no-orgs.preview.gitpod-dev.com/iam/oidc/start?id=82792e35-1d01-4d72-8b38-96e4c055e81e) into the preview env
- try to create a [new org](https://gpl-16936-no-orgs.preview.gitpod-dev.com/orgs/new)
- see how that fails :heavy_check_mark: 
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Block org-level users from creating/joining new organizations

---

components/dashboard/src/App.tsx

Fixes #
- inject the frontend into staging
- manipulate https://github.com/gitpod-io/gitpod/blob/8496ae0c36d868fbb0681f950c1da84cad24a432/components/dashboard/src/hooks/use-user-and-teams-loader.ts#L24-L26 to set `user` to `undefined`
- see how you end up with the loading screen :+1:
- on removing that code, you should end up with the rendered App again :+1:
- (this tests that [the fix from yesterday](https://github.com/gitpod-io/gitpod/pull/16941/files) is still in effect)
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[dashboard] Avoid re-rendering the whole App on Org load

---

.github/actions/delete-preview/Dockerfile
.github/actions/deploy-gitpod/Dockerfile
.github/actions/deploy-monitoring-satellite/Dockerfile
.github/actions/preview-create/Dockerfile
.github/workflows/build.yml
.github/workflows/ide-integration-tests.yml
.github/workflows/preview-env-gc.yml
.gitpod.yml
.werft/aks-installer-tests.yaml
.werft/build.yaml
.werft/cleanup-installer-tests.yaml
.werft/debug.yaml
.werft/eks-installer-tests.yaml
.werft/gke-installer-tests.yaml
.werft/k3s-installer-tests.yaml
.werft/platform-trigger-werft-cleanup.yaml
.werft/workspace-run-integration-tests.yaml
WORKSPACE.yaml
components/ws-daemon/pkg/internal/session/workspace.go
components/ws-manager/pkg/manager/manager.go
components/ws-manager/pkg/manager/monitor.go
dev/image/Dockerfile

Update our dev image to support Jammy
Ref: https://github.com/gitpod-io/workspace-images/pull/1017
Some changes were necessary in `ws-manager- and `ws-daemon` to avoid linter errors (assumption: the newer version of go has changes that improve linting):
1. 2aad8120a309bd00b46cdfc1258c6456f671a547
2. ca2df6fbbf77b681d69eb5b7be6ad2f5c077cdc4
Additionally, the linter was timing out on `registry-facade`: 24a28b8b8af202e84ce7a43d8d776142d0622514
And I updated `gcloud` because ours was getting "old": 663ea050f4007dfb2f29748105b334989e3245b3
Fixes # n/a
```
cd dev/image
docker build . --tag foo:bar
docker run --rm -it foo:bar
```
4. [Test in the preview environment by starting the Gitpod mono repo from a preview environment](https://kylos101-j2dabf45871.preview.gitpod-dev.com/?editor=code#https:/ …

[dev image] update to Jammy

---

License.third-party.go.txt

Updates the third-party license file for all Go code.
```release-note
NONE
```

Update third-party Go licenses

---

components/dashboard/src/App.tsx
components/dashboard/src/app/AppLoading.tsx
components/dashboard/src/components/Delayed.tsx
components/dashboard/src/components/EmptyMessage.tsx
components/dashboard/src/components/ErrorBoundary.tsx
components/dashboard/src/data/organizations/orgs-query.ts
components/dashboard/src/data/setup.tsx
components/dashboard/src/hooks/use-analytics-tracking.ts
components/dashboard/src/hooks/use-user-loader.ts
components/dashboard/src/menu/OrganizationSelector.tsx
components/dashboard/src/teams/OrgSettingsPage.tsx
components/dashboard/src/teams/TeamBilling.tsx
components/dashboard/src/teams/TeamSettings.tsx
components/dashboard/src/teams/TeamUsageBasedBilling.tsx
components/dashboard/src/user-context.tsx
components/dashboard/src/user-settings/PageWithSettingsSubMenu.tsx
components/dashboard/src/user-settings/Plans.tsx
components/dashboard/src/user-settings/SSHKeys.tsx

Addresses a few things that deal with app loading state, and org loading.
* Adds top level ErrorBoundary to catch errors if user or org loading throw errors
* Swapped user loading to a useQuery so errors can get caught in ErrorBoundary. Left UserContext for state management for now, but we can migrate to an exposed useQuery later to get the user.
* Extract org billing mode from `useOrganizations()` query and swap to `useOrgBillingMode()` query where it was used. This removes having to load every orgs billing mode as a blocking path for the app rendering.
* Removed `UserContext.billingMode` in favor of `userUserBillingMode()` query
* Add a view for `<AppLoading/>` that shows up if app takes longer than 3 seconds to load.
Fixes #16803
```release-note
NONE
```
Run the build with werft …

Improve app and org loading states

---

components/ws-manager-mk2/controllers/suite_test.go
components/ws-manager-mk2/controllers/timeout_controller.go
components/ws-manager-mk2/controllers/timeout_controller_test.go
components/ws-manager-mk2/main.go

Emit event for timed out workspaces
```
0s          Normal    TimedOut                  workspace/94bd04a6-5692-4f0f-b300-33397fa1e3fc          workspace timed out after period of inactivity (00h01m) took longer than 00h01m
```
n.a.
- Open workspace in [preview environment](https://fo-timedout-events.preview.gitpod-dev.com/workspaces)
- Set timeout of workspace to 1m
- Check events with `kubectl get events` 
```release-note
None
```
<details>
</details>
<details>
</details> …

[wsman-mk2] Emit event for timed out workspaces

---

components/dashboard/src/workspaces/CreateWorkspacePage.tsx

Fixes a bug that we noticed yesterday. Probably it was fixed with https://github.com/gitpod-io/gitpod/pull/16976 already, but having the guard + log helps in case this happens again.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] Ensure we always send an organizationId if we need to!

---

components/ws-proxy/cmd/run.go

Adding a quality of life logging statement to hopefully save future us time.
Fixes: https://github.com/gitpod-io/ops/issues/8805
Scale ws-manager to zero.
Rollout restart ws-proxy.
Check ws-proxy logs.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-proxy] log before attempting to dial ws-manager

---

.github/pull_request_template.md
.github/workflows/build.yml

support run integration-test for gha
Fixes #
see this job https://github.com/gitpod-io/gitpod/actions/runs/4502498386/jobs/7925282541
```release-note
NONE
```
<details>
</details>
<details>
</details>

support integration-test for gha

---

components/ws-daemon/pkg/controller/workspace_controller.go
components/ws-daemon/pkg/controller/workspace_operations.go

Depends on https://github.com/gitpod-io/gitpod/pull/16823
After we have taken the backup we delete the workspace content and only then we update the backup condition on the workspace CR. If the delete operation is interrupted due to ws-daemon restart we will retry the backup due to the missing backup condition and will create only a partial backup. Instead we now first update the backup condition and only then we delete the workspace content. 
n.a.
- Open workspace in [preview](https://gc71da2917f.workspace-preview.gitpod-io-dev.com/workspaces) 
- Everything should work as usual
```release-note
None
```
<details>
</details>
<details> …

[ws-manager-mk2] Prevent partial workspace backups

---

components/node-labeler/cmd/run.go

Ensure registry-facade can reach ws-manager by trying to get details from a workspace.
```release-note
NONE
```
<details>
</details>
<details>
</details>

Improve node-labeler

---

components/ws-daemon/pkg/controller/workspace_operations.go

Depends on https://github.com/gitpod-io/gitpod/pull/16997
Ensure that content init can be restarted if interrupted.
n.a.
- Open workspace in [preview](https://gc71da2917f.workspace-preview.gitpod-io-dev.com/workspaces) with long initialization times
- Restart ws-daemon
- Workspace should open normally
```release-note
None
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Ensure content init can be restarted

---

components/ws-daemon/pkg/controller/housekeeping.go
components/ws-daemon/pkg/daemon/daemon.go

Old workspaces (identified by having no workspace state file) will be garbage collected after 1 hour. This takes care of situations where we fail to remove the workspace content after backup e.g. because ws-daemon has been restarted.
n.a.
- Open workspace in [preview environment](https://gc71da2917f.workspace-preview.gitpod-io-dev.com/workspaces)
- SSH into node and delete the workspace state file from disk
- The garbage collection age has been modified in the preview environment so the workspace should be garbage collected after 2 minutes. 
```release-note
None
```
<details>
</details>
<details> …

[ws-manager-mk2] Garbage collect workspaces

---

components/server/src/user/user-service.ts

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Fix userService.deauthorize to disallow disconnecting the last auth provider

---

.github/actions/deploy-gitpod/entrypoint.sh
.github/actions/deploy-gitpod/metadata.yml
.github/workflows/build.yml
.github/workflows/workspace-integration-tests.yml
components/ws-manager-mk2/service/manager.go
dev/preview/workflow/preview/deploy-gitpod.sh
test/pkg/integration/apis.go
test/pkg/integration/integration.go
test/pkg/integration/setup.go
test/tests/components/ws-manager/prebuild_test.go
test/tests/components/ws-manager/protected_secrets_test.go

* Support running e2e tests against ws-manager-mk2 by setting the `WS_MANAGER_MK2=true` env var
* Fixes for mk2 to pass failing tests
* Add boolean to Github Actions workflow to run tests against mk2
* Run e2e tests with(out) `WS_MANAGER_MK2=true`
* Trigger GHA from this branch with the mk2 boolean enabled/disabled
```release-note
NONE
```
<details>
</details>
<details>
</details>

[e2e] Support and fixes for mk2 e2e tests

---

components/dashboard/src/components/PageWithSubMenu.tsx
components/dashboard/src/components/typography/headings.tsx

Step 1 to making sidebars responsive. Shifts the sidebar to a row that scrolls on smaller screens. Also made the `<Heading1/>` slightly smaller on small screens.
| Header | Header |
| <img width="407" alt="image" src="https://user-images.githubusercontent.com/367275/227397674-5738b10c-6a3d-4bf6-858e-7f30ca6d6595.png"> | <img width="424" alt="image" src="https://user-images.githubusercontent.com/367275/227397642-b6f2059a-b459-401c-a786-82d2e064c892.png"> | 
**Follow Up Steps**
* Explore using a dropdown for the sidebar navigation items versus scrollable menu.
* Explore adding a scrolling indicator on left/right edge of menu when there's more options off-screen.
* Currently navigation on the submenu results in a full route re-render, which resets the scroll position of …

Make sidebars responsive

---

operations/observability/mixins/IDE/dashboards.libsonnet

Add missing dashboard setting
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[observability] add supervisor dashboard

---

.github/actions/deploy-gitpod/entrypoint.sh
.github/pull_request_template.md
.github/workflows/build.yml
.werft/jobs/build/installer/installer.ts
dev/preview/workflow/preview/deploy-gitpod.sh

```release-note
NONE
```
<details>
</details>
<details>
</details>

Remove references to enterprise licenses

---

components/server/BUILD.yaml
components/server/package.json
components/server/src/api/user.ts
components/server/src/container-module.ts
components/server/src/server.ts
gitpod-ws.code-workspace
yarn.lock

Adds an un-implemented UserService onto server. This service is a gRPC/connect service, which conforms to the same interface as the public-api as per WebApp architectural direction.
Currently unused, but will be used by as part of https://github.com/gitpod-io/ops/issues/8192 to issue a BlockUser call
* Depends on https://github.com/gitpod-io/gitpod/pull/17000
* Part of https://github.com/gitpod-io/ops/issues/8192
1. Preview
2. Port forward `k port-forward deployment/server 9877:9877`
3. 
```
curl \
--header "Content-Type: application/json" \
--data '{}' \                           
http://localhost:9877/gitpod.experimental.v1.UserService/BlockUser
{"code":"unimplemented","message":"unimplemented"}
```
```release-note
NONE
``` …

[server] gRPC/Connect Unimplemented User Service

---

components/node-labeler/cmd/run.go

Switch to a controller to not use the low-level watch abstraction.
A side effect of this change is the reduction in ~20s to add the required node labels
```release-note
NONE
```
<details>
</details>
<details>
</details>

Replace watch with builder.ControllerManagedBy

---

install/installer/pkg/common/constants.go
install/installer/pkg/components/server/constants.go
install/installer/pkg/components/server/deployment.go
install/installer/pkg/components/server/networkpolicy.go
install/installer/pkg/components/server/objects.go

* Depends on https://github.com/gitpod-io/gitpod/pull/16999
* Part of https://github.com/gitpod-io/ops/issues/8192
1. `kubectl port-forward service/server 9877:9877`
2.
```
curl \
--header "Content-Type: application/json" \
--data '{}' \                           
http://localhost:9877/gitpod.experimental.v1.UserService/BlockUser
{"code":"unimplemented","message":"unimplemented"}
```
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[server] Expose gRPC API port to public-api & usage

---

components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/src/user/user-service.ts
components/server/src/workspace/workspace-starter.ts

Cleans up blocking users rpc, which makes it easier to introduce it on the gRPC API in `api/user.ts` see https://github.com/gitpod-io/gitpod/pull/16999 for details if needed.
* Moves stopping of workspaces to workspace starter (it already has the stop method there)
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Cleanup adminBlockUser RPC

---

components/ws-daemon/pkg/controller/workspace_controller.go
components/ws-manager-api/go/crd/v1/workspace_types.go
components/ws-manager-mk2/controllers/metrics.go
components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/workspace_controller.go
components/ws-manager-mk2/controllers/workspace_controller_test.go

Report content init/dispose failures in the workspace status.
Fixes the `TestMissingBackup` e2e test.
Part of #11416
Tested by modifying ws-daemon to return an init (1) and dispose (2) error:
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Report content init/dispose failures

---

components/dashboard/src/contexts/FeatureFlagContext.tsx
components/dashboard/src/index.css
components/dashboard/src/teams/git-integrations/GitIntegrationListItem.tsx
components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
components/dashboard/src/teams/git-integrations/GitIntegrationsList.tsx
components/dashboard/src/user-settings/Integrations.tsx
components/server/src/auth/auth-provider-service.ts
components/server/src/workspace/gitpod-server-impl.ts

Next steps in preparing Git Auth for use in orgs and in dedicated.
* Default `orgGitAuthProviders` flag to `true` in dashboard so it's on for dedicated. Still off for production though. We can revisit this once we have more robust ff support in dedicated.
* Several small Git Auth config UI updates/fixes I noticed when testing
* Adjusting org git auth providers and how we check for duplicate host names.
* Adding `userGitAuthProviders` feature flag that guards ability to create user-based git auth providers. Default is `false` so it's disabled on dedicated, but flag is `true` in non-prod and prod to keep existing behavior.
Fixes #16934, https://github.com/gitpod-io/gitpod/issues/17018
**Preview Env:** https://bmh-git-auth-updates.preview.gitpod-dev.com/user/account
Should be able to create …

default orgGitAuthProviders to true for dedicated

---

WORKSPACE.yaml

Fixes #16614
- Open `https://github.com/Derroylo/sulu-workspace-sample`
- Check the version running `docker compose version` is `Docker Compose version v2.17.2-gitpod.0`
```release-note
NONE
```
<details>
</details>
<details>
</details>

Update docker compose to v2.17.2

---

components/gitpod-protocol/src/protocol.ts

Attempt to disable the onboarding flow for organizational accounts, i.e. created using OIDC SSO of any org. 
Fixes WEB-30
1. Setup OIDC SSO on a new Org
2. Use the Login button (...) next to the OIDC config entry
3. See that there is no Onboarding flow happening after signing in
```release-note
NONE
```
<details>
</details>
<details>
</details>

[WEB-30][onboarding] skip for organizational accounts

---

install/installer/pkg/common/common.go
install/installer/pkg/components/agent-smith/daemonset.go
install/installer/pkg/components/registry-facade/daemonset.go
install/installer/pkg/components/ws-daemon/daemonset.go

Currently we update one instance of a daemonset at a time. With a large number of nodes updating all instances can take a long time. With this change we update 20% of nodes at the same time.
n.a.
- Create ephemeral cluster
- Restart daemonsets
```release-note
None
```
<details>
</details>
<details>
</details>

[workspace] Increase rollout speed of daemonsets

---

components/common-go/grpc/ratelimit.go
components/common-go/grpc/ratelimit_test.go

* Support rate limiting keyed on boolean fields
* Support composite rate limit keys
* Comma separated, e.g. `foo.bar,foo.baz`
* Improve performance of rate limiter by moving string splitting out of the hot path
Run unit tests and benchmarks. Tested single and composite keys in a preview env
```release-note
NONE
```
<details>
</details>
<details>
</details>

[common-go] Rate limiting on booleans and composite keys

---

components/dashboard/src/teams/OrgSettingsPage.tsx
components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
components/dashboard/src/teams/git-integrations/GitIntegrationsList.tsx

Replacing "Git Auth" with "Git Integrations". ([Internal discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1679923278367079))
```release-note
NONE
```
<details>
</details>
<details>
</details>

[git-integrations] correct menu entries

---

components/server/package.json
components/server/src/api/user.spec.ts
components/server/src/api/user.ts

Implements blockUser on the gRPC/Connect server side.
Fixes #
1. Sign in
2. Get your user ID
1. `kubectl port-forward service/server 9877:9877`
3. 
```
curl \
--header "Content-Type: application/json" \
--data '{"userId": "your-user-id", "reason": "foo"}' \                           
http://localhost:9877/gitpod.experimental.v1.UserService/BlockUser
{}
```
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[server] Implement blockUser

---

components/gitpod-db/src/typeorm/workspace-cluster-db-impl.ts

context https://gitpod.slack.com/archives/C02EN94AEPL/p1680000631745719
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-man-bridge] Hard delete workspace clusters on deregistration

---

.github/actions/delete-preview/Dockerfile
.github/actions/deploy-gitpod/Dockerfile
.github/actions/deploy-monitoring-satellite/Dockerfile
.github/actions/preview-create/Dockerfile
.github/workflows/build.yml
.github/workflows/ide-integration-tests.yml
.github/workflows/preview-env-check-regressions.yml
.github/workflows/preview-env-gc.yml
.github/workflows/workspace-integration-tests.yml
.gitpod.yml
.werft/aks-installer-tests.yaml
.werft/build.yaml
.werft/cleanup-installer-tests.yaml
.werft/debug.yaml
.werft/eks-installer-tests.yaml
.werft/gke-installer-tests.yaml
.werft/k3s-installer-tests.yaml
.werft/platform-trigger-werft-cleanup.yaml
.werft/workspace-run-integration-tests.yaml
dev/image/Dockerfile

Fixes prebuild tasks by updating to the most recent `workspace-full` supporting Jammy.
Also, introduces build output (results and logs) for dev/* assets in the [build](https://github.com/gitpod-io/gitpod/blob/6d09aa38f00859c456ba0814cf71edc73d774fb1/.github/workflows/build.yml) Github Action workflow.
Fixes # n/a
Open a Gitpod Workspace from this PR, observe prebuild tasks run now. Thank you, @axonasif for the fix in workspace-images!
Also, [see this comment and links within](https://github.com/gitpod-io/gitpod/pull/17019#discussion_r1148577810) to observe the dev/* build output now.
```release-note
NONE
```
<details>
</details>
<details>
Add …

[dev image] update base image

---

components/BUILD.yaml

Had some false positives with the existing `.only` check (would fail for any changes that included the word `only`. I've adjust the regex to match a bit more precisely.
Fixes #
If the build passes then it should be a decent test, as the line change in this PR includes the words `only`, which would have failed it previously.
```release-note
NONE
```
<details>
</details>
<details>
</details>

Adjust mocha .only check

---

components/ws-daemon/pkg/controller/snapshot_controller.go
components/ws-daemon/pkg/controller/workspace_controller.go
components/ws-daemon/pkg/controller/workspace_operations.go

- Harmonize names
- Introduce interface for workspace operations so that we can mock it in tests
Fixes WKS-14
```release-note
None
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] [WKS-14] Refactor workspace operations

---

components/ws-manager-mk2/service/manager.go

Same implementation as mk1
Context: https://gitpod.slack.com/archives/C02EN94AEPL/p1680006550822509?thread_ts=1680000631.745719&cid=C02EN94AEPL
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Implement DescribeCluster

---

components/common-go/experiments/types.go

[common-go] force set configcat log level to error
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[common-go] force set configcat log level to error

---

.github/workflows/jetbrains-integration-test.yml
dev/jetbrains-test/BUILD.yaml
dev/jetbrains-test/src/main/kotlin/io/gitpod/jetbrains/launcher/IdeDownloader.kt
dev/jetbrains-test/src/test/kotlin/io/gitpod/jetbrains/launcher/GatewayLauncherTest.kt
dev/jetbrains-test/test.sh

It allows to run test against platform changes to stable GW plugin.
Fixes #
Check out https://github.com/gitpod-io/gitpod/actions/runs/4552408927/jobs/8028172989 and corresponding GW tests actions https://github.com/gitpod-io/gitpod/actions/workflows/jetbrains-integration-test.yml
```release-note
NONE
```
<details>
</details>
<details>
</details>

[jb] support testing of stable GW

---

components/dashboard/src/Login.tsx
components/dashboard/src/login/SSOLoginForm.tsx
components/dashboard/src/provider-utils.tsx
components/gitpod-db/go/dbtest/oidc_client_config.go
components/gitpod-db/go/oidc_client_config.go
components/gitpod-db/go/oidc_client_config_test.go
components/gitpod-db/go/team.go
components/gitpod-db/go/team_test.go
components/gitpod-protocol/src/protocol.ts
components/public-api-server/pkg/apiv1/oidc.go
components/public-api-server/pkg/apiv1/oidc_test.go
components/public-api-server/pkg/oidc/oauth2.go
components/public-api-server/pkg/oidc/router.go
components/public-api-server/pkg/oidc/router_test.go
components/public-api-server/pkg/oidc/service.go
components/public-api-server/pkg/oidc/service_test.go

Adds a `Sign in with SSO` option to the Login screen.
This feature is guarded by a hidden flag, as it's hard to use feature flags for that. One can enable it by 
Fixes https://github.com/gitpod-io/gitpod/issues/15967
Fixes WEB-37
1. Enable this feature by adding some magic experimental flag to local storage:
```localStorage.setItem("gitpod-ui-experiments", `{"ssoLogin": true}`)```
2. Create OIDC SSO integration for a team
3. Log out and find the `Sign in with SSO` button
```release-note
NONE
```
<details>
</details>
<details>
</details> …

Sign in with SSO

---

dev/loadgen/configs/prod-benchmark.yaml
dev/loadgen/pkg/loadgen/executor.go
dev/loadgen/pkg/observer/success.go

Some loadgen improvements:
- Add workspace tasks to exercise some load on changing port visibility
- In `executor.go`, resubscribe to ws-manager if the connection closes (e.g. on restarting ws-manager-mk2)
- Log IDs of workspaces that stopped early
Tested in a load test
```release-note
NONE
```
<details>
</details>
<details>
</details>

[loadgen] Resubscribe, log ids of stopped workspaces, change port visibility

---

.github/workflows/build.yml

to fix dispatching GH action workflow for GW: https://github.com/gitpod-io/gitpod/actions/runs/4555380954/jobs/8034825391?pr=17078
Fixes #
merge and rerun GW automation
```release-note
NONE
```
<details>
</details>
<details>
</details>

[jb] fix running JB integration tests triggered by PR

---

components/gitpod-db/src/periodic-deleter.ts

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] Log ticks of periodic db deleter

---

components/gitpod-db/src/periodic-deleter.ts
components/server/src/server.ts

Quorum leader is re-elected whenever the leader got unresponsive, but the periodic deleter is only considering this once on server init. This can lead to a state where no deleter is active.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server/db] resume periodic deleter on quorum re-election

---

components/server/src/auth/generic-auth-provider.ts

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[server] improve logging on logins

---

components/dashboard/src/user-settings/Preferences.tsx
components/dashboard/src/user-settings/SelectIDE.tsx

Some small cleanup to the code in user prefs around updating the editor options.
* Adjusted user update logic to avoid mutating user object in react state directly.
* Also cleaned up a few places that needed a `useCallback()` wrapper.
Fixes WEB-39
* Go to user preferences
* Change Editor
* Click Account in side, then click Preferences
* Ensure your Editor change is reflected
* Reload page and ensure it's still reflected.
```release-note
NONE
```
<details>
</details>
<details>
</details> …

User Pref Editor change cleanup

---

.github/workflows/jetbrains-update-plugin-platform-template.yml
.github/workflows/jetbrains-updates.yml

Automation is reusing the same branch and same preview envs correspondingly. On harvester there are various issues networks, like stale load balancer for long living preview envs, or network rate limitting. This PR is switching to GCE to avoid it.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[jb] run integrtion tests with gce to avoid networking issues

---

components/gitpod-db/src/periodic-deleter.ts

This is a follow-up to https://github.com/gitpod-io/gitpod/pull/17092. It's failing to catch up the amount of entries to be deleted.
```release-note
NONE
```
<details>
</details>
<details>
</details>

Limit rows to be deleted per run

---

.github/workflows/jetbrains-integration-test.yml
.github/workflows/jetbrains-update-plugin-platform-template.yml

It should fix stable auto upgrade. Before it will set the upper boundary bogusly.
Fixes #
Merge and rerun the automation.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[jb] fix platform version range for stable GW plugin

---

components/dashboard/src/App.tsx
components/dashboard/src/Login.tsx
components/dashboard/src/Setup.tsx
components/dashboard/src/components/ErrorBoundary.tsx
components/dashboard/src/components/error-boundaries/QueryErrorBoundary.tsx
components/dashboard/src/components/error-boundaries/ReloadPageErrorBoundary.tsx
components/dashboard/src/hooks/use-user-loader.ts
components/dashboard/src/index.tsx

Adding a new `<QueryErrorBoundary>` to handle expected api errors that queries may throw. These will currently only come from the 2 queries we've enabled the `useErrorBoundary` option on.
* `getLoggedInUser()` - [code](https://github.com/gitpod-io/gitpod/blob/d7a546371fb2d1eb132ee1923270d8a18f7749a3/components/dashboard/src/hooks/use-user-loader.ts#L23)
* `listTeams()` - [code](https://github.com/gitpod-io/gitpod/blob/d7a546371fb2d1eb132ee1923270d8a18f7749a3/components/dashboard/src/data/organizations/orgs-query.ts#L31)
When these queries throw, they're caught first by the `<QueryErrorBoundary>`, which will handle any errors where `code` is one of `NOT_AUTHENTICATED` or `SETUP_REQUIRED` (we can add more in the future as we need). If it's not one of those errors, we re-throw it, and let it …

handle api errors in error boundary

---

components/gitpod-db/src/tables.ts

```
PRIMARY KEY (userId,uri)
```
This PR fixes the `d_b_user_storage_resource` entry in tables.ts accordingly. 
```release-note
NONE
```
<details>
</details>
<details>
</details>

[gitpod-db] fix PK entry

---

components/gitpod-db/src/periodic-deleter.ts

First cycle took ~20mins, that appears to be be still to much. 
```release-note
NONE
```
<details>
</details>
<details>
</details>

[db-deleter] lower limit of queries for smaller ticks

---

components/gitpod-cli/go.sum
components/public-api-server/go.mod
components/public-api-server/go.sum
components/public-api/go/go.mod
components/public-api/go/go.sum

Includes a fix from 1.4.0 where panics are logged more explicitly
https://github.com/bufbuild/connect-go/releases/tag/v1.4.0
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

Upgrade to connect-go 1.5.2

---

README.md

Relates to: 
- https://github.com/gitpod-io/website/pull/3553
[Internal context](https://gitpod.slack.com/archives/C01KGM9DVRC/p1680093542160309)
```release-note
NONE
```

Remove roadmap references from the README

---

components/public-api-server/pkg/apiv1/team.go

I'll be adding a regression test in a follow-up PR, just want to get this fix in quick
Fixes #
1. Preview
2. Sign in
3. Repeatedly reload /workspaces page until you exhaust the rate limit imposed by `server`
4. Eventually, you should get a "rate limited" response, but not a 500 from the ListTeams endpoint
```release-note
NONE
```
<details>
</details>
<details>
</details>

[public-api] Fix panic due to incorrect err ref

---

dev/preview/workflow/preview/deploy-gitpod.sh

Prerequisite for https://github.com/gitpod-io/gitpod/pull/17074
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

Configure LinkedIn in preview environments

---

components/dashboard/src/app/AppRoutes.tsx

As discussed [here](https://gitpod.slack.com/archives/C02EN94AEPL/p1680253858918529?thread_ts=1680246650.399619&cid=C02EN94AEPL).
Fixes #
- try visit https://gpl-switch-redirect.preview.gitpod-dev.com/switch-to-payg?personalSubscription=asd
```release-note
NONE
```
<details>
</details>
<details>
</details>

[dashboard] Redirect `/switch-to-payg` to docs

---

components/ws-manager-mk2/controllers/status.go
install/installer/pkg/components/ws-manager-mk2/role.go
install/installer/pkg/components/ws-manager-mk2/rolebinding.go

Ports https://github.com/gitpod-io/gitpod/issues/12021 to mk2. Fixes workspace failure false-positives where the pod's container status ends up in `ContainerStatusUnknown`
Fixes WKS-22
Tested in an ephemeral cluster using loadgen to spin up 100 workspaces and then stopping them. Without this fix, several of them would "fail" with `The container could not be located when the pod was terminated` or `The container could not be located when the pod was deleted.  The container used to be Running`. With this fix none of them do. 
For the workspaces that were failing before the fix, backups were being taken, so nothing was really failing.
```release-note
NONE
```
<details>
</details> …

[ws-manager-mk2] Ignore container killed failures

---

operations/observability/mixins/workspace/dashboards/components/ws-manager-mk2.json

* Fix startup time panels, and change to Heatmap
* Remove Probe startup time panel
* Add ImageBuild and Prebuild startup times
* Add new `workspace_failure_total` metrics panel
* Better coloring of timeseries
**Before:**
**After:**
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Dashboard improvements

---

test/tests/components/ws-manager/additional_repositories_test.go
test/tests/components/ws-manager/content_test.go
test/tests/components/ws-manager/prebuild_test.go
test/tests/components/ws-manager/tasks_test.go
test/tests/workspace/contexts_test.go
test/tests/workspace/example_test.go
test/tests/workspace/git_hooks_test.go
test/tests/workspace/git_test.go

Fix loop closures, some parallel tests were accessing the loop variable which would most likely have changed value at the time it gets accessed
Potentially might fix some flakiness with the tests?
This should no longer pick up any loopclosure lint errors:
```
cd test
golangci-lint run | grep closure
```
```release-note
NONE
```
<details>
</details>
<details>
</details>

[test] Fix loop closures

---

WORKSPACE.yaml
install/installer/pkg/components/workspace/ide/constants.go

Update code to `1.77.0`
```release-note
NONE
```

VS Code Browser release `1.77.0`

---

dev/preview/infrastructure/modules/dns/dns.tf

add local ssh dns to preview env
Related https://github.com/gitpod-io/gitpod/issues/16836
- Build preview env
- Ping `test.lssh.<preview_env_host>` to see if it points to localhost
✅ 
```
➜  ~ ping test.lssh.hw-preview-dns.preview.gitpod-dev.com
PING test.lssh.hw-preview-dns.preview.gitpod-dev.com (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.073 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.231 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.086 ms
^C
--- test.lssh.hw-preview-dns.preview.gitpod-dev.com ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.073/0.130/0.231/0.072 ms
➜  ~ 
```
```release-note
NONE
``` …

[preview] add local ssh dns to preview env

---

components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/workspace_controller.go

* If a headless task container exits with a non-empty `Message`, consider it a failure (as we do with mk1).
* Always log workspace status in reconciliations. We can disable at a later point, but without it it becomes almost impossible to debug workspace/pod state changes.
* In addition, also log the pod status
In a preview env, create an image build, restart ws-daemon during the build (which currently causes the build to fail), and observe the workspace exits with a `Failed` condition and doesn't transition through `Initializing` after `Running`.
```release-note
NONE
```
<details>
</details>
<details> …

[ws-manager-mk2] Extract headless task failure (WKS-18)

---

components/ws-daemon/pkg/controller/workspace_operations.go
components/ws-manager-mk2/service/manager.go
test/README.md
test/tests/components/ws-manager/git_status_test.go

Fixes git status not being reported for mk2 workspaces. Also adds an e2e test to check this.
Fixes WKS-28
Run e2e tests, run in preview env and check any workspace file/git changes are shown after the workspace is stopped.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[ws-manager-mk2] Fix git status

---

components/server/ee/src/workspace/gitpod-server-impl.ts

This change skips queued prebuilds, so that users will get a fresh workspace instead of waiting for a prebuild that has not even started yet.
Also fixes a null pointer error (https://linear.app/gitpod/issue/WEB-82/cannot-read-properties-of-undefined-reading-id), that occurs when we try to obtain an instanceid for a queued prebuild in order to let users wait for them to finish.
Fixes https://linear.app/gitpod/issue/WEB-82/cannot-read-properties-of-undefined-reading-id
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[server] don't wait for queued prebuilds

---

components/dashboard/src/components/toasts/Toast.tsx
components/dashboard/src/components/toasts/Toasts.tsx
components/dashboard/src/components/toasts/reducer.ts
components/dashboard/src/data/current-user/update-mutation.ts
components/dashboard/src/index.tsx
components/dashboard/src/user-settings/Preferences.tsx
components/dashboard/src/user-settings/SelectIDE.tsx
components/dashboard/tailwind.config.js

**WIP**
Adding Toasts and updating User Preferences to use them for dotfiles and timeout fields. Also tweaked those forms on user prefs page to have a bit more feedback for the UX.
Some considerations:
* Opted for animate in from right for toasts as it's a slightly simpler thing to implement that centered toasts that animate in from bottom. We can always revisit though.
* Deferred adding specific types of toasts to reduce initial scope, i.e. success/error/info etc. We should add those as a followup though.
| 1 | 2 |
| <img width="805" alt="image" src="https://user-images.githubusercontent.com/367275/227669101-35c648dd-1e8d-4e6f-af58-7f72f8b842b6.png"> | <img width="605" alt="image" src="https://user-images.githubusercontent.com/367275/227669166-3b54fe37-56c3-4c40-8435-6 …

Adding Toasts

---

.github/pull_request_template.md

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

Add /hold to all PRs by default (through template) (WEB-92)

---

components/ws-daemon/nsinsider/main.go
components/ws-daemon/pkg/content/hooks.go
components/ws-daemon/pkg/content/service.go
components/ws-daemon/pkg/daemon/config.go
components/ws-daemon/pkg/daemon/daemon.go
components/ws-daemon/pkg/iws/iws.go
install/installer/pkg/cluster/checks.go
install/installer/pkg/components/ws-daemon/configmap.go
install/installer/pkg/config/v1/experimental/experimental.go
install/installer/pkg/config/v1/experimental/validation.go

The default workspace network cell uses a private range that can conflict with some pre-existing network in the VPC that creates a network routing error (`no route to host`) when we try to reach any IP address of the such subnet.
For this scenario, we introduce a new ws-daemon parameter that allows us to set a different subnet. If the parameter is not present, we use the default value we use.
fixes WKS-50
- Use the default configuration
- Verify workspaces run
- Check the IP addresses in the workspace. The value should be `10.0.5.2/30`
- Change the installer configuration to set a different subnet
- Verify workspaces run
- Check the IP addresses in the workspace. The value should match the subnet, and the workspace should have the second IP address in the range.
```release-note
NONE
``` …

Add new feature for custom workspace network CIDR

---

components/dashboard/src/user-settings/Account.tsx

Minor spacing change to the delete account button under `/account`. Seems like a small side effect from the typography components added in https://github.com/gitpod-io/gitpod/pull/16673.
This will add a ~spacing-scale-3 (`1rem`/`16px`) between the heading and the button.
|-|-|
| <img width="697" alt="button-before" src="https://user-images.githubusercontent.com/120486/229582741-88d0ca04-079e-40f8-8680-b8485f499ce6.png"> | <img width="697" alt="button-after" src="https://user-images.githubusercontent.com/120486/229582745-db936e96-71e4-4531-a38f-88100b35bfc1.png"> |
Posting for visibility below a screenshot from **Foundations / Spacing** in the component library in our Figma team, to justify the change.
| Spacing Guidelines |
|-|
| …

Update delete account button spacing

---

components/ws-manager-api/go/crd/v1/workspace_types.go
components/ws-manager-mk2/controllers/metrics.go
components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/workspace_controller.go
components/ws-manager-mk2/controllers/workspace_controller_test.go

Introduce an `EverReady` condition:
* Gets set when the workspace container becomes `Ready`, i.e. when content init succeeded and the supervisor readiness check passes.
This condition then allows us to:
* Count startup failure metrics similarly to mk1: a workspace that reaches the `Stopped` phase without ever becoming ready
* Not moving a workspace from `Running` to `Initializing` if its container becomes unready. Once a workspace becomes ready it should not move backwards in phase
To track workspace failures that happen after startup, a new `workspace_failure_total` metric is added which gets incremented whenever a workspaces receives the `Failed` condition. This includes content init and disposal failures, but also all other possible failures.
The `workspace_stops_total` metric is also …

[ws-manager-mk2] Refactor metrics with EverReady condition

---

components/dashboard/src/data/workspaces/resolve-context-query.ts
components/dashboard/src/start/StartWorkspace.tsx
components/dashboard/src/workspaces/CreateWorkspacePage.tsx
components/dashboard/src/workspaces/WorkspaceEntry.tsx
components/gitpod-protocol/src/gitpod-service.ts
components/server/src/workspace/gitpod-server-impl.ts

Several smaller improvements to the create workspace page
- apply the same preprocessing of the given contextURL for resolving a workspace context that is applied when creating a workspace.
- handle `referrer` prefix URLs, so that the workspace starts immediately
- ensure createWorkspace is not called multiple times
- checks and displays directly if a workspace on the same revision is already running
cc @gtsiolis 
Fixes https://linear.app/gitpod/issue/WEB-68/startworkspacewithoptions-invalid-url-error-on-missing-scheme
Fixes https://linear.app/gitpod/issue/WEB-81/context-urls-with-referrer-dont-show-modal
Fixes https://linear.app/gitpod/issue/WEB-73/[new-workspace-page]-dont-start-more-than-one-workspace-with-enter
- Try starting a workspace with a contextURL that lacks the https:// part: …

[Create WS] Various fixes

---

components/usage/pkg/server/server.go
install/installer/pkg/common/constants.go
install/installer/pkg/common/net.go
install/installer/pkg/components/public-api-server/configmap.go
install/installer/pkg/components/public-api-server/configmap_test.go
install/installer/pkg/components/server/configmap.go
install/installer/pkg/components/server/constants.go
install/installer/pkg/components/usage/configmap.go
install/installer/pkg/components/usage/configmap_test.go

* Adds server address to usage config - needed for usage to talk to server
* Refactors ClusterAddress construction to use common
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>

[usage] Add server address to config - WEB-94

---

components/dashboard/src/admin/BlockedRepositories.tsx
components/dashboard/src/admin/Settings.tsx
components/dashboard/src/admin/UserDetail.tsx
components/dashboard/src/components/forms/CheckboxInputField.tsx
components/dashboard/src/components/forms/InputFieldHint.tsx
components/dashboard/src/projects/ProjectSettings.tsx
components/dashboard/src/projects/ProjectVariables.tsx
components/dashboard/src/teams/TeamSettings.tsx
components/dashboard/src/user-settings/Integrations.tsx
components/dashboard/src/user-settings/Notifications.tsx
components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
components/dashboard/src/user-settings/SelectIDE.tsx

- Migrating to the `CheckBoxInput` component instead of `CheckBox` component for consistency.
Fixes #16768
```release-note
Migrate all checkbox inputs to the new CheckBoxInput component for consistency
```
<details>
</details>
<details>
</details>

Migrate all checkbox inputs to the `CheckBoxInput` component

---

components/ws-daemon/go.mod
components/ws-daemon/go.sum
components/ws-daemon/nsinsider/go.mod
components/ws-daemon/nsinsider/go.sum
install/installer/go.mod
install/installer/go.sum

To get several fixes https://github.com/google/nftables/compare/ec1e802faf9426e1f27cd8bfa8434e110bae5146...main
```release-note
NONE
```
<details>
</details>
<details>
</details>

Update github.com/google/nftables to v0.1.0

---

WORKSPACE.yaml
install/installer/pkg/components/workspace/ide/constants.go

Update code to `1.77.2`
Implements https://github.com/microsoft/vscode/releases/tag/1.77.2
```release-note
NONE
```

 VS Code Browser release `1.77.2`

---

dev/image/Dockerfile

Such that we can 
* Run tests against an intance of redis
* Use the cli to interact with redis
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

[dev] Add redis to workspace image

---

components/public-api-server/pkg/billingservice/client.go

* Missed adding the necessary invocation when doing the RPC call stack setup.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

[stripe] Actually call the billing service :facepalm: WEB-62

---

components/dashboard/src/admin/BlockedRepositories.tsx
components/dashboard/src/admin/Settings.tsx
components/dashboard/src/admin/UserDetail.tsx
components/dashboard/src/components/forms/CheckboxInputField.tsx
components/dashboard/src/components/forms/InputField.tsx
components/dashboard/src/onboarding/StepOrgInfo.tsx
components/dashboard/src/projects/ProjectSettings.tsx
components/dashboard/src/projects/ProjectVariables.tsx
components/dashboard/src/teams/TeamSettings.tsx
components/dashboard/src/user-settings/Integrations.tsx
components/dashboard/src/user-settings/Notifications.tsx
components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
components/dashboard/src/user-settings/SelectIDE.tsx

This is a PR to facilitate @Devansu-Yadav's contributions in #16813 
I made a couple changes on top of the ones in the linked PR.
* To avoid needing a `CheckboxInputContainer` wrapper at times, I reworked the `CheckboxInputField` into a more explicit `CheckboxListField`, and `CheckboxInput` into `CheckboxInputField`. This means that in most cases, you can use `<CheckboxInputField/>` and have the proper form styles/spacing without needing to add any wrapper components.
* Removed the un-needed `value` props passed in a few spots.
Fixes WEB-115, https://github.com/gitpod-io/gitpod/issues/16768
**Preview Env:** https://bmh-devans98e355c547.preview.gitpod-dev.com/workspaces
These changes were tested previously in #16813 - but can also be tested in the preview environment by visiting different …

Migrate checkbox component

---

components/dashboard/src/components/LinkButton.tsx
components/dashboard/src/user-settings/Plans.tsx
components/dashboard/src/utils.ts
components/dashboard/src/workspaces/WorkspaceEntry.tsx

This fixes the last remaining lint errors in dashboard.
* Swaps some uses of `<a>` tags w/ onClick handlers to use a new `<LinkButton/>` component, which is a `<button>` styled to look like a link. This is the preferred way to handle this type of UX for a11y reasons. Here's a screenshot of it applied to to old Plans page, which was the only place atm that had these lint errors, but we should be able to use this component for any future areas as well.
Fixes WEB-112
**Preview Env:** https://bmh-link-button.preview.gitpod-dev.com/user/plans
* Can run `yarn lint` from dashboard component manually to verify there are no lint errors. I ran it and verified it myself though too.
* To verify the `<LinkButton/>` changes, can navigate to the old Plans page, and you should be able to see them used in …

Fixing remaining dashboard lint errors

---

.github/pull_request_template.md

To avoid having to fill in NONE in majority of cases, saves a couple of secs on each PR
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

Default to release note NONE in PR template

---

components/dashboard/src/App.tsx
components/dashboard/src/Login.tsx
components/dashboard/src/Setup.tsx
components/dashboard/src/components/error-boundaries/QueryErrorBoundary.tsx
components/dashboard/src/components/error-boundaries/ReloadPageErrorBoundary.tsx
components/dashboard/src/hooks/use-user-loader.ts
components/dashboard/src/index.tsx

This is a followup attempt at #17086 after we had to revert it due to an issue it caused for non-authenticated users and a delay in showing the login page.
Disabling `retry` on the current user query fixes the issue that caused a delay in showing the login page. Without it, the query would retry (3 times) since a 401 is an error that's thrown.
Fixes WEB-70
**Preview Env:** https://bmh-top-le2c3d5f5693.preview.gitpod-dev.com/workspaces
* On the preview environment, test logging in and out.
* Ensure there isn't a significant delay in showing the login page when you're logged out.
If you look at the websocket, you should only see one call for `getLoggedInUser` when the login page displays.
```release-note
NONE
``` …

Top Level ErrorBoundary second attempt

---

.github/workflows/jetbrains-update-plugin-platform-template.yml
.github/workflows/jetbrains-updates.yml

[github action] use roboquat to create PR
This PR also remove auto approve, because it's doesn't work
Fixes #
See this PR https://github.com/gitpod-io/gitpod/pull/17185 it created by `roboquat` and github action is running.
```release-note
NONE
```
<details>
</details>
<details>
</details>

[github action] use roboquat to create PR

---

.github/workflows/build.yml

Use a separate leeway cache bucket for the main branch
Fixes #
see github action job, in this PR it should be `gitpod-core-leeway-cache-branch`
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

[github action] Use a separate leeway cache bucket for the main branch

---

WORKSPACE.yaml
install/installer/pkg/components/workspace/ide/constants.go

Update code to `1.77.3`
```release-note
NONE
```

VS Code Browser release `1.77.3`

---

components/dashboard/src/components/Button.tsx
components/dashboard/src/contexts/FeatureFlagContext.tsx
components/dashboard/src/onboarding/OnboardingStep.tsx
components/dashboard/src/onboarding/StepUserInfo.tsx
components/dashboard/src/onboarding/UserOnboarding.tsx

Wraps the connect with linkedin part of new user onboarding w/ a new feature flag - `linkedinConnectionForOnboarding`. If the flag is off the experience will be like what's on gitpod.io today.
| FF Off | FF On |
| ![image](https://user-images.githubusercontent.com/367275/231574846-1e86bcbf-78e8-40d0-bbc2-a25fed36059e.png) | ![image](https://user-images.githubusercontent.com/367275/231575678-6cddd529-de9b-4a29-b976-5f0fcac6c190.png) | 
* Go through the onboarding flow on the preview environment: https://bmh-ff-conf3e3f052bf.preview.gitpod-dev.com/workspaces?onboarding=force
* With `linkedinConnectionForOnboarding` off, it should be the same experience as what's on gitpod.io today where you must enter in an email address.
* I wasn't able to fully going through with …

wrap ff around connect with linkedin

---

components/dashboard/src/Login.tsx
components/dashboard/src/data/auth-providers/auth-provider-query.ts
components/dashboard/src/data/workspaces/resolve-context-query.ts
components/dashboard/src/projects/NewProject.tsx
components/dashboard/src/start/CreateWorkspace.tsx
components/dashboard/src/user-settings/Integrations.tsx
components/dashboard/src/workspaces/CreateWorkspacePage.tsx
components/server/src/workspace/gitpod-server-impl.ts

This pull request improves the handling of context resolution errors by refactoring the code and introducing new error messages. It adds a new method resolveContext to the GitpodServer interface and handles errors separately using the handleError method. Additionally, it updates the usage of authProviders and includes the useAuthProviders hook to manage auth provider data within the components. Overall, this improves the user experience by providing more informative error messages and streamlining the code.
Fixes #16977
Fixes WEB-67
Login to the preview environment and try starting a workspace on a private repository.
E.g: https://svenefftin78d9e41e4b.preview.gitpod-dev.com/#github.com/gitpod-io/gitpod-dedicated
```release-note
NONE
```
Run Leeway …

[dashboard] handle context resolution errors

---

components/dashboard/src/workspaces/CreateWorkspacePage.tsx

This changes keeps the "Create Workspace" button enabled during context resolution, so that users don'T need to wait for the context resolution to happen nor get distracting by a flashing button changing its state.
Fixes WEB-136
Use create page and see that "loading ..." state doesn't happen anymore. 
https://se-button-enabled.preview.gitpod-dev.com/new/#github.com/gitpod-io/gitpod
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[dashboard] create ws keep button enabled

---

components/dashboard/src/menu/OrganizationSelector.tsx
components/dashboard/src/workspaces/CreateWorkspacePage.tsx

This PR aims to maintain the context url from the new workspace page even as the org changes.
As the context url changes, this gets set in the url hash now, and the org switcher links have a special case to handle if we're on the `/new` route so that state from the url is maintained.
I would have liked a solution that didn't require a special case for the org switching urls, but considering other approaches of trying to track the state of the new workspace page, and persist/reload it in the right places, this felt simpler. I also opted to not try and maintain the other values on that form (the ide and ws class). We could explore tracking those as well (as query params maybe?) in a followup.
Fixes WEB-120
**Preview Env:** https://bmh-keep-c7205484caf.preview.gitpod-dev.com/new/#https://gith …

Persist new workspace contextURL on org change

---

install/installer/pkg/components/server/authpki.go
install/installer/pkg/components/server/constants.go
install/installer/pkg/components/server/objects.go

Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

[server] Generate key-pair for signing JWT sessions WEB-100

---

components/server/src/config.ts
install/installer/pkg/components/server/authpki.go
install/installer/pkg/components/server/configmap.go
install/installer/pkg/components/server/configmap_test.go
install/installer/pkg/components/server/deployment.go
install/installer/pkg/components/server/types.go

Takes secret generated from https://github.com/gitpod-io/gitpod/pull/17205 and mounts and loads the private/public keys into server
gitpod:summary
Fixes #
You can see this in action in https://github.com/gitpod-io/gitpod/pull/17200 PR's preview env
1. Preview kubectx
2. Check auth-pki mounted as volume
3. Check auth-pki refrences in servers' config
4. Check server is running
```release-note
NONE
```
<details>
</details>
<details>
</details> …

[server] Load auth-pki into server config - WEB-100

---

components/public-api/go/config/config.go
install/installer/pkg/common/constants.go
install/installer/pkg/components/public-api-server/authpki.go
install/installer/pkg/components/public-api-server/configmap.go
install/installer/pkg/components/public-api-server/configmap_test.go
install/installer/pkg/components/public-api-server/deployment.go
install/installer/pkg/components/public-api-server/deployment_test.go
install/installer/pkg/components/server/authpki.go
install/installer/pkg/components/server/constants.go

Mounts `auth-pki` secret onto public api, and feeds paths into public api config. This will be needed to validate incoming JWT cookies. 
The mounted files are not used in this PR, will be used in subsequent ones.
<ul>
<li><b>🏷️ Name</b> - mp-papi-mo79f2f5a707</li>
<li><b>🔗 URL</b> - <a href="https://mp-papi-mo79f2f5a707.preview.gitpod-dev.com/workspaces" target="_blank">mp-papi-mo79f2f5a707.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
Fixes #
1. Preview
2. Public …

[papi] Mount Auth PKI - WEB-101

---

dev/preview/workflow/config/monitoring-satellite.yaml
dev/preview/workflow/preview/deploy-monitoring-satellite.sh

In an existing preview env, we still see `certmanager` namespace :upside_down_face: :
```
gitpod /workspace/gitpod (aledbf/remove-psp) $ kubens
cert-manager
certmanager
default
kube-node-lease
kube-public
kube-system
monitoring-satellite
rook-ceph
werft
```
Fixes WKS-71
Assert this preview environment has `cert-manager` and not `certmanager` namespace, and start a workspace in it.
```
gitpod /workspace/gitpod (kylos101/certmanager) $ kubectx -c
kylos101-certmanager
gitpod /workspace/gitpod (kylos101/certmanager) $ kubens
cert-manager
default
kube-node-lease
kube-public
kube-system
monitoring-satellite
rook-ceph
werft
gitpod /workspace/gitpod (kylos101/certmanager) $ kubectl get all -n cert-manager
NAME                                          READY   STATUS      RESTARTS   AGE …
```

[preview] Use cert-manager namespace for satellite, not certmanager namespace

---

install/installer/cmd/mirror_list.go

Makes it possible to extract the list of images, without having to provide a completely valid configuration file.
```bash
installer mirror list --config gitpod.config.yaml --strict-parse=false --repository test --domain test.com
[
{
"original": "b.gcr.io/cloudsql-docker/gce-proxy:1.11",
"target": "test/cloudsql-docker/gce-proxy:1.11"
},
{
"original": "docker.io/bitnami/bitnami-shell:11-debian-11-r60",
"target": "test/bitnami/bitnami-shell:11-debian-11-r60"
},
{
"original": "docker.io/bitnami/minio:2022.12.12-debian-11-r0",
"target": "test/bitnami/minio:2022.12.12-debian-11-r0"
}
...
]
```
Fixes #
```release-note
NONE
```
<details>
</details>
<details> …

[installer] add flags with ability to overwrite [repository, domain] in the config file for `mirror list`

---

components/server/package.json
components/server/src/auth/jwt.spec.ts
components/server/src/auth/jwt.ts
components/server/src/auth/login-completion-handler.ts
components/server/src/container-module.ts
components/server/src/prometheus-metrics.ts
components/server/src/session-handler.ts

On succesful sign-in, a JWT cookie is generated and stored in the client session.
Feature is behind a feature flag.
* Fixes WEB-100
* Depends on https://github.com/gitpod-io/gitpod/pull/17214
1. Preview
2. Sign-in
3. Observe there's a new cookie assigned with `_jwt_` suffix
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

[server] Set JWT cookie on sign-in  WEB-100

---

components/supervisor/pkg/supervisor/notification.go
components/supervisor/pkg/supervisor/services.go

gitpod:summary
Fixes #
nothing, merge if tests are green
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

[supervisor] log potentially leaking grpc streams

---

components/ide/jetbrains/backend-plugin/gradle-latest.properties

This PR updates the Platform Version from JetBrains Backend Plugin (EAP) to the latest version.
<details>
3. Start a workspace using this repository: https://github.com/gitpod-samples/spring-petclinic
</details>
```release-note
NONE
```
_This PR was created automatically with GitHub Actions using [this](https://github.com/gitpod-io/gitpod/blob/main/.github/workflows/jetbrains-update-plugin-platform-template.yml) …

[JetBrains] Update Platform Version from JetBrains Backend Plugin (EAP)

---

.github/pull_request_template.md

gitpod:summary
Fixes #
<details>
</details>
<details>
</details>
/hold

Remove release note from PR template

---

install/installer/pkg/components/server/configmap.go
install/installer/pkg/components/server/constants.go
install/installer/pkg/components/server/types.go
install/installer/pkg/config/v1/experimental/experimental.go
install/installer/pkg/config/versions/versions.go

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[installer] Remove chargebee refs - WEB-144

---

components/server/src/config.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] Remove chargebee config reading WEB-144

---

components/gitpod-db/src/typeorm/migration/1681806678725-DropTheiaPlugin.ts

* Depends on https://github.com/gitpod-io/gitpod/pull/17255
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[db] Drop d_b_theia_plugin - WEB-168

---

components/gitpod-db/src/typeorm/migration/1681808788247-DropUserMessageView.ts

* Depends on https://github.com/gitpod-io/gitpod/pull/17258
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[db] Drop d_b_user_message_view_entry - WEB-172

---

components/dashboard/src/app/AppRoutes.tsx

Fallout from [this change](https://github.com/gitpod-io/gitpod/pull/17242/files#diff-7d06461d6c55d4b24d38b66745a49c9a28e9992fccb8eb7459bc91f4d4583e11L230).
Fixes WEB-180
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[dashboard] Fix broken /usage redirect

---

.github/workflows/build.yml

[GHA] use different local cache with main branch, this will make main build clean
gitpod:summary
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

[GHA] use different local cache with main branch

---

components/server/src/config.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] Remove reading of license file - WEB-171

---

.github/workflows/ide-integration-tests.yml

This PR fixes integration test, because it missing some params. And also change `infrastructure_provider` to gce, make test more stable
```
gateway_test.go:178: POST https://api.github.com/repos/gitpod-io/gitpod/actions/workflows/jetbrains-integration-test.yml/dispatches: 422 No ref found for:  []
```
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>

Fix IDE integration test

---

components/dashboard/src/contexts/FeatureFlagContext.tsx
components/dashboard/src/menu/OrganizationSelector.tsx

Fixes WEB-184
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[dashboard] Remove superfluous usage_view feature flag

---

components/dashboard/src/components/SelectIDEComponent.tsx
components/dashboard/src/contexts/FeatureFlagContext.tsx
components/gitpod-protocol/src/ide-protocol.ts
components/ide-service-api/go/config/ideconfig.go
install/installer/pkg/components/ide-service/ide_config_configmap.go

Introduces a new feature flag which enables IDEs to be optionally marked as `experimental`. When an IDE is `experimental`, it will only show to users whose ConfigCat response for `experimentalIdes` returns true. 
<ul>
<li><b>🏷️ Name</b> - ide-experi28316dc360</li>
<li><b>🔗 URL</b> - <a href="https://ide-experi28316dc360.preview.gitpod-dev.com/workspaces" target="_blank">ide-experi28316dc360.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
Needed to introduce …

`experimental` IDEs feature flag

---

components/server/ee/src/prebuilds/prebuild-manager.ts

The logic to retrieve organizationId on prebuilds was broken.
Fixes WEB-85
<ul>
<li><b>🏷️ Name</b> - se-prebuild-orgid</li>
<li><b>🔗 URL</b> - <a href="https://se-prebuild-orgid.preview.gitpod-dev.com/workspaces" target="_blank">se-prebuild-orgid.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
Add …

[server] fix prebuild organizationId

---

components/server/src/workspace/workspace-starter.ts

Defaults to true
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] Remove usage of do_not_wait_for_ws_manager flag

---

install/installer/pkg/components/workspace/ide/constants.go

to pick up changes to validate links: https://github.com/gitpod-io/gitpod-code/commit/0b2fb39d35def04293397c07b29cb44cc3b14612
Fixes #
- Smoke test VS Code Browser.
<ul>
<li><b>🏷️ Name</b> - ak-code-vadf63c56a26</li>
<li><b>🔗 URL</b> - <a href="https://ak-code-vadf63c56a26.preview.gitpod-dev.com/workspaces" target="_blank">ak-code-vadf63c56a26.preview.gitpod-dev.com/workspaces</a>.</li>
</ul> …

bump up gitpod code extension

---

WORKSPACE.yaml

Should probably fix false positives from running through leeway https://gitpod.slack.com/archives/C01KLC56NP7/p1681974328788429
will still fail on compile if it's actually not used
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[lint] golangci - exclude typecheck error by regex

---

components/gitpod-db/src/tables.ts
components/gitpod-db/src/typeorm/migration/1681829114367-DropChargebeeSubscriptionTables.ts
components/gitpod-db/src/typeorm/migration/1681829127935-DropPendingGitHubEvents.ts

Removes all (now unused) Chargebee-related DB models and DB tables. Let's wait with merging for a couple of hours.
Depends on https://github.com/gitpod-io/gitpod/pull/17287 to be rolled out.
Fixes WEB-147
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[db] Purge all Chargebee-related DB tables

---

.github/actions/deploy-gitpod/metadata.yml
.github/workflows/build.yml

Extracting from https://github.com/gitpod-io/gitpod/pull/17303
This was necessary to get the `with-dedicated-emulation` running again
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[gha] Fix property propagation to "deploy-gitpod" action

---

components/supervisor/pkg/supervisor/supervisor.go

There were some weird things in routes. This PR clean up them and remove unnecessary routes.
Fixes #
Run components/supervisor/validate.sh
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[supervisor] small fixes of previous leftovers

---

components/gitpod-db/src/periodic-deleter.ts

Let's get rid of log entries like this:
```
[PeriodicDbDeleter] Identified 0 entries in ${rowsForTableToDelete.table} to be deleted.
```
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] stop logging 0 items

---

components/ws-manager-mk2/controllers/create.go

Set missing workspace class and workspace class info environment variables (also rlimit)
Fixes WKS-93
- Open workspace in preview environment and check that environment variables are set
<details>
</details>
<details>
</details>
/hold

[wsman-mk2] Set workspace class environment variables

---

components/server/src/auth/jwt.spec.ts
components/server/src/prometheus-metrics.ts
components/server/src/session-handler.ts

* Expose metrics on number of sessions which contained JWT cookie
Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-server-bd3882035f</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-bd3882035f.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-bd3882035f.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[server] Metrics for sessions with JWTs WEB-102

---

components/server/src/auth/jwt.spec.ts
components/server/src/prometheus-metrics.ts
components/server/src/session-handler.ts

Reverts gitpod-io/gitpod#17302

Revert "[server] Metrics for sessions with JWTs WEB-102"

---

test/pkg/integration/apis.go
test/tests/ide/jetbrains/gateway_test.go
test/tests/workspace/contexts_test.go

Fix ide integration test
Fixes https://github.com/gitpod-io/gitpod/actions/runs/4782041442/jobs/8501195938
Related PR https://github.com/gitpod-io/gitpod/pull/17286
- Start integration test with this PR
<ul>
<li><b>🏷️ Name</b> - hw-ide-int</li>
<li><b>🔗 URL</b> - <a href="https://hw-ide-int.preview.gitpod-dev.com/workspaces" target="_blank">hw-ide-int.preview.gitpod-dev.com/workspaces</a>.</li>
</ul> …

[integration-test] remove plan changing

---

components/server/ee/src/user/stripe-service.ts
components/server/src/user/user-deletion-service.ts

Fixes WEB-191
<ul>
<li><b>🏷️ Name</b> - gpl-user-delete-sub</li>
<li><b>🔗 URL</b> - <a href="https://gpl-user-delete-sub.preview.gitpod-dev.com/workspaces" target="_blank">gpl-user-delete-sub.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[server] Only try to delete Stripe subscription if the user's BillingMode is "usage-based"

---

components/public-api/go/config/config.go
components/server/src/auth/login-completion-handler.ts
components/server/src/config.ts
components/server/src/session-handler.ts
install/installer/pkg/components/auth/config.go
install/installer/pkg/components/auth/config_test.go
install/installer/pkg/components/public-api-server/configmap.go
install/installer/pkg/components/public-api-server/configmap_test.go
install/installer/pkg/components/server/configmap_test.go

We want to be able to create/read cookies on both Public API and Server. For that, we should have a shared understanding of the cookie names to look for when extracting the (JWT) session.
* Cookie Name, and opts are specified in `auth.session.cookie` config, used by both server and public-api
* Depends on https://github.com/gitpod-io/gitpod/pull/17314
Unit tests
Preview
1. View
2. Check JWT cookie is set, and the naming
3. Check both server & public-api receive the config in their configmap
<ul>
<li><b>🏷️ Name</b> - mp-config-6a7121c1a4</li>
<li><b>🔗 URL</b> - <a href="https://mp-config-6a7121c1a4.preview.gitpod-dev.com/workspaces" target="_blank">mp-config-6a7121c1a4.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 …

 [installer] Add JWT cookie opts to config WEB-101

---

install/installer/pkg/components/server/deployment.go
install/installer/pkg/components/ws-manager-bridge/deployment.go

When we do a full installation of Gitpod (i.e. webapp and workspace components all within the same cluster) and ws-manager-mk2 is specified use the ws-manager-mk2 secret instead of the mk1 secret (mk1 will not exist). 
Fixes WKS-105
- Use https://github.com/gitpod-io/workspace-preview to create a VM with a full installation of Gitpod. Make sure you have enabled mk2
- All components should get ready. None should get stuck because secrets cannot be mounted
- Start workspace
<details>
</details>
<details>
</details> …

[wsman-mk2] Use mk2 tls certificates for server and bridge

---

components/public-api-server/pkg/oidc/service_test.go
components/public-api/go/config/config.go
dev/preview/workflow/preview/deploy-gitpod.sh
install/installer/pkg/components/public-api-server/configmap.go
install/installer/pkg/components/public-api-server/configmap_test.go
install/installer/pkg/components/public-api-server/deployment.go
install/installer/pkg/components/public-api-server/deployment_test.go
install/installer/pkg/components/public-api-server/objects_test.go
install/installer/pkg/config/v1/experimental/experimental.go

* Removes OIDC symmetric key/secret, no longer needed as we are using RSA generated by cert manager
* Depends on https://github.com/gitpod-io/gitpod/pull/17328
<ul>
<li><b>🏷️ Name</b> - mp-papi-re5b714b1e90</li>
<li><b>🔗 URL</b> - <a href="https://mp-papi-re5b714b1e90.preview.gitpod-dev.com/workspaces" target="_blank">mp-papi-re5b714b1e90.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[installer] Remove OIDC secret from public-api WEB-206

---

components/server/ee/src/container-module.ts
components/server/ee/src/server.ts
components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/src/container-module.ts
components/server/src/server.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/snapshot-service.ts

Moves Snapshot service out of EE, we don't have EE anymore so no need to keep it seperate
Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-move-sn5410bfd74b</li>
<li><b>🔗 URL</b> - <a href="https://mp-move-sn5410bfd74b.preview.gitpod-dev.com/workspaces" target="_blank">mp-move-sn5410bfd74b.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[server] Move snapshot service out of EE

---

components/server/src/api/server.ts
components/server/src/api/workspaces.ts
components/server/src/container-module.ts

Adds an unimplmeneted workspaces service. Currently unused. Mostly to have the setup in place and reduce required steps when we approach implementing it.
Fixes #
```release-note
NONE
```
<details>
</details>
<details>
</details>
/hold

[server] Unimplemented workspaces service

---

components/dashboard/src/admin/WorkspaceDetail.tsx
components/dashboard/src/index.tsx
components/gitpod-protocol/src/admin-protocol.ts
components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/src/auth/rate-limiter.ts
components/server/src/workspace/gitpod-server-impl.ts

enhances the Workspace details in the admin dashboard by showing the organization as well as all previous instances.
Fixes WEB-175
Fixes WEB-176
login to preview create a workspace and restart it a couple of times. Go to admin dashboard and look up that workspace.
<ul>
<li><b>🏷️ Name</b> - se-admin-workspaces</li>
<li><b>🔗 URL</b> - <a href="https://se-admin-workspaces.preview.gitpod-dev.com/workspaces" target="_blank">se-admin-workspaces.preview.gitpod-dev.com/workspaces</a>.</li> …

[admin] show workspace instances and organization

---

components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/gitpod-server-impl.ts

* Depends on https://github.com/gitpod-io/gitpod/pull/17341
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] Move remaining trivial RPCs away from EE

---

components/dashboard/src/data/workspaces/delete-inactive-workspaces-mutation.ts
components/dashboard/src/data/workspaces/delete-workspace-mutation.ts
components/dashboard/src/data/workspaces/list-workspaces-query.ts
components/dashboard/src/data/workspaces/toggle-workspace-pinned-mutation.ts
components/dashboard/src/data/workspaces/toggle-workspace-shared-mutation.ts
components/dashboard/src/data/workspaces/update-workspace-description-mutation.ts

Fixes a regression, where the key for the workspaces-list would be wrong when used from migrations
Fixes WEB-204
delete a workspace
<ul>
<li><b>🏷️ Name</b> - se-delete-workspace</li>
<li><b>🔗 URL</b> - <a href="https://se-delete-workspace.preview.gitpod-dev.com/workspaces" target="_blank">se-delete-workspace.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[dashboard] fix ws query invalidation

---

components/dashboard/src/components/SelectableCardSolid.tsx

Adds focus rings to the cards component for improved accessibility. 
Split from https://github.com/gitpod-io/gitpod/pull/17053
Partly addresses https://github.com/gitpod-io/gitpod/issues/16723
Go to the preview environment, to user preferences, and <kbd>Tab</kbd> your way through to the Theme selection. It should always be clear which one is selected.
<ul>
<li><b>🏷️ Name</b> - ft-selecta9ef3ce70f0</li>
<li><b>🔗 URL</b> - <a href="https://ft-selecta9ef3ce70f0.preview.gitpod-dev.com/workspaces" target="_blank">ft-selecta9ef3ce70f0.preview.gitpod-dev.com/workspaces</a>.</li> …

Add focus ring for `<SelectableCardSolid>`

---

components/dashboard/src/App.tsx
components/dashboard/src/contexts/FeatureFlagContext.tsx
components/dashboard/src/onboarding/OnboardingStep.tsx
components/dashboard/src/whatsnew/MigrationPage.tsx
components/gitpod-protocol/src/gitpod-service.ts
components/server/src/auth/rate-limiter.ts
components/server/src/user/user-service.ts
components/server/src/workspace/gitpod-server-impl.ts

Moves the automatic migration on login, to an explicit migration, that the user triggers themselves after they have read information about the change wánd what it means.
**Attention**
The design and text is not finished yet, obviously 🤣. I'm waiting for input from @gtsiolis.
But the general code changes can be reviewed already.
Fixes WEB-186
Login and see the information as the first thing. We will not show this to new users in prod, but because we don't have existing users in preview environments I configured the feature flags so that it happens for new users as well.
<ul>
<li><b>🏷️ Name</b> - se-show-info</li>
<li><b>🔗 URL</b> - <a href="https://se-show-info.preview.gitpod-dev.com/workspaces" …

[orgs-only] Show Information before migration.

---

components/gitpod-db/src/typeorm/migration/1682403474866-AdminUserOnboardedTimestamp.ts
components/gitpod-protocol/src/protocol.ts
dev/preview/workflow/preview/deploy-gitpod.sh

This PR:
- disables SaaS related secrets (linkedin, stripe) if `with-dedicated-emulation` is set
- disable the Onboarding flow for the `admin-user` ([commit](https://github.com/gitpod-io/gitpod/pull/17337/commits/c7b2a62cd17b7492181d67c746cecadc55289b64)): Not very fond of the solution, and definitely open for alternative suggestions!
Fixes WEB-213
- `previewctl admin credentials create`
- visit `https://gpl-dedica693133f791.preview.gitpod-dev.com/api/login/ots/admin/your-token`
- notice the "new org" screen :heavy_check_mark: 
<ul>
<li><b>🏷️ Name</b> - gpl-dedica693133f791</li>
<li><b>🔗 URL</b> - <a href="https://gpl-dedica693133f791.preview.gitpod-dev.com/workspaces" …

[preview] Configure with-dedicated-emulation

---

components/gitpod-db/src/typeorm/team-db-impl.spec.db.ts
components/gitpod-db/src/typeorm/team-db-impl.ts
components/gitpod-db/src/user-to-team-migration-service.ts

Relaxes the unnecessary strict requirments for organization names.
Fixes WEB-220
<ul>
<li><b>🏷️ Name</b> - se-org-nam7ae9c219c3</li>
<li><b>🔗 URL</b> - <a href="https://se-org-nam7ae9c219c3.preview.gitpod-dev.com/workspaces" target="_blank">se-org-nam7ae9c219c3.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[org-only] relax org name restriction

---

operations/observability/mixins/workspace/rules/central/workspaces.yaml
operations/observability/mixins/workspace/rules/central/ws-manager.yaml
operations/observability/mixins/workspace/rules/satellite/workspaces.yaml

Add alerts for ws-manager-mk2
Fixes WKS-111
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[ws-manager-mk2] Add alerts

---

install/installer/pkg/components/workspace/ide/constants.go

Adds commit information to the logs for the `gitpod-web` extension.
https://github.com/gitpod-io/gitpod-code/pull/9
<ul>
<li><b>🏷️ Name</b> - ft-bump-code</li>
<li><b>🔗 URL</b> - <a href="https://ft-bump-code.preview.gitpod-dev.com/workspaces" target="_blank">ft-bump-code.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

Update Gitpod code

---

dev/preview/workflow/preview/deploy-gitpod.sh

The reason why we get this error is because we generate those secret every time, and `ws-daemon` might not restart to apply these change, this PR change it to hardcode random seed so that can make sure every time it's generate same secret.
It's safe because we don't expose internal service to internet (i.e. mysql/minio/rabbitmq)
Fixes #
1. start workspace in this branch
2. kubectl get secret minio -oyaml
3. re-run github action
4. check secret again, it should keep same
5. try start workspace in this preview env, it should success
<ul>
<li><b>🏷️ Name</b> - pd-fix-unsca00845e2d</li>
<li><b>🔗 URL</b> - <a href="https://pd-fix-unsca00845e2d.preview.gitpod-dev.com/workspaces" …

[dev] use hardcode seed value in preview environment

---

components/dashboard/src/onboarding/StepOrgInfo.tsx
components/gitpod-protocol/src/protocol.ts

Stop asking for company website during user onboarding
Fixes item 2. in [Slack message](https://gitpod.slack.com/archives/C04PH56LZK5/p1681917949501639?thread_ts=1681389401.968919&cid=C04PH56LZK5) (internal)
gitpod:summary
<details>
</details>
<details>
</details>
/hold

Stop asking for company website during user onboarding

---

components/server/src/redis/mutex.ts
components/server/src/workspace/garbage-collector.ts

As Workaround for https://github.com/mike-marcacci/node-redlock/issues/168 and https://github.com/mike-marcacci/node-redlock/issues/169
Also reduces log verbosity
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] Wrap using redis mutex API and catch quorum error WEB-229

---

components/gitpod-db/src/typeorm/migration/1682510207256-UnblockAdminuser.ts

This additional safe-guard is not necessary anymore because we guard admin credential creation by other means.
Fixes WEB-235
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[db] Unblock admin-user by default

---

components/gitpod-db/src/typeorm/workspace-db-impl.ts

If the periodic deleter doesn't run, we would delete the same workspaces over and over again.
Fixes WEB-238
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[wsgc] fix workspaceForPurging query

---

operations/observability/mixins/cross-teams/dashboards.libsonnet
operations/observability/mixins/cross-teams/dashboards/gitpod-overview-mk2.json

Add overview dashboard
Fixes WKS-113
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[wsman-mk2] Add overview dashboard

---

operations/observability/mixins/workspace/dashboards/success-criteria.json

Update workspace success criteria to include ws-manager-mk2
Fixes WKS-73
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[ws-manager-mk2] Update workspace success criteria

---

components/gitpod-db/src/typeorm/workspace-db-impl.ts
components/gitpod-db/src/workspace-db.spec.db.ts
components/server/src/workspace/workspace-deletion-service.ts

We no longer need the periodic deleter (non more db-sync).
So as a step towards getting rid of it, workspaces are going to be directly deleted.
Fixes WEB-250
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[db] directly delete workspaces

---

components/proxy/conf/Caddyfile
dev/preview/workflow/preview/deploy-gitpod.sh
install/installer/pkg/components/proxy/constants.go
install/installer/pkg/components/proxy/deployment.go
install/installer/pkg/components/proxy/networkpolicy.go
install/installer/pkg/components/proxy/service.go

to prevent triggering rate limiting on analytics from internal components 
see https://gitpod.slack.com/archives/C02EN94AEPL/p1682493547309509
- Start a workpace in previe envs, connect via SSH.
- Check that events from server, bridge and ws-proxy are registered in segment.
<ul>
<li><b>🏷️ Name</b> - ak-interna297d9dfe48</li>
<li><b>🔗 URL</b> - <a href="https://ak-interna297d9dfe48.preview.gitpod-dev.com/workspaces" target="_blank">ak-interna297d9dfe48.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your …

internal analytics endpoint

---

components/dashboard/src/service/service.tsx
components/gitpod-protocol/src/util/generate-workspace-id.spec.ts
components/gitpod-protocol/src/util/gitpod-host-url.spec.ts
components/gitpod-protocol/src/util/gitpod-host-url.ts
components/server/src/bitbucket-server/bitbucket-server-api.spec.ts
components/server/src/bitbucket-server/bitbucket-server-context-parser.spec.ts
components/server/src/bitbucket-server/bitbucket-server-file-provider.spec.ts
components/server/src/bitbucket-server/bitbucket-server-repository-provider.spec.ts
components/server/src/prebuilds/bitbucket-server-service.spec.ts
components/supervisor/frontend/src/ide/supervisor-service-client.ts
components/supervisor/frontend/src/shared/urls.ts

when workspace URL contains search, hash or path
See https://gitpod.slack.com/archives/C045J13P8A1/p1682337644081519
- Start a workspace and check network tabs for any errors doing following
- Prepend something to workspace URL like `?payload=[["logLevel", "debug"]]` and navigate
- Stop the workspace
- Start another workspace, but this time close the page and check that that it times out in 5 mins, i.e. close heartbeat is still registered.
<ul>
<li><b>🏷️ Name</b> - ak-fix-metrcis-sup</li>
<li><b>🔗 URL</b> - <a href="https://ak-fix-metrcis-sup.preview.gitpod-dev.com/workspaces" target="_blank">ak-fix-metrcis-sup.preview.gitpod-dev.com/workspaces</a>.</li> …

[supervisor-frontend] fix metrics reporting

---

components/dashboard/src/components/error-boundaries/QueryErrorBoundary.tsx
components/gitpod-protocol/go/error.go
components/gitpod-protocol/src/messaging/error.ts
components/server/src/workspace/gitpod-server-impl.ts

Because it blocks all API calls needed during the onboarding flow.
Partially reverts #17303. 
The new plan is to add a page for the onboarding flow and redirect to it. It might require to guard access to to afterwards. 
<ul>
<li><b>🏷️ Name</b> - at-rm-onboc0047292d5</li>
<li><b>🔗 URL</b> - <a href="https://at-rm-onboc0047292d5.preview.gitpod-dev.com/workspaces" target="_blank">at-rm-onboc0047292d5.preview.gitpod-dev.com/workspaces</a>.</li>
</ul> …

Removing ONBOARDING_IN_PROGRESS condition

---

components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/suite_test.go
components/ws-manager-mk2/controllers/timeout_controller.go
components/ws-manager-mk2/controllers/timeout_controller_test.go
components/ws-manager-mk2/controllers/workspace_controller.go
components/ws-manager-mk2/main.go

Continue reconciling workspaces in maintenance mode, to e.g. finish disposal and advance the workspace phase to stopped. Instead, don't move a workspace to Stopping (which starts disposal in daemon) for timeouts and when a headless workspace exits.
Fixes WKS-48
Enable maintenance mode, and observe starting/stopping workspaces is still not possible, but the workspaces should get reconciled and advance phase if they were e.g. stopping at the time of maintenance mode. 
Workspaces should not timeout when maintenance mode is enabled, but should once it gets disabled.
```release-note
NONE
```
<details>
</details>
<details> …

[ws-manager-mk2] Maintenance continue reconciles

---

components/server/src/redis/mutex.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[serer] Fix capture of ExecutionError error message comparison

---

components/ws-daemon/pkg/controller/snapshot_controller.go
components/ws-daemon/pkg/controller/workspace_controller.go
components/ws-manager-mk2/controllers/maintenance_controller.go
components/ws-manager-mk2/controllers/timeout_controller.go
components/ws-manager-mk2/controllers/workspace_controller.go
components/ws-manager-mk2/service/manager.go

Improves reconciler error logging by wrapping returned errors with additional context.
Also logs workspace status update conflicts as Info level rather than Error, as they're expected in normal operations.
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[ws-manager-mk2] Improve reconcile err logging

---

components/dashboard/src/service/service.tsx
components/gitpod-protocol/src/frontend-dashboard-service.ts

This reverts commit c520c72398235104a2a870014d20e476ac211890.
Related https://github.com/gitpod-io/gitpod/pull/17425
Build should pass
gitpod:summary
<details>
</details>
<details>
</details>
/hold

Revert "[dashboard] send heartbeat telemetry (#17358)"

---

components/gitpod-db/src/periodic-deleter.ts
components/server/src/server.ts

Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-server-6ebe3a0f55</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-6ebe3a0f55.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-6ebe3a0f55.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[server] Use redlock for periodic db deleter

---

components/server/src/user/token-garbage-collector.ts

Switches to Redis redlock to acquire mutex on token gc.
Fixes #
1. preview
2. adjust frequency from config (in configmap), restart server
3. Observe token gc runs
<ul>
<li><b>🏷️ Name</b> - mp-server-2b23095254</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-2b23095254.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-2b23095254.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[server] Use Redlock for token gc WEB-226

---

components/server/src/projects/webhook-event-garbage-collector.ts

Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-server-0a41d11a34</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-0a41d11a34.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-0a41d11a34.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[server] Use redlock for webhook gc WEB-224

---

components/dashboard/src/components/Button.tsx

Pressing enter on confirmation modal deletes the entry even if cancel is focused. This PR is a possible fix
Fixes #16717

Fix for workspace delete on Enter keydown

---

components/dashboard/src/admin/ProjectsSearch.tsx
components/dashboard/src/admin/UserSearch.tsx
components/dashboard/src/admin/WorkspacesSearch.tsx
components/dashboard/src/projects/Prebuilds.tsx
components/dashboard/src/projects/Project.tsx
components/dashboard/src/projects/ProjectListItem.tsx
components/dashboard/src/teams/Members.tsx

- Display the `absolute time` in a tooltip when using the `relative date and time` format.
|_**Before**_|_**After**_|
|-------------|------------|
|![Screenshot (388)](https://user-images.githubusercontent.com/76192403/213012926-a0cc10fd-7f65-492b-acef-41faf40cb9f9.png)|![image](https://user-images.githubusercontent.com/76192403/213013095-d2dc332d-91a9-4234-96f2-3bd6df4d367b.png)|
Fixes #13764 
- Hover mouse over any `relative date and time` format.
```release-note
Display a tolltip with absolute date when using relative date format
```
<details>
</details>
<details>
</details> …

:tada: [feat]: Tooltip to display `absolute time` when using `relative date and time` format (#13764)

---

dev/preview/previewctl/cmd/admin.go

print out the admin login link when generating the token
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[previewctl] print admin link

---

components/image-builder-mk3/pkg/orchestrator/monitor.go
components/ws-manager-api/go/crd/v1/workspace_types.go
components/ws-manager-mk2/controllers/status.go

Fixes headless task failures to get reported through the `HeadlessTaskFailed` condition instead of the `Failed` condition.
Fixes WKS-122
Tested image build failures using: https://github.com/wverlaek/gitpod-testing/tree/fail-image-build
Verify that the `gitpod_ws_manager_mk2_workspace_stops_total{reason="failed"}` metric doesn't get incremented on headless task failures
gitpod:summary
<details>
</details>
<details>
</details> …

[ws-manager-mk2] Fix headless task failures

---

components/dashboard/src/admin/ProjectsSearch.tsx
components/dashboard/src/admin/UserSearch.tsx
components/dashboard/src/admin/WorkspacesSearch.tsx
components/dashboard/src/projects/Prebuilds.tsx
components/dashboard/src/projects/Project.tsx
components/dashboard/src/projects/ProjectListItem.tsx
components/dashboard/src/teams/Members.tsx

Pick up changes from the community contribution in https://github.com/gitpod-io/gitpod/pull/17234. Cc @tanishq-singh-2407
For more context, see **[relevant section](https://www.notion.so/gitpod/How-we-develop-e8ce7e562478458a9223eb9b797415b2?pvs=4#ef8b432a56b6425db16039d603ac97f4)** in How we develop.
Fixes https://github.com/gitpod-io/gitpod/issues/13764
<ul>
<li><b>🏷️ Name</b> - gt-merge-17234</li>
<li><b>🔗 URL</b> - <a href="https://gt-merge-17234.preview.gitpod-dev.com/workspaces" target="_blank">gt-merge-17234.preview.gitpod-dev.com/workspaces</a>.</li> …

Add tooltip with absolute date and time on relative times

---

components/dashboard/src/menu/Menu.tsx
components/dashboard/src/teams/sso/OIDCClientListItem.tsx

This will update and normalize log in an log out verbs, see [relevant discussion](https://gitpod.slack.com/archives/C01KGM9DVRC/p1682689148308139) (internal).
Cc @mbrevoort @atduarte @lucasvaltl @svenefftinge 
Fixes #
1. Once you log in, go to the user menu and notice the new _Log out_ verb.
2. Inside an org, after adding an OIDC client, open the more actions menu and notice the new _Log in_ verb.
<ul>
<li><b>🏷️ Name</b> - gt-normalif4dddf2da2</li>
<li><b>🔗 URL</b> - <a href="https://gt-normalif4dddf2da2.preview.gitpod-dev.com/workspaces" target="_blank">gt-normalif4dddf2da2.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d040 …

Normalize log in and log out verbs

---

components/common-go/experiments/configcat.go
components/common-go/experiments/types.go

The custom attribute "gitpod-host" was added in `server` component, but is missing on the golang side.
https://github.com/gitpod-io/gitpod/pull/17303#discussion_r1173710700
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[common-go] add custom attribute "gitpod-host"

---

components/ws-daemon/pkg/controller/workspace_controller.go
components/ws-manager-mk2/controllers/workspace_controller.go

Log reconciliations
Related to WKS-120
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[wsman-mk2] Log reconciliations

---

.github/workflows/workspace-integration-tests.yml
dev/preview/workflow/preview/deploy-gitpod.sh
test/pkg/integration/apis.go
test/pkg/integration/integration.go
test/pkg/integration/setup.go

Runs workspace integration tests against mk2 by default (both in the scheduled job, and in manual dispatch inputs)
Also includes several fixes and improvements needed to run the tests:
- Update `name` and `version` workflow inputs to not be required, and allow either one to be set without the other
- Remove previewctl hash, this was causing not-found errors when downloading the `previewctl` binary as the hash was constructed incorrectly. Not specifying any hash will also try to download the latest version which is what we want
- Fix preview environment sometimes failing to create with mk2 enabled, due to namespaces sometimes being applied after the manifests in that namespace, causing those manifests to fail to apply. Specifically this was failing for the `workspace-secrets` namespace …

[ws-manager-mk2] Run integration tests against mk2 by default in GHA (+ preview fixes)

---

.github/workflows/workspace-integration-tests.yml
test/README.md
test/pkg/integration/setup.go

Runs the e2e tests against mk2 by default
Fixes WKS-98
Run workspace integration tests without specifying the `WS_MANAGER_MK2` env var, and see it runs against mk2. Set `WS_MANAGER_MK2=false` should run against mk1.
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[ws-manager-mk2] Run e2e tests against mk2 by default

---

components/dashboard/src/data/organizations/create-org-mutation.ts
components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
components/dashboard/src/dedicated-setup/GettingStartedStep.tsx
components/dashboard/src/dedicated-setup/OrgNamingStep.tsx
components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
components/dashboard/src/dedicated-setup/SetupCompleteStep.tsx
components/dashboard/src/dedicated-setup/SetupLayout.tsx

This adds the org naming (and creation) step to the dedicated setup flow. I also stubbed out the sso config step, and final completed view so that they're ready to build out in subsequent PRs.
Fixes WEB-244
* Since the setup flow isn't complete end to end yet, the easiest way to test this it to start a workspace using this PR/branch, and point gitpod-staging at your workspace dashboard assets w/ the `x-frontend-dev-url` header.
* Load up gitpod staging and set a query param that will initiate the flow.
* https://gitpod-staging.com/workspaces?dedicated-setup=force
* You should see the getting started step, and after proceeding, you can name your org. 
* After that completes you should land on a placeholder for the sso setup page in the flow.
<p>Gitpod was successfully deployed to your …

Adds org naming step in dedicated setup flow

---

components/dashboard/src/Login.tsx
components/dashboard/src/login/SSOLoginForm.tsx
components/dashboard/src/provider-utils.tsx
components/gitpod-db/go/team.go
components/gitpod-db/go/team_test.go
components/public-api-server/pkg/oidc/service.go
components/public-api-server/pkg/oidc/service_test.go
components/server/src/user/user-service.ts

For Gitpod installations that don't have global authproviders we assume a single org with SSO (dedicated).
Users that are owned by an org will not get an org when they are created.
The login screen for dedicated users:
Fixes WEB-48
Fixes WEB-272
1. Log in: https://se-dedicated-login.preview.gitpod-dev.com/workspaces
2. Verify you are a member of ACME and no other org
<ul>
<li><b>🏷️ Name</b> - se-dedicated-login</li>
<li><b>🔗 URL</b> - <a href="https://se-dedicated-login.preview.gitpod-dev.com/workspaces" target="_blank">se-dedicated-login.preview.gitpod-dev.com/workspaces</a>.</li> …

Streamline dedicated login/signup

---

components/dashboard/src/menu/OrganizationSelector.tsx
components/dashboard/src/onboarding/use-show-user-onboarding.ts
components/gitpod-protocol/src/protocol.ts

- remove the "New Organization" button from the org selector if the user is organizationOwned. The server side already handles this.
- skip onboarding flow for organizationOwned users.
Fixes WEB-276
Fixes WEB-30
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[dashboard] handle organization-owned users

---

components/public-api-server/pkg/identityprovider/cache.go
components/public-api-server/pkg/identityprovider/cache_test.go

This change will improve the stability of the identity provider functionality. It does that by re-persisting a public key if it's been lost in the meantime, e.g. because Redis restarted. 
Fixes WEB-268
See unit test
gitpod:summary
<details>
</details>
<details>
</details>

Repersist IDP public key when lost

---

components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/workspace_controller.go

Fixes an aborted prebuild getting a `Failed` condition, due to supervisor exiting with a non-zero exit code due to a cancelled context. Supervisor exits with message `headless task failed: context canceled`, this PR now considers any (headless) termination message starting with `headless task failed: ` as a headless task failure instead of a workspace failure.
Also changes the reconciler such that stopping workspaces move through `Stopping` before `Stopped`, as otherwise it's possible in some scenarios to miss the `Stopping` phase (e.g. when aborting a prebuild). `ws-manager-bridge` relies on prebuilds to move through the `Stopping` phase to determine the outcome of the prebuild, without this fix some prebuilds would get stuck in `Running`.
Fixes WKS-136
In a mk2 preview env, repeatedly …

[ws-manager-mk2] Fix abort prebuild failure

---

components/gitpod-db/src/user-to-team-migration-service.spec.db.ts
components/gitpod-db/src/user-to-team-migration-service.ts
components/server/src/user/user-service.ts

In PR #17432 I messed up the order of how users are stored in the DB and the team migration were ignoring the passed user object and reload what ever state is in the DB, resulting in creating two orgs one with a UUID. This PR fixes that.
Fixes #17460 
Fixes WEB-283
login to the preview environment and verify that you don't see a second org named by a UUID.
<ul>
<li><b>🏷️ Name</b> - svenefftin9a21e320f5</li>
<li><b>🔗 URL</b> - <a href="https://svenefftin9a21e320f5.preview.gitpod-dev.com/workspaces" target="_blank">svenefftin9a21e320f5.preview.gitpod-dev.com/workspaces</a>.</li> …

[server] fix login regression

---

operations/observability/mixins/cross-teams/dashboards/gitpod-overview-mk2.json

w/o this change, it becomes difficult to see image builds, because they're visible on the left Y axis, rather than the right.
Fixes WKS-138
Before this change, Running image builds use the left axis. After this change, they use the right axis.
Before:
After:
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[obs] right align image builds in the Running Workspaces pane

---

components/gitpod-protocol/package.json
components/gitpod-protocol/src/util/timeutil.spec.ts
components/gitpod-protocol/src/util/timeutil.ts
components/server/src/workspace/gitpod-server-impl.ts
yarn.lock

Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-server-ae2fc95782</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-ae2fc95782.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-ae2fc95782.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[server] Fix parsing of go duration WEB-280

---

components/public-api-server/pkg/oidc/router.go
components/public-api-server/pkg/oidc/service.go
components/public-api-server/pkg/oidc/service_test.go
components/server/src/iam/iam-oidc-create-session-payload.ts
components/server/src/iam/iam-session-app.spec.ts
components/server/src/iam/iam-session-app.ts

During the Dedicated Onboarding flow, we learned that it's necessary to have the Issuer (URL) updatable, which means, it will be updatable on the Org Settings page as well, which mean it cannot be used as part of the stable composite key for the SSO identity in the data model. 
This PR updates the composite key of SSO identities to be `(ClientConfigID & Subject)`, which should not change during the lifecycle of a SSO config. (Transitioning from one SSO config to another is not in scope.)
Fixes WEB-279
See unit test.
gitpod:summary
<details>
</details>
<details>
</details>
If …

[SSO] Use ClientConfigID & Subject as composite key for identities WEB-279

---

operations/observability/mixins/workspace/dashboards/components/ws-manager-mk2.json

A rate of 5m makes the graph too dense, and, it doesn't match the the overview dashboard's heatmap.
Fixes # n/a
Refer to screenshots (will add).
**mk2 component dashboard**
While a rate of `5m`:
When a rate of `$__rate_interval`:
**Overview Dashboard** with mk2, for comparison, this has not changed
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[obs] mk2 dashboard, change startup time heatmap's rate to `rate interval`

---

components/gitpod-db/go/dbtest/oidc_client_config.go
components/gitpod-db/go/oidc_client_config.go
components/gitpod-db/go/oidc_client_config_test.go
components/public-api-server/pkg/apiv1/oidc.go
components/public-api-server/pkg/apiv1/oidc_test.go

Implements updating of OIDC Client Config with respect to the scope which we currently support.
Remaining to add:
* After the update, deactivate the OIDC config (done)
* Unit tests for the API layer (done)
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[public-api] Implement UpdateOIDCClientConfig WEB-278

---

components/ws-manager-mk2/controllers/metrics.go
components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/workspace_controller.go

Fixes two start failure false positives for prebuilds:
- Prebuilds with empty tasks finishing too quickly to observe the `Running` state, therefore missing the `EverReady` condition. This is fixed by retroactively adding the EverReady condition if we observe the prebuild has succeeded.
- Prebuilds that get aborted before becoming ready. They won't have been ready (and hence considered to have a start failure). Fixed by excluding aborted prebuilds in start failure recording
Fixes WKS-137
Tested in a preview env, by repeatedly creating prebuilds with an empty task, which exercises both aborting previous prebuilds, and prebuilds with empty tasks.
Afterwards, observed the `ws-manager-mk2` metrics and find there are no longer start failures being recorded.
gitpod:summary …

[ws-manager-mk2] Fix prebuild start failure false positives

---

components/ws-manager-mk2/controllers/create.go
components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/workspace_controller_test.go

We have observed that compared to mk1 the p25 workspace startup time for mk2 workspace is slightly worse. With mk2 we have relied on the readiness probe of the workspace to transition the workspace to `Running`. This introduces an additional delay before we detect that the workspace is ready. Instead we now use ide readiness to ensure that the IDE is available and the ContentInit condition to ensure that the content is initialized.
Fixes WKS-120
- Open https://github.com/gitpod-io/empty 
- Workspace should enter Running phase faster
<ul>
<li><b>🏷️ Name</b> - fo-p25-latency</li>
<li><b>🔗 URL</b> - <a href="https://fo-p25-latency.preview.gitpod-dev.com/workspaces" …

[ws-manager-mk2] Fix slow p25 workspace startup time

---

components/common-go/baseserver/server.go
components/common-go/baseserver/server_test.go
components/common-go/baseserver/testing.go

Instead of looking for a free port, we can use the port 0 which will automatically assign a port when it binds the listener. This solves a current race where we would:
1. Look for a port
2. Create a listener on it
3. Determine the port number
4. Close the listener
5. Use the port to start an actual server
This lead to clashes with the acquired port. Using port 0 instead ensures that we also claim the port when it is assigned by the OS, removing the race.
Fixes #
1. Existing unit tests pass
gitpod:summary
<details>
</details>
<details>
</details> …

[baseserver] Test port is 0

---

components/gitpod-db/go/dbtest/team_membership.go
components/gitpod-db/go/dbtest/user.go
components/gitpod-db/go/team_membership.go
components/gitpod-db/go/team_membership_test.go
components/public-api-server/pkg/apiv1/oidc.go
components/public-api-server/pkg/apiv1/oidc_test.go

Ensures that only team owners can perform actions on OIDC Client Configs
Fixes #
Unit tests
<ul>
<li><b>🏷️ Name</b> - mp-oidc-au11b8dbf2e7</li>
<li><b>🔗 URL</b> - <a href="https://mp-oidc-au11b8dbf2e7.preview.gitpod-dev.com/workspaces" target="_blank">mp-oidc-au11b8dbf2e7.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[oidc] Restrict actions to team owners WEB-284

---

components/gitpod-db/src/team-db.spec.db.ts
components/gitpod-db/src/team-db.ts
components/gitpod-db/src/typeorm/team-db-impl.ts
components/gitpod-protocol/src/gitpod-service.ts
components/server/src/auth/rate-limiter.ts
components/server/src/workspace/gitpod-server-impl.ts

A pragmatic approach to compute the state of the cell to tell if the Dedicated Onboarding flow should be shown.
This adds `getOnboardingState` to server which result resolves to 
```ts
interface OnboardingState {
/**
* Whether this Gitpod instance is already configured with SSO.
*/
readonly isCompleted: boolean;
/**
* Whether this Gitpod instance has at least one org.
*/
readonly hasAnyOrg: boolean;
}
```
Fixes WEB-287
<ul>
<li><b>🏷️ Name</b> - at-onboarding-state</li>
<li><b>🔗 URL</b> - <a href="https://at-onboarding-state.preview.gitpod-dev.com/workspaces" target="_blank">at-onboarding-state.preview.gitpod-dev.com/workspaces</a>.</li> …

Compute onboarding state – WEB-287

---

components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
components/dashboard/src/workspaces/WorkspacesSearchBar.tsx

The new workspace button on the workspaces list is not rendered properly.
Fixes #
<ul>
<li><b>🏷️ Name</b> - se-button-fix</li>
<li><b>🔗 URL</b> - <a href="https://se-button-fix.preview.gitpod-dev.com/workspaces" target="_blank">se-button-fix.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
Add …

[dashboard] fix button rendering

---

operations/observability/mixins/workspace/dashboards/success-criteria.json

Include p01, p25 and p75 in success criteria
Fixes WKS-147
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[obs] Include p01, p25 and p75 in success criteria

---

components/dashboard/src/start/start-workspace-options.ts
components/dashboard/src/user-settings/Preferences.tsx
components/dashboard/src/workspaces/CreateWorkspacePage.tsx
components/gitpod-protocol/src/protocol.ts

- Add a checkbox, so that users don't need to always manually trigger the workspace start.
- introduces a search param `autoStart=true` that allows to create Gitpod start links that auto start the workspace
Fixes WEB-192
Try the new option with different repositories and orgs.
Try an autostart link:
https://se-dont-ask.preview.gitpod-dev.com/?autostart=true#https://github.com/gitpod-io/gitpod
<ul>
<li><b>🏷️ Name</b> - se-dont-ask</li>
<li><b>🔗 URL</b> - <a href="https://se-dont-ask.preview.gitpod-dev.com/workspaces" target="_blank">se-dont-ask.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38ee …

[dashboard] Always use these options for repository

---

components/usage/pkg/scheduler/ledger_job.go

Forgot to bind the constructor, so the job panicks (in staging)
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[usage] Fix constructor binding

---

components/ws-manager-mk2/controllers/create.go
dev/preview/workflow/preview/deploy-gitpod.sh

Only schedule on on experimental nodes if experimental mode is disabled
Fixes WKS-123
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[wsman-mk2] Schedule on non experimental nodes

---

components/gitpod-db/src/user-to-team-migration-service.spec.db.ts
components/gitpod-db/src/user-to-team-migration-service.ts
components/server/src/workspace/gitpod-server-impl.ts

In the migration we didn't anticipate that we have only updated usageAttribuitionIds for workspace instances from last June until now.
This change makes sure that workspaces get an orgId oin migration and because we already have executed many migrations we unfortunately also need to fix this on the fly.
Fixes #17482
Fixes WEB-294
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] migrate ws without usageattribution

---

components/ws-manager-mk2/controllers/metrics.go

Log workspace startup time
Fixes WKS-152
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[wsman-mk2] Log workspace startup time

---

components/server/src/workspace/gitpod-server-impl.ts

This fixes the build.
gitpod:summary
<details>
</details>
<details>
</details>

Add missing await on promise.

---

components/server/src/jobs/runner.ts
components/server/src/prometheus-metrics.ts

Reports duration of jobs, such that we can show it on a dashboard
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] Report duration of jobs

---

components/gitpod-db/src/typeorm/webhook-event-db-impl.ts
components/gitpod-db/src/webhook-event-db.spec.db.ts

Instead of deleting through marking the webhook events as deleted, such that they are eventually GCed by the DB deleter, we delete them directly.
Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-delete-b5e8963a85</li>
<li><b>🔗 URL</b> - <a href="https://mp-delete-b5e8963a85.preview.gitpod-dev.com/workspaces" target="_blank">mp-delete-b5e8963a85.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[server] Delete webhook events directly

---

components/gitpod-db/src/typeorm/migration/1683183008878-AdminUserMigrated.ts

mark admin as migrated
Fixes WEB-296
<ul>
<li><b>🏷️ Name</b> - se-migrate-admin</li>
<li><b>🔗 URL</b> - <a href="https://se-migrate-admin.preview.gitpod-dev.com/workspaces" target="_blank">se-migrate-admin.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
Add desired feature flags to the end of the …

[server] mark admin as migrated

---

components/dashboard/src/App.tsx
components/dashboard/src/app/AppBlockingFlows.tsx
components/dashboard/src/data/oidc-clients/oidc-clients-query.ts
components/dashboard/src/data/organizations/orgs-query.ts
components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
components/dashboard/src/dedicated-setup/OrgNamingStep.tsx
components/dashboard/src/dedicated-setup/SSOSetupStep.tsx
components/dashboard/src/dedicated-setup/use-check-dedicated-setup.ts
components/dashboard/src/user-context.tsx
components/gitpod-db/src/typeorm/team-db-impl.ts
components/server/src/workspace/gitpod-server-impl.ts

Hooks up the new `getOnboardingState()` api to our check for showing the dedicated setup. I had to add a bit of client-side state tracking for when we show/complete the setup flow. I also made a couple other changes.
* Filtering out deleted oidc clients from `hasAnyOrgWithActiveSSO()`
* Removing the caching and ff check in `getOnboardingState()`
Fixes WEB-245
* Try and login to the preview env with your gitpod.io email: https://bmh-dedica741b327561.preview.gitpod-dev.com/workspaces
* If you're an admin/owner of the org, you can also force the setup flow manually by adding `?dedicated-setup=force` to the url and reload.
<ul>
<li><b>🏷️ Name</b> - bmh-dedica741b327561</li> …

Use getOnboardingState api for dedicated setup flow

---

components/server/src/config.ts
components/server/src/user/user-service.ts
install/installer/pkg/components/server/configmap.go
install/installer/pkg/components/server/types.go

* We use admin credentials to seed admin user
* This feature is no longer needed
* Depends on https://github.com/gitpod-io/gitpod/pull/17300
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] Remove grant first user admin WEB-127

---

components/server/src/iam/iam-session-app.spec.ts
components/server/src/iam/iam-session-app.ts

Fixes WEB-303
see unit test
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] remove admin-user from org on first user sign-in – WEB-303

---

components/dashboard/src/app/AppRoutes.tsx
components/dashboard/src/login/SSOLoginForm.tsx
components/dashboard/src/teams/Members.tsx
components/gitpod-db/src/team-db.spec.db.ts
components/gitpod-db/src/team-db.ts
components/gitpod-db/src/typeorm/team-db-impl.ts
components/public-api-server/debug.sh
components/public-api-server/pkg/apiv1/team.go
components/public-api-server/pkg/apiv1/team_test.go
components/server/src/workspace/gitpod-server-impl.ts

SSO enabled orgs are inviting through their SSO login.
Fixes WEB-270
Join my org https://se-sso-invites.preview.gitpod-dev.com/login/my-org
<ul>
<li><b>🏷️ Name</b> - se-sso-invites</li>
<li><b>🔗 URL</b> - <a href="https://se-sso-invites.preview.gitpod-dev.com/workspaces" target="_blank">se-sso-invites.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[dashboard] invite link for SSO orgs

---

components/ws-daemon/pkg/controller/workspace_controller.go
components/ws-manager-mk2/controllers/workspace_controller.go

The deletion of the workspace pod was not logged. Also changed some names to make them better searchable.
Fixes WKS-158
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[ws-manager-mk2] Ensure stop reason is logged

---

WORKSPACE.yaml
install/installer/pkg/components/workspace/ide/constants.go

Update code to `1.78.0`
Related https://github.com/gitpod-io/gitpod/issues/17351
<ul>
<li><b>🏷️ Name</b> - jp-vscode-update-178</li>
<li><b>🔗 URL</b> - <a href="https://jp-vscode-update-178.preview.gitpod-dev.com/workspaces" target="_blank">jp-vscode-update-178.preview.gitpod-dev.com/workspaces</a>.</li> …

VS Code Browser release 1.78

---

dev/loadgen/README.md

update docs to support ws-manager-mk2
Fixes # n/a
Loadgen against a preview environment, if desired.
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[loadgen] update docs to support ws-manager-mk2

---

components/dashboard/src/user-settings/EnvironmentVariables.tsx
components/dashboard/src/user-settings/EnvironmentVariablesSearchBar.tsx

filter functionality gitpod.io/variables
Added a filter functionality for gitpod.io/variables
Fixes #17158
add some variables at gitpod.io/variables and use the searchbar to filter through your variables
gitpod:summary
<details>
</details>
<details>
</details>
/hold

added filter functionality

---

components/dashboard/src/menu/OrganizationSelector.tsx
components/server/src/auth/resource-access.spec.ts
components/server/src/auth/resource-access.ts
components/server/src/iam/iam-session-app.spec.ts

Adds the usage view to all org members (previously only owners could see usage)
Fixes WEB-314
Join https://se-usage.preview.gitpod-dev.com/orgs/join?inviteId=71788c56-a3bb-4de1-913c-ca81de001327
<ul>
<li><b>🏷️ Name</b> - se-usage</li>
<li><b>🔗 URL</b> - <a href="https://se-usage.preview.gitpod-dev.com/workspaces" target="_blank">se-usage.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

Show usage

---

.pre-commit-config.yaml
components/dashboard/BUILD.yaml
components/dashboard/package.json
components/dashboard/src/admin/UserDetail.tsx
components/dashboard/src/admin/WorkspaceDetail.tsx
components/dashboard/src/menu/OrganizationSelector.tsx
components/dashboard/src/onboarding/StepOrgInfo.tsx
components/dashboard/src/start/StartPage.tsx

This adds dashboard linting to pre-commit hooks so we won't commit any error/warnings the linter spots.
Linter errors can be seen in the git hook output or by manually running the linter.
```bash
leeway run components/dashboard:lint
yarn run lint
```
Fixes WEB-111
I was able to test this while making these changes, but changing any ts/js file in the dashboard component so it has a linter error/warning, and trying to commit it should cause the hook to fail. 
gitpod:summary
<details>
</details>
<details>
</details> …

Enable dashboard linter for pre-commit hooks

---

dev/preview/infrastructure/modules/gce/variables.tf
dev/preview/infrastructure/variables.tf

Let's update the preview image to ref: https://github.com/gitpod-io/gitpod-packer-gcp-image/releases/tag/gitpod-k3s-202305091902
We're shifting traffic to this now with gen97.
Fixes # n/a
Build a preview env, assert the kernel version is 6.1 via `uname -a`, you should see a 6.1 kernel like:
```
uname -gitpod /workspace/dazzle (main) $ uname -a
Linux gitpodio-dazzle-16u0dambld8 6.1.27-060127-generic #202305051509 SMP PREEMPT_DYNAMIC Fri May  5 15:48:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
<ul>
<li><b>🏷️ Name</b> - kylos101-gen97-image</li>
<li><b>🔗 URL</b> - <a href="https://kylos101-gen97-image.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-gen97-image.preview.gitpod-dev.com/workspaces</a>.</li> …

[preview] update VM image to match gen97

---

components/dashboard/src/service/service.tsx

see IDE-69
fix IDE-69
- Ensure that VS Code Desktop, VS Code Desktop Insiders and Intellij works
<ul>
<li><b>🏷️ Name</b> - ak-whitelib79f1fcc25</li>
<li><b>🔗 URL</b> - <a href="https://ak-whitelib79f1fcc25.preview.gitpod-dev.com/workspaces" target="_blank">ak-whitelib79f1fcc25.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

allow to redirect only for whitelisted trusted protocols

---

components/dashboard/src/components/ConfirmationModal.tsx
components/dashboard/src/components/EmptyMessage.tsx
components/dashboard/src/teams/sso/OIDCClientConfigModal.tsx
components/dashboard/src/teams/sso/OIDCClientListItem.tsx
components/dashboard/src/teams/sso/OIDCClients.tsx
components/public-api/go/experimental/v1/oidc.pb.go

This updates the Org Settings SSO section to show if a config is active or not. It also adds an Activate link in the menu if the config isn't active already. This will go through the Log In flow and result in an activated sso config. 
There is some work associated with WEB-322 around a future iteration of the SSO Config page for nuances w/ activating/deactivating an SSO config that we can work on following this change.
Fixes WEB-313
* Create an Org in the preview environment.
* Under Settings => SSO - create a new SSO config.
* It should show up int he list as inactive (gray circle).
* If you have a valid config that works, you can click the Activate item in the menu. This will send you through the Log in flow w/ the SSO provider. 
* You'll need to logout, and back in with your first …

Display active state on org sso configs

---

components/ws-manager-mk2/controllers/suite_test.go
components/ws-manager-mk2/controllers/timeout_controller.go
components/ws-manager-mk2/controllers/timeout_controller_test.go
components/ws-manager-mk2/main.go
components/ws-manager-mk2/pkg/activity/activity.go
components/ws-manager-mk2/service/manager.go

Moves the lastActivity logic that takes into account a controller restart from `timeout_controller` to `WorkspaceActivity`, such that e.g. the workspace activity metric also considers workspaces with no stored `lastActivity` timestamp as active after a restart (but only when the `FirstUserActivity` condition is present, otherwise we know no activity was recorded yet before the restart either). 
Previously the metrics would show a high amount of inactive workspaces after restarting the pod.
Fixes WKS-161
Run the ws-manager-mk2 unit tests.
gitpod:summary
<details>
</details>
<details> …

[ws-manager-mk2] Refactor lastActivity

---

components/server/src/workspace/gitpod-server-impl.ts

adding a git povider to an org should be considered an update to the org not creation
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] adding git authprovider is an org update

---

components/dashboard/src/app/AppBlockingFlows.tsx
components/dashboard/src/app/AppLoading.tsx
components/dashboard/src/app/AppRoutes.tsx

This adjusts the app loading flow so we don't wait for the result of `getOnboardingState` before rendering the current route. The motivation is to avoid adding a delay for majority of users (where dedicated setup isn't required) and render right away. The tradeoff is in the case where dedicated setup is required, there may be a brief flash of the current route rendered prior to the setup flow. I've also bumped up the delay for how long we wait before rendering the `<AppLoading/>` state from 2 seconds to 3.
Fixes WEB-297
It's quite difficult to reproduce scenarios that would cause the app to take longer to load, so testing that the app still loads as expected is probably the best approach. 
Testing starting workspaces is another good flow that benefits from these changes as well.
<p>Gitpod …

Don't wait for onboarding state to render

---

components/dashboard/src/dedicated-setup/use-check-dedicated-setup.ts

This ensures we don't show the dedicated setup flow on prod saas (gitpod.io). It's a bit of a hacky check atm, but wanted it in there as a safety guard while we sort out some related work around distinguishing different installation types.
Fixes WEB-358
As this explicitly checks for `gitpod.io` as the host, there's not much to test other than making sure the app loads on a preview environment.
<ul>
<li><b>🏷️ Name</b> - bmh-saas-d9604327a75</li>
<li><b>🔗 URL</b> - <a href="https://bmh-saas-d9604327a75.preview.gitpod-dev.com/workspaces" target="_blank">bmh-saas-d9604327a75.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7 …

ensure dedicated setup doesn't show on prod saas

---

components/proxy/plugins/analytics/analytics.go
install/installer/pkg/components/proxy/deployment.go
install/installer/pkg/config/v1/experimental/experimental.go

in case of dedicated we would like to stream to telemetry exporter instead
Fixes #
- Start a workspace, check proxy logs for errors, check segment that events are still reported.
<ul>
<li><b>🏷️ Name</b> - ak-analytic1fb6136ea</li>
<li><b>🔗 URL</b> - <a href="https://ak-analytic1fb6136ea.preview.gitpod-dev.com/workspaces" target="_blank">ak-analytic1fb6136ea.preview.gitpod-dev.com/workspaces</a>.</li>
</ul> …

[analytics plugin] allow to configure segment endpoint

---

.github/workflows/build.yml
.github/workflows/ide-integration-tests.yml
.github/workflows/jetbrains-update-plugin-platform-template.yml
.github/workflows/jetbrains-updates.yml
.github/workflows/preview-env-check-regressions.yml

[gh-action] update IDE github action to default use ws-manager-mk2
Fixes #
<ul>
<li><b>🏷️ Name</b> - pd-update-template</li>
<li><b>🔗 URL</b> - <a href="https://pd-update-template.preview.gitpod-dev.com/workspaces" target="_blank">pd-update-template.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[gha] update IDE github action to default use ws-manager-mk2

---

WORKSPACE.yaml
install/installer/pkg/components/workspace/ide/constants.go

Update code to `1.78.2`
```release-note
NONE
```

Update VS Code Browser to `1.78.2`

---

components/ws-manager-mk2/controllers/create.go

xref: WKS-177 
gitpod:summary
<details>
</details>
<details>
</details>
/hold

Increase workspace TerminationGracePeriodSeconds to avoid removal of nodes

---

components/supervisor/pkg/supervisor/supervisor.go

Created another endpoint `tunnel2` for now to keep backwards compatibility for old versions of local-app
- Try connecting tunneling ssh over websocket, it should work
<ul>
<li><b>🏷️ Name</b> - jp-test-993</li>
<li><b>🔗 URL</b> - <a href="https://jp-test-993.preview.gitpod-dev.com/workspaces" target="_blank">jp-test-993.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

Directly tunnel websocket connection to ssh server

---

components/public-api-server/pkg/apiv1/oidc.go
components/server/src/user/user-service.ts
components/server/src/workspace/gitpod-server-impl.ts

This better co-locates the logic in the service, and allows us to re-use the logic in other places, or when migrating to gRPC
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] Move update user implementation to UserService

---

components/usage/pkg/scheduler/job.go
components/usage/pkg/scheduler/ledger_job.go
components/usage/pkg/scheduler/reset_usage_job.go
components/usage/pkg/scheduler/scheduler.go
components/usage/pkg/scheduler/scheduler_test.go
components/usage/pkg/server/server.go

Follow-up to https://github.com/gitpod-io/gitpod/pull/17167
Fixes #
Unit tests
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[usage] Scheduler with mutex by default

---

components/dashboard/src/components/Header.tsx
components/dashboard/src/components/UsageView.tsx
components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
components/dashboard/src/hooks/use-document-title.ts
components/dashboard/src/projects/Prebuild.tsx
components/dashboard/src/start/StartPage.tsx
components/dashboard/src/teams/JoinTeam.tsx
components/dashboard/src/teams/NewTeam.tsx

Fixes WEB-344
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[dashboard] update document title on setup

---

components/dashboard/src/data/workspaces/create-workspace-mutation.ts
components/dashboard/src/start/start-workspace-options.ts
components/dashboard/src/workspaces/CreateWorkspacePage.tsx
components/gitpod-protocol/src/util/gitpod-host-url.ts

Fixes an endless loop that could happen when opening a context in the context fo the wrong org.
Fixes WEB-334
https://se-create-ws-loop.preview.gitpod-dev.com/workspaces
1) create two orgs
2) memorize workspace options in one org
3) switch to the other org
4) use a contextURL for the memorized repo
Expected behavior is that the dashboard switched to the org the start options were remembered for and starts the workspace.
https://se-create-ws-loop.preview.gitpod-dev.com/workspaces
<details>
</details>
<details>
</details>
If enabled …

[dashboard] fix reload

---

components/gitpod-db/go/stripe_customer.go
components/gitpod-db/src/container-module.ts
components/server/package.json
components/server/src/container-module.ts
components/server/src/iam/iam-session-app.ts
components/server/src/migration/user-to-team-migration-service.spec.db.ts
components/server/src/migration/user-to-team-migration-service.ts
components/server/src/user/stripe-service.ts
components/server/src/user/user-service.ts
components/server/src/workspace/gitpod-server-impl.ts
components/usage/pkg/apiv1/billing.go
components/usage/pkg/stripe/stripe.go
scripts/mysql-test.sh

The org-only migration needs to update the attribution id in stripe as well.
Fixes WEB-351
gitpod:summary
<details>
</details>
<details>
</details>
/hold

Update stripe customers during migration

---

components/supervisor/pkg/supervisor/supervisor.go
components/supervisor/pkg/supervisor/supervisor_test.go

Relates [PRD-59](https://linear.app/gitpod/issue/PRD-59/persisted-terminal-history)
1. start a workspace in your preview environment
2. execute some command in this workspace
3. restart this workspace
4. use up arrow key to check if history still in there
repeat these step in different ide, i.e. Jetbrains, ssh, vscode desktop
<ul>
<li><b>🏷️ Name</b> - pd-bash-history</li>
<li><b>🔗 URL</b> - <a href="https://pd-bash-history.preview.gitpod-dev.com/workspaces" target="_blank">pd-bash-history.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for …

[supervisor] Persist bash history across workspace restarts PRD-59

---

install/installer/pkg/components/workspace/ide/constants.go

Just updated the extension to https://github.com/gitpod-io/gitpod-code/commit/11506211281adf4b61b4f0111e87963b202f5d80.
https://github.com/gitpod-io/gitpod-code/pull/10
Look at VS Code Browser and see no release notes (or any other way to trigger them)
<ul>
<li><b>🏷️ Name</b> - ft-update-b579dbdab9</li>
<li><b>🔗 URL</b> - <a href="https://ft-update-b579dbdab9.preview.gitpod-dev.com/workspaces" target="_blank">ft-update-b579dbdab9.preview.gitpod-dev.com/workspaces</a>.</li> …

Remove VS Code changelogs (update `gitpod-web`)

---

components/gitpod-db/src/typeorm/user-db-impl.ts
components/gitpod-db/src/user-db.spec.db.ts
components/gitpod-db/src/user-db.ts
components/server/src/iam/iam-session-app.spec.ts
components/server/src/iam/iam-session-app.ts
components/server/src/user/user-service.ts

First try to look up accounts by `[subjectID, audience]` as composite key, then try to lookup by email address. The scope of this lookup is limited to the Org owning the SSO configuration.
Fixes WEB-346
* See unit test
* Regular SSO login should still work
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[SSO] find organizational accounts by email – WEB-346

---

components/docker-up/dependencies.sh
components/ws-daemon/debug.Dockerfile
components/ws-daemon/go.mod
components/ws-daemon/go.sum
components/ws-daemon/leeway.Dockerfile
install/installer/go.mod
install/installer/go.sum

Fix regressions introduced in previous versions https://github.com/opencontainers/runc/releases/tag/v1.1.7
gitpod:summary
<details>
</details>
<details>
</details>
/hold

Update runc to v1.1.7

---

.gitpod.yml

To keep these the same as other tasks, and make it easier to have a sane setup on narrow screens
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[gitpod] Remove go task open right

---

components/server/src/jobs/fix-stripe-job.ts
components/server/src/jobs/runner.ts

The job runner schedules jobs using `repeat` which lets it wait the `frequencyMs` before running it the first time. This change will run all jobs on start and subsequently every `frequencyMs`.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] immediately run jobs

---

components/server/src/workspace/gitpod-server-impl.ts

Fixes WEB-349
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] fix adminSetUsageLimit

---

components/dashboard/src/app/AppBlockingFlows.tsx
components/dashboard/src/dedicated-setup/DedicatedSetup.tsx
components/dashboard/src/dedicated-setup/use-needs-setup.ts
components/dashboard/src/dedicated-setup/use-show-dedicated-setup.ts

Fixing some bugs with when we show the dedicated setup flow.
* Ensure `needsSetup` is only true after we've loaded onboarding state. This was causing the setup flow to sometimes render when it shouldn't, and sometimes not render when it should.
* Removing query cache & stale times for `getOnboardingState`. This was causing issues at the end of the setup flow.
* Removed logic that sets setup flow to in progress from a useEffect to in the render. The `useEffect` wasn't running as reliably as it seemed to be setup to. This felt wrong to me at first, but because of the check against the value it changes, it won't cause render loops. Also, [this part](https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes) of the react docs does suggest this approach over …

SSO Setup screen showing on setup cell

---

components/dashboard/src/components/SelectWorkspaceClassComponent.tsx

Minor follow-up fix from https://github.com/gitpod-io/gitpod/pull/17622. Cc @easyCZ 
This will move the class description on the second line to scale better, following the editor metadata (Desktop, Browser). Similarly, we can later use that element for surfacing context metadata.
~~⚠️ Haven't tested code changes in a preview environment.~~
|-|-|
| <img width="501" alt="Frame 1500" src="https://github.com/gitpod-io/gitpod/assets/120486/d3fd9e94-4a1e-4c7f-9f95-38dd27a0753d"> | <img width="501" alt="Frame 1501" src="https://github.com/gitpod-io/gitpod/assets/120486/0826e90d-86d8-4cfe-8d04-1ef646d01ddf"> |
Try opening a workspace in /new, changing the default editor in user /preferences, or going through the user onboarding and notice that the new UX for selecting workspace …

Fix new workspace class element overflow

---

components/ws-daemon/pkg/controller/workspace_operations.go

Log the error when uploads fail
Relates to WKS-183
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[ws-daemon] Log backup failure error

---

components/server/src/workspace/workspace-starter.ts

Right now, the default auto-refresh duration on the mutex is 1sec, and we have to 
```
A lock `duration` must be at least 100ms greater than the `automaticExtensionThreshol
```
Our current default config is 
```
return new Redlock([this.redis.get()], {
// The expected clock drift; for more details see:
// http://redis.io/topics/distlock
driftFactor: 0.01, // multiplied by lock ttl to determine drift time
// The max number of times Redlock will attempt to lock a resource
// before erroring.
retryCount: 3,
// the time in ms between attempts
retryDelay: 200, // time in ms
// the max time in ms randomly added to retries
// to improve performance under high contention
// see https://www.awsarchitectureblog.com/2015/03/backoff.html
retryJitter: 200, // time in ms
// The minimum remaining time …
```

[server] Fix workspace start mutex initial lock duration

---

components/dashboard/.eslintrc.js
components/dashboard/src/admin-context.tsx
components/dashboard/src/payment-context.tsx
components/dashboard/src/projects/project-context.tsx

This fixes a few react Contexts that are sending unstable (change on every render) context values by wrapping them in useMemo(). This helps avoid re-renders that aren't necessary. I've also enabled a lint rule to catch these in the future.
Fixes WEB-391
Verify you can login and create projects. Bonus points for setting up a subscription for your org.
gitpod:summary
<details>
</details>
<details>
</details> …

Fixing unstable react context values and adding lint rule

---

WORKSPACE.yaml

This PR updates the JetBrains IDE images to the most recent `stable` version.
<details>
1. For each IDE changed on this PR, follow these steps:
2. Open the preview environment generated for this branch
3. Choose the stable version of the IDE that you're testing as your default editor
4. Start a workspace using any repository (e.g: `https://github.com/gitpod-io/empty`)
5. Verify that the workspace starts successfully
6. Verify that the IDE opens successfully
7. Verify that the version of the IDE corresponds to the one being updated in this PR
The following resources should help, in case something goes wrong (e.g. workspaces don't start):
- …

[JetBrains] Update IDE images to new build version

---

components/public-api-server/pkg/auth/personal_access_token_test.go

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[papi] Remove rogue print from PAT tests

---

install/installer/pkg/config/v1/config.go

We run ShiftFS in gitpod.io and Dedicated, it should be the default.
Also, preview environments are presently using the default, which happens to be FuseFS. :grimacing: 
gitpod.io: https://github.com/gitpod-io/ops/blob/cc5006df73f8803fc9f6e5559187f2bc79a5ee4f/deploy/workspace/installer-values.yaml#L897
Dedicated: https://github.com/gitpod-io/gitpod-dedicated/blob/c1c7ac706511635f40c58ff350463dcfc8d1e3fd/bootstrap/lambdas/application/app/installer/workspace.yaml#L233
Fixes # n/a
Start a workspace
<ul>
<li><b>🏷️ Name</b> - kylos101-fsmethod</li>
<li><b>🔗 URL</b> - <a href="https://kylos101-fsmethod.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-fsmethod.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 …

[installer] default the FSShiftMethod to ShiftFS

---

components/public-api-server/pkg/apiv1/identityprovider.go
components/public-api-server/pkg/apiv1/identityprovider_test.go

This PR adds the `email` claim to the ID tokens produced by the IDP feature.
Fixes #17530 
see unit tests or `gp idp token`
<ul>
<li><b>🏷️ Name</b> - cw-fix-17530</li>
<li><b>🔗 URL</b> - <a href="https://cw-fix-17530.preview.gitpod-dev.com/workspaces" target="_blank">cw-fix-17530.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[idp] Add email to ID token

---

components/gitpod-db/src/auth-provider-entry.spec.db.ts
components/gitpod-db/src/typeorm/migration/1684328022688-AuthProviderUniqueHostName.ts
components/server/src/auth/auth-provider-service.ts

Stumbled over this [log message](https://cloudlogging.app.goo.gl/hExAVvtFJ1Dwu3cc7). Which is caused by two entries in d_b_auth_provider_entry with the same host. There is only this one duplicate case in the prdo DB and I don't know how it got there, but instead of always ignoring one entry we should enforce this on insert/update.
The message is logged because the actual config that is used alternates with every call. 
And since we cache by host name it gets re-created every time.
https://github.com/gitpod-io/gitpod/blob/079d31e7de2e0319a097ef391156e1be05acbe78/components/server/src/auth/host-context-provider-impl.ts#L84-L109
Fixes #
gitpod:summary
<details>
</details>
<details> …

[server] delete duplicate auth provider

---

components/server/src/iam/iam-session-app.spec.ts
components/server/src/iam/iam-session-app.ts
components/server/src/user/user-service.ts

Updates email address of SSO users on each sign-in.
Fixes WEB-370
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[server] update OIDC users on sign-in (email) – WEB-370

---

components/gitpod-db/go/oidc_client_config.go
components/gitpod-db/go/oidc_client_config_test.go
components/public-api-server/pkg/apiv1/oidc.go
components/public-api-server/pkg/apiv1/oidc_test.go
components/public-api-server/pkg/oidc/service.go

This is a follow-up to #17576. 
With this change it's possible to deactivate a client config by using `SetClientConfigActivation` RPC method with `Activate: false` parameter.
See unit test.
gitpod:summary
<details>
</details>
<details>
</details>
/hold

Implement deactivation of OIDC client configs – WEB-333

---

components/gitpod-db/src/typeorm/workspace-db-impl.ts
components/gitpod-db/src/workspace-db.ts

removes a non used join in an [expensive query](https://console.cloud.google.com/sql/instances/gitpod-prod-us-west1/insights;database=gitpod;start=2023-05-22T05:26:09.107Z;end=2023-05-22T11:26:09.107Z;trace=285f231e970ccae54055b44e873b7b08;span=7371e3939908471b;query_hash=4131081551255458668;sort_by=TOTAL_EXEC_TIME?project=gitpod-191109)
Fixes #
gitpod:summary
<details>
</details>
<details>
</details> …

[db] removed unused instance join

---

.github/CODEOWNERS
components/scrubber/BUILD.yaml
components/scrubber/README.md
components/scrubber/config.go
components/scrubber/example_test.go
components/scrubber/go.mod
components/scrubber/go.sum
components/scrubber/sanitisation.go
components/scrubber/sanitisation_test.go
components/scrubber/scrubber.go
components/scrubber/scrubber_test.go

This PR prepares the interface for a new `scrubber` library which we'd use to remove sensitive information at the application level.
See the [design doc](https://www.notion.so/gitpod/Data-Sanitisation-4747f7941ed54b28b2459bab5220febd) for more information.
This library can be imported using `github.com/gitpod-io/gitpod/components/scrubber` as import path. 
>**Note**: Importing this library from outside this repo will download the entire Gitpod repo, a fairly slow operation.
gitpod:summary
<details>
</details>
<details>
</details>
If …

Initial commit of the scrubber

---

components/gitpod-db/src/tables.ts

We have recently started to diirectly delete workspace related records but forgot to remove the config from the periodic deleter, which now tries to find records in very large tables without success.
E.g. 
```sql
SELECT
`id`
FROM
`d_b_workspace_instance`
WHERE
`deleted` = TRUE
LIMIT
?
```
[runs for 15min on average](https://console.cloud.google.com/sql/instances/gitpod-prod-us-west1/insights;database=gitpod;start=2023-05-15T11:02:19.802Z;end=2023-05-22T11:02:19.802Z;trace=2e27a58eb21c6d5afd9c97345e491702;span=39ad907303feaa23;query_hash=14991341230805561798;sort_by=TOTAL_EXEC_TIME?project=gitpod-191109) because it scans the full table and doesn't find a single record.
Fixes #
gitpod:summary
<details> …

[periodic deleter] remove unmanaged tables

---

components/dashboard/src/components/ConfirmationModal.tsx
components/dashboard/src/components/toasts/Toasts.tsx
components/dashboard/src/components/toasts/reducer.ts
components/dashboard/src/teams/sso/ActivateConfigModal.tsx
components/dashboard/src/teams/sso/OIDCClientConfigModal.tsx
components/dashboard/src/teams/sso/OIDCClientListItem.tsx
components/dashboard/src/teams/sso/OIDCClients.tsx
components/dashboard/src/teams/sso/use-verify-client.ts

Some followup work from #17635 
* Updating some copy
* Added clickable actions inside toast notifications for verifying and activating configs. Needed to shift some of the activate & verify logic up a few component levels for this to work right.
* Shifted the `<ConfirmationModal/>`'s `alert` to be above the warning text based on feedback.
* Made the `toast()` function (from `useToast`) accept a ReactNode for the message instead of only a string. This allows for clickable links, etc, inside of toasts. Would be good to iterate here and settle on a pattern for action buttons on toasts to be more explicit. Would also be nice to have a specific error style toast as well. cc @gtsiolis 
| Header | Header |
| <img width="404" alt="image" …

Touch up SSO Config changes

---

components/dashboard/src/provider-utils.tsx

This fixes an issue where the onSuccess callback to the auth popup flows sometimes run when they shouldn't. This can happen if any unsuccessful flows (user closed popup) precede a successful one. The successful one will then trigger all other ones to fire their onSuccess as well.
Adds a unique key for each popup auth flow so we can correlate the callbacks to the right success handlers. We were already passing a `message=success` param throughout the flow, and validating the `success` value. I've built onto that making the value we pass through the flow, and check at the end unique. This will prevent scenarios where multiple previously opened flows that never finished may all have their success callbacks fired as soon as a successful flow completes.
I've also added a check against the …

Auth window message success handlers running more than once

---

components/server/src/prebuilds/prebuilt-status-maintainer.ts

This PR reduces the amount of prebuilt status updates to half the updateable age (i.e. 6h /2 = 3h). 
I'm not sure we need this code at all, but I I've seen two occasions in the past days where this code actually did something (two log entries). So I guess we keep it, but running this expensive query every minute is way too often if it only is there to fix a status that has been pending for over 6h.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
Valid options …

[server] run status updater less frequently

---

components/server/src/jobs/runner.ts
components/server/src/jobs/workspace-gc.ts
install/installer/pkg/components/server/configmap.go

We are currently running workspace garabge collection every 5 minutes, which is way more often than needed. Also jobs get executed more often than the configured frequency because we release the lock too early.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] garbage collect ws less often

---

components/ws-manager-mk2/controllers/maintenance_controller.go
components/ws-manager-mk2/controllers/status.go
components/ws-manager-mk2/controllers/suite_test.go
components/ws-manager-mk2/controllers/timeout_controller.go
components/ws-manager-mk2/pkg/maintenance/maintenance.go
components/ws-manager-mk2/service/manager.go
install/installer/pkg/components/ws-manager-mk2/configmap.go
install/installer/pkg/components/ws-manager-mk2/constants.go

Removes the maintenance mode ConfigMap from the installer, such that its data does not get overwritten when a new install is applied. The alternative is filtering out the CM from the installer manifests but this seems simpler to reason about.
Also updated the maintenance logic to do load the ConfigMap on the first check. This fixes the case where after a rollout, maintenance mode will be briefly true until the first time the CM gets reconciled (which can take 10s of seconds due to waiting to acquire leader election).
Relates to WKS-128 and WKS-129
In a preview env, check that maintenance is disabled when the maintenance CM does not exist, and that it gets enabled once it exists and has `enabledUntil` set to a future timestamp.
Preview URL: …

[ws-manager-mk2] Remove maintenance CM from installer

---

components/server/src/auth/auth-provider.ts
components/server/src/auth/authenticator.ts
components/server/src/auth/generic-auth-provider.ts
components/server/src/auth/login-completion-handler.ts
components/server/src/bitbucket-server/bitbucket-server-auth-provider.ts
components/server/src/bitbucket/bitbucket-auth-provider.ts
components/server/src/container-module.ts
components/server/src/dev/authenticator-dev.ts
components/server/src/github/github-auth-provider.ts
components/server/src/gitlab/gitlab-auth-provider.ts

* Stops using session storage to store the AuthFlow
* Instead, uses a signed JWT as part of the sign-in dance attached to the `state` param
* The `state` param is echoed back to us by the auth provider, and we extract our information from it
Part of WEB-365
1. Preview
2. Sign-in with different providers, observe sign-in works
<ul>
<li><b>🏷️ Name</b> - mp-server-70f37720f6</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-70f37720f6.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-70f37720f6.preview.gitpod-dev.com/workspaces</a>.</li> …

[server] Use JWTs for Sign-in flow state WEB-365

---

components/server/src/container-module.ts
components/server/src/jobs/runner.ts
components/server/src/jobs/snapshots.ts
components/server/src/server.ts
components/server/src/workspace/snapshot-service.ts

Migrate snapshot job to Redis and our new jobs wrapper.
This is the final piece, which unblocks removal of Messagebus leadership election
Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-server-cb5b78d460</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-cb5b78d460.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-cb5b78d460.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[server] Migrate snapshots jobs WEB-225

---

components/dashboard/src/data/featureflag-query.ts
components/dashboard/src/whatsnew/MigrationPage.tsx
components/gitpod-protocol/src/gitpod-service.ts
components/gitpod-protocol/src/protocol.ts
components/server/src/auth/rate-limiter.ts
components/server/src/migration/user-to-team-migration-service.spec.db.ts
components/server/src/migration/user-to-team-migration-service.ts
components/server/src/user/user-service.ts
components/server/src/workspace/gitpod-server-impl.ts

This is a preparation step for running the user migration as a job and then flagging users so thex see the migration message next time they log into the product.
Also removes two feature flags, that are no longer needed.
Fixes WEB-371
This is what I did during my test:
- signup on the preview env. As a new user you should not see the migration message.
- update the `isMigratedToTeamOnlyAttribution` flag in the DB
- reload page or religion and verifythat you now see the message as the user has been migrated a second time (also gets another org which is expected)
<ul>
<li><b>🏷️ Name</b> - se-migration-message</li>
<li><b>🔗 URL</b> - <a href="https://se-migration-message.preview.gitpod-dev.com/workspaces" …

Show migration message after migration

---

components/server/src/workspace/context-parser.spec.ts
components/server/src/workspace/context-parser.ts

Makes sure branches from issue contexts are always spec-compliant and therefore valid for git. 
Fixes WEB-375
Testing should be done by logging in through SSO and starting a workspace from an issue context. I unfortunately couldn't find a way to do the SSO login, but for proper testing it has to be done like that.
<ul>
<li><b>🏷️ Name</b> - ft-fix-issd380c132cf</li>
<li><b>🔗 URL</b> - <a href="https://ft-fix-issd380c132cf.preview.gitpod-dev.com/workspaces" target="_blank">ft-fix-issd380c132cf.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for …

Correctly infer branch names for SSO users

---

components/gitpod-db/src/typeorm/app-installation-db-impl.ts

The query to fetch the installation is called on every github event. It is not using the given indexes properly and creates therefore unnecessarly high load.
See [dashboard](https://console.cloud.google.com/sql/instances/gitpod-prod-us-west1/insights;start=2023-05-23T13:45:11.764Z;end=2023-05-23T19:45:11.764Z;span=0d8e47e9f396d891;sort_by=TOTAL_EXEC_TIME?project=gitpod-191109)
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[db] optimize often used qery

---

.github/workflows/ide-integration-tests.yml

gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Add default value for manually GHA running

---

components/server/src/jobs/org-only-migration-job.ts
components/server/src/migration/user-to-team-migration-service.ts
components/server/src/user/user-service.ts
components/server/src/workspace/gitpod-server-impl.ts

Increases the amount of users migrated per job run and adds more log information
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] adjust migration job

---

components/server/src/session-handler.ts

Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-server-cef7053450</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-cef7053450.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-cef7053450.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[server] Fetch User based on JWT Session sub

---

components/server/src/jobs/database-gc.ts
components/server/src/jobs/org-only-migration-job.ts
components/server/src/jobs/ots-gc.ts
components/server/src/jobs/runner.ts
components/server/src/jobs/snapshots.ts
components/server/src/jobs/token-gc.ts
components/server/src/jobs/webhook-gc.ts
components/server/src/jobs/workspace-gc.ts
components/server/src/migration/user-to-team-migration-service.ts
components/server/src/workspace/workspace-starter.ts

In a few places the resources argument to redlock.using had been interpreted as a key (like in react-query) but it is a list of locked resources.
This PR changes 
- the job API so that we use the job's name and optionally any number of additional resources for locking.
- two other places where an array of string was passed to make the lock more specific instead of widening it.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[server] fix wrong use of redlock's resources argument

---

components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx

If the user hasn’t entered a host value yet in the form, our links are broken as described in the issue. ~I’ve opted to have the links default to github.com and gitlab.com when there’s no custom host entered in the form yet, but once there is, the links will use that host.~
After some discussion, we'll simplify this view so the hint text links below the input aren't dynamic, and we just link to the corresponding GitLab or GitHub docs.
| GitLab | GitHub | Bitbucket Server |
|--------|--------|--------|
| ![image](https://github.com/gitpod-io/gitpod/assets/367275/ec562b7d-5979-49fb-bbe5-8967b9f1ce8a) | ![image](https://github.com/gitpod-io/gitpod/assets/367275/1193091b-db40-43e5-b4cc-003134f9ec45) | ![image](https://github.com/gitpod-io/gitpod/assets/367275/4c148161-e3bb-4ab5-88db-bb0a36fb7a …

Fix dev settings link for git providers

---

components/dashboard/src/Login.tsx

There was a small icon size shift over the last few weeks. This will change the icon size of the first icon in the login page.
See [relevant discussion](https://gitpod.slack.com/archives/C01KPEPQYE6/p1684925014417869) (internal) and WEB-406.
| <img width="1512" alt="Screenshot 2023-05-24 at 20 08 04" src="https://github.com/gitpod-io/gitpod/assets/120486/79708a2a-1d4c-428f-ae25-b0c4761bf2e1"> | <img width="1512" alt="Screenshot 2023-05-24 at 20 07 53" src="https://github.com/gitpod-io/gitpod/assets/120486/1dbd38eb-951a-4f16-9f6b-41db3edde668"> | 
Try to login, and notice the different icon size on the login page when you're trying to login for the first time.
<ul>
<li><b>🏷️ Name</b> …

Update login page icon size

---

components/dashboard/src/workspaces/CreateWorkspacePage.tsx

When creating workspaces in organizations you have not requested access for Gitpod yet, `{" "}` would appear as part of the message, which is unwanted.
<ul>
<li><b>🏷️ Name</b> - ft-create-ws-msg</li>
<li><b>🔗 URL</b> - <a href="https://ft-create-ws-msg.preview.gitpod-dev.com/workspaces" target="_blank">ft-create-ws-msg.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

Unwanted characters in workspace create error message

---

components/dashboard/src/teams/Members.tsx
components/dashboard/src/utils.ts

Copy to clipboard functionality broke inside of modals in #17684 due to the focus trap, and the hidden textinput we append to the `document.body` (outside of the focus trap). This results in programatic select/copy to not work. We could adjust where we append that temporary element based on the active element, but I think we can avoid all that complexity and just use the builtin clipboard api that's [widely supported](https://caniuse.com/mdn-api_clipboard_writetext) now.
```ts
navigator.clipboard.writeText(text);
```
Fixes WEB-408
You'll need to have a copy to clipboard input inside of a modal to test this.
* Navigate to Org Members and click the Invite Members button. 
* Use the copy to clipboard icon and verify it works. …

Fix copy to clipboard in Modals

---

operations/observability/mixins/workspace/dashboards/success-criteria.json

Remove mk1 from workspace success. Also added P95/P75P50P25/P01 to the workspace startup time graph.
Fixes WKS-121
gitpod:summary
<details>
</details>
<details>
</details>
/hold

[ws-manager-mk2] Remove mk1 from workspace success

---

.github/CODEOWNERS
.gitleaks.toml
codecov.yml
gitpod-ws.code-workspace

Workspace no longer reports:
```
Error loading workspace folders (expected 37, got 36) failed to load view for file:///workspace/gitpod/components/ws-manager: err: chdir /workspace/gitpod/components/ws-manager: no such file or directory: stderr:
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details> …

Remove some leftover ws-man refs to fix vscode workspace

---

components/dashboard/public/complete-auth/index.html
components/dashboard/src/Login.tsx
components/dashboard/src/OauthClientApproval.tsx
components/dashboard/src/provider-utils.tsx
components/server/src/oauth-server/oauth-controller.ts

The Login component can use the provided `returnToPath` to forward on client request. Passing the same value down into the callback handlers is completely unnecessary.
Part of WEB-50
* try with local app and see if the OAuth service works as usual
<ul>
<li><b>🏷️ Name</b> - at-cleanupc42cd04d49</li>
<li><b>🔗 URL</b> - <a href="https://at-cleanupc42cd04d49.preview.gitpod-dev.com/workspaces" target="_blank">at-cleanupc42cd04d49.preview.gitpod-dev.com/workspaces</a>.</li> …

[dashboard] remove `returnTo` param from /complete-auth endpoint

---

components/server/src/jobs/runner.ts
components/server/src/redis/mutex.ts

Jobs are expected to run in parallel and have only one job run succeed
to aquire the log and actually run the job. This is not the case for other
uses of a distributed lock, where we just want to postpone the execution
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] reduce logging

---

components/server/src/jobs/org-only-migration-job.ts

We can migrate twice as many users per run
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] double amount of migrated users per run

---

components/dashboard/src/admin/BlockedEmailDomains.tsx
components/dashboard/src/admin/admin.routes.ts
components/dashboard/src/app/AppRoutes.tsx
components/gitpod-db/src/email-domain-filter-db.ts
components/gitpod-db/src/typeorm/email-domain-filter-db-impl.ts
components/gitpod-protocol/src/admin-protocol.ts
components/server/src/auth/rate-limiter.ts
components/server/src/workspace/gitpod-server-impl.ts

Allows admins to manage the list of blocked email domains.
Fixes #
<ul>
<li><b>🏷️ Name</b> - se-admin-bb0a5e9ec1e</li>
<li><b>🔗 URL</b> - <a href="https://se-admin-bb0a5e9ec1e.preview.gitpod-dev.com/workspaces" target="_blank">se-admin-bb0a5e9ec1e.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[server] expose admin ui for blocked email domains

---

components/dashboard/src/components/Modal.tsx
components/dashboard/src/components/billing/AddPaymentMethodModal.tsx

The billing modal potentially renders an iframe for 3ds verification. Because this is appended to the document body, we need to disable focus lock on the modal to avoid interfering with the iframe form inputs.
Fixes WEB-413
* Upgrade billing plan using a stripe test credit that forces 3ds verification: `4000002760003184`
* When the test verification ui appears, try and tab through the buttons. If that works, then this is successfully disabling the focus lock.
<ul>
<li><b>🏷️ Name</b> - bmh-disablb1f1454002</li>
<li><b>🔗 URL</b> - <a href="https://bmh-disablb1f1454002.preview.gitpod-dev.com/workspaces" target="_blank">bmh-disablb1f1454002.preview.gitpod-dev.com/workspaces</a>.</li> …

Disable focus lock on billing modal

---

operations/observability/mixins/workspace/rules/central/nodes.yaml

Alert when workspace node pools are under high load.
[Runbook](https://github.com/gitpod-io/runbooks/pull/414).
Fixes # n/a
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[obs] alert when cluster is under high load

---

components/gitpod-db/go/team.go
components/gitpod-db/go/team_test.go
components/public-api-server/pkg/oidc/service.go

This PR fixes the lookup for SSO configs in Dedicated installations. If no identifier is provided, it should try to find a single Org which has an active SSO config. 
This PR doesn't solve the issue, that more than one Org was created on an internal Dedicated installation. Evaluating `isSingleOrgInstallation` sound reasonable to solve that task. This change improves resilience and unblocks users.  
Fixes WEB-409
See unit tests
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[papi] Start request should search for single Org with active SSO – WEB-409

---

components/dashboard/src/admin/BlockedEmailDomains.tsx
components/dashboard/src/admin/BlockedRepositories.tsx

Minor copy update for the search alert in `/admin`.
Follow-up from https://github.com/gitpod-io/gitpod/pull/17754. Cc @svenefftinge @AlexTugarev @geropl 
1. Go to `/admin/blocked-email-domains`
2. Notice the search alert copy mentions the email domain URL, not the repository URL.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

Update admin search alert copy

---

components/server/src/container-module.ts
components/server/src/jobs/fix-stripe-job.spec.db.ts
components/server/src/jobs/fix-stripe-job.ts
components/server/src/jobs/runner.ts

Run a job that fixes the users for which the stripe update didn'T work due to #17764
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] run job, that fixes bad stripe migration

---

components/public-api-server/pkg/oidc/oauth2.go
components/public-api-server/pkg/oidc/router.go
components/server/src/user/user-controller.ts

This PR improves reporting of errors which might happen during the OAuth/OIDC flow on backend.
Issues revealed:
* errors are reported twice, in some cases
* toast notification expires after a couple of seconds, user might miss them
Fixes WEB-50
* create any SSO config, e.g. using `accounts.google.com`, set an invalid secret and try to verify
<ul>
<li><b>🏷️ Name</b> - at-forward-errors</li>
<li><b>🔗 URL</b> - <a href="https://at-forward-errors.preview.gitpod-dev.com/workspaces" target="_blank">at-forward-errors.preview.gitpod-dev.com/workspaces</a>.</li> …

Forward errors through /complete-auth endpoint – WEB-50

---

components/gitpod-db/src/blocked-repository-db.ts
components/gitpod-db/src/typeorm/blocked-repository-db-impl.ts
components/gitpod-db/src/typeorm/entity/db-blocked-repository.ts
components/server/src/auth/authenticator.ts
components/server/src/linkedin-service.ts
components/server/src/prebuilds/incremental-prebuilds-service.ts

Fixes some imports so `yarn test` works reliably (again).
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server, db] Fix some imports to re-enable "yarn test" in server

---

components/gitpod-protocol/go/gitpod-service.go
components/gitpod-protocol/go/mock.go
components/local-app/pkg/bastion/bastion.go
components/public-api-server/pkg/apiv1/workspace.go
components/public-api-server/pkg/apiv1/workspace_test.go
components/supervisor/cmd/call-server.go
components/supervisor/pkg/ports/exposed-ports.go
components/supervisor/pkg/serverapi/publicapi.go

Add WorkspaceUpdates method, so it reports all events from a workspaceId
Also replace the old InstanceUpdates method
<ul>
<li><b>🏷️ Name</b> - jp-workspa63f29a1b95</li>
<li><b>🔗 URL</b> - <a href="https://jp-workspa63f29a1b95.preview.gitpod-dev.com/workspaces" target="_blank">jp-workspa63f29a1b95.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

Add WorkspaceUpdates method

---

components/gitpod-cli/cmd/ports-list.go
components/gitpod-cli/cmd/ports-protocol.go
components/supervisor/go.mod
components/supervisor/go.sum
components/supervisor/pkg/ports/ports.go

Support "Change port protocol" (HTTP/HTTPS)
Some user using `https` for their service, but now Gitpod only support forward `http` protocol, which means these service cannot visit in workspace ports url, they only can test it via local-desktop IDE (ssh port-forward)
This PR also changes supervisor port forward using nftable, it support any protocol, more fast and easy.
Part of #15915
1. start a workspace with this repo https://github.com/iQQBot/test.test/tree/https in [preview env](https://pd-port-15915.preview.gitpod-dev.com/workspaces)
2. it should able access port 5173 via workspace port url
3. use `curl https://localhost:5173 -v -k` make sure protocol is https
4. you can also using `gp ports protocol 5173:https` to change protocol
5. or define port protocol in `.gitpod.yml`
6. change …

Support forward https protocol port

---

components/public-api-server/pkg/identityprovider/cache.go
components/public-api-server/pkg/identityprovider/idp.go
components/public-api-server/pkg/identityprovider/idp_test.go

Correctly set the `Content-Type` of the endpoint[^1]. Also changes two typos I noticed :).
Fixes #
Visit https://api.ft-idp-improvements.preview.gitpod-dev.com/idp/keys and check the headers
<ul>
<li><b>🏷️ Name</b> - ft-idp-improvements</li>
<li><b>🔗 URL</b> - <a href="https://ft-idp-improvements.preview.gitpod-dev.com/workspaces" target="_blank">ft-idp-improvements.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

Respond to `/idp/keys` with JSON

---

components/gitpod-cli/cmd/env.go

fix IDE-130
- Use gp env with invalid arguments
- Check logs of ide-metrics that they don't have such errors as before
<ul>
<li><b>🏷️ Name</b> - ak-gp-evn-0396c44d0d</li>
<li><b>🔗 URL</b> - <a href="https://ak-gp-evn-0396c44d0d.preview.gitpod-dev.com/workspaces" target="_blank">ak-gp-evn-0396c44d0d.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

Report gp env arg parsing errors as user errors

---

components/common-go/experiments/types.go
components/gitpod-cli/cmd/validate.go

In `logrus`, log.Entry 's Logger property is the parent Logger. So we can't use `.Logger.SetLevel` to change log level
https://go.dev/play/p/OtGHXjEm7sL
Change value of `useParentLogger` to see different
Fixes #
You can open PR with Gitpod and use `hot-deploy.sh`
1. Add log.Info("helloooooooooo") to supervisor publicapi.go after configcat Client created `hot-deploy supervisor`
2. Start/Restart workspace in preview env it should log hello
3. Revert fixing changes in common-go and `hot-deploy supervisor`
4. It should log nothing
<ul>
<li><b>🏷️ Name</b> - hw-fix-ide-127</li>
<li><b>🔗 URL</b> - <a href="https://hw-fix-ide-127.preview.gitpod-dev.com/workspaces" target="_blank">hw-fix-ide-127.preview.gitpod-dev.com/workspaces</ …

Fix incorrect log level setup - IDE-127

---

components/server/src/prometheus-metrics.ts
components/server/src/workspace/workspace-starter.spec.ts
components/server/src/workspace/workspace-starter.ts

Show error message when cluster is not available due to maintenance
Fixes WKS-185
<ul>
<li><b>🏷️ Name</b> - fo-wks-185d6a652c34e</li>
<li><b>🔗 URL</b> - <a href="https://fo-wks-185d6a652c34e.preview.gitpod-dev.com/workspaces" target="_blank">fo-wks-185d6a652c34e.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details> …

[server] Show maintenance error message

---

components/gitpod-db/package.json
components/server/BUILD.yaml
components/server/src/api/teams.spec.db.ts
components/server/src/container-module.ts
components/server/src/user/user-service.spec.db.ts

Enables `server` db-tests in CI (again). 
This restores the previous behavior: we leverage leeway to only run a db test per ~commit~ _leeway cache key_ (NOT on every CI/build run). This makes it harder to understand whether a test ran or not, and waaaay harder to find the relevant build for a component in the GitHub actions UI. Also, it's potentially subject to leeway issues and cache issues.
One could argue that we want to run it on every build, independent of caching. Let's have that discussion and adjustments in a follow up PR.
Fixes: WEB-436
Depends on: https://github.com/gitpod-io/gitpod/pull/17786
- look at the output of the build action
- see that [the output for server:dbtest](https://github.com/gitpod-io/gitpod/actions/runs/5134617596/jobs/9238878908#step:14:4146), and verify …

Have db-tests run during CI again

---

components/public-api-server/pkg/identityprovider/cache.go
components/public-api-server/pkg/identityprovider/cache_test.go
components/public-api-server/pkg/server/server.go

[idp] periodically persist public key
The current implementation tries to refresh the ttl of the publickey only when someone uses the idp for authentication, the problem with this is that if no one uses it for `1 hour` (our default ttl), there will be no key on redis, which results in accessing the keys endpoint with the key of the current pod, which is an obvious problem for a `public-api-server` running with multiple replicates that only returns its own publickey each time.
In addition, the keyid in the previous implementation is always random, which leads to a random keyid being stored each time when trying to persist again once the key expires, which leads to a very long list of keys if more people use them, and they are all duplicates (only the key ids are different)
This PR fixes …

[idp] periodically persist public key

---

components/gitpod-db/src/typeorm/entity/db-identity.ts
components/gitpod-db/src/typeorm/migration/1685694597883-RemoveIdentityTokens.ts
components/gitpod-db/src/typeorm/user-db-impl.ts
components/gitpod-protocol/src/protocol.ts
components/server/src/workspace/gitpod-server-impl.ts

`tokens` column is unused for long time, but we forgot to remove it.
Part of WEB-400
* Verify that login into the preview env is working.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[gitpod-db] remove deprected/unused `tokens` column – WEB-400

---

components/public-api/gitpod/experimental/v1/workspaces.proto

gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[public-api] Update getWorkspace proto

---

components/ws-proxy/pkg/proxy/routes.go

instead fallback directly to workspace without additional remote request
Discovered as part of instrumenting http metrics in ws-proxy: https://github.com/gitpod-io/gitpod/pull/17294
There are more 404 errors but they are unfortunately how VS Code bundle source maps for 3rd party extensions. Maybe we can server source maps always from sources. It is out of scope of this PR though.
Fixes #
- Check that VS Code is still working, file explorer, extensions
<ul>
<li><b>🏷️ Name</b> - ak-ws-prox9086f3011a</li>
<li><b>🔗 URL</b> - <a href="https://ak-ws-prox9086f3011a.preview.gitpod-dev.com/workspaces" target="_blank">ak-ws-prox9086f3011a.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - …

[ws-proxy] don't hit blobserve with web sockets

---

components/supervisor/pkg/ports/ports.go

[supervisor] fix port config nil panic
https://cloudlogging.app.goo.gl/XZuETDEqpauQJjwx9
Fixes [internal thread](https://gitpod.slack.com/archives/C01KGM9BH54/p1685978831757399)
This PR contains a test commit, which can help reviewers with testing, but it should be removed before merging
1. start a workspace in preview env
2. run `gp ports test`, workspace should not stop
3. a port should be add in port list
<ul>
<li><b>🏷️ Name</b> - pd-fix-port-panic</li>
<li><b>🔗 URL</b> - <a href="https://pd-fix-port-panic.preview.gitpod-dev.com/workspaces" target="_blank">pd-fix-port-panic.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d0 …

[supervisor] fix port config nil panic

---

components/supervisor/pkg/terminal/terminal.go
components/supervisor/pkg/terminal/terminal_test.go

fix IDE-16
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

try to fix flaky terminal tests by using timeout context to unblock closing of terminals

---

components/gitpod-db/go/dbtest/identity.go
components/gitpod-db/go/dbtest/user.go
components/gitpod-db/go/identity.go
components/gitpod-db/go/user.go
components/gitpod-db/go/user_test.go

Defines a User model in go, such that we can being to issue OIDC sessions from public api
Fixes #
Unit tests
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[db] Add go model for User - WEB-263

---

components/ide/jetbrains/gateway-plugin/build.gradle.kts

merge and check that stable is update in https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions/stable after a while
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

fix publishg of JB GW plugin

---

components/ws-daemon/cmd/run.go
components/ws-daemon/pkg/daemon/config.go
components/ws-daemon/pkg/daemon/daemon.go
dev/preview/workflow/preview/deploy-gitpod.sh
install/installer/pkg/components/ws-daemon/configmap.go
install/installer/pkg/components/ws-daemon/constants.go
install/installer/pkg/components/ws-daemon/daemonset.go
install/installer/pkg/components/ws-daemon/role.go
install/installer/pkg/components/ws-daemon/rolebinding.go
install/installer/pkg/components/ws-manager-mk2/configmap.go
install/installer/pkg/components/ws-manager-mk2/objects.go
install/installer/pkg/components/ws-proxy/role.go
install/installer/pkg/config/v1/experimental/experimental.go

Fixes WKS-209
<ul>
<li><b>🏷️ Name</b> - fo-remove-9db19ffeb4</li>
<li><b>🔗 URL</b> - <a href="https://fo-remove-9db19ffeb4.preview.gitpod-dev.com/workspaces" target="_blank">fo-remove-9db19ffeb4.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[ws-manager-mk2] Remove ws-manager-mk2 from experimental section

---

components/supervisor/pkg/supervisor/supervisor.go
components/supervisor/pkg/terminal/terminal.go

[supervisor] concurrent map writes when terminals close
Fixes [IDE-147](https://linear.app/gitpod/issue/IDE-147)
<ul>
<li><b>🏷️ Name</b> - pd-fix-ide-147</li>
<li><b>🔗 URL</b> - <a href="https://pd-fix-ide-147.preview.gitpod-dev.com/workspaces" target="_blank">pd-fix-ide-147.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[supervisor] concurrent map writes when terminals close

---

components/content-service/pkg/storage/gcloud.go

Looks like the error message has changed, it's now `Your previous request to create the named bucket succeeded and you already own it.`. 
Removing ` this bucket` from the message check, which should now both match this error and the previous message (in case it still gets returned?)
Fixes WKS-202
Tested in an ephemeral cluster, with a hack in ws-daemon to create the bucket twice. Without this PR, that fails, and with the fix in this PR it succeeds (for both content init and backup)
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[content-service] Fix GCP error message check

---

.github/actions/deploy-gitpod/entrypoint.sh
.github/actions/deploy-gitpod/metadata.yml
.github/pull_request_template.md
.github/workflows/build.yml
.werft/jobs/build/deploy-to-preview-environment.ts
.werft/jobs/build/installer/installer.ts
.werft/jobs/build/job-config.ts

Disable ws-manager-mk1 preview environments entirely
Fixes WKS-162
- Create preview environment
- Get kubecontext and check that mk2 has been deployed
<ul>
<li><b>🏷️ Name</b> - fo-mk2-defec8f7f9906</li>
<li><b>🔗 URL</b> - <a href="https://fo-mk2-defec8f7f9906.preview.gitpod-dev.com/workspaces" target="_blank">fo-mk2-defec8f7f9906.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

Enable ws-manager-mk2 in preview environments by default

---

components/gitpod-protocol/src/gitpod-service.ts
components/server/src/auth/rate-limiter.ts
components/server/src/workspace/gitpod-server-impl.ts

Removes a deprecated and unused API method
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] Removed deprecated api.getEnvVars

---

components/dashboard/src/components/toasts/Toast.tsx
components/dashboard/src/usage/download/DownloadUsage.tsx

Following up from https://github.com/gitpod-io/gitpod/pull/17791 (Cc @selfcontained @easyCZ), this will make some minor style changes for the usage export toast on the dark theme. 🌔 
| <img width="592" alt="Frame 1570" src="https://github.com/gitpod-io/gitpod/assets/120486/da1f7957-8725-449e-abe6-72fcc1098d4d"> | <img width="592" alt="Frame 1569" src="https://github.com/gitpod-io/gitpod/assets/120486/d5f50571-4e6e-4e47-83c3-5d47a45040a7"> |
Try exporting usage for an organization and notice the subtle color changes as described above.
<ul>
<li><b>🏷️ Name</b> - gt-update-8fb0b83e75</li>
<li><b>🔗 URL</b> - <a href="https://gt-update-8fb0b83e75.preview.gitpod-dev.com/workspaces" …

Update usage export toast style

---

dev/preview/infrastructure/modules/gce/variables.tf
dev/preview/infrastructure/modules/harvester/variables.tf
dev/preview/infrastructure/variables.tf

The latest packer image via https://github.com/gitpod-io/gitpod-packer-gcp-image/pull/236
Fixes # n/a
Start a workspace in a preview environment.
<ul>
<li><b>🏷️ Name</b> - kylos101-g24ec4b4c6c</li>
<li><b>🔗 URL</b> - <a href="https://kylos101-g24ec4b4c6c.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-g24ec4b4c6c.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[preview] update image for gen99

---

components/ws-manager-mk2/controllers/workspace_controller.go

Also catch and log conflict errors as `info` from `actOnStatus`, as was already being done for updating the workspace status. 
Reduces error logging noise, after this PR we should now catch all conflict errors and log them at info level
Check in a preview env that workspace start/stop works, and any reconciler conflict errors are logged at info level.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[ws-manager-mk2] Log conflict errors as info

---

components/gitpod-db/src/tables.ts
components/server/src/server.ts
install/installer/pkg/components/database/incluster/init/01-create-and-init-sessions-db.sql
install/installer/pkg/components/database/incluster/init/04-drop-sessions-db.sql
install/installer/pkg/components/database/init/files/00-create-and-init-sessions-db.sql
install/installer/pkg/components/database/init/files/02-drop-sessions-db.sql

* Depends on https://github.com/gitpod-io/gitpod/pull/17846
<ul>
<li><b>🏷️ Name</b> - mp-db-drop-sessions</li>
<li><b>🔗 URL</b> - <a href="https://mp-db-drop-sessions.preview.gitpod-dev.com/workspaces" target="_blank">mp-db-drop-sessions.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[db] Drop sessions table & db - WEB-106

---

components/supervisor/pkg/supervisor/supervisor.go
components/supervisor/pkg/supervisor/supervisor_test.go

In order to allow tools to access the browser which rely on it.
Fixes #14046
Test both in VS Code Browser and Desktop for task and regular terminals:
```
yarn global add @teambit/bvm
bvm install
echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc && source ~/.bashrc
PATH=$HOME/bin:$PATH
bit login
```
In all cases it should open the browser.
<ul>
<li><b>🏷️ Name</b> - ak-code-browser</li>
<li><b>🔗 URL</b> - <a href="https://ak-code-browser.preview.gitpod-dev.com/workspaces" target="_blank">ak-code-browser.preview.gitpod-dev.com/workspaces</a>.</li> …

configure BROWSER in supervisor

---

components/dashboard/src/usage/UsageEntry.tsx
components/dashboard/src/usage/UsageView.tsx
components/dashboard/src/usage/download/transform-usage-record.ts

This adjusts a few places on the dashboard UI that are filtering usage entries by `kind`. The API already filters by `kind="workspaceinstance"`, but I think it would be good to be guarding a bit in the client still so we don't accidentally break if we try to render an unexpected entry. These changes optimize where we filter when rendering.
Fixes WEB-438
* Load usage page, create a workspace to have a record. 
* There should be no visual changes with this PR
<ul>
<li><b>🏷️ Name</b> - brad-web-4990499d995</li>
<li><b>🔗 URL</b> - <a href="https://brad-web-4990499d995.preview.gitpod-dev.com/workspaces" target="_blank">brad-web-4990499d995.preview.gitpod-dev.com/workspaces</a>.</li> …

Adjust filtering of usage entries

---

components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
components/dashboard/src/user-settings/Integrations.tsx

This PR adds the option to configure Bitbucket (Cloud) as Git provider under the organization. 
NOTE: This is currently only expected to work in Single-Org mode!
Fixes WEB-454
0. Edit `server-config` configmap and remove the bitbucket integration + restart server pod.
1. Create an Org
2. Under /settings/git, create a new integration with Bitbucket (Cloud)
<ul>
<li><b>🏷️ Name</b> - at-org-git04583328f9</li>
<li><b>🔗 URL</b> - <a href="https://at-org-git04583328f9.preview.gitpod-dev.com/workspaces" target="_blank">at-org-git04583328f9.preview.gitpod-dev.com/workspaces</a>.</li> …

Add Bitbucket to Git Providers under Orgs – WEB-454

---

components/server/src/auth/verification-service.ts
components/server/src/workspace/gitpod-server-impl.ts

This adds three new analytics events for the phone number verification flow:
* `phone_verification_sent` : `{ properties: { channel: string, requestedChannel: string }
* (channel could vary if we request voice in a country w/ only sms enabled)
* `phone_verification_completed` : `{ properties: { channel: string }`
* `phone_verification_failed` : `{ properties: { channel: string }`
| `phone_verification_sent` | `phone_verification_completed` | `phone_verification_failed` |
|--------|--------|--------|
| <img width="422" alt="image" src="https://github.com/gitpod-io/gitpod/assets/367275/cc6ab4be-cb24-40a0-85c6-81ce3b86fa94"> | <img width="397" alt="image" src="https://github.com/gitpod-io/gitpod/assets/367275/e0d709d9-67d9-4fd5-ab61-a2c993e9b907"> | <img width="412" alt="image" …

Add phone verification analytics events

---

components/dashboard/src/login/SSOLoginForm.tsx

If not authenticated, the login component is rendered no any location. Given that, the second path segment should only be considered if the browser's location is /login/slug. Otherwise, if any other string is read as second path segment, it uses it as Org's slug and fails to find the SSO config.
Fixes WEB-458
* setup sso
* use /settings/git as location when not authenticated
* `git` should not be used as slug to do the SSO signin
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

Fix /login/slug handling – WEB-458

---

components/dashboard/src/user-settings/Account.tsx
components/gitpod-protocol/src/protocol.ts

As a follow-up to WEB-437, this PR would move the selection of the email for SSO account to the `User.getPrimaryEmail`. By doing so we can expect the email be rendered consistently throughout the app.  
Related WEB-437
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

User.getPrimaryEmail to return email of SSO identity – WEB-437

---

dev/preview/workflow/preview/deploy-gitpod.sh

Enables network limiting in preview environments
Fixes WKS-69
- SSH into node
- Find workspacekit process and enter the network namespace with nsenter
- Use `nft list ruleset` to list networking rules
<ul>
<li><b>🏷️ Name</b> - fo-previewa1988b53bd</li>
<li><b>🔗 URL</b> - <a href="https://fo-previewa1988b53bd.preview.gitpod-dev.com/workspaces" target="_blank">fo-previewa1988b53bd.preview.gitpod-dev.com/workspaces</a>.</li>
</ul> …

[preview] Enable network limiting

---

WORKSPACE.yaml
install/installer/pkg/components/workspace/ide/constants.go

Update code to `1.79.0`
<ul>
</ul>
```release-note
NONE
```

Update VS Code Browser to `1.79.0`

---

components/gitpod-protocol/src/gitpod-service.ts
components/server/src/auth/rate-limiter.ts
components/server/src/auth/resource-access.spec.ts
components/server/src/workspace/env-var-service.spec.ts
components/server/src/workspace/gitpod-server-impl.ts

Improves tests around EnvVars
Related: WEB-353
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] Add tests for resource-access and env-var-service

---

components/dashboard/src/data/workspaces/delete-inactive-workspaces-mutation.ts
components/dashboard/src/data/workspaces/delete-workspace-mutation.ts
components/dashboard/src/data/workspaces/stop-workspace-mutation.ts
components/dashboard/src/start/StartWorkspace.tsx

Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-dashboa62efb578df</li>
<li><b>🔗 URL</b> - <a href="https://mp-dashboa62efb578df.preview.gitpod-dev.com/workspaces" target="_blank">mp-dashboa62efb578df.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[dashboard] Always use Public API for workspace stop & delete

---

components/server/src/user/user-controller.ts
components/server/src/websocket/websocket-connection-manager.ts
components/server/src/workspace/gitpod-server-impl.ts

To ensure we do not have stale information stored on the Websocket User object
Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-server-723b761599</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-723b761599.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-723b761599.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

[server] Store only User ID on WS connection instance - WEB-460

---

components/ws-proxy/pkg/proxy/infoprovider.go
components/ws-proxy/pkg/sshproxy/server.go

Check workspace phase in ssh-gateway before connect to workspace
Fixes IDE-109
1. start a workspace using this branch
2. start a workspace using this preview env
3. upload your ssh public key, this step can make ssh connection url stable, otherwise you need get ownerToken everytime
4. in preview env workspace, do `dd if=/dev/random of=test.img bs=1M count=5000` it will created a large file in workspace folder, and run `gp stop` stop the workspace
5. during stopping, you can use ssh command trying to connect to workspace, it should failed
6. run `./dev/preview/portforward-monitoring-satellite.sh` in step 1 workspace, and open prometheus UI, search for `gitpod_ws_proxy_ssh_attempt_total` you should see there is a new error `WS_NOT_RUNNING`
7. repeat this test in preview env workspace …

Check workspace phase in ssh-gateway before connect to workspace

---

.vscode/launch.json
components/server/debug.sh
components/server/deploy.sh
components/server/package.json

Allows to debug the server pod in preview environments
Fixes #
1) Start a workspace on this PR
2) cd components/server
3) ./debug.sh
4) Launch "Attach to Node (gitpod)" in VS Code
<ul>
<li><b>🏷️ Name</b> - se-debug-server</li>
<li><b>🔗 URL</b> - <a href="https://se-debug-server.preview.gitpod-dev.com/workspaces" target="_blank">se-debug-server.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
Run …

[server] allow debugging

---

components/gitpod-db/src/typeorm/user-db-impl.ts
components/server/src/workspace/gitpod-server-impl.ts

Encapsulates the DBUser object graph within user-db-impl
Fixes #
<ul>
<li><b>🏷️ Name</b> - se-user-object</li>
<li><b>🔗 URL</b> - <a href="https://se-user-object.preview.gitpod-dev.com/workspaces" target="_blank">se-user-object.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[gitpod-db] don't leak DBUser

---

components/server/src/workspace/workspace-starter.ts
components/ws-manager-bridge/src/bridge.ts
components/ws-manager-bridge/src/workspace-instance-controller.ts

In order to avoid relying on DB in dedicated for general analytics and investigating timeouts:
- align with DB timestamps
- add info about stopping time, timeout and conditions to stopped event
fix IDE-133
- Start and stop workspace.
- Check events in segment source.
<ul>
<li><b>🏷️ Name</b> - ak-wse-enrich</li>
<li><b>🔗 URL</b> - <a href="https://ak-wse-enrich.preview.gitpod-dev.com/workspaces" target="_blank">ak-wse-enrich.preview.gitpod-dev.com/workspaces</a>.</li> …

enrich workspace events

---

components/gitpod-db/src/typeorm/entity/db-gitpod-token.ts
components/gitpod-db/src/typeorm/user-db-impl.ts
components/gitpod-db/src/user-db.spec.db.ts
components/gitpod-db/src/user-db.ts
components/gitpod-protocol/src/protocol.ts
components/server/src/auth/resource-access.ts
components/server/src/user/user-controller.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/workspace-starter.ts

The relation would pull non-fully initialized user objects into the system. We should rather not use relations but keys and explicitly fetch the user when needed.
Fixes #
<ul>
<li><b>🏷️ Name</b> - se-remove-relation</li>
<li><b>🔗 URL</b> - <a href="https://se-remove-relation.preview.gitpod-dev.com/workspaces" target="_blank">se-remove-relation.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
Run …

[server] remove user relation from gitpod_token

---

components/supervisor/BUILD.yaml
components/supervisor/browser.sh
components/supervisor/leeway.Dockerfile
components/supervisor/pkg/supervisor/supervisor.go
components/supervisor/pkg/supervisor/supervisor_test.go

Tools like `npm` expect the `$BROWSER` env var to correspond to an executable. Similar to VSCode's `BROWSER=/ide/bin/helpers/browser.sh`
Fixes https://github.com/gitpod-io/gitpod/issues/17913
- Open https://github.com/johnston9/shot-caller in Gitpod
- Run `npm start`
<ul>
<li><b>🏷️ Name</b> - axonasif-ue2f5466fab</li>
<li><b>🔗 URL</b> - <a href="https://axonasif-ue2f5466fab.preview.gitpod-dev.com/workspaces" target="_blank">axonasif-ue2f5466fab.preview.gitpod-dev.com/workspaces</a>.</li> …

Use a script for BROWSER variable

---

components/gitpod-db/src/container-module.ts
components/gitpod-db/src/data-cache.ts
components/gitpod-db/src/test-container.ts
components/gitpod-db/src/typeorm/user-db-impl.ts
components/server/package.json
components/server/src/auth/login-completion-handler.ts
components/server/src/billing/billing-mode.spec.db.ts
components/server/src/jobs/org-only-migration-job.spec.db.ts
components/server/src/main.ts
components/server/src/prometheus-metrics.ts
components/server/src/redis/data-cache.spec.ts
components/server/src/redis/data-cache.ts
components/server/src/test/authentication-github.spec.ts
components/server/src/user/user-service.spec.db.ts
components/ws-manager-bridge/ee/src/index.ts
components/ws-manager-bridge/src/index.ts
gitpod-ws.code-workspace
yarn.lock

Introduces a CachingService that is used to cache user objects retrieved by its id (happens on most requests).
The primary interface is 
```typescript
/**
* A cache that can be used to cache expensive operations, such as retrieving data from the database.
*/
export interface DataCache {
/**
* Retrieves the value for the given key from the cache. If the value is not in the cache, the provider is called and the result is stored in the cache.
* @param key the key to retrieve the value for. Should be segmented using `:`. For example: `user:123`
* @param provider the provider to call if the value is not in the cache
*/
get<T>(key: string, provider: () => Promise<T | undefined>): Promise<T | undefined>;
/**
* @param keyPattern the key pattern to invalidate. The `*` denotes a wildcard segment. …
```

[gitpod-db] cache user object

---

.github/workflows/workspace-integration-tests.yml

Remove setup of gcloud for workspace integration tests and use gcloud that's already installed in the dev image used by the jobs.
Should fix flakes where the job fails due to `google-github-actions/setup-gcloud failed with: EACCES: permission denied, mkdir '/__t/gcloud'`
Relates to WKS-228
Example run: https://github.com/gitpod-io/gitpod/actions/runs/5254377210
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

Remove setup-gcloud from workspace integration tests workflow

---

components/scrubber/scrubber.go
components/scrubber/scrubber_test.go

it is an extract from https://github.com/gitpod-io/gitpod/pull/17781 to unblock https://github.com/gitpod-io/gitpod-dedicated/pull/1332
- better JSON handling
- removing unnecessary double traversing
- sub property name matching to cover different permutations, i.e. wsContextURL, contextURL, contextUrl, worksapceContextUrl, etc.
- handling of https://github.com/gitpod-io/security/issues/64 for JSON and structs
Fixes #
- Review the code, tests should pass.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
<summary>Preview …

[scrubber] various fixes

---

components/registry-facade/pkg/registry/layersource.go
components/registry-facade/pkg/registry/layersource_test.go
components/registry-facade/pkg/registry/registry.go

To always use the latest (updated) image pull credentials
Relates to WKS-239
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[registry-facade] Use resolverProvider for static layers

---

components/dashboard/src/components/DropDown2.tsx
components/dashboard/src/hooks/use-dirty-state.ts
components/dashboard/src/workspaces/CreateWorkspacePage.tsx

On the create workspace page we have a few scenarios that auto-update the editor or ws class. Sometimes this can override a user's manual selection. In those cases, we don't want to update those values if the user has explicitly changed it already.
I accomplished this by creating a new `useDirtyState()` hook that behaves similar to `useState()`:
```ts
const [value, setValue, isDirty] = useDirtyState("initial value");
// isDirty will now be true
setValue(newValue);
// isDirty won't change based on this call
setValue(newValue, false);
```
It returns a third parameter indicating if the value is "dirty", meaning the value has been changed by the user. `setValue` can also be called with an optional 2nd argument to bypass tracking the dirty state (useful when we want to update the value behind …

Don't change editor/ws class values if user has modified them

---

operations/observability/mixins/IDE/rules/vscode.yaml
operations/observability/mixins/meta/rules/content-service.yaml

Some alert rule groups have duplicate metadata names.
To migrate our alerts to Dedicated, it will be easier to manage these as discrete namespaces.
Related SID-373
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[obs] setup better names for alert rules

---

operations/observability/mixins/workspace/rules/central/workspacefailure-SLO.yaml
operations/observability/mixins/workspace/rules/central/workspaces.yaml
operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
operations/observability/mixins/workspace/rules/satellite/ws-daemon.yaml

This includes old alerts, old recording rules, what appear to be SLO alert rules that appear incomplete, and fixing a bug with BackupFailureBecauseOfGitpodWsDaemonCrash.
Also, flip a couple image builder alerts back to warning to avoid false positives.
Related SID-373
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[obs] remove ws-manager (mk1) alert references

---

operations/observability/mixins/workspace/rules/central/workspaces.yaml
operations/observability/mixins/workspace/rules/central/ws-daemon.yaml
operations/observability/mixins/workspace/rules/central/ws-manager.yaml
operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
operations/observability/mixins/workspace/rules/satellite/ws-daemon.yaml

1. metadata.name (namespace) cannot be duplicate, renamed some rules.
2. added decorator labels so that the alerts get picked up by the sync process.
Related SID-373
You can see the alerts here: https://gitpoddedicatedprod.grafana.net/alerting/list
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details> …

[obs] Fix workspace alerts to work in Grafana cloud

---

components/gitpod-protocol/package.json
components/gitpod-protocol/src/protocol.ts
components/gitpod-protocol/src/user-env-var.spec.ts
components/server/src/auth/resource-access.ts
components/server/src/workspace/env-var-service.spec.ts

This PR allows to specify environment variable patterns for subgroups in GitLab. This is a long-standing issue that we always avoided to fix, but is now requested/assumed to be working by multiple customers.
We had multiple discussions in the past about deprecating this feature in the first place. However never did so, because it's a very convenient feature, that even if we had better secret support, adds value for users.
For examples of what's possible see the tests [here](https://github.com/gitpod-io/gitpod/pull/17831/files#diff-bec292cdaefd0cda4dcc4402f0b610f28a9a81d5d4a2f90c57e8abb73abcc4a7) and [here](https://github.com/gitpod-io/gitpod/blob/996620b21db10109f15f0598d90f659e9449db53/components/gitpod-protocol/src/user-env-var.spec.ts#L24-L145).
The docs don't need to be changed, but …

Allow user env vars for GitLab subgroups

---

WORKSPACE.yaml
install/installer/pkg/components/workspace/ide/constants.go

Update code to `1.79.2`
<ul>
</ul>

Update VS Code Browser to `1.79.2`

---

components/dashboard/src/user-settings/Account.tsx

Surfaces the user's ID through the Account settings in the Dashboard.
Falls under https://github.com/gitpod-io/gitpod/issues/15654
Open the Dashboard in the preview environment :)
<ul>
<li><b>🏷️ Name</b> - ft-user-idf0721f5345</li>
<li><b>🔗 URL</b> - <a href="https://ft-user-idf0721f5345.preview.gitpod-dev.com/workspaces" target="_blank">ft-user-idf0721f5345.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
Run the build with werft …

Show User ID on Account page

---

.github/workflows/build.yml
.github/workflows/ide-integration-tests.yml
.github/workflows/jetbrains-update-plugin-platform-template.yml
.github/workflows/jetbrains-updates.yml
.github/workflows/preview-env-check-regressions.yml
.github/workflows/workspace-integration-tests.yml
test/README.md
test/pkg/integration/apis.go
test/pkg/integration/setup.go
test/tests/components/ws-manager/protected_secrets_test.go

Clean up ws-manager-mk2 options from github actions workflows and integration tests.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[ws-manager-mk2] Cleanup mk1 from workflow inputs and tests

---

components/server/src/workspace/gitpod-server-impl.ts

Obsolete
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] Remove mayStartWorkspaceOnRepo

---

test/pkg/integration/fuse.go
test/tests/components/ws-daemon/fuse_device_test.go

Add test for fuse device
Fixes WKS-217
```
cd test
go test -v ./... -run TestFuseDevice -kubeconfig /home/gitpod/.kube/config
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[test] Add test for fuse device

---

dev/preview/workflow/preview/deploy-gitpod.sh
test/pkg/integration/integration.go
test/pkg/integration/workspace.go
test/tests/workspace/process_limit_test.go

Add e2e test for max process limit.
It succeeds if either of the following happens:
- `bash: fork: retry: Resource temporarily unavailable` gets logged
- Or the workspace exits with a failure (due to supervisor crashing due to process limit being reached. See WKS-249)
Fixes WKS-222
```
cd test
go test -v ./... -run TestProcessLimit -kubeconfig=/home/gitpod/.kube/config
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[test] Add test for process limit

---

components/dashboard/src/components/AuthorizeGit.tsx

Avoid label truncation on the integration buttons.
See [relevant discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1687166969222969) (internal). Cc @easyCZ 
Fixes WEB-485
<ul>
<li><b>🏷️ Name</b> - gt-fix-prob8eea78954</li>
<li><b>🔗 URL</b> - <a href="https://gt-fix-prob8eea78954.preview.gitpod-dev.com/workspaces" target="_blank">gt-fix-prob8eea78954.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
Run the build with werft …

Avoid label truncation on the integration buttons

---

test/README.md
test/pkg/integration/setup.go
test/tests/workspace/k3s_test.go

* Speed up test setup (4.5s -> 1s), makes it faster to iterate on them.
* Remove the need to specify `-kubeconfig=/home/gitpod/.kube/config` when running the tests using `go test`
* Update k3s test to fail early and log the failure when k3s fails to start in the workspace
* Skip the k3s test, as it's not supported in workspaces
Relates to WKS-153
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[test] Speed up setup, debug and disable k3s

---

components/gitpod-protocol/src/gitpod-service.ts
components/server/src/auth/rate-limiter.ts
components/server/src/workspace/gitpod-server-impl.ts

Obsolete
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] Remove hasPermission rpc

---

components/gitpod-protocol/go/gitpod-service.go
components/gitpod-protocol/go/mock.go

forgot to remove in previous PR https://github.com/gitpod-io/gitpod/pull/17981/files
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] Remove hasPermission from go API client

---

.github/workflows/workspace-integration-tests.yml
test/run.sh

Include number of skipped/failed tests in slack message:
```
23/36 tests passed
```
to
```
23 tests passed, 7 tests failed, 6 tests skipped
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[test] Update slack msg to include nr skipped

---

operations/observability/mixins/workspace/rules/satellite/workspaces.yaml

Decrease the percentage of regular not active workspace that we get notified earlier. At the same time ensure that we do not get paged if we only have a low number of workspaces.
Fixes WKS-261
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[workspace] Update regular not active alert

---

components/gitpod-protocol/go/gitpod-service.go
components/gitpod-protocol/go/mock.go
components/gitpod-protocol/src/gitpod-service.ts
components/server/src/auth/rate-limiter.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/workspace-starter.ts
test/tests/components/content-service/content-service_test.go

Looks entirely unused (at least from the `server` side)
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Remove getContentBlob Upload/Download URL

---

components/dashboard/src/user-settings/Account.tsx

Minor tooltip change for copying the user ID.
Follow-up from https://github.com/gitpod-io/gitpod/pull/17956. Cc @filiptronicek @loujaybee 
Go to `/user/account` and try to copy the new user ID field. The tooltip should use a new label.
<ul>
<li><b>🏷️ Name</b> - gt-rename-e12d262cb2</li>
<li><b>🔗 URL</b> - <a href="https://gt-rename-e12d262cb2.preview.gitpod-dev.com/workspaces" target="_blank">gt-rename-e12d262cb2.preview.gitpod-dev.com/workspaces</a>.</li>
</ul> …

Rename copy user ID tooltip

---

test/pkg/integration/workspace.go
test/tests/components/ws-manager/content_test.go
test/tests/components/ws-manager/prebuild_test.go

Fixes flakiness in the prebuild e2e tests, where the prebuild was getting to a `stopped` phase too quickly before we were waiting for the workspace to stop.
Solved by adding a new `WaitForWorkspaceOpt` parameter that waits for the workspace to stop after launching it, so we always observe the last workspace (stopped) status even when the prebuild exits immediately.
This also lets us speed up the prebuild tests by removing the 10s wait for some prebuild tasks.
Relates to WKS-153 and WKS-227
```
cd test
go test -v ./tests/components/ws-manager/...
```
I've ran this a number of times without flakes, where previously it was commonly failing
gitpod:summary
<details>
</details>
<details> …

[test] Fix flakes and speed up prebuild tests

---

components/gitpod-db/src/team-db.ts
components/gitpod-db/src/typeorm/team-db-impl.ts

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[db] Make Team DB transactional

---

components/gitpod-db/src/typeorm/project-db-impl.ts
components/gitpod-db/src/typeorm/team-db-impl.ts
components/gitpod-db/src/typeorm/transactional-db-impl.ts
components/gitpod-db/src/typeorm/user-db-impl.ts
components/gitpod-db/src/typeorm/workspace-db-impl.ts

Some minor cleanups in the db-impls.
- remove unnecessary undefined symbol
- made members private where there very unnecessarily protected
- removed unused code
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[db] some cleanups for db impls

---

operations/observability/mixins/workspace/dashboards/components/ws-daemon.json
operations/observability/mixins/workspace/dashboards/components/ws-manager-mk2.json

Add panels for longest running reconciliation to the ws-manager-mk2 and ws-daemon dashboards.
Lets us observe when a reconciliation gets stuck or is running longer than expected.
Fixes WKS-263
See linear issue for screenshots
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Add longest running reconcile to dashboards

---

components/ws-daemon/cmd/run.go
components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go
components/ws-daemon/pkg/cgroup/plugin_proc_limit_v2.go
components/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go
components/ws-daemon/pkg/cgroup/plugin_psi.go
components/ws-daemon/pkg/container/containerd.go
components/ws-daemon/pkg/content/hooks.go
components/ws-daemon/pkg/controller/workspace_controller.go
components/ws-daemon/pkg/controller/workspace_operations.go
components/ws-daemon/pkg/internal/session/workspace.go
components/ws-daemon/pkg/iws/iws.go
components/ws-daemon/pkg/netlimit/netlimit.go
components/ws-manager-api/go/crd/v1/workspace_types.go

Add OWI to ws-daemon logs that didn't have it yet, to help debug specific workspace logs.
Open a workspace in a preview env, check the logs for OWI info.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[ws-daemon] Add OWI to logs

---

components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
components/dashboard/src/user-settings/Integrations.test.tsx
components/dashboard/src/user-settings/Integrations.tsx
components/server/src/auth/auth-provider-service.ts
components/server/src/auth/authenticator.ts
components/server/src/auth/generic-auth-provider.ts
components/server/src/express.ts

Removing the `host_like` segment form the callback URL of git providers.
e.g. instead of `/auth/github.com/callback` it should work with `/auth/callback` once this is landed.
Here you can see, the legacy URL still works nicely:
Fixes WEB-398
* test with github.com (legacy callback URL) directly through the sign-up
* [join](https://at-callback-url.preview.gitpod-dev.com/orgs/join?inviteId=ec3a1f1a-5e92-4d88-91f4-3546190e4818) my org to test with gitlab.com (simplified callback URL) which is configured under the Org
<ul>
<li><b>🏷️ Name</b> - at-callback-url</li>
<li><b>🔗 URL</b> - <a href="https://at-callback-url.preview.gitpod-dev.com/workspaces" target="_blank">at-callback-url.preview.gitpod-dev.com/workspaces</a>.</li> …

Remove hostname from callback URL – WEB-398

---

components/proxy/conf/Caddyfile
install/installer/pkg/common/common.go
install/installer/pkg/common/constants.go
install/installer/pkg/components/ide-service/constants.go
install/installer/pkg/components/openvsx-proxy/constants.go
install/installer/pkg/components/proxy/constants.go
install/installer/pkg/components/proxy/deployment.go
install/installer/pkg/components/proxy/networkpolicy.go
install/installer/pkg/components/proxy/service.go

fix IDE-185
- Check logs of all dependent components that they can resolve feature flag.
- Try to change some feature flags and see whether changes are picked up.
<ul>
<li><b>🏷️ Name</b> - ak-ide-185</li>
<li><b>🔗 URL</b> - <a href="https://ak-ide-185.preview.gitpod-dev.com/workspaces" target="_blank">ak-ide-185.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[configcat] use internal route

---

dev/preview/workflow/preview/deploy-gitpod.sh

E2e tests that start workspaces through server have been failing recently on 
```
code 451 message: Increase usage limit and try again.
```
See e.g. https://github.com/gitpod-io/gitpod/actions/runs/5346803374/jobs/9694625865#step:8:1037
Setting a default non-zero spending limit for teams fixes this (tested locally).
Related WKS-153
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid options …

[test] Fix tests, set team spending limit

---

components/gitpod-db/go/cost_center_test.go
components/gitpod-db/go/dbtest/cost_center.go
components/gitpod-db/go/dbtest/stripe_customer.go
components/gitpod-db/go/dbtest/usage.go
components/gitpod-db/go/dbtest/workspace_instance.go
components/gitpod-db/go/stripe_customer_test.go
components/gitpod-db/go/usage_test.go
components/gitpod-db/go/workspace_instance.go
components/gitpod-db/go/workspace_instance_test.go
components/usage/pkg/apiv1/billing.go
components/usage/pkg/apiv1/billing_test.go
components/usage/pkg/apiv1/usage_test.go
components/usage/pkg/stripe/stripe_test.go

Removes user attribution from the usage components
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[usage] cleanup after org-only mig

---

components/dashboard/src/components/DropDown2.tsx

Fix the location of the search input in the dropdown2 component, on the new workspace page.
Thanks @aledbf for re-surfacing this UX issue. 🙇 
1. Go to `/new` and click on the **repository** or the **editor** dropdown.
2. Scroll down and notice how the search input is always fixed at the top.
<ul>
<li><b>🏷️ Name</b> - gt-keep-se9c004c10e4</li>
<li><b>🔗 URL</b> - <a href="https://gt-keep-se9c004c10e4.preview.gitpod-dev.com/workspaces" target="_blank">gt-keep-se9c004c10e4.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to …

Keep search input visible when scrolling on the repository and editor dropdown

---

components/gitpod-db/src/typeorm/team-db-impl.spec.db.ts
components/gitpod-db/src/typeorm/team-db-impl.ts
components/gitpod-db/src/typeorm/transactional-db-impl.ts

The implementation of a db method should be able to use transactions
when it makes sense without assumptions of whether the code
is called from a running transaction or not.
TypeORM actually does support this in a newer version. But they essentially [do the same](https://github.com/typeorm/typeorm/pull/8541/files#diff-78ff8320cc81d7f789d6ee8fa43c23fb755e01dc3d7f13d5e5fda1b85e6e5e56) as what this PR does.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[db] allow nesting transactions

---

.github/workflows/preview-env-gc.yml

When one of the delete jobs fails they cancel the other ongoing deletion jobs in the matrix, setting `fail-fast` to false prevents that. Also limiting the concurrency to 1, as some are failing to acquire the TF lock (presumably cause multiple jobs in the matrix are trying that at the same time)
Related: https://github.com/gitpod-io/gitpod/pull/18025#issuecomment-1602765618
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[preview] Disable fail-fast and limit parallel jobs to 1

---

components/supervisor/pkg/supervisor/supervisor.go

Fix properly close ssh tunnel websocket connection 
<ul>
<li><b>🏷️ Name</b> - jp-vulnerable-macaw</li>
<li><b>🔗 URL</b> - <a href="https://jp-vulnerable-macaw.preview.gitpod-dev.com/workspaces" target="_blank">jp-vulnerable-macaw.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

Fix supervisor ssh tunnel close stale connection

---

components/usage/pkg/scheduler/scheduler.go

Makes [this log message](https://console.cloud.google.com/logs/query;cursorTimestamp=2023-06-26T07:05:24.002063499Z;pinnedLogId=2023-06-26T07:05:24.002063499Z%2Fzprf54b5vovdbce3;query=resource.labels.container_name%3D%22usage%22%0A%22reset_usage%22%0Atimestamp%3D%222023-06-26T07:05:24.002063499Z%22%0AinsertId%3D%22zprf54b5vovdbce3%22?project=gitpod-191109) become info severity
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[usage] reduce log noise

---

components/gitpod-protocol/go/gitpod-service.go
components/public-api-server/pkg/apiv1/identityprovider.go

Add organization id in claims
the claim name is `org_id`
if user is Org-owned user `org_id` is organization id. 
if user is normal user, then `org_id` workspace's organization id.
Fixes IDE-103
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Add organization id in claims

---

components/server/src/authorization/checks.ts
components/server/src/authorization/definitions.ts
components/server/src/workspace/gitpod-server-impl.ts
install/installer/pkg/components/spicedb/data/schema.yaml

Fixes WEB-529
Fixes WEB-530
Fixes WEB-531
Fixes WEB-532
<ul>
<li><b>🏷️ Name</b> - gpl-org-authprovider</li>
<li><b>🔗 URL</b> - <a href="https://gpl-org-authprovider.preview.gitpod-dev.com/workspaces" target="_blank">gpl-org-authprovider.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details>
</details>
<details> …

[server] Guard org authProvider-related API calls centralizedPermissions

---

components/gitpod-db/go/workspace_instance.go
components/gitpod-db/go/workspace_instance_test.go

The query to find running instances does a scan on all instances since August 2022. [The query gets slower and slower](https://console.cloud.google.com/sql/instances/gitpod-prod-us-west1/insights;database=gitpod;duration=PT1H;query_hash=2850358609397758774;sort_by=TOTAL_EXEC_TIME?project=gitpod-191109) and it is unnecessary to recheck such old instances, as instances can run at most 36 hours and it is not the responsibility of this control loop to handle when this is not the case.
Fixes WEB-571
gitpod:summary
<details>
</details>
<details>
</details>
<details> …

[usage] less expensive reconcilation

---

components/gitpod-db/src/typeorm/code-sync-resource-db.ts

Delete code sync resources directly, as we don't need to the two-phase deletion anymore. Also the [deletion query is slow](https://console.cloud.google.com/sql/instances/gitpod-prod-us-west1/insights;database=gitpod;duration=PT1H;query_hash=3431532609399736197;sort_by=TOTAL_EXEC_TIME?project=gitpod-191109).
Tests are [here](https://github.com/gitpod-io/gitpod/blob/58108e58defdc9233e63f38f0057640a33df6957/components/gitpod-db/src/typeorm/code-sync-resource-db.spec.db.ts#L242).
Fixes WEB-570
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details> …

[db] directly delete code sync resources

---

components/server/src/workspace/gitpod-server-impl.ts

This reverts commit 01117568d7f49971572cf588ea8f8b78035090ff.
Incident: https://stspg.io/lzd5wlknj7yc
Fixes #
<ul>
<li><b>🏷️ Name</b> - gpl-revert-getteams</li>
<li><b>🔗 URL</b> - <a href="https://gpl-revert-getteams.preview.gitpod-dev.com/workspaces" target="_blank">gpl-revert-getteams.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details>
</details>
<details> …

Revert "[perms] Implement getTeams WEB-501 (#18039)"

---

components/dashboard/src/menu/OrganizationSelector.tsx
components/dashboard/src/usage/UsageSummary.tsx

Fixes a regression from https://github.com/gitpod-io/gitpod/pull/17621.
Fixes WEB-421
Here's what I did, see the screenshot below for verification:
- setup Dedicated
- note that you don't see /billing links in:
- the usage view
- the org menu
<ul>
<li><b>🏷️ Name</b> - gpl-org-bm</li>
<li><b>🔗 URL</b> - <a href="https://gpl-org-bm.preview.gitpod-dev.com/workspaces" target="_blank">gpl-org-bm.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[dashboard] Only show /billing links for UBP

---

components/dashboard/src/app/AppLoading.tsx
components/dashboard/tailwind.config.js

The loading screen is currently white for 5 sec and than immediately jumps to logo with text.
This change proposes to smoothen the experience and make it bit more gradual.
- After 1 sec the logo softly fades in
- After 6 sec the text apears
- After 20 sec we tell the user that something is off.
Here's a [loom](https://www.loom.com/share/49e9c244e6064841985e01fadaea8dfc?sid=31061572-5955-47f8-a401-07d4559cdc79).
Fixes #
<ul>
<li><b>🏷️ Name</b> - se-loading</li>
<li><b>🔗 URL</b> - <a href="https://se-loading.preview.gitpod-dev.com/workspaces" target="_blank">se-loading.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce …

[dashboard] smoother loading screen

---

dev/preview/workflow/preview/deploy-gitpod.sh
install/installer/pkg/components/database/incluster/helm.go
install/installer/pkg/config/v1/config.go
install/installer/third_party/charts/mysql/values.yaml

Enables the use of MySql 8.0 for **all preview environments**.
Part of the effort to identify problems in migration from MySQL 5.7 to 8.0
Fixes #
- start a workspace and see that it works as usual.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[installer] Optional flag to use mysql 8.0

---

dev/preview/workflow/preview/deploy-gitpod.sh

https://linear.app/gitpod/issue/WEB-568#comment-35a1ee42
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[mysql] Disable v8 in preview

---

.github/workflows/workspace-integration-tests.yml

Find and use the latest successful build on main by looking back 10 builds, instead of trying/waiting on the most recent build when no specific installer version is specified.
Makes it easier to iterate on the tests by removing the wait on the latest build to finish, and also prevents a main build flake from failing the periodic e2e test runs. Now it will fall back on the most recent green build.
Testing here: https://github.com/gitpod-io/gitpod/actions/runs/5388611363, and ran the `gh run list ...` commands locally to check
gitpod:summary
<details>
</details>
<details>
</details>
<details> …

[test] Use latest successful main build

---

components/server/src/workspace/gitpod-server-impl.ts

Adds permission checks for getTeams call
Fixes WEB-501
1. Start with feature flag disabled
* Create an org
2. Enable feature flag
* Create another org
* You should now see both Orgs
3. Disable feature flag
* You should see both orgs
<ul>
<li><b>🏷️ Name</b> - se-perms-list-teams</li>
<li><b>🔗 URL</b> - <a href="https://se-perms-list-teams.preview.gitpod-dev.com/workspaces" target="_blank">se-perms-list-teams.preview.gitpod-dev.com/workspaces</a>.</li>
</ul>
<details> …

[perms] Implement getTeams WEB-501

---

components/server/src/authorization/authorizer.ts

This is a pre-PR for implementation of `leaveTeam`. 
This change composes individual relationship updates - allows us to reuse the relationships in bigger (public signature) methods to be used outside of the authorizer.
As it stands, the change is semantically equivalent to the current implementation.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[perms] Compose org updates

---

.github/actions/delete-preview/Dockerfile
.github/actions/deploy-gitpod/Dockerfile
.github/actions/deploy-monitoring-satellite/Dockerfile
.github/actions/preview-create/Dockerfile
.github/workflows/build.yml
.github/workflows/ide-integration-tests.yml
.github/workflows/preview-env-check-regressions.yml
.github/workflows/preview-env-gc.yml
.github/workflows/workspace-integration-tests.yml
.gitpod.yml
.werft/aks-installer-tests.yaml
.werft/build.yaml
.werft/cleanup-installer-tests.yaml
.werft/debug.yaml
.werft/eks-installer-tests.yaml
.werft/gke-installer-tests.yaml
.werft/k3s-installer-tests.yaml
.werft/platform-trigger-werft-cleanup.yaml
dev/image/Dockerfile

Updates the dev image to include `zed` and `spicedb`CLI
Fixes WEB-478
start a workspace on this PR and verify the 
- `zed` command is available
- `spicedb` command is available
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

update dev image

---

.github/workflows/workspace-integration-tests.yml
dev/preview/infrastructure/modules/gce/vm.tf
dev/preview/previewctl/cmd/report.go
test/pkg/integration/apis.go
test/pkg/integration/integration.go
test/pkg/integration/setup.go
test/pkg/integration/workspace.go
test/run.sh
test/tests/workspace/contexts_test.go
test/tests/workspace/git_hooks_test.go
test/tests/workspace/gp_top_test.go

* Increase node disk size to 512Gi, as node is running out of ephemeral storage quite often.
* Upload test results as artefact, allows inspecting the results of a GHA run in more details (e.g. time it takes to run each test)
* Print the preview env's installer version to the GHA summary
* Increase DB port-forward to 60 minutes. Fixes flake where the DB connection got closed due to the port-forward timing out
* Only build each instrumentation agent once (and reuse for following tests)
* Add additional logging. E.g. preview env health when workspace start times out
* Fix nil-pointer
* Increase some timeouts that are commonly reached
Related to WKS-153
gitpod:summary
<details>
</details>
<details> …

[test] E2e test fixes and improvements

---

test/pkg/integration/apis.go
test/pkg/integration/setup.go
test/pkg/integration/workspace.go
test/tests/components/ws-daemon/cpu_burst_test.go

Logs the preview env status when an integration test fails, to help debug the failure.
Also add a small sanity check to assert that the cpu limit config is non-zero (not sure that would've been caught by the test otherwise). 
Fixes WKS-219
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[test] Log preview env state on failure, check cpu limit config is set

---

components/gitpod-protocol/src/util/logging.ts
components/gitpod-protocol/src/util/scrubbing-config.ts
components/gitpod-protocol/src/util/scrubbing.spec.ts
components/gitpod-protocol/src/util/scrubbing.ts

This PR ports scrubbing from golang to TS and integrate in logging. During logging we only scrub primitive properties of log context and payload. All nested properties are scrubbed with `redacted:nested` to avoid incurring performance costs.
Fixes SID-284
Fixes SID-288
- Tests should be green.
- Start/stop a workspace, review logs of server and bridge.
<ul>
<li><b>🏷️ Name</b> - ak-scrub-ts</li>
<li><b>🔗 URL</b> - <a href="https://ak-scrub-ts.preview.gitpod-dev.com/workspaces" target="_blank">ak-scrub-ts.preview.gitpod-dev.com/workspaces</a>.</li> …

[ts] initial scrubbing integrated in logging

---

operations/observability/mixins/cross-teams/dashboards/gitpod-overview.json

This extends the Gitpod / Overview dashboard so that we can use it for Gitpod Dedicated as well
1. It adds a new `cell` variable - for Gitpod SaaS the dropdown will be empty and won't affect the results
2. Adds a few panels related to showing what version of Gitpod is running (currently and historically). This is nice in SaaS but pretty crucial in Gitpod Dedicated as installations can lack behind and can differ between cells.
See loom in [How to test](#how-to-test) below
Part of SID-374
Tested in both Gitpod SaaS Grafana and Gitpod Dedicated Grafana
https://www.loom.com/share/9ad19e22fca14dac87aea17a4278200c
gitpod:summary
<details>
</details>
<details>
</details> …

Add cell variable and panels which show the Gitpod version

---

components/ide-service/pkg/server/server.go
components/ide-service/pkg/server/testdata/resolve_ws_config_prebuild_code.golden
components/ide-service/pkg/server/testdata/resolve_ws_config_prebuild_intellij.golden
components/ide-service/pkg/server/testdata/resolve_ws_config_prebuild_multiple_ide.golden
components/ide/jetbrains/image/create-supervisor-config.js
components/ide/jetbrains/image/leeway.Dockerfile
components/ide/jetbrains/image/supervisor-ide-config_clion-latest.json
components/ide/jetbrains/image/supervisor-ide-config_clion.json
components/ide/jetbrains/image/supervisor-ide-config_goland-latest.json
components/ide/jetbrains/image/supervisor-ide-config_goland.json
components/ide/jetbrains/image/supervisor-ide-config_intellij-latest.json
components/ide/jetbrains/image/supervisor-ide-config_intellij.json
components/ide/jetbrains/image/supervisor-ide-config_phpstorm-latest.json
components/ide/jetbrains/image/supervisor-ide-config_phpstorm.json
components/ide/jetbrains/image/supervisor-ide-config_pycharm-latest.json
components/ide/jetbrains/image/supervisor-ide-config_pycharm.json
components/ide/jetbrains/image/supervisor-ide-config_rider-latest.json
components/ide/jetbrains/image/supervisor-ide-config_rider.json
components/ide/jetbrains/image/supervisor-ide-config_rubymine-latest.json
components/ide/jetbrains/image/supervisor-ide-config_rubymine.json
components/ide/jetbrains/image/supervisor-ide-config_webstorm-latest.json
components/ide/jetbrains/image/supervisor-ide-config_webstorm.json
components/ide/jetbrains/launcher/main.go
components/ide/jetbrains/launcher/main_test.go
components/supervisor/cmd/prepare-ide-prebuild.go
components/supervisor/pkg/supervisor/config.go
components/supervisor/pkg/supervisor/supervisor.go
components/supervisor/pkg/supervisor/tasks.go
components/supervisor/supervisor-config.json

This PR extract JB warmup task configuration from server to JB integration itself to enable usage of `gp validate` to investigate warmup issues in the regular workspace. Composition of IDE prebuild tasks are done by supervisor, i.e. it can detect multiple desktop IDEs now. 
A prerequisite to IDE-182
- Create a project for https://github.com/akosyakov/spring-petclinic
- And run a prebuild
- It does not need to succeed, but just check that warmup of IntelliJ was triggered from logs
- Or test that starting IntelliJ from https://ak-validat3f63c69ca3.preview.gitpod-dev.com/projects/spring-petclinic/766afbb5-ec90-46e9-906b-d56fa6b7d9c9 works both for stable and latest.
<ul>
<li><b>🏷️ Name</b> - ak-validat3f63c69ca3</li> …

validate jb warmup

---

components/gitpod-db/src/typeorm/team-db-impl.spec.db.ts
components/gitpod-db/src/typeorm/team-db-impl.ts
components/gitpod-protocol/src/messaging/error.ts
components/gitpod-protocol/src/messaging/proxy-factory.ts
components/gitpod-protocol/src/util/logging.ts
components/gitpod-protocol/src/util/tracing.ts
components/server/src/auth/verification-service.ts
components/server/src/dev/authenticator-dev.ts
components/server/src/iam/iam-oidc-create-session-payload.ts
components/server/src/iam/iam-session-app.ts
components/server/src/linkedin-service.ts
components/server/src/prebuilds/github-app.ts
components/server/src/prebuilds/prebuild-manager.ts
components/server/src/prebuilds/start-prebuild-context-parser.ts
components/server/src/projects/projects-service.ts
components/server/src/user/stripe-service.ts
components/server/src/user/user-controller.ts
components/server/src/user/user-service.ts
components/server/src/websocket/websocket-connection-manager.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/workspace-factory.ts

We want to go away from json-rpc so it doesn't make sense to reuse its ResponseError in our code base.
This PR introduces a compatible Error and replaces the usages.
Fixes #
<ul>
<li><b>🏷️ Name</b> - se-application-error</li>
<li><b>🔗 URL</b> - <a href="https://se-application-error.preview.gitpod-dev.com/workspaces" target="_blank">se-application-error.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - se-application-error-gha.12347</li>
</ul>
<details> …

[server] Use our own error type

---

components/ide/jetbrains/image/leeway.Dockerfile

I removed proper permissions by incident.
The build should pass.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

jb: fix permissions

---

components/gitpod-cli/cmd/idp.go
components/gitpod-cli/go.mod

Make the command appear and do not hide it.
Fixes IDE-190
```
gp --help
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Show `gp idp` in the CLI help menu

---

.github/workflows/build.yml

increases heap size in build, because some tasks fail with out of memory ocasionally.
e.g. https://github.com/gitpod-io/gitpod/actions/runs/5421053110/jobs/9855995616?pr=18099
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[build] increase js heap size

---

components/server/package.json
components/server/src/auth/auth-provider-service.ts
yarn.lock

Getting rid of unnecessary dependency.
Fixes #
* use preview env
* try creating a new Git Integration and see if the reachability checks still works
<ul>
<li><b>🏷️ Name</b> - at-rm-is-reachable</li>
<li><b>🔗 URL</b> - <a href="https://at-rm-is-reachable.preview.gitpod-dev.com/workspaces" target="_blank">at-rm-is-reachable.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - at-rm-is-reachable-gha.12380</li>
</ul>
<details>
Run the …

[server] replace is-reachable with fetch

---

components/ide/jetbrains/launcher/main.go

There are many of such errors: https://console.cloud.google.com/logs/query;query=%22failed%20to%20suppress%203rd-party%20plugins%20consent%22;timeRange=P7D;cursorTimestamp=2023-06-27T08:16:04.383502217Z?project=workspace-clusters
but it is expected condition, so we just suppress it
Fixes #
The build should be green.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

jb: don't log if alien_plugins.txt file already does not exist

---

test/tests/workspace/cgroup_v2_test.go

Fail cgroupv2 test if v2 is not enabled
Fixes WKS-270
```
cd test
go test -v ./... -run TestCgroupV2
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[test] Assert cgroup v2 is enabled

---

components/blobserve/go.mod
components/content-service/go.mod
components/ee/agent-smith/go.mod
components/ide-service/go.mod
components/ide/code-desktop/status/go.mod
components/ide/code/codehelper/go.mod
components/ide/jetbrains/launcher/go.mod
components/image-builder-bob/go.mod
components/image-builder-mk3/go.mod
components/installation-telemetry/go.mod
components/node-labeler/go.mod
components/openvsx-proxy/go.mod
components/public-api-server/go.mod
components/registry-facade/go.mod
components/service-waiter/go.mod
components/supervisor/go.mod
components/usage/go.mod
components/workspace-rollout-job/go.mod
components/workspacekit/go.mod
components/ws-daemon/go.mod
components/ws-daemon/nsinsider/go.mod
components/ws-manager-mk2/go.mod
components/ws-proxy/go.mod
dev/gp-gcloud/go.mod
dev/gpctl/go.mod
dev/loadgen/go.mod
test/go.mod

```
../../../common-go/log/log.go:150:17: undefined: scrubber.TrustedValue
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Fix build error undefined: scrubber.TrustedValue

---

components/ws-manager-mk2/leeway.Dockerfile

Fixes WKS-269
- Workspaces should open
<ul>
<li><b>🏷️ Name</b> - aledbf-mk2-wolfi</li>
<li><b>🔗 URL</b> - <a href="https://aledbf-mk2-wolfi.preview.gitpod-dev.com/workspaces" target="_blank">aledbf-mk2-wolfi.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - aledbf-mk2-wolfi-gha.12467</li>
</ul>
<details>
</details>
<details> …

Migrate ws-manager-mk2 to wolfi

---

.github/workflows/workspace-integration-tests.yml
dev/preview/infrastructure/modules/gce/variables.tf
dev/preview/infrastructure/modules/gce/vm.tf
test/README.md
test/pkg/integration/setup.go
test/pkg/integration/workspace.go
test/run.sh
test/tests/components/content-service/content-service_test.go
test/tests/components/image-builder/builder_test.go
test/tests/components/ws-daemon/storage_test.go
test/tests/components/ws-manager/prebuild_test.go

* Run e2e tests in parallel
* Add 2 local SSDs to the preview VM if `with-large-vm` is enabled, which together with [this change](https://github.com/gitpod-io/gitpod-packer-gcp-image/pull/240) removes node disk pressure issues, which were causing the tests to fail
* Some other fixes + improvements, see self review
Relates to WKS-228 WKS-153 WKS-227
Create preview env with large vm:
```
TF_VAR_with_large_vm=true leeway run dev:preview
```
Run tests:
```
cd test
./run.sh -s workspace
```
See also two successful GHA runs:
* https://github.com/gitpod-io/gitpod/actions/runs/5442586097
* https://github.com/gitpod-io/gitpod/actions/runs/5443292092
gitpod:summary
<details>
</details>
<details> …

[test] Fix disk pressure, run in parallel

---

test/go.mod
test/go.sum
test/pkg/agent/daemon/api/api.go
test/pkg/agent/daemon/main.go
test/pkg/integration/integration.go
test/tests/components/ws-daemon/network_limiting_test.go

Add test for network limiting.
Works by:
* installing an agent in ws-daemon, with a new `GetNftRulesets` RPC
* this agent then finds the workspace container's `pid`
* then the `ring0` child process of the container process
* enters the network namespace of the ring0 process
* checks `nft list ruleset` and verifies rate limiting is present
Took a while to get this working 😄 
Fixes WKS-223
```
cd test
go test -v ./... -run TestNetworkLimiting
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[test] Add network limiting e2e test

---

components/gitpod-cli/cmd/validate.go
components/ide/code/codehelper/go.mod
components/supervisor/pkg/supervisor/config.go

Otherwise there is a race during gp validate. It does not affect the real prebuild since we don't run IDEs there at all.
Prerequisite to IDE-182
- Open this PR on gitpod.io with stable IntelliJ.
- checkout test repo: `cd /workspace && git clone https://github.com/gitpod-samples/spring-petclinic && cd spring-petclinic && git fetch && git checkout ak/test_warmup`
- validate prebuild without IDE: `cd /workspace/gitpod/components/supervisor && ./validate.sh --workspace-folder /workspace/spring-petclinic --prebuild --headless` - it will run headless prebuild, you won't be able to access IDE, but you will see tasks output in the terminal as well as initellij prebuild task will be triggered
- validate prebuild with IDE: `cd /workspace/gitpod/components/supervisor && ./validate.sh …

validate: run IDE prebuild only in headless workspace

---

.github/workflows/ide-integration-tests.yml
.github/workflows/preview-env-check-regressions.yml
.github/workflows/workspace-integration-tests.yml

Fixes preview env creation sometimes getting stopped for scheduled workflows on main, due to a main build cancelling the preview env creation because of matching concurrency groups (`main-infrastructure`).
See e.g. https://github.com/gitpod-io/gitpod/actions/runs/5443913650/attempts/1
The scheduled workflows should actually use the preview env's name as the concurrency group instead of the branch ref, that will prevent them from getting stopped by a main build too
Relates to WKS-228
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[preview] Update infra concurrency groups to match preview name

---

components/gitpod-protocol/src/experiments/configcat-server.ts
components/server/package.json
components/server/src/authorization/definitions.ts
components/server/src/authorization/spicedb-authorizer.ts
components/server/src/container-module.ts
components/server/src/orgs/organization-service.spec.db.ts
components/server/src/orgs/organization-service.ts
components/server/src/workspace/gitpod-server-impl.ts
install/installer/pkg/components/spicedb/data/schema.yaml

Adds an orgaization service and corresponding test, which includes testing spicedb permissions.
Fixes #
- review unit tests
- play around with the preview env, e.g. join my org https://se-add-org-service.preview.gitpod-dev.com/login/sven's-org?org=551f2a25-602a-42f4-b5cf-da8008ed0f49
<ul>
<li><b>🏷️ Name</b> - se-add-org-service</li>
<li><b>🔗 URL</b> - <a href="https://se-add-org-service.preview.gitpod-dev.com/workspaces" target="_blank">se-add-org-service.preview.gitpod-dev.com/workspaces</a>.</li> …

[server] add organization service

---

.github/workflows/code-nightly.yml

Base Insiders off of the 1.80 release branch for VS Code Browser, like every month...

Point code nightly to release branch

---

components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt

Preview on [this PR's dev JB plugin](https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions/dev/355030)
|:--------:|:--------:|
|<video src="https://github.com/gitpod-io/gitpod/assets/55068936/8de1238a-669f-46a1-bf84-3da88b8885aa"/>|<video src="https://github.com/gitpod-io/gitpod/assets/55068936/aae4a59a-acc7-495b-8033-373c91061f54"/>|
Fixes [IDE-189 : error message in loading dialog of JB GW should no be editable](https://linear.app/gitpod/issue/IDE-189/error-message-in-loading-dialog-of-jb-gw-should-no-be-editable)
- Install [JB Plugin](https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions/dev/355030)
- Start any workspace in JB IDEs
- Try to type in the Start Workspace window tray.
No …

[JetBrains-plugin] Error message shouldn't be editable on Workspace Phase tray window

---

components/ide-metrics/pkg/server/server.go
install/installer/pkg/components/ide-metrics/configmap.go

They are too noisy right now. We still report observability. Later we are going to reconsider to report only from our components to make it more useful.
Fixes #
The build should pass.
<ul>
<li><b>🏷️ Name</b> - ak-no-browser-errors</li>
<li><b>🔗 URL</b> - <a href="https://ak-no-browser-errors.preview.gitpod-dev.com/workspaces" target="_blank">ak-no-browser-errors.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - ak-no_browser_errors-gha.12507</li>
</ul> …

[metrics] exclude VS Code Browser from error reporting

---

.werft/package.json
components/content-service-api/typescript/package.json
components/gitpod-protocol/package.json
components/ide-metrics-api/typescript-grpc/package.json
components/image-builder-api/typescript/package.json
components/supervisor-api/typescript-grpc/package.json
components/ws-daemon-api/typescript/package.json
components/ws-manager-api/typescript/package.json
components/ws-manager-bridge-api/typescript/package.json
yarn.lock

Avoid more outdated dependencies.
Fixes WEB-575
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Updated outdated dependencies to avoid CVEs

---

components/gitpod-protocol/src/headless-workspace-log.ts
components/server/src/workspace/messagebus-integration.ts
components/server/src/workspace/workspace-starter.ts
components/ws-manager-bridge/src/messagebus-integration.ts
components/ws-manager-bridge/src/prebuild-updater.ts

Cleanup after we talked in sync, as preparation for the redis work.
I don't think it's worth replacing the UPDATEABLE_QUEUE, yet, as we use the GitHub API to update, not only the DB, and we call it from server and bridge ([source](https://github.com/gitpod-io/gitpod/blob/638ec536e0d273686f485ac305c643363ea61e79/components/server/src/prebuilds/prebuilt-status-maintainer.ts#L164-L176)).
Let's make this a separate queue for, the shape is an ID plus status ([source](https://github.com/gitpod-io/gitpod/blob/f1d2a38dc7e8bf2042692e4ff440091879a62d4d/components/gitpod-protocol/src/headless-workspace-log.ts#L27-L30)).
Fixes #
gitpod:summary
<details>
</details>
<details> …

[server, bridge] Small messagebus cleanup

---

.github/workflows/build.yml

gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Remove cancel-in-progress concurrency setting

---

components/gitpod-protocol/src/index.ts
components/gitpod-protocol/src/redis.ts
components/ws-manager-bridge/package.json
components/ws-manager-bridge/src/bridge.ts
components/ws-manager-bridge/src/redis/publisher.spec.ts
components/ws-manager-bridge/src/redis/publisher.ts
components/ws-manager-bridge/src/workspace-instance-controller.ts

Publishes the instance ID and workspace ID to redis. Currently there are no consumers, but we can observe metrics to verify the publishing works.
Fixes #
<ul>
<li><b>🏷️ Name</b> - mp-ws-man-d3e5aaf871</li>
<li><b>🔗 URL</b> - <a href="https://mp-ws-man-d3e5aaf871.preview.gitpod-dev.com/workspaces" target="_blank">mp-ws-man-d3e5aaf871.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - mp-ws-man-redis-publish-instance-update-gha.12681</li>
</ul>
<details> …

[ws-man-bridge] Publish ws-instance-update - WEB-592

---

.github/actions/delete-preview/Dockerfile
.github/actions/deploy-gitpod/Dockerfile
.github/actions/deploy-monitoring-satellite/Dockerfile
.github/actions/preview-create/Dockerfile
.github/workflows/build.yml
.github/workflows/ide-integration-tests.yml
.github/workflows/preview-env-check-regressions.yml
.github/workflows/preview-env-gc.yml
.github/workflows/workspace-integration-tests.yml
.gitpod.yml
.werft/aks-installer-tests.yaml
.werft/build.yaml
.werft/cleanup-installer-tests.yaml
.werft/debug.yaml
.werft/eks-installer-tests.yaml
.werft/gke-installer-tests.yaml
.werft/k3s-installer-tests.yaml
.werft/platform-trigger-werft-cleanup.yaml
dev/image/Dockerfile

Bumps leeway to v0.7.5 which adds support for the segment reporter.
Run a leeway build with `LEEWAY_SEGMENT_KEY` set to a segment write key and observe the events.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Bump leeway to v0.7.5

---

components/gitpod-protocol/src/gitpod-service.ts
components/server/src/billing/entitlement-service-ubp.ts
components/server/src/billing/entitlement-service.ts
components/server/src/workspace/workspace-starter.ts

Set maximum workspace lifetime. Followup to https://github.com/gitpod-io/gitpod/pull/17767
Fixes WKS-234
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[server] Set maximum workspace lifetime

---

components/common-go/cgroups/cgroup.go
components/common-go/cgroups/v2/io.go
dev/preview/workflow/preview/deploy-gitpod.sh
test/pkg/agent/daemon/api/api.go
test/pkg/agent/daemon/main.go
test/run.sh
test/tests/components/ws-daemon/cpu_burst_test.go
test/tests/components/ws-daemon/io_limiting_test.go
test/tests/workspace/docker_test.go
test/tests/workspace/process_limit_test.go

Add IO limit e2e test
Fixes WKS-220
Run integration test
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[test] IO Limits

---

install/installer/pkg/components/redis/networkpolicy.go

Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[installer] Allow ws-man-bridge to connect to redis WEB-601

---

.github/workflows/build.yml
.github/workflows/code-nightly.yml
.github/workflows/jetbrains-auto-update-template.yml
.github/workflows/jetbrains-integration-test.yml

Use the LEEWAY_SEGMENT_KEY to observe builds
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Use leeway segment key secret

---

components/ws-daemon/nsinsider/main.go
components/ws-daemon/pkg/iws/iws.go

Log network link state in case we cannot set up the workspace network
Fixes WKS-279
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Log network link state

---

.github/workflows/workspace-integration-tests.yml
components/ws-daemon/pkg/content/initializer.go

Fix footer link to workflow run
Add OWI to content init failure log in ws-daemon, as well as the size of the error message (see https://linear.app/gitpod/issue/WKS-243#comment-9d30d9d8, suspicion that the error message can be too big to get logged)
Works here: https://gitpod.slack.com/archives/C03E52788SU/p1688482928525039
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[test] Fix slack footer and improve ws-daemon log

---

components/ws-manager-bridge/leeway.Dockerfile
components/ws-manager-bridge/package.json

Fixes WEB-608
<ul>
<li><b>🏷️ Name</b> - se-bridge-fix</li>
<li><b>🔗 URL</b> - <a href="https://se-bridge-fix.preview.gitpod-dev.com/workspaces" target="_blank">se-bridge-fix.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - </li>
</ul>
<details>
</details>
<details>
</details>
<details>
Add desired …

[ws-manager-bridge] fix path to entry point

---

components/gitpod-protocol/go/gitpod-service.go
components/public-api-server/pkg/apiv1/workspace.go
components/public-api-server/pkg/apiv1/workspace_test.go

Update getWorkspace api response with new `recent_folders` attribute
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

[public-api] Update getWorkspace api response implementation

---

components/ws-daemon/nsinsider/main.go

Log ip address for default gateway
Fixes WKS-279
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

Log ip address for default gateway

---

components/dashboard/src/data/featureflag-query.ts
components/dashboard/src/usage/UsageView.tsx

Removes the `usageDownload` flag that was wrapping the usage `Export as CSV` button now that it's fully enabled.
Fixes WEB-439
Verify the Usage page has the Export as CSV button
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold

removing usageDownload flag

---

components/dashboard/src/components/Button.tsx
components/dashboard/src/components/InputWithCopy.tsx
components/dashboard/src/components/Modal.tsx
components/dashboard/src/components/Tooltip.tsx
components/dashboard/src/components/forms/CheckboxInputField.tsx
components/dashboard/src/components/forms/SelectInputField.tsx
components/dashboard/src/components/forms/TextInputField.tsx
components/dashboard/src/images/check-currentColor.svg
components/dashboard/src/index.css
components/dashboard/src/teams/git-integrations/GitIntegrationModal.tsx
components/dashboard/src/user-settings/Account.tsx

This fixes a bug where clicking the copy button on the InputWithCopy component would submit a form. The main reason was due to the `<button>` not having a `type` explicitly set, which would result in a form submitting if it was inside of one. To fix that I've:
* Explicitly set `button.type=button`
* Added a `preventDefault()` on the click handler as an extra measure to prevent side-effects beyond copying to the clipboard.
I've also updated a few things in the InputWithCopy component to re-use existing hooks/components. A byproduct of that was updating a couple related components.
* New optional `spacing='compact|default'` prop to allow tighter padding when needed.
* Added `type='transparent'` instead of the `button.reset` global css class name
* Added optional …

Prevent Input w/ Copy button from submitting forms

---

.github/workflows/lacework-inline-scanner.yml
scripts/lw-scan-images.sh

This PR adds:
- `scripts/lw-scan-images.sh`: Scan all images for a given Gitpod version using the Lacework inline scanner [[1](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwisjKra4fn_AhVw0QIHHUt0DckQFnoECBUQAQ&url=https%3A%2F%2Fdocs.lacework.net%2Fonboarding%2Fintegrate-inline-scanner&usg=AOvVaw0Rvx-joprdhfQMkyiK-ln9&opi=89978449)], and send the result to lacework so we can use it in policies/alerts 
- a new workflow `Lacework Inline Scanner` which gets trigger on each successful main build and uses that script
First I tried to hook this up to the build directly, but it slowed it down too much (~10mins).
- figure out how to access docker.io from GitHub actions [[2](https://github.com/gitpod-io/gitpod/blob/2882ae5e97f8d1ee389ce64df0e965eb867058e6/.g …

[github] Basic lacework integration

---

.github/workflows/lacework-inline-scanner.yml

Hopefully last follow-up for https://github.com/gitpod-io/gitpod/pull/18178 :crossed_fingers: 
Fixes #
Working example: https://github.com/gitpod-io/gitpod/actions/runs/5476187478/jobs/9973362193
Check results at: https://gitpod.lacework.net/ui?redirectUrl=/investigation/container/VulnerabilityDashboard and search for "All images", "Build ID = main-gha.12830"
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

Fix lacework integration workflow

---

WORKSPACE.yaml
install/installer/pkg/components/workspace/ide/constants.go

Update code to `1.80.0`
Related https://github.com/gitpod-io/gitpod/issues/18132
<ul>
<li><b>🏷️ Name</b> - hw-code-180</li>
<li><b>🔗 URL</b> - <a href="https://hw-code-180.preview.gitpod-dev.com/workspaces" target="_blank">hw-code-180.preview.gitpod-dev.com/workspaces</a>.</li> …

Update VS Code Browser to 1.80.0

---

operations/observability/mixins/workspace/rules/central/ws-manager.yaml

When it triggers now, it's generally due to WKS-210, and is not valuable to  gitpod.io or Dedicated in it's current form.
In other words, if ws-manager-mk2 restarts, it recovers and no action is needed. If it's unable to start, we won't be able to createWorkspace (and server should emit a signal).
Fixes WKS-288
n/a
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …

[obs] reduce noise related to GitpodWsManagerCrashLoopingMk2
