gitpod-io/gitpod

security.txt

Adds a security.txt file in accordance with https://securitytxt.org resp. https://tools.ietf.org/html/draft-foudil-securitytxt-05

Added security.txt file

---

chart/BUILD.yaml
components/theia/packages/gitpod-extension/src/browser/github/fork/github-forks-loader.spec.ts
components/theia/packages/gitpod-extension/src/browser/github/github-model/github-rest-api.spec.ts
components/theia/packages/gitpod-extension/src/browser/gitpod-git-token-validator.spec.ts

[build] Fixes the build up until the deployment

---

.werft/build.js
.werft/values.dev.yaml

- inject `authProviders`
- (disable HTTPS again, needs more debugging...)

[preview envs] AuthProviders, disable HTTPS

---

components/proxy/Dockerfile
install/aws-terraform/main.tf
install/aws-terraform/variables.tf
install/gcp-terraform/main.tf
install/gcp-terraform/modules/helm/main.tf
install/gcp-terraform/modules/helm/variables.tf
install/gcp-terraform/variables.tf
install/installer/cmd/aws.go
install/installer/cmd/gcp.go

Certbot support was in the helm chart but ignored by the installer

installer certbot support

---

install/aws-full-terraform/BUILD.yaml
install/aws-full-terraform/README.md
install/aws-full-terraform/data.tf
install/aws-full-terraform/main.auto.tfvars
install/aws-full-terraform/modules/gitpod/main.tf
install/aws-full-terraform/modules/gitpod/variables.tf
install/aws-full-terraform/modules/https/variables.tf
install/aws-full-terraform/modules/mysql/main.tf
install/aws-full-terraform/modules/mysql/variables.tf
install/aws-full-terraform/modules/registry/variables.tf
install/aws-full-terraform/variables.tf
install/aws-terraform/modules/gitpod/main.tf
install/aws-terraform/variables.tf
install/gcp-full-terraform/modules/gitpod/main.tf
install/gcp-full-terraform/modules/https/main.tf
install/gcp-full-terraform/modules/kubernetes/variables.tf
install/gcp-full-terraform/modules/mysql_helm/main.tf
install/gcp-full-terraform/modules/mysql_helm/variables.tf
install/gcp-full-terraform/modules/network/main.tf
install/gcp-full-terraform/modules/registry/main.tf
install/gcp-terraform/BUILD.yaml
install/gcp-terraform/main.tf
install/gcp-terraform/modules/helm/main.tf
install/gcp-terraform/modules/helm/variables.tf
install/gcp-terraform/variables.tf

Let's make sure the scripts don't break :)

Add CI checks for Terraform

---

install/aws-terraform/variables.tf

Correct me if I'm wrong on any of these

Add descriptions to the variables in the minimal script

---

.gitpod.yml

[dev setup] add privileged flag

---

components/dashboard/src/components/tos/terms-of-service.tsx
components/server/ee/src/user/user-service.ts
components/server/src/auth/auth-error-handler.ts
components/server/src/auth/errors.ts
components/server/src/auth/generic-auth-provider.ts
components/server/src/express-util.ts
components/server/src/user/user-controller.ts
components/server/src/user/user-service.ts

On each Gitpod installation, the first user must accept ToS.

[login] first user must accept ToS

---

components/theia/app/leeway.Dockerfile

Removes copying node twice for Theia.

[theia] get rid of duplicate node

---

components/ws-manager-node/pkg/hostsgov/tcpproxy.go

Fixes the timeout bug on image pulls we see on `staging`/`devstaging` with `registry-facade` enabled. The issue is within the library we use to forward TCP traffic from the host (in `ws-manager-node`) to `registry-facade`: [It does not behave as it should](https://github.com/inetaf/tcpproxy/issues/28).

[ws-manager-node] tcpproxy: fix DialProxy.DialTimeout and 0 target case

---

install/aws-full-terraform/modules/gitpod/main.tf
install/aws-full-terraform/versions.tf
install/aws-terraform/modules/gitpod/main.tf

Use `dependency_update` as https://github.com/hashicorp/terraform-provider-helm/issues/459 has been fixed

Use `dependency_update` again

---

components/dashboard/src/components/start-workspace.tsx
components/gitpod-protocol/src/gitpod-service.ts
components/server/ee/src/workspace/workspace-health-monitoring.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/workspace-starter.ts

Allow user to use default image on failure

---

components/dashboard/src/components/tos/terms-of-service.tsx

Changed some labels to be more specific

Change the messaging on the terms of service page

---

components/dashboard/public/index.html

update meta description.

---

components/supervisor-api/generate.sh
components/supervisor-api/typescript-grpc/BUILD.yaml
components/supervisor-api/typescript-grpc/build.sh
components/supervisor-api/typescript-grpc/package.json
components/supervisor-api/typescript-grpcweb/BUILD.yaml
components/supervisor-api/typescript-grpcweb/build.sh
components/supervisor-api/typescript-grpcweb/package.json
components/supervisor-api/typescript-rest/build.sh
components/supervisor-api/typescript-rest/package.json

Unbreaks master in a workspace.
- Open a workspace and wait for the yarn build to finish cleanly

[supervisor-api] Fix yarn workspace build for supervisor API packages

---

components/supervisor/frontend/BUILD.yaml
components/supervisor/frontend/package.json
components/supervisor/frontend/src/index.ts
components/theia/packages/gitpod-extension/src/browser/activity/gitpod-keep-alive-polling.ts
yarn.lock

- check that a ws connection to the server sends heartbeat while you are moving mouse or press keys

move heartbeat to supervisor frontend

---

.gitpod.yml

check that prebuild does not fail with yarn network timeout

increase yarn network timeout to fix prebuilds

---

components/ws-proxy/pkg/proxy/workspaceinfo.go

[ws-proxy] Don't fail on workspace log output

---

install/docker/examples/gitpod-gitlab/docker-compose.yaml
install/docker/examples/gitpod-gitlab/gitlab/BUILD.yaml
install/docker/examples/gitpod-gitlab/gitlab/Dockerfile
install/docker/examples/gitpod-gitlab/gitlab/entrypoint.sh
install/docker/examples/gitpod-gitlab/gitlab/gitlab-helm-installer.yaml
install/docker/examples/gitpod-gitlab/gitlab/persistent-volumes.yaml
install/docker/examples/gitpod-gitlab/values/auth-providers.yaml
install/docker/gitpod-image/BUILD.yaml
install/docker/gitpod-image/Dockerfile
install/docker/gitpod-image/entrypoint.sh
install/docker/gitpod-image/gitpod-helm-installer.yaml
install/docker/gitpod-image/persistent-volumes.yaml
install/docker/gitpod-image/values.yaml

- Add volumes to store state
- Fix docker-compose DNS
/werft with-installer

Update Gitpod k3s

---

chart/templates/_default.yaml

Annotations to services can be made using the variable `serviceAnnotations` in components.
```
components:
serviceAnnotations: {}
```

[helm] added support of annotations for services

---

components/supervisor/pkg/supervisor/tasks.go

nothing to test really, just a precaution

[supervisor] don't fail the process on tasks' errors

---

components/supervisor/pkg/supervisor/supervisor.go

To better support the IO usecase and enable CLI re-use.

[supervisor] Replace supervisor opts with global values

---

components/dashboard/public/schemas/gitpod-schema.json
components/server/src/workspace/workspace-starter.ts
components/ws-daemon/BUILD.yaml
components/ws-manager/go.sum

This PR permits the `user_namespace` feature flag without the `privileged-ws` permission.

[user-namespaces] No more privileged-ws permission

---

scripts/setup-google-adc.sh

This will update the GCP setup script instructions to match the current settings and repository URL.

Update GCP setup script instructions

---

components/supervisor/cmd/rings.go
components/supervisor/pkg/supervisor/supervisor.go

This PR improves the shutdown behaviour of supervisor, working towards fixing #2148.
1. we introduce fixed time budgets for all operations that have to happen within the `terminationGracePeriod`. E.g. we ensure the IDE terminates within a fixed amount of time after it received `SIGTERM`. If it doesn't, we'll `SIGKILL` it rather than waiting for Kubernetes to SIGKILL supervisor.
2. we properly set `PDEATHSIG` for user-namespaced workspaces: in Linux a process can register to receive a signal when the thread that started that process ends. This is done using the `prctl` syscall with `PR_SET_PDEATHSIG`. It’s this syscall that we rely on for propagating the `SIGKILL` that Kubernetes sends to supervisor (ring0) when the `terminationGracePeriod` is up.
Programs have no means of reacting to …

[supervisor] Ensure timely shutdown

---

components/supervisor/cmd/rings.go

ring1ShutdownTimeout is the time ring1 gets between SIGTERM and SIGKILL.
We do this to ensure we have enough time left for ring0 to clean up prior
to receiving SIGKILL from the kubelet.
This time must give ring1 enough time to shut down (see time budgets in supervisor.go),
and to talk to ws-daemon within the terminationGracePeriod of the workspace pod.

[supervisor] Introduce ring1 shutdown timeout to ensure proper cleanup

---

components/gitpod-db/src/typeorm/migration/1592203031938-Baseline.ts

fix: theia listing grammar

---

chart/templates/server-deployment.yaml
chart/values.yaml

breaks content service
Reverts gitpod-io/gitpod#2190

Revert "Fixes minio configuration to use localized endpoint"

---

components/supervisor/pkg/gitpod/gitpod-config.go
components/supervisor/pkg/ports/exposed-ports.go
components/ws-daemon/seccomp-profile-installer/main.go

This PR makes supervisor not crash when instance updates stop

[supervisor] Don't panic when instance updates stop

---

components/supervisor/pkg/supervisor/supervisor.go

This PR makes supervisor a zombie reaper.
We have loads of processes that produce zombies, e.g. broken language servers.
Once their parent exits, they get reparented to supervisor eventually.
This change makes supervisor reap those child processes properly if need be.
1. Start a workspace
2. Compile this program (with `gcc -o zombie zombie.c`) and run it (e.g. `./zombie`)
```
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
int main () {
pid_t child_pid;
child_pid = fork();
if (child_pid > 0) {
sleep(1);
} else {
exit(0);
}
return 0;
}
```
3. Notice how there's no zombie process in the workspace using `ps guax | grep defunct`
4. Bonus points: do the same thing in a prod or staging workspace, there the zombie remains.

[supervisor] Add zombie reaper for reparented processes

---

components/supervisor/pkg/gitpod/gitpod-service.go

[supervisor] Fix write on closed channel for instance updates

---

components/supervisor/pkg/supervisor/tasks.go

This PR makes the task API non-incremental to avoid race conditions between the original sign up of clients and subsequent updates. It also aligns with the other APIs within Gitpod.

[supervisor] Publish full task updates instead of incremental ones

---

components/ws-manager/pkg/manager/headless.go

This PR attempts to prevent ws-manager from leaking Go routines in the headless listener.
Prior to this change, a leadless listener could be stuck when trying to send to `lastLineReadChan`, if the Go routine that read from this channel had already moved on. Previously we assumed that closing the log stream would also stop the reading Go routine, but missed that we might be hanging on the channel write.
This change introduces a secondary closing mechanism for the listener, where it closes a channel s.t. we can stop writing to `lastLineReadChan` if the `oldLogs` are closed.
fixes #2280

[ws-manager] Close headless listener properly

---

components/dashboard/leeway.Dockerfile

to reduce the number of known vulnerabilities.

[dashboard] Update nginx to stable alpine (1.18.0)

---

components/supervisor/pkg/supervisor/supervisor.go

This PR tones down the process reaper in supervisor.

[supervisor] Tone down process reaper logs

---

components/supervisor/pkg/ports/ports.go
components/supervisor/pkg/ports/ports_test.go
components/supervisor/pkg/supervisor/services.go
components/supervisor/pkg/supervisor/tasks.go

- fix #2290: it make sure that no updates can help between clients receiving an initial status and subscribing
- added unit tests for concurrent subscription of ports (since we had issued there in the past)
- fixed task management that run only returns when all tasks are done, before we will miss some conditions like if a task could not be started at all but the prebuild will look successful
- tests still should pass
- terminals and ports should work

ensure that clients don't miss ports/tasks status updates

---

components/ws-daemon/pkg/content/service.go

This PR avoids a race between "content ready" and supervisor. Before, ws-daemon's content-initializer would place the content ready file, and then ws-daemon would `chown` the workspace content to match the user namespace UID shift.
Now, we run the content initializer with the correct UID already. Because we still give the content-inititalizer `CAP_FCHOWN` that also works with the non-shifted backups we have.
1. Enable Feature Preview in https://cw-fix-userns-content-init.staging.gitpod-dev.com/settings/
2. Start a large workspace, e.g. https://cw-fix-userns-content-init.staging.gitpod-dev.com/#https://github.com/kubernetes/kubernetes
3. Do that so many times that you feel confident :D
4. Stop one of those workspaces and start it again

[ws-daemon] Make content initialiser properly shift UID/GIDs

---

components/gitpod-protocol/data/gitpod-schema.json
components/gitpod-protocol/src/protocol.ts
components/server/src/workspace/workspace-starter.ts

This PR removes the `privileged` workspace config flag.

[workspace] Remove privileged workspace config flag

---

components/ws-proxy/pkg/proxy/pass.go
components/ws-proxy/pkg/proxy/routes.go
components/ws-proxy/pkg/proxy/routes_test.go

Fixes https://github.com/gitpod-io/gitpod/issues/2206.
Test: http://gpl-filter-xframeoptions-wsproxy.staging.gitpod-dev.com/#https://github.com/gitpod-io/django-locallibrary-tutorial
Expectation: see working preview on the side (does not work here: https://gitpod-staging.com/#https://github.com/gitpod-io/django-locallibrary-tutorial)

[ws-proxy] Filter X-Frame-Options

---

chart/templates/ws-daemon-configmap.yaml
components/ws-daemon/pkg/hosts/kubernetes.go

Prior we'd be spamming /etc/hosts and ws-daemon

[registry-facade] Fix fixedIPSource

---

components/ws-manager-api/typescript/src/client-provider.ts

The package/namespace of gRPC has been changed from 'protocol' to 'wsman'. This commit adds the option to configure WorkspaceManager with legacy = true in order to use the old namespace for certain WorkspaceManager instances.
This should probably be reverted as soon as we do not need to talk to legacy WorkspaceManagers anymore.

[wsman] Add support to talk to older WorkspaceManagers

---

components/ws-proxy/pkg/proxy/routes.go

A simple approach to get the broken reload working before the release while keeping the fix for duplicate workspace starts.

[ws-proxy] Wait 3 secs for WS info before redirecting to /start

---

components/common-go/pprof/pprof.go

This PR enables temporary mutex profiling and mutex contention sampling.

[pprof] Fix sampling based profiles

---

components/dashboard/src/components/feature-settings.tsx
components/dashboard/src/components/ide-settings.tsx
components/dashboard/src/components/settings/index.tsx
components/dashboard/src/components/user-settings.tsx

fix #2332: pull user settings state up to avoid race conditions
Change different settings and check that all changes are applied. Also try to start a workspace after switching IDE.
I'm not sure how to test email settings, so reviewing carefully changed code in this area would be good 👀

pull user settings state up

---

components/ee/ws-scheduler/pkg/scheduler/scheduler.go

Fixes #2341.
- verify that regular scheduling works: http://gpl-fix-ws-scheduler-race.staging.gitpod-dev.com/#https://github.com/gitpod-io/django-locallibrary-tutorial
- check the beginning of `ws-scheduler` logs and verify that in the list of messages reading `removed from localBindingCache` pods from other namespaces (especially `kube-system`) are listed as well

[ws-scheduler] List pods from _all_ namespaces when calculating available resources

---

components/docker-up/runc-facade/main.go

fixes https://github.com/gitpod-io/gitpod/issues/2331
1. Enable feature preview in https://csweichel-use-runc-from-path-2331.staging.gitpod-dev.com/settings
2. Open workspace on https://csweichel-use-runc-from-path-2331.staging.gitpod-dev.com/#https://github.com/meysholdt/test/tree/test_wsfull_docker
3. run `sudo rm /usr/sbin/runc && sudo run docker-up`
4. run a Docker container`docker run --rm it alpine:latest`

[runc-facade] Use runc from the path

---

components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/src/auth/resource-access.ts
components/server/src/websocket-connection-manager.ts
components/server/src/workspace/gitpod-server-impl.ts

This PR fixes workspace sharing.
The resource access guard does not care about a workspace being shared.
This change introduces a new resource access guard that takes care of that.

[server] Fix shared workspace access

---

components/server/src/auth/generic-auth-provider.ts

this should fix pushing to bitbucket.

[server/auth] refreshed tokens missing user name

---

components/dashboard/src/components/create/create-workspace.tsx
components/dashboard/src/components/start-workspace.tsx
components/gitpod-db/src/typeorm/migration/1607429613319-TermsAcceptance-lastModified.ts
components/server/src/auth/auth-provider.ts
components/server/src/auth/authenticator.ts
components/server/src/auth/generic-auth-provider.ts
components/server/src/auth/login-completion-handler.ts
components/server/src/terms/tos-flow.ts
components/server/src/user/user-controller.ts

Signed-off-by: Alex Tugarev <alex.tugarev@typefox.io>

[server] fix login

---

components/ws-manager/pkg/manager/testdata/cdwp_ghost.golden

This PR unbreaks the ws-manager tests.

[ws-manager] Fix broken CDWP test case

---

dev/manual-tests/testsuite.yaml

See also [relevant discussion](https://typefox.slack.com/archives/CGVQAPNPL/p1607543123276900) (internal).

Add manual tests for HTML and CSS syntax

---

.werft/build.js

* don't create preview envs for release builds
* always create an installer for release builds.

Release Build Improvements

---

components/ws-daemon/pkg/content/initializer.go
components/ws-daemon/pkg/content/service.go

[ws-daemon] don't fail if prebuilt is not found

---

components/ws-daemon/pkg/content/initializer.go

[ws-daemon] Add nil pointer guard in content initializer for prebuilds

---

.werft/build.yaml

`n2-standard-16` 
Cmp. https://github.com/gitpod-io/gitpod/pull/2540

[werft] Run build on bigger build node

---

components/supervisor/pkg/ports/ports.go

Fixes the flaky tests by preserving insertion order of served ports while filtering duplicates.
- CI should pass.
- Running `cd components/supervisor/pkg/ports && go test -run TestPortsUpdateState -count 100` in the workspace should not fail.

fix flaky port tests

---

install/aws-full-terraform/main.tf
install/aws-terraform/kubernetes.tf
install/installer/leeway.Dockerfile

This PR updated the AWS modules in Terraform to the latest version and resolves the version conflict during installation.

[Terraform,AWS] updated versions

---

install/aws-full-terraform/main.tf
install/aws-full-terraform/versions.tf
install/aws-terraform/kubernetes.tf

`terraform fmt -recursive` has been run to get the formatting right.

[Terraform] fixed formatting in AWS

---

components/server/ee/src/monitoring-endpoint-ee.ts

Fixes #2608 
Changes were made following [Prometheus node.js client library](https://github.com/siimon/prom-client/blob/bec8067e0860b26ba0350608fc331d58ef7bdb4c/example/server.js#L92-L99) example.
Before:
After:

Fix server metrics endpoint

---

components/dashboard/src/components/auth-providers.tsx
components/server/src/auth/auth-provider-service.ts
components/server/src/auth/auth-provider.ts
components/server/src/auth/authenticator.ts
components/server/src/auth/generic-auth-provider.ts
components/server/src/auth/login-completion-handler.ts
components/server/src/user/user-controller.ts

fixes https://github.com/gitpod-io/gitpod/issues/2579
1. do the initial setup
2. verify, there is no second tab opened once you select `Connect`.
it should redirect to the login/terms flow first, and to the dashboard eventually
3. go to /access-control, you should be able to update permissions

Fix for mark as verified in Self Hosted

---

components/dashboard/src/components/auth-providers.tsx

Fixes #2677 .
Test:
- http://gpl-sh-tos-broken.staging.gitpod-dev.com/workspaces/
- follow first-steps

[dashboard] Fix /first-steps

---

components/docker-up/docker-up/main.go

[docker-up] move docker root to /workspace

---

components/server/src/workspace/context-parser.ts

Resolves https://github.com/gitpod-io/gitpod/issues/2606

[server] disallow prefix matching for host names

---

.werft/build.js
chart/values.yaml
docs/self-hosted/install/database.md
docs/self-hosted/install/install-on-aws-script.md
docs/self-hosted/install/install-on-gcp-script.md
install/gcp-terraform/environment/full/main.tf
install/installer/BUILD.yaml

Fixes https://github.com/gitpod-io/gitpod/issues/2697.
Also, bumps (and releases) `0.6.0-beta5`.

SH 0.6.0-beta5: Use correct imagePrefix

---

chart/values.yaml
docs/self-hosted/install/configure-ingress.md
docs/self-hosted/install/install-on-kubernetes.md
docs/self-hosted/install/troubleshooting.md

- Follow the installation instructions, but append an `--version 0.6.0-beta5` for every `upgrade`/`install`.

[docs] Self-hosted: small improvements based on tester feedback

---

components/registry-facade/pkg/registry/registry.go

This PR makes registry-facade respect the `handover.enabled` flag. Prior, it would attempt a handover if a socket was present, which would likely fail because the deployment was not prepared for the handover mechanism.
1. registry-facade no longer crashes in dev-staging

[registry-facade] Only attempt/offer handover when enabled

---

docs/self-hosted/install/install-on-kubernetes.md

This commit polishes the language of our "install on Kubernetes" docs.

Polished language for docs "install on k8s"

---

docs/self-hosted/install/install-on-kubernetes.md

This fixes markdown issues and minor wording.

Minor fixes for self-hosted docs

---

.werft/build.js

and remove the `https` build config. This is In preparation for making registry-facade standard.
Fixes gitpod-io/gitpod#2704

[devstaging] Deploy all preview environments with HTTPS

---

install/aws-full-terraform/versions.tf

Use latest helm provider for hashicorp aws

---

components/dashboard/src/components/footer.tsx

[dashboard] update copyright year

---

components/theia/packages/gitpod-extension/src/browser/setup/setup-manager.ts
components/theia/packages/gitpod-extension/src/browser/setup/setup-view.tsx

Quick fix for gitpod-io/gitpod#3012.

[project setup wizard] Create readme file if missing and fix some bugs

---

.werft/build.js
.werft/build.yaml

fixes #2573 
Produces this slack message if the build fails:

[build] Send slack notification when build fails

---

components/ide/code/leeway.Dockerfile
components/ide/code/startup.sh

- fix #2802: add missing commands to Code
Changes in Code: https://github.com/gitpod-io/vscode/compare/ae8dc44299153ca820ac9e13cc9def5bb6baafd1..gp-code
Open Code and check that all commands except sharing and snapshots are available according to: https://github.com/gitpod-io/gitpod/issues/2802#issuecomment-768931765

add missing commands to Code

---

components/ide/code/leeway.Dockerfile
components/image-builder/go.mod
components/ws-manager/go.sum

- fix #3114: fix user data URI on windows machine
A change in Code: https://github.com/gitpod-io/vscode/commit/791d97eab4a4d591cc12a4784bf263088968c6d3
- Switch to Feature Preview and enable Code
- Start a workspace on windows machine and check that IDE is revealed

[code] fix user data URI on windows machine

---

components/ws-manager/pkg/manager/metrics.go

A gauge vector reporting the fill levels of all subscriber queues for debugging overflowing subscriber queues in prod.
We produce a time series per subscriber, which might lead to high cardinality issues. That said, we should not see all that many subscribers anyways (just ws-proxy and ws-manager-bridge) - and if we do, that's a good indicator something's broken.
Produces
```
gitpod_ws_manager_workspace_subscriber_queue_level{client="k10.60.36.162:58358@1612279793773152852"} 0
gitpod_ws_manager_workspace_subscriber_queue_level{client="k10.60.36.166:50180@1612279814879737788"} 0
gitpod_ws_manager_workspace_subscriber_queue_level{client="k10.60.37.28:44534@1612280198312307240"} 0
```
- `kubectl port-forward ws-manager-... 9500`
- `curl localhost:9500/metrics | grep …

[ws-manager] Provide subscription queue metric

---

components/gitpod-db/src/typeorm/migration/1612448906950-ExampleRepositories.ts
components/gitpod-db/src/typeorm/migration/README.md

We now have better examples in https://www.gitpod.io/#get-started and https://www.gitpod.io/docs/examples/
1. Log in to https://jx-refresh-example-repos.staging.gitpod-dev.com/workspaces/
2. See proposed example repositories

[dashboard] Refresh example repositories featured in empty workspaces list

---

components/server/ee/src/workspace/gitpod-server-impl.ts

This PR introduces basic audit logging for admin API calls.

[admin] Introduce audit logs for admin API calls

---

components/dashboard/ee/src/components/admin/workspace-view.tsx

to something more appriopriate and less brutal.
| before | after |
|---|---|
| ![image](https://user-images.githubusercontent.com/3210701/107184644-43bdc380-69e1-11eb-9503-816a33977b0e.png) | ![image](https://user-images.githubusercontent.com/3210701/107184697-589a5700-69e1-11eb-9565-2976a95d6214.png) |

[admin] Rename stop workspace button

---

install/docker/gitpod-image/entrypoint.sh

When using docker-compose, there is usually a Docker DNS at 127.0.0.11. When using docker run there is usually no such DNS. The entrypoint.sh script fails when the Docker DNS is missing. This PR fixes this.
This also adds some more comments to the entrypoint.sh file.
Fixes gitpod-io/gitpod#3139

[gitpod-k3s] Fix adding iptables rules when there is no Docker DNS

---

components/dashboard/src/components/workspaces.tsx

Progresses https://github.com/gitpod-io/gitpod/issues/2531 but the language chosen does not resolve the following aspect:
> **We want to educate users about using fresh workspaces for new tasks** but also help them understand how to use the product efficiently as well as provide useful product features that allow users to have more control over content and more.
So nit away :)

[dashboard] Improve awareness for automatic workspace deletion due to garbage collection

---

chart/templates/ws-daemon-daemonset.yaml

[helm] Fix invalid procMount type

---

components/dashboard/src/components/workspaces.tsx

Follow up on https://github.com/gitpod-io/gitpod/pull/3158, see https://github.com/gitpod-io/gitpod/pull/3158#issuecomment-780363631.

Update help link in garbage collection alert

---

chart/Chart.yaml

Helm 2 was deprecated last November https://helm.sh/blog/helm-v2-deprecation-timeline/

[helm] Deprecate support for helm2

---

components/ee/ws-scheduler/go.mod
components/ee/ws-scheduler/go.sum
components/ee/ws-scheduler/pkg/scaler/driver.go

Fixes broken ghost deployments.

[ws-scheduler] Normalize workspaceImage ref

---

.werft/values.dev.yaml
chart/values.yaml

Using Always could cause crash loops if there are networking issues reaching the image registry

[helm] Change default image pull policy to IfNotPresent

---

dev/image/Dockerfile

Required for new tests in #3255

[dev-environment]: Add kubebuilder binaries

---

.werft/build.js

🤞🏻 to fix namespace cleanup for preview environments.

Update werft/sweeper after default branch rename

---

dev/image/Dockerfile

required for #3318
cc @csweichel

[dev-image] Update go to 1.16

---

components/ide/code/leeway.Dockerfile

Code needs to create some additional directories on start.
Fixes issues with Java extension.

update code with creating diretories for globalstorage

---

components/gitpod-protocol/src/accounting-protocol.ts
components/gitpod-protocol/src/admin-protocol.ts
components/gitpod-protocol/src/gitpod-service.ts
components/gitpod-protocol/src/messaging/error.ts
components/gitpod-protocol/src/payment-protocol.ts
components/gitpod-protocol/src/team-subscription-protocol.ts
components/server/src/auth/rate-limiter.ts
components/server/src/workspace/gitpod-server-impl.ts

[protocol] fold in com aspects

---

components/ee/ws-scheduler/pkg/scaler/driver.go

ws-scheduler's driver had a state management issue where it relied on Kubernetes to update its state quickly enough. If that didn't happen, we'd start way too many ghosts.
This change maintains a more up-to-date local state to prevent this issue.

[ws-scheduler] Prevent ghost explosions

---

install/docker/README.md

This adds missing `\` in the code example on the readme file

Fix code example

---

components/content-service/pkg/archive/tar.go
components/content-service/pkg/archive/tar_test.go

fixes https://github.com/gitpod-io/gitpod/issues/3174
**How to test:** follow any of the scenarios described in the issue.

[content-service] Decompress preserving permissions and remap file owners

---

components/blobserve/leeway.Dockerfile
components/content-service/leeway.Dockerfile
components/ee/cerc/debug.Dockerfile
components/ee/cerc/leeway.Dockerfile
components/ee/ws-scheduler/leeway.Dockerfile
components/image-builder/leeway.Dockerfile
components/registry-facade/leeway.Dockerfile
components/service-waiter/leeway.Dockerfile
components/ws-daemon/debug.Dockerfile
components/ws-daemon/leeway.Dockerfile
components/ws-daemon/seccomp-profile-installer/leeway.Dockerfile
components/ws-manager/debug.Dockerfile
components/ws-manager/leeway.Dockerfile
components/ws-proxy/leeway.Dockerfile
dev/poolkeeper/leeway.Dockerfile
dev/sweeper/leeway.Dockerfile
install/installer/leeway.Dockerfile
test/leeway.Dockerfile

**Changes:**
- latest is not a version. Use latest alpine release
- Always check for package updates
- cleanup after installation of packages

Cleanup docker files

---

components/gitpod-cli/cmd/open.go
components/gitpod-cli/cmd/preview.go
components/gitpod-cli/cmd/preview_test.go

This PR does some minor cleanup in `gp preview`, `gp open`

[gitpod-cli] Support args in open/preview env vars

---

.gitpod.yml
.werft/build.yaml
dev/image/Dockerfile

This change updates telepresence to version `0.109`.

Update telepresence in dev environment

---

components/gitpod-protocol/go/gitpod-service.go
components/gitpod-protocol/go/mock.go
components/supervisor/pkg/supervisor/supervisor.go

Make sure current `agent-smith` works.

[agent-smith] auto block users

---

components/server/src/storage/gcloud-storage-client.ts

Fixes #3152
start and stop a workspace, try to download the workspace

[server] Fix workspace download for GCP storage

---

.github/stale.yml

[stale-bot] Tone down stale bot

---

components/dashboard/src/App.tsx

Prefetches sub components when the browser idles to increase snappiness

[dashboard] prefetch components

---

components/supervisor/cmd/notify.go
components/supervisor/pkg/supervisor/notification.go

Some misc cleanup of the notification PR.

[supervisor] Minor post-notification PR cleanup

---

components/dashboard/src/provider-utils.tsx
components/server/src/bitbucket/bitbucket-auth-provider.ts

<table><tr><th>Before</th><th>After</th></tr><tr><td>
</td><td>
</td></tr></table>

[dashboard] Fix Bitbucket case and Login button icon

---

components/supervisor/pkg/terminal/service.go

- fix https://github.com/gitpod-io/gitpod/issues/3127: This PR cleans up the terminal grpc service by making sure that `Send` method is not called from different go routines.
@csweichel I could not trigger hanging terminals with this change anymore, tried for 2 hours following:
- run following node script in one terminal:
```js
(async () => {
let content = 'a';
for (let i = 0; i < 4096; i++) {
content += 'a';
}
while (true) {
console.log(content);
await new Promise(resolve => setTimeout(resolve, 0.1))
}
})();
```
- at the same time split terminal, wait to see the prompt, close the terminal
- do it till the first terminal hangs, usually one needs around 5-10 mins
I found that similar approach helped to resolve deadlocks in other libraries: …

[supervisor] thread-safe terminal listening

---

components/dashboard/src/workspaces/StartWorkspaceModal.tsx
components/gitpod-db/src/typeorm/migration/1616920059049-UpdateExamples.ts

... when there are no recent projects. fixes https://github.com/gitpod-io/gitpod/issues/3606 fixes #3603 
Also updated the example list (removed markdown and real world projects)

[dashboard] pop up directly goes to examples

---

components/dashboard/src/Login.tsx
components/dashboard/src/images/welcome/automate.svg
components/dashboard/src/images/welcome/code.svg
components/dashboard/src/images/welcome/collaborate.svg
components/dashboard/src/images/welcome/customize.svg
components/dashboard/src/images/welcome/fresh.svg
components/dashboard/src/images/welcome/prebuild.svg

Changes the login page to welcome. Also removes the left half if the user has seen our website before.
Fixes #3302

[Dashboard] Welcome Page

---

components/dashboard/src/WhatsNew.tsx

fixes https://github.com/gitpod-io/gitpod/issues/3649

[dashboard] updated what's new

---

components/dashboard/src/settings/Account.tsx

Fixes https://github.com/gitpod-io/gitpod/issues/3532

[dashboard] fix full name in Account

---

components/docker-up/.gitignore
components/docker-up/BUILD.yaml
components/docker-up/dependencies.sh
components/docker-up/docker-up/main.go

or based in some of the `gitpod/workspace-*` variants.
fixes https://github.com/gitpod-io/gitpod/issues/3632

[docker-up] Do not assume container is ubuntu

---

components/ide/code/leeway.Dockerfile

This will fetch the dark theme changes from https://github.com/gitpod-io/vscode/pull/16. 🌙

Update dark theme

---

components/supervisor/pkg/supervisor/services.go
components/supervisor/pkg/supervisor/supervisor.go

Start this PR and check that git hub PR extension is installed.

[supervisor] fix #3714: return partial worksapce info if content is not ready

---

.gitpod.yml

Use go mod instead of go get

---

components/dashboard/src/App.tsx
components/dashboard/src/FromReferrer.tsx

Fix https://github.com/gitpod-io/gitpod/issues/3682

[dashboard] handle /from-referrer

---

components/dashboard/src/App.tsx
components/dashboard/src/settings/Account.tsx
components/dashboard/src/settings/Preferences.tsx

This will:
1. Change font weight in some labels.
2. Add missing redirect URL for the `/upgrade-subscription` link triggered from the IDE.
3. ...

Minor dashboard updates

---

components/dashboard/src/settings/Teams.tsx
components/dashboard/src/utils.ts

The pending purchase state ...
* should expire after a short while
* should not be persisted until the payment endpoint is hit
* should be updated (removed) on forth/back navigation

[dashboard] fix pending state in Teams

---

components/supervisor/frontend/src/index.ts

- fix #3759: guard waiting for the running phase
- Start and share a workspace.
- Ask someone to check whether he can access the workspace.
- Stop a workspace and check in devtools that ws connections to the workspace is closed.

[supervisor-frontend] if running poll ready checks

---

components/dashboard/src/settings/Plans.tsx
components/dashboard/src/settings/Teams.tsx

Partially fixes https://github.com/gitpod-io/gitpod/issues/3753
Details on the Team Subscription is missing in the modals.

Handle Team Invite URLs

---

components/ws-manager-api/typescript/src/client-provider.ts
components/ws-manager-bridge/src/cluster-service-server.ts
components/ws-manager-bridge/src/config.ts
components/ws-manager-bridge/src/container-module.ts
components/ws-manager-bridge/src/main.ts

This PR fixes both issues in #3792

[ws-manager-bridge] Fix Cluster API issues

---

dev/loadgen/cmd/run.go

[loadgen] Add TLS support to loadgen

---

components/ide/theia/leeway.Dockerfile

See https://github.com/gitpod-io/theia-app/commit/04b3d2db03f140a9a3cd463f921fe717ce6deefe
Using Theia as IDE open https://github.com/theia-ide/theia and check that smartness is available.

[theia] fix #3808: pin vscode-uri

---

components/dashboard/src/Login.tsx
components/dashboard/src/service/service.tsx
components/gitpod-protocol/src/gitpod-service.ts
components/gitpod-protocol/src/messaging/browser/connection.ts
components/supervisor/frontend/src/shared/loading-frame.ts

Try to login on gitpod.io and workspace location without any credentials stored in the browser.

fix #3847: reconnect ws to server in iframe

---

components/ws-daemon/pkg/content/service.go
components/ws-daemon/pkg/internal/session/workspace.go

This PR removes some left-over variance from the user namespace feature flag.

[ws-daemon] Remove user namespace variance

---

components/image-builder/pkg/builder/builder.go

Fix invalid type in error message

[image-builder] Fix build volume error message

---

chart/config/proxy/lib.locations.conf
components/dashboard/conf/Caddyfile

[dashboard] Refactoring of cache headers

---

.werft/build.ts
.werft/util/kubectl.ts

- create file `.werft/test.ts` with:
```
import { findFreeHostPorts } from './util/kubectl';
const [wsdaemonPort, registryProxyPort, registryNodePort] = findFreeHostPorts([
{ start: 10000, end: 11000 },
{ start: 20000, end: 21000 },
{ start: 30000, end: 31000 },
], 'hostports');
console.log(wsdaemonPort + "|" + registryProxyPort + "|" + registryNodePort)
```
- `npx ts-node test.ts`
- job runs successfully: https://werft.gitpod-dev.com/job/gitpod-build-gpl-3913-ports.1

[preview env] Only select free hostports

---

components/ws-manager/pkg/manager/monitor.go

We've been heavily using Jaeger and distributed tracing while working on improving workspace startup times. During our analysis, we've noticed that `/workspace/phase-<some_phase>` spans are broken and don't represent the correct duration of such event.
At the same time, we already have another span that is emitted and closed at the exact same points,`/workspace/handle-<some_phase>`, but those seem to be a lot more representative of the real behavior.
This PR removes `/workspace/phase-<some_phase>` with the intent of removing distractions while analyzing traces.
* Log in into the preview, start some workspaces
* Open a workspace on this PR, run the command `kubectl port-forward <jaeger_pod> 16686` and open the preview on browser
* Search for traces with:
*  Service: ws-manager
* Operation: …

[ws-manager] Remove broken phase spans

---

components/ws-manager/pkg/manager/monitor.go

Another round of fixes for ws-manager traces

[ws-manager] Cleaning up unhelpful traces

---

components/content-service-api/typescript/src/blobs_pb.d.ts
components/content-service-api/typescript/src/content_pb.d.ts
components/content-service-api/typescript/src/ideplugin_pb.d.ts
components/content-service-api/typescript/src/initializer_pb.d.ts
components/content-service-api/typescript/src/workspace_pb.d.ts
components/gitpod-protocol/src/wsready.ts
components/image-builder-api/typescript/src/imgbuilder_pb.d.ts
components/ws-daemon-api/go/go.mod
components/ws-daemon-api/go/go.sum
components/ws-daemon-api/go/mock/mock.go
components/ws-daemon-api/typescript/src/daemon_pb.d.ts
components/ws-daemon-api/typescript/src/workspace_daemon_pb.d.ts
components/ws-manager-api/typescript/src/core_pb.d.ts
components/ws-manager-bridge-api/typescript/src/cluster-service_pb.d.ts
scripts/protoc-generator.sh

~~WIP: Untested. Please advise on how to run the generator. 😇~~

[protoc] Automatically remove trailing spaces in generated pb.d.ts files

---

components/registry-facade/pkg/registry/manifest.go
components/registry-facade/pkg/registry/registry.go

This PR improves registry facade logging.

[registry-facade] Improve logging

---

.werft/build.ts
components/supervisor/go.sum
components/workspacekit/go.sum
components/ws-daemon/go.sum
components/ws-manager/go.sum

This PR ensures we're not publishing to NPM or building the installer on forks.

[build] Don't trigger full build on forks

---

components/dashboard/src/settings/SelectAccountModal.tsx

This small change includes a fix for the avatar icon.

[dashboard] fix images on Select Account modal

---

components/content-service/pkg/storage/gcloud.go

Fixes #4077 .
Not sure how to test this as we have not clue what triggers this errors. But the stacktraces is straight forward.

[content-service] Handle err to prevent segfault

---

components/ws-manager/pkg/manager/metrics.go

Similar to #4108, but for another metric.
We might want to get this into prod ASAP as well.

Fix naming of activity metric

---

README.md
components/common-go/namegen/workspaceid.go
components/gitpod-protocol/src/util/generate-workspace-id.ts

Fix Shields.io badge color

---

.gitpod.yml

Signed-off-by: Lorenzo Fontana <lo@linux.com>

Make port 6080 private

---

.werft/build.ts
chart/templates/_helpers.tpl
chart/templates/server-deployment.yaml
chart/templates/ws-manager-bridge-deployment.yaml
components/common-go/analytics/analytics.go
components/common-go/go.mod
components/common-go/go.sum
components/gitpod-protocol/package.json
components/gitpod-protocol/src/util/analytics.ts
components/server/src/auth/login-completion-handler.ts
components/server/src/container-module.ts
components/server/src/user/user-controller.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/workspace-starter.ts
components/supervisor/cmd/run.go
components/supervisor/go.mod
components/supervisor/go.sum
components/supervisor/pkg/supervisor/supervisor.go
components/workspacekit/cmd/rings.go
components/ws-manager-bridge/src/bridge.ts
components/ws-manager-bridge/src/container-module.ts
components/ws-manager/go.sum
yarn.lock

We've predominantly relied on the database to understand how Gitpod is used. This approach has hit it's limits, hence we're looking to introduce something like segment to help with this matter.

Add Segment support

---

components/ws-manager-bridge/src/cluster-service-server.ts

This PR prevents accidental de-registration of active clusters:

[PWC] Prevent deregistering non-empty cluster

---

components/supervisor/pkg/supervisor/supervisor.go

[supervisor] Fix negative WaitGroup counter

---

.werft/util/kubectl.ts

Fixes the situation where preview environments don't get delete because `kubectl delete pod ...` hangs indefinitely on single workspaces.

[werft] Use delete pod --force for stubborn workspaces

---

components/workspacekit/cmd/rings.go
components/workspacekit/pkg/lift/lift.go
components/workspacekit/pkg/seccomp/notify.go

Fixes pending issue returning exit code 130.
https://github.com/gitpod-io/gitpod/pull/3430#issuecomment-804045030

[workspacekit] Refactor lift command

---

components/dashboard/src/prebuilds/InstallGitHubApp.tsx

Minor typo. 😇 
In case you haven't seen these pages in action here're some screenshots. 🖼️ 
| BEFORE | AFTER|
|-|-|
| ![image](https://user-images.githubusercontent.com/120486/118892796-177fe000-b90a-11eb-8219-48132fa775a9.png) | ![image](https://user-images.githubusercontent.com/120486/118892785-15b61c80-b90a-11eb-99a6-e97adeba170c.png) |

[dashboard] Typo in install GitHub app modal

---

components/gitpod-cli/cmd/init.go

Fixes `gp init`
- opens `.gitpod.yml`
- removes creation of a sticky `.gitpod.dockerFile`
fixes #3975

[gp cli] fix gp init

---

components/ws-manager/pkg/manager/status.go

Remove deprecated code 9 months ago

[ws-manager] Remove deprecated annotation

---

dev/charts/jaeger/templates/jaeger-deployment.yaml

Changes:
- version 1.14 is two years old.
- switch pull policy to IfNotPresent

[dev] Update jaeger to latest version

---

dev/image/Dockerfile

Upgrade Terraform to have new features, such as [configuration_aliases](https://www.terraform.io/docs/language/modules/develop/providers.html), available.

Upgrade Terraform

---

chart/templates/db-sync-configmap.yaml
chart/templates/db-sync-deployment.yaml
chart/templates/db-sync-serviceaccount.yaml
chart/templates/db-sync-unprivileged-rolebinding.yaml

Fixes small chart issues after db-sync move.

[chart] Fix db-sync

---

components/gitpod-db/src/typeorm/migration/1621920691254-InitialComSetup.ts

[db] Fix InitialComSetup

---

components/local-app/pkg/bastion/bastion.go
components/supervisor/pkg/supervisor/supervisor.go

This PR makes sure that tunnels are closed by getting rid of waiting for both directions to be closed. Instead if at least one is closed then another is closed as well.
- Start the workspace and check that ports are working as usual: https://ak-local-app-stale-tunnels.staging.gitpod-dev.com#https://github.com/akosyakov/parcel-demo
- Start the app
```bash
curl -OL https://ak-local-app-stale-tunnels.staging.gitpod-dev.com/static/bin/gitpod-local-companion-darwin
chmod +x ./gitpod-local-companion-darwin
GITPOD_HOST=https://ak-local-app-stale-tunnels.staging.gitpod-dev.com ./gitpod-local-companion-darwin --mock-keyring
```
- Reload the page and check that you can open the page with tunnels as many times as you want.
- Check on `/_supervisor/debug/tunnels` that if you close all localhost pages …

[tunnel] close the tunnel if at least one side is dropped

---

chart/templates/ws-manager-bridge-configmap.yaml

[chart] Fix ws-manager-bridge static config

---

chart/templates/proxy-configmap.yaml

[proxy] Add kedge route

---

chart/templates/proxy-configmap.yaml

[proxy] Final fix

---

components/proxy/conf/Caddyfile

how to test:
visit /admin/users first then try to hard reload in the browser. verify, you don't see an "unhandled request" error generated by the server.

[proxy] fix api-server config

---

chart/Chart.yaml
chart/values.yaml

As there is the need to disable rabbitmq, this will enable it.

making it possible to diable rabbitmq by value like the other dependencies

---

chart/templates/ws-manager-deployment.yaml

This PR assumes https://github.com/gitpod-io/gitpod/pull/4319 is merged first.

Include rbac proxy for server and ws-manager

---

components/content-service/pkg/initializer/git.go

Fixes https://github.com/gitpod-io/gitpod/issues/4335
Note: This is similar to the 'git stash -u' error when repositories are empty, so the fix is mostly a copy of:
https://github.com/gitpod-io/gitpod/blob/b43fbfa22f6d3da0f1fd037ce4a686182a9c1a19/components/content-service/pkg/initializer/prebuild.go#L88-L93

[content-init] Don't fail when origin is an empty repository

---

components/server/src/user/user-service.ts
components/server/src/workspace/gitpod-server-impl.ts

Adds new Segment call for new signups that includes marketing information such as email, name, etc.

[analytics] Add Track Event for Signups & Notification Changes

---

components/gitpod-db/src/typeorm/user-db-impl.ts

Enable Product Comm by default for new Signups

---

components/local-app/main.go
components/local-app/pkg/bastion/bastion.go
components/ws-manager/go.sum

Deleted 'defer'ed close of terminal was main cause.
Fixed some [other](https://github.com/gitpod-io/gitpod/issues/4347) [minor](https://github.com/gitpod-io/gitpod/issues/4346) issues while there.

Fix issues blocking ssh from local terminal

---

SECURITY.md

Fixes https://github.com/gitpod-io/website/issues/512

Fix the security reporting URL

---

components/server/src/github/github-context-parser.spec.ts
components/server/src/github/github-context-parser.ts

[github] handle issue page context

---

.gitpod.yml
.werft/build.yaml
.werft/run-integration-tests.yaml
.werft/wipe-devstaging.yaml
components/gitpod-protocol/go/gitpod-config_test.go
dev/image/Dockerfile

See https://github.com/gitpod-io/gitpod/compare/jk/go-install-4379

[dev] don't overwrite Go installation in dev image

---

CHANGELOG.md
components/dashboard/src/components/PendingChangesDropdown.tsx
components/dashboard/src/workspaces/WorkspaceEntry.tsx

| Before | This PR |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/24960040/121072141-1d623600-c7d1-11eb-9460-4d4e024b6f10.png) | ![image](https://user-images.githubusercontent.com/24960040/121072035-fc014a00-c7d0-11eb-8d60-1b32f6e3fee6.png) |
Fixes #4194

[dashboard] Fix workspaces list dark text colors

---

components/dashboard/src/settings/EnvironmentVariables.tsx
yarn.lock

[dashboard] Fix text overflow in env vars settings

---

components/dashboard/src/components/Modal.tsx

[dashboard] Don't close modal when click outside

---

components/content-service/pkg/archive/tar.go
components/content-service/pkg/layer/provider.go
components/content-service/pkg/storage/minio.go
components/registry-facade/pkg/registry/manifest.go
components/ws-daemon/pkg/content/initializer.go
components/ws-daemon/pkg/content/service.go
components/ws-manager/pkg/manager/monitor.go
components/ws-manager/pkg/manager/probe.go

Changes:
- remove unnecessaries changes of types
- remove binary content fields
- send error messages instead of error

Cleanup tracing spans

---

.werft/build.ts
.werft/build.yaml

[werft] Generate code coverage

---

components/dashboard/public/robots.txt

helps progress https://github.com/gitpod-io/website/issues/599

dashboard(robotstxt): exclude from-referrer

---

.gitpod.yml
.werft/build.ts
.werft/build.yaml
.werft/run-integration-tests.yaml
.werft/wipe-devstaging.yaml
components/gitpod-protocol/go/gitpod-config_test.go
dev/image/Dockerfile

**Changes:**
- Remove pulumi
- Update gcloud sdk from 245 to 344
- Switch to binary codecov uploader

[dev-environment] Do not use a pinned version and use new codecov uploader

---

components/BUILD.yaml

Run `leeway run components:make-user-admin`
@gtsiolis: We discussed this and since I needed this now I implemented it. Are you available for a review (not time critical at all)?

[dev] Add make-user-admin script

---

components/gitpod-cli/cmd/env_test.go
components/gitpod-cli/go.mod
components/gitpod-cli/go.sum

Fixes https://github.com/gitpod-io/gitpod/pull/4494#pullrequestreview-683235276

[gitpod-cli] Use go-cmp for env test comparison

---

components/ee/agent-smith/BUILD.yaml
components/ws-manager/BUILD.yaml

for agent smith and ws-manager

[build] Fix version manifest

---

components/proxy/conf/Caddyfile

Signed-off-by: Lorenzo Fontana <lo@linux.com>

Enable COOP in Caddy

---

components/server/src/bitbucket/bitbucket-context-parser.ts

Fixes #4224
Test that an empty repo opens and that these 2 context URLs work:
- https://clu-empty-bitbucket-4224.staging.gitpod-dev.com/#https://bitbucket.org/corneliusludmann/empty/src
- https://clu-empty-bitbucket-4224.staging.gitpod-dev.com/#https://bitbucket.org/corneliusludmann/empty
Bonus points for checking that “normal” repos still work, e.g.:
- https://clu-empty-bitbucket-4224.staging.gitpod-dev.com/#https://bitbucket.org/gitpod/sample-repository/src
- https://clu-empty-bitbucket-4224.staging.gitpod-dev.com/#https://bitbucket.org/gitpod/sample-repository/
- https://clu-empty-bitbucket-4224.staging.gitpod-dev.com/#https://bitbucket.org/gitpod/sample-repository/branch/branch-with-dir

[Bitbucket] Allow to open empty Bitbucket repo

---

chart/templates/agent-smith-daemonset.yaml

Same as https://github.com/gitpod-io/gitpod/pull/4517, but for agent smith.

use value that k8s uses no. 2

---

components/gitpod-protocol/data/gitpod-schema.json

[gitpod-schema] Add deprecation message to prebuild task

---

components/gitpod-protocol/data/gitpod-schema.json

[gitpod-schema] Remove unused 'ide' property

---

components/server/src/gitlab/gitlab-auth-provider.ts
components/server/src/gitlab/gitlab-repository-provider.ts

[gitlab] Handle null in avatar_url

---

.werft/values.dev.yaml
components/ws-manager/config-schema.json
components/ws-manager/pkg/manager/config.go
components/ws-manager/pkg/manager/create.go

Became unnecessary with the new agent-smith.

[supervisor] Remove theiaSupervisorToken

---

components/gitpod-protocol/src/util/generate-workspace-id.ts

very cute fat bird, ended up being killed by us introducing apex predators (read: "cats") to its island's wildlife
pretty sure the last dodo's thoughts before being eaten were about all the Gitpod workspaces that would be named after its extinct species

Add dodo to animals

---

components/workspacekit/cmd/lift.go
test/pkg/integration/agent.go
test/pkg/integration/integration.go
test/pkg/integration/workspace.go
test/tests/storage/storage_test.go
test/tests/workspace/content_test.go
test/tests/workspace/git_test.go

How to test:
- open build workspace
- in a terminal: `cd test && go test -v ./...`

[test] Fix integration tests

---

components/supervisor/pkg/supervisor/supervisor.go

We can see in the log the time, like `"IDE readiness took 8.021 seconds",`

[supervisor] Improve IDE ReadinessHTTPProbe

---

components/ee/kedge/pkg/kedge/kubernetes.go

This PR aims to remove the label `app.kubernetes.io/instance` from the services created by Kedge.
'app.kubernetes.io/instance' is automatically added to kedge when it is deployed by ArgoCD. This mechanism is used so ArgoCD knows which resource it is supposed to control and which ones it isn't. If we add this label to the resources created by kedge, ArgoCD will think that ArgoCD should be controlled, and since their resource definitions are not in git, ArgoCD will try to delete them.

Remove ArgoCD label from services created by kedge

---

chart/templates/db-deployment.yaml

This enabled db-deployments to be scaled using values.

[Helm] added replicas to db deployment

---

.werft/build.ts
.werft/util/certs.ts

Introduced a flag k3s-ws to indicate that there should be worksapce deployment to k3s cluster for preview environment.
Refactored functions to reuse them to issue certificate and create A record for k3s cluster ws components.
Subsequent PR will add logic to trigger cert issuance for ws cluster

k3s ws preview env related refactoring

---

components/content-service/pkg/storage/gcloud.go

mitigation for https://github.com/gitpod-io/gitpod/issues/4671

[content-service] Fallback to prodcopy in prod

---

components/content-service/pkg/storage/gcloud.go

Revert "[content-service] Fallback to prodcopy in prod"

---

components/proxy/Dockerfile
components/proxy/conf/Caddyfile

[caddy] Provide artifical sec-websocket-key

---

chart/templates/server-deployment.yaml

Fixes #4679
_(See issue for details.)_

[helm] Set the Theia version as env var in server

---

components/ide/code/leeway.Dockerfile

- fix #4726 
Gitpod Code Change: https://github.com/gitpod-io/vscode/commit/fde107c3bf415f31560a050d2bde356d8e7602fd
Start a workspace and try to share.

[code] confirm sharing

---

components/server/src/github/github-context-parser.spec.ts

The tests for the GitHub context parser are broken. This PR fixes the tests.

[server] Fix GitHub context parser spec

---

components/dashboard/conf/Caddyfile

- fix #4806
https://akosyakov-json-catalogue-points-4806.staging.gitpod-dev.com/schemas/gitpod-schema.json should return proper JSON

rewrite gitpod-schema location

---

components/server/src/workspace/additional-content-prefix-context-parser.ts

[server] Remove misleading log in AdditionalContentPrefixContextParser

---

components/server/package.json
components/server/src/auth/login-completion-handler.ts
components/server/src/server.ts
components/server/src/user/user-controller.ts
yarn.lock

In order to attribute client side events to signed up users, I changed the anonymous ID trait on server side identify calls to the one used on the client side.

[analytics] fixed anonymous ID trait in identify()

---

dev/loadgen/prod-benchmark.yaml

Branch namens `master` and `main` were mixed up. See code changes.

Fix lodgen benchmark cloneTargets

---

OWNERS_ALIASES

[prow] Add csweichel to meta owner list

---

chart/values.yaml

[agent-smith] Disable by default

---

chart/values.yaml

Follow-up to https://github.com/gitpod-io/gitpod/pull/4969

[chart] Set workspace size limit

---

components/dashboard/src/workspaces/workspace-model.ts

[dashboard] add regular workspaces to list only

---

OWNERS_ALIASES

/cc @JanKoehnlein 
/approve no-issue

[prow] Add new team member

---

components/server/src/workspace/workspace-starter.ts

[server] Allow workspace restarts with base image from private repo

---

components/ws-manager-bridge/src/meta-instance-controller.ts

when forcing the phase from preparing or unknown
/cc @MrSimonEmms

[ws-manager-bridge] Set stopping/stopped time

---

components/supervisor/pkg/supervisor/supervisor.go

fixes #5091 
by reaping all child processes, respecting `wait` interruptions and not blocking the `SIGCHILD` handler.

[supervisor] Correctly reap child processes

---

chart/templates/server-deployment.yaml
chart/values.yaml
components/dashboard/src/settings/Preferences.tsx

There is a parsing error in templates/server-deployment.yaml:167.
ArgoCD complains:
```
rpc error: code = Unknown desc = Manifest generation error (cached): `/bin/sh -c helm template --release-name gitpod . ${values_files_arguments}` failed exit status 1: walk.go:74: found symbolic link in path: /tmp/git@github.com_gitpod-com_gitpod/charts/gitpod_io/charts/gitpod resolves to /tmp/git@github.com_gitpod-com_gitpod/gitpod-core/chart Error: parse error at (gitpod_io/charts/gitpod/templates/server-deployment.yaml:167): unclosed action Use --debug flag to render out invalid YAML
```

revert 7826291

---

components/dashboard/src/Menu.tsx
components/dashboard/src/projects/Prebuilds.tsx
components/dashboard/src/projects/Project.tsx

This will make some minor visual changes on the project header.
| BEFORE  | AFTER |
|-|-|
| <img width="440" alt="Screenshot 2021-08-11 at 2 27 07 PM" src="https://user-images.githubusercontent.com/120486/129021515-1b76a791-f5fb-468b-bf41-ddb43b43bcdb.png"> | <img width="440" alt="Screenshot 2021-08-11 at 2 26 23 PM" src="https://user-images.githubusercontent.com/120486/129021519-8f03cbe1-2cb2-4a1d-9d5c-a9297afe30bd.png"> |

Minor project header visual changes

---

components/ws-daemon/pkg/content/service.go
components/ws-manager/pkg/manager/monitor.go

```
no remote storage configured:
github.com/gitpod-io/gitpod/ws-daemon/pkg/content.(*WorkspaceService).uploadWorkspaceLogs
github.com/gitpod-io/gitpod/ws-daemon/pkg/content/service.go:552"
```
Internal log https://cloudlogging.app.goo.gl/2ty2pZsFRfVtLARx6

Do not upload ghost workspace logs and skip backups

---

chart/templates/server-deployment.yaml
chart/values.yaml
components/dashboard/src/settings/Preferences.tsx

This reverts commit 7826291736fe9ca241782989e759612131572529.
Fixes #4965

Revert the revert of "[ide] added VS Code "Insiders" IDE variant"

---

.werft/wipe-devstaging.yaml

[werft] Update sweeper to use new cluster credentials

---

OWNERS_ALIASES

Such that he's no longer chosen as reviewer.

removed fntlnz from code owners

---

components/service-waiter/cmd/messagebus.go

It seems like the current long description came from `database.go` and it is not correct for the current file.

Update long description in messagebus

---

components/dashboard/src/start/CreateWorkspace.tsx

[dashboard] Propose to add Git integration

---

components/content-service/pkg/storage/gcloud.go

Internal link https://cloudlogging.app.goo.gl/aiiGkG9QEQWY4rD47

[content-service] Remove error log if the bucket does not exists

---

chart/README.md

Corrects minio helm repo command

---

components/licensor/ee/pkg/licensor/licensor.go
components/licensor/ee/pkg/licensor/licensor_test.go

Related to https://github.com/gitpod-io/gitpod/issues/5314
I did not use `Fixes` because there is a corresponding change that needs to be done on the website.

[license] adjust users of self-hosted license

---

OWNERS_ALIASES
components/ide/OWNERS
components/supervisor/OWNERS

This PR introduces the IDE team and updates the appropriate OWNERS files.

[owners] Introduce the IDE team

---

chart/templates/payment-endpoint-deployment.yaml
chart/values.yaml

Aftermath of https://github.com/gitpod-io/gitpod/pull/4982

[server, paymentendpoint] Fix config (parsing)

---

chart/templates/payment-endpoint-deployment.yaml
chart/templates/server-configmap.yaml
chart/values.yaml
components/server/src/config.ts

Aftermath of https://github.com/gitpod-io/gitpod/pull/4982.

[server] Add/propagate missing defaults

---

chart/templates/server-configmap.yaml
components/server/src/config.ts

Aftermath of https://github.com/gitpod-io/gitpod/pull/4982.

[server] Fix temporary config validation

---

components/gitpod-db/src/typeorm/migration/1630566926740-AddPrebuildInfo.ts

Fixes https://github.com/gitpod-io/gitpod/issues/5494

[db-migration] fix timestamp of AddPrebuildInfo

---

components/gitpod-db/src/typeorm/migration/1630586785018-UpdateDevxAndOnboardingMail.ts

[db-migration] update timestamp of UpdateDevxAndOnboardingMail

---

OWNERS
components/local-app/OWNERS

[prow] Give IDE team more ownership

---

chart/values.yaml

From eng meeting revert gitpod-io/gitpod#5228
```release-notes
NONE
```

Revert "[chart] Reduce verbosity of the logs"

---

components/content-service/pkg/storage/gcloud.go

Fixes #5535.
I thought about adding tests to this PR (bc codecov complains). I refrained because:
- the logic to test would be most interesting to run as integration test: no codecov anyways
- we do not have content-service integration in integration tests yet. Happy do add this, but in a separate PR.
Also it's unclear what the actual error messages is, as it's hidden by the segfault. This PR unearthes that error messages.
```release-note
NONE
```

[content-service] DeleteObject: improve it.Next err handling

---

.github/pull_request_template.md
.werft/changelog.yaml

Fixes some minor changelog issues
- Use a dedicated GitHub token 
- Added a link to our docs in the template
Fixes #4919
```release-note
NONE
```

[changelog] some cleanup

---

CHANGELOG.md

Updated the changelog from recent PR descriptions
```release-note
NONE
```

[changelog] updated changelog

---

components/server/src/auth/resource-access.ts

/no-cc
Fixes #
```release-note
NONE
```

[server] Fix SharedWorkspaceAccessGuard

---

components/ws-manager/pkg/manager/monitor.go

> This error happens quite often (> 6000 entries in the last 7 days) and seems to be user-facing (i.e. error message on start workspace).
From the detail of the several traces, the error happens in ring 0 during the shutdown (there is only two connection to InWorkspaceService). We are too eager to call `finalizeWorkspaceContent`.
This PR adds an additional wait time on top of the `deletionGracePeriod` to make sure the changes propagate on the data plane.
Fixes https://github.com/gitpod-io/gitpod/issues/5574
- kill `ws-daemon` pod
- wait until new `ws-daemon` pod is running
- stop workspace
- check there are no errors in `ws-daemon` removing workspace content and
- check the backup was created
```release-note
NONE
```

[ws-manager] Wait additional time to deletionGracePeriod before finalize workspace

---

components/dashboard/src/projects/Prebuilds.tsx

Fixes https://github.com/gitpod-io/gitpod/issues/5673
```release-note
NONE
```

[projects] fix filter for prebuilds updates

---

components/server/src/user/newsletter-subscription-controller.ts

Added a route to allow users to unsubscribe from onboarding emails
Fixes #5672
```release-note
allow users to unsubscribe from onboarding emails
```

[server] allow unsubscribe from onboarding emails

---

components/supervisor/pkg/supervisor/services.go

Fixes error message `  "error": "rpc error: code = DeadlineExceeded desc = context canceled"` when the real cause is `Canceled`
Fixes #
```release-note
NONE
```

[supervisor] Check for canceled context and reword message

---

components/ws-daemon/pkg/iws/iws.go

Fixes #
```release-note
NONE
```
/approve no-issue

[ws-daemon] Remove not useful log

---

components/content-service/pkg/storage/gcloud.go
components/ee/payment-endpoint/src/chargebee/subscription-handler.ts
components/server/src/workspace/workspace-starter.ts
components/ws-manager-bridge/src/bridge-controller.ts
components/ws-manager-bridge/src/bridge.ts
components/ws-manager-bridge/src/cluster-service-server.ts
components/ws-manager-bridge/src/meta-instance-controller.ts

Removes/downgrades loglevel/filters log statements to reduce logging noise.
Context: #5551
```release-note
NONE
```

[meta] Logging hygiene for server, payment-endpoint, ws-manager-bridge, content-service

---

components/gitpod-protocol/go/reconnecting-ws.go

Recently we changed the reconnecting web socket to allow propagate bad handshake errors to clients, that they can handle failed auth for instance in the case of the local app. It caused the issue thought that the bad handshake returned by some intermediate software like the proxy since it cannot proxy to the target host like in the case of server restart, and consequently complete breaks connection.
This PR changes the reconnecting web socket to propagate bad handshake only for 3xx or 4xx status code, otherwise it tries to reconnect 15 times, so around 5mins and then fails too.
fix #5762
- Start a workspace, and monitor logs.
- Delete the server several times, each time checks that supervisor reconnects in ws logs.
```release-note
NONE
```

try reconnect 15 times to ws on bad handshake with 3xx or 4xx status code

---

components/gitpod-db/src/typeorm/migration/1630333424897-ReplaceStringBooleansWithBooleans.ts

[db] Fix string booleans to be booleans

---

chart/values.yaml

Reinstate after 20th of September.
Fixes #
```release-note
NONE
```
/hold

[chart] Reduce verbosity of the logs

---

components/ws-manager/pkg/manager/internal/grpcpool/pool.go
components/ws-manager/pkg/manager/manager.go

The previous logic removes valid connections.
Fixes #
```release-note
NONE
```

[ws-manager] Fix invalid logic to remove old endpoint

---

components/dashboard/package.json
components/dashboard/src/Analytics.tsx
components/dashboard/src/App.tsx
components/dashboard/src/Menu.tsx
components/dashboard/src/admin/UserSearch.tsx
components/dashboard/src/admin/WorkspacesSearch.tsx
components/dashboard/src/components/ContextMenu.tsx
components/dashboard/src/components/PillMenuItem.tsx
components/dashboard/src/components/TabMenuItem.tsx
components/dashboard/src/index.tsx
components/dashboard/src/projects/NewProject.tsx
components/dashboard/src/projects/Projects.tsx
components/dashboard/src/teams/Members.tsx
components/gitpod-protocol/src/analytics.ts
components/gitpod-protocol/src/gitpod-service.ts
components/gitpod-protocol/src/util/analytics.ts
components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/src/auth/rate-limiter.ts
components/server/src/user/enforcement-endpoint.ts
components/server/src/websocket-connection-manager.ts
components/server/src/workspace/gitpod-server-impl.ts

Implements tracking for the dashboard
- Go to Segment's staging untrusted source
- This PR should generate page and tracking events a user navigating through the dashboard
```release-note
NONE
```
/werft with-clean-slate-deployment=true

[analytics] Track Projects & Teams

---

OWNERS_ALIASES

Updates the OWNER_ALIASES file to reflect the latest team changes
FIxes no issue
```release-note
NONE
```

[owners] Update to reflect latest team changes

---

components/ws-proxy/pkg/proxy/pass.go

[proxy] Do not log supervisor proxy errors

---

components/server/src/auth/login-completion-handler.ts

Error fix for login analytics call
Cannot be tested in preview environment as http header is added by google load balancer
```release-note
NONE
```

[analytics] Fix location prop in analytics track call

---

components/supervisor/pkg/supervisor/supervisor.go

`docker-up` or other docker components some time crash or OOM Killer, but previous implementation
of socketActivationForDocker is a one time starter, so when `dockerd` crash, `docker` command stuck
Fixes #
start a workspaces
run `docker ps`
see docker-up is running
then run `sudo killall docker-up`
then run again `docker ps`
see docker-up is running again
```release-note
NONE
```

[supervisor] fix docker stuck for some reason 

---

components/gitpod-db/src/workspace-db.spec.db.ts

This change just adds two additional test cases for the workspaces find query function, to verify it is working properly.
```release-note
NONE
```

[gitpod-db] added more tests

---

components/dashboard/src/projects/Project.tsx

Some improvements on the branches page
- allow navigating to the repository
- allow navigation to the branches
Fixes #5585
Create a project and see the changes on the branches page.
```release-note
NONE
```

[dashboard] improve branches page

---

components/server/src/workspace/headless-log-service.ts

On certain repositories (especially gitpod-io/gitpod) prebuild logs would not show in most cases while the prebuild was still running. The problem was caused by broken handling of terminals that have already finished.
Fixes #5770
1. clone gitpod-io/gitpod into your account
2. go to https://gpl-5770-logs.staging.gitpod-dev.com/new and create a new team and import that project
3. trigger a prebuild and view it's logs: should always display/stream
```release-note
[prebuilds] fix prebuild logs with multiple tasks
```

[server] Handle terminals for tasks that have already been closed

---

README.md

Cleaned up dead links and brushed Readme.
```
NONE
```

Clean-up Readme

---

test/entrypoint.sh

Fix location of integration tests binaries

---

test/pkg/integration/setup.go

[test] Add missing kubeconfig flag

---

test/pkg/integration/setup.go

Fix parsing of test binaries flags

---

test/entrypoint.sh
test/leeway-build.sh

[test] Ensure agent binaries are available in PATH

---

components/dashboard/src/projects/Project.tsx

This PR fixes rendering of the Project page.
Fix-up for issues from #5640
```release-note
NONE
```

[projects] fix for empty projects page

---

components/dashboard/src/settings/Teams.tsx

Follow up for https://github.com/gitpod-io/gitpod/pull/6011, see https://github.com/gitpod-io/gitpod/pull/6011#issuecomment-933498123. 🐈 
```release-note
NONE
```

Fix typos for team plans

---

components/ee/agent-smith/pkg/agent/agent.go
components/ee/agent-smith/pkg/agent/config.go

Fixes #5280
```release-note
NONE
```

[agent-smith] Allow commands to skip infringements

---

.werft/changelog.yaml
dev/changelog/pullrequest.go

Fixes #
```release-note
NONE
```

[changelog] next try to enable automatic merge

---

.werft/changelog.yaml
dev/changelog/pullrequest.go
dev/changelog/update.go

Fixes for the changelog
- automerge should work now
- entries are now fetched in "created" order and sorted by merge date
```release-note
NONE
```

[changelog] fixes for the changelog

---

components/dashboard/src/components/ConfirmationModal.tsx

Fixes #6383 
1. Create a team
2. Go to team settings
3. Click Delete Team
5. Press enter without focusing on the modal , it not submit
```release-note
NONE
```

[dashboard] fix skip confirm modal #6383

---

.werft/code-nightly.yaml

Fixes #
```release-note
NONE
```

fix debug command for code-nightly

---

.werft/code-nightly.yaml

Fixes #
```release-note
NONE
```

fix code nightly job

---

.werft/changelog.yaml
CHANGELOG.md
dev/changelog/update.go

"None" was not detected as no release notes
```release-note
NONE
```

[changelog] support all case variations of "nOnE"

---

components/registry-facade/README.md

Add docs to registry-facade
N/A
N/A
```release-note
Add documentation for registry-facade
```

[registry-facade] Add docs to registry-facade

---

components/gitpod-db/src/typeorm/user-db-impl.ts

Fixes #
- go to https://gpl-fix-update-user.staging.gitpod-dev.com/preferences
- switch to insiders: note how that works
```release-note
NONE
```

[db] Fix  updateUserPartial

---

components/dashboard/src/FromReferrer.tsx
components/dashboard/src/workspaces/StartWorkspaceModal.tsx
components/dashboard/src/workspaces/Workspaces.tsx

Replace hard-coded gitpod.io links
Fixes #6400
```release-note
NONE
```

Replace hard-coded gitpod.io links

---

components/dashboard/src/App.tsx

Add support for github.dev
Fixes #6258
```release-note
NONE
```

Add support for github.dev

---

components/ee/db-sync/package.json
yarn.lock

This was missed in #6433
Fixes #
```release-note
NONE
```

[db-sync] Upgrade argparse

---

components/supervisor/pkg/supervisor/supervisor.go

Fixes shutting down the IDE process in supervisor.
/werft with-clean-slate-deployment
Fixes #6530
Stop a workspace and make sure that the segfauls error mentioned in the issue does not occur.
```release-note
NONE
```

[supervisor] Fix IDE shutdown

---

installer/example-config.yaml
installer/pkg/cluster/checks.go
installer/pkg/common/sorter.go
installer/pkg/components/ws-daemon/configmap.go
installer/pkg/config/v1/validation.go

This PR improves the generated YAML by removing empty documents, trimming empty lines and adding helpful comments for navigating the document.
It also adds a validation that checks if the certificate secret is present.
```bash
installer validate cluster --config your-config.yaml
installer render --config your-config.yaml
```
```release-note
NONE
```

[installer] Improve generated YAML

---

components/image-builder-bob/cmd/build.go
components/image-builder-bob/pkg/builder/builder.go
components/supervisor/pkg/supervisor/tasks.go
components/supervisor/pkg/terminal/terminal.go
test/entrypoint.sh
test/leeway.Dockerfile
test/pkg/integration/setup.go
test/tests/components/content-service/content-service_test.go
test/tests/components/server/server_test.go
test/tests/workspace/contexts_test.go

[test] Use configured username

---

components/dashboard/src/App.tsx

support gitpod.io/<project-url>
Fixes #6445
only can support https://gitpod.io/github.com/gitpod-io/website
```release-note
NONE
```

[dashboard] support gitpod.io/<project-url>

---

components/gitpod-db/src/config.ts

Fix config in: https://github.com/gitpod-io/gitpod/pull/6605
Fixes #
```release-note
NONE
```

[db] Fix migrations config

---

chart/templates/db-migrations-job.yaml
components/gitpod-db/migrate.sh
components/gitpod-db/migrate_gcp.sh
components/gitpod-db/typeorm.sh

Fixes https://github.com/gitpod-io/gitpod/pull/6612
```release-note
NONE
```

[db] Fix 'migrations' migration for GCP case

---

.werft/build.ts
.werft/util/certs.ts
.werft/util/gpctl.ts
.werft/util/kubectl.ts
.werft/util/util.ts
.werft/wipe-devstaging.ts
.werft/yarn.lock

Makes build.ts more readable and extensible.
Fixes #
- see that the deployment works: https://werft.gitpod-dev.com/job/gitpod-build-gpl-dev-werft-chores.2
- see that the `wipe-devstaging` job works as well: https://werft.gitpod-dev.com/job/gitpod-wipe-devstaging-gpl-dev-werft-chores.1/logs
```release-note
NONE
```

[werft] Cleanup build.ts around KUBECONFIG

---

operations/workspace/deployment/pkg/orchestrate/deploy.go
operations/workspace/deployment/pkg/step/installgitpod.go

Implement step to install gitpod. It invokes a script `install-gitpod.sh` which installs gitpod on the cluster.
Fixes https://github.com/gitpod-io/gitpod/issues/6332
Tested it here with other PR changes: https://werft.gitpod-io-dev.com/job/ops-workspace-deploy-workspace-prs-install-gitpod.29/raw
```release-note
None
```

[ws-deployment] Add gitpod installation step

---

WORKSPACE.yaml

Upgrade to VS Code 1.62.2 recovery release
Picks up fixes for the following upstream issues
https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22October+2021+Recovery+2%22
- Switch to latest VS Code in settings.
- terminals are preserved and resized properly between window reloads
- extension host process: check language smartness and debugging
- extension management (installing/uninstalling)
- install VIM extension to test web extensions
- that user data are sync across workspaces as well as on workspace restart, especially for extensions
- extensions from .gitpod.yml are not installed as sync
- extensions …

[code] upgrade to vscode 1.62.2

---

.werft/build.ts
.werft/values.nodeAffinities_1.yaml

Because of an increase of prev-environements, we need to activate an extra nodepool.
https://gitpod.slack.com/archives/C01KGM9EBD4/p1636574938263100

added an extra nodepool

---

components/gitpod-protocol/src/gitpod-service.ts
components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/src/container-module.ts
components/server/src/server.ts
components/server/src/user/enforcement-endpoint.ts
components/server/src/websocket/websocket-connection-manager.ts
components/server/src/workspace/gitpod-server-impl.ts
operations/observability/mixins/meta/dashboards/components/server.json

Gets more insights into where websocket connection are originated.
Context: https://github.com/gitpod-io/gitpod/issues/6662
```release-note
NONE
```

More insights into websocket connection

---

components/image-builder-bob/leeway.Dockerfile

https://github.com/moby/buildkit/releases/tag/v0.9.3
```release-note
NONE
```

[image-builder-bob] Update buildkit

---

components/dashboard/src/settings/EnvironmentVariables.tsx

This will change environment variable scope placeholder.
https://github.com/gitpod-io/website/issues/1250
```release-note
NONE
```

Change environment variable scope placeholder

---

operations/observability/mixins/workspace/dashboards.libsonnet
operations/observability/mixins/workspace/dashboards/success-criteria.json

See https://grafana.gitpod.io/d/jgjwvIc7k/success-criteria?orgId=1
Open https://grafana.gitpod.io/d/jgjwvIc7k/success-criteria?orgId=1
```release-note
NONE
```

[observability] Add ws team success criteria dashboard

---

gitpod-ws.code-workspace

Add installer folder to vscode settings

---

installer/pkg/common/common.go

[installer] Update kube-rbac-proxy container and reduce log level

---

components/ee/payment-endpoint/src/github/subscription-reconciler.ts

Log errors when reconciling plans with GitHub
Fixes #6531
I fear this cannot be tested.
```release-note
NONE
```

[payment] added more resilience to GitHub payment endpoint

---

components/gitpod-db/src/typeorm/entity/db-prebuilt-workspace.ts
components/gitpod-db/src/typeorm/entity/db-subscription.ts
components/gitpod-db/src/typeorm/entity/db-workspace.ts
components/gitpod-db/src/typeorm/migration/1637586292251-IndexTokenEntryExpiryDate.ts
components/gitpod-db/src/typeorm/migration/1637586576910-IndexSubscriptionTsSlotId.ts
components/gitpod-db/src/typeorm/migration/1637587163581-IndexPWSProjectId.ts
components/gitpod-db/src/typeorm/migration/1637587650752-IndexWorkspaceGCQueries.ts

Fixes #6807
1. run all `EXPLAIN`s from [the issue](https://github.com/gitpod-io/gitpod/issues/6807) and note how `type` is always `ref` or `index`, never `ALL` or `range`
2. make sure there is a typeorm `@Index` for every index added and vice-versa
```release-note
NONE
```

[db] Add missing indexes

---

.werft/observability/monitoring-satellite.ts

In https://github.com/gitpod-io/observability/pull/29 we made 2 changes:
* Hid tracing components behind `tracing_enabled` external variable.
* Simplified deployment logic
This commit also do the same 2 things:
* Set to true the `tracing_enabled` external variable
* Re use upstream deployment logic instead of maintaining our own.
Related to https://github.com/gitpod-io/observability/issues/27
```release-note
NONE
```

.werft/observability: Simplify deployment logic

---

components/ws-manager/pkg/manager/testdata/cdwp_affinity.golden

Fixes #6940 
```release-note
NONE
```

[ws-manager] fixes cdwp affinity test is flakey

---

components/gitpod-db/src/typeorm/migration/helper/helper.ts

Fixes `indexExists`.
This is still fallout from the version upgrade :slightly_smiling_face: 
Fixes #
```release-note
NONE
```

[db] Fix indexExists

---

components/supervisor/pkg/supervisor/supervisor.go

[supervisor] Fixes failing prebuilds are not reported as "headlessTaskFailed"
Fixes #6643
Following this step https://github.com/gitpod-io/gitpod/issues/6643#issuecomment-977904766
```release-note
NONE
```

[supervisor] Fixes failing prebuilds are not reported as "headlessTaskFailed"

---

components/proxy/plugins/workspacedownload/workspace_download.go

Adapts the route to also work with other domains. 
Fixes #6351
```release-note
Workspace download route config set to work with other domains.
```

Adapt workspace download config

---

.werft/build.ts

If observability is enabled, we want to deploy it before installing Gitpod itself. The reason behind it is because Gitpod components will start sending traces to a non-existent OpenTelemetry-collector otherwise.
Fixes https://github.com/gitpod-io/ops/issues/304
```release-note
NONE
```

.werft/build: Deploy monitoring-satellite before Gitpod

---

operations/observability/mixins/meta/dashboards/components/meta-overview.json
operations/observability/mixins/meta/dashboards/components/server.json

[ops] Small dashboard/graph fixes

---

components/server/BUILD.yaml

Re-enables telepresence for server
`leeway run components/server:telepresence`  should work
```release-note
NONE
```

[server] re-enable telepresence

---

.github/workflows/changelog.yml

This changes the shell which is used to run the changelog script and should solve the error.

changed shell for changelog

---

.github/workflows/changelog.yml

This does only change the time schedule to run the changelog action to 0:00 every day. I also changed the vm-image to ubuntu-latest.

changed time schedule for changelog

---

components/image-builder-mk3/pkg/orchestrator/orchestrator.go

This corrects the use of digested base images.
Prior to this change, bob proxy would force the tag and ignore the digest.
Fixes #7050
1. open `https://github.com/appdev-projects/base-rails/tree/5e42ef0d03bcc267baf7f13b47f3b7f3ad71dc32` in a workspace. If it contains ruby 2.7.3 we choose the correct base image
```release-note
NONE
```

[image-builder] Pull digested base refs correctly

---

components/image-builder-mk3/pkg/orchestrator/monitor.go

[image-builder] fixes nil-deref
Fixes #7017 
```release-note
NONE
```

[image-builder] fixes nil-deref

---

.gitpod.yml
.werft/build.yaml
.werft/debug.yaml
.werft/run-integration-tests.yaml
.werft/wipe-devstaging.yaml
components/supervisor/pkg/config/gitpod-config_test.go
dev/image/Dockerfile

[dev] upgrade dev image, leeway and werft and dazzle
Fixes #
```release-note
NONE
```

[dev] upgrade dev image

---

components/gitpod-protocol/src/util/tracing.spec.ts
components/gitpod-protocol/src/util/tracing.ts

Fixes null/undefined handling bug and adds a generic "catch-all".
Fixes #
```release-note
NONE
```

[tracing] Fix null/undefined handling and be more resilient in general

---

components/image-builder-mk3/pkg/resolve/resolve.go

fixes image-builder-mk3 resolve issue
Fixes #7114
```release-note
NONE
```

[image-builder] fixes resolve issue

---

components/ws-manager-api/go/config/config.go
components/ws-manager/pkg/manager/create_test.go
components/ws-manager/pkg/manager/manager.go
components/ws-manager/pkg/manager/manager_test.go
components/ws-manager/pkg/manager/testdata/cdwp_with_ephemeral_storage.golden
components/ws-manager/pkg/manager/testdata/cdwp_with_ephemeral_storage.json
components/ws-manager/pkg/manager/testing_test.go
installer/pkg/components/ws-manager/configmap.go

Add new EphemeralStorage field to use ephemeral-storage feature in workspaces
```release-note
NONE
```

Add support for ephemeral storage

---

components/gitpod-db/src/traced-db.ts
components/gitpod-protocol/src/util/tracing.ts
components/image-builder-api/typescript/src/sugar.ts
components/server/ee/src/prebuilds/github-app.ts
components/server/ee/src/prebuilds/prebuild-manager.ts
components/server/ee/src/prebuilds/prebuilt-status-maintainer.ts
components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/ee/src/workspace/workspace-factory.ts
components/server/ee/src/workspace/workspace-health-monitoring.ts
components/server/src/one-time-secret-server.ts
components/server/src/user/token-garbage-collector.ts
components/server/src/websocket/websocket-connection-manager.ts
components/server/src/workspace/config-provider.ts
components/server/src/workspace/garbage-collector.ts
components/server/src/workspace/gitpod-server-impl.ts
components/server/src/workspace/image-source-provider.ts
components/server/src/workspace/workspace-deletion-service.ts
components/server/src/workspace/workspace-factory.ts
components/server/src/workspace/workspace-starter.ts
components/ws-manager-bridge/ee/src/bridge.ts
components/ws-manager-bridge/src/bridge.ts
components/ws-manager-bridge/src/messagebus-integration.ts

Mainly contains two changes (+ minor cleanup)
- improve API level tracing: https://github.com/gitpod-io/gitpod/commit/7e28d67e433fc45e24eeeb915643d0f4f0cf57c4
- use less `span.log(...)` calls:
- https://github.com/gitpod-io/gitpod/commit/2105d4775eab924347c9b5f5472c17c129828cf6
- https://github.com/gitpod-io/gitpod/commit/78ce11bbd10cc540f4501cbd6fd3acc1d0217e89
Fixes #
```release-note
NONE
```
/cc @csweichel

[tracing] Improve tracing for TS components

---

chart/values.yaml

Fixes #
```release-note
NONE
```

Pin insiders version temporarily

---

.github/workflows/code-nightly.yaml

Fixes #
```release-note
NONE
```

Point code nightly workflow back to main

---

chart/templates/server-ide-configmap.yaml

clean up ide config map in helm
Fixes #7201 
```release-note
NONE
```

clean up ide config map in helm

---

OWNERS_ALIASES
installer/OWNERS

Now it's owned by the self-hosted team
```release-note
NONE
```

[installer]: change ownership

---

OWNERS

Add self-hosted team to main owners file
```release-note
NONE
```

[prow]: add self-hosted team as owners

---

components/ee/payment-endpoint/src/accounting/subscription-service.ts
components/gitpod-db/src/container-module.ts
components/gitpod-db/src/oss-allowlist-db.ts
components/gitpod-db/src/tables.ts
components/gitpod-db/src/typeorm/deleted-entry-gc.ts
components/gitpod-db/src/typeorm/entity/db-oss-allowlist.ts
components/gitpod-db/src/typeorm/entity/db-team.ts
components/gitpod-db/src/typeorm/migration/1638973332787-OssAllowlist.ts
components/gitpod-db/src/typeorm/oss-allowlist-db-impl.ts
components/gitpod-protocol/src/index.ts
components/gitpod-protocol/src/oss-allowlist.ts
components/server/ee/src/user/user-service.ts
components/server/src/auth/host-context-provider-impl.ts
components/server/src/auth/host-context-provider.ts
components/server/src/auth/login-completion-handler.ts
components/server/src/user/user-service.ts

Fixes #6918
- `kubectl port-forward mysql-0 3306`
- `mysql -u gitpod -h 127.0.0.1 -p`
- `INSERT INTO d_b_oss_whitelist SET identity = '<str>'`, example: `github.com/geropl`
- go to https://gpl-6918-oss-positivelist.staging.gitpod-dev.com/plans
- expect to see: 
```release-note
NONE
```

[server] OSS Allowlist

---

installer/README.md

Document how to install to a namespace
```release-note
NONE
```

[installer]: document installing to a namespace

---

WORKSPACE.yaml

Upgrade to VS Code 1.63.2
VSCode Endgame: https://github.com/microsoft/vscode/issues/139120
Candidate Issues: https://github.com/issues?q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22November+2021+Recovery+2%22+
Fixes #
- Switch to latest VS Code in settings.
- terminals are preserved and resized properly between window reloads
- extension host process: check language smartness and debugging
- extension management (installing/uninstalling)
- install VIM extension to test web extensions
- that user data are sync across workspaces as well as on workspace restart, especially for extensions
- extensions from .gitpod.yml are not installed as sync
- …

[code] upgrade to vscode 1.63.2

---

gitpod-ws.code-workspace

[vscode] Remove image-builder folder

---

components/server/src/express-util.ts

Motivation: https://github.com/gitpod-io/gitpod/issues/7082#issuecomment-996825731
Context: #7082 
```release-note
NONE
```

[server] Debug output for dangling ws connections

---

operations/observability/mixins/meta/dashboards/components/meta-overview.json
operations/observability/mixins/meta/dashboards/components/server.json
operations/observability/mixins/meta/rules/components/server/alerts.libsonnet
operations/observability/mixins/tests/dashboardDatasources.jsonnet

Runbook PR: https://github.com/gitpod-io/runbooks/pull/315
This not fixes the root cause of #7082 but creates an alert for it's symptoms to get by the upcoming holidays.
Review the PR by commit!
Drive-by changes:
- fix Meta Overview dashboard
- fix Server dashboard
(I made screenshots to prove they work but unfortunately they're gone, so you have to trust me with these :see_no_evil: The devx here is not optimal, really...)
Fixes #7082 
```release-note
NONE
```

[ops] Meta: Add alert ServerEventLoopLagTooHigh 

---

installer/pkg/components/workspace/constants.go

Updates vscode stable image in installer
Fixes #
```release-note
NONE
```

Update vscode stable image in installer

---

test/tests/ide/python_ws_test.go

Update python ws test to use gp-code-server-test script
https://www.npmjs.com/package/gp-code-server-test
Fixes #
1. Login to the test env
2. Open this PR in a gitpod workspace
3. Run:
```
cd test
go test -v github.com/gitpod-io/gitpod/test/tests/ide -kubeconfig=/home/gitpod/.kube/config -namespace=staging-jp-test-use-gp-code-server-test -username=your_username
```
```release-note
NONE
```
/werft with-helm

Use gp-code-server-test script

---

components/gitpod-db/src/typeorm/migration/1641287965022-DropDBPaymentSourceInfo.ts

Follow up for https://github.com/gitpod-io/gitpod/pull/7287
Fixes #
```release-note
NONE
```

[db] DROPT TABLE d_b_payment_source_info

---

components/supervisor/pkg/supervisor/user.go

fix addgroup \ adduser command not pair in some os, like `fedora`
Relate #7071
Create a [test repo](https://github.com/mustard-mh/test/tree/fedora) with files below and start a gitpod workspace
`.gitpod.yml`
```yaml
image:
file: .gitpod.Dockerfile
```
`.gitpod.Dockerfile`
```Dockerfile
FROM registry.fedoraproject.org/fedora:latest
```
```release-note
NONE
```

[supervisor] fix addgroup adduser command not pair

---

.werft/build.ts
.werft/post-process.sh
.werft/vm/manifests.ts

Fixes #
```release-note
NONE
```
NONE

Allow Ingress traffic for Gitpod when running on Harvester

---

components/server/src/config.ts
installer/pkg/components/server/configmap.go
installer/pkg/components/server/deployment.go

This should fix a mismatch of paths in telepresence mode. 
```release-note
NONE
```

Fix telepresence for server

---

WORKSPACE.yaml
components/ide/code/bin/code
components/ide/code/bin/gp-code
components/ide/code/bin/open
components/ide/code/leeway.Dockerfile
components/ide/code/startup.sh

There were some changes in the server part upstream so we need to update some paths that have changed
1. Open a workspace
2. Test cli commands e.g. `gp open`, `code folder/path`, etc are working
```release-note
NONE
```

[code] Address insiders changes

---

.werft/build.ts
.werft/post-process.sh
components/ws-daemon/pkg/content/initializer.go

Some post processing can be removed now that we're on K8s 1.21
n/a
Create preview environments with the installer
```release-note
NONE
```

[werft] support core-dev k8s 1.21

---

components/dashboard/src/projects/ConfigureProject.tsx
components/dashboard/src/projects/Projects.tsx

- Projects page grid columns breakpoints
- check `/projects` and `/projects/<some-project>/configure` page and scale down browser window
```release-note
NONE
```

Web responsiveness

---

OWNERS_ALIASES

True up aliases to match the current team members.
Add @kylos101 , @Furisto , and @utam0k 
Remove @MrSimonEmms (sorry amigo!)
Will add @sagor999 later, next week - no pressure to add "now". :smile: 
n/a
Can we approve workspace PRs? :)
```release-note
NONE
```

Update Team Workspace aliases

---

components/workspacekit/cmd/rings.go

Fixes #7696
```release-note
NONE
```
Edit: [context for the suggested change](https://gitpod.slack.com/archives/C02F19UUW6S/p1642618609068400?thread_ts=1642615433.067400&cid=C02F19UUW6S)

did not receive seccomp fd from ring2

---

components/docker-up/runc-facade/main.go

Drop the `kernel.domainname` as rootless container currently fail. If this does not work, consider using oci hooks.
- https://github.com/opencontainers/runc/issues/2091
- https://github.com/opencontainers/runtime-spec/issues/592
Relate #7440
This will work, but I'm not sure if it will work as expected by the issue reporter, so I'll leave it out of the fix.
Check that the following commands work on gitpod
```console
$ cd components/docker-up/runc-facade/
$ go build
$ sudo cp runc-facade /usr/bin/runc-facade
$ docker run --domanname "example.com" osixia/openldap:stable
```
```release-note
None
```
No

docker-up: drop the `kernel.domainname` as rootless container currently fail

---

CHANGELOG.md
License.third-party.npm.txt
components/dashboard/src/components/ConfirmationModal.tsx
components/ee/payment-endpoint/src/accounting/account-service.spec.db.ts
components/ee/payment-endpoint/src/accounting/subscription-service.spec.db.ts
components/gitpod-protocol/src/ide-frontend-service.ts
components/gitpod-protocol/src/util/gitpod-host-url.ts
components/server/ee/src/user/user-deletion-service.ts
components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/src/auth/generic-auth-provider.ts
components/server/src/auth/rate-limiter.ts
components/server/src/workspace/git-token-scope-guesser.ts
components/server/src/workspace/workspace-starter.ts

There were some u+00a0 characters in the codebase which could cause errors, I replaced them with regular space characters
Fixes #
```release-note
NONE
```

Use space character instead of u+00a0

---

components/gitpod-cli/cmd/credential-helper.go

Fixes #7702
1. Open preview env
2. Open this workspace https://github.com/jeanp413/test-gp-bug
3. Run `npm install`
4. Observe NO notification with this message appears `Unknown repository '' Please grant the necessary permissions.`
```release-note
NONE
```

credential-helper: validate parsed git command data

---

components/gitpod-cli/cmd/credential-helper.go

Continuation from https://github.com/gitpod-io/gitpod/pull/7735
Did a minor refactor so it's easier to add tests in the future for `parseGitCommandForOriginRemote`
Edit:
There was a regression in the original PR #7735, doing git operations like `git push` weren't working, I fixed it in this PR
Same steps as https://github.com/gitpod-io/gitpod/pull/7735
And run more git commands to ensure everything works fine, play with git permissions in dashboard/integrations
```release-note
NONE
```

credentialHelper minor refactor

---

components/server/ee/src/prebuilds/prebuilt-status-maintainer.ts

fixes #7794 as well as generally commit checks on PRs turning green too early.
Not testable with reasonable effort as it fixes an issue that only happens in production (maybe staging as well).
```release-note
NONE
```

[prebuilds] no update status for pending prebuild

---

components/server/src/express/ws-connection-handler.ts

Before, if we received the pong very quickly, and our subsequential check got delayed, we might have cancelled ws connections wrongly.
Fixes #
```release-note
NONE
```

[server] Fix case where we might close ws connections too frequently

---

OWNERS
OWNERS_ALIASES
components/content-service-api/OWNERS
components/dashboard/OWNERS
components/ee/db-sync/OWNERS
components/ee/kedge/OWNERS
components/ee/payment-endpoint/OWNERS
components/gitpod-db/OWNERS
components/gitpod-messagebus/OWNERS
components/gitpod-protocol/OWNERS
components/image-builder-api/OWNERS
components/licensor/OWNERS
components/local-app-api/OWNERS
components/proxy/OWNERS
components/registry-facade-api/OWNERS
components/server/OWNERS
components/service-waiter/OWNERS
components/supervisor-api/OWNERS
components/ws-daemon-api/OWNERS
components/ws-manager-api/OWNERS
components/ws-manager-bridge-api/OWNERS
components/ws-manager-bridge/OWNERS
installer/pkg/components/dashboard/OWNERS
installer/pkg/components/proxy/OWNERS
installer/pkg/components/server/OWNERS
installer/pkg/components/ws-manager-bridge/OWNERS
installer/pkg/config/versions/OWNERS
operations/observability/mixins/meta/OWNERS

[owners] rename team meta to webapp

---

.werft/vm/manifests.ts
.werft/vm/vm.ts
dev/preview/ssh-proxy-command.sh

(cherry picked from commit 6926c575f4485b4275cb151eeba0320c23347905)
I'm just opening a PR towards wulf's branch since he is busy with security issues.
I've tested it a couple of times and indeed solved the SSH problem. Thanks @iQQBot for taking care of it!
```release-note
NONE
```

Harvester: Change VM ssh port to resolve conflict with gateway

---

.gitpod.yml
.werft/build.yaml
.werft/debug.yaml
.werft/run-integration-tests.yaml
.werft/wipe-devstaging.yaml
dev/image/Dockerfile

Use newer workspace full image which does not contain postgresql chunk.
Fixes # none
NA
```release-note
None
```

Update base image for dev env and  dev-env tag

---

OWNERS_ALIASES

add `sagor999` to workspace team owner aliases
Fixes #
```release-note
none
```

add sagor999 to workspace team

---

installer/pkg/components/gitpod/configmap.go

This is useful for debugging purposes. As there is no longer anything sensitive in here, this is safe to add in
Deploy and get the config map
```release-note
NONE
```

[installer]: add the Installer config to a configmap for debugging

---

components/gitpod-cli/cmd/credential-helper.go
components/gitpod-cli/cmd/credential-helper_test.go

This PR has made many adjustments
1. Advance the get token operation so that the expected token is returned regardless of whether track or git-token-validator is in error
2. Modify the original repo match rule to make it compatible with non-origin remotes
3. ~~Some commands are not started by Git, such as `npm install`, which doesn't call git clone, but instead calls git's internal commands to download the repo, so we set the `git command` to `clone` to count and validator~~ Added `ls-remote` (used by npm) as valid command to be recognized
4. Fix `/proc/[pid]/stat` read problem (command maybe contain space)
Fixes #7702 
- Open a public git repository and try pushing some commit with and without permissions in the dashboard, if no permissions a popup should appear in vscode
- Open a …

Fix git credentials not work when git remote is not origin

---

OWNERS_ALIASES

add @felladrin as an owner of ide bits to enable PR reviews
Fixes #
```release-note
NONE
```

add felladrin to IDE team

---

.werft/post-process.sh

This PR disables the telemetry cron job for preview environments.
Verify that `spec.suspend` of the telemetry cronjob is set to `true`.
```release-note
NONE
```

[werft] Disable telemetry job for preview environments

---

.werft/build.ts

We've always had trace spans for the VM phase, but we don't close them correctly. This PRs just closes all spans at the right time.
You can see the difference in:
* [A trace without closing spans](https://ui.honeycomb.io/gitpod/datasets/werft/result/g3fbJ1RnsjR/trace/GpfcXDkBkKB?span=f5afbf02369a0235)
* [A trace from this PR, which closes spans](https://ui.honeycomb.io/gitpod/datasets/werft/result/txg3SBVddiZ/trace/hCYE53gx18q?span=58297105af92dc9c)
Please pay attention in the `VM` phase
Fixes https://github.com/gitpod-io/ops/issues/639
Start a job and check the trace in honeycomb
PS: We should add the honeycomb trace URL as one of the Werft results 🤔 
```release-note
NONE
```

werft: Close slice spans

---

components/gitpod-db/src/typeorm/entity/db-prebuilt-workspace-updatable.ts
components/gitpod-db/src/typeorm/migration/1643879235654-PWSUIndexes.ts

Fixes #7997
```release-note
NONE
```

[db] Add index for all queries on DBPrebuildWorkspaceUpdatable

---

components/docker-up/docker-up/main.go

Fix typo in assignment introduced in https://github.com/gitpod-io/gitpod/pull/7989
Fixes #
```release-note
none
```

fix typo in assignment

---

.github/workflows/code-nightly.yaml

Temporarily pin insiders to stable branch
Fixes #
```release-note
NONE
```

Temporarily pin insiders to stable branch

---

operations/observability/mixins/workspace/dashboards.libsonnet
operations/observability/mixins/workspace/dashboards/coredns.json

Fixes #7826 
```release-note
none
```

add coredns dashboard

---

.gitpod.yml

remove not exist components gateway-plugin:plugin
Fixes #8022 
```release-note
NONE
```

remove not exist components gateway-plugin:plugin

---

components/server/src/workspace/headless-log-controller.ts

Replaces single usage of `nextTicket` with `setImmediate`
Fixes #
```release-note
NONE
```

[server] Replace nextTick with setImmediate

---

.github/workflows/code-nightly.yaml

Fixes #
```release-note
NONE
```

Point code nightly job back to main

---

operations/observability/mixins/cross-teams/rules/components/nodes/alerts.libsonnet

Fixes this issue: https://github.com/gitpod-io/ops/issues/928
```release-note
none
```

add alert for conntrack table getting full

---

.github/workflows/jetbrains-updates-template.yml

[jetbrains] label release update PRs with IDE label
Fixes #8026
https://github.com/peter-evans/create-pull-request#action-inputs
see this input value for detail
```release-note
NONE
```

[jetbrains] label release update PRs with IDE label

---

.werft/build.ts

Gracefully exit on deployment errors in main branch
Fixes https://github.com/gitpod-io/ops/issues/947
Well, this one is kinda hard to test since it needs to be run from the `main` branch
```release-note
NONE
```

Werft: Don't fail main jobs for failed deployments

---

components/gitpod-cli/cmd/credential-helper.go
components/gitpod-cli/cmd/credential-helper_test.go
components/gitpod-cli/go.mod
components/gitpod-cli/go.sum

Debt from previous PR https://github.com/gitpod-io/gitpod/pull/7889#discussion_r797290160
Fixes #
Follow smoke test steps: 
- Open a public git repository and try pushing some commit with and without permissions in the dashboard, if no permissions a popup should appear in vscode
- Open a private git repository and try pushing some commit with and without permissions in the dashboard, if no permissions a popup should appear in vscode
- Private npm package
- Create a private git repository for an npm package e.g https://github.com/jeanp413/test-private-package
- Start a workspace, then run `npm install github:jeanp413/test-private-package` with and without permissions in the dashboard
- Private npm package no access
- Open this workspace https://github.com/jeanp413/test-gp-bug and run `npm …

Use procfs library for reading proc files

---

components/server/src/workspace/workspace-starter.ts
components/supervisor/pkg/supervisor/config.go
components/supervisor/pkg/supervisor/ssh.go
components/supervisor/pkg/supervisor/supervisor.go
components/supervisor/pkg/supervisor/supervisor_test.go

Reverts gitpod-io/gitpod#8082
And provides a fix for the issue with Env Var injection.
```release-note
NONE
```

Revert "Revert "Ship env vars as one-time secret""

---

components/ws-manager/pkg/manager/status.go
components/ws-manager/pkg/manager/testdata/status_disposal_STOPPED01.golden

Removes unnecessary log message.
Fixes #8154 
```release-note
none
```

remove contact support message

---

components/supervisor/cmd/init.go

This PR fixes the shutdown behaviour of `supervisor init`:
- `os.Notify` is very particular about the number of times it can be called. Prior to this change we called it twice which did not result in the expected signalling behaviour.
- The `supervisor run` wait group `Done()` call was not deferred, which could lead to situations where the waitgroup was never done and `init ` would not return.
1. Run a prebuild with very fast task
```release-note
NONE
```

[supervisor] Improve init shutdown behaviour

---

components/supervisor/pkg/supervisor/supervisor.go

Fix panic if ssh server failed to start
Related issue: #7754 
```release-note
none
```

fix panic if ssh server failed to start

---

components/ide/jetbrains/backend-plugin/README.md
components/ide/jetbrains/backend-plugin/src/main/kotlin/io/gitpod/jetbrains/remote/GitpodManager.kt
components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/auth/GitpodAuthService.kt
components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt
components/ide/jetbrains/image/status/main.go

This PR enables development/debug of JB backend plugin against running workspace.
Fixes #
- Install plugin in your Gateway: https://plugins.jetbrains.com/plugin/download?rel=true&updateId=158516
- Restart Gateway to apply it!
- Start a workspace for this PR from prev envs with IntelliJ: https://ak-jb-backend-debug-flow.staging.gitpod-dev.com/#referrer:jetbrains-gateway/https://github.com/gitpod-io/gitpod/pull/8239
- Follow and ensure that you can debug: https://github.com/gitpod-io/gitpod/tree/ak/jb_backend_debug_flow/components/ide/jetbrains/backend-plugin#development
- For instance put a breakpoint in hearbeating loop.
```release-note
NONE
```

jb: enable debug flow for backend plugin

---

components/ws-manager-bridge/src/bridge.ts
components/ws-manager-bridge/src/container-module.ts
components/ws-manager-bridge/src/preparing-update-emulator.ts

Follow-up fix for #7523
Fixes #
```release-note
none
```

[bridge] Fix PreparingUpdateEmulator initialization

---

operations/observability/mixins/workspace/rules/components/ws-daemon/alerts.libsonnet

Update runbook url for GitpodWsDaemonExcessiveGC alert
Fixes https://github.com/gitpod-io/runbooks/issues/317
Depends on PR https://github.com/gitpod-io/runbooks/pull/326
NA
```release-note
None
```

Update runbook url for GitpodWsDaemonExcessiveGC

---

.github/workflows/code-nightly.yaml

Update code nightly action
Fixes #
```release-note
NONE
```

Update code nightly action

---

.werft/vm/manifests.ts

Updates Harvester VM image
Fixes #
```release-note
NONE
```

werft/vm: Update image

---

.github/workflows/code-nightly.yaml

revert nightly job to gp-code/main
Fixes #
```release-note
NONE
```

[code] revert code nightly to gp-code main

---

.werft/jobs/build/deploy-to-preview-environment.ts

Wait until k3s ApiServer is ready before we interact with k3s.
Fixes # https://github.com/gitpod-io/gitpod/issues/8680
```release-note
NONE
```

Wait until k3s apiserver is ready

---

.werft/jobs/build/deploy-to-preview-environment.ts
.werft/util/kubectl.ts

This PR superseeds https://github.com/gitpod-io/gitpod/pull/8705 and https://github.com/gitpod-io/gitpod/pull/8696
```release-note
NONE
```

werft/previews: Wait for k3s readiness before installing gitpod

---

install/installer/README.md

Updating the Installer README to include a small note on what each `InstallationKind` signifies
NA
NA
```release-note
NONE
```
No

[installer] explain `InstallerKind` in README

---

components/server/ee/src/prebuilds/prebuild-manager.ts

Lint/fixing the file, will be used in https://github.com/gitpod-io/gitpod/pull/8767
```release-note
NONE
```

[server] Lint/fix prebuild-manager.ts

---

components/server/src/github/api.ts

Fixes #7307 
```release-note
fix caching of GitHub server<->server queries
```

Fix caching of GitHub queries

---

dev/loadgen/prod-benchmark.yaml

Use more recent builds
```release-note
[loadgen] Update benchmark images
```

[loadgen] Update benchmark yaml

---

test/tests/ide/vscode/python_ws_test.go

Update python-test-workspace repo in IDE test, python-test-workspace has been moved to gitpod-io
I also enabled prebuilds in the repo but it seems it's failing due to a bug
So maybe we can just merge it and test it on main and check if it works, if not I will revert the prebuild changes so the test pass again
cc @iQQBot 
```release-note
NONE
```

Update python-test-workspace repo in ide test

---

components/ee/agent-smith/pkg/agent/agent.go

The go map does not allow concurrent access i.e. both read and write. So, take lock in the following scenarios:
1. Before reading an entry from the map
2. Before ranging over the map
3. Before updating an entry in the map
Since both process classification and egress checks are performed in the same go routine, repeated locking attempt before reading will cause a delay in execution of classification method.
The contention impact on performance can be evaluated when this runs in production.
Fixes https://github.com/gitpod-io/gitpod/issues/8843
NA
```release-note
None
```

[agent-smith] lock workspaces map before read

---

.gitpod.yml
.werft/build.yaml
.werft/debug.yaml
.werft/platform-clean-up-werft-build-nodes.yaml
.werft/platform-delete-preview-environments-cron.yaml
.werft/run-integration-tests.yaml
.werft/wipe-devstaging.yaml
dev/image/Dockerfile

Update Dockerfile to use newer version of tools
Fixes NA
Build should succeed.
```release-note
None
```

[dev] Update Dockerfile

---

components/gitpod-db/src/typeorm/workspace-db-impl.ts

Fixes #
```release-note
fix findPrebuildsWithWorkpace query
```

[db] Fix findPrebuildsWithWorkpace

---

dev/kubecdl/main.go

Fixes #
```release-note
NONE
```

[kubecdl] Fix instance filter

---

.github/workflows/code-nightly.yaml
WORKSPACE.yaml

point code nightly to gp-code main release 1.66
n/a
```release-note
NONE
```

[code] point code nightly to gp-code main release 1.66

---

install/kots/manifests/kots-preflight.yaml

Currently, this only checks that it's not OpenShift. This may be expanded in future
Fixes #8864 
```release-note
[kots]: add distribution check to the KOTS preflights
```

[kots]: add distribution check to the KOTS preflights

---

.github/CODEOWNERS

API changes are architecturally significant, uncertainty should be discussed with @aledbf or @csweichel before proceeding.
We'll update more Workspace components later, as teammates gain related proficiency.
Fixes #8981
After this is merged to main, submit a change to `ws-manager-api` or `ws-daemon-api`.
```release-note
NONE
```

Change reviewers for some workspace components

---

components/ws-manager-bridge/ee/src/bridge.ts

Needed to further diagnose issues which led to revert of https://github.com/gitpod-io/gitpod/pull/9148
1. Run a prebuild
2. ws-manager-bridge prints extra logs
```release-note
NONE
```

[ws-manager-bridge] Log handling of prebuild update events

---

components/dashboard/src/App.tsx
components/dashboard/src/Menu.tsx
components/dashboard/src/index.tsx
components/dashboard/src/payment-context.tsx
components/dashboard/src/settings/Account.tsx
components/dashboard/src/settings/EnvironmentVariables.tsx
components/dashboard/src/settings/Integrations.tsx
components/dashboard/src/settings/Notifications.tsx
components/dashboard/src/settings/Plans.tsx
components/dashboard/src/settings/Preferences.tsx
components/dashboard/src/settings/Teams.tsx
components/dashboard/src/settings/settings-menu.ts

| Without Payment | With Payment |
| --- | --- |
| <img width="1436" alt="Screenshot 2022-03-31 at 16 44 20" src="https://user-images.githubusercontent.com/599268/161087252-447e9333-bcae-4b79-9764-9731a980013e.png"> | <img width="1439" alt="Screenshot 2022-04-01 at 11 16 59" src="https://user-images.githubusercontent.com/599268/161234507-87da9409-022b-4709-85d4-b6666e55503e.png"> |
_Side-note: The dynamic menu does cause [a bit of layout-shifting](https://youtu.be/eWwJk4KHbI0) specifically when refreshing Settings pages, but that should be fine as refreshing Settings is not a common user behavior._
Fixes https://github.com/gitpod-io/gitpod/issues/8916
1. Have payments disabled (default for Werft deployments)
2. Open `/settings` -- the menu items `Plans` and `Teams` should **not** be …

[dashboard] Implement a PaymentContext and use it to hide payment features when payment is disabled

---

WORKSPACE.yaml

Update code to 1.66.1
Related https://github.com/gitpod-io/gitpod/issues/9020
- that user data is synced across workspaces as well as on workspace restart, especially for extensions
```release-note
NONE
```

[code] Build stable image for 1.66.1

---

.gitpod.yml
scripts/goland-indexing.sh

This PR enables indexing with GoLand in prebuilds.
Fixes #
- Enable GoLand in settings: gitpod.io/preferences
- Start a workspace on this branch and check that indexing is already done: https://gitpod.io#https://github.com/gitpod-io/gitpod/pull/9193
```release-note
NONE
```

enable indexing with GoLand in prebuilds

---

components/common-go/kubernetes/probes.go
components/registry-facade-api/go/config/config.go
components/registry-facade/cmd/run.go
components/registry-facade/pkg/registry/blob.go
components/registry-facade/pkg/registry/cache.go
components/registry-facade/pkg/registry/cache_test.go
components/registry-facade/pkg/registry/manifest.go
components/registry-facade/pkg/registry/registry.go
install/installer/pkg/components/registry-facade/configmap.go
install/installer/pkg/components/registry-facade/daemonset.go
install/installer/pkg/config/v1/experimental/experimental.go
install/installer/pkg/config/v1/experimental/validation.go

Fixes #
```release-note
[registry-facade] Revert removal of DisableKeepAlives
[registry-facade] Check redis connection on start
[registry-facade] Separate Redis manifest cache from IPFS
[registry-facade] Check if the keys exist and use MULTI
[registry-facade] Use sync.Pool as buffer
Include error in probe log
```

[registry-facade] Refactoring

---

.github/CODEOWNERS
components/public-api-server/RAEDME.md

Initial component setup for public api server
Relates to https://github.com/gitpod-io/gitpod/issues/9229
CI runs
```release-note
NONE
```

Setup component (and dir) for public API server

---

README.md

Update Readme Header's elements alignment.
<table>
<thead>
<tr>
<td>Before</td>
<td>After</td>
</tr>
</thead>
<tbody>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
NONE
Open [the README.md file from this PR in Github](https://github.com/gitpod-io/gitpod/blob/update-readme-header/README.md), to preview the new Readme Header. It should be like in the screenshot above.
```release-note
NONE
```
NONE

Update Readme Header's elements alignment

---

components/public-api-server/main.go

Run a tiny server which serves something, so we can try to deploy it and hit the endpoint.
Relates to #9229 
`cd components/public-api-server && go run main.go`
`curl localhost:9000`
`> hello world`
```release-note
NONE
```
NONE

[public-api-server] Serve a hello world over http

---

components/gitpod-db/src/auth-provider-entry-db.ts
components/gitpod-db/src/auth-provider-entry.spec.db.ts
components/gitpod-db/src/typeorm/auth-provider-entry-db-impl.ts
components/server/ee/src/prebuilds/bitbucket-app.ts
components/server/ee/src/prebuilds/bitbucket-server-app.ts
components/server/ee/src/prebuilds/github-app.ts
components/server/ee/src/prebuilds/github-enterprise-app.ts
components/server/ee/src/prebuilds/gitlab-app.ts
components/server/src/auth/auth-provider-service.ts
components/server/src/auth/authenticator.ts
components/server/src/auth/generic-auth-provider.ts
components/server/src/auth/host-context-provider-impl.ts
components/server/src/bitbucket-server/bitbucket-server-auth-provider.ts
components/server/src/bitbucket/bitbucket-auth-provider.ts
components/server/src/express/ws-connection-handler.ts
components/server/src/express/ws-layer.ts
components/server/src/github/github-auth-provider.ts

This PR fixes two things:
1. it resolves an issue with dynamic auth providers being initialized in a 2s loop, if `host` attribute stored in DB is not lower case. DB test included.
2. it also sanitizes log statements including big/unwanted/boring objects as payload to be serialized, thus pulling down performance of server.
1. Create a Git Integration with garbage details, the only thing of interest is that the host should contain upper case char. 
2. Check debug logs to not include sequences of {initializing provider1, disposing provider1}
```release-note
NONE
```

Fix memory leak in server

---

components/ws-daemon/pkg/iws/iws.go

to make the new nftables setup work
```release-note
NONE
```

[ws-daemon] Enable workspace IP forwarding

---

components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go

Prior to this change we'd set `io.max` only once. This is problematic for two reasons:
- we might not have interacted with all disks yet, because we're essentially racing workspacekit.
- the user might create new devices for which we'll want to impose IO limits, too (thanks @utam0k for pointing this out).
This PR re-writes the IO limits every 30 seconds.
- Run ws-daemon with IO limits enabled. Observe that all devices are eventually subject to `io.max` entries
```release-note
NONE
```

[ws-daemon] Apply IO limits continuosly

---

install/installer/pkg/components/server/deployment.go
install/installer/pkg/components/ws-manager-bridge/deployment.go

Fixes #
```release-note
none
```

[installer] Add missing ports to server, ws-manager-bridge

---

components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go

Add additional logging for io limiting
n.a.
n.a.
```release-note
None
```

Add additional logging for io limiting

---

components/supervisor/pkg/supervisor/tasks.go
components/supervisor/pkg/terminal/terminal.go

Server listen to task terminals via supervisor API to stream logs in prebuilds page. But in headless terminals we disable timeouts for reading, so if a server misbehaving, i.e. slow to read or leak stream, then tasks get stale and never finish.
This PR is unblocking by making sure that such clients have only 5s otherwise they got dropped, but only supervisor itself is blocking to read all output.
Fixes #
- https://ak-unblockc0f5112798.staging.gitpod-dev.com#prebuild/https://github.com/gitpod-io/spring-petclinic/pull/59
- You should see the prebuild page and it should finish within 15 mins and open a workspace from prebuild.
```release-note
NONE
```

[supervisor] prevent slow clients to stale tasks in headless workspaces

---

install/installer/pkg/components/openvsx-proxy/statefulset.go

Should assign to
https://github.com/gitpod-io/gitpod/blob/37435335ae86eef44eb9fee7f53f62b7e156c8e1/chart/templates/openvsx-proxy-statefulset.yaml#L78-L90
Fixes #
See if preview env openvsx-proxy started
```release-note
NONE
```

[installer] fix redis pvc name incorrect

---

components/ws-daemon/pkg/cpulimit/cpulimit.go
components/ws-daemon/pkg/cpulimit/dispatch.go

Reverts gitpod-io/gitpod#8459
```release-note
Revert "[ws-daemon] Fix CPU limit annotation"
```

Revert "[ws-daemon] Fix CPU limit annotation"

---

.werft/jobs/build/prepare.ts
.werft/vm/manifests.ts

In #9391 We introduce a way to use RouterOS to relay traffic to access the harvester internal sub-network
While the current solution is based on RouterOS we’re now evaluating if we want to have this in our tech stack in the long term or move to another routing/tunneling solution. 
This PR use `kubectl port-forward` to replace RouterOS
It has the following benefits
- the addition to our tech stack is very minimal
- we don’t need an additional `RouterOS` / `publicIP` on the Harvester side
- we don’t need an additional `vpc router` / `RouterOS` on the GCP side
Fixes #
1. run werft job in `this PR` or `create a new branch base on this PR`
2. start a workspace, check ssh gateway is work
```release-note
NONE
```

[werft] change routeros to kubectl port-forward

---

components/server/src/workspace/gitpod-server-impl.ts

Adds prioritization to suggested repo URLs in new workspace modal, so that new users get their own
repositories suggested before the generic templates.
Login in and start a workspace through the new workspace modal.
You should find your own repositories listed above the gitpod templates.
```release-note
NONE
```

[server] Add priorization to repo URLs

---

components/ws-manager-bridge/src/bridge.ts

Adds inline documentation for the next poor soul that goes to investigate this.
None
```release-note
NONE
```
NONE

[ws-man-bridge] Document when unknown workspace instance occurs

---

components/public-api-server/integration_test.go

Semantic merge between https://github.com/gitpod-io/gitpod/commit/11f21809a61aa8e2319dbe7d12b06b1df5ea23ab and https://github.com/gitpod-io/gitpod/commit/a0d5559ae9f98aae4635861dfe26bfcb72ade7ef
Fixes CI on main
Unit tests, CI passes
```release-note
NONE
```
NONE

[public-api] Fix semantic merge

---

components/ws-manager-bridge/ee/src/container-module.ts
components/ws-manager-bridge/ee/src/index.ts
components/ws-manager-bridge/src/bridge-controller.ts
components/ws-manager-bridge/src/cluster-service-server.ts
components/ws-manager-bridge/src/config.ts
components/ws-manager-bridge/src/container-module.ts
components/ws-manager-bridge/src/index.ts
components/ws-manager-bridge/src/main.ts
components/ws-manager-bridge/src/messagebus-integration.ts
components/ws-manager-bridge/src/meta-instance-controller.ts
components/ws-manager-bridge/src/preparing-update-emulator.ts
components/ws-manager-bridge/src/prometheus-metrics-exporter.ts
components/ws-manager-bridge/src/wsman-subscriber.ts

Ran `pre-commit run --files components/ws-manager-bridge/**/*.ts` with bash expansion. Contains no logic changes.
Fixes #
CI passes
```release-note
NONE
```
NONE

[wsman-bridge] Lint typescript files

---

components/server/ee/src/prebuilds/github-service.ts

Follow-up to https://github.com/gitpod-io/gitpod/pull/9231: Map GitHub API repositories during pagination, not after.
Fixes https://github.com/gitpod-io/gitpod/issues/9461
1. Without adding a GitHub App, you should still be able to add Projects and run Prebuilds
```release-note
[server] Optimization: Map GitHub API repositories during pagination, not after
```

[server] Optimization: Map GitHub API repositories during pagination, not after

---

components/server/src/workspace/workspace-starter.ts

Add more context for logging
```release-note
NONE
```

[server] enhance log message for image build

---

install/installer/pkg/components/public-api-server/deployment.go

* Depends on https://github.com/gitpod-io/gitpod/pull/9319
* Part of https://github.com/gitpod-io/gitpod/issues/9229
* navigate to `api.<preview-env-url>` and it should continue to work
```release-note
NONE
```
NONE

[public-api] Use /ready and /live for probes

---

components/ws-daemon/pkg/cgroup/plugin_iolimit_v1.go

Remove useless log https://cloudlogging.app.goo.gl/YcGHidiz6YFSa8T58
```release-note
[ws-daemon] Check blkio throttle exists
```

[ws-daemon] Check blkio throttle exists

---

components/ws-manager-bridge/src/prometheus-metrics-exporter.ts

Missed this in https://github.com/gitpod-io/gitpod/pull/9422
Fixes #
Compiles
```release-note
NONE
```
NONE

[ws-manager-bridge] Fix workspace instance update started total metric incrementing

---

components/common-go/baseserver/server.go

Fixes #
```release-note
NONE
```
NONE

[baseserver] Fix log typo to show correct port

---

WORKSPACE.yaml

Minor change to `Export all logs` command category
https://github.com/gitpod-io/openvscode-server/commit/bf3c9e080df9c63500d99f4f47ff0f3a289260dd
1. Select insiders
2. Open workspace
3. Open command palette and search for `Export all logs` check its `Gitpod: Export all logs`
```release-note
NONE
```

[code] Update vscode 1.66.2

---

chart/values.yaml
install/installer/pkg/components/workspace/ide/constants.go

Update vscode stable image
Tested in https://github.com/gitpod-io/gitpod/pull/9587
```release-note
NONE
```

Update vscode stable 1.66.2

---

scripts/ws-deploy.sh

Slightly improves the recent devloop script for workspace components.
It ensures that we're guaranteed pull the image by setting the `imagePullPolicy`, and it uses the actually generated name of the image which makes the script more robust because fewer assumptions need to be made.
```release-note
NONE
```

[workspaces] Improve dev loop script

---

components/registry-facade/pkg/registry/cache.go

```release-note
[registry-facade] Improve redis error messages
```

[registry-facade] Improve redis error messages

---

components/common-go/grpc/grpc.go

* Ensures that handler panics are turned into meaningful (Internal Error) rpc responses
* Uses https://github.com/grpc-ecosystem/go-grpc-middleware
```release-note
NONE
```
NONE

[grpc] Add recovery interceptor to default interceptors

---

components/public-api-server/RAEDME.md
components/public-api-server/README.md

Add more detail to component readme, so we can start sharing more about the direction and current state of the API.
* Fixes naming of the readme file
None
```release-note
NONE
```
NONE

[public-api] Extend readme with more information about the package

---

chart/templates/ws-manager-configmap.yaml

Fixes the #@*% helm charts.
```release-note
NONE
```
/werft without-vm=true
/werft with-helm=true

[helm] Fix ws-manager configmap

---

components/ws-daemon/pkg/config/config.go

Do not swallow config errors
n.a.
n.a.
```release-note
None
```

Do not swallow config errors

---

components/docker-up/BUILD.yaml

```release-note
[docker-up] Update docker compose to 2.5.0
```

[docker-up] Update docker compose to 2.5.0

---

.github/workflows/code-nightly.yaml

Point code nightly to gp-code/release/1.67 branch
related https://github.com/gitpod-io/gitpod/issues/9667
```release-note
NONE
```

[code] point code nightly to gp-code/release/1.67 branch

---

components/blobserve/go.mod
components/blobserve/go.sum
components/registry-facade/go.mod
components/registry-facade/go.sum
components/registry-facade/pkg/registry/cache.go
install/installer/go.mod
install/installer/go.sum

Adjust options to improve deduplication and use of faster FileStore
```release-note
[registry-facade] Adjust IPFS client Add options
```

[registry-facade] Adjust IPFS client Add options

---

components/public-api-server/main.go
components/public-api-server/pkg/server/integration_test.go
components/public-api-server/pkg/server/server.go

* This is pre-requisite work to do the following:
* Specify configuration and parse it before starting the server
* Be able to inject version into the server similar to how other components do it
* Part of https://github.com/gitpod-io/gitpod/issues/9229
CI works
```release-note
NONE
```
NONE

[public-api] Restructure packages to better align with other components

---

dev/installer-diff/cmd/filter.go

This PR fine-tunes the installer-diff tool to reduce noise by:
- filtering out unwanted objects
- renames certain objects to for easier diffing
- sorts Service ports by name
Fixes #
```release-note
NONE
```

[installer-diff] Filter out unwanted objects, and reduce noise

---

components/registry-facade/pkg/registry/cache.go

```release-note
[content-service] Add logs for Redis pipeline errors
```

[content-service] Add logs for Redis pipeline errors

---

.github/workflows/code-nightly.yaml

Point code nightly back to gp-code/main branch
```release-note
NONE
```

[code] point code nightly back to gp-code/main branch

---

.pre-commit-config.yaml

See https://pre-commit.com/hooks.html
Build runs
```release-note
NONE
```
NONE

[pre-commit] Ensure a file is either empty, or ends with one newline

---

components/ws-manager/pkg/manager/manager.go

While we are waiting for the workspace to come up, the context can time out which means the removal of the finalizer will fail. Instead use a seperate context for deletion of the workspace.
```
{
insertId: "36gpzslgv8uop3jn"
jsonPayload: {
@type: "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent"
error: "context canceled"
instanceId: "<redacted>"
level: "error"
message: "was unable to remove finalizer"
pod.Name: "<redacted>"
pod.Namespace: "default"
serviceContext: {2}
userId: "<redacted>"
workspaceId: "<redacted>"
}
labels: {1}
logName: "projects/workspace-clusters/logs/stderr"
receiveTimestamp: "2022-05-06T08:27:22.832122356Z"
resource: {2}
severity: "ERROR"
timestamp: "2022-05-06T08:27:21Z"
}
```
n.a.
n.a.
```release-note
Ensure workspace can be …
```

Ensure workspace can be deleted even if context timed out

---

components/ws-manager-bridge/src/bridge-controller.ts

Fixes unnecessary bloated logging.
Fixes #
- look at ws-manager-bridge, and grep for "done reconciling."
- note how "allClusters" only contains names
```release-note
NONE
```

[bridge] Fix logging

---

components/dashboard/src/components/PrebuildLogs.tsx

This PR attempts to fix endless `getHeadlessLog` from the PrebuildLogs component.
FIxes #9935
```release-notes
NONE
```

[dashboard] fixing backoff for getHeadlessLog calls

---

.github/workflows/jetbrains-updates-template.yml
.github/workflows/jetbrains-updates.yml

Improving the "how-to-test" section
|--------|-------|
|    <img width="823" alt="Screenshot 2022-05-13 at 14 27 42" src="https://user-images.githubusercontent.com/2318450/168282988-240b53de-1280-4cee-b8e3-e42797d09485.png">    |     <img width="823" alt="Screenshot 2022-05-13 at 14 26 16" src="https://user-images.githubusercontent.com/2318450/168282855-a004b371-a0a5-474c-bd6a-f09450e03226.png"> |
```release-note
NONE
```

Improve automated PR description for JetBrains auto-update

---

components/workspacekit/cmd/rings.go

workspacekit: Record the errors of connecting to ws-daemon
Relates: #9673
Open a workspace
```release-note
None
```
No

workspacekit: Record the errors of connecting to ws-daemon

---

components/ws-daemon/pkg/daemon/daemon.go

this call can block indefinitely:
https://github.com/gitpod-io/gitpod/blob/82665f4bd481a75723037719e83bd097ddde00b8/components/ws-daemon/pkg/daemon/daemon.go#L215
This just makes sure that it will not hang forever on that call if it happens.
I don't think it is a root cause of the #10081, but I think it will not hurt to have a timeout here.
```release-note
none
```

[ws-daemon] ensure readyiness probe will not block indefinetely

---

components/workspacekit/pkg/seccomp/notify.go

Relates #10108
```release-note
seccomp notify: correction of system call name in the log.
```
No

seccomp notify: correction of system call name in the log.

---

.github/workflows/code-nightly.yaml
.github/workflows/jetbrains-auto-update-template.yml

Bump workflows dependencies' version to assign to production. This will fix Nightly job
Fixes #
Run Github Action with `Code Nightly` or `JB Nightly`
See also 
- Code Nightly result https://github.com/gitpod-io/gitpod/runs/6504414219?check_suite_focus=true
- JB Nightly result https://github.com/gitpod-io/gitpod/actions/runs/2351159077 thanks @iQQBot 
```release-note
NONE
```

Bump workflows dependencies' version

---

WORKSPACE.yaml

Picks up https://github.com/gitpod-io/openvscode-server/commit/9501728f63e11002972752ad59bd543ba22a2e87
```release-note
NONE
```

[code] Build stable image

---

install/installer/pkg/components/workspace/ide/constants.go

Continuation from https://github.com/gitpod-io/gitpod/pull/10196
```release-note
NONE
```

[code] Update stable image

---

components/ws-manager/pkg/manager/monitor.go

https://gitpod.slack.com/archives/C01KLC56NP7/p1653509837991769
```release-note
[ws-manager] Check the pod contains a workspace class and exists
```

[ws-manager] Check the pod contains a workspace class and exists

---

components/registry-facade/pkg/registry/resolver.go

Remove expirations from Redis
```release-note
[registry-facade] Remove Redis expiration from resolve
```

[registry-facade] Remove Redis expiration from resolve

---

components/dashboard/src/workspaces/Workspaces.tsx

Remove a noisy `console.log` from the dashboard.
None
```release-note
NONE
```

Remove `console.log` statement

---

components/content-service/pkg/archive/tar.go

Do not try to restore trusted attributes and filter error logs
xref: https://github.com/gitpod-io/gitpod/issues/10108
```release-note
[content-service] Improve restoration of extended attributes
```

[content-service] Improve restoration of extended attributes

---

components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnector.kt

Added connector's name for the statistics
https://youtrack.jetbrains.com/issue/CWM-6256
```release-note
NONE
```

getConnectorId implementation added to GitpodConnector

---

components/supervisor/pkg/supervisor/user.go
components/supervisor/pkg/supervisor/user_test.go

[supervisor] improve error message around user group and uid
Fixes #
```release-note
[supervisor] improve error message around user group and uid
```

[supervisor] improve error message around user group and uid

---

.gitpod.yml
.werft/build.yaml
.werft/debug.yaml
.werft/ide-integration-tests-startup-jetbrains.yaml
.werft/ide-integration-tests-startup-vscode.yaml
.werft/ide-run-integration-tests.yaml
.werft/platform-delete-preview-environments-cron.yaml
.werft/platform-trigger-werft-cleanup.yaml
.werft/run-integration-tests.yaml
.werft/wipe-devstaging.yaml
.werft/workspace-run-integration-tests.yaml
dev/image/Dockerfile

Context: https://gitpod.slack.com/archives/C01KGM9AW4W/p1654025762967629
Fixes #
```release-note
NONE
```

Remove X-Server from Dev-Image

---

components/docker-up/BUILD.yaml

Ensure the download of docker-compose is correct
- Check `docker-compose` binary is valid
```release-note
[docker-up] Check docker-compose download
```

[docker-up] Check docker-compose download

---

components/usage/pkg/db/conn.go

Bind our standard logging into Gorm to ensure logs are consistent.
Fixes #
Unit tests (also run on CI)
See the log output from the tests, optionally compare to logs on main
```release-note
NONE
```
NONE

[usage] Log db with standard logger

---

components/usage/cmd/run.go
components/usage/go.mod
components/usage/pkg/controller/reconciler.go
components/usage/pkg/db/conn_test.go
components/usage/pkg/db/workspace_instance.go
components/usage/pkg/db/workspace_instance_test.go

* Setup a new reconciler which initially only lists workspace instances in a given period.
* On default runs, it lists instances for the current month
* Initially, outputs number of records found - in subsequent PRs we'll be adding more logic
* Adds a method to list instances in range (and corresponding unit tests with DB for this logic)
Components prints the following:
```
{"level":"info","message":"Gathering usage data from 2022-06-01 00:00:00 +0000 UTC to 2022-07-01 00:00:00 +0000 UTC","serviceContext":{"service":"usage","version":"commit-198841c5fc34130a0d8b414302f618f5e570f26b"},"severity":"INFO","time":"2022-06-06T08:28:26Z"}
{"level":"info","message":"Identified 1 instances between 2022-06-01 00:00:00 +0000 UTC and 2022-07-01 00:00:00 +0000 …
```

[usage] List workspace instances

---

.werft/platform-delete-preview-environments-cron.ts

Reverts gitpod-io/gitpod#10498

Revert "Always keep preview envs on db activity"

---

components/gitpod-protocol/src/messaging/error.ts
components/server/ee/src/workspace/gitpod-server-impl.ts
components/server/src/websocket/websocket-connection-manager.ts

Refactor hard-coded `ResponseError(500, msg)` --> `ResponseError(ErrorCodes.INTERNAL_SERVER_ERROR, msg)`
Fixes https://github.com/gitpod-io/gitpod/pull/10378#discussion_r892048343
- Should build
```release-note
NONE
```

[server] Introduce and use a ErrorCodes.INTERNAL_SERVER_ERROR

---

components/usage/pkg/controller/reconciler.go
components/usage/pkg/controller/reconciler_test.go
components/usage/pkg/db/workspace_instance.go

Generate a usage report in the reconciler.
Broader unit tests will be added in subsequent PR, to enable getting this into staging sooner and perform first pass validation.
Fixes #
Unit tests
```release-note
NONE
```
NONE

[usage] Generate usage report

---

.werft/jobs/build/prepare.ts

Self-explanatory
Fixes https://github.com/gitpod-io/ops/issues/2727
```release-note
NONE
```

werft/build: Rename created_vm span attribute

---

.github/workflows/code-nightly.yaml

Point code nightly to gp-code/main branch
https://github.com/gitpod-io/gitpod/issues/10487
```release-note
NONE
```

[code] point code nightly to gp-code/main branch

---

operations/observability/mixins/IDE/dashboards/components/jb.json

Fixes #
```release-note
NONE
```

[jb] fix dashboard

---

components/gitpod-cli/cmd/timeout.go

Update description of `gp timeout`
Fixes #
```release-note
Update description of `gp timeout`
```

[gp-cli] update timeout description

---

components/gitpod-protocol/package.json
yarn.lock

Update gitpod-protocol dependencies, most importantly `vscode-uri` as it was really old and was giving some package dependency issues in our fork of vscode
```release-note
NONE
```

Update gitpod-protocol deps

---

components/usage/pkg/db/conn.go

Fixes werft not being happy with logs. [Details (internal)](https://gitpod.slack.com/archives/C02EN94AEPL/p1655887916284179?thread_ts=1655881072.548939&cid=C02EN94AEPL)
Fixes #
Unit tests
```release-note
NONE
```
NONE

[usage] Do not run tests with SQL debug mode

---

components/usage/pkg/db/workspace_test.go

Temporarily remove the test until I can properly debug it, this prevents failing main
Fixes #
```release-note
NONE
```
NONE

[usage] Temporarily remove flaky test

---

components/dashboard/src/projects/ProjectSettings.tsx

Ensure that setting one checkbox on the project settings page doesn't overwrite the state of the other.
fixed in response to[ internal discussion](https://gitpod.slack.com/archives/C02EN94AEPL/p1655768161654689)
* Open preview env and add a project.
* Go to settings, and enable persistent volume claim support and incremental prebuilds.
* Observe that both checkboxes are checked now.
* Refresh settings page. Both checkboxes remain checked.
```release-note
Experimental feature checkboxes on the project settings page now behave correctly
```
None

[dashboard] Fix checkboxes on project settings page

---

components/server/src/user/token-service.ts

Fixes a linting issue:
```
/workspace/gitpod/components/server/src/user/token-service.ts:42:13
ERROR: 42:13  no-floating-promises  Promises must be handled appropriately
```
```release-note
NONE
```

[server] fix linting issue

---

components/dashboard/src/workspaces/WorkspaceEntry.tsx
components/gitpod-protocol/src/context-url.ts

Fixes #8411
```release-note
NONE
```

[dashboard] Fix displaying of snapshot contexts on /workspaces

---

components/licensor/ee/pkg/licensor/licensor.go

Fixes unmarshalling of the LicensePayload.
```release-note
NONE
```

[licensor] Make LicensePayload.CustomerID omitEmpty

---

components/supervisor/pkg/ports/ports.go

xref: https://cloudlogging.app.goo.gl/9PLuEBZMDiazzHrm9
```release-note
NONE
```

[supervisor] Remove common warnings

---

components/dashboard/src/projects/ProjectSettings.tsx
components/server/ee/src/prebuilds/prebuild-manager.ts

Small follow up to #10962
```release-note
NONE
```

[prebuilds] store cancel reason

---

components/server/src/auth/generic-auth-provider.ts
components/server/src/server.ts

Remove sensitive data from `server` logs.
Fixes https://github.com/gitpod-io/ops/issues/3062
```release-note
NONE
```

Clean up oauth logging

---

components/licensor/typescript/ee/src/api.ts

This seems to be a leftover from last weeks licensor changes.
Fixes #
```release-note
NONE
```

[licensor] Align dirty repo state

---

.github/workflows/code-nightly.yaml

Point Code Nightly to `gp-code/release/1.69`
Related https://github.com/gitpod-io/gitpod/issues/10990
```release-note
NONE
```

Point Code Nightly to gp-code/release/1.69

---

components/ws-proxy/cmd/run.go

Refactor GRPC client connection
Fixes https://github.com/gitpod-io/gitpod/issues/11020
```release-note
NONE
```

[ws-proxy] Refactor SSH heartbeat GRPC connection

---

components/supervisor/pkg/supervisor/supervisor.go

xref: https://console.cloud.google.com/errors/detail/CIrWqOajzfiasgE?authuser=1&project=workspace-clusters
```release-note
NONE
```

[supervisor] Remove signal terminated log

---

components/ws-proxy/pkg/proxy/routes_test.go

This is follow up https://github.com/gitpod-io/gitpod/pull/11072
Add `ws-proxy` route test case for `blobserve` and `workspace port`, make sure they both set correct
We only take care about `blobserve` and `workspace port`
Fixes #
build pass
```release-note
NONE
```

[ws-proxy] Add test case for blobserve and workspace port

---

.werft/installer-tests.ts
.werft/jobs/build/deploy-to-preview-environment.ts
.werft/jobs/build/installer/installer.ts
.werft/jobs/build/job-config.ts
.werft/jobs/build/trigger-integration-tests.ts
.werft/jobs/build/typecheck-werft-jobs.ts
.werft/jobs/build/validate-changes.ts
.werft/observability/monitoring-satellite.ts
.werft/observability/tracing.ts
.werft/package.json
.werft/platform-delete-preview-environments-cron.ts
.werft/util/certs.ts
.werft/util/gcloud.ts
.werft/util/gpctl.ts
.werft/util/kubectl.ts
.werft/util/preview.ts
.werft/util/shell.ts
.werft/util/slack.ts
.werft/util/util.ts
.werft/util/werft.ts
.werft/vm/vm.ts
.werft/wipe-devstaging.ts
.werft/yarn.lock

Format all `.ts` files in the `.werft` folder so that we can use auto-formatting vie pre-commit-hook in the future. 
Fixes https://gitpod.slack.com/archives/C01KGM9EBD4/p1657014082016499
Review this PR carefully to check that prettier does not break anything. 
```release-note
NONE
```

Run 'prettier' on .ts files in .werft folder.

---

install/installer/pkg/components/ws-manager/configmap.go
install/installer/pkg/components/ws-manager/configmap_test.go

Fix workspace template generation, so that it correctly generates only one configmap that includes all relevant workspace templates.
Related https://github.com/gitpod-io/gitpod/issues/10418
```release-note
none
```

[installer] fix workspace template generation

---

components/ws-daemon/pkg/iws/iws.go

[ws-daemon] Remove WorkspaceInfo noisy log

---

.github/workflows/configcat.yml

Adds code-scanning to reference feature flags in Configcat
See 
* https://configcat.com/docs/advanced/code-references/github-action/
* https://configcat.com/docs/advanced/code-references/overview/
Fixes #
```release-note
NONE
```
NONE

[configcat] Add code scanning for feature flags

---

components/server/src/oauth-server/db.ts

Add `function:getSSHPublicKeys` scope for vscode client so we can improve ssh connection experience in gitpod-desktop extension
```release-note
NONE
```

Add `function:getSSHPublicKeys` scope to vscode client

---

install/installer/pkg/common/customize_test.go

This was raised as a specific issue in #11106, but cannot recreate this issue. Test added to ensure that no regression happens.
Fixes #11106
Check werft runs
```release-note
[installer]: add test for customization of proxy service
```

[installer]: add test for customization of proxy service

---

components/ws-proxy/pkg/sshproxy/server.go

improve SSH Gateway no-client-auth analytics
Fixes #
1. start a workspace, connect via SSH (use user upload ssh key)
2. see segment, you will see only one `ssh_connection` event in phase `auth`
```release-note
NONE
```

[ws-proxy] improve no-client-auth analytics

---

install/installer/pkg/components/workspace/ide/constants.go

Updates stable VS Code Web to 1.69.0 with 
- https://github.com/gitpod-io/openvscode-server/pull/379 picked
Fixes https://github.com/gitpod-io/gitpod/issues/11243
See How to Test section in https://github.com/gitpod-io/openvscode-server/pull/379
```release-note
[code] fix `.gitpod.yml` ports onOpen not work on workspace startup
```

[code] upgrade stable code with ports onOpen fix

---

components/ide/jetbrains/gateway-plugin/build.gradle.kts
components/ide/jetbrains/gateway-plugin/gradle.properties
components/ide/jetbrains/gateway-plugin/src/main/kotlin/io/gitpod/jetbrains/gateway/GitpodConnectionProvider.kt

Update 'gateway-plugin' to work with JetBrains Gateway v222.3345.1+.
The main difference is that v222.3345.1 had a change on the constructor parameters of `ClientOverSshTunnelConnector`.
Some other small updates/renames were made to the code to resolve issues like deprecation and variable shadowing, pointed out by IntelliJ IDEA.
None.
- Download JetBrains Gateway v222.3345.1 for Mac from [here](https://gitpod.slack.com/archives/C02BRJLGPGF/p1657041136854829) (internal link), and install it.
- [Download this Gateway Plugin build, from Gitpod's Plugin Dev Channel](https://plugins.jetbrains.com/plugin/18438-gitpod-gateway/versions/Dev/193675), and [install it on the Gateway](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk).
- Confirm if you can connect to …

Update 'gateway-plugin' to work with JetBrains Gateway v222.3345.1+

---

components/ws-daemon/pkg/content/service.go

improve DisposeWorkspace logging
Fixes #
```release-note
none
```

[ws-daemon] improve DisposeWorkspace logging

---

components/supervisor/pkg/ports/served-ports.go
components/workspacekit/cmd/rings.go

Fixes not very helpful log messages.
Fixes #
```release-note
none
```

fix unhelpful log messages

---

components/supervisor/pkg/supervisor/supervisor.go

[supervisor] fix metrics
Fixes #
1. start a workspace
2. run `curl localhost:22999/metrics` it should not 404
3. run `echo "some_metric 3.14" | curl --data-binary @- localhost:22990/metrics/job/some_job` it should not 404
4. run again `curl localhost:22999/metrics` it should show something which you put in setp 3
```release-note
NONE
```

[supervisor] fix metrics

---

install/installer/pkg/components/ws-manager/configmap.go
install/installer/pkg/config/v1/experimental/experimental.go

Same other PRs related to #10418, improves installer so that we don't need to overwrite configmap for SaaS
Related https://github.com/gitpod-io/gitpod/issues/10418
```release-note
none
```

[installer] improve ws-manager config

---

components/ws-manager/pkg/manager/manager.go

Due to Kubernetes issue https://github.com/kubernetes/kubernetes/pull/108366 we had to add a workaround to bypass the issue. Now that upstream versions are available (since April 13th) we can remove it.
Affected Kubernetes version with the issue released a fix in:
- [v1.22.9](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#v1229)
- [v1.23.6](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#v1236)
We need to remove the workaround due to additional conditions that can affect the scheduling, like scale-up events.
Creating and deleting pods due to timeouts only add load to the API server.
Edit: example of side effect https://cloudlogging.app.goo.gl/SG2Qx1e21EykbRzNA
```release-note
NONE
```

[ws-manager] Remove temporal workaround for kubelet issue

---

components/ws-manager/pkg/manager/manager.go

Fix regression introduce in https://github.com/gitpod-io/gitpod/pull/11392.
We need to wait until the pod is Running before removing any annotation
- Open a workspace. It should work
```release-note
NONE
```

[ws-manager] Wait for pod running before removing annotations

---

components/server/ee/src/prebuilds/prebuild-manager.ts

We were missing a `span.finish()`. Also, added a log line for traceability. 
Fixes #
- see that it builds
```release-note
NONE
```

[server] Fix tracing and logging when aborting prebuilds on newer push

---

components/content-service/pkg/git/git.go
components/content-service/pkg/initializer/git.go
components/supervisor/pkg/supervisor/supervisor.go
components/ws-daemon/BUILD.yaml
components/ws-daemon/default.gitconfig
components/ws-daemon/leeway.Dockerfile
components/ws-daemon/pkg/content/service.go
components/ws-daemon/pkg/internal/session/workspace.go
test/pkg/integration/common/git-client.go
test/tests/workspace/contexts_test.go
test/tests/workspace/git_test.go

logs: https://cloudlogging.app.goo.gl/Wr2SmPaFz7EVu4zb6
- Workspaces should open and work as expected
```release-note
NONE
```

Simplify configuration of git setting safe.directory

---

.github/CODEOWNERS

As another part of https://github.com/gitpod-io/gitpod/commit/d6cf319e4f01c71be82c75e0b11f3bc5fd18d4a7
Fixes #
```release-note
NONE
```

Change blobserve CODEOWNERS to team IDE

---

components/ws-manager/cmd/run.go

Remove the duplicated error message
Fixes #
None
```release-note
None
```
None

Remove the duplicated error message

---

components/usage/pkg/apiv1/usage.go
components/usage/pkg/apiv1/usage_test.go
components/usage/pkg/db/workspace_instance_usage.go
components/usage/pkg/db/workspace_instance_usage_test.go

Adds default ordering to billing records
Fixes #
Unit tests
```release-note
NONE
```

[usage] By default sort results descending

---

components/server/ee/src/workspace/gitpod-server-impl.ts

We decided to never update the "Billing Account" setting on the user automatically.
/cc @easyCZ 
Fixes #
```release-note
NONE
```

[server] Never set User.usageAttribution automatically

---

components/ee/agent-smith/pkg/agent/actions.go
components/ee/agent-smith/pkg/agent/agent.go

[agent-smith] Add ID of the workspace that triggered blocking the account

---

install/installer/pkg/components/proxy/constants.go

[installer] Sync alpine version

---

components/usage/pkg/apiv1/usage.go
components/usage/pkg/apiv1/usage_test.go
components/usage/pkg/db/workspace_instance_usage.go

Order results based on parameters
* Depends on https://github.com/gitpod-io/gitpod/pull/11577
Unit tests
```release-note
NONE
```

[usage] Implement ordering of usage report with request params

---

components/server/src/workspace/workspace-starter.ts

Map workspace classes to workspace classes using PVC
Fixes #https://github.com/gitpod-io/gitpod/issues/11357
```release-note
None
```

Use workspace classes for PVC workspaces

---

operations/observability/mixins/workspace/dashboards.libsonnet
operations/observability/mixins/workspace/dashboards/ephemeral-storage.json

Add dashboard for ephemeral storage

---

components/common-go/grpc/grpc.go

Traces from this service add no value, and the volume could impact costs.
```release-note
NONE
```

Filter grpc health check from tracing

---

components/ws-manager/pkg/manager/manager.go

[ws-manager] Improve tracing logs

---

components/ws-daemon/pkg/container/containerd.go
components/ws-daemon/pkg/dispatch/dispatch.go

Fixes https://github.com/gitpod-io/gitpod/issues/11725
```release-note
NONE
```

[ws-daemon] Increase WaitForContainer timeout

---

components/ws-manager/pkg/manager/manager.go

In case of a timeout waiting for a workspace pod in running state, delete the pod and call `StartWorkspace` passing the remaining time to respect the initial timeout from server.
```release-note
NONE
```

[ws-manager] Handle Pending pod due to Unschedulable reason

---

components/ws-daemon/pkg/cgroup/plugin_fuse_v2.go
components/ws-daemon/pkg/cgroup/plugin_iolimit_v2.go

[ws-daemon] Configure plugins log level to Debug

---

install/preview/BUILD.yaml
install/preview/entrypoint.sh
install/preview/leeway.Dockerfile
install/preview/prettylog/BUILD.yaml
install/preview/prettylog/go.mod
install/preview/prettylog/go.sum
install/preview/prettylog/main.go

Currently, The telemetry of `local-preview` is the same as any self-hosted install which
means that these telemetry cronjob is run daily, and also once when the installation is ready.
This information isn't as useful, as the properties aren't that important for a short-lived
installation.
Instead, It would make sense to have telemetry on each event of the `local-preview`
command itself so that we can measure the Installation success rate,  Time taken, etc
to improve the overall UX of `local-preview`. This will be more important for us
to understand the usage of `local-preview` itself.
This PR fixes that by attaching a telemetry event to be sent, for each status update
in `local-preview`. For this to work, A anonymous User ID is generated and used
for all status updates.
Event Schema:
``` …
```

[local-preview] Add new Telemetry

---

operations/observability/mixins/IDE/rules/components/openvsx-proxy/alerts.libsonnet

Remove check for absence, since we're deploying the monitoring stack to clusters that don't have Gitpod installed. ([ref](https://gitpod.slack.com/archives/C03QM0ZHF5Z/p1659314278938249))
Fixes #
```release-note
NONE
```

Remove check for absence

---

components/ws-daemon/pkg/content/service.go
components/ws-manager/pkg/manager/monitor.go

Check instance ID and workspace ID are not empty.
Fixes #
```release-note
None
```
None

Check instance ID and workspace ID are not empty

---

components/server/ee/src/user/user-service.ts

This reverts commit 6e48a144361ed40ad0065cd716f274ad0b475ad7.
Fixes #
- log in to the preview env
- see that you can sign up
```release-note
NONE
```

Revert "TEST COMMIT"

---

.werft/observability/monitoring-satellite.ts

Adds some simple debug if observability fails to install
Fixes [#3585](https://github.com/gitpod-io/ops/issues/3585)
```release-note
NONE
```

Add observability debug on failure

---

components/ws-manager/pkg/manager/manager.go
components/ws-manager/pkg/manager/monitor.go

improve tracing to make it easier to debug an issue with pods stuck in terminating state
Fixes https://github.com/gitpod-io/gitpod/issues/11787
```release-note
none
```

[ws-manager] improve tracing and fix lock

---

components/ws-manager/pkg/manager/create.go

[ws-manager] Disable PVC feature

---

.github/workflows/code-nightly.yaml

Point to 1.70 release branch
```release-note
NONE
```

[code] Point to 1.70 release branch

---

install/installer/cmd/render_test.go

Fix the update golden file command. See [internal](https://gitpod.slack.com/archives/C01KLC56NP7/p1659602351920569).
```release-note
NONE
```

[installer] Fix writing golden files

---

components/content-service/pkg/initializer/git.go

This PR should address #11845 though I was not able to reproduce this exact same error in preview environment.
Tried both github and gitlab private repos, but each time I was getting an error about private repo from server, it never made it to start workspace phase. :thinking: 
There might be some edge case where it gets through server, so this would fix it on workspace side as well.
Fixes https://github.com/gitpod-io/gitpod/issues/11845
```release-note
none
```

[content-service] handle git access denied error

---

components/content-service/pkg/initializer/git.go

Fixes https://github.com/gitpod-io/gitpod/issues/11854
```release-note
none
```

[content-init] do not hide error during git checkout

---

install/installer/cmd/testdata/render/external-registry/config.yaml
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/pkg/common/display.go

This PR adds an installer render test with an external registry.
_This PR is based on #11879. Please merge the other PR first._
```release-note
NONE
```

[installer] Add external registry test

---

components/server/src/billing/entitlement-service.ts

Fixes a bug in the community distribution...
Fixes #
```release-note
NONE
```

[server] Add missing @injectable()

---

.github/workflows/code-nightly.yaml

Fixes #
Relates https://github.com/gitpod-io/gitpod/issues/11638
No need
```release-note
NONE
```

[code] point nightly job back to gp-code/main

---

components/usage/pkg/server/server.go

Adding metrics to improve observability into the grpc client. This is needed to better debug the current failure of
```
ResourceExhausted desc = grpc: received message larger than max (20545761 vs. 16777216)"
```
Fixes #
```release-note
NONE
```

[usage] Add grpc client metrics, up max call sizes

---

components/server/src/workspace/workspace-starter.ts

Enable workspace classes feature for teams
n.a.
```release-note
None
```

Enable workspace classes feature for teams

---

components/ws-daemon/pkg/content/service.go

Return error to the client and only ignore tracing error.
Fixes #11710
Fixes #11713
None
```release-note
None
```
None

Return error to the client and only ignore tracing error

---

components/server/src/workspace/workspace-starter.ts

Related to this comment: https://github.com/gitpod-io/gitpod/issues/11823#issuecomment-1206161641
Fixes #
```release-note
none
```

fix log to output all info properly

---

.github/CODEOWNERS

Fixes #
no need
```release-note
NONE
```

Change installer testdata CODEOWNERS to anyone

---

components/ws-daemon/pkg/internal/session/workspace.go

ws-daemon: enhance log
Fixes #
N/A
```release-note
N/A
```
N/A

ws-daemon: enhance log

---

components/server/src/workspace/workspace-starter.ts

Ensure that the workspace class is persisted regardless of whether new or old workspace classes are used.
Fixes #https://github.com/gitpod-io/gitpod/issues/11956
Open a workspace and check in the database that the workspace class is there
```release-note
None
```

Ensure workspace class is persisted

---

components/usage-api/typescript/src/usage/v1/sugar.ts

Apparently we have to set up this boilerplate to ensure that we can connect (or cache connections) to the billing service in the usage API.
Fixes #11988
Is dependency for #11888
I'm not sure..
```release-note
NONE
```

Add billing setup in sugar

---

operations/observability/mixins/platform/rules/scrape.libsonnet

The goal is to avoid getting alerted due to small unavailabilities that don't represent a treat.
```release-note
NONE
```

Increase threshold for unavailable targets

---

install/installer/pkg/components/ws-proxy/deployment.go

[installer] Fix lint issue

---

components/content-service/pkg/initializer/git.go

Check remote branch exists before git checkout.
Fixes #11854
1. Install the Jaeger in the preview environment
2. Open the test repo https://github.com/jenting/lh/tree/test-branch-1 on the preview environment
3. Filter the Jaeger tracing, make sure no error happens
- service=content-initializer
- error=true
Note:
- if the remote branch exists, the `git ls-remote origin <branch-name>` outputs
```console
51846208d000f4b6fe40a17f7b37bc232ca8f0f4	refs/heads/test-branch-1
```
- if the remote branch does not exist, the `git ls-remote origin <branch-name>` outputs _empty with no error code_
```release-note
None
```
None

content-service: check remote branch exists before git checkout

---

WORKSPACE.yaml

Build code image for 1.70.1
1. Check about dialog says 1.70.1
```release-note
NONE
```

[code] build stable code image for 1.70.1

---

install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/pkg/components/workspace/ide/constants.go

Updates code image for 1.70.1
1. Check about dialog says 1.70.1
```release-note
NONE
```

[code] update stable code image to 1.70.1

---

components/gitpod-cli/cmd/tasks-list.go

When I attach to different tasks using SSH (or integrated terminal), I often ask myself "Where am I?" In which tasks am I?".
I thought that a simple highlight would be helpful. Let me know if you like the idea and I can open the PR for review.
My scenario:
1. I run `gp tasks attach <ID>` (Go)
2. I run `gp tasks list` (I don't know where I am) - See screen of current behaviour
After this change, when I run `gp tasks list`, I would see highlighted the task in which I am.
Fixes #
```release-note
Gitpod CLI: Highlight current task in gp tasks list
```

[Gitpod CLI] Highlight current task in `gp tasks list`

---

components/registry-facade/pkg/registry/blob.go

`ipfsBlobSource` already returns `dontCache=true`
```release-note
NONE
```

[registry-facade] Remove unnecessary check

---

dev/loadgen/README.md

Fixes #
```release-note
NONE
```

loadgen: Slight README improvement.

---

.gitpod.yml

Fixes #
```release-note
NONE
```

removed vscode java pack

---

components/dashboard/src/teams/TeamBilling.tsx

Make team billing settings accessible only to team owners, by auto-redirecting `/t/:team/billing` when the user is not a team owner.
Fixes https://github.com/gitpod-io/gitpod/issues/12095
1. Create a team
2. Go to to team billing settings (it works) -- save the URL
3. Downgrade yourself from Owner to Member
4. Open the team billing settings URL again
Expected: This should redirect you away, instead of showing you a (partly dysfunctional) team billing UI.
```release-note
NONE
```

[dashboard] Make team billing settings accessible only to team owners

---

components/ws-manager/pkg/manager/monitor.go

Add mutex when writing into map to prevent race condition crash on ws-manager start up when there are a lot of volume snapshots ready.
Fixes #11786 
```release-note
none
```

fix race condition when creating notifyPod channel

---

test/go.mod
test/go.sum
test/integration.yaml
test/tests/workspace/cgroup_v2_test.go

fix integration tests
Fixes #
Run integration test and pass the cgroup v2 test
```release-note
NONE
```

test: fix the cgroup v2 test.

---

install/installer/cmd/testdata/render/customization/output.golden
install/installer/cmd/testdata/render/external-registry/output.golden
install/installer/cmd/testdata/render/minimal/output.golden
install/installer/cmd/testdata/render/statefulset-customization/output.golden
install/installer/pkg/components/workspace/ide/constants.go

Updates code image for 1.70.2
- Check about dialog says 1.70.2
```release-note
NONE
```

[code] update stable code image to 1.70.2

---

WORKSPACE.yaml

Build code image for 1.70.2
- Check about dialog says 1.70.2
```release-note
NONE
```

[code] build stable code image for 1.70.2

---

.werft/installer-tests.ts

This is a very small PR that reduces the number of alerts sent out for integration test failures. Now test failures for one slack channel(one team) will be sent out only once in a consolidated message.
Fixes #
One can use this doc to [try and trigger tests](https://www.notion.so/gitpod/WIP-Self-hosted-automated-nightly-pipelines-fdc5a202e67b4197aa00d93b98d57927).
```release-note
NONE
```

[installer-tests] Consolidate slack alerts to reduce noise

---

install/infra/single-cluster/aws/Makefile
install/infra/single-cluster/aws/terraform.tfvars
install/infra/single-cluster/gcp/Makefile
install/infra/single-cluster/gcp/terraform.tfvars

This is a small PR making some aesthetic changes to the `Makefile` output in the `terraform` module. Alongside this cleans up the messages in `terraform.tfvars` for better usability.
Fixes #
```release-note
NONE
```

[terraform] Cleanup messages in tf modules

---

components/ws-manager/pkg/manager/annotations.go
components/ws-manager/pkg/manager/monitor.go

https://github.com/gitpod-io/gitpod/pull/11950#discussion_r950980671
Fixes #
```release-note
NONE
```

ws-manager: Improve the monitor code.

---

install/installer/cmd/testdata/render/workspace-requests-limits/output.golden

Fix installer test
Fixes #
```release-note
None
```

[installer] Fix installer test

---

dev/loadgen/cmd/benchmark.go
dev/loadgen/configs/prod-benchmark-pvc.yaml

Fixes #
```release-note
none
```

[loadgen] add support for passing feature flags

---

install/installer/cmd/testdata/render/aws-setup/config.yaml
install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/azure-setup/config.yaml
install/installer/cmd/testdata/render/azure-setup/output.golden
install/installer/cmd/testdata/render/gcp-setup/config.yaml
install/installer/cmd/testdata/render/gcp-setup/output.golden

Add golden file render tests for AWS, Azure and GCP basic setups
```release-note
[installer]: add golden files for aws, azure and gcp
```

[installer]: add golden files for aws, azure and gcp

---

components/ws-manager/pkg/manager/monitor.go

https://github.com/gitpod-io/gitpod/pull/12215#discussion_r952046348
Fixes #
```release-note
NONE
```

ws-manager: Consistently use clearInitializerFromMap.

---

install/installer/cmd/testdata/render/aws-setup/output.golden
install/installer/cmd/testdata/render/azure-setup/output.golden
install/installer/cmd/testdata/render/gcp-setup/output.golden

Fixes https://github.com/gitpod-io/gitpod/pull/11177#issuecomment-1223747178
```release-note
NONE
```

[installer] Fix golden files

---

dev/loadgen/README.md

Update loadgen readme
Fixes #
```release-note
None
```
None

Update loadgen readme

---

components/dashboard/src/teams/TeamUsageBasedBilling.tsx

Quick follow-up to https://github.com/gitpod-io/gitpod/pull/12291
Fixes https://github.com/gitpod-io/gitpod/issues/12115
```release-note
NONE
```

[dashboard] Clarify that spending limit is in credits 2/2

---

.github/workflows/code-nightly.yaml
.github/workflows/jetbrains-auto-update-template.yml
.github/workflows/jetbrains-integration-test.yml
.gitpod.yml
.werft/aks-installer-tests.yaml
.werft/build.yaml
.werft/cleanup-installer-setups.yaml
.werft/debug.yaml
.werft/eks-installer-tests.yaml
.werft/gke-installer-tests.yaml
.werft/ide-integration-tests-startup.yaml
.werft/k3s-installer-tests.yaml
.werft/platform-delete-preview-environments-cron.yaml
.werft/platform-trigger-werft-cleanup.yaml
.werft/run-integration-tests.yaml
.werft/self-hosted-installer-tests.yaml
.werft/wipe-devstaging.yaml
.werft/workspace-run-integration-tests.yaml
dev/image/Dockerfile

- Open this PR in Gitpod
- Check leeway tasks can be executed
```release-note
NONE
```

Update leeway and dazzle

---

components/common-go/testing/fixtures.go
components/content-service/pkg/initializer/initializer.go
components/content-service/pkg/layer/provider_test.go
components/content-service/pkg/logs/logs.go
components/content-service/pkg/storage/gcloud.go
components/ee/agent-smith/pkg/classifier/classifier.go
components/registry-facade/pkg/registry/layersource.go
components/workspacekit/cmd/rings.go
components/workspacekit/pkg/seccomp/notify.go
components/ws-daemon/pkg/cgroup/plugin_process_priority_v2.go
components/ws-daemon/pkg/container/config.go
components/ws-daemon/pkg/content/hooks.go
components/ws-daemon/pkg/content/service.go
components/ws-daemon/pkg/cpulimit/cpulimit_test.go
components/ws-daemon/pkg/internal/session/store.go
components/ws-daemon/pkg/internal/session/workspace.go
components/ws-daemon/pkg/iws/iws.go

Fixes https://github.com/gitpod-io/gitpod/issues/12323
```release-note
none
```

replace os.IsNotExist with errors.Is(err, fs.ErrNotExist)

---

.github/workflows/code-nightly.yaml
dev/image/Dockerfile

https://github.com/gitpod-io/leeway/pull/92
```release-note
NONE
```

Update leeway to fix regression

---

dev/loadgen/configs/prod-benchmark-pvc.yaml
dev/loadgen/configs/prod-benchmark.yaml

Use a variety of workspace classes
n.a.
```release-note
None
```

[loadgen] Use a variety of workspace classes
